### ISSUE TITLE
Is the Docker-Image already updated to v4.3?

### ISSUE THREAD

**Issue by taut98** [ONLYOFFICE/DocumentServer#100]
See Title.

Thank you

**Comment by ShockwaveNN** [comment]
@taut98 
Yes it is, both [documenserver](https://hub.docker.com/r/onlyoffice/documentserver/tags/) and [documentserver-integration](https://hub.docker.com/r/onlyoffice/documentserver-integration/tags/) have 4.3.0.340 as latest version
