### ISSUE TITLE
Viewmode 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1001]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**

when i view a document its viewed in "original-mode" but we want that users view documents in "markup-mode" is that possible?

Kind regards

**Comment by Rita-Bubnova** [comment]
Hello, @hahaxd35.
You can try using the instruction https://api.onlyoffice.com/editors/config/editor/customization#reviewDisplay.

**Comment by hahaxd35** [comment]
Yes this the option we are looking for!

many thanks!
