### ISSUE TITLE
Mising hotkey for pasting content as "plain text"

### ISSUE THREAD

**Issue by moonmehta** [ONLYOFFICE/DocumentServer#1002]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Pasting as plain text not possible using the keybaord

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Copy some formatted text from anywhere. Paste it into the OnlyOffice editors. Unless you use the "Paste Special" dialog, it won't work. Having to use the mouse to click the dialog, then select plain text every single time during multiple copy-paste operations is tiresome and not efficient at all. 

**What is the expected behavior?**
Should be able to paste content as plain text using a hotkey.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.3.3

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer since it's our base product and problem actual there

**Comment by lixaotec** [comment]
+1. Its not in Desktop edition.

**Comment by ztwhaley** [comment]
Any update on this? Badly needed

**Comment by ShockwaveNN** [comment]
Sorry, no specific news, we've discussed several possibilities for that hotkey, but have not found perfect solution for all the systems, so this issue is still unresolved

**Comment by artificiel** [comment]
For sure, we all agree that the "icon-that-appears-once-you-pasted" is definitely not a "perfect solution". We would be interested in hearing how your discussion about assigning some keys to the function deadlocked hard enough to be "worse" that the icon.

There are a number of ways to quickly determine the ideal cross-platform solution: either copy one of the established platforms (ex: google docs meta-shift-v) or adopt the platform-specific generalized approach (alt-shift-meta-v for macos as stated above), or decide something else (as long as it is present in the context menu).

OR: if you prefer not to determine a specific key combo, provide a configuration tool that allows the assignment of keys to functions.

**Comment by ElenaMaaya** [comment]
Hello @moonmehta!
I have great news: in version 7.4.1 this problem has been successfully implemented.
The actual keyboard shortcuts for “Insert text without style formatting” are Ctrl+⇧ Shift+V.
Thank you for reaching out and have a nice day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
