### ISSUE TITLE
The lower margin of the second page's duplicate header line is inconsistent with the format of the first header line, and the solid line of the bottom border is not displayed

### ISSUE THREAD

**Issue by jfzhangak** [ONLYOFFICE/DocumentServer#1003]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Open the document, repeat the header line on the second page, and the solid line at the bottom of the table does not appear
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a table, set no borders, set header lines to be displayed repeatedly at the top of each page, and set header lines to be solid at the bottom. When the table crosses pages, the boundary below the duplicate header line on the second page is not displayed
**What is the expected behavior?**
The bottom boundary of the second page's duplicate header line is the same as the header line format on the first page
**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
5.5.3
**Operating System:**
windows

**Comment by Rita-Bubnova** [comment]
Hello, @jfzhangak.
Could you attach file with problem?

**Comment by jfzhangak** [comment]
zhangjunfeng10he@163.com
 
From: Rita-Bubnova
Date: 2020-09-25 20:50
To: ONLYOFFICE/DocumentServer
CC: Vito; Mention
Subject: Re: [ONLYOFFICE/DocumentServer] The lower margin of the second page's duplicate header line is inconsistent with the format of the first header line, and the solid line of the bottom border is not displayed (#1003)
Hello, @jfzhangak.
Could you attach file with problem?

**Comment by Rita-Bubnova** [comment]
@jfzhangak, if your file contains confidential data, change the confidential data of the original document without changing its structure. Or send the original file by email files@onlyoffice.com.

**Comment by jfzhangak** [comment]
@Rita-Bubnova 
[报错文档3333.docx](https://github.com/ONLYOFFICE/DocumentServer/files/5297596/3333.docx)

**Comment by matveevms** [comment]
@jfzhangak 
I confirm it's bug. I posted this on our local bug tracker 46776

**Comment by jfzhangak** [comment]
Where should I look to see if this bug has been resolved? @ShockwaveNN

**Comment by ShockwaveNN** [comment]
I'll post any updates if this bug resolved.
Currently this bug is not resolved

**Comment by jfzhangak** [comment]
> I'll post any updates when this bug resolved.
> Currently this bug is not resolved

So when do you expect to fix this BUG

**Comment by KirillovIlya** [comment]
We are expecing to fix this in one of our future 6.2 or 6.3 releases

**Comment by matveevms** [comment]
The bug number for your problem has changed, now it's 47264

**Comment by KirillovIlya** [comment]
Here is the fix for this problem 
https://github.com/ONLYOFFICE/sdkjs/commit/0482c774795f9cb8eb8e697cbf5c3a80cdb8bbbf

This will be included in version 6.2

**Comment by ShockwaveNN** [comment]
I'll leave this issue open until we make public release with this fix

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.2.0 are released.
This issue should be fixed.
Feel free to comment or open new issue if got any troubles.
