### ISSUE TITLE
Change page background on Document Editor

### ISSUE THREAD

**Issue by ebanDev** [ONLYOFFICE/DocumentServer#1005]
**Do you want to request a *feature* or report a *bug*?**

I don't really know 😅

**What is the current behavior?**

I don't find any option to change page background on Document Editor

**DocumentServer version:**

The latest version on the debian repo onlyoffice-documentserver/squeeze,now 5.6.5-3 amd64 (https://download.onlyoffice.com/repo/debian)

**Operating System:**

Debian 10 (Buster)

**Browser version:**

Firefox 81.0 (64-bit) archlinux

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1009.
