### ISSUE TITLE
TTS plugin seems not be working

### ISSUE THREAD

**Issue by ebanDev** [ONLYOFFICE/DocumentServer#1006]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

When a try to use a plugin, I have to following error : https://i.postimg.cc/tg1q2kWJ/Capture-d-cran-de-2020-09-27-11-55-38.png

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm using the Debian repo's version. Steps to reproduce :

- Open a Document from NextCloud
- Click on TTS plugin

**DocumentServer version:**

The latest version on the Debian repo onlyoffice-documentserver/squeeze,now 5.6.5-3 amd64 (https://download.onlyoffice.com/repo/debian)

**Operating System:**

Debian 10 (Buster)

**Browser version:**

Firefox 81.0 (64-bit) archlinux

**Comment by Rita-Bubnova** [comment]
Hello, @ebanDev.
Sorry for late response.
Is this issue reproduce in the current DocumentServer version 6.3.0?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
