### ISSUE TITLE
Dark mode/theme

### ISSUE THREAD

**Issue by Virtheon** [ONLYOFFICE/DocumentServer#1008]
**Do you want to request a *feature* or report a *bug*?**
A feature.

**What is the current behavior?**
The only application colouring is blue/green/orange and white.

**What is the feature?**
I'd like to see an option to opt for a dark (black/dark grey) theme for the application, like Office or LibreOffice offer. I know it's a minor thing, but I quite miss it, and it'd make the OnlyOffice seem more complete and just generally polished.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
All versions and OSes, as far as I'm aware.

**Comment by ShockwaveNN** [comment]
We are moved this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by ArchOwlen** [comment]
It is difficult for me to use programs that do not have a dark mode, so I am also adding my support for this feature!

Specifically hoping for Linux and/or Android support!

**Comment by werymanen** [comment]
I'd love to see dark mode, it'd be very good

**Comment by aatiger2007** [comment]
Before I say anything, I love ONLYOFFICE.
I find apps with light theme very difficult to use. But I'd really like to see dark mode. That's the only thing keeping me from completely switching to ONLYOFFICE.

**Comment by ChronoTriggered** [comment]
Here I am, once again asking for your accesibility support, we need a dark theme, it is the only thing I miss right now, we know you can do it, come on!, Thanks

**Comment by theRippedPug** [comment]
I have a suggestion: In my humble opinion, some way to customise the colours(eg. a dotfile) is a better thing to do than straightup implement the theme yourselves. Implementing a dark theme will is quite a significant ask and presents some design challenges that require quite some UI/UX design prowess to overcome.    
This is an open-source project and I am sure the community will do a fabulous job designing colour schemes. This approach allows better integration into Linux desktops via theme engines. You can just pick the theme you guys find the best and make it your default theme if you want to.   
If I am not mistaken, the editors are styled using CSS. So this can be implemented by allowing us to change some CSS variables thus reducing work for the core team.

**Comment by werymanen** [comment]
Yes, that's probably a better way to approach this.

**Comment by benji88i** [comment]
dark theme would be great!

**Comment by LeSnake04** [comment]
I also would love this feature.

I may switch over from LibreOffice entirely if this gets added ...

**Comment by chetanpandey1266** [comment]
Dark theme is must...please make it happen

**Comment by LeSnake04** [comment]
> I have a suggestion: In my humble opinion, some way to customise the colours(eg. a dotfile) is a better thing to do than straightup implement the theme yourselves. Implementing a dark theme will is quite a significant ask and presents some design challenges that require quite some UI/UX design prowess to overcome.
> This is an open-source project and I am sure the community will do a fabulous job designing colour schemes. This approach allows better integration into Linux desktops via theme engines. You can just pick the theme you guys find the best and make it your default theme if you want to.
> If I am not mistaken, the editors are styled using CSS. So this can be implemented by allowing us to change some CSS variables thus reducing work for the core team.

This would be even better, since we then will get a selection out of many themes made by the community instead just 2-4 themes made by the devs

But I would be fine with 1 dark theme too!

**Comment by bphd** [comment]
**Do you want to request a *feature* or report a bug?**

**What is the current behavior?**

White, all white, eyes strain everywhere

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open a document, or even the software and BAM, light at profusion

**What is the expected behavior?**

An option in the parameters to set the UI in dark and to invert text/BG colors of the document (only for the purpose or using in through ONLYOFFICE, the exported/saved document still in original defined colors, not the dark adaptation)

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Latest, Linux, no

**Comment by darkRaspberry** [comment]
I don't want to add any duplicate issue.

**Comment by beerbears** [comment]
If OnlyOffice had a dark theme I would use it. I’m forced to use libreoffice because it supports a dark theme built in

**Comment by maxkadushkin** [comment]
@beerbears, dark theme is under development now. it's planned in ver 6.3

**Comment by jebjordan** [comment]
Really hoping that when this is done it's announced in some big way so that people know about it. Really like this but need a dark mode.

**Comment by janxkoci** [comment]
So I learnt before that ONLYOFFICE uses javascript for macros. I happen to have some [javascript snippets](https://gist.github.com/janxkoci/6328abcbdab3d8b2107fd19d9dd158bb) which I use as bookmarklets in web browsers to switch websites to nightmode. So I naively tried two of them as macros and they kind of worked. I got dark UI with the first one (it makes negative of a page), but the page was still white (see below). The third one made everything dark grey, including the page, but text was not visible.

Here is a screenshot for the first snippet:

![Snímek z 2021-01-18 20-19-11](https://user-images.githubusercontent.com/19331850/104955389-7c621280-59ca-11eb-9eef-5f0e4aad2e2b.png)

Anyway, this was just a very dumb experiment and I got more far than I expected. The scripts are designed for webpages, not office UI, but still I got something. If somebody knows more about javascript and the internals of ONLYOFFICE, I'm sure they can write a macro that actually works. The UI can clearly be modified using macros this way.

**Comment by bphd** [comment]
The problem is not about difficulty to do this modification, even in dev side

Like you saw even one command submitted to the browser engine can make almost all the work

If this problem is still here since years it's because of the team priorities and capacities. It seems that they're not that much to resolve the issues fast enough and that they don't care about these kind of asks, in other words it's not prioritize

Even if it takes like 2 hours to decide about the new color design and 15 minutes to implement it. It's not about time or difficulty, but priorization

**Comment by janxkoci** [comment]
I get that, I just noticed there is a lot of people demanding this feature and I thought I could show some way to hack this yourself.

However getting dark mode right is no small feat, definitely not something that can be done in hours, so I understand they take their time.

**Comment by bphd** [comment]
I count in effective work time, not office work time where you do a lot of things at the same time and in final you take 2 weeks to finish a task. I only talk about time where they effectively think about that, discuss about that, manipulating about that, in total it makes something like 2 or 3 hours for design and 5-15 minutes in coding (only coding, not all the other process between dev and effective downloadable software)

**Comment by janxkoci** [comment]
Same for me, but this cannot be designed in hours. It's not just UI, but also all colour palettes have to be checked with the new design for legibility, contrast and so on. Track changes should be readable. Some people use redshifting / blue light filters for better sleep cycles (also mentioned above in this thread) which should be considered too. There is a lot of decisions to be made. Maybe the coding part can be done in hours, but design that works at least for most people will take significantly more time than that.

**Comment by bphd** [comment]
If you add all of that effectively it makes the work grow up exponentially

**Comment by jilv220** [comment]
Still the best alternative to Office set in my opinion. If there is a dark theme for the overall UI, it will be even better.

**Comment by maxkadushkin** [comment]
it's planned in 6.3 ver

**Comment by djose1164** [comment]
I'm looking forward to the new night mode, too!!!!

**Comment by Normand-Nadon** [comment]
What is happening with this request? I am tracing it way back in 2019 in many requests!
Honestly, software made in this decade should by default be in dark mode, then, in other ways... It is a health concern!

Can someone point me to a possible ETA for this feature? I will follow it closely and try to contribute! :)

Have a nice day.

**Comment by TraySSan** [comment]
Any updates? It's been almost 2 years since this "feature" has been requested. It's not that hard to change a few colours around. Speaking from experience. I'll experiment with some of my own code and possibly contribute. Not promising anything though. I've got uni stuff to do :D Anyways, I really like this project and seriously appreciate your guys' work.
Cheers!

**Comment by AshenPaladin** [comment]
> What is happening with this request? I am tracing it way back in 2019 in many requests!
> Honestly, software made in this decade should by default be in dark mode, then, in other ways... It is a health concern!
> 
> Can someone point me to a possible ETA for this feature? I will follow it closely and try to contribute! :)
> 
> Have a nice day.

It was mentioned a few replies above that it's planned for the 6.3 version. Seeing as the 6.2 version just launched, it's probably a few weeks or a few months away

**Comment by darkRaspberry** [comment]
They have said they planned. Not that they are working on it, As i rem. I guess ETA would stretch.

**Comment by 0x1a8510f2** [comment]
[At long last, this issue can be closed](https://www.onlyoffice.com/blog/2021/05/onlyoffice-docs-v6-3-dark-theme-150-scaling-protecting-files-with-passwords-updated-reviewing/) :D

**Comment by ShockwaveNN** [comment]
@0x1a8510f2 I'll leave this issue opened until we release DesktopEditors soon, because some people in this thread are with Desktop apps, but in DocumentServer - yeah, Dark Theme is implemented

**Comment by lucasgabrielmoreno** [comment]
Thanks!
🙏 🙏 🙏 🙏 🙏

**Comment by 0x1a8510f2** [comment]
@ShockwaveNN I see. Thanks!

**Comment by JarnoB** [comment]
I was just searching for this feature on the Github page in the hope that it would be implemented soon. This is sooner than I expected! Jusdging from the dcreenshot, it looks great too! Everybody that has been involved in not only the darkmode, but OnlyOffice in general: Thank you very much for this amazing office suite! :)

**Comment by ShandoTheKing** [comment]
@JarnoB Me too 🤣🤣🤣

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.3.1 is released. This issue should be fixed

**Comment by lucasgabrielmoreno** [comment]
> DocumentServer and DesktopEditors v6.3.1 is released. This issue should be fixed

Yes, but no flatpack or snap or deb Ubuntu version yet

**Comment by darkRaspberry** [comment]
@lucasgabrielmoreno https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v6.3.1 Try this it is the same binary

**Comment by ShockwaveNN** [comment]
> Yes, but no flatpack or snap or deb Ubuntu version yet

Yes, we know, we'll release them a little bit after

**Comment by lucasgabrielmoreno** [comment]
> @lucasgabrielmoreno https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v6.3.1 Try this. It has the same binary and its updated deb.

It works!!! has deb package! Tank you!
Wow! Dark mode it's so beautiful!

(Linux Mint 20.1)





> > Yes, but no flatpack or snap or deb Ubuntu version yet
> 
> Yes, we know, we'll release them a little bit after

Thanks!!!

**Comment by adigitoleo** [comment]
Thanks for the dark document theme! It seems like there is no dark theme for the web portal yet though, right? Is that a planned feature?

![onlyoffice_themes](https://user-images.githubusercontent.com/34595875/233953264-0896fbc7-fecd-4120-ba55-5eba21aaad84.png)
