### ISSUE TITLE
Word custom properties lost after edit

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#1010]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Lost of word custom properties after Onlyoffice edit

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Create in word a document with custom properties (Info / Properties / Advanced Properties then tab Custom)
- Open it with Onlyoffice and do a minor modification to save it
- Reopen with Word, properties has been lost

**What is the expected behavior?**

Custom properties are still there

**Did this work in previous versions of DocumentServer?**

Don't think so

**DocumentServer version:**

5.5.1

**Operating System:**

Win10 (but expect ALL)

**Browser version:**

ALL

**Comment by Rita-Bubnova** [comment]
Hello, @cpot.
Thank you for report.
I can confirm - this is bug, issue 46739 in our private issue tracker.

**Comment by cpot** [comment]
@Rita-Bubnova for the record, it is on the template of one of the largest European Institution.... Hope for a 'quick' fix (i am not talking about managing custom properties, just not loosing them

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/core/commit/a7d8e656c63935a439817ffc29d69867484d4db5, https://github.com/ONLYOFFICE/sdkjs/commit/2f4e89626caeddddbf330ce46d9e7a6c132de855) in future major release, but currently I have no ETA for this release.

**Comment by cpot** [comment]
@Rita-Bubnova i don't know why onlyoffice bug fixes are in major release ... bug fixes should be in minor releases (or intermediates release for difficult ones). 

Lost of Office data is a bug IMHO.

**Comment by ShockwaveNN** [comment]
@cpot Some fixes require major redone of application and simply cannot be include in any near release, so sometimes those fixes are moved to next release

And I'm pretty sure mention somewhere else, but again - QA team didn't decide in which version bugs should be fixed, we can advices, but this is developers decision.

Sorry for your bug, but we simply cannot release a new minor version for bug which was reported several weeks ago and one commit of fix of this bug contains [1216 additions](https://github.com/ONLYOFFICE/core/commit/a7d8e656c63935a439817ffc29d69867484d4db5)

**Comment by cpot** [comment]
>> QA team didn't decide in which version bugs should be fixed, we can advice, **but this is developers decision**.

Well let's say more management decision

**Comment by ShockwaveNN** [comment]
DocumentServe and DesktopEditors 6.1 is released. This issue should be fixed

**Comment by cpot** [comment]
> DocumentServe and DesktopEditors 6.1 is released. This issue should be fixed

Thank you very much
