### ISSUE TITLE
Do not lose the lock on Excel sheet when open in Onlyoffice 

### ISSUE THREAD

**Issue by yyelena** [ONLYOFFICE/DocumentServer#1013]
**I want to request a *bug* 

**I apply the lock to Excel sheet with password and then I open this file in Onlyoffice , I lose the lock, so I can modify the file**

**Lock Excel sheet with password, open this sheet in Onlyoffice**

**Keep the lock on Excel sheet when open in Onlyoffice**

**Did this work in previous versions of DocumentServer?**

**Operating System:*Windows*

**Browser version:*Chrome  *85.0.4183.121*

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/488.

**Comment by Rita-Bubnova** [comment]
> Duplicate #488.

Sorry, this massage is not correct. This problem is a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/752.
