### ISSUE TITLE
Saving a document changes text background colour to white

### ISSUE THREAD

**Issue by janxkoci** [ONLYOFFICE/DocumentServer#1015]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
If I open or create any document (tested with .docx) and save it, the background of the text is changed **from transparent to white**.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create new document, type text, save it. Alternatively, open existing document (created by other office suite) with transparent background of text and just save it without editting.
2. Open the same document in another editor, that supports Eye protection or changing UI background colour (WPS Office & LibreOffice can do this, both are free).
3. The page has background set by the UI settings (i.e. Eye protection or LO custom background), while the background of the text is set to white.

WPS Office with Eye protection:
![Snímek z 2020-09-30 18-00-25](https://user-images.githubusercontent.com/19331850/94710257-eb95f700-0346-11eb-90db-e84e777e87fa.png)

LibreOffice with UI customised to emulate Eye protection feature:
![Snímek z 2020-09-30 17-51-50](https://user-images.githubusercontent.com/19331850/94709833-6ca0be80-0346-11eb-97f7-de91df0eae8c.png)

**What is the expected behavior?**
The background of the text should be transparent. Also, format of opened documents should not change without explicit user action (like changing background).

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
I tried this in Linux version with both flatpak  and snap packages (both version `5.6.4`).

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer, since it's our base product and problem actual there too

**Comment by janxkoci** [comment]
Thanks. Looking forward to the next release. Since it's resolved, I think the issue can be closed (it doesn't need tracking anymore, right?).

FYI this issue does not seem to be in effect when using the ODT format.

**Comment by ShockwaveNN** [comment]
@janxkoci Hi, in our workflow we leave issue opened until we release version with fix to general public

**Comment by janxkoci** [comment]
**FYI:** I still see the bug after updating to `6.0.0`.

**Comment by ShockwaveNN** [comment]
@janxkoci This is correct, as @Rita-Bubnova said earlier this bug currently fixed on 6.1.0, which is currently in testing stage

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
