### ISSUE TITLE
debian packages don't include version number

### ISSUE THREAD

**Issue by dafeer** [ONLYOFFICE/DocumentServer#102]
__Bug__

The package file name [onlyoffice-documentserver_amd64.deb](http://download.onlyoffice.com/repo/debian/pool/main/o/onlyoffice-documentserver/onlyoffice-documentserver_amd64.deb) is static over multiple package versions. This breaks caching proxies, which server the old file content, which leads to a apt-get "Size mismatch" error.

The [Debian Policy Handbook](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-pkgname) explicitly states that package files are to be named in a scheme which includes the version number. This would easily prevent those issues.

Please fix that. Thanks.

**Comment by JohnPerkin** [comment]
Hello @dafeer!
We agree that this is an important moment and will take it into consideration. Thank you for the remark.

**Comment by igwyd** [comment]
Hello @dafeer, sorry for the late reply, we are fixed it. You can verify this using our repositiry from the manual https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx. Thank you for report.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
