### ISSUE TITLE
FileConverter returns malformed url

### ISSUE THREAD

**Issue by Axelen123** [ONLYOFFICE/DocumentServer#1020]
Note: Onlyoffice domain name has been replaced with office.domain.tld.

**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
The FileUrl is an object instead of a string. When it is used in the browser the url will look like this:
`https://office.domain.tld%2C%20office.domain.tld/cache/files/1338870046/Editor.bin/Editor.bin?md5=VPEZ-MqYDGCn8IA0GEzxrQ&expires=1604952247&disposition=attachment&filename=Editor.bin`. This causes problems because libcURL will throw an exception and will mark the onlyoffice configuration as broken (will not allow you to open the editor). If you work around it by editing the code to correct it (shown below), you will be able to open the editor but the document itself won't load because of the same problem.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1.
Start nextcloud 20.0.0 (does not matter if it is docker or not) and download the latest version of the onlyoffice app.
2.
Install onlyoffice using these instructions:
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx
The docker image is **not** affected by this issue for some reason.
3.
Go into the admin settings and try to configure it.
It should fail with libcURL error 3 (malformed url).
4.
Add debug output [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/59cc6bb006cb9cc7653953088a059c8bbe24c236/lib/documentservice.php#L178) to print `$response_data->FileUrl` (log or just throw it as an exception).
5.
Look in the log and you will see that the url is malformed.
**What is the expected behavior?**
The urls should not be malformed and look like this: `https://office.domain.tld/cache/files/1338870046/Editor.bin/Editor.bin?md5=VPEZ-MqYDGCn8IA0GEzxrQ&expires=1604952247&disposition=attachment&filename=Editor.bin`
**Did this work in previous versions of DocumentServer?**
I don't know. The weird thing about this issue is that it does not happen if you run onlyoffice inside a docker container.
**DocumentServer version:**
Onlyoffice 5.6.5-3
**Operating System:**
Ubuntu 20.04
**Browser version:**
Chromium 86 (also happens in Firefox 81 but this is probably not a browser issue).

**Partial workaround:**
Change [this](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/59cc6bb006cb9cc7653953088a059c8bbe24c236/lib/documentservice.php#L93) line to `return $responceFromConvertService->FileUrl[1];`. Now you will not get the libcURL error but the Editor.bin link that the editor gets from a websocket connection will still be malformed.

**Potential cause:**
My guess is that maybe a javascript library changed from returning urls as strings to returning them as URL objects?

I will try to replicate this issue inside a VM tomorrow

**Comment by Axelen123** [comment]
I tried it in a vm and i cant replicate it.
Probably an issue with my environment then somehow

**Comment by ShockwaveNN** [comment]
@Axelen123 Hi, I never seen a problem like this and personally do not have any idea how to reproduce it

Maybe if someone has some idea how to repeat this problem we will able to fix it

**Comment by Axelen123** [comment]
I will try again with a different vm tomorrow.
If I still can't reproduce it then I will try and see if I can find anything with wireshark.

**Comment by Axelen123** [comment]
I found the cause: My nginx configuration had duplicate `proxy_set_header` directives which means that nginx was sending the Host header twice. Since the header was sent twice it probably turned into an array inside the FileConverter code which malformed the url. This is not a bug inside onlyoffice. It was a misconfiguration on my part.

**Comment by Mer0me** [comment]
> I found the cause: My nginx configuration had duplicate `proxy_set_header` directives which means that nginx was sending the Host header twice. Since the header was sent twice it probably turned into an array inside the FileConverter code which malformed the url. This is not a bug inside onlyoffice. It was a misconfiguration on my part. Sorry

You've saved my day with this... Thank you.
