### ISSUE TITLE
Any Plans for API to Support Search Functions

### ISSUE THREAD

**Issue by kmtong** [ONLYOFFICE/DocumentServer#1021]
There are cases when an external application need to:

1. embed an editor (which is ok now)
2. invoke some editor functions, say search within the document (which is not possible now)

I have gone thru most API docs but cannot find such a way to invoke editor functions (other than save) programmatically.

Any plans for doing so?

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer repo

@flaminestone please take a look

**Comment by flaminestone** [comment]
Hello @kmtong. Unfortunetly, we have not plans with this functions. But I think, you can make search in document via plugin, and run it automaticly after document is ready.

See [example](https://api.onlyoffice.com/editors/config/editor/plugins) how to add your plugin in document editors object (or you can add plugin to documentserver, but this way less flexible)

And [methods for search in document](https://api.onlyoffice.com/docbuilder/textdocumentapi/apidocument/searchandreplace)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
