### ISSUE TITLE
no Release file Update Problems

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1023]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
apt update report errors on your repository:
`
E: The E: The repository 'http://download.onlyoffice.com/repo/debian squeeze Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
repository 'http://download.onlyoffice.com/repo/debian squeeze Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
apt update 
**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
"5.6.5"

**Operating System:**
Debian 10.5
**Browser version:**
---

**Comment by ShockwaveNN** [comment]
Thank you for your report and sorry for waiting.

We tried to rename our default repo name from `squeeze` to `main` and broke old variant

Please check again if everything fine now, I just checked and seems ok. 
If you have no troubles either - please close this issue

Sorry again

**Comment by hahaxd35** [comment]
yeah its not quite simple to manage an repository :D 
Now its working
i have tried to put stretch and buster in source.list but that does not work

**Comment by ShockwaveNN** [comment]
@hahaxd35 Yeah, we tryed to change not to `stretch` and `bunster`, but to more generic `main`.
But got troubles, thanks for your patiences
