### ISSUE TITLE
Bug: Editing docx file breaks formatting for MS Office

### ISSUE THREAD

**Issue by pktiuk** [ONLYOFFICE/DocumentServer#1026]
**What is the current behavior?**
1. Edit file:
[2020 09 23_zal_05_Wniosek_Stypendium Rektora_2020.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/5378774/2020.09.23_zal_05_Wniosek_Stypendium.Rektora_2020.docx) 
2. I save it
3. Upload on OneDrive and open using Word in browser.
4. Notice broken formatting of file:
![image](https://user-images.githubusercontent.com/45544416/96003937-11d58f80-0e3b-11eb-938a-548431e4c243.png)

**What is the expected behavior?**
Saved file should be still properly formatted for MS Office Word users.  
Proper formatting: 
![image](https://user-images.githubusercontent.com/45544416/96003834-f4082a80-0e3a-11eb-949c-8a261412eab6.png)

**Version**
Ubuntu 20.04
ONLYOFFICE Desktop Editors ver. 5.6.4.20

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by pktiuk** [comment]
This bug is no longer present in `ONLYOFFICE Desktop Editors ver. 6.0.2.10`

I am closing this :)
