### ISSUE TITLE
Pivot table drops its formatting after udating

### ISSUE THREAD

**Issue by kompilainenn** [ONLYOFFICE/DocumentServer#1027]
Open XLSX with formatted Pivot table in OnlyOffice 6.0
Try update the Pivot table
Result: the Pivot table got some OO's standard format instead existing format

**Comment by calegario** [comment]
Hi guys, any progress?

**Comment by ShockwaveNN** [comment]
@calegario Sorry, there is no news

**Comment by ShockwaveNN** [comment]
Sorry, we are a QA team and we cannot provide any time frame for this fix

If you really need estimates - better to contact sales@onlyoffice.com

**Comment by rsnegirev** [comment]
@kochn @kompilainenn @felipemurro 

Problem was fixed in the next commits https://github.com/ONLYOFFICE/sdkjs/commit/b85be0ba298671a3c605b3ee034f48f92c2ac21f https://github.com/ONLYOFFICE/sdkjs/commit/bd9ff87e527d6d3d91b5fe29e5691fe7be11c83a

It will be release in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
