### ISSUE TITLE
Spreadsheet's cursor doesn't move on Pivot table

### ISSUE THREAD

**Issue by kompilainenn** [ONLYOFFICE/DocumentServer#1029]
Open a XLSX file with a long Pivot table in OO 6.0
Select any cell inside Pivot table
Press and hold arrow right cursor key on your keyboard
Look at screen => cursor moved only to one cell right
Drop the key and look at screen => cursor jump into end of row (if you will be wait a long time).
I think the cursor moves on Pivot table but it doesn't show to user

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
