### ISSUE TITLE
MMULT Behaviour problem?

### ISSUE THREAD

**Issue by turunut** [ONLYOFFICE/DocumentServer#1030]
Hello I would like to report a possible bug related with MMULT formula on spreadsheet module.
I just downloaded OnlyOffice for first time and I just realized that, like LibreOffice, the name of the Spreadsheet's formulas is concistent with the names used in Excel.
However MMULT dos not work at all as it's supposed, even following the structions on the website (https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/Functions/mmult.aspx).

I'm trying to calculate the product of an array and a vector, this is:
![image](https://user-images.githubusercontent.com/6783564/96005718-04b9a000-0e3d-11eb-95e9-124bcc423979.png)

As you can see in the picture the number of columns of the array is consistent with the number of rows in the vector. However I'm getting the error #VALUE specified on the web:
_Note: if any of the cells in the array contain empty or non-numeric values, the function will return the #N/A error.
If the number of columns in array1 is not the same as the number of rows in array2, the function will return the #VALUE! error._

The expected result would be the same that one could obtained when using LibreOffice:
![image](https://user-images.githubusercontent.com/6783564/96006239-91645e00-0e3d-11eb-98ec-eb3e1e514c14.png)

I'm doing something wrong or is this a bug.

Thank you very much.

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/0a292fb886c53b3c92ff682274026f5eaff8f506), but currently I have no ETA for this release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
