### ISSUE TITLE
Randomly nodeJS - error downloadFile with Error response: statusCode:403

### ISSUE THREAD

**Issue by zubanst** [ONLYOFFICE/DocumentServer#1031]
Randomly I have nodeJS - error downloadFile errors with Error response: statusCode:403 and documents cannot be opened. Here is my configuration: Server1 ubuntu server 18.04 with ownCloud 10.4.1.3 and onlyoffice connector 6.0.1 and Server2 ubuntu server 18.04 with onlyoffice document-server 5.6 installed from the repository described here https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx . The document server uses https with selfsigned certificate. The document server works fine, a test in a browser on the local network with https://<server_address>/ is redirected https://<server_address>/welcome/ saying Document server is running.
At the first run, the onlyoffice connector on ownCloud was configured with the server address https://<server_address>/, Disable certificate verification checked and no secret key. Saving the configuration, I get the success message. Opening a document from the web interface went fine at the first run. Try open a document by another user from a different computer resulted in a error message saying the server is not accessible. After that I couldn't open the documents myself with the same error. Removing the configuration from the connector and punting it back, randomly allowed me to open documents again. You will see the randomness in the log file attached, at the bottom. I already checked the following things:

- set a secret connector side and server side - same randomness
 
- Time: both servers are ntp synchronized

- Configure ownCloud with

    'onlyoffice' => array (
    'verify_peer_off' => true
    )
None of these worked

[onlyoffice-issue.zip](https://github.com/ONLYOFFICE/DocumentServer/files/5396261/onlyoffice-issue.zip)

**Comment by ShockwaveNN** [comment]
I'll close this issue since you got contacted via support at duplicate issue here https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/329#issuecomment-711992873
