### ISSUE TITLE
The function "SUMIFS" doesn't work.

### ISSUE THREAD

**Issue by piiskop** [ONLYOFFICE/DocumentServer#1032]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using the function _SUMIFS_ brings up the error message modal window that the user can download the document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just use the function _SUMIFS_!
**What is the expected behavior?**
That the function _SUMIFS_ does what it's meant to do.
**Did this work in previous versions of DocumentServer?**
I don't know.
**DocumentServer version:**
Microsoft Excel 14.03
**Operating System:**
Ubuntu
**Browser version:**
86.0.4240.75 (Official Build) (64-bit)

**Comment by Rita-Bubnova** [comment]
Hello, @piiskop.
Can you attach file with problem?
Which version DocumentServer you use (not Microsoft Excel)?

**Comment by piiskop** [comment]
The file is [õpetajate-päev](https://nextcloud.tennis24.ee/index.php/s/NiccpZtW2n3aRwZ).

The version of DocumentServer is _ONLYOFFICE/5.6.0.17_.

**Comment by Rita-Bubnova** [comment]
Sorry, I don't see function `SUMIFS` in your file.

**Comment by piiskop** [comment]
Of course, you don't see it because every time I use it the file crashes. This is why I solved the situation going another way. However, you can try using that function there and see what'll happen:
"An error in entered formula. Wrong operator is used. Please correct the error or use the Esc button to cancel the formula editing."
This is what I got after entering "=sumifs(J56,B2,1,C2,1,D2,1)" into _L2_.
Once I replace all the commas by semicolons, I get:
"An error occured during the work with the document. Use the 'Download as...' option to save the file backup copy to your computer hard drive."

**Comment by Rita-Bubnova** [comment]
Could you update version Document Server to 6.0.0? 
I think this problem fixed (don't reproduces in Document Server.6.0.0 (build:105)).

**Comment by piiskop** [comment]
I'm not sure whether I updated correctly as I had lot of troubles installing and upgrading later from _5.4_ as we remember from previous discussions. Anyway, I did _sudo apt upgrade_ and it showed that it upgraded to _6_. However, something is still running in _docker_ and I don't know whether it's a different instance.

After that named upgrade, there was a message that as the _Internet_ connection went away, I have to reload the file. After doing this, I went _File_ -> _Document Info..._ and saw that the _Application_ is _ONLYOFFICE/5.6.0.17_. I tested out _SUMIFS_ in the same file and this time it worked. I remember mentioning earlier in one of our discussions that the old version was still shown. Is it because the file was created using the old version? However I created a new file and it showed for _Application_ another value, something with _Microsoft Excel_. I created a DOC-file and it showed that the application was _Microsoft Word_. Then I started this reply and wanted to give one more try to the new file and now, it shows _ONLYOFFICE/6.0.0.105_. Why is all this mess there? It's so confusing! Three different application versions displayed although actually, all of them are the newest one.

This time the upgrade seems to have gone without troubles for the first time.

**Comment by Rita-Bubnova** [comment]
The problem you faced cannot be reproduced in the new version (6.0), we checked it several times, therefore, the issue can be closed. 

If you have problems with updating Document Server or questions about versioning, please, contact our support team at https://helpdesk.onlyoffice.com/hc/en-us.

**Comment by piiskop** [comment]
That support team won't help me:

> Hello,
> 
> If you have any ONLYOFFICE paid solution, specify your Order ID, your registration e-mail as we can help you.
> 
> Please note also that we do not offer support nor consulting for free open source solutions. You can use a trial version for a paid solution or you can pay for support if you need it, in other case you can ask all your questions on forum dev.onlyoffice.org.
> 
> Yours sincerely,
> Eugenie
> ONLYOFFICE Support Team
> Tel: +371 66016425
> +371 63399867
> +44 20 3287 1086
> www.onlyoffice.com
> cloud.onlyoffice.org

So I create another issue on versioning and close this.
