### ISSUE TITLE
Fonts in the future

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1035]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**
We plan to install new "default" fonts. before we do, we wont to ask if we have to deal with some future updates that makes the new fonts maybe unusable. As i have tested fonts in format ".otf" are working but ONLYOFFICE prefer ".ttf" or?

if we have a separate converter (ONLYOFFICE) do the convert need this font too?
I saw allready errors on generate-AllFonts.sh?

Kind regards

**Comment by ShockwaveNN** [comment]
> we wont to ask if we have to deal with some future updates that makes the new fonts maybe unusable

Currently we got no plans to remove support of current font formats

>if we have a separate converter (ONLYOFFICE) do the convert need this font too?

I'm not 100% sure, but I think it's a safe way to have same set of fonts on each DocumentServer instance

> I saw allready errors on generate-AllFonts.sh?

Could you show me them?

**Comment by hahaxd35** [comment]
i mean i saw errors reportet here in github with this script :D
Can you tell witch fonts ONLYOFFICE support as well?

**Comment by ShockwaveNN** [comment]
We support only vector fonts formats, just ignoring raster.

There is plenty of different formats and I don't think we got a complete list of them.
So If you got any question about specific format - better ask to be sure

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
