### ISSUE TITLE
Issues with German hyphenated abbreviations

### ISSUE THREAD

**Issue by solarjoe** [ONLYOFFICE/DocumentServer#1037]
I saw that there are some issue (Desktop Editors Version 5.6.4.20) with German spell checking. 

"**Softwareent**- und **abwicklung**" (bold means red underlined in the software). 

It's a correct hyphenation and abbreviation. Instead of "Softwareentwickung und Softwareabwicklung" you can write
"Softwareent- und abwicklung" to save a "wicklung". But you can also write "Softwareentwickung und -abwicklung", save-split at a different position and save a "Software". Basically you can choose how much to save and what sounds better.

**Comment by Rita-Bubnova** [comment]
Hello, @solarjoe. 
Thank you for report.
I created issue 46976 in our private issue tracker.

**Comment by solarjoe** [comment]
To check for this some kind of syllable split detection is needed. Then concatenate the words and check for each.

"Softwareent- und -abwicklung" -> Software / ent + ab / wicklung = Softwareentwicklung + Softwareabwicklung 

"Softwareentwicklung und -abwicklung" -> Software / entwicklung + abwicklung = Softwareentwicklung + Softwareabwicklung

The first part might or might not be a complete word.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/7ee14c7f5783cf94b8a7cf92cc86b7174857effe) in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.2.0 are released.
This issue should be fixed.
Feel free to comment or open new issue if got any troubles.
