### ISSUE TITLE
Export Word document to PDF with table of content

### ISSUE THREAD

**Issue by romale** [ONLYOFFICE/DocumentServer#1042]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
OO + nextcloud

**What is the expected behavior?**
Save word document as pdf with table of content

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
OO 5.5.3.39 docker

**Operating System:**
centos7

**Browser version:**
FF 78.4.0esr

**Comment by Rita-Bubnova** [comment]
Maybe, duplicate of #https://github.com/ONLYOFFICE/DesktopEditors/issues/419 ?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by romale** [comment]
This bug Is solved?

**Comment by ShockwaveNN** [comment]
No, original issue #419 is still actual, I've just closed this issue as duplicate

**Comment by romale** [comment]
Ok, thanks
