### ISSUE TITLE
split repository to stable/testing

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1049]
**Do you want to request a *feature* or report a *bug*?**

Feature request (just a idea) 

**What is the current behavior?**

I can only install updates once a week. after testing new Version 6.0.0 i want to install update on other Server. But in mean time there is a 6.0.1 Update. I cannot install update to only 6.0.0 that is was already tested.  

**What is the expected behavior?**

often updates have problems, maybe you can split your repository? 
One stable and another testing? 
before new versions go published maybe user can test them in test-repository always the newest Version with newest features and bug fixings. 
stable would be already tested Version and version good to know as working. (safe to install)

At the moment i would split maybe 5.6.4 to stable and 6.0.1 would be now test (just a example)  

I have Server running 5.5.1 bacause i dont want to update to fast. If one update is not working as aspect, user lose there data and maybe hours of working.

**Operating System:**
Linux, Debian 10

**Comment by ShockwaveNN** [comment]
Hi, we got testing version, only via docker format, but those are real testing like `onlyoffice/4testing-documentserver:6.1.0.40`

But our release process consider 6.0.0 as stable version and 6.0.1 as hotfix for this stable version, both are not `testing`, but stable with some hotfix commits

Sorry, but I don't think we are planning to change our release process and\or naming any time soon

**Comment by ShockwaveNN** [comment]
Closing this issue since there is no more feedback on my anwser
