### ISSUE TITLE
Incorrect AutoCorrect

### ISSUE THREAD

**Issue by kaners80** [ONLYOFFICE/DocumentServer#1051]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

When entering the text in a new paragraph "1-1234567." It is replaced by List Paragraf on the screen it looks like "1."
Empirically, I found out that autocorrect occurs when typing: numbers one or any seven characters.

Examples:
1-1234567.
1-qwertyu.
1-qwerty.
1-qwert.
1-qwer.
1-qwe.
1-qw.
1-q.
1-.

Replaced with "1."

**What is the expected behavior?**
Autocorrect must be disabled
**Did this work in previous versions of DocumentServer?**
Yes in 5.2.8 work is fine.
**DocumentServer version:**
6.0.0
**Operating System:**
Ubuntu
**Browser version:**
Google Chrome latest

**Comment by Rita-Bubnova** [comment]
Hello, @kaners80.
Thank you for report.
We add options "Automatic bulleted lists" and "Automatic numbered lists" (in "AutoCorrect" window) in Document Server version 6.1. In the test Document Server version 6.1.0 (build:40) these options work, but currently this version is not ready for production.

**Comment by kaners80** [comment]
I have installed test Document Server version 6.1.0 (build: 40). Indeed, the options "Automatic bulleted lists" and "Automatic numbered lists" are there and work correctly.

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until we release v6.1.0 as stable

**Comment by ShockwaveNN** [comment]
DocumentServe and DesktopEditors 6.1 is released. This issue should be fixed
