### ISSUE TITLE
DocumentServer on github and debian repo

### ISSUE THREAD

**Issue by iwkse** [ONLYOFFICE/DocumentServer#1054]
Hi,
I would like to ask if the version shipped here in github it's the same downloaded from 
```
deb https://download.onlyoffice.com/repo/debian squeeze main
```
Would you also please add deb-src or some way to get the origin of such binaries?

To me it looks quite different, as I see binaries where in gihtub there are javascript files.
Eg. onlyoffice/documentserver/server/DocService/docservice
it's a single ELF binary

Could you kindly explain?

Cheers

**Comment by ShockwaveNN** [comment]
> Eg. onlyoffice/documentserver/server/DocService/docservice

Yeah, we use [pkg](https://github.com/vercel/pkg) to pack those nodejs file to remove runtime dependency of `nodejs`

> Would you also please add deb-src or some way to get the origin of such binaries?

You can use [build_tools](https://github.com/ONLYOFFICE/build_tools/) repo to build DocumentServer from scratch

**Comment by iwkse** [comment]
Oh cool, thanks for the explanation!
