### ISSUE TITLE
Upgrade to 6.0.1: Uncaught TypeError: yc.rQb is not a function

### ISSUE THREAD

**Issue by simmstein** [ONLYOFFICE/DocumentServer#1059]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

Upgrade to 6.0.1: Uncaught TypeError: yc.rQb is not a function

Client side: the document is not loaded
Server side: an error is triggered

```
[2020-11-05T09:57:23.714] [ERROR] nodeJS - changesError: docId = 1249301444 Error: Uncaught TypeError: yc.rQb is not a function Script: https://xxxxx/v5.2.8-24//sdkjs/common/libfont/wasm/fonts.js Line: 37:174 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 platform: Linux x86_64 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: TypeError: yc.rQb is not a function
    at https://xxxxx/v5.2.8-24//sdkjs/common/libfont/wasm/fonts.js:37:174
    at https://xxxxx/v5.2.8-24//sdkjs/common/libfont/wasm/fonts.js:37:181
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Upgrade to 6.0.1.

**What is the expected behavior?**

Document loaded and editable.

**Did this work in previous versions of DocumentServer?**

Yes.

**DocumentServer version:**

onlyoffice-documentserver_6.0.1-32_amd64

**Operating System:**

Ubuntu 16.04.7 LTS

**Browser version:**

Version 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.6 (64-bit)

**Additional logs**

```
Préparation du dépaquetage de .../onlyoffice-documentserver_6.0.1-32_amd64.deb ...
Preparing for shutdown, it can take a lot of time, please wait...Done
Stopping documentserver services...
ds:spellchecker: stopped
ds:docservice: stopped
ds:converter: stopped
ds:metrics: stopped
Dépaquetage de onlyoffice-documentserver (6.0.1-32) sur (6.0.0-105) ...
>>>> dpkg : avertissement : le sous-processus ancien script post-removal a retourné une erreur de sortie d'état 1
>>>> dpkg: tentative d'exécution du script du nouveau paquet à la place...
>>>> dpkg: ... on dirait que tout a fonctionné correctement.
[...]
Paramétrage de nodejs (10.23.0-1nodesource1) ...
Paramétrage de onlyoffice-documentserver (6.0.1-32) ...
>>>> Installation de la nouvelle version du fichier de configuration /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf ...
>>>> /var/lib/dpkg/info/onlyoffice-documentserver.postinst: 124: [: false: unexpected operator
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
Congratulations, the ONLYOFFICE documentserver has been installed successfully!
```

**Comment by ShockwaveNN** [comment]
Hi, is this error happens for new created documents after update or only to older ones?
Is this error for each file or only for some specific?

**Comment by simmstein** [comment]
It happens for creating a new file or opening an existing one.
Tested with .docx, .xlsx and .pptx.
Not reproduced with Google Chrome 86.0.4240.183 (Build officiel) on debian 10
Not reproduced with Firefox 78.4.0esr on debian 10.

**Comment by simmstein** [comment]
Client side screenshot:

![](https://upload.deblan.org/u/2020-11/5fa3eaac.png)

**Comment by simmstein** [comment]
fonts.js: https://privatebin.deblan.org/?198ab9e51c06ac8e#DFJAaFB1fstfyzGLrrrdUnCM37Lsbe3EQEr4HmEMTQ7G

**Comment by ShockwaveNN** [comment]
To be clear

Your problem is actual on
Google Chrome Version 83.0.4103.116 (Developer Build) on Debian 10
and not actual on
Google Chrome 86.0.4240.183 (Build officiel) on debian 10

I understand that 83 version of Chrome is not very old, but I'm not sure we guarantee working of older version of Chrome in latest releases.

Is there any reason you could not update chrome 83 to 86?

**Comment by simmstein** [comment]
Sorry the browser version was not complete : Chromium v83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.6 (64-bit). This the version of Chromium packaged in Debian 10 (buster) (package: `chromium`).

**Comment by simmstein** [comment]
> Is there any reason you could not update chrome 83 to 86?

Because this not Google Chrome but Chromium and Chromium is packaged by Debian (so stability + security). 
Btw, 6.0.1 should not break 6.0.0, right?

**Comment by ShockwaveNN** [comment]
Yeah, I've agree with you, something is not right in this

**Comment by ShockwaveNN** [comment]
I've just checked my test server with 6.0.1 installed

And used VirtualBox with Debain with Chromium `Version 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.6 (64-bit)` to access it
![image](https://user-images.githubusercontent.com/668524/98253616-4f39c280-1f8c-11eb-8572-85de5d24c71e.png)

Everything seems fine for me

I think you'r problem is related with font installed on your server

Do you install some additional fonts on your system (on server side)?
Could you attach `/usr/share/fonts` of your server?

**Comment by simmstein** [comment]
Some of files are symlinks so I transformed them to real files. The archive is quite large:

* file: https://kim.deblan.fr/~simon/github/fonts.tar.gz (56MB)
* sha256: 3046e5c321791a6b869904a0e3c3eea78393d6ac7fe3542c7bbf96e84cddb927

**Comment by ShockwaveNN** [comment]
Installed your fonts
![image](https://user-images.githubusercontent.com/668524/98259862-ad1dd880-1f93-11eb-8fc8-04fd8acd7fba.png)

Everything is fine for me

One thing is strange for me, just noticed now:

You said you got error:
```
[2020-11-05T09:57:23.714] [ERROR] nodeJS - changesError: docId = 1249301444 Error: Uncaught TypeError: yc.rQb is not a function Script: https://xxxxx/v5.2.8-24//sdkjs/common/libfont/wasm/fonts.js Line: 37:174 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 platform: Linux x86_64 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: TypeError: yc.rQb is not a function
    at https://xxxxx/v5.2.8-24//sdkjs/common/libfont/wasm/fonts.js:37:174
    at https://xxxxx/v5.2.8-24//sdkjs/common/libfont/wasm/fonts.js:37:181
```

Why there is 5.2.8 version in logs? Did you upgrade from 5.2.8 straight to 6.0.1?

Maybe your chromium got cache from older version?

**Comment by simmstein** [comment]
My history of apt said that `onlyoffice-documentserver:amd64` was upgraded from the version `6.0.0-105` to the version `6.0.1-32`.
`v5.2.8-24` is a part of the request made by the onlyoffice connector in my nextcloud instance.

**Comment by ShockwaveNN** [comment]
This is not right, maybe you're enable Nextcloud Community DocumentServer? It's based on our product but pretty outdated,

**Comment by simmstein** [comment]
> maybe you're enable Nextcloud Community DocumentServer

Negative: 

![](https://upload.deblan.org/u/2020-11/5fa46b0d.png)

Btw, I if run `supervisorctl start all`, the result is: 

![](https://upload.deblan.org/u/2020-11/5fa46bab.jpg)

**Comment by ShockwaveNN** [comment]
On this problem chromium pc could you see which address you see in Debugger for FrameEditor?

![image](https://user-images.githubusercontent.com/668524/98341456-eac84300-201f-11eb-8b4a-eb1e42b3b1d7.png)

You see version 6.0.1.32

If you see 5.2.8.24 something wrong

If everything is fine with this version - you should find why there is 5.2.8 version in logs, I have no idea, unless those some lefovers from Community DocumentServer

**Comment by simmstein** [comment]
As I said, this is my server. 

![screenshot_496](https://user-images.githubusercontent.com/520175/98343687-789d3180-2012-11eb-82ff-ee942f254aa8.png)

**Comment by simmstein** [comment]
How can I regenerates fonts.js?

**Comment by ShockwaveNN** [comment]
@simmstein on your screen version 6.0.0.105 in header, but you said you upgraded to 6.0.1

Could you open this page on both chromium and on some working browser and compare content of fonts.js, do they have same version in commented header?

> How can I regenerate fonts.js?

You can run font generation process via this [instruction](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx)

**Comment by simmstein** [comment]
After comparison, the fonts.js was in cache and I had to remove the Cache folder to force the reload. 
Sorry about that, onlyoffice works fine. Thank you very much @ShockwaveNN!
