### ISSUE TITLE
Document server on Linux has port 8080 in use even when using custom port.

### ISSUE THREAD

**Issue by tarangkhandelwal** [ONLYOFFICE/DocumentServer#106]
I have installed Document server v4.3 on UBUNTU 14.04 LTS using Deb package way.  I changed the  default Document Server port to 8085 .
The server is running fine and is being accessible from port 8085. The issue really is that my port 8080 is not free and is occupied by openoffice process.

 lsof -i :8080
COMMAND  PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    1948 onlyoffice   11u  IPv6  44508      0t0  TCP *:http-alt (LISTEN)

lsof -i :8085
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx   1732     root    7u  IPv4  15391      0t0  TCP *:8085 (LISTEN)
nginx   1732     root    8u  IPv6  15392      0t0  TCP *:8085 (LISTEN)
nginx   1735 www-data    7u  IPv4  15391      0t0  TCP *:8085 (LISTEN)
nginx   1735 www-data    8u  IPv6  15392      0t0  TCP *:8085 (LISTEN)
nginx   1737 www-data    7u  IPv4  15391      0t0  TCP *:8085 (LISTEN)
nginx   1737 www-data    8u  IPv6  15392      0t0  TCP *:8085 (LISTEN)
nginx   1738 www-data    7u  IPv4  15391      0t0  TCP *:8085 (LISTEN)
nginx   1738 www-data    8u  IPv6  15392      0t0  TCP *:8085 (LISTEN)
nginx   1744 www-data    7u  IPv4  15391      0t0  TCP *:8085 (LISTEN)
nginx   1744 www-data    8u  IPv6  15392      0t0  TCP *:8085 (LISTEN)

Expected behavior: I expect port 8080 to be free and available for other app to be used.

**Comment by agolybev** [comment]
Hello.
Thank you for your interest to ONLYOFFICE DocumentServer.
DocumentServer consists of several componets each of them listens TCP port.
See details [here](https://helpcenter.onlyoffice.com/server/docker/document/open-ports.aspx)
