### ISSUE TITLE
.txt file format being changed on edit.

### ISSUE THREAD

**Issue by sreejan-chowdhury** [ONLYOFFICE/DocumentServer#1067]
**Do you want to request a *feature* or report a *bug*?**
On editing a .txt file, the .txt file has openxml format data

**What is the current behavior?**
.txt file edited displays openxml raw data on being opened in a text editor. The data is displayed properly only when opened in Microsoft Word.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Upload a .txt file. Edit it. Download the file and open it in a text editor.

**What is the expected behavior?**
.txt file format should not be changed.

**Did this work in previous versions of DocumentServer?**
NA

**DocumentServer version:**
6.1

**Operating System:**
MacOS

**Browser version:**
Firefox 82.0.2

@ShockwaveNN ShockwaveNN

**Comment by ShockwaveNN** [comment]
> Upload a .txt file. Edit it. Download the file and open it in a text editor.

Do not understand you, if you download file as txt it should download as txt 

> DocumentServer version:
> 6.1

Are you sure, we do not release 6.1 to general public yet, are you using testing version

> @ShockwaveNN ShockwaveNN

Please do not call me directly, until 100% sure I will anser your question, I'm not only one handling issues on GitHub

**Comment by sreejan-chowdhury** [comment]
DocumentServer version:
using latest onlyoffice image `onlyoffice/documentserver:latest

The file extension remains as .txt , but the file content is converted to openxml raw data when being opened in a text editor.

The files I worked on is herewith attached
Before editing:
[docEditing.txt](https://github.com/ONLYOFFICE/DocumentServer/files/5517608/docEditing.txt)
After Editing:
![image](https://user-images.githubusercontent.com/55656762/98680962-22205200-2388-11eb-9b53-6144ab3f9292.png)
[docEditing.txt](https://github.com/ONLYOFFICE/DocumentServer/files/5517632/docEditing.txt)

**Comment by ShockwaveNN** [comment]
Which DocumentServer integration with DMS are you using? Nextcloud, some other or your own?

If you're using your own - are you sure you're sending txt as [fileType](https://api.teamlab.info/editors/config/document#fileType) options?

**Comment by sreejan-chowdhury** [comment]
I am trying it on my own.

The fileType is set to txt. The config that I am using is as follows:
var config = {
  "type": "desktop",
  "documentType": "text",
  "document": {
    "title": "docEditing.txt",
    "url": "https://xyz.com/service/docEditing.txt",
    "fileType": "txt",
    "key": "f6ccfc9e2",
    "permissions": {
      "comment": true,
      "download": true,
      "edit": true,
      "fillForms": true,
      "modifyFilter": true,
      "modifyContentControl": true,
      "review": true
    }
  },
  "editorConfig": {
    "mode": "edit",
    "callbackUrl": "https://xyz.com/service/docEditing.txt",
    "lang": "en",
    "user": {
      "id": "a017d463",
      "name": "testuser"
    },
    "customization": {
      "forcesave": false
    }
  },
  "token": "some token"
};

**Comment by sreejan-chowdhury** [comment]
I tried uploading the `.txt` to https://personal.onlyoffice.com/Products/Files/default.aspx#1606623 and editing it.

On upload, the file extension is `.txt`
![image](https://user-images.githubusercontent.com/55656762/98689286-c955b700-2391-11eb-8031-638822a3d6de.png)

Edited the file:
![image](https://user-images.githubusercontent.com/55656762/98689575-1174d980-2392-11eb-98b7-9e96b3a4d98c.png)

After saving the edited file, I refreshed the view. The file extension was changed to `.docx`
![image](https://user-images.githubusercontent.com/55656762/98689766-3e28f100-2392-11eb-86ac-d9bc151e8029.png)

**Comment by ShockwaveNN** [comment]
@sreejan-chowdhury Yeah, I agree I can reproduce your case on personal, trying to figure it out

**Comment by ShockwaveNN** [comment]
I asked our dev team and this is correct behavoir, any document after editing become ooxml
If you want to change it back to txt you should send it to convert service

This is a post about it in [FAQ](https://api.onlyoffice.com/editors/faq/saving#saving_3)

**Comment by sreejan-chowdhury** [comment]
Thanks. I have gone through the link.
My initial file format is `txt` and the final file format is also `txt`.
The [Conversion API documentation](https://api.onlyoffice.com/editors/conversionapi) specifies that txt to txt conversion is not supported.

**Comment by ShockwaveNN** [comment]
@sreejan-chowdhury Yes, but after editing txt file in result you got `docx` file, and converting it back to `txt` is supported

**Comment by sreejan-chowdhury** [comment]
That is true for https://personal.onlyoffice.com/Products/Files/default.aspx#1606623.

But the project that I have created does something different. On Save, the callback URL is called by document server. The doPost method that has been implemented for the callback, internally calls the document server to get the file (`docEditing.txt`). 
On receiving the response, the InputStream from the response's content is stored to a file with the same name.

In this case there is no conversion of `txt` to `docx`.

**Comment by ShockwaveNN** [comment]
I'm not very good at DocumentServer integration, but as far as I understand - there is no way to edit txt file, without converting it to docx. So you should handle this situation, if your integration trying to edit txt file - result always will be docx file, send it to convert service, get txt and overwrite previous result of `docx`

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
