### ISSUE TITLE
concatenate function displays proper results while document is open in onlyoffice, but breaks in Excel 

### ISSUE THREAD

**Issue by DmitryZayats** [ONLYOFFICE/DocumentServer#1068]
This is a bug.

Enter text in A1 One
Enter text in B1 Two
Enter formula in C1 =CONCAT(A1,"-",B1)
Text displayed in C1 is now One-Two
So far so good.
Save document and open it in Excel (in below example I'm using web based Office 365, but same results are in Windows Excel).

 How it looks in onlyoffice
![image](https://user-images.githubusercontent.com/37493923/98770911-e21d9700-23a8-11eb-8046-3f3bb0ecb9d0.png)

How it looks in Excel
![image](https://user-images.githubusercontent.com/37493923/98770934-ea75d200-23a8-11eb-9c40-df236a7c8c1a.png)

Why it looks like this in Excel is because of @ symbol between = and formula name
If I do Replace in Excel of this symbol - then formula starts to display expected value One-Two
![image](https://user-images.githubusercontent.com/37493923/98770966-fc577500-23a8-11eb-849c-bc51b3325fcc.png)

I'm on Ubuntu 18.04
```
dpkg --list | grep -i onlyoffice
ii  onlyoffice-desktopeditors                  6.0.0-110                                                   amd64        ONLYOFFICE Desktop Editors installation package
```

My settings

![image](https://user-images.githubusercontent.com/37493923/98771324-c8308400-23a9-11eb-8400-e3a74f3a7ce8.png)

My locale

![image](https://user-images.githubusercontent.com/37493923/98771372-ebf3ca00-23a9-11eb-905e-a389354aade6.png)

**Comment by janxkoci** [comment]
I can kind of reproduce this with LibreOffice 6.4, however WPS Office and Gnumeric understand it and open the file just fine. However I do not see the `@` symbol, instead the function name `CONCAT` is in lowercase (i.e. `concat`).

I'm also using Ubuntu-based system and I have all three office suits installed as flatpaks.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/ef765b00c3f0fa9eff8f2724de4986df1ffdc868) in future major releases, but not in release 6.2.

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.3.1 is released. This issue should be fixed
