### ISSUE TITLE
How to add watermark when preview any files?

### ISSUE THREAD

**Issue by 1992w** [ONLYOFFICE/DocumentServer#1070]
OnlyOffice can do this ? How ?

**Comment by matveevms** [comment]
Hello, @1992w 
Do you mean adding a watermark in preview mode on the portal? 


![image](https://user-images.githubusercontent.com/49515977/120475448-088d3900-c3b2-11eb-8cae-ce4e008a7728.png)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by wai52168** [comment]
@1992w 
Have you already resolved your needs? I have the same requirement.
Can you please share your solution? Thank you.
