### ISSUE TITLE
cant find run.bat script in server

### ISSUE THREAD

**Issue by xyz0101** [ONLYOFFICE/DocumentServer#1078]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
i want to compile and deploy server in my windows computer,but i cant find the run.bat script ,and i see it in README 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
i want run the server in my computer by source code
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
 source code,branch master
**Operating System:**
windows 10
**Browser version:**
google

**Comment by ShockwaveNN** [comment]
> i see it in README

Could you point out place there did you see it? I cannot find any info about `run.bat` in https://github.com/ONLYOFFICE/DocumentServer/blob/master/Readme.md

**Comment by xyz0101** [comment]
> > 我在自述文件中看到了它
> 
> 您能指出您看到那里的地方吗？我`run.bat`在[https://github.com/ONLYOFFICE/DocumentServer/blob/master/Readme.md中](https://github.com/ONLYOFFICE/DocumentServer/blob/master/Readme.md)找不到任何有关的信息[](https://github.com/ONLYOFFICE/DocumentServer/blob/master/Readme.md)

here  https://github.com/ONLYOFFICE/server/blob/01cf013e9a77431115931f946ae0dd116b7c5fa6/Readme.md

**Comment by ShockwaveNN** [comment]
Thanks for pointing out, we'll fix this instruction
BTW running only server component is not enough to run our product from source, it's need to be compiled using (build_tools)[https://github.com/ONLYOFFICE/build_tools], but currently we got working instruction only for Linux, not for Windows

**Comment by ShockwaveNN** [comment]
Closing this issue since all things related to compilation will be discuessed in `build_tools` repo
