### ISSUE TITLE
Text frame not imported correctly from this .docx file

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#1079]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
In the attached .docx file, the first line of the text appears outside of its frame.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the .docx file in OO and Word and compare.
**What is the expected behavior?**
The .docx file should appear the same in OO and Word.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
DE 6.0.2, debian 11 bullseye.

**Comment by parrenin** [comment]
This issue seems to be fixed as of 7.0.2.

**Comment by Rita-Bubnova** [comment]
@parrenin, you're right.
This is issue fixed. I tested it in Document Server version 7.0.1.
