### ISSUE TITLE
Feature request: Allow to open documents in separate windows

### ISSUE THREAD

**Issue by artem-leonov** [ONLYOFFICE/DocumentServer#108]
**Do you want to request a *feature* or report a *bug*?**
It's a feature request

**What is the current behavior?**
Opening documents in separate windows is not supported

**What is the expected behavior?**
I want to open documents in separate windows. For example, I want to arrange document windows in various virtual desktop to quick switching between them.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

I use ONLYOFFICE 4.3.2.318 in Windows 10

**Comment by trofim24** [comment]
Good afternoon. You can manage the opening of documents yourself using [api](https://api.onlyoffice.com/editors/basic). If you are looking at a [test case](https://github.com/ONLYOFFICE/document-server-integration) that starts with the server, then yes, there the opening occurs in a separate tab.

**Comment by artem-leonov** [comment]
@trofim24 I am not sure that you correctly understood me. I use desktop version of ONLYOFFICE and I can't open a document in another ONLYOFFICE window.

**Comment by artem-leonov** [comment]
Oh, I accidentally closed it

**Comment by artem-leonov** [comment]
@trofim24 I am sorry, I opened issue in wrong repo. I close it and create in DesktopEditors
