### ISSUE TITLE
Chinese font shape show incorrect. 

### ISSUE THREAD

**Issue by tbs575** [ONLYOFFICE/DocumentServer#1082]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I imported chinese font into onlyoffice docker image and can select these chinese fonts when edit document with onlyoffice server by chrome.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
chinese font sharp is wrong. please see pic. it seemed same shape with cell 'B3','B4','B5' 
![image](https://user-images.githubusercontent.com/30616402/100324540-5d668600-3002-11eb-8451-52036381a3e0.png)

**What is the expected behavior?**
using same font with local 'wps' excel, that is different with 'B3,B4,B5'
![image](https://user-images.githubusercontent.com/30616402/100324989-ed0c3480-3002-11eb-9d70-1710103ecb2e.png)

**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
Docker onlyoffice/documentserver:latest
**Operating System:**
Ubuntu 18
**Browser version:**
Chrome

**Comment by ShockwaveNN** [comment]
@tbs575 Hi, sorry for late responce

Could you attach file with your problem?

**Comment by tbs575** [comment]
@ShockwaveNN upgrade new version 6.1, issue gone.

**Comment by tbs575** [comment]
@ShockwaveNN have a new issue with chinese font file. How can I add chinese font correctly, I added chinese fonts, but display name is english, how to display chinese? thanks
![image](https://user-images.githubusercontent.com/30616402/102839950-aca2a980-443c-11eb-91f4-61e91ac44516.png)
how to setup 'KaiTi'  to  '楷体'

**Comment by tbs575** [comment]
@ShockwaveNN Hi ShockwaveNN, I found new issue with docker's onlyoffice.
used docker image : onlyoffice/documentserver:6.1
and copy fonts into docker as this url 'https://github.com/ONLYOFFICE/DocumentServer/issues/651', found same issue. Then its name will be shown as "????"
![image](https://user-images.githubusercontent.com/30616402/102860078-171d0f00-4468-11eb-8194-2e0177fe6a33.png)

**Comment by ShockwaveNN** [comment]
@tbs575 If your original problem is gone I'll close your issue

About your new issue is latest comment - we already known about this, this is described in https://github.com/ONLYOFFICE/DocumentServer/issues/1099
