### ISSUE TITLE
Changes in xlsx files not saved. 

### ISSUE THREAD

**Issue by anasurimbo** [ONLYOFFICE/DocumentServer#1087]
Hello.
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Working with nextcloud.
After installing DS from source changes in xlsx files not saved. Doc files works fine. Changes in xlsx shown for a minute or two via nextcloud. After some time opening modified xlsx shows it's older version.  

**Did this work in previous versions of DocumentServer?**
Yes

**DocumentServer version:**
serverVersion":"6.0.0"

NextCloud version 
20.0.2

Logs of docservice
```
2020-12-03T09:29:29.068] [DEBUG] nodeJS -.[39m postData request: docId = 3284556416;url = https://ncloud.edcn.ru/index.php/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI4OEQ2RDk4Qi1BNzI1LTQ2QkYtQjM5Ny04Qzk5MDY3NTk1MUQiLCJmaWxlSWQiOjE5NjYyNiwiZmlsZVBhdGgiOiJcLzQ1Ni54bHN4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.q0MgoqlG5Hdx9lL42Tf9Ken5qNdCc3OSWDtzrDzvZ7E;data = {"key":"3284556416","status":3,"url":"https://onlyoffice.edcn.ru/cache/files/3284556416_113/output.xlsx/output.xlsx?md5=2LF_gub3BSlUJcDUlbHeSw&expires=1606977870&disposition=attachment&filename=output.xlsx","changesurl":"https://onlyoffice.edcn.ru/cache/files/3284556416_113/changes.zip/changes.zip?md5=E73iA3-OExaDbTMHUcEXjw&expires=1606977870&disposition=attachment&filename=changes.zip","history":{"serverVersion":"6.0.0","changes":[{"created":"2020-12-03 06:29:18","user":{"id":"ocqt3jyzoelq_88D6D98B-A725-46BF-B397-8C990675951D","name":"obivan"}}]},"users":["ocqt3jyzoelq_88D6D98B-A725-46BF-B397-8C990675951D"],"actions":[{"type":0,"userid":"ocqt3jyzoelq_88D6D98B-A725-46BF-B397-8C990675951D"}],"lastsave":"2020-12-03T06:29:21.054Z","notmodified":false}
.[36m[2020-12-03T09:29:29.261] [DEBUG] nodeJS -.[39m postData response: docId = 3284556416;data = {"error":0}
.[36m[2020-12-03T09:29:29.262] [DEBUG] nodeJS -.[39m End commandSfcCallback: docId = 3284556416
.[36m[2020-12-03T09:29:29.262] [DEBUG] nodeJS -.[39m End receiveTask: docId = 3284556416
.[32m[2020-12-03T09:29:38.706] [INFO] nodeJS -.[39m GET /doc/2037773125/c/info?t=1606976980643 1ms 200
.[32m[2020-12-03T09:29:39.151] [INFO] nodeJS -.[39m GET /doc/2037773125/c/625/0s4t22zi/websocket 0ms (unfinished)
.[36m[2020-12-03T09:29:39.151] [DEBUG] nodeJS -.[39m sendData: docId = undefined;type = license
```

**Comment by anasurimbo** [comment]
Pert of Converter log

[36m[2020-12-03T10:01:43.132] [DEBUG] nodeJS -.[39m Start Task(id=3621324087_6583)
.[36m[2020-12-03T10:01:43.132] [DEBUG] nodeJS -.[39m downloadFileFromStorage list 3621324087/Editor.bin (id=362132
4087)
.[36m[2020-12-03T10:01:43.133] [DEBUG] nodeJS -.[39m downloadFileFromStorage complete(id=3621324087_6583)
.[36m[2020-12-03T10:01:43.133] [DEBUG] nodeJS -.[39m downloadFileFromStorage list  (id=3621324087_6583)
.[36m[2020-12-03T10:01:44.536] [DEBUG] nodeJS -.[39m error spawnAsync(id=3621324087)
Error: ../FileConverter/bin/x2t exited with non-zero code: 86    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async
/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:
17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
.[91m[2020-12-03T10:01:44.536] [ERROR] nodeJS -.[39m stdout (id=3621324087_6583):
.[91m[2020-12-03T10:01:44.536] [ERROR] nodeJS -.[39m stderr (id=3621324087_6583):change_code: Rf.sa&&AscCommon.Rd.F6(Rf.sa));oe[mf].Og.$Of()}jd.wfc=!0;jd.Qec=!0;Le.Tyd(null,lf,!1);Qd.uu();ic.uE=!1;ic.nYc=ic.gjb();null!=Xb&&Xb()})}else null!=Xb&&Xb()};ab.prototype.Ulg=function(Bb,Xb,ic){if(null!=Xb){this.uE=!0;if(null==Bb){var lc=b.Asc.editor.Xc.Wka,Qc;for(Qc in lc)Nd(lc[Qc])&&Nd(lc[Qc].Og)&&Nd(lc[Qc].Og.controller)&&(lc[Qc].yFa(),lc[Qc].Og.controller.Hh());Qd.gg();Qd.Fg();Qd.ONa(null);Qd.eFa(null);Bb=new AscCommonExcel.l0c;Qd.Uyd(Bb,!1)}lc=new AscCommon.k7(Xb,Xb.l
ength);lc.nq=null;var Bd=
change: Uncaught TypeError: Cannot read property 'Wka' of null
DoctRenderer:<result><error index="-2" /></result>

.[91m[2020-12-03T10:01:44.537] [ERROR] nodeJS -.[39m ExitCode (code=86;signal=null;error:-86;id=3621324087_6583)
.[36m[2020-12-03T10:01:44.546] [DEBUG] nodeJS -.[39m processUploadToStorage complete(id=3621324087_6583)

**Comment by ShockwaveNN** [comment]
> change: Uncaught TypeError: Cannot read property 'Wka' of null

Yeah, this is not good

> serverVersion":"6.0.0"

Please describe exact version of DocumentServer your using, host os and installation method (deb, rpm, snap of something else)

And please describe - is this error happens for any xlsx file, or some specific?

**Comment by anasurimbo** [comment]
Installation method: from source via build_tools
DocumentServer: 6.0.0
Host:  Ubuntu 19.10 (builded on 14.04.6)
THis happens for any xlsx file. Newly created, old ones. It looks like every file affected. 
Docs works fine

**Comment by ShockwaveNN** [comment]
Could you try to temporaly setup DocumentServer via Docker pre-compiled version and check if problem in manually compiled version

Also yesterday we released v6.1.0 - you can try to compile it and maybe your problem is gone

**Comment by anasurimbo** [comment]
Cloned https://github.com/ONLYOFFICE/build_tools.git
Now trying to compile again. 
While compiling I'll try to setup Docker version.

Thank you for fast replies.

**Comment by anasurimbo** [comment]
Compiled but shows the same 6.0.0 version. Is it normal?

**Comment by ShockwaveNN** [comment]
Seems we updated master to 6.1.0 two days ago, so I'm not sure

![image](https://user-images.githubusercontent.com/668524/101048264-8a331400-3593-11eb-90e6-e70b00c66a8d.png)

But once again could you try our provided compiled version (docker\deb\rpm) to check if it's your configuration\integration problem or it's really problem with compiled version

**Comment by anasurimbo** [comment]
I've  CentOS8 deployed and install from rpm.
Error shows in logs...

2020/12/04 17:05:05 [error] 10626#10626: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.201.30, server: , request: "GET /healthcheck HTTP/1.1", upstream: "htt
p://127.0.0.1:9810/", host: "onlyoffice2.serv.ru"

netstat -tulp | grep 9810 show nothing.

something is missing

**Comment by ShockwaveNN** [comment]
@Carazyda could you take a look, I'm not familiar with `workspace-install.sh` script

**Comment by anasurimbo** [comment]
This part is the issue.

No such service in http://localhost:9810;

```
location /healthcheck {
        rewrite /healthcheck(.*) /$1  break;
        proxy_pass http://localhost:9810;
        proxy_redirect ~*/(.*) /healthcheck/$1;

        client_max_body_size 100m;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by ShockwaveNN** [comment]
We discussed it with our team and do not understand why port 9810 is used, according to @Carazyda `workspace-install.sh` will install RPM only on default port

And once again - please try to setup Docker version to check your bug, I'm most used to it and with docker I can try to at least help you

**Comment by anasurimbo** [comment]
Sorry for late reply. 

I've managed to launch Onlyoffice Document server builded from sources on CentOS8 (clean install).
It seams all issues vanished. So I think it was system related problem (but 5.5 works fine). 
So my DS moved on CentOS 8 now. 

Thank you for your advices!

**Comment by ShockwaveNN** [comment]
In that case I'll close your issue.
Feel free to comment if you encounter any other isssues, but please first recheck that your problem actual for compiled version only, or for both compiled version and our Docker, it's save time to debug and figure out the reason

**Comment by Teetoow** [comment]
Hi, 

I just had the same problem with 6.1.0 built from source under FreeBSD. I recently upgraded to the latest github version (6.3.1) two days ago and I still have the same problem. I will try to debug x2t in order to understand the problem but it seems to be the same bug since it's exactly the same error message and return code
