### ISSUE TITLE
Onlyofffice preview only show current tab

### ISSUE THREAD

**Issue by avanhoveceovision** [ONLYOFFICE/DocumentServer#1089]
**Do you want to request a *feature* or report a *bug*?**

It's a bug

**What is the current behavior?**

The onlyoffice spreesheet preview only show the focus tab

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![image](https://user-images.githubusercontent.com/65297327/101151374-daf14e00-3621-11eb-8a29-07d7cf520d71.png)
![image](https://user-images.githubusercontent.com/65297327/101151467-fbb9a380-3621-11eb-8d95-7bc4d544f08b.png)
![image](https://user-images.githubusercontent.com/65297327/101151522-0f650a00-3622-11eb-98fa-cf8fe7b6c109.png)

**What is the expected behavior?**

We expected to have all tabs on preview

**Did this work in previous versions of DocumentServer?**

No

**DocumentServer version:**

6.1.0 (Last stable build version)

**Operating System:**

Windows 10/Macos

**Browser version:**
All Browsers

**Comment by avanhoveceovision** [comment]
I will add:

If I open the spreedsheet with onlyoffice and choose to print it. I have this window:

![image](https://user-images.githubusercontent.com/65297327/101152455-67504080-3623-11eb-81c3-e6a3c2578dd5.png)

By default it's "Current sheet". I think it will be "All sheets" by default.

**Comment by Rita-Bubnova** [comment]
Hello, @avanhoveceovision.
We don't think that setting the print range "All sheets" by default is a good idea. An XLSX file can contain many sheets and if a user hit the print button by mistake, it will lead the printing a large number of pages. 

But if you set the Print Range - "All Sheets" once, the browser will save this setting and print all sheets by default for all files.

**Comment by avanhoveceovision** [comment]
Hello, @Rita-Bubnova ,
Ok i understand your point of view.
But can you improve your api pdf convert to get all sheet and not just a single one?
We have onlyoffice preview on our software and it's very blocker for our customers.

Kind regards,

Alexis

**Comment by ShockwaveNN** [comment]
@avanhoveceovision If you want to use convert api to convert all sheets to pdf - see solution [here](https://github.com/ONLYOFFICE/DocumentServer/issues/606#issuecomment-730359636)
Short version - just add empty `spreadsheetLayout: {}` param to your requrest to convert all sheets to PDF

**Comment by avanhoveceovision** [comment]
Thanks ! It works ! 
Have a good day !

Kind regards,

Alexis
