### ISSUE TITLE
Spreadsheet duplicate text being created after carriage return

### ISSUE THREAD

**Issue by Haplo064** [ONLYOFFICE/DocumentServer#109]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Duplicate text being created after a carriage return.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1.Open a spreadsheet in OnlyOffice.
2.Create a cell with two or more lines (Type some text, press [Alt]+[Enter] for a new line and enter some more text)
3.Click off of the cell
4.Click on the cell once, then click on the text entry field above the spreadsheet
5.Begin typing

There is also a similar bug (which I assume is related) to text being duplicated without the carriage return involved, though I have been unable to replicate that issue.

**What is the expected behavior?**
No duplicate text being created.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
Replicated in Chrome and Firefox, on Windows 7 and Mac osX.

**Comment by Haplo064** [comment]
Is there anyone looking into this?

**Comment by trofim24** [comment]
We fixed this problem in the version [ONLYOFFICE-DocumentServer-4.4.1](https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-4.4.1).
Thank you.
