### ISSUE TITLE
some Font issue after upgrade to 6.1.0 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1090]
**Do you want to request a *feature* or report a *bug*?**
Bug & question 
**What is the current behavior?**

> ttf-mscorefonts-installer is now optional dependency. 

What does that mean? There are also installed from ONLYOFFICE from Version 6.0?
/var/www/onlyoffice/documentserver/core-fonts/msttcorefonts/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

After installing "ttf-mscorefonts-installer from (debian constrib)" and run "documentserver-generate-allfonts.sh" 
All fonts look the same. Custom install font also not working.
documentserver-generate-allfonts.sh 
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: ERROR (no such process)
ds:docservice: ERROR (no such process)
ds:converter: ERROR (no such process)
ds:converter: ERROR (no such process)

but: (i had restart all before gen-all-fonts)
supervisorctl status all
converter                        RUNNING   pid 14765, uptime 0:01:23
docservice                       RUNNING   pid 14766, uptime 0:01:23
metrics                          RUNNING   pid 14763, uptime 0:01:23
spellchecker                     RUNNING   pid 14764, uptime 0:01:23

**Did this work in previous versions of DocumentServer?**
Yes 6.0.0

**DocumentServer version:**
6.1.0

**Operating System:**
Debian 10.6
**Browser version:**
Firefox 78.4.1esr

How can i repair my fonts?

**Comment by ShockwaveNN** [comment]
To be clear

Every time you call `documentserver-generate-allfonts.sh` you get

```
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: ERROR (no such process)
ds:docservice: ERROR (no such process)
ds:converter: ERROR (no such process)
ds:converter: ERROR (no such process)
```

or just once?

**Comment by hahaxd35** [comment]
I get this every time.
But not if im running `supervisorctl restart all`

If you want you can close this ticket. I have figure out that my cache and maybe slow internet(?) was the problem.... But this was strange...

SORRY

**Comment by thomasgg23** [comment]
supervisorctl restart all 

worked for me, after clearing cache and restart.
Arial etc. are working

**Comment by ShockwaveNN** [comment]
I'll close that issue, not sure that was the reason, but if `supervisorctl restart all` helped - I think this was not some major issue, but if you got logs containing errors why services not startted it may point out for some bug. Or not

And once again to be clear - every time you add new fonts to DocumentServer every client MUST cleanup it's browser cache for fonts to correctly shown
