### ISSUE TITLE
Cannot save file

### ISSUE THREAD

**Issue by Maxence1502** [ONLYOFFICE/DocumentServer#1094]
Hello there !

After installing OnlyOffice on Nextcloud, I got this error every time I open a document :
![image](https://user-images.githubusercontent.com/42026318/101262156-d40b2e00-373c-11eb-85a2-1a2c441c666c.png)

**Translation :**
Cannot save the document. Please check your login settings or contact your administrator.
When you click the 'OK' button, you will be prompted to download the document.

Logs files of OnlyOffice are empty :
![image](https://user-images.githubusercontent.com/42026318/101262192-21879b00-373d-11eb-853e-cd0b0dab23da.png)

Thanks for your help !

**Comment by ShockwaveNN** [comment]
Hi
> Logs files of OnlyOffice are empty :

You only shown converter logs, there are several folders in there, there may be some other error

**Comment by Maxence1502** [comment]
Thanks for your reply @ShockwaveNN ! I saw that there is other folder. But the err.log is always empty in each.
![image](https://user-images.githubusercontent.com/42026318/101649423-2731f900-3a3b-11eb-8430-238cab13639c.png)
![image](https://user-images.githubusercontent.com/42026318/101649458-3022ca80-3a3b-11eb-8146-4f95bf75f5bc.png)
![image](https://user-images.githubusercontent.com/42026318/101649479-36b14200-3a3b-11eb-8e81-b3244ffe55ad.png)

**Comment by ShockwaveNN** [comment]
If there is no errors in `out.log` in `docserver` folder
I think your error related to integration process, you could try to start up DocumentServer integrated example, via `supervsiorctl start all` and go to `docserverulr/example` to see if test file can be opened and saved OK
If you got no problem with test example - I think problem with integration itself and I'll move your trouble to `onlyoffice-nextcloud` repo

**Comment by Maxence1502** [comment]
I started the example :
![image](https://user-images.githubusercontent.com/42026318/101736246-6310a100-3ac3-11eb-874b-32b9005d9bed.png)
Logs of the example are empty :
![image](https://user-images.githubusercontent.com/42026318/101736280-6f94f980-3ac3-11eb-9ca5-706636328239.png)

The page onlyoffice/example looks good :
![image](https://user-images.githubusercontent.com/42026318/101736353-8c313180-3ac3-11eb-952f-5605f812772c.png)

Welcome page :
![image](https://user-images.githubusercontent.com/42026318/101736377-95220300-3ac3-11eb-9302-96d06e3c67e1.png)

**Comment by ShockwaveNN** [comment]
> The page onlyoffice/example looks good :

Are you able to correctly perform those actions via `/example`
1. Create new docx file and open it
2. Type some random text in it 
3. Save this file and close editor tab
4. Wait for around a minute to file to finish updating version
5. Repopen this file once again and see if all data from step 2 is ok

**Comment by Maxence1502** [comment]
Hm, I can't create a file :
![image](https://user-images.githubusercontent.com/42026318/101740918-bbe33800-3ac9-11eb-9e7a-f95e43ae7c02.png)
But it is added to "My Document" on the example page :
![image](https://user-images.githubusercontent.com/42026318/101741074-e8974f80-3ac9-11eb-80c6-3dfb259ab6bd.png)

In the log file I have after a few tests :
![image](https://user-images.githubusercontent.com/42026318/101740986-cd2c4480-3ac9-11eb-814d-7797c1127c37.png)

**Comment by ShockwaveNN** [comment]
Could you record a video of this process and attach as zip file to this issue? I have several ideas, but I want to be sure

**Comment by Maxence1502** [comment]
Yes I'll do that this evening :)
If you prefer, I'm also available (this evening) to share my screen with you via Teamviewer for example

**Comment by ShockwaveNN** [comment]
> Yes I'll do that this evening :)

That good

> If you prefer, I'm also available (this evening) to share my screen with you via Teamviewer for example

Sorry, I'm just a QA guy, I'm prefer leave Teamviewer or any other real time communication with customers to our support team

**Comment by Maxence1502** [comment]
Hello @ShockwaveNN ! I'm sorry for the delay, here is the video :
[onlyoffice-issue-1094.zip](https://github.com/ONLYOFFICE/DocumentServer/files/5683416/onlyoffice-issue-1094.zip)

I hope you'll see everything you need on it :)

**Comment by ShockwaveNN** [comment]
@Maxence1502 Thanks for video, I see everything I wanted to see, but still not sure I'm understanding your problem right

I've got several questions
1. Which server os and package version you're using
2. I see on your video, that spell checker logs are big, this is not right, probably there is some error in spell checker

I'm not sure how spellcheker can affect opening new files, but I'll start with it, seems there is at least one trouble

**Comment by Maxence1502** [comment]
Hey !

OS : 
![image](https://user-images.githubusercontent.com/42026318/102068490-c4ef4480-3dfc-11eb-95af-685990763d6d.png)

Package version :
![image](https://user-images.githubusercontent.com/42026318/102068577-e18b7c80-3dfc-11eb-8e6f-b753d3d8bc0f.png)

About Spell checker there is a problem, right. This error is spamming :
```
[2020-12-14T11:10:20.969] [WARN] nodeJS - Express server starting...
[2020-12-14T11:10:21.159] [ERROR] nodeJS - Mon, 14 Dec 2020 10:10:21 GMT uncaughtException: bind EADDRINUSE null:8080
[2020-12-14T11:10:21.162] [ERROR] nodeJS - Error: bind EADDRINUSE null:8080
    at listenOnMasterHandle (net.js:1347:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-12-14T11:10:21.193] [WARN] nodeJS - worker 7160 died (code = 1; signal = null). restart...
```

Maybe because Nginx is already on 8080. Where can I change the port of NodeJS ?
![image](https://user-images.githubusercontent.com/42026318/102068964-6f676780-3dfd-11eb-8145-7993b17e7a17.png)

**Comment by ShockwaveNN** [comment]
> Maybe because Nginx is already on 8080. Where can I change the port of NodeJS ?

All configs are stored in `/etc/onlyoffice/documentserver`, but I've never tried to change default port for spellcheker, so this can be a problem.

Maybe it's better to use Docker version for you, it will not need 8080 host port and probably your original error will be gone

**Comment by Maxence1502** [comment]
I purged the old version and installed the docker version on port 8080 (because 80 is running apache) but I still have the same error.
I cannot find the logs files, where are they ?

**Comment by ShockwaveNN** [comment]
Docker logs are inside container in same location in `/var/log/onlyoffice`
You need to connect to container to see them, like `docker exec -it container_id bash`

**Comment by Maxence1502** [comment]
That's really weird. The container doesn't return any logs.
And I don't have the folder "onlyoffice" in /var/log :'(

**Comment by ShockwaveNN** [comment]
> And I don't have the folder "onlyoffice" in /var/log :'(

This is not right, which options for  `docker run` you're used while starting container?

**Comment by Maxence1502** [comment]
I used : 
**sudo docker run -i -t -d -p 8080:80 --restart=always onlyoffice/documentserver**
And then, for the example :
**sudo docker exec 9b67bb7c1c5d sudo supervisorctl start ds:example**

**Comment by ShockwaveNN** [comment]
docker run seems pretty minimal, so I'm not sure there is should be troubles

> And I don't have the folder "onlyoffice" in /var/log :'(

So to be 100%

`docker exec -it 9b67bb7c1c5d  ls /var/log/`
This command didn't show onlyoffice folder?

**Comment by Maxence1502** [comment]
Is show the onlyoffice folder, but it's not on the server in /var/logs :
![image](https://user-images.githubusercontent.com/42026318/103568165-62eaa200-4ec5-11eb-8e95-6fa51cae73b9.png)

**Comment by ShockwaveNN** [comment]
I think your graphical file manager just looking in files on host os, not inside container.
Please note, that container's `/var/log` and host os `/var/log` are completely different folders

**Comment by ShockwaveNN** [comment]
@Maxence1502 Could you describe why you closed this issue? Did you find the source of this problem? Could you describe it if someone else will have same error?

**Comment by Maxence1502** [comment]
I re-installed the server, and made the tutorial again and it worked. I don't really know why
