### ISSUE TITLE
[AMQP] Error: Socket closed abruptly during opening handshake

### ISSUE THREAD

**Issue by ToukiLiu** [ONLYOFFICE/DocumentServer#1095]
I follow this page https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx installed onlyoffice on my server. 

Now,
1. I can access onlyoffice welcome page https://office.xxxxx.xxx/welcome/.
2. But example is not working. 
3. I can create new file on https://office.xxxxx.xxx/example/, 
4. but can not open.

Here is error log by nginx
```
2020/12/10 12:32:10 [error] 28359#28359: *767 open() "/usr/share/nginx/html/doc/192.168.100.100https___office.xxxxx.xxx_8001_example_files_192.168.100.100_new_20_3_.docx1607571005617/c/info" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /doc/192.168.100.100https___office.xxxxx.xxx_8001_example_files_192.168.100.100_new_20_3_.docx1607571005617/c/info HTTP/1.1", host: "office.xxxxx.xxx:8001", referrer: "https://office.xxxxx.xxx:8001/6.1.0-83/web-apps/apps/documenteditor/main/index.html?_dc=6.1.0-83&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=https://office.xxxxx.xxx:8001"
```
I found that file at  ```/var/lib/onlyoffice/documentserver-example/files/192.168.100.100/```.

The question is I don't know is that server work successfully?

Then I have one more issue.
I set the ```Document Editing Service address``` as https://office.xxxxx.xxx:8001/, but nextcloud can't connect to onlyoffice.
Here is the log file
by nextcloud:
```
GuzzleHttp\Exception\ClientException: Client error: `GET https://office.xxxxx.xxx:8001/healthcheck` resulted in a `404 Not Found` response
```
by nginx:
```
2020/12/10 13:06:24 [error] 28362#28362: *848 open() "/usr/share/nginx/html/healthcheck" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /healthcheck HTTP/1.0", host: "office.xxxxx.xxx:8001"
```
I know this issue has already been discussed, but it's not work to me.

I already tried add nextcloud configuration
```
'onlyoffice' => array ('verify_peer_off'=> TRUE),
```
to ```config.php```, but it's not work.

I don’t know if there is any connection between these two issues.
What should I do?

Here is ```/var/log/onlyoffice/documentserver/converter/out.log```
```
$ tail out.log
[2020-12-10T16:10:57.763] [ERROR] nodeJS - [AMQP] Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/snapshot/server/build/server/Common/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-12-10T16:10:58.764] [ERROR] nodeJS - [AMQP] Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/snapshot/server/build/server/Common/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
and ```/var/log/onlyoffice/documentserver/docservice/out.log```
```
$ tail out.log
[2020-12-10T16:13:00.464] [ERROR] nodeJS - [AMQP] Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/snapshot/server/build/server/Common/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-12-10T16:13:01.466] [ERROR] nodeJS - [AMQP] Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/snapshot/server/build/server/Common/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ToukiLiu** [comment]
> RabbitMQ似乎有问题
> 
> rammitmq是否正常运行？rabbitmq日志中有问题吗？
> 
> PS将此问题移至DocumentServer，因为当前问题与nextcloud无关

Actually I have never used rabbitmq, so I don't know how to set it up. I just installed it according to the manual.
But I did not find any error msg from rabbitmq log file. `startup_err`, `shutdown_err` and `crash.log` is empty. 'rabbit@main.log' just has a lot of [info] msg. However, the newest msg is loggd at 12:30 pm.

**Comment by ShockwaveNN** [comment]
@ToukiLiu I've never seen an error like this, googling found this thread
https://github.com/squaremo/amqp.node/issues/101

Seems this error maybe have something to do with descriptions

BTW, could you add info about your host os, DocumentServer package version and rabbitmq version

**Comment by ToukiLiu** [comment]
> @ToukiLiu I've never seen an error like this, googling found this thread
> [squaremo/amqp.node#101](https://github.com/squaremo/amqp.node/issues/101)
> 
> Seems this error maybe have something to do with descriptions
> 
> BTW, could you add info about your host os, DocumentServer package version and rabbitmq version

This is my OS and package version:
Ubuntu 20.04 STL
Nginx 1.18.0
RabbitMQ 3.8.2
DocumentServer 6.1.0-83

One more thing is I'm using WSL host, is that could be the problem?

**Comment by ShockwaveNN** [comment]
> One more thing is I'm using WSL host, is that could be the problem?

This sound like major thing 
To be clear - you're installed ubuntu on Windows 10 via WSL?
I'm not sure we suport such a thing, I've googled `wsl and rabbitmq` and find a lot of different issues

I think it's better to use Docker version in your case, not sure how Windows support docker, not a Windows user (

**Comment by ToukiLiu** [comment]
> > One more thing is I'm using WSL host, is that could be the problem?
> 
> This sound like major thing
> To be clear - you're installed ubuntu on Windows 10 via WSL?
> I'm not sure we suport such a thing, I've googled `wsl and rabbitmq` and find a lot of different issues
> 
> I think it's better to use Docker version in your case, not sure how Windows support docker, not a Windows user (

Yes, I'm installed ubuntu on Windows 10 via WSL.
Unfortunately docker can not run on WSL.

Looks like the best way to solove this problem is buy a Raspberry Pi.

**Comment by ShockwaveNN** [comment]
> Looks like the best way to solove this problem is buy a Raspberry Pi.

Please note there is no easy way to run [DocumentServer on ARM](https://github.com/ONLYOFFICE/DocumentServer/issues/152)

> Unfortunately docker can not run on WSL.

Again I'm not 100% sure but Docker can be run on Widnows iteself, without WSL

**Comment by ToukiLiu** [comment]
> Please note there is no easy way to run [DocumentServer on ARM](https://github.com/ONLYOFFICE/DocumentServer/issues/152)

Oh, thank you for the notes. I'll try put DocumentServer on Windows.

**Comment by ShockwaveNN** [comment]
I think I'll close this issue, for me it's look like more like RabbitMQ issue on WSL, that issue our team can fix

If you got any troubles setup using Docker or native windows version - please create new issue
