### ISSUE TITLE
[Feature Request] PDF Editing

### ISSUE THREAD

**Issue by nlogozzo** [ONLYOFFICE/DocumentServer#1098]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
OnlyOffice has support for opening and viewing PDF files but there is no way to edit and markup these files.

**What is the expected behavior?**
Ability to highlight PDF text, add your own custom TextBoxs, draw on PDFs with a marker tool, add comments, etc. It's nice to have an all in one editor for all types of documents including PDFs and working with the tab interface for all documents as well.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
All versions of OnlyOffice on all platforms up to 6.1.0

**Comment by maruacat** [comment]
Hello @nlogozzo!
I have great news. We have implemented your request to add features in the latest version of Document Server and Desktop Editor - version 8.1.0.
Thank you very much!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
