### ISSUE TITLE
Chinese-font name show character ??? in version 6.1

### ISSUE THREAD

**Issue by rosyclouds** [ONLYOFFICE/DocumentServer#1099]
This same issue has been requested in the past (https://github.com/ONLYOFFICE/DocumentServer/issues/740) and was fixed in 5.4.2. But It doesn't work in  the 6.1. By the way, It works in version 5.6.1.6.

The testing environment is ubuntu20.04 + Docker 19.03.8

![image](https://user-images.githubusercontent.com/10812350/102064642-87a5a980-3e32-11eb-996b-3beccd1beee0.png)
![image](https://user-images.githubusercontent.com/10812350/102059477-e87db380-3e2b-11eb-8114-fb397cf0148c.png)

**Comment by ShockwaveNN** [comment]
Can confirm this issue with this simple Dockerfile:
```
FROM onlyoffice/documentserver:6.1.0

RUN wget https://github.com/ONLYOFFICE/DocumentServer/files/5688010/simsun.tar.gz && \
    tar xvf /simsun.tar.gz && \
    cp /simsun.ttf /usr/share/fonts
```

```
docker build .
docker run -itd -p 80:80 image_id
sleep 120 # wait for documentserver to boot
docker exec -it container_id supervisorctl start all
```

And confirm everything was fine on 5.6.1

I've created bug 47995 in our private issue tracker

**Comment by rosyclouds** [comment]
I have tried your Dockerfile and created two images.(onlyoffice/documentserver_6.1.0_simsun and onlyoffice/documentserver_5.6.1.6_simsun) 
Chinese-font name shows correctly on version 5.6.1.6, but fails on 6.1.0.
![image](https://user-images.githubusercontent.com/10812350/102094409-41197480-3e5d-11eb-8f19-c0b65b399905.png)
**Version 5.6.1.6**
![image](https://user-images.githubusercontent.com/10812350/102094851-c2710700-3e5d-11eb-8829-611326aef4d9.png)
**Version 6.1.0**
![image](https://user-images.githubusercontent.com/10812350/102096010-2b0cb380-3e5f-11eb-8146-c272f5c0f03b.png)

**Comment by ShockwaveNN** [comment]
Problem fixed by https://github.com/ONLYOFFICE/core/commit/de1dde6d1b6859017ec53605641287eb4af7f145 in version 6.1.1
We hope we can make 6.1.1 available by end of year

**Comment by tbs575** [comment]
@ShockwaveNN when will upgrade docker image version?

**Comment by ShockwaveNN** [comment]
DocumentServer v6.1.1 is release, this problem should be fixed

**Comment by cnraorong** [comment]
![1](https://user-images.githubusercontent.com/6263486/106768702-256d6600-6677-11eb-8278-b4ec102d7261.png)
The fonts drop-down menu is displayed correctly, but some text in document content is displayed incorrectly....

**Comment by ShockwaveNN** [comment]
@cnraorong You should create a new issue and describe it in more details (compare for MS Word for example), because our team is not very good at chinese
