### ISSUE TITLE
for spreadsheet how can i setCellValue programmatically

### ISSUE THREAD

**Issue by unmurphy** [ONLYOFFICE/DocumentServer#1102]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently, for spreadsheet  we must click and input to change the cell value

**What is the expected behavior?**
whether exist related api or hook function to change the cell value

**DocumentServer version:**
6.1

**Operating System:**
CentOS
**Browser version:**
all

**Comment by ShockwaveNN** [comment]
@askonev Could you take a look?

**Comment by askonev** [comment]
@unmurphy  Yes, there is an API for inserting values into a table cell.

It is convenient to work with data in cells through methods of the [ApiRange](https://api.onlyoffice.com/docbuilder/spreadsheetapi/apirange) class. This class has a [SetValue()](https://api.onlyoffice.com/docbuilder/spreadsheetapi/apirange/setvalue) method with which we already change the value as we need. By clicking on the link, you will see a simple example of using the method.

[Learn more](https://api.onlyoffice.com/docbuilder/basic) methods for working with Onlyoffice editors for more flexibility working with macros and document builder.

Sincerely yours Onlyoffice Team!

**Comment by unmurphy** [comment]
@askonev thanks for patient reply!  I've seen the spec which you pasted before, but it doesn't seem to solve my problem. my situation is we need open the existed spreadsheet with document server on webpage, when click each one of the cells, it will call a drawer with [jsoneditor](https://github.com/josdejong/jsoneditor) automatically through add event listener with cell. people can edit cell value by jsoneditor layer, the question is we can't set value back into the cell when jsoneditor drawer closed. maybe we need some api for DocEditor

**Comment by askonev** [comment]
Hello @unmurphy! "we can't set value back into the cell when jsoneditor drawer closed" Do you mean that the editor is already closed at this moment?

**Comment by unmurphy** [comment]
@askonev yes！exactly～

**Comment by askonev** [comment]
@unmurphy ok. At the moment, it is possible to access Api methods through JavaScript context: frameEditor. It is possible to test the use of methods in this way through the browser console.

Create a variable [for Spreadsheet] `var Api = Asc.editor`
and then insert the script into the console.

for example:
```
oWorksheet = Api.GetActiveSheet();
oRange = oWorksheet.GetRange("A1");
oRange.SetValue('test');
```

After updating the canvas, the data will be displayed in the cell. Сanvas will be refreshed after the first interaction with the editor interface

**Comment by unmurphy** [comment]
@askonev ok! thanks for your patient and detailed reply, and I‘ll try that later!

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
