### ISSUE TITLE
Cannot read property 'Wka' of null when saving xlsx files

### ISSUE THREAD

**Issue by dani** [ONLYOFFICE/DocumentServer#1106]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Same as described in Bug #1087 (but the bug as been closed). With OnlyOffice 6.1.0 installed on CentOS 8 from RPM, saving an XLS file fails with
```
déc. 20 13:32:31 oods oods-converter[752]: [2020-12-20T13:32:30.994] [ERROR] nodeJS - stdout (id=d60c5348294d589b8a7b_9798):
déc. 20 13:32:32 oods oods-converter[752]: [2020-12-20T13:32:31.026] [ERROR] nodeJS - stderr (id=d60c5348294d589b8a7b_9798):change_code: Rf.sa&&AscCommon.Rd.F6(Rf.sa));oe[mf].Og.$Of()}jd.wfc=!0;jd.Qec=!0;Le.Tyd(null,lf,!1);Qd.uu();ic.uE=!1;ic.nYc=ic.gjb();null!=Xb&&Xb()})}else null!=Xb&&Xb()};ab.prototype.Ulg=function(Bb,Xb,ic){if(null!=Xb){this.uE=!0;if(null==Bb){var lc=b.Asc.editor.Xc.Wka,Qc;for(Qc in lc)Nd(lc[Qc])&&Nd(lc[Qc].Og)&&Nd(lc[Qc].Og.controller)&&(lc[Qc].yFa(),lc[Qc].Og.controller.Hh());Qd.gg();Qd.Fg();Qd.ONa(null);Qd.eFa(null);Bb=new AscCommonExcel.l0c;Qd.Uyd(Bb,!1)}lc=new AscCommon.k7(Xb,Xb.length);lc.nq=null;var Bd=
déc. 20 13:32:32 oods oods-converter[752]: change: Uncaught TypeError: Cannot read property 'Wka' of null
déc. 20 13:32:32 oods oods-converter[752]: DoctRenderer:<result><error index="-2" /></result>
déc. 20 13:32:32 oods oods-converter[752]: [2020-12-20T13:32:31.026] [ERROR] nodeJS - ExitCode (code=86;signal=null;error:-86;id=d60c5348294d589b8a7b_9798)

```
No problem with docx files, only xlsx seems to be affected (haven't tested ods or doc though)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Using OnlyOffice through Seafile integration. Create a new xlsx file, edit it. Try to save it and get

![image](https://user-images.githubusercontent.com/526826/102713435-83610c80-42c8-11eb-853f-3bb76466b946.png)

And the errors posted above in OnlyOffice logs

**What is the expected behavior?**
Document should be saved

**Did this work in previous versions of DocumentServer?**
Yes, was working in all previous version as far as I know, last working version was 6.0.2

**DocumentServer version:**
6.1.0

**Operating System:**
CentOS 8 (but same issue with CentOS 7)

**Browser version:**
Google Chrome 86 but most likely irrelevant

**Comment by ShockwaveNN** [comment]
@dani Hi, several questions

1. Is this error happens for any xlsx file, or any empty xlsx will do? Some specific info should be entered in it, or just some text is A1 cell is enough?
2. Bug #1067 was for ONLYOFFICE DocumentServer compiled from source code and gone after recompilation, am I clear that you're using rpm file provided by our team?
3. Could you try to start integrated test example (info at `http://docserver_ur/welcome`) and try to reproduce your issue without integration to SeaFile

**Comment by dani** [comment]
> @dani Hi, several questions
> 
> 1. Is this error happens for any xlsx file, or any empty xlsx will do? Some specific info should be entered in it, or just some text is A1 cell is enough?

Any XLSX seems to trigger it, even an empty one

> 2. Bug #1067 was for ONLYOFFICE DocumentServer compiled from source code and gone after recompilation, am I clear that you're using rpm file provided by our team?

Yes, I'm using your RPM

> 3. Could you try to start integrated test example (info at `http://docserver_ur/welcome`) and try to reproduce your issue without integration to SeaFile

I just have "Document Server is running" message. How can I test editing a file from the welcome page ?

**Comment by ShockwaveNN** [comment]
> I just have "Document Server is running" message. How can I test editing a file from the welcome page ?

Are you 100% sure that you're using DocumentServer v6.1.0?
"Document Server is running" message is correct message for welcome page on version older than 6.1.0
On version 6.1.0 you should see something like this:
![image](https://user-images.githubusercontent.com/668524/102768434-36e20380-4392-11eb-9c08-8a34540bf588.png)
Could you clear your browser cache and check again?

**Comment by dani** [comment]
Arg my bad. Forgot I reverted the VM from a snapshot, so it's indeed running 6.0.2. Will update to 6.1.0 again and report back

**Comment by ShockwaveNN** [comment]
@dani Ok, good, because it may explain that your problem was actual in other issue, but I hope your problem is gone with update 6.1.0

**Comment by dani** [comment]
Nop, the problem is definitly on 6.1.0. And saving XLSX is working in 6.0.2 (that's the reason for me to revert the VM to a pre 6.1.0 state)

**Comment by ShockwaveNN** [comment]
@dani Ok, try to reproduce your problem with test example (and please record a video just in case)

**Comment by dani** [comment]
mmm, I don't understand. Upgraded again to 6.1.0-83 (still on CentOS 8, using your RPM), but still have the old welcome page

![image](https://user-images.githubusercontent.com/526826/102774519-6fcaaa00-438b-11eb-9ced-81dc898cc0a9.png)

Anyway, will try to bootstrap the example container from your screenshot

**Comment by ShockwaveNN** [comment]
@dani Hm, this may be some unrelated bug, maybe we missed default test example in Centos8, I'll check it again

**Comment by ShockwaveNN** [comment]
Just checked clean installation of DocumentServer on Centos8 using this script:
https://github.com/ONLYOFFICE-QA/documentserver-install-from-manual/blob/master/Centos8/install.sh

There is correct actual welcome screen:
![image](https://user-images.githubusercontent.com/668524/102782497-816f7a00-43aa-11eb-9c04-ac2c6ab15ad3.png)

**Comment by dani** [comment]
Might be because I only have the documentserver component installed
```
[root@oods ~]# rpm -qa | grep only
onlyoffice-documentserver-6.1.0-83.x86_64
[root@oods ~]#

**Comment by ShockwaveNN** [comment]
![image](https://user-images.githubusercontent.com/668524/102785206-9f3ede00-43ae-11eb-9742-d0957c6fa066.png)
Same here, other components from my screen is not installed, but available from repo

So anyway, I think something wrong with your installation, maybe your upgrade process went wrong.
Could you create new virtual machine to check it or use docker versions

**Comment by dani** [comment]
OK, installed 6.1 on a vanilla CentOS 8, I can run and use the sample page. Saving xlsx doesn't fail here, so it might be only happening with either some specific settings I have on a prod box, or something to do with the way it's integrated with Seafile. Will dig a bit more on this

**Comment by dani** [comment]
OK, finaly nailed it. Not sure why, but the script /bin/documentserver-generate-allfonts.sh did not ran during the RPM upgrade. Manually running it after the upgrade fixes it. Not sure why (but most something specific in my setup, and not a bug in OnlyOffice)
