### ISSUE TITLE
When editing Excel at the same time, if you start editing on your PC, you won't be able to edit when your phone is open at the same time

### ISSUE THREAD

**Issue by bigbencat** [ONLYOFFICE/DocumentServer#1109]
When editing Excel at the same time, if you start editing on your PC, you won't be able to edit when your phone is open at the same time

**Comment by ShockwaveNN** [comment]
HI, please fill out issue template correctly, version of DocumentServer, your host OS and your phone os and that do you mean by "editing Excel", we are not Microsoft Excel team

**Comment by bigbencat** [comment]
DocumentServer  6.0.2.5；

**Comment by ShockwaveNN** [comment]
@bigbencat Not sure that is the reason, could you record a video of this process?

**Comment by bigbencat** [comment]
<img width="598" alt="WX20201224-163532@2x" src="https://user-images.githubusercontent.com/9876006/103075267-3651a300-4606-11eb-99c8-9d116f218111.png">
1：edit file on my pc:chrome

**Comment by ShockwaveNN** [comment]
This may be an issue with your integration, which Document Mangement System are you using? Owncloud, nexcloud or something else

**Comment by bigbencat** [comment]
But I have no problem editing on my phone by myself.

**Comment by ShockwaveNN** [comment]
Ok, I'm not very good at mobile editors, @nav-fess could you take a look

**Comment by bigbencat** [comment]
> Ok, I'm not very good at mobile editors, @nav-fess could you take a look

thanks ~

**Comment by nav-fess** [comment]
Case is not repeated. Can be edited synchronously on PC, iOS and Android devices.
DocumentServer 6.4.1.40  
start editing on my PC：Linux Mint 18.04 /chrome
iPad Air 2  (iOS 14.7.1): Chome
Samsung Galaxy S10 (Androdi 11): Chome 93 

![coedit_3](https://user-images.githubusercontent.com/22593004/134510147-62b2dd28-369e-49fb-a96b-7ad12bd6afb3.png)
![coedit_2](https://user-images.githubusercontent.com/22593004/134510151-ee577374-5fa0-45cc-89ef-fcadcef124f5.jpg)
![coedit_1](https://user-images.githubusercontent.com/22593004/134510157-4b6a22e0-3bf8-4aae-91cb-fc3eb52375ad.jpg)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
