### ISSUE TITLE
What is the maximum number of pages supported by a docx file?

### ISSUE THREAD

**Issue by 1992w** [ONLYOFFICE/DocumentServer#1111]
I have a docx document with a file size of 4M and 10009 pages. When previewing, it prompts that the file size exceeds the limit. so, What is the maximum number of pages supported by a docx file?

**Comment by ShockwaveNN** [comment]
As far as I know we have no limits for number of pages by default

But we have limits on size of xml files in OOXML after extraction from zip archive

Default limits located at:
/etc/onlyoffice/documentserver/default.json
```
"inputLimits": [
        {
          "type": "docx;dotx;docm;dotm",
          "zip": {
            "uncompressed": "50MB",
            "template": "*.xml"
          }
        },
        {
          "type": "xlsx;xltx;xlsm;xltm",
          "zip": {
            "uncompressed": "300MB",
            "template": "*.xml"
          }
        },
        {
          "type": "pptx;ppsx;potx;pptm;ppsm;potm",
          "zip": {
            "uncompressed": "50MB",
            "template": "*.xml"
          }
        }
      ]
```

**Comment by 1992w** [comment]
I used the default configuration and the docx document does not exceed the limit. I don't know why the file size exceeds the limit when there are too many pages.

**Comment by ShockwaveNN** [comment]
> docx document does not exceed the limit.

not just docx file, but docx file extracted as zip file
If you attach this file I can take a look into it

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
