### ISSUE TITLE
Different view of pdf files in DocumentServer and other viewers

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#1114]
**Do you want to request a *feature* or report a *bug*?**
*bug*

[This file](https://drive.google.com/file/d/1v-U7-Qw4ODXn4l-e0DXaPfKX4gJgGFOF/view?usp=sharing) shows different.

In DocumentServer it looks like:
![image](https://user-images.githubusercontent.com/20418709/103189759-1107b200-48f0-11eb-8ed1-e57412f892fa.png)

All other pdf-viewers show like:
![image](https://user-images.githubusercontent.com/20418709/103189782-2b419000-48f0-11eb-8cc9-2b2b45f3f2bb.png)

**DocumentServer version:**
6.1.0

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Thank you for report.
I can confirm - this is bug, issue 48149 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released.
I checked the issue in this version - the bug fixed. 
So I close this issue. Feel free to comment or reopen it if you got further questions.
