### ISSUE TITLE
Font list was not loaded properly in editor in Chrome 58, Windows 7, and Document Server v4.2

### ISSUE THREAD

**Issue by nettree** [ONLYOFFICE/DocumentServer#112]
**Do you want to request a *feature* or report a *bug*?**
It's a bug
**What is the current behavior?**

This issue can only be reproduced in Chrome 58 with Windows 7.

We installed "Open Sans" related fonts by following the official instructions below:
https://helpcenter.onlyoffice.com/fr/server/linux/document/install-fonts.aspx
We can see the "Open Sans" related fonts in font list in editor after install them to document server, but when you click "Open Sans" in font drop down list, it will give you the fourth font under the font you choose from the list, for example, I have the font drop down list as shown below:
```
Open Sans
Open Sans Extrabold
Open Sans Light
Open Sans Semibold
OpenSymbol
TakaoExGothic
TakaoGothic
TakaoPGothic
Times New Roman(missing in Chrome 58 in Windows 7)
Trebuchet MS(missing in Chrome 58 in Windows 7)
Verdana(missing in Chrome 58 in Windows 7)
Webdings(missing in Chrome 58 in Windows 7)
```
When I click `Open Sans`, it actually gives me `OpenSymbol` instead, if I click `Open Sans Extrabold`, the text of document will become `TakaoExGothic`, if I click `Open Sans Light`, the font `TakaoGothic` is applied, if I click `Open Sans Semibold`, the font `TakaoPGothic` was used. And there are four fonts missing in Chrome 58, no issue was found in Firefox. Not tested in IE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Steps that are used to reproduce the issue:
* Open a .docx document in OnlyOffice
* Select one paragraph and change font to `Open Sans` or other font in question
* Observe the fourth font underneath what you choose is applied to selected paragraph

**What is the expected behavior?**
The selected font should be applied to text rather than the fourth font underneath it in font list.
**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
The environment we use are:
* Windows 7 Professional Service Pack1
* Chrome 58.0.3029.110
* OnlyOffice Document Server v4.2 with Open Sans font library installed

Not sure whether it works in previous version.

Please investigate, thank you.

**Comment by K0R0L** [comment]
Are you run documentserver-generate-allfonts.sh? This scenario is possible when AllFonts.js (show in network tab) has not been updated or cached in browser. Please clear browser cache.

**Comment by nettree** [comment]
Yes, I followed instruction and run documentserver-generate-allfonts.sh. Will try to clear the browser cache and see if the issue remains.

**Comment by nettree** [comment]
@K0R0L, thank you for your solution, confirmed that clear browser cache solve this issue. I will close this ticket then.
