### ISSUE TITLE
onRequestCompareFile  inoperative,  compare button  not be displayed , my documentServer version is 6.1.0

### ISSUE THREAD

**Issue by kouwenjl** [ONLYOFFICE/DocumentServer#1120]
"events": {
               
                "onRequestCompareFile": onRequestCompareFile,

            }

**Comment by ShockwaveNN** [comment]
Hi, there is plenty of reason why this can happen, so please fill issue template fully, specify OS and especially edition of DocumentServer, since Compare version is not available in open-source version (see [here](https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions))

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
