### ISSUE TITLE
[Feature Request] draw.io functionality

### ISSUE THREAD

**Issue by kleener** [ONLYOFFICE/DocumentServer#1121]
Hi,
it is possible to integrate the functionality of draw.io in onlyoffice.
Then you would have everything together.

**Comment by ShockwaveNN** [comment]
I've take a look at draw.io [source code](https://github.com/jgraph/drawio) and seem it has back-end on java

So I don't think we will be using it

You can try to write your own plugin which will use draw.io if draw.io has some 3rd-party API using our [plugin API](https://api.onlyoffice.com/plugin/basic), but this is defenetly not `several hours of work` task

**Comment by kleener** [comment]
OK, Danke. Ich schätze mal wir nutzenes dann so. Wäre halt nur scön gewesen alles aus einer Hand.
