### ISSUE TITLE
update to 6.0.1, Excel got open error

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/DocumentServer#1122]
Hi:
   we update the version from 5.6.4 to 6.0,  but some excel open got error
![image](https://user-images.githubusercontent.com/11469578/104141340-19341700-53f1-11eb-930d-a68f05b5593e.png)

**Comment by ShockwaveNN** [comment]
Maybe fixed in https://github.com/ONLYOFFICE/DocumentServer/issues/1043

Please fill issue template correctly, i do not understand that is the error in Chinese

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
