### ISSUE TITLE
restart required

### ISSUE THREAD

**Issue by mbaldazzi85** [ONLYOFFICE/DocumentServer#1124]
**Do you want to request a *feature* or report a *bug*?**
i think is a bug

**What is the current behavior?**
several times during the day onlyoffice is inaccessible. supervisor must be restarted. I don't have errors in the onlyoffice logs just a WARN in out.log:
[2021-01-12T12:52:04.308] [WARN] nodeJS - Express server starting...
[2021-01-12T12:52:04.312] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-01-12T12:52:04.377] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

in the last guide i have no seen nothing about install nodejs.
but i remember that in the old version we need to do.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Installed ONLYOFFICE Docs Community Edition on Ubuntu 20.04 on the same server with nextcloud 20.

**What is the expected behavior?**
still works like in other installations with ubuntu 16.04.

**DocumentServer version:**
onlyoffice-documentserver 6.1.0-83
**Operating System:**
Ubuntu 20.04
**Browser version:**
last mozilla 

does anyone have the same problem as me?

**Comment by ShockwaveNN** [comment]
This warn is ok

ONLYOFFICE DocumentServer using nodejs, but not required it, since we using packed binaries, so this is not related to your case

Are you 100% sure there is no errors in any files in `/var/www/onlyoffice/documentserver` or maybe something wrong in nginx itself if your instance is not accessible

**Comment by mbaldazzi85** [comment]
hello ShockwaveNN and thanks for the reply.

at the moment checking the logs onlyoffice and nginx i did not see any errors.
The os is ubuntu 20.04 virtual machine with 2 cpu and 4gb RAM.
At the moment since yesterday (last service restart at 12) onlyoffice is running.
If the problem is nginx what can I check? 

this is the conf ds.conf I use with nginx:

includes /etc/nginx/includes/http-common.conf;
server {
   includes /etc/nginx/includes/ds-*.conf;

     server_name mysite.it;
     listen [::]: 8443 ssl ipv6only = on;
     listen 8443 ssl;
     server_tokens off;
     ssl_certificate /etc/cert/cert.pem;
     ssl_certificate_key /etc/cert/priv.pem;

}
it is OK?
i have some installations and only with ubuntu 20 i have this problem.

**Comment by ShockwaveNN** [comment]
> If the problem is nginx what can I check?

Maybe there is some info in `/var/log/nginx*` or at `/var/log/etc/onlyoffice/nginx*`?

**Comment by mbaldazzi85** [comment]
hello ShockwaveNN,
sorry if I answer now but I do the tests you suggest when the service is not working.
actually it seems that the problem is just nginx crashing. just restart it and come back on the service.
in the error.log under / var / log / nginx /

there is this line:
2021/01/16 19:50:59 [info] 319623 # 319623: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:63

hello shockwawe,
sorry if I answer now but I do the tests you suggest when the service is not working.
actually it seems that the problem is just nginx crashing. just restart it and come back on the service.
in the error.log under / var / log / nginx /

there is this line:
2021/01/16 19:50:59 [info] 319623 # 319623: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:63

can be related to the problem?

**Comment by ShockwaveNN** [comment]
> 2021/01/16 19:50:59 [info] 319623 # 319623: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:63

I think this may be a problem, I googled it and got https://serverfault.com/questions/1005991/how-to-remove-nginx-modulesusing-32768kib-of-shared-memory-for-nchan

There is may be some extra modules in your config, maybe required only by Nextcloud and I'm not aware of them

This may be beacuse you're installed nextcloud and ONLYOFFICE DocumentServer on same server. We do not recommend that.
If you got only on server you better start DocumentServer in docker

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by ykzk** [comment]
Hey.
Just to let you know that this happens to me on Docker containers as well.
The nginx configuration of the DocumentServer container starts with `events {
        worker_connections 768;
        # multi_accept on;
}` but is soon overwritten with `worker_connections 1073741816;` at some point during the start-up phase. Not sure by what exactly. Reverting manually the configuration back to `worker_connections 1024;` inside the container and reloading nginx `nginx -s reload` fixes the issue.
