### ISSUE TITLE
Bug report:  When you open some files, stuck.

### ISSUE THREAD

**Issue by kalcaddle** [ONLYOFFICE/DocumentServer#113]
*bug*

When you open some files, stuck.

demo file:
[error.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1009743/error.xlsx)

All versions are happend

**Comment by trofim24** [comment]
Good afternoon. Thanks for the file. It has 45164 custom style.
We'll fix the problem in the next release.

**Comment by kalcaddle** [comment]
Ok,Thanks

**Comment by kalcaddle** [comment]
And this file;  cann't open.
[test.doc.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1031165/test.doc.zip)

**Comment by trofim24** [comment]
This is not exactly a doc file. Inside is the usual html.
We will correct the recognition of such files, but for now you can simply rename the file and it will open without problems.
[test.doc.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1031672/test.doc.zip)

**Comment by kalcaddle** [comment]
Ok, Thanks

**Comment by ShockwaveNN** [comment]
Closing since issue with original file should be resolved in DocumentServer 4.3.5
