### ISSUE TITLE
Is there an interface for string insertion

### ISSUE THREAD

**Issue by hqzhen** [ONLYOFFICE/DocumentServer#1131]
Is there an interface for string insertion? Similar image insertion interface,Like DocsAPI.insertImage()
![image](https://user-images.githubusercontent.com/45785181/104905328-28046600-59bd-11eb-902f-36e902a8f719.png)

**Comment by ShockwaveNN** [comment]
You mean like typing text into document via GUI?

**Comment by hqzhen** [comment]
> 您是说要通过GUI在文档中键入文本？

Yes is there any way？

**Comment by hqzhen** [comment]
> You mean like typing text into document via GUI?

Yes is there any way？ @ShockwaveNN

**Comment by ShockwaveNN** [comment]
Methods like [this](https://api.onlyoffice.com/docbuilder/textdocumentapi/apiparagraph/addtext) can be called via using Macroses,

**Comment by hqzhen** [comment]
Solved my problem, thanks @ShockwaveNN
