### ISSUE TITLE
uncertainity of open document state during document server upgrade

### ISSUE THREAD

**Issue by devz3r0** [ONLYOFFICE/DocumentServer#1134]
**Do you want to request a *feature* or report a *bug*?**
Information in Documentation not found
**What is the current behavior?**
Uncertainity of state of open documents if upgrading the document server
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
shutdown the document server upgrade, restart and don't know if users lost data.
**What is the expected behavior?**
Either knowing somehow who is having open documents and/or to be able to remotely write back all files and close them.
**Did this work in previous versions of DocumentServer?**
this is not known
**DocumentServer version:**
6.1
**Operating System:**
Ubuntu 20.04
**Browser version:**
Firefox 84.0.2

**Comment by ShockwaveNN** [comment]
Hi, not sure that I'm understand you right, but there is [documentation](https://helpcenter.onlyoffice.com/installation/docs-community-update-linux.aspx
) on upgrading
and there is step with running `documentserver-prepare4shutdown.sh` which will close all opened documents of users

**Comment by devz3r0** [comment]
Thanks for the reply as i am using the docker version I never crossed this one and wasn't able to find that either with my queries.
So i need to do ``` docker exec -it <CID> /bin/bash ```  and then the shutdown command first.
