### ISSUE TITLE
New Request/Upgrade of feature for comments on Document Server Editor

### ISSUE THREAD

**Issue by pankajmalkani** [ONLYOFFICE/DocumentServer#1136]
hi,
Currently we are using Document Server Enterprise Edition. I need new Request/Upgrade of comments as following below.

1) Currently When we upload a word file to Only Office editor in view mode, Comments editor are disabled by default, and in edit/ review mode, comments editor on the left side  are enabled and allow unrestricted of users to add/edit/delete comments in the comments editor
My new Request to the comments : Can we restrict to a small set of users who can see, edit and delete comments in all modes view, edit and review mode. For example in the doceditor.php the code is 

  docEditor = new DocsAPI.DocEditor("iframeEditor",
                {
user: user = [{id:"0","name":"Jonn Smith"}, {id:"1","name":"Mark Pottato"}, {id:"2","name":"Hamish Mitchell"}]
commentuser: user=[{id:"0","name":"Jonn Smith"}, {id:"1","name":"Mark Pottato"}]
}
where user has three users viz john smith, mark pottato and hamish michell and comment user has only john smith and mark pottato who can see, edit and delete the comments but not hamish michell as hamish michell doesn't have rights .

If it is possible then please treat it as a new pull request and we need it urgently as my client want this new feature.

**Comment by SergeyKorneyev** [comment]
Hi,
If you have a valid license, please create your request at https://helpdesk.onlyoffice.com/.

**Comment by ShockwaveNN** [comment]
Closing this issue, since paid users handled by other team
