### ISSUE TITLE
when open a sheet that size is 38M then prompt 'The file size exceeds the limitation set for your server.<br>Please contact your Document Server administrator for details.'  how can i fix it out

### ISSUE THREAD

**Issue by zhikeke** [ONLYOFFICE/DocumentServer#1138]
when open a sheet that size is 38M then prompt 'The file size exceeds the limitation set for your server.<br>Please contact your Document Server administrator for details.'

**Comment by ShockwaveNN** [comment]
You should change values in /etc/onlyoffice/documentserver/default.json in `FileConverter:inputLimits:type[xlsx;xltx;xlsm;xltm]`

Your file may be only 38mb zipped (xlsx file are zipped by default) but extracted it can be greater than 300Mb

**Comment by zhikeke** [comment]
> You should change values in /etc/onlyoffice/documentserver/default.json in `FileConverter:inputLimits:type[xlsx;xltx;xlsm;xltm]`
> 
> Your file may be only 38mb zipped (xlsx file are zipped by default) but extracted it can be greater than 300Mb

it work,thanks!!!

**Comment by urnash** [comment]
I had a similar problem and I solved it very simply by editing
/etc/onlyoffice/documentserver/default.json

But recently I changed one ONLYOFFICE container to the same one and changed the parameters in the same way, and the solution with default.json did not help
I spent almost 2 days looking for a solution, downloaded and compared all the container files, I thought that last time I edited not only default.json, but something else
But the container configuration files were the same.
Finally a solution!!!
1) download from our computer the file that I did not open in nextcloud
2) delete the file in nextcloud
3) upload back
4) and that's it, the file starts to open
