### ISSUE TITLE
Pre-configure Spellchecker-Port

### ISSUE THREAD

**Issue by jotoeri** [ONLYOFFICE/DocumentServer#1139]
**Do you want to request a *feature* or report a *bug*?**
Depends on why the feature is not active? ;)

**What is the current behavior?**
Spellchecker automatically takes Port 8080, no pre-configuration possible.

**What is the expected behavior?**
I really love the way one can pre-set settings on debconf. Unfortunately, the lines, that read the ports for docservice, spellchecker & example are commented out in the postinstallation script and have a different(old?) syntax. Therefore, i can not pre-set a value for `onlyoffice/spellchecker-port: 8081`. (Port 8080 is blocked already for me.)

**Did this work in previous versions of DocumentServer?**
Don't know, seems like it was at least planned somewhen?

**DocumentServer version:**
6.1.0-83
**Operating System:**
Ubuntu 18.04

**Comment by ShockwaveNN** [comment]
@agolybev Could you add this feature?

**Comment by ShockwaveNN** [comment]
Since DocumentServer v6.3.0 there is no separate spellcheker service so this issue should be resolved
