### ISSUE TITLE
Disable Default plugins

### ISSUE THREAD

**Issue by lemonbyte** [ONLYOFFICE/DocumentServer#114]
Is there a option for disabling default plugins.

**Comment by JohnPerkin** [comment]
Hello @lemonbyte!
All the plugins are in the directory `/var/www/onlyoffice/documentserver/sdkjs-plugins/`. You may manually delete the corresponding folders.

**Comment by lemonbyte** [comment]
Thank you !

**Comment by trofim24** [comment]
ONLYOFFICE/sdkjs-plugins#12
