### ISSUE TITLE
Videos in pptx documents

### ISSUE THREAD

**Issue by gensi0** [ONLYOFFICE/DocumentServer#1140]
**What is the current behavior?**

I'm trying to open a PPTX  that is around 238.35 MB. This document contains multiple Videos.
It failed the first time I tried to open it and then the file was updated to ~7MB with all the videos deleted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can't post the file here so I don't know how you can reproduce it. 

My question is : are videos in a PPTX file supported ? 

**What is the expected behavior?**

My presentation with the videos working.

**Did this work in previous versions of DocumentServer?**

I don't know.

**DocumentServer Docker tag:**

onlyoffice/documentserver-de:6.1

**Host Operating System:**
Debian 10.7

**Comment by Rita-Bubnova** [comment]
Hello, @gensi0.
Videos in PPTX file don't delete (issues 35699, 35843 in our private issue tracker), but our presentation editor can't play local videos.
It's connected with https://github.com/ONLYOFFICE/DocumentServer/issues/997.

**Comment by gensi0** [comment]
Hi @Rita-Bubnova ! 

Thanks for the quick answer.

**Comment by ShockwaveNN** [comment]
If your lost your data in this file - this is separate bug, but we cannot help you until we can reproduce this issue with this exact file

I'll close this issue in favor of #997, or in case you can add this file - I'll reopen
