### ISSUE TITLE
Onlyoffice cells format bug

### ISSUE THREAD

**Issue by JohnMcReady** [ONLYOFFICE/DocumentServer#1143]
Hello,

When editing a document and selecting a date cell type (ex: 01/01/2020) everything works. When the document is reopened at random, the cell switches back to number format. Do you have an idea ?

Onlyoffice 6.2.0 via nextcloud 19.0.7

Thanks

**Comment by ShockwaveNN** [comment]
> Onlyoffice 6.2.0
Seems this is version of connector application, not documentserver itself

Could you specify version of ONLYOFFICE DocumentServer? Or by any chance you're using Nextcloud's Community DocumentServer (which is based on our product, but we're not supporting it)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
