### ISSUE TITLE
Wrong output when trying to produce pt-br accents in macOS

### ISSUE THREAD

**Issue by drebs** [ONLYOFFICE/DocumentServer#1144]
**Do you want to request a *feature* or report a *bug*?**

Bug report.

**What is the current behavior?**

- Trying to produce a `ç` (in Mac, it's produced with `Option`+`c`), we get a `©` instead. This problem happens both in Chrome and Firefox.
- Trying to produce an acute accent such as `á`, `é`, `í`, `ó` or `ú` (in Mac, one types `Option` + `e` + the corresponding letter) we get an `€` before the letter with the accent, for example, when trying to get an `é` we get `€é` instead. This problem happens only in Firefox (Chrome works just fine).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Fire up a document in Document Server 6.1.1 using a macOS and then try to produce one of the characters as explained above:

- `Option` + `c`
- `Option` + `e` and then `e`

**What is the expected behavior?**

- When typing `Option`+`c` one should get: `ç`
- When typing `Option`+`e` and then `e` one should get: `é`

**Did this work in previous versions of DocumentServer?**

Yes, we're building the server ourselves, so we know that up to `5.5.3.42` the issue was not present, but then in `6.1.0.33` the problem is already present.

**DocumentServer version:**

We see the issue in all of the following versions:

- 6.1.0.33
- 6.1.0.95
- 6.1.1.56

**Operating System:**

Mac OS Catalina 10.15.6 (19G2021)

**Browser version:**

- Firefox 85.0 (64-bit)
- Chrome 88.0.4324.146 (Official Build) (x86_64)

**Comment by DenisDeeSign** [comment]
Hello @drebs,
thank you for your detailed report. I can confirm - this is a bug, I've created issue 48647 in our private issue tracker.

**Comment by maruacat** [comment]
Hello, @drebs 
We have fixed this issue and it is not reproducible in the latest release version of Document Server and Desktop Editor - version 7.4.1.36.
Thank you very much for your feedback!

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
