### ISSUE TITLE
Word document gets corruptet if it has & sign in the dropdown list

### ISSUE THREAD

**Issue by EugeneBelovOnlyOffice** [ONLYOFFICE/DocumentServer#1155]
I want to report a bug

If Word document has  "&" sign in a dropdown list and I download it into Community Server then the Item with the & sign disappears

Steps.
1. Download the attached file into your docs on the community server
2. Choose item with & sign, save the file
3. Open it again.
4. The item is gone

After investigating, we found that that document has a dropdown where one of the items contains an ampersand. 
Word represents it with &amp;​ but OnlyOffice converts it to a regular &​ which makes it corrupted

 Word version:
<w:dropDownList>
    <w:listItem w:displayText="[select from list]" w:value="[select from list]"/>
    <w:listItem w:displayText="a" w:value="a"/>
    <w:listItem w:displayText="b" w:value="b"/>
    <w:listItem w:displayText="c &amp; c" w:value="c &amp; c"/>
    <w:listItem w:displayText="d" w:value="d"/>
    <w:listItem w:displayText="e " w:value="e"/>
</w:dropDownList>

OnlyOffice version:
<w:dropDownList>
    <w:listItem w:displayText="[select from list]" w:value="[select from list]" />
    <w:listItem w:displayText="a" w:value="a" />
    <w:listItem w:displayText="b" w:value="b" />
    <w:listItem w:displayText="c & c" w:value="c & c" />
    <w:listItem w:displayText="d" w:value="d" />
    <w:listItem w:displayText="e " w:value="e" />
</w:dropDownList>

Didn't try that on the previous versions

OS is win 10, MS office 2019

Chrome 64bit 88.0.4324.150

[word-1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6002958/word-1.docx)
![Screenshot 2021-02-17 at 17 07 06-1](https://user-images.githubusercontent.com/79261168/108361391-7a76b380-7203-11eb-84ad-844490b4b57c.png)

**Comment by Rita-Bubnova** [comment]
Hello, @EugeneBelovOnlyOffice.
Thank you for detailed report.
I can confirm - this is bug, issue 48817 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
We checked this bug in ONLYOFFICE Document Server version 8.0 and I confirm - it was fixed.
Sorry, we forgot to mention that issue was fixed.
