### ISSUE TITLE
Hope to have the function of inserting content control

### ISSUE THREAD

**Issue by xyz0101** [ONLYOFFICE/DocumentServer#1158]
**Do you want to request a *feature* or report a *bug*?**

 *feature* 

**What is the current behavior?**

At present, when editing word documents, content controls can be displayed, but custom content controls cannot be inserted

 
**What is the expected behavior?**

I want to be able to add the ability to insert content controls .

I see that the source code contains this part of the code, but it has been annotated. I don't know why it was annotated.

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
6.0.0
**Operating System:**
linux
**Browser version:**
chrom

**Comment by ShockwaveNN** [comment]
Adding content control is not available in open source version of DocumentServer
You can compare features at [this](https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions) table

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
