### ISSUE TITLE
Document parsing stops unexpectedly at the opening

### ISSUE THREAD

**Issue by jlemangarin** [ONLYOFFICE/DocumentServer#1159]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Document parsing stops unexpectedly at the opening after an unrecognized tag, I guess.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't know to reproduce this behavior, i'm asking my customer to tell me more about how they created the document.

Because this document is confidential, I removed nearly all the content and just kept the broken part.

[Broken_Invisible_Part.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6028528/Broken_Invisible_Part.docx)

Here is the behavior with OnlyOffice (DesktopEditor here) : 
![Capture d’écran de 2021-02-23 12-06-41](https://user-images.githubusercontent.com/22454938/108835398-b62cc700-75cf-11eb-9291-aa611f09f219.png)
And here is the behavior with another editor (MS Office or LibreOffice) : 
![Capture d’écran de 2021-02-23 12-07-13](https://user-images.githubusercontent.com/22454938/108835696-23d8f300-75d0-11eb-9d19-d84a009869a5.png)

**What is the expected behavior?**
Document is parsed successfully

**Did this work in previous versions of DocumentServer?**
i don't know

**DocumentServer version:**
Last DocumentServer & last DesktopEditor versions

**Operating System:**
CentOS 7 / Ubuntu XX / Win10

**Browser version:**
Last chrome version, Last FF version..

**Comment by matveevms** [comment]
Hi, @jlemangarin 
I can confirm - this is bug, issue 48920 in our private issue tracker.

**Comment by jlemangarin** [comment]
Hi @matveevms,

Could you provide us some explications about this issue (When and why it happens) ?

Thanks in advance !

**Comment by matveevms** [comment]
This bug will be fixed (https://github.com/ONLYOFFICE/sdkjs/commit/ca0ba5707e7d3316f422141f29013ae98e93a53a) presumably in the next release 6.2.1.

**Comment by ShockwaveNN** [comment]
DocumentServer 6.2.1 is released and this issue should be fixed
