### ISSUE TITLE
Chrome consume memory when open large spreadsheets file (xlsx)

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DocumentServer#116]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When open large spreadsheets file (xlsx,...) above 10MB, stuck

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Upload 10MB xlsx file about 500.000 row
2. Open it
3. Stuck. Chrome consume more than 2GB ram, and forced close

**What is the expected behavior?**
Ability open and work with large file

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
All version

**Demo file**
[test large xls 3.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1028237/test.large.xls.3.zip)

**Comment by trofim24** [comment]
I think we fixed this issue in previos versions. At the moment I'm opening this file on version 6.2 and Chrome consuming only 250 Mb RAM memory.

**Comment by nor-nic** [comment]
Have the same problem with large docx files on 6gb RAM on two editor instance. Is there a part loading opportunity for large documents?

<img width="1655" alt="Screenshot 2021-05-26 at 12 20 13" src="https://user-images.githubusercontent.com/38042627/119636819-acf50580-be1d-11eb-8ed0-bff4f07f1418.png">
<img width="1674" alt="Screenshot 2021-05-26 at 12 30 34" src="https://user-images.githubusercontent.com/38042627/119637411-4de3c080-be1e-11eb-91a5-2b323ce370b4.png">


> I think we fixed this issue in previos versions. At the moment I'm opening this file on version 6.2 and Chrome consuming only 250 Mb RAM memory.

**Comment by ShockwaveNN** [comment]
@nor-nic No, there is no option to part open document

Maybe we got some memory leak in specific file, you should create a new issue and atach this file
