### ISSUE TITLE
app.css bug

### ISSUE THREAD

**Issue by mpc-killer** [ONLYOFFICE/DocumentServer#1160]
documentserver/web-apps/apps/documenteditor/main/resources/css/app.css

"-webkit-transition:background-color.2s linear;"

should be changed to

"-webkit-transition:background-color .2s linear;"

This problem also occurs in other css.

**Comment by ShockwaveNN** [comment]
Thanks for noticing, our team fixed it in https://github.com/ONLYOFFICE/web-apps/commit/17535856a014bbaf38bce9067be4b2d8719507e4

**Comment by ShockwaveNN** [comment]
DocumentServer v6.3.0 is released. This problem should be fixed
