### ISSUE TITLE
Bug: Incorrect rendering after page 1 (text document)

### ISSUE THREAD

**Issue by theosche** [ONLYOFFICE/DocumentServer#1161]
**What is the current behavior?**
I have a simple word document which opens fine in Word (2011 Mac, v16.29.1) and LibreOffice, but behaves strangely using OnlyOffice. The issue happened first on my nextcloud instance, with OnlyOffice app v6.2.0 and latest docker DocumentServer (id: 289798f72e62). Then I tried to upload the file on personal.onlyoffice.com and the issue remains (which is why I post here).

With Word:
(page 1)
<img width="417" alt="word1" src="https://user-images.githubusercontent.com/34695683/109164869-33e10600-777b-11eb-8e97-36a5ae09fa16.png">
(page 2)
<img width="412" alt="word2" src="https://user-images.githubusercontent.com/34695683/109164933-45c2a900-777b-11eb-973e-dd1037493ddf.png">

With OnlyOffice:
(page 1)
<img width="413" alt="onlyoffice1" src="https://user-images.githubusercontent.com/34695683/109165016-5c690000-777b-11eb-95ac-509b97ec5c1e.png">
(page 2)
<img width="410" alt="onlyoffice2" src="https://user-images.githubusercontent.com/34695683/109165044-64c13b00-777b-11eb-8f26-42feecf70a17.png">
(page 3)
<img width="411" alt="onlyoffice3" src="https://user-images.githubusercontent.com/34695683/109165060-6a1e8580-777b-11eb-8bd0-35b0b486c49a.png">

And it continues with only one line at the bottom for a few pages, then empty pages until page 42.

**To reproduce**
Please check this document:
[example.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6043530/example.docx)
You can see it on OnlyOffice here:
https://personal.onlyoffice.com/Products/Files/DocEditor.aspx?fileid=3970322&doc=U0VLRTBWMDhIM0I5ZlU5dlpaTDlyRjQrWUFrVlhVU2lzRU94c1VzTVJtYz0_IjM5NzAzMjIi0

Currently I could not identify what in particular causes this in the document, I will try to experiment a bit.

**What is the expected behavior?**
Display the file correctly, as in Word.

**DocumentServer version:**
6.1.0 (on personal.onlyoffice.com)
6.2.0 (on my nextcloud server)

**Browser version:**
Occurs at least on 3 different browsers.

**Comment by matveevms** [comment]
Hi, @theosche.
I can confirm - this is bug, issue 48910 in our private issue tracker.

**Comment by theosche** [comment]
Hi, thank you @matveevms.
To clarify, the document was downloaded from a Google Drive, then uploaded to my nextcloud server and modified with OnlyOffice. The issue occured after a few modifications by some other users. So there is not an identical 'original' document that has this issue and was never opened in the OnlyOffice editor.

**Comment by hoegerl** [comment]
Hi, we have the same/similar problem as described here. Some .docx files get suddenly corrupted. We're using NC20.0.8, onlyoffice/documentserver 6.2.0.123, ONLYOFFice-app 6.3.0.
The corrupted file also shows corrupted on another NC/onlyoffice instance.

We managed to get the file working again by opening it in MS Word, saving it as .doc. Then reopeneing the .doc file and save as .docx. From now on this file shows correct again in NC/onlyoffice editor.

The file is beeing worked on by multiple users. The rendering of the file ends with an annotation comment.

This behaviour is really threatening the use of NC/onlyoffice for collaborative work. The possible sudden & random  corruption of documents is not good ;-)

**Comment by ShockwaveNN** [comment]
@hoegerl I think you'r issue may be is not releated to original issue, so better create a new issue and attach sample files which was corrupted

**Comment by hoegerl** [comment]
Hi ShockwaveNN,

sure, i'll do that. I will have to remove/replace the text in the corrupted file since it's confidential information.
