### ISSUE TITLE
Problem with multi-instance deployment

### ISSUE THREAD

**Issue by kevindenight** [ONLYOFFICE/DocumentServer#1166]
**Do you want to request a *feature* or report a *bug*?**
bug
**Did this work in previous versions of DocumentServer?**
Worked in v5.3.4
**DocumentServer version:**
v6.0.2

We deployed onlyoffice service with multi-instance plan.

The CoAuthoring feature worked fine in v5.3.4.

We upgraded to v6.0.2 last week, then we encountered a bug with the CoAuthoring feature: In v5.3.4 the CoAuthoring information was stored in redis before, so it can be shared within several server instance, but now in v6.0.2 the CoAuthoring information is stored in memory, then the CoAuthoring feature become fluctuating.

We find a commit: e796affb5ba2ef9f3814e5700ca3c2969a9656b0 Feature/editor data memory, and we tested the feature in single-instance deployment, it works fine, so we can confirm this problem exactly exists in multi-instance deployment.

Is there a plan fallback to redis?

**Comment by ShockwaveNN** [comment]
Which version of ONLYOFFICE DocumentServer are you using?
We removed support of redis from free `onlyoffice-documentserver` package, but it's still present in `onlyoffice-documentserver-de` and `onlyoffice-documentserver-ee`
I'm not quite remember the reason, like simplify requirement for free package and it's was decision from high management

**Comment by kevindenight** [comment]
@ShockwaveNN We forked this repository and build from source, so i guess it is the free onlyoffice-documentserver package.

**Comment by ShockwaveNN** [comment]
As far as I remember redis code is not in public repo any more

**Comment by kevindenight** [comment]
OK, i see.
