### ISSUE TITLE
Customized Format Cell. [*Unfinished*/*Enchancement*]

### ISSUE THREAD

**Issue by Xelbayria** [ONLYOFFICE/DocumentServer#1167]
This is an enhancement. The feature is not finished. 

I've tried to format a cell where it would have its own units such as "kg" or any units. The "custom" via (*Number Format*) menu does nothing at all. I recommend that the feature need to be finished for the future of OnlyOffice's versions. 

The version of OnlyOffice: 6.1.0.90

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.2.0 are released.
This issue should be fixed.
Feel free to comment or open new issue if got any troubles.
