### ISSUE TITLE
Disable copy to outside OnlyOffice

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DocumentServer#117]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No config param for disable copy to outside OnlyOffice

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Can disable copy to outside OnlyOffice. But can copy in document editor

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
All version

**Comment by falling-star** [comment]
+1 , Can we please get any inputs on this ?

**Comment by denisnone** [comment]
+1, Very good idea. But also add ability to disable downloading files. All this is for handling sensitive information so that employees can't take it home.

**Comment by sprajcpf** [comment]
+1

Mit freundlichen Grüßen,
Christian Sprajc
—
Web: https://www.powerfolder.com
Blog: https://www.powerfolder.com/blog/
XING: https://www.xing.com/companies/powerfolder
LinkedIn: https://www.linkedin.com/company/powerfolder
Facebook: https://www.facebook.com/pages/PowerFolder/298970357835
Twitter: https://twitter.com/PowerFolder
—
PowerFolder dal33t GmbH
HRB 15833, Amtsgericht Neuss
contact@powerfolder.com
+49 2132 / 97 92 292
—
Emanuel-Leutze-Straße 11
40547 Düsseldorf
Germany

**Comment by K0R0L** [comment]
This functionality has already been implemented. After the next issue it will be possible to use

**Comment by falling-star** [comment]
@K0R0L , what are the next release timelines, if you have any update regarding that ?

**Comment by mramsterdam85** [comment]
Hello,
We are using the commercial version latest.
Is it release include?

**Comment by ShockwaveNN** [comment]
@mramsterdam85 sorry, we implement this ability but forgot to include config settings for it. We try to include fix for this in 5.2 in several weeks

**Comment by mramsterdam85** [comment]
Sorry, I have tried "/var/www/onlyoffice/documentserver/sdkjs/common". However i couldn't find the "apiBase.js". 
Our documentserver is onlyoffice-documentserver-de.x86_64 version   5.1.5-59

**Comment by ShockwaveNN** [comment]
@mramsterdam85 this is because source code is minimized by `google-closure-compiler`. It's all in sdk-all.js file, you should find method that looks like `isCopyOutEnabled` and commented it there, I'm trying to find it by now

**Comment by mramsterdam85** [comment]
Ah, found it. It is inside the sdjjs/cell and word

**Comment by ShockwaveNN** [comment]
@mramsterdam85 I think it at http://localhost/2018-07-13-11-42/sdkjs/word/sdk-all-min.js 
by `Ka.prototype.d0a` name

**Comment by mramsterdam85** [comment]
I could successfully configure it. However, the "Copy" menu context is still there. Are we able to disable it as well?

**Comment by ShockwaveNN** [comment]
@mramsterdam85 but copy context menu should be available since copy inside document still be available

**Comment by mramsterdam85** [comment]
@ShockwaveNN how can we totally disable the "Copy" function?

**Comment by ShockwaveNN** [comment]
@mramsterdam85 currently there is no such feature, there is already an issue about it https://github.com/ONLYOFFICE/DocumentServer/issues/254

**Comment by mramsterdam85** [comment]
@ShockwaveNN  thanks for your reply.
Can you please show me how to disable for excel and slide file as well?
I couldn't find the "Ka.prototype.d0a"

**Comment by ShockwaveNN** [comment]
@mramsterdam85 `Ka.prototype.d0a` apply for all 3 editors

**Comment by mramsterdam85** [comment]
Hi,
Could you please try again? I can only find Ka.prototype.d0a in the Word folder.

**Comment by ShockwaveNN** [comment]
@mramsterdam85 names are different, but patterns are same
`Ha.prototype.Z9a` in http://localhost/2018-07-13-11-42/sdkjs/cell/sdk-all-min.js
`Ja.prototype.D0a` in http://localhost/2018-07-13-11-42/sdkjs/slide/sdk-all-min.js

You can easy find them because the located 4 functions after `return "../Common/Images/"` lines

**Comment by mramsterdam85** [comment]
Hahha, got it!
Thanks, it is really tricky ones.
I've tried to compile by run "make" inside the sdkjs folder. However, it always hangs when goes to this file:
`Warning: Error: spawn /home/kevin/Ansarada/DocumentServer/web-apps/build/node_modules/optipng-bin/vendor/optipng ENOENT in file ../apps/documenteditor/main/resources/img/controls/dimension-picker/dimension-highlighted.png Use --force to continue.`
Do you have any experience on this?

**Comment by ShockwaveNN** [comment]
@mramsterdam85 do not know, do you follow instruction closely, it's pretty complicated process
https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx

**Comment by Medanna** [comment]
> 
> 
> @ShockwaveNN how can we totally disable the "Copy" function?

You don't need the 'Copy' feature in editing or viewing mode? Please, describe a situation when it's important.

**Comment by Medanna** [comment]
> 
> 
> @ShockwaveNN how can we totally disable the "Copy" function?

You don't need the 'Copy' feature in editing or viewing mode? Please, describe a situation when it's important.

**Comment by K0R0L** [comment]
https://api.onlyoffice.com/editors/config/
Add flag "copyoutenabled" : false. This is disabled ALL copy functionality, but buttons and conxetxt menu will be presented (but does not work)

**Comment by falling-star** [comment]
@Medanna Could you Please point out where exactly 'copyoutenabled' field has to be put in entire config at https://api.onlyoffice.com/editors/config/ ? Also post which DocumentServer version this functionality exists ?

**Comment by ShockwaveNN** [comment]
@falling-star Hi, seems we got some troubles with using `config` to send this param, we post an update at this issue as soon it will be resolved

**Comment by eg04lt3r** [comment]
@ShockwaveNN , any updates for this issue?

**Comment by K0R0L** [comment]
Мы никак не решим, куда и в какой конфиг добавить эти флаги - настройки для движка редактора. Пока не решили - я сделал возможность выставлять настройки в системном плагине (документация будет чуть позже). В кратце - это плагин, который работает в фоне при старте редактора и не мешает работе других плагинов. Пример для выставления двух настроек (запрет копирования и вотермарк): [.](https://github.com/ONLYOFFICE/sdkjs-plugins/tree/develop/examples/settings)
Можно пользоваться с версии 5.2.8 (выйдет в самое ближайшее время).

**Comment by trofim24** [comment]
We added [document.permissions.copy](https://api.onlyoffice.com/editors/config/document/permissions#copy) field in version 6.0. See [changelog](https://api.onlyoffice.com/editors/changelog#60)
