### ISSUE TITLE
setting style for a line fails

### ISSUE THREAD

**Issue by loigu** [ONLYOFFICE/DocumentServer#1174]
**Do you want to request a *feature* or report a *bug*?**
this is a "double" bug
**What is the current behavior?**
on some lines I observe two behaviors:
1. text on line is selected - on clicking on style it changes the font properties of the text but does not assign style
2. text on line is not selected - on clicking on style it changes the style both for the line and for lines around

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
using attached file [Chore description - for onlyoffice heading bug.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6080594/Chore.description.-.for.onlyoffice.heading.bug.docx)

**case1: assigning style to selected line**
select line "Monthly:" under sangha court
![selected1](https://user-images.githubusercontent.com/274622/109905130-49a17e80-7cd9-11eb-9e13-1f578592d2a8.png)
click "heading4"
![selected2](https://user-images.githubusercontent.com/274622/109905133-4c03d880-7cd9-11eb-8fa6-2d476698c829.png)
result: font properties are changed but text retains "no spacing" style, does not change to "heading4"
![selected3](https://user-images.githubusercontent.com/274622/109905136-4c9c6f00-7cd9-11eb-96a8-4bc4f4b859be.png)

**case2: assigning style to line without selecting**
put cursor on line "Monthly" under Sangha court (does not seem to matter if on beginning, middle or end)
![unselected1](https://user-images.githubusercontent.com/274622/109905139-4dcd9c00-7cd9-11eb-9194-2a581b4b9ffd.png)
click "heading4"
![unselected2](https://user-images.githubusercontent.com/274622/109905142-4e663280-7cd9-11eb-94bc-3b536b5a8769.png)
result: the line, plus four before and one after are changed to 'heading4'
![unselected3](https://user-images.githubusercontent.com/274622/109905145-4efec900-7cd9-11eb-97d1-84c1f4681b9b.png)

Strangely enough if I do the same on the line "Daily:" it works in both cases as expected.

**What is the expected behavior?**
in both cases I would expect it to change only the line "Monthly:" 
* font properties to be according to "heading4"
* the style of the text to be marked as "heading4"

**Did this work in previous versions of DocumentServer?**
No, I have seen this before. It happens very often.

**DocumentServer version:**
docker image from docker hub
image onlyoffice/documentserver id c58d07454e56
"Created": "2020-11-27T21:32:32.51234092Z",
onlyoffice-documentserver 6.1.0-83 amd64

**Operating System:**
docker under debian stretch 64bit

**Browser version:**
chromium Version 88.0.4324.182 (Developer Build) built on Debian 10.8, running on Debian 10.8 (64-bit)

**Comment by matveevms** [comment]
Hello, @loigu 
The display in the style panel is correct. In these cases, we show which style is applied to the paragraph. Applying the linked style depends on the selection. If a fragment of text is selected, then the text style is applied, and if the cursor is in the text or the entire paragraph is selected, then the paragraph style is applied.

**Comment by loigu** [comment]
Dear @matveevms,
I am not sure to which usecase you are referring. There are few separate bugs in my eyes depending on what is selected or not. Can you please specify what usecase you are referring to?

**Comment by matveevms** [comment]
In the first case, a piece of text is selected and a text style is applied to it.
In the second case, the cursor is in the text (or if the entire paragraph is selected) the paragraph style is applied.
In all cases, in our panel, we show the current paragraph style, and not the linked style (when the style of the text and paragraph is linked), as it is implemented, for example, in MS Word.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by loigu** [comment]
Well if user does the same thing on two pieces of text that looks the same and the result is different)(case2 monthly vs daily) .. I would not call that a feature.
But I am nit maintaining that installation anymore, so it completely on you what you thimk about your product.
