### ISSUE TITLE
Hiding rows/columns is applied to last part of a multi-part selection only

### ISSUE THREAD

**Issue by Norbert80** [ONLYOFFICE/DocumentServer#1176]
**Do you want to request a *feature* or report a *bug*?**

Bugreport

**What is the current behavior?**
Hiding rows is applied to last part of a multi-part selection only.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Open a spreadsheet with some content
- Select some rows
- While holding down CTRL select some more rows
- Right-click the over the row-buttons of the last selected row range
- Click "Hide" ("Verbergen" in German language version.)

**What is the expected behavior?**

All rows of the multi-part selection should be hidden.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Linux and Windows builds are affected. Version 5.2.

Note: Same bug applies tp hiding columns.

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual
