### ISSUE TITLE
Document Editing Service address Nextcloud No Longer Working

### ISSUE THREAD

**Issue by jayfinley** [ONLYOFFICE/DocumentServer#1179]
Hello

I had the full blown community server running on Windows, and can no longer get the URL to be accepted in the Document Editing Service address section in Nextcloud.

I have setup a Linux Document Server running latest 6.20 version, followed the guide and enabled SSL.

When I try and use the URL over SSL I get the /welcome page saying that the document server has successfully started.

Nextcloud reports a 404 error whenever I try and enter the full URL even through it loads OK on a webbrowser.

Has anything changed with the later version as its the same now same behavior in both Linux and Windows for me?

Thanks

**Comment by ShockwaveNN** [comment]
Hi, could you exmplain in more details that do you mean by

> I had the full blown community server running on Windows
> I have setup a Linux Document Server running latest 6.20 versio

Because I'm not quite sure that you mean by community server on windows

**Comment by jayfinley** [comment]
Hello

I meant I have tried a dedicated Linux Document Server, and the Windows Workspace OnlyOffice with the Document Server bundle (I thought this was refered to as the Community Edition)

Thanks

**Comment by ShockwaveNN** [comment]
Could you enable integrated test example as describe on `https://doserverurl/welcome` page, open `https://doserverurl/example` and see if you can upload and edit file via this example

If it's ok seems problem somehow on nextcloud side

**Comment by jayfinley** [comment]
Thanks

I have performed those steps and tried to create a sample file as well as upload one.

The documents get created when i try and open them I get these errors

[https://ibb.co/g3886zx](url)

**Comment by ShockwaveNN** [comment]
@jayfinley This is not right.
Could you try to tempraly disable firewall on this server and see if problem persists

If disabling firewall will not help try to look for error in `/var/log/onlyoffice`

**Comment by jayfinley** [comment]
I think this maybe related to SSL

If i open the page with http I get the "Document Server is Runnning"

If i open over SSL i get the welcome page?

**Comment by ShockwaveNN** [comment]
> If i open the page with http I get the "Document Server is Runnning"
> If i open over SSL i get the welcome page?

This is strange
DocumentServer is running is old version of welcome page we removed around release 6.1

Could you check that only one version of `onlyoffice-documentserver` are currently installed via
```
dpkg -l | grep onlyoffice-documentserver
```

If only one - maybe something wrong during update process if you're updated from older version
I'll suggest to use clean install

**Comment by jayfinley** [comment]
Thanks ive done a clean install on a new PC on Windows 

How does this command run on windows? 

net start DsExampleSvc

**Comment by ShockwaveNN** [comment]
@jayfinley I'm no good at windows, so I do not know, but I think this command should be on `/welcome` page

**Comment by jayfinley** [comment]
Your right they provided the Windows command on there.

This is an clean install on a new server running the 

Error.
An error occurred while processing your request.
Server error

**Comment by ShockwaveNN** [comment]
@DenisDeeSign Could you take a look there to look for logs and detect problem on Windows-based server?

**Comment by jayfinley** [comment]
Whats the logic for the ports?

im using localhost/ds-vpath/ and that gets me to the welcome page

IT also references this in the setup

http://localhost:8083/

With the older Community server bundle I had no issues just using localhost/ds-vpath/ would work fine 

The install has added the IIS web server and created port bindings Im unable to figure out the root cause.

**Comment by DenisDeeSign** [comment]
Hello @jayfinley,
are Nextcloud Server and Onlyoffice Workpace different servers? Does Nextcloud run with SSL?

**Comment by jayfinley** [comment]
Hi

Only Office is running on a dedicated Windows Server, and Nextcloud is running on a dedicated Linux VM Appliance

Both are using a SSL.

For the time being I'm using Only Office and adding the Next Cloud WebDav folder to access the documents which works OK.

I'm at a loss of how to get the Document Server running.

**Comment by DenisDeeSign** [comment]
If you open https://worspaceurl:8083/healthcheck , what you get?
Does the editors work fine from Documents module?

**Comment by jayfinley** [comment]
Running from the OnlyOffice Server 
**https://worspaceurl:8083/healthcheck**
This site can’t provide a secure connection

**http://onlyoffice01.sras.cloud:8083/welcome/**
True

Port 8083 is not opened on the Firewall as it is not any port that has been added into the IIS web server sites that were added during installation.

**Comment by DenisDeeSign** [comment]
`ds-vpath` is a virtual folder for external requests and analogue of port 8083, so you should use `ds-vpath` to connect DocumentServer to Nextcloud. 

Do you get any errors if you open the document from Workspace Documents module?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by florian-bellencontre** [comment]
@ShockwaveNN It seems that I have the same problem on my instance.
I have the same error message as @jayfinley.

When I went to look in the logs I saw this: 
```
    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
[2021-06-07T17:01:36.642] [ERROR] nodeJS - error downloadFile:url=https://domain/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.PVO5b0Jnsc_26516IQcnrzlwYfijhHVbRxE6pWVG0Y0;attempt=2;code:EPROTO;connect:null;(id=conv_check_1183000569_docx)
Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
[2021-06-07T17:01:37.648] [ERROR] nodeJS - error downloadFile:url=https://domain/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.PVO5b0Jnsc_26516IQcnrzlwYfijhHVbRxE6pWVG0Y0;attempt=3;code:EPROTO;connect:null;(id=conv_check_1183000569_docx)
Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
```

Searching a bit in the issues I found this issue that seemed similar (https://github.com/ONLYOFFICE/DocumentServer/issues/946). Being under Debian Buster I switched to Ubuntu Focal to get Erlang 22. But the problem is still there.

I looked at my nginx configuration to try to remove the TLS 1.3 but it didn't change anything.

Would you have an idea?

**Comment by ShockwaveNN** [comment]
@florian-bellencontre 
>I have the same error message as @jayfinley.

I'm not sure but I think original author of this issue said nothing about 
```
Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70
```

I think for you it's better to create new issue also make sure that certificate on https://domain is correct, check it via any online cert check tool
