### ISSUE TITLE
Failure to compile on Debian 8

### ISSUE THREAD

**Issue by monoxane** [ONLYOFFICE/DocumentServer#118]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
`~/DocumentServer/core $ make` fails with
```
make[2]: Leaving directory '/home/monoxane/DocumentServer/core/X2tConverter/ASCOfficeDocxFile2/Linux'                                                                                             
Makefile:177: recipe for target 'sub----------ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first' failed                                                                               
make[1]: *** [sub----------ASCOfficeDocxFile2-Linux-ASCOfficeDocxFile2Lib-pro-make_first] Error 2                                                                                                 
make[1]: Leaving directory '/home/monoxane/DocumentServer/core/X2tConverter/build/Qt/X2tSLN.build'                                                                                                
Makefile:241: recipe for target 'build/bin/linux_/x2t' failed                                                                                                                                     
make: *** [build/bin/linux_/x2t] Error 2      
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Follow https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx

**What is the expected behavior?**
It compiles without error

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
Document server version is current git
OS is Debian 3.16.39-1+deb8u2 (2017-03-07)
nodejs is v4.8.3
npm is 4.6.1
No idea if this worked in previous version as I've never compiled it before

**Comment by ShockwaveNN** [comment]
Everything seems fine in compiling `core` for me.
Do you have enough memory and swap for it? It's pretty memory and CPU intensive project.

**Comment by ShockwaveNN** [comment]
Closed due to lack of response

**Comment by saurabhx** [comment]
Hi,

I am having the same problem compiling.

home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/../../../build/lib/linux_64/libdoctrenderer.so: undefined reference to `v8::TryCatch::Message() const'
/home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/../../../build/lib/linux_64/libdoctrenderer.so: undefined reference to `v8::V8::Dispose()'
/home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/../../../build/lib/linux_64/libdoctrenderer.so: undefined reference to `v8::External::New(v8::Isolate*, void*)'
/home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/../../../build/lib/linux_64/libdoctrenderer.so: undefined reference to `v8::TryCatch::~TryCatch()'
/home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/../../../build/lib/linux_64/libdoctrenderer.so: undefined reference to `v8::ScriptCompiler::CachedData::CachedData(unsigned char const*, int, v8::ScriptCompiler::CachedData::BufferPolicy)'
collect2: error: ld returned 1 exit status
Makefile.X2tConverter:157: recipe for target '../../../../build/bin/linux_64/x2t' failed
make[2]: *** [../../../../build/bin/linux_64/x2t] Error 1
make[2]: Leaving directory '/home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/X2tSLN.build'
Makefile:416: recipe for target 'sub-X2tConverter-pro-make_first' failed
make[1]: *** [sub-X2tConverter-pro-make_first] Error 2
make[1]: Leaving directory '/home/sauravarora/codebase/DocumentServer/core/X2tConverter/build/Qt/X2tSLN.build'
Makefile:249: recipe for target 'build/bin/linux_64/x2t' failed
make: *** [build/bin/linux_64/x2t] Error 2

**Comment by ShockwaveNN** [comment]
@saurabhx  What OS and `gcc` are you using.
Alsot check that you have at least 2gb RAM with enabled swap

**Comment by saurabhx** [comment]
OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
GCC :Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

Swap
Filename				Type		Size	Used	Priority
/dev/sda2                              	partition	31250428	0	-1

**Comment by ShockwaveNN** [comment]
@saurabhx 
Seems it's the problem with compiling v8 on ubuntu 16.04
You can see the [thread](https://bbs.archlinux.org/viewtopic.php?id=209871
):
This error can be fixed by 
```
rm DocumentServer/core/Common/3dParty/v8/v8/third_party/binutils/Linux_x64/Release/bin/ld.gold && \
ln -s /usr/bin/ld.gold DocumentServer/core/Common/3dParty/v8/v8/third_party/binutils/Linux_x64/Release/bin/ld.gold
```

**Comment by ShockwaveNN** [comment]
@saurabhx Make a [Dockerfile](https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/master/Dockerfile-Ubuntu-16.04) to test build on Ubuntu 16.04.
Everything is fine
Keep attention to [RUN on 28 line ](https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/master/Dockerfile-Ubuntu-16.04#L28) - With this workaround v8 building without errors
