### ISSUE TITLE
[Seafile] Anonymous users cannot add comments or make revisions

### ISSUE THREAD

**Issue by emilyst** [ONLYOFFICE/DocumentServer#1188]
**Do you want to request a *feature* or report a *bug*?**

Unclear if this is a feature request or a bug report because I do not know what functionality should exist.

**What is the current behavior?**

When I share a document from Seafile, anonymous viewers who are not authenticated to Seafile cannot leave comments or make revision suggestions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In Seafile, from any library:

1. Create a Word document.
2. Get the document's share link from Seafile.
3. Open that share link from a private browser.
4. Observe that the comments pane is totally blank.
5. Observe that the context menu provides no option to leave a comment.

**What is the expected behavior?**

I would expect anonymous viewers to be able to leave comments or make revision suggestions.

**Did this work in previous versions of DocumentServer?**

Unknown. I'm evaluating OnlyOffice's suitability for writing projects, and the ability to accept revisions or comments from people who are not already users is necessary (similar to how Apple Pages or Google Docs work today).

**DocumentServer version:**

6.2.0 installed from [Docker](https://hub.docker.com/r/onlyoffice/documentserver) using the `latest` tag.

Integrated with Seafile 8.0.3 installed from [Docker](https://hub.docker.com/r/seafileltd/seafile-mc) using the `latest` tag.

**Operating System:**

macOS 11.2.3

**Browser version:**

Safari 14.0.3 (16610.4.3.1.7)

**Comment by ShockwaveNN** [comment]
Seems there is incorrect permissions set for comments set while sharing files

Seafile integration is not developed by us, ONLYOFFICE team, but seafile team

I'm not sure which repo is correct to reporting this error, but I think you could try https://github.com/haiwen/seafile/issues

**Comment by emilyst** [comment]
Thank you for the prompt response. I'll try to figure out where in Seafile to file this issue.
