### ISSUE TITLE
Compatibility issue of docx containing chart

### ISSUE THREAD

**Issue by Themistoklis** [ONLYOFFICE/DocumentServer#1189]
**Bug report**
ONLYOFFICE / Microsoft Word compatibility issue.

**What is the current behaviour?**
The saved file created by ONLYOFFICE can't be opened using MS Word.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Create a new Document using ONLYOFFICE.
- Create a chart.
- Save the document.
- Try to open it using MS Word.

The issue does not occur every time / for every chart you do.
Here attached a test file that can't be opened using MS Word.
[test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/6182644/test.docx)

**What is the expected behaviour?**
The file should open fine using MS Word.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
DesktopEditor 6.2 on Windows 10
It didn't work with 6.1 either.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/ab4a8d78315b58b04b4f5ee7f7ad1b029da8f04f, https://github.com/ONLYOFFICE/sdkjs/commit/82a0759517fa582e73e90131fd4966ba91df99f7) in future release.
