### ISSUE TITLE
Unique function shows a wrong result in cell

### ISSUE THREAD

**Issue by kompilainenn** [ONLYOFFICE/DocumentServer#1190]
**Do you want to request a *feature* or report a *bug*?**
it's a bug
**What is the current behavior?**
Unique function shows a wrong result in cell
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Enter in A column some numbers, for example
23
23
45
67
45
23
In C1 cell enter =Unique(A1:A6) and press enter => you'll see only 23 instead
23 in C1
45 in C2
67 in C3
**What is the expected behavior?**
It should be
23 in C1
45 in C2
67 in C3
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors версия 6.2.0.148

![изображение](https://user-images.githubusercontent.com/9006514/111838874-ffd8ab00-890a-11eb-91cb-0eff205d4591.png)

**Comment by VladimirProkofiev52** [comment]
Hello! @kompilainenn 
I have great news. We've fixed this issue, and it will be available in the next major version of the editor.
Have a great day!

**Comment by GrimAnEye** [comment]
@VladimirProkofiev52 Очень и очень ждём!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
