### ISSUE TITLE
There is no entry on the page to set a drop-down box for a cell

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1200]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
There is no entry on the page to set a drop-down box for a cell.
The drop-down box can only be seen using OnlyOffice after the cell drop-down box is set up by other local Office software

**What is the expected behavior?**
You want to have an entry on the page to set the Excel cell drop down box

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
5.5.3

**Operating System:**
win10

**Browser version:**
Chrome Version 89.0.4389.90 (Official) (64-bit)

**Comment by ShockwaveNN** [comment]
Hi

> DocumentServer version:
> 5.5.3

This version is very old, could you update to current version 6.2 and see if this problem exists

**Comment by nobt854** [comment]
Hi,

> 这个版本很旧，您能否更新到当前版本6.2，看看是否存在此问题

As you said, version 5.5.3 is too low. After I tried to upgrade to version 6.2, the problem has been solved and can be closed. Thank you

**Comment by ShockwaveNN** [comment]
@nobt854 Glad to hear
