### ISSUE TITLE
Compatibility Problem MS Excel Sheet — Cross Sheet Reference

### ISSUE THREAD

**Issue by markusTraber** [ONLYOFFICE/DocumentServer#1203]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I got an xlsx file, made with MS Excel, which makes on sheet 2 a reference to a cell on sheet 1. When I now add a new row in sheet 1, the references in sheet 2 won't be updated. When creating the file with OnlyOffice, the cross sheet reference gets updated as expected, therefore I think it is a compatibility issue?! Also I checked the file with MS Office and it works there.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use the file "test_before". Check the output of cells B11 and B12 in sheet 2. They should show "400,00" and "150,00". Add in sheet 1 a row at the top of the document. Check the output of cells B11 and B12 in sheet 2 again, they are now different, since the reference did not get updated.

**What is the expected behavior?**
The reference should be updated, that the value of the cell stays the same.

**Did this work in previous versions of DocumentServer?**
I don't know.

**DocumentServer version:**
6.1.1.53

**Operating System:**
Mac OS Catalina 10.15.7

**Browser version:**
Firefox 87.0

It also seems to affect the Desktop Editors (6.2.0.134).

[test_before.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/6237071/test_before.xlsx)
[test_after.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/6237070/test_after.xlsx)

**Comment by alinasafonova** [comment]
I can confirm - this is bug, issue 49410 in our private issue tracker.
Thank you for report.

**Comment by pangufirst** [comment]
I'd like to know the progress of this issue.

**Comment by alinasafonova** [comment]
This problem is already fixed in v7.3.3
