### ISSUE TITLE
after edit the paragraph ， the paragraph locked,

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/DocumentServer#1205]
Hi
after edit the paragraph ， the paragraph locked, and can not edit again
![image](https://user-images.githubusercontent.com/11469578/113240044-78ae0e80-92de-11eb-8651-d19cf74b4099.png)

**Comment by ShockwaveNN** [comment]
Hi, this is just a too small information to figure out by ourself
Probably some kind of bug on integration side.

Please note your DocumentServer version, host os, document management system

And record video just in case

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
