### ISSUE TITLE
Where is the button or entry of "Automatically insert header" when the table changes pages

### ISSUE THREAD

**Issue by wyb12345** [ONLYOFFICE/DocumentServer#1209]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by matveevms** [comment]
Hello, @wyb12345. 
If I understood you correctly, you are interested in this function indicated in the screenshot
![Screenshot_58](https://user-images.githubusercontent.com/49515977/113718369-3e38dd00-96f5-11eb-9af6-8222c6393a31.png)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
