### ISSUE TITLE
Cannot insert blocklvlsdt with oDocument.InsertContent([xx]) at the current cursor position?

### ISSUE THREAD

**Issue by cnraorong** [ONLYOFFICE/DocumentServer#1214]
@ShockwaveNN 
```
plugin.callCommand(function () {
    oDocument = Api.GetDocument();
    let oBlockLvlSdt1 = Api.CreateBlockLvlSdt();
    oBlockLvlSdt1.GetContent().GetElement(0).AddText("This is the first block.");
    oDocument.AddElement(0, oBlockLvlSdt1);

    let oBlockLvlSdt2 = Api.CreateBlockLvlSdt();
    oBlockLvlSdt2.GetContent().GetElement(0).AddText("This is the second block.");
    oDocument.InsertContent([oBlockLvlSdt2]);

    let oBlockLvlSdt3 = Api.CreateBlockLvlSdt();
    oBlockLvlSdt3.GetContent().GetElement(0).AddText("This is the third block.");
    oDocument.AddElement(oBlockLvlSdt3);
    oDocument.Push(oBlockLvlSdt3);
});
```
The first block and third block can be inserted into the document normally

But the second block is not inserted into the document ...

Why is that?

**Comment by ShockwaveNN** [comment]
@askonev Please take a look

**Comment by askonev** [comment]
Hello @cnraorong. Judging by this [line](https://github.com/ONLYOFFICE/sdkjs/blob/9100c268af8b3c61128ea025fc1704da36cc7ee0/word/apiBuilder.js#L3522), the method insert an array of elements consisting of paragraphs and tables. Therefore, the script from the second block does not work.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
