### ISSUE TITLE
Document is getting slow after some hours of continuous edits in formal mode and 4-5 Users

### ISSUE THREAD

**Issue by devz3r0** [ONLYOFFICE/DocumentServer#1216]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Big Document is getting slow if opened a longer time
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open a document in the morning by multiple users do some edits and witness nearly unresponsiveneness and huge RAM usage.
If all users are getting out of the document and wait 5 mins so it is unloading from the document server and they are reentering it, it works well again.
It looks like the server is keeping a huge amount of transaction logs or such
**What is the expected behavior?**
Some kind of save the document, reload into the documentserver and reload it for all users
**Did this work in previous versions of DocumentServer?**
unknown
**DocumentServer version:**
6.0.2.5 with nextcloud 20.0.8
**Operating System:**
Ubuntu 20.04
**Browser version:**
Firefox 87, chrome

**Comment by ShockwaveNN** [comment]
> DocumentServer version:
> 6.0.2.5 with nextcloud 20.0.8

Could you update to latest version 6.2.1?
We constantly making improvement and memory usage can be improved on latest versions

**Comment by devz3r0** [comment]
I run the update and will doing the test during the next days

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
