### ISSUE TITLE
There is something wrong with the translation

### ISSUE THREAD

**Issue by cnraorong** [ONLYOFFICE/DocumentServer#1217]
![image](https://user-images.githubusercontent.com/6263486/114353443-9bbea500-9b9f-11eb-933a-7d40a4df1e3f.png)
![image](https://user-images.githubusercontent.com/6263486/114353479-ab3dee00-9b9f-11eb-8a29-7e958893bb5c.png)

**Comment by VladaOnlyoffice1** [comment]
您好！请详细翻译有什么问题？

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
