### ISSUE TITLE
Why the English letters   are incomplete??

### ISSUE THREAD

**Issue by efreer1988** [ONLYOFFICE/DocumentServer#1219]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Hi, please describe your problem in details by filling out issue template, I've no idea that you mean

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
