### ISSUE TITLE
Today() function seems to be off by 12 hours

### ISSUE THREAD

**Issue by ressing1** [ONLYOFFICE/DocumentServer#1221]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Today() fills in cell with tomorrows date after 12PM
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use today() function in a cell after 12PM
**What is the expected behavior?**
Show show today's date until 12AM
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
N/A
**Operating System:**
Windows 10
**Browser version:**
N/A

**Comment by alinasafonova** [comment]
Hello, @ressing1
Could you please specify your time zone?

**Comment by ressing1** [comment]
MST

**Comment by alinasafonova** [comment]
I can confirm - this is bug, issue 49032 in our private issue tracker.
Thank you for report.

**Comment by alinasafonova** [comment]
@ressing1

This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/1a72f8a20df112e00d194f8f95a91a983f0b83d0
It will be released as v7.1.0
