### ISSUE TITLE
Data loss for Datetime cells when importing .ods

### ISSUE THREAD

**Issue by quazgar** [ONLYOFFICE/DocumentServer#1227]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
When importing ods sheets, datetime cells are deleted upon the next save.  This behaviour was also described here:
ONLYOFFICE/onlyoffice-nextcloud#242

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. create LibreOffice ods with datetime cell
2. open with OnlyOffice and save
3. open again

**What is the expected behavior?**
Datetime cells should still have original value.

**Did this work in previous versions of DocumentServer?**
Unknown

**DocumentServer version:**
Onlyoffice 6.0.2.5 as owncloud plugin on ownCloud Enterprise Edition 10.4.1
(not my server, so I cannot test on newer versions)

**Operating System:**
Server OS: unknown

**Browser version:**
Firefox 78.5.0esr n Debian

**Comment by ShockwaveNN** [comment]
@Rita-Bubnova Could you take a look at current version is problem persists?

> (not my server, so I cannot test on newer versions)

Sorry @quazgar if this problem cannot be reproduces on latest stable version - I can only advise for your sysadmins to update your server, we constantly improve our product

**Comment by Rita-Bubnova** [comment]
Hello.
> create LibreOffice ods with datetime cell

@quazgar, which format file do you use (ods or xlsx)?
Could you attach file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
