### ISSUE TITLE
OpenOffice files not meeting Microsoft specifications

### ISSUE THREAD

**Issue by gmannGlasswall** [ONLYOFFICE/DocumentServer#1229]
I've tried to do this though your support function but they have not been particularly helpful. I've copied below my initial request to them. Apologies if you are not right team for this, but if you can point me to the right people that would be great. if you are the right people really happy to engage on this.

regards
Greg Mann

[Microsoft defined XSDs inconsistencies with files.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/6318952/Microsoft.defined.XSDs.inconsistencies.with.files.pdf)

Hi,
I'm a test managers at Glasswall Solutions, a CDR technology supplier, but I also deal with support issues escalated to the development team. We’ve hit upon an issue with processing files generated by OnlyOffice and would like to discuss as it could have an impact on both our products. One of our customers, who have our technology embedded in their CDS solutions, reported an issue with files from one of their customers that had been created in OnlyOffice. No files generated by your software are  being regenerated by our engine. We don’t know who the final user is and have one example file from them for investigation purposes but unfortunately we are not allowed to share that. 
When we did our investigation we found that there are structures within the file that do not match the current Microsoft specification. Besides the original sample we used the tool on your website to create simple sample docx and xlsx files and saw similar issues. Although I can’t share the original customer file the app.xml Application tag has ONLYOFFICE/5.6.4.20. When we created the samples the online tool wrote ONLYOFFICE/6.1.0.83. 

The developer wrote up his findings in the attached pdf. His investigation was based upon the current specification but appreciate you could be working to an earlier version. We have seen instances in the past where sequencing and optionality of tags has changed in the specification and made adjustments to our code but have not seen such examples in the tags we had issues with before.
We are not a direct customer of yours, but thought it might be worth collaborating to get to the bottom of what is happening to keep your and our customers happy.

Regards
Greg Mann
Test Manager, SDK Products 
Email: gmann@glasswallsolutions.com
 
Glasswall Solutions Limited
Continental House, Oakridge
West End
Woking
Surrey
GU24 9PJ
www.glasswallsolutions.com

**Comment by ShockwaveNN** [comment]
Hi, thanks for your detailed document

I've created issue 49667 in our private issue tracker to discuss this problem. 
I've got a little talk with our dev team and they will be able to fix this problem not in next release v6.3.0 but probably in v6.4.0, but currently it's not clear if this an easy fix, so I will not make any promises

**Comment by gmannGlasswall** [comment]
@ShockwaveNN I should add that the samples we looked at were very simple so there could be other sequencing errors elsewhere.

Also are there any estimates on the timeline for the releases you mention?

**Comment by ShockwaveNN** [comment]
> Also are there any estimates on the timeline for the releases you mention?

Sorry, once again - I'm not in position to make any promises

**Comment by gmannGlasswall** [comment]
Appreciate that (been in the same place far too often), just looking for an indication if we are talking days , weeks or months away?

**Comment by ShockwaveNN** [comment]
Defenetly at least months, since we are in process of relese version of v6.3 and not even started on working on next major release in which this change may (or may not) be included

**Comment by gmannGlasswall** [comment]
Thanks

**Comment by ShockwaveNN** [comment]
@gmannGlasswall Hi there, your issue should be fixed via https://github.com/ONLYOFFICE/core/commit/e4f9cf881b2cd950679cec222238319c0cc0c62d

And available in nightly build v99.99.99.2518 (Please note that it's not ready for any kind of production use and may contain very serious bugs)

You can test it via installing via Docker image - `docker run -itd -p 80:80 onlyoffice/4testing-documentserver-ee:99.99.99.2518`

I personally didn't test this changes, but please attach specific problems with incorrect order, not just PDF with general info if issue is still actual for any setting

**Comment by gmannGlasswall** [comment]
Thanks for the update

**Comment by ShockwaveNN** [comment]
@vladad Our team has fixed problem with `uiPriority` and `qFormat` order at https://github.com/ONLYOFFICE/core/commit/a6b459923e2c4db10d76b2e90ca16e5a828ce509

And this fix will be available in v7.0.0

If anyone found any new issues with structure of ooxml please create separate issue for each problem, since current issue is already pretty messy from several issues (some fixed, some not) and will be hard to track in future

**Comment by ShockwaveNN** [comment]
If I'm not mistaken all problems in this issue should be fixed in current stable version, but feel free to comment or open a new one if I'm wrong
