### ISSUE TITLE
Issue with displaying bullet points on a form header spanning multiple pages.

### ISSUE THREAD

**Issue by Haplo064** [ONLYOFFICE/DocumentServer#123]
[Can Open.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1060156/Can.Open.docx)
[Cannot Open.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1060157/Cannot.Open.docx)

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
.docx document will not open if the document contains a table that spans multiple pages, with a header containing a bullet point.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have provided two example documents, labeled "Cannot open" and "Can open" with the only difference being the bullet point in the table header.

Also, adding a bullet point to a header in OnlyOffice editing and then inputting any other character will erase the table in the editor.

**What is the expected behavior?**
The header should not crash the system when it contains a bullet points.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
DocServer Less than 4.3.0, Chrome, IE, Firefox, Windows, Mac, Linux.

I am unsure if this worked in previous version of only office.

**Comment by ShockwaveNN** [comment]
Both files opens fine in 5.1.1, so closing bug
