### ISSUE TITLE
Is there a plan for custom formulas?

### ISSUE THREAD

**Issue by huisnotacouncillor** [ONLYOFFICE/DocumentServer#1231]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

  As the title describes

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by Rita-Bubnova** [comment]
Hello, @huisnotacouncillor.
Could you describe in more detail what you need? Or show how it is implemented in other applications?

**Comment by huisnotacouncillor** [comment]
For example, calculate the Round half to even result

URL for calculation formula rules：https://en.wikipedia.org/wiki/Rounding#Round_half_to_even

**Comment by Rita-Bubnova** [comment]
@huisnotacouncillor, could you point out not that formula you'll need, but to mechanism how to implement own formula for example in MS Office or Google Sheets?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
