### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1232]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In the formula calculation logic, how can OnlyOffice get the coordinate of the cell where the current formula calculation is taking place.

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
6.2.1

**Operating System:**
win10

**Browser version:**
Chrome Version 89.0.4389.90 (Official) (64-bit)

**Comment by ShockwaveNN** [comment]
@GoshaZotov could you point out code place

**Comment by nobt854** [comment]
@GoshaZotov could you help me point out code place?
thank you.

**Comment by GoshaZotov** [comment]
before answering this question, I need to understand why you need the coordinate of the cell? what do you want to do?

**Comment by nobt854** [comment]
@GoshaZotov I want to add a custom formula in SDKJS. In the logic of the custom formula, I want to get the cell coordinates of the calculation of the current formula, and set the format of the cell according to the cell coordinates.
thank you for your reply.

**Comment by nobt854** [comment]
@GoshaZotov hello

**Comment by GoshaZotov** [comment]
@nobt854, hello! Can you give us a concrete example?

**Comment by GoshaZotov** [comment]
Example of calculating one of the formulas - https://github.com/ONLYOFFICE/sdkjs/blob/master/cell/model/FormulaObjects/textanddataFunctions.js#L1857

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
