### ISSUE TITLE
 Move cell, row or column [Spreadsheet] [Feature]

### ISSUE THREAD

**Issue by biva** [ONLYOFFICE/DocumentServer#1234]
Feature request

I didn't find the way to move a cell (or a row or a column) and _insert it_ where I move it (instead of replacing the existing cell).

### Feature request: steps to reproduce in Excel

1. Select a cell
2. Drag and drop it somewhere else, while pressing the _Shift_ key
3. Result: the cell is inserted where I left it
4. This also works with rows and columns

I tried in OnlyOffice and it just **replaces** the existing cell where I move it (instead of **inserting** it).

I read the documentation but the only workaround I found is to insert a row/column, move my data and delete the empty row (where my data was before)

**Comment by Rita-Bubnova** [comment]
Hello, @biva.
Maybe, is it duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1208?

**Comment by biva** [comment]
Definitely a duplicate. Sorry again, I did not search carefully enough :(
