### ISSUE TITLE
Insert cell [spreadsheet] [feature]

### ISSUE THREAD

**Issue by biva** [ONLYOFFICE/DocumentServer#1235]
Feature request

**What is the current behavior?**
I can insert a column or a row, but not a cell

**What is the expected behavior?**
In Excel, I can insert a cell, and then choose if I want to shift the cells right or down.
If I select multiple cells, it inserts the number of cells that I have selected.

I would love to see this in OnlyOffice.

**Comment by Rita-Bubnova** [comment]
Hello, @biva.
Do you mean this insert of cells?
![ForIssue1235](https://user-images.githubusercontent.com/25282241/115572709-d2e03500-a2c8-11eb-8c40-2c832aa41354.JPG)

**Comment by biva** [comment]
Yes! Sorry, I don't know how I did not see it. Let me close this issue.
