### ISSUE TITLE
6.2.1 Server-side exceptions

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1241]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Preview any format document, all report error, error log see attachment,
C:\Program Files\ONLYOFFICE\DocumentServer\Log\converter:
[converter-error-log.zip](https://github.com/nobt854/self_file/raw/main/converter-error-log.zip)

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
6.2.1

**Operating System:**
The service is deployed in Windows Server 2012.
Use OnlyOffice on Windows 10.

**Browser version:**
Chrome Version 89.0.4389.90 (Official) (64-bit)

**Comment by ShockwaveNN** [comment]
I think there may be some other errors in other logs, not only in converter. Could you attach them

Currently in logs are:
```
[2021-04-22T16:17:01.485] [ERROR] nodeJS - ExitCode (code=3221225506;signal=null;error:-80;id=596910121439648-V1)
```
And I'm not sure that this mean, which nodejs version are you using?

**Comment by nobt854** [comment]
OnlyOffice has removed the dependency on NodeJS since version 5.5.0, I am currently using 6.2.1 and no independent installation of NodeJS, it should be the built-in NodeJS, right?

**Comment by ShockwaveNN** [comment]
Oh, sorry you're right about nodejs

But question about other logs still actual

**Comment by nobt854** [comment]
1. The directory is empty with no associated folder
C:\Program Files\ONLYOFFICE\DocumentServer\server\App_Data\cache\files
2. The Log directory contains all Log files
[onlyoffice-database-sql](https://raw.githubusercontent.com/nobt854/self_file/main/onlyoffice-database-sql.sql)
3. OnlyOffice database all SQL scripts
[Log.zip](https://github.com/nobt854/self_file/raw/main/Log.zip)

**Comment by ShockwaveNN** [comment]
I've talked with our dev team and `-80` error mean trouble with convertation, maybe your file is broken?

Could you attach files which you're trying to convert?

**Comment by nobt854** [comment]
I don't think the documentation caused the problem. You can check
[exception-demo-file.zip](https://github.com/nobt854/self_file/raw/main/exception-demo-file.zip)

**Comment by ShockwaveNN** [comment]
Yeah, this files opens fine on docker on ubuntu 18.04 with DocumentServer 6.2.2

I think this may be some kind windows-related problem

Since I'm not a windows guy - @DenisDeeSign could you take a look

I think there may be something wrong with `x2t` on this system, but I'm not sure

**Comment by nobt854** [comment]
During Windows environment deployment, are there any dependencies or packages related to X2T that need to be customized and installed

**Comment by ShockwaveNN** [comment]
Sorry seems I've missed your last question

Unfortunately we still do not have full and correct compilation instruction for windows platform so I simply do not know answer to your question

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
