### ISSUE TITLE
The key ctrl+click don‘t open the contents pages？

### ISSUE THREAD

**Issue by zhzg605** [ONLYOFFICE/DocumentServer#1242]
Hello ： I am a newer to onlyoffice 。I installed the latest version for document server and commutity server 。
and when i open a doc ，but in the begin  ，i don‘t open the page of contents ：

![image](https://user-images.githubusercontent.com/2666836/115830963-8f5e0600-a443-11eb-96da-4f9bddd6bfd1.png)

**Did this work in previous versions of DocumentServer?  6.0**

**DocumentServer version: 6.0

**Operating System: window server 2012 sp2

**Browser version:** chrome80

**Comment by ShockwaveNN** [comment]
> **DocumentServer version: 6.0

Hi, I need you to recheck this issue on latest stable version - 6.2.2

**Comment by zhzg605** [comment]
Ok ,I just to check and reinstall the latest stable version 
Thanks!

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
