### ISSUE TITLE
Impect of Removal of Redis from community Version on Load Balancing.

### ISSUE THREAD

**Issue by meetdhawalpatel** [ONLYOFFICE/DocumentServer#1245]
In the Earlier version (<5.5), The load balancing of the Document Server was achieved by
 - Centralising Redis, RabbitMq, Postgres, and FileStorage(For App-data)
 - Running Multiple Document Server behind load balance, and every instance was connecting to the same Redis, RabbitMq Postgres, and FileStorage

From version 5.5 onward, since Redis is removed and an in-memory cache is used to store the data. Will this result in not supporting the above scenario. If yes, then is there any other way to support load balancing with new versions.

**Comment by ShockwaveNN** [comment]
I think I don't have qualification to answer this question

Redis is still supported in commercial version, and in free version we got limit of 20 simular connection, so I don't think you need to use load balancer for 20 connection?

**Comment by meetdhawalpatel** [comment]
For 20 connection Load Balancing is required but the same setup can be used for High Availability.

**Comment by ShockwaveNN** [comment]
Again, I'm not sure, but is there will be real troubles in HA with two different in-memory cache?

If you got any particular bugs I will be glad if you provide some simple docker-compose file with reproducable scenario

**Comment by meetdhawalpatel** [comment]
Sorry if I am posting this at the wrong place. But it was a query and not an issue exactly.

I am going to upgrade from 5.4 to 6.x version soon, and the setup was done in the HA mode. So I wanted to know will the removal of Redis will impact the HA?

**Comment by ShockwaveNN** [comment]
> the setup was done in the HA mode

Could you point out instruction which you've used?

I don't think anyone tried to setup HA for open-source version before

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
