### ISSUE TITLE
Impossible to filter sheet per user in strict mode

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#1246]
**Do you want to request a *feature* or report a *bug*?**

**BUG**

**What is the current behavior?**

In Strict Mode, just one user can use filter

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) Create a sheet with some filters
2) User A filters some rows and sees the rows filtered
3) User B cannot use the filter (does nothing)

**What is the expected behavior?**

User B can define it's own filter

**Did this work in previous versions of DocumentServer?**

NO

**DocumentServer version:**

6.2

**Operating System:**

ALL

**Browser version:**

ALL

**Comment by Rita-Bubnova** [comment]
Hello, @cpot.
This is correct work in strict co-editing mode of the XLSX file.
I think you can try using sheet views. More details [here](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/UsageInstructions/SheetView.aspx).

**Comment by cpot** [comment]
Hello @Rita-Bubnova,

Thank you for your quick reply. I will give your advice about sheet views to our customer in our forum https://community.ceo-vision.com/topic/499/excel-in-onlyoffice-filtering-and-coediting

I will also tell them that it is in the paid version

Thank again

**Comment by Rita-Bubnova** [comment]
> PS: However, there is still a bug, the filter should be 'greyed'

I agree with you.
Could you create separate issue?

**Comment by cpot** [comment]
@Rita-Bubnova i will try if i can find some time, have a good day

**Comment by Rita-Bubnova** [comment]
> PS: However, there is still a bug, the filter should be 'greyed'

I created issue 50584 in our private issue tracker. 

I think, we can close the original issue?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
