### ISSUE TITLE
The Sheet is locked

### ISSUE THREAD

**Issue by huisnotacouncillor** [ONLYOFFICE/DocumentServer#1247]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Sheet is locked，you cannot modify any information

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1.Insert a formula into a cell, for example, the sum formula
2.Delete formula name character by character
3.Error messages can be seen in the browser developer tools
4.Continue to delete the equal sign，You will find that the sheet is locked，you cannot modify any information

Here are the screenshot
![image](https://user-images.githubusercontent.com/45624731/116543148-16b5e880-a920-11eb-87bd-04477663f708.png)
![image](https://user-images.githubusercontent.com/45624731/116543473-7dd39d00-a920-11eb-81ae-6ad96c4dfe8c.png)

**What is the expected behavior?**
The sheet can be edited normally

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
6.2.2-21

**Operating System:**
Windows

**Browser version:**
Latest Chrome

**Comment by Rita-Bubnova** [comment]
Hello, @huisnotacouncillor.
I can confirm - this is know issue 49249 in our private issue tracker. 
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/1cd95eb1167b21ca333e241ae1d5d66dc5e3e451) in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.3.0 is released. This problem should be fixed
