### ISSUE TITLE
[Feature] Physical world interface for scanned docs - file name vs. displayed name

### ISSUE THREAD

**Issue by cnbhl** [ONLYOFFICE/DocumentServer#1249]
**Do you want to request a *feature* or report a *bug*?**
_Feature request_

First of all I really appreciate the work, you folks been doing on ONLYOFFICE. Thanks for that. I will shortly describe a used workflow, that I think could be useful for every user.

When dealing with scanned pdf files (e.g. old non digitalised documents, signed contracts, invoices ...) I scan these documents with an UUID as file name (e.g. dee0fa25-39ba-4add-9661-6574fc47793d.pdf coming form a barcode lable on document).

The benefit of doing it that way is, the physical document is uniquely identified and when I rescan the document (e.g. second signature), resp. upload it a second time, onlyoffice will notice the new version of an already existing file (the upload option "replace same filename", what is a very nice feature).

The disadvantage is, that I have non human readable filenames.  If I change the filename the recognition of a new version is not working any more.

The same behaviour - documents leaving ONLYOFFICE and comming back - could be applied for digital documents. So a unique identifier placed inside the file itself would be a good idea, i think.

**What is the current behavior?**
It is possible to upload pdf files with UUIDs as filename and store them inside ONLYOFFICE. When I change the filename to human readable the benefit of unique identifiers vanish.

**What is the expected behavior?**
It would be perfect to have a phyical/digital interface using UUIDs which are used as filename to identify a document inside ONLYOFFICE. And to have a second let's call it _display name_ stored inside the database that can be changed instead of the file name of the stored document. Maybe both names are displayed.

This way ONLYOFFICE notice the incoming files by the identifier but the user sees a human readable display name.

Attached:
Example file: [doc_7c40160f-7f7f-4ca4-bb4e-376c2c00a49d.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/6406965/doc_7c40160f-7f7f-4ca4-bb4e-376c2c00a49d.pdf)

**Comment by ShockwaveNN** [comment]
> . And to have a second let's call it display name stored inside the database that can be changed instead of the file name of the stored document

To be clear - I think this should not be a feature of DocumentServer itself, since it didn't store any documents, but DMS (document management system)

Am I right and you're using DocumentServer with ONLYOFFICE Community?

**Comment by cnbhl** [comment]
> Am I right and you're using DocumentServer with ONLYOFFICE CommunityServer?

Yes, you're right. So I will close this issue and reopen it at https://github.com/ONLYOFFICE/CommunityServer.
Sorry for the misplacement.
