### ISSUE TITLE
Fail to open powerpoint 2003 (ppt) with password protected?

### ISSUE THREAD

**Issue by agungsijawir** [ONLYOFFICE/DocumentServer#125]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
OnlyOffice Presentation Editor fail to open ppt (office power point 2003) with password protected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 - create simple powerpoint 2003 file, save with password protected
 - upload to onlyoffice 
 - open file
 - Display error message: An error has occurred while opening the file. Press "OK" to return to document list.

**What is the expected behavior?**
 - onlyoffice will ask for document password,
   - if success, document opened
   - if password is wrong, document can not be opened

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
 - DocumentServer v4.3.5
 - Chrome 59, FireFox 53.0.3 64bit
 - OS Linux Ubuntu 14.04 (on server / document server), my desktop is Ubuntu 16.04
 - never tried on previous version, 1st install

Attached sample powerpoint 2003 file (document password: `Abcd1234`, zip are not password protected )

[Sample PowerPoint 2010.ppt.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1073744/Sample.PowerPoint.2010.ppt.zip)

**Comment by SergeyLuzyanin** [comment]
Hello, @agungsijawir . We will fix the problem with protected ppt in the nearest releases.

**Comment by agungsijawir** [comment]
Hi @SergeyLuzyanin, thank you for your reply. Looking forward to nearest releases!
