### ISSUE TITLE
BUG: Unable to edit documents in untranslated laguages

### ISSUE THREAD

**Issue by zilion2000** [ONLYOFFICE/DocumentServer#126]
In my case I cannot edit documents that are written in polish (in my case).

```
tail -f /var/log/onlyoffice/documentserver/nginx.error.log

2017/06/22 07:07:33 [error] 412#0: *273 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/locale/pl.json" failed (2: No such file or directo
ry), client: 172.18.0.4, server: , request: "GET /2017-06-09-10-21/web-apps/apps/documenteditor/main/locale/pl.json HTTP/1.1", host: "192.168.50.132", referrer: "http:
//192.168.50.132/2017-06-09-10-21/web-apps/apps/documenteditor/main/index.html?_dc=2017-06-09-10-21&lang=pl-PL&customer=ONLYOFFICE&frameEditorId=iframeEditor"
```
All is fine when document language is one of corresponding to these files from directory:
/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/locale/

cs.json  
de.json  
en.json  
es.json  
fr.json  
it.json  
ja.json  
lv.json  
pt.json  
ru.json  
sl.json  
tr.json

Why it's impossible to edit documents whose language is unsupported?

**Comment by ShockwaveNN** [comment]
Hi, please tell your OS, documentserver version, standart installation or in docker, and do you use only `documentserver`, or with `onlyoffice-communityserver`

**Comment by zilion2000** [comment]
Hi,
In my case it's onlyoffice-communityserver on docker on ubuntu 16.04

**Comment by ShockwaveNN** [comment]
Yeah, we aware of nginx error, but this should not cause any problems with editing document.
That do you mean by `impossible to edit documents whose language is unsupported`. It show some error in editor?

**Comment by zilion2000** [comment]
I'm attaching document with changed language to pl_PL. 
If you try to edit you will get error like on png:
![onlyoffice sample document1 docx](https://user-images.githubusercontent.com/12670914/27424908-fda30cf4-5736-11e7-92de-18017fdc6cb3.png)

[ONLYOFFICE Sample Document1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1094137/ONLYOFFICE.Sample.Document1.docx)

**Comment by ShockwaveNN** [comment]
Ok, this is pretty strange and not normal.
Tell me your `onlyoffice-documentserver` docker image version, `onlyoffice-communityserver` docker image version and how they configure, do they placed on different host or how

**Comment by zilion2000** [comment]
All images are on same host.

installed with this commands:
```
docker network create --driver bridge onlyoffice

sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-document-server \
	-v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data \
	-v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice \
	onlyoffice/documentserver

sudo docker run --net onlyoffice --privileged -i -t -d --restart=always --name onlyoffice-mail-server \
	-p 25:25 -p 143:143 -p 587:587 \
	-v /app/onlyoffice/MailServer/data:/var/vmail \
	-v /app/onlyoffice/MailServer/data/certs:/etc/pki/tls/mailserver \
	-v /app/onlyoffice/MailServer/logs:/var/log \
	-v /app/onlyoffice/MailServer/mysql:/var/lib/mysql \
	-h yourdomain.com \
	onlyoffice/mailserver

sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-community-server \
	-p 80:80 -p 5222:5222 -p 443:443 \
	-v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
	-v /app/onlyoffice/CommunityServer/mysql:/var/lib/mysql \
	-v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
	-v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServerData \
	-e DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server \
	-e MAIL_SERVER_DB_HOST=onlyoffice-mail-server \
	onlyoffice/communityserver
```

onlyoffice.community.release-date: 20170504
onlyoffice.community.version: 9.0.0.300

I don't know how to find version of  **onlyoffice-documentserver**, but I've found this:
Created 	2017-06-09 12:31:43
Build 	Docker 1.13.0 on linux, amd64

**Comment by ShockwaveNN** [comment]
I cannot reproduce a problem
1. I run container infrastructure like in your commands.
2. Login to community and change portal language to Poland
3. Create new document and enter some data.
4. Close document and open it again - data present, not error.
Is your steps are the same?

**Comment by zilion2000** [comment]
After your last reply I've checked again, and miraculously it's worked.
I reinstalled all fresh and it's still working fine.
I don't know what happened...

Thank  you for your time!
