### ISSUE TITLE
XML spreadsheet 2003 looks different in Onlyoffice 6.3.0 and MS office

### ISSUE THREAD

**Issue by kirillFedorov1** [ONLYOFFICE/DocumentServer#1260]
Compare to MS office, in Openoffice 6.3.0 sometimes empty cells are missed, and sometimes there are extra empty cells. Also, all cells are wider than in MS office.
[ZWWW_SAMPLE_INVOICE_XML_EXCEL.xls](https://github.com/ONLYOFFICE/DocumentServer/files/6465627/ZWWW_SAMPLE_INVOICE_XML_EXCEL.xls)
![Безымянный123](https://user-images.githubusercontent.com/50590149/117963086-a1d3ad00-b328-11eb-9d62-869f9745ff11.png)

**Comment by Rita-Bubnova** [comment]
Hello, @kirillFedorov1.
Thank you for report.
I created new issue 50409 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/core/commit/6414a49ae154cc794c97a1ab0c0aa02d92290a7f) in version 6.3.1.
