### ISSUE TITLE
Download failed or An error has occurred while opening the file.

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/DocumentServer#1263]
I did run DocumentServer in local enviroment on my windows 10 successfully.But i got an error yesterday.Here it is:
when i use ip:port to access it ,i always got this kind of warning:

An error has occurred while opening the file.

{errorCode: -82, errorDescription: "An error has occurred while opening the file."}
ConvertUnknownFormat

when i use localhost:port to access it ,i got another one:

Download failed
{errorCode: -4, errorDescription: "Download failed."}

my part of configs is here:
Common\..\default.json no changes
nodejs\..\default.json no changes
nodejs\..\development-windows.json:
{
  "server": {
    "port": 80,
    "siteUrl": "http://127.0.0.1:8001/",
    "apiUrl": "web-apps/apps/api/documents/api.js",
    "preloaderUrl": "web-apps/apps/api/documents/cache-scripts.html"
  }
}
Common\..\development-windows.json:
"services": {
    "CoAuthoring": {
      "server": {
        "host": "192.168.30.114",
        "port": 8001,
        "static_content": {
          "/fonts": {
            "path": "../../../fonts"
          },
          "/sdkjs": {
            "path": "../../../sdkjs"
          },
          "/web-apps": {
            "path": "../../../web-apps"
          },
          "/sdkjs-plugins": {
            "path": "../../../sdkjs-plugins"
          }
        }
      },
      "utils": {
        "utils_common_fontdir": "C:\\Windows\\Fonts"
      },
     
      "editor": {
        "spellcheckerUrl": "http://127.0.0.1:8080"
      },
      "sockjs": {
        "sockjs_url": "/web-apps/vendor/sockjs/sockjs.min.js"
      }
    }
  }

any idea for me?thx a lot.

**Comment by ShockwaveNN** [comment]
Not sure that about Windows, but on Ubuntu this is symptoms of firewall problem

> when i use localhost:port

This will not work 100%, you should always use your local ip (or external ip) to access DocumentServer

**Comment by alfabeto2019** [comment]
> Not sure that about Windows, but on Ubuntu this is symptoms of firewall problem
> 
> > when i use localhost:port
> 
> This will not work 100%, you should always use your local ip (or external ip) to access DocumentServer

i both ran successfully on Ubuntu or windows10,and i both close the firewall .But this often happens on windows10 .Dont know the reason.

**Comment by ShockwaveNN** [comment]
If this windows10 problem only maybe @DenisDeeSign can help you, I'm personally no good at windows systems

**Comment by alfabeto2019** [comment]
> If this windows10 problem only maybe @DenisDeeSign can help you, I'm personally no good at windows systems

its very kind of u.thx very much.;)
