### ISSUE TITLE
how to reduce some fonts on ubuntu?

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/DocumentServer#1264]
every time i built programs on ubuntu,it always wasted a lot of time to generate fonts,is that sufficient that i just remove some fonts    which r under folder /usr/share/fonts/ ?

**Comment by ShockwaveNN** [comment]
I think yes, you can remove fonts from '/usr/share/fonts'

Also for Docker variant of DocumentServer we got [`GENERATE_FONTS` key](https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters) to disable font generation on each restart
