### ISSUE TITLE
Content not updated if anonymous editor doen't have the right to edit (nextcloud)

### ISSUE THREAD

**Issue by socialize-IT** [ONLYOFFICE/DocumentServer#1269]
Using Document Server 6.2.2 and the nextcloud OO app 7.0.2 the content of an opened file is not updated as long as the anonymous user doen't have the right to write in the file. If another user is changing the document I would linke to see the changes also in the view of the anonymous user. This works if you have the right to edit the shared file.

**Comment by DenisDeeSign** [comment]
Moving this issue to DocumentServer repo, since it is not related to Nextcloud.

**Comment by DenisDeeSign** [comment]
Duplicate #552.
