### ISSUE TITLE
how to transmit my custom datas into editor

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/DocumentServer#1270]
Is there any way to transmit datas?

**Comment by ShockwaveNN** [comment]
Hi, could you explain in more details what do you want? Maybe some self-written plugin/macros? See documentation [here](https://api.onlyoffice.com/plugin/basic)

**Comment by alfabeto2019** [comment]
> Hi, could you explain in more details what do you want? Maybe some self-written plugin/macros? See documentation [here](https://api.onlyoffice.com/plugin/basic)

I have read documentation about plugins part.Maybe not quite suit my case.For example,i want to click my custom button to save docs rather than on the cornor one,what should i do?Any idea for me?Thx

**Comment by ShockwaveNN** [comment]
Sorry I do not understand you, could you explain what you need in more details and why you need that?
Why you need custom button instead of some "cornor one"

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
