### ISSUE TITLE
Ctrl+I does not reliably toggle italics in equation editor

### ISSUE THREAD

**Issue by kbauer** [ONLYOFFICE/DocumentServer#1273]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When in the equation editor, the "italics" state is inconsistent, causing confusing behavior when trying to produce upright letters.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Insert new equation
2. Type `Hello<Ctrl+I>Wide<Ctrl+I>World`

**Expected Output:** <i>Hello</i>Wide<i>World</i>
**Actual Output:** <i>HelloWide</i>World

Closer to an actual use-case:

**Input:** `V_<Ctrl+I>ext <Ctrl+I>(r) `
**Expeced Output:** <i>V</i><sub>ext</sub>(<i>r</i>)
**Actual Output:** <i>V<sub>ext</sub>(r)</i>

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

ONLYOFFICE Desktop Editors version 6.2.0.148

**Comment by TatianaKirillova** [comment]
Hello, @kbauer !
The problem has been fixed by [this commit ](https://github.com/ONLYOFFICE/sdkjs/commit/8193ea5b36924630cd04a14ad7e8fb381c55f170
)and will be included in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
