### ISSUE TITLE
Documentserver 6.3.0 spellchecking shared worker not running on Raspbian 10 Chromium

### ISSUE THREAD

**Issue by kruthoff** [ONLYOFFICE/DocumentServer#1275]
**Do you want to request a *feature* or report a *bug*?**
Feature/Bug?
**What is the current behavior?**
The spellchecker is not spellchecking.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I've upgraded from 6.2 to 6.3. The CHANGELOG states that "Spellchecker implemented as SharedWorker. No more back-end service for spellchecker". That's ok. Spellchecker is not starting anymore, but it doesn't spellcheck :-(
**What is the expected behavior?**
Check spelling in Test documents.
**Did this work in previous versions of DocumentServer?**
Yes, 6.2 was ok.
**DocumentServer version:**
6.3.0
**Operating System:**
Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
**Browser version:**
Chromium Version 88.0.4324.187 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

It works in Firefox on a x86 Linux system. What's a "Shared Worker"? Does it work on arm? How can I make it work? Any help is much appreciated!

**Comment by ShockwaveNN** [comment]
> What's a "Shared Worker"

https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker

I'm not familiar with this technology myself, but you can see them by opening `chrome://inspect/#workers` in chrome

> Does it work on arm?

I do not know, but since we do not support ARM officially - we cannot guarantee that it will work at all

**Comment by kruthoff** [comment]
Ok, I see a single worker in the devtools: github-socket-worker-v2-43xxxxxxx
Nothing related to OnlyOffice unfortunately.

**Comment by ShockwaveNN** [comment]
I have no idea that may be a reason, so I think until we start officially [support ARM](https://github.com/ONLYOFFICE/DocumentServer/issues/152) you should stay on v6.2.0

**Comment by kruthoff** [comment]
Somehow a pity to have this platform dependency, as the app is running in my web browser. I don't need the server on ARM. This is another topic, right? My web browser runs on ARM.

**Comment by ShockwaveNN** [comment]
@kruthoff Hm, maybe I'm understand you wrong

Are you saying you're using x86 document server and opening DocumentServer using Chrome on arm and got problems with spellcheker?

**Comment by kruthoff** [comment]
Correct.

**Comment by ShockwaveNN** [comment]
@kruthoff Ok, I think there may be a problem, I'll try to find raspbian and reproducce

In the meantime could you install firefox on Rasbian and check for spellchecker?

**Comment by kruthoff** [comment]
Spellchecker on Firefox 78.10.0esr (32-bit) works!

**Comment by ShockwaveNN** [comment]
So I got Raspberry PI 3 with latest raspbian and I checked:

Firefox esr 78.10 - spell check works
Chromium 88 - spell check works

So maybe you've configured your chromium in some way? Maybe some optimization to reduce memory footprint? 
I've just installed chromium on almost clean system (it's my personal raspberry and there is only media-center `kodi` was installed)

Can you try to purge chromium and install it again and see for result?

**Comment by kruthoff** [comment]
You're right. It's my linux account.
I've tried with another account and it worked as expected. I don't know but even after I've reset my chromium settings, it didn't help. I'll purge my .config/chromium and will retry.
