### ISSUE TITLE
OnlyOffice Docs - files returning broken after edit

### ISSUE THREAD

**Issue by afterlogic-support** [ONLYOFFICE/DocumentServer#1277]
We're working on integration of our product with OnlyOffice Docs. Upon editing and saving a file, occasionally we get "Choose TXT option" prompt when trying to edit the same file again. Usually it occurs after making small changes to the file.

* [file-sample_100kB_good.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6538894/file-sample_100kB_good.docx) - is the file after the first edit with OnlyOffice Docs, and it opens for editing just fine
* [file-sample_100kB_bad.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6538897/file-sample_100kB_bad.docx) - it's the file after the 2nd edit, we get "Choose TXT option" message when trying to edit it again

We're not retrieving the file immediately after it was saved, but rather, once OnlyOffice Docs returns the file to our application via callback, then we're getting it - and it comes broken from OnlyOffice Docs.

We'd appreciate any pointers on why this could happen. It's particularly disturbing that the file retains its length in bytes after editing yet it cannot be open. Maybe, there are some settings which could affect the behavior?

DocumentServer version: 6.2.2-21
Operating System: Debian 10

**Comment by ShockwaveNN** [comment]
Is there any errors in logs in `/var/log/onlyoffice/documentserver`?

**Comment by afterlogic-support** [comment]
[nginx.error.log](https://github.com/ONLYOFFICE/DocumentServer/files/6539288/nginx.error.log) file only contains a few records, not sure how relevant these are, attaching the file. 
It's the only error log file recorded today.

**Comment by ShockwaveNN** [comment]
I don't think those entries are relevant

Trt to look not only `*.error.log` file but to `out` files too - we write only critical error in `error` file, but some problem may be in other logs too, usually with some stack trace

**Comment by afterlogic-support** [comment]
We've checked all the files under `/var/log/onlyoffice/documentserver` and subdirectories but the only other file generated today is `metrics/out.log` and that one doesn't contain any errors.

**Comment by ShockwaveNN** [comment]
Are you saying there is no other log files at all? Or other logs file without any intersting info?

**Comment by afterlogic-support** [comment]
No other logs recorded today at all, the previous log files there are over 1 week old.

**Comment by ShockwaveNN** [comment]
Ok, currently I have no idea why this happens, seems maybe some kind of network error while sending file from DocumentServer to your storage

Several idea I had
1. bad file is broken on zip level
```
unzip file-sample_100kB_bad.docx 
Archive:  file-sample_100kB_bad.docx
error [file-sample_100kB_bad.docx]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```
Never seen anything like this, if there is no errors in log files - I can think only about network level
So "Choose TXT option" is just a symptom that file is completely broken, in that case we cannot detect it type and thinking that it's just a hard-to-read txt

2. I'm not 100% sure that DocumentServer is working correct on your system - could you try to start integrated example (instruction located at http://documentserverurl/welcome, after that open  http://documentserverurl/example and try to reproduce same results)

**Comment by afterlogic-support** [comment]
Thank you, that really helped a lot. We have checked this with the integrated example, the issue wasn't occurring there. So we have narrowed the issue down and turned out the issue was in our code, not on DocumentServer side.

Thanks again!

**Comment by ShockwaveNN** [comment]
@afterlogic-support Glad to hear that, you're welcome
