### ISSUE TITLE
Spreadsheets: Copy & Rename breaks charts

### ISSUE THREAD

**Issue by aknobloch** [ONLYOFFICE/DocumentServer#1283]
**Do you want to request a *feature* or report a *bug*?**
Bug report. This is a regression from previous versions, although I'm not sure which version it was working on. It broke sometime after April 1st, 2021.

**What is the current behavior?**
Copying a sheet tab which contains a chart, and then renaming the copy, breaks the chart references.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Prerequisite: Have a spreadsheet page, "Original" which contains a chart with references to the current page. 

See example: https://i.imgur.com/Pwi7wt4.png

Steps to reproduce:

1. Right click the "Original" tab and then "Copy"
2. Select "(Copy to End)"
3. Observe that tab is named "Original (2)" and the chart references on the tab are now pointing towards "Original (2)". Example here: https://i.imgur.com/eJL5R0H.png
4. Rename the tab from "Original (2)" to "Copied Sheet"
5. Observe that the chart now breaks. Example here: https://i.imgur.com/FtNn6sO.png

**What is the expected behavior?**
References to tab names should be updated when the name is changed.

**Did this work in previous versions of DocumentServer?**
Yes.

**DocumentServer version:**
6.3.0.111

**Operating System:**
UI in Nextcloud, Document Server on Ubuntu 20.04

**Browser version:**
Firefox 89.0 (64-bit)

**Comment by SergeyLuzyanin** [comment]
Hello @aknobloch. Thank you for your report. I can confirm that this is a bag. It will be fixed in version 6.3.1.

**Comment by SergeyLuzyanin** [comment]
[https://github.com/ONLYOFFICE/sdkjs/commit/606434c7f5b135e68dd99b0dd91c3fdc69ae718e](url)

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
