### ISSUE TITLE
Brave - In any doc type can not select font type since update to 6.3.0

### ISSUE THREAD

**Issue by markareait** [ONLYOFFICE/DocumentServer#1284]
Bug - In any doc type can not select font type

Documents Server 6.3.0

Worked on earlier version of Doc server

Brave web browser (latest ver) - Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit) - Site protection off (or on)

Works in Chrome

Noticed this different from Chrome in dev console -

Failed to load resource: the server responded with a status of 404 ()                  fonts_thumbnail@1.5x.png:1

**Comment by TatianaKirillova** [comment]
Hello, **@markareait**
Thanks for your request!
I could not replicate your problem. I have checked it on OS Win10, in Brave browser version 1. 25.70.
Can you refresh your browser and check if your problem persists? 
If the problem persists in the new version of the browser, please send a video about it. And specify your OS.
