### ISSUE TITLE
Where is the source code of allfontsgen?

### ISSUE THREAD

**Issue by niushuai1991** [ONLYOFFICE/DocumentServer#1287]
I didn't find it.
Pleace tell me, Thanks.

**Comment by ShockwaveNN** [comment]
Just a simple search shown me this:
https://github.com/ONLYOFFICE/core/blob/master/DesktopEditor/AllFontsGen/AllFontsGen.pro#L14

**Comment by niushuai1991** [comment]
OK, Thanks for your help.
