### ISSUE TITLE
What's Editor.bin used for?

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/DocumentServer#1290]
When i tried to opan a docx file,I saw a request url like this:https://ip:port/cache/files/Y2lwLXRlc3QvMjAyMS8wNi8wNy8wZDlkZjU5NDRjMzc0OWNmOTVkYy5kb2N4/Editor.bin/Editor.bin?md5=eD0d31nGu9UzDMUFBKRjqg&expires=1625642157&disposition=attachment&filename=Editor.bin
What's Editor.bin used for？Thanks.

**Comment by ShockwaveNN** [comment]
It's whole document you've trying to open, convert to our own internal format

**Comment by alfabeto2019** [comment]
> It's whole document you've trying to open, convert to our own internal format

So it was stored in onlyoffice server side,r8?Need i delete these temp files daily?

**Comment by ShockwaveNN** [comment]
> So it was stored in onlyoffice server side

It's not stored as I'm aware, it's converted on a runtime

> Need i delete these temp files daily?

No, there is no need

**Comment by alfabeto2019** [comment]
> No, there is no need
Can i edit the storage part of default.json to store my docs ouside on my own server?

**Comment by alfabeto2019** [comment]
Then can i config the "storage" part of default.json to store my docs ouside on my own server?

**Comment by alfabeto2019** [comment]
> > Then can i config the "storage" part of default.json to store my docs ouside on my own server?
> 
> Not sure, maybe by utilizing some kind of nfs server and linux mounts
> 
> What's your endgame here? I think that storing storage on other server has negative impact on performance

I  need to get original docs every time for other uses,so here .bin,the internal format files may not suit me.And i dont want to invoke the “save file ”s api you provided every time.But what is the part of "storage" in default.json  used for?Any idea for me?Molto Gracie~

**Comment by ShockwaveNN** [comment]
> But what is the part of "storage" in default.json used for?

I may be not 100% right, but I think it's for caching use only

> And i dont want to invoke the “save file ”s api you provided every time

You can take a look at `forcesave` option for integration, I don't fully understand your case, but somehow it may suite here
It described [here](https://api.onlyoffice.com/editors/config/editor/customization#forcesave).

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
