### ISSUE TITLE
Images in docx files are not printed, saved pdfs are not printable.

### ISSUE THREAD

**Issue by w202mg** [ONLYOFFICE/DocumentServer#1291]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
While printing from Nextcloud no images in docx are printed, doesn't matter if created in Nextcloud or in MS Office and than uploaded. Saved pdf can not be opened and pictures are shown but the print out is without the images.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a docx file, insert an image, print. Or: open a docx file, insert an image, save as pdf, print.

**What is the expected behavior?**
Documents shall show the inserted images.

**Did this work in previous versions of DocumentServer?**
I had only one version till now.

**DocumentServer version:**
6.3.0

**Operating System:**
Linux mint

**Browser version:**
Chrome, Firefox

**Comment by ShockwaveNN** [comment]
@w202mg Hi, we were unable to reproduce your problem

Just to be sure - could you try to reproduce it not via integration with nextcloud, but by using integration test example - you can see instruction how to start it via visiting `http://docserver_url/` and after service start it will be accessible on `http://docserver_url/example`

**Comment by w202mg** [comment]
> @w202mg Hi, we were unable to reproduce your problem
> 
> Just to be sure - could you try to reproduce it not via integration with nextcloud, but by using integration test example - you can see instruction how to start it via visiting `http://docserver_url/` and after service start it will be accessible on `http://docserver_url/example`

I tried this but at the moment I have some issue with tokens, so for now I can't open any dox using the test page. At the moment looking for solution. After solved I'll try.

**Comment by w202mg** [comment]
OK, so now the exemple server is running. I was able to print images using the example server that I started in Firefox and Chrome on my server running Linux Mint.

Back to my windows PC:
Chrome is not printing files are having only image inside, no text. If I add text it prints only text. If I print to pdf and then printing the pdf, it prints including images. In the beginning I had an error by printing the pdf with images (no print possible).
Firefox is just offering to open the file as pdf or to save it as pdf, when I open as pdf the file is printed incl. images.

I reinstalled the printer, empty the cash of Chrome, restarted the PC...

**Comment by ShockwaveNN** [comment]
So to be clear - using DocumentServer example page all files are printed correctly

But using same DocumentServer with Nextcloud only part of files are printed correctly?

Maybe there is some kind proxy or complicated network setup between them and some data (not sure how) is filtered out?

**Comment by w202mg** [comment]
If use my server computer running Linux Mint all is printed well both in NC and in test server.
On my windows PC:
1. using Chrome in test server and in NC no print if only image, if image+text print but without image (only text). If printing to pdf file and saving print is possible if the file is very simple (like only one image), if the file a bit more complicated no print+error message
2. using Firefox is possible only to save as pdf or open as pdf

**Comment by ShockwaveNN** [comment]
This is strange

1. Could you record a video of first case on your windows PC using test examaple. We are now completly ignore NC, since I don't think problem related to NC if it happens on test example also. Also - do you open resulting pdf in chrome or any other software

2. Could you try another windows pc and see if result same?

3. On your Linux Mint server - are you using localhost to access it or same ip/network name as on windows?

**Comment by w202mg** [comment]
here are 3 videos from test server. After the error in the first video I had to restart Chrome. 3rd video is Firefox
1. https://youtu.be/sdpkWDme9Bs
2. https://youtu.be/9SSYWtGMNnI
3. https://youtu.be/-44C3B0Zgoc

Unfortunately I do not have access to any other windows PC to test it.
The server and windows PC are in the same network, same LAN printer.

**Comment by ShockwaveNN** [comment]
So am I right in all cases pdf file in result are correct one, with both text and image, but when you print those pdf via default pdf viewer - there is lost data on real paper? If so I only can think about some problems in printer's driver, since those PDF files are look good in PDF viewer

**Comment by w202mg** [comment]
Not really. Let's see:
Video 1: Testserver. Windows. Chrome.
1. File only with a picture- no print action at all (no print task but printer sign is appearing).
2. Typing some random text in addition to the image- printing is running, but no image on paper.
3. Trying to print again- error, restarting Chrome.

Video 2. Test server. Windows. Chrome after restarting
1. save as pdf the file with image+text.
2. try to print- error in Adobe Acrobat
3. delete text, save as pdf file. open in Acrobat, printed with image

Video 3. Test server. Windows. Firefox. Can only save or open as pdf.

Just tested, all saved pdf files are printable if I open them in a browser (Chrome+Firefox) but not if opened in Acrobat (only very simple files are printable).

Before I worked with the same files from MS Office daily, printing, sending, no problems at all.

**Comment by w202mg** [comment]
What I see also is that in Firefox the headers section is damaged. Maybe it is related somehow. Both in test server as well as in NC.
![2021-06-09 08_43_38-Window](https://user-images.githubusercontent.com/84856053/121306385-0faace80-c8ff-11eb-81de-bd108b7b394a.png)

**Comment by ShockwaveNN** [comment]
> Just tested, all saved pdf files are printable if I open them in a browser (Chrome+Firefox) but not if opened in Acrobat (only very simple files are printable).

This is strange, I really think there is some kind of problem in Acrobat, are you using the latest version? Maybe contact it's support with note that some file are printed from chrome fine, but not from Acrobat

> What I see also is that in Firefox the headers section is damaged.

This is not right, are this problem only for Firefox with damage ParagraphStyles or for Chrome on same PC also?
This may (and may not) related to some problem with Font\Theme generation on DocumentServer installation, but I've never saw a problem like this

**Comment by w202mg** [comment]
> > Just tested, all saved pdf files are printable if I open them in a browser (Chrome+Firefox) but not if opened in Acrobat (only very simple files are printable).
> 
> This is strange, I really think there is some kind of problem in Acrobat, are you using the latest version? Maybe contact it's support with note that some file are printed from chrome fine, but not from Acrobat

The version is not the latest but I use it really hardcore every day in all possible ways and there ar eno issues at all.

> > What I see also is that in Firefox the headers section is damaged.
> 
> This is not right, are this problem only for Firefox with damage ParagraphStyles or for Chrome on same PC also?

Only on the windows PC in Firefox. Chrome is working properly (besides of the print function)

**Comment by ShockwaveNN** [comment]
> The version is not the latest but I use it really hardcore every day in all possible ways and there ar eno issues at all.

I've never used Acrobat, but I think this may be an issue just in some minor way

> Only on the windows PC in Firefox, on Mint server in Firefox ithis issue does not appear.

In that case I don't think this is our problem, maybe some drivers on Firefox+Windows combination

I'm almost out of ideas, only advices left - found out another PC\another printer and try to reproduce, because

**Comment by w202mg** [comment]
OK, I was able to fix this. I played around with the printer drivers and finally it worked. Still very stramge to me because in all other possible situations it worked perfectly and I never had to touch the drivers. Bit OK, now it's done.

How about the firefox issue? Shall I open a new issue for it?

**Comment by ShockwaveNN** [comment]
> I played around with the printer drivers and finally it worked. 

Glad to hear, because I was out of ideas )

> How about the Firefox issue (header section)? Shall I open a new issue for it?

Yes, I think you should, but I've never seen a error like this and only in firefox, maybe it's some graphical glitch in drivers or something like this, I'm almost sure this is not an issue from our side, but creating new issue to try to figure out details is no harm

**Comment by w202mg** [comment]
I updated the intel inf package on windows PC and rebooted, the issue in Firefox is away now. But the local.json in the test server folder was changed back for some reason and the token was switched off... enabled again and it works.

Thanks for your help!

**Comment by ShockwaveNN** [comment]
@w202mg You're welcome, glad to help
