### ISSUE TITLE
What do the numbers in the array of ParaRun Lines mean ?

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/DocumentServer#1292]
![image](https://user-images.githubusercontent.com/6262739/121013604-9fe7f700-c7cb-11eb-8be3-866954f1b795.png)

I think these annotation has some problem. If this paragraph has two paragraphs, it should be [2, 0 , 2, 0 , 15, 15, 17]. If this paragraph has three paragraphs, it should be [2, 0 , 2, 4, 0, 10, 10, 15, 15, 17].  I think there are three components to this data，the  first is  line, the second I don't know what is it, the third is startpos and endpos. Please help me explain it, thanks!

**Comment by Malenconiaprincep** [comment]
Thank you very much for your answer

**Comment by ShockwaveNN** [comment]
@Malenconiaprincep You're welcome. I'll close this issue but if you got any question - feel free to start a new one
