### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by kztao** [ONLYOFFICE/DocumentServer#1294]
![image](https://user-images.githubusercontent.com/1481448/121286665-be0c3f00-c912-11eb-8d1c-0c499b9cceb6.png)

**Comment by ShockwaveNN** [comment]
I see you've using pretty old version 5.5.3 of DocumentServer, could you update to latest v6.3.1 and see if problem is persists.

If so - we need some kind of scenario, never saw a error like this

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
