### ISSUE TITLE
When I copy both the image and the text in Word, and paste it into Word in OnlyOffice's online preview, I get an error:

### ISSUE THREAD

**Issue by baoyuping** [ONLYOFFICE/DocumentServer#1295]
When I copy both the image and the text in Word, and paste it into Word in OnlyOffice's online preview, I get an error:Not allowed to load local resource: file:///C:/Users/*/AppData/Local/Temp/ksohtml20156/wps4.jpg

like this:

![ecbc7f00-ae10-42b1-968f-234e6f1e6af4](https://user-images.githubusercontent.com/75818314/121287441-20197400-c914-11eb-98e0-490cad4d048e.png)

**Comment by ShockwaveNN** [comment]
@TatianaKirillova please take a look

**Comment by TatianaKirillova** [comment]
Hello, **@baoyuping**
Thanks for your request!
I can confirm that the problem exists. I created ticket 50803 in our private  tracker with your issue.

Problem reproduces in Document Server.

**Comment by Rita-Bubnova** [comment]
I think, this is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1069.

**Comment by ShockwaveNN** [comment]
@Rita-Bubnova Yeah, I think you're right, in that case I'll close it
