### ISSUE TITLE
Consultation of document-server-proxy

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1296]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I know that you provide an existing proxy configuration solution:
https://github.com/ONLYOFFICE/document-server-proxy

But if I want to implement document-server-proxy from the firewall level, I need to know exactly what port list the proxy document-server needs to expose

I don’t know if you can understand what I mean by asking, or put it another way, if I want to proxy the document-server through a machine and it is not in the proxy solution provided by you, what port do I need to listen to and what should I pay attention to? 

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
I think 80/443 port and maybe 8000 port is enought, I'm not 100% sure

And maybe some info [here](https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx) will be usefull for you, but I'm not sure that it's 100% actual

**Comment by nobt854** [comment]
Can you confirm the list of ports that need to be monitored? According to the NGINX configuration you provided([here](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-https-to-http.conf)), we don't need to care about other ports except the port of the service itself. But can we ask anyone to confirm this?

**Comment by ShockwaveNN** [comment]
@nobt854 I think it's better to `try to`, I don't think I can confirm anything

**Comment by ShockwaveNN** [comment]
I'll found [this page](https://helpcenter.onlyoffice.com/installation/docs-community-open-ports.aspx) in documentation, this may help

Please notice that currently there is no need for spellchecker port, we'll update this page soon

**Comment by nobt854** [comment]
thank you,you can close this issues.
