### ISSUE TITLE
the file size exceeds the limitation set for your server

### ISSUE THREAD

**Issue by luckycloud-GmbH** [ONLYOFFICE/DocumentServer#1299]
**Do you want to request a *feature* or report a *bug*?**
Bug

**DocumentServer version:**
6.2.2
**Operating System:**
Linux / Debian
**Browser version:**
Firefox

Hi,

i can't open a 180MB XLSX with OnlyOffice.
I have already increased the limits as described in the following issues.
However, I still get the same error

https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/354

**Comment by luckycloud-GmbH** [comment]
this is a link for my test file
https://wetransfer.com/downloads/3979241b46b147d8b0f926fe6d8c74c820210611174346/45b961

I tried to open it with a seafile server

How can i open it via the integrated test example?

**Comment by ShockwaveNN** [comment]
> How can i open it via the integrated test example?

Open `http://docserverurl/welcome` and execute shown command and integrated example will be avaiable on `http://docserverurl/example`

I've executed steps in [this reply](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/354#issuecomment-824678415) and opened your file successfully
![image](https://user-images.githubusercontent.com/668524/122013961-5d27af80-cdc7-11eb-81ed-2d50df2879be.png)

So check if this works for you

If you can open via test example also - in that case you should contact seafile support. Seafile DocumentServer connector was done not via our team, but via Seafile team and we cannot provide any help to configuring it

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
