### ISSUE TITLE
Problem open archives in nextcloud with share storage ! 

### ISSUE THREAD

**Issue by albama** [ONLYOFFICE/DocumentServer#130]
Error download when trying to open office files inside a shared folder configured with the cifs protocol configured as external storage in nextcloud.
nextcloud last version 
onlyoffice last version 

![image](https://user-images.githubusercontent.com/12208567/27646068-015e3774-5c28-11e7-8bf8-250bf1f7c769.png)

[error onlyoffice_nextcloud.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1109259/error.onlyoffice_nextcloud.docx)
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

**Comment by ShockwaveNN** [comment]
Please duplicate this issue in https://github.com/ONLYOFFICE/onlyoffice-owncloud

**Comment by trofim24** [comment]
cc @LinneyS
