### ISSUE TITLE
Editor.bin loaded from root path

### ISSUE THREAD

**Issue by astachowiak** [ONLYOFFICE/DocumentServer#1301]
**Do you want to request a *feature* or report a *bug*?**
Bug or missing configuration

**What is the current behavior?**
At the moment when a docker version of the document server (at least this I tried) is installed with ingress passing data via path .e.g https://system/onlyoffice/ editor.bin is to be loaded from /cache/files/ instead of /onlyoffice/cache/files. I tried to look for any configuration item but I have not found one that can configure it. Is there a way to configure the onlyoffice documentserver to run properly on a specific path?

**DocumentServer version:**
6.3.1

**Operating System:**
Linux (Docker image)

**Comment by astachowiak** [comment]
I think the issue here is that the URL for the cached data is build directly based on the bucketName. https://github.com/ONLYOFFICE/server/blob/2b151e6dfaae439497eb82aa01b4e23d4d6e643c/Common/config/default.json
There is no way to specify on which path the system runs thus making adjustments to the URLs for the storage.

So the quick solution might be to change the value of the bucketName and prepend it with the path. E.g. instead of having value `cache` it should be then `onlyoffice/cache`. This would work with the docker image and ingress as it does not require any configuration change for the nginx.

The best would be to introduce a new parameter to the configuration e.g. `path-prefix` that would be injected into this URL. That again would only work in case of a ingress / proxy which adds path element as the nginx that serves data is configured separately and does not depend on the docservice configuration.

**Comment by ShockwaveNN** [comment]
Hi

I'm not very good at server configuration, but could you explain why this is a bad thing?

Also I take a look - seems not only Editor.bin loaded from url like `https://doc-server-url/cache/files/__name__&expires=1626337177&disposition=attachment&filename=Editor.bin`, but other files as well, like

`https://doc-server-url/6.3.1-32/web-apps/apps/documenteditor/main/app.js`

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
