### ISSUE TITLE
Import some Microsoft Yahei or Source han serif fonts words in a doc that it show difference from word

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/DocumentServer#1302]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
[思源宋体.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6653874/default.docx)

Import some Microsoft Yahei or Source han serif fonts words in a doc that it show difference from word. I suggest because miss linepitch property. I use Ascent + Descent divide by DocGrid  and get ratio, but msyh and source than serif are not followed this rule

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It's the same as MS-Word

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**
macos
**Browser version:**
91.0

**Comment by ShockwaveNN** [comment]
@TatianaKirillova Please take a look - this may be Duplicate with our other problems with CJK fonts

**Comment by TatianaKirillova** [comment]
Hello, **@Malenconiaprincep**

Thanks for your request!I can confirm - this is know bug, issue 48564 in our private issue tracker.
