### ISSUE TITLE
Some PDF files are previewed with garbled code

### ISSUE THREAD

**Issue by baoyuping** [ONLYOFFICE/DocumentServer#1304]
Some PDF files are previewed with garbled code，like this 
![holderimg_20210618103228](https://user-images.githubusercontent.com/75818314/122497827-9e66cc00-d020-11eb-9330-106f28ee2fbc.png)

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer since it's not CommunityServer issue

@baoyuping Could you state you DocumentServer version, host OS and attach this pdf file?

**Comment by baoyuping** [comment]
Sorry, PDF is a private file and cannot be made public.
DocumentServer Version: 6.3.0,
Operating System: Win10
Browser Version: Google

**Comment by ShockwaveNN** [comment]
@baoyuping In that case we cannot detect this issue correcrlly, maybe you can delete some private data by some 3rd party app?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
