### ISSUE TITLE
Sync forcesave command

### ISSUE THREAD

**Issue by DoctorFTB** [ONLYOFFICE/DocumentServer#1307]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Command forcesave always async cuz variable hardcoded to true
https://github.com/ONLYOFFICE/server/blob/master/DocService/sources/converterservice.js#L176

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-

**What is the expected behavior?**
Async variable can be set to false from body in request 

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
6.2.2 (build:21)

**Operating System:**
-

**Browser version:**
-

Additional info:
Request is sent to `coauthoring/CommandService.ashx`.

**Comment by ShockwaveNN** [comment]
Hi could you explain in more details why forcesave in current form is a bad thing and need to be changed?

**Comment by DoctorFTB** [comment]
Hi.
Current forcesave is not a bad thing, its cool thing.
In my case:
I press my own button which send request to backend (with additional info) and I need save file with forcesave (normal save not working cuz editor is open) and send changed file to another service for handle.

I cant send changed file cuz method forcesave is async so I cant handle full request from frontend.
I need send changed file inside request because task logic.

**Comment by konovalovsergey** [comment]
Hi. Do you mean add parameter and change response to this request?
https://api.onlyoffice.com/editors/command#forcesave
In the browser you can get a link to the actual file through downloadAs method
https://api.onlyoffice.com/editors/methods#downloadAs

**Comment by DoctorFTB** [comment]
Hi.
Yes, I mean add parameter and change response.
I think PR solving my request (if PR incorrect - it can be close).
