### ISSUE TITLE
Editing formula by deleting symbols one by one crashes the file once reached a number starting by comma

### ISSUE THREAD

**Issue by piiskop** [ONLYOFFICE/DocumentServer#1311]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
The file crashes during editing the formula once reached a number starting by comma.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Enter a formula like `=29*1,22+29*1,22/128,21*10,5*1,22`!
2. Replace `+` by `(`!
3. Start deleting symbols one by one starting after `(`!
4. Once you reach the situation `=29*1,22(,22/128,21*10,5*1,22` you see the warning message and the file crashes.

Please see the companion [video](https://youtu.be/-P-f_ZK1k7Q).
**What is the expected behavior?**
While the editing of the formula is still in process, _ONLYOFFICE_ shouldn't validate it and therefore not crash the file. Or it should accept odd situations and inform about them - also without crashing the file.

**Did this work in previous versions of DocumentServer?**
I don't know.

**DocumentServer version:**
6.1.0.83

**Operating System:**
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

**Browser version:**
91.0.4472.114 (Official Build) (64-bit)

**Comment by ShockwaveNN** [comment]
Hi, could you update to latest DocumentServer v6.3.1 and see if problem actual, we may fixed it, v6.1.0 is rather old

**Comment by piiskop** [comment]
I did the upgrade and the result is:

> onlyoffice-documentserver/squeeze,now 6.3.1-32 amd64 [installed]

If I open the file used in the video and go _File_ -> _Spreadsheet Info..._, I see for _Application_:

> ONLYOFFICE/6.1.0.83

After creating a new spreadsheet, I see the version in that:
> ONLYOFFICE 3.000

The version information is still confusing.

However, the issue of crashing the file while editing a formula doesn't exist after upgrade.

**Comment by ShockwaveNN** [comment]
> If I open the file used in the video and go File -> Spreadsheet Info..., I see for Application:

I think we already got this converstation before, but clarify once again

DocumentServer itself do not create any new files - then you press New Document in your Document Management System (DMS - Nextcloud, owncloud etc) it just use provided document as `New Document` and I don't know which DMS are you using, but it contain very old new files

If you use document server integration example (instruction how to use located at `http://docserverurl/welcome`)
You got no such info in `File -> Spreadsheet Info`
![image](https://user-images.githubusercontent.com/668524/123602698-b3521500-d801-11eb-8ba4-0a83bc771b7d.png)

But generally speaking best way to infom about DocumentServer version - to take a look at package version, or at least use `About` tab:
![image](https://user-images.githubusercontent.com/668524/123602775-cb299900-d801-11eb-9cd2-4e566801ec6f.png)

**Comment by piiskop** [comment]
I still use _Nextcloud_.

If you mean by integration using _Community Server_, I've tried it already. The result was a useless server machine as the server took first huge amount of time to set itself up and after that, it overloaded the system. Therefore, something is terribly wrong with _Community Server_ as if I used any other office software, no such overload would occur. This is why I rely on _Nextcloud_ as it's the only DMS that works with _ONLYOFFICE_ so far in my environment.

Is _About_ available in _Community Server_ only? Your screenshot doesn't seem to have it neither.

**Comment by ShockwaveNN** [comment]
> If you mean by integration using Community Server, I've tried it already.

No I mean integrated test example, which can be enabled via instruction at `http:/documentserver_url/welcome` and aviable after that via `http:/documentserver_url/example`

> Is About available in Community Server only? Your screenshot doesn't seem to have it neither.

I just cut this screenshot, it should be with any integration
![image](https://user-images.githubusercontent.com/668524/123626362-709c3700-d819-11eb-9db7-d56108986f42.png)

Note that about is not in File menu, but below `Search`, `Chat` etc buttons in left menu
