### ISSUE TITLE
Download failed when i use document server in my own app

### ISSUE THREAD

**Issue by Axel-AMGHAR** [ONLYOFFICE/DocumentServer#1312]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
when i use onlyoffice api , i get Download failed error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Docker compose for onlyoffice
```js 
onlyoffice:
  container_name: onlyoffice
  image: onlyoffice/documentserver
  restart: always
  ports:
    - "7777:80"
```

My app :
HTML 
```html
<script type="text/javascript" src="http://localhost:7777/web-apps/apps/api/documents/api.js"></script>
<body class="h-full">
    <div id="onlyoffice-file" ></div>
</div>
...
```
js 
```js 
...
    const config = {
      document: {
        fileType: 'docx',
        title: 'Example Document Title.docx',
        /* url of the file in the server */
        url: documentInfos.url,
// url being http://localhost/strorage/my-file.docx 
// the url is working and dl the file when i reach it in the url
        permissions: {
          comment: true,
          download: true,
          edit: false,
          fillForms: true,
          print: true,
          review: true,
          modifyContentControl: true,
          modifyFilter: true
        }
      },
      documentType: 'word',
      editorConfig: {
        lang: 'fr'
      },
      height: '100%',
      width: '100%'
    };

    (window as any).docEditor = new (window as any).DocsAPI.DocEditor('onlyoffice-file', config);
    (window as any).docEditor.denyEditingRights()
```

And there is the error
https://api.onlyoffice.com/editors/troubleshooting#download

**What is the expected behavior?**
I want to be able to see my file

**Did this work in previous versions of DocumentServer?**
This is the first time i'm using the api

**DocumentServer version:**
Latest image 28/06/21 (docker hub onlyoffice/documentserver)

**Operating System:**
WSL 2 : ubuntu 20-04

**Browser version:**
Chrome latest 28/06/21

**Comment by ShockwaveNN** [comment]
So, this literally mean that DocumentServer cannot download file provided from your app

Try to attach to docker container and download file by direct link via wget\curl

Also I see you've using WSL - maybe problem in some network permissions, I've no experience with WSL

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
