### ISSUE TITLE
Hidden worksheets in onlyoffice => wrong behaviour in Excel 2010

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DocumentServer#1319]
**Do you want to request a *feature* or report a *bug*?**
It's a bug report

**What is the current behavior?**
When I open in Excel 2010 a .xlsx with hidden worksheets (were hidden in onlyoffice), Excel hides the worksheets, but when using worksheets tab buttons, behaviour is inconsistent (it seems that Excel displays tab button correctly, but when clicking, all worksheets tab buttons are active, hidden or visible)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create an onlyoffice .xlsx
2. Hide some worksheets and save the file
3. Open this file in Excel 2010
4. Click on the worksheet tab buttons to switch from a sheet to another
5. => UI is corrupted, you have to click on the tab buttons as if all the worksheets were visible. Double clicking at right of the tab bar show the title of the sheet at his real place (see capture)

![bugonlyoffice](https://user-images.githubusercontent.com/6248852/124248283-faeae080-db22-11eb-8029-e14b1ef5d48f.png)

**What is the expected behavior?**
UI in Excel 2010 should be consistent : hidden worksheets and tab buttons OK.

**Did this work in previous versions of DocumentServer?**
don't know

**DocumentServer version:**
Version: 6.3.0.111 Enterprise Edition

**Operating System:**
Debian

**Browser version:**
Firefox 78.11 ESR

**Comment by Rita-Bubnova** [comment]
Hello, @Mer0me.
Sorry for late response.
I can't reproduce your problem. Could you attach XLSX file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by Mer0me** [comment]
Sorry, I've missed the first notification. Cannot reproduce the problem anymore.

**Comment by ShockwaveNN** [comment]
It's ok if you can reproduce this problem in the future - please attach xlsx file and I'll reopen this issue
