### ISSUE TITLE
Document viewer: Bulletpoint fonty type and size default settings

### ISSUE THREAD

**Issue by lennyvd** [ONLYOFFICE/DocumentServer#1322]
**Do you want to request a *feature* or report a *bug*?**
Not sure yet..

**What is the current behavior?**
When I add bulletpoints to my document, the font style and letter size changes to a default setting that is not suited for my document. Is there a way to change this default setting?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Start a new document -> type one line with a different font type and size then is standard -> add a bulletpoint. The bulletpoint will appear with the standard font type and size.

**What is the expected behavior?**
That the bulletpoints will follow the font type and size of the text that is already there, or that there is a way to set a standard for that font type and size

**Did this work in previous versions of DocumentServer?**
Don't know

**DocumentServer version:**
6.3.1

**Comment by matveevms** [comment]
Hi. @lennyvd. 
Could you attach a video with this problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
