### ISSUE TITLE
[MacOS] Keyboard shortcuts issues 

### ISSUE THREAD

**Issue by aol-nnov** [ONLYOFFICE/DocumentServer#1328]
Text navigation via shortcuts does not work

cmd+left/right arrow does not place cursor in the beginning/end of a line
option+left/right arrow does not jumps over words in the line

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
cmd+left/right arrow jumps over the words
option+left/right arrow acts as if no modifier is pressed - cursor moves letter by letter

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Type few words in the blank document, try some actions described in "current/expected behavior"

**What is the expected behavior?**

cmd+left/right arrow cursor jumps to the berinning/end of a line
option+left/right arrow jumps over the words

**Did this work in previous versions of DocumentServer?**

no. it's a long-living bug

**DocumentServer version:**

6.3.1 Community edition

**Operating System:**

MacOS 11.4 

**Browser version:**

Google Chrome Version 91.0.4472.114

**Comment by ShockwaveNN** [comment]
@DenisDeeSign Please take a look as soon as you got free time

**Comment by DenisDeeSign** [comment]
Hello @aol-nnov,
this is duplicate #1093.

**Comment by aol-nnov** [comment]
There are much more duplicates for this bug, unfortunately... Isn't it a highly demanded change then? )

**Comment by ShockwaveNN** [comment]
@aol-nnov It may be, but seems if devs cannot fix it now - there is some complications, I'm not sure
