### ISSUE TITLE
ipfilter is not work

### ISSUE THREAD

**Issue by Envikia** [ONLYOFFICE/DocumentServer#1337]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Keep showing the welcome page.
![image](https://user-images.githubusercontent.com/45445297/125422165-645752f9-938d-4d10-a6a6-35d310567323.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Update /etc/onlyoffice/documentserver/default.json
```
"ipfilter": {
	"rules": [
	  {"address": "A.B.C.D", "allowed": true},
	  {"address": "*", "allowed": false}
	],
	"useforrequest": false,
	"errorcode": 403
},
```
2. Restart the service or container

**What is the expected behavior?**
When accessing my document server portal "https://documentserver.mydomain.com" not from A.B.C.D, the portal will redirect to 403 error page. 

**Did this work in previous versions of DocumentServer?**
yes (it is work on 5.5.3)

**DocumentServer version:**
6.3.1

**Operating System:**
Windows 10

**Browser version:**
Chrome

**Comment by ShockwaveNN** [comment]
@igwyd please take a look as soon as you got free time

**Comment by igwyd** [comment]
Hello @Envikia
Thank you for report.
I can confirm - this is bug, issue 51318 in our private issue tracker.

**Comment by igwyd** [comment]
Sorry @Envikia i made mistake, its not the bug.
Ipfilter in default.json does not deny user access to the server ip adress or domain name, it controls internal requests from the server to the server.
If you want to restrict user access to your server, for example you can to configure your proxy server.

**Comment by ShockwaveNN** [comment]
Also we did a little investigation and seems we have no official documentation of usage of `ipfilter` server params, so if you found any mentions about this in public place @Envikia - could you share a links, I think we should update those

**Comment by Envikia** [comment]
Thank you @igwyd  and @ShockwaveNN for the following up.

I am using below guides to configure default.json (or local.json) before the version of 5.5.3
https://www.howtoforge.com/tutorial/how-to-restrict-access-to-the-onlyoffice-editors-to-the-users-of-your-nextcloud-instance/
https://dev.onlyoffice.org/viewtopic.php?f=9&t=35176

My purpose is to restrict the document server only access by my self-hosted nextcloud.
1. May I know any alternative ways to secure the document server (is that something like using the JWT token)? 
2. And how to disable the welcome page?

Please feel free to correct me and guide me, thanks.

**Comment by ShockwaveNN** [comment]
> is that something like using the JWT token

I think JWT token is best way to secure DocumentServer instance

> And how to disable the welcome page?

I think you should edit nginx config and comment welcome page

**Comment by Envikia** [comment]
> > is that something like using the JWT token
> 
> I think JWT token is best way to secure DocumentServer instance
> 
> > And how to disable the welcome page?
> 
> I think you should edit nginx config and comment welcome page

Do you mean the nginx config inside document server container?

**Comment by ShockwaveNN** [comment]
> Do you mean the nginx config inside document server container?

Yes, if you really need this, because there is no official way to disable welcome page via some options or params

**Comment by Envikia** [comment]
Thanks, for workaround, I successfully patch it for my purpose.
Path: /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
```
#welcome page
rewrite ^/$ https://www.mydomain.com redirect;
```
--------
By the way, if it is not a bug of "ipfilter", is it not support custom rules after version 5.5.3 ?

**Comment by ShockwaveNN** [comment]
> is it not support custom rules after version 5.5.3

It's not supported and before, this option designed not to block web connection, but convert connection as far as I remember

**Comment by Envikia** [comment]
Thanks you @ShockwaveNN.

Have a nice day :) Let me close the case.
