### ISSUE TITLE
Indent wrong on .odt file

### ISSUE THREAD

**Issue by h8ghbzc9bbr8c7** [ONLYOFFICE/DocumentServer#1339]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When reading a .odt file with a specific indent setting, Onlyoffice shows the indent wrong

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the attached .odt file and compare with the attached .pdf file which is generated by libreoffice 7.1.4 and see the difference. Similar bug happens with other indent settings.

**What is the expected behavior?**
Onlyoffice should handle the indent the same as libreoffice

**DocumentServer version:**
Desktop Editors 6.3.1.56

**Operating System:**
Ubuntu 18.04
**Browser version:**
[Testdoc-ODTIndent.odt](https://github.com/ONLYOFFICE/DocumentServer/files/6811354/Testdoc-ODTIndent.odt)
[Testdoc-ODTIndent.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/6811355/Testdoc-ODTIndent.pdf)

**Comment by matveevms** [comment]
Hello @h8ghbzc9bbr8c7 
Thank you for report.
I can confirm - this is bug, issue 51327 in our private issue tracker.

**Comment by h8ghbzc9bbr8c7** [comment]
Thanks!

**Comment by ShockwaveNN** [comment]
I'll leave this issue open until we release a fix for this

**Comment by h8ghbzc9bbr8c7** [comment]
This bug is fixed in 7.0.0.127

**Comment by ShockwaveNN** [comment]
Yep, sorry

This issue fixed in https://github.com/ONLYOFFICE/core/commit/383bae3750854643b2dace96088076485f5fb51f

I'll close this issue, thanks for your attention
