### ISSUE TITLE
Spreadsheet: Concatenated links in HYPERLINK formula are not filled down

### ISSUE THREAD

**Issue by michaelfreiberg** [ONLYOFFICE/DocumentServer#1348]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
This issue concerns Excel sheets (version=16.0300) opened with Spreadsheet. Links generated with Excel's HYPERLINK and CONCATENATE formulas don't lead to the correct URL if pasted down a column. The URL target in all cells equals the formula result of the cell in the first row respectively the most top manually edited cell.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Given that the formular entered in Column B is =HYPERLINK(CONCATENATE("http://example.com/";A2);CONCATENATE("http://example.com/";A2)), the link target is generated as follows:

| Column A  | Column B                | Link target (B)         |
| 1         | http://example.com/1    | http://example.com/1    | 
| 2         | http://example.com/2    | http://example.com/1    | 
| 3         | http://example.com/3    | http://example.com/1    | 
| 4         | http://example.com/4    | http://example.com/1    | 
| 5         | http://example.com/5    | http://example.com/1    | 

![only-office-bug-1](https://user-images.githubusercontent.com/3900239/126611028-ba68310a-5325-42e7-a227-105e26d80422.png)

If a formula (e.g. B3) is updated manually by copy-pasting or by reentering it in the formula bar the link target of the cell will be updated. The following cells in the column remain unchanged.

| Column A  | Column B                | Link target (B)         |
| 1         | http://example.com/1    | http://example.com/1    | 
| 2         | http://example.com/2    | http://example.com/1    | 
| 3         | http://example.com/3    | http://example.com/3    | 
| 4         | http://example.com/4    | http://example.com/1    | 
| 5         | http://example.com/5    | http://example.com/1    | 

**What is the expected behavior?**
| Column A  | Column B                | Link target (B)         |
| 1         | http://example.com/1    | http://example.com/1    | 
| 2         | http://example.com/2    | http://example.com/2    | 
| 3         | http://example.com/3    | http://example.com/3    | 
| 4         | http://example.com/4    | http://example.com/4    | 
| 5         | http://example.com/5    | http://example.com/5    | 

**Did this work in previous versions of DocumentServer?**
I have no access to a previous version. 

**DocumentServer version:**
Spreadsheet Editor 5.4.1.

**Operating System:**
Windows 10 Pro 20H2

**Browser version:**
Firefox 78.12.0esr (64-Bit)
Edge 91.0.864.71

**Comment by ShockwaveNN** [comment]
> DocumentServer version:
> Spreadsheet Editor 5.4.1.

This is very old version, more than 2.5 years old - could you update to latest v6.3.1

We rechecked your problem and if we done everything right - problem is not actual any more

**Comment by michaelfreiberg** [comment]
Thanks for your kind and fast answer. I didn't know that the OnlyOffice installation in our PowerFolder instance is that outdated.
