### ISSUE TITLE
File names inside the archive

### ISSUE THREAD

**Issue by test-OnlyOffice** [ONLYOFFICE/DocumentServer#1350]
Good afternoon. When testing the server version, we found a serious problem in the method of archiving backup copies of user files. Inside the archive, all user files are stored by their id and there is no association of file names with their id. In this case, if the user deletes the file, it is not possible to find the owner of the file or the file itself in the backup copy. This is a significant drawback that jeopardizes the very process of restoring users ' files.

**Comment by ShockwaveNN** [comment]
Are you sure you talking about ONLYOFFICE DocumentServer, not ONLYOFFICE CommunityServer?

**Comment by test-OnlyOffice** [comment]
> Are you sure you talking about ONLYOFFICE DocumentServer, not ONLYOFFICE CommunityServer?

We use both servers

**Comment by ShockwaveNN** [comment]
> We use both servers

But I don't think there is backup operation for DocumentServer? So this is a problem in CommunityServer?

**Comment by test-OnlyOffice** [comment]
> > We use both servers
> 
> But I don't think there is backup operation for DocumentServer? So this is a problem in CommunityServer?

You know better. Thanks. I created a ticket on a different thread.
