### ISSUE TITLE
documentbuilder builder.SaveFile error

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1351]
documentbuilder  
v6.2.0.123
sdk version:  6.2.0 (build:123)

```
builder.OpenFile("src.docx");

console.log("0000000")
builder.SaveFile("docx", "dst.docx");
builder.CloseFile();
```

[src.docx.zip](https://github.com/ONLYOFFICE/DocumentServer/files/6870171/src.docx.zip)

namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
le 90" hidden="false"/><wp:cNvGraphicFramePr/><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
false"/><wp:cNvGraphicFramePr/><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight

**Comment by ShockwaveNN** [comment]
I don't think namespace errors are related.

Could you try run `sudo documentbuilder script.js`

**Comment by verydemo** [comment]
> I don't think namespace errors are related.
> 
> Could you try run `sudo documentbuilder script.js`


I have the same problem with Sudo, I have this problem with DocumentBuilder, DocumentServer is fine.

**Comment by ShockwaveNN** [comment]
I recheck you problem, it show those messages, but those are warnings, you can ignore them

After running 
```
sudo documentbuilder test.js
```

I got output file `dst.docx` and it's looking fine

**Comment by verydemo** [comment]
thanks, output file is fine.
