### ISSUE TITLE
Incorporating Fully Fledged PDF Reader and Editor

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DocumentServer#1359]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

How about making and Incorporating a Fully Fledged PDF Reader Editor with Features on [Adobe Acrobat DC ](https://www.adobe.com/acrobat/features.html) and PDFSam [Enhanced](https://pdfsam.org/pdfsam-enhanced/) and [Basic](https://github.com/torakiki/pdfsam) ?

### Main Features as Summary :

- [ ] Convert to PDF as Visual Option instead of the current one under File > Save As > Choosing File Type
- [ ] Picture to PDF & Vice Versa
- [ ] PDF to Word/Docment, Excel/Spreadsheet, Presentation/PowerPoint and Picture
- [ ] Compress PDF like in PDFSam Visual with ability to control the size each and every KB
- [ ] Editing PDF content ssuch as Text and Images
- [ ] Add notes, Highlights and Comments
- [ ] OCR
- [ ] Combine Multiple files into PDF
- [ ] Rearrange pages in PDF
- [ ] Remove pages from PDF
- [ ] Rotate pages to portrait or landscape mode
- [ ] Trim the outer edges of page content
- [ ] Add pages to PDF file
- [ ] Split a PDF into multiple files
- [ ] Protect PDF with Multiple Options for Viewing, Editing and Copying
- [ ] Compare two PDFs to quickly spot differences
- [ ] Digital Signatures
- [ ] Validating Digital Signatures of any Form Flawlessly

 It might be troublesome as there are lot of Features to implement. But we can implement one by one. Though there is a PDF reader hidden in OnlyOffice , It is actually dumb as we can use the browsers instead.

 This would be great make most of People, Offices and Business Productivity to Open - Source Apps.

**Comment by Loki-L1130** [comment]
Hmm, Yep I know and as You & I said this could take a lot of time. But having a Open-Source PDF reader and Editor would be great a lot.

As you moved this issue to Document server will it be implemented in Desktop Editors or not ?
 
Was it actually possible to have this issue in Desktop Editors as Duplicate too ?

**Comment by ShockwaveNN** [comment]
> As you moved this issue to Document server will it be implemented in Desktop Editors or not ?

As soon at it be implemented I think it will be in both

I've moved in this repo because it's our main repo, in DesktopEditors we trying to collect issues only related to problems with desktop or feature actual only for Desktop

If the feature request actual for both - we usually log it in this repo, without need of duplicate, at least until we release this feature in DocumentServer

**Comment by tbsbdr** [comment]
+1 =D especially for 
- Add notes, Highlights and Comments

**Comment by oswaldocostaneto** [comment]
+2 =D especially for

Add notes, Highlights and Comments

**Comment by cameronj86** [comment]
+3 =D especially for

Add notes, Highlights and Comments

**Comment by louiesun** [comment]
So in v8.1, we've get a full featured PDF editor. 
Why not close it?

**Comment by Gingetsu** [comment]
Hello, @louiesun!
Yes, we have almost implemented it (the main part) and we will close this. But there will be improvements in future versions and for new bugs, proposals need to be issued with new issues.
