### ISSUE TITLE
comments display

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1360]
The added comments need to be selected before they can be displayed, Can you set automatic display

**Comment by ShockwaveNN** [comment]
Could you describe your scenario step-by-step, I do not understand you, comments are displayed as soon as you add them:
![image](https://user-images.githubusercontent.com/668524/127450879-14c629f7-e3f7-469d-ae3a-0f7328baa015.png)

**Comment by verydemo** [comment]
![image](https://user-images.githubusercontent.com/29354679/127473565-72a0133b-dab1-42d3-bcf3-28a10369a3e5.png)

 need to select content to display comments.

**Comment by ShockwaveNN** [comment]
We got comment panel on the left

![image](https://user-images.githubusercontent.com/668524/127482607-7daf9a28-dcb8-44f2-a289-73ecbdae0463.png)

**Comment by verydemo** [comment]
thanks， Also OK.
