### ISSUE TITLE
Text document API Range SetHighlight

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1361]
hello,The  Range SetHighlight() API  will share the highlighting to the co-editor,  I need a highlight like API Range Select(), set the highlighting, unhighlight.What to do?

**Comment by ShockwaveNN** [comment]
Hi, could you describe your problem in more precise maner, step-by-step, I completely do not understand you

> SetHighlight() API will share the highlighting to the co-editor
Yes it will, because why not, co-editor should have same document as caller of SetHighlight

**Comment by verydemo** [comment]
Is there a way to temporarily highlight? Not shared with co-editors, similar to func Select.

**Comment by ShockwaveNN** [comment]
No, there is no such feature

Is any other editor with cooperative editing have similar feature?
