### ISSUE TITLE
Owncloud can't connect to Onlyoffice after I upgrade Onlyoffice from ver. 6.2

### ISSUE THREAD

**Issue by joskapista44** [ONLYOFFICE/DocumentServer#1367]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Before upgrading Onlyoffice DocumentServer, Owncloud can connect to Onlyoffice with token. If I upgrade, it stops working, I can only connect them without token.

DocumentServer version:
6.2.2.21

Onlyoffice app version:
6.4.3

Owncloud version:
10.7.0

Operating System (server):
Ubuntu 20.04 LTS

**Comment by ShockwaveNN** [comment]
To be clear - did you updated Owncloud\Owncloud connector, not DocumentServer itself?

**Comment by joskapista44** [comment]
Sorry I made a mistake with the report. I edited it so it must be clear now. Owncloud and Owncloud connector are the newest versions. DocumentServer is what I would like to upgrade.

**Comment by ShockwaveNN** [comment]
By tokens do you mean JWT?

Maybe JST settings are lost in upgrade? could you check that `/etc/onlyoffice/documentserver/local.json` contain correct tokens

**Comment by joskapista44** [comment]
yes, JWT. I knew the local.json problem so I made a backup about it. So it contains the necessary token as before. Everything looks the same.

**Comment by ShockwaveNN** [comment]
Could you try to run DocumentServer integration example? Instruction at `http://docserver_url/welcome` and will be accessable at `http:/docserver_url/example`

If this example works fine - I think there may be some troubles on owncloud side

**Comment by ShockwaveNN** [comment]
Try to open it via external ip, not via `localhost` (if you've used that)

**Comment by joskapista44** [comment]
My local.json looks like this:
{
  "services": {
    "CoAuthoring": {
      "sql": {
        "type": "postgres",
        "dbHost": "localhost",
        "dbPort": "5432",
        "dbName": "oo",
        "dbUser": "oo",
        "dbPass": "oo"
      },
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "AuthorizationJwt"
        },
        "outbox": {
          "header": "AuthorizationJwt"
        }
      },
      "secret": {
        "inbox": {
          "string": "secret"
        },
        "outbox": {
          "string": "secret"
        },
        "session": {
          "string": "secret"
        }
      }
    }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}

**Comment by ShockwaveNN** [comment]
Edit `/etc/onlyoffice/documentserver-example/local.json` so it should have content like this:
```
"server": {
    "token": {
      "enable": true,
      "secret": "secret", 
      "authorizationHeader": "AuthorizationJwt" 
    }
  }

```

**Comment by joskapista44** [comment]
same error message :(
I tried it with the previous working setup and got the same result

**Comment by ShockwaveNN** [comment]
Hm, this is strange

For now lets leave owncloud out of picture and try to fix `http://docserver_url/example`

Does secrets in  `/etc/onlyoffice/documentserver-example/local.json` and `/etc/onlyoffice/documentserver/local.json` files are the same?

**Comment by joskapista44** [comment]
yes

**Comment by ShockwaveNN** [comment]
This is not right, do you restarted your services?

Could you record a video with error using /example page?

**Comment by joskapista44** [comment]
I's very strange. I didn't have time to make the record and I didn't change anything and but the example page started working well. Now I can't try the update on the running server but I will make it at the weekend.

**Comment by ShockwaveNN** [comment]
Ok, got it, feel free to comment any time, I'll leave this issue opene for at least a month

> I's very strange

Your issue is very strange indeed and I still have no idea why this happened

**Comment by joskapista44** [comment]
Thank you for your answers. I tried it yesterday, and it happened again - didn't work.
So I wanted to make the record today but it worked well. I have no idea why.
Then I tried upgrade the onlyoffice documentserver and I could install the (6.4.0-121) over (6.2.2-21) successfully. Then I fixed the tokens in local.json and voila! Everything works well now. Maybe something is different in 6.4 than 6.3 or I'm just luckier today. I have no idea.

**Comment by ShockwaveNN** [comment]
> Maybe something is different in 6.4 than 6.3 or I'm just luckier today

I don't think we change anything major in v6.4, so I think it's just luck since your working state vary for you day from the day

I'm sorry but I don't think we can figure out the reason for this problem until we can reproduce it each time and in our test environment

So I hope this problem is gone for you - if not we need somehow to reproduce it

**Comment by joskapista44** [comment]
Sure thank you, I hope it will never happen again and I will be able to upgrade next time without any problem. So we can close this I think.
