### ISSUE TITLE
Real dark theme (document page with black background and white font)

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [ONLYOFFICE/DocumentServer#1371]
- feature

Although there is a dark background, the document still has a white background, which is very dazzling. Is there any way to make the white background of the page black, and then change the default black font color to white? But it does not affect the actual file in other editors Open in?
![1111](https://user-images.githubusercontent.com/57204004/128280691-09d3a259-c090-4dde-9902-601c84a8d6e6.png)

**Comment by ShockwaveNN** [comment]
Hi there, we already implemented this feature and it will be available in next+1 release (probably 6.5, after we release 6.4 soon)
But currently it's not thoroughly tested so there maybe some problem
You can check it by installing docker `onlyoffice/4testing-documentserver-ee:99.99.99.2534 - first enable dark mode and after that new icon appear in top toolbar to change to full dart mode 

![image](https://user-images.githubusercontent.com/668524/128307646-f36e6914-97dc-41e5-b27a-4b2b67298dca.png)

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> Hi there, we already implemented this feature and it will be available in next+1 release (probably 6.5, after we release 6.4 soon)
> But currently it's not thoroughly tested so there maybe some problem
> You can check it by installing docker `onlyoffice/4testing-documentserver-ee:99.99.99.2534 - first enable dark mode and after that new icon appear in top toolbar to change to full dart mode
> 
> ![image](https://user-images.githubusercontent.com/668524/128307646-f36e6914-97dc-41e5-b27a-4b2b67298dca.png)

good job! thank for you team!

**Comment by ShockwaveNN** [comment]
I'll leave this issue open until we release v6.5 with this feature implemented for general public

**Comment by cipricus** [comment]
> I'll leave this issue open until we release v6.5 with this feature implemented for general public

Hello! I'm very glad to hear full dark mode will be available, but I'm eager to run 6.5 already, therefore in Kubuntu 20.04 I have done `sudo docker run -i -t -d -p 80:80 onlyoffice/4testing-documentserver-ee:99.99.99.2534`, but now I'm lost as to how start OnlyOffice.

I hope I'm not completely out of line here if I ask for a few instructions on how to see the application running ...!

**Comment by ShockwaveNN** [comment]
@cipricus I would advice you do not use 99.99.99 version almost in any cases, because it may be completely broken

If you want to try out full dark mode - install v7.0.0 (any latest build) - it should include toggle to enable dark mode in view settings menu as far as I remember

You run using same command and follow instruction on `/welcome` page to enable integrated test example

**Comment by cipricus** [comment]
> we already implemented this feature and it will be available in next+1 release (probably 6.5

Could you please tell when approximately 6.5 with full dark will be out? Just to make note and not forget to check it out. 

(I'm using LO until then —because I need the full dark screen required by my bresbital habitude).

**Comment by ShockwaveNN** [comment]
> Could you please tell when approximately 6.5 with full-dark will be out? Just to make note and not forget to check it out.

We really hope to ship v7.0 (it will be v7.0, not v6.5) early next year

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open new issue if problem still actual

**Comment by hydroEng** [comment]
Hello,

I can't seem to find the full dark mode toggle in DesktopEditors v 7.4. Am I missing something? 
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/59785388/62e0e147-fea2-49ef-83a1-a39746d61dab)
