### ISSUE TITLE
Incorrect data in MS Office 2003 xml spreadsheet file

### ISSUE THREAD

**Issue by kirillFedorov1** [ONLYOFFICE/DocumentServer#1373]
This is xml 2003 spreadsheet, it opens fine in microsoft excel.
R7 is trying to open it as a doc file, probably it doesn't recognize some tags? Other xml 2003 files work fine in R7.
[EXPORT.xls](https://github.com/ONLYOFFICE/DocumentServer/files/6937251/EXPORT.xls)
(I have renamed it to xls because github doesn't allow to upload xml, please rename it back to xml)

**Comment by ShockwaveNN** [comment]
Oh, this is Office xml 2003 file, I do not like them, there is a lot of misunderstanding in using them ((

Could you try to rename it to xls and try and open them, it may incorrect detect this as doc, but changing it extension to xls or xlsx can help

Also currently I have no access to MS Excel, but I've tried to open this file in LibreOffice with xml and xls extension - and in both cases this file look empty (but do not raise any error). Are you sure this file is correct at all?

> R7 is trying to open it as a doc file

Also please note that we are ONLYOFFICE team, not R7 - this is completely different organization and people
But I see problem opening it in ONLYOFFICE DocumentServer 6.3.1

**Comment by kirillFedorov1** [comment]
(I just got some idea and I actually don't need this exact file in my work)

> Could you try to rename it to xls
"Format is not supported"

>Are you sure this file is correct at all?
I just opened it with ms excel

>Also please note that we are ONLYOFFICE team
Sure, it was a typo about r7, i'm testing onlyoffice

**Comment by ShockwaveNN** [comment]
Seems we found a problem, creating a new issue in our private issue tracker

But

> > "Format is not supported"

Are you sure? We can show different errors but not like this for xls file?

**Comment by ShockwaveNN** [comment]
We created issue 51748 in our private issue tracker

We checked in version 6.3.1 - this file even not converting
We checked in next version 6.4.0 (which we not released by now) - file is opening but inside there is garbade
![image](https://user-images.githubusercontent.com/668524/128341251-bf7c1d4d-57e2-4468-bb75-24af2b00b450.png)

So defenetly there is something wrong

**Comment by trofim24** [comment]
fixed in 7.0.0
so I closed this issue
