### ISSUE TITLE
Open Word with tables in onlyOffice, display is incomplete  

### ISSUE THREAD

**Issue by baoyuping** [ONLYOFFICE/DocumentServer#1374]
**Do you want to request a *feature* or report a *bug*?**
it is  a bug
**What is the current behavior?**
Open Word with tables in onlyOffice, display is incomplete  
![image](https://user-images.githubusercontent.com/75818314/128474074-172b5dc3-75a3-428f-95f1-45d2d808cfee.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1、Create tables in Word using WPS  
2、Open the word in onlyOffice  
**What is the expected behavior?**
I expect the table in Word to display properly
**Did this work in previous versions of DocumentServer?**
No, it is working on the latest DocumentServer, version 6.3.1
**DocumentServer version:**
6.3.1
**Operating System:**
win10
**Browser version:**
Google Chrome 91.0.4472.124

This is the file in question
[新建 DOCX 文档.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6943919/DOCX.docx)

**Comment by TatianaKirillova** [comment]
Hello, **@baoyuping**
Thanks for your request!
I don't find the problem. In the editor ONLYOFFICE and Microsoft Office tables are displayed in the same way. Which version of Microsoft Office are you using? Or maybe you will attach the file before editing in ONLYOFFICE?

**Comment by TatianaKirillova** [comment]
![DOCX docx  - table](https://user-images.githubusercontent.com/72191601/128478200-6e831bed-c18c-4198-8b8f-904122522b3a.png)

**Comment by baoyuping** [comment]
Sorry I opened Word in WPS, this is word in WPS display  
![image](https://user-images.githubusercontent.com/75818314/128490382-d23f9aef-8911-4691-b85d-9e61f6dce1c6.png)

**Comment by TatianaKirillova** [comment]
Is your source file created in Microsoft Office or WPS editor?

**Comment by baoyuping** [comment]
Yes, I'm sure.

**Comment by baoyuping** [comment]
I've seen tables display normally in WPS, but not in onlyOffice Online, and then I adjusted the table width in the table properties using the online editing of OnlyOffice Online to make it work

**Comment by TatianaKirillova** [comment]
If both ONLYOFFICE and Microsoft Office open the file in the same way - this is the correct opening.

**Comment by baoyuping** [comment]
I have not tried ms Office, I only used WPS, I try ms Office open what is it like

**Comment by ShockwaveNN** [comment]
This issue is closed because we use MS Office as standard for opening docx file, since docx is developed by MS itself
