### ISSUE TITLE
need help to restore files from cache files editor.bin

### ISSUE THREAD

**Issue by bobfh** [ONLYOFFICE/DocumentServer#1377]
After update form v4.4.1 to v.6.2 on my server i lost data in docx xlsx files.

i guess problem is that onlyoffice have stored changes in cache - but dont save it back on owncloud

i found cached files - is this the way to convert them to normal type ?

**Comment by bobfh** [comment]
it was simple - i have made new file - onlyoffice - creates empty editor.bin - i have replced by own file - and tap f5 - all fine

**Comment by bobfh** [comment]
But problem was when i updated onlyoffice - cache files are in postgress base - and after update this base stayed clean

**Comment by ShockwaveNN** [comment]
@DenisDeeSign Could you take a look as you got free time?
But I'm not sure that in v4.4.1 we got correct mechanism to upgrading to newer version, I think we added this somewhere around version v5.x so maybe server was not shut down correctly
