### ISSUE TITLE
Can't install Document Server using ONLYOFFICE_Community_Edition_Win-install.v17.05.113

### ISSUE THREAD

**Issue by kakadanhem** [ONLYOFFICE/DocumentServer#138]
After open the setup file, even Nodejs is installed, the installation still show that Nodejs is not found. But if click next to begin download and install Nodejs using the installation it will show error message says:
Node.js x86 mandatory prerequisite was not correctly installed.

**Comment by Velesey** [comment]
Same problem, have you got a solution?

**Comment by agolybev** [comment]
Hello @Velesey,
Try removing Nodejs and installing it throughONLYOFFICE_Community_Edition_Win-install

**Comment by eafarooqi** [comment]
Anyone got the solution for this ? same issue with the community edition. I have tried to install node.js manually and from community edition installation. no luck same error.

**Comment by agolybev** [comment]
Hello @eafarooqi 
Try removing Nodejs and installing it through ONLYOFFICE_Community_Edition_Win-install. Also you can try instalingl Node.js by this [link](https://nodejs.org/dist/v6.9.2/node-v6.9.2-x86.msi).
Unfortunaly, community installation has bug, it checks Node.js installation by product code. It will be fixed in the near release.

**Comment by eafarooqi** [comment]
hi @agolybev 
i have already tried this but still its the same error. Waiting for the fix.

**Comment by agolybev** [comment]
Hi @eafarooqi, yes, you are right. I tried to install ONLYOFFICE_Community_Edition_Win-install just now and hadn't success. But when I had installed Node.js by this [link](https://nodejs.org/dist/v6.9.2/node-v6.9.2-x86.msi), I installed Community Server successfully.

**Comment by eafarooqi** [comment]
hi @agolybev. ya it worked with the version 6.9.2. But will not work with the higher versions. So i have to downgrade to 6.9.2 from latest version than it works. Thanks.

**Comment by agolybev** [comment]
@HellRoad, could you verify this bug with latest Community module.

**Comment by HellRoad** [comment]
ONLYOFFICE_Community_Edition_Win-install (5.0.7) correctly working with node.js version 9.4.0
