### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by safo01** [ONLYOFFICE/DocumentServer#1381]
I have Nextcloud (21.0.3) and Onlyoffice Document Server (6.3.2.2) installed on the same server without docker. I'm using only nginx as webserver. I'm using european ssl certificate.

Installation from Document Server was without any problems I also can access it via browser without any ssl errors. Nextcloud and Document Server they have different domain names -> cloud.xxx.com and office.xxx.com. However if I'm trying to connect Document Server via Nextcloud Onlyoffice app I'm getting following error message:
**_Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 6.3.2.2)_**

On the server itself wget had a ssl problem to https://office.xxx.com I resolved it via commands:
sudo apt-get install --reinstall ca-certificates
sudo apt-get -f install
sudo dpkg --purge --force-depends ca-certificates
sudo apt-get -f install

Log file from document server:

```
[2021-08-12T10:23:20.232] [ERROR] nodeJS - error downloadFile:url=https://cloud.xxx.com/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.2RoHxWozXgNo9i_L0oxuVHqZ1leG8KP42SN3xXActVE;attempt=3;code:UNABLE_TO_VERIFY_LEAF_SIGNATURE;connect:null;(id=conv_check_406930463_docx)
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)
```

If I disable rejectUnauthorized it works but I don't want to do this on a live system.

**Comment by safo01** [comment]
By changing /etc/onlyoffice/documentserver/nginx/ds.conf

```
## Normal HTTP host
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name _;
  server_tokens off;
  server_name office.xxx.com;

  ## Redirects all traffic to the HTTPS host
  root /nowhere; ## root doesn't have to be a valid path since we are redirecting
  rewrite ^ https://$host$request_uri? permanent;
}

#HTTP host for internal services
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
  server_name localhost;
  server_tokens on;
  server_name office.xxx.com

  include /etc/nginx/includes/ds-common.conf;
  include /etc/nginx/includes/ds-docservice.conf;
}
```

Righ now I'm on a test server. It is not accessible from the outside.

**Comment by ShockwaveNN** [comment]
I strongly think this is not problem on DocumentServer side, but simply incorrect certificate

**Comment by ShockwaveNN** [comment]
In that case I see two options

1. Try to `wget https://cloud.xxx.com/` from server and see for any errors
2. Temprary make this server public and check it certificate by ssllab

**Comment by safo01** [comment]
wget to https://cloud.xxx.com is without any problems

I tested the certificate for the live server with ssllab and there are no errors

**Comment by ShockwaveNN** [comment]
Could you try to

1. Enable test example of DocumentServer - instruction here: https://office.xxx.com/welcome
2. Check if files are correctly editing in https://office.xxx.com/example page

If step 2 is without any error - DocumentServer is setup correctly and I've moved your issue to person who understand how nextcloud can be setup

**Comment by safo01** [comment]
I restored the test machine to the state before installing the documents server

Now if I do wget https://cloud.xxx.com I'm getting this message:

```
Resolving cloud.xxx.com (cloud.xxx.com)... xx.xx.xx.xx
Connecting to cloud.xxx.com (cloud.xxx.com)|xx.xx.xx.xx|:443... connected.
ERROR: cannot verify cloud.xxx.com's certificate, issued by ‘CN=EuropeanSSL Server CA 2,O=EUNETIC GmbH,L=Durmersheim,ST=Baden-W\\C3\\BCrttemberg,C=DE’:
  Unable to locally verify the issuer's authority.
To connect to cloud.xxx.com insecurely, use `--no-check-certificate'.
```

**Comment by ShockwaveNN** [comment]
Soo, if DocumentServer is not installed and you have some issies - this is not DocumentServer issue?

**Comment by safo01** [comment]
I'm not sure. I saved the .crt file to **/usr/local/share/ca-certificates/** and run **sudo dpkg-reconfigure ca-certificates** after that wget didn't show me any errors.

But on the log file from documents server it still says "**Error: unable to verify the first certificate**"

**Comment by ShockwaveNN** [comment]
I do not understand why you need to save your certificate in `ca-certificates` at all

If you certificate fully correct it should work without placing in system certificates chain
