### ISSUE TITLE
[BUG] Error while opening text document

### ISSUE THREAD

**Issue by lksmsr** [ONLYOFFICE/DocumentServer#1384]
Bug report

**What is the current behavior?**
OnlyOffice texteditor randomly throws an error when I try to open a text file that I just edited. Can't open the file for a while then it suddenly works but all progress is gone. Happened to me 3-4 times now... very frustrating :-(

 ![image](https://user-images.githubusercontent.com/36881892/129737006-1ffc8e0f-8837-43f0-b571-67a10e002aa7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create text file
- edit it for a couple of minutes
- exit out of the editor
- pray, that the file can be opened

**What is the expected behavior?**
I just want to open my previously edited file.

**Did this work in previous versions of DocumentServer?**
Don't know, just started using Only Office

**DocumentServer version:**
0.1.11

**Operating System:**
Ubuntu 20.04

**Browser version:**
Chrome 92.0.4515.131

**Comment by ShockwaveNN** [comment]
> DocumentServer version:
> 0.1.11

Are you sure this version is correct? This is not our version
Maybe this is Community Document Server?

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by lksmsr** [comment]
my bad, it's the community server

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue
