### ISSUE TITLE
Substitution of range names in the INDIRECT function, formed by information from cell and additional text

### ISSUE THREAD

**Issue by GeniusBroccoli** [ONLYOFFICE/DocumentServer#1385]
**Do you want to request a *feature* or report a *bug*?**
Bug.
**What is the current behavior? What is the expected behavior?**
I encountered problems in some advanced Excel documents with multiple INDIRECT function substitutions. Excel recognizes a formula like INDIRECT(A1&"[#All]"), where A1 contains the table (range) name. This construction can be used in the horizontal and vertical search functions. But I see an error in ONLYOFFICE, maybe I need to change the formula for compatibility in some way, I have not found an answer to this question.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have attached screenshots.
**DocumentServer version:**
6.3.1.56 Desktop, 6.2.2.21 Server
![Снимок](https://user-images.githubusercontent.com/18056785/129750487-2b0a24d0-c67d-4031-8c8c-96dda945ae50.PNG)
![Снимок2](https://user-images.githubusercontent.com/18056785/129750495-12482c36-c941-4559-a2d8-66c9212178e2.PNG)

**Comment by Rita-Bubnova** [comment]
Hello, @nnolex.
Could you attach file with problem?

**Comment by nnolex** [comment]
I created another document with drop-down lists and INDIRECT functions.
[test_indirect.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/7008640/test_indirect.xlsx)

**Comment by Rita-Bubnova** [comment]
Thank you for XLSX file.
I can confirm - this is bug, issue 52050 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/706d40389de5bcdf3b3dcc3f092098fae1882f7f) in a future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open new issue if problem still actual
