### ISSUE TITLE
Hello, there is an exception when using the community app，Loading succeeded once and failed once，errorCode: -82

### ISSUE THREAD

**Issue by furyHuang** [ONLYOFFICE/DocumentServer#1387]
**Do you want to request a *feature* or report a *bug*?**
The server version 6.3.1 has been installed for about a month. The prompt message "errorcode: - 82, errordescription:" an error has occurred while opening the file "often appears when previewing or opening the file, which makes it unusable. I upgrade to the latest version；What should I do?
`{errorCode: -82, errorDescription: "An error has occurred while opening the file."}
errorCode: -82
errorDescription: "An error has occurred while opening the file."
`
This is my office configuration：
`{
    "type":"desktop",
    "width":"100%",
    "height":"100%",
    "documentType":"text",
    "document":{
        "title":"empty.docx",
        "url":"http://192.168.2.209:9204/common/office/download?resource==/statics/upload/2021-08-19/aae54ba1-3a7b-4132-8dae-c6f07236a360.docx",
        "fileType":"docx",
        "key":"60.docx1629364036473",
        "permissions":{
            "edit":true
        }
    },
    "editorConfig":{
        "mode":"view",
        "user":{
            "id":"1",
            "name":"jack",
            "group":"group1(103)"
        },
        "customization":{

        }
    },
    "events":{

    }
}`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer version:**
For Windows Server 2012 or higher (64-bit only) Version: 6.3.2
**Browser version:**
Google Chrome 92.0.4515.131（64 位）

**Comment by furyHuang** [comment]
It has been upgraded to the latest version 6.3.2 of the community version, and there are still exceptions

**Comment by ShockwaveNN** [comment]
I think error like this

> {errorCode: -82, errorDescription: "An error has occurred while opening the file."} errorCode: -82 errorDescription: "An error has occurred while opening the file."

usually happens in DocumentServer itself cannot download file to edit by some reasons, maybe network error

Connect to server with DocumentServer and run `wget http://192.168.2.209:9204/common/office/download?resource==/statics/upload/2021-08-19/aae54ba1-3a7b-4132-8dae-c6f07236a360.docx`

**Comment by furyHuang** [comment]
Hello, if it is a download path problem, the error information is as follows:
![1629374120(1)](https://user-images.githubusercontent.com/43334699/130064490-cea325b6-3d23-422f-afe2-c2eb6e548dde.png)
When this file is opened, it fails once and succeeds once. It is very regular. Is there some setting added to the community version server

**Comment by furyHuang** [comment]
When I upload files to https://personal.onlyoffice.com/ There is no problem opening multiple times
![1629374545(1)](https://user-images.githubusercontent.com/43334699/130065375-e0a47554-7e0c-48e4-833a-292cc472f151.png)

**Comment by furyHuang** [comment]
This is the path of the file. You can download it. I open this file with community server 6.3.2. If it is loaded successfully at one time, code: - 82 error URL will appear next time
[filePath](https://personal.onlyoffice.com/Products/Files/DocEditor.aspx?fileid=4229821&amp;doc=RjBZblp3NjkrcnowcVlMd1FLSTRpTll5MlJiSmk0S2k5bCthU0l5OHEyWT0_ IjQyMjk4MjEi0)

**Comment by furyHuang** [comment]
Loading all the files in the server is such a regular problem code: - 82, please take a look. Thank you

**Comment by ShockwaveNN** [comment]
I found several similar issues

https://github.com/ONLYOFFICE/DocumentServer/issues/1263
https://github.com/ONLYOFFICE/DocumentServer/issues/507
But in both cases there is no much information from users

Is there any other errors in log files?

Are you using some kind of integration you've implemented by yourself?

If not I need some kind of way to reproduce this problem on my system, preferable Docker image or virtual machine, because I've no idea about reason of this problem

**Comment by furyHuang** [comment]
Sorry, the reason for the occurrence of: errorcode: - 82 is: rabbitmq
When PostgreSQL is deployed, if two computers are deployed, the same database can not be used, or the same message queue will appear in the same queue. The server and computer computer have deployed applications, resulting in this result.

**Comment by ShockwaveNN** [comment]
> if two computers are deployed, the same database can not be used

Yes this is correct

It's very hard for me to fully understand what you mean. Is your issue resolved?

**Comment by furyHuang** [comment]
Yes, it has been solved. Thank you
