### ISSUE TITLE
Download after adding a sheet to xlsx-File leads to outdated content

### ISSUE THREAD

**Issue by davidchristopherbuchanan** [ONLYOFFICE/DocumentServer#1393]
**What is the current behavior?**

After you entered a second sheet to a table (XSLX), the downloaded file does not seem to refresh anymore with new content.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Steps to reproduce the problem:

- Create a .XLSX (Table) somewhere and edit it with OnlyOffice
- enter "123" to the first top left cell
- add a second sheet by pressing the PLUS symbol left to "Sheet 1"
- enter "456" to the first top left cell
- leave the document 
- download the file and open it in EXCEL
- reopen the file in onlyoffice and compare the content

**But what happens:**

The file in OnlyOffice seems to be ok and contains Sheet 1 and Sheet 2 as well as "123" and "456".

But the downloaded file shows an empty table.

Remark: If you repeat, and leave OnlyOffice after entering "123" and continue editing from there, the content is "Sheet 1" with "123" instead.

**What is the expected behavior?**

The downloaded file should show the same content as the online edited file.

**Did this work in previous versions of DocumentServer?**

I did not test yet.

**DocumentServer version:**

Server:  Nextcloud 21.0.3, OnlyOffice 6.3.1.32

**Browser Versions:**

Browser: Firefox 91.0.1 running on Windows 10 Pro

**Comment by davidchristopherbuchanan** [comment]
I figured out, that if you upload the file again with a different filename, the content is still there. It looks like OnlyOffice saves additional sheets in a format that other programs cannot read. Tested with Microsoft Excel and OpenOffice.

**Comment by ShockwaveNN** [comment]
@davidchristopherbuchanan Judging by your last video your actions is

1. Create new file
2. Edit this file
3. Do not close this file and download this file from Document Management System (DMS, `/example` in your case)

Problem is that ONLYOFFICE DocumentServer by default do not work that way - we make new version of file only after all users closed this file

You can try to enable [`force-save`](https://api.onlyoffice.com/editors/config/editor/customization#forcesave), but I'm not sure if this setting is implemented on `nextcloud` part (this is not my area of knowledge) and I do not language you've using on screenshots

**Comment by davidchristopherbuchanan** [comment]
How do i close a file?

**Comment by davidchristopherbuchanan** [comment]
If you review the video, you can see that also the menu option "File" -> "Save" is gray.  So, is it not a good reason to believe that the file is already saved? If it would be enabled, it would be easy to click it, before i download.

**Comment by davidchristopherbuchanan** [comment]
I tested a bit with enabled force-save option. I can confirm that this option would work.

If you can tell me how to close a file in the OnlyOffice intended way, it is more easy for me. I can explain this to the single user easily. In my case, the download after edit workflow is quite rare use case.

The alternative would be to retrain all other users to save their work before leaving. This can be a challenge because they don't expect it at the moment.

**Comment by ShockwaveNN** [comment]
> How do i close a file?

Just close all opened editing session of file

> So, is it not a good reason to believe that the file is already saved?

No, it's not. Changes are saved, but they are not applied to current file version. It's designed that way

> If you can tell me how to close a file in the OnlyOffice intended way, it is more easy for me

See above

**Comment by davidchristopherbuchanan** [comment]
ok, that seem to work for me. Thanks for your help.

**Comment by ShockwaveNN** [comment]
You're welcome. If everything is clear for you - I'll close this issue
