### ISSUE TITLE
Converted pdf file is diffrent when use V5.5.3 and V6.31 which cause picture display issue on webpage

### ISSUE THREAD

**Issue by RainyGao-GitHub** [ONLYOFFICE/DocumentServer#1395]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
The picture display will be incorrect when use V6.3.1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. build a word file with some pictures on that
2. convert it to pdf with V5.5.3
3. convert it to pdf with V6.6.1
4. Compare them with Beyond Compare, 
5. Show pdf on webpage, the pdf which converted by V6.3.1 will be incorrect

**What is the expected behavior?**
Converted pdf should be same with the same file and should not have dispaly issue

**Did this work in previous versions of DocumentServer?**
It works on 5.5.3, I am not sure if it works on previous version

**DocumentServer version:**
6.3.1

**Operating System:**
Windows 10

**Browser version:**
Chrome

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
