### ISSUE TITLE
issues with editor icons

### ISSUE THREAD

**Issue by mbx2015** [ONLYOFFICE/DocumentServer#1396]
The icons of the document editor interface are not in the appropriate place and the editor is read only.

**Comment by mbx2015** [comment]
This happens with the docker version, but the .deb version is correct. 
Could you please check the docker build ?

**Comment by ShockwaveNN** [comment]
@mbx2015 I've rechecked once again

![Screenshot_20210830_151359](https://user-images.githubusercontent.com/668524/131337317-0dd37a41-82d6-41a2-90ad-21289430ce23.png)

My actions:

1. `docker run -itd -p 80:80 onlyoffice/documentserver:6.4.0.121`
2. sleep 240 for correct init
2. `sudo docker exec 5ca8d8820c38 sudo supervisorctl start ds:example`
3.  Open `localhost/example` and create new doc

**Comment by mbx2015** [comment]
It works! I tried with another PC
There is most likely something with my laptop.

Thanks.

**Comment by ShockwaveNN** [comment]
@mbx2015 I think this usually mean cache problem, try another browser on your laptop, or check proxy settings or something like this and clear browser cache
