### ISSUE TITLE
Mainland China YouTube is blocked, are there any alternative solutions for pptx videos?

### ISSUE THREAD

**Issue by yangmingli08** [ONLYOFFICE/DocumentServer#1397]
I want to request a feature as YouTube links are broken in mainland China.

I've noted the #997 

Is there any possibility to add other video vendors instead of YouTube? 

**What is the expected behaviour?**
Play videos in pptx using the Document server

**Did this work in previous versions of DocumentServer?**
Never

**DocumentServer version:**
6.3.2 Community Edition

**Operating System:**
CentOS 7

**Browser version:**
Chrome 92

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
