### ISSUE TITLE
Copy/Paste doesn't work with general clipboard

### ISSUE THREAD

**Issue by iwkse** [ONLYOFFICE/DocumentServer#14]
Hi, I've just tested it and it seems you cannot copy/paste from within the environment but only inside of onlyoffice application. This is someone a limit. If I want to copy a text from web, or a pdf document or anything else from outside of onlyoffice the copy/paste function will not work.

**Comment by AnaMih** [comment]
To copy or paste from applications outside the editor use CTRL+C/V/X combinations.
We are planning to add a workaround on one of the nearest updates.

**Comment by iwkse** [comment]
I've tried that but it doesn't work with CTRL+C/V/X
