### ISSUE TITLE
Formulas calculating / refreshing not possible

### ISSUE THREAD

**Issue by GregMighty** [ONLYOFFICE/DocumentServer#140]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I have a spreadsheet with ca. 500 lines in it. I have it  imported into OnlyOffice as .xslx file. I am using widely vlookup formula in my spreadsheet. After opening the file all the formulas are counted properly. But as we change anything within the range of the formula, suddenly most (about 90% of fields) begin displaying #N/A error. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Create a xlsx file (in external editor), populate it with random data and use vlookup formula in it. Than have the file uploaded onto OnlyOffice server and change anything in columns you want the vlookup formula to go through. The results of formula should now return errors.

**What is the expected behavior?**

Results of formulas should display / refresh properly after modifying the data.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

We are running NextCloud v.12  with DocumentServer  4.4.1 and integration API 1.1.3
Issue is browser independant.

**Comment by dgierejkiewicz** [comment]
I've got the same problem with formula vlookup (#N/A error).

**Comment by ShockwaveNN** [comment]
Could you attach file with error. It will be much simpler to fix with them.

**Comment by GregMighty** [comment]
Hi. 
I am attaching our example file. 
If you open it in external spreadsheet program, you will see that vlookup returns proper values (formulas are in the first sheet). 
After uploading it into document server, and refreshing formulas instead of values I get #N/A errors.

[test.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1196249/test.xlsx)

**Comment by ShockwaveNN** [comment]
@GregMighty Hi, did you attached original file or file that you got after exporting it via ONLYOFFICE
For me it's exported file, but we need original file.
I see no `vlookup` formulas in it (or point for me that cell if I'm wrong)

**Comment by GregMighty** [comment]
Hi,
Actually this is a file that I exported from ONLYOFFICE and "fixed" in excel.
The file is ready to be uploaded to Document Server.
I am reattaching it since the file I sent previously indeed had no formulas in it. 
I am also attaching a printscreen that shows how these formulas look in OnlyOffice.

Hope it helps.
Grzegorz / Greg

[test_original.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1201069/test_original.xlsx)
![in_onlyoffice](https://user-images.githubusercontent.com/28106243/28978683-31efc484-7947-11e7-88d1-e40c97360634.png)

**Comment by ShockwaveNN** [comment]
@GregMighty Yeah, I was able to repdouce you `N/A` problem, we looking into it now

**Comment by trofim24** [comment]
@GregMighty Thank you. At us function `VLOOKUP` is case-sensitive, but should be case-insensitive. We will fix this in the next release.

**Comment by GregMighty** [comment]
@trofim24 

Thanks for the information. We are really looking forward to the update.

**Comment by trofim24** [comment]
Fix. [4.4.3](https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-4.4.3)
