### ISSUE TITLE
About config customization issue

### ISSUE THREAD

**Issue by smileheart2** [ONLYOFFICE/DocumentServer#1404]
I have download the "Net (C#) Example" demo, after changed the customization.customer info like below find it not work
 
![image](https://user-images.githubusercontent.com/29588680/131648287-d3e7e0e5-2567-4000-a1e5-c38fb6cf9665.png)

if click the "About" button ,it's still show below image
![image](https://user-images.githubusercontent.com/29588680/131648708-3daf7f93-21d5-4c42-a01a-a1f561a5d643.png)

Win10 
Google Chrome "92.0.4515.131"

**Comment by ShockwaveNN** [comment]
Are you init your license correctly while starting DocumentServer?

There is asterisk [ here](https://api.onlyoffice.com/editors/config/editor/customization#customer) in documentation

And this mean this feature only available if you have paid edition, not opensource version

**Comment by smileheart2** [comment]
Get it, Thank you for your reply
