### ISSUE TITLE
Arm64/AARCH64 online installation or Arm/AARCH64 architecture Docker image  

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1406]
The RPM dependencies you provide are the X86_64 architecture, docker image is the AMD64 architecture, How to install or deploy docker images online in ARM64 architecture?

I wanted to implement the simplest solution: run an existing AMD64 architecture image on an ARM64 machine, 

I try to use qemu - user - static, I only found the AMD64 run ARM64 mirror the demo, modified hoping to ARM64 run AMD64 architecture image, I don't know is I incorrectly or do not support such use  

```
wget https://github.com/multiarch/qemu-user-static/releases/download/v6.1.0-1/qemu-x86_64-static.tar.gz

tar xzf qemu-x86_64-static.tar.gz

cp qemu-x86_64-static /usr/bin/

chmod +x /usr/bin/qemu-x86_64-static

docker run --rm --privileged multiarch/qemu-user-static:register

docker run -it -d -p 8084:80 -v /usr/bin/qemu-x86_64-static:/usr/bin/qemu-x86_64-static  onlyoffice/documentserver:6.2.1
```

**Comment by ShockwaveNN** [comment]
We officially do not support arm in any way

All discussion in [issue here](https://github.com/ONLYOFFICE/DocumentServer/issues/152)

There is unofficial workaround [described here](https://github.com/ONLYOFFICE/DocumentServer/issues/152#issuecomment-834217879)
