### ISSUE TITLE
Border added around images when saving DOCX as PDF

### ISSUE THREAD

**Issue by VanCoding** [ONLYOFFICE/DocumentServer#141]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
For some images a border gets added when the DOCX file gets saved as a PDF file.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new document, add the image attached, save the document as PDF, open the PDF with a PDF viewer, notice the grey border around the image.

**What is the expected behavior?**
The border should not be there, the image should be displayed exactly as in the docx file.
**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
DesktopEditors 4.4.1.342 and also DocumentServer-Docker
I don't know if this bug was in previous versions.

**NOTES**
I have a bit of experience with the PDF format, and noticed that the image gets embedded into the PDF with a black border around it. And then to hide said border, an SMask is provided. If I modify the PDF to have no such SMask, the black border is visible again. Is there a reason why this black border is added to the image in the first place? 

**FILES**
[document.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1155328/document.docx)
[document.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/1155329/document.pdf)
![image](https://user-images.githubusercontent.com/595361/28310377-9eabd1ba-6bac-11e7-8d15-74570dd370b8.png)

**Comment by VanCoding** [comment]
**UPDATE**
Ah, now I understand! The image has a transparent border, and when it gets embedded into the PDF, it gets converted to JPG, and because JPG does not support transparency, the border is now black. That's why the SMask gets added, to make the border transparent again.

But even if I understand why it is done now, the border should not appear in the resulting PDF. It still means there is a bug, that needs to get fixed.

Btw: Is it possible to use a lossless format for images in PDF export, if the source file is also lossless, like a PNG file? Converting PNGs to JPEG means a loss in quality.

**Comment by ShockwaveNN** [comment]
Closing this issue since problem seems to be fixed. If not please comment and I'll reopen this issue

**Comment by VanCoding** [comment]
I quickly checked it with the newest Desktop Editors (5.2.83.470) and the problem is still there. Or was this only fixed for DocumentServer?

I had a look a the commit log of PdfWriter, but I didn't have the impression there was a commit that should fix this.

**Comment by ShockwaveNN** [comment]
@VanCoding Sorry, we take an another look at your case and agree this is not right, we'll try to fix it.

**Comment by VanCoding** [comment]
Ok, thanks :)
I think the best fix will be to support PNGs instead of converting them to JPEG.

Did you forget to reopen the issue?

**Comment by K0R0L** [comment]
PNG can not be embedded in PDF. We code color channels as JPEG, and transparency - separately. Fully transparent pixels MS Office makes white. Now we have it.

https://github.com/ONLYOFFICE/core/commit/826be463f50a947e0ec1a3128abb85341893cb88

**Comment by ShockwaveNN** [comment]
I leave this issue opened until we public release fixed version

**Comment by VanCoding** [comment]
@K0R0L 
> PNG can not be embedded in PDF. We code color channels as JPEG, and transparency - separately. Fully transparent pixels MS Office makes white. Now we have it.
> 
> [ONLYOFFICE/core@826be46](https://github.com/ONLYOFFICE/core/commit/826be463f50a947e0ec1a3128abb85341893cb88)

Thanks! That was fast :)

You're right. PNG cannot be embedded directly into PDF, but images can still be embedded into a PDF losslessly by using flatedecode and optionally predictor encoding, which does about the same as PNG does internally.

MS Office, for example, does not convert PNG images to JPEG when saving as PDF. And that's important, because logos and stuff like that looks bad after converting to JPEG. And logos are probably the most common type of images in a docx-file.

We already had people complain about this. It's not suuper important, but still a thing you might need to keep in mind.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
