### ISSUE TITLE
An error has occured while opening the file sometime on document server with nodejs file storage

### ISSUE THREAD

**Issue by sandeepjangir** [ONLYOFFICE/DocumentServer#1413]
**Do you want to request a *feature* or report a *bug*?**: Bug

**DocumentServer version:**: 6.4.0

**Operating System:**: Ubuntu

We have document server install on ubuntu and we are running nodejs service as document storage service. But at sometime when we try to load the file stored nodejs storage service we getting an error "An error has occured while opening the file".

we have integrated doceditor api on the client side for viewing the file.

PS> File are working sometimes and sometime not.

we have have provided you the document storage service default.json configuration file and the logs.

Sandeep Jangir

[onlyoffice-logs.zip](https://github.com/ONLYOFFICE/DocumentServer/files/7115916/onlyoffice-logs.zip)

**Comment by ShockwaveNN** [comment]
Hi

> DocumentServer version:: 3

I don't think this is correct version. Please specify version in more details

> "An error has occured while opening the file"

This usually mean that DocumentServer cannot access file which it try to open. This maybe network/firewall error or something else

I don't see any specific error in your logs, do you enabled extended logs? I don't think this is requred in your case, error like your's should be visible in default log level

And please attach all log file, not only one of them. Log file located at `/var/log/onlyoffice`

**Comment by sandeepjangir** [comment]
@ShockwaveNN 

I have updated the version the correct one is 6.4.0 and I am attaching the logs here.

[backup-log.zip](https://github.com/ONLYOFFICE/DocumentServer/files/7116527/backup-log.zip)

**Comment by ShockwaveNN** [comment]
1. I don't see any partiucalr errors, because seems you enabled debug level logs and there is a lot messages

I think it's better to disable and leave default option `WARN` specified in `/etc/onlyoffice/documentserver/log4js/production.json`  file or any other place you've edit them
And replace your problems and send more clear logs

2. Could you see for error in Chrome Debug Tools in console section then `"An error has occured while opening the file".` happens

**Comment by sandeepjangir** [comment]
I have done the necessary changes on the server and seen that there is no error logs on the server and couple of errors are in dev console which's screenshot I am attaching here.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/14825242/132234766-e8338940-084d-4f19-84f8-335961c5af7b.png)

**Comment by ShockwaveNN** [comment]
I can see similar errors in my installation by the are not red, but just a warnings

![Screenshot_20210906_181411](https://user-images.githubusercontent.com/668524/132237634-b9a1fdf7-d584-415c-9d22-36cce5503eef.png)

This is strange

> running nodejs service as document storage service

Do you mean you've implemented your own nodejs storage server or used our default one?

**Comment by sandeepjangir** [comment]
Yes I have used my own nodejs storage server.

**Comment by ShockwaveNN** [comment]
I think problem in your server, you should compare our own default server with your code

Without ability to simulate your error on my hardware I don't think I've any idea that happened

**Comment by sandeepjangir** [comment]
I have found the issue, I was sending same key in config to only office so sometime files were working and sometimes not.

**Comment by ShockwaveNN** [comment]
@sandeepjangir Yes, this seems like the reason of strange behavior

In that case I'll close this issue
