### ISSUE TITLE
the docx|doc file,The title is not displayed

### ISSUE THREAD

**Issue by lzeqian** [ONLYOFFICE/DocumentServer#1417]
the doxc file,The title is not displayed
the show result: https://s3.bmp.ovh/imgs/2021/09/154f2173c905ffa3.png
the version: v6.2.0

**Comment by ShockwaveNN** [comment]
Hi, this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1368

Already fixed, please upgrade to latest stable version
