### ISSUE TITLE
Freeze Pane for spreadsheet

### ISSUE THREAD

**Issue by raphson93** [ONLYOFFICE/DocumentServer#142]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Freeze pane for spreadsheet
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
4.4.1.38, chrome in windows 10 pro. Yes

**Comment by ShockwaveNN** [comment]
Freeze pane is already avaiable in Spreadsheet Editor for long time.
Try open context menu for any cell and press `Freeze panes` entry

**Comment by raphson93** [comment]
when i tried to view the spredsheet online using onlyoffice (with freeze pane enabled in microsoft excel), the freeze pane is gone

**Comment by ShockwaveNN** [comment]
@raphson93 Can you attach example file for this problem?

**Comment by trofim24** [comment]
@raphson93
Because from you there is no answer, I close the issue. If the problem persists, re-open the issue or start a new one.
