### ISSUE TITLE
/5.5.3-39/web-apps/vendor/requirejs/require.js Garbled code

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1421]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
Garbled code when loading / 5.5.3-39/web-apps/vendor/requirejs/require.js script

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
docker pull onlyoffice/documentserver:5.5.3
sudo docker run -i -t -d -p 8706:80 onlyoffice/documentserver:5.5.3

```js
new window.DocsAPI.DocEditor(this.id, {
  document: {
    fileType: 'docx',
    key: '18NAFE233291',
    url: `${docHost}:7701/static/1.docx`,
    title: '1.docx'
  },
  documentType: 'text',
  editorConfig: {
    callbackUrl: domainUrl
  }
})
```
This is an error message prompted by the web page
![image](https://user-images.githubusercontent.com/56250514/132828404-54d158b0-ac20-4f09-bfb9-49a0395e3e78.png)

This is the return value of my view request
![image](https://user-images.githubusercontent.com/56250514/132828531-061bee59-612d-4901-a962-9a2a54bc48a1.png)

**What is the expected behavior?**
The script can be loaded normally and displayed

**Did this work in previous versions of DocumentServer?**
I have no problem with the same code in version 6.3.1

**DocumentServer version:**
5.5.3-39

**Operating System:**
macOS Mojave 10.14.5

**Browser version:**
Chrome@93.0.45xxx

**Comment by ShockwaveNN** [comment]
Hi

> I have no problem with the same code in version 6.3.1

> DocumentServer version: 5.5.3-39

And that your expectations of us to do? v5.5.3 is old and unsupported

**Comment by bszhct** [comment]
I have no problem using version 6.3.1. I expect it can be used normally on version 5.5.3. Do you mean that it is not supported even if there is a problem, it will not be fixed?

**Comment by bszhct** [comment]
@ShockwaveNN

**Comment by ShockwaveNN** [comment]
@bszhct Yes, we only release bug fixes to latest stable release - it's our release flow. In your case it's not event one or two releases old - v5.5.3 it's 4 major and  14 bugfix release old

**Comment by bszhct** [comment]
...OK

**Comment by ShockwaveNN** [comment]
If you got no other questions - I'll close this issue
