### ISSUE TITLE
import my own pptx, execute(Duplicate Slide) error 

### ISSUE THREAD

**Issue by larrychen8276** [ONLYOFFICE/DocumentServer#1423]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
 execute Duplicate Slide
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/3021516/133189490-231f35b1-4b67-4d3e-8ffc-2d0ce5729bb1.png)

![image](https://user-images.githubusercontent.com/3021516/133189406-fba29db0-78e8-47eb-8ae4-c72579807fb8.png)

**What is the expected behavior?**
can copy a new slide
**Did this work in previous versions of DocumentServer?**
I'm not sure
**DocumentServer version:**
Document Editor Version 6.4.0
**Operating System:**
Windows 10
**Browser version:**
Version 93.0.4577.63 (Official Build) (64-bit)

#### Attach pptx File

[2020_11_23.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/7158735/2020_11_23.pptx)

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/4e6fa8127d94c44415b858078606961d02148905) in future release.

**Comment by larrychen8276** [comment]
cool

**Comment by ShockwaveNN** [comment]
@larrychen8276 I'll leave this issue opened until we release fixed as stable version

**Comment by ShockwaveNN** [comment]
DocumentServer v6.4.1 is released and this problem should be fixed
