### ISSUE TITLE
How to pass custom business parameters to plug-ins

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1424]
**Do you want to request a *feature* or report a *bug*?**
feature?

**What is the current behavior?**
Custom parameters cannot be passed to plugins through onlyoffice API

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I need to write a custom plug-in to implement the three functions of abc. If the "type" obtained from "location.href" is equal to 1 to display a function, and 2 to display b function, because "onlyoffice editor" is embedded in the page through an iframe, "Onlyoffice plugin" cannot directly read the external "location.href" field inside. Is there a corresponding method in the onlyoffice API that can obtain the external "type" parameter inside?

**What is the expected behavior?**
I can pass some custom parameters to the plugin through the onlyoffice API

**Did this work in previous versions of DocumentServer?**
I have no idea

**DocumentServer version:**
6.3.1

**Operating System:**
macOS Mojave 10.14.5

**Browser version:**
Chrome@93.0.45xxx

**Comment by ShockwaveNN** [comment]
@askonev Please take a look, but personally I don't quite understand the request

**Comment by bszhct** [comment]
Sorry, let me describe in detail:

I have a page: http://30.xx.xx.xx:9901/document/editor?id=1

This page uses onlyoffice, because onlyoffice is loaded to the page through an iframe, its address is: http://30.xx.xx.xx:8701/web-apps/apps/documenteditor/main/index.html? _dc=6.3.1-32&lang=zh-CN&customer=ONLYOFFICE&frameEditorId=editor-1872208&parentOrigin=http://30.xx.xx.xx:9901

My question is: How can I pass the "id=1" parameter into the iframe? Does onlyoffice have a corresponding API?

@ShockwaveNN

**Comment by ShockwaveNN** [comment]
Thanks, it's clear to me now that you want, but I don't know if this possible

@askonev take a look at your issue as soon as he got free time

**Comment by bszhct** [comment]
Ok thanks for reply

**Comment by bszhct** [comment]
Can you help me take a look during your busy schedule, thanks @askonev

**Comment by askonev** [comment]
@bszhct, nice to meet you! If I understood you correctly, then this data can be silenced inside the plugin like this:

```js
(function(window, undefined){

         window.Asc.plugin.init = function()
    {
        console.log(window.parent.location);
        break;
    
})(window, undefined);
```
The output will be similar to the given example

```js
ancestorOrigins: DOMStringList {0: 'http://ip', length: 1}
assign: ƒ assign()
hash: ""
host: "ip"
hostname: "ip"
href: "http://ip/6.4.0-121/web-apps/apps/documenteditor/main/index.html?_dc=6.4.0-121&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=http://ip"
origin: "http://ip"
pathname: "/6.4.0-121/web-apps/apps/documenteditor/main/index.html"
port: "port"
protocol: "http:"
reload: ƒ reload()
replace: ƒ replace()
search: "?_dc=6.4.0-121&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=http://ip"
toString: ƒ toString()
valueOf: ƒ valueOf()
Symbol(Symbol.toPrimitive): undefined
```

**Comment by bszhct** [comment]
Nice to meet you too! Through window.parent.location, only the host of the parent can be obtained, and the parameters after the question mark of the parent link cannot be obtained.

For example, I have a page that uses onlyoffice, the address is: http://ip/document/editor?id=1, I want to pass the "id=1" parameter to onlyoffice

**Comment by bszhct** [comment]
@askonev

**Comment by bszhct** [comment]
Can you help me take a look during your busy schedule, thanks. @ShockwaveNN

**Comment by ShockwaveNN** [comment]
We'll have a look as soon as we able. Your problem is not very trivial.
If.you want guarantee help - it's better buy license with support. Github support is voluntary and not in high priority

**Comment by bszhct** [comment]
Okay, thanks for your reply! Looking forward to the official solution to this problem, we are considering whether to buy

**Comment by ShockwaveNN** [comment]
If you really consider buying our porduct - I think a better and quick solution - contact support via support@onlyoffice.com and discuss possibility

**Comment by askonev** [comment]
HI @bszhct 
From your window, in which the ONLYOFFICE editor is open, you can get only the src of this screen. All other information is blocked by the browser security system. Currently, we are not planning to implement this in near future, but if planning to buy a license - better discuss this specific situation with the sales team

**Comment by bszhct** [comment]
OK

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
