### ISSUE TITLE
html page automaticall scrolls to position of Document Editor

### ISSUE THREAD

**Issue by scholar-xia** [ONLYOFFICE/DocumentServer#1425]
After my page is loaded, my onlyoffice is at the bottom of the page. When onlyoffice loads the excel file, the browser automatically scrolls to the excel display position. How do I set up onlyoffice so that the browser does not automatically scroll to the onlyoffice iframe element position .

**Comment by ShockwaveNN** [comment]
Hi, please fill out the issue template completely, with versions of your product, host os, and other data

And please provide HTML which we can check and reproduce your situation

**Comment by ShockwaveNN** [comment]
I think we've reproduced the problem with scrolling, I've created issue 52732 in our private issue tracker

**Comment by askonev** [comment]
@scholar-xia added a parameter to the configuration that prohibits the editor from intercepting the focus

https://api.onlyoffice.com/editors/config/editor/customization#integrationMode

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
