### ISSUE TITLE
The picture with Chinese characters displayed in onlyOffice is lost at noon

### ISSUE THREAD

**Issue by baoyuping** [ONLYOFFICE/DocumentServer#1426]
**Do you want to request a *feature* or report a *bug*?**
This is a bug
**What is the current behavior?**
Preview word with Chinese picture with onlyOffice, the Chinese on the picture is lost  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use WPS to paste the pictures with Chinese characters into Word and use onlyOffice to preview
![image](https://user-images.githubusercontent.com/75818314/133371257-1a12b524-4efb-4a5d-b07c-f96c58790630.png)

This is the document in question
[新建 Microsoft Word 文档 (2).docx](https://github.com/ONLYOFFICE/DocumentServer/files/7167219/Microsoft.Word.2.docx)

**What is the expected behavior?**
Images with Chinese characters will display normally in the preview
**Did this work in previous versions of DocumentServer?**
My current version is 6.3.1
**DocumentServer version:**
6.3.1
**Operating System:**
win10 X64
**Browser version:**
Google Chrome 91.0.4472.124

**Comment by ShockwaveNN** [comment]
@TatianaKirillova please take a look, I've got similar result as on screenshot

**Comment by TatianaKirillova** [comment]
Hello, **@baoyuping**
Thanks for your request!
I can confirm that the problem exists. I created ticket 52578 in our private  tracker with your proposal.

**Comment by TatianaKirillova** [comment]
Hello, @baoyuping!
The problem has been fixed and will be included in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
