### ISSUE TITLE
Call the GetFooter() method to report an error

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1427]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
Call the GetFooter() method to report an error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```js
window.Asc.plugin.info.recalculate = true
window.Asc.plugin.executeCommand('command', [
  '(function () {\n',
  '  var oDocument = Api.GetDocument()',
  '  var sections = oDocument.GetSections()',
  '  console.log(sections, sections.length)', // Output: 2
  '  console.log(sections[0].GetFooter)', // ƒ (vc,Hc){if("title"===vc)var Jb=this.Uu.mv;else if("even"===vc)Jb=this.Uu.Fv;else if("default"===vc)Jb=this.Uu.bw;else return null;null===Jb&&!0===Hc&&(Hc=vd(),Jb=new Tj(Hc.UAa(),Hc,Hc.ob,hs),"title"…
  '  try {',
  '    console.log(sections[0].GetFooter("default", true))',
  '  } catch (err) {',
  '    console.error(err)', // TypeError: Cannot read properties of undefined (reading 'aa')
  '  }',
])
```
The error message of the console:

![image](https://user-images.githubusercontent.com/56250514/133545350-40e73acd-9229-4de4-8e90-b528225dcff7.png)

**What is the expected behavior?**
Call GetFooter() to get the return value normally

**Did this work in previous versions of DocumentServer?**
I have no idea

**DocumentServer version:**
6.3.1

**Operating System:**
macOS Mojave 10.14.5

**Browser version:**
Chrome@93.0.45xxx

**Comment by ShockwaveNN** [comment]
@askonev please take a look

**Comment by bszhct** [comment]
Can you help me take a look during your busy schedule? thanks @askonev

**Comment by askonev** [comment]
@bszhct  Hi! This problem has already been resolved, so I advise you to update to the latest version `6.4` of the editor.

Also, I advise you not to use the [executeCommand](https://api.onlyoffice.com/plugin/executecommand) method because it is deprecated. Please use the [callCommand](https://api.onlyoffice.com/plugin/callcommand) method.

Here is a working example:

```js
(function(window, undefined){

         window.Asc.plugin.init = function()
    {

                // call command without external variables
                this.callCommand(function() {
                    var oDocument = Api.GetDocument();
                    var sections = oDocument.GetSections();
                    console.log('sections length ' + sections.length);
                    try {
                        oFooter = sections[0].GetFooter("default", true);
                        console.log('oFooter => ' + oFooter.GetClassType());
                        oParagraph = oFooter.GetElement(0);
                        oParagraph.AddText("This is a page footer");
                    } catch (err) {
                        console.error(err);
                    }
                }, true);
         break;
    }

})(window, undefined);
```

**Comment by bszhct** [comment]
Ok thank you very much, i'll give it a try

**Comment by bszhct** [comment]
After I upgraded the onlyoffice version to 6.4.0, calling sections[0].GetFooter("default", true) did not report an error.

But I encountered another situation: the same docx file with two pages, I call oDocument.GetSections().length method, I output 2 in version 6.3.1 and output 1 in version 6.4.0.@askonev

**Comment by bszhct** [comment]
Doesn't the GetSections() method get every page of the document? For example, if my docx document has 10 pages, then GetSections().length will output 10. Did I understand it wrong?

**Comment by ShockwaveNN** [comment]
> I call oDocument.GetSections().length method, I output 2 in version 6.3.1 and output 1 in version 6.4.0

I think this is a completely separate issue so please create a new one, since the problem with GetFooter is resolved - I closing this issue
