### ISSUE TITLE
Insert Slide [Presentation] [feature] 

### ISSUE THREAD

**Issue by larrychen8276** [ONLYOFFICE/DocumentServer#1429]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
I can insert a slide template, like 
https://github.com/pipipi-pikachu/PPTist
display website :  https://pipipi-pikachu.github.io/PPTist/ 
![image](https://user-images.githubusercontent.com/3021516/134113908-1646ebc6-7328-4cd8-b58b-b5ae8c4a66d0.png)

it can be export json data : 
![image](https://user-images.githubusercontent.com/3021516/134114474-31983793-5c96-4b91-9aac-d1c6a0a29f26.png)

json file format
[pptist_slides.txt](https://github.com/ONLYOFFICE/DocumentServer/files/7200417/pptist_slides.txt)

**Comment by ShockwaveNN** [comment]
Could you provide a little bit more description, all description of https://github.com/pipipi-pikachu/PPTist is on Chinese and we do not understand it at all

Is this json format is used to store single slide data?
Is any other application except of PPTist is support this format? Libreoffice/Ms Office?

**Comment by larrychen8276** [comment]
> Could you provide a little bit more description, all description of https://github.com/pipipi-pikachu/PPTist is on Chinese and we do not understand it at all
> 
> Is this json format is used to store single slide data?
> Is any other application except of PPTist is support this format? Libreoffice/Ms Office?

yes, like powerpoint template
![image](https://user-images.githubusercontent.com/3021516/134146462-76661d92-b88b-455b-8af6-4ab4ef1b2b3b.png)
![image](https://user-images.githubusercontent.com/3021516/134146606-ccb6edcc-b137-466b-80c3-875042ad1da0.png)

**Comment by ShockwaveNN** [comment]
Could you record a video how to add this file `pptist_slides.txt` to MS PowerPoint? We've tried to - but seems it's not working

**Comment by larrychen8276** [comment]
> Could you record a video how to add this file `pptist_slides.txt` to MS PowerPoint? We've tried to - but seems it's not working

i want to make different template, like this
https://api.onlyoffice.com/docbuilder/presentationapi/apipresentation/addslide
![image](https://user-images.githubusercontent.com/3021516/134181228-5c5c0197-ebab-49db-a328-0505a1dd2891.png)

**Comment by larrychen8276** [comment]
> We try to complete our picture of this software you mention, so please answer my question with video - how did you add a theme from `pptist_slides.txt` to MS PowerPoint?
> 
> If you just need to add a template to DocumentServer - you should create template in MS Office and add it via [instruction here](https://helpcenter.onlyoffice.com/installation/docs-community-add-themes-linux.aspx)

it can't add to MS PowerPoint , i saw the author had achieve the function (export to json) and discuss consider to  use PPTX2HTML library to implement import json to html, so i ask would you consider adding this feature
https://github.com/pipipi-pikachu/PPTist/issues/57
![screenshot-github com-2021 09 21-22_29_51](https://user-images.githubusercontent.com/3021516/134196687-c67d8a67-87f4-449b-847c-87f39a58082c.png)

**Comment by ShockwaveNN** [comment]
Sorry, I don't think we will be adding some feature for the unknown format of themes only for some software which even do not have documentation in English
