### ISSUE TITLE
Presentation editor, settings plugin does not work on slideshow mode.

### ISSUE THREAD

**Issue by gkokoszkaFP** [ONLYOFFICE/DocumentServer#1433]
**What is the current behavior?**
settings (watermark) plugin is not displayed in presentation slideshow mode.

**What is the expected behavior?**
watermark should be displayed on slideshow of presentation.

**DocumentServer version:**
Developer Edition 6.4.0 - docker image

**Operating System:**
Windows running Docker Desktop

**Browser version:**
Chrome, but it doesn't really work on any browser.

**Comment by igwyd** [comment]
Hello @gkokoszkaFP, thank you for your report, i can confirm this is bug, 52759 in our private issue tracker.

**Comment by gkokoszkaFP** [comment]
Hello @igwyd thanks for response, is there any way to "fix" this on developer site? If not is it possible to somehow disable slideshow all together?

**Comment by igwyd** [comment]
@gkokoszkaFP, sorry no idea, but i will comment here when receive a response from the plugins developer. 
Impossible to disable the slideshow at this moment, no such option.

**Comment by Xiaoyoou** [comment]
Hello @igwyd Is there any news about this plugin?

**Comment by igwyd** [comment]
Hi @Xiaoyoou, unfortunately there is no news, this task has a low priority at the moment. You can try contacting sales at sales@onlyoffice.com to speed up it.

**Comment by igwyd** [comment]
Hello @Xiaoyoou @gkokoszkaFP It's fixed at: https://github.com/ONLYOFFICE/sdkjs/commit/12e7079f986524d459b4c91d4deac9608d831bf2 and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
