### ISSUE TITLE
Integration with Drawio

### ISSUE THREAD

**Issue by Pelicans-git** [ONLYOFFICE/DocumentServer#1436]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

# Background
OnlyOffice is a fantastic tool and the online editors are excellent. The versioning of these files in OnlyOffice is exceptional.
The one thing missing from the suite, is a diagramming tool.

Drawio is an open source online diagramming tool that like OnlyOffice, is extremely popular. See what the online interface looks like [here](https://app.diagrams.net/) and find the project [here.](https://github.com/jgraph/drawio)

# Feature Request
Support for Drawio in OnlyOffice. When a drawio file is clicked, OnlyOffice opens the editor. When the file is saved, it is saved back in OnlyOffice.

**Comment by Rita-Bubnova** [comment]
@Pelicans-git, We added the plugin draw.io [here](https://github.com/ONLYOFFICE/plugin-drawio).
We would be interested to hear your opinion on it.

**Comment by ShockwaveNN** [comment]
I'll close this issue then, all question/troubles about this plugin should be reported as issues in its repo

**Comment by Pelicans-git** [comment]
> @Pelicans-git, We added the plugin draw.io [here](https://github.com/ONLYOFFICE/plugin-drawio). We would be interested to hear your opinion on it.

Thanks - we'll test and revert.
