### ISSUE TITLE
cd core/Common/3dParty && ./make.sh

### ISSUE THREAD

**Issue by kalai6095** [ONLYOFFICE/DocumentServer#144]
##Hi, this kalaiselvan, i compiled Document Server for my local server while running this command  **cd core/Common/3dParty && ./make.sh**  i am getting the issue. how can i fix  this?

![documentserver](https://user-images.githubusercontent.com/6815038/28671269-b2f588b0-72f9-11e7-85a8-ae297151554c.png)

**Comment by ShockwaveNN** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/118#issuecomment-317392992

**Comment by kalai6095** [comment]
Thanks
