### ISSUE TITLE
Are there any plans to use woff fonts in the future?

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/DocumentServer#1440]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Now the loaded fonts are very large, which causes the page to load slowly without cache. Using woff fonts should improve

**DocumentServer version:**
6.4.1

**Operating System:**
MacOs 11.5.2

**Browser version:**
Chrome 93.0.4577.82

**Comment by ShockwaveNN** [comment]
Are you talking about some specific font?

I've just checked this random font I googled in woff format - http://google-webfonts-helper.herokuapp.com/fonts/lateef?subsets=latin

`lateef-v18-latin-regular.woff`

Mounted to DocumentServer as described in  [instruction](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx)and it work correctly 

![image](https://user-images.githubusercontent.com/668524/135227375-16088130-ec5b-48c5-a900-2732b24c7e9b.png)

**Comment by Malenconiaprincep** [comment]
Thanks for your answer !
Yes, I use some chinese fonts is .ttf end , but the font is so big size, I try to some chinese ttf convert to woff later. I have a doubt, why don't the official core-fonts use woff?

**Comment by ShockwaveNN** [comment]
I'm not sure, maybe some limitations or historical reason. We are not very good in Chinese at all, so I don't think we ever fought about this

**Comment by Malenconiaprincep** [comment]
Isn't the Latin font also woff smaller than ttf?

**Comment by ShockwaveNN** [comment]
We do not use woff or ttf directly, we convert them to our internal format

So I don't think if original font smaller - our internal format will change size

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
