### ISSUE TITLE
missing apps/common folder in debian bundle

### ISSUE THREAD

**Issue by HolgerHees** [ONLYOFFICE/DocumentServer#1441]
I run the latest official onlyoffice docker container which is using your debian package. If I open the editor from nextcloud, the file `/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/index_loader.html` is loaded. This file contains a javascript include `<script src="../../common/main/lib/util/htmlutils.js"></script>` but this common folder is missing and I get a 404.

**Comment by ShockwaveNN** [comment]
I think it's better to continue discussion at old issue until we figure out root case of problems

**Comment by HolgerHees** [comment]
my guess is that your debian bundle is missing a folder.

**Comment by ShockwaveNN** [comment]
@HolgerHees Seems this problem actual only for nextcloud and currently I don't know why and if we ever use this file
