### ISSUE TITLE
Hardening Cache-Output

### ISSUE THREAD

**Issue by aignerat** [ONLYOFFICE/DocumentServer#1444]
**Do you want to request a *feature* or report a *bug*?**
Feature/Security-Bug

**What is the current behavior?**
Using the url https://nextcloudurl/only/cache/files you see a stacktrace that can help an attacker to get access to unauthorized data, a customized error-page would be useful

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just type in the url and you see a stacktrace with onlyoffice-internal paths
<img width="1198" alt="onlyoffice_stacktrace" src="https://user-images.githubusercontent.com/46312655/135260282-d6d5e2a8-3bb3-4c86-9993-ab9ca57e2f07.png">

**What is the expected behavior?**
Don't output sensible configuration-data

**Did this work in previous versions of DocumentServer?**
I don't think so

**DocumentServer version:**
5.4.2 and 6.2.2

**Operating System:**
Centos 7

**Browser version:**
not relevant, on every browser the same as this is server-side functionality without javascript

**Comment by ShockwaveNN** [comment]
@igwyd please take a look

**Comment by igwyd** [comment]
Hello @aignerat, i can't reproduce your error, in my case i see error 404. I try with Nextcloud 22.1.1 in docker with onlyoffice app for nextcloud 7.1.2, onlyoffice-documentserver 6.2.2 and lasted release 6.4.1. Can you describe the installation in more detail?

**Comment by ShockwaveNN** [comment]
Also as a side note from me - do @aignerat ever install Nextcloud Community DocumentServer extension? Because I think path `/only/cach` may be a leftover of this installation

**Comment by aignerat** [comment]
hey, thx for looking into this matter so quickly, i have to work with a nc 19, I just saw an old connector on nexcloud-side, I will update this to 6.4.2 and tell you if the stacktrace is still visible, I know that nc 19 is out of life from nextcloud-side

br chris

**Comment by aignerat** [comment]
nope, with 6.4.2 the stacktrace is still shown, so this issue seems to be fixed with 7+ I try to backport the latest version as next step

**Comment by aignerat** [comment]
backport of the connector-version 7.1.2 sadly shows the same stacktrace

**Comment by ShockwaveNN** [comment]
@aignerat Maybe some incorrect configured nginx?

**Comment by aignerat** [comment]
nextcloudside - apache with haproxy
documentserverside - nginx
thx for the tip, any suggestions where I should start to check the configuration? Seems like its documentserverside as the stacktrace looks like java

**Comment by ShockwaveNN** [comment]
> any suggestions where I should start to check the configuration

I think you should check if any new server you setup with similar configuration has save error messages, because for us - new setup has no, so maybe yours is leftowers of some unsuccessful configuration attempts

> Seems like its documentserverside as the stacktrace looks like java
No, it's our nodejs stacktrace,

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
