### ISSUE TITLE
[BUG] Editing highlighted email addresses is not updating their hyperlink.

### ISSUE THREAD

**Issue by RDKRACZ** [ONLYOFFICE/DocumentServer#1449]
Originally reported in https://github.com/ONLYOFFICE/DocumentServer/issues/1448.

**DesktopEditors version** and **Operating System**
6.3.1-2 from AUR - Arch Linux

![image](https://user-images.githubusercontent.com/43277609/135442370-bf951c9f-a952-4fb2-b5b5-41a470a8461d.png)

**Comment by Rita-Bubnova** [comment]
Hello, @RDKRACZ. 
Could you describe your problem in more detail?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
