### ISSUE TITLE
Websocket Error and can't save when delete a row in spreadsheet

### ISSUE THREAD

**Issue by leuedaniel** [ONLYOFFICE/DocumentServer#1450]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When i delete a row in a spreadsheet i can't save the .xlsx file and see websocket errors.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I open an existing .xlsx file and delete the row 28, after that i press on save but nothing happens. I see these websocket errors
![websocketerror](https://user-images.githubusercontent.com/44936305/135588755-086b4cc0-5d71-4e81-b1e4-a8a6526e8ac2.png)

**What is the expected behavior?**
I can delete a row and save the spreadsheet
**Did this work in previous versions of DocumentServer?**
I think so
**DocumentServer version:**
6.4.0.121
**Operating System:**
Win 10
**Browser version:**
Chrome 94.0.4606.71

**Comment by ShockwaveNN** [comment]
Hi, is this problem happens regularuly?

Usually those errors happens then something broken on back-end side, not on client

Is there any errors at `/var/log/onlyoffice/`? I think there should be restarts or some errors in nginx log. 
Is nginx using default settings?


And second possible case - changes is too big, so there raising 413 error
For detecting this we need original file and step-by-step guide how to raise same erorr

**Comment by leuedaniel** [comment]
There are no errors in nginx.error.log. I run Onlyoffice in a Docker with default nginx settings.
Here the File.
[2021_Spesen Arbeitsgruppen HGV.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/7265604/2021_Spesen.Arbeitsgruppen.HGV.xlsx)
I will delete row 27 in onlyoffice.

**Comment by ShockwaveNN** [comment]
I've checked my local setup of Docker v6.4.0.121 and everything seems fine deleting 27 row

So

1. Please take a look at other browser, maybe this is browser specifc error
2. If possible - setup another server temporarely and check this problem via inegrated example at `http://docserverurl/welcome` and see if this problem persists

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
