### ISSUE TITLE
Docker : Fatal Error due to Permissions Issue. Easily Fixed

### ISSUE THREAD

**Issue by grizzy255** [ONLYOFFICE/DocumentServer#1452]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Server fails to start

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

2021-10-04 04:10:50.135 UTC [135] FATAL: private key file "/etc/ssl/private/ssl-cert-snakeoil.key" has group or world access 
2021-10-04 04:10:50.135 UTC [135] DETAIL: File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root. 
2021-10-04 04:10:50.143 UTC [135] LOG: database system is shut down pg_ctl: could not start server Examine the log output. ...fail! * Starting RabbitMQ Messaging Server rabbitmq-server ...done. Waiting for connection to the localhost host on port 5432 
Waiting for connection to the localhost host on port 5432 
Waiting for connection to the localhost host on port 5432 

It is easily fixed by chmod 640 etc/ssl/private/ssl-cert-snakeoil.key

**What is the expected behavior?**
Server should start

**Did this work in previous versions of DocumentServer?**
Yes

**DocumentServer version:**

root@a24f64d9f5f5:/# uname -a
Linux a24f64d9f5f5 5.13.8-Unraid #1 SMP Wed Aug 4 09:39:46 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

root@a24f64d9f5f5:/# supervisorctl version
4.1.0

**Operating System:**
Unraid

**Browser version:**
Safari

**Comment by ShockwaveNN** [comment]
I don't think we should change permissions of file - since I think this file is mounted via docker mount - changing it's permissions inside container may make this file innacassable on host os

**Comment by grizzy255** [comment]
Apologies I don't understand - I am only mounting the following directories in the container to my host 

/var/lib/onlyoffice to a path within the host
/var/lib/postgresql to a path within the host
/usr/share/fonts/ to a path within the host
/tmp/ to a path within the host
/var/log/onlyoffice/ to a path within the host
/var/www/onlyoffice/Data/ to a path within the host

I am not mounting the /etc from the docker onto the host ?

**Comment by ShockwaveNN** [comment]
Ok, sorry, my bad

Seems I didn't read your message right, but anyways

1. `/etc/ssl/private/ssl-cert-snakeoil.key` file is not part of our app, so I think it's installed via some dependency, I don't think we should change its permission
2. I cannot reproduce your problem with `File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.` error on my system, so please provide a docker run command, preferable without any mounts, which will raise same error
On my docker system permissions on this file are:
```
root@ee375beaee59:/# ls -la /etc/ssl/private/ssl-cert-snakeoil.key
-rw-r----- 1 root ssl-cert 1704 Sep 19 19:55 /etc/ssl/private/ssl-cert-snakeoil.key
```

**Comment by grizzy255** [comment]
I will close this for now. I can't seem to replicate this after nuking the container and recreating it again. Thank you for looking thought though !

**Comment by ShockwaveNN** [comment]
Ok, gald to hear - feel free to reopen if you will be able to repdocue it
