### ISSUE TITLE
Request.JS error (Error: ESOCKETTIMEDOUT)

### ISSUE THREAD

**Issue by charnesp** [ONLYOFFICE/DocumentServer#1453]
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
I got a 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I usually got the following error when running the DocumentServer (Docker version):

Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**What is the expected behavior?**
No Socket timeout error

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
6.4.0
**Operating System:**
Linux / MacOS
**Browser version:**
Safari / Firefox / Chrome

**Comment by ShockwaveNN** [comment]
> I usually got the following error when running the DocumentServer (Docker version):

Could you show exact Docker run command or `docker-compose` file? Seems somewhere is network error

**Comment by charnesp** [comment]
My docker-compose looks like : 

`
  onlyoffice:
    image: "onlyoffice/documentserver"
    restart: always
    volumes:
      - /files/data/nextcloud/onlyoffice/custom_fonts:/usr/share/fonts/custom_fonts
    environment:
      - VIRTUAL_HOST=onlyoffice.XXX
      - LETSENCRYPT_HOST=onlyoffice.XXX
    networks:
      - webservices
`

I am behind a letsencrypt-nginx-proxy-companion. 

The nginx.conf is the following:

`
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
client_max_body_size 30g;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 443 ssl http2;
	access_log /var/log/nginx/access.log vhost;
	return 503;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}

# onlyoffice.XXX
upstream onlyoffice.XXX {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				## Can be connected with "webservices" network
			server 172.26.0.8:80;
}
server {
	server_name onlyoffice.XXX;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location /.well-known/acme-challenge/ {
		auth_basic off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name onlyoffice.XXX;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/onlyoffice.XXX.crt;
	ssl_certificate_key /etc/nginx/certs/onlyoffice.XXX.key;
	ssl_dhparam /etc/nginx/certs/onlyoffice.XXX.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/onlyoffice.XXX.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://onlyoffice.XXX;
	}
}
`

Thank you

**Comment by ShockwaveNN** [comment]
I think problem in your proxy - try to temporarily disable it and see if there is no such error

After that - try to remove most of keyts from config and see which key is the reason of this error

**Comment by charnesp** [comment]
Thanks, I will try that and come back to you.

**Comment by charnesp** [comment]
I switched to Traefik, everything now works. Thank you
