### ISSUE TITLE
Support WPD extensions files

### ISSUE THREAD

**Issue by AndyXheli** [ONLYOFFICE/DocumentServer#1458]
Hello it would be nice for onlyoffice to support wpd file extensions. The WPd file is extinction is used a lot when using WordPerfect application.

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer since support should be first introduced where

Could you attach an example document of this format?

**Comment by andyxheli** [comment]
Here you go. Please unzip the file. Let me know if you need anything else. Also thank you. 
[Labels.client info.zip](https://github.com/ONLYOFFICE/DocumentServer/files/7294482/Labels.client.info.zip)

**Comment by andyxheli** [comment]
@VladimirProkofiev52 any updates on this?

**Comment by ShockwaveNN** [comment]
@andyxheli Sorry, no updates. This is a low-priority task for us since we prefer to concentrate our development on OOXML formats, and adding a completely separate new format will take A LOT of time. If you don't agree with our priorities - feel free to contact sales@onlyoffice.com and discuss it

**Comment by ShockwaveNN** [comment]
I'll leave this issue open until we'll implement this feature

**Comment by andyxheli** [comment]
Hi @ShockwaveNN any updates on this?

**Comment by ShockwaveNN** [comment]
Sorry, no update, we'll post it there will be any news

https://github.com/ONLYOFFICE/DocumentServer/issues/1458#issuecomment-983389460

This statement still actual so nothing I can do here
