### ISSUE TITLE
Default plugins removal problem - Docker Image

### ISSUE THREAD

**Issue by gkokoszkaFP** [ONLYOFFICE/DocumentServer#1459]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Plugins stay on document editor even when removed from sdkjs-plugins folder. I can see in networking tab that plugins.json still have all plugins inside `pluginsData` entry.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Under folder with plugins
`\\wsl$\docker-desktop-data\version-pack-data\community\docker\overlay2\df41276bd7ad4c4a51b33280e732ce91e2e8d3a64ef79a0ca85b2c4225533e7d\diff\var\www\onlyoffice\documentserver\sdkjs-plugins`
i remove default plugins and leave only my custom ones.
VS Code with docker extension allow me to see inside container and it shows all plugins folders are still there (default ones) but they are empty.

Once document is reloaded with cache cleared i still see plugins tab and plugins that were supposed to be removed.

using `supervisorctl restart all` on docker image does not help.

Restarting container does not remove plugins from UI.
Stopping and Starting container recreates deleted plugins folders.

**What is the expected behavior?**
Once plugins are removed they should not be displayed inside plugins tab.

**Did this work in previous versions of DocumentServer?**
no idea

**DocumentServer version:**
onlyoffice-documentserver-de_6.4.1-45_amd64.deb

**Operating System:**
Windows running Docker Desktop

**Browser version:**
Any

**Comment by ShockwaveNN** [comment]
I've tried

So my steps

1. Setup docker documentserver in docker, all plugins are here:
![image](https://user-images.githubusercontent.com/668524/136196246-3ecd6219-3567-4b74-ba68-9db37b7c493a.png)

2. 
```
docker exec -it DocumentServer1a6beaf8-73a2-43c0-91d5-f0150689cba9 bash
cd /var/www/onlyoffice/documentserver/sdkjs-plugins
rm -rf highlightcode/ macros/ mendeley/ ocr/ photoeditor/ speech/ thesaurus/ translator/ youtube/ zotero/
```

3. Open browser and refresh page with CTRL+F5. All plugins are gone
![image](https://user-images.githubusercontent.com/668524/136196409-130a26f4-9b49-4a9a-9d56-f035f8e84db3.png)

Plugin tab is not displayed

So I cannot reproduce

**Comment by gkokoszkaFP** [comment]
Thanks alot, it seems that removing plugins folder via bash resolved issue :)
