### ISSUE TITLE
connect ECONNREFUSED 

### ISSUE THREAD

**Issue by kalai6095** [ONLYOFFICE/DocumentServer#146]
I am using ubuntu 16.0  for building document server everything work's fine and java integration example runs in windows machine but, I'm getting connection refused while opening a document 

![issue1](https://user-images.githubusercontent.com/6815038/28711353-ff1ba840-73a4-11e7-9fac-51b0cf62becf.png)
![issue2](https://user-images.githubusercontent.com/6815038/28711354-ff1f2d44-73a4-11e7-98ed-7f8db36f20f3.png)

**Comment by ShockwaveNN** [comment]
So you setup DocumentServer on one machine (Ubuntu) and Java example run on another (windows)?
If so - there is something wrong in your Java example config.
Seems DocumentServer trying to save document on localhost, but should save on ip_of_java_example

**Comment by kalai6095** [comment]
yeah! you are correct, ShockwaveNN. but In my case folder structure is like same as you mentioned above

**Comment by kalai6095** [comment]
![issue3](https://user-images.githubusercontent.com/6815038/28764198-78acb9cc-75e1-11e7-911e-0a89f58b6cad.png)

**Comment by ShockwaveNN** [comment]
Please, show content of your[ `settings.properties` ](https://github.com/ONLYOFFICE/document-server-integration/blob/master/web/documentserver-example/java/src/main/resources/settings.properties)

**Comment by kalai6095** [comment]
![img](https://user-images.githubusercontent.com/6815038/28769538-90b05d40-75f9-11e7-9f9e-ba591a08860b.png)

**Comment by ShockwaveNN** [comment]
Could you try to open java test example by IP, not by `localhost` in browser

**Comment by kalai6095** [comment]
like that also i tried  shockwaveNN
![img2](https://user-images.githubusercontent.com/6815038/28770888-76722b66-75fe-11e7-9b0a-3168a120e3a1.png)

**Comment by ShockwaveNN** [comment]
Could you try to setup Java Integration Example without using addition route `192.168.x.x:8085/editorexp`.
Additional routes not supported in Java Example. 
Try to setup it to use `192.168.x.x:8085/`

**Comment by kalai6095** [comment]
like that also i tried ShockwaveNN

**Comment by ShockwaveNN** [comment]
@kalai6095 Could you press "Ctrl+U" to open source code of editor page and find JSON data that should look like this:
```

"document": {
--
  | "title": "sample.docx",
  | "url": "https://192.168.x.x:8085/example/files/85.198.95.234/new.docx",
  | "fileType": "docx",
  | "key": "723250018",
  | "info": {
  | "author": "Me",
  | "created": "Mon Jul 31 2017"
  | },
  | "permissions": {
  | "comment": true,
  | "download": true,
  | "edit": true,
  | "review": true
  | }
  | },
```
And check that `url` value - `https://192.168.x.x:8085/example/files/85.198.95.234/new.docx`could be opened on document server machine without any errors (you should be able to `wget` it)

**Comment by kalai6095** [comment]
@ShockwaveNN  i tried my-url: wget  https://192.168.x.x:8085/example/files/85.198.95.234/new.docx returns 404

**Comment by ShockwaveNN** [comment]
@kalai6095 this is not right, you should be able to download this file freely.
Maybe there is troubles with access rights to this folder, like you run java server from admin first time, and after that run from user, or like so.

**Comment by kalai6095** [comment]
thank you @ShockwaveNN  now wget   https://192.168.x.x:8085/example/files/85.198.95.234/new.docx   now its works fine but still i can't able to open document  and 
i have some clarification in old DocumentServer version(3.0) i used in url  like below :
url: "http://192.168.x.x/ResourceService.ashx?path=temp_-114111126%2f-114111126.tmp&nocache=true&deletepath=temp_-114111126&filename=-114111126.tmp"

but here without ResourceService assigning direct url

**Comment by ShockwaveNN** [comment]
@kalai6095 `ResourceService.ashx` is deprecated, since in 3.0 we used `mono` to run DocumentServer, but now it all on `nodejs`.
So so far - you don't have 404 error for accesing files, but still cannot open documents with some other error?
What in logs and what error shown in browser?

**Comment by kalai6095** [comment]
i saw that  nodejs code @ShockwaveNN  and there is no log files in /var/log/onlyoffice/documentserver

converterservice has some ExitCode
![img3](https://user-images.githubusercontent.com/6815038/28822758-24911732-76d8-11e7-8fdc-ab7c3c3ebe2d.png)

**Comment by ShockwaveNN** [comment]
@kalai6095 Hm, this is one of most generic error that we have.
One of possible reason - you have some error while building `core` and `x2t` tool, that convert files not builded properly.


You can check that it work by this command on server - by converting any docx file to rtf. I've attached one
[04 Test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1190466/04.Test.docx)
```
wget -P /tmp https://github.com/ONLYOFFICE/DocumentServer/files/1190466/04.Test.docx
/var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t /tmp/04.Test.docx /tmp/04.Test.rtf
file /tmp/04.Test.rtf 
#  /tmp/04.Test.rtf: Rich Text Format data, version 1, unknown character set
```

Also 
```/var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t` command should show some help info

**Comment by kalai6095** [comment]
yeah! i think so, some error happened in core /x2t tool  i'll  rebuild it once again and check with you @ShockwaveNN

**Comment by kalai6095** [comment]
while running  `cd core/Common/3dParty && ./make.sh`  some error happen(like below) and terminated 

________ running '/usr/bin/python v8/tools/clang/scripts/update.py --if-needed' in '/home/sysadmin/DocumentServer/core/Common/3dParty/v8'
Updating Clang to 259396-1...
Clang is already up to date.

________ running '/usr/bin/python v8/build/gyp_v8' in '/home/sysadmin/DocumentServer/core/Common/3dParty/v8'
Updating projects from gyp files...

PYTHONPATH="/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/tools/generate_shim_headers:/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/build::/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/build/gyp/pylib:" \
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. -S.native -Dclang=0
make[1]: Entering directory '/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/out'
  LINK(target) /home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/out/native/mksnapshot
/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/third_party/binutils/Linux_x64/Release/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: unsupported reloc 42 against global symbol __gmon_start__
/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/third_party/binutils/Linux_x64/Release/bin/ld.gold: error: /usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS): unsupported reloc 42 against global symbol __dso_handle
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o(.init+0x7): error: unsupported reloc 42
/usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS):function atexit: error: unsupported reloc 42
collect2: error: ld returned 1 exit status
tools/gyp/mksnapshot.target.native.mk:252: recipe for target '/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/out/native/mksnapshot' failed
make[1]: *** [/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/out/native/mksnapshot] Error 1
make[1]: Leaving directory '/home/sysadmin/DocumentServer/core/Common/3dParty/v8/v8/out'
Makefile:312: recipe for target 'native' failed
make: *** [native] Error 2
cp: cannot stat './out/native/obj.target/tools/gyp/libv8_external_snapshot.a': No such file or directory
sysadmin@onlyoffice:~/DocumentServer/core/Common/3dParty$

**Comment by kalai6095** [comment]
thank you @ShockwaveNN  now it working fine without docker help and without any errors

**Comment by zmhbh** [comment]
@ShockwaveNN @kalai6095 
Hi ShockwaveNN and kalai6095, I got the same issue, "Download failed".

I used the same [Dockerfile](https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/master/Dockerfile-Ubuntu-16.04), the compilation is all good.
I use docker to run it in Machine A(10.173.3.124) and expose port 80. I can access welcome page.

Then I use your [java integration example](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/java), maven and deploy into tomcat in the same Machine A.

When I access it directly or from Machine B, I got the "Download failed" error.

In addition my document url is something like this: "http://10.173.3.124:8080/app_data/127.0.1.1/sample+%286%29.docx"

**"127.0.1.1"** looks very different. Could you please help me debug?
Thank you very much

**Comment by ShockwaveNN** [comment]
@zmhbh  Are you able to download `http://10.173.3.124:8080/app_data/127.0.1.1/sample+%286%29.docx` file on your Machine A and on some other machine?

**Comment by zmhbh** [comment]
@ShockwaveNN 
Thank you so much for your quick response. No, I'm not able to download this file. It shows tomcat 404 error.

**Comment by ShockwaveNN** [comment]
@zmhbh check your app folder, does this file exists on file system.

**Comment by zmhbh** [comment]
<img width="581" alt="screen shot 2017-08-09 at 1 40 19 pm" src="https://user-images.githubusercontent.com/9757323/29142972-6aa73d60-7d08-11e7-9a25-ab729a727e88.png">
This is the tomcat web app folder. 
You mean, I need to create "/app_data" folder in the system where I deploy tomcat?

**Comment by ShockwaveNN** [comment]
@zmhbh seems that there is some problem with file path, instead of creating `app_data` folder, they have `app_data\`  in their name. Sorry, I've absolutely no experience working with tomcat, but generally speaking - files should stored in app_data, maybe this help you. See https://github.com/ONLYOFFICE/DocumentServer/issues/146#issuecomment-318973576 - this is a correct file tree structure

**Comment by zmhbh** [comment]
@ShockwaveNN okay, I will try to figure that out. One thing, I want to know, app_data should be in document server machine or tomcat machine. Thanks!

**Comment by zmhbh** [comment]
@ShockwaveNN Thank you so much, I finally figure that out. It's related to "slash", Mac and Windows use different slash. I got to open the file correctly many times. However, it's not stable, sometimes, I get this error:
<img width="645" alt="screen shot 2017-08-09 at 3 40 10 pm" src="https://user-images.githubusercontent.com/9757323/29146987-224f406a-7d19-11e7-87ae-525de34e0e01.png">

and something in the console:
<img width="904" alt="screen shot 2017-08-09 at 3 40 26 pm" src="https://user-images.githubusercontent.com/9757323/29146993-2cabc498-7d19-11e7-8a56-4d57dc9667e7.png">

**Comment by ShockwaveNN** [comment]
@zmhbh I think there is some problems with your tomcat server, maybe it crashes and restarts. You should see logs for tomcat

**Comment by maxkadushkin** [comment]
could you show the console output when got stuck on 'loading document'?

**Comment by kalai6095** [comment]
@zmhbh  #146 [comment](https://github.com/ONLYOFFICE/DocumentServer/issues/146#issuecomment-321379790) is correct Its due path  instead of using sample (1).docx /sample (2).docx   use `UUID.randomUUID().toString+filename` or `System.currentTimeMillis()+filename`
