### ISSUE TITLE
OnlyOffice PDF viewer shows wrong glyphs

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#1463]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
![изображение](https://user-images.githubusercontent.com/20418709/137076086-4d16cf2f-690e-443b-89eb-9f67f8df2d58.png)

In any other pdf viewer it shows like this:
![изображение](https://user-images.githubusercontent.com/20418709/137076163-f2ec58f2-3316-497d-be80-a23530c306a6.png)
[Directum RX 4.0. Интеллектуальная обработка документов (веб-клиент)(v1).pdf](https://github.com/ONLYOFFICE/DocumentServer/files/7335333/Directum.RX.4.0.-.v1.pdf)

**DocumentServer version:**
6.3.2

**Operating System:**
any

**Browser version:**
any

**Comment by Rita-Bubnova** [comment]
I checked this issue in version 7.2.2.56 and it was fixed.

**Comment by DenisDeeSign** [comment]
DocumentServer v7.2.2 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
