### ISSUE TITLE
Restore unsaved document

### ISSUE THREAD

**Issue by wilkis3** [ONLYOFFICE/DocumentServer#1467]
**Do you want to request a *feature* or report a *bug*?**
Question / Bug

**What is the current behavior?**
* Some files were not closed and saved correctly by `documentserver-prepare4shutdown.sh`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Execute command `documentserver-prepare4shutdown.sh`
  * Get "Preparing for shutdown, it can take a lot of time, please wait... Done"
* Stop OnlyOffice Docker container
* Start an updated OnlyOffice instance

**What is the expected behavior?**
* OnlyOffice opening the latest updated version of the document

**Did this work in previous versions of DocumentServer?**
Yes, with Version 6.2.2

**DocumentServer version:**
6.4.0

**Operating System:**
Ubuntu 20.04

**Browser version:**
Firefox 93.0/Chromium 94.0

I still have the old database and App_Data directory. Can I import these old no unsaved files into the new OnlyOffice instance? Can I do a database migration or something else?

Possible relevant to issue #196 or #924

**Comment by ShockwaveNN** [comment]
@DenisDeeSign Please take a look - could those files be recovered?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by wilkis3** [comment]
> @DenisDeeSign Please take a look - could those files be recovered?

Yes, but with huge amount of work. I mean I have to copy entries for database and much more.

**Comment by wilkis3** [comment]
> @wilkis3, Sorry for the long wait. DocumentServer v8.1.3 is released. Is this issue relevant?

This Issue is not relevant.
