### ISSUE TITLE
Improve loading performance

### ISSUE THREAD

**Issue by jakobroehrl** [ONLYOFFICE/DocumentServer#1469]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
For  creating or opening a document I have to wait 8-10 seconds. 

**What is the expected behavior?**
Google and MS documents are loading in 2-5 sec.

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
onlyoffice/documentserver-ee 6.4.1

**Operating System:**
Linux, Onlyoffice Docker Enterprice Version

**Browser version:**
latest crome and firefox

**Comment by jakobroehrl** [comment]
Thanks a lot!
So the network speed could be the problem but why is Google and MS faster with the same (bad) network speed?

**Comment by ShockwaveNN** [comment]
I think it mostly depends of server location

Do you install DocumentServer by yourself using some hosting? Maybe connection speed to that hosting is not that great. 
Also, Google and MS use a large network of CDN-s to make loading of every script blazing fast. 
I think you can configure DocumentServer's Nginx to use CDN but this is not a trivial task and I don't think we got a guide for that

**Comment by ShockwaveNN** [comment]
> Onlyoffice needs to download some big files:

Yes it needs, but it only download it one time on first document open and after that it cache it

We cannot make them smaller. it all the code )
