### ISSUE TITLE
Failed to open document Nextcloud  with Onlyoffice

### ISSUE THREAD

**Issue by julltebe** [ONLYOFFICE/DocumentServer#147]
- I install Nextcloud as described on page https://www.techandme.se/nextcloud-vm/ (Using OVA version to deploy on my virtual machine.)
- I also install onlyoffice as descibed on  page https://www.linuxbabe.com/ubuntu/integrate-nextcloud-onlyoffice
- My Nextcloud running with Https, the certificate generated from our CA server. Also onlyoffice(documentserver), the certificate generated from CA server.
- Nextcloud not publish to the public network, only reachable from local domain (intranet).
ISSUE
- I have two document server(only office) https and http (just for testing). Both running normally. But, the https cannot save on Document Editing Service address (nextcloud setting). if using http, is able to save the setting, no error. But the document is failed to open. "The document could not be saved. bla bla bla"

LOGs:
- Logging nextcloud:
file_get_contents(https://documentserver/coauthoring/CommandService.ashx): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#305
--
file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#305
--
CommandRequest on check error: Bad Request or timeout error

- Logging apache2:
[ssl:warn] [pid 2892] AH1909 : domain.local:443:0 server certificate does not include an ID which matches the server name
[core:notice] [pid 2893] AH00094: Command line: '/usr/sbin/apache2'

/etc/hosts:
127.0.1.1 files
192.168.0.66 files

/etc/apache2/sites-available/default-ssl.conf
ServerName files.local
ServerAlias 192.168.66
DocumentRoot /var/www/nextcloud

firewall (ufw disable) has been disable

root@files:/etc/apache2/ssl# netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 localhost:mysql         *:*                     LISTEN
tcp        0      0 *:webmin                *:*                     LISTEN
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp6       0      0 [::]:http               [::]:*                  LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
tcp6       0      0 [::]:https              [::]:*                  LISTEN
udp        0      0 *:10000                 *:*

Appreciate if anyone here can help me.

**Comment by ShockwaveNN** [comment]
Please duplicate this issue in https://github.com/ONLYOFFICE/onlyoffice-owncloud

**Comment by trofim24** [comment]
cc @LinneyS

**Comment by alexanderonlyoffice** [comment]
Hello @julltebe, 

The cause of the problem is that the entered URL addresses are invalid. Could you please specify the addresses where you NextCloud installed and where Document Server, and send us the screenshot of the settings in administrator section of NextCloud.

**Comment by Shawndev** [comment]
The nextcloud and onlyoffice is installed together, and the onlyoffice USES the docker deployment method. setting and save errors 

![Uploading image.png…]()
![wx20180403-110404](https://user-images.githubusercontent.com/17489462/38227019-c1abe7a6-372e-11e8-8886-9944308c593e.png)
