### ISSUE TITLE
oDocument.Search is not a function

### ISSUE THREAD

**Issue by ghost** [ONLYOFFICE/DocumentServer#1470]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Call the oDocument.Search() method to report an error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```js
me.callCommand(function() {
  try {
    var oDocument = Api.GetDocument()
    var res = oDocument.Search('111')
  } catch (error) {
    console.error(error) // oDocument.Search is not a function
  }
```

**What is the expected behavior?**
Call oDocument.Search() method without error

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer version:**
5.5.3

**Operating System:**
macOS Mojave 10.14.5

**Browser version:**
Chrome 94.0.46xxx

**Comment by bszhct** [comment]
I can open and search through command + F, which means that version 5.5.3 supports the Search() method, right?

![image](https://user-images.githubusercontent.com/56250514/137872072-7f553590-9a9f-4640-912d-7ca665f793c7.png)
