### ISSUE TITLE
How to hide system built-in plugins

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1473]
**Do you want to request a *feature* or report a *bug*?**
Feature?

**What is the current behavior?**
Will show all system plugins

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Setting plugins: true in the configuration item will display all system plugins:

![image](https://user-images.githubusercontent.com/56250514/138015037-bfcb11b8-4c12-4743-b6b3-3e9a9e9a619d.png)

**What is the expected behavior?**
Is it possible to customize the system plug-ins to be displayed, for example, I only want to display Macros plug-ins

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer version:**
6.3.1

**Operating System:**
macOs Mejave 10.14.5

**Browser version:**
94.0.46xxx

**Comment by bszhct** [comment]
OK. I will study his plan again, it will solve my problem if it can be executed automatically, thank you again~ @ShockwaveNN

**Comment by bszhct** [comment]
@hahaxd35 thanks

**Comment by hahaxd35** [comment]
are those new UUID's changing? or can i update my script with the new "dir names"? 
editing  plugin-default does not work like expected

**Comment by trofim24** [comment]
If you want to hide all plugins use [customization option](https://api.onlyoffice.com/editors/config/editor/customization#plugins)
or you can see [our documentation](https://api.onlyoffice.com/plugin/installation/onpremises) about plugins
