### ISSUE TITLE
Preview doc from file stream

### ISSUE THREAD

**Issue by Starsky-Type** [ONLYOFFICE/DocumentServer#1479]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

I would like to know if we can preview docs using file stream.
As far as I tested, preview a doc now, needs to load the whole file first. 
For example a ppt file may include many pages and each page includes some pictures. Can we preview the ppt file even when it is not 100% loaded. We can see the first page and the reset remain downloading with a icon?
![image](https://user-images.githubusercontent.com/89373410/138391875-d00b149f-2634-45e8-a338-eb824bcfc50d.png)

In the "mode" parameter:
https://api.onlyoffice.com/editors/config/editor#mode
Add a new value :stream view ? Something like this way.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
