### ISSUE TITLE
key events hijacked in IE and Edge

### ISSUE THREAD

**Issue by kaniansky** [ONLYOFFICE/DocumentServer#148]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
User is unable to type anything inside an input on a page with iFrame with full access permissions using Internet Explorer or Edge (see attached sample html).
The frame has to be removed before the user can use the input

**What is the expected behavior?**
User should be able to type in an input while having the editor open

**Test file**
[test.html.txt](https://github.com/ONLYOFFICE/DocumentServer/files/1204208/test.html.txt) (rename to .html)

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
both 4.2.10 and 4.4.2, IE11 and MS Edge

**Comment by trofim24** [comment]
Hi. I tried to repeat this problem now, type anything inside an input occurs without any problems.
Microsoft Edge 40.15063.0.0

Do you repeat this problem?

**Comment by kaniansky** [comment]
great! works flawlessly!
