### ISSUE TITLE
Whether the read-only mode will support collaborative viewing in the future？

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/DocumentServer#1484]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Currently, read-only mode does not work well with content，Do not know is what reason is designed like this.

**What is the expected behavior?**

Read-only mode can synchronize content because read-only mode simply should not edit permissions

**DocumentServer version:**
6.4.0

**Operating System:**
mac os
**Browser version:**
chrome 95.0.4638.54

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
