### ISSUE TITLE
When use thew plugins settings, the command "crtl+c" is invalid

### ISSUE THREAD

**Issue by vietsDeng** [ONLYOFFICE/DocumentServer#1486]
**Do you want to request a *feature* or report a *bug*?**
a bug.

**What is the current behavior?**
I upload the onlyoffice/sdkjs-plugins/settings code to the /var/www/onlyoffice/documentserver/sdkjs-plugins, use the watermark. And then the word and the excel can not use the "ctrl + c" to copy. And delete settings, they recover.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Put the onlyoffice/sdkjs-plugins/settings code to the /var/www/onlyoffice/documentserver/sdkjs-plugins.
And then open a word file or a excel file.
Input some words, and choose them, then "ctrl + c", then "ctrl + v".
Found that not copy right things.

**What is the expected behavior?**
When use the plugins `settings`, the copy operation ("ctrl + c") can use normal.

**Did this work in previous versions of DocumentServer?**
No try.

**DocumentServer version:**
6.3.1.32

**Operating System:**
Ubuntu 20.04.2 LTS（Docker & images）

**Browser version:**
Chrome 86.0.4240.198 (32 bit)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
