### ISSUE TITLE
If large space exists between characters, typography calculation is incorrect after input

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/DocumentServer#1487]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/6262739/139184166-c9444c74-8606-469d-ac4f-dcbe7003eca7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Step 1  is to write a few letters, such as ABC
Step 2 Insert Spaces between letters
Step 3 Set the space character size to 96
Step 4 Enter a letter or number

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/6262739/139184444-6567895d-bdd9-4820-8004-f3f3cce46fa1.png)

It should be the same as the tail

**DocumentServer version:**
6.4.1

**Operating System:**
macos

**Browser version:**
95.0.4638.54

**Comment by TatianaKirillova** [comment]
Hey, @Malenconiaprincep 
Thanks for your request!
The problem has been corrected https://github.com/ONLYOFFICE/sdkjs/commit/9b65adb8f125f472376633cb51d6e3db09363a50

**Comment by Rita-Bubnova** [comment]
The issue don't reproduce in DocumentServer version 7.4.1 so I close this issue. 
Feel free to comment or reopen it if you got further questions.
