### ISSUE TITLE
purging onlyoffice-documentserver prepend documenserver to work

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1488]
**Do you want to request a *feature* or report a *bug*?**
Bug.
**What is the current behavior?**
purging already removed "onlyoffice-documentserver" package makes "onlyoffice-documentserver-de" not working still reinstall onlyoffice-documentserver-de (no config changes needed it just worked perfect again)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

install onlyoffice-documentserver and onlyoffice-documentserver-de and remove + purge onlyoffice-documentserver  

**What is the expected behavior?**
nothing should happen
**Did this work in previous versions of DocumentServer?**
-
**DocumentServer version:**

**Operating System:**
Debian 9

**Browser version:**
--

 i have reboot, starting services nothing worked

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
