### ISSUE TITLE
editing CSV throws "Unknown error"

### ISSUE THREAD

**Issue by kaniansky** [ONLYOFFICE/DocumentServer#149]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Trying to open a CSV file for editing returns and error "Unknown error".
There is an error trying to download some setting.json file (http://localhost/webdocuments/cache/files/4aab53cfa72fe725ca07/settings.json/settings.json?md5=oqLYQZ1wbOxv6tlEBJCKNg==&expires=1495095802&disposition=attachment&ooname=output.json)
The same file is possible to open in OnlyOffice desktop app.

**What is the expected behavior?**
User should be able to edit CSV files.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
4.2.10 and 4.4.2 
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by trofim24** [comment]
If you rename the file to the csv extension, will it work?

**Comment by kaniansky** [comment]
no luck. The extension didn't change anything. The editor still starts but fails again on the same error message "Unknown error" with one request to download settings.json resulting in 404.
The server log contains: `2017/08/03 13:54:59 [error] 32240#0: *5077 open() "/var/lib/onlyoffice/documentserver/App_Data/cache/files/4b036f1ba6d869a0fcf4/settings.json" failed (2: No such file or directory), client: 192.168.6.56, server: , request: "GET /cache/files/4b036f1ba6d869a0fcf4/settings.json/settings.json?md5=BSi72qk-i8qt4JJBa7p6Vw==&expires=1504353300&disposition=attachment&ooname=output.json HTTP/1.1", host: "192.168.6.93", referrer: "https://192.168.6.56/webdocuments/2017-07-21-15-03/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2017-07-21-15-03&lang=en&customer=ONLYOFFICE&frameEditorId=onlyoffice_placeholder1501761415590"` but the folder `/var/lib/onlyoffice/documentserver/App_Data/cache/files/4b036f1ba6d869a0fcf4/` contains only 1 file `origin.xlsx`, no settings.json to be found

**Comment by trofim24** [comment]
Do you open the file `origin.xlsx`?
Try changing the extension to `.csv`, it will be `origin.csv`.
Or attach your file to this issue.

**Comment by kaniansky** [comment]
the original file is a csv file with csv extension but trying to open it throws an error in nginx that it's trying to get `settings.json` from a folder where there is only a single file `origin.xls`
[csv.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1199605/csv.zip)

**Comment by trofim24** [comment]
Please include the full logs in `/etc/onlyoffice/documentserver/log4js/production.json`. restart the server, reload the file and send us logs.
`"nodeJS": "ALL"`

**Comment by kaniansky** [comment]
this is all i've got from the `/var/log/onlyoffice/documentserver` directory
[logs.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1204165/logs.zip)

**Comment by trofim24** [comment]
You use `filetype` instead of `fileType`. 
https://api.onlyoffice.com/editors/config/document#fileType

**Comment by kaniansky** [comment]
Thank You very much for your help. The error message is a little bit too general :D
when you don't set `fileType`, you can still open xls and doc files
when you set `fileType` to a wrong value, it throws correct error
