### ISSUE TITLE
convert docx to png style not match

### ISSUE THREAD

**Issue by jilieryuyi** [ONLYOFFICE/DocumentServer#1492]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
onlyoffice/documentserver latest
**Operating System:**

**Browser version:**

It should look like this

![QQ截图20211101173131](https://user-images.githubusercontent.com/2398119/139651840-69247877-1c56-48de-b8e2-2af480ce136f.png)

got
![test](https://user-images.githubusercontent.com/2398119/139651867-58e887bf-ae92-4914-8e72-b216a4ad175b.png)

test file
[文字文稿1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/7452155/1.docx)

**Comment by ShockwaveNN** [comment]
Seems this is font issue, I've opened file you've attached in Documents editors and it looks like on incorrect screenshot

![image](https://user-images.githubusercontent.com/668524/139653570-2a004512-204c-4198-aa99-9992799c6551.png)

So I think we need font files to correctly handle this issue

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
