### ISSUE TITLE
open excel edit, when input wrong formula, the file is locked and can't edit again.

### ISSUE THREAD

**Issue by vietsDeng** [ONLYOFFICE/DocumentServer#1499]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when I use excel edit, I input wrong formula, then it will notice `an error occurred ...`, and the excel is locked that can edit.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. open a excel online;
2. choose a cell, input `=SUM(F14:80)`   (error formula)
3. use the mouse chick some times

**What is the expected behavior?**
the excel can edit normal when input wrong formula, can delete or edit the cell.

**Did this work in previous versions of DocumentServer?**
yes

**DocumentServer version:**
6.3.1.32
docker images - onlyoffice/documentserver:6.3.1.32

**Operating System:**
docker

**Browser version:**
Chrome 86.0.4240.198.

**Comment by ShockwaveNN** [comment]
Hi, could you recheck it on latest version - I've checked on v6.4.2 and there is no `an error occureded` message, just standart `#VALUE!` in cell

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
