### ISSUE TITLE
Documents accessed by API

### ISSUE THREAD

**Issue by iwkse** [ONLYOFFICE/DocumentServer#15]
Hi,
I would like to know where documents ,that are accessed by API, are saved. The Data folder is empty so I suppose this is not the right place for documents accessed by API.

**Comment by AnaMih** [comment]
If you are using standard DocumentEditorExample the files are stored as it is specified here: https://github.com/ONLYOFFICE/DocumentServer/blob/master/OnlineEditorsExample/settings.config#L6
i.e example folder + storage path + IP of the connected user
The storage-path is empty by default, please check the IP folder (not App_Data https://github.com/ONLYOFFICE/DocumentServer/blob/master/OnlineEditorsExample/settings.config#L6)

**Comment by iwkse** [comment]
No, I'm talking by using it with API not the DocumentEditorExample

**Comment by AnaMih** [comment]
When you open a new document in browser there is still no version that can be found and opened.
When you work on the document the cache can be found in
/var/lib/onlyoffice/documentserver/App_Data/cache/files
After finishing editing and closing the document in all tabs (by all users who use the document) it can be found in /var/lib/onlyoffice/documentserver/App_Data/cache/files
If it doesn't help could you please specify the task more detailed (the moment when you are trying to find the document)

**Comment by iwkse** [comment]
Thanks, I found them in /var/lib/onlyoffice/documentserver/App_Data. I guess I can regularly delete data inside of this as this is used as cache. I'm using the editors with Alfresco, so once it's edited the file is saved back to Alfresco and when I open again if it won't find data in App_Data it will load it from Alfresco.
