### ISSUE TITLE
Cannot open DocumentServer after compiling

### ISSUE THREAD

**Issue by kingkazmam** [ONLYOFFICE/DocumentServer#150]
I just compiled DocumentServer use http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx, step by step and without error.

But when I run it and open localhost or localhost:8000, I get "Cannot GET /" in my brower.

I have disable the default nginx website and create the /etc/nginx/sites-available/onlyoffice-documentserver file, redis postgresql nginx rabbitmqI is run, I don't konw why, could you help me?

OS : Ubuntu-16.04.2-desktop-amd64
Brower : FireFox
DocumentServer version : the lastest version by use git

**Comment by ShockwaveNN** [comment]
Do you `DocService` (last command from `Running Document Server`) started without any errors?

**Comment by kingkazmam** [comment]
# export NODE_ENV=production-linux NODE_CONFIG_DIR=/etc/onlyoffice/documentserver && sudo -u onlyoffice -E node /var/www/onlyoffice/documentserver/server/DocService/sources/server.js
[2017-08-04 21:58:01.837] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2017-08-04 21:58:01.864] [WARN] nodeJS - update cluster with 1 workers
[2017-08-04 21:58:01.880] [WARN] nodeJS - worker 7557 started.
[2017-08-04 21:58:01.881] [WARN] nodeJS - update cluster with 1 workers
[2017-08-04 21:58:02.211] [WARN] nodeJS - Express server starting...
[2017-08-04 21:58:03.705] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

I'm surely reload nginx whit sudo nginx -s reload.

I just find I can open localhost/welcome, it shows Document Server is running.
But I try others link like localhost/web-apps/apps/documenteditor/main/ , it's loading all the time.
Is there an entry file in it? or I must input the link when I use it?

**Comment by ShockwaveNN** [comment]
>I just find I can open localhost/welcome, it shows Document Server is running.
It mean it worked fine.
You can integrate it with your own solution or try https://github.com/ONLYOFFICE/document-server-integration/

**Comment by kingkazmam** [comment]
Ok, thank you. Best whishes!
