### ISSUE TITLE
Conversion from csv to xlsx generates an invalid xlsx

### ISSUE THREAD

**Issue by gmenegoz** [ONLYOFFICE/DocumentServer#1500]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when I call the ConvertService API to convert a csv file to xlsx format the resulting file is invalid and cannot be repaired by Excel

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Prepare with a text editor a csv file with at least two rows
2. Use the ConvertService API to convert the csv file to xlsx format
3. Try to open the resulting file with micorsoft Excel
4. You will be notified that the file is corrupted and asked if you want to repair it
5. Choose to repair the file
6. Notice that only the first line is preserved
7. Repeat the process bu instead of opening the xlsx file with Excel extract the content and open _\xl\worksheets\sheet1.xml_
8. Notice that the first cell of the spreadsheet (the <c> tag) is named *A0* instead of the expected *A1*
9. Replace all <c> tags ("A0"->"A1", "A1"-> "A2", etc)
10. Save the file, compress the structure again in a xlsx
11. Open the modified xlsx with Excel and notice that it works fine

It may be useful to notice that converting from csv to ods and from ods to xlsx the result is a valid xlsx (so there is actually a valid workaround)

**What is the expected behavior?**
The file obtained from the conversion should be correctly opened by microsoft Excel

**Did this work in previous versions of DocumentServer?**
yes

**DocumentServer version:**
Version: 6.4.2 (build:6)

**Operating System:**
docker on Ubuntu 18.04

**Browser version:**
Chrome 95.0.4638.69

**Comment by ShockwaveNN** [comment]
@l8556 Please take a look at this issue as soon as you got free time

**Comment by l8556** [comment]
Hi @gmenegoz

Thank you for your issue
I can confirm - this is a bug. Issue #1500 in our private issue tracker.

**Comment by gmenegoz** [comment]
Thank you for your attention!

In the meanwhile I will keep using my workaround

**Comment by Rita-Bubnova** [comment]
This has been fixed (https://github.com/ONLYOFFICE/core/commit/15ccea03063af6b135ab5d1cde3daef9cb10a22c, https://github.com/ONLYOFFICE/core/commit/1a3191216a6a981d104f89fd05587599bc718298).

DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
