### ISSUE TITLE
onlyoffice will add redundant tag w:eastAsiaTheme="minorEastAsia"

### ISSUE THREAD

**Issue by yayaQAQ** [ONLYOFFICE/DocumentServer#1504]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I imported a document with italics, I deleted the italic paragraph characters, and then I exported the document and found that the italics became simsun.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
No Step
**What is the expected behavior?**
No change in format
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer version:**
Latest
**Operating System:**
All
**Browser version:**
All

**We found the solution,we added the following code:**
![image](https://user-images.githubusercontent.com/20497531/140876301-cd2586b0-10ee-4923-bbbe-74cf3eb9759e.png)

**We also found the reason:**
onlyoffice will actively add this tag ```w:eastAsiaTheme="minorEastAsia"```

**Comment by ShockwaveNN** [comment]
Hi, I'm not sure that I understand why eastAsiaTheme tag is bad

But if this scenario is correct:

> When I imported a document with italics, I deleted the italic paragraph characters, and then I exported the document and found that the italics became simsun.

I think this is not correct behavior

Could you attach file you've uploaded originally and I think video with this problem will help us localize the problem

**Comment by yayaQAQ** [comment]
> Hi, I'm not sure that I understand why eastAsiaTheme tag is bad
> 
> But if this scenario is correct:
> 
> > When I imported a document with italics, I deleted the italic paragraph characters, and then I exported the document and found that the italics became simsun.
> 
> I think this is not correct behavior
> 
> Could you attach file you've uploaded originally and I think video with this problem will help us localize the problem

My doc file has private data, I can send it to you via email. 😁

**Comment by yayaQAQ** [comment]
@ShockwaveNN

**Comment by ShockwaveNN** [comment]
Maybe you'll try to remove private data or replace it with some non-private data?

Because we prefer to make our issue tracker without private user data

But if you cannot do that - please send it to `files@onlyoffice.com` with title `GitHub DocumentServer#1504`

and comment here after that

**Comment by yayaQAQ** [comment]
> Maybe you'll try to remove private data or replace it with some non-private data?
> 
> Because we prefer to make our issue tracker without private user data
> 
> But if you cannot do that - please send it to `files@onlyoffice.com` with title `GitHub DocumentServer#1504`
> 
> and comment here after that

Maybe I didn't express I opened a document, then exported it, then opened it using MS word, and it did not behave the same way as if it had been opened directly using word. Is this a normal presentation?
Because my criteria still prevails with word.
I also tried using onlyoffice(Desktop Edition, Mac) to open, then export, then open again with onlyoffice, and the performance was the same before and after the two times. But the exported document does not behave consistently in Word(Microsoft).

**Comment by ShockwaveNN** [comment]
> and it did not behave the same way as if it had been opened directly using word. Is this a normal presentation?

No it's not, we should break files even we do not support some features

So if you can - you should edit your doc in MS Word and replace private data with any data
Save it
Open in ONLYOFFICE DocumentServer, edit save and make sure it also rendering incorrect in MS Word, not the way before - and attach it here

**Comment by yayaQAQ** [comment]
@ShockwaveNN I sent email. 😁

**Comment by ShockwaveNN** [comment]
@yayaQAQ Thanks, we've received it. We'll response here as soon as we localize the problem or will have any questions for you

**Comment by yayaQAQ** [comment]
@ShockwaveNN How's the progress? 😁

**Comment by ShockwaveNN** [comment]
@yayaQAQ Sorry no news, please note that we are not a support team and we'll take a look at your issue as soon as we got free time

If you want high priority for issues - better contact support@onlyoffice.com

**Comment by yayaQAQ** [comment]
@ShockwaveNN 👌

**Comment by TatianaKirillova** [comment]
Hello, **@yayaQAQ**
Thanks for your request!
I can confirm that the problem exists. I created ticket 53626 in our private  tracker with your issue.
