### ISSUE TITLE
If word is Arial, it can not change to other font?

### ISSUE THREAD

**Issue by yayaQAQ** [ONLYOFFICE/DocumentServer#1509]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When the imported font is Arial, the font cannot be changed
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
can change font or tell me what's wrong
**Did this work in previous versions of DocumentServer?**
Dont know
**DocumentServer version:**
Lastest
**Operating System:**
Mac
**Browser version:**

![image](https://user-images.githubusercontent.com/20497531/141295427-162a96d1-d65e-47e4-b24b-3db2aefc6507.png)

![image](https://user-images.githubusercontent.com/20497531/141295576-11bfe284-1ca1-4906-b169-cd687fc94062.png)

this is my file:
[3443.docx](https://github.com/ONLYOFFICE/DocumentServer/files/7520297/3443.docx)

**Comment by TatianaKirillova** [comment]
Hello, **@yayaQAQ**
Thanks for your request!
I can confirm - this is know bug, issue 53553 in our private issue tracker.
