### ISSUE TITLE
COUNTIF formula ignores TRUE and FALSE

### ISSUE THREAD

**Issue by cuibonobo** [ONLYOFFICE/DocumentServer#151]
Bug report.

The COUNTIF spreadsheet formula currently allows you to specify a range of cells as the first argument, and a 'match value' as the second argument. For strings and numbers, cells that match the second argument are counted correctly, but cells that contain a boolean (TRUE/FALSE) are not counted correctly.

For example, for `A1 = TRUE`, `A2 = FALSE`, and `A3 = TRUE`, the formula `=COUNTIF(A1:A3, TRUE)` should return `2`, but instead it returns `0`.

Document Server 4.4.2.

**Comment by trofim24** [comment]
Thanks. We will fix this in the next releases.

**Comment by trofim24** [comment]
Fix
[ONLYOFFICE-DocumentServer-5.0.3](https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-5.0.3)
