### ISSUE TITLE
Add support for 300% interface scaling

### ISSUE THREAD

**Issue by alex-kinokon** [ONLYOFFICE/DocumentServer#1513]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.4.2.6

### Expected Behavior

UI scales correctly.

See @ShockwaveNN’s [comment](https://github.com/ONLYOFFICE/DesktopEditors/issues/217#issuecomment-966883796) on ONLYOFFICE/DesktopEditors#217. 

### Actual Behavior

It does not.

### Reproduction Steps

1. Open OnlyOffice.

### Additional information

![Capture d’écran du 2021-11-12 11-50-10](https://user-images.githubusercontent.com/8125011/141504558-1937c629-10da-4284-aa46-92ef328ac6c4.png)

**Comment by proteriax** [comment]
@ShockwaveNN Do you have an ETA for this bug?

**Comment by ShockwaveNN** [comment]
@proteriax Sorry, I cannot provide any ETA. If you really need that feature - you better to contact sales@onlyoffice.com

**Comment by rommy2015** [comment]
> ### Эта проблема уникальна.
> 
>     * [x] Я использовал [инструмент поиска ](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=)и не нашел проблему, описывающую мою ошибку.
> 
> 
> ### Операционная система
> 
> Linux (DEB-пакет)
> ### Информация о версии
> 
> 6.4.2.6
> ### Ожидаемое поведение
> 
> Пользовательский интерфейс масштабируется правильно.
> 
> См @ShockwaveNN к [комментарий ](https://github.com/ONLYOFFICE/DesktopEditors/issues/217#issuecomment-966883796)ONLYOFFICE [/DesktopEditors#217 ](https://github.com/ONLYOFFICE/DesktopEditors/issues/217).
> ### Фактическое поведение
> 
> Это не.
> ### Этапы воспроизведения
> 
>     1. Откройте ТолькоОфис.
> 
> 
> ### Дополнительная информация
> 
> ![Скриншот от 2021-11-12 11-50-10](https://user-images.githubusercontent.com/8125011/141504558-1937c629-10da-4284-aa46-92ef328ac6c4.png)

In Windows 10 That is yet not work. This is extremely inconvenient. Everything is very small.

**Comment by janagutchess** [comment]
I'd like to add my encouragement to add 300% scaling. I'm using an 8K display (7680x4320 resolution) on Windows, and the menu text and icons in OnlyOffice are very small, making it quite difficult to use. To add some context of how much smaller it is than other programs I am using, here is a screenshot of OnlyOffice side by side with Word. I would be very happy to see a 300% interface scaling option come to OnlyOffice! 

![OnlyOffice scaling vs Word 2022-03-22](https://user-images.githubusercontent.com/102190673/159589424-6633a333-8567-4a4f-931b-40c01983937f.png)

**Comment by Opendreas** [comment]
I have a similar problem with OnlyOffice 7, I have a 15.6" laptop with 4K resolution and 200% scaling is not enough, menu icons and font are very small. But 300% would be too much, 250% scaling would be optimal.

**Comment by wimvandorst** [comment]
Please, please, make 300% scaling work. It is imperative for hi-res linux laptops, like mine!

**Comment by maxkadushkin** [comment]
yes, support for scaling 250% and bigger is in development now and will be available in closest releases

**Comment by janagutchess** [comment]
> yes, support for scaling 250% and bigger is in development now and will be available in closest releases

Thanks for the update, @maxkadushkin  - This is great news, and I look forward to seeing this improvement come to the desktop apps!! 👏

**Comment by LuckySpecialist** [comment]
Interface scaling higher than 200% was added since version 7.4.
