### ISSUE TITLE
Config is not secured correctly, can be changed by end user

### ISSUE THREAD

**Issue by prozyckiFP** [ONLYOFFICE/DocumentServer#1514]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm trying to secure config using security tokens. I have following config, as you can see the whole config is signed in JWT. I can't enable printing by changing config in browser dev tools, so it works as expected, but I can enable chat or change watermark settings.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Enable config singing.
2. Put breakpoint before "new DocsAPI.DocEditor("iframeEditor", config);"
3. Change editorConfig.customization.chat to true
4. Continue script execution

![image](https://user-images.githubusercontent.com/94322677/141699239-de9637e3-86dd-41a9-8043-210100b809db.png)

**What is the expected behavior?**
According to documentation (https://api.onlyoffice.com/editors/security) the data from the payload is considered valid and is used instead of the corresponding data from the main parameters. But it is not working for me

**DocumentServer version:**
onlyoffice-documentserver-de_6.4.1-45_amd64.deb

**Operating System:**
Windows running Docker Desktop

**Browser version:**
Any

**Questions:**
Is there any way to block config manipulation?

**config:**
```
"{"type":"desktop","documentType":"cell","watermarkJsonData":"{\"isEnabled\":true,\"text\":\"Office Viewer\\nConfidential - Not for Distribution\\nNicholas Ball\\nnicholas.ball @ compxag.com\\n10.57.17.0,    20:50 UTC, 14/11/2021\",\"opacity\":\"0.3\",\"fontName\":\"Helvetica\",\"linesCount\":5}","auditConfig":"{\"baseUrl\":\"http://vm-strlng-tm1\",\"guid\":\"a91d8955-49ca-4c52-bb8c-21234bc73f8e\",\"projectId\":34253,\"documentGlobalId\":\"861f8c0f-3f30-492d-99f3-32420447f4d6\",\"userId\":65}","document":{"title":"1.16_file_sample_xlsx","url":"http://host.docker.internal/compVDR/Handlers/DownloadDocumentHandler.ashx?projectId=34253\u0026documentId=1028450\u0026convert=true","fileType":"xlsx","key":"c0ccd88b-13a8-420d-8ee9-96d6ddcff08a_637672152603800000","info":{"owner":"Me","uploaded":"01/11/2021","favorite":null},"permissions":{"comment":false,"download":false,"print":true,"edit":false,"copy":false,"fillForms":false,"modifyFilter":false,"modifyContentControl":false,"review":false}},"editorConfig":{"lang":"en-GB","customization":{"chat":false,"comments":false,"anonymous":{"request":false}}},"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiZGVza3RvcCIsImRvY3VtZW50VHlwZSI6ImNlbGwiLCJ3YXRlcm1hcmtKc29uRGF0YSI6IntcImlzRW5hYmxlZFwiOnRydWUsXCJ0ZXh0XCI6XCJPZmZpY2UgVmlld2VyXFxuQ29uZmlkZW50aWFsIC0gTm90IGZvciBEaXN0cmlidXRpb25cXG5OaWNob2xhcyBCYWxsXFxubmljaG9sYXMuYmFsbCBAIGNvbXB4YWcuY29tXFxuMTAuNTcuMTcuMCwgICAgMjA6NTAgVVRDLCAwMS8xMS8yMDIxXCIsXCJvcGFjaXR5XCI6XCIwLjNcIixcImZvbnROYW1lXCI6XCJIZWx2ZXRpY2FcIixcImxpbmVzQ291bnRcIjo1fSIsImF1ZGl0Q29uZmlnIjoie1wiYmFzZVVybFwiOlwiaHR0cDovL3ZtLXN0cmxuZy10bTFcIixcImd1aWRcIjpcImE5MWQ4OTU1LTQ5Y2EtNGM1Mi1iYjhjLTIxMjM0YmM3M2Y4ZVwiLFwicHJvamVjdElkXCI6MzQyNTMsXCJkb2N1bWVudEdsb2JhbElkXCI6XCI4NjFmOGMwZi0zZjMwLTQ5MmQtOTlmMy0zMjQyMDQ0N2Y0ZDZcIixcInVzZXJJZFwiOjY1fSIsImRvY3VtZW50Ijp7InRpdGxlIjoiMS4xNl9maWxlX3NhbXBsZV94bHN4IiwidXJsIjoiaHR0cDovL2hvc3QuZG9ja2VyLmludGVybmFsL2NvbXBWRFIvSGFuZGxlcnMvRG93bmxvYWREb2N1bWVudEhhbmRsZXIuYXNoeD9wcm9qZWN0SWQ9MzQyNTMmZG9jdW1lbnRJZD0xMDI4NDUwJmNvbnZlcnQ9dHJ1ZSIsImZpbGVUeXBlIjoieGxzeCIsImtleSI6ImMwY2NkODhiLTEzYTgtNDIwZC04ZWU5LTk2ZDZkZGNmZjA4YV82Mzc2NzIxNTI2MDM4MDAwMDAiLCJpbmZvIjp7Im93bmVyIjoiTWUiLCJ1cGxvYWRlZCI6IjE0LzExLzIwMjEiLCJmYXZvcml0ZSI6bnVsbH0sInBlcm1pc3Npb25zIjp7ImNvbW1lbnQiOmZhbHNlLCJkb3dubG9hZCI6ZmFsc2UsInByaW50Ijp0cnVlLCJlZGl0IjpmYWxzZSwiY29weSI6ZmFsc2UsImZpbGxGb3JtcyI6ZmFsc2UsIm1vZGlmeUZpbHRlciI6ZmFsc2UsIm1vZGlmeUNvbnRlbnRDb250cm9sIjpmYWxzZSwicmV2aWV3IjpmYWxzZX19LCJlZGl0b3JDb25maWciOnsibGFuZyI6ImVuLUdCIiwiY3VzdG9taXphdGlvbiI6eyJjaGF0IjpmYWxzZSwiY29tbWVudHMiOmZhbHNlLCJhbm9ueW1vdXMiOnsicmVxdWVzdCI6ZmFsc2V9fX19.Mg2PDGL8TwyZfpm2DCOtAw93Rn41gQ8olXXFW_kRUTY"}"
```

**Comment by igwyd** [comment]
Hello, @prozyckiFP
Thank you for report, i can confirm - this is bug, issue 53757 in our private issue tracker.

**Comment by igwyd** [comment]
@prozyckiFP it's fixed, param chat moved to [permissions](https://api.onlyoffice.com/editors/config/document/permissions):
https://github.com/ONLYOFFICE/web-apps/commit/abb96ec86620254971ff87a3ac1471347e161f67
And will be released in the next major release.
