### ISSUE TITLE
Request for more documentation regarding collaborative editing/explaining architecture

### ISSUE THREAD

**Issue by CallumDowling** [ONLYOFFICE/DocumentServer#1515]
I can't find where the magic for collaborative editing works in the code. I also looked into redis and rabbitmq, as they are a sensible place to handle the collaboration - but the data does not seem to be going through them. I just tailed the logs when editing the document to find this out.

I would love to get a document with a high level overview of this feature and where to look for it in the code. My goal is to deploy onlyoffice across multiple sites and have the collaborative editing work as though it were deployed on one site. 

Thanks!

**Comment by ShockwaveNN** [comment]
> My goal is to deploy onlyoffice across multiple sites and have the collaborative editing work as though it were deployed on one site.

Hi, I think this is a very specific situation and I think it's better to contact support@onlyoffice.com, they'll answer all your questions about complicated setups

**Comment by CallumDowling** [comment]
Thanks, I will do that.
