### ISSUE TITLE
The Interface (GUI) of onlyoffice ignores system font settings...

### ISSUE THREAD

**Issue by piedrok** [ONLYOFFICE/DocumentServer#1516]
Trying Onlyoffice for the first time, installed on linux (ARCH, fully updated). Sadly the interface ignores my system settings. FOnts are different, font sizes are different... also I cannot find any settings for the interface apart from very limited scaling options... - in addition GUI fonts seem not to be black but grey which is a real problem for me as I need the contrast... 

How can I make sure Openoffice GUI respect system font settings? 
(in may case: Roboto 13pt, slight RGB hinting, font color: black, font weight: medium) 

Thanks for help, p.

**Comment by trofim24** [comment]
Sorry for late response, seems we missed this issue.
This repo is [ONLYOFFICE Docs](https://www.onlyoffice.com/office-suite.aspx?utm_source=github&utm_medium=cpc&utm_campaign=GitHubDS). It's server, not desktop for using your system settings.

If you want to customize interface see [our documentation](https://api.onlyoffice.com/editors/config/editor/customization).
If you have any questions, please create new issue.
