### ISSUE TITLE
DocumentServer nodes behind haproxy and collaborative edition

### ISSUE THREAD

**Issue by c0r3dump3d** [ONLYOFFICE/DocumentServer#1518]
Hi, It's possible to install different document server nodes, behind a haproxy, sharing the same database, RabbitMQ and redis installation, and to be certain that the collaborative editing from Nextcloud works?

**Comment by ShockwaveNN** [comment]
I think this is not an issue, but a question and better to ask in on our forum forum.onlyoffice.com
