### ISSUE TITLE
Error font!

### ISSUE THREAD

**Issue by caohieu089** [ONLYOFFICE/DocumentServer#1519]
Hello, i've installed OnlyOffice Document server for my NextCloud
Everything on Web work ok, but my version has some issue:

-When open a readable file with font Arial, it's display a square text:

[https://i.imgur.com/ofTBOLu.png](https://i.imgur.com/ofTBOLu.png)
Example: Dự án Hệ thống xử lý nước thải Yên Xá, thành phố Hà Nội.

-When open a file with many sheet+text (Arial font all), its have a error:

[https://i.imgur.com/dlOlinx.png](https://i.imgur.com/dlOlinx.png)

When download and open this downloaded file on Local Computer using Microsoft Office, it's had no problem and very smooth.

Anyone have a suggestion? Thanks and sorry about my English!

This is my OS and version i've installed (on 18/Nov/2021)
```
----------------------------------------------------------------------------------------------
Server:
     OS: Ubuntu 20.04.3  GNU/Linux 5.4.0-90-generic x86_64
     NodeJS: v12.22.7
     Postgresql: v12.9
     onlyoffice-documentserver/squeeze,now 6.4.2-6 amd64 [installed]
----------------------------------------------------------------------------------------------
Client/User
     OS: Windows 10
     Browser: Firefox 94.0.1 x64
-------------------------------------------------------------------------------------------------
```

**Comment by ShockwaveNN** [comment]
For first error we need your file to analyze it

For second error with Font not loaded - please take a look at browser console during load of this file - seems some fonts are not loaded, maybe because of some network problems

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
