### ISSUE TITLE
Missing Spellchecker

### ISSUE THREAD

**Issue by nebulade** [ONLYOFFICE/DocumentServer#1520]
While trying to fix an [issue](https://forum.cloudron.io/topic/6014/spellcheck-not-working) from one of our users about spellchecking, I found that the Spellchecker folder is simply not part of the release packages. 

I can see it in https://github.com/ONLYOFFICE/server/tree/10929a06b9560175b56b9c81757b7ef991034d7f/SpellChecker but that folder does not exist for some reason in the release packages. Is there any postinstall step or otherwise obvious thing which we could miss? The corresponding dictionaries are present in the the release packages.

**Did this work in previous versions of DocumentServer?** It used to be included as a separate service.
**DocumentServer version:** 6.4
**Operating System:** Ubuntu 20

**Comment by ShockwaveNN** [comment]
I'm not very familiar with technology itself, but it moved to use shared worker

So it should just work in any modern browser

For example, you can check it in chrome via opening `chrome://inspect/#service-workers`

In my case it's showing this:
![image](https://user-images.githubusercontent.com/668524/142398424-55a2f9cf-a9b4-4edb-92fd-a54a205f6a3f.png)

Maybe something went wrong during your repackaging, what are you doing when you are rebuilding our package to Cloudron package? Maybe some nginx issues? Is there any error in JS console?

**Comment by nebulade** [comment]
Thanks for the quick reply!

No shared worker is run in my tests. Unfortunately there are no errors in neither chrome nor firefox. The console just shows:
```
JQMIGRATE: Migrate is installed, version 3.3.2
App.vue:381 Notifications permissions not yet requested
session-heartbeat.js:101 session heartbeat polling started
```
On the server-side there is also nothing particular, not even when running the node app with `DEBUG=*`

So with the shared worker, are you then confirming that https://github.com/ONLYOFFICE/server/tree/master/SpellChecker should not be part of the .deb/.rpm releases from https://github.com/ONLYOFFICE/DocumentServer/releases/tag/v6.4.2 ?
The Cloudron package just unpacks the .deb package, nothing much further.

Also where would I find the Spellchecker shared worker code now to be able to debug this further? Given it is now client side, should it be somewhere at `/var/www/onlyoffice/documentserver/web-apps`? I assume then it simply isn't even loaded or found. The network tab in the browser also shows nothing which, at least to me, indicates that it attempts to load something spellcheck related.

**Comment by ShockwaveNN** [comment]
> So with the shared worker, are you then confirming that https://github.com/ONLYOFFICE/server/tree/master/SpellChecker should not be part of the .deb/.rpm releases

Yeah, we got some leftowers but not all removed

> The Cloudron package just unpacks the .deb package, nothing much further.

I think you should start with installing DocumentServer via docker and comparing if something missing

>  Given it is now client side, should it be somewhere at /var/www/onlyoffice/documentserver/web-apps?

https://github.com/ONLYOFFICE/sdkjs/tree/master/common/spell

**Comment by nebulade** [comment]
Thanks for the clarification there where to expect things to be. I was now able to pin it down to some missing nginx configs, adding those fixed it as far as I can tell. Sorry for the noise, I will then track the upstream nginx config changes for next versions as well.
