### ISSUE TITLE
[WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

### ISSUE THREAD

**Issue by charnesp** [ONLYOFFICE/DocumentServer#1521]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

I often obtain the following error when using Onlyoffice 

"Warning : an error appeared when saving the file. Please use option ........."

When I look at the logs I see the following errors:
```

==> /var/log/onlyoffice/documentserver/docservice/out.log <==

[2021-11-18T11:50:08.383] [WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

[2021-11-18T11:50:28.002] [WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

[2021-11-18T11:51:39.319] [WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

[2021-11-18T11:52:31.549] [WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

[2021-11-18T11:52:41.853] [WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

[2021-11-18T11:55:12.485] [WARN] nodeJS - sendServerRequest returned an error: docId = 1285932263; data = {"error":1}

```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have onlyoffice with Nextcloud (both of them being a Traefik reverse proxy)

**What is the expected behavior?**

No warning

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
6.4.2.6

**Operating System:**
MacOS, Linux, Windows

**Browser version:**
Sarafi, Chrome, Firefox

**Comment by ShockwaveNN** [comment]
I think this is network error, for some reason DocumentServer instance cannot retrieve data from CommunityServer

Maybe problem in proxy or something related

**Comment by charnesp** [comment]
Thanks for your answer. It is strange because the DocumentServer instance and the CommunityServer are on Docker (docker-compose stack) and are communicating through virtual networks.

Here is my configuration on Nextcloud:

ONLYOFFICE Docs address:
https://onlyoffice.mycompany.com

ONLYOFFICE Docs address for internal requests from the server:
http://onlyoffice/

Server address for internal requests from ONLYOFFICE Docs
http://nextcloud/ 

Thus, if I understand correctly, OnlyOffice and the Server do not use any proxy.

Do you have an hint for tracking the potential problem?

**Comment by ShockwaveNN** [comment]
Oops, sorry, I've got a typo in my message, am I right your setup has not ONLYOFFICE CommunityServer involved? Only ONLYOFFICE DocumentServer and Nextcloud?

Because I cannot understand which product you've meant in this sentence
>OnlyOffice and the Server

Could check that using integrated example in DocumentServer (can be found at `http://docserverurl/welcome/`) can create and save file by itself

And if so - I don't think it's an issue and specific to your configuration and better to ask question on our [forum](https://forum.onlyoffice.com)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
