### ISSUE TITLE
fonts are not loaded

### ISSUE THREAD

**Issue by seyeonHello** [ONLYOFFICE/DocumentServer#1529]
I tried this. (docker version)
https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx

An error appears when I enter the document.
"fonts are not loaded. contact your document server administrator."

how can i solve this problem?

**Comment by seyeonHello** [comment]
![image](https://user-images.githubusercontent.com/47855648/144010332-e1ddb97f-5363-43e8-9c69-f45dbeed6c33.png)

**Comment by ShockwaveNN** [comment]
I think something wrong with either:

1. You didn't run `documentserver-generate-allfonts.sh` or it exited with errors
2. Something wrong with your nginx setup
3. You got problems with cache (try another browser or incognito mode)

**Comment by seyeonHello** [comment]
@ShockwaveNN thank you
