### ISSUE TITLE
Spreadsheet editor Undo/Redo functions disabled when the same file opened and edited in different tabs

### ISSUE THREAD

**Issue by kesavarajaphp** [ONLYOFFICE/DocumentServer#153]
*Bug*

We integrated the document server V 4.4.2 with Nextcloud 12. We are facing the problem in document editing.
When the user opens a same document in two tabs (for checking different sheets) for editing purpose. If the user try to undo received an error with Undo / Redo functions disabled in a Popup. Also the document shared with another user only sees the red box even after 5 minutes and not received the saved changes, if the original user saved the document. The Co-editing mode is set to fast. We see no errors in Log files.

Please Create Or Open Or Upload a document in same window with Two different tabs. Try to edit in both tabs and make undo in any of the document, then you can see the Error.

We are expecting to Modify on both tabs on the same sheet when the user make undo, it should not display error. Also if it is a Shared document, it should be saved, and Not showing the redboxes

DocumentServer Version : 4.4.2,Browser : Google Chrome, Firefox

![doc undo-redo issue](https://user-images.githubusercontent.com/29251273/29173714-d26bc606-7e01-11e7-944f-5c4e1e876e25.JPG)

**Comment by ShockwaveNN** [comment]
@kesavarajaphp Hi there, if you open Spreadsheet Editor in two tabs you enter Fast Co-Edit mode, and currenlty we support Undo only in DocumentEditor and Presentation Editor.
You can change to Strict CoEdit from settings and Undo-Redo will work fine

**Comment by kesavarajaphp** [comment]
@ShockwaveNN Thank you for the reply. Can we expect the Undo/Redo in Fast Co-edit mode in spreadsheet editor in Future ?

**Comment by ShockwaveNN** [comment]
@kesavarajaphp Yeah we planning to add Undo in near feature. Adding Redo to all editors (currently we have only Undo in Fast Co-Edit in Documents and Presntations) may take more time.

**Comment by kesavarajaphp** [comment]
@ShockwaveNN Thank you for the reply. I shall Close this now.
