### ISSUE TITLE
#convertion api :  Throw string(12) "{"error":-7}" when ADD parameter “key” use variable

### ISSUE THREAD

**Issue by chinaguole** [ONLYOFFICE/DocumentServer#1532]
Document Server 6.4/PHP7/Apache2

when i use convertion api in php script, add parameter “key” , it throw: string(12) "{"error":-7}" .
```
    $randtoken = addslashes(substr(md5(time()),0,13));
    $url1="http://oo.com/test/1.pdf";
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => 'http://oo.com/ConvertService.ashx',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS =>'{
            "async": false,
            "filetype": "pdf",
            "outputtype": "png",
            "thumbnail": {
              "aspect": 2,
              "first": true,
              "height": 1131,
              "width": 800
          },
          "key": "$randtoken",
          "title": "Example Document Title.docx",
          "url": "$url1"
    }',
        CURLOPT_HTTPHEADER => array(
            'Accept: application/json',
            'Content-Type: Application/json;charset=UTF-8'
        ),
    ));
    $response = curl_exec($curl);
    var_dump ($response);`

The ERROR:
`string(12) "{"error":-7}"
```

I hope to get your reply as soon as possible,THX!

**Comment by ShockwaveNN** [comment]
Hi, I've had no experience with PHP, but `key` attribute is required and can be random string or GUID

> add parameter “key” , it throw: string(12) "{"error":-7}" .

So you've saying same code without `key` do not raise error? This is unexpected

Could you simulate same error with simple `curl` or `wget` request or `postman` example?

**Comment by chinaguole** [comment]
Sorry,it's my fault. The json use php variable in php code between " is `.$Variable Name. `  .  Like: `{"key":".$randtoken."} `

Thanks for ur work. Onlyoffice is a wonderful   &incredible project👍🏻👍🏻👍🏻

**Comment by ShockwaveNN** [comment]
Ok thanks for feedback, in that case I'll close this issue
