### ISSUE TITLE
I can't wrap lines with spaces when I use Block/Inline LvlSdt。/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by blurries** [ONLYOFFICE/DocumentServer#1533]
I use Api to Create a BlockLvlSdt or InlineLvlSdt, I want set typesetting the word, use some blank space. but it can't warp
![image](https://user-images.githubusercontent.com/16989791/144201585-8632c0a6-b4d5-43c1-8882-da2214e0a14b.png)

**Comment by ShockwaveNN** [comment]
Hi, we need more details

Please fill out issue template correctly, specify your DocumentServer version, host os and other info and attach script you've used to call those mthods

**Comment by blurries** [comment]
bug
https://api.onlyoffice.com/docbuilder/textdocumentapi/ApiTextPr
Enter some spaces at the end of a line
Ctrl+A select all paragraph
![image](https://user-images.githubusercontent.com/16989791/144364336-e866fa8d-f35c-4328-a0e4-8f95ac4343c9.png)
DocumentServer version:6.4.0.121
Server Operating System:CentOS8
Operating System:Window10
Browser version:Chrome 92.0.4515.159

**Comment by ShockwaveNN** [comment]
@askonev please take a look at this issue

**Comment by askonev** [comment]
@blurries  Hi! This is not a bug because this behavior is technically the same as in ms office.

![image](https://user-images.githubusercontent.com/60688343/144603465-c4fa2f75-b44a-4735-a48f-a0cbf918648e.png)

**Comment by blurries** [comment]
> This is not a bug because this behavior is technically the same as in ms office.
