### ISSUE TITLE
Cannot read properties of undefined (reading 'MN')

### ISSUE THREAD

**Issue by kaizi000** [ONLYOFFICE/DocumentServer#1535]
![image](https://user-images.githubusercontent.com/22171155/144565627-898b47dc-3bd0-4855-9c90-2e75b7d9de46.png)

**Comment by ShockwaveNN** [comment]
I think this issue is with DocumentServer, not with nextcloud

So please add info about your DocumentServer version, installation method and host os

Also attach file for which this problem happened

**Comment by kaizi000** [comment]
DocumentServer version:6.2.2-21 (Linux onlyoffice-556b8f977c-dxn46 3.10.0-957.12.1.el7.x86_64)
Server Operating System:Ubuntu 20.04.2
Operating System:Window10
Browser version:Chrome  96.0.4664.45

**Comment by ShockwaveNN** [comment]
> DocumentServer version:6.2.2-21 

This is rather old version and we've released several major version and several bugfixes

Please update to current stable v6.4.2 and see if problem persists

**Comment by kaizi000** [comment]
I have upgraded version to 6.3.0-111，have  other problems.
[2022-01-06T09:14:15.062] [ERROR] nodeJS - changesError: docId = xxxx; Error: Uncaught TypeError: Cannot read properties of undefined (reading 'Nn') Script: https://onlyoffice.lixiangoa.com/6.3.0-111/sdkjs/word/sdk-all.js Line: 9186:280 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 platform: Win32 isLoadFullApi: true isDocumentLoadComplete: false StackTrace: TypeError: Cannot read properties of undefined (reading 'Nn')

**Comment by ShockwaveNN** [comment]
> I have upgraded version to 6.3.0-111

6.3.0 is not the latest version, please upgrade to latest one and after that we'll figure out error if it still occurs

**Comment by RainyGao-GitHub** [comment]
this issue maybe related with the local fonts







------------------ Original ------------------
From: Pavel Lobashov ***@***.***&gt;
Date: Thu,Jan 6,2022 8:54 PM
To: ONLYOFFICE/DocumentServer ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ONLYOFFICE/DocumentServer] Cannot read properties of undefined (reading 'MN') (Issue #1535)





  
I have upgraded version to 6.3.0-111
  
6.3.0 is not the latest version, please upgrade to latest one and after that we'll figure out error if it still occurs
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShockwaveNN** [comment]
> this issue maybe related with the local fonts

Not sure, because according to first post it happens while clicking on arrow figure

**Comment by kaizi000** [comment]
> > this issue maybe related with the local fonts
> 
> Not sure, because according to first post it happens while clicking on arrow figure

the arrow error has resolved in v6.3.0。how to sure  the correct fonts

**Comment by ShockwaveNN** [comment]
@kaizi000 Sorry, do not understand you at all

**Comment by kaizi000** [comment]
> correct



> > this issue maybe related with the local fonts
> 
> Not sure, because according to first post it happens while clicking on arrow figure



> > this issue maybe related with the local fonts
> 
> Not sure, because according to first post it happens while clicking on arrow figure

the error has resolved in v6.3.0 while clicking on arrow figure

**Comment by ShockwaveNN** [comment]
Ok, in that case, I'll close your issue, but I still advise you to update not to v6.3.0 but to the latest stable v6.4.2

**Comment by kaizi000** [comment]
the v6.3.0 is maximum version with permissions，so not  to the latest stable v6.4.2
