### ISSUE TITLE
How about the progress of Asia fonts support?

### ISSUE THREAD

**Issue by Sraw** [ONLYOFFICE/DocumentServer#154]
Since May, your team declares that you started developing fonts support for Asia fonts.

Now it is August, how about the progress?

I think there are at least two features should be implemented:

1. Set the default converted font to a font which support Asia fonts(e.g. Chinese, Japanese) if there is no font matched.

2. Automatically change the input default font if the input font is an Asia font.

Thanks for reply.

**Comment by heiyv** [comment]
I have the same problem. Same Chinese fonts cant correct identification like 仿宋.ttf.

**Comment by shurik09** [comment]
same issue here, I need Korean 말곤 고딕.ttf (malgun.ttf) font support

**Comment by changuoqiang** [comment]
I have a patch to resolve this problem, and pull request to core repo long time ago, but it not merged into upstream yet 
https://github.com/ONLYOFFICE/core/pull/57

**Comment by ShockwaveNN** [comment]
Issue shoul be reaolved in DocumentServer 5.3

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
