### ISSUE TITLE
how to disable print and enable commeting via wopi protocol for view mode

### ISSUE THREAD

**Issue by manjulaghanti** [ONLYOFFICE/DocumentServer#1541]
**Do you want to request a *feature* or report a *bug*?**
how to disable print and enable commeting via wopi protocol for view mode

**What is the current behavior?**
user based permission to enable and disavle print,download and commenting for view mode

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

By default print and download button appearing, and commenting is not enabled.

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
@igwyd Please, take a look as soon as you got free time

**Comment by ShockwaveNN** [comment]
@manjulaghanti Actually my collegues are talking that you've contacted our official support

In that case we prefer to handle this situation via support and I'm closing this issue

**Comment by wooln** [comment]
disable print:  [DisablePrint | CheckFileInfo | ONLYOFFICE](https://api.onlyoffice.com/docs/docs-api/using-wopi/wopi-rest-api/checkfileinfo/#DisablePrint)
