### ISSUE TITLE
Spreadsheet cursor flickering on last versions of Firefox ESR

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DocumentServer#1542]
We can observe a blinking/flickering/disappearing mouse pointer on Spreadsheet sheets since we upgrade to Firefox 91 ESR on some ACER laptops only. Deactivating graphic acceleration on Firefox didn't resolve problem.

What we have tested to target the problem :
- ACER laptop, with Edge => no problem, cursor OK
- ACER laptop, with OO Desktop Editors => no problem, cursor OK
- ACER laptop, with Firefox 86 ESR => no problem, cursor OK
**- ACER laptop, with Firefox 91ESR or 95 => cursor flickering**
- ACER laptop, all versions of Firefox, Document Editor => no problem, cursor OK
- other machines, all versions of Firefox : no problem, cursor OK
- ACER laptop opening a mstsc window on a machine with Firefox 91 ESR => no problem, cursor OK

The Spreasheet Editor is quite unusable when cursor is flicking : you don't know where your pointer is until you stop to move the mouse.

**Comment by Mer0me** [comment]
Installing 6.4.2 broke the Onlyoffice/Nextcloud integration. Now, I get the message "Cannot save document" when I try to open any file.
I had to add some stuff by hand in the default.json config file because I've refused to replace our config files by new ones from the packet during apt update. I've added the "wopi" section and 2 lines on the "Services" section. Can it be the cause of the trouble ?

**Comment by ShockwaveNN** [comment]
It may be because by design you should make and changes to `default.json` and store any local you-specific changes in config in `local.json`

**Comment by Mer0me** [comment]
Sorry for the update accident, it's ok now, 6.4.2 installed, but the problem of flickering cursor is still there.
How can we help ?

**Comment by ShockwaveNN** [comment]
@Mer0me Ok, we'll take a look in detail, but we cannot promise any results, since seems by your report - we need some specific hardware and I don't think we own it

So until we'll able to find a way to reproduce

**Comment by ShockwaveNN** [comment]
@Mer0me 

Could you record video of this problem
And specify DPI, display resoltuion and browser zoon on system there it happens

**Comment by Mer0me** [comment]
Can you see this ? 

https://user-images.githubusercontent.com/6248852/145788713-e2bcebbf-8f3f-4aed-a68f-b765fee35acd.MOV

**Comment by Mer0me** [comment]
![image](https://user-images.githubusercontent.com/6248852/145788892-a0685a63-3265-4b16-a836-65851972127d.png)

**Comment by ShockwaveNN** [comment]
Yeah, I can see a video (by downloading it), but system info is not that are we looking at, we need display info

**Comment by Mer0me** [comment]
Browser zoom : 100%
Resolution : 1920*1080

**Comment by ShockwaveNN** [comment]
Ok thansk, we'll take a look, but no promises

Because I think this may be a Firefox\Video Card problem (especially if this specific to specific system), not problem on our side

**Comment by Mer0me** [comment]
I will try to post the bug to Mozilla too.
Thanks for your effort anyway.

**Comment by ShockwaveNN** [comment]
@Mer0me I'm not sure that is Mozilla bug either, not sure at all, but feel free to

**Comment by Mer0me** [comment]
Problem appears with last version of FF. Downgrading to FF 86 ESR solve it.

**Comment by Mer0me** [comment]
I documented a bug at bugzilla : https://bugzilla.mozilla.org/show_bug.cgi?id=1758357

**Comment by Mer0me** [comment]
We found a workaround : configure windows to activate mouse trail at minimum level.

It can be done with regedit : 

[HKEY_CURRENT_USER\Control Panel\Mouse]
"MouseTrails"="2"

**Comment by ShockwaveNN** [comment]
@Mer0me Thanks for your workaround, still have no idea is this a bug at our code or at firefox, let's see that firefox team will decide

**Comment by Mer0me** [comment]
Here is the bug correction that introduced the regression on OnlyOffice/Acer laptop : https://bugzilla.mozilla.org/show_bug.cgi?id=1724120

**Comment by ShockwaveNN** [comment]
According to mozilla issue tracker this issue is resolved

@Mer0me Could you confirm that?

**Comment by Mer0me** [comment]
I can confirm that the last versions of Firefox are OK. Issue closed.

**Comment by ShockwaveNN** [comment]
@Mer0me Glad to hear, thanks, glad that Mozilla team figured out the reason
