### ISSUE TITLE
Impossible to open documents with Firefox

### ISSUE THREAD

**Issue by lepus2589** [ONLYOFFICE/DocumentServer#1543]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I came from here: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/556#issuecomment-989959055 This was the original problem:

> This happens for me, too. I don't get an error message, but the document editor gets stuck on "Loading Document..."

> Nextcloud 22.2.2 Enterprise, OnlyOffice 6.4.2, Firefox 96.0b2, Mac OS X

> Browser console shows this:

```
Uncaught TypeError: sf.o0b is not a function
    <anonymous> https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:38
    <anonymous> https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:38
    <anonymous> https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:38
    <anonymous> https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:38
fonts.js:38:265
```

```
Uncaught (in promise) TypeError: Ia.AscFonts.o0b is not a function
    el https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:19
    be https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:10
    fh https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:14
    qd https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:14
    Yg https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:32
    fh https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:24
    Yg https://<redacted domain>/6.4.2-6/sdkjs/common/libfont/wasm/fonts.js:24
fonts.js:19:102
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open any Office document with OnlyOffice on Nextcloud in Firefox.

**What is the expected behavior?**
The document should load properly.

**Did this work in previous versions of DocumentServer?**
Unknown. One day, I tried to open a document in our Nextcloud (hosted by IT department) and it didn't work. I have no idea, if the DocumentServer was updated in the interim. My browser definitely got updated. IT department shrugs their shoulders because it works in other browsers.

**DocumentServer version:**
Nextcloud 22.2.2 Enterprise, OnlyOffice 6.4.2

**Operating System:**
Client: Mac OS X
Server: unknown, probably some Linux distro

**Browser version:**
Firefox 96.0b2

Concerning @ShockwaveNN's questions:

1. I don't know, if fonts were added to the DocumentServer (hosted by IT department).
2. Yes, in Safari, it works.
3. I didn't add any fonts and I don't know how to clean the firefox font cache, specifically. I tried it, and indeed, it works in Incognito mode! The bug only happens in normal mode.

**Comment by ShockwaveNN** [comment]
> it works in Incognito mode! The bug only happens in normal mode.

In that case I think is something wrong with cache and not a bug (or at least we almost sure never able to reproduce it)

This is first google result for [Firefox clear cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache)

**Comment by lepus2589** [comment]
I cleaned the cache and data for our Nextcloud domain only using these instructions (for anyone also stumbling over this problem): https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox I didn't want to clear all my cache.

It fixed the problem! Thanks for the tip and sorry for the noise. This was really frustrating.

**Comment by ShockwaveNN** [comment]
No problem, I personally think we got some bug with that, but scenario with old cache and updates of font files are very complicated so it will require a lot of work to reproduce this issue, but a "clean cache" workaround is easy and robust enough to think about investing some time in other issues
