### ISSUE TITLE
Download file error

### ISSUE THREAD

**Issue by wengguanjie1997** [ONLYOFFICE/DocumentServer#1547]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Error:
```
[ERROR] nodeJS - error downloadFile:url=http://xxx.xxx.com/download/file/only26065309913441/5fb10499c3549c97/d6f8dde59e1c06f8a4bb712e7037277b.pptx?ut=eyJvY2lkIjoiYzQzYWFmN2NmOGNlOGNjZTZiNzI3MzFmMzY1ZTM3YjYiLCJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlaWQiOjEsInN1YiI6Im9hdG9zLmNvbSIsImlhdCI6MTYzOTM2MjEyNSwidWlkIjoyfQ.KKmAxfnOMH-kZnvheU-JxszMjESynRPYxAaueDXF7No;attempt=1;code:ETIMEDOUT;connect:null;(id=26065309913441_3144_view)^M Error: Error: whole request cycle timeout     at raiseError (/snapshot/server/build/server/Common/sources/utils.js:0:0)     at Timeout._onTimeout (/snapshot/server/build/server/Common/sources/utils.js:0:0)     at ontimeout (timers.js:436:11)     at tryOnTimeout (timers.js:300:5)     at listOnTimeout (timers.js:263:5)     at Timer.processTimers (timers.js:223:10)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

Error:

**Comment by verydemo** [comment]
downloadFile:url is too long.

**Comment by wengguanjie1997** [comment]
Why does the length of the url affect the download?

**Comment by verydemo** [comment]
> 为什么url的长度会影响下载？
我也遇到过，提过issue,官方一直没修改

**Comment by ShockwaveNN** [comment]
Hi, please fill out issue template fully, not only error message
