### ISSUE TITLE
x2t convert ,FontFamily is changed, fontsize is changed.

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1548]
#### BUG: 
 x2t convert ,FontFamily is changed, fontsize is changed. 
FontFamily : 宋体 -> 等线;
fontsize: 24 -> 20;

#### behavior:
./x2t test.docx testa.bin
./x2t testa.bin testa.docx

#### files:
[test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/7701012/test.docx)
[testa.docx](https://github.com/ONLYOFFICE/DocumentServer/files/7701016/testa.docx)

![Snipaste_2021-12-13_12-21-06](https://user-images.githubusercontent.com/29354679/145753079-0554bda2-8d37-4906-b420-055492fefa61.png)

#### reason ：
`w:asciiTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi" w:eastAsiaTheme="minorHAnsi"`
Each w:r->w:rPr->w:rFont has the above three attributes,
```
      <w:r>
        <w:rPr>
          <w:rFonts w:cs="Calibri" w:asciiTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi" w:eastAsiaTheme="minorHAnsi"/>
          <w:b w:val="0"/>
          <w:bCs w:val="0"/>
          <w:sz w:val="24"/>
          <w:szCs w:val="24"/>
        </w:rPr>
        <w:fldChar w:fldCharType="end"/>
      </w:r>
```

**Comment by verydemo** [comment]
#1504  is same.

**Comment by ShockwaveNN** [comment]
Hi, I've got two questions

1. Could this issue be reproduced without direct usage of `x2t`. `x2t` is not designed to be used by users, so you should upload your file to DocumentServer and download it back as `docx` to check if we lost something
2. I've rechecked your issues on v6.4.2 and I see some minor changes in `rFonts` parameters, but seems nothing is lost

But I've rechecked your file also on v7.0.0 which is currently on the latest stage of development - and for me, it seems that your file get better - could you check by itself on `docker run -itd -p 80:80 onlyoffice/4testing-documentserver-ee:7.0.0.83`

But please note that v7.0.0 currently is not finalized so it's not suitable for production use

**Comment by ShockwaveNN** [comment]
Ok, seems you're already find issue, and seems we do not completely fix it

Thanks for report!
