### ISSUE TITLE
Support for custom slide layouts

### ISSUE THREAD

**Issue by wrighteap** [ONLYOFFICE/DocumentServer#1551]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

The current feature set for customizing and saving layouts appears limited to adding objects to existing layouts. The ability to define, save and use custom layouts would be greatly appreciated! Interestingly, version 6.4.2 appears to already detect custom layouts defined in other office suits, e.g. in a .pptx presentation.

**Comment by jagjordi** [comment]
Is there any plan to implement this feature. In my view it is a quite important one

**Comment by candideu** [comment]
+1 for this. I really like the Presentation editor, but this is what I'm really missing...

**Comment by ElenaMaaya** [comment]
I have great news! In the version 8.1 this enhancement has been successfully implemented.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
