### ISSUE TITLE
Error in spread sheet function DATEDIF

### ISSUE THREAD

**Issue by plan3d** [ONLYOFFICE/DocumentServer#1556]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
DATEDIF returns wrong result if month of start date and end date are equal
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert in cell A1 date value 2020/10/2 and in cell B1 value 2021/10/1 and in cell C1 the formula "=DATEDIF(A1;B1;"Y")" -> cell C1 is evaluated to 1
**What is the expected behavior?**
Cell C1 should be evaluated to 0
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

The calculation in https://github.com/ONLYOFFICE/sdkjs/blob/b51baac873046b8a2070afb150a0d1c517cbf284/cell/model/FormulaObjects/dateandtimeFunctions.js#L647 may be wrong

**Comment by alinasafonova** [comment]
Hello, @plan3d 
I can confirm - this is bug, issue 54552 in our private issue tracker.
Thank you for report.

**Comment by jzmini** [comment]
Half a year has passed, is there any update?

**Comment by ShockwaveNN** [comment]
@jzmini Sorry, not news

**Comment by alinasafonova** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/70bc04522c09aff4b003ef9d2b4ad28913481fd6

It will be released as v7.4.0

**Comment by DenisDeeSign** [comment]
DocumentServer v7.4.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
