### ISSUE TITLE
VLOOKUP does not fetch the correct cell (problem with uppercase?)

### ISSUE THREAD

**Issue by pdehaye** [ONLYOFFICE/DocumentServer#1558]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.4.2.6

### Expected Behavior

In the use case screenshotted below, I would expect the first two columns to be identical, since I am using a simple VLOOKUP formula.

### Actual Behavior

Rows 9, 16 and 17 contain two different entries in the example. 

![image](https://user-images.githubusercontent.com/3274335/146390890-0e6906e0-c9b7-4bd3-b54a-07878a8e42bb.png)
[test_vlookup.ods](https://github.com/ONLYOFFICE/DesktopEditors/files/7728117/test_vlookup.ods)

### Reproduction Steps

See attached file. 

### Additional information

The issue is also present on the Document Server, see https://github.com/ONLYOFFICE/DocumentServer/issues/1544

**Comment by ShockwaveNN** [comment]
Thank you for your report

We've created issue 54560 in our private issue tracker to figure out this problem

Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by rsnegirev** [comment]
Hi @pdehaye 

The problem was fixed in this one commit:
https://github.com/ONLYOFFICE/sdkjs/commit/a8b628dfee92a2fbf613c019db1c740bfaf031b4

Fixes will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
