### ISSUE TITLE
Save documents to a custom file storage service

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1559]
**Do you want to request a *feature* or report a *bug*?**
feature?

**What is the current behavior?**
The file storage location can be modified by configuring the storagePath and storageFolder fields. Can this address be designated as a third-party file storage service? For example, set it to https://oss.exmple.com/document, because I want to store the files in a separate place instead of on the same server as the onlyoffice service.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
6.4.2

**Operating System:**
macOS Mojave 10.14.5

**Browser version:**
Chrome 95.xxx

**Comment by ShockwaveNN** [comment]
Hi

1. This is config for storing temp cache files, because by design DocumentServer do not store any files, it need to connect to DMS (Document Management System) which stores all files in constant way.
So to store files on https://oss.exmple.com/document - you need DMS which store files there

2. If you want to store cache on [this](https://oss.exmple.com/document) - as far as I'm aware it support on linux files and s3
You didn't describe what is the instance of https://oss.exmple.com/document. If this is just a Linux server - you can setup CIFS share and mount it on DocumentServer instance and store cache files `as local`

**Comment by bszhct** [comment]
Do you mean the cache files in the directory /var/lib/onlyoffice/documentserver/App_Data/cache/files? If it is a cache file, is there an automatic cleaning mechanism? Will it accumulate more and more?

**Comment by ShockwaveNN** [comment]
As far as I remember it's automatically clean itself up as soon as file correctly saved to DMS

**Comment by bszhct** [comment]
I want to confirm one thing first. Regarding the DMS you mentioned, onlyoffice has a DMS service by default, right?

**Comment by ShockwaveNN** [comment]
> DMS service by default

We got nodejs integrated example shipped with every DocumentServer by default (it's enabled via `http://docserverurl/welcome` page) - it's an example, not for production use

And we got ONLYOFFICE CommunityServer - full suite of DMS, CMS, Project Management and etc
It should installed separately or as part of ONLYOFFICE Workspace

**Comment by bszhct** [comment]
I saw this configuration in the configuration of /etc/onlyoffice/documentserver/default.json:

![image](https://user-images.githubusercontent.com/56250514/146742104-469bb464-7a9f-426d-a58c-c8ccc4649a5c.png)

This is the built-in DMS service, right?

**Comment by bszhct** [comment]
Great God, are there any examples of custom DMS? @ShockwaveNN

**Comment by ShockwaveNN** [comment]
> This is the built-in DMS service, right?

This is cache, all DMS-related code is in `test example`

> Great God

I'm sorry that????

> are there any examples of custom DMS

We got example on different languages [here](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example)

But those are just example, not suited for production use as I said before

For production use - use ONLYOFFICE CommunityServer, Nextcloud, Owncloud and [etc](https://www.onlyoffice.com/all-connectors.aspx) (more than 20)

**Comment by bszhct** [comment]
> This is cache, all DMS-related code is in test example

OK.

> I'm sorry that????

You are my great god. You have answered many of my questions. Thank you very much.

> We got example on different languages here

Thanks, let me learn.

**Comment by ShockwaveNN** [comment]
> You are my great god. You have answered many of my questions. Thank you very much.

Ok, thanks, but usually this phrase mean some kind of frustration

**Comment by bszhct** [comment]
Sorry for my poor English level. I originally wanted to express honorifics. In my language, it means "大佬". I think this is caused by national differences, right? Feel sorry...

**Comment by bszhct** [comment]
Thanks, I get it.

**Comment by ShockwaveNN** [comment]
You're welcome
