### ISSUE TITLE
Petição Inicial

### ISSUE THREAD

**Issue by keysecf** [ONLYOFFICE/DocumentServer#156]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

**Comment by trofim24** [comment]
#157
