### ISSUE TITLE
Small numbers rounded to 0 while converting xls -> xlsx

### ISSUE THREAD

**Issue by charvotj** [ONLYOFFICE/DocumentServer#1560]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

6.4.2.17

### Expected Behavior

Import data from XLS file correctly

### Actual Behavior

When opening an XLS file with very low values (eg. 0,00000001039792031), program seems to round them to a clear "0". If I then write the exact same values manualy and save file as XLSX, the right values remain.

### Additional information

It could be related to the czech decimal point ",", but other (shorter) decimal values remains correct.

I'm actually using Manjaro and I'm not sure if my version is the RPM or DEB package.

**Comment by alinasafonova** [comment]
@charvotj
This problem is fixed in https://github.com/ONLYOFFICE/core/commit/efeaf9b8d1bcdea6b91d8175a458d371c84e17dc

It will be released as v7.1.0

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
