### ISSUE TITLE
copy whole document，picture can not copy to new documet，need again upload picture one by one 

### ISSUE THREAD

**Issue by kaizi000** [ONLYOFFICE/DocumentServer#1566]
![image](https://user-images.githubusercontent.com/22171155/147716427-27714776-1d32-4174-ac3f-2baaa775b450.png)

**Comment by ShockwaveNN** [comment]
Hi, please fill out issue template with all needed information, like versions, step-by-step scenario and all other items

**Comment by Edison6351** [comment]
@kaizi000 replay @ShockwaveNN 's question

**Comment by kaizi000** [comment]
> Hi, please fill out issue template with all needed information, like versions, step-by-step scenario and all other items

DocumentServer version:6.2.2-21 (Linux onlyoffice-556b8f977c-dxn46 3.10.0-957.12.1.el7.x86_64)
Server Operating System:Ubuntu 20.04.2
Operating System:Window10
Browser version:Chrome 96.0.4664.45

**Comment by ShockwaveNN** [comment]
> DocumentServer version:6.2.2-21

This version is rather old

Please upgrade to latest stable 6.4.2 and see if problem still occurs
If so - please describe a step-by-step scenario to reproduce it
