### ISSUE TITLE
chrome browser crash ： when sort file (the file has 10w rows and 30 columns )  (excel)

### ISSUE THREAD

**Issue by crystalstone** [ONLYOFFICE/DocumentServer#1569]
when i sort a file which has has 10w rows and 30 columns , and use " sort extend unselected area", the browser always crash

**Comment by crystalstone** [comment]
When I open "autosave" ,  may because "History.GetSerializeArray()" 

![image](https://user-images.githubusercontent.com/5661922/147800385-b7191c7c-8759-4b40-a74e-5815d67668b4.png)

But I close "autosave", chrome browser also crashed

**Comment by ShockwaveNN** [comment]
First of all - please fill out issue template and specify version of product, os and all other information

Second of all - if problem occurs on latest v6.4.2 - we need this exact file

**Comment by crystalstone** [comment]
> First of all - please fill out issue template and specify version of product, os and all other information
> 
> Second of all - if problem occurs on latest v6.4.2 - we need this exact file
（1）version：v6.4.2；chrome version：96.0.4664.110。
（2）file：how can i send the file to you？
I think crash will always happen when sort a excel file which has 10w rows and 30 column , because the memory over 4g



![image](https://user-images.githubusercontent.com/5661922/147810703-2dc34d2e-606b-4db7-be53-57fe3c13f08b.png)

**Comment by ShockwaveNN** [comment]
If this file is not private or you can remove all private data - it's better to attach it directly to github

If this not possible - please send it to files@onlyoffice.com with title `GitHub DocumentServer#1569` - we'll take a look after holidays

**Comment by ShockwaveNN** [comment]
@crystalstone We still didn't received any file on files@onlyoffice.com. Is the issue still actual for you?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
