### ISSUE TITLE
 Found an error while editing a text, where part is copied externally and part typed. The part entered does not adhere to the formatting entered through the editor. See GIF with error.

### ISSUE THREAD

**Issue by keysecf** [ONLYOFFICE/DocumentServer#157]
**Do
) you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
![error_selection_edit](https://user-images.githubusercontent.com/20209834/29379046-8627e938-8297-11e7-8978-ca43ddba9560.gif)

**Comment by flaminestone** [comment]
This problem is already fixed and will be gone in the next version. Thank you for report.

**Comment by ShockwaveNN** [comment]
Closing since fixed in 5.1.0
