### ISSUE TITLE
Excel-image-blur-problem

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1572]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Excel-image-blur-problem
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[excel-file](https://github.com/nobt854/self_file/raw/main/Excel-image-blur-problem.xlsx)
**What is the expected behavior?**
The picture is displayed normally
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer version:**
6.4.2
**Operating System:**
windows
**Browser version:**
chrome 96.0.4664.110

**Comment by Rita-Bubnova** [comment]
Hello, @nobt854.
I can confirm - this is bug, issue 54795 in our private issue tracker. 
Thank you for report.

**Comment by Rita-Bubnova** [comment]
This issue fixed in a future major release (but I can't give a specific commit as there were many fixes).

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
