### ISSUE TITLE
Request for dark theme to affect page colour

### ISSUE THREAD

**Issue by FiraliaDev** [ONLYOFFICE/DocumentServer#1576]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Dark theme does not affect page colour. 
The page colour remains white, and creates an extremely bright contrast that hurts the eyes.

**What is the expected behavior?**
Dark theme affects page colour, similar to how it functions in the latest versions of Microsoft Word.
Page colour should be tied to theme, and not individual documents themselves. Ideally would be toggleable like in Word, so that it's easy to check what your document looks like for printing.

This was a recent absolute godsend for someone with sensitive eyes. No alternatives seem to support it as of now (as far as I know), and it's the only thing keeping me from dropping Microsoft Office altogether.

**Comment by ShockwaveNN** [comment]
![image](https://user-images.githubusercontent.com/668524/148673957-9d202de4-05de-4fdb-a168-772f30cd850d.png)

Hi, we already implemented this mode and it will be available in v7.0 - hope we will release this version this month in a week or two

> Ideally would be toggleable like in Word

Yes, it will:
![image](https://user-images.githubusercontent.com/668524/148674048-62dc09f7-bf67-4b00-94eb-f1bd5e0c7a3d.png)

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open new issue if problem still actual
