### ISSUE TITLE
cannot edit word files after entering jwt token

### ISSUE THREAD

**Issue by msevgen** [ONLYOFFICE/DocumentServer#1578]
Hi
I'm using Onlyoffice 6.3.1.32 & Nextcloud 22.2.3 without issue. 
I did a clean install of Onlyoffice version 6.4.2.6 on Ubuntu 18.4.5.
after installation the example worked fine.

I entered jwt security token in local.json file. In the example, when I wanted to open a file, I started getting the error "The document security token is not correctly formed".

local.json is : 
```json
{
  "services": {
    "CoAuthoring": {
      "sql": {
        "type": "postgres",
        "dbHost": "localhost",
        "dbPort": "5432",
        "dbName": "onlyoffice",
        "dbUser": "onlyoffice",
        "dbPass": "xxxxxxxxxxx"
      },
 "server": {
    "token": {
      "enable": true,
      "secret": "xxxxxxxxxxxxxxxxxxxxxxxx",
      "authorizationHeader": "AuthorizationJwt"
    }
  },
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "AuthorizationJwt"
        },
        "outbox": {
          "header": "AuthorizationJwt"
        }
      },
      "secret": {
        "inbox": {
          "string": "xxxxxxxxxxxxxxxxxxxxxxxx"
        },
        "outbox": {
          "string": "xxxxxxxxxxxxxxxxxxxxxxxx"
        },
        "session": {
          "string": "xxxxxxxxxxxxxxxxxxxxxxxx"
        }
      }
  }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}

```

When I do the Newtxloud integration, I can open and save Excel files without any problems. 
When I open Word files I cannot make any changes and all controls seem to be disabled.

There is no way I haven't tried. I reinstalled onlyoffice multiple times according to the https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx instructions.

There was no change when use this commands:
echo onlyoffice-documentserver onlyoffice/jwt-enabled boolean true | sudo debconf-set-selections
echo onlyoffice-documentserver onlyoffice/jwt-secret password xxxxxxxxxxxxxxxxxxxxxxxx | sudo debconf-set-selections
 
where am i doing wrong? please help me.

**Comment by msevgen** [comment]
hi,
thank you for quick answer.
I am not using proxy. I just installed onlyoffice version 6.4.2.6.
I did a standard install. I have additionally installed some special fonts with otf extension.

When I use token value is false, I can make changes to word-excel files in https://onlyoffice2.domain.com/example.

`     "token": {
        "enable": {
          "request": {
            "inbox": false,
            "outbox": false
          },
          "browser": false
        },
`
When I use token value is true, the https://onlyoffice2.domain.com/example interface works, the file can be uploaded.
when I want to open one of the word or excel files. I get an error :
"The document security token is not correctly formed" 
![2022-01-12_09-49-40](https://user-images.githubusercontent.com/97592698/149142678-94929578-e933-4e17-92c0-e6eaffbd4e39.png)
Is there a bug or am I doing something wrong?

**Comment by ShockwaveNN** [comment]
> when I want to open one of the word or excel files. I get an error :

You've mention earlier that only word files raise this problem but with `/example` both word and excel files raising it, am I correct?

> Is there a bug or am I doing something wrong?

I don't think there is a bug, just a misconfiguration

Maybe it's better to try docker versions? Seems that something went wrong on configuration step and some values of JWT is messed-up (just a guess)

**Comment by msevgen** [comment]
Yes true. I get error in example when jwt is enabled. In this case, nextcloud integration can be done.
Excel files can be edited but word files cannot in nextcloud.

I didn't use the docker version because nextcloud and onlyoffice are on different servers. I wanted to update the onlyoffice application, but I did not want any interruption in updating the currently used application, so I install new version on a separate server.

**Comment by ShockwaveNN** [comment]
@msevgen I think some configs messed up

I think it's better to setup once again a clean installation
After that do not change `local.json` manually but use `debconf-set-selections` as mention [here](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx) for setup JWT

I advice you to use docker so it's simpler to start anew if something went wrong and using docker env variables to setup JWT for me is much simpler, than remembering `debconf` not so trivial syntax

**Comment by msevgen** [comment]
hi,
I installed the docker version as you said.

my installation script on Ubuntu 18.4.5 is :
`
sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

 echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io


sudo docker run -i -t -d -p 80:80 -p 443:443 -e JWT_ENABLED='true' -e JWT_SECRET='xxxxxxxxxxxxxxxxxxxxxxxx' -e JWT_HEADER='AuthorizationJwt' -e JWT_IN_BODY='True' -e DB_PWD='xxxxxxxxxxxxxxxx' --restart=always \
    -e LETS_ENCRYPT_DOMAIN=onlyoffice2.mydomain.com-e LETS_ENCRYPT_MAIL=it@mydomain.com  onlyoffice/documentserver

`
I can edit word and excel files on the example page.
Excel files can be edited when I do the nexcloud integration.
word files can only be viewed, not edited. Editor controls is disabled.

I can edit both files in onlyoffice old version. (6.3.1.32)
my nexcloud version:22.2.3
Is the problem caused by nextcloud or am I doing something missing in the onlyoffice installation?
I would appreciate it if you could share your thoughts.
best wishes.

![2022-01-20_16-38-20](https://user-images.githubusercontent.com/97592698/150349444-a89fe390-f46e-4623-a282-04f70f7a03a2.png)

**Comment by ShockwaveNN** [comment]
> Is the problem caused by nextcloud 

I think it is, I'm not very good with nextcloud so I'm not sure that I can help it

It definitely not a problem with JWT, because in that case Editor wouldn't; allow even open document


I got two ideas
1. Please check that in incognito mode controls still disabled
2. Check JS console for any errors
3. Check DocumentServer logs (`/var/log/onlyoffice/` in container for any errors) and nextcloud logs (Sorry, don't know which ones)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by xclsky1** [comment]
> hi, I installed the docker version as you said.
> 
> my installation script on Ubuntu 18.4.5 is :
> 
> ```
> sudo apt-get update -y
> sudo apt-get upgrade -y
> 
> sudo apt-get install \
>     ca-certificates \
>     curl \
>     gnupg \
>     lsb-release
> 
> curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
> 
>  echo \
>   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
>   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
>   
> sudo apt-get update
> 
> sudo apt-get install docker-ce docker-ce-cli containerd.io
> 
> 
> sudo docker run -i -t -d -p 80:80 -p 443:443 -e JWT_ENABLED='true' -e JWT_SECRET='xxxxxxxxxxxxxxxxxxxxxxxx' -e JWT_HEADER='AuthorizationJwt' -e JWT_IN_BODY='True' -e DB_PWD='xxxxxxxxxxxxxxxx' --restart=always \
>     -e LETS_ENCRYPT_DOMAIN=onlyoffice2.mydomain.com-e LETS_ENCRYPT_MAIL=it@mydomain.com  onlyoffice/documentserver
> ```
> 
> I can edit word and excel files on the example page. Excel files can be edited when I do the nexcloud integration. word files can only be viewed, not edited. Editor controls is disabled.
> 
> I can edit both files in onlyoffice old version. (6.3.1.32) my nexcloud version:22.2.3 Is the problem caused by nextcloud or am I doing something missing in the onlyoffice installation? I would appreciate it if you could share your thoughts. best wishes.
> 
> ![2022-01-20_16-38-20](https://user-images.githubusercontent.com/97592698/150349444-a89fe390-f46e-4623-a282-04f70f7a03a2.png)


 This is not a bug. Final and Original mode display the document in viewer
