### ISSUE TITLE
Request for a new Shortcut

### ISSUE THREAD

**Issue by oMrSmith** [ONLYOFFICE/DocumentServer#1582]
which will immediately insert text from the clipboard
_without the original formation_!

This works very well in Thunderbird
with the shortcut Control+Shift+V...

In MS Word this would open a dialog first
which I find so annoying as it slows everything down.

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1002.
