### ISSUE TITLE
Error "Fonts are not downloaded"

### ISSUE THREAD

**Issue by L0ul0u76** [ONLYOFFICE/DocumentServer#1584]
Hello,

I have install Onlyoffice document server on a Debian 10 server to use with nextcloud and when I try to open a document with onlyoffice I have the error "Fonts are not downloaded" (I think it's the good translation because my nextcloud is in french).

Have you some idea for solve this problem ?

Thank's

**DocumentServer version:**

onlyoffice-documentserver/squeeze,now 6.4.2-6 amd64 [installed]

**Operating System:**

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

**Comment by ShockwaveNN** [comment]
Hi, could you try to reproduce this error in different browser in Incognito mode or on different client PC

Usually, this error means two possible things:
1. Networking errors. Fonts sometimes (especially CJK) are rather big and sometimes some proxy limit downloading of files bigger for example than 5 MB
2. Cache errors. Usually, this happens after upgrades, but this seems not your case if it's clean install

**Comment by L0ul0u76** [comment]
> 

Hi, thank's for this idea. The problem append only on one of my browser but not in private mode. So it's certainly a cache errors.

Thank you,
