### ISSUE TITLE
Conversion from .docx to .rtf breaks styles

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/DocumentServer#1590]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The conversion from .docx to .rtf breaks styles.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Convert a docx file to rtf using the conversion API or through the "Download as..." menu.

**What is the expected behavior?**
The styles should load correctly on Microsoft Word or Microsoft Wordpad

**Did this work in previous versions of DocumentServer?**
Not on 6.x, but it worked on 5.6.5

**DocumentServer version:**
6.4.2 or 7.0.0

**Operating System:**
Microsoft Windows 10

**Browser version:**
Google Chrome 91

![image](https://user-images.githubusercontent.com/14880633/150032611-518e339f-0c66-48b5-a6cf-9e25804b7180.png)
![image](https://user-images.githubusercontent.com/14880633/150032686-f4edeb20-77e5-4632-b190-067134e06374.png)

Looking at the converted .rtf file, you can see the reason. Characters inside ASCII range are encoded using the \u<code>* escape sequences. They shouldn't. On versions before 6.x, those caracters were not encoded using escape sequences, only those characters outside the ASCII.

**Comment by Gingetsu** [comment]
Hello, @tsmgodoi .
Thank you for the report.
I can confirm - this is a bug, issue 54957 in our private issue tracker.

**Comment by Gingetsu** [comment]
Hello, @tsmgodoi . Our dev team is fixed your issue in version v7.1.0 which will be released in a month (But sorry, no exact ETA)
This fixed here: ONLYOFFICE/core@db2930e

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
