### ISSUE TITLE
Documentserver EE update  6.4.2.6 to 7.0.0.132 fails and renders service unavailable

### ISSUE THREAD

**Issue by budachst** [ONLYOFFICE/DocumentServer#1592]
**Do you want to request a *feature* or report a *bug*?**
Update bug

**What is the current behavior?**
Documentserver can't open documents

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Update Documentserver EE from 6.4.2.6 to 7.0.0.132 using yum
While updating this error was encountered:

Incorrect DB_TYPE value! Possible value of DB_TYPE is 'postgres' or 'mysql'.
warning: %post(onlyoffice-documentserver-ee-7.0.0-132.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package onlyoffice-documentserver-ee-7.0.0-132.x86_64

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
No issues with previous updates

**DocumentServer version:**
7.0.0.132
**Operating System:**
CentOS Linux release 7.9.2009 (Core)

**Browser version:**
Firefox 96.01

**Comment by igwyd** [comment]
Hello @budachst, attach please your onlyoffice config files - /etc/onlyoffice/documentserver/local.json and /etc/onlyoffice/documentserver/default.json without secret information

**Comment by budachst** [comment]
Hi @igwyd,

actually my install hasn't a local.json, but only a default.json. I have stripped it from sensitive information and attached it to this message.

At this time, I have rolled-back my VM, but I am ready to give it another try
[default_json.txt](https://github.com/ONLYOFFICE/DocumentServer/files/7899071/default_json.txt)
.

**Comment by igwyd** [comment]
@budachst when updating installer looking for local.json file and DB setting for update DB. Did you delete local.json yourself?
Specific settings should be added to the local.json if you want update documentserver and save configuration, more [here](https://api.onlyoffice.com/editors/faq/general).

**Comment by budachst** [comment]
Hi @igwyd  - no, I didn't delete it. I am running two instances and neither of them has the local.json. Both installations are already 2 to 3 years old and I am sure, that there never had been a local.json. I will have a look at the link you provided, but I am not sure, if I can create a completely new local.json manually.

**Comment by igwyd** [comment]
I attach default local.json file for 6.4.2 version of onlyoffice-documentserver, try put it in etc/onlyoffice/documentserver/, edit with your settings and after update your installation. 
[local.json.txt](https://github.com/ONLYOFFICE/DocumentServer/files/7903437/local.json.txt)

**Comment by igwyd** [comment]
We have a bug 50603 for this and we are working to have some error if there is no local.json file, because the absence of this file is not normal.

**Comment by budachst** [comment]
Thank you - I was able to successfully update by creating the local.json file from your template. However, I have already tweaked the default.json in the past, e.g. to allow for larger file uploads and from the documentation I took, that one never should alter the default.json file.

Does this mean, that I will have to somehow check and move the changes I made to default.json to local.json?

**Comment by igwyd** [comment]
Yes, need move changes from default.json to local.json if you want save settings. When updating, the file default.json will be replaced with a new one, but local.json with your settings will not change.

**Comment by budachst** [comment]
But… the current update didn't replace the default.json, so I guess, I was lucky in that regard. I have changed the local.json to just accomodate the options I had changed in default.json. I have attached my new local.json, maybe you can tell me, if this looks good for you
[local.json.txt](https://github.com/ONLYOFFICE/DocumentServer/files/7903903/local.json.txt)
.

**Comment by igwyd** [comment]
In my case default.json was replased on update, you may have some specific server settings i think. 
Your local.json is standard in my opinion. I'm glad you got it working.

**Comment by budachst** [comment]
Thanks @igwyd  - this was really helpful. Now I am going to update my production as well.
