### ISSUE TITLE
Wrong wiev bullets and numbering in Documet Editor

### ISSUE THREAD

**Issue by Akrobs** [ONLYOFFICE/DocumentServer#1597]
**Do you want to request a *feature* or report a *bug*?**
Yes

**What is the current behavior?**
Wrong wiev bullets and numbering

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
6.4.2, 7.0.0

**Operating System:**
CentOS 8.5

**Browser version:**
Any

Please see attachmets

MS Word 2013
![Spisok-MS](https://user-images.githubusercontent.com/57731196/150526198-efd9f7cf-f2c9-44f1-a4b1-ebac2d8edf0b.jpg)

OnlyOffice
![Spisok-OO](https://user-images.githubusercontent.com/57731196/150526208-75162a03-4678-4951-aafe-862ff9f779df.jpg)

**Comment by ShockwaveNN** [comment]
Hi, could you attach original file?

**Comment by Akrobs** [comment]
Soory, this document is confedentional, i can't share in  public access. I can sent in private message or email.

**Comment by ShockwaveNN** [comment]
@Akrobs send it to files@onlyoffice.com with title "DocumentServer Github Issue 1597"

**Comment by ShockwaveNN** [comment]
@Akrobs we got it, thanks

@Wo1fgang will take a look

**Comment by ShockwaveNN** [comment]
@Akrobs I can confirm that on a clean installation of DocumentServer those symbols render incorrect

But I think it's a fonts issue and they require font `Symbol` to be correctly rendered if I'm not mistaken

You can read this [help entry](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx) about installing additional fonts in DocumentServer

**Comment by Akrobs** [comment]
> @Akrobs I can confirm that on a clean installation of DocumentServer those symbols render incorrect
> 
> But I think it's a fonts issue and they require font `Symbol` to be correctly rendered if I'm not mistaken
> 
> You can read this [help entry](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx) about installing additional fonts in DocumentServer

Yep, i'm istall **Symbol** font and document render fine. Thanks!

Maybe your team add to help center list of needed fonts?
