### ISSUE TITLE
Read files on folder outside of the docker container

### ISSUE THREAD

**Issue by tonygonzalez811** [ONLYOFFICE/DocumentServer#16]
Hello, I would like to see the documents in a folder outside of the docker container, is it possible?

**Comment by ibnpetr** [comment]
The documents can be stored in your own storage in case ONLYOFFICE Document/Spreadsheet/Presentation Editors are [integraded into your web site](https://api.onlyoffice.com/editors/save)

They also can be accessed from outside the docker container if you have [mounted the volumes](https://github.com/ONLYOFFICE/Docker-CommunityServer#storing-data) for the Community Server Data (In case you use Onlyoffice Community Server integrated with Document Server)
