### ISSUE TITLE
I have a problem with Polish diacritic marks such as i and ć.

### ISSUE THREAD

**Issue by waldek1984** [ONLYOFFICE/DocumentServer#160]
Hi, I have a problem with Polish characters in the document server. If you can write diacritic marks, you can not insert characters with a dash (alt + x) and c with a dash (alt + c). The same is true for both the cloud and nextcloud. Can it be improved somehow, something needs to be changed?

**Comment by waldek1984** [comment]
Problem is only with small letter, capital letter is ok.

**Comment by waldek1984** [comment]
In xlsx problem is when i write in field. When i write in formula field is all ok.
In docx problem is all time.

**Comment by waldek1984** [comment]
In chrome browser is ok. Problem is in FF, Edge.

**Comment by K0R0L** [comment]
I repeated it and working on this. Thanks

**Comment by K0R0L** [comment]
https://github.com/ONLYOFFICE/sdkjs/commit/a2cf49a3a2273850e623d964913ea844dfe0b987

Wait 5.0.4
