### ISSUE TITLE
GetValue for a range

### ISSUE THREAD

**Issue by spacezmonkey** [ONLYOFFICE/DocumentServer#1604]
Hello , I am trying out macro in spreadsheet.
I realised that there is getValue function which return us 1st value of current range.

May I know if it is possible to get the whole range of values instead of 1st value of the range ( as shown below ) 
![image](https://user-images.githubusercontent.com/73033222/150837194-ac0f339c-7810-4708-80a2-f0d335753b45.png)

**Comment by trofim24** [comment]
Sorry for late response, seems we missed this issue.
Thanks for your feature request. We've implemented return array of values [for range GetValue method](https://api.onlyoffice.com/docbuilder/spreadsheetapi/apirange/getvalue)
