### ISSUE TITLE
Auto numbering of captions doesn't work

### ISSUE THREAD

**Issue by DefaultX-od** [ONLYOFFICE/DocumentServer#1608]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.0.127

### Expected Behavior

Auto numbering of images in their captions. It works in 6.4.2.6 version

### Actual Behavior

The number doesn't change, and it's always 11

### Reproduction Steps

1. Insert an image in document
2. Right click on the image
3. Click insert caption

**Comment by ShockwaveNN** [comment]
Yeah, it should be fixed on 7.0.1 but for the internal reasons we skipped release v7.0.1 of DesktopEditors, so I'll leave this issue opened until we release it

**Comment by ShockwaveNN** [comment]
Seems we forgot to close it for quite some time (

DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
