### ISSUE TITLE
Incomplete math symbols.

### ISSUE THREAD

**Issue by kingkazmam** [ONLYOFFICE/DocumentServer#161]
I find the "Insert Equation" function is very similar to Microsoft office, but some symbols which in Microsoft office is not in OnlyOffice.

Such as:
I can find the "Therefore" symbol(∴) at "Insert Equation", but there is no "Because" symbol(∵).
Many commonly used symbols also not in it, such as ⊆ ⊂ ⊇ ⊃∠⊥∥ and so on.

You can find more symbols at Microsoft office "Symbols" menu.
I really love OnlyOffice and hope it more perfect. I and my colleagues need these symbols at work, so I hope you can add more. Thanks!

**Comment by andrewerf** [comment]
Is there any progress?

**Comment by ShockwaveNN** [comment]
Yeah, seems we forgot to close those issue. (there was issue 36129 in our private issue tracker)

We decided that best place to store that extra symbols - in Symbols table, seems all those equations are in Cambria Math font
![image](https://user-images.githubusercontent.com/668524/83385367-c1ace200-a3f1-11ea-834f-e4ace784b1ce.png)
