### ISSUE TITLE
Error of view after insert equation in document editor.

### ISSUE THREAD

**Issue by Akrobs** [ONLYOFFICE/DocumentServer#1612]
**Do you want to request a *feature* or report a *bug*?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert - Equation - Radicals.
If i'm downloading document in PDF thats ok.

**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
6.4.2   7.0.0
**Operating System:**
Linux
**Browser version:**
All

Document Editor
<img width="205" alt="form" src="https://user-images.githubusercontent.com/57731196/151443000-99f1efd6-28b4-4eaf-84ca-42dba73f14ca.png">

PDF file
<img width="227" alt="form_pdf" src="https://user-images.githubusercontent.com/57731196/151443110-01a47bb5-a84e-4147-b8ef-a5b30c9c277a.png">

**Comment by ShockwaveNN** [comment]
Hi, could you clarify your DocumentServer installation method?

I think it may be missing some fonts or something like this

I've just check v7.0.0 from Docker image and it created same equation without any troubles and it displays correctly in both docx and pdf

![image](https://user-images.githubusercontent.com/668524/151515048-a3a14528-c62d-43eb-ac7d-ee29e360cdf5.png)

**Comment by Akrobs** [comment]
> Hi, could you clarify your DocumentServer installation method?
> 
Installation method from official hel center. For Linux distribution CentOS.
Step by step.

**Comment by ShockwaveNN** [comment]
Ok, I'll recheck it on Centos then

**Comment by Akrobs** [comment]
Thanks.

**Comment by ShockwaveNN** [comment]
Got the same good result on Centos 7 as well

Maybe some fonts are missing on your system, if I'm not mistaken - Cambria Math or Asana Math is required for displaying of this formulas

Install them by [this instruction](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx)

**Comment by Akrobs** [comment]
I'm copy all font from my PC, to DocumentServer system in /usr/local/fonts/, and Cambria Math, Asana Math font, then run **documentserver-generate-allfonts.sh** command.
All font are available in document Editor, but Equation same problem.

I,m trying open this doument in MS office, and all Equation fine.

**Comment by ShockwaveNN** [comment]
Everything seems right, I'll recheck this on clean centos 7 installation
But as sidenote (I don't think this is a source of your problem) - Centos 8 is EOLed and this system is totally unsupported so maybe something also broke on their side with fonts...

**Comment by Akrobs** [comment]
> Everything seems right, I'll recheck this on clean centos 7 installation But as sidenote (I don't think this is a source of your problem) - Centos 8 is EOLed and this system is totally unsupported so maybe something also broke on their side with fonts...

Ok, thanks! Can you give name of fonts? I'm trying add manualy.

**Comment by ShockwaveNN** [comment]
I thin it should be Asana math, but I'll recheck them after weekend

**Comment by ShockwaveNN** [comment]
I've rechecked again on clear Centos7 installation (DigitalOcean server image) and everything seems fine

And yes, I think font for those equation should be Cambria Math

Could you check that this problem is exists for you on Centos7 server?

**Comment by Akrobs** [comment]
> And yes, I think font for those equation should be Cambria Math

Yes, i'm copy font cambria.ttc from my PC to documentserver, then all Equation looks good.
Thanks!
