### ISSUE TITLE
mouse cursor should disappear in presentation mode after some seconds

### ISSUE THREAD

**Issue by shu0406** [ONLYOFFICE/DocumentServer#1615]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
mouse is visible while holding a presentation 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
mouse should disappear after some seconds
**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
6.4.2 and desktop 7.0.0
**Operating System:**
win 10
**Browser version:**
firefox 96

**Comment by Wo1fgang** [comment]
Hello @shu0406 

Sorry for long wait and thank you for this enhancement

Issue #55705 was created in our private issue tracker

**Comment by Wo1fgang** [comment]
Hello @shu0406 

Your enhancement was implemented in this [commit](https://github.com/ONLYOFFICE/sdkjs/commit/4dd9624657622450abcddaad574af582ffa06ca4) аnd will be released as version 7.1 if nothing will change in our release process

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
