### ISSUE TITLE
wrong symbols in pptx created in ms powerpoint

### ISSUE THREAD

**Issue by shu0406** [ONLYOFFICE/DocumentServer#1616]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
wrong symbols get shown in oo
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
6.4.2 and desktop 7.0.0
**Operating System:**
win 10
**Browser version:**
firefox 96

![Zwischenablage01](https://user-images.githubusercontent.com/76654412/151515754-97d705e7-0745-435b-9236-a839fd993ad9.jpg)

**Comment by ShockwaveNN** [comment]
Hi, could you attach this file?

But this may be because those font are missing on your installation of DocumentServer, you may need to install it manually

**Comment by shu0406** [comment]
Yes! I think your are right, opened in my onlyoffice.eu cloud it works. Could you send me the instructions to install (that) fonts?

**Comment by ShockwaveNN** [comment]
> I guess we have to do that:
> https://helpcenter.onlyoffice.com/de/installation/docs-community-install-fonts-linux.aspx

Yes you are, this is correct instruction

> Do you know where to get that ms fonts package?

It depends of which font is used, but some fonts are not allow any distribution, so I'll break the law by sharing links, so try to google it yourself )

**Comment by shu0406** [comment]
I see the symbols work with OO7.0 on onlyoffice.eu and with desktopeditor7.0. Does that mean the fonts are included in v7.0 or do we have to add them manually anyway?

**Comment by ShockwaveNN** [comment]
I think we do not have any additional fonts in v7.0.0

On onlyoffice.eu you see them - because in cloud version we allow to use some additional fonts by license, but cannot install them wich user DocumentServer installation

And on DesktopEditors use some fonts installed on your system, so they also not provided by our installation

**Comment by shu0406** [comment]
Thanks for the information!

**Comment by ShockwaveNN** [comment]
I'll close that issue but feel free to ask any question and I'll reopen if your localize your problem and that it's not symbols problem
