### ISSUE TITLE
Bug pdf conversion API rendering of a pptx

### ISSUE THREAD

**Issue by avanhove** [ONLYOFFICE/DocumentServer#1618]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
When i'm using the PDF converter API, i have render problems on my pptx file(see attachments)
![image](https://user-images.githubusercontent.com/61686963/151570964-ef3c8f49-b00b-429d-a26e-b8924c3fa1ec.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I will give u my file and can you test to convert the document into PDF using API

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/61686963/151571078-acb44d9c-f032-4e64-81e8-628e7a7e3e7a.png)

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
7.0.0

**Operating System:**
Microsoft Windows 10

**Browser version:**
Google Chrome 91

[PB Preview OO_INSAL_GoFAST_Tuto_Actions_enmasse.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/7959685/PB.Preview.OO_INSAL_GoFAST_Tuto_Actions_enmasse.pptx)

**Comment by ShockwaveNN** [comment]
Hi, could you clarify parameters you've used?

I've converted your file via:
```
curl --location --request POST 'http://localhost/ConvertService.ashx' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"async": false,
	"filetype": "pptx",
	"key": "50ae2df7-f06d-4205-9a68-ea695cfbae1d",
	"outputtype": "pdf",
	"title": "PB.Preview.OO_INSAL_GoFAST_Tuto_Actions_enmasse.pptx",
	"url": "https://github.com/ONLYOFFICE/DocumentServer/files/7959685/PB.Preview.OO_INSAL_GoFAST_Tuto_Actions_enmasse.pptx"
}'
```

And everything seems fine (I've opened PDF in it Google Chrome and ONLYOFFICE DocumentServer):
![image](https://user-images.githubusercontent.com/668524/151575205-fd22fe2e-9a8f-49c1-a98c-213af796553c.png)

**Comment by cpot** [comment]
@ShockwaveNN we are checking and give you update next week.

**Comment by ShockwaveNN** [comment]
> incompatbile with PDF.js (LO and MS-Office working)


It may be, I think we got reports of problems with pdf.js earlier, but if  file is renders fine in Google Chrome, LibreOffice and Word - this should be reported as bug in pdf.js library

**Comment by cpot** [comment]
Not exactly, PDF exported from LibreOffice or MS-Powerpoint is correctly displayed by PDF.js, not PDF export from Onlyoffice

**Comment by ShockwaveNN** [comment]
@cpot Sorry, correct me if I got you wrong, but I've meant another thing

1. Export pdf from ONLYOFFICE DocumentServer
2. Open in in GoogleChrome or for example Adobe Acrobat or Okular (my default viewer on KDE) and pdf.js

And if this pdf is OK in Google Chrome, and Okular and not OK in pdf.js - I think it's the problem in pdf.js

I've rechecked resulting pdf in Mozilla firefox (as I understand it uses pdf.js by default) and I confirm that it renders incorrectly, but google chrome and Okular render ok

**Comment by avanhove** [comment]
Hi ! 
This is the render with firefox : 

![image](https://user-images.githubusercontent.com/61686963/151791587-549b43e1-afe3-4b09-9e01-4ae7c553050b.png)

I confirm, so i think it's a pdf.js problem we will see and come back after we fix this bug.

Thanks,

**Comment by cpot** [comment]
But still, LO and Powerpoint export a correct PDF of this file in PDF.js ....

**Comment by ShockwaveNN** [comment]
Maybe because they use completely another engine or some specific operations

I thin the best way right now to handle this situation - file an issue to pdf.js and wait for their analyze of this problem

**Comment by nicozhang** [comment]
The same problem. The pdf.js team seems not accepted this problem.
<img width="942" alt="image" src="https://user-images.githubusercontent.com/1912794/231736422-41b02af6-92f7-45ca-b1bd-dc26157b4ca7.png">
