### ISSUE TITLE
'Copy Style' button doesn't work between sheets

### ISSUE THREAD

**Issue by cuibonobo** [ONLYOFFICE/DocumentServer#162]
Bug report.

Copying the style of a cell (with the 'Copy Style' button) does not work if the cell being copied to is on a different sheet; no styles are copied.

To reproduce:
- Create a new spreadsheet with 2 worksheets inside of it (Sheet1 and Sheet2)
- Change the background of a cell on Sheet1, select the cell, then click the 'Copy Style' button. Observe that the cursor changes to 'Copy Style' mode.
- Switch to Sheet2. You will see that the cursor is still in 'Copy Style' mode, but selecting a cell to apply the style either has no effect, or it fills the cell with black

Since the cursor is still in 'Copy Style' mode when I switch sheets, I would expect that I am able to copy a style from one sheet to another.

DocumentServer version 4.4.2.20. macOS 10.10 and 10.11, on multiple browsers. I am not aware if this worked on previous versions of DocumentServer.

**Comment by Rita-Bubnova** [comment]
This bug fixed.
I checked in version 6.1- "Copy style" works.

**Comment by ShockwaveNN** [comment]
Sorry we didn't note about this bug before
I'll close this issue, but if any problem related to this issue or some new issue occur - please comment
