### ISSUE TITLE
RTL In the Editor

### ISSUE THREAD

**Issue by ikfir** [ONLYOFFICE/DocumentServer#1621]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Only LTR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can type in hebrew

**What is the expected behavior?**
To be able to type in hebrew

**Did this work in previous versions of DocumentServer?**
no

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19
