### ISSUE TITLE
Impossible to add comment to a document using a smartphone

### ISSUE THREAD

**Issue by ben3474** [ONLYOFFICE/DocumentServer#1622]
Not sure I am in the right project but here's something weird. It seems like I missed something but can't manage to add any comment via my smartphone.

Here are the steps to reproduce:
1. Open a document
2. select a word
3. click on + at the top (screenshot 1)
4. click on "Comment" (screenshot 2)
5. Type in a comment like "Test"
6. Hit the check button (screenshot 3)
The comment is not saved.

Thanks

![screenshot_1](https://user-images.githubusercontent.com/73280761/152701135-dd31ba35-079b-4f2c-9523-47a64bbdcf96.png)
![screenshot_2](https://user-images.githubusercontent.com/73280761/152701139-333f9676-2007-479a-8a07-4eef562dbd78.png)
![screenshot_3](https://user-images.githubusercontent.com/73280761/152701138-def68ec0-6756-45ea-9157-6e09e3cda8b6.png)

**Comment by mariabondareva** [comment]
@ben3474 , hi! 
Have you turned on the display of comments in the application settings?
![photo1644241252 (1)](https://user-images.githubusercontent.com/74345194/152800214-6de74195-9c21-4dbd-95c6-aa1f765685b4.jpeg)

**Comment by ben3474** [comment]
> @ben3474 , hi! Have you turned on the display of comments in the application settings? ![photo1644241252 (1)](https://user-images.githubusercontent.com/74345194/152800214-6de74195-9c21-4dbd-95c6-aa1f765685b4.jpeg)

**Comment by ben3474** [comment]
Hi Maria,
Yes it is and also I am able to add comments from my personal computer. It is only from my smartphone that there is a problem.

**Comment by mariabondareva** [comment]
@ben3474, tell me please:
1) What application do you use on your smartphone? (and it's version)
2) Onlyoffice document server version
3) Android version

**Comment by ben3474** [comment]
1. 96.3.1 (Build #2015860755), 5e0953d24+
AC: 96.0.15, 0178a6fde9
GV: 96.0.3-20220126154723
AS: 86.2.2

2. Version 6.0.0 this is what I see on my smartphone on the about menu but not sure it is what you need. Btw I don't have access to the server itself. I would have to ask our supplier

3. Android 10 build 8901.3.A.0135.20211222


By the way you will note one of my colleague within the organisation has the same issue using a tablet.

To help reproducing the problem I have shared a document with you that is publically accessible and writable. https://nuage.paysrochoisentransition.org/s/3BjAaWD6m6xKkXp

**Comment by mariabondareva** [comment]
@ben3474, you need to update document server version to 7.0. The problem should be gone.

**Comment by ben3474** [comment]
Can you share a document running on that server version to make sure it solves the problem?
Thank you

**Comment by mariabondareva** [comment]
> Can you share a document running on that server version to make sure it solves the problem? Thank you

[https://nct.onlyoffice.com/sh/X2G](url)

**Comment by ben3474** [comment]
Yes, works. Thanks! The problem is identified.
