### ISSUE TITLE
Please allow inserting equation using linear format

### ISSUE THREAD

**Issue by Cris70** [ONLYOFFICE/DocumentServer#1623]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When you work a lot with equations, inserting them using point-and-click is not efficient.
It would be much more efficient if equations could be inserted with a linear format, like LibreOffice does.
e.g. writing "hat ABC simeq hat {A'B'C'}" is much quicker and efficient that having to click around in the equation menu
You can use a linear format of your invention, use the one supported by LibreOffice, use LaTeX... you say it. The important thing is to be able to insert equations using a linear format.

**Comment by Cris70** [comment]
Hi, any news on this request?

**Comment by TatianaKirillova** [comment]
@Cris70 Yes, you can now use formulas in Latex mode and write them in linear form, converting them to a professional look if necessary!

**Comment by Cris70** [comment]
Thank you Tatiana, this is great news! 
Which is the first version of OnlyOffice desktop with the functionality?

**Comment by TatianaKirillova** [comment]
@Cris70 I am very happy to please you! version 8.0.1 already contains these features. There’s also a convenient panel for inserting and setting up formula modes :)
