### ISSUE TITLE
Table of figures doesn't work properly

### ISSUE THREAD

**Issue by Willena** [ONLYOFFICE/DocumentServer#1627]
**Do you want to request a *feature* or report a *bug*?**

Bug; Might be related to #1608 

**What is the current behavior?**

- The table of figure is inserted twice. 
- The table of figure is not updatable
- Caption numbering is wrong (#1608)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a new document 
2. Add an image or chart
3. Insert a Caption (notice the wrong numbering)
4. Insert a table of figure (notice the double insertion and the fact that figures are not listed)
5. Table cannot be updated

<img src="https://user-images.githubusercontent.com/1786065/153076406-86766d44-53b0-4aeb-9846-f37d26ce1840.png" width="500px"/>

**What is the expected behavior?**

- Table of figure should contain a list of figures and their captions. 
- Numbering should increment for each new figure. 
- The table should be updatable to list recently added figures.

**Did this work in previous versions of DocumentServer?**

I don't know. 

**DocumentServer version:**

7.0.0

**Operating System:**

Ubuntu

**Browser version:**

Firefox 96.0.3 (64bit)

**Comment by matveevms** [comment]
@Willena, Hello.
Indeed, the error is related to [#1608](https://github.com/ONLYOFFICE/DocumentServer/issues/1608).
This problem already fixed it in the next version:
https://github.com/ONLYOFFICE/sdkjs/commit/96533178e996929081775ad3e52c3f743ac210ba

**Comment by Willena** [comment]
Do you have any ETA for the next version ?

**Comment by ShockwaveNN** [comment]
@Willena We really hope in will be within a month, but we got not exact date

**Comment by ShockwaveNN** [comment]
DocumentServer v7.0.1 is released
This issue should be fixed

Feel free to comment or reopen it otherwise
