### ISSUE TITLE
Does Community Edition support Mobile web editors?

### ISSUE THREAD

**Issue by t-anh** [ONLYOFFICE/DocumentServer#1628]
At readme,  "Mobile web editors: - (Community Edition)" is described.
But after downloading docker and installing it, I can use the option "Open in editor for mobile devices" to edit files in mobile.
https://www.onlyoffice.com/download-docs.aspx?from=downloadintegrationmenu#docs-community
Does it mean Community Edition supports Mobile web editors?
And Mobile web editors are same as Enterprise Edition?

**Comment by ShockwaveNN** [comment]
> Does it mean Community Edition supports Mobile web editors?

No, it shouldn't. We got some changes in the previous version, but the current stable version of DocumentServer (7.0.0) should not support it. Maybe you've downloaded some older version.

You should see window like this:
 
![image](https://user-images.githubusercontent.com/668524/153158263-e77227cc-6c6d-4ac6-b655-03b9066645d2.png)


> And Mobile web editors are same as Enterprise Edition?

Yes they are, it's same engine, we just limited ability to edit in free version

You can read about that decision in more details [here](https://github.com/ONLYOFFICE/DocumentServer/issues/805#issuecomment-601772523)

**Comment by t-anh** [comment]
@ShockwaveNN 
Thank you for your quick response. I installed the latest version and it displayed the warning.
