### ISSUE TITLE
Paste with Ctrl + Shift + V without formatting

### ISSUE THREAD

**Issue by z0k8** [ONLYOFFICE/DocumentServer#1633]
Often i want to copy and paste text without formattig with the shortcut "Ctrl + Shift + V", like in M$ word or google docs, but this does not work with Only Office. Would be nice to get this function here to in near future.

Only workarround i know, is to use notepad to remove the old formatting and paste again from there.

**Comment by veter069** [comment]
> There is such functionality.
> 
> We have the special paste button for this purpose ![image](https://user-images.githubusercontent.com/17902914/78368334-243d5980-75cc-11ea-843d-8f2b3f68db93.png)
> 
> Ctrl + Shift + V has a different meaning, it paste text formatting, that was previously copied.

It doesn't work in "Find and Replace" window.

**Comment by ShockwaveNN** [comment]
@veter069 I think it's better to create new issue
