### ISSUE TITLE
Change level is not available (grey)

### ISSUE THREAD

**Issue by biva** [ONLYOFFICE/DocumentServer#1636]
Hello, 

In a document that I'm editing:
- I have a multilevel numbered list (1. then 1.1 then 1.1.1 )
- The level of 1.1.1 is 2, while it should be 3 (see the pink circle below)
- If I try to change it, with _Paragraph Advanced Settings_, I can't change the outline level (it is greyed: see the red circle below)
![image](https://user-images.githubusercontent.com/9964305/153846565-a612ce65-1138-47dd-ab21-3916cb9f5084.png)
- Is it a bug, or normal behaviour? How can I change it?
- I attach the document so that you can see it
[Test Doc List Level.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8059951/Test.Doc.List.Level.docx)

Thank you!

**DocumentServer version:**
7.0

**Operating System:**
Debian Stretch

**Browser version:**
Firefox 97.0 on Windows 10

**Comment by matveevms** [comment]
@biva, Hello.
If I understand you correctly, in your case you need to apply the "Heading 3" style to the third list item. The styles "Heading 1" and "Heading 2" are applied to the two previous elements, respectively. While the third element also has the "Heading 2" style applied.

**Comment by biva** [comment]
Hum, why did you close this @ShockwaveNN ? I might have misunderstood but the issue is not solved for me

**Comment by biva** [comment]
The problem is not about heading, the problem is about the level

**Comment by ShockwaveNN** [comment]
Sorry, for me issue seems resolved, reopened it again

**Comment by matveevms** [comment]
Here is your example which I made for you in our editor. Was that your question?
![Screenshot_113](https://user-images.githubusercontent.com/49515977/153881711-76776c19-a429-442b-ab6f-e995d061ab53.png)
[Test_Doc_Level.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8061468/Test_Doc_Level.docx)

**Comment by matveevms** [comment]
It is worth noting that the style of the third level was created on the basis of "Heading 3", which I wrote about above.

**Comment by biva** [comment]
Hi, sorry, I wasn't clear enough myself. This worked, thank you very much. I was surprised to not be able to change it in the settings, but this workaround works.

Thank you again!
