### ISSUE TITLE
docx -> odt export missing equations

### ISSUE THREAD

**Issue by xyont** [ONLYOFFICE/DocumentServer#1637]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.0.0.127

### Expected Behavior

document contains equation need to be shown as original, even some format is missing (e.g aligned)

### Actual Behavior

equation is lost when document is exported to ODT format, try reopening with OnlyOffice and OpenOffice still the same.

### Additional information

![2022-02-14 19_01_42-ExportODT_errorDocumentContainsEquation](https://user-images.githubusercontent.com/72367311/153860835-5eaa5b5c-bd78-4d6c-b858-58169b8a4734.jpg)

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
