### ISSUE TITLE
Several problems in xlsx file render

### ISSUE THREAD

**Issue by Akrobs** [ONLYOFFICE/DocumentServer#1638]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Please, see attachments.

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
7.0.0

**Operating System:**
CentOS 8.5

**Browser version:**
All

MS Office 2013
![Kredit_MS](https://user-images.githubusercontent.com/57731196/153890658-13e5ff1e-44a3-4bc0-a155-432082976734.jpg)

OO
![Kredit_OO](https://user-images.githubusercontent.com/57731196/153890666-24fcbd9b-f392-45d6-b9a0-842998470534.jpg)

[TF02802352.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/8061840/TF02802352.xlsx)

**Comment by ShockwaveNN** [comment]
HI, could you create separate issue for second file (and do not forget to attach it)
It's hard to track separate problems in single issues and judging by screenshot problems are separate

**Comment by Akrobs** [comment]
No problem.

**Comment by alinasafonova** [comment]
Problem with displaying "x000a" in headers is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/5870b4502492a955a63ddd600641bb8fd7382d0d
It will be released as v7.3.0

**Comment by Akrobs** [comment]
> Problem with displaying "x000a" in headers is fixed in [ONLYOFFICE/sdkjs@5870b45](https://github.com/ONLYOFFICE/sdkjs/commit/5870b4502492a955a63ddd600641bb8fd7382d0d) It will be released as v7.3.0

Thanks!!!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
