### ISSUE TITLE
Response url from conversion service having private ip

### ISSUE THREAD

**Issue by ghartaan** [ONLYOFFICE/DocumentServer#164]
I am running document server in a docker container on a linux host machine. I am using conversion service of document server to generate thumbnails for my files. I send a post request to document server and gets back the response in xml. The response is in the following form:

<?xml version="1.0" encoding="utf-8"?>
<FileResult>
    <FileUrl>http://172.17.0.2/cache/files/conv_pdf_1280_720_pdf/output.pdf/output.pdf?md5=cEUYq6BxASIG6b3qzxhh0A==&amp;expires=1507288279&amp;disposition=attachment&amp;ooname=output.pdf</FileUrl>
    <Percent>100</Percent>
    <EndConvert>True</EndConvert>
</FileResult>

The generated file url 
[url]http://172.17.0.2/cache/files/conv_pdf_1280_720_pdf/output.pdf[/url]
has the private ip [172.17.0.2] of container so not accessible from outside world.
Is there any way to configure document server so that a client on a remote machine can make a request and can access the generated output file using the response url?

Thanks in advance.

**Comment by agolybev** [comment]
Hi @ghartaan,
Document server uses a host name from a http request to generate output url in a http response. 
So, the local ip or the local host name uses when you make request inside local network. 
There is the same result if you use proxy server before document server. See [this](https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx) guide to get the document server work on correctly.

**Comment by agolybev** [comment]
Hi @ghartaan 
Your service should download converted file and store it in own storage, then generate link to it.

**Comment by agolybev** [comment]
Try changing `Host` header in request to document server. Also you can add `X-Forwarded-Proto` and `X-Forwarded-Host` HTTP headers.  'X-Forwarded-Proto' header is a de-facto standard header for identifying the protocol (HTTP or HTTPS) that a client used to connect to the proxy or load balancer. 'X-Forwarded-Host' is a standard header for identifying the original host requested by the client in the Host HTTP request header. 
So, the documentserver will use those value to assemble output url.

**Comment by ghartaan** [comment]
Thanks @agolybev .
