### ISSUE TITLE
No coding method for Chinese GBK/GB2312

### ISSUE THREAD

**Issue by wxf26054** [ONLYOFFICE/DocumentServer#1645]
It seems like there has no coding method selection for Chinese GBK/GB2312. Will support it in he future?
![image](https://user-images.githubusercontent.com/22016320/154876784-7686cb41-2e0d-4769-8214-8624027f3e64.png)

**Comment by ShockwaveNN** [comment]
Hi, could you attach file which uses this encoding?

**Comment by wxf26054** [comment]
[userImport.csv](https://github.com/ONLYOFFICE/DocumentServer/files/8107936/userImport.csv)
This is an example file.

**Comment by wxf26054** [comment]
Also it has no ANSI coding method

**Comment by ShockwaveNN** [comment]
Could you clarify that's the problem with this file

I've selected Chinese encoding at import and it seems fine for me:
![Screenshot_20220221_125155](https://user-images.githubusercontent.com/668524/154930894-06c52ad0-7429-41f7-945b-d84b640fddb4.png)
![Screenshot_20220221_125214](https://user-images.githubusercontent.com/668524/154930904-79f0850e-37aa-401a-aca7-da9084dd0431.png)

**Comment by ShockwaveNN** [comment]
I've installed clean DocumentServer v7.0.0 via Docker image
![image](https://user-images.githubusercontent.com/668524/154955012-f03f4ad0-6328-4483-bdcc-4b6a155e7013.png)

And I got this option

So please clarify your installation method and versions

**Comment by wxf26054** [comment]
Docker version 
![image](https://user-images.githubusercontent.com/22016320/155050374-f4bf859f-0818-4bae-9eed-a1213c1acc7e.png)

**Comment by wxf26054** [comment]
Document Server Version 6.2.0

**Comment by ShockwaveNN** [comment]
This is rather old, try to update to latest stable version and re-check

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
