### ISSUE TITLE
windows 版本onlyoffice document server无法插入图片

### ISSUE THREAD

**Issue by yww0926** [ONLYOFFICE/DocumentServer#1647]
![Uploading am8_20220222123749473.jpg…]()
windows版本的onlyoffice无法在Excel内上传图片，版本5.4，6.0 , 6.4均试过，都无法插入。操作系统版本windows7，windows server 2016，浏览器版本 IE11，Chrome98.0，均存在以上问题。其他插件版本erlang19.1和20.3，rabbitmq-server 3.5.4和3.7.7，redis3.2和5.0，postgresql-9.6.0和12.9，各种版本均试过，都有此问题。
但是，docker版本的onlyoffice document server一切正常，能插入图片

**Comment by ShockwaveNN** [comment]
Plese, use only english in describing issues, we do not understand your language at all

And screenshot link is broken

**Comment by yww0926** [comment]
> 
Roger, I'll restart
