### ISSUE TITLE
No entries for a list of figures could be found.

### ISSUE THREAD

**Issue by marrobHD** [ONLYOFFICE/DocumentServer#1649]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.0.0.127

### Expected Behavior

It should create a list of figures as documented in the [docs](https://helpcenter.onlyoffice.com/de/onlyoffice-editors/onlyoffice-document-editor/UsageInstructions/AddCaption.aspx).

### Actual Behavior

It shows message:
```
No entries for a list of figures could be found.
No entries for a list of figures could be found.
```

### Reproduction Steps

https://helpcenter.onlyoffice.com/en/onlyoffice-editors/onlyoffice-document-editor/UsageInstructions/AddCaption.aspx

### Additional information

![grafik](https://user-images.githubusercontent.com/29308361/155032502-1d6365dc-b6bb-4616-a442-68423c78f114.png)

**Comment by marrobHD** [comment]
Can I install this patch somehow manually? I really need it now

**Comment by ShockwaveNN** [comment]
https://s3.eu-west-1.amazonaws.com/repo-doc-onlyoffice-com/onlyoffice/testing/ubuntu/onlyoffice-desktopeditors_7.0.1-37_amd64.deb

You can use this one
