### ISSUE TITLE
Cannot Create or Edit Documents on an OwnCloud SMB/CIFS Share.

### ISSUE THREAD

**Issue by shieldsit** [ONLYOFFICE/DocumentServer#165]
**Do you want to request a *feature* or report a *bug*?**

Bug Report

**What is the current behavior?**

Documents in the default home storage of OwnCloud can be created and edited with OnlyOffice.  If you attempt to create or edit an OnlyOffice document in a mounted share in OwnCloud OnlyOffice produces a "Download failed." error.  It appears that the document is actually created, but it cannot be opened or edited.  Other types of files & folders can be created in this share so it doesn't appear to be a permissions issue. 

This is the error shown in the documentserver/converter/out.log

[ERROR] nodeJS - error downloadFile:url=http://164.4.245.200/owncloud/index.php/apps/onlyoffice/download?doc=b0pSUFRYbERQQXRlaCtLZlJuL2JWQUh4NXh1SlhsZitZWHM4aFRCQmgxZz0/eyJmaWxlSWQiOjgyLCJvd25lcklkIjoiMUFCNDc0OTAtNjE0NS00NzYzLTgzNTUtRURBNEY2MjgwOEIyIiwiYWN0aW9uIjoiZG93bmxvYWQifQ%3D%3D;attempt=2;code:undefined;connect:undefined;(id=821470152013)
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:243:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Mount a SMB/CIFS share in Owncloud and make sure the correct user has the needed permissions.  Click the + sign to create a new document, name the document, hit enter.  OnlyOffice creates the document and attempts to open the editor, that is when the error occurs. 

**What is the expected behavior?**

The editor opening the existing document for editing or a blank document for editing when you have created a new document.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

DocumentServer is running on Debian 9.  I can't seem to find a place that tells me the version number, but I just installed it today using this repo:  http://download.onlyoffice.com/repo/debian squeeze main

**Comment by shieldsit** [comment]
This has been reported to the NextCloud github issues page, but I don't think it's a NextCloud/OwnCloud issue, so I wanted to report it here.  This is exactly what I'm seeing as well.  https://github.com/nextcloud/server/issues/4194

**Comment by trofim24** [comment]
Please duplicate this issue in https://github.com/ONLYOFFICE/onlyoffice-owncloud
cc @LinneyS
