### ISSUE TITLE
Protected document can be opened without password request.

### ISSUE THREAD

**Issue by Akrobs** [ONLYOFFICE/DocumentServer#1655]
**Do you want to request a *feature* or report a *bug*?**
Maybe bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

After set protect with password, from main menu-file-protect-protect with password on v7.0.0, document can be opened with MS Office or OO v6.4.2 without password request. After open same document on v6.4.2 and set protect with password, file can be open in v7.0.0 without password request.

**Did this work in previous versions of DocumentServer?**
Not sure
**DocumentServer version:**
7.0.1 6.4.2

**Operating System:**
CentOs 8.5

**Browser version:**
Firefox last

**Comment by alinasafonova** [comment]
Hello, @Akrobs

Could you please attach a document before and after protecting with password?

**Comment by Akrobs** [comment]
> Hello, @Akrobs
> 
> Could you please attach a document before and after protecting with password?

Hi, Alina. Shure 
[sample-clean.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8141490/sample-clean.docx)
[sample-passw.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8141492/sample-passw.docx)

From OO v7.0.0

**Comment by Akrobs** [comment]
Password not saved, after document is download. I'm upload protected file with password the opened and no have password request.

**Comment by alinasafonova** [comment]
@Akrobs
Please make video of screen with following steps:
1. Set password
2. Open again menu File and Protect tab in this menu
3. Download file

**Comment by Akrobs** [comment]
Now it's ok. I'm think broblem with browser caching. I'm reset cache, reboot OO server and files download with password protection.
