### ISSUE TITLE
numbering wrong display

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1656]
**DocumentServer version:**
7.0.1; 6.4.2

**Operating System:**
windows 11

**Browser version:**
chrome 98.0.4758

wrong display:
![image](https://user-images.githubusercontent.com/29354679/155687183-bfc819f6-9cdb-4384-9222-1a2647b45d6f.png)

origin file:

[origin.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8139922/origin.docx)

**Comment by ShockwaveNN** [comment]
Hi, we not good at chinese at all but seems juding by this file - those fonts are part of `仿宋` font

I've tried to google it but only chinese pages are up and I have no idea if this font really exists

I think you should install it if it really a font by [this instriciton](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx)
