### ISSUE TITLE
Error opening files of any type

### ISSUE THREAD

**Issue by Mathias-devop** [ONLYOFFICE/DocumentServer#1658]
**Do you want to request a *feature* or report a *bug*?**
bug/problem

**What is the current behavior?**
Ofter opening the file on the Nextcloud shows the error message:
"The file cannot be accessed right now"
![error](https://user-images.githubusercontent.com/79152255/155710861-1bde57d3-4c62-46e6-b74a-999cdec16e12.PNG)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Installed the latest version of the Document Server based on the manual: https://helpcenter.onlyoffice.com/installation/docs-community-install-centos.aspx

**What is the expected behavior?**
Opening the file for editing

**Did this work in previous versions of DocumentServer?**
Previously we used nextcloud community edition app

**DocumentServer version:**
7.0.1

**Operating System:**
CentOS 7

**Browser version:**
Chrome Version 98.0.4758.102

**More Information**
 Also I tried to enbale the example page on the document server but he same error message occurs when I opened the created file. I've been looking the log files, but there are no records about the error. 
The logs from time I've been trying to open files for editing and also the json setting are in the attachment.
[logs.tar.gz](https://github.com/ONLYOFFICE/DocumentServer/files/8140896/logs.tar.gz)
[jsonConfig.zip](https://github.com/ONLYOFFICE/DocumentServer/files/8140903/jsonConfig.zip)

**Comment by ShockwaveNN** [comment]
Hi

>Also I tried to enbale the example page on the document server but he same error message occurs when I opened the created file. I've been looking the log files, but there are no records about the error.

Let's localize your problem via `/example`

Judging by your logs - seems that you've used DocumentServer for quite a long time and as far as unerstand - you've updated old installation, am I right? Because I see some logs file for version rather old (like `spellchecker` logs)

Could you try to setup a new installation and see if problem occcurs?

**Comment by Mathias-devop** [comment]
Yes, I've been using it for test back at the 2020 I think, but since the nextcloud released their community version I switch to that

OK, I will prepare new installation and try it. I will let you knw if the problem is still there when all will be set up.

**Comment by ShockwaveNN** [comment]
Yeah, sure I'll leave this issue opened

But I'm almost sure that problems are either:
1. In conflict with some of our old installations, maybe two different versions are installed same time
2. Conflict with `nextcloud community documentserver` - this product a different with ours too much so you need to choose only one

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
