### ISSUE TITLE
Installing documentserver in ubuntu 16 causes error

### ISSUE THREAD

**Issue by kalaikurtis007** [ONLYOFFICE/DocumentServer#166]
can anyone help me to fix this error 
```
sysadmin@onlyoffice:~$ sudo apt-get --reinstall install onlyoffice-documentserver
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
Need to get 0 B/142 MB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package onlyoffice-documentserver.
(Reading database ... 240913 files and directories currently installed.)
Preparing to unpack .../onlyoffice-documentserver_4.4.3-7_amd64.deb ...
Unpacking onlyoffice-documentserver (4.4.3-7) over (4.4.3-7) ...
dpkg: warning: subprocess old post-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
dpkg: ... it looks like that went OK
Processing triggers for fontconfig (2.11.94-0ubuntu1.1) ...
Setting up onlyoffice-documentserver (4.4.3-7) ...
Generating AllFonts.js, please wait...Done
dpkg: error processing package onlyoffice-documentserver (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ShockwaveNN** [comment]
@kalaikurtis007  
Hi.
Cannot reproduce your problem on my Ubuntu 16 system.
You can try to reinstall `onlyoffice-documentserver` by those command (after backup all your user data)
```
sudo apt purge onlyoffice-documentserver
sudo rm -rf /var/www/onlyoffice/documentserver
sudo apt install onlyoffice-documentserver
```

**Comment by agolybev** [comment]
Hi, @kalaikurtis007!
Could you check status for `nginx` and `supervisor` services?
They restart at the end of postinstall script. Try restarting it manualy by these command:
```
sudo service supervisor restart
sudo service nginx restart
```

**Comment by kalaikurtis007** [comment]
Hi, @ShockwaveNN & @agolybev   
thanks for your quick response. the problem is due to nginx 

 followed below steps as per @ShockwaveNN 

`sudo apt purge onlyoffice-documentserver`
`sudo rm -rf /var/www/onlyoffice/documentserver`
`sudo apt install onlyoffice-documentserver`

Setting up libnginx-mod-stream (1.10.3-1+deb9u1) ...
Setting up nginx-extras (1.10.3-1+deb9u1) ...
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-09-13 16:37:59 IST; 20ms ago
     Docs: man:nginx(8)
  `Process: 16035 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)`

Sep 13 16:37:59 onlyoffice systemd[1]: Starting A high performance web server and a reverse proxy server...
Sep 13 16:37:59 onlyoffice nginx[16035]: nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
Sep 13 16:37:59 onlyoffice nginx[16035]: nginx: configuration file /etc/nginx/nginx.conf test failed
Sep 13 16:37:59 onlyoffice systemd[1]: nginx.service: Control process exited, code=exited status=1
Sep 13 16:37:59 onlyoffice systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Sep 13 16:37:59 onlyoffice systemd[1]: nginx.service: Unit entered failed state.
Sep 13 16:37:59 onlyoffice systemd[1]: nginx.service: Failed with result 'exit-code'.
dpkg: error processing package nginx-extras (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up python-pkg-resources (33.1.1-1) ...
Setting up python-meld3 (1.0.2-2) ...
Setting up supervisor (3.3.1-1) ...
Setting up pwgen (2.07-1.1+b1) ...
dpkg: error processing package onlyoffice-documentserver (--configure):
 package onlyoffice-documentserver is not ready for configuration
 cannot configure (current status 'half-installed')
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Errors were encountered while processing:
 nginx-extras
 onlyoffice-documentserver

**Comment by ShockwaveNN** [comment]
@kalaikurtis007 
Seems there is some problem with `/etc/nginx/nginx.conf`
It is default nginx config and `onlyoffice` didn't modify it, so it is possible it broken for some reason.
Try to fix it by reinstalling `nginx` and `nginx-extras` and install `onlyoffice-documentserver` after that.

**Comment by kalaikurtis007** [comment]
Hi! @ShockwaveNN 
Thank you for a quick response yah! its due to nginx  i fixed it now its works fine

**Comment by ShockwaveNN** [comment]
@kalaikurtis007 good to hear!
