### ISSUE TITLE
Balance SBCS characters and DBCS characters

### ISSUE THREAD

**Issue by joeyer** [ONLYOFFICE/DocumentServer#1661]
![image](https://user-images.githubusercontent.com/11498128/156112025-7c13dd46-a6bc-4e9f-8ded-4f018eaf9ab0.png)

versions
onlyoffice：7.0.0

problem：
The spacing of spaces and other symbol spacings will exist in different cases from the MS

**Comment by Rita-Bubnova** [comment]
Hello, @joeyer.
Could you attach the file with problem?

**Comment by joeyer** [comment]
file:
[HelloWord.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8159660/HelloWord.docx)

**Comment by joeyer** [comment]
@[Rita-Bubnova](https://github.com/Rita-Bubnova)

**Comment by Rita-Bubnova** [comment]
@joeyer, thank you for attach file.
We don't support the option "Balance SBCS characters and DBCS characters" in the document editor. 
I created issue 56288 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/8ad9c15237a55376d321d2da57265f328c867966) in the future major release.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/8ad9c15237a55376d321d2da57265f328c867966) in the future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
