### ISSUE TITLE
callCommand (func, isClose, isCalc), "isCalc=false" cause excel to save fail

### ISSUE THREAD

**Issue by sunshine001** [ONLYOFFICE/DocumentServer#1662]
If callCommand (func, false, false), "isCalc=false" it cause excel to save fail.

Please help me, thanks.

![image](https://user-images.githubusercontent.com/6621221/156132032-c66b579e-6f8f-4f5d-b4bf-078676031e32.png)

**Comment by sunshine001** [comment]
Onlyoffice runs on my own machine.
I looked for logs in _/var/log/onlyoffice/documentserver_, there's no useful log. 

When i set isCalc=true, it works normally, but set "isCalc=false", it save fail.
"isCalc=true" cause plugin.init trigger multiple times, i need isCalc=false.

Thanks @ShockwaveNN .

**Comment by ShockwaveNN** [comment]
Could you clarify product version and installation method

And I think I was wrong about DMS - I didn't read your question correctly, sorry, seems this may be just a bug in plugin code

But we need a product version still

**Comment by sunshine001** [comment]
Onlyoffice's verison: 7.0, I install it on centos, not docker mode.

**Comment by ShockwaveNN** [comment]
@askonev Please take a look at this issue

**Comment by sunshine001** [comment]
My plugin 's usage is listening cell changes to checking the content.
 
When exec callCommand(func, false, true),  cell always recalculate, so I set callCommand(func, false, false), but it cann't save correct.

Please help me, thanks.

**Comment by sunshine001** [comment]
@askonev Please take a look for my question, thanks.

**Comment by ShockwaveNN** [comment]
@sunshine001 Please stop spamming, we'll help as we got the free time. 
If you want priority support with specific time frame for answering questions - use support@onlyoffice.com if you got paying license

**Comment by askonev** [comment]
@sunshine001 HI! Thank you for your patience! This script turned out to be a bug, so I started a [Bug 56047](https://bugzilla.onlyoffice.com/show_bug.cgi?id=56047) on our private repository.

**Comment by askonev** [comment]
@sunshine001 bug fixed on version 7.2

https://github.com/ONLYOFFICE/sdkjs/commit/4484f451a27b1ce845b3610348a6a581d9712ce1

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
