### ISSUE TITLE
Can excel lock the cell's column?

### ISSUE THREAD

**Issue by sunshine001** [ONLYOFFICE/DocumentServer#1663]
Hello, I want to know whether excel can lock cell's column, so that it cann't be cutted or deleted for others.

![image](https://user-images.githubusercontent.com/6621221/156289315-44de6a25-256f-4823-8441-fd1087f54f06.png)

**Comment by alinasafonova** [comment]
Hello, @sunshine001
Have you seen this feature in any other editors?

**Comment by sunshine001** [comment]
I understand, thanks .

**Comment by alinasafonova** [comment]
@sunshine001
We have an ability to lock and unlock cells (you can find corresponding checkbox on the Protection tab of top toolbar). But this setting works only when sheet is protected which restricts some actions with cells and other objects on the sheet.

If you mean something else by locking columns, provide us an example of this feature in other editors and we'll see if we can implement it.

**Comment by sunshine001** [comment]
Thanks @alinasafonova, I'll look at it again. I'll provide your an example if I find this feature in other editor.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
