### ISSUE TITLE
Change Date Time Language

### ISSUE THREAD

**Issue by kabouter** [ONLYOFFICE/DocumentServer#1669]
I'm wondering how I can change the date time language to Dutch.
Default Onlyoffice selects English. 

My settings:
```

    "editorConfig": {
        "callbackUrl": "{{ $save }}",
        "lang": "nl-BE",
        "location": "be",
        "region": "nl-BE",
    },
```
Here the date is in English:

![afbeelding](https://user-images.githubusercontent.com/6320511/156849607-2b210bac-8364-4a43-94f8-68709d87f2b0.png)

PM notation for some reason:
![afbeelding](https://user-images.githubusercontent.com/6320511/156849656-8c62a671-6d50-4368-ac48-8897b09ba365.png)

**Comment by ShockwaveNN** [comment]
To be clear - you got trouble with date time in the Comment window?

Because if I got your right - the first screenshot is for inserting date and you should manually select format there

**Comment by kabouter** [comment]
To be honest I thought that setting the localisation in the config would change the time notation.
