### ISSUE TITLE
Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by w3cways** [ONLYOFFICE/DocumentServer#1671]
**Do you want to request a *feature* or report a *bug*? No

**What is the current behavior?** Uncaught Error: Bootstrap's JavaScript requires jQuery

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem..

**What is the expected behavior? It can work in electron

**Did this work in previous versions of DocumentServer?  No

**DocumentServer version:6.4.2-6

**Operating System:win64

**Browser version: Chrome/91.0.4472.164 Electron/13.6.6

It works fine in chrome, but when I use it in electron BrowserWindow, it prompt error in console. 
![image](https://user-images.githubusercontent.com/6859510/157206268-22851f55-a465-4a41-996c-aa483965e4ed.png)
Hope someone can help me solve this problem， thx

here is new BrowserWindow webPreferences options
webPreferences = {
    nodeIntegration: true,
    contextIsolation: false,
    nativeWindowOpen: true,
    preload: path.join(__dirname, 'preload.js'),
    enableRemoteModule: true,
    navigateOnDragDrop: false,
    webSecurity: false,
    nodeIntegrationInSubFrames: true,
    webviewTag: true,
}

**Comment by ShockwaveNN** [comment]
Hi, not sure that are you planning to do and don't think someone at our team has a really good experience in Electron (DesktopEditors are not using electron)
But first thing in Google show me [this](https://stackoverflow.com/questions/63191705/uncaught-error-bootstraps-javascript-requires-jquery-at-bootstrap-min-js6-in)

If this not help - I'm not sure how we can help you because I do not understand that end goal are you trying to achieve and if you have enough experience to achieve this goal

**Comment by w3cways** [comment]
> Hi, not sure that are you planning to do and don't think someone at our team has a really good experience in Electron (DesktopEditors are not using electron) But first thing in Google show me [this](https://stackoverflow.com/questions/63191705/uncaught-error-bootstraps-javascript-requires-jquery-at-bootstrap-min-js6-in)
> 
> If this not help - I'm not sure how we can help you because I do not understand that end goal are you trying to achieve and if you have enough experience to achieve this goal

Thank you for help.[This](https://stackoverflow.com/questions/63191705/uncaught-error-bootstraps-javascript-requires-jquery-at-bootstrap-min-js6-in) not work for me.

when I use onlyoffice in electron browserWindow, such as the pic below:
![image](https://user-images.githubusercontent.com/6859510/157354858-ba9ecfb1-870c-4852-b924-504d0a2d4495.png)

but it works fine with the same url in chrome, so I have no idea to deal with this issue

**Comment by ShockwaveNN** [comment]
I also have no idea what to do with this problem, have no idea if this is an issue on our side, on the electron side, or on your configuration

I'll leave this issue open until someone more experienced with dealing with such problem will help

**Comment by w3cways** [comment]
> I also have no idea what to do with this problem, have no idea if this is an issue on our side, on the electron side, or on your configuration
> 
> I'll leave this issue open until someone more experienced with dealing with such problem will help

thx

**Comment by w3cways** [comment]
I fixe it. I use electron webview tag, and addEventListener 'new-window' in webview, capture the window.open event in webview,, then create new browserWindow.

**Comment by ShockwaveNN** [comment]
@w3cways Thanks for explanation I hope this will help for someone else in this situation )
