### ISSUE TITLE
Cannot edit cells on protected sheet

### ISSUE THREAD

**Issue by smarquespt** [ONLYOFFICE/DocumentServer#1676]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

Latest

### Expected Behavior

Ability to work on current file

### Actual Behavior

I am unable to work on it because Onlyoffice (desktop and server) say file is protected

### Reproduction Steps

Open file, fill yellow fields

### Additional information

This document has VBA macros and this could be the issue. I've tried to open file in other editors and none of them have this issue.
[CONTTOCV11.xls](https://github.com/ONLYOFFICE/DesktopEditors/files/8191060/CONTTOCV11.xls)

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by alinasafonova** [comment]
@smarquespt
This problem is fixed in https://github.com/ONLYOFFICE/core/commit/c23a0ee4a8a61707e754dd756a055425d5b75f6c

It will be released as v7.1.0

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
