### ISSUE TITLE
Better text input in oform (enhancement/bug)

### ISSUE THREAD

**Issue by shu0406** [ONLYOFFICE/DocumentServer#1677]
Would be perfect if oform would support richtext like control fields. Now it is just plain text which get hard to read if it is longer than 10 lines without any format and bullets.

If I export as PDF it gets even worst, the input field stays small even if I write more than 4 words, I think that's a bug:
in PDF Xchange
![grafik](https://user-images.githubusercontent.com/76654412/157084642-257de93f-0b2e-4af3-b08e-80b7a1d9f1d5.png)
in Firefox
![grafik](https://user-images.githubusercontent.com/76654412/157084868-ee73bb71-e480-4c02-8ed9-8d87bc938228.png)

**Comment by TatianaKirillova** [comment]
Hello, [shu0406](https://github.com/shu0406)
Thanks for your request!
Text formatting can be configured during form creation.
To view pdf files containing form fields, it is better to use Adobe Acrobat

**Comment by shu0406** [comment]
I attached a PDF file, the problem exists in every of my pdf viewer (Xchange, PDFdrawboard, firefox, XODO PDF). The textfield stays that small even if I write much more text.

Sorry, I do not find the possibility to configure text formatting: 
[Testformular.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/8232580/Testformular.pdf)

![grafik](https://user-images.githubusercontent.com/76654412/157883864-a5dde92c-03a4-4a92-b54f-0a1b2c3fe464.png)

**Comment by TatianaKirillova** [comment]
In order for the form field in pdf editors to be larger, you must enable the "fixed size" property of the form field and adjust the desired size by dragging the mouse outside the border.

**Comment by shu0406** [comment]
Thanks, that worked. However I still cant find the option to activate formatting inside the textfield.

**Comment by TatianaKirillova** [comment]
great job :) Formatting inside form fields works the same as regular text formatting: go to the "Home" tab and change the font color, size, use a bullet, etc.

**Comment by shu0406** [comment]
I think that is a missunderstanding. I was talking about the person filling out the oform. There are no options to formatting the text, since there is no home tab and also the shortcuts like ctrl+b don't work: 
![grafik](https://user-images.githubusercontent.com/76654412/158863899-b92e322f-47e3-455c-af61-d82a33ae0d5a.png)

**Comment by TatianaKirillova** [comment]
Yes, text formatting in the form field is available only at the document editing stage (in docxf format).

**Comment by Chartman123** [comment]
I had the same problem and fixed it this way :) Regarding the formatting problem there is another one in dropdown fields: I didn't find any way to adjust the text color for this type of field. It always stays grey.
![grafik](https://user-images.githubusercontent.com/16020496/167176617-eb54349f-11e7-4b48-a8cd-d70e7a523a35.png)
I formatted the both fields in the exact same way in onlyoffice, however, the PDF output stays grey for the second (dropdown) field

**Comment by TatianaKirillova** [comment]
please, attach a document to better understand the problem

**Comment by Chartman123** [comment]
> please, attach a document to better understand the problem

Will do that as soon as I'm back home again. Thank you for your quick response :)

**Comment by Chartman123** [comment]
@TatianaKirillova Here you are :) I had to zip the docxf file because Github doesn't accept that file type.

[Antrag.zip](https://github.com/ONLYOFFICE/DocumentServer/files/8646096/Antrag.zip)

**Comment by TatianaKirillova** [comment]
Thank you, @[Chartman123](https://github.com/Chartman123)! This behavior is correct (grey font color) if the text is written in "placeholder". In your document "Abteilung wählen" will be grayed out, the rest of the options will be black. There may be problems when displaying in a PDF viewer, try opening the document in Adobe Acrobat Reader.

**Comment by Chartman123** [comment]
Yes, I understand that... But if I print the document (as PDF or on paper) the selected entry will also always be printed in grey and not in black. So I don't think it has to do with the PDF viewer...

**Comment by TatianaKirillova** [comment]
@Chartman123, I cannot reproduce your issue. Can you tell me what OS you have?

**Comment by TatianaKirillova** [comment]
@Chartman123, Try to repeat your problem on the new version 7.1

**Comment by TatianaKirillova** [comment]
@Chartman123 What program are you using to open the file? In Adobe Acrobat Reader or Foxit Reader?

**Comment by TatianaKirillova** [comment]
@Chartman123， Please create a new issue about this. I will write a proposal to solve it.

**Comment by Chartman123** [comment]
> Please create a new issue about this. I will write a proposal to solve it.

@TatianaKirillova I tested it again with the latest release and couldn't reproduce my issue. If I see again, I'll create a new issue 👍🏻

**Comment by shu0406** [comment]
I still got some problems using oform in v7.3.3:

As you can see fixed fields are quite useless when typing more lines in oform (right) no matter which setting I use. 
Typing more lines is possible in infield field however as soon as I save it to pdf they disappear and get one looooooong line (pdf left).
Also the date input (second field) disappears in pdf.


![grafik](https://github.com/ONLYOFFICE/DocumentServer/assets/76654412/9434c58d-8723-4d9e-bdac-6e15f6eeddd0)

**Comment by TatianaKirillova** [comment]
Hello, @shu0406 

To enter a large number of lines, use the "multi-line field" setting, if you save to pdf format, it is also better to turn on the "fixed size field" setting.

In version 7.4.1. Are you still having problems with the Date& Time field?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
