### ISSUE TITLE
warning during installation on CentOS

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#168]
1. Install `onlyoffice-documentserver` using instruction http://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx
2. On `sudo yum install onlyoffice-documentserver` step there will be warning

```
Installing : onlyoffice-documentserver-4.4.3-7.x86_64                                                                79/80 
Generating AllFonts.js, please wait...Done
warning: %post(onlyoffice-documentserver-4.4.3-7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package onlyoffice-documentserver-4.4.3-7.x86_64
```

But everything seems working fine.

Tested on:
`CentOS Linux release 7.3.1611 (Core)`
`onlyoffice-documentserver-4.4.3-7.x86_64`

**Comment by agolybev** [comment]
@ShockwaveNN  Can't reproduce it with latest version, could you confirm if the bug still exists.

**Comment by ShockwaveNN** [comment]
@agolybev yep, still there
See full install log for `yum -y install onlyoffice-documentserver-ie > install.log 2>&1`
[install.log](https://github.com/ONLYOFFICE/DocumentServer/files/1678307/install.log)

**DocumentServer version:** 5.0.99.448

**Operating System:** CentOS Linux release 7.4.1708 (Core)

**Comment by ShockwaveNN** [comment]
Seems that problem is resolved on latest stable version
Install log looks like this:
```
Installing : onlyoffice-documentserver-ee-6.4.2-6.x86_64        6/6 
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
The package msttcore-fonts-installer not found
You can install it with the commands:
    # yum install cabextract xorg-x11-font-utils
    # rpm -i https://deac-ams.dl.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
  Verifying  : supervisor-3.4.0-1.el7.noarch                      1/6 
  Verifying  : libXScrnSaver-1.2.2-6.1.el7.x86_64                 2/6 
  Verifying  : xorg-x11-server-Xvfb-1.20.4-16.el7_9.x86_64        3/6 
  Verifying  : onlyoffice-documentserver-ee-6.4.2-6.x86_64        4/6 
  Verifying  : python-meld3-0.6.10-1.el7.x86_64                   5/6 
  Verifying  : pwgen-2.08-1.el7.x86_64                            6/6
  ```
  
  So I'm closing this issue
