### ISSUE TITLE
Is there an auto testing tool for onlyoffice? What if the performance encountered in it is not consistent with the previous one?

### ISSUE THREAD

**Issue by yayaQAQ** [ONLYOFFICE/DocumentServer#1682]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
No automated testing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
not a bug
**What is the expected behavior?**
Find ways to automate testing
**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by yayaQAQ** [comment]
> We got [this](https://github.com/ONLYOFFICE/document-server-stress-testing)
> 
> And some other tools, but we're not planning to release them in open source, they only for our private usage

How can I get them? Money？

**Comment by ShockwaveNN** [comment]
May be, it's out of my job responsibilities to make such a decision
You should contact sales@onlyoffice.com

But for start I think open-source repo I've mention should be enought

**Comment by ShockwaveNN** [comment]
selenium-webdriver, we're using it

**Comment by yayaQAQ** [comment]
> selenium-webdriver, we're using it

Can you share the corresponding test script?

**Comment by ShockwaveNN** [comment]
Sorry, no, I'm not allowed to share those scripts

We got some building blocks of it available at [this org](https://github.com/ONLYOFFICE-QA/)
But most of our end-testings scripts are not publically accesable

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
