### ISSUE TITLE
Only Office documents and spreadsheet is loading slow

### ISSUE THREAD

**Issue by vicky1hr** [ONLYOFFICE/DocumentServer#1684]
we are using only office in my Nextcloud application.

When I'm opening any document its taking more time to load the onlyoffice editor.

Example when opening document/spreadsheet sdk-all-min.js & sdk-all.js when it opens it taking more time to load.

So like that many JS files are loading slow on first time. And then next time its loading from disk cache so its faster.

My questions are below.
1) How can we load the JS file much faster and second time how can we load all files from memory cache instead of disk cache.
2) Is there any way to load any some JS files after opens the document/spreadsheet which we don't need at the time of opening the document.

Below screenshot is mentioned first time load and second time load 

![image](https://user-images.githubusercontent.com/47319706/158602013-4105f98d-5f02-416d-a206-46c804914261.png)

![image](https://user-images.githubusercontent.com/47319706/158600533-b63e6a98-a027-4368-83c9-e29e9fbcbb1c.png)

**Comment by ShockwaveNN** [comment]
> How can we load the JS file much faster and second time how can we load all files from memory cache instead of disk cache.

I don't know the answer to that question, I think it may somehow be configured via Nginx or I think the browser itself how to load that
Personally, I don't think that cached numbers like 232ms is really bad

> Is there any way to load any some JS files after opens the document/spreadsheet which we don't need at the time of opening the document.

Most of the files on your screenshot (like 069 or 070) are font files, maybe the document you've opened has a lot of complicated fonts. Usually CJK fonts are rather big

If you'll try to open a file with contains only Calibre font there will be a minimal set of fonts we're loading to be compatible with the most common fonts

**Comment by vicky1hr** [comment]
Thank you for your response.

Can you guide me how can we use minimal set of fonts? and remove all unwanted bigger fonts in onlyoffice?

**Comment by ShockwaveNN** [comment]
> Can you guide me how can we use minimal set of fonts?

Sorry, there is no such guide, this set is downloaded for a reason, to be compatible with most documents

You can try to remove some fonts from `/var/www/onlyoffice/documentserver/core-fonts/` and run `documentserver-generate-allfonts.sh` but not sure if it will worked

Also please note - if those fonts downloading for 2 seconds - it's rather long for 200kb files, maybe your front-end connection speed should be improved and\or DocumentServer should be placed in local network\datacenter nearer

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
