### ISSUE TITLE
6.4.2 How to close spellcheck service in edit mode

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1690]
6.4.2 How to close spellcheck service in edit mode

**Comment by nobt854** [comment]
https://api.onlyoffice.com/editors/config/editor/customization#spellcheck

Does not work in edit mode, still spell checking

**Comment by ShockwaveNN** [comment]
Hi, could you recheck this problem on latest stable v7.0.1, I think we fix something related to that in this version, but not sure for 100%

Also please make sure you've checking it with clean cache in incognito mode

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
