### ISSUE TITLE
MacOS Keyboard navigation is broken (works like Windows/Linux)

### ISSUE THREAD

**Issue by a-gerhard** [ONLYOFFICE/DocumentServer#1693]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Pressing Command + left/right skips a word. Pressing Option + left/right just moves the cursor by one character

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to navigate the cursor in a line in Document Editor. Haven't tried this in any other editor.

**What is the expected behavior?**

Pressing Command + left/right skips to the beginning or end of the line. Pressing Option + left/right skips a word (Like ctrl+left/right in Windows/Linux)

**Did this work in previous versions of DocumentServer?**

Don't know.

**DocumentServer version:** 7.0.0

**Operating System:** MacOS (client), Debian (server)

**Browser version:** Chrome 99.0.4844.51 (Official Build) (arm64)

**Comment by Gingetsu** [comment]
Hello @a-gerhard ,
this is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1093
