### ISSUE TITLE
PDF render has image problem

### ISSUE THREAD

**Issue by aetna-softwares** [ONLYOFFICE/DocumentServer#17]
I installed a local document server using docker.

It run fine except that PDF export has problem on images rendering

On my SaaS personal.onlyoffice.com account the PDF is fine : 

image problem : 
![image](https://cloud.githubusercontent.com/assets/8860618/11468315/cf6429bc-974e-11e5-897d-6e86954b059c.png)

on personal.onlyoffice.com : 
![image](https://cloud.githubusercontent.com/assets/8860618/11468341/f6abb832-974e-11e5-8176-dcfc3d22016a.png)

**Comment by ibnpetr** [comment]
We need to analyze the file.
Could you please send it to server@onlyoffice.com 
regards

**Comment by trofim24** [comment]
If you have a problem with the file display , give us a link to a file
