### ISSUE TITLE
apply changes error

### ISSUE THREAD

**Issue by yayaQAQ** [ONLYOFFICE/DocumentServer#1706]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
apply changes error
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I'm not sure about the operation of recurrence, because there are many operations done
**What is the expected behavior?**
apply changes right
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer version:**

**Operating System:**

**Browser version:**

I'm using onlyoffice for editing and it reports an error after refreshing.
<img width="894" alt="image" src="https://user-images.githubusercontent.com/20497531/160518080-b857e1d9-832e-4a01-8eef-b95afe0ea2b0.png">

The next thing I found was code like this:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/20497531/160518252-a7a6e61a-4a65-4d31-8014-e4266d0a5819.png">

Why do we have to fetch the value from the content after the length of the array has been exceeded?

oDocument.Content.length = 58 
Pos=61

**Comment by ShockwaveNN** [comment]
Hi, which version of DocumentServer are you using?
This maybe be a bug, and it may be fixed in latest v7.0.1

But without proper step-by-step scenario I don't think we'll able to reproduce it and fix if it happens on latest stable version

**Comment by yayaQAQ** [comment]
> 

I'll wait for 7.0.1 then, thanks for the reply

**Comment by yayaQAQ** [comment]
> Hi, which version of DocumentServer are you using? This maybe be a bug, and it may be fixed in latest v7.0.1
> 
> But without proper step-by-step scenario I don't think we'll able to reproduce it and fix if it happens on latest stable version

I'll wait for v7.0.1 then, thanks for the reply.

**Comment by ShockwaveNN** [comment]
v7.0.1 is released for quite some time so if you got not this version you should update

If this issue is still persists - we need step-by-step scenario as I described earlier
