### ISSUE TITLE
Document Server connection to PostgreSQL via SSL

### ISSUE THREAD

**Issue by virtio-technique** [ONLYOFFICE/DocumentServer#1708]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Unable to connect  the Document Server App to PostgreSQL using SSL

Add the ability to specify the Document Server App connection to PostgreSQL via SSL in the docker container ENV VAR

Also need fix documentation how to pass connection string variables "SSL Mode=Require;Trust Server Certificate=true" in /etc/onlyoffice/documentserver/local.json config file.

"sql": {
        "type": "postgres",
        "dbHost": "",
        "dbPort": "5432",
        "dbName": "",
        "dbUser": "",
        "dbPass": ""
},

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 Document Server App unable to connect to PostgreSQL with pg_hba.conf like this

hostnossl all           all                all              reject

**What is the expected behavior?**
Forming a connection string to PostgreSQL using SSL

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**
documentserver:7.0.1

**Host Operating System:**
Official docker image

**Comment by igwyd** [comment]
@virtio-technique we can suggest a workaround. We have a param in sql section https://nct.onlyoffice.com/Products/Projects/ProjectTeam.aspx?prjID=171 for support any connector configuration. For example you can add your self-signed certs:
1. Create certificates in openssl and configure postgresql with SSL https://www.postgresql.org/docs/12/ssl-tcp.html
2. Allow to use self-signed certs in documentserver /etc/onlyoffice/documentserver/default.json:
```
"requestDefaults": {
...
	"rejectUnauthorized": false
},
```
3. Convert certs to PEM format and pass in /etc/onlyoffice/documentserver/default.json as string with line-feed characters:
```
"sql": {
...
	"pgPoolExtraOptions": {
		"ssl":{
			"rejectUnauthorized": false,
			"ca": "-----BEGIN CERTIFICATE-----\n...root_crt...\n",
			"key": "-----BEGIN PRIVATE KEY-----\n...client_key...\n",
			"cert": "-----BEGIN CERTIFICATE-----\n...client_crt...\n"
		}
	}
}
```
You can use the command to convert each pem file:
```
awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' cert-name.pem
```
4. Add environment variable ```ALLOW_CONFIG_MUTATIONS=true``` to supervisor configs /etc/supervisor/conf.d/ds-converter.conf, /etc/supervisor/conf.d/ds-docservice.conf and reboot server
5. Check connection

**Comment by igwyd** [comment]
It's fixed at: https://github.com/ONLYOFFICE/server/commit/3ac402c70ef6e5a0bbbf9da1e4a0b99f29748f31
And will be released in the next major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Comment by shazinahmed** [comment]
Is there a documentation on how we can define pgPoolExtraOptions when running using Docker containers?

**Comment by igwyd** [comment]
Hello @shazinahmed, now only [workaround](https://github.com/ONLYOFFICE/DocumentServer/issues/1708#issuecomment-1091981622) is possible, but we have enchancemen issue 59891 on our private issue tracker for VAR in docker.

**Comment by jonahallibone** [comment]
> Hello [@shazinahmed](https://github.com/shazinahmed), now only [workaround](https://github.com/ONLYOFFICE/DocumentServer/issues/1708#issuecomment-1091981622) is possible, but we have enchancemen issue 59891 on our private issue tracker for VAR in docker.

hi, did this ever get landed? I would love to be able to use a flag to disable the SSL rejection from docker so i don't need a default.json copied?

**Comment by shazinahmed** [comment]
@jonahallibone It's been a while and I have moved on from the company. From what I remember, we went with the option of mounting the configuration as a JSON file.

**Comment by igwyd** [comment]
Hello @jonahallibone. Unfortunately, the docker variable has not been implemented yet. I will remind our team about this. You can transfer these parameters to `local.json` and mount it as @shazinahmed until the feature not implemented.
