### ISSUE TITLE
Does onlyoffice support inserting latex formulas? Or will it be supported in later versions?

### ISSUE THREAD

**Issue by yayaQAQ** [ONLYOFFICE/DocumentServer#1709]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
no latext support
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
not a bug
**What is the expected behavior?**
can insert latext and render latex.
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by Rita-Bubnova** [comment]
Maybe it's a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1623.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
