### ISSUE TITLE
Viewer Error Code -82? What is it?

### ISSUE THREAD

**Issue by rpuskarich** [ONLYOFFICE/DocumentServer#1710]
We are currently using version DocumentServer-DE 5.5.1 on Windows Server 2019.

When opening a file with the viewer, certain files with throw the following error:

![image](https://user-images.githubusercontent.com/24723644/161081215-be9f1898-b250-44d1-97f1-d442d24c1b0f.png)

Typically, this can be associated with file names that are invalid or contain invalid characters and simply changing the name will suffice. Occasionally, it doesn't matter what the file name is, it will throw this error with no resolution. The file will download and open just fine.

I cannot find any documentation on this non-descript error anywhere. Error code -82 is also not part of the documentation.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
