### ISSUE TITLE
Comments are sorted by location(page, x, y)

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1711]
What is the current behavior?
Chronological order.

DocumentServer Docker tag:
documentserver:7.0.1

**Comment by ShockwaveNN** [comment]
Hi, isn't

![image](https://user-images.githubusercontent.com/668524/161224889-c8054b60-823f-4f99-8491-bab40d7b28ed.png)

From top to botton is that you need?

Starting from top of document and going to it's bottom>

**Comment by verydemo** [comment]
yes, thank you.
