### ISSUE TITLE
Allow mouse selection of multiple words for replacement

### ISSUE THREAD

**Issue by brendan-pike** [ONLYOFFICE/DocumentServer#1713]
Feature request.  One Office365 feature that is missing is the ability to mouse select multiple words then type to change those words.  This is a more focused rather than a mass find/replace function.

**Comment by Rita-Bubnova** [comment]
This is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1497.

**Comment by brendan-pike** [comment]
Thanks, I didn't find that before.
