### ISSUE TITLE
failed to start docs server

### ISSUE THREAD

**Issue by tbswork1** [ONLYOFFICE/DocumentServer#1714]
**Do you want to request a *feature* or report a *bug*?**
fail to start service 

**What is the current behavior?**
fail to start docs service 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The docs server was working. At some point the Linux (on Vmware) reported out of memory. After reboot the issue comes up.

runs `sudo supervisorctl restart all`

```
ds:docservice: stopped 
ds:example: stopped
ds:metrics: stopped
ds:converter: ERROR (spawn error)
ds:docservice: ERROR (spawn error)
ds:metrics: started
ds:example: started
```
**What is the expected behavior?**
no error reported

**Did this work in previous versions of DocumentServer?**
don't know

**DocumentServer version:**
7.0.1

**Operating System:**
Ubuntu 20.04

**Browser version:**
any

**Comment by ShockwaveNN** [comment]
Hi

> At some point the Linux (on Vmware) reported out of memory.

Do you have swap on this system? I think we recommend 4gb minimal swap on almost any system, because some complex files need a lot of memory to be converted

> ds:converter: ERROR (spawn error)

I think there should be some logs at `/var/log/supervisor/supervisord.log` or `/var/log/onlyoffice/documentserver/` locations

**Comment by tbswork1** [comment]
It has swap space set up by default installation of Ubuntu. The problem was caused by malformed `/etc/onlyoffice/documentserver/local.json'. 

Thanks for the help.
