### ISSUE TITLE
`Cannot read properties of undefined` while opening ppt file

### ISSUE THREAD

**Issue by Floatlen** [ONLYOFFICE/DocumentServer#1718]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
file cannot be opened
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
upload file and open
**What is the expected behavior?**
open normally
**Did this work in previous versions of DocumentServer?**
yes, it works normally at version 6+
**DocumentServer version:**
7.0.1
**Operating System:**
windows
**Browser version:**
google chrome version 100.0.4896.75

**Comment by Floatlen** [comment]
Shape.js:1544 Uncaught TypeError: Cannot read properties of undefined (reading 'getMatchingShape')
    at CShape.getHierarchy (Shape.js:1544:59)
    at CTextBody.<anonymous> (TextBody.js:190:45)
    at Object.ExecuteNoHistory (Format.js:824:17)
    at CTextBody.recalculateBodyPr (TextBody.js:185:19)
    at CTextBody.getCompiledBodyPr (TextBody.js:292:14)
    at CShape.<anonymous> (Shape.js:1353:36)
    at Object.ExecuteNoHistory (Format.js:824:17)
    at CShape.getBodyPr (Shape.js:1342:22)
    at CShape.<anonymous> (Shape.js:3017:50)
    at Object.ExecuteNoHistory (Format.js:824:17)

**Comment by ShockwaveNN** [comment]
Hi, please fill out issue template with all required information

Judging by error - did you compile DocumentServer manually?

Also we need this file, which raises this error

**Comment by Floatlen** [comment]
> Judging by error - did you compile DocumentServer manually?
> yes, I compiled the front end, in order to see the detailed error reason。
> Also we need this file, which raises this error

**Comment by ShockwaveNN** [comment]
I can confirm that problem with this file exists on v 7.0.1, but I've checked it on v7.1.0 which is currently in development and error is gone and file opens correctly
![image](https://user-images.githubusercontent.com/668524/162681110-994fb4e8-7c89-4664-9e36-34bf95f4d6cb.png)

I really hope that we'll able to release this version in a month, but you can try it with

```
docker run -itd -p 80:80 onlyoffice/4testing-documentserver-ee:7.1.0.158
``` 
But please do not use it in production, it's not 100% ready for that

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until we release version with fix to stable

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there is some troubles
