### ISSUE TITLE
doc file content error.

### ISSUE THREAD

**Issue by kalcaddle** [ONLYOFFICE/DocumentServer#172]
bug

file content error
demo file:

[content error.doc.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1323459/content.error.doc.zip)

versions 4.4

**Comment by ShockwaveNN** [comment]
Bug in our private bugzilla http://bugzilla.onlyoffice.com/show_bug.cgi?id=36342

**Comment by ShockwaveNN** [comment]
5.1.0 released and issue should be fixed
