### ISSUE TITLE
Use of + sign in Sheets

### ISSUE THREAD

**Issue by smarquespt** [ONLYOFFICE/DocumentServer#1721]
**Do you want to request a *feature* or report a *bug*?**

Not sure.

**What is the current behavior?**

Pressing + sign is not equivalent to = sign

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In a cell: '+1+1' instead of =1+1
To sum 2 cells with values press: '+cell1 + cell2' instead of '=cell1 + cell2'

**What is the expected behavior?**

sign + should be equivalent to = sign, just like in MS Office and other suites

+1+1 returns 2

**Operating System:**

Windows 10

**Browser version:**

Chromium 100.x

**Comment by Rita-Bubnova** [comment]
This issue is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/547.
