### ISSUE TITLE
Sort / Custom Sort does not respect frozen rows

### ISSUE THREAD

**Issue by gwpl** [ONLYOFFICE/DocumentServer#1722]
To reproduce:

* make spredsheet, put headers (e.g. first two rows)
* freeze first two rows with headers (by drag&drop from upper left corner)
* then Data->Sort / Data->CustomSort

Expected:

* to get data sorted from rows from 3rd to end

What happens:

* sorts data from 1st row, ignoring fact that first two rows were frozen.

**Comment by ShockwaveNN** [comment]
Hi, could you fill out the issue template correctly

We need product version, host-client os

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
