### ISSUE TITLE
[Feature request] Add Flatpak / AppImage packaging

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/DocumentServer#1724]
Hey,
I really would like to see a additional Flatpak release for Onlyoffice Documentserver as it was already done for the [Desktopeditor package](https://flathub.org/apps/details/org.onlyoffice.desktopeditors).
Using DocumentServer as Flatpak could ease packaging and usage for certain distributions. Especially on NixOS I'm [unable to get the binary (Debian) version to work](https://github.com/NixOS/nixpkgs/pull/138818) and manual compilation seems to difficult there too.

Best regards
Jonas

**Comment by ShockwaveNN** [comment]
Hi, is there any particular reason why this will be better than Docker (our preferred way to distribute DocumentServer) or `snap` (I know that a lot of people do not like snap packages, but we got it right now and I cannot promise that we'll ever do flatpak)

Personally, I understand that people need snap\flatpak\appimage for desktop applications, I use them a lot, but for any server application I think Docker is the better way in every parameter

**Comment by onny** [comment]
Good point this does make sense, I‘m just struggling to get this to work on NixOS because the binary packaged with pkg is tricky to patch on this distro. Probably Flatpak or Appimage wont help here. I‘ll see if I can get it to compile from source :) Thank you!

**Comment by ShockwaveNN** [comment]
Just a sidenote - we got [snap](https://github.com/ONLYOFFICE/snap-documentserver/) of DocumentServer, maybe this may somehow help you

P.S. Don't quite remember why we done it, probably some from our clients really wanted it and do not liked Docker way (
