### ISSUE TITLE
WOPI discovery of onlyoffice supports embeddded param, but actually not works

### ISSUE THREAD

**Issue by zyf0330** [ONLYOFFICE/DocumentServer#1725]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The urlsrc in the wopi hosting/discovery xml gives <e=EMBEDDED&> query param, but it doesn't work. Returned preview page is still `desktop` type.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. use urlsrc given in the wopi hosting/discovery xml to construct a url
2. set `e` param in the url to `true`
3. do POST request with url
4. preview returned doc page
**What is the expected behavior?**
The doc page should be previewed as `embedded` mode instead of `desktop` mode.

The `type` property at root level of the config in the response HTML of POST request is `desktop` which should be `embedded`.

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
7.0
**Operating System:**
Linux Ubuntu
**Browser version:**
Google Chrome v100

**Comment by igwyd** [comment]
Hello @zyf0330 We added embedded mode because our editors have it, but it's not fully implemented in wopi yet. We have issue 56772 in our private issue tracker.

**Comment by igwyd** [comment]
It's fixed at: https://github.com/ONLYOFFICE/server/commit/6331a5b672d04d807a50020f0200b8fffd0b3c07 https://github.com/ONLYOFFICE/web-apps/commit/92bb952875aaee5057f8b0e73faa08e648e78344
And will be released in the next major release

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Comment by zyf0330** [comment]
Ok. May I know When the feature will be released?

**Comment by ShockwaveNN** [comment]
It is released in v7.2.0 several weeks ago
