### ISSUE TITLE
document conversion with  issue

### ISSUE THREAD

**Issue by kalai6095** [ONLYOFFICE/DocumentServer#173]
I am using onlyoffice integration server recent version while upload a document to server shapes are not converted properly and i unable to move (wrap) shapes

original document
![ip onlyoffice2](https://user-images.githubusercontent.com/6815038/30793649-0a524934-a1e1-11e7-940e-057cd2a291d0.png)

after the conversion

![ip onlyoffice](https://user-images.githubusercontent.com/6815038/30793648-0a519430-a1e1-11e7-9309-166ce289bebc.png)

**Comment by flaminestone** [comment]
Can you attach this file to issue?

**Comment by kalai6095** [comment]
sure! @flaminestone 
[Creation & Removal.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1329095/Creation.Removal.zip)

**Comment by flaminestone** [comment]
Yes, @kalai6095 , it is realy problem, but not in shape wrap. Problem in image wrap after doc -> docx conversion. We will fix it in future release
Thank you for report.

**Comment by kalai6095** [comment]
thank you, @flaminestone  and one more bug  doc-> pdf conversion page border works fine but doc->docx conversion page border is in dotted line

**Comment by ShockwaveNN** [comment]
Bug in our private bugzilla - http://bugzilla.onlyoffice.com/show_bug.cgi?id=36339

**Comment by KirillovIlya** [comment]
Fixed https://github.com/ONLYOFFICE/sdkjs/commit/289b58a8eda18325fda740724644706f26b143b5
