### ISSUE TITLE
Spreadsheet : XLSX with data validation not working properly after import

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#1731]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
After import of the XLSX attached, the table with data validation and cascading dropdown is not working properly.
I need to validate the INDIRECT function from data validation panel to make the cascading dropdown works properly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![menu-cascade](https://user-images.githubusercontent.com/11867613/165247747-787e9d67-dd30-4567-a667-4abad7090259.gif)

**What is the expected behavior?**
Choice made from the first dropdown column id should update correctly the dropdown from the column prenom

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
7.0.1.37

**Operating System:**
Docker

**Browser version:**
Firefox 99.0.

XLSX file :

[test_menu_cascade.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/8560919/test_menu_cascade.xlsx)

**Comment by alinasafonova** [comment]
Hello, @ydelattre

This is known issue - 56293 in our private issue tracker.
Thank you for report.

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
