### ISSUE TITLE
healthcheck 502 Bad Gateway

### ISSUE THREAD

**Issue by Tealk** [ONLYOFFICE/DocumentServer#1734]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If i try to open https://onlyoffice.rollenspiel.cloud/healthcheck i get 502 Bad Gateway

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have changed the domain but now the healthcheck no longer works

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
see a white page with true

**DocumentServer version:**
7.0.1-37

**Operating System:**
Debian 10

**Browser version:**
Firefox 99.0.1

**Comment by ShockwaveNN** [comment]
Hi, you should check for errors in `/var/log/onlyoffice`

**Comment by Tealk** [comment]
Which log exactly should I look at?
```
/var/log/onlyoffice# ls -al
total 16
drwxr-xr-x  4 onlyoffice onlyoffice 4096 Apr 29 12:35 .
drwxr-xr-x 15 root       root       4096 Apr 29 12:12 ..
drwxr-xr-x  6 ds         ds         4096 Apr 29 12:37 documentserver
drwxr-xr-x  2 onlyoffice onlyoffice 4096 Apr 29 12:17 documentserver-example


/var/log/onlyoffice/documentserver# ls -al
total 36
drwxr-xr-x 6 ds         ds         4096 Apr 29 12:37 .
drwxr-xr-x 4 onlyoffice onlyoffice 4096 Apr 29 12:35 ..
drwxr-xr-x 2 ds         ds         4096 Apr 29 12:35 converter
drwxr-xr-x 2 ds         ds         4096 Apr 29 12:35 docservice
drwxr-xr-x 2 ds         ds         4096 Apr 29 12:35 metrics
-rw-r--r-- 1 root       root       9200 Apr 29 13:21 nginx.error.log
drwxr-xr-x 2 ds         ds         4096 Apr 29 12:35 spellchecker
```

**Comment by ShockwaveNN** [comment]
All of them, but probably nginx or docservice

**Comment by ShockwaveNN** [comment]
> [2022-04-29T12:35:52.616] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672


This mean that RabbitMQ server cannot be reached

**Comment by Tealk** [comment]
the log is not exactly meaningful of it


/var/log/rabbitmq/startup_log
`ERROR: epmd error for host OnlyOffice: timeout (timed out)`

**Comment by Tealk** [comment]
I have now specified the cmoputer in the /etc/host now it works
`127.0.0.1	localhost OnlyOffice`
