### ISSUE TITLE
All Chinese words become square boxes in generated pdf file.

### ISSUE THREAD

**Issue by qianweichun** [ONLYOFFICE/DocumentServer#1738]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
All Chinese words become square boxes in generated pdf file.
![截屏2022-05-06 13 50 26](https://user-images.githubusercontent.com/45196316/167074558-b1f3c680-8652-4347-a099-61a079d85737.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have added Chinese font files to the container. And it is fine while editing. 
**What is the expected behavior?**
The Chinese word should be display normally in generated pdf.

**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
7.0
**Operating System:**
Client is Mac. Server is docker linux.
**Browser version:**
Microsoft Edge 101.

**Comment by ShockwaveNN** [comment]
Hi, could you provide original file?

**Comment by qianweichun** [comment]
Here is a sample file.
[doc1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/8641312/doc1.docx)
[doc1.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/8641313/doc1.pdf)

**Comment by ShockwaveNN** [comment]
I think some more additional fonts are required in your case

I'm not sure (I do not understand chinese at all), but seems if `微软雅黑` font is installed (and seems that it's installed on my server with A LOT of additional fonts) result pdf is looking fine 

![image](https://user-images.githubusercontent.com/668524/167153417-62a5cc00-338b-4a48-a602-74956087ef59.png)
Also please note that your file looks completly different that your original file from first message

**Comment by qianweichun** [comment]
Yes It is a different file.
I have double checked that if I use the core-fonts bundle, the pdf generated will look fine. But with the chinese fonts from windows system....
Like this, words using core-fonts are fine...
![截屏2022-05-06 22 47 48](https://user-images.githubusercontent.com/45196316/167157064-c641d0c9-7eeb-4ae7-8343-a6e138980980.png)

**Comment by qianweichun** [comment]
It is the problem about font files....I was using font files from sharing of someone, it was proved that I reinstalled a windows and ms office, and copied fonts from the new installed box. The problem disappeared....

**Comment by ShockwaveNN** [comment]
Glad to hear that problem is resolved
