### ISSUE TITLE
Unable to configure storage-s3 for document cache

### ISSUE THREAD

**Issue by nitin02** [ONLYOFFICE/DocumentServer#174]
/etc/onlyofffice/documentserver/default.json specifies a way to use S3 for document cache instead of the mounted file system. But there is no documentation on how to use it. How can we configure it?

Also, By configuring s3, is the shared /var/lib/onlyoffice/documentserver/App_Data location for multiple instances not required?

Moreover, shouldn't it be be able to be configurable from Environment variables (like how nginx/redis etc config as set in the Docker version).

**Comment by ShockwaveNN** [comment]
Using S3 is not documented.
And also this those never tested and used in any real configuration after development.
Sorry

**Comment by bsavelev** [comment]
hello!

Is something changed here? Can I use s3 for cache?

**Comment by ShockwaveNN** [comment]
@bsavelev Sorry, no news
