### ISSUE TITLE
onlyoffice7.0.1 failed to save .doc file

### ISSUE THREAD

**Issue by z001357999** [ONLYOFFICE/DocumentServer#1740]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
.doc file failed to save. .docx file success to save
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open normally Doc file editing content saving prompt "error occurred when saving file".
ServerError:
 [2022-05-09T03:48:20.863] [ERROR] nodeJS - stdout (id=633-LocalFile-DDDCA918CAEB3B6B01D697EC6AA94D89-20220427163016_9076):
[2022-05-09T03:48:20.864] [ERROR] nodeJS - stderr (id=633-LocalFile-DDDCA918CAEB3B6B01D697EC6AA94D89-20220427163016_9076):
[2022-05-09T03:48:20.864] [ERROR] nodeJS - ExitCode (code=80;signal=null;error:-80;id=633-LocalFile-DDDCA918CAEB3B6B01D697EC6AA94D89-20220427163016_9076)
**Did this work in previous versions of DocumentServer?**
onlyoffice6.4 normal
**DocumentServer version:**
docker 7.0.1
**Operating System:**
centos7.6
**Browser version:**
chrome96

**Comment by ShockwaveNN** [comment]
Hi, is this error happens to some specific file or to any file?

And if only for specific - we need this file and step-by-step scenario how to reproduce the problem

**Comment by z001357999** [comment]
> 嗨，这个错误是发生在某个特定文件还是任何文件上？
> 
> 如果只是针对特定的 - 我们需要这个文件和分步场景如何重现问题



> 

Thanks for your reply. I tried all of them .doc format files are all wrong, but There is no problem with .docx files

**Comment by ShockwaveNN** [comment]
Seems there is some troubles with your installation, for some reason x2t and convert service do not work properly

Maybe has something to do with your permissions, something like SELinux or similar

If there is no additional errors in log file - it's hard to understand real reason

Maybe you should setup a new server, check if it works fine and compare settings?

**Comment by z001357999** [comment]
> 您的安装似乎有一些问题，由于某种原因 x2t 和转换服务无法正常工作
> 
> 也许与您的权限有关，例如 SELinux 或类似的
> 
> 如果日志文件中没有其他错误 - 很难理解真正的原因
> 
> 也许您应该设置一个新服务器，检查它是否工作正常并比较设置？



> Seems there is some troubles with your installation, for some reason x2t and convert service do not work properly
> 
> Maybe has something to do with your permissions, something like SELinux or similar
> 
> If there is no additional errors in log file - it's hard to understand real reason
> 
> Maybe you should setup a new server, check if it works fine and compare settings?

I pulled the last version from docker hub. Are there any changes in versions 7.0 and 6.4? The same server, the same docker. There is no problem with version 6.4.
![image](https://user-images.githubusercontent.com/105187158/167371225-c647ffc7-0b71-47bd-ad8c-0e9455836e1c.png)
![image](https://user-images.githubusercontent.com/105187158/167371732-08508011-4c6b-43b6-b717-8898374c6853.png)

**Comment by ShockwaveNN** [comment]
There is lot of small changes between 6.4 and 7.0 and I cannot point out why this happens

It may depend of rest of your environment, or maybe some dirty database or left out migration, so I advice to check it on temp clean server

Or run docker without any mounts or volumes (if you use some)

Still I need exact scenario how to reproduce this problem, including `docker run` configuration or `docker-compose` you've using

**Comment by z001357999** [comment]
> There is lot of small changes between 6.4 and 7.0 and I cannot point out why this happens
> 
> It may depend of rest of your environment, or maybe some dirty database or left out migration, so I advice to check it on temp clean server
> 
> Or run docker without any mounts or volumes (if you use some)
> 
> Still I need exact scenario how to reproduce this problem, including `docker run` configuration or `docker-compose` you've using

I just did it again. Unfortunately, I still reported an error. This is the whole process of my operation.
![image](https://user-images.githubusercontent.com/105187158/167376177-fe4074af-8d4c-4506-a4f5-345e5b2b6fff.png)

**Comment by ShockwaveNN** [comment]
`priviledged` is not requred for using of DocumentServer

Try it again and without it and if problem persists - attach some example file in this issue and I try it on my own

**Comment by ShockwaveNN** [comment]
Also try to add `-it` to run command, not sure if it needed,. but just in case

**Comment by z001357999** [comment]
> 还尝试添加`-it`到运行命令，不确定是否需要。但以防万一

I saw an error message and didn't know if it was related.
![image](https://user-images.githubusercontent.com/105187158/167380808-6d5ddcd3-3dd9-45eb-9426-968161682d03.png)

**Comment by ShockwaveNN** [comment]
I'm not sure, i see you got some not default upstream ids in file name

Are you using some custom DMS? 

Could you enable integrated example (via `http://docserverurl/welcome') and check if on `/example` test example your files are opened correctly?

**Comment by z001357999** [comment]
> example

I have no problem with the test in the example. I'll check it again. Thank you

**Comment by z001357999** [comment]
> I'm not sure, i see you got some not default upstream ids in file name
> 
> Are you using some custom DMS?
> 
> Could you enable integrated example (via `http://docserverurl/welcome') and check if on `/example` test example your files are opened correctly?

I found in the example test that I uploaded Doc file will be converted to by default Docx file, so I can't verify this problem. Here is my example file.
[files.zip](https://github.com/ONLYOFFICE/DocumentServer/files/8650547/files.zip)

**Comment by ShockwaveNN** [comment]
> I found in the example test that I uploaded Doc file will be converted to by default Docx file,

So you didn't mention that you wrote a DMS that do not convert doc to docx but try to edit them without conversion directly
Wow, this is really needed information

So no, we do not support editing all files directly, you NEED to convert them to docx, edit them and convert back to doc if you need to leave them in original format

**Comment by z001357999** [comment]
> > 我在示例测试中发现我上传的 Doc 文件将默认转换为 Docx 文件，
> 
> 所以你没有提到你写了一个不将doc转换为docx但尝试直接编辑它们而不直接转换的DMS 哇，这确实是需要的信息
> 
> 所以不，我们不支持直接编辑所有文件，如果您需要将它们保留为原始格式，您需要将它们转换为 docx，编辑它们并转换回 doc

Is this a new change in version 7.0? Because I didn't convert doc to docx in previous versions

**Comment by ShockwaveNN** [comment]
It was always like this, so you just used some unofficial way to edit file, it was working, but I don't think we've ever guaranteed it to work

In all our product we convert doc files to docx to allow proper edits in them

**Comment by z001357999** [comment]
> 一直都是这样，所以您只是使用了一些非官方的方式来编辑文件，它可以正常工作，但我认为我们从未保证过它可以正常工作
> 
> 在我们所有的产品中，我们将 doc 文件转换为 docx 以允许对其进行适当的编辑

okay, thank you

**Comment by ShockwaveNN** [comment]
I'll close this issue if you got any further question - feel free to comment here or create new issue
