### ISSUE TITLE
Document language for uploaded files are detected as English (United States).

### ISSUE THREAD

**Issue by qianweichun** [ONLYOFFICE/DocumentServer#1742]
The language is set correctly for New documents. The language for nextcloud is Chinese, then the language new documents is also Chinese, as expected.

But for those files those I uploaded, the language are NOT detected correctly, so the spellchecker reports error for every word in the Chinese doc.

Is it possible to set the document language automatically?

**Comment by ShockwaveNN** [comment]
Hi, could you provide an example of such files? I think they are have language property set as not chinese

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
