### ISSUE TITLE
issue with the pdf version of my oForm

### ISSUE THREAD

**Issue by JOduMonT** [ONLYOFFICE/DocumentServer#1744]
With OnlyOffice 7.1.0.215 with Nextcloud 22
When I transform my .docxf into PDF or PDF/a, the multiple line entry possibilities disappear.

### from the docxf
![image](https://user-images.githubusercontent.com/5204724/168531310-ae30ae20-d3e7-432f-9afa-00ccd3db22fa.png)

### after saving it as pdf
![image](https://user-images.githubusercontent.com/5204724/168531479-7d0934d6-f7a9-4971-9baf-e8a560b133e8.png)

### it would be acceptable if
in the pdf version; when you fill the field with an overflow of text, it would make a new line, but it doesn't.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
