### ISSUE TITLE
Value selection via drop-down menu is broken if result cell is made of merged cells

### ISSUE THREAD

**Issue by Alex01d** [ONLYOFFICE/DocumentServer#1755]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

6.4.1.46

### Expected Behavior

A cell, made of several merged cells, with data validation 'Allow List' has only one drop-down menu. The cell shows the value I selected.

### Actual Behavior

A cell, made of several merged cells, with data validation 'Allow List' has several drop-down menus. The cell shows the value I selected only if I used the first menu (on the left).

### Reproduction Steps

1. Merge 3 cells in row.
2. Open 'Data validation' on 'Data' tab and select 'List' in 'Allow' setting, then select some source cells.
3. Click on left, middle and right part of the cell from 1. You will see 3 drop-down menus.
4. Try to select something from them.

**Comment by ShockwaveNN** [comment]
v7.1 has been released and this issue should be fixed
