### ISSUE TITLE
[FEATURE/QUESTION] Enter present mode programatically

### ISSUE THREAD

**Issue by thediamondor** [ONLYOFFICE/DocumentServer#1756]
for my app I need to be able to open the presentation on full-screen (present) mode from the get-go.

I am currently using Microsoft's Office Online and i want to migrate to OnlyOffice but without this feature I cannot

I went over the documentation and the API, and I did not find a way to do it. If there is a way to do it, please tell me.

**Comment by ShockwaveNN** [comment]
I think you can rename your presentation to `.ppsx` and it will be autostarted in slideshow view

But this depends of DMS you've using, I've checked with ONLYOFFICE CommunityServer - and if I upload ppsx file, open it - it instantly started in full screen slideshow

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
