### ISSUE TITLE
Spreadsheet changes comma to point

### ISSUE THREAD

**Issue by user239393** [ONLYOFFICE/DocumentServer#1757]
This issue is unique.
 I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.
Operating System
Windows 10 / 8.1 / 7

Version information
Version: 7.0.1

Expected Behavior
A cell with a formularformula should not change from decimal comma to decimal point when it was pasted as value only.

Actual Behavior
Interface Language = German
We use decimal comma ( , )

Common_decimal_separators_-_Decimal_point_and_decimal_comma

Insert a value with formular in a cell like =1,01*1234
Format it as currency (1246,34 €)
Copy this value and paste it in a new cell
Click on the symbol and choose "Paste only value" or "Value + number format"
The decimal comma is now changed to decimal point.
This leads to completely wrong values.

Zwischenablage03

Reproduction Steps
Interface Language = German

Insert a value with formular in a cell like =1,01*1234
Format it as currency (1246,34 €)
Copy this value and paste it in a new cell
Click on the symbol and choose "Paste only value" or "Value + number format"
The decimal comma is now changed to decimal point.
Additional information

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by user239393** [comment]
I didn't know you are russian, no help from my side for you murders.

**Comment by alinasafonova** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/5028d5e841123e1a79b93d549667b3ace34b266b

It will be released as v7.3.0

**Comment by DenisDeeSign** [comment]
DocumentServer and DesktopEditors v7.3.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
