### ISSUE TITLE
unable to open document after update DS to v7.1

### ISSUE THREAD

**Issue by thunderpick** [ONLYOFFICE/DocumentServer#1759]
**What is the current behavior?**
got status_info error "-81" in DS logs when trying to open document in editor
**What is the expected behavior?**
DS should show the document
**Did this work in previous versions of DocumentServer?**
yes(was 7.0.1)
**DocumentServer version:**
7.1
**Operating System:**
docker image onlyoffice/documentserver:latest(Ubuntu 20.04.4 LTS)
**Browser version:**
Chrome 101.0.4951.67(win7x64)

![image](https://user-images.githubusercontent.com/638615/169868347-a1ca4408-758c-4db8-ab45-c9f7b0d359e9.png)

**Comment by thunderpick** [comment]
But, as you can see, checkJWT step is success.

**Comment by ShockwaveNN** [comment]
But I see no other error in your logs, so let's start with JWT, you can disalbe it at all and if it still fail than JWT is not related

**Comment by thunderpick** [comment]
seems it's not JWT problem

**Comment by ShockwaveNN** [comment]
Is this happen to some specific files or for all files?

Which DMS\Integration are you using?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
