### ISSUE TITLE
Cannot open document

### ISSUE THREAD

**Issue by ManuelRighi** [ONLYOFFICE/DocumentServer#176]
Hello,
I have a problem with owncloud.
OS is Ubuntu Server 16.04 LTS.
Owncloud is 10.0.2.
OnlyOffice DocumentServer is latest.
When I open new document or existing document I receive error "Download failed"

On logs I see this:

[2017-09-28 21:06:38.807] [ERROR] nodeJS - error downloadFile:url=https://myUrl/index.php/apps/onlyoffice/download?doc=WFp5Y1Z4K2FidDBYRm5WMkx3aitETnJEQmdnWFp3cnZUeStmM0ZHQ214bz0/eyJmaWxlSWQiOjE3ODE2MCwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D;attempt=3;code:undefined;connect:undefined;(id=17816015066090282)^M
Error: Error response: statusCode:403 ;body:^M
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:243:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

**Comment by alexanderonlyoffice** [comment]
Hello @ManuelRighi, 
  
Please specify if the JWT is turned on? 

Provide us also with OwnCloud logs.

**Comment by ManuelRighi** [comment]
Hello @alexanderonlyoffice , yes is turned on.
If I turned off all works.

**Comment by alexanderonlyoffice** [comment]
@ManuelRighi, please specify where JWT is turned on: in OwnCloud or in editors. If JWT is turned on in OwnCloud, it must be enabled in editors too.

**Comment by ManuelRighi** [comment]
I have enabled on both, in onlyoffice with this guide: https://api.onlyoffice.com/editors/signature/

**Comment by alexanderonlyoffice** [comment]
@ManuelRighi, please send us OwnCloud logs, so we can detect the issue.

**Comment by ManuelRighi** [comment]
I not see any errors on owncloud.log when error occours :\
Is strange ...

**Comment by ManuelRighi** [comment]
I need particolar method (for example PUT/DELETE or others) from/to owncloud and documentserver ?

**Comment by ManuelRighi** [comment]
On apache2 access logs in owncloud server I seee these:

xxxxxx - - [29/Sep/2017:13:48:44 +0200] "POST /index.php/apps/onlyoffice/track?doc=S3oyWnFYWXJOdzYybkFYUlBCTGRKbEVVK2hqRzZEMjd4U3NKWWkxb25DVT0/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6InRyYWNrIn0%3D HTTP/1.0" 403 962 "-" "-"
xxxxxxx - - [29/Sep/2017:13:48:44 +0200] "GET /index.php/apps/onlyoffice/download?doc=T2RzSnI1anZRVU5wR0djcDRUQ1RKUDl3THdCRlc2OHp5NEwvRHpCTE5kST0/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D HTTP/1.0" 403 970 "-" "-"
xxxxxx - - [29/Sep/2017:13:48:45 +0200] "GET /index.php/apps/onlyoffice/download?doc=T2RzSnI1anZRVU5wR0djcDRUQ1RKUDl3THdCRlc2OHp5NEwvRHpCTE5kST0/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D HTTP/1.0" 403 972 "-" "-"
xxxxx - - [29/Sep/2017:13:48:46 +0200] "GET /index.php/apps/onlyoffice/download?doc=T2RzSnI1anZRVU5wR0djcDRUQ1RKUDl3THdCRlc2OHp5NEwvRHpCTE5kST0/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D HTTP/1.0" 403 966 "-" "-"

**Comment by alexanderonlyoffice** [comment]
@ManuelRighi, please follow [this instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration/server/logging_configuration.html) to set logs level to 0. Then post the full logs of OwnCloud here or send at support@onlyoffice.com

**Comment by ManuelRighi** [comment]
@alexanderonlyoffice I have enabled debug log on owncloud.
When I configure, in owncloud admin, the Document server url, secret key and others, I see this in owncloud log:

{"reqId":"wsBXFYZmxRT28oGFNmmW","level":1,"time":"September 29, 2017 14:12:21","remoteAddr":"xxxx","user":"EA4FBA34-EF05-4195-ACCB-805764DFFDF9","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"SetDocumentServerUrl: https:\/\/myFQDNonlyoffice\/"}
{"reqId":"wsBXFYZmxRT28oGFNmmW","level":1,"time":"September 29, 2017 14:12:21","remoteAddr":"xxx","user":"EA4FBA34-EF05-4195-ACCB-805764DFFDF9","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"SetDocumentServerInternalUrl: https:\/\/myFQDNonlyoffice\/"}
{"reqId":"wsBXFYZmxRT28oGFNmmW","level":1,"time":"September 29, 2017 14:12:21","remoteAddr":"xxxx","user":"EA4FBA34-EF05-4195-ACCB-805764DFFDF9","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"SetStorageUrl: https:\/\/myFQDNcloud\/"}
{"reqId":"wsBXFYZmxRT28oGFNmmW","level":1,"time":"September 29, 2017 14:12:21","remoteAddr":"xxx","user":"EA4FBA34-EF05-4195-ACCB-805764DFFDF9","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"Set secret key"}

Now, when I open new txt or docx document, after tab with onlyoffice is opened I see these errors on owncloud:

{"reqId":"f6zV37WolmKZ1E6cd4lI","level":0,"time":"September 29, 2017 14:15:57","remoteAddr":"myPCIPAddress","user":"EA4FBA34-EF05-4195-ACCB-805764DFFDF9","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/178682","message":"Open: 178682"}
{"reqId":"nTx48BjbBdqCnBCz3hUr","level":0,"time":"September 29, 2017 14:15:59","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=TmJ3QkNCMXJwUmN5QVYzeFFHOFhmb3hKbk5zMGoxTW13V2tycFB0c201Yz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6InRyYWNrIn0%3D","message":"Track: 178682 status 1"}
{"reqId":"nTx48BjbBdqCnBCz3hUr","level":1,"time":"September 29, 2017 14:15:59","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=TmJ3QkNCMXJwUmN5QVYzeFFHOFhmb3hKbk5zMGoxTW13V2tycFB0c201Yz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6InRyYWNrIn0%3D","message":"Track without jwt"}
{"reqId":"aPPd97TSXEdSroebkBXI","level":0,"time":"September 29, 2017 14:15:59","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download: 178682"}
{"reqId":"aPPd97TSXEdSroebkBXI","level":1,"time":"September 29, 2017 14:15:59","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download without jwt"}
{"reqId":"NVkwLkpXtSyMd8337yrG","level":0,"time":"September 29, 2017 14:16:00","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download: 178682"}
{"reqId":"NVkwLkpXtSyMd8337yrG","level":1,"time":"September 29, 2017 14:16:00","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download without jwt"}
{"reqId":"UfCjc6rb4pPdROtgjFCb","level":0,"time":"September 29, 2017 14:16:01","remoteAddr":"onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download: 178682"}
{"reqId":"UfCjc6rb4pPdROtgjFCb","level":1,"time":"September 29, 2017 14:16:01","remoteAddr":"4onlyofficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download without jwt"}

**Comment by alexanderonlyoffice** [comment]
@ManuelRighi, according to the log, JWT is not enabled in editors. Message: "Download without jwt".

Have you restarted the services for the config changes to take effect?

**Comment by ManuelRighi** [comment]
@alexanderonlyoffice I have restarted services on document server, I attach now logs.


{"reqId":"w2TCi9oK7H0SHf5QYxFf","level":0,"time":"September 29, 2017 14:49:40","remoteAddr":"MyPCIPAddress","user":"EA4FBA34-EF05-4195-ACCB-805764DFFDF9","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/178682","message":"Open: 178682"}
{"reqId":"gJX5kOvSAp5IzHJjEWD0","level":0,"time":"September 29, 2017 14:49:41","remoteAddr":"MyPCIPAddress","user":"FA8DE44B-08B3-4E7B-90F0-DEA8393370AC","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 Unsupported client version.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\BlockLegacyClientPlugin->beforeHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/BlockLegacyClientPlugin.php\",\"Line\":77,\"User\":\"FA8DE44B-08B3-4E7B-90F0-DEA8393370AC\"}"}
{"reqId":"pQby10b9t5DDUOgY1P3s","level":0,"time":"September 29, 2017 14:49:43","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=TmJ3QkNCMXJwUmN5QVYzeFFHOFhmb3hKbk5zMGoxTW13V2tycFB0c201Yz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6InRyYWNrIn0%3D","message":"Track: 178682 status 1"}
{"reqId":"pQby10b9t5DDUOgY1P3s","level":1,"time":"September 29, 2017 14:49:43","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=TmJ3QkNCMXJwUmN5QVYzeFFHOFhmb3hKbk5zMGoxTW13V2tycFB0c201Yz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6InRyYWNrIn0%3D","message":"Track without jwt"}
{"reqId":"3MNt9LDeF59wD1AAqrNy","level":0,"time":"September 29, 2017 14:49:43","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download: 178682"}
{"reqId":"3MNt9LDeF59wD1AAqrNy","level":1,"time":"September 29, 2017 14:49:43","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download without jwt"}
{"reqId":"Zy0cKuPFp7uTapE9AVsx","level":0,"time":"September 29, 2017 14:49:44","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download: 178682"}
{"reqId":"Zy0cKuPFp7uTapE9AVsx","level":1,"time":"September 29, 2017 14:49:44","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download without jwt"}
{"reqId":"WViHsoZ1lOtzahJFlqar","level":0,"time":"September 29, 2017 14:49:45","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download: 178682"}
{"reqId":"WViHsoZ1lOtzahJFlqar","level":1,"time":"September 29, 2017 14:49:45","remoteAddr":"onyOfficeIPAddress","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=VFlkZVpwOVdad3prTEpka3lsaHhwdnk3clI5Q0JuNjBlMk95b2lHSzJkYz0\/eyJmaWxlSWQiOjE3ODY4Miwib3duZXJJZCI6IkVBNEZCQTM0LUVGMDUtNDE5NS1BQ0NCLTgwNTc2NERGRkRGOSIsImFjdGlvbiI6ImRvd25sb2FkIn0%3D","message":"Download without jwt"}

**Comment by alexanderonlyoffice** [comment]
Please add the following section to the config file:

{
    "services": {
        "CoAuthoring": {
            "token": {
                "enable": {
                    "browser": true,
                    "request": {
                        "inbox": true,
                        "outbox": true
                    }
                }
            }
        }
    }
}

Please follow the instruction under this [link](https://api.onlyoffice.com/editors/signature/).

**Comment by ManuelRighi** [comment]
I have this:

{ "services": { "CoAuthoring": }

**Comment by agolybev** [comment]
Hi, @ManuelRighi 
It seems like the `Authorization` header missing in request while proxing by apache.
The same problem discused [here](https://stackoverflow.com/questions/26475885/authorization-header-missing-in-php-post-request) and [here](https://stackoverflow.com/questions/37158714/enable-apache-http-authorization-header).

**Comment by ManuelRighi** [comment]
Hi @agolybev , Authorization in front of DocumentServer (I have nginx) ? Or in fron of owncloud (I have apache) ?

Thanks

**Comment by ManuelRighi** [comment]
Exactly I have owncloud with apache2 (no proxy in front).
document server is on nginx with HTTP but in front I have nginx reverse proxy where I have SSL offloading.

**Comment by agolybev** [comment]
I think, apache2 in front of owncloud strips  Authorization headers from documentserver requests.

**Comment by ManuelRighi** [comment]
Thanks @agolybev , I have resolved :)
I put Authorization header in apache (owncloud), and now works ;)

<VirtualHost>
    # ...
    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
    # ...
</VirtualHost>

**Comment by agolybev** [comment]
Hi @ManuelRighi, It's good news!

**Comment by benhartwich** [comment]
Hi,

I´ve the same issue and I´m using nginx. I´ve set the authorization header: fastcgi_pass_header Authorization; and I´ve set the secret at my config.php at nextcloud. I´m still getting the same error. What can I do?
