### ISSUE TITLE
Can Only Office support iterative calculation in the future?

### ISSUE THREAD

**Issue by Floatlen** [ONLYOFFICE/DocumentServer#1762]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
do not support ，Some cells show error
![1653460884164_EC188F63-BC9C-4932-9EEA-8ED60076D943](https://user-images.githubusercontent.com/42170165/170197021-c9b39cba-342e-4e0d-91cf-051ef637c333.png)

**What is the expected behavior?**
![lQLPJxZXTSKEDA7NAobNAziw4tQzavRdDtYCkBnMbID5AA_824_646](https://user-images.githubusercontent.com/42170165/170197317-f2fa5b0a-d9cf-47bf-98b0-c881fffb4d7b.png)

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
7.1.0

**Operating System:**
win10

**Browser version:**
chrome 101.0.4951.67

**Comment by ShockwaveNN** [comment]
Hi, could you attach example file with such values?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by jamesdeluk** [comment]
Any update on this?

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed in [version 8.2](https://github.com/ONLYOFFICE/DocumentServer/blob/master/ROADMAP.md#spreadsheet-editor-1).
Feel free to comment or reopen it if you got further questions.

**Comment by jamesdeluk** [comment]
Oh, thanks! Where's the setting for it, as I can't find it? Simply trying it gives #NUM!s
