### ISSUE TITLE
Add full sentence for source strings

### ISSUE THREAD

**Issue by Aikatsui** [ONLYOFFICE/DocumentServer#1765]
**What is the current behavior?**

We noticed some source strings with half contents (or half sentences) and those sentences cannot translate to any or most non SVO languages. If we tried to modify the sentence and translate it somehow but it still express uncomfortable message to user. 

Some examples below,
- {{category}} users can
- Access to {{product}} module is given to
- For solving technical issues, use
- Support is no longer available for your license since

E.g. **For solving technical issues, use {{name}}**; when we translate it to some non svo language then it need to write as this.

**Technical issues | solving | for | {{name}} | use**

I guess above example helps to understand the problem.

Furthermore, non SVO countries also have locally developed office suites with local language then when compare with onlyoffice; although not opensource, that products are more user friendly and feel interested to use 

**What is the expected?**

Check and identify such source strings and add full sentence

https://translate.onlyoffice.com/

**Comment by ShockwaveNN** [comment]
Hi, I'm sorry I don't think I can help somehow with translate.onlyoffice.com system, it's completely out of my job responsible

I think it's better to contact your supervisor who did provide you access to this service

**Comment by Aikatsui** [comment]
> Hi, I'm sorry I don't think I can help somehow with translate.onlyoffice.com system, it's completely out of my job repsonsibilites

That's not a problem related to translate.onlyoffice.com then developers will have to search in code repositories and identify those strings and apply appropriate fixes. i shall consider to let them know.

**Comment by ShockwaveNN** [comment]
I'm very little familiar with translate.onlyoffice.com since I've no access to it at all )

So it's better to contact person who give you access and it will be decided by them that to do next
