### ISSUE TITLE
Version history spinner continuously loading on React app

### ISSUE THREAD

**Issue by new-ranger** [ONLYOFFICE/DocumentServer#1768]
**Do you want to request a *feature* or report a *bug*?**
need help

If I use docEditor as a react state then version history spinner continuously loading. Not able to see version history list on click of 'version history' menu.

const contentEditor = ({ person_Id }) => {
  const [config, setConfig] = useState(null);
  const [docEditor, setDocEditor] = useState(null);

  useeffect(() => {
    const onRequestHistoryData = (event) => {
      var version = event.data;
      docEditor.setHistoryData({
        changesUrl: "https://example.com/url-to-changes.zip",
        fileType: "docx",
        key: "Khirz6zTPdfd7",
        previous: {
          fileType: "docx",
          key: "af86C7e71Ca8",
          url: "https://example.com/url-to-the-previous-version-of-the-document.docx",
        },
        url: "https://example.com/url-to-example-document.docx",
        version: version,
      });
    };

    const onRequestHistory = () => {
      docEditor.refreshHistory({
        currentVersion: 2,
        history: [
          {
            changes: changes,
            created: "2010-07-06 10:13 AM",
            key: "af86C7e71Ca8",
            serverVersion: serverVersion,
            user: {
              id: "F89d8069ba2b",
              name: "Kate Cage",
            },
            version: 1,
          },
        ],
      });
    };

    const tempconfig = {
      events: {
        onRequestHistory,
        onRequestHistoryData,
      },
    };
    setConfig(tempconfig);
  }, [person_id]);

  useEffect(() => {
    if (docEditor) {
      docEditor.requestClose();
      docEditor.destroyEditor();
      setDocEditor(null);
    }
    if (config) {
      setDocEditor(new DocsAPI.DocEditor("placeholder", config));
    }
  }, [config]);
};

I can see and edit the document. only version history is not working on click of menu option.

**Comment by ShockwaveNN** [comment]
I am sorry, but I don't think we have enough knowledge to debug a React code, so if anyone has any experience - please welcome to help here

**Comment by new-ranger** [comment]
It got fixed. Thanks!
