### ISSUE TITLE
sendDataWarning(conn, msg) will trigger the error on web page

### ISSUE THREAD

**Issue by RainyGao-GitHub** [ONLYOFFICE/DocumentServer#1779]
**Do you want to request a *feature* or report a *bug*?**
feature
I want to send a warning message to user, but sendDataWarning will trigger error “File can not be accessed”
**What is the current behavior?**
sendDataWarning(conn, msg) will trigger error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I wish it just show the warning message which I sent on server side.
But I did not find such interface to send the warning message

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Hi, I'm not aware of `sendDataWarning` method at all and in which part of project it can be called

Is it documented anywhere?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
