### ISSUE TITLE
Excel table data validation cells, when copying and then pasting, the same series of data validation will be invalid

### ISSUE THREAD

**Issue by PlatonaBoy** [ONLYOFFICE/DocumentServer#1781]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Excel table data validation cells, when copying and pasting, the same series of data validation will fail
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![GIF 2022-6-3 16-45-58](https://user-images.githubusercontent.com/80155818/171821292-b4246c81-0fa2-4094-bd76-74fb9546910a.gif)

**What is the expected behavior?**
Excel table data validation cells, when copying and pasting, the data validation of the same series will not fail
**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
7.1
**Operating System:**
win10
**Browser version:**
edge  101.0.1210.53

**Comment by alinasafonova** [comment]
Hello, @PlatonaBoy

This is known issue - 56222 in our private issue tracker.
Thank you for report.

**Comment by alinasafonova** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/eac07a18223e102b612300d0e064b6a4b1f0f9ce

It will be released as v7.2.0
