### ISSUE TITLE
Hiding protect tab not working in the editor?

### ISSUE THREAD

**Issue by bipana50** [ONLYOFFICE/DocumentServer#1793]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
even when the protect config is false, protect tab is still showing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-> use the JS onlyoffice API for doc editor, pass config where config.document.permissions.protect = false 

the config is:

```
document: {
			title: doc.title,
			url: `${onlyOfficeConfig.zegalServer}/download?docId=${doc._id}&Auth=${authInfo}`,
			fileType: 'docx',
			key: doc._id,
			info: {
				owner: doc.owner.email
			},
			permissions: {
				chat: false,
				comment: true,
				copy: false,
				download: false,
				edit: true,
				print: false,
				modifyFilter: false,
				modifyContentControl: false,
				review: false,
				protect: false
			}
		},
```

**What is the expected behavior?**
-> the protect option the the file tab should be hidden

**DocumentServer version:** - Document Editor version 6.4.0

**Operating System:** Linux

**Browser version:** Google Chrome

**Comment by ShockwaveNN** [comment]
Hi

> DocumentServer version: - Document Editor version 6.4.0

I think this may be the reason, this version is very old and probably this option is not supported back there. Could you recheck it on latest stable v7.1.1

**Comment by bipana50** [comment]
Hey, yeah in version 7.0.1 its working, tested locally

We are using this ` Open Source Online Office Suite : Latest Version: ONLYOFFICE Docs 7.0.0- Ubuntu 20.04` from aws.
https://aws.amazon.com/marketplace/pp/prodview-6m6ejps4kp6d6
Not sure why does this have an 6.4.0 editor version instead of the updated version

**Comment by ShockwaveNN** [comment]
> https://aws.amazon.com/marketplace/pp/prodview-6m6ejps4kp6d6

This is not our official marketplace item, not sure even that it is

Ours is [this one](https://aws.amazon.com/marketplace/pp/prodview-m47ijkzvv34ea) and it's v7.1.1

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
