### ISSUE TITLE
Can't add fonts to ONLYOFFICE Docs

### ISSUE THREAD

**Issue by Zoranner** [ONLYOFFICE/DocumentServer#1795]
**Do you want to request a *feature* or report a *bug*?**
I tried this ([https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx)) in docker container, cleared the browser cache, but there is no change in the font list, is the new version any different? 

**DocumentServer version:**
7.1.1 with docker

**Operating System:**
CentOS 7

**Browser version:**
Edge 102.0.1245.41

**Comment by ShockwaveNN** [comment]
Are you sure you've cleaned a cache?

Are there any errors in logs?

Could you attach fonts so I can check it on my instance

**Comment by ShockwaveNN** [comment]
I've run documentserver like this:

```
docker run -itd -p 80:80 -v ~/sources/DocumentServer-Data:/usr/share/fonts/truetype/custom onlyoffice/documentserver
```

And seems that this document is rendered fine and the fonts are in the list of fonts

![image](https://user-images.githubusercontent.com/668524/175028962-77eae1d7-b4cb-449f-bc8c-7eee52dae006.png)

**Comment by ShockwaveNN** [comment]
With Chinese interface language it's fine for me too:
![image](https://user-images.githubusercontent.com/668524/175243453-08158ac0-a943-45e1-af53-f28a203b937e.png)

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue
