### ISSUE TITLE
Bug: Image Exif data is not processed, resulting in rotated images on export

### ISSUE THREAD

**Issue by yamanq** [ONLYOFFICE/DocumentServer#1796]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Images with rotation information in the exif data are not rotated upon export. All other document processors I tested (LibreOffice, Microsoft Word) do not interpret exif data, so the image appears rotated in the document. This is also the case when exporting to PDF.

This is important because phone camera images typically rotate images using the exif metadata.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
For this demo, I have created 2 test images:
## test.jpg: This is a file with no exif data.
![test](https://user-images.githubusercontent.com/8166212/174218683-23f2321d-7de6-4aef-8f86-8d20ed58cdce.jpg)

Internal representation (screenshot of GIMP):
![image](https://user-images.githubusercontent.com/8166212/174219028-b4e4205a-1882-4e43-a977-006393003b83.png)

## test-rotate-with-exif.jpg: This file notates rotation using its exif data.
![test-rotate-with-exif](https://user-images.githubusercontent.com/8166212/174218690-a5f1c099-b1ba-49b4-a67c-517924b17c0f.jpg)

Internal representation (screenshot of GIMP):
![image](https://user-images.githubusercontent.com/8166212/174219000-26bad925-6d92-45cf-bc07-006f25e48529.png)
Also has the following exif metadata: `Orientation                     : Rotate 90 CW`

## Reproduction Steps
1. Insert both images into a docx document
![image](https://user-images.githubusercontent.com/8166212/174218651-d4f72ccc-9e2a-4e88-96fd-88cb4e206bf5.png)
2. Export the docx to any format (docx, pdf, odt)
3. Open the exported file using the viewer/editor of your choice
4. Observe screenshots below

docx opened in LibreOffice (issue also occurs in Microsoft Word):
![image](https://user-images.githubusercontent.com/8166212/174219723-d5f65db6-3302-4583-8321-6fae84f08af5.png)

PDF opened with Firefox built-in pdf renderer (issue also occurs in Okular):
![image](https://user-images.githubusercontent.com/8166212/174219646-65030946-1d72-4fa7-9d89-7d85e73426d8.png)

**What is the expected behavior?**
Images should be cleared of exif data and rotated by the DocumentServer. This serves 2 purposes:
1. Fixes this issue
2. Privacy. Documents shared with others will not include all exif data of the image, as this contains geolocation, creation date, and extensive information on the phone/camera that took the image.

**Did this work in previous versions of DocumentServer?**
Not sure.

**DocumentServer version:**
7.1.1

**Operating System:**
Linux

**Browser version:**
Firefox 101.0

### Related issue
This has the same root cause as #1192. In the example document shared [there](https://github.com/ONLYOFFICE/DocumentServer/issues/1192#issuecomment-805565675), both images contain Orientation exif data. Libreoffice and other document processors do not read this data while onlyoffice does, so it results in an incorrect orientation.

**Comment by TatianaKirillova** [comment]
Hello, [@](https://github.com/michal-barteczko)[yamanq](https://github.com/yamanq)
Thank you for report. I can confirm - this is know bug, issue 46717 in our private issue tracker.

**Comment by TatianaKirillova** [comment]
Hello @yamanq ! I have good news: the problem has been fixed by a [commit](https://github.com/ONLYOFFICE/server/commit/68ac6ec1614f1bb558279f2f97d9119f808595ce
) and is no longer reproducible in version 8.0.1.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
