### ISSUE TITLE
Version changed problem

### ISSUE THREAD

**Issue by liangzhengai** [ONLYOFFICE/DocumentServer#18]
Hello.
I download 3.0 source code and run it in my computer.
When I upload existing file or open demo.docx, it renders it and enter to edit mode successfully.
I modify the docx such as entering some words and then close the web browser.

and then I reopen the browser and link to that docx file.
But it shows "Version changed" error message.
and i can't edit the docx file any more.

Even though I reload it several times, and tried other files, the prog shows the same error.

If u solve this problem, it is very thankful.

Thank you.

**Comment by ibnpetr** [comment]
Hello
>I modify the docx such as entering some words and then close the web browser.

Please note that every time you close the session the "key" [parameter] (https://api.teamlab.info/editors/basic) should be changed
BTW the file can be opened in a viewer even with the same key identifier.
But you should change the key if you are going to edit the file.
