### ISSUE TITLE
BUG>> "Jumping" formulas

### ISSUE THREAD

**Issue by realkot** [ONLYOFFICE/DocumentServer#180]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
DEMO:
![jumping formulas](https://user-images.githubusercontent.com/24507273/31717274-e5de8442-b413-11e7-9ae8-0482c53c1012.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
watch the demo

**What is the expected behavior?**
formulas works as expected... formulas doesn't changed in cell

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

Latest avaible build.
Ubuntu 16.04 (x64).

**Comment by ShockwaveNN** [comment]
Hi, could you attach original file

**Comment by realkot** [comment]
@ShockwaveNN 

[Fin September.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1394589/Fin.September.xlsx)

**Comment by ShockwaveNN** [comment]
Issue still actual, issue 36102 in our private bug tracker, forgot to specify it here.
Currently we cannot fix it since we do not diffirintiate cut and copy opertaion.
But may fix it in future

**Comment by ShockwaveNN** [comment]
I think we've fixed issues long time ago, at version 5.6, so I think it's safe to close this issue, sorry we forgot

I'll close it now, but if you got any question related to this issue - please ask here, or create new issue
