### ISSUE TITLE
characters with accents are not displayed in bold (spreadsheet only)

### ISSUE THREAD

**Issue by go-ten** [ONLYOFFICE/DocumentServer#1800]
Hello,

Since the last version of Document Server (7.1.1.23), characters with accents (or numbers) are not displayed in a spreadsheet when they are in bold.

I use the latest version of google Chrome (102).

Any Ideas ?

Thks

![Screenshot 2022-06-21 10 56 21](https://user-images.githubusercontent.com/47599241/174760040-d893b2ec-8cbf-4f1e-aaf7-2b7d06f7d49a.png)

**Comment by ShockwaveNN** [comment]
Hi, could you attach this file as example?

**Comment by go-ten** [comment]
Hi, this is this File

[Nouveau classeur.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/8947974/Nouveau.classeur.xlsx)

**Comment by go-ten** [comment]
the problem is obviously with the police Carlito

**Comment by go-ten** [comment]
Hi, Debian 11 and this is the docker version

**Comment by TatianaKirillova** [comment]
The problem is also not reproducible on your OS. Do you just type text and make it bold?
