### ISSUE TITLE
error when upload large excel file on onlyoffice

### ISSUE THREAD

**Issue by DungNg013** [ONLYOFFICE/DocumentServer#1810]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
My GG Sheet File have 12 sheets, when upload on Onlyoffice i just have only 08 sheets, loss 04 sheets.

**What is the expected behavior?**
I expected have 12 sheets  on Onlyoffice when upload Sheet File

**Did this work in previous versions of DocumentServer?**
i did not check that

**Operating System:**
DocServer run on ubuntu18

**Comment by ShockwaveNN** [comment]
Hi, we need this file and information about which version of DocumentServer you're using (you can check `About` tab)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
