### ISSUE TITLE
File size exceeds the limitation

### ISSUE THREAD

**Issue by codesmaker** [ONLYOFFICE/DocumentServer#1812]
Hi,

I have OnlyOffice Document Server integrated with Nextcloud. When I try to open big document files in Nextcloud (~70 MB), I get the following error:
![image](https://user-images.githubusercontent.com/6999196/176678659-15f8f9a3-b93a-4f9a-a756-565b44ffd2e9.png)

Here is what I have in the 'default.json' file:

"FileConverter": {
                "converter": {
                        "maxDownloadBytes": 314572800,
                        "downloadTimeout": {
                                "connectionAndInactivity": "2m",
                                "wholeCycle": "2m"
                        },
                        "downloadAttemptMaxCount": 3,
                        "downloadAttemptDelay": 1000,
                        "maxprocesscount": 1,
                        "fontDir": "null",
                        "presentationThemesDir": "null",
                        "x2tPath": "null",
                        "docbuilderPath": "null",
                        "docbuilderAllFontsPath": "null",
                        "docbuilderCoreFontsPath": "",
                        "args": "",
                        "spawnOptions": {},
                        "errorfiles": "",
                        "streamWriterBufferSize": 8388608,
                        "maxRedeliveredCount": 2,
                        "inputLimits": [
                                {
                                "type": "docx;dotx;docm;dotm",
                                "zip": {
                                        "uncompressed": "100MB",
                                        "template": "*.xml"
                                }
                                },
                                {
                                "type": "xlsx;xltx;xlsm;xltm",
                                "zip": {
                                        "uncompressed": "1000MB",
                                        "template": "*.xml"
                                }
                                },
                                {
                                "type": "pptx;ppsx;potx;pptm;ppsm;potm",
                                "zip": {
                                        "uncompressed": "100MB",
                                        "template": "*.xml"
                                }
                                }
                        ]
                }

I have no errors in the '/var/log/onlyoffice/documentserver/converter/out.log' or '/var/log/onlyoffice/documentserver/converter/err.log'. Any idea what's causing it?

The OnlyOffice Document Server version is 7.1.1-23 runs on Ubuntu 20.04.

Thanks a lot for your help.

**Comment by ShockwaveNN** [comment]
I think you need to change `nginx` 

See [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/354#issuecomment-824678415)

**Comment by codesmaker** [comment]
I'm afraid that I can't because it contains some personal data. I'll try to find a big generic Excel file.

**Comment by ShockwaveNN** [comment]
Also my collegues inform me that if file is not opened because of limit - you should try to reupload this file once again after limits change

This is some kind of `nextcloud-like` feature, that it's store status of file in DB, so you need a new file

or you could check DocumentServer integrated example (enabled at `http://docserver/welcome`) and see if via example this file opens fine. In that case - it's not DocumentServer fault

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
