### ISSUE TITLE
Saving the document has failed - All modification lost

### ISSUE THREAD

**Issue by jlemangarin** [ONLYOFFICE/DocumentServer#1814]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Saving a document has failed, one of our customers's CISO (A french town) has lost all their modifications.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Our customer have made some modifications and closed the document, I'm asking our customer if saving this document again works

**What is the expected behavior?**
//

**Did this work in previous versions of DocumentServer?**
//

**DocumentServer version:**
7.1.0

**Operating System:**
CentOS 7

**Browser version:**
//

**Logs:**

```
18:29:29,782 DEBUG [org.alfresco.repo.jscript.RhinoScriptProcessor.calls] [http-nio-8080-exec-87] updateOnlyofficeHash.get.js End 1 ms
18:29:29,791 DEBUG [com.parashift.onlyoffice.CallBack] [http-nio-8080-exec-16] Received JSON Callback
18:29:29,792 DEBUG [com.parashift.onlyoffice.CallBack] [http-nio-8080-exec-16] {
   "actions": [{
      "type": 0,
      "userid": "XXX"
   }],
   "key": "37100dXXXm5uxtk7wi",
   "lastsave": "2022-06-30T16:29:11.000Z",
   "notmodified": false,
   "status": 3,
   "users": ["XXX"]
}
18:29:29,795 ERROR [com.parashift.onlyoffice.CallBack] [http-nio-8080-exec-16] ONLYOFFICE has reported that saving the document has failed
18:29:29,801 INFO  [com.parashift.onlyoffice.CallBack] [http-nio-8080-exec-16] removing prop
18:29:29,955 DEBUG [org.alfresco.repo.jscript.RhinoScriptProcessor] [http-nio-8080-exec-16] Imports resolved, adding resource '_root
18:29:29,965 DEBUG [org.alfresco.repo.jscript.RhinoScriptProcessor.calls] [http-nio-8080-exec-16] workspace://SpacesStore/0a1XXX9dc25 Start
```

```
[2022-06-30T18:29:29.563] [ERROR] nodeJS - stdout (id=37100XXXtk7wi_1667):
[2022-06-30T18:29:29.564] [ERROR] nodeJS - stderr (id=37100d3XXX7wi_1667):
[2022-06-30T18:29:29.564] [ERROR] nodeJS - ExitCode (code=80;signal=null;error:-80;id=37100XXXwi_1667)
```

**Comment by jlemangarin** [comment]
Hello @ShockwaveNN 

Sorry for the delay, we didn't find any other logs unfortunately. 

Also there was no temporary file stored in the server and we can't find a way to reproduce the issue..

I will contact the support and see what they think about it.

Thanks for your feddback !

**Comment by ShockwaveNN** [comment]
Thanks, I'll close that issue in that case until I'll hear some news
