### ISSUE TITLE
Spreadsheet Editor: Vertical text width measurement not working

### ISSUE THREAD

**Issue by voegtlel** [ONLYOFFICE/DocumentServer#182]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
The content size of a cell with orientation "rotate text up" or "rotate text down" is measured in horizontal direction for truncating content by "###". Also for double clicking the column width handle (to resize the column to its content) will use the vertical content size as measurement.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In a new document set the orientation of a cell to "rotate text up" or "rotate text down" and the content type *not* to "text" (e.g. to date or number). Then make the cell high enough to contain the content, but make it only so wide to contain the font height. The content will be replaced by "##" but should actually be visible.

This is useful e.g. for displaying a Date on the top and inserting X's for participations on that date. The column could thus be smaller than the full date's text size.

**What is the expected behavior?**
The content truncation size is supposed to be measured by cell height if content is rotated by 90 degrees (or by the minimum of both if only rotated by 45 degrees).

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
Spreadsheet Editor 4.4.3, client running on Chrome/Windows. Didn't check if it worked on a previous version.

**Comment by trofim24** [comment]
We fixed this problem in version 6.0.0
