### ISSUE TITLE
Wopi integration real-time editing problem

### ISSUE THREAD

**Issue by 1340896123** [ONLYOFFICE/DocumentServer#1820]
我实现了WOPIHOST,并且在我的应用程序中也可以编辑文档了,但是在实时编辑中,并不会吧编辑后的文档马上发送回WOPIHOST,而是需要关闭编辑页面并且还需要等待20多秒才会把编辑后的文档发送回WOPIHOST,请问有什么办法文档编辑后就马上返回WOPIHOST,而不需要等待?

**Comment by ShockwaveNN** [comment]
Hi, we only understand english so please explain what you mean in english

**Comment by 1340896123** [comment]
I have implemented wopihost and can edit documents in my application. However, in real-time editing, the edited document will not be sent back to wopihost immediately. Instead, I need to close the editing page and wait more than 20 seconds before sending the edited document back to wopihost. Is there any way to return to wopihost immediately after document editing without waiting?
