### ISSUE TITLE
Missing imported/embedded objects when viewing by direct URL

### ISSUE THREAD

**Issue by nautilux2** [ONLYOFFICE/DocumentServer#1828]
[BUG]

Missing imported/embedded objects when viewing by direct URL while fully displayed in MS Excel

Because my docs are private so I can not provide an exact file. But you guys can try to insert a bitmap by going to Insert -> Object and picking any bitmap you want, save and preview in only office and it's gone
When clicking on the original object in MS Excel, the formula bar shows `=EMBED("PBrush","")`

Imported/embedded objects should be displayed

DocumentServer version: 7.1.1 Docker Community

Operating System: Windows 10

Browser version: FF version 102.0 (64-bit)

**Comment by LuckySpecialist** [comment]
Hi @nautilux2, we don't have support for working with embedded objects, but we also don't delete them when working in our editor.
I checked this on the latest version of Desktop Editor 7.4.1 and the objects remain in the file.

**Comment by Rita-Bubnova** [comment]
So I close this issue. Feel free to comment or reopen it if you got further questions.
