### ISSUE TITLE
While opening version history, it gets stuck in ` opening document ` and unknown error occurs

### ISSUE THREAD

**Issue by bipana50** [ONLYOFFICE/DocumentServer#1830]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
version history not loading document

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I am passing the required history data via events as mentioned here ` https://api.onlyoffice.com/editors/history ` but getting 410 error here in this endpoint ` /cache/files/62d4d6a1a1b81d498844beaa_2087/changes.zip/changes.zip?md5=gqK7Jt0b3zJUM5hC3OzLNQ&expires=1658118125&filename=changes.zip `

[screen shot link](https://ibb.co/tJ79f3k)

**What is the expected behavior?**
the document should have downloaded

**DocumentServer version:**
Document Editor version 6.4.0

**Operating System:**
Linux/Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Hi, my first advice is to update DocumentServer to the latest stable, v6.4.0 is rather old and we currently do not support it

Another idea - this may be somehow related to cache cleanup, 410 is gone error and maybe cache cleanup was triggered for some reason, but not sure

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
