### ISSUE TITLE
Problem to open xls documents

### ISSUE THREAD

**Issue by aukfood** [ONLYOFFICE/DocumentServer#1832]
Hello, we have some problems to open xls documents with onlyoffice. 

![image](https://user-images.githubusercontent.com/67263702/174578519-602ef4c6-13e6-40fe-a073-5621ef52fc3f.png)

Headers of the file : 
```
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="ProgId" 
content="Excel.Sheet"><meta name="Generator" content="Microsoft Excel 11">
```

Do you have somme ideas ?

Thanks

**Comment by ShockwaveNN** [comment]
Hi, sorry for long response, this issue should be filed at another repo, so we'll handle it faster

This seems like xls file, which is actually HTML file, we got a lot of troubles with those one and constantly trying to improve it's detection

So my first question -are you using latest stable version of DocumentServer v7.1.1? Because each release we've make a little improvements in handling of those files

And if you using latest version - could you check opening of this file in integrated example located at `http://docserver_url/welcome` and see if this file opens OK without Nextcloud?

**Comment by aukfood** [comment]
Hello, yes the version is 7.1.1

I test opening file with example plateform and document is empty

**Comment by ShockwaveNN** [comment]
> document is empty

Should it be empty? Could you attach this file?

**Comment by aukfood** [comment]
No if I open the file with @ShockwaveNN I'm so sorry I test the wrong file. Why the good one I have this error in exemple plateform 
```
Upload error: Error occurred in the ConvertService: Error document request
Please select another file and try again. 
```

I'll ask to user if I could send you the file

**Comment by ShockwaveNN** [comment]
Thanks, maybe they can remove sensitive data, since we really want to look at that file )

**Comment by aukfood** [comment]
yes users are in holidays i wait a reply

**Comment by aukfood** [comment]
Hello, this file
[Ademe.xls](https://github.com/ONLYOFFICE/DocumentServer/files/9196176/Ademe.xls)

**Comment by ShockwaveNN** [comment]
@aukfood I don't think it's a xls file, it plain old html file

![image](https://user-images.githubusercontent.com/668524/181193117-4056ffca-a589-49ba-9382-ecebda417ed2.png)


Could you rename it to Ademe.html and open? It open s fine for me:
![image](https://user-images.githubusercontent.com/668524/181193217-cbc266c8-282a-4c8b-b77a-52a485976381.png)

**Comment by aukfood** [comment]
ah ok so i don't understand why client application generate this file in xls and not in html

**Comment by ShockwaveNN** [comment]
I don't know either, seems that problem is that since it's has xls extension - we try to open in with SpreasheetEditor, but it fail, since it's not even a table

But if you change extension to HTML it will be opening with DocumentEditor - and it succed

**Comment by aukfood** [comment]
ye i done the same test ! i'll go to inform my client about that.

Thanks for you're time
