### ISSUE TITLE
Use nginx proxy_ pass proxy forwarding port 8215

### ISSUE THREAD

**Issue by libing1998** [ONLYOFFICE/DocumentServer#1833]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
I want to use nginx proxy_ pass proxy forwarding port 8215
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
My nginx configuration is as follows：
```shell
 location /onlyoffice/ {
    proxy_pass http://ip:8215/;
 }
```
but the url error：
```
/cache/files/xxx/Editor.bin/Editor.bin?md5=Foh9zXMGtsdEYoBt4RhsRA&expires=1661304504&filename=Editor.bin
```
**What is the expected behavior?**
Use url:8216/onlyoffice/ instead of 8215 to access

**Comment by fenghw2087** [comment]
缺的东西挺多的，报什么错就代理什么，因为不是所有资源路径都是在onlyoffice下
有/cache  /doc  /fonts  /sdkjs/common/Images/*.png

**Comment by fenghw2087** [comment]
前置代理是非根目录域名吗？那需要改的东西就多了
documentSever里有个nginx，会把所有资源重定向至根目录，前置nginx就访问不通了
除了这个nginx，部分资源的路径是sdk自己拼接的，默认也是拼根目录的，这个cache就是sdk自动发起的链接，你需要修改sdk代码
最后一点就是回调里的文档地址，也是拼接的根目录，需要自己修改

最简单的解决方案是，直接部署在根域名下

**Comment by wideweide** [comment]
> 部分资源的路径是sdk自己拼接的，默认也是拼根目录的，这个cache就是sdk自动发起的链接，你需要修改sdk代码 最后一点就是回调里的文档地址，也是拼接的根目录，需要自己修改

must to modify the source code? is there method just to modify the config file?

the requirement is usefult for me too, for the port is not enough,and is safer to open less port

**Comment by igwyd** [comment]
Hello, @libing1998, as @fenghw2087 rightly noted integrated nginx is used by many services in the documentserver. So if you need to change the port, we have guides on how to do this in different distributions [here](https://helpcenter.onlyoffice.com/installation/docs-index.aspx). If you need to redirect the address to a virtual directory, you can use an external proxy server, we have several [examples](https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx) for setting up.

**Comment by Rita-Bubnova** [comment]
I'll close this issue. Feel free to comment or reopen it if you got further questions.
