### ISSUE TITLE
OnlyOffice Desktop Editor for MacOS ignores Option Key on german keyboard layout

### ISSUE THREAD

**Issue by mhoffmann75** [ONLYOFFICE/DocumentServer#1834]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.1.1

### Expected Behavior

Pressing Option-L should print "@" , Option-E should print "€" and Option-shift-7 should print "\" on german apple keyboard.

### Actual Behavior

All Option-something Characters are ignored in OnlyOffice for MacOS and not added in text oder tables.
This happens with builtin keyboard or external bluetooth keyboard (both german layout).

All other Apps on Macbook work as expected.

### Reproduction Steps

Start OnlyOffice 7.1.1 on MacOS. Create new text document. Start writing and press one of those characters that can only be accesses via option key.

### Additional information

Same result for left and right Option key.

**Comment by istvnurbn** [comment]
I have a similar issue on macOS as well with ONLYOFFICE 7.1.1. I have Hungarian keyboard and while Option + KEY mostly work, when I try to input something that requires Option + Shift + KEY (like * which is Option + Shift + ,) nothing happens.

**Comment by Gingetsu** [comment]
Hello, @istvnurbn. Yes, this is the same issue as in the original, and it's still not solved, sorry. Thank you for report.

**Comment by cmahnke** [comment]
I'm using 7.1.1, can you please give an estimate when this will be fixed? It's very annoying...

**Comment by ShockwaveNN** [comment]
@cmahnke Sorry, we (QA team) cannot provide any timeframe for that. If you really need this issue to be fixed - please contact sales@onlyoffice.com

**Comment by mhoffmann75** [comment]
It seems that this has been already fixed, since 7.2.1 works for me with german layout.
