### ISSUE TITLE
Nextcloud + DocumentServer: Cannot print or export custom added fonts

### ISSUE THREAD

**Issue by pizzidellamaremma** [ONLYOFFICE/DocumentServer#1836]
Bug:
I'm using Nextcloud 24.0.3 (latest version available) and DocumentServer 7.1.1 (never used before) on Docker.
I add some fonts I need, Onlyoffice works well but when I print it or export to PDF the text with custom fonts it's not printed, even in preview. 
With native fonts it works well.
Is it a Nextcloud problem or is it Onlyoffice not passing custom fonts when exporting?

New sheet with custom font:
![image](https://user-images.githubusercontent.com/39835713/180787069-6308a6d7-007b-47d6-9506-23f6a5bd1d2b.png)

Ctrl+P preview:
![image](https://user-images.githubusercontent.com/39835713/180787284-1d2bacd0-04a0-4935-86f7-be918244faa4.png)

This one is the PDF exported from Onlyoffice menu:
![image](https://user-images.githubusercontent.com/39835713/180787793-c4025ee2-5a72-4ce3-b8df-19e8ae9e47ac.png)

**Comment by ShockwaveNN** [comment]
Is this problem only for this specific font or for other default fonts as well?

**Comment by pizzidellamaremma** [comment]
As written before native fonts are working, the problem is with custom fonts.

**Comment by ShockwaveNN** [comment]
1. Is this problem happens with EVERY custom font or only for specific ones?
2. Is there some proxy setup or nextcloud and DocumentServer are on different hosts\container
3. Is there any errors in DocumentServer logs `/var/log/onlyoffice/`

And please attach this `Raleway black` font file

**Comment by ShockwaveNN** [comment]
![image](https://user-images.githubusercontent.com/668524/180950367-0bbf7f06-fdcf-4725-9314-801967596709.png)

I've checked your font and for me font is rendering

As far as I remember - seems we got some similar issue and it was something to do with not very correct reverse proxy setup, but I don't remember any details

We can try to check this problem without Nextcloud/proxy via opening `http://docserverurl/welcome` and creating file in integrated test example and check if it will print there too

**Comment by pizzidellamaremma** [comment]
I checked on the example page. Both, PDF export and chrome print preview, do the exact same things as before (not load custom fonts, native fonts only).
Document: (first line Arial, second line custom font)
![image](https://user-images.githubusercontent.com/39835713/181066258-97656060-b580-4fd1-91db-9575c050051d.png)
PDF export:
![image](https://user-images.githubusercontent.com/39835713/181066341-c59f9fa8-724d-4796-a91e-70031ae1a742.png)
Print preview:
![image](https://user-images.githubusercontent.com/39835713/181067128-b3b3ad75-029b-4ece-946b-05519717dcc6.png)


I checked from external and internal url, they do the same.

**Comment by ShockwaveNN** [comment]
Ok, I think it's proxy problem, something is wrong because on my setup everything is fine

Could you setup simplest docker setup like `docker run -itd -p 80:80 onlyoffice/documentserver` on another host, check that this version is working fine with your host (like mine do) and after that compare proxy settings and find out which option make this change

**Comment by pizzidellamaremma** [comment]
I'm trying to run the onlyoffice/documentserver image with the command you gave me but seems the nginx is not hosting the web page...

EDIT: I've added the `ONLYOFFICE_HTTPS_HSTS_ENABLED` environment variable on my docker compose, recreated the server and now the situation is changed. Some custom fonts are correctly represented, other parts are not but it's random. The same font is showing up in some places and not in others... 
When I have time I'll retry with a new fresh server.

**Comment by ShockwaveNN** [comment]
> I'm trying to run the onlyoffice/documentserver image with the command you gave me but seems the nginx is not hosting the web page...

There is definitely some incorrect with your setup, since it's *the* simplest run command can be, maybe some proxy by default applying for our service for some reason and messing up stuff

**Comment by pizzidellamaremma** [comment]
I think I resolved the problem. Fonts were in the wrong folder. I placed them in `/usr/share/fonts` but the right folder is `/usr/share/fonts/truetype/custom`.

Thank you all!
