### ISSUE TITLE
Can't select custom added font, switches to another one

### ISSUE THREAD

**Issue by solracsf** [ONLYOFFICE/DocumentServer#1839]
See attached video, it's very clear. When custom added font LATO is selected, it switches to LIBERATION MONO.
Font here attached too.

[Described problem](https://user-images.githubusercontent.com/12234510/181194869-1d5fab5b-9c76-437c-a1b2-6a5960d25e59.mp4)

[Lato-Font.zip](https://github.com/ONLYOFFICE/DocumentServer/files/9196317/Lato-Regular.zip)

Windows 10

**Browser version:**

Chromium: 103.0.5060.134 (Build officiel) (64 bits)

**Comment by ShockwaveNN** [comment]
Hi, I think it's a cache problem, after updating font list you need to clean browser cache, you can check incognito mode and in this mode everything will be ok

**Comment by solracsf** [comment]
Well I've cleared cache mode. I'll try in incognito mode and report back.

**Comment by solracsf** [comment]
@ShockwaveNN same problem on incognito mode.

**Comment by ShockwaveNN** [comment]
In that case I think it may be caching on proxy/reverse-proxy side if you've using any

**Comment by solracsf** [comment]
It was a cache problem. Thanks.
