### ISSUE TITLE
xls type files cannot be saved, but can be previewed

### ISSUE THREAD

**Issue by TangTing520** [ONLYOFFICE/DocumentServer#1840]
Hi @ShockwaveNN
The xls type file cannot be saved, but it can be previewed. Have you solved it? How to solve it? Looking forward to the reply
![4da9fe23d40b5355a800405ecb06f02](https://user-images.githubusercontent.com/59990894/181215148-118a75a4-5552-4e5b-9085-ccad4ef22ee7.png)
!

**Comment by ShockwaveNN** [comment]
This is network error and something should be in logs of DocumentServer in `/var/log/onlyoffice`, probably some connection error

**Comment by TangTing520** [comment]
![c90e4fb33452fc18db127d69f75e6a5](https://user-images.githubusercontent.com/59990894/181218479-cf06d69b-3a95-42ba-88d3-5e4fc7572b4a.png)
[2022-07-27T09:44:30.159] [ERROR] nodeJS - stdout (id=90xls_7297):
[2022-07-27T09:44:30.159] [ERROR] nodeJS - stderr (id=90xls_7297):
[2022-07-27T09:44:30.159] [ERROR] nodeJS - ExitCode (code=88;signal=null;error:-88;id=90xls_7297)
[2022-07-27T09:44:46.263] [ERROR] nodeJS - stdout (id=90xls_1095):
[2022-07-27T09:44:46.263] [ERROR] nodeJS - stderr (id=90xls_1095):
[2022-07-27T09:44:46.263] [ERROR] nodeJS - ExitCode (code=88;signal=null;error:-88;id=90xls_1095)

I don't understand what this error means

**Comment by ShockwaveNN** [comment]
I don't think it's this error, some other errors should be, maybe in nginx log

**Comment by 15717169499** [comment]
I have also had this problem. After editing, xls and doc files cannot be saved. The log prompts "A document saving error has occurred."

**Comment by 15717169499** [comment]
![image](https://user-images.githubusercontent.com/35255404/195268194-2050edcd-6d6b-48cf-bf95-23f87aeb2500.png)
There is no error message in nginx
I don't know how to deal with it at present. What good suggestions do you have

**Comment by ShockwaveNN** [comment]
@15717169499 Please create a new issue, your's and OP's may be not related

And add more info about your setup

Usually, this errors mean that DocumentServer cannot connect to DMS because of networking problems and errors will be not in the converter log, but in `docservice` logs

I'm closing this issue because OP do not respond
