### ISSUE TITLE
An error has occurred while opening the file.

### ISSUE THREAD

**Issue by mehmetkoyuncu** [ONLYOFFICE/DocumentServer#1843]

**Comment by mehmetkoyuncu** [comment]
Hello,


I am using version 11 of the document. On the node js sample project, when I try to create a document or open documents that I have created before, I get the error in the image. I installed the same version on a windows server (including Rabbitmq). But I got this error on another windows server. When I examine the logs, it prints the following error.

![image](https://user-images.githubusercontent.com/46028783/181623362-649f14ff-751d-40db-9ffe-e9b4a8f74a54.png)

When I examine the logs, it prints the following error.

Converter Logs : 
![image](https://user-images.githubusercontent.com/46028783/181624259-3aafb1b6-eeb7-4897-a4fb-6b4f8392124a.png)

DocService Logs : 
![Uploading image.png…]()

Can you support?

**Comment by ShockwaveNN** [comment]
Hi, never saw error like this, especially exit code 3221225781

Maybe some permission problem on one host? Especially if you saying same setup works fine on another server, not sure that we can help until you figure out that the difference between those setups

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
