### ISSUE TITLE
Not see Protection tabs 

### ISSUE THREAD

**Issue by cutorek** [ONLYOFFICE/DocumentServer#1845]
i have Nextcloud 22.2.3 on local server
And Onlyoffice conector 7.4.4
and on second local server apt info onlyoffice-document server i see version 7.1.1-23

On document i dont see tab Protection.
(i need lock some cells or rows atc..) 

Its necesary acivate this tab ??
Thanks

**Comment by ShockwaveNN** [comment]
Hi, this is strange, we do not hide this tab by default and I've not even sure we got option to hide this tab

Could you show a screenshot?

**Comment by cutorek** [comment]
![Snímek obrazovky 2022-07-29 174145](https://user-images.githubusercontent.com/110244571/181795377-389d4220-a7f4-4970-8979-96468dc598a4.png)

**Comment by ShockwaveNN** [comment]
Seems that protection tab was disabled by [this config](https://api.onlyoffice.com/editors/config/document/permissions#protect) value

Could you check that if you open file via integrated test example (http://documentserver-url/welcome) this tab is present?

If so this is a coming from Nextcloud Integration and I'll transfer this issue there

**Comment by cutorek** [comment]
No in onlyofficedocumente server on example demo o dont see tab protection. 
Where is location this config ? in Api.js /var/www/onlyoffice/documentserver/web-apps/apps/api/documents  ?

Thnaks.

**Comment by ShockwaveNN** [comment]
> No in onlyofficedocumente server on example demo o dont see tab protection.

This is not right, by default this tab is visible in `/example` and as far as I remember it's not easiest task to disable it

How did you run DocumentServer? Any custom parameters? Is this new installation or upgrade?

**Comment by cutorek** [comment]
Its runing on virtual ubuntu 20.04.1 LTS  ( on proxmox virtualizer) . 
Comon instalation (NO docker) . 
I dont now if there is extra custum parametr. I think there is normal state. 
Its 2years old instalation. But i did not install it. 
Maybe i try new instalation on other virtual pc.

**Comment by ShockwaveNN** [comment]
>  But i did not install it.

Maybe someone disabled this tab or maybe something went wrong during some of updates, but if so we need some detailed steps on how to reproduce it

So yeah, try new install or clean all config files on this one and reinstall

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
