### ISSUE TITLE
OnlyOffice Presentation cursor misplacing issue (Mouse/Pointer)

### ISSUE THREAD

**Issue by unknown009d** [ONLYOFFICE/DocumentServer#1846]
## Cursor not working correctly or misplacing...
So i have been using the presentation extensively and for a long period of time, so i use the scroll to change pages and sometimes to zoom in and out of the presentation. <br>
After spending almost an hour or so the cursor misplaces itself, while am moving any images or text the cursor misplaces itself. It's like if am pointing to the (x:980 | y:500) coordinate the selection area is in (x: 950 | y:450), it really annoys because there is no way to fix it. <br> *The only solution i can get now is saving the document and reopening the document.*

### Following is a reference of it
![Only](https://user-images.githubusercontent.com/60551363/181791103-e8f3e2ea-4c7d-426d-b2f7-641e3f7d7976.jpg)

**Comment by ShockwaveNN** [comment]
Hi, I think we got once some similar issue, but we never found out exact scenario how to reproduce this and seems you don't have one either, so I don't know what we can do in current state, since we cannot reproduce it

**Comment by unknown009d** [comment]
## Let me tell you the steps to re-create this issue
1. Get any online .ppt/.pptx template with over 50 slides or more.
2. Try deleting few pages & adding some.
3. Zoom in and out of the document.
4. Move the icons or images also pasting images.
5. Try editing few texts
6. Make some shapes change

*I have given a custom design to make you understand the issue.. but I can send you a video if you want and create the exact scenario*

**Comment by ShockwaveNN** [comment]
I think we need any example file you've described as `Get any online .ppt/.pptx template with over 50 slides or more.`

And yes, video will help us very much to detect this issue

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by ksceniev** [comment]
It happens with docx/doc and  xlsx/xls files as well. Oddly enough i can only verify this on Chrome. Bug not present on Firefox or Edge here.
