### ISSUE TITLE
Not delete the last character in the content when the cursor is at the last position of plain text

### ISSUE THREAD

**Issue by kchzhang** [ONLYOFFICE/DocumentServer#1847]
**Do you want to request a feature or report a bug?**
Report a bug.

**What is the current behavior?**

The content cannot be deleted when the cursor is at the last position of plain text

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a document.
2. Insert plain text.
3.  Input content.
4. Cannot delete the last one.

**What is the expected behavior?**
Can delete the last character in the content when the cursor is at the last position of plain text

**Did this work in previous versions of DocumentServer?**
Not that I know of.

**DocumentServer version:** 7.1.1

**Operating System:**

Client: Ubuntu 22.04 / Ubuntu 20.04

**Browser version:**

Google Chrome  103.0.5060.134

![plain](https://user-images.githubusercontent.com/22465727/182293884-76dcfb18-26f5-421e-969e-fbd14323a302.png)

**Comment by ShockwaveNN** [comment]
Hi, could you record a video about this, because for me if you place a cursor at end of plain text content control - you can delete all content

If you want to delete only last symbol - you should place cursor before last symbol and press `delete`

**Comment by kchzhang** [comment]
thanks

**Comment by ShockwaveNN** [comment]
I assume you got no further questions? In that case, I'll close it
