### ISSUE TITLE
In Office Online, the list of co-edited users is duplicated

### ISSUE THREAD

**Issue by yt-confirm** [ONLYOFFICE/DocumentServer#1849]
Hello, I am using Word to edit online in Office Online, but I have a problem in co-editing.

The same user requests the same Word document more than once, causing the names of the co-edited user lists to display repeatedly.

I'm using Office Online 2019
![phenomenon](https://user-images.githubusercontent.com/68738517/182812671-7786fe87-dae4-424a-bfaa-ad530e7f6245.png)

**Comment by ShockwaveNN** [comment]
I'm sorry, but this is no our product, this is Word Online on your screenshot, and this is ONLYOFFICE DocumentServer repo, you better to contact Microsoft
