### ISSUE TITLE
feature request: being able to specify output format on docEditor.downloadAs

### ISSUE THREAD

**Issue by silto** [ONLYOFFICE/DocumentServer#185]
**Do you want to request a *feature* or report a *bug*?**
request a feature

**What is the current behavior?**
calling downloadAs triggers a document conversion and an url is generated. an "onDownloadAs" event is then triggered with the new document's url as parameter, in a default format (docx for documents, xlsx for spreadsheets and pptx for presentations). There is no way to specify an output format, even though it is possible when downloading from inside the editor.

**What is the expected behavior?**
I think adding a file format parameter to downloadAs (string, ex: "ODT") would be a good fix.
This parameter would be used in place of the default format, just as downloads work inside the editor.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
All versions.

**Additional information**
I have already made a fix by manually editing the compiled code in a docker container and I have tested that it can work without any deep modification.

Also I can make a pull request to make it easier for you.

Thanks for your time and this amazing tool!

**Comment by agolybev** [comment]
Hi @silto, we'll think about it. 
At least the function has an incorrect name for such functionality.
Thank you for the report.

**Comment by silto** [comment]
OK, I'll keep an eye on the changelog then.
Thank you for the quick response.
