### ISSUE TITLE
Sorting dates sorts text instead of dates

### ISSUE THREAD

**Issue by piiskop** [ONLYOFFICE/DocumentServer#1851]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Sorting date fields results with sorted according to the text.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create an unsorted list of dates and eventually, set the field type for them also as _Date_!
2. Click _Sort ascending_ or use _Data_ -> _Custom Sort_ on the fields created in the step _1_!
3. See that the result is a sorted list but not according to dates but according to the values as text!

**What is the expected behavior?**

i expect dates to be sorted as dates.

**Did this work in previous versions of DocumentServer?**

i have no idea.

**DocumentServer version:**

_ONLYOFFICE/7.1.1.23_

**Operating System:**

`kalmer@kalmer-GL752VW:~$ lsb_release -a`

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04 LTS
> Release:	22.04
> Codename:	jammy

**Browser version:**

_Version 103.0.5060.134 (Official Build) (64-bit)_

**Comment by Rita-Bubnova** [comment]
Hello, @piiskop, sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by piiskop** [comment]
I do not know about _DesktopEditors_ The version I have now is _ONLYOFFICE/7.4.1.36_. The issue still persists. It recognizes the American date format as text.

**Comment by piiskop** [comment]
[test-file](https://nextcloud.tennis24.ee/index.php/s/xDTNDREBD7qLYzw)

**Comment by rsnegirev** [comment]
@piiskop 

Sorry for a long answer. I can see another problem in the provided file - that the ascending sort put the 2023 year first instead of the 2022.

**Comment by piiskop** [comment]
@rsnegirev, of course, the sorting works if using your given format because then, it is text sorting, not date sorting. Multiple date formats are available, and my given one is one of them. The date sort should work on any date format.

**Comment by piiskop** [comment]
So _MS Excel_ is also broken and there is no way to report it as it is MS. Is it really necessary to clone all the functionalities of _MS Office_ or could ONLYOFFICE be better?

**Comment by rsnegirev** [comment]
Are LibreOffice and Google Sheets broken too? It works exactly the same in them.

When you choosing some custom date format like _yyyy/mm/dd_ you should enter a date exactly in this format. Otherwise the editor decides it's text.

**Comment by piiskop** [comment]
I just checked in _Calc_ and yes, it is broken. I can use multiple date formats and even if I set the correct date format that conforms to the content, sorting does not work as expected. It would not make sense to have these multiple date formats otherwise.

**Comment by rsnegirev** [comment]
I don't really understand what exactly do you mean.

Here I set different date formats (spelling follows the specified format) and sorted them ascendingly:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/65603548/0f88d179-bf92-46ac-8b70-1f9172eea256)

So sorting works. 

There is no sense in setting a certain format and not conforming to it.

**Comment by piiskop** [comment]
Your example brings out two more issues.

I entered the dates as they are in your example. Then I cut them and pasted them into new cells and then, the middle value looked like the last value. The format was changed automatically. This is one issue although not connected to sorting.

My entered values look like the last one of yours. The format is the same. The format will not be recognized as date or numeric for the custom sort as only textual sorting is offered. This is the other issue that is directly connected to sorting.

**Comment by rsnegirev** [comment]
Hi @piiskop 

Sorry for a long answer, but I think there are no bugs or any other problems. This is exactly how sorting works in the different editors.

**Comment by piiskop** [comment]
What do you mean by _different editors_? Should dates not be sorted as dates but as text? From my point of view, dates should be sorted as dates and not as text if the format is given. I do not care whether the same bug lives in Microsoft. Is the intention of ONLYOFFICE-creators to also copy all the bugs? Can you not be better?

**Comment by RenatoSilvaVR** [comment]
I'm getting same issue. Sort isn't working properly.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/139921876/995bafdc-3216-4e91-b1a2-e5d0a4aca23e)

**Comment by rsnegirev** [comment]
@RenatoSilvaVR can you please provide a file example?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
