### ISSUE TITLE
Can't set default document template in Docker Container

### ISSUE THREAD

**Issue by djohnson1865** [ONLYOFFICE/DocumentServer#1853]
Bug (Maybe?)

Was attempting to set the default layout for documents, but it does not seem to be possible.

Attempted to add a new default template for text documents similarly to described in https://github.com/ONLYOFFICE/DesktopEditors/issues/759

As far as I could tell, the defaults for new documents are stored in the official documentserver container in `/var/www/onlyoffice/documentserver/document-templates/`. So I attempted to replace not just one but all of the docx files in the directory with one I had created with defaults I wanted in case of a locale issue or something. No joy. This also including bind mounting a copy of the git repo at that directory with all updated docx files and spinning up the container fresh from there. 

This is being done in concert with the Nextcloud Onlyoffice integration. Had a clear browser cache after each change, so I don't think it's a browser caching issue. 

End goal is to set the default margins to the "US Normal" rather than "Normal" preset. 

Let me know if I am going about this entirely wrong or if there is an easier way to accomplish this. 

If not, or it is not possible, I'll put this down as a feature request to either document the process, or make it more user friendly to set.

**Comment by ShockwaveNN** [comment]
Hi

> As far as I could tell, the defaults for new documents are stored in the official documentserver container in /var/www/onlyoffice/documentserver/document-templates/.

This location is for empty files if you using integrated example (you can replace something and check it in example at `http://docserverurl/welcome`

But if you're using Nextcloud - you should replace them in nextcloud side, since this files always comes from DMS side

Sorry, don't know location of them in nextcloud, but can transfer your issue to appropriate repo

**Comment by djohnson1865** [comment]
That is exactly the information I needed. Solved the issue immediately. Appreciate it! Closing
