### ISSUE TITLE
Feature request: lock some sheet tabs

### ISSUE THREAD

**Issue by meaz** [ONLYOFFICE/DocumentServer#1854]
Hi,

when you work on a sheet, you can create different tabs, each one with a different sheet.

It would be nice to be able to allow editing on a specific tab/sheet, but lock the others. For example, I'm trying to use that with my pupils; I would like them to be able to edit a sheet, but not all as on one of them, I have added formulas and I don't want them to mess them up!

**Comment by ShockwaveNN** [comment]
Hi, any other online office suites allow to do so?

**Comment by meaz** [comment]
I've no idea, sorry.

**Comment by ShockwaveNN** [comment]
Could checkout our [documentation](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/ProgramInterface/ProtectionTab.aspx) and describe exactly what you missing?

There is one whole page for [protecting sheets](https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-spreadsheet-editor/UsageInstructions/ProtectSheet.aspx)

**Comment by meaz** [comment]
Ok thanks.
