### ISSUE TITLE
OnlyOffice not displaying new fonts

### ISSUE THREAD

**Issue by Brich40** [ONLYOFFICE/DocumentServer#1855]
Hello, 

I'm trying to add two new fonts below :
**- 3OF9** 
**- Calibri**
to the OnlyOffice editor, but nothing is displayed in the fonts list.

I'm using a docker container server and below the procedure which I used :

[Documentation link](https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx
)

Also, In the launched script `/usr/bin/documentserver-generate-allfonts.sh` I noticed that the input is 
`/var/www/onlyoffice/documentserver/core-fonts`, so the new fonts should be added to this directory or in /usr/share/fonts/ as mentioned in the documentation ?
In all cases I tried both before launching the script but nothing changed, noting that the ttf files have the right permissions 
(`-rw-r--r– / 664`) and ds as (owner:group), there is no error or notice during the script launch and I cleared the cache 

I’m using :

- OnlyOffice 6.4 in a container with Ubuntu 20.04.3 LTS.
- FireFox Browser 103.0.1

Thanks in advance.

**Comment by ShockwaveNN** [comment]
> OnlyOffice 6.4 in a container with Ubuntu 20.04.3 LTS.

This is a *very* old version, try to update to latest stable and recheck, we've fixed a lot of issues with fonts

Also please aware that after adding new fonts you should clean a browser cache, so please check if those fonts are present in browser incognito mode

**Comment by Brich40** [comment]
Unfortunately, it is not possible to update to the latest version because the application that includes OnlyOffice does not support it. 
But the problem is solved by using 6.4.2.
You can close the issue and Thank you for your reactivity.

**Comment by ShockwaveNN** [comment]
Ok, thanks for feedback, please note that we only support one latest stable version, so maybe it's a good idea to report it to your application maintainers
