### ISSUE TITLE
貌似不支持在页眉中插入标题样式引用，自动检索每一页，功能似乎不完整

### ISSUE THREAD

**Issue by Zhang1506900502** [ONLYOFFICE/DocumentServer#1857]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Insert field code header style reference in header

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The first specified type title of each page can be automatically recognized and can be changed in linkage

**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
7.1
**Operating System:**
win10x64
**Browser version:**
Chrome 103.0.5060.134

**Comment by ShockwaveNN** [comment]
Hi, sorry, I do not understand you completly, have no idea that are you meaning

Maybe you can point out some examples in other office suites about that

And **PLEASE** do not any language except English int titles of issues

**Comment by Zhang1506900502** [comment]
It seems that it does not support inserting a title style reference in the header and automatically retrieving the chapter name of each page. The function seems incomplete

![image](https://user-images.githubusercontent.com/71248383/184076243-94eee65f-12c9-4bb5-b1af-f02c163a3ecd.png)
![image](https://user-images.githubusercontent.com/71248383/184076260-b4bb3ac5-4558-4cd9-b2ed-7a0904bcba3f.png)

**Comment by matveevms** [comment]
@Zhang1506900
Hello. At the moment we have not been able to understand the problem you describe here. 

Could you please attach a video showing your steps to reproduce the problem in our editor and for comparison, the behavior of any other editor?

Or we need two documents with a demonstration of the problem. For example, one from the OnlyOffice editor, the second created in MS Word (or any other)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
