### ISSUE TITLE
The time of revision mode is different from the MS Office

### ISSUE THREAD

**Issue by kchzhang** [ONLYOFFICE/DocumentServer#1858]
**Do you want to request a feature or report a bug?**

Report a bug.

**What is the current behavior?**

The time of revision mode is different from the MS Office

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a document.
2. Click the "track changes"
3. Input content.
4.  Download and open.
5. Time is different.

**What is the expected behavior?**
The same time

**Did this work in previous versions of DocumentServer?**
Not that I know of.

**DocumentServer version:** 7.1.1-23

**Operating System:**

Client: Ubuntu 22.04 / Ubuntu 20.04

**Browser version:**

Google Chrome  103.0.5060.134
![time](https://user-images.githubusercontent.com/22465727/184076893-fbb4261a-5ee3-4dfc-a2d6-1c74148ba4b4.png)

**Comment by ShockwaveNN** [comment]
I think this may depends of timezone which setup on your server, which timezones you have on your browser\ms office side and on DocumentServer side?

**Comment by kchzhang** [comment]
`ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`

I tried, but it didn't work

`var dateStr = new Date(reviewInfo.DateTime).toISOString().slice(0, 19) + 'Z'`

Maybe it's the 'toISOString'?

**Comment by TatianaKirillova** [comment]
Hello, @kchzhang 
Thank you for report.
The ONLYOFFICE editor takes into account the client's time zone, while the MS Office editor records the current time without considering the time zone. In our editor, this is done so that when changing a document from different time zones, the chronology of changes is preserved.

**Comment by kchzhang** [comment]
thanks

**Comment by ShockwaveNN** [comment]
If there is no any question I'll close this issue, but feel free to comment if got any
