### ISSUE TITLE
Please support ISO date (yyyy-MM-dd) 

### ISSUE THREAD

**Issue by grinapo** [ONLYOFFICE/DocumentServer#186]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the expected behavior?**
dates as 2017-10-25, possibly as 2017-Oct-25

**Comment by konovalovsergey** [comment]
This issue is fixed (ONLYOFFICE/sdkjs@57fff58).
Сhanges will be released in 6.3 version

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until we release version 6.3

**Comment by ShockwaveNN** [comment]
DocumentServer v6.3.0 is released. This problem should be fixed
