### ISSUE TITLE
The "&" symbol in the picture is inconsistent

### ISSUE THREAD

**Issue by kchzhang** [ONLYOFFICE/DocumentServer#1865]
**Do you want to request a feature or report a bug?**

Report a bug.

**What is the current behavior?**

The "&" symbol in the picture is inconsistent

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open the hello.docx

**What is the expected behavior?**

the same

**Did this work in previous versions of DocumentServer?**
Not that I know of

**DocumentServer version:** 7.1.1-23

**Operating System:**

Client: Ubuntu 22.04 / Ubuntu 20.04

**Browser version:**

Google Chrome  103.0.5060.134

 
![55555555](https://user-images.githubusercontent.com/22465727/184865335-9d656389-37c3-455c-9567-c92b880b7feb.png)

**Comment by kchzhang** [comment]
[
[hello.docx](https://github.com/ONLYOFFICE/DocumentServer/files/9350317/hello.docx)
](url)

**Comment by ShockwaveNN** [comment]
> [hello.docx](https://github.com/ONLYOFFICE/DocumentServer/files/9350317/hello.docx)
> file

In your file the table is an image, are you sure you've shared correct file? In this file this table is **image**

And rendered fine BTW
![image](https://user-images.githubusercontent.com/668524/184875072-5c797993-c631-4480-b013-4a267e033e11.png)

**Comment by kchzhang** [comment]
I tried, but it's the same.

![666](https://user-images.githubusercontent.com/22465727/185019229-becd10b5-1a82-4c2c-96d1-3e90e80a25c5.png)

![image](https://user-images.githubusercontent.com/22465727/185019267-147ba85a-39c9-474b-9159-8565480cc198.png)

![11](https://user-images.githubusercontent.com/22465727/185019615-e912245a-92bc-4763-9bab-8368928f4818.png)

**Comment by ShockwaveNN** [comment]
So am I sure that this document **should** be with picture and problem in picture render?

If so - what browser zoom level you've using and what zoom level inside DocEditor is set?

**Comment by kchzhang** [comment]
I got it，thanks

**Comment by ShockwaveNN** [comment]
Could you explain your solution if someone stumble around same error?

**Comment by kchzhang** [comment]
> Could you explain your solution if someone stumble around same problem?

It's , i deleted some fonts.

**Comment by ShockwaveNN** [comment]
@kchzhang Not sure how deleting fonts can impact image rendering (It can impact symbol rendering, but this was picture, not text file)
But I'll close issue if issue is resolved for you
