### ISSUE TITLE
strange fonts  

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1868]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
we have deleted many default fonts and added some custom fonts. 
Since that we have a font with "chines character" , if selected the fonts looks very "default"
there are 2 more "dead" fonts named like another added font, if selected font name changes to "ASCW" and looks like the default font. 

we have no idea why this happen, restart, cache reboot all did not work (sure we have execute: gen-all-fonts"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
Yes, maybe

**DocumentServer version:**
7.1.1
**Operating System:**
Debian
**Browser version:**
multi

**Comment by ShockwaveNN** [comment]
`ASCW3` is our font used for displaying some non-printing symbols, like tabs, newlines or some control symbols like `radiobuttons` and something like this

But generally speaking we do not advice deleting some default fonts, because anything can happened after that, since those are **default** fonts for a reason

**Comment by hahaxd35** [comment]
can u tell witch fonts i should not delete? Customer wants only wanted fonts
and how i can generate ASCW3 again?

**Comment by ShockwaveNN** [comment]
> can u tell wich fonts i should not delete?

I don't think we got a list of fonts you shouldn't delete, we advice not to delete at all

> and how i can generate ASCW3 again?

https://github.com/ONLYOFFICE/core-fonts/blob/master/ASC.ttf

**Comment by hahaxd35** [comment]
is there a way to not show fonts?

**Comment by ShockwaveNN** [comment]
> 
is there a way to not show fonts?

No, don't think so

> forgot to upload screenshots

Not sure if those `curvy` fonts are part of packaging, are you sure that those are not system fonts? Did you used docker installation? Since I think it has less fonts by default than any other installation, since it's not using system fonts without extra mount volume

**Comment by hahaxd35** [comment]
this curvy fonts we have added to Onlyoffice (no docker install), It's kind of German Schreibschrift, 

so i will try out to find out which font can be removed without strange behavior

**Comment by hahaxd35** [comment]
i does not know how to work with docker, but i have this script that remove all fonts i give as param, because after update font would be there again :)

This is how the script was called:
removeFont.sh wqy-zenhei ubuntu-font-family ttf-khmeros-core tibetan-machine takao-gothic samyak-fonts samyak padauk openoffice nanum lohit-telugu lohit-tamil-classical lohit-tamil lohit-punjabi lohit-oriya lohit-malayalam lohit-kannada lohit-gujarati lohit-devanagari lohit-bengali lohit-assamese liberation kacst-one kacst freefont fonts-telu-extra fonts-gujr-extra fonts-beng-extra droid dejavu crosextra asana arphic-ukai ancient-scripts abyssinica andalemo* Andale_Mono* comic* Comic* cour* Cour* georgia* Georgia* impact* Impact* Webdings Webdings noto

is maybe "ancient-scripts" the reason?

`
#!/bin/bash

if [ "${#}" -eq 0 ]
  then
      echo "Keine Parameter uebergeben"
      echo "Beeenden."
      exit
fi

habichgeloescht=0

for removeFont in $@
  do
    if test -d /var/www/onlyoffice/documentserver/core-fonts/$removeFont 
      then
          rm -r /var/www/onlyoffice/documentserver/core-fonts/$removeFont && let habichgeloescht++
    else
          rm /var/www/onlyoffice/documentserver/core-fonts/*/$removeFont &> /dev/null && let habichgeloescht++
          rm /usr/share/fonts/msttcorefonts/$removeFont &> /dev/null && let habichgeloescht++

    fi
done

if [ $habichgeloescht -gt 0 ]
  then
      documentserver-generate-allfonts.sh && supervisorctl restart all
  else
      echo "Keine Schrift geloescht."

fi

`

**Comment by ShockwaveNN** [comment]
> is maybe "ancient-scripts" the reason?

Sorry, I don't know, you seems to delete **a lot** of fonts

I think fonts like Webdings are used to display marked list characters, Impact for some other reasons

I think it's really a bad idea to remove those fonts, consequences can be unpredictable, since we include them in our setup for a reason

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by hahaxd35** [comment]
the chines character was the font """ukai"""" 
added again, but still in front menu, when selected  know i can type "normal" 
before when selected  some chinise characters was displayed, most only as white box, strange (for me) was that output was real chinies unicode characters "匀"

Webdings (part of microsoft fonts not Onlyoffice core-fonts) added again but still same problem.

can u tell me other fonts that are not alphabetic?  

> I think it's really a bad idea to remove those fonts, consequences can be unpredictable, since we include them in our setup for a reason, it's a perfect set of fonts to have greater compatibility with most office files, so removing those you're loosing it

customer whats to remove all there fonts because there dont look nice and there need special fonts (as you saw), we dont care about microsoft compatibility

sorry for long response,m did not have time to test
