### ISSUE TITLE
Cross domain issues

### ISSUE THREAD

**Issue by chinamaqs** [ONLYOFFICE/DocumentServer#1872]
**Do you want to request a *feature* or report a *bug*?**
	In doubt
**What is the current behavior?**
	I want to open onlyoffice as a new page instead of embedding it	
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by chinamaqs** [comment]
I want to get the link to edit the document instead of directly embedding it. Because direct embedding sometimes has cross domain problems, how about getting links?

**Comment by chinamaqs** [comment]
![image](https://user-images.githubusercontent.com/48231152/185359732-bf1c849f-cff7-479e-adb6-3ec7a911343d.png)

**Comment by ShockwaveNN** [comment]
Sorry, I don't get you at all, you need to clarify what you already done, what fails and what you want to do more clearly

**Comment by chinamaqs** [comment]
![f1460bc417cc1cdbb038274bcae835f](https://user-images.githubusercontent.com/48231152/185361503-4d892adc-980d-4296-b317-a8d87117478f.png)

**Comment by ShockwaveNN** [comment]
Not sure if this is even possible, your DocumentServer opened in iframe and if I'm not mistaken they cannot share any context

**Comment by chinamaqs** [comment]
> Not sure if this is even possible due to browser security, your DocumentServer opened in iframe and if I'm not mistaken they cannot share any context

Okay, thank you. I'll think about it
