### ISSUE TITLE
After using docker to pull the image for installation, the document server can be accessed successfully, but a serious error will be prompted when editing the file, which makes it impossible to edit

### ISSUE THREAD

**Issue by hehehebigking** [ONLYOFFICE/DocumentServer#1876]
After using docker to pull the image for installation, the document server can be accessed successfully, but a serious error will be prompted when editing the file, which makes it impossible to edit，How should I solve this problem？
This is an error report picture：
<img width="961" alt="suc" src="https://user-images.githubusercontent.com/109956173/185601243-ebfe3997-ca0a-4609-b9eb-38b8631ab8fd.png">
This is the system nginx error log for Ubuntu operating system，：
[nginx.error.log](https://github.com/ONLYOFFICE/DocumentServer/files/9381472/nginx.error.log)

**Comment by ShockwaveNN** [comment]
Hi, nothing serious in nginx logs

1. Could you take a look at `/var/log/onlyoffice/documentserver` for any other error in logs?
2. That DMS are you using? Is this error happens while opening file via integrated test example (can be enabled at `http://localhost/welcome`

**Comment by hehehebigking** [comment]
Thank you for your answer. I now use the Linux system (Ubuntu) on my server. The above error occurred by editing the file using the test example. In the log of "/ var / log / onlyoffice / documentserver", I see no other error logs except the error log of nginx. I have uploaded the zip files of all the system logs under the directory of "/ var / log / onlyoffice / documentserver". Please check here, Look at the cause of the error
[documentserver.zip](https://github.com/ONLYOFFICE/DocumentServer/files/9390901/documentserver.zip)

> Hi, 
nothing serious in nginx logs
> 
> 1. Could you take a look at `/var/log/onlyoffice/documentserver` for any other error in logs?
> 2. That DMS are you using? Is this error happens while opening file via integrated test example (can be enabled at `http://localhost/welcome`

**Comment by ShockwaveNN** [comment]
Yeah, I agree that there is nothing strange in logs except this error 

1. Which host os are you using?
2. Is this error happened on any xlsx file on only on some specific ones
3. How did you run the docker container? Any additional non-default option
Could you check if you run `docker run -itd -p 80:80 onlyoffice/documentserver` - error still be present or not?

**Comment by hehehebigking** [comment]
Thank you for your patience to answer many times, I have found the problem, is the problem that the web browser, I used to use Google browser, probably because I installed before many scripts plug-in or other reasons cause my browser when using onlyoffice appeared the problem, after I change into edge browser can normal editing and access.
Have a good life, my good friend.

**Comment by ShockwaveNN** [comment]
@hehehebigking You can try chrome incoginto mode and I think the problem did not occur there either

Glad that you've find the reason, I'm closing this issue
