### ISSUE TITLE
big ppt file(size 100MB+,100+page) open very slow

### ISSUE THREAD

**Issue by ova1900** [ONLYOFFICE/DocumentServer#1877]
hi developer,

i use community version documentserver(docker deploy,latest version) ,when open ppt file(file size more than 100MB+,100+page)  ,very slow( use time 70~100 second), how can i  optimized that? 

I have two questions:

1.  convert to ooxml slow, it can be optimized by setting certain parameters ?
2. i saw must be fully load the document to open the editor in broswer, can lazy load or paging load the file?

**Comment by ShockwaveNN** [comment]
> convert to ooxml slow, it can be optimized by setting certain parameters ?

Not, there is no option, I think it's better to convert it to pptx once and open in pptx format, it will be faster that using ppt->pptx convert each time

> i saw must be fully load the document to open the editor in broswer, can lazy load or paging load the file?

No our technology do not allow it


If you share this file I can take a look at it and maybe I got some advice about how to speed things up

**Comment by ova1900** [comment]
> > convert to ooxml slow, it can be optimized by setting certain parameters ?
> 
> Not, there is no option, I think it's better to convert it to pptx once and open in pptx format, it will be faster that using ppt->pptx convert each time
> 
> > i saw must be fully load the document to open the editor in broswer, can lazy load or paging load the file?
> 
> No our technology do not allow it
> 
> If you share this file I can take a look at it and maybe I got some advice about how to speed things up

i find the slow reason that because must load so many font data(40+request),and total request 1000+,in chrome  had parallel limit(6 request) ,over limit request must wait for finish,i tring to use http2 protocol to break limit,but it didn't make much of a difference. i find the onlyoffice example via preload the js script and the core font data to speed up.

**Comment by ShockwaveNN** [comment]
Those fonts data are cached, so it will be slow only for first open of this document with some big fonts (usually CJK fonts are big)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by NeverLuckyLiu** [comment]
> > > convert to ooxml slow, it can be optimized by setting certain parameters ?
> > 
> > 
> > Not, there is no option, I think it's better to convert it to pptx once and open in pptx format, it will be faster that using ppt->pptx convert each time
> > > i saw must be fully load the document to open the editor in broswer, can lazy load or paging load the file?
> > 
> > 
> > No our technology do not allow it
> > If you share this file I can take a look at it and maybe I got some advice about how to speed things up
> 
> i find the slow reason that because must load so many font data(40+request),and total request 1000+,in chrome had parallel limit(6 request) ,over limit request must wait for finish,i tring to use http2 protocol to break limit,but it didn't make much of a difference. i find the onlyoffice example via preload the js script and the core font data to speed up.

hi， could you show an example that you preload the fonts? Thanks
