### ISSUE TITLE
Can allow Latin text to wrap in the middle of a word?

### ISSUE THREAD

**Issue by EllaEmmaWang** [ONLYOFFICE/DocumentServer#1879]
**Do you want to request a *feature* or report a *bug*?**
It must be a feature.
**What is the current behavior?**
We just opened a file, review it. But when there is Latin text on lines, it will has Line break.
Below is OnlyOffice:
![WeChatWorkScreenshot_d8c8f32a-587a-4876-a1d7-c9431a6a54ed](https://user-images.githubusercontent.com/111862170/186124192-513ad68c-75fa-482c-ab74-9fd1f8f41260.png)

Below is on WPS office:
<img width="981" alt="WeChatWorkScreenshot_a10876a1-1df4-462f-87cd-c2714243bb80" src="https://user-images.githubusercontent.com/111862170/186124735-49f7884d-1c0f-4135-9a47-6bcd2760d193.png">

Can you tell us how we can control it, make it just like on the WPS office? Like as, doing settings on DocumentServer?
**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
We just use version 6.4.2, so we don't know it.
**DocumentServer version:**
 version 6.4.2

**Comment by ShockwaveNN** [comment]
> We just use version 6.4.2, so we don't know it.


Could you update to the latest v7.1.1, I'm not sure, but I thought we got some very similar issue resolved in previous releases

**Comment by EllaEmmaWang** [comment]
> > We just use version 6.4.2, so we don't know it.
> 
> Could you update to the latest v7.1.1, I'm not sure, but I thought we got some very similar issue resolved in previous releases

Thank you for replying, we will try it to verify v7.1.1 is Okay or not.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
