### ISSUE TITLE
RPM documentserver-configure.sh show ValueError: Port tcp/80 already defined

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#188]
After https://github.com/ONLYOFFICE/document-server-package/commit/4d04f0698ef128c910bbcbcbf691bdc9533775ad
Calling `bash documentserver-configure.sh` without defined `DS_PORT` cause warning
```
ValueError: Port tcp/80 already defined
```

Everything seems working fine through.

**DocumentServer version:** 5.0.3.37

**Operating System:** Centos 7.4

**Comment by agolybev** [comment]
Fixed with https://github.com/ONLYOFFICE/document-server-package/commit/f4c3f22dc57d69440cf11aa236d4b64d30ac0471#diff-33bf4a606bddad743243d48760507d07
@ShockwaveNN, could you verify the bug.

**Comment by ShockwaveNN** [comment]
Confirm fixed
`bash documentserver-configure.sh` output now is clear, without errors.
Checked on 
onlyoffice-documentserver-ie.x86_64       5.0.99-446
