### ISSUE TITLE
Please tell me some problems with version 7.1.1. Thanks！

### ISSUE THREAD

**Issue by wwtaoqaq** [ONLYOFFICE/DocumentServer#1885]
I downloaded onlyoffice for linux of version 7.1.1, but the /etc/onlyoffice directory is not generated under /etc, and I created local.json file and configured token does not take effect.

**Comment by ShockwaveNN** [comment]
Hi, sorry it's very hard to understand you

But if I'm understand you right 

> but the /etc/onlyoffice directory is not generated under /etc,

This is not right, but I have no idea why this is happened

You shouldn't create `local.json` file by yourself

**Comment by wwtaoqaq** [comment]
Thank you for taking the time to help me! I created the local.json file in this directory /usr/local/services/web-version/out/linux_64/onlyoffice/documentserver/server/Common/config, but it doesn't seem to work.  I also tried to write token-related configuration in development-linux.json, but the DocServer startup directly reported an error.  Do you know what this is about?

**Comment by ShockwaveNN** [comment]
> /usr/local/services/web-version/out/linux_64/onlyoffice/documentserver/server/Common/config

I don't know this location, it's not a default location for any download version

Sorry, but I do not understand at all what you did and what a version you get (and from there)

So instead of guessing please describe step-by-step scenario of what you've downloaded, what you've setup and how

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
