### ISSUE TITLE
OnlyOffice generates corrupted .ods file containing urls due to invalid content.xml

### ISSUE THREAD

**Issue by hubitor** [ONLYOFFICE/DocumentServer#1886]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.1.0.215

### Expected Behavior

OnlyOffice should handle spreadsheet files in .ods format containing urls without issues and generally generate a valid content.xml regardless of what characters the file contains.

### Actual Behavior

I saved a file containing 10 rows with urls, some text and a SUM function as .ods. As I re-opened the file in OnlyOffice 8 rows were missing.

Then I tried to open the file in LibreOffice 7.4 and I got a popup message with this text:

> Read Error:
> Format error discovered in the file in sub-document content.xml at 1,9325(row,col).

and as I clicked OK LibreOffice just closed.

Then I decompressed the file and opened the content.xml in VSC. There were 3 errors:

> The reference to entity "l" must end with the ';' delimeter.

Based on this:
[ERROR: 'The reference to entity "L" must end with the ';' delimiter.'](https://coderanch.com/t/596361/java/ERROR-reference-entity-delimiter)
I removed the related ampersands (&), saved the content.xml and compressed the modified .ods file based on this: [How does Open Office compress its files?](https://stackoverflow.com/questions/4957212/how-does-open-office-compress-its-files)

After that I was able to recover the missing rows (still have to replace the 3 affected urls).

### Reproduction Steps

1. Save a spreadsheet file in .ods format containing urls.
E.g. `https://www.example.com/blabla?k=&l=&display=10` 
2. Close file.
3. Try to reopen file.

### Additional information

I use Arch Linux and the package is the "onlyoffice-bin" from AUR.

**Comment by hubitor** [comment]
Nice. Thanks!

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
