### ISSUE TITLE
The track changes box is showing while editing even though I have turned it off in the config 

### ISSUE THREAD

**Issue by bipana50** [ONLYOFFICE/DocumentServer#1888]
**Do you want to request a *feature* or report a *bug*?**
 Bug
 
**What is the current behavior?**
track changes box is showing on editing. The first edit is fine, after its saved and the editor reinitialized. the box appears on every edit

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here is the link of the screenshot I took: https://ibb.co/dp6xngr
and here is my config
```	let config = {
		width: '100%',
		height: '100%',
		type: '',
		documentType: 'word',
		token: '',
		document: {
			title: doc.title,
			url: `${onlyOfficeConfig.zegalServer}zegal/download?docId=${doc._id}&dragonAuth=${authInfo}`,
			fileType: 'docx',
			key: `${doc._id}${uuidv4()}`,
			info: {
				owner: doc.owner.email
			},
			permissions: {
				chat: false,
				comment: true,
				copy: true,
				download: false,
				edit: true,
				print: false,
				modifyFilter: false,
				modifyContentControl: false,
				review: false,
				protect: false
			}
		},
		editorConfig: {
			mode: edited ? 'view' : 'edit',
			lang: 'en',
			callbackUrl: `${onlyOfficeConfig.zegalServer}zegal/track?docId=${doc._id}&dragonAuth=${authInfo}`,
			templates: [],
			user: {
				group: '',
				id: person?.email,
				name: `${person?.primary_name?.given_name} ${person?.primary_name?.surname}`
			},
			embedded: {
				saveUrl: '',
				embedUrl: '',
				shareUrl: '',
				toolbarDocked: 'top'
			},
			customization: {
				about: false,
				chat: true,
				comments: true,
				feedback: false,
				forcesave: true,
				autosave: true,
				submitForm: false,
				uiTheme: 'theme-light',
				logo: {
					image: `${onlyOfficeConfig.zegalServer}images/logoEdited.png`,
					url: onlyOfficeConfig.zegalServer
				},
				toolbarHideFileName: true,
				compactHeader: true,
				toolbarNoTabs: true,
				compatibleFeatures: false,
				plugins: false,
				features: {
					spellcheck: {
						mode: false,
						change: false
					}
				},
				spellcheck: false,
				help: false,
				hideNotes: true,
				hideRightMenu: true,
				hideRulers: false,
				macros: false,
				mentionShare: false,
				hideReviewDisplay: true,
				showReviewChanges: false,
				trackChanges: false,
				hoverMode: false,
				review: {
					hideReviewDisplay: true,
					showReviewChanges: false,
					trackChanges: false,
					hoverMode: false
				}
			},
			fileChoiceUrl: ''
		},
		events: {
			onRequestUsers: onRequestUsers,
			onRequestHistory: onRequestHistory,
			onRequestHistoryClose: onRequestHistoryClose,
			onRequestHistoryData: onRequestHistoryData
		}
	};
```

**What is the expected behavior?**
To not track the changes when its turned off in the config

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer version:**
seen on both 7.1.1 and 6.4.0

**Operating System:**
Linux ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Hm, this is strange

Since you've clearly set `trackChanges` as false

Maybe something wrong with initialization and it's messed up for some reason on every other edit except first?
Not sure that we'll be able to localize this problem only by config example

To be sure - could you check integrated example at `http://docserver-url/welcome` and be sure that you cannot reproduce your problem there

**Comment by bipana50** [comment]
Even after the reinitialize the config is exactly the same except the key. I couldn't reproduce in the example code. 
In the example code, even when the permission.review is true and editorConfig.mode is "edit" the trackChanges isn't enabled which it should've according to this answer in [How to open a document with "track changes" mode enabled?](https://api.onlyoffice.com/editors/faq/sharing). I took the exact same config from example code to my code, but in that case also trcakChnages was enabled which is correct behavior when the permission.review is true and editorConfig.mode is "edit" according to the doc

**Comment by askonev** [comment]
Good afternoon @bipana50
If I understood everything correctly, then the brief view of your configuration in which you encounter the bug looks like this

```js
var docEditor = new DocsAPI.DocEditor("placeholder", {
    "document": {
        "permissions": {
            "edit": true,
            "review": false
        },
        ...
    },
    "editorConfig": {
        "mode": "edit",
        ...
    },
    ...
});
```

And when editing a document you are in review mode.

At the moment I could not reproduce your scenario with the provided editor configuration. My reproduction of your configuration without the event implementation

![Peek 2022-09-02 16-11](https://user-images.githubusercontent.com/60688343/188153393-9aabd417-a1bd-40cf-9b2e-e982fd9939d2.gif)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
