### ISSUE TITLE
Configure Unit of Measurement “character”？

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1891]
The measurement unit now supports "point inch centimeter ". Can you add a supporting ”character“？ MS supported.

**Comment by ShockwaveNN** [comment]
Hi, could you specify in more details what do you mean (maybe link to MS documentation)

Because in my copy of Office 2021 there is no such option

![image](https://user-images.githubusercontent.com/668524/188101060-294cf3c6-4e13-4c24-bea7-cfcb5ae41dcf.png)

**Comment by verydemo** [comment]
@ShockwaveNN 
![image](https://user-images.githubusercontent.com/29354679/188370422-749f5a7d-66dd-41b4-8539-531eb2263149.png)
hi, here.

**Comment by ShockwaveNN** [comment]
This is strange, so this option is in Office 2019 and there is no such option in Office 2021?

Any idea why? Maybe there is some documentation on Microsoft site for this option, but I didn't find it

**Comment by verydemo** [comment]
I don't know why

**Comment by ShockwaveNN** [comment]
I'm sorry, but without proper reference documentation we cannot implemented this feature, since I do not understand why it's hidden or how it should work

So please find some documentation

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
