### ISSUE TITLE
Receive status 3 when track the document changing.

### ISSUE THREAD

**Issue by chenghuibj** [ONLYOFFICE/DocumentServer#1900]
**Do you want to request a *feature* or report a *bug*?**
bug 
**What is the current behavior?**
I have a document system integrated onlyoffice Document Server.
When edit a docx file , the tacking endpoint receive a request. But the request has body which status is 3 and has no url. So document can't save changed file.
Check the logs .
C:\Program Files\ONLYOFFICE\DocumentServer\Log\converter
`[ERROR] nodeJS - Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ADMINI~1\AppData\Local\Temp\ASC_CONVERT12289-i67e5f.abnd'
    at Object.rmdirSync (fs.js:916:10)
    at deleteFolderRecursive (C:\snapshot\server\build\server\FileConverter\sources\converter.js)
    at ExecuteTask (C:\snapshot\server\build\server\FileConverter\sources\converter.js)
    at ExecuteTask.next (<anonymous>)
    at C:\snapshot\server\build\server\FileConverter\sources\converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (C:\snapshot\server\build\server\FileConverter\node_modules\co\index.js:65:19) {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\ASC_CONVERT12289-i67e5f.abnd'
}
`
C:\Program Files\ONLYOFFICE\DocumentServer\Log\docservice\out.log
`[WARN] nodeJS - sendServerRequest returned an error: docId = -1320449177; data = {"error":1}`

How can I resovle it.

**DocumentServer version:**
7.1.1-23
**Operating System:**
Windows Server 2016

**Comment by ShockwaveNN** [comment]
> C:\Users\ADMINI~1\AppData\Local\Temp\ASC_CONVERT12289-i67e5f.abnd' at Object.rmdirSync

This is strange, seems something wrong with conversion

Could you check that everything works fine with integrated test example, you can enable it on `http:\\docserver-url\welcome`

**Comment by chenghuibj** [comment]
@ShockwaveNN Thx

**Comment by chenghuibj** [comment]
@ShockwaveNN Thx
The example is work.  I can open , view and edit the document using onlyoffice ,and when reopen the changed document, the changes are not lose.  However changed document can't be saved to document system . The track endpoint reseives a message which status 3.

**Comment by ShockwaveNN** [comment]
If integration example works seems something wrong with your own integration

Seems that status 3 caused by `[ERROR] nodeJS - Error: ENOTEMPTY: directory not empty, rmdir` error you've mention

But without ability to reproduce this error on our system I don't think we can do anything
Maybe some broken file is send in callback, maybe some permission problems, maybe something else

**Comment by chenghuibj** [comment]
I test a new docx file with one character. The same error occurs.So it seems not broken file error.

How to modify the temp directory? Driver 'C' offen has permission problom.

C:\Users\ADMINI~1\AppData\Local\Temp\ASC_CONVERT12289-i67e5f.abnd

**Comment by chenghuibj** [comment]
I test a new docx file with one character. The same error occurs.So it seems not broken file error.

How to modify the temp directory? Driver 'C' offen has permission problom.

C:\Users\ADMINI~1\AppData\Local\Temp\ASC_CONVERT12289-i67e5f.abnd

**Comment by ShockwaveNN** [comment]
> How to modify the temp directory? Driver 'C' offen has permission problem.

I think if problems with permissions were the reason - when converting files using `\example` be failing also

I think the reason in something else, maybe in some specific setups of your windows system, or in your integration itself (maybe some keys are incorrect while returning files or something like this)

Anyway - without any way to reproduce this error on our systems - we can only guess

**Comment by chenghuibj** [comment]
Thank you. ShockwaveNN
The error has resolved，it is not a bug.
 The redis is not working.After fixed redis，errors disappeared.
