### ISSUE TITLE
When converting multi page xlsx to pdf, only one page is converted

### ISSUE THREAD

**Issue by JiffyChen** [ONLYOFFICE/DocumentServer#1906]
**Do you want to request a *feature* or report a *bug*?**
BUG

**DocumentServer version:**
Community Edition，7.1.0

**Operating System:**
Docker 

**Browser version:**
Chrome  96.0.4664.110

**Comment by ShockwaveNN** [comment]
Hi, please describe step-by-step scenario to reproduce this problem, since there a lot of ways how you can convert xlsx to pdf

**Comment by JiffyChen** [comment]
1) I have a Multi workSheet  cell;

**Comment by JiffyChen** [comment]
Hi

**Comment by JiffyChen** [comment]
env:
1) docker DocumentServer  
2) Multi worksheets in a xlsx file
3) call api ConvertService.ashx, post with Accept:"application/json" and Content-Type: "application/json"), param：
   {async: false, filetype:"xlsx", key:"randrom string", url:"http://xxx.xlsx", outputtype:"pdf"}

**Comment by ShockwaveNN** [comment]
Could you try to add some more params like in this example

https://api.onlyoffice.com/editors/conversionapi#sample-spreadsheet-to-pdf

It should print multipage

**Comment by JiffyChen** [comment]
THS，add spreadsheet param success.
