### ISSUE TITLE
Plugin Manager not good for GDPR

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1918]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Plugin manger allows user to use plugins that are not allowed (because of GDPR) 

**What is the expected behavior?**
let administrator choose what plugins can be used, not users!  we have to follow the law.  i

**Did this work in previous versions of DocumentServer?**
YES

**DocumentServer version:**
7.1.1

**Comment by ShockwaveNN** [comment]
Hi, sorry for the late response, we are not very often get legal questions

My colleagues informed me that any legal questions should be directed to the sales team, so please contact sales@onlyoffice.com

I'll close this issue, since it's out of my responsibilities to discuss legal matters
