### ISSUE TITLE
Help The new onlyoffice cant add Chinese support

### ISSUE THREAD

**Issue by mannyzhcn** [ONLYOFFICE/DocumentServer#192]
**Do you want to request a *feature* or report a *bug*?**i use ubuntu server 16.04 and docker and owncloud 10.0.3
My onlyoffice is running on this platform of the newest version
For Chinese support
this steps i do
apt-get install fonts-arphic-ukai
cd /usr/share/fonts/
tar cv * | docker exec -i XXX tar x -C /usr/share/fonts/
docker exec XXX /var/www/onlyoffice/documentserver/Tools/GenerateAllFonts.sh
where XXX is the container ID

But icant find “GenerateAllFonts.sh” line。
Very tks

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Hi.
According to [instruction](http://helpcenter.onlyoffice.com/server/linux/document/install-fonts.aspx) - you should use `/usr/bin/documentserver-generate-allfonts.sh`
`GenerateAllFonts.sh` is pretty old name for this script, where did you find info about it?

**Comment by mannyzhcn** [comment]
Thkn

**Comment by mannyzhcn** [comment]
Thank you very much，
This page
https://github.com/ONLYOFFICE/DocumentServer/issues/7

**Comment by ShockwaveNN** [comment]
@mannyzhcn oh, yeah, this is not actual any more

**Comment by mannyzhcn** [comment]
Oh oh，i find it!!
Thks

**Comment by mannyzhcn** [comment]
@ShockwaveNN So,i find this file. 
Waht is the right steps,for add lanaguange support .
Tks!

**Comment by ShockwaveNN** [comment]
@mannyzhcn 
The same, just other script file
`docker exec XXX bash /usr/bin/documentserver-generate-allfonts.sh`
