### ISSUE TITLE
Insert in document stops when cursor is hidden

### ISSUE THREAD

**Issue by elatella** [ONLYOFFICE/DocumentServer#1920]
I am currently using Arch with the [dotfiles from cloudlena](https://github.com/cloudlena/dotfiles).
In this setup, the cursor is hidden after a few seconds of inactivity.

When I write in OnlyOffice, the program stops inserting my typing the moment my cursor is hidden, this makes editing and writing texts extremely tedious.

**Comment by Rita-Bubnova** [comment]
Hello, @elatella.
Sorry for late restonse, seems we missed this issue.
DocumentServer v7.4.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
