### ISSUE TITLE
Status code 2 instead of 4 after force saving

### ISSUE THREAD

**Issue by natoponen** [ONLYOFFICE/DocumentServer#1922]
**Do you want to request a *feature* or report a *bug*?**
Question/bug

**What is the current behavior?**
DocumentServer sends status code 2 for the file that **hasn't been changed** after force save

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1.  Open file
2.  Make some changes
3.  Force save
4.  Open Version history or leave the editor
5.  DocumentServer sends POST to callback url with status code 2 (document is ready for saving)

**What is the expected behavior?**

 5. DocumentServer sends POST to callback url with status code 4 (document is closed with no changes)

This creates two duplicate version of file after force saving and leaving file.

**DocumentServer version:**

7.1.1.23

**Browser version:**

Chrome 106.0.5249.91, Edge 105.0.1343.53

---------------------------------------------------------------------------------------------------------------------------------------------------

Is this expected behaviour or bug? Looks like a bug for me, because it creates unnecessary duplicate versions.

**Comment by Rita-Bubnova** [comment]
Sorry for the long wait.
DesktopEditors v7.4.1 has been released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
