### ISSUE TITLE
highlight in pdf

### ISSUE THREAD

**Issue by jmoest** [ONLYOFFICE/DocumentServer#1923]
Hi,
I have the last Only Office and connector.
When I read a pdf with highlighting, the text is hidden.
![image](https://user-images.githubusercontent.com/20969770/170959520-1844fdb9-0569-4c9b-867a-46b2ea08391d.png)

in pdf viewer:
![image](https://user-images.githubusercontent.com/20969770/170959656-0f9ffc32-b62f-4264-8081-5748961a2a3e.png)

Thank you

**Comment by ShockwaveNN** [comment]
@jmoest Hi, sorry for long responce, your issue was lost in incorrect repo

Could you attach pdf file you've opening?

**Comment by jmoest** [comment]
Hi,

Thank you for your reply. 
The new version of OnlyOffice (ONLYOFFICE-DocumentServer-7.2.0) fixes this issue.
You can close this.

Jonathan

**Comment by ShockwaveNN** [comment]
Glad to hear that, thanks )
