### ISSUE TITLE
fileType set to html , callback handler changesUrl can't download 

### ISSUE THREAD

**Issue by GGBeng1** [ONLYOFFICE/DocumentServer#1926]
when I set editorConfig => document => fileType : html, this version's changes.zip not create

<img width="648" alt="image" src="https://user-images.githubusercontent.com/40552498/194700513-fca7d10e-8df7-435c-b6f8-2654db70d042.png">
but fileType is docx, it will be create
<img width="711" alt="image" src="https://user-images.githubusercontent.com/40552498/194700607-a323ce49-789b-4e15-aaf7-496ee4704f79.png">

**Comment by ShockwaveNN** [comment]
I think the reasoing behind this is that we do not support version history in HTML (or I think in any non-ooxml) files

**Comment by GGBeng1** [comment]
> I think the reasoing behind this is that we do not support version history in HTML (or I think in any non-ooxml) files

thanks, T _ T
