### ISSUE TITLE
The Conversion API always works fine even if I don't pass an url param or pass an error url like '1'

### ISSUE THREAD

**Issue by qqxadyy** [ONLYOFFICE/DocumentServer#1927]
Here is my log

`requestURL=========>http://.../ConvertService.ashx`
`requestJSON========>{"async":false,"filetype":"doc","outputtype":"pdf","title":"b17a41c2f4604daf88966b662d3ca31d"}`
`responseStr========><?xml version="1.0" encoding="utf-8"?><FileResult><FileUrl>http://.../cache/files/conv_undefined_pdf/output.pdf/b17a41c2f4604daf88966b662d3ca31d.pdf?md5=ifzV1ABwLsaKiSF8rvOTSQ&amp;expires=1665308307&amp;filename=b17a41c2f4604daf88966b662d3ca31d.pdf</FileUrl><FileType>pdf</FileType><Percent>100</Percent><EndConvert>True</EndConvert></FileResult>`

The FileUrl always can download a file , it seems that is my previours success conversion's file

The OnlyOffice Version：7.1 with docker

**Comment by ShockwaveNN** [comment]
> The FileUrl always can download a file , it seems that is my previours success conversion's file

Hi, maybe you forgot to change [key](https://api.onlyoffice.com/editors/conversionapi#key) in request to random one?

**Comment by qqxadyy** [comment]
> > The FileUrl always can download a file , it seems that is my previours success conversion's file
> 
> Hi, maybe you forgot to change [key](https://api.onlyoffice.com/editors/conversionapi#key) in request to random one?

Thanks for anwser! But what's the 'key' actually use for?

I try to pass a random string, but I got below error
`<?xml version="1.0" encoding="utf-8"?><FileResult><Error>-4</Error></FileResult>`
