### ISSUE TITLE
Font rendering unreadable on firefox

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DocumentServer#1931]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

Version: 7.0.0.132

### Expected Behavior

The file should be readable on all platforms, all browers, like this (W10 + Firefox 91.8 ESR) :

![image](https://user-images.githubusercontent.com/6248852/195033623-327094fc-8660-43d2-9233-9b7c32ecaa47.png)

### Actual Behavior

On a Windows 7 computer, with Firefox 91.8 ESR of FF Portable 105, I get this, same file : 

![image](https://user-images.githubusercontent.com/6248852/195033910-df51f379-0fbe-4005-bbe4-2a0ae8eb6c24.png)

Look the C15 Cell content and the real content on the function bar.

What I've tried on this computer with no success : 
- New firefox profile with no extensions
- Private navigation windows
- Other firefox version (Portable app)
- Zooming / Dezooming Firefox
- Zooming / Dezooming Onlyofffice
- Disable/Enable hardware acceleration
- Other files, on OO Doc, OO Spreadsheet
- Other fonts (Arial, Times, Calibri)
- Changing Localization 

On Chrome, with the same computer => it works. Unfortunately Firefox is our default browser.
With Google Docs/Spreadsheet on Firefox => no problem.

The faulty combination on this computer seems to be : W7 (not sure if it is relevant here) + Firefox (all versions) + OnlyOffice

### Reproduction Steps

Simply open OnlyOffice file on firefox

**Comment by ShockwaveNN** [comment]
Hi, could you update to latest stable version of DocumentServer v7.2.0?

We've fixed a lot of render issues in last several versions

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
