### ISSUE TITLE
Does onlyoffice support merging two documents?

### ISSUE THREAD

**Issue by DMcoders** [ONLYOFFICE/DocumentServer#1935]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Does onlyoffice support merging two documents?

**Comment by ShockwaveNN** [comment]
Hi, don't think so

Any other editors (MS Office, LibreOffice) allow to do so?

**Comment by DMcoders** [comment]
MS word support this function, insert-->object, tks

**Comment by matveevms** [comment]
Hello, @DMcoders 
At the moment, we have implemented the Combine function (Collaboration > Combine) for documents. 
You can already try out this feature in the new version of DocumentServer. 
Feel free to comment or reopen an issue if you have additional questions.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
