### ISSUE TITLE
RHEL-9 installation fails

### ISSUE THREAD

**Issue by assen-totin** [ONLYOFFICE/DocumentServer#1936]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.2.0-204

### Expected Behavior

The package installs from the OnlyOffice YUM repository on RHEL-9.

### Actual Behavior

The package fails to install from the OnlyOffice YUM repository on RHEL-9.

### Reproduction Steps

1. Install the package using 
yum install onlyoffice-documentserver

### Additional information

[root@cgdconly assen.totin]# yum install onlyoffice-documentserver
Last metadata expiration check: 0:03:01 ago on Wed 12 Oct 2022 09:20:06 PM CEST.
Error: 
 Problem: package onlyoffice-documentserver-7.2.0-204.x86_64 requires msttcore-fonts-installer, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides xorg-x11-font-utils needed by msttcore-fonts-installer-2.6-1.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Reason for the error: the msttcore-fonts-installer you provide in your YUM repository requires xorg-x11-font-utils, but this package does not exist in RHEL-9. Fedora has decided to split this and some other X11-related packages into multiple independent ones, one per utility: see the below links:

https://bugzilla.redhat.com/show_bug.cgi?id=2059773
https://fedoraproject.org/wiki/Changes/XorgUtilityDeaggregation

In addition, the same msttcore-fonts-installer package you provide needs to use mkfontscale, mkfontdir and xset. These are part of two independent RPM packages that you need to add as its dependencies - otherwise the fonts would not build and install:
- mkfontscale
- xorg-x11-server-utils

**Comment by igwyd** [comment]
Hello, @assen-totin.
Thank you for report.
I can confirm - this is bug, issue 59372 in our private issue tracker.

**Comment by igwyd** [comment]
@assen-totin its fixed, we added xorg-x11-font-utils to our official repository. Try to install.

**Comment by ShockwaveNN** [comment]
I'm closing this issue. Problem should be fixed
But please report if got any trouble
