### ISSUE TITLE
Improve the offline experience : let user work on their doc after being reconnected

### ISSUE THREAD

**Issue by ImaCrea** [ONLYOFFICE/DocumentServer#1938]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello there,
At the moment OnlyOffice is very difficult to use online when you have a bumpy connection. Let's take a very usual case : **working during a train trip**. The internet is getting disconnected randomly. What happens is that instead of letting user get back to work after being reconnected, one has to download one's file to not loose change then reload then leave the doc then upload the file then restart... 

What I've seen with our users is that it doesn't help in building trust. They tend to become afraid to lose data once in a while if a random disconnection happens. Some of them actually told us they might go back to GDocs because of that :/ User should not feel anxious when working with OnlyOffice (or any great tool) but feel comfortable and at ease :)

Find here a video showing the experience and comparing it to how it's done in Google Docs:

https://user-images.githubusercontent.com/764332/195861041-75f12b8a-d859-4704-ad96-1228a002d136.mp4

That would be a huge step in (re)building trust in OnlyOffice. And a game changer feature would be to be able to keep working eventhough while I'm offline by caching changes in localstorage and re-sync once it's reconnected for the ultimate flawless experience. 💎

Keep it up, and hopefully this feat. request is helpful. Bravo for all the work done 🙌

Setup : 
- Nextcloud 23.0.9
- OnlyOffice Nextcloud plugin 7.4.4
- OnlyOffice 7.1.123

**Comment by ShockwaveNN** [comment]
Sorry, I don't think it's possible in our architecture

Some time ago, probably around version 5.0 we got a feature, that users can reconnect to a document after the connection lost

And this cause a lot of conflicts and data loss for our users
So we changed that, because data loss in unacceptable for us

A warning message is all we can do that no data is lost and after the connection restore - users can refresh document and restore not-saved information

> it to how it's done in Google Docs:

It's great that Google Docs allows doing so, but their algorithms are private and we don't know how they did it

**Comment by ImaCrea** [comment]
Thanks for your answer. I understand there's a high technical challenge here, but *there is* also data loss with that solution as most user won't care about downloading and then re-uploading by hand. Especially if it happens every 5-10 minutes with a difficult connection.

**Comment by ShockwaveNN** [comment]
This message is introduced because there is no other way, sorry

If someone have difficult connection - it's better to use DesktopEditors
