### ISSUE TITLE
WORKDAY function using -1 day-offset is not working, it counts weekend days

### ISSUE THREAD

**Issue by busted-it-guy** [ONLYOFFICE/DocumentServer#194]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
When you use the workday function (Ex. WORKDAY(B3,-1,$A$11), the day-offset being -1 in between the values of start-day and holiday will cause the function to still count weekends.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

This seems like an issue when you use a NEGATIVE one day offset. When we use a -1 day offset, it counts the weekend days. If you use a -2 day-offset, it will skip the weekend days and count the last 2 workdays.

Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?

All versions we have tried and in all browsers.

I previously put in an issue for +1 workday day-offset but did not try -1.  

The issue was here:

https://github.com/ONLYOFFICE/DocumentServer/issues/184

And the fix bug 36064 resolved that issue of using +1 day-offset is resolved but it did not resolve the ability to use -1 in the WORKDAY function.  

The file is attached which displays the issue

[Workday Function Example-negatives.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1441580/Workday.Function.Example-negatives.xlsx)

**Comment by busted-it-guy** [comment]
Any chance this fix will also be included in 5.1 like the +1 Workday bug here:?
https://github.com/ONLYOFFICE/DocumentServer/issues/184

**Comment by ShockwaveNN** [comment]
@busted-it-guy Yeah, it will! It's already fixed on `develop` - https://github.com/ONLYOFFICE/sdkjs/commit/c9f23742353eabaff68ec833a268422648177e04

**Comment by ShockwaveNN** [comment]
5.1.0 was released, closing bug
