### ISSUE TITLE
All Chinese input method Can't input word to editor

### ISSUE THREAD

**Issue by stepjacky** [ONLYOFFICE/DocumentServer#1940]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Any Windows 

### Version information

All version 

### Expected Behavior

Chinese input method work correctly!

### Actual Behavior

All Chinese input method like  [https://speedxbu.baidu.com/shurufa/ime/setup/BaiduPinyinSetup_5.8.6.5.exe](url) , [http://cdn.qq.ime.sogou.com/e1776319f5ce8444b16002f6a30f629f/634d4f38/QQPinyin_Setup_6.6.6304.400.exe](url)
[https://ime.sogouimecdn.com/202210172041/d5fcb9a08b67a807e86829f77d49ccd5/dl/gzindex/1664357486/sogou_pinyin_125.exe?f=pinyinbanner&dcs=f24fc2a050c22526112e60e83bfd9098](url)
can not input Chinese character to editor!

### Reproduction Steps

1 download Chinese input method tools list above
2 open onlyoffice document server 7.2 on google chrome 49
3 input some text ,but the Chinese character  can't rendered to  the editor 

### Additional information

the browser must be the Google Chrome 49-

**Comment by ShockwaveNN** [comment]
Hi

> the browser must be the Google Chrome 49-

Do you check newer version of Google Chrome? This version I think is 5 years old

**Comment by stepjacky** [comment]
> Hi
> 
> > the browser must be the Google Chrome 49-
> 
> Do you check newer version of Google Chrome? This version I think is 5 years old

of  cause it  works  correctly  in  lasted  version of  chrome,but  also  some user  used  the  oldest chrome  on  windows  xp in internat.

**Comment by ShockwaveNN** [comment]
I don't think we are planning to support such old software, even if google itself do not support it

Please, do not use outdated software, it's very dangerous

**Comment by stepjacky** [comment]
> I don't think we are planning to support such old software, even if google itself do not support it
> 
> Please, do not use outdated software, it's very dangerous

o ,that's right,but the customer's computer for working can't be choose by us ,that's it

**Comment by ShockwaveNN** [comment]
It's sad but in this situation, I think we literally cannot do anything

If those customers are really important - you can contact support@onlyoffice.com (if you got a license) and discuss something like a "special version for your customers" but in other cases - we got no resources to support 6-year-old browsers for free

I'm closing this issue
