### ISSUE TITLE
[FR] Table: repeat table heading

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DocumentServer#1942]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

For documents with long tables spreading several pages it's desirable to tick a setting to repeat table headers on every page as long as the table runs.

Such feature certainly exists in LibreOffice Writer and MS Word.
![LO-Repeat-Header](https://user-images.githubusercontent.com/64358003/196250863-6d5df04d-fb73-4578-bcd6-7cd0a0645820.png)

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
