### ISSUE TITLE
The size of actions exceeds the limitation set for your server

### ISSUE THREAD

**Issue by lnsoft** [ONLYOFFICE/DocumentServer#1950]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.1.34

### Expected Behavior

By modifying the excel document I get the message in question and it is not possible to make any changes. With the previous version 7.2.0-204 everything works correctly.

### Actual Behavior

With the latest version available 7.2.1-34 I can't make any changes to the file, getting the error in question

**Comment by ShockwaveNN** [comment]
Hi, could you provide a file you've used and maybe a video of the error?

Do you change some default values in configs for some options?

**Comment by sabrinamile** [comment]
Hi there,
we have the same problem: our update was about 3 days ago from 7.2.0 to 7.2.1-34.
No changes in configs. We used a diff checker to be sure.

You can test it over here: https://cloud.wzb.eu/s/neXDEZM8P243MzF
Just try to type in something and leave the cell. The error message will show up.

**Comment by ShockwaveNN** [comment]
@sabrinamile Thanks, I can confirm something wrong here, this option should be disabled by default, we'll investigate

**Comment by igwyd** [comment]
Hello @sabrinamile, @lnsoft, we have added a new parameter in [default.json](https://github.com/ONLYOFFICE/server/blob/a46493dd1ab68897a485b6ce5a8fa3f1084d2e8d/Common/config/default.json#L263), I think that for some reason default.json have not updated on the server. Just add it to your ```/etc/onlyoffice/documentserver/default.json``` and restart services ```supervisorctl restart all```, this should solve the problem.

**Comment by sabrinamile** [comment]
Thanks, that worked!

**Comment by igwyd** [comment]
Thank you for report.
I created issue 59501 in our private issue tracker. Its already fixed [here](https://github.com/ONLYOFFICE/sdkjs/commit/46b998c0ed253e2b3961caf92bff34d79368b5b9) and will be released in the next major release.

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
