### ISSUE TITLE
 hints appear that completely replace the entered text. How to remove it.

### ISSUE THREAD

**Issue by alex-sky-cloud** [ONLYOFFICE/DocumentServer#1951]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

Desktop Editors версия 7.2.1.36

### Expected Behavior

when typing - there were no annoying prompts.

### Actual Behavior

 After the update, hints appear that completely replace the entered text. How to remove it.

### Reproduction Steps

Input text

### Additional information

1920x1080 screen size

**Comment by ShockwaveNN** [comment]
Hi, could you clarify what you mean? Maybe record a video or a screenshot

I don't understand what you mean at all

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
