### ISSUE TITLE
BankerRound support

### ISSUE THREAD

**Issue by JiffyChen** [ONLYOFFICE/DocumentServer#1953]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Add BankerRound support

**Comment by ShockwaveNN** [comment]
Hi, please provide some description what do you mean by this, with some link to documentation

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
