### ISSUE TITLE
Recover lost onlyoffice document

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/DocumentServer#196]
Hey,
I would like to ask if it's possible to recover old onlyoffice documents.
I unfortunately purged the PostgreSQL database but still have all cached files in /var/lib/onlyoffice.
Are old revision still stored inside the Editor.bin files?

Best regards,
Jonas

**Comment by trofim24** [comment]
@onny 
Have you lost the original documents and are trying to restore them from the file cache? Did I understand you correctly?

**Comment by onny** [comment]
Yes, that's what I wanted to do

**Comment by trofim24** [comment]
Make a zip-archive inside which will be `Editor.bin` and name it according to the format. For example, if it was `docx`, then the archive should have a `.docx` extension.
Then open the editor and download as.

**Comment by onny** [comment]
Okay thank you, I'll give it a try 👍

**Comment by rasos** [comment]
I have rescued an `Editor.bin` file from the cache (OO in Docker with nextcloud, which has not been saved properly). If I try to open the xlsx with the OO desktop editor I get an error. If I open it as binary I see `DOCY;v10;0;  ....` . Any other hint how to recover it?
