### ISSUE TITLE
Inserting a row - "Insert Top" is incorrect

### ISSUE THREAD

**Issue by hl2guide** [ONLYOFFICE/DocumentServer#1963]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.1.1.57

### Expected Behavior

Applies to the English language for the installation.

In the Spreadsheet app try to insert a row above the current line by right clicking the row numbers to the left.

The menu item should say "Insert row above" instead of "Insert Top".

"Top" is incorrect.

### Actual Behavior

The menu items says "Insert Top".

### Reproduction Steps

In the Spreadsheet app try to insert a row above the current line by right clicking the row numbers to the left.

View the context menu.

### Additional information

![example](https://user-images.githubusercontent.com/17044982/187945953-a7175ad4-ad46-4e0e-9f90-601ab50441b8.jpg)

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/web-apps/commit/76cefaad20daa0263d3fd20e08186f6ff9363dbc) in version 7.3.
