### ISSUE TITLE
Mobile web client pages could not be built.

### ISSUE THREAD

**Issue by qianwch** [ONLYOFFICE/DocumentServer#1964]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.2.1-34

### Expected Behavior

./automate.py server
should successfully build the mobile web pages.

### Actual Behavior

cd tools/linux
./automate.py server
I would get the error reports. And the mobile pages does not be generated.

**Comment by ShockwaveNN** [comment]
Please do no make duplicates https://github.com/ONLYOFFICE/build_tools/issues/543
