### ISSUE TITLE
Typing `constructor` into Spreadsheet Editor cause `Cannot read properties of undefined (reading 'substring')`

### ISSUE THREAD

**Issue by c0repwn3r** [ONLYOFFICE/DocumentServer#1969]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

7.2.0.204

### Expected Behavior

Typing `constructor` would not cause an error of the spreadsheet editor. This has never worked to my knowledge.

### Actual Behavior

Upon typing the `r` in the word `constructor`, editing will be disabled and an error popup will appear. Typing `constructo` works fine, but immediately upon typing the `r` at the end, the error appears.

### Reproduction Steps

1. Open up the Spreadsheet Editor
2. In any cell, type `constructor`
3. Observe the error pop up

### Additional information

The following error occurs inside the editor console on the web app:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
    at CellEditor._onWindowKeyPress (sdk-all.js?ver=5.1.0-1667066034249:14472:171)
    at Api.onKeyPress (sdk-all.js?ver=5.1.0-1667066034249:14586:40)
    at CTextInput.onKeyPress (sdk-all.js?ver=5.1.0-1667066034249:27609:325)
    at HtmlArea.onkeypress (sdk-all.js?ver=5.1.0-1667066034249:27580:86)
```
It is unknown to me if this error also occurs inside the desktop editor; however identical erroneous behavior can be observed.

**Comment by ShockwaveNN** [comment]
This issue is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/b214017e25d839bf256f1d1309e03fcedb1ef5ed in will be released in next major release in several months

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
