### ISSUE TITLE
Spreadsheet: Insert/Delete entire row keyboard shortcut

### ISSUE THREAD

**Issue by somoant** [ONLYOFFICE/DocumentServer#1972]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
Please add insert/delete entire row shortcut to Spreadsheet. Usually ctrl + "+"/"-" when is entire row selected.

**Comment by ShockwaveNN** [comment]
Closing this issue since it was resolved a long ago
