### ISSUE TITLE
Bug: Browse windows to select file to open unusable

### ISSUE THREAD

**Issue by massimolamanna** [ONLYOFFICE/DocumentServer#198]
Hi,
this is a regression. The window I open to browse my disc and select a file to open, all the characted (file names, directories) are replaced by a bogus char  and they are unreadable.

I attach a view of the windows.

The current version is 4.4.1.338 on Ubuntu

My machine uses:
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

but I had some problems also on 17.04

Thank you in advance,
Massimo

![screenshot from 2017-11-09 14-27-41](https://user-images.githubusercontent.com/5574644/32609004-69d71696-c55e-11e7-958b-4e0eb48d4a59.png)

**Comment by agolybev** [comment]
Hi @massimolamanna, According to your screenshot you use DesktopEditors. It's another product than DocumentServer. Please, report this issue to [another](https://github.com/ONLYOFFICE/DesktopEditors) repository.

**Comment by ShockwaveNN** [comment]
And this is possible duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/52
