### ISSUE TITLE
In the arm64 architecture, an error occurs when deploying onlyoffice. The error message is as follows: Waiting for connection to the localhost host on port 5432

### ISSUE THREAD

**Issue by zhouyt168** [ONLYOFFICE/DocumentServer#1981]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

onlyoffice/documentserver:7.2

### Expected Behavior

In amd64, the normal situation should be as follows
![IP)J{O6T`YQ1P@03Y0)_7DD](https://user-images.githubusercontent.com/92049147/199689579-5205d5a4-d336-4daa-8f53-7b4b2e34d2bf.png)

### Actual Behavior

An exception occurred while accessing the server deployed in the arm64 architecture
In log ： Waiting for connection to the localhost host on port 5432

### Additional information

After I redeploy different versions, I found that 7.1.1.23-arm64 can start the docker container normally, but some requests cannot be accessed
![$9C7 UIJ~`KD830XCR$T3MV](https://user-images.githubusercontent.com/92049147/199691038-49d2f317-3208-4af0-9fc2-0efca1ed9a79.png)

**Comment by ShockwaveNN** [comment]
Please do not duplicate issues https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/538
