### ISSUE TITLE
Document info not included as metadata in generated PDF files

### ISSUE THREAD

**Issue by fathyar** [ONLYOFFICE/DocumentServer#1982]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

Document info (e.g. author, title, subject) should be included as metadata in generated PDF files.

### Actual Behavior

Currently, the document info is not included as metadata in generated PDF files.

### Reproduction Steps

1. Create a new (Document, Spreadsheet, Presentation, or Form Template) document.
2. Go to the **File** tab and then select **Document Info**.
3. Fill out the document properties forms (Title, Subject, Comment, Author). Then click the **Apply** button.
4. Save the document.
5. To generate a PDF file of the document (i.e. saving the document as a PDF file), go back to the **File** tab and then select **Save as** (or you can just press the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> hotkey). And then a dialog window will pop up. In the dialog window, choose the document format with your preferred PDF version (`Portable Document (*.pdf)` or `Portable Document /A(*.pdf)`).
6. Open the generated PDF file with any PDF viewer. (tested on: Evince, Okular, Foxit Reader)
7. View document properties of the file.

### Additional information

This behavior is also present in previous versions of onlyoffice.

**Comment by LuckySpecialist** [comment]
Hi @fathyar,
We have released a new version of editors 7.3, which includes a fix for saving metadata when exporting to PDF format.
Can you check it and let me know if everything is working correctly for you?

**Comment by fathyar** [comment]
Thanks. I've checked it out and done some tests with both PDF formats. The document info is now shown in the PDF metadata. So, I can say that everything is working properly now.

**Comment by DenisDeeSign** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
