### ISSUE TITLE
Unable to display watermark on a PDF file using Chinese font like simsun.ttf or others

### ISSUE THREAD

**Issue by teqian** [ONLYOFFICE/DocumentServer#1985]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2

### Expected Behavior

Display Chinese watermark

### Actual Behavior

Unable to display Display Chinese watermark  on a PDF file

### Reproduction Steps

Just open a PDF file with watermark using Chinese font like simsun.ttf or others

**Comment by ShockwaveNN** [comment]
Hi, please attach example file

**Comment by teqian** [comment]
Hi, this is a PDF file with watermark text in three common Chinese fonts. Nextcloud flyer.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/9945891/Nextcloud.flyer.pdf)

**Comment by teqian** [comment]
> Hi, please attach example file



> Hi, please attach example file


Hi, this is a PDF file with watermark text in three common Chinese fonts. 
Nextcloud flyer.pdf(https://github.com/ONLYOFFICE/DocumentServer/files/9945891/Nextcloud.flyer.pdf).

**Comment by ShockwaveNN** [comment]
Yep, thanks, I can confirm something is wrong

**Comment by VladimirProkofiev52** [comment]
Hello.
@teqian, I can confirm - this is bug, issue 59642 in our private issue tracker.
Thank you for report.

**Comment by teqian** [comment]
> Hello. @teqian, I can confirm - this is bug, issue 59642 in our private issue tracker. Thank you for report.
Welcome.  Looking forward to fixing this bug.

**Comment by Rita-Bubnova** [comment]
This issue fixed in the next major version.

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
