### ISSUE TITLE
Calc is changing column with and date format in saved and reopend spreadsheet

### ISSUE THREAD

**Issue by Codeleiche** [ONLYOFFICE/DocumentServer#1990]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

When saving the spreadsheet with specific format (column with, date format) after reopening the sheet should be the same.

### Actual Behavior

The sheet changes after reopening, columns are getting smaller and date format gets changed (from 03.08 a 2022,August,03).

### Reproduction Steps

- open sheet, highlight a column,  use custom time format with home -> Number Format -> More Formats -> Date -> 15.08
- save
- close
- reopen

**Comment by alinasafonova** [comment]
Hello, @Codeleiche

Please, specify your region settings (File -> Advanced Settings -> Region).

**Comment by Codeleiche** [comment]
"Deutsch (Deutschland)" Germany

**Comment by alinasafonova** [comment]
Unfortunately I can't reproduce the problem by specified steps.
Could you please attach video?

**Comment by Codeleiche** [comment]
Hello alinasafonova, I'm super sorry for responding that late, I missed the notification of your answer. here is a video showcastig my problem:


[onlyoffice_date_problem.webm](https://user-images.githubusercontent.com/29143641/204029292-368ea0d7-64aa-4076-a54d-ce9c2a064b5c.webm)

**Comment by Codeleiche** [comment]
I'm sorry to wast you time. The problem o cures in the Desktop edition, not in the DocumentServer.
