### ISSUE TITLE
update onlyoffice

### ISSUE THREAD

**Issue by jvelarde-mpi** [ONLYOFFICE/DocumentServer#1991]
### Discussed in https://github.com/ONLYOFFICE/DocumentServer/discussions/1989

<div type='discussions-op-text'>

<sup>Originally posted by **jvelarde-mpi** November  7, 2022</sup>
Hello new to forum, I just updated my onlyoffice to latest version, but now it shows this "Test sample" page. Before I updated it said "document server ready".  How do I disabled this test sample ? thanks.

https://onlyoffice.modernparking.net/welcome/
</div>

**Comment by ShockwaveNN** [comment]
I'm close this issue since it's more a discussion than an issue and there is already a discussion
