### ISSUE TITLE
Can not copy/paste images from MS word

### ISSUE THREAD

**Issue by DMcoders** [ONLYOFFICE/DocumentServer#1992]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.1

### Expected Behavior

Can not copy/paste images from MS word only red X
![1667912615848](https://user-images.githubusercontent.com/16876873/200572959-02671bec-462f-4888-b00c-62349fea4eea.png)

### Actual Behavior

Can not copy/paste images from MS word only red X
![1667912615848](https://user-images.githubusercontent.com/16876873/200573066-af4abe07-de24-4b68-8665-1d5fb23480e5.png)

### Additional information

![1667912615848](https://user-images.githubusercontent.com/16876873/200573175-4c93e65b-66d2-415a-9937-edff34eca1f3.png)

**Comment by ShockwaveNN** [comment]
Hi, could you update to the latest stable of DocumentServer, add information about which browse you're using and which OS and MS Word version

**Comment by Rita-Bubnova** [comment]
Maybe, this's a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/1069.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
