### ISSUE TITLE
Fail to install msttcore-fonts-installer-2.6-1.noarch.rpm

### ISSUE THREAD

**Issue by c0r3dump3d** [ONLYOFFICE/DocumentServer#1998]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.2

### Expected Behavior

Trying to install msttcore-fonts-installer-2.6-1.noarch.rpm package in Centos 7.

### Actual Behavior

Following the documentation (https://helpcenter.onlyoffice.com/installation/docs-community-install-centos.aspx), when I try to install msttcore-fonts-installer-2.6-1.noarch.rpm, fail:

![imagen](https://user-images.githubusercontent.com/5602401/201052943-0af03487-3319-4c27-bb3a-e236e339d78c.png)

**Comment by ShockwaveNN** [comment]
Hi, seems something wrong with sourceforce site

Try this

rpm -i https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm

**Comment by ShockwaveNN** [comment]
I've created issue https://github.com/ONLYOFFICE/helpcenter/issues/40 in our private repo for helpcenter to fix it
