### ISSUE TITLE
Table of contents is Word Editor

### ISSUE THREAD

**Issue by liangzhengai** [ONLYOFFICE/DocumentServer#20]
Hello
i'm one of users for your document server.
it is good software.
i like it but there isn't table of contents in word editor.
table of contents is very critical function in document editing.

How can i implement it?
What is problem to implement the table of contents?

in zoho, they implemented table of contents.
Thank you.

**Comment by liangzhengai** [comment]
I think that it is important to be better than zoho

**Comment by nommaz** [comment]
Google also have a reduced function TOC but gets the job done. I hope it can be added soon.

**Comment by ibnpetr** [comment]
Hello 
We understand that this is an important feature, it's already on our roadmap
We will let you know as soon as it is released, [keep in touch](https://github.com/ONLYOFFICE/DocumentServer/releases)

**Comment by rjurado01** [comment]
+1

**Comment by cpot** [comment]
+1

**Comment by tomaszbrudzinski** [comment]
+1

**Comment by etatuev** [comment]
+1

**Comment by bongtrop** [comment]
+1

**Comment by zisuu** [comment]
+1

**Comment by Kualt** [comment]
+1

**Comment by TMHBOFH** [comment]
+1

**Comment by richardklose** [comment]
+1

**Comment by magican** [comment]
+1

**Comment by dkorzhevin** [comment]
+100500

**Comment by alexpashkov** [comment]
+1

**Comment by Floflobel** [comment]
+1

**Comment by SanguisFerrum** [comment]
+1

**Comment by KirillovIlya** [comment]
It will be added in the next stable version.

**Comment by waldek1984** [comment]
+1

**Comment by flaviobattimo** [comment]
+1

**Comment by yannicka** [comment]
@KirillovIlya: When will this next version be released?

**Comment by ShockwaveNN** [comment]
@yannicka wait until febuary or at least march of 2018, we already have TOC in dev version and it's working pretty good :)

**Comment by ShockwaveNN** [comment]
Table of content was added in 5.1.0
