### ISSUE TITLE
Filters in columns showing dates should be grouped

### ISSUE THREAD

**Issue by sigulete** [ONLYOFFICE/DocumentServer#2000]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

When filtering a column showing dates, it would be ideal to show the information grouped by Year, Month and Day.
I'm attaching a screenshot to explain better.

![Screenshot from 2022-11-13 14-09-19](https://user-images.githubusercontent.com/35115643/201503805-7ac9e17d-e5ef-4920-bd27-b7a08e93d160.png)

**Comment by Rita-Bubnova** [comment]
Hello, @DarhonSoftware.
Thank you for the enhancement. 
This is known as issue 27601 in our private issues tracker.

**Comment by Rita-Bubnova** [comment]
This was fixed (https://github.com/ONLYOFFICE/sdkjs/commit/54a4c56342bcd421f318a10c6c1d012ca693404e) in the version 7.5.
