### ISSUE TITLE
multiple reverse proxy x-forwarded-*  headers comma separated list

### ISSUE THREAD

**Issue by kazimsarikaya** [ONLYOFFICE/DocumentServer#2001]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1.34

### Expected Behavior

document server should handle x-forwarded-for and x-forwarded-host headers if there is multiple reverse proxies.

### Actual Behavior

document server sends location header for redirect with comma separated list of x-forwarded-host. if there is multiple reverse proxies present proxies add hosts with comma separated.

```
...
X-Forwarded-Proto: https
X-Forwarded-Host: example.com, example.com
...
```

and the response contains

```
...
Location: https://example.com, example.com/welcome/
...
```

### Reproduction Steps

install two reverse proxy servers.  in our conf, we have one for ssl termination and second for load balancing.

**Comment by kazimsarikaya** [comment]
Is there a any progress? The incorrect line is:

https://github.com/ONLYOFFICE/server/blob/a46493dd1ab68897a485b6ce5a8fa3f1084d2e8d/Common/sources/utils.js#L668

forwardedHostHeader should be parsed, should not used directliy.

**Comment by igwyd** [comment]
Hello @kazimsarikaya, i set up 2 proxies in front of the document server as you mentioned, one with loadbalancer and second with ssl ant it work for me. We have examples for nginx, maybe it help you https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

**Comment by kazimsarikaya** [comment]
Hi @igwyd , solutions at that link disables apache's auto adding proxy headers. Hence I added a last nginx sidecar for onlyoffice to edit x-forward-for header. It is an ugly solution however it works.
