### ISSUE TITLE
Cannot found Taiwan Region.

### ISSUE THREAD

**Issue by PasserDreamer** [ONLYOFFICE/DocumentServer#2004]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1.34

### Expected Behavior

Region menu has Taiwan options.

### Actual Behavior

Region menu missing Taiwan options.

**Comment by ShockwaveNN** [comment]
Hi, do you mean Taiwan region in spreadsheet settings menu?

**Comment by PasserDreamer** [comment]
yes

**Comment by LuckySpecialist** [comment]
Hi @PasserDreamer,
We have released a new version of editors 7.3, which includes the region you need.
Can you check it and let me know if everything is working correctly for you?

**Comment by LuckySpecialist** [comment]
Fixed in the https://github.com/ONLYOFFICE/web-apps/pull/2079.
Issue can be closed.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
