### ISSUE TITLE
Print option on Spreadsheet editor really weird behaviour

### ISSUE THREAD

**Issue by KrLx1994roller** [ONLYOFFICE/DocumentServer#2009]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.1.34

### Expected Behavior

I expected the print option to print the spreadsheet as I see it on my computer, but it does not. This issue did happen as well in previous versions of DocumentServer.

### Actual Behavior

Spreadsheets adds plenty of space inside of some of the cells themselves, thus the PDF result is way bigger (in length) than it should. When going back to the spreadsheet, all the cells' UI is buggy until I scroll down and back up so that the cells reload and then I get to see the bigger cells that got printed. If I apply some sort of format to those cells (like center text vertically), the cells' inner space goes back to normal.

### Reproduction Steps

Initial state:

<img width="776" alt="1" src="https://user-images.githubusercontent.com/1145054/203178701-d74e49fa-49c7-4949-8d36-a9f63250bfaf.png">

1. Click print icon (command + P)
2. Select "Current sheet"
3. Click "Save & print"
4. Preview will open in Google Chrome with and you can see already how the inside of the cells is way bigger than when you clicked on print
<img width="1174" alt="2" src="https://user-images.githubusercontent.com/1145054/203178720-3a38101a-a9bb-47e6-9596-c14ba086f8c6.png">

5. Click "Cancel" to go back to the spreadsheets
6. Now all the cells show the "normal" size but when you click on them, they are bigger, thus the selection being buggy
7. Scroll down and back up for the cells to reload and show its new bigger size
<img width="762" alt="3" src="https://user-images.githubusercontent.com/1145054/203178734-96e7a01c-029b-467f-a858-71bae5b72651.png">

8. Select all those row and apply some sort of format (center text vertically)
9. Cells will go back to normal

**Comment by LuckySpecialist** [comment]
Hi @KrLx1994roller!
Please briefly describe your environment (OS version, display and its resolution, interface scale)?

**Comment by KrLx1994roller** [comment]
Hi!

Sure:
- OS version: Mac OS Monterey 12.4
- Display: 16-inch (3456 × 2234)
- Interface scale: 100%

If you need anything else please let me know.

Thanks in advance!

**Comment by LuckySpecialist** [comment]
Can you attach your source file on which the problem was shown?

**Comment by KrLx1994roller** [comment]
I'm sorry, I cannot do that anymore... I managed to fix the issue by removing completely the format on all the cells of the document, re-formatted it and that fixed the issue. I'm really confused about this behaviour. Same formatting as before and now printing works properly every time, no matter how much I change the format of the cells of the document...
