### ISSUE TITLE
This is not enough, please do not ignore parts of my message, we're not wizards and the more information you provide - the more efficiently we can help you

### ISSUE THREAD

**Issue by Janeisme-lll** [ONLYOFFICE/DocumentServer#2011]
This is not enough, please do not ignore parts of my message, we're not wizards and the more information you provide - the more efficiently we can help you

_Originally posted by @ShockwaveNN in https://github.com/ONLYOFFICE/DocumentServer/issues/2007#issuecomment-1324693889_

**Comment by ShockwaveNN** [comment]
What are you doing, please stop spamming
