### ISSUE TITLE
How do I connect http with a virtual box?

### ISSUE THREAD

**Issue by lsj020221** [ONLYOFFICE/DocumentServer#2013]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.
I am using Oracle Cloud by connecting it to the next cloud with http
If you keep trying, it won't work with http, it'll only connect to https
![ssss](https://user-images.githubusercontent.com/118890357/203516759-76883dcf-475a-4192-ae8b-183ba0a65c21.PNG)

**Comment by ShockwaveNN** [comment]
I'm sorry, but we're not aware of Oracle Cloud and how it works, I think you better to contact it's support

**Comment by trofim24** [comment]
@lsj020221 we've released 7.4.1 verson and connector to nextcloud [8.2.0](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/CHANGELOG.md#820)
Do you still have problems with this?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
