### ISSUE TITLE
Font garbled characters

### ISSUE THREAD

**Issue by wwtaoqaq** [ONLYOFFICE/DocumentServer#2014]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

6.4.2

### Expected Behavior

When I used onlyoffice to open a PDF document, I found that part of the text was garbled. Is it the font?

### Actual Behavior

The first picture below shows the opening of Onlyoffice, while the second picture shows the normal opening. 

### Reproduction Steps

null

### Additional information

![error](https://user-images.githubusercontent.com/96608142/203523811-9ab11ce0-6f39-4d13-867c-a198a1a99c3b.png)

![normal](https://user-images.githubusercontent.com/96608142/203523821-8e77ac5b-b638-45d8-969b-7a3c5f8906ab.png)

**Comment by ShockwaveNN** [comment]
> Version information
> 6.4.2

This is very old version, please upgrade to latest stable and recheck a file, we made a lot of improvements in font render

**Comment by wwtaoqaq** [comment]
I just installed version 7.1.1.7 of the software and still have this problem.

**Comment by ShockwaveNN** [comment]
7.1.1.7 is not the latest version, the latest is v7.2.1

**Comment by chinaguole** [comment]
字体文件不对，更换字体文件并fc-cache -fv 再document-generation...

**Comment by trofim24** [comment]
for rebuild cache in linux use [fc-cache](https://linux.die.net/man/1/fc-cache) command
@wwtaoqaq if you have any questions or problems create new issue
This issue was closed due to no response.
