### ISSUE TITLE
How to setup document server to use custom URL base path ?

### ISSUE THREAD

**Issue by SuperdukeGates** [ONLYOFFICE/DocumentServer#2016]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I want to mitigate the rude and malicious probe to my document server. There comes a simple idea that to put the real document server base url under a custom base url rather than /.
```
https://ds.example.tld/  ==>  https://ds.example.tld/m5Hm33D2/
```
For this purpose, the web server `rewrite` like directives are not the options because the `rewrite` helps client to learn the real document base URL. I need a native solution.

I also have nextcloud with onlyoffice connector app installed. This setup works fine. However,  as I said I want to change the document server's base URL to secure my server.

How can I do this ?
Or would you please add this feature ?

Thanks.

**Comment by igwyd** [comment]
Hello @SuperdukeGates, sorry for the late reply.
You can use reverse proxy for this, we have examples [here](https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx) (with Virtual path in your case).

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by joshuajeschek** [comment]
Hi, did you end up finding a solution for this?
