### ISSUE TITLE
Double Click to select word and following words

### ISSUE THREAD

**Issue by serhumanos** [ONLYOFFICE/DocumentServer#2017]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I think that is a good idea to add "double click" selecting word/words like others editors (vscode, kate, firefox address bar in linux) keeping hold de las click and dragging cursor over the following (or back ) words

https://user-images.githubusercontent.com/7744939/203865521-4a43cc57-d493-4e2b-aee0-f687bf1153e8.mp4

**Comment by Rita-Bubnova** [comment]
Hello, @serhumanos.
This is known as issue 49735 in our private issue tracker. 

Thank you for the enhancement.

**Comment by HectorB-2020** [comment]
I beg your pardon, what's the gist of the problem?
Double click selects a word, triple click selects a paragraph, everything is like in MS Word.
:confused:

**Comment by HectorB-2020** [comment]
Interesting, I've found another request for the same. :smile: 
* https://github.com/ONLYOFFICE/DesktopEditors/issues/311

**Comment by Rita-Bubnova** [comment]
@HectorB-2020, you're right. 
There are some differences in the steps to reproduce. But we think that the problems have one reason.

This is a duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/311.
