### ISSUE TITLE
Cannot customize the total number of pages

### ISSUE THREAD

**Issue by LeoJRH** [ONLYOFFICE/DocumentServer#2019]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello:
 When creating a document with a home page, I cannot customize a total number of pages. For example, the total number of pages in the document is 41 pages. I want the page number to be displayed as 1/40 to 40/40. Now the total number of pages can only be inserted as 41。If I manually change 41 to 40, when I increase the number of pages, the total number of pages cannot be changed, and it is always fixed at 40。I want to set the total number of pages to be automatically deducted according to the number of my covers。
Thanks a lot.

**Comment by ElenaMaaya** [comment]
Hello @LeoJRH !
Thank you for report!
This may solve your problem. 
Try these settings:
Header and footer settings -> Options -> Сlick checkbox "Different first page" 
Header and footer settings ->Page Numbering ->Start at -> 0
![page](https://github.com/ONLYOFFICE/DocumentServer/assets/96118677/10443bee-665a-4805-b590-968c62124ab8)


This option will show the number of pages without the home page.

If you want to see another option, please send a screenshot or file with concrete example.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
