### ISSUE TITLE
There are blank pages in the import document preview 

### ISSUE THREAD

**Issue by huzedong2015** [ONLYOFFICE/DocumentServer#2025]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2

### Expected Behavior

Onlyoffice and MS Word display the same
No additional blank pages

### Actual Behavior

One more blank page

### Reproduction Steps

1、Import the [test.doc](https://github.com/huzedong2015/pictures/blob/6dff17fb2c520ed097f3454adea13538a5181569/test.doc) file in the example
2、open the edit page

### Additional information

Convert doc to docx. It works normally

Possible causes：
1、First Page has “End of Section” (Open [test.doc](https://github.com/huzedong2015/pictures/blob/6dff17fb2c520ed097f3454adea13538a5181569/test.doc) with MS Word)

**Comment by ElenaMaaya** [comment]
Hello @huzedong2015! Thanks for the report. This issue will be fixed in the next release. We advise you to follow the updates.

**Comment by ElenaMaaya** [comment]
Hello @huzedong2015!  This issue is fixed in DocumentServer and DesktopEditors v7.3.0.
Thanks for contacting us!
