### ISSUE TITLE
Shared editing doesn't work

### ISSUE THREAD

**Issue by tthdvd** [ONLYOFFICE/DocumentServer#203]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
When we open a file toghether, just some people see eachother (not everyone), we didn't find deterministic behavior .
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
More then one people open the file.
**What is the expected behavior?**
We should see each other work.
**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
5.0.4.15
**Operating System:**
Ubuntu 16.04.03 LTS
**Browser version:**
Chrome 61.0.3163.100

**Comment by ShockwaveNN** [comment]
Does all people have `fast` coedit mode?

**Comment by tthdvd** [comment]
Yes, they're in fast coedit mode.
but it's very strange, becouse two people see eachother and 2 different people see eachother.

**Comment by ShockwaveNN** [comment]
Wich product calls for those users? Does this `nextcloud\owncloud` integration, `document-server-integration` or `onlyoffice-communityserver`?

**Comment by tthdvd** [comment]
This is a nextcloud integration

**Comment by ShockwaveNN** [comment]
Ok, duplicate this bug in https://github.com/ONLYOFFICE/onlyoffice-owncloud please
