### ISSUE TITLE
In Onlyoffice Spreadsheet when you insert a row above a chart, it does not update the data range

### ISSUE THREAD

**Issue by MancomunitatRiberaAlta** [ONLYOFFICE/DocumentServer#2030]
Hi,
In Onlyoffice Spreadsheet when you insert a row above a chart, it does not update the data range. 
![añadir_filas_onlyoffice2](https://user-images.githubusercontent.com/119578016/205055834-3852c293-1f3b-4c52-93cb-be9a1de5e4f9.png)
![añadir_filas_onlyoffice](https://user-images.githubusercontent.com/119578016/205055869-8aeac689-1544-4521-a0bf-b589f45bd2b7.png)

thanks,

**Comment by DenisDeeSign** [comment]
Moving this issue to DocumentServer repo, since the issue in not related to CommunityServer.

**Comment by Rita-Bubnova** [comment]
Hello, @MancomunitatRiberaAlta. 
This is a duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/744.
