### ISSUE TITLE
"An error occurred during the work with the document"

### ISSUE THREAD

**Issue by jhthorsen** [ONLYOFFICE/DocumentServer#2032]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1.34

### Expected Behavior

I expect to able to open a XLSX file and edit it. I have many other XLSX files that works perfectly, but this one does not. The only two things I can think of is:

1. This file has a lot of Japanese in it.
2. It has multiple pivot tables.

I'm sorry, but I would not want to share this specific file.

### Actual Behavior

Instead of being able to edit the file, I get this error message:

<img width="449" alt="Screenshot 2022-12-05 at 23 00 49" src="https://user-images.githubusercontent.com/45729/205655474-41cf23e9-90d8-4f71-9344-e36c62136af0.png">

Sorry for the screenshot, but I'm unable to select the text inside that popup box.

I used the developer tools and saw this:

Raw error message:
<img width="695" alt="Screenshot 2022-12-04 at 20 15 02" src="https://user-images.githubusercontent.com/45729/205656397-3bd1af7f-80d4-494a-8692-ec1008600f91.png">

After prettyprinting those lines:
<img width="489" alt="Screenshot 2022-12-04 at 20 14 32" src="https://user-images.githubusercontent.com/45729/205656386-926c1b79-1712-44a0-a1ea-d9fca8accf5c.png">

### Reproduction Steps

I open my private Nextcloud instance, click on the XLSX file, and after Onlyoffice is (seemingly) done loading, I get the error message above, and I'm only able to view the document, and not edit it.

### Additional information

I'm running Openoffice in docker.

I got Nextcloud 25.0.1 and https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/v7.6.8

I got nginx as a reverse proxy in front of both Openoffice and Nextcloud.

**Comment by alinasafonova** [comment]
Hello, @jhthorsen

Sorry, but we can't reproduce this problem without file.
Maybe you could replace your private data with some samples? Or send your file to our email files@onlyoffice.com

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
