### ISSUE TITLE
OnlyOffice / Seafile silent error on file save when disk is full

### ISSUE THREAD

**Issue by bougault** [ONLYOFFICE/DocumentServer#2033]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.0.1

### Expected Behavior

Document Editor should send user a UI feedback when an error occurred while saving the document.

### Actual Behavior

Document editor displays "All Changes saved" while an error writing the file occurred on the Seafile backend. Here is the log from Seafile backend: 

```
2022-12-06 11:34:25 upload-file.c(2078): [upload] Failed to write temp file: No space left on device.
```

Error seems to be silently ignored on the frontend side. Nothing in the web console nor in the OnlyOffice UI.

### Reproduction Steps

1. Have OnlyOffice + Seafile setup
2. Create a Office file while the disk is not full yet (otherwise impossible to create that file)
3. Make the disk full
4. Go edit the Office file previously created
5. Save. Frontend displays "All Changed Save" while Seafile backend logs an error:
```
2022-12-06 11:34:25 upload-file.c(2078): [upload] Failed to write temp file: No space left on device.
```
6. Reload page or re-open document. Changes are lost.

**Comment by igwyd** [comment]
Hello @bougault, i think you need to write a issue to the Seafile with this behavior. The DocumentServer in this case has no information about the free space in the Seafile. I checked several integrations such as ONLYOFFICE CommunityServer, Nexcloud and Owncloud, they all stop working and don't allow you to open files.

**Comment by bougault** [comment]
Thanks for your feedback @igwyd 
I was not sure where to open the issue as the Seafile backend logs the error. Issue opened on Seafile project.
