### ISSUE TITLE
3 Colors SCale Formatting Rules Error

### ISSUE THREAD

**Issue by UbioZur** [ONLYOFFICE/DocumentServer#2036]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

7.2.1 App Image

### Expected Behavior

I would expect 12 to be considered higher than 9.
It also happened in a previous version, which I replaced for an updated.

### Actual Behavior

Error Message: "The value for the Maxpoint must be greater than the value for the Midpoint."

Any Maxpoint number that is not the Midpoint number is considered lowered than the Midpoint number.

### Reproduction Steps

- Create a spreadsheet
- Select any single cell (empty or not)
- Add Conditional Formatting
- Select 3 Color Scale
- Minpoint: Number 1
- Midpoint: Number 9
- Maxpoint: Number 12
- Press OK
- Enjoy being told 12 is lower than 9.
- Press OK
- Maxpoint: Number 20000
- Press OK
- Enjoy being told 20000 is lower than 9.
- Press OK
- Maxpoint: Number 8
- Press OK
- Enjoy being told 8 is lower than 9.
- Press OK
- Maxpoint: Number 9
- Press OK
- It works, but what's that's a 2 color scale! not 3

### Additional information

PS: Maybe on the operating system of the bug reporting form, you should add "App Image" "Snap" "Flatpak"

**Comment by alinasafonova** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/938bf0ef1ff734945fda6cbece1b99d4200d78c4
It will be released as v7.3.0
