### ISSUE TITLE
Copy multiple pictures to display exceptions in the edited word

### ISSUE THREAD

**Issue by Janeisme-lll** [ONLYOFFICE/DocumentServer#2037]
Hello, I found that multiple images copied from other files cannot be displayed in the edited word, but a single image displays normally. Do you want to set parameters?
![image](https://user-images.githubusercontent.com/27803972/202960825-d56977b6-fed8-476c-9c30-ed63bb1de2a5.png)

**Comment by LuckySpecialist** [comment]
Hi @Janeisme-lll!
At the moment, this limitation cannot be circumvented in a web application. In the new version we will add a hint about this.
Please use the desktop version, where this problem does not exist.

**Comment by LuckySpecialist** [comment]
Hint added to web app:
> We can't paste this image from the Clipboard, but you can save it to your device and 
> insert it from there, or you can copy the image without text and paste it into the document.

This issue can be closed.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
