### ISSUE TITLE
Show office files on web pages only

### ISSUE THREAD

**Issue by mingweiY** [ONLYOFFICE/DocumentServer#2038]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Thanks to the author for contributing to such a huge and powerful project, but now I just want to do the function of browsing files online. Which part of the code should I focus on? I have studied this project for two days, but the progress is not smooth, because I am not familiar with js and c++. We look forward to your help and reply. Thank you.

**Comment by stepjacky** [comment]
好好看看官方example

**Comment by mingweiY** [comment]
> 

谢谢回复，我是想找到这部分代码单独拿出来，因为只浏览的话还要带着MQ、mysql这些太庞大了。您知道涉及那些代码，麻烦不吝赐教。谢谢。

**Comment by mingweiY** [comment]
> 好好看看官方示例

谢谢回复，我是想找到这部分代码单独拿出来，因为只浏览的话还要带着MQ、mysql这些太庞大了。您知道涉及那些代码，麻烦不吝赐教。谢谢

**Comment by stepjacky** [comment]
他那一整套都是整体，无法分离

**Comment by igwyd** [comment]
Hello @mingweiY, sorry for the last reply. We have API documentation [here](https://api.onlyoffice.com/editors/basic), installation [guides](https://helpcenter.onlyoffice.com/installation/docs-community-index.aspx) and many [intergrations](https://helpcenter.onlyoffice.com/integration/nextcloud.aspx).

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
