### ISSUE TITLE
Add FILTER() Function

### ISSUE THREAD

**Issue by DeathKhan** [ONLYOFFICE/DocumentServer#2039]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Implement the FILTER() function from Excel for compatibility. 
https://support.microsoft.com/en-us/office/filter-function-f4f7cb66-82eb-4767-8f7c-4877ad80c759

**Comment by ikeofkc** [comment]
https://www.onlyoffice.com/blog/2023/06/onlyoffice-desktop-editors-v7-4-released

This release page mentions adding the FILTER function.  Does this issue need to be closed?

**Comment by Rita-Bubnova** [comment]
@ikeofkc You are right.
 I close this issue. Feel free to comment or reopen it if you got further questions.
