### ISSUE TITLE
Problem with OpenSymbol font

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#204]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when you select OpenSymbol font, most of the characters are displayed as white rectangle

![opensymbol](https://user-images.githubusercontent.com/11867613/32896213-bac88bbe-cae2-11e7-940b-4f9d6ba69b95.jpg)

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.0.4

**Operating System:**
Docker 17.09
**Browser version:**
Chrome 62.0.3202.94 (64bits)
Firefox 57 (64bits)

Thanks for your help !
Yoann.

**Comment by ydelattre** [comment]
Hello !

This issue remain.
Am i the only one ?
Could be a local thing ? (UTF-8, ISO-8859-1...)
It's weird because some characters are show correctly.

Thanks for your help,
Yoann

**Comment by ShockwaveNN** [comment]
"Symbol Table" plugin use font info from Document Editor (list of font and list of unicode ranges, supported by each font).
There are several possible problems:
Font info may store data about support of some Unicode range, but it's not required, that ALL symbols from that range are included in Font.
Plugin got all supported Unicode ranges and trying show them in plugin windows. Font symbol table is filled and `font-family` property set by this font.
But browser can display table data in another font, that specified in `font-family` (f.e. on client side - there is not such font, or something else. Depends of browser )
Also it may be, that font if plugin window, and font used in Text area may be differ (see Font Name combobox of Document Editor), so Document Editor combobox may have not support of that symbol.
You can detect, which font browser use for displaying table in Table Symbol (by debugging tools, `Rendered Fonts` in chrome) and use same font in DocumentEditor to try to display that symbols correctly.
In your case on my machine chrome Use 'Times New Roman' to display `L` symbol. (See screenshot)
We aware of this problem, but currently have no solution for this.
![spectacle cj6399](https://user-images.githubusercontent.com/668524/33882540-7cf7a948-df49-11e7-970b-70bbbef082ba.png)

**Comment by ydelattre** [comment]
Hello,

thanks for taking the time to answer me :)
You right, not all characters are included in this font (basic latin a,b,c,d,e...are not include for example). It's a little weird because in OpenOffice/LibreOffice, you can type those letters even if it's not include in the font (i suppose it do an internal mapping with a font who contain basic latin).
Anyway, i can live with that !

Thanks again,
Yoann

**Comment by ShockwaveNN** [comment]
>OpenOffice/LibreOffice, you can type those letters even if it's not include in the font
I just tryed on my Ubuntu + LibreOffice 5.4.2.2 and LibreOffice show same rectangles for "Hello" phrase in `OpenSymbol`

**Comment by ydelattre** [comment]
No problem typing "Hello" with Windows 7 and OpenOffice/LibreOffice. 
I just tested on an Ubuntu 16.04 and LibreOffice and it show rectangles.
Some Windows magic i guess ! 😄
