### ISSUE TITLE
502 error healthcheck owncloud

### ISSUE THREAD

**Issue by CarollineRibeiro** [ONLYOFFICE/DocumentServer#2040]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.2.0

### Expected Behavior

We are getting error 502 when configuring onlyoffice in owncloud. Only office server is on the same network and without firewall:

![image](https://user-images.githubusercontent.com/32525488/207069412-82b75816-b550-42cb-8d7d-8d87ede158a3.png)

### Actual Behavior

wget at owncloud server works: 

requisição HTTP foi enviada, aguardando resposta... 302 Moved Temporarily
Localização: http://dev-onlyoffice.ici.curitiba.org.br/welcome/ [redirecionando]
--2022-12-12 11:26:13--  http://dev-onlyoffice.ici.curitiba.org.br/welcome/
Conectando-se a dev-onlyoffice.ici.curitiba.org.br (dev-onlyoffice.ici.curitiba.org.br)|172.19.***|:80... conectado.
A requisição HTTP foi enviada, aguardando resposta... 301 Moved Permanently
Localização: https://dev-onlyoffice.ici.curitiba.org.br/welcome/ [redirecionando]
--2022-12-12 11:26:13--  https://dev-onlyoffice.ici.curitiba.org.br/welcome/
Conectando-se a dev-onlyoffice.ici.curitiba.org.br (dev-onlyoffice.ici.curitiba.org.br)|172.19.***|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... **200 OK**
Tamanho: 4734 (4,6K) [text/html]
Salvando em: “index.html”

in the browser:

![image](https://user-images.githubusercontent.com/32525488/207070776-a4759286-af8c-4dde-a305-6ba74a385cf9.png)

But when trying to insert ONLYOFFICE Docs Address nginx returns error 502: 

172.19.**** - - [12/Dec/2022:11:08:05 -0300] "GET /healthcheck HTTP/1.1" **502** 150 "-" "ownCloud Server Crawler"
172.19.**** - - [12/Dec/2022:11:08:11 -0300] "GET /healthcheck HTTP/1.1" **502** 150 "-" "ownCloud Server Crawler"

Server error response [url] https://dev-onlyoffice.ici.curitiba.org.br/healthcheck [status code] 502 [reason phrase] Bad Gateway)

### Additional information

nginx conf with wildcard cert: 

server {
   listen 80;
   server_name dev-onlyoffice.ici.curitiba.org.br;
   rewrite ^/(.*) https://dev-onlyoffice.ici.curitiba.org.br/$1 permanent;
   access_log  /var/log/nginx/dev-onlyoffice.ici.curitiba.org.br.access.log;
   error_log  /var/log/nginx/dev-onlyoffice.ici.curitiba.org.br.error.log;
}
server {
   listen 443 ssl;
   client_max_body_size 20M;
   client_body_buffer_size 320k;
   server_name dev-onlyoffice.ici.curitiba.org.br;

   proxy_set_header Host dev-onlyoffice.ici.curitiba.org.br;
   ssl_certificate           /etc/nginx/certificados/wildcard_ici.***.pem;
   ssl_certificate_key       /etc/nginx/certificados/wildcard_ici.***.key;

   ssl on;
   ssl_session_cache  builtin:1000  shared:SSL:10m;
   ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
   ssl_prefer_server_ciphers on;

   access_log  /var/log/nginx/dev-onlyoffice.ici.curitiba.org.br.access.log;
   error_log  /var/log/nginx/dev-onlyoffice.ici.curitiba.org.br.error.log;

   location / {
       proxy_pass http://dev-onlyoffice.ici.curitiba.org.br:8081/;
   }
}

**Comment by ant0nwax** [comment]
Hi @CarollineRibeiro how did you fix this? Some have trouble in this issue:
https://github.com/ONLYOFFICE/DocumentServer/issues/2083
