### ISSUE TITLE
Issue when saving different documents concurrently

### ISSUE THREAD

**Issue by RicardoMrLin** [ONLYOFFICE/DocumentServer#2048]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello, I want to save different documents at the same time. I try to test with 10 identical Excels. I found that when the editor is closed and saved, the callbackurl is triggered, and the DocumentServer will take it out of the ds.converttask queue of rabbitmq one by one for conversion processing. In this way, if multiple documents need to be saved at the same time, the callbackurl of some documents may face more waiting time. is this normal? Is there a way to increase concurrent transform processing capacity.

### Here's some basic info on my system
CPU: I5-12400
Memory: 16G

### Operating System of DocumentServer
Windows 10 21H2 (Docker)

### Version information
7.1.1.23

**Comment by Rita-Bubnova** [comment]
@RicardoMrLin Sorry for the long wait.
DocumentServer v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
