### ISSUE TITLE
[Office 2013] Problem with picture in footnote

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#205]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when you insert a picture in a footnote, the document downloaded can't be opened in Office 2013.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) create a document
2) insert a footnote and add a picture in it
3) download the file
4) open it with office 2013
5) this error appear :

![bug_footnote](https://user-images.githubusercontent.com/11867613/32937196-afdef3b0-cb77-11e7-87b2-1f136d337711.jpg)

**Did this work in previous versions of DocumentServer?**
Yes, with the 4.4.3 version

**DocumentServer version:**
5.0.4

**Operating System:**
Docker 17.09

**Browser version:**
Chrome 62.0.3202.94 (64bits)
Firefox 57 (64bits)

**Comment by flaminestone** [comment]
Thank you for report. Yes, it is bug. We fix it in future.
Bug in our private bugzilla - http://bugzilla.onlyoffice.com/show_bug.cgi?id=36380

**Comment by ydelattre** [comment]
Great, thanks for your quick answer !
Yoann

**Comment by ydelattre** [comment]
I confirm, this issue is fixed with the document server version 5.0.5.26.
Thanks !
Yoann.
