### ISSUE TITLE
Cannot display or copy  placeholder symbol

### ISSUE THREAD

**Issue by chinaguole** [ONLYOFFICE/DocumentServer#2054]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Docker

### Version information

7.2.2.56

### Expected Behavior

from version 6.4 to 7.2.2，“Placeholder” symbol cannot display or copy in onlyoffice document online editor

### Actual Behavior

i wish fix this bug, make placeholder symbol can be displayed or copied in onlyoffice document online editor

### Reproduction Steps

1.open MSoffice Word ,add "placeholder" in document
2.copy the placeholder symbol to onlyoffice document online editor
3.the placeholder symbol cannot show in online editor

**Comment by TatianaKirillova** [comment]
Hello, @chinaguole!
Thanks for your request!
Can you clarify which “Placeholder” we're talking about?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
