### ISSUE TITLE
Some pdf files are not fully displayed, especially on the left and right sides

### ISSUE THREAD

**Issue by yuhui321** [ONLYOFFICE/DocumentServer#2055]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.2   ,  7.1.1

### Expected Behavior

Display complete pdf file contents

### Actual Behavior

![1672108593522](https://user-images.githubusercontent.com/100281324/209749526-21d61fc7-04a7-4ac1-bfd6-ff3edc0551e4.jpg)
[test-source.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/10311765/test-source.pdf)

### Reproduction Steps

1. uplode this test-source.pdf
2. see content
[test-source.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/10311773/test-source.pdf)

**Comment by Rita-Bubnova** [comment]
Hello, @yuhui321.
Thank you for the report. 
This is issue 60441 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/core/pull/1125) in version 7.3.
