### ISSUE TITLE
editable cells in protected excel sheet are not editable

### ISSUE THREAD

**Issue by Reis-A** [ONLYOFFICE/DocumentServer#2056]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

tag:latest=7.2 (enterprise edition)

### Expected Behavior

selected cells are editable for everyone without password protection in a password protected excel file

### Actual Behavior

the cells can be selected but are not editable

### Reproduction Steps

1.) create an excel file
2.) select a range of cells to be editable without password for example b2:D4
3.) protect the sheet with a password
try to write in the cells b2:d4
the fields b2:d4 are then not editable unless the the password protection is removed

### Additional information

i went back to version only office/documentserver-ee:7.1 and there the bug is not there.
i found a related issue that was fixed in version 7.1 [https://github.com/ONLYOFFICE/DocumentServer/issues/1676](url)

**Comment by digwa-ing** [comment]
I am using the browser-version of OnlyOffice as a user (therefore I can't tell the version number) but I am experiencing the same problem. Even with a clean document, created by OnlyOffice.

**Comment by alinasafonova** [comment]
Hello, @Reis-A
Do you uncheck 'Select locked cells' option when protect sheet?

**Comment by digwa-ing** [comment]
> Hello, @Reis-A Do you uncheck 'Select locked cells' option when protect sheet?

Hi @alinasafonova yes. This only happens when 'Select locked cells' is unchecked. The unlocked cells can be selected but not edited.

**Comment by alinasafonova** [comment]
This is known issue - 59578 in our private issue tracker.
It is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/79434184bb3f6bb98d851ac924c86c3e209daf5e
It will be released as v7.3.0

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
