### ISSUE TITLE
Excel formula evaluation failure

### ISSUE THREAD

**Issue by akshaiaksh** [ONLYOFFICE/DocumentServer#2057]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

6.3.1

### Expected Behavior

Original FIle when opened through MS Excel:

All the values evaluated using formulas are correct as expected.

[Kindly refer to the snippets document attached]
[Snippets.docx](https://github.com/ONLYOFFICE/DocumentServer/files/10323247/Snippets.docx)

### Actual Behavior

We are facing an issue with Only Office, Please find the details of the issue below:
we are unable to see values for formulas when Excel files are opened in Only Office. It shows a #REF! Value instead of the numerical value as in the screenshots in document attached : 
[Snippets.docx](https://github.com/ONLYOFFICE/DocumentServer/files/10323250/Snippets.docx)

We have seen same behaviour when same file uploaded and viewed using onlyoffice website

Note : 
The formulas are interdependent and contains calculations for SUM and other formulas to perform analysis of the data in the file.

### Reproduction Steps

1. Open file using only Office
2. Verify the values

**Comment by Rita-Bubnova** [comment]
Hello, @akshaiaksh.
Could you attach the XLSX file with problem?

**Comment by gagandeepsinghubbi** [comment]
@Rita-Bubnova  Please find the attached file with the problem. 
[2.1 (changed).xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/12097710/2.1.changed.xlsx)

Please let me know if you need any other details.

**Comment by rsnegirev** [comment]
Hi @gagandeepsinghubbi @akshaiaksh 

We can confirm - this is a bug, issue 63427 in our internal issue tracker.
Thank you for report.

**Comment by rsnegirev** [comment]
The bug was fixed in this commit:
https://github.com/ONLYOFFICE/sdkjs/commit/0ccbceb45ee3f4c092101d34f55e786e11c916f8

Fixes will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
