### ISSUE TITLE
Some functional problems in Excel preview mode

### ISSUE THREAD

**Issue by DDDJing** [ONLYOFFICE/DocumentServer#2058]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I encountered a problem. For Excel without editing permission, the cell filter icon cannot be used, which makes it impossible to quickly locate the desired data

**Comment by LuckySpecialist** [comment]
Hi @DDDJing!
If you mean that it is not possible to change filters when the document is open for reading, then use a special filtering mode for this.
If I misunderstood, then describe your use case in more detail.

**Comment by DDDJing** [comment]
> 
Yes, I hope that when the Excel document is opened in readable mode, I can use the filter in the cell to quickly find the data I want. Please tell me how the special filter mode is used. thank you
![image](https://user-images.githubusercontent.com/87412876/211228132-2b0d3fc5-344d-4c8b-bb74-f28792244c42.png)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by lumos0** [comment]
> Hi @DDDJing! You can use a special editing mode when the use of filtering does not affect other users (you can read [here](https://api.onlyoffice.com/editors/config/document/permissions#modifyFilter)). But I think maybe a [Sheet View](https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-spreadsheet-editor/UsageInstructions/SheetView.aspx) would be better for you.

But both modifyFilter and sheetview are only available to users with editing permissions.
The problem is how to use filter in preview mode (read-only mode).
There is nothing inappropriate in terms of permissions, because read-only users can already access all the data in the table, they just want to further filter when previewing.
