### ISSUE TITLE
How to add a image watermark?

### ISSUE THREAD

**Issue by 277801235** [ONLYOFFICE/DocumentServer#2060]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I want to add image watermark to docx through plugin, but couldn't find the method.

**Comment by Akrobs** [comment]
Tab menu - Layout - Watermark

**Comment by 277801235** [comment]
> 
Thanks for your reply, I need to configure it through plugin.

https://api.onlyoffice.com/plugin/executemethod/setproperties

But it only supports "text".

```
"watermark_on_draw": {
    "align":  1,
    "height": 100,
    "paragraphs": [
        {
            "align": 2,
            "runs": [
                {
                    "font-size": 70,
                    "fill":      [255,255,255],
                    "text":      ""
                }
            ]
        }
    ],
    "rotate": -45,
    "width": 260
}
```

**Comment by askonev** [comment]
Hi @277801235 

You doesen't want find method because watermark is a drawings obj at header/footer.

You can add it in general using the script for builder api in the context of the plugin

[CallCommand methos](https://api.onlyoffice.com/plugin/callcommand)


Api builder script added watermark
```js
    var oDocument = Api.GetDocument();
    var oParagraph = oDocument.GetElement(0);
    oParagraph.AddText("A watermark was inserted into this document.");
    oDocument.InsertWatermark("Watermark");
```

Simple script to delete all watermarks

```js
    var oDocument = Api.GetDocument();
    var oSection = oDocument.GetFinalSection();
    var oHeader = oSection.GetHeader('default', false);
    oHeader.RemoveAllElements();
```

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by 125487684** [comment]
I encountered the same issue. Although the official OnlyOffice documentation states that the `fill` parameter supports base64 images or URLs, in practice, setting `fill` to a base64 string or a URL does not seem to work.

**Comment by Rita-Bubnova** [comment]
@lemonowl take a look, please.
