### ISSUE TITLE
Text format is changed when converted in oo.

### ISSUE THREAD

**Issue by RumbleWx** [ONLYOFFICE/DocumentServer#2061]
### This issue is unique.

- [ ] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1.34

### Expected Behavior

![image](https://user-images.githubusercontent.com/75654441/210559074-9d9116a5-02a7-4445-9d45-506cbe0aebee.png)
![2](https://user-images.githubusercontent.com/75654441/210559373-ad3274f4-8a9a-45ed-b835-7a553ec1e635.png)

### Actual Behavior

When i open the local file in msoffice, it looks like the pic1; but it looks like pic2 in oo.
The format of the paragraphs has been changed.
The similar quesiton occurs in docker docServer's example,  after the file has been converted, there will be more carriage returns for some title positions.

**Comment by Rita-Bubnova** [comment]
Hello, @RumbleWx.
Could you attach the file with the problem?

**Comment by RumbleWx** [comment]
The problem cannot be seen directly from the file.

![image](https://user-images.githubusercontent.com/75654441/210677142-20326995-8da7-4587-bf97-72f459037ce9.png)
opened in wps/msoffice
![image](https://user-images.githubusercontent.com/75654441/210677213-3c05491c-fe53-4be7-b1a6-b90874562b6f.png)
opened in oo

**Comment by RumbleWx** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/1994
similar problem

**Comment by Rita-Bubnova** [comment]
Could you attach the file displayed on your screenshots? Because I need to check the problem.

**Comment by RumbleWx** [comment]
> 

It should be the bug - issue 59675

**Comment by Rita-Bubnova** [comment]
Ok, then this is a duplicate issue https://github.com/ONLYOFFICE/DocumentServer/issues/1994.
