### ISSUE TITLE
in request , nginx 502 bad

### ISSUE THREAD

**Issue by hqb72** [ONLYOFFICE/DocumentServer#2064]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.2.2

### Expected Behavior

show word and edit

### Actual Behavior

nothing and network show nginx 502 
![image](https://user-images.githubusercontent.com/30142521/211001071-14d0cc68-c6d2-46aa-879e-2a17445473f3.png)

### Additional information

![image](https://user-images.githubusercontent.com/30142521/211001319-e28e237c-d0bb-4ff6-b543-51908400622c.png)

**Comment by hqb72** [comment]
How do it ?

**Comment by GaetanLepage** [comment]
I now also get 502 errors using the docker version of the server... Was something critical updated ?

**Comment by hqb72** [comment]
I don`t kwon

**Comment by ant0nwax** [comment]
i read in the other thread that a part of the documentation was not followed, but in 7.1 eveything worked. I wonder which part of the docs they refer to. Do you know?

**Comment by hqb72** [comment]
> i read in the other thread that a part of the documentation was not followed, but in 7.1 eveything worked. I wonder which part of the docs they refer to. Do you know?

不好意思, 我也不晓得

**Comment by ant0nwax** [comment]
Translated from Chinese to German with a online translation software: 
Entschuldigung, ich weiß es auch nicht.

Vielen Dank das ist in Ordnung :)

**Comment by Akrobs** [comment]
You need to use command export DS_PORT=<PORT_NUMBER>
Now, you change the redis port, not DS port!

**Comment by hqb72** [comment]
.

**Comment by hqb72** [comment]
Can you help me delete this issue

**Comment by igwyd** [comment]
Hello @hqb72, sorry for the late reply. We can't remove the issue, but we will close it and activity will stop after [2 weeks](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/about-your-personal-dashboard#finding-your-recent-activity).
