### ISSUE TITLE
Crash when editing docx [ERROR] nodeJS - changesError: Error: TypeError: this.aa[Ea] is undefined

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DocumentServer#2070]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.0.0.132

### Expected Behavior

Editing a docx file should not crash the app.

### Actual Behavior

When editing a docx file under Nextcloud, the app sometimes throws an error and we need to restart the app.

![69bd87d9663a1f63b3c0e954498c90f2](https://user-images.githubusercontent.com/6248852/211604580-7c749541-975e-47bc-b6da-241826f22a1b.png)

### Reproduction Steps

Open a docx file from Nextcloud
Edit the document
Randomly (apparently) the app crash and ask to download the file locally

### Additional information

`[2023-01-10T13:49:50.765] [ERROR] nodeJS - changesError: docId = 1377000641 Error: TypeError: this.aa[Ea] is undefined Script: https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js Line: 7403:79 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 platform: Win32
 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: dg.prototype.WAg@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:7403:79
dg.prototype.iSd@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:7393:53
dg.prototype.ia@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:7204:224
Rf.prototype.ia@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:7649:462
pf.prototype.Eg@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:6465:335
yf.prototype.Mag@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:8494:494
yk.prototype.Eg@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:8870:201
yf.prototype.Eg@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:8281:303
yf.prototype.fnf@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:8353:404
Ha.AscCommonWord.R3g/this.OUa@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:10298:473
Nb.prototype.OUa@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all-min.js:1264:384
OUa@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:11230:447
pe/this.ws.onkeypress@https://office.dummy.fr/7.0.0-132/sdkjs/word/sdk-all.js:11212:204
`

**Comment by Rita-Bubnova** [comment]
Hello, @Mer0me.
Sorry for late restonse, seems we missed this issue.
DocumentServerv7.4.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
