### ISSUE TITLE
Logrotate config in rpm package is generating annoying output

### ISSUE THREAD

**Issue by markuslf** [ONLYOFFICE/DocumentServer#2071]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.2.2-56

### Expected Behavior

No output

### Actual Behavior

The issue [#972](https://github.com/ONLYOFFICE/DocumentServer/issues/972) is back - logrotate config in rpm package is generating annoying output:

```
/etc/cron.daily/logrotate:
Redirecting to /bin/systemctl restart supervisord.service
```

This is because the config is using `service` instead of `systemctl` to restart the daemon.

### Reproduction Steps

Install OnlyOffice.

**Comment by bzblf** [comment]
Hi there
i still see the same beaviour.  The service that is noted changes 'randomly'
