### ISSUE TITLE
Allow anonymous user to use nextcloud onlyoffice on shared link

### ISSUE THREAD

**Issue by kratzerph** [ONLYOFFICE/DocumentServer#2081]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.2-56

### Expected Behavior

Anonymous User/shared via e-mail address can edit files with onlyoffice.

### Actual Behavior

Users cannot edit *.docx, *.xlsx, *.doc, *.xls via onlyoffice webbrowser app. They can only download the files.

### Reproduction Steps

1. Share a link to users by entering their e-mail addresses
2. User receives e-mail with a link in it
3. User clicks link, nextcloud opens
4. User can see files/folders
5. User clicks on *.doc only download is possible. OnlyOffice does not open and allow editing (did so in former versions of Nextcloud/OnlyOffice)

### Additional information

I'm using Ubuntu Snap of nextcloud latest Version (25.02)

Greets
Andreas

**Comment by Keyinator** [comment]
Bump? This is really hurting the extend I can use nextcloudXonlyoffice

**Comment by XDmitryK** [comment]
@kratzerph 
Hi, In your steps i'm not find step when you turn on option "Allow Editing". Are you sure you enabled this option?
![TestikD - Files - Nextcloud - Google Chrome 2023-0](https://user-images.githubusercontent.com/46962983/231414362-00d33b5a-887b-424d-b2fb-8073f06718f9.jpg)
