### ISSUE TITLE
Configuration property "bottleneck.getChanges" is not defined

### ISSUE THREAD

**Issue by sabrinamile** [ONLYOFFICE/DocumentServer#2082]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

Documentserver 7.3.0-184~stretch

### Expected Behavior

Docservice should be running after upgrade onlyoffice-documentserver-ee:amd64 7.2.2-56 -> 7.3.0-184~stretch

### Actual Behavior

Documentserver/Docservice is not starting after an upgrade: onlyoffice-documentserver-ee:amd64 7.2.2-56 -> 7.3.0-184~stretch

**Error in Logfiles:**
supervisorctl status:
ds:converter                     RUNNING   pid 8360, uptime 0:21:18
ds:docservice                    FATAL     Exited too quickly (process log may have details)
ds:example                       RUNNING   pid 8348, uptime 0:21:18
ds:metrics                       RUNNING   pid 8347, uptime 0:21:18

In /var/log/onlyoffice/documentserver/docservice/err.log we found this error:
Error: Configuration property "bottleneck.getChanges" is not defined
    at Config.get (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/baseConnector.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/DocsCoServer.js)

### Reproduction Steps

upgrade onlyoffice-documentserver-ee:amd64 7.2.2-56 -> 7.3.0-184~stretch

**Comment by Akrobs** [comment]
Same problem on rpm package.

**Comment by sabrinamile** [comment]
There was a conflict between the old and the new config-file. The unattended installation at night was not fully finished. Trying the update once again solved the issue for us.

**Comment by nahoj** [comment]
I had the same error upgrading from `7.1.0~ynh1` to `7.3.3~ynh1` on YunoHost.

I used the fix suggested in https://github.com/ONLYOFFICE/DocumentServer/issues/1472, namely:

```shell
cd /etc/onlyoffice/documentserver
cp default.json.dpkg-dist default.json
supervisorctl restart all
```

**Comment by igwyd** [comment]
Hello @sabrinamile, you're right, ```/etc/onlyoffice/documentserver/default.json``` should be updated, all custom changes must be made to ```/etc/onlyoffice/documentserver/local.json```.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
