### ISSUE TITLE
Scrolling is not smooth + very janky on macOS

### ISSUE THREAD

**Issue by yllekz** [ONLYOFFICE/DocumentServer#2085]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.11 x86

### Version information

7.2.1 (535)

### Expected Behavior

Scrolling and zooming should be smooth and not stuttery.

### Actual Behavior

Scrolling and zooming on macOS in OnlyOffice is not smooth. Instead, it seems to operate on a system that relies on snapping between various scroll/zoom points.  It makes for an awkward experience, especially when running the application side-by-side with another app that properly and smoothly handles zooming/scrolling such as OneNote. Please update the zooming and scrolling such that it either behaves like other modern apps in this regard.

### Reproduction Steps

1. Open a document
2. Scroll or zoom

**Comment by ggrzeczkowicz** [comment]
I think this bug is also present on mobile editing. On a smartphone a small mouvement of the finger will move a spreadsheet by one row or one column, which is not something usual for a smartphone user.

**Comment by michael-gao-1998** [comment]
Is this bug fixed as to today 1/24/2024? Where can I see the fix? Thanks.

**Comment by yllekz** [comment]
I will check it out later today.

**Comment by michael-gao-1998** [comment]
Thank you very much for response!

**Comment by yllekz** [comment]
Hello, I have the latest OnlyOffice for Mac (7.5.1, according to the update checker), and the issue still persists.

**Comment by michael-gao-1998** [comment]
@yllekz Thank you very much for the reply. If the issue still persists, we don't need the latest version of OnlyOffice for now.

**Comment by michael-gao-1998** [comment]
> Hello, I have the latest OnlyOffice for Mac (7.5.1, according to the update checker), and the issue still persists. It seems the latest version is from November 2023 and there is no new build. Do you need to push it out?

Btw, do you know how the scrolling and document view/display work? Any document on this part? I would like to study and try to fix it. Thanks.

**Comment by michael-gao-1998** [comment]
I tried the latest version of OnlyOffice Doc (docker tag: 8.0) released at the end of January, 2024. The problem stays the same. Anyone else has tried the latest one? Thanks.

**Comment by gnaegi** [comment]
Oh yes, scrolling on MacOS ist very weird. When scrolling using the mouse in large tables it moves the cells left/right even when scrolling only top/down. It only works by dragging the scrollbar and not using the wheel. It makes working with working with spread-sheets very hard and frustrating!

**Comment by jeugregg** [comment]
This BUG is very important and must be solved because we cannot use your app on MacOS : totally useless today... 👎

**Comment by yllekz** [comment]
Closing as the issue has been fixed in a recent update + there was an inappropriate and irrelevant comment added above.

**Comment by LuckySpecialist** [comment]
Hi @yllekz, тhat's right, the problem has been fixed since version 8.2.
Thanks for the help.
