### ISSUE TITLE
PDF file with vector graphics is displayed incorrectly

### ISSUE THREAD

**Issue by DonMins** [ONLYOFFICE/DocumentServer#2088]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3

### Expected Behavior

It didn't work in earlier versions either.

The document is displayed correctly.

![image](https://user-images.githubusercontent.com/26121516/216521487-0d80691b-bde8-421d-9b9f-fdb3de5a5b9d.png)

### Actual Behavior

The document is displayed incorrectly

![image](https://user-images.githubusercontent.com/26121516/216521459-30f078a4-c2ec-46d5-a2a6-8ecc691e9508.png)

### Reproduction Steps

Download this file for preview

[tnp.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/10575865/tnp.pdf)

**Comment by LuckySpecialist** [comment]
I have issued a Bug 61014 for this problem.
Thank you for contacting us.

**Comment by LuckySpecialist** [comment]
This problem was fixed earlier https://github.com/ONLYOFFICE/sdkjs/pull/3325 in release 7.3.3.
This issue may be closed.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
