### ISSUE TITLE
highlight change is not saved in .odt

### ISSUE THREAD

**Issue by Artiom-M** [ONLYOFFICE/DocumentServer#2094]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

1. Create a text document then highlight some text in it. Save in **.ott** format and close
2. Reopen the document and change the highlight colour. Save and close
3. Reopen and see the colours applied in the step 2

### Actual Behavior

When I change the highlight on a text and save it in the .ott/.odt file it remains unchanged (previous colour is conserved). Any other change is saved as expected. Saving in .docx works as expected. Also only changing is not working. Initial highlight is applied even during edit of an existing document.
The same can be observed in the android app.

**Comment by ElenaMaaya** [comment]
Hello, @Artiom-M.
This is issue fixed in future version - 7.3.3. 
The issue reproduced in Document Server.
Thank you very much!

**Comment by DenisDeeSign** [comment]
DocumentServer and DesktopEditors v7.3.3 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
