### ISSUE TITLE
Collaborative Editing - Chat User problem - Nextcloud APP

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/DocumentServer#210]
**BUG**

**OO Nextloud installed via APT Guide**

- Opening the same document on different Systems Windows 7, 8, 10, Ubuntu / Browsers will result in different amounts of active Users in Chat Plugin OO and reload the page and reopen the document

Please see screenshot.
https://pasteboard.co/GV6rK5T.jpg

**Login as different users and refresh the Document page, or reopen it.**

**Chat Plugin should Update**

**DocumentServer version:** Newest

**Operating System:** Ubuntu 16.04 LTS

**Browser version:** Apache2 NC, NGINX OO

**Comment by onny** [comment]
You should report this issue here: https://github.com/ONLYOFFICE/onlyoffice-owncloud
It's also the repository for the Nextcloud app!

**Comment by ExaconAT** [comment]
True thx

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/125
