### ISSUE TITLE
PowerPoint diagram (wmf) doesn't render correctly

### ISSUE THREAD

**Issue by 1nikolas** [ONLYOFFICE/DocumentServer#2100]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

The diagram renders correctly

### Actual Behavior

The diagram does not display correctly (has some weird artifacts). Here is OnlyOffice (left) vs InkScape (right, just opened the wmf file)

![image](https://user-images.githubusercontent.com/30593419/201544863-6a5d3dae-468b-4428-bc55-93d2e8b0b189.png)

Upon reopening OnlyOffice it's rendered differently, yet still wrong

![image](https://user-images.githubusercontent.com/30593419/201546558-5fd0d2a6-3a38-48f1-97f0-df00aa69af56.png)

### Reproduction Steps

[Example files](https://github.com/ONLYOFFICE/DesktopEditors/files/9998241/Archive.zip)
The zip file contains both the pptx and the wmf of the diagram shown above (you can also extract it from the pptx).

I should also mention that this diagram is made using a really old version of MS Office (and then modified with a newer one, you can look at the created/modify dates).

**Comment by DenisDeeSign** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too.

**Comment by Gingetsu** [comment]
Hello, @1nikolas . Our dev team is fixed your issue in next version (But sorry, no exact ETA)
This fixed here: https://github.com/ONLYOFFICE/core/commit/96ff2246fa32c955ac8324202b1755ff14e11f52

**Comment by DenisDeeSign** [comment]
DocumentServer and DesktopEditors v7.3.3 are released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by 1nikolas** [comment]
Fixed thank you!
