### ISSUE TITLE
How to change file download url host address?

### ISSUE THREAD

**Issue by fuzi1996** [ONLYOFFICE/DocumentServer#2101]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

When users use the public network to access onlyoffice, the file download address given by onlyoffice is also the public network。How to change file download url host address?

**Comment by igwyd** [comment]
What do you have in mind? Why do you want to change the host address? Please describe in more detail the use case and what you think needs to be changed.

**Comment by fuzi1996** [comment]
Users can access onlyoffice through the public cloud (for example: `http://xxx.cloud`）, but onlyoffice cannot access the public cloud address(`http://xxx.cloud/cache/files/xxxx/output.docx/output.docx?md5=xxx&expires=xxx&filename=output.docx`）, onlyoffice can only be accessed through the intranet(`http://192.168.10.1/cache/files/xxxx/output.docx/output.docx?md5=xxx&expires=xxx&filename=output.docx`)

![image](https://user-images.githubusercontent.com/21113919/222997485-570d2262-033a-4990-ab26-82d5dd1ad35d.png)

**Comment by igwyd** [comment]
The ONLYOFFFICE-Docs can work inside a private network, but ONLYOFFICE-Docs must be resolvable and connectable both from yuor cloud and any end clients from a local or global network, through a proxy for example https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx.
