### ISSUE TITLE
Spreadsheet: date value lost/erased after reading an .ods file created by LibreOffice and saving again to .ods

### ISSUE THREAD

**Issue by rene-olsthoorn** [ONLYOFFICE/DocumentServer#2102]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

 7.2.1.36

### Expected Behavior

I expected to be able to work (read,modify,save) with existing LibreOffice spreadsheets in ods-format. 

 

### Actual Behavior

After saving the file and opening again the date values were blank/erased. 

### Reproduction Steps

Create a spreadsheet with LibreOffice Community version 7.4.3.2
Format cell A1 to YYYY-MM-DD"T"HH:MM:SS  
Enter a date value 
Save as s1.ods 
quit Libreoffice

Open s1.ods with OnlyOffice
Save as s2.ods
quit OnlyOffice

now s2.ods misses the date value
as you can see by opening s2.ods with either OnlyOffice or LibreOffice.

[s1.ods](https://github.com/ONLYOFFICE/DesktopEditors/files/10202731/s1.ods)
[s2.ods](https://github.com/ONLYOFFICE/DesktopEditors/files/10202732/s2.ods)

### Additional information

I used the OnlyOffice version as distributed by Manjaro.

**Comment by Gingetsu** [comment]
Hello, @rene-olsthoorn. Our dev team is fixed your issue in next version (But sorry, no exact ETA)
This fixed here: https://github.com/ONLYOFFICE/core/commit/e71e4068e494dde29cb9c65e15bb6d168c3927e4

**Comment by DenisDeeSign** [comment]
DocumentServer and DesktopEditors v7.3.3 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
