### ISSUE TITLE
 -e JWT_ENABLED=false    

### ISSUE THREAD

**Issue by dongSpring** [ONLYOFFICE/DocumentServer#2106]
DocumentServer7.3

![image](https://user-images.githubusercontent.com/46913726/217753040-97783ca9-845f-4dde-be67-78881a8286f2.png)

**Comment by dongSpring** [comment]
Close jwt. I am using client to connect to docker service
Opening the file brings up this error

**Comment by dongSpring** [comment]
OnlineEditorsExampleJava Open jwt is normal

**Comment by askonev** [comment]
@dongSpring  Are you using a self-written js client using docserver documentation?
https://api.onlyoffice.com/editors/basic

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
