### ISSUE TITLE
DocumentBuilder API: ToJON method on ApiStyle object throws SerStyle is not a function

### ISSUE THREAD

**Issue by Willena** [ONLYOFFICE/DocumentServer#2110]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.0

### Expected Behavior

ToJON method on ApiStyle should return the json representation. 

### Actual Behavior

Calling ToJON() method on ApiStyle objects throws the following exception 

``` 
TypeError: oWriter.SerStyle is not a function
    at ApiStyle.ToJSON (apiBuilder.js:11538:23)
``` 

### Reproduction Steps

1. Start a document server stack
2. Create a minimalist plugin
3. Call the callCommand method with the following minimal function:
``` 
function () {
      const doc = Api.GetDocument();
      const heading = doc.GetAllHeadingParagraphs()[0];
      const jsonData = heading.ToJSON()
      console.log('Data', heading, jsonData);
    }
``` 
4. The dev console should show the error

**Comment by l8556** [comment]
Hello, @Willena !
I was unable to reproduce your issue.

Maybe your document is missing heading paragraphs, 
so the method from your example `doc.GetAllHeadingParagraphs()[0]` returns `undefined`, which could have caused an error when calling `heading.ToJSON()`

Example of a correct script:
```
var oDocument = Api.GetDocument();
var oNewDocumentStyle = oDocument.GetStyle("Heading 1");
var oParagraph = oDocument.GetElement(0);
oParagraph.SetStyle(oNewDocumentStyle);
oParagraph.AddText("Heading 1");
var heading = oDocument.GetAllHeadingParagraphs();
if (heading !== undefined && heading.length !== 0) {
   var jsonData = heading[0].ToJSON()
   console.log(jsonData)
}
```

Tested on 7.4.1.36
