### ISSUE TITLE
The picture in the word can't display when DS was  installed in the local area network.

### ISSUE THREAD

**Issue by zhc77** [ONLYOFFICE/DocumentServer#2114]
We installed DS in windows server 2019, and it was in the local area network. 
The url we visited DS was like 'https://xxxx.xxxx.com:64162/xxxxxx', and it swithed to 'http://192.168.xx.xx/xxxxxx' in local.
We could open the word file ,but the images in the word couldn't display ,because it's url is like 'http://192.168.xx.xx/xxxxxx.jpg'.
How to switch the image's url to ''https://xxxx.xxxx.com:64162/xxxxxx.jpg'?
thank u!

**DocumentServer version:**
7.3

**Operating System:**
Windows Server 2019

**Browser version:**
edge 107

**Comment by trofim24** [comment]
Sorry for late response, seems we missed this issue.
@zhc77 can you send us your proxy settings?

or you can see our [ONLYOFFICE Document Server example configurations for proxy](https://github.com/ONLYOFFICE/document-server-proxy)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
