### ISSUE TITLE
Get the specified position text

### ISSUE THREAD

**Issue by shenX1998** [ONLYOFFICE/DocumentServer#2117]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello

In docx, I want to get and replace the text at the specified position. What should I do

**Comment by askonev** [comment]
Hi @shenX1998 How do you want to choose a specific position?

You can use the Find and Replace function in the editor interface.

![image](https://user-images.githubusercontent.com/60688343/222409563-0b23f7a7-6603-44f1-abe0-c542f91673e4.png)

**Comment by askonev** [comment]
Hello @shenX1998, issue is actual?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
