### ISSUE TITLE
checkJwt error: name = JsonWebTokenError message = jwt must be provided token = undefined

### ISSUE THREAD

**Issue by vvrnv** [ONLYOFFICE/DocumentServer#2121]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.2

### Expected Behavior

jwt token works

### Actual Behavior

jwt token does not works

### Reproduction Steps

1. Clean vm, ubuntu 20.04, used latest docker tag

docker run -i -t -d -p 80:80 -p 443:443 --restart=always --name onlyoffice-document-server \
  -v /data/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
  -v /data/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
  -v /data/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
  -v /data/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver
  
2. https://my-endpoint.my-domain.com/welcome/ — works correctly,
check that jwt secret exists —  sudo docker exec 3493109012c8 /var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string' OK

3. Tried to open document from Elma service
```
[2023-02-21T10:20:47.886] [WARN] [localhost] [706bd203-570d-4d46-bedc-9905402e67a4.1675942096] [userId] nodeJS - checkJwt error: name = JsonWebTokenError message = jwt must be provided token = undefined
```

### Additional information

Also tried to use onlyoffice/documentserver:7.3.0 — same problem
Also tried to use JWT env `-e JWT_SECRET=0YuaC829SRbiW43XdRNd` same problem

Works if i disable jwt from env `-e JWT_ENABLED=false`, but jtw token is still being created in the configuration file, is that correct?

same issue — https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/514

**Comment by trodix** [comment]
I have the same issue, I'm working with the docker image `onlyoffice/documentserver:7.3.2.8`.

**Comment by igwyd** [comment]
Hello @vvrnv, sorry for the late reply. Check please the integrated test example at the "welcome" page https://my-endpoint.my-domain.com/welcome/, are there any errors?
![111](https://github.com/ONLYOFFICE/DocumentServer/assets/67538082/45794515-96d1-4ecf-9135-17f393158d45)

**Comment by yokesh22** [comment]
I also face the same error and "https://my-endpoint.my-domain.com/welcome/" there is no error here

**Comment by igwyd** [comment]
@yokesh22 Did I understand you correctly? You have the same error ```nodeJS - checkJwt error: name = JsonWebTokenError message = jwt must be provided token = undefined``` when using the other intagration app and have no errors in the logs with intergated test example from the page https://my-endpoint.my-domain.com **/example** . Its true? 
Provide information about your server, integration application, docker version and other details if any.

**Comment by yokesh22** [comment]
@igwyd , I have runned this cmd "sudo docker run -i -t -d -v onlyoffice_docx_volume:/var/lib/onlyoffice/documentserver-example/files -p 8050:80 --restart=always -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver-de"
now i can successfully use the "https://my-endpoint.my-domain.com/ /example?new.docx". now I'm trying to integrate my onlyoffice with react so. I have created a React app 

`return (
       <div style={{height:"100vh"}}>
         <DocumentEditor
            id="docxEditor"
            documentServerUrl="http://192.168.1.119:8050"
            config={{
                "document": {
                    "fileType": "docx",
                    'key': 'my_jwt_secret',
                    "title": "new.docx",
                    "url": "http://192.168.1.119:8050/example/editor?fileName=new.docx",
                    
                },
                "documentType": "word",

            }}
            events_onDocumentReady={onDocumentReady}
        />
       </div>
    );`
    
    when i run the app, It throws error as "The document token is not correctly formed". and in log file of docker give
    "[2023-08-23T12:37:10.022] [WARN] [localhost] [my_jwt_secret] [userId] nodeJS - checkJwt error: name = JsonWebTokenError message = jwt must be provided token = undefined "

**Comment by igwyd** [comment]
It looks like your application is not providing a token. We have [React component](https://api.onlyoffice.com/editors/react) and several [Language-specific examples](https://api.onlyoffice.com/editors/demopreview), I hope this can help you.

**Comment by yokesh22** [comment]
@igwyd 
For [React component](https://api.onlyoffice.com/editors/react) , in key field what should i give ? and a backend needed for this react component ?

**Comment by askonev** [comment]
@igwyd The backend role is document server with jwt activated, then how you configured the server above

After in the component it is necessary to specify token jwt for correct work of client-server architecture.

As an example, here is the client configuration on pure js

[The token field of the config object](https://api.onlyoffice.com/editors/config/#token)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
