### ISSUE TITLE
Slider overlaps numbers in column filter

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DocumentServer#2123]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0.184

### Expected Behavior

Both numbers and the slider are visible and usable

### Actual Behavior

As you can see yourself, the slider bar overlaps numbers. :disappointed: 
<img width="283" alt="OO-column-filter" src="https://user-images.githubusercontent.com/64358003/219760834-d08955f6-c81b-405f-84c9-84b8ed232425.png">

**Comment by rsnegirev** [comment]
This problem is fixed in https://github.com/ONLYOFFICE/web-apps/commit/8abd90167de2c9ddeaae2ee9645e5260187220c9

It will be released as v7.4.0

**Comment by DenisDeeSign** [comment]
DocumentServer and DesktopEditors v7.4.0 are released so I close this issue. Feel free to comment or reopen it if you got further questions.
