### ISSUE TITLE
Failed to start nginx

### ISSUE THREAD

**Issue by a1643977841** [ONLYOFFICE/DocumentServer#2125]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

latest

### Expected Behavior

success

### Actual Behavior

Following the document startup prompts an error message in the image

### Additional information

<img width="560" alt="image" src="https://user-images.githubusercontent.com/75775858/220899915-4c12a876-2cc4-431f-bad4-83650469d560.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/75775858/220900179-2c857263-566c-4317-83f1-9def141ac8ab.png">

**Comment by igwyd** [comment]
Hello @a1643977841, sorry for the late reply. Provide please more information about your server and docker version.

**Comment by a1643977841** [comment]
> Hello @a1643977841, sorry for the late reply. Provide please more information about your server and docker version.
I am using Apple Notebook, using Docker desktop 4.21.1 (114176)  Engine: 24.0.2

**Comment by igwyd** [comment]
@a1643977841 Then you need more information, do you have an Intel chip or an Apple silicon, macOS version?

**Comment by igwyd** [comment]
I checked installation in docker desktop 4.22.0 (docker engine 24.0.2) on macOS Monterey 12.6.8 with Apple M2 and don't have any errors. My run command ```sudo docker run -i -t -d -p 80:80 onlyoffice/documentserver:7.4.1.1``` 

Please provide more information on the steps to reproduce your issue, including the run command.

![222](https://github.com/ONLYOFFICE/DocumentServer/assets/67538082/5fb6e9f8-2a3f-4024-ba43-0e0ac4342556)

**Comment by a1643977841** [comment]
> @a1643977841 Then you need more information, do you have an Intel chip or an Apple silicon, macOS version?

Apple M1 Pro and  13.4.1

**Comment by a1643977841** [comment]
> sudo docker run -i -t -d -p 80:80 onlyoffice/documentserver:7.4.1.1

The problem has been solved, thank you very much for your support!
<img width="879" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/75775858/fec9abd5-982a-4376-bae9-3a6224e8f886">

**Comment by igwyd** [comment]
I'm glad you did it. Can we close this issue?

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by gotohr** [comment]
> The problem has been solved, thank you very much for your support!

if you could please explain - how did you resolve this problem?
