### ISSUE TITLE
Mail merge fields stop working as fields

### ISSUE THREAD

**Issue by sse450** [ONLYOFFICE/DocumentServer#2128]
Nextcloud: 25.0.0
OnlyOffice-Nextcloud: 7.6.6
OnlyOffice Doc Server: 7.2.1.34

I insert fields using Insert Merge Field button. It works while the doc is open. But, after a few subsequent openings of the doc, the fields previously inserted properly don't work anymore. The fields just become static <<Field>> texts.
It was working before 7.6.6.
Thanks.

**Comment by Mer0me** [comment]
I confirm the problem. It has been documented here too : 
https://forum.onlyoffice.com/t/mail-merge-stopped-working/2812
https://forum.onlyoffice.com/t/mailmerge-help-documents-with-mergefields-only-work-once/3130

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released. Please state is this problem still actual for you?

**Comment by trofim24** [comment]
I think it was fixed in 7.3.3 by 61300 and 59709 issues by @Mer0me urls on forum, so I close this issue.
If the problem persists, please reopen this issue
