### ISSUE TITLE
After clicking the Save button, the file cannot be saved normally and the status is 7

### ISSUE THREAD

**Issue by 183demao** [ONLYOFFICE/DocumentServer#2129]
After clicking Save, the address of the callback function can be called normally, but the status is 7 after the body is resolved, so it cannot be saved normally. Could you please tell me what is the situation and could you help solve it? Thank you

![2](https://user-images.githubusercontent.com/16781295/221345943-7d0df396-9709-4308-b276-94f33d687329.png)
![1](https://user-images.githubusercontent.com/16781295/221345946-bd93a661-ceba-4c80-9ed5-99b37f194635.png)
![3](https://user-images.githubusercontent.com/16781295/221345949-51551b87-42ba-4e0e-8f83-b65f04091c38.png)

**Comment by alexanderonlyoffice** [comment]
Hello @183demao, please enable the error folder that collects conversion failures and send it to us, as well as converter out.log. 

1. You need to add the value error to the parameter `"errorfiles": ""` in **/etc/onlyoffice/documentserver/default.json** of the Document Server
```
"FileConverter": {
     "converter": {
        "errorfiles": "error",
```
2. Restart all Document Server services with `systemctl restart ds-*` to apply the changes to the config
3. Once the issue occurs again, please send us all subfolders **/var/lib/onlyoffice/documentserver/App_Data/cache/files/error/** and **/var/log/onlyoffice/documentserver/converter/out.log**

If you are using Docker installation - all actions are performed inside the container with Document Server, for step 2 use command `supervisorctl restart all` instead. If it is Windows Server installation, please let me know and I will provide you with another guide.

**Comment by 183demao** [comment]
Thank you very much for your help，Here are the files I copied from the container，Please take a look for me。
[error.zip](https://github.com/ONLYOFFICE/DocumentServer/files/10837877/error.zip)

system version  Ubuntu 22.04.1 LTS
Docker version 23.0.1, build a5ee5b1


[thanks again](javascript:;)

**Comment by 183demao** [comment]
文件类型为doc，不是docx，无法保存成功

**Comment by 183demao** [comment]
The file type is doc, not docx, and cannot be saved successfully

**Comment by konovalovsergey** [comment]
Editing(and saving) .doc files is not available [at this moment](https://api.onlyoffice.com/editors/conversionapi#text-matrix).
