### ISSUE TITLE
Help in my application not is necessary of button upload images.  how I doing?

### ISSUE THREAD

**Issue by jrangel02** [ONLYOFFICE/DocumentServer#213]
**Do you want to request a *feature* or report a *bug*?**
Hidden button upload images
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.0
**Operating System:**

**Browser version:**
Google Crome

**Comment by ibnpetr** [comment]
It's not a bug. 
This type of customization isn't included into the opensource version.
Please contact ONLYOFFICE  team at support@onlyoffice.com to discuss all possible ways how you can customize the interface.
