### ISSUE TITLE
.odt incompability with Libreoffice Writer

### ISSUE THREAD

**Issue by umitseyhan75** [ONLYOFFICE/DocumentServer#2130]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.3.0.184

### Expected Behavior

The spacing behavior of tabs between both editor to be the same.

### Actual Behavior

The spacing behavior of tabs between both editor is inconsistent.

### Additional information

Libreoffice Writer:
![ORabyMCKld](https://user-images.githubusercontent.com/43583375/219899541-502f6d5c-19fc-47c7-8182-7aff81af2c71.png)

Onlyoffice:
![VLAYPUTVZJ](https://user-images.githubusercontent.com/43583375/219899554-1b60e112-cbd2-41d0-a057-0c829a78abbd.png)

**Comment by XDmitryK** [comment]
This will be fixed in the next version. Commit https://github.com/ONLYOFFICE/core/commit/ec3d6fa05b3d994274a23635b48aff2f71f42193

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
