### ISSUE TITLE
Equation editing causes "An error occurred during the work with the document."

### ISSUE THREAD

**Issue by Heath123** [ONLYOFFICE/DocumentServer#2131]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0.184

### Expected Behavior

Equation editing should not throw errors

### Actual Behavior

Sometimes, I get this error when editing equations:
![image](https://user-images.githubusercontent.com/13787163/220753027-c8a85d59-65dc-4339-9b41-8ca0513db412.png)
If I look at the dev console on the cloud version I see this:
![image](https://user-images.githubusercontent.com/13787163/220753388-462832c5-3def-4f58-a83e-516dcb359a70.png)

### Reproduction Steps

1. Open this document: 
[error.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/10808124/error.docx)
2. Click after the end on the equation to move the cursor there:
![image](https://user-images.githubusercontent.com/13787163/220753787-2649dbbb-103d-4172-af83-fccde921a182.png)
3. Hold Shift, and press the left arrow key two times to select the second fraction
![image](https://user-images.githubusercontent.com/13787163/220753941-0a8c6460-31b2-4f3b-91d2-41b886c1d99c.png)
4. Release Shift, and press the left arrow key once more. You should see an error dialog pop up.

### Additional information

I'm using the AUR package, but that wasn't an option in the dropdown so I put .deb (I think the AUR package I'm using is built from the deb anyway). However I have confirmed that this happens on personal.onlyoffice.com through a web browser too, so I don't think it's platform-specific.

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.3 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
