### ISSUE TITLE
Document Editor crashes on `Ctrl`-`V`. Recent changes are lost.

### ISSUE THREAD

**Issue by HectorB-2020** [ONLYOFFICE/DocumentServer#2136]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1.36

### Expected Behavior

 Expected Behavior works without unexpected crashes. Document contents is preserved or recovered after restart.

### Actual Behavior

It stops with exception, asking to 'Save as'. But 'Save as' dialog doesn't open.
Editor windows becomes empty.
Added/modified text is lost.  :angry: 

### Reproduction Steps

**Is there a way to enable debug or trace internal actions?**
Nearly once a day OnlyOffice crashes ruining results of my work.
I'm inclined to dig what led to that.

**Comment by maruacat** [comment]
@HectorB-2020 
We have fixed this problem in the latest release version of Document Server and Desktop Editor - version 7.3.3.
Thank you very much!
