### ISSUE TITLE
Unable to display directory normally

### ISSUE THREAD

**Issue by wyb12345** [ONLYOFFICE/DocumentServer#2138]
For the same word document, the directory cannot be displayed normally in only office, but it can be displayed normally in the word software of office

![image](https://user-images.githubusercontent.com/35788437/222118964-2f459050-8715-4eb3-9c46-e21b13d1b008.png)
![image](https://user-images.githubusercontent.com/35788437/222119123-c3e2becb-3c3e-4ac4-851d-e8e99db6a10f.png)

**Comment by Gingetsu** [comment]
Hello, @wyb12345.
Could you please provide this file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
