### ISSUE TITLE
Cannot create forms any more after upgrading from 4.4.1 to 5.0.4

### ISSUE THREAD

**Issue by bugnetz** [ONLYOFFICE/DocumentServer#214]
Hi Devs!

After upgrading from 4.4.1 to 5.0.4 I can not create any forms any more as described in your manual here: https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/UsageInstructions/InsertRichTextContentControls.aspx

I even tested this with an embedded demo version on your official Website and had the same issue.

Is this an intended behaviour or can I expect to see this feature in the future again.

I am using Ubuntu 16.04 and Nginx.

Thanks in advance and best regards

**Comment by KirillovIlya** [comment]
We are very sorry, this was added to version 4.4 by mistake. Hot keys Shift + F * were added only for testing purposes and should not work in the release version. We will add a normal UI for this functionality. The page describing the addition of the form will also be redone.

Thank you for your issue.

**Comment by bugnetz** [comment]
Thank you for your fast respond. We are looking forward to this feature to be integrated.
