### ISSUE TITLE
Custom Math autocorrect rules dont't work since last update

### ISSUE THREAD

**Issue by 1nikolas** [ONLYOFFICE/DocumentServer#2147]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.0.184

### Expected Behavior

Custom math autocorrect rules should work

### Actual Behavior

When I set custom math autocorrect rules of any kind, they don't work. Predefined ones do work though.

### Reproduction Steps

1. Set any Math Autocorrect rule (let's say `\test` to `∙`)
2. Use a Math input and type `\test` + space
3. Nothing happens
4. Type `\sqrt` + space (works fine)

### Additional information

Was working fine in 7.2.1, using DesktopEditors

**Comment by ElenaMaaya** [comment]
Hi, @1nikolas!
This is a known Bug 61009 in our private issue tracker, which relates to the DocumentServer.
Thank you for contacting us.

**Comment by ElenaMaaya** [comment]
Hello @1nikolas! This bug is fixed in DocumentServer and DesktopEditors v7.4.0.
Thanks for contacting us!

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.0 is released so I close this issue. 
Feel free to comment or reopen it if you got further questions.
