### ISSUE TITLE
Message "No image uploaded" when i try insert image PNG format

### ISSUE THREAD

**Issue by HellRoad** [ONLYOFFICE/DocumentServer#215]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
No image uploaded

Steps:
  1.Open Document Server Welcome page
  2.Create Document
  3.Try to insert image (only PNG Format)

**What is the expected behavior?**
Insert image

**Did this work in previous versions of DocumentServer?**
Yes

**DocumentServer version:**
5.0.5 25 Windows Version

**Operating System:**
Win 10 Home x64

**Browser version:**
Chrome 62
P.S  on Linux version (5.0.5 26)  working correctly

**Comment by agolybev** [comment]
Fixed with https://github.com/ONLYOFFICE/sdkjs/commit/1ef3e35fc2d473ecad7f559f4348715f7f0ccf64
Relesed in [5.0.7](https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-5.0.7)
@HellRoad, could you verify the bug?

**Comment by HellRoad** [comment]
@agolybev 
Yes this bug is not reproduced in version 5.0.7
