### ISSUE TITLE
Font rendering issue when generating PDF

### ISSUE THREAD

**Issue by capybara614** [ONLYOFFICE/DocumentServer#2150]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.2.8

### Expected Behavior

When a pdf is printed, all fonts should be rendered as they show in the document editor. 

### Actual Behavior

When I try to print a pdf from a document that uses the CrayonE font, the text that should be rendered as cursive characters shows up as garbled text. 

### Reproduction Steps

1. Install custom fonts in the container, by putting them in /usr/share/fonts and running the documentserver-generate-allfonts.sh script.
2. Edit a document that uses one of the problematic fonts.
3. Use the print button
4. The browser's printing window that opens shows that the font is rendered incorrectly.

I am joining a [zip archive](https://github.com/ONLYOFFICE/DocumentServer/files/10899976/Onlyoffice.Font.Rendering.Issue.zip) containing files needed to reproduce the issue:
- 2 fonts that I have installed, OpenDyslexic which renders correctly and serves as a control and CrayonE which renders garbled characters when generating a PDF.
- A sample docx, which has a small sample of text in each font
- Two pdfs generated by Onlyoffice, one from the browser, the other using the ConvertService API
- A pdf generated by Libreoffice Writer from the same document in which the font renders correctly

### Additional information

As said here (https://github.com/ONLYOFFICE/DocumentServer/issues/1844#issuecomment-1455199617_), here's a new issue   @LuckySpecialist

**Comment by LuckySpecialist** [comment]
Hi @capybara614, I apologize for the long delay.
For this problem, issued Bug 63529 in our internal tracker.

**Comment by LuckySpecialist** [comment]
This issue is fixed by [this commit](https://github.com/ONLYOFFICE/core/commit/6f839a24de679c8575e4edda971f0620debdc2ee) and will be included in the next release version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by capybara614** [comment]
I can confirm that it is fixed on onlyoffice/documentserver:7.5.0.1.

My thanks to the team. :+1:
