### ISSUE TITLE
Unable to insert special char with <ALT> + ascii code

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DocumentServer#2152]
[Onlyoffice documentation](https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/UsageInstructions/InsertSymbols.aspx) claims that we can insert a symbol knowing his ascii code and using ALT + code.
It works on the Desktop Editor, but not on the onlyoffice nextcloud app.

Note that it works with a linux OS, using ctrl shift u + hexadecimal code, so I suppose the problem is about the ALT key which should be interpreted/captured by the browser or something

Tested on NC 25.0.4 and OnlyOffice Document Server 7.3.2.8 , Nextcloud OnlyOffice APP 7.6.8

**Comment by hahaxd35** [comment]
no problem pasting ¯ unicode stuff with ctr + shift + u

**Comment by Rita-Bubnova** [comment]
@Mer0me Sorry for the long wait.
DesktopEditors v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
