### ISSUE TITLE
Can't paste picture on a xlsx file

### ISSUE THREAD

**Issue by bundyboss** [ONLYOFFICE/DocumentServer#2153]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.3.2.8

### Expected Behavior

Before my update I was able to paste a picture directly in a cell.
It was working well on previous versions (not sure the version but I think 7.2)

### Actual Behavior

Now it's not working. I need to save a picture and to load it in the document

### Reproduction Steps

Take a screenshot of your desktop and try to paste the picture in a cell on a xlxs file

### Additional information

I'm using latest version of Chrome.

**Comment by Rita-Bubnova** [comment]
Hello, @bundyboss.
Think you for the report. 
This is issue 60963 in our private issue tracker. It fixed (https://github.com/ONLYOFFICE/sdkjs/commit/faf96f9407977cdb6a22f1626d6ecfe4b7695c19) in the next version. 

Problem actual in DocumentServer.

**Comment by DenisDeeSign** [comment]
DocumentServer v7.3.3 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by bundyboss** [comment]
I confirm it's working well ! Txs a lot !
