### ISSUE TITLE
Incorrect behavior of "\bar" in an equation

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2154]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.0

### Expected Behavior

It should be possible to add an horizontal bar on top of a variable in an equation.

### Actual Behavior

When typing "\bar" in an equation, the bar is located on the left of the variable.

### Reproduction Steps

Steps to reproduce:
- open a new text document
- insert an equation
- type "\bar" and then space
- type a character, e.g., "m" and then space
- => the bar is located on the left of the character

**Comment by ElenaMaaya** [comment]
Hello, @parrenin3.!
Thanks for the report!
I checked your issue. 
Please repeat these steps:
1. Open a new text document
2. Insert equation
3. Enter a character, such as "m"
4. Type "\bar" and double-click the space bar.

**Actual Behavior.**

Horizontal bar is on top of a variable in an equation.

Same behavior of this option in MS Word.

Always happy to help!

**Comment by parrenin** [comment]
Hello Elena,
Thanks for the tip, I did not know it was working this way.
I thought \bar had to be typed before the character.
