### ISSUE TITLE
Impossible to see comment on equation

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2156]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.0

### Expected Behavior

In the sample attached .docx file, the equation is commented, but I don't see a way to access the comment.

[bugOO-comment-on-equation.docx](https://github.com/ONLYOFFICE/DocumentServer/files/10942252/bugOO-comment-on-equation.docx)

### Actual Behavior

There is no way to see the comment on the equation.

**Comment by 0xMehedi** [comment]
> In the sample attached .docx file, the equation is commented, but I don't see a way to access the comment.

Clicking the _Comments_ icon on the left sidebar reveals the comments. Alternatively, you can press <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>H</kbd> to view the comments.

**Comment by parrenin** [comment]
> Clicking the Comments icon on the left sidebar reveals the comments. Alternatively, you can press Ctrl Shift H to view the comments.

Yes, I saw that, thanks.
But I think there should be a way to see the comment by just clicking on the equation, as is possible with the other comments on in the text.

**Comment by TatianaKirillova** [comment]
Hello, @parrenin
Thanks for your request!
I can confirm that the problem exists. I created ticket 61661 in our private  tracker with your  issue.

**Comment by parrenin** [comment]
This issue is even worse in 8.0.0.
Now, if I try to edit the equation, OO hangs.

**Comment by TatianaKirillova** [comment]
@parrenin I hasten to inform you that we have fixed the problems associated with comments in formulas in the hotfix version!

**Comment by parrenin** [comment]
This bug is now fixed in 8.0.1., you can close this bug report.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
