### ISSUE TITLE
Copy of a protected sheet should be unprotected by default

### ISSUE THREAD

**Issue by mwagner-git** [ONLYOFFICE/DocumentServer#2158]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi!

I made a spreadsheet with some protected sheets.
If I copy one of the protected sheets, the copy of the sheet is also protected.
This does not fit my workflow and the implementation in Google Sheets is also different.
I would prefer if the copy of the protected sheet is unprotected by default.
If I have access to the spreadsheet-file I can "steal" the content anyway.

My workflow is the following: I share my spreadsheet and the original sheets are protected.
Other people can copy my sheets and modify the content of the new sheets without beeing able to modify the original.

It is my first feature request, so please be kind if I am not used to the typical processes.

Regards,
Michael

**Comment by rsnegirev** [comment]
Hi, Michael @mwagner-git

This is the same behavior as in MS Excel or Libreoffice. Yes, it's different from Google Sheets, but correct way to work for our Editor.

Thank you for the request!
