### ISSUE TITLE
plugins => Events : onChangeContentControl cannot be triggered

### ISSUE THREAD

**Issue by GGBeng1** [ONLYOFFICE/DocumentServer#2159]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.2.8

### Expected Behavior

Fires the event function to return the current content control when it changes

### Actual Behavior

The content control change event did not fire

### Reproduction Steps

1 Insert content control
2 Input content text

**Comment by GGBeng1** [comment]
[7.3.3.49](https://hub.docker.com/layers/onlyoffice/documentserver/7.3.3.49/images/sha256-ce4379016dc7070ffe3ae831a93f40f74fd27b3e547a56b6e86bd73e6a0c4f75?context=explore)

**Comment by GGBeng1** [comment]
[7.3.3.49](https://hub.docker.com/layers/onlyoffice/documentserver/7.3.3.49/images/sha256-ce4379016dc7070ffe3ae831a93f40f74fd27b3e547a56b6e86bd73e6a0c4f75?context=explore)The plugin for the Community Edition image is still unable to use this event

**Comment by askonev** [comment]
Hello @GGBeng1. Currently in the api.onlyoffice.com documentation there is an incorrect example of using the onChangeContentControl event

Example of use:

Event initialization in config.json
```json
    "variations" : [ 
            {
            ...
            "events" : ["onChangeContentControl"],
            ...
           }
```

Using Event

```js

        var _plugin = window.Asc.plugin

        _plugin.event_onChangeContentControl = function(control){
            console.log(control);
        };

```

**Comment by GGBeng1** [comment]
Thank you very much, my friend. Thank you again for your help
