### ISSUE TITLE
Update restore default configuration

### ISSUE THREAD

**Issue by Floflobel** [ONLYOFFICE/DocumentServer#216]
When I update onlyoffice-documentserver with repo package the config are restored to default.

I have set up a specific:
/etc/nginx/conf.d/onlyoffice-documentserver.conf
/etc/onlyoffice/documentserver/default.json

I configured these two files with specific settings but when upgrading from 5.0.4-15 to 5.0.5-26 the configurations were reset by default.
This is a problem because my nginx configuration is no longer good and the installation never succeeds. And my secret key which is defined in the file "default.json" is deleted.

To solve the problem, I have to put back my old configuration that I saved.

Would it be possible not to change the basic configuration ? 
If we take the example of another package like nginx, when updating if we have a specific configuration, it is not changed. But in our case it is overwritten by the onlyoffice-documentserver package.

**Comment by ShockwaveNN** [comment]
Yeah, we agree, this is not correct behaviour

**Comment by agolybev** [comment]
Hi We're going to fix it in v5.1

**Comment by ClundXIII** [comment]
I am also affected by this issue (I just updated).

A backup into .json.old should be doable with minimal effort IF you would be so nice to notice user about this behaviour here: https://helpcenter.onlyoffice.com/server/linux/document/upgrade-document.aspx

Now I need to search for my database password ... argh!

**Comment by igwyd** [comment]
Hello @Floflobel , sorry for the late reply. Now changes in ```/etc/nginx/conf.d/ds.conf``` saved while update. About default.json - you can add your custom changes in ```/etc/onlyoffice/documentserver/local.json``` this file will not be replaced after the update.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
