### ISSUE TITLE
There is no Accept All track changes button.

### ISSUE THREAD

**Issue by alan-esper** [ONLYOFFICE/DocumentServer#2166]
Hello! 
There is no Accept All track changes in my Only Office nor in the only office API doc
<img width="1296" alt="Screen Shot 2023-03-09 at 11 48 56 AM" src="https://user-images.githubusercontent.com/105375452/224138015-8140fae0-e683-4c17-a62d-1b84d2ea0ece.png">

However, it seems like this feature exists?
https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/helpfulhints/review.aspx#:~:text=Accept%20or%20reject%20changes&text=To%20quickly%20accept%20all%20the,the%20Accept%20All%20Changes%20option.

**Comment by alan-esper** [comment]
Hi! Thank you so much for getting back to me.  Can you elaborate on disabling the reviewGroups option? 
The current implementation for the config is this:
```
export interface IEditorPermissions {
  comment?: boolean;
  commentGroups: {
    edit: string[];
    view: string[];
    remove: string[];
  };
  copy: boolean;
  deleteCommentAuthorOnly: boolean;
  download: boolean;
  edit?: boolean;
  editCommentAuthorOnly: boolean;
  fillForms: boolean;
  modifyContentControl: boolean;
  modifyFilter: boolean;
  print: boolean;
  review?: boolean;
  reviewGroups?: string[];
}

const defaultEditorPermissions = {
  comment: true,
  commentGroups: { edit: [''], view: [''], remove: [''] },
  copy: true,
  deleteCommentAuthorOnly: false,
  download: true,
  edit: true,
  editCommentAuthorOnly: false,
  fillForms: true,
  modifyContentControl: true,
  modifyFilter: true,
  print: true,
  review: true,
  reviewGroups: [''],
} as IEditorPermissions;
```

These are the ways I have tried but I end up encountering this error

-  Removing reviewGroups from IEditorPermissions and defaultEditorPermissions
-  Setting reviewGroups to accept both `string[] | string` to be able to  pass in `reviewGroups: ''`  in defaultEditorPermissions (as mentioned in the api doc "If the value is "" or not specified, then the user can review changes made by any user.")

<img width="432" alt="Screen Shot 2023-03-14 at 10 40 28 AM" src="https://user-images.githubusercontent.com/105375452/225091675-da75a865-1963-481c-bd7e-ecec5949c40a.png">

Any help or pointers would be appreciated! Thanks!

**Comment by SergeyKorneyev** [comment]
The solution here is to set the value of **reviewGroups** to **null**: 
```
    "document": { 
      "permissions": {
        "reviewGroups": null
```

The option will be available then.
