### ISSUE TITLE
PPT自动翻页

### ISSUE THREAD

**Issue by hwwjason** [ONLYOFFICE/DocumentServer#2169]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

你好开发者，我有办法通过api操作ppt自动翻页吗

**Comment by stepjacky** [comment]
you  can  view  the  builder  api  of  slider or get  it

**Comment by askonev** [comment]
@stepjacky Class https://api.onlyoffice.com/docbuilder/presentationapi/apislide representing a slide. May be define example?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
