### ISSUE TITLE
Error when "track changes" is activated

### ISSUE THREAD

**Issue by ZID-TU-Graz** [ONLYOFFICE/DocumentServer#2175]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.2.8

### Expected Behavior

No error occurs during editing

### Actual Behavior

When "tack changes" is activated and a text with bullet points is added and deleted then an error message occurs and an empty page is shown

https://user-images.githubusercontent.com/100593683/225860193-0859c6dc-7c51-4f4b-9476-f3c1fac1ed79.mov

![e44bc8a6-7426-436a-a08d-45c62c879eda](https://user-images.githubusercontent.com/100593683/225861006-49f2e2f8-1d96-4843-b801-118d121c7b19.PNG)

### Reproduction Steps

1. Create a text document and open it 
2. Activate "track changes"
3. Add a text with bullet points
4. Delete the paragraph
5. Editing is not possible, a error occurs (error message in german: "Bei der Arbeit mit dem Dokument ist ein Fehler aufgetreten." and and empty page is shown. (Reload does not help)
6. After some time everything works again

### Additional information

onlyoffice is used with the nextcloud app (app version: 7.6.8, NC Version 25.x).
Used browsers: Firefox 111.0 (Windows 11)

**Comment by KirillovIlya** [comment]
Hello, thanks for your report
This issue will be fixed in 7.3.3 version

Here is the commit 
https://github.com/ONLYOFFICE/sdkjs/commit/1405b6c1756ff1013510bfe5e55f7051221b12fb
