### ISSUE TITLE
Copy & Paste from context menu doesn't work

### ISSUE THREAD

**Issue by Akrobs** [ONLYOFFICE/DocumentServer#2182]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.3.3

### Expected Behavior

Since version 7.3.0 doesn't work exactly

### Actual Behavior

If I copy text through the context menu from the document, then the text is not pasted into the document. If you copy and paste through the hot keys Ctrl+C & Ctrl+V, then the function works. Some users copy through the context menu.

### Reproduction Steps

1) Copy some text from another document via context menu
2) Paste via context menu
3) Nothing happens

### Additional information

This bug only online editor. Desktop editor works fine via contex menu.

**Comment by VladimirProkofiev52** [comment]
Hi! @Akrobs,

This is not an error.

This behavior is specially implemented in the WEB version of the editor.

When you try to paste through the context menu, an information window should appear.
![Capture](https://user-images.githubusercontent.com/86404945/229131172-ced9224c-ed18-4377-a689-2c7bfed0cd4f.PNG)

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
