### ISSUE TITLE
Tables don't show correctly from a .doc file

### ISSUE THREAD

**Issue by andreldmonteiro** [ONLYOFFICE/DocumentServer#2185]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.3.0.184 (flatpak)

### Expected Behavior

Tables should show correctly.

### Actual Behavior

Tables are very thin.

![issue](https://user-images.githubusercontent.com/56444382/225137095-229b7dcf-bb99-4695-93ef-81477e84f11d.png)

### Reproduction Steps

1. Open file

### Additional information

File:
[江苏领辉M5仪表_2号协议&5S协议说明书-V1.1 - EN.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/10973735/M5._2.5S.-V1.1.-.EN.zip)

**Comment by ElenaMaaya** [comment]
Hello @andreldmonteiro! I have a good news! This issue will be fixed in the next release. We advise you to follow the updates.
