### ISSUE TITLE
Some builtin fonts are rendered as blank while exporting as PDF or printing

### ISSUE THREAD

**Issue by ljn917** [ONLYOFFICE/DocumentServer#2189]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.3.49

### Expected Behavior

All builtin fonts should be rendered correctly when exporting or printing

### Actual Behavior

Some builtin fonts are rendered as white spaces

### Reproduction Steps

1. Create a new docx file
2. Type: `12345678`
3. Select the text and set its font to `WenQuanYi Zen Hei` (or `Noto Sans Tamil`, most of the Noto Sans do not work)
4. Export to PDF (or print)

### Additional information

Some builtin fonts work, e.g. FreeSans and Open Sans.

In addition, I have custom fonts installed, but they should not interfere, I guess.

**Comment by XDmitryK** [comment]
@ljn917 
Hello, can you attach a screenshot here showing the difference?
But i dont see difference on my pc. I used Font WenQuanYi Zen Hei Sharp Regular
![photo_2023-04-12_12-44-19](https://user-images.githubusercontent.com/46962983/231423740-58888d6d-f441-4643-9051-360d17f18957.jpg)
If possible, can you share a link to the fonts you use?

**Comment by ljn917** [comment]
It seems this issue went away with 7.3.3.50 (docker). Closing it for now. Thanks for your investigation.
