### ISSUE TITLE
[Debian 12] Cannot install or uninstall, two different errors

### ISSUE THREAD

**Issue by SSUPII** [ONLYOFFICE/DocumentServer#2190]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.3-49~stretch

### Expected Behavior

The server package should install and uninstall without issues.

### Actual Behavior

When installing:
ERROR: can't connect to postgressql database

When uninstalling:
Stopping documentserver services...
unlink: impossibile scollegare '/etc/nginx/conf.d/ds.conf': File o directory non esistente

### Reproduction Steps

https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx has been followed, with the only difference being:
`echo onlyoffice-documentserver onlyoffice/ds-port select 5656 | sudo debconf-set-selections`

### Additional information

The package is currently half-installed, but cannot be completed due to the first error. Can't also be purge because of the second error. The install can be restarted by deleting the `postrm` file of the package and purging (will not remove any files). But restarting makes no difference.

**Comment by hahaxd35** [comment]
Debian 12 RC1 was released on monday

**Comment by SSUPII** [comment]
> Debian 12 RC1 was released on monday

You are talking about the installer. This is Debian 12 and its currently in its final stretch before leaving the `testing` branch  in probably a few months.

**Comment by chriscroome** [comment]
I'd suggest creating a Debian Bookworm thread on [the forum](https://forum.onlyoffice.com/c/documents/32) for this problem, I believe that this repo is a mirror of an internal ONLYOFFICE one and it appears that issues raised here don't get the same attention as they get when raised on their Discourse forum.

**Comment by SSUPII** [comment]
> I'd suggest creating a Debian Bookworm thread on [the forum](https://forum.onlyoffice.com/c/documents/32) for this problem, I believe that this repo is a mirror of an internal ONLYOFFICE one and it appears that issues raised here don't get the same attention as they get when raised on their Discourse forum.

Thanks for your suggestion. I will do it as soon as I have the time.

**Comment by igwyd** [comment]
Hello @SSUPII, Debian 12 is stable now. I checked your Reproduction Steps with the same port in the debconfig, onlyoffice-documentserver installed without issues. I guess that issue was in the unreleased Debian 12 and fixed in stable.

**Comment by igwyd** [comment]
@SSUPII could you please re-install the document server on Debian 12 stable and close this if there is no errors.

**Comment by SSUPII** [comment]
> @SSUPII could you please re-install the document server on Debian 12 stable and close this if there is no errors.

Just tried. I did manage to install it now, but after noticing a different issue. 

Here is what might have happened as this is entirely an error on my part. During a previous attempt, I might have set the wrong password instead of the default one when prompted by debconfig. Despite the server being then uninstalled, it has remembered what I have set so it never prompted me for new data ever again. The workaround I have done could be removed after a `dpkg-reconfigure` and setting the right data as debconfig technically still had the wrong password saved.

At most what I can suggest is to either let the user reinsert their server and user data when this isn't reachable, or let the error being more descriptive.

I think this issue can be closed as the error was fixed, sorry for wasting anyone's time.

<details> 
  <summary>A little more of what I did under this spoiler, so to not clutter this page.</summary>
   
I still got:
`ERROR: can't connect to postgressql database`
during the post-installation script at first.

The version apt is installing is `7.4.1-36`

I checked what port postgresql is using and it's 5432, the one listed in the ports sections of the onlyoffice documentation.

The error seems to come from this function:
```
install_postges() {
        if [ -n "$DB_PWD" ]; then
                export PGPASSWORD="$DB_PWD"
        fi
        PSQL="psql -q -h$DB_HOST -p${DB_PORT:="5432"} -d$DB_NAME -U$DB_USER -w"
        # test postgresql connection
...
```

Line 5 of this snipped, `PSQL="psql -q -h$DB_HOST -p${DB_PORT:="5432"} -d$DB_NAME -U$DB_USER -w"`, doesn't work and is not setting `PSQL`.

Checking manually, looks like $DB_PWD is getting filled with a non-default and wrong password. Connecting to the database manually using the password written inside the variable returns `psql: error: Failed to connect to server on 'localhost' (::1), port 5432: FATAL: Password authentication failed for user 'onlyoffice'` (This error is machine translated)

Using the default password to manually connect instead works just fine.

Knowing this, I have passed the issue by **hardcoding** the password on line 68 of the post-install script, where PD_PWD is being set.

After this workaround, the rest of the server installed and the example editor is working properly.

But reading the .config script, I noticed all the fields not being prompted at all.
</details>
