### ISSUE TITLE
PDF Export from Presentations is Buggy

### ISSUE THREAD

**Issue by T-Herrmann-WI** [ONLYOFFICE/DocumentServer#2192]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.3

### Expected Behavior

All graphics inside presentations should be part of the PDF exported version. By using MS Powerpoint 365 the export it works with OnlyOffice DocumentServer and Desktop Clients the export shows bug with same PPTX sources file.

### Actual Behavior

Bug: Some graphics inside presentations are not part of the PDF exported version and some are cropped. 

### Reproduction Steps

This Bug is part in all version I used since 2022 and also on the Desktop Clients.

### Additional information
I use MacOS Ventura as Desktop OS.

Demo Files for the Bug: https://github.com/T-Herrmann-WI/onlyoffice-dev/tree/main/ONLYOFFICE_PDF_BUG_1

OnlyOffice Version PPTX:
https://github.com/T-Herrmann-WI/onlyoffice-dev/blob/main/ONLYOFFICE_PDF_BUG_1/Test_OnlyOffice.pptx

OnlyOffice Version PDF Export with missing graphic:
https://github.com/T-Herrmann-WI/onlyoffice-dev/blob/main/ONLYOFFICE_PDF_BUG_1/Test_OnlyOffice_PDF.pdf

Powerpoint Version PPTX:
https://github.com/T-Herrmann-WI/onlyoffice-dev/blob/main/ONLYOFFICE_PDF_BUG_1/Test_Powerpoint.pptx

Powerpoint Version PDF Export without errors:
https://github.com/T-Herrmann-WI/onlyoffice-dev/blob/main/ONLYOFFICE_PDF_BUG_1/Test_Powerpoint.pdf

**Comment by Gingetsu** [comment]
Hello, @T-Herrmann-WI. Our dev team is fixed your issue in next version (But sorry, no exact ETA)This fixed here: https://github.com/ONLYOFFICE/core/pull/1176/commits/2e8bb7177cd7d3a335427db588eb5d5f3ac6773a

**Comment by T-Herrmann-WI** [comment]
Thank you for this good news.

**Comment by DenisDeeSign** [comment]
DocumentServer v7.4.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
