### ISSUE TITLE
html对docx文件内容的操作

### ISSUE THREAD

**Issue by wwjje** [ONLYOFFICE/DocumentServer#2194]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

我的需求是，有一个基础模板docx文件，还有n个素材docx文件，素材文件里，可能是带样式的文字、图片、表格等，用户预览素材列表，点击插入按钮，素材插入到基础模板docx文件**光标位置**。用户会不停的插入素材至基础模板docx文件里，最终下载生成文件。请问使用什么API进行素材所有内容的读取，然后插入到基础模板docx文件光标位置呢？谢谢！

**Comment by askonev** [comment]
@wwjje Please translate your question into English so that you can refer to these answers in the future

**Comment by wwjje** [comment]
Well, thank you

**Comment by askonev** [comment]
Perhaps a solution based on a self-developed plugin for ONLYOFFICE editors will work for you

If you describe the scenario repeatedly

1. User opens a template docx document for editing
2. opens the plugin
3. In the plugin selects the required reference document from the list
4. The document is installed in rich content control in the part of the template document specified by the user

Installing third-party documents by url is implemented in the plugin example
https://github.com/ONLYOFFICE/sdkjs-plugins/tree/master/example_work_with_content_controls

Also if you have any questions about working with plugin api we are always happy to help you

**Comment by trofim24** [comment]
I closed the issue. @wwjje if you have another question about this scenario, please reopen the issue. If you have any questions about the product open new issue.
