### ISSUE TITLE
Document loader implementation

### ISSUE THREAD

**Issue by sysint64** [ONLYOFFICE/DocumentServer#22]
Hello, I want to extend editor and add minimal language for rendering new elements e.g. I want display current time in document, I write in doc 

`time{url:http://www.timeapi.org/utc/now}`

or if I want to add link to user at chat, I need to write `@user{go:chat}`

Where in a source code can I find document loading implementation (creating all elements on view such as images, paragraphs, headers etc.).

Thanks in advance!

**Comment by ibnpetr** [comment]
These features will be introduced in the future versions
Feel free to share your thoughts with us in the [appropriate forum] (http://dev.onlyoffice.org/viewforum.php?f=42&sid=259ff5c802c1135088353d23855a860e)

**Comment by vokshirg** [comment]
As I understand @sysint64 wanted to ask the name of file in code, where he could change some functions

**Comment by trofim24** [comment]
> Where in a source code can I find document loading implementation (creating all elements on view such as images, paragraphs, headers etc.).

[Paragraphs creating in file DocumentServer/OfficeWeb/sdk/Word/Editor/Document.js](https://github.com/ONLYOFFICE/DocumentServer/blob/master/OfficeWeb/sdk/Word/Editor/Document.js)
in function: `Add_NewParagraph: function (bRecalculate, bForceAdd)`

**Comment by trofim24** [comment]
We are release Open Source Version and file move to
https://github.com/ONLYOFFICE/sdkjs/blob/master/word/Editor/Document.js#L3740
