### ISSUE TITLE
Api is not defined

### ISSUE THREAD

**Issue by wwjje** [ONLYOFFICE/DocumentServer#2205]
`function getContent() {
  var oDocument = Api.GetDocument();
  var aDocElements = oDocument.GetContent(true);
  return aDocElements;
}`
Api is not defined

**Comment by askonev** [comment]
@wwjje if you have get to the firs element in the docuement please see the examples for the documentbuidler api.

To use this script in macros, just get rid of the `builder` commands and wrap the script in an anonymous function.

```js

(function()
{

})();
```

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
