### ISSUE TITLE
Delay experienced when zooming in/out on files in iOS web

### ISSUE THREAD

**Issue by rupalijaiswal** [ONLYOFFICE/DocumentServer#2206]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

6.3.1

### Expected Behavior

When zoomed in and out on the page contents, it should not lag and have a smoother UI experience.

### Actual Behavior

While zoom in or zoom out is performed on iOS version 16.4.1 onlyoffice web files there is a delay of few seconds before it takes effect.

**Comment by mariabondareva** [comment]
Hi @rupalijaiswal !
I can confirm, this is a bug
I've created issue 62087 in our private issue tracker

**Comment by gagandeepsinghubbi** [comment]
Hi @DenisDeeSign @mariabondareva ,

We are facing this issue as well. Any updates on when this will be fixed?

**Comment by mariabondareva** [comment]
> Hi @DenisDeeSign @mariabondareva ,
> 
> We are facing this issue as well. Any updates on when this will be fixed?

Now we can't say when the problem will be fixed.

**Comment by shibliansari** [comment]
This performance issue looks same on iPad devices too. @gagandeep @DenisDeeSign @mariabondareva

**Comment by shibliansari** [comment]
@DenisDeeSign @mariabondareva any new update on fixing this? waiting.

**Comment by mariabondareva** [comment]
Hi, @shibliansari! The problem has been fixed in version v.7.4.0

**Comment by DenisDeeSign** [comment]
DocumentServer v7.4.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
