### ISSUE TITLE
Webpage becomes unresponsive when zooming in/out on files in iOS web

### ISSUE THREAD

**Issue by rupalijaiswal** [ONLYOFFICE/DocumentServer#2207]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

6.3.1

### Expected Behavior

Webpage should not become unresponsive on zoom in and out on files.

### Actual Behavior

When zoomed in or out on onlyoffice web files for 2-3 times the page becomes unresponsive.

This behaviour is observed in iOS version 16.3.1.

**Comment by rupalijaiswal** [comment]
> @rupalijaiswal , I can't reproduce this problem with the last version of Document Server 7.3.3 , iOS 16.3.1 Please, try to update your Document Server version.

Hi @mariabondareva,
I have been able to reproduce the issue with latest version of OnlyOffice using the sample spreadsheet and PPT files.
You might have to zoom in and out a few times continuously to see this behavior.

**Comment by gagandeepsinghubbi** [comment]
Hi @mariabondareva ,

I am able to recreate this with iOS 157 and 16.3.1 as well.

**Comment by mariabondareva** [comment]
@rupalijaiswal could you please send a video?
 I know about problem with the presentation editor freezing after zoom at maximum, but I don't see this behavior in the sample spreadsheet. I zoom the spreadsheet several times, but the buttons in the toolbar and the context menu work without problems after these actions.

**Comment by gagandeepsinghubbi** [comment]
https://user-images.githubusercontent.com/130988419/233323122-cd16401e-05a9-4064-9d26-ec1ea81935e7.mp4

Hi @mariabondareva  Please find the video attached where we are seeing the same behavior is spreadsheets.

**Comment by gagandeepsinghubbi** [comment]
Hi @mariabondareva Hope you were able to recreate the problem refferring the video. Let us know if you need any more details.

**Comment by mariabondareva** [comment]
@gagandeepsinghubbi tell please, can you reproduce this problem with the last version of Document Server 7.4.1?
