### ISSUE TITLE
Broken UTF-8 encoding when importing CSV

### ISSUE THREAD

**Issue by natoponen** [ONLYOFFICE/DocumentServer#2211]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.2

### Expected Behavior

UTF-8 symbols from importing CSV/TXT are encoded properly.

### Actual Behavior

Encoding of input is broken:
![image](https://user-images.githubusercontent.com/57988162/232513328-5a5b494d-8198-4af0-ad99-534ac98419db.png)

### Reproduction Steps

1. Create txt file with some comma separated words not in English (Russian, for example).
2. Create spreadsheet
3. Import txt with "Data -> Get Data -> From Local TXT/CSV"

**Comment by maruacat** [comment]
Hello, @natoponen 
This is known issue 61839 in our internal issue tracker.
Thank you for report.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/0ecfbe9c85fd92a8bedc757891c9465c881dbf97, https://github.com/ONLYOFFICE/sdkjs/commit/976c0eb76874a7e6279192b306d2c1bce01d24d0, https://github.com/ONLYOFFICE/sdkjs/commit/7f946c6abb90e695870c1354bc76f7329d40d944) in DocumentServer мукышщт 7.4.0.

DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
