### ISSUE TITLE
Document Bouncing When Editing A Shared Document

### ISSUE THREAD

**Issue by ZID-TU-Graz** [ONLYOFFICE/DocumentServer#2212]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.3

### Expected Behavior

When editing a document, I want to be able to see what I'm editing. I don't want the document to start jumping up and down

### Actual Behavior

Similiar to #1955 

https://user-images.githubusercontent.com/100593683/232754833-cda2850f-719d-4c2e-91ee-1ff7e13aed80.mp4

### Reproduction Steps

1. Share a document with multiple people using an external link (or a document shared with a circle)
2. Set everyone's access (the shared external link) to full access
3. Have everyone edit the document at the same time live

### Additional information

NC 25.0.5
OnlyOffice Nextcloud App 7.8.0

**Comment by XDmitryK** [comment]
Hello, @ZID-TU-Graz 
I can confirm - this is bug, issue 61733 in our private issue tracker.
Thank you for report.

**Comment by KirillovIlya** [comment]
All problems should be fixed in the new version 7.4

**Comment by Rita-Bubnova** [comment]
This is fixed (https://github.com/ONLYOFFICE/sdkjs/commit/961d07db8d9acdb65ed8e8bae7b43d1bee09a4cd) in DocumentServer v7.4.0.
So I close this issue. Feel free to comment or reopen it if you got further questions.
