### ISSUE TITLE
Macros can access window and document via globalThis

### ISSUE THREAD

**Issue by KernelDeimos** [ONLYOFFICE/DocumentServer#2213]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.2.56

### Expected Behavior

Macros shouldn't be javascript code at all. It would make more sense to use an embedded lua interpreter written in javascript. Why? Because sandboxing user-entered javascript code in a secure manner is so non-trivial that it is effectively impossible.

### Actual Behavior

I was able to gain access to window and document simply by using `globalThis` in my macro.

### Reproduction Steps

1. Create a macro
2. console.log(globalThis.window)

**Comment by K0R0L** [comment]
Fixed in 7.4
