### ISSUE TITLE
Issue with dead keys chars - circumflex - utf8

### ISSUE THREAD

**Issue by pierreozoux** [ONLYOFFICE/DocumentServer#2216]
Hi,

we have a strange issue.
The OS of the 2 users that can reproduce the issue is:
 - Firefox 111.0.1
 - Ubuntu 22.04.2 LTS
(A user with Ubuntu 18 can't reproduce.)

When I write an accented char without dead keys, it works as expected.

When I write an accented char with a dead key, on my keyboad, I press: "alt + \`" and then the char I want accented, like "e".
(or `alt + i` and then `o` to make `ô`)

When I do that, I expect that the char is written in place, but instead, it goes to the end of the line.

![Screenshot 2023-04-07 at 12-11-51 Files - Nuage Liiibre](https://user-images.githubusercontent.com/1863453/230591054-640cad97-f176-422e-b02f-5347f399efa3.png)

It looks related to this issue:
https://github.com/ONLYOFFICE/DocumentServer/issues/409

I'm trying to gather feedback about combination of OS/Browser:
 - https://forum.indiehosters.net/t/comportement-bizarre-dans-onlyoffice/4899
 - https://forum.chatons.org/t/onlyoffice-nextcloud-comportement-bizarre-dead-keys-accents/4724

I'm using the docker image, and I could reproduce with:
 - [7.3.3.49](https://hub.docker.com/layers/onlyoffice/documentserver/7.3.3.49/images/sha256-ce4379016dc7070ffe3ae831a93f40f74fd27b3e547a56b6e86bd73e6a0c4f75?context=explore)
 - [7.2.2.56](https://hub.docker.com/layers/onlyoffice/documentserver/7.2.2.56/images/sha256-5d865fe631ab4d6f5806e0c3ed6b973c8a98b76b292f9348a72431f907458021?context=explore)

**Comment by ElenaMaaya** [comment]
Hello @pierreozoux!
Thank you for report!
I can confirm that the problem exists. I created ticket  62251  in our internal tracker with your issue.
Problem reproduces in Document Server.

**Comment by ayakael** [comment]
I also encounter this issue the debian package version on version 7.4.4. Is there a workaround that I can share with my users?

**Comment by pierreozoux** [comment]
I tested with ff 115:
```
nix-shell -p firefox-esr -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4ab8a3de296914f3b631121e9ce3884f1d34e1e5.tar.gz
```

and I could reproduce.

But, the good news is that with ff 118, the bug seemed fix!

I'll close the issue on my side.
