### ISSUE TITLE
DocumentServer:Editor/messy toolbar display with 'zh-CN' for lang 

### ISSUE THREAD

**Issue by BurizaDo** [ONLYOFFICE/DocumentServer#222]
editorConfig: {
     lang: "zh-CN",
    ....
}
as I set the lang with zh-CN, most behaviors are correct, except the toolbar on the top-right area.
as attached:

![screen shot 2017-12-09 at 6 12 25 pm](https://user-images.githubusercontent.com/2141706/33794731-957c53a4-dd0c-11e7-96d7-ccbb84e8429c.png)

Does anyone have the idea about how to fix this? Or is it because zh-CN has not been fully supported? 
Thanks in advance.

**Comment by agolybev** [comment]
Hi @BurizaDo, could you provide any document example where problem happened?

**Comment by agolybev** [comment]
It works for me: ![guanlibanfa2](https://user-images.githubusercontent.com/8861642/33825416-9b050886-de72-11e7-8976-6a479f187643.png)
It seems there aren't fonts referred in styles. Could you check is there `Arial` installed on the server and is there 'Arial' font listed in the font checkbox.

**Comment by BurizaDo** [comment]
I wanna Chinese be supported on the toolbar and all the UI of the editor,  not just the content of the document.

Please start the editor with 'zh-CN' for 'lang' parameter like 
editorConfig: {
lang: "zh-CN",
....
}
and you will see the 'Heading ....' buttons been displayed  in unrecognized format.

**Comment by BurizaDo** [comment]
![Uploading Screen Shot 2017-12-11 at 6.18.15 PM.png…]()
@agolybev it's in English, I guess you started the editor with 'en' for lang :)

**Comment by BurizaDo** [comment]
![screen shot 2017-12-11 at 6 18 15 pm](https://user-images.githubusercontent.com/2141706/33826510-3297f4d8-dea0-11e7-8873-faa799d5b570.png)

@agolybev it's in English, I guess you started the editor with 'en' for lang :)

**Comment by agolybev** [comment]
OK, I understand. I think you use unofficial Chinese localization. Unfortunaly Document Server doesn't support Chinese UI. 
The problem occur because translated default style names contain symbols that don't exist in font of style. We are going to replace such symbols form another font, but it will be done later.

**Comment by BurizaDo** [comment]
@agolybev could you tell me where to change ? I add the Chinese code in translation.js and build the code on my server but that doesn't work.

**Comment by agolybev** [comment]
Hi @BurizaDo, I think you may to change style fonts  in the the new document template but it will be work only for new documents. Unfortunaly, Document Server hasn't got such functionality at this moment.  However I can do it with Microsoft Office. Also I should know how do you use Document Server to reffer you to the new document tepmlate location.

**Comment by BurizaDo** [comment]
@agolybev I follow the instruction below to build on my server.
http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx
 
Currently I'm using the JAVA sample and put the document in the folder extracted from the war file, then access the editor directly using http://sampleurl.com/EditorServlet?mode=edit&fileName=document.docx

**Comment by 3xxx** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/7
here is ok for chinese toolbar.

**Comment by linmsh** [comment]
为什么我的字体显示“yahei”而不显示“微软雅黑”

**Comment by ShockwaveNN** [comment]
This is quite old issue but I think it's should be resolved for quite some time

I've checked v7.1.0 and it's looking fine:
![image](https://user-images.githubusercontent.com/668524/169235141-109408b4-937e-4d1f-be14-85065b3a069d.png)

I'll close this issue, but if you got any more troubles - I think it's better to create a new one
