### ISSUE TITLE
Fonts of the printed text are not smooth

### ISSUE THREAD

**Issue by ostasevych** [ONLYOFFICE/DocumentServer#2220]
Comparing two texts printed from my office text editor and the onlyoffice I found that the letters on the text printed through OO do not look like smooth and clear. What can be done with that?

**Comment by Rita-Bubnova** [comment]
Hello, @ostasevych.
Sorry for late restonse, seems we missed this issue.DocumentServer v7.4.1 is released. Please state is this problem still actual for you?
Please, fill in all the fields of the form completely.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
