### ISSUE TITLE
I use ONLYOFFICE Personal (web) on Firefox to edit my docs/sheets from OneDrive, and I always lose my changes

### ISSUE THREAD

**Issue by tp01-gogogo** [ONLYOFFICE/DocumentServer#2222]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

ONLYOFFICE Personal - Document management: ONLYOFFICE App Server v.1.2.0 Online editors: ONLYOFFICE Docs v.7.3.3.49

### Expected Behavior

The changes should be saved.

### Actual Behavior

ONLYOFFICE cloud: Personal 
Report a bug: I connect my OneDrive account to ONLYOFFICE. And I use ONLYOFFICE Personal (web) on Firefox to edit my docs/sheets from OneDrive, and I often lose my changes, my changes cannot synchronize to OneDrive. Please fix it.
pictures are here:
1.I edit my documents in OneDrive
![2023 04 24_13 51 35](https://user-images.githubusercontent.com/111100869/233913653-c779e32d-7e74-4cb1-9e64-2cb211667643.png)

2.All changes saved
![2023 04 24_14 01 27](https://user-images.githubusercontent.com/111100869/233913674-4e500a23-cf4e-480a-8e39-f5a9f53299ed.png)

3.I close webpage but sometime I see this icon and i wait a long time, about thousands hour, this icon is still here, and my changes losed.
![2023 04 24_13 50 50](https://user-images.githubusercontent.com/111100869/233913682-c01a253b-6d5a-43c6-adfb-3bfba24393cb.png)

I use ONLYOFFICE Personal (web) on Firefox to edit my docs/sheets from OneDrive, and I always lose my changes.

**Comment by LuckySpecialist** [comment]
Hi, @tp01-gogogo!
I connected my OneDrive account to my personal portal. Documents are created and saved correctly.
Maybe there is something to add to your usage scenario?
Tested on Windows 11 Pro 22H2 x64 + Firefox 112.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
