### ISSUE TITLE
The only offer installed in Windows 10 always prompts for loading documents when opening Word

### ISSUE THREAD

**Issue by huweibo2046** [ONLYOFFICE/DocumentServer#2229]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

loading documents 

### Expected Behavior

loading documents 

### Actual Behavior

loading documents

**Comment by rsnegirev** [comment]
Hi @huweibo2046 

Could you please provide reproduction steps?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
