### ISSUE TITLE
[Spreadsheet] incorrect auto-completion of formulas 

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#223]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In spreadsheet, selecting cells from an other sheet to complete a formula lead to an error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![bug_formula](https://user-images.githubusercontent.com/11867613/33874483-3e049982-df1f-11e7-9b99-02631546a610.gif)

**What is the expected behavior?**
Same when you complete a formula from the same sheet : change of cell number

![expected_behaviour](https://user-images.githubusercontent.com/11867613/33874496-477df760-df1f-11e7-87f4-86af5c2da958.gif)

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.0.6.14

**Operating System:**
Docker 17.09.1

**Browser version:**
Firefox 57.0.2 (64bits)

**Comment by ShockwaveNN** [comment]
Yeah, thanks, seems like a bug.
We try to fix it in future releases

**Comment by ydelattre** [comment]
Great, thanks for your quick answer !
Yoann

**Comment by ydelattre** [comment]
Hello,
This issue is fixed with the document server version 5.0.7.
Thanks !
Yoann.
