### ISSUE TITLE
Editor.bin CORS

### ISSUE THREAD

**Issue by leon-W-yao** [ONLYOFFICE/DocumentServer#2234]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

6.4.0-121

### Expected Behavior

ws://{ip}/6.4.0-121/doc/8aaa804587d269390187efe97a4500f8_1/c/767/3t4gwofv/websocket
这是一个websocket请求,返回的数据应该是这样：
![image](https://user-images.githubusercontent.com/20450161/236611534-8385f413-a96b-4ce9-9e9f-95e828d0170c.png)
里面返回了一个Editor.bin文件的链接,此链接是http或者https协议
https://{ip}/cache/files/8aaa804587d269390187e99bca880062_1/Editor.bin/Editor.bin?md5=Lg2SqLC85pOFFzwq-sxfXw&expires=1685846109&filename=Editor.bin
这时是正常的

### Actual Behavior

但是现在返回的是Editor.bin的链接是websocket协议
![image](https://user-images.githubusercontent.com/20450161/236611763-bb20d309-5497-400b-a56f-9cec4b7028f1.png)
请求这个url时，会报跨域CORS
![image](https://user-images.githubusercontent.com/20450161/236611935-887e85f0-1163-43c2-bc8c-54187031545f.png)

**Comment by konovalovsergey** [comment]
It looks like you are using `x-forwarded-proto` header in proxy. check what value you are passing.
In newer versions only https and http is allowed. so this situation is impossible.
You can also set the desired host through `storage.externalHost` in server config file.

**Comment by softboy99** [comment]
Hi,
@konovalovsergey , We use minio public bucket as the storage and encounter the same problem. After upgrading from 8.3.3 to 9.2.1, i get the fllowing error:

index.html?_dc=0&lang=zh&customer=ONLYOFFICE&type=desktop&frameEditorId=editor-1767588663950-522&is…:1 Access to XMLHttpRequest at 'http://192.168.1.166:9001/storage-cache/files/data/sys_method_draft2008025857343209474_1199329131065100/Editor.bin/Editor.bin?md5=FwqvKskV41iNCyZ0R5czBA&expires=1770183187&shardkey=sys_method_draft2008025857343209474_1199329131065100&filename=Editor.bin' from origin 'http://localhost:3380' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 




However, before upgrading, it's ok.  What's the storage.externalHost means? taget to the mino server?my storage config as the following:



  "storage": {
    "name": "storage-s3",
    "region": "GUANGZHOU",
    "endpoint": "https://oss.gbjc.cc:9000",
    "bucketName": "gbt",
    "storageFolderName": "files",
    "cacheFolderName": "data",
    "commandOptions": {
      "s3": {
        "putObject": {},
        "getObject": {},
        "copyObject": {
          "MetadataDirective": "COPY"
        },
        "listObjects": {
          "MaxKeys": 1000
        },
        "deleteObject": {}
      },
      "az": {
        "uploadData": {},
        "uploadStream": {},
        "download": {},
        "syncCopyFromURL": {},
        "listBlobsFlat": {
          "maxPageSize": 1000
        },
        "deleteBlob": {}
      }
    },
    "urlExpires": 604800,
    "accessKeyId": "CEgpzwiGCDC2OlJaVeEX",
    "secretAccessKey": "xGyUJmpmuSMuEliIYfnPutO97XrXWMa2VcFwAUq7",
    "sslEnabled": false,
    "s3ForcePathStyle": true,
    "externalHost": "",
    "useDirectStorageUrls": false
  },
