### ISSUE TITLE
doc to docx default values

### ISSUE THREAD

**Issue by sunnyawake5** [ONLYOFFICE/DocumentServer#2236]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

latest

### Expected Behavior
only write really-needed subelements for pPr

### Actual Behavior

doc to docx : the result docx w:pPr contains many subelements whose value are default values.

**Comment by TatianaKirillova** [comment]
Hey, @sunnyawake5!
Thanks for your request!
Please clarify the steps. Do you immediately open the doc-document in our editor and save it as docx? Or
 you edit the document and save it later?

**Comment by sunnyawake5** [comment]
i use x2t command.

**Comment by l8556** [comment]
Hi, @sunnyawake5!
Can I ask for a document to confirm this?  Unless, of course, it contains confidential information.
And please clarify the steps to reproduce the problem.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
