### ISSUE TITLE
doc to docx: pPr

### ISSUE THREAD

**Issue by sunnyawake5** [ONLYOFFICE/DocumentServer#2237]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

latest

### Expected Behavior

<w:tabs>
      <w:tab w:val="clear" w:pos="4510"/>
      <w:tab w:val="clear" w:pos="9020"/>
  </w:tabs>
or:
  <w:tabs>
      <w:tab w:leader="none" w:val="center" w:pos="4510"/>
      <w:tab w:leader="none" w:val="right" w:pos="9020"/>
  </w:tabs>
but not both

### Actual Behavior

<w:tabs>
    <w:tab w:val="clear" w:pos="4510"/>
    <w:tab w:val="clear" w:pos="9020"/>
</w:tabs>
<w:tabs>
    <w:tab w:leader="none" w:val="center" w:pos="4510"/>
    <w:tab w:leader="none" w:val="right" w:pos="9020"/>
</w:tabs>

**Comment by l8556** [comment]
Hey, @sunnyawake5!
Thanks for your request!
Can I ask for a document to confirm this?
And please clarify the steps to reproduce the problem.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
