### ISSUE TITLE
How to cache fonts in browser when editing documents using an iframe

### ISSUE THREAD

**Issue by gowy222** [ONLYOFFICE/DocumentServer#2238]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello,

I'm using OnlyOffice ([docker](https://github.com/ONLYOFFICE/Docker-DocumentServer)) to embed a document editor in my web application (@onlyoffice/document-editor-vue). The editor is loaded within an iframe each time users open a document. I noticed that when the editor is loaded, it downloads font files from URLs like `https://xxxx/7.3.3-49/fonts/011...036`. The issue is that these files are quite large and can impact the editor's loading time(like 5-10 mins in 70MB data).

I'd like to enable browser caching for these fonts to improve performance. This way, users won't have to re-download the font files each time they open the editor in the same browsing session, even when using iframes.

I've tried various solutions, including modifying the Nginx configuration and using JavaScript to load and cache the font files. However, none of these solutions seem to work as expected.

any help with provide guidance on how to enable browser caching for these font files when using an iframe?

**Comment by Jimmy0769** [comment]
> ### This issue is unique.
> * [x]  I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.
> 
> ### Your idea.
> Hello,
> 
> I'm using OnlyOffice ([docker](https://github.com/ONLYOFFICE/Docker-DocumentServer)) to embed a document editor in my web application (@onlyoffice/document-editor-vue). The editor is loaded within an iframe each time users open a document. I noticed that when the editor is loaded, it downloads font files from URLs like `https://xxxx/7.3.3-49/fonts/011...036`. The issue is that these files are quite large and can impact the editor's loading time(like 5-10 mins in 70MB data).
> 
> I'd like to enable browser caching for these fonts to improve performance. This way, users won't have to re-download the font files each time they open the editor in the same browsing session, even when using iframes.
> 
> I've tried various solutions, including modifying the Nginx configuration and using JavaScript to load and cache the font files. However, none of these solutions seem to work as expected.
> 
> any help with provide guidance on how to enable browser caching for these font files when using an iframe?

Hello @gowy222 . Have you found a solution? Please tell me how you cache these font files. Thanks
