### ISSUE TITLE
View moving while typing in collaboration mode not fixed in NextCloud

### ISSUE THREAD

**Issue by GabrielModinBarzen** [ONLYOFFICE/DocumentServer#2242]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.3

### Expected Behavior

Edit text normally while colaborating

### Actual Behavior

View of other collaborator slowly shifts as each character is entered.

### Reproduction Steps

1. Start collaboration in NextCloud.
2. Write in multi-page document.
3. Screen slowly shifts. 

### Additional information

I have a NextCloud 25.0.1 instance running alongside the Document Server on my TrueNas box. 

[issue.webm](https://github.com/ONLYOFFICE/DocumentServer/assets/71310727/13acd2a3-f0df-4b43-934d-fd8a149f7659)

**Comment by ElenaMaaya** [comment]
@GabrielModinBarzen! The problem is not repeated on version 7.4.1. Please update DocumentServer and DesktopEditors to version 7.4.1. Thank you for using our products. Good day!

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
