### ISSUE TITLE
Track Changes balloon showing incorrect information for adjacent deletes

### ISSUE THREAD

**Issue by ryanamannion** [ONLYOFFICE/DocumentServer#2245]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.3.50

### Expected Behavior

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/46059412/b669aa47-17b2-4bfe-95e0-d45a3c532f63)

In a document with the above XML in the document part, I would expect to see a balloon for the first edit similar to:
```
Ryan
Deleted: Some text
```
And a second balloon when the cursor is over the second edit
```
Author2
Deleted: Other text.
```

I am unsure how this worked in previous versions.

### Actual Behavior

Instead of having two balloons, there is a single balloon. This single balloon only shows the author of the second delete, and the text following "Deleted:" shows both the text from the first delete, and the text from the second.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/46059412/89ac5340-8269-42a0-8a1c-ff9db37b58be)

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/46059412/69bcda9a-2a38-4853-9534-82f1c8c0f6bf)

This appears to be happening with deletes that are not separated by contentful elements. By that I mean it happens when there is an empty `w:r` tag between them, but not where there is a `w:r` tag that has text in it (including whitespace).

### Reproduction Steps

Open this document in OnlyOffice, which has the above-screenshotted `document.xml` part: [doc.minimal.docx](https://github.com/ONLYOFFICE/DocumentServer/files/11511043/doc.minimal.docx)

OR
1. Open a document and **without** track changes, add some text.
2. Turn on track changes, delete that text.
3. Turn off track changes, add more text immediately following the first delete.
4. Have a second user (either a different person or change your user name in your editor) turn on track changes and delete the text immediately following the first delete.

With the document open, make sure "Display Mode" is set to "Markup and Balloons". 

### Additional information

rsid values created in Word do not seem to help with this issue, and inserting things like commentRangeStart or commentRangeEnd, commentReference, etc. between the two deletes does not seem to help.

**Comment by TatianaKirillova** [comment]
Hello, @ryanamannion 
Thanks for your request!
I can confirm that the problem exists. I created ticket 62748 in our internal  tracker with your  issue.

**Comment by TatianaKirillova** [comment]
Hey, @ryanamannion
The problem has been fixed in version v.7.4.0

**Comment by DenisDeeSign** [comment]
DocumentServer v7.4.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
