### ISSUE TITLE
Long loading filters in Excel

### ISSUE THREAD

**Issue by dwpoint** [ONLYOFFICE/DocumentServer#2248]
Hi all! Friends, we work in WorkSpace. We are 12 people. Everything is super, except for the sheet, on which there are 163,000 lines.
When you open it, the web page starts to work very slowly. And hangs for 3-4 seconds when you try to put a filter in the header. Tell me, is it possible to somehow optimize the work of sheets with big data? 163,000 lines.

**Comment by dwpoint** [comment]
@DenisDeeSign thx

**Comment by rsnegirev** [comment]
Hi @dwpoint 

Which version of the DocumentServer do you use? And maybe can you provide a file example?

**Comment by Rita-Bubnova** [comment]
@dwpoint Sorry for the long wait.
DocumentServer v7.4.1 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
