### ISSUE TITLE
hard to operate on mobile editor

### ISSUE THREAD

**Issue by BurizaDo** [ONLYOFFICE/DocumentServer#225]
As I use the 'mobile' type for document editor, I find it's difficult to scroll the doc on both Android and iOS.

For Android, if the width and height is set to 100% in config and the document has multiple pages, it's hard to scroll down. But once the virtual keyboard is called, scroll will be easy. And if the width and height is set less than 100%, for instance, 80%, scroll will be easy too.  My Android version is 7.1.

For iOS, scroll is normal at the first time. But once the virtual keyboard is called, the document will not be able to scroll horizontally, only vertically. 

The behavior is normal on OnlyOffice's document app. Does anyone have the same issue?

**Comment by BurizaDo** [comment]
I see. There's something wrong in the JAVA example, as I switch to the node sample, it's OK now

**Comment by ibnpetr** [comment]
@BurizaDo Thanks for the info. We will look into it.

**Comment by ShockwaveNN** [comment]
I'm close this issue since problem should be resolved by now. If not - please create new issue
