### ISSUE TITLE
office file encryption 

### ISSUE THREAD

**Issue by XiaoYueTan** [ONLYOFFICE/DocumentServer#2252]
### This issue is unique.

- [ ] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

How to use the encryption and decryption of onlyoffice in java? Is there any Java example

**Comment by askonev** [comment]
Hi @XiaoYueTan. Example was developed as an example of document server integration. You can always fork the [project](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/java) and refine it.

**Comment by XiaoYueTan** [comment]
hi @askonev I Can't find The Example Of Java Encrypted Only Office, So I Asked The Community For Help. I Want To Know To Call Only Office To Encrypt Office Files And Use Java Code To Implement It.

**Comment by XiaoYueTan** [comment]
hi @ @askonev  I can't find an example of using Java encryption with OnlyOffice, so I am seeking help from the community. I want to know how to call OnlyOffice to encrypt office files and implement it using Java code.

**Comment by askonev** [comment]
It is also possible to connect a jwt

It is necessary to activate jwt on the server document side

Configure the java project to work with jwt [here](https://github.com/ONLYOFFICE/document-server-integration/blob/2a6e5e44bf33b3576de26d34ac2b5b3a54de7782/web/documentserver-example/java/src/main/resources/settings.properties#L21)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
