### ISSUE TITLE
Some understandings of Onlyoffice

### ISSUE THREAD

**Issue by fernfei** [ONLYOFFICE/DocumentServer#2253]
1. I discovered that the document builder api is essentially sdkjs
2. I debugged document-server and found that all text became charcode (Is that right? Not so sure)

**Comment by KirillovIlya** [comment]
Hello.
1. Almost true
2. What do you mean?

**Comment by fernfei** [comment]
> 

I mean, sdkjs seems to be converting text to charcode when handling text (guess better compatibility, handling special characters, performance optimization). Because when I debug it's just numbers and no text 
 
<img width="1030" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/42832987/56489dca-d4fc-4b22-992d-9116ea0a2b55">

**Comment by KirillovIlya** [comment]
Yes, this is also true

**Comment by fernfei** [comment]
> Yes, this is also true

Thank you for your replay

**Comment by KirillovIlya** [comment]
I want to add about the text:

The text is a sequence of char codes(code points in a new way), so we are not actually converting the text. We use the values ​​that are written directly in the file.
