### ISSUE TITLE
Great project! How to insert characters to the Word document cursor position it

### ISSUE THREAD

**Issue by Dingzhaocheng** [ONLYOFFICE/DocumentServer#2254]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I can use command?or Please give me some ways

**Comment by stepjacky** [comment]
perhaps  the  document  builder  api  can  help  you doing  something

**Comment by Dingzhaocheng** [comment]
Sorry, I'm confused about how this builder can be integrated into the web page, can it provide an mvp implementation

**Comment by stepjacky** [comment]
you  can  use it within  a custom plugin .  please  read  the  document  of  learning      to  write  a  plugin.
