### ISSUE TITLE
Autofill option increment 

### ISSUE THREAD

**Issue by Clitis** [ONLYOFFICE/DocumentServer#2255]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi, I have a suggestion on the autofill option in Spreadsheet Editor.

The content of one of my cells starts with a number and ends with a number. When I use the auto-fill function, the incrementation automatically happens on the number at the end of the cell. I would like to have the option to choose whether I want an incrementation at the beginning or at the end when the content of my cell starts and ends with a number.

![autofill](https://github.com/ONLYOFFICE/DocumentServer/assets/134702141/e2b3147e-4823-4bd3-be60-4fb64a5dceb5)

Thanks in advance.

Clitis

**Comment by Clitis** [comment]
Hi,
Thank you for you answer

Clitis

**Comment by DenisDeeSign** [comment]
I'm close this issue since the problem is solved. Feel free to create a new one if you got further questions.
