### ISSUE TITLE
Recover OnlyOffice file

### ISSUE THREAD

**Issue by Likestoo** [ONLYOFFICE/DocumentServer#2256]
I have been working all week on a document in OnlyOffice. I have backups from Tuesday and Wednesday but not more recently. 

I saved it this morning as I turned off my laptop. When I returned it showed in the folder as 0 bytes and when I opened that it is a blank page rather than the 24 pages I had been working on. When I started up again I was warned my memory space was only 48MB and I was asked if I wanted to empty the trash. I presume that was what caused the problem (even though the file is nothing like that big). 

I hope there are the running backups that are saved in case of the program crashing that I might be able to return to? I have found a folder Onlyoffice which contains just one file Desktopeditors. In that are folders Data, Recover and Plugins. I presume I am getting close? When I dig further I find files with no attribution so am wary to try anything further. 

Where do I go from here?

**Comment by Likestoo** [comment]
Update. I went into Recover and found eight folders with alpahnumeric titles. I opened each in turn and most were called DocumentX and were temporary files I had not gone back to.

One had the title of the lost file but when I copied and pasted it to my home folder and then opened it, it was also blank :(

It was dated at the time I opened my computer again so does not appear to be from the previous session.

**Comment by Likestoo** [comment]
This is a screenshot of the contents of Cache ...
/home/mihail/Screenshot from 2023-05-28 16-48-51.png

**Comment by HectorB-2020** [comment]
@Likestoo, you might want to look into other reports related to recovering documents:

- https://github.com/ONLYOFFICE/DesktopEditors/issues/550
- https://github.com/ONLYOFFICE/DesktopEditors/issues/1144
- https://github.com/ONLYOFFICE/DocumentServer/issues/2136

**Comment by Rita-Bubnova** [comment]
Hello, sorry for the long wait.
@Likestoo, Are you using DocumentServer or DesktopEditors? What version?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
