### ISSUE TITLE
There is a problem with conversion service

### ISSUE THREAD

**Issue by eyasliu** [ONLYOFFICE/DocumentServer#226]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I want to convert office document files to some other format. the target file is wrong

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
please see my attachment.
[screenshot.zip](https://github.com/ONLYOFFICE/DocumentServer/files/1568281/screenshot.zip)

1. the convert target file url access 403
2. convert to pdf/odt/rtf can't open, but the file size look like normal
3. convert to image format, if set `thumbnail.first` is `true`, will be work fine, if set `false`, will be wrong, but the file size look like normal

**What is the expected behavior?**
Should open the file normally

**Did this work in previous versions of DocumentServer?**
5.0.4 i try, no work

**DocumentServer version:**
docker run -tid -p 8080:80 onlyoffice/documentserver:5.0.6.14

**Operating System:**
deepin 15.5, is a linux release version

**Browser version:**
chrome 58.0.3029.110 (64-bit)

my api `http://192.168.1.5:8121/api/v1/office/convert` code is just like:
```js
const { body } = await fetch('http://192.168.1.5:8080/ConvertService.ashx', {method: "POST", ......})
const { FileResult } = await xml2js(body.toString())
response.json({
  success: true,
  data: FileResult
})
```

**Comment by eyasliu** [comment]
@ShockwaveNN thanks your reply
the screenshot test file url is `http://www.micropoint.com.cn/company/file/Install-Wizard.doc` (you lost www), I try to convert [callback url file](https://api.onlyoffice.com/editors/callback#url) (save file first, and then call convertsion api use saved file url), it is wrong too

**Comment by ShockwaveNN** [comment]
1. 403 error
You should unescape  HTML in result field
If you get link like: `http://localhost:8080/cache/files/conv_test4_pdf/output.pdf/output.pdf?md5=k14sPdZAZAfz9fLrKK1pkQ==&amp;expires=1516269930&amp;disposition=attachment&amp;ooname=output.pdf`
You should unesapce and your link will be `http://localhost:8080/cache/files/conv_test4_pdf/output.pdf/output.pdf?md5=k14sPdZAZAfz9fLrKK1pkQ==&expires=1516269930&disposition=attachment&ooname=output.pdf` and should downloaded fine
2. Seems fine to me, but why you set `filetype` as `pdf` for `Install-Wizard.doc`
3. According to [help](https://api.onlyoffice.com/editors/conversionapi)
You should get zip if you set `thumnail.first` to false. So you need specify `"outputtype": "zip"` in request.

**Comment by eyasliu** [comment]
very thanks,

1. sorry, I ignore that is an esapce url, it fine to me after unesapce
2. wrote  a wrong filetype is my misstake, the convert failed reason is I set thumbnail object in my nodejs code to define default options, like `const params = Object.assign({}, defaultOptions, request.body)`, it is fine after I remove the defaultOptions.thumbnail
3. sorry, I no attention is a zip file, I rename `output.jpg` to `output.zip`, and then extract the zip, I get all the images successfully

Sorry, all is my misstake, I should look at the document seriously
