### ISSUE TITLE
It always opens a same file also not not loading file from URL

### ISSUE THREAD

**Issue by mohitbumb2310** [ONLYOFFICE/DocumentServer#2263]
What I'm trying to do here is showing multiple openoffice instance on same page using Angular as FE but it always shows same content for all instance also I try giving different name but not works when I give different key then there's an error coming "download failed"

I'm also giving document.url but its not changing anything and not loading that particular file 

Not sure but that issue might be coming because of this warning "The document could not saved. Please check connection setting or contact system admistration"

I'm using Ubuntu in my localhost for document server now and using ip address instead of localhost but not sure the exact issue and solution that how can I use multiple instance on same page

**Comment by trofim24** [comment]
We have different examples. [Angular is among them.](https://api.onlyoffice.com/editors/angular)
Please try it. And If you have any other questions, create new issue.
If you have any questions about this problem reopen issue
