### ISSUE TITLE
While converting pdf to zip/images, does the Conversion API support converting the specified page number? 

### ISSUE THREAD

**Issue by Forest-Wei** [ONLYOFFICE/DocumentServer#2265]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
While converting pdf to zip/images, i didn't find the parameters about  the specified page number from Conversion API document .

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
While converting pdf to zip/images, what parameters can be used to specify the conversion page number ?

**Did this work in previous versions of DocumentServer?**
I have no idea.

**DocumentServer version:**
v7.3

**Operating System:**
centos 7.9

**Browser version:**

have any suggestion ?  thanks a lot.

**Comment by Forest-Wei** [comment]
@l8556 thanks, in other words, the current version of this api only supports conversion of the first page or all of them, but does not support the specified conversion of a collection of pictures with a certain range of page numbers.  For example, a pdf file has 10 pages. I cannot directly convert the second page.  I understand, right?

**Comment by l8556** [comment]
Right,
Currently, when converting documents to images, 
you can create a thumbnail for just the first page or for all pages of the document.

**Comment by Forest-Wei** [comment]
Best wish
