### ISSUE TITLE
Opening document fails after upgrade to 12.5.2 - "Because, It is private IP address"

### ISSUE THREAD

**Issue by thomass4t** [ONLYOFFICE/DocumentServer#2268]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4

### Expected Behavior

I should be able to edit xlsx and doc files after the update (as it worked before)

### Actual Behavior

When I try to open a .docx or .xslx file, I receive an error message "Download failed".

The log of the community-server shows an error from node-js

```
nodeJS - error downloadFile:url=http://xxx:8080/Products/Files/HttpHandlers/filehandler.ashx?action=stream&fileid=28&stream_auth=42443xxxXJ56L2TBSE&X-REWRITER-URL=https%3a%2f%2fxxx%3a443;attempt=3;code:undefined;connect:undefined Error: DNS lookup 192.168.1.41(family:4, host:onlyoffice) is not allowed. Because, It is private IP address.
    at validateIPAddress (/snapshot/server/build/server/Common/node_modules/request-filtering-agent/lib/request-filtering-agent.js:73:20)
    at Socket.<anonymous> (/snapshot/server/build/server/Common/node_modules/request-filtering-agent/lib/request-filtering-agent.js:90:21)
...
```
Both docker containers (documentServer, communityServer) run on the same machine, thus the download is from the private network.
It seems to be a security feature:
How can I allow private addresses?
Are there any env-variables I can set?

Thanks in advance!
Thomas

**Comment by thomass4t** [comment]
A temporary fix was, entering the docker container and edit 
/etc/onlyoffice/documentserver/local.json

```
{
  "services": {
    "CoAuthoring": {
      "request-filtering-agent": {
        "allowPrivateIPAddress": true,
        "allowMetaIPAddress": true
      },
```
The parameter allowPrivateIPAddress was probably the solution.

Any hint, how I can add this parameter to docker compose?

**Comment by tom666-debug** [comment]
Same here after update to onlyoffice-ds version 7.4.0:

```
[2023-06-14T06:10:49.005] [ERROR] [localhost] [4230106422] [oc90q2btdfk5_owncloud] nodeJS - error downloadFile:url=https://owncloud.MYDOMAIN.de/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6MTIsInVzZXJJZCI6Im93bmNsb3VkIn0.AN9lbCmzIwYJNcUurUacEcSZt0Eb6Pj0tZ27DheMtPk;attempt=1;code:undefined;connect:undefined Error: DNS lookup 192.168.0.3(family:4, host:owncloud.MYDOMAIN.de) is not allowed. Because, It is private IP address.
    at validateIPAddress (/snapshot/server/build/server/Common/node_modules/request-filtering-agent/lib/request-filtering-agent.js:73:20)
    at TLSSocket.<anonymous> (/snapshot/server/build/server/Common/node_modules/request-filtering-agent/lib/request-filtering-agent.js:90:21)
    at TLSSocket.emit (events.js:400:28)
    at emitLookup (net.js:1055:12)
    at /snapshot/server/build/server/Common/node_modules/dnscache/lib/index.js:151:58
    at Array.forEach (<anonymous>)
    at /snapshot/server/build/server/Common/node_modules/dnscache/lib/index.js:151:34
    at /snapshot/server/build/server/Common/node_modules/dnscache/lib/cache.js:72:25
    at RawTask.call (/snapshot/server/build/server/Common/node_modules/asap/asap.js:40:19)
    at flush (/snapshot/server/build/server/Common/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by thomass4t** [comment]
Another workaround is to copy local.json or default.json to your local machine, set or adjust allowPrivateIPAddress=true and mount it into the docker container back again. Not nice but works till the next update hopefully.

**Comment by Afgan0r** [comment]
Same here after update:
```
[2023-06-16T15:56:44.427] [ERROR] [localhost] [55F0F3450F] [uid-1683797008809] nodeJS - error downloadFile:url=https://localhost:7001/api/docserver/content/fb7b905f-b527-4169-831d-44f9a87f5ad1;attempt=3;code:undefined;connect:undefined Error: DNS lookup 127.0.0.1(family:4, host:localhost) is not allowed. Because, It is private IP address.
    at validateIPAddress (/snapshot/server/build/server/Common/node_modules/request-filtering-agent/lib/request-filtering-agent.js:73:20)
    at TLSSocket.<anonymous> (/snapshot/server/build/server/Common/node_modules/request-filtering-agent/lib/request-filtering-agent.js:90:21)
    at TLSSocket.emit (events.js:400:28)
    at emitLookup (net.js:1055:12)
    at /snapshot/server/build/server/Common/node_modules/dnscache/lib/index.js:125:28
    at /snapshot/server/build/server/Common/node_modules/dnscache/lib/cache.js:116:13
    at RawTask.call (/snapshot/server/build/server/Common/node_modules/asap/asap.js:40:19)
    at flush (/snapshot/server/build/server/Common/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
Get this error during development with local backend

**Comment by VSDodonov** [comment]
Same here after update to onlyoffice-ds version 7.4.0:
`onlyoffice-document-server  | 2023-06-21T12:22:03.456217763Z [2023-06-21T12:22:03.454] [ERROR] [localhost] [conv_check_1090857475_docx] [userId] nodeJS - error downloadFile:url=http://app-server/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.JHBK5uBhJF4iM2TU2WQEJeD1bvCa4BsDwGLepNr4Gjk;attempt=2;code:undefined;connect:undefined Error: DNS lookup 172.20.0.6(family:4, host:app-server) is not allowed. Because, It is private IP address.
`

**Comment by igwyd** [comment]
Hello @thomass4t, you are right, this is a security feature. Do you disabled the jwt token check and use the integration in the local network?

**Comment by thomass4t** [comment]
Hello @igwyd 
yes.. you are right.
As the application is running in our internal network, the JWT token is disabled:
```
    environment:
      - JWT_ENABLED=false
      - JWT_SECRET=jwt_secret
      - JWT_HEADER=AuthorizationJwt
```
You are also right about the network, it is running on the host network.

Would it work with just JWT enabled?

**Comment by igwyd** [comment]
This is to protect against SSRF attacks. We highly recommend enabling JWT in your integrations. When JWT is enabled links in the server are signed by it and you won't get any "request-filtering-agent" errors.

**Comment by thomass4t** [comment]
Hello @igwyd 
I activated the JWT token and removed the binding of the modified default.json
Everything works now, great 🙂
Thank you very much for the helpful information!

So it means, that I can set JWT_ENABLED=false but then I will break my system.
It seems that after the last update, the JWT got mandatory.

It would be great if you could add some hints in the documentation or make the JWT mandatory.
Setting it to false doesn't make much sense now anymore.

Thanks for your support! Thomas

**Comment by igwyd** [comment]
Yes, we enabled[ JWT by default](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#720) since 7.2. in new installations and show it on /welcome page.

**Comment by DenisDeeSign** [comment]
@thomass4t 
Seems your problem is solved. Can we close this issue?

**Comment by thomass4t** [comment]
@DenisDeeSign 
The problem itself is solved, yes.
A hint in the documentation (for the parameter JWT_ENABLED) would be helpful to prevent the pitfal.

**Comment by viscous-coder** [comment]
if id enable my jwt then i get the token error, "The document security token is not correctly formed. Please contact your Document Server administrator"
import React, { useState, useEffect } from “react”;
import { DocumentEditor } from “[@onlyoffice](https://forum.onlyoffice.com/u/onlyoffice)/document-editor-react”;

const OnlyOffc = (props) => {
const [docUrl, setDocUrl] = useState(“”);
let token = sessionStorage.getItem(“jwt_token”);
let username = localStorage.getItem(“username”);
let deptRole = sessionStorage.getItem(“role”);
let sessionId = sessionStorage.getItem(“sessionId”);
console.log(props.url, token, “this”);
let correctUrl = props?.url?.replaceAll(“xxxyyyzzz”, “/”);

const onDocumentReady = () => {
console.log(“Document is loaded”);
setLoading(false);
};

const onLoadComponentError = function (errorCode, errorDescription) {
switch (errorCode) {
case -1: // Unknown error loading component
console.log(errorDescription);
break;

case -2: // Error load DocsAPI from http://documentserver/
console.log(errorDescription);
break;

case -3: // DocsAPI is not defined
console.log(errorDescription);
break;
}
};

useEffect(() => {
fetch(For_Getting_the_file_url, { //to get the file url
headers: {
“Content-Type”: “application/json”,
Authorization: "Bearer " + token,
username: username,
deptRole: deptRole,
sessionId: sessionId,
},
})
.then(async (res) => {
console.log(res, “res”);
let data = await res.blob();
// console.log(data);

let file = new File([data], "test.docx");
console.log("file", file.name);

setDocUrl(URL.createObjectURL(file)); // set object URL of file as docUrl
})
.catch((error) => {
console.log(error);
});
}, [correctUrl, token, username, deptRole, sessionId]);

console.log(“docurl”, docUrl);

return (

{docUrl && (
<DocumentEditor
id=“docxEditor”
documentServerUrl=“DOCKER_URL” //getting from docker
config={{
document: {
key: “SECRET_KEY”,
fileType: “docx”,
title: “farmer.docx”,
url: docUrl,
},
documentType: “word”,
type: “desktop”,
height: “800px”,
width: “100%”,
}}
events_onDocumentReady={onDocumentReady}
onLoadComponentError={onLoadComponentError}
/>
)}

);
};
export default OnlyOffc;

[//local.json](https://local.json/)
{
“services”: {
“CoAuthoring”: {
“sql”: {
…data
},
“token”: {
“enable”: {
“request”: {
“inbox”: true,
“outbox”: true,
},
“browser”: true
},
“inbox”: {
“header”: “Authorization”,
“inBody”: false
},
“outbox”: {
“header”: “Authorization”,
“inBody”: false
}
},
“secret”: {
“inbox”: {
“string”: “SECRET_KEY”
},
“outbox”: {
“string”: “SECRET_KEY”
},
“session”: {
“string”: “SECRET_KEY”
}
}
}
},
“rabbitmq”: {
“url”: “Some_URL”
},
“wopi”: {
“enable”: false,
“privateKey”: “SOMEVALUES”,
“privateKeyOld”: “SOMEVALUES”,
“publicKey”: “SOMEVALUES”,
“publicKeyOld”: “SOMEVALUES”,
“modulus”: “SOMEVALUES”,
“modulusOld”: “SOMEVALUES”,
“exponent”: 12333,
“exponentOld”: 11111
},
“queue”: {
“type”: “abc”
},
“storage”: {
“fs”: {
“secretString”: “MY_SECRET_KEY”
}
}
}

[//compose.yml](https://compose.yml/)

environment:

JWT_ENABLED=true
JWT_SECRET=SECRET_KEY
JWT_HEADER=Authorization
how to resolve that error

**Comment by igwyd** [comment]
Hello @viscous-coder, your error is not related to this issue, create a new one. Describe your issue in more detail and provide the reproduction steps.

**Comment by viscous-coder** [comment]
hello @igwyd , thanks for reply,
My issue is that when i open my docx file in the onlyoffice it show me error "The document security token is not correctly formed. Please contact your Document Server administrator" I go several docs and blogs when i do things according to them like JWT_ENABLE = false, then i get the error "Download Failed"
i also shared my docker file also.

**Comment by igwyd** [comment]
Your issue is different from this one. Please create a new issue and we will try to help.

**Comment by AliSK81** [comment]
For those encountering security or download errors in a Docker deployment:

1. Set `JWT_ENABLED=false` in the `onlyoffice-documentserver` environment.
2. Enable `allowPrivateIPAddress` in `/etc/onlyoffice/documentserver/default.json` inside the container. For more details, see this [[guide](https://community.onlyoffice.com/t/how-to-allow-private-ip-to-access-onlyoffice-documentserver/5755/2)].

**Comment by AliSK81** [comment]
For those encountering security or download errors in a Docker deployment:

1. Set `JWT_ENABLED=false` in the `onlyoffice-documentserver` environment.
2. Enable `allowPrivateIPAddress` in `/etc/onlyoffice/documentserver/default.json` inside the container. For more details, see this [guide](https://community.onlyoffice.com/t/how-to-allow-private-ip-to-access-onlyoffice-documentserver/5755/2).
