### ISSUE TITLE
The chinese font of simsun.ttc ，italics is unavailable ！

### ISSUE THREAD

**Issue by kevin139168** [ONLYOFFICE/DocumentServer#2271]
version 7.4
I get the chinese font of 【**simsun.ttc**】to the 【/usr/share/fonts/】，and I fond that the operation of **italics** is unavailable  for the  【**simsun.ttc**】！

I test version 7.3.3 ，actually ，this  problem have bean found！

**Comment by kevin139168** [comment]
thinks !

**Comment by igwyd** [comment]
Hello @kevin139168 thank you for report.
I can confirm - this is bug, issue 63066 in our internal issue tracker.

**Comment by igwyd** [comment]
This has been fixed at: [ONLYOFFICE/sdkjs@12e7079](https://github.com/ONLYOFFICE/sdkjs/commit/e1c438e9e208d7e37436595eeadd927a6cbb54b8) and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
