### ISSUE TITLE
Spreadsheet Ctrl C + Ctrl V copy from external Program to onlyoffice web editor 7.3.2

### ISSUE THREAD

**Issue by timcheuk** [ONLYOFFICE/DocumentServer#2274]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Docker

### Version information

7.3.2.8

### Expected Behavior

Success copy the image to webeditor Spreadsheet
Success copy the image to webeditor Document
Success copy the image to webeditor Powerpoint

### Actual Behavior

Success copy the image to webeditor Document
Success copy the image to webeditor Powerpoint
After Ctrl + C the image on local microsoft Word file. Ctrl + V to spreadsheet webeditor, no response. The image is not copied.

Use the Tab Insert > Image, select the image file. This method work properly. 
Draft and drop a image file to webeditor spreadsheet. This method work properly.
Same method for old version 6.3.1 onlyoffice Ctrl + V on spreadsheet work properly.

### Reproduction Steps

1. Opan a image with Window Paint program, select a image area 
3. Open a onlyoffice webeditor spreadsheet with Chrome browser Version 111.0.5563.65 (Official Build) (64-bit)
4. Select the image and Ctrl + C to copy it
5. Ctrl + V on onlyoffice webeditor
6. Image is not copied.

### Additional information
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/77771021/911e6fc0-ad39-4b9f-9ab2-d61bffdd736b)

**Comment by timcheuk** [comment]
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/77771021/911e6fc0-ad39-4b9f-9ab2-d61bffdd736b)

**Comment by rsnegirev** [comment]
Hi @timcheuk 

We recommend to updating your version of DocumentServer. Now the latest is 7.4.0 and there is no copy-paste problem, just like in 7.3.3.50.

**Comment by timcheuk** [comment]
OK. Noted. 
Then update to latest version is the only option.
