### ISSUE TITLE
After calling the 'force save' command, the callback request works normally, and I successfully saved the file to my own server. However, when I try to open the file again using the same key and URL, it prompts that the version has changed, and refreshing does not work either. What should I do now to make it work again?

### ISSUE THREAD

**Issue by RebelTinker** [ONLYOFFICE/DocumentServer#2275]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3

### Expected Behavior

work again

### Actual Behavior

After calling the 'force save' command, the callback request works normally, and I successfully saved the file to my own server. However, when I try to open the file again using the same key and URL, it prompts that the version has changed, and refreshing does not work either. 

### Reproduction Steps

After calling the 'force save' command, the callback request works normally, and I successfully saved the file to my own server. However, when I try to open the file again using the same key and URL, it prompts that the version has changed, and refreshing does not work either.

**Comment by trofim24** [comment]
Sorry for late responce, seems we missed this issue.
> Every time the document is edited and saved, the key must be generated **anew**.

Please, read our documentation about [key parameter](https://api.onlyoffice.com/editors/config/document#key)

If you have any questions, create new issue
