### ISSUE TITLE
Subscript, parenthesis and superscript shortcuts cause the affected symbols to shrink and turn black from another color in the formula format in Presentations

### ISSUE THREAD

**Issue by avachon100510** [ONLYOFFICE/DocumentServer#2279]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.4.0

### Expected Behavior

The font size and color should remain unchanged regardless whether subscript, parenthesis, superscripts and any other operation shortcut.

### Actual Behavior

Instead, when I do that, the font turns black and shrinks to default size

### Reproduction Steps

1. Say for example we want to input f_\psi_0(\Omega_\omega)(100). Go to Formula and do "add equation". Set the color to whatever color of your choosing
2. Type the equation. Press F, then once you do `Shift + -` then type \psi, the two characters shrink and turn black, regardless of color or font size.

**Comment by ElenaMaaya** [comment]
Hi, @avachon100510 !
This is a known Bug 61764 in our internal issue tracker, which relates to the DocumentServer.
Thank you for contacting us.

**Comment by avachon100510** [comment]
> Hi, @avachon100510 ! This is a known Bug 61764 in our internal issue tracker, which relates to the DocumentServer. Thank you for contacting us.

No problem!

**Comment by TatianaKirillova** [comment]
Hello @avachon100510 ! The problem was partially fixed in version 8.1. But the main issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/pull/4691/commits/2c27c4d9827351d82511e7bd07de8b94d4255a44) and will be included in the next release. Don't miss updates. Have a good day!

**Comment by avachon100510** [comment]
> Hello @avachon100510 ! The problem was partially fixed in version 8.1. But the main issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/pull/4691/commits/2c27c4d9827351d82511e7bd07de8b94d4255a44) and will be included in the next release. Don't miss updates. Have a good day!

Hey, thanks, I have certainly waited a long time for this!

**Comment by avachon100510** [comment]
With that being said, we can finally close this issue. If this reappears, it will be reopened in the future.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
