### ISSUE TITLE
ONLYOFFICE fails to parse a string representation of a number with a space in it.

### ISSUE THREAD

**Issue by rustysys-dev** [ONLYOFFICE/DocumentServer#2285]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.3.3

### Expected Behavior

given the following file...

```csv
st,c_id,s_id,date
1,"01","10 ",2022/07/01
```

I expect to see some correct representation of that data...

### Actual Behavior

instead I see

st | c_id | s_id | date
-- | -- | -- | --
1 | 1 |   | 2022/07/01

s_id should be parsed as a string as is, or as a number with white space removed, doesn't really matter to me, but not whatever is happening here :sweat_smile: .

### Reproduction Steps

create csv, and open it.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
