### ISSUE TITLE
Unexpected Content Control Box Appears in Footer Section After Uploading DOCX File in ONLYOFFICE

### ISSUE THREAD

**Issue by shahzebgit** [ONLYOFFICE/DocumentServer#2290]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.0.163

### Expected Behavior

Here is the original DOCX File :- [sedgq2.docx](https://github.com/ONLYOFFICE/DocumentServer/files/11957793/sedgq2.docx) , opened in MS Word.

Here in Footer Section of the file there is no Content box
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/51449693/712a4944-66ee-44cb-9234-50160199ac29)

### Actual Behavior
Here is the original DOCX File :- [sedgq2.docx](https://github.com/ONLYOFFICE/DocumentServer/files/11957793/sedgq2.docx)

After importing/uploading DOCX file into ONLYOFFICE, there is content control (plain text) box in footer section
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/51449693/65dfabaa-fee7-4c96-a31c-2a549355ce5f)

### Reproduction Steps

Example:
1. Upload MS Word File [sedgq2.docx](https://github.com/ONLYOFFICE/DocumentServer/files/11957793/sedgq2.docx)
2. Check footer section, it's showing with content box.
3. Done.

### Additional information
here is a [live file](https://personal.onlyoffice.com/products/files/doceditor?fileid=5677344&doc=UUhNcFNqK2dsL0d4VU8vNjhld3pJcVI3NUFIbkUxTkpsaURISUkrNDhrND0_NTY3NzM0NA) if needed 

FYI, you can take any LibreOffice, MW Word and Google Docs.
Importing any DOCX file with page numbers, the Object I found in `LogicDocument` it has shown as `CRunText` instead of `CRunPageNum`, is this a bug or new way of converting page numbers as `paraRun`

**Comment by maruacat** [comment]
Hello @shahzebgit  
Thank you for your feedback.
This is known issue 40322 in our internal system.  I have added information about your request.
Have a good day!

**Comment by maruacat** [comment]
Hello @shahzebgit
I have great news. We have completed your feature request https://github.com/ONLYOFFICE/sdkjs/commit/6bed6f7702020a0ac0f99dc90e0647858f223c0b and it will be available in a new version.
Have a good day!

**Comment by shahzebgit** [comment]
> feature request https://github.com/ONLYOFFICE/sdkjs/commit/6bed6f7702020a0ac0f99dc90e0647858f223c0b
Thank you for the update, will wait for the release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
