### ISSUE TITLE
How to contribute to this repository。

### ISSUE THREAD

**Issue by moonlitusun** [ONLYOFFICE/DocumentServer#2295]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I'm interested in this aspect, but I've read a lot of documentation and don't know how to develop, whether there is detailed documentation

**Comment by trofim24** [comment]
[Here](https://api.onlyoffice.com/editors/getdocs) is API of ONLYOFFICE Docs.
Instructions for building ONLYOFFICE Docs for a local server from source code are in [our helpcenter](https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx).
