### ISSUE TITLE
OO hangs on a document after a copy/paste

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2299]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.4.0

### Expected Behavior

It should be possible to copy a document into another document.

### Actual Behavior

It does not work with the attached document.

[bug-OO-copy-paste.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/11848948/bug-OO-copy-paste.docx)

### Reproduction Steps

Steps:
- open the attached document
- select all with CTRL-A and copy with CTRL-C
- open another document
- paste with CTRL-V
- => OO hangs on the new document

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/6f072b768c28eb9a2a9fe4c5b0398b51155b45ee) in future major release.

**Comment by cpot** [comment]
Confirmed and annoying. In my case a copy/paste of an image in Firefox to Onlyoffice 7.2.2

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
