### ISSUE TITLE
Highlight the protected range in your spreadsheet

### ISSUE THREAD

**Issue by 18311002500** [ONLYOFFICE/DocumentServer#2302]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I'm are unable to edit a certain cell, but me cannot see which areas me cannot edit. You can consider adding shading to the areas that you cannot edit to make it more intuitive. Thanks

**Comment by rsnegirev** [comment]
Hi @18311002500 

How do you see the implementation of this functionality? Maybe you have examples from other applications?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
