### ISSUE TITLE
xlsm 2 xlsx losing blocked cell

### ISSUE THREAD

**Issue by rardcode** [ONLYOFFICE/DocumentServer#2316]
When i convert xlsm to xlsx, locked cells results locked...
![Screenshot_20230707_164458](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/50568864/5f8c81b9-3749-4af3-9f49-0391e2558679)
but are actually writeable. 

If i unlock and relock same cell, locking doesn't work.
if i lock and relock another cell on the same sheet...doesn't work

if i lock a cell of a NEW sheet same file....WORK

***UPDATE***
the issue is only on sheets where are pivot tables

**Comment by rsnegirev** [comment]
Hi @rardcode 

Can you please attach a problem file?

**Comment by rardcode** [comment]
cell example:
- sheets MONDAY -> cell blocked -> sheet blocked
- i try to write cell C3
- cell writed!! :(

[WEEKLY_BASE_italiano.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/12321671/WEEKLY_BASE_italiano.xlsx)

**Comment by rsnegirev** [comment]
I confirm this is a bug. But this has been fixed in version 7.5, which will be released in the near future.

**Comment by rardcode** [comment]
Hi to all
I confirm that with 7.5.0.1 bug is fixed.
thanks to all
