### ISSUE TITLE
IP address not logged

### ISSUE THREAD

**Issue by mivek** [ONLYOFFICE/DocumentServer#2317]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.0.163

### Expected Behavior

After configuring the IP filter as show [here](https://helpcenter.onlyoffice.com/installation/docs-configure-ipfilter.aspx), if I try to access a document from a not allowed IP the log in `/var/log/onlyoffice/documentserver/converter/out.log`should contain the IP trying to connect.

The same behaviour is expected when the checkJwt fails. In `/var/log/onlyoffice/documentserver/docservice/out.log` the client IP should be present.

Without the IP address it is not possible to set up a banning strategy using fail2ban or crowdsec.

### Actual Behavior

The client ip is missing from the logs

In `/var/log/onlyoffice/documentserver/docservice/out.log`
```
[2023-08-06T08:26:33.518] [WARN] [localhost] [docId] [userId] nodeJS - checkJwt error: name = JsonWebTokenError message = invalid signature token
```

### Reproduction Steps

Configure the IP filter as documented https://helpcenter.onlyoffice.com/installation/docs-configure-ipfilter.aspx.
Try to open a document from an unallowed  IP.
Check the logs in /var/log/onlyoffice/documentserver/docservice/out.log

**Comment by igwyd** [comment]
Hello @mivek, ipfilter is a feature that controls access of the document server to the storage server, not the end clients.

**Comment by mivek** [comment]
thank you for your answer @igwyd
