### ISSUE TITLE
Convert PDF Chinese garbled code using Conversion API

### ISSUE THREAD

**Issue by winfordguo** [ONLYOFFICE/DocumentServer#2318]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

onlyoffice/documentserver:7.4

### Expected Behavior

When I add some Chinese fonts and display them normally, even if some fonts are lost, adjacent fonts should still be displayed.

### Actual Behavior

When I try to convert a PDF from a document using the "simhei. ttf" font, the text that should have been presented as bold characters appears as garbled text. If I don't add any Chinese fonts to the '/usr/shares/fonts' directory, Chinese can be displayed normally with the closest font substitute, but that's not what I want.

### Reproduction Steps

1. Add any Chinese font to the '/usr/shares/fonts' directory, such as' simhei. ttf'.
2. Run the documentserver-generate-allfonts.sh file.
3. POST https://documentserver/ConvertService.ashx
```json
{
	"filetype": "docx",
	"async": false,
	"outputtype": "pdf",
	"region": "zh-CN",
	"title": "test.docx",
	"url": "https://xxx/test.docx",
	"key": "m9MzYV7y7f_t"
}
```

### Expected Behavior
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/24788233/ea8fc04e-fd93-4f3c-a237-f29639d909cf)

### Actual Behavior
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/24788233/a83fe840-333e-42a7-8082-85c89e0ec3b2)

### The test doc and font
[test_convert_assets.zip](https://github.com/ONLYOFFICE/DocumentServer/files/12273389/test_convert_assets.zip)

**Comment by l8556** [comment]
Hello, @winfordguo

I was unable to reproduce your issue.
The `simhei.ttf` font you provided displays correctly after adding it to the document server.

To install the font you need to:
1. Install the font by copying it to `/usr/share/fonts/`
2. Open the `/usr/bin` folder
3. Run the `documentserver-generate-allfonts.sh` file.
4. Clear the browser cache and reopen the page.

After converting the file you provided to pdf via ConvertService, the font `simhei.ttf` is displayed correctly.

Tested on onlyoffice/documentserver:7.4
OS: Ubuntu 22.04

**Comment by winfordguo** [comment]
Hello, @l8556 

Please help me see where there is a problem, thank you very much. My entire operation steps are as follows:

1. `vim docker-compose.yml`
```yml
version: '3'

services:
  onlyoffice:
    image: onlyoffice/documentserver:7.4
    container_name: onlyoffice
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=xxx

```
2. `docker-compose up -d`
3. `docker cp simhei.ttf onlyoffice:/usr/share/fonts/`
4. `docker exec onlyoffice /usr/bin/documentserver-generate-allfonts.sh`
```shell
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
Generating js caches, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
```
5. POST https://documentserver/ConvertService.ashx
```json
{
	"filetype": "docx",
	"async": false,
	"outputtype": "pdf",
	"region": "zh-CN",
	"title": "test.docx",
	"url": "https://xxx/test.docx",
	"key": "m9MzYV7y7f_t"
}
```

Thank you very much.

**Comment by winfordguo** [comment]
Sorry, I found the reason because `simhei.ttf` does not have read permission.

**Comment by cv-msan** [comment]
May I ask if you would not report an error without permission when making such a request?

**Comment by winfordguo** [comment]
参考[官方文档](https://api.onlyoffice.com/editors/conversionapi#error-codes)的错误码`
-8 | Invalid token.`应该是你的服务端启用了JWT验证，参考[Request with token in body](https://api.onlyoffice.com/editors/signature/body#conversion)，如果是这样你的`body`里应该只有一个`token`，像这样：

```json
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjIjoiaW5mbyIsImtleSI6IktoaXJ6NnpUUGRmZDcifQ.r_6sThjFABsHMNHhkVdHDSz4jwkbXRQNYdvawkBGJgg"
}
```

**Comment by cv-msan** [comment]
还有就是我暂时先把onlyoffice的token校验在local.json里关了然后请求体{
"filetype": "docx",
"key": "Khirz6zTPdfd7",
"outputtype": "pdf",
"title": "Example Document Title.docx",
"url": "https://example.com/url-to-example-document.docx"
}用这种的确实返回了转化完成的url路径但是请求该路径的时候返回403，请问这个问题有没有遇到过
![0e888f3050190f569ce778afa93b721](https://github.com/ONLYOFFICE/DocumentServer/assets/76542419/48a06cfd-31d0-457a-ad2d-20c1ecffd008)

**Comment by zhangjf108** [comment]
把返回的链接中的amp;去掉就可以了
