### ISSUE TITLE
conversion of document from docx to png or pptx to png is not working

### ISSUE THREAD

**Issue by superdexter** [ONLYOFFICE/DocumentServer#232]
Hello Presently I have installed dcoument Server on my local system(Please find spec below). I am trying to use rest api from document server to convert files from one type to other.
Presently i tried to convert docx ,pptx files

 to png .But it does not seems to be working. below is the format of request sent to server.
http://localhost:1234/ConvertService.ashx 
{
    "async": false,
    "filetype": "xlsx",
    "key": "qweqwe12",
    "outputtype": "png",
    "title": "foo.docx",
    "url":" http://localhost:27000/foo.docx"

}

document server tries to convert docx file to png .But ends up with single small sized png file.
![output](https://user-images.githubusercontent.com/11054692/35285698-5f675596-005e-11e8-9456-6e77f89a5374.png)
I have uploaded the output in attachment .
Specification of the Environment
Document Server Version v5.0.99.417
Windows version :  Windows 7
There were no errors during installation.

**Comment by ShockwaveNN** [comment]
Yeah, the main reason we developed ability to convert docs to images - to have thumbnails,  so by default images have thumbnails size 100*100 px.
You can manually specify image size by `thumbnail` -> `height` and `width` parameter
like so:
```
{
	"async": false,
	"filetype": "xlsx",
	"outputtype": "png",
	"url": "https://s3.us-west-2.amazonaws.com/nct-data-share/xlsx/7.xlsx",
	"thumbnail": {
		"height": 800,
		"width": 800
	},
	"key": "{{$guid}}"
}
```
You can see addition info about thumbnails in [here](https://api.onlyoffice.com/editors/conversionapi) 

If it is not enought feel free to reopen this issue

**Comment by superdexter** [comment]
Thank you for quick reply.. @ShockwaveNN  Is it possible to convert the whole document to png. For eg a docx file consiting of 10 pages. to folder with 10 png files of each page

**Comment by ShockwaveNN** [comment]
@superdexter Yeah, `thumbnail` -> `first` is option for what. If it set to `false` - you get zip archive with several png-s.
Like this:
```
{
	"async": false,
	"filetype": "docx",
	"outputtype": "zip",
	"url": "https://s3.us-west-2.amazonaws.com/nct-data-share/docx/0+(1).docx",
	"thumbnail": {
		"first": false,
		"height": 800,
		"width": 600
	},
	"key": "{{$guid}}"
}
```
