### ISSUE TITLE
Table function IF with remote file

### ISSUE THREAD

**Issue by w202mg** [ONLYOFFICE/DocumentServer#2322]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.4.1.36

### Expected Behavior

When using IF function referring to data from a remote file the function shall work and not showing an error instead.

### Actual Behavior

There is an error.

### Reproduction Steps

1. Create a file data.xlsx with a sheet named Sheet
2. Type 1 in A1
3. Create a new file in the same folder
4. Open new file
5. Type in A1: =If('[data.xlsx]Sheet'!A1="";"";'[data.xlsx]Sheet'!A1)

### Additional information

Tried under Linux with flatpak and deb, as well as under Windows.

**Comment by rsnegirev** [comment]
Hi @w202mg 

The problem was fixed in the https://github.com/ONLYOFFICE/sdkjs/commit/6bfd71a1499a679c965a28a13c7b29ceed355459. The result you will see in the next release version of ONLYOFFICE.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
