### ISSUE TITLE
replacing text under "track changes" deletes the text but then inserts new typed text at the beggining of the text

### ISSUE THREAD

**Issue by Noa-Lavie** [ONLYOFFICE/DocumentServer#2324]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36

### Expected Behavior

When highlighting a text (for example a word) in order to change it the highlighted text will be replaced by the typed text

### Actual Behavior

Under track changes (not under normal editing) the highlighted text is deleted but the new text is inserted in the beginning of the paragraph and not instead of the deleted text.

### Reproduction Steps

1. activate track changes
2. add a paragraph or a chunk of text
3. highlight a specific word inside it that you would like to replace
4. start typing the new word

**Comment by maruacat** [comment]
Hey @Noah-Lavi!
I have great news. We have fixed this issue https://github.com/ONLYOFFICE/sdkjs/commit/8bf29dafd43f80d09f6c6ad03230a2d2f7a8f5a3 and it will be available in the new major version of the editor.
Have a nice day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
