### ISSUE TITLE
Deploy DocumentServer locally, run the sample project to open and edit the document, and an error occurs

### ISSUE THREAD

**Issue by mylvghb** [ONLYOFFICE/DocumentServer#2327]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.4.1.36

### Expected Behavior

![QQ截图20230811172753](https://github.com/ONLYOFFICE/DocumentServer/assets/35945793/229bdc8d-b112-408e-8e74-0448233753d5)

### Actual Behavior

![QQ截图20230811172753](https://github.com/ONLYOFFICE/DocumentServer/assets/35945793/865295ba-14a6-4d75-a60a-453700f4966b)

**Comment by igwyd** [comment]
Hello @mylvghb, which version of the Windows server are you using? Please provide the logs of the document server.

**Comment by mylvghb** [comment]
I have solved it. Tanks
