### ISSUE TITLE
zh-CN fully support has an date？

### ISSUE THREAD

**Issue by jinyue-rdj** [ONLYOFFICE/DocumentServer#233]
when open the  2007 & 2013 office document，such as excel，will appear messy.
Is it because zh-CN has not been fully supported? 
Is there an date or for Chinese support？
Thanks in advance.
![onlyoffice_zhcn](https://user-images.githubusercontent.com/19581634/35434682-f10f5640-02c2-11e8-8e1e-37f32d32b1d7.png)

**Comment by 3xxx** [comment]
#7
here is ok for chinese.
https://github.com/3xxx/ONLYOFFICE-golang

**Comment by jinyue-rdj** [comment]
@3xxx thank you very much，but i can`t use it，our language is java

**Comment by ShockwaveNN** [comment]
If I understand correctly - this issue should be fixed in DocumentServer 5.3

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
