### ISSUE TITLE
Onlyoffice document editor some areas can be edited

### ISSUE THREAD

**Issue by huazai0803** [ONLYOFFICE/DocumentServer#2331]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Onlyoffice restricts the editable area of the same document for online editing, with specified parts being editable online and unspecified parts not being editable

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
