### ISSUE TITLE
CSV Files Not Saved Correctly

### ISSUE THREAD

**Issue by Sledge-Hammer** [ONLYOFFICE/DocumentServer#2333]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

6.4.2.6

### Expected Behavior

1) When adding a new cell to a CSV file to be saved.
2) When adding two cells to a CSV file to be saved in the correct order
3) When adding 2 or more cells to a CSV file for all of them to be present after save

### Actual Behavior

1) When adding only one cell and click Save it's missing after the file is reopened.
2) When adding 2 cells and click Save their values are switched when the file is reopened (**this occurs only sometimes, more often I get problem 3 when adding only 2 cells**).
3) When adding 2 or more cells and click Save the values are in the correct order but the last one is always missing after the file is reopened.

### Reproduction Steps

While working with CSV files in the Spreadsheet App on Windows I've found 3 bugs.
Here's an example CSV:
```
column1,column2,column3
row1_value1,row1_value2,
row2_value1,row2_value2,
row3_value1,row3_value2,
row4_value1,row4_value2,
row5_value1,row5_value2,
```

**Problem 1:**
If I add the value 'row1_value3' in the first row below column3 and click Save the value is missing when I re-open the file.

**Problem 2:**
_This occurs rarely, I get problem 3 almost every time with this case._
If I add 2 values 'row1_value3' and 'row2_value3' below column3 and click Save both values are there but with switched places when I re-open the file.
Here's the resulting CSV:

```
column1,column2,column3
row1_value1,row1_value2,row2_value3
row2_value1,row2_value2,row1_value3
row3_value1,row3_value2,
row4_value1,row4_value2,
row5_value1,row5_value2,
```

**Problem 3:**
If I add 2 (or more) values 'row1_value3', 'row2_value3' and 'row3_value3' below column3 and click Save the last value is missing when I re-open the file.
Here's the resulting CSV:

```
column1,column2,column3
row1_value1,row1_value2,row1_value3
row2_value1,row2_value2,row2_value3
row3_value1,row3_value2,
row4_value1,row4_value2,
row5_value1,row5_value2,
```

### Additional information

Haven't tested with anything other than the native Windows app.

**Comment by rsnegirev** [comment]
Hi @Sledge-Hammer 

Problem was fixed in this commit https://github.com/ONLYOFFICE/sdkjs/commit/670b423bac1a24d8cceb480cc3b946ee9bec6b4e

It will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by Sledge-Hammer** [comment]
Thank you, I've tested the new version and can confirm that the issue has been fixed.
