### ISSUE TITLE
How to remove the buttons in the left operation bar

### ISSUE THREAD

**Issue by alixiaodi** [ONLYOFFICE/DocumentServer#2335]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/64963636/9352c7c8-0056-4ea3-a5e6-36df3d50cec4)

**Comment by alixiaodi** [comment]
editorConfig: {
					mode: 'edit',
					lang: 'zh-CN',
					customization: {
						customer: {
							logo: 'http://127.0.0.1:8080/s/a3kvwg',
						},
					},
				},


I have used the above configuration but it does not take effect

**Comment by alixiaodi** [comment]
Currently, this content cannot be modified or closed

**Comment by igwyd** [comment]
Hello @alixiaodi, some buttons can be removed from the left action bar, but not all. You can view the options [here](https://api.onlyoffice.com/editors/config/editor/customization). About  [customer](https://api.onlyoffice.com/editors/config/editor/customization#customer) and [logo](https://api.onlyoffice.com/editors/config/editor/customization#logo), this is available in commercial versions with a license, but you can test it in the ONLYOFFICE-Docs Developer edition.
![333](https://github.com/ONLYOFFICE/DocumentServer/assets/67538082/706dc69b-4a15-419f-bc31-982182a403ea)

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
