### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin

### ISSUE THREAD

**Issue by kenrmayfield** [ONLYOFFICE/DocumentServer#2337]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

OwnCloud 10.12.2.1

### Expected Behavior

The Browers FireFox, Opera and Chrome to Open Documents for Editing.

### Actual Behavior

@igwyd

I used the Browsers FireFox, Opera and Chrome for Testing OwnCloud connected to OnlyOffice.

FireFox(Initial Browser I used for 2 Weeks) **does not receive** the Error: **ONLYOFFICE cannot be reached. Please contact admin** when clicking on  a Document.
I am able to Open a Document and Edit with FireFox.

Opera and Chrome(Used both 2 Weeks after) receive the Error: **ONLYOFFICE cannot be reached. Please contact admin** when clicking on a Document.

Using the same User Account when Logging into All Three Browsers at Once.

Is there a Trust Relationship happening when using New Browsers to Login if you have already had Previous Login Connections
from the Initial Browser between OwnCloud and OnlyOffice?

**Comment by igwyd** [comment]
In your installation, you are using self-signed certificates (your other [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/2311)), I think the point is the browser's trust in the certificate. Have you added your certificate to the local certificate store FireFox and not added to the local storage PC(Opera and Chrome use the PC certificate store, unlike FF, which has its own store)?

**Comment by kenrmayfield** [comment]
@igwyd 

First of all Igor, Thanks for All your Help and Time.

For FireFox I did not have to Add to the Local Certificate Store for FireFox.   

No, I did not Add to the Local Storage on the PC for Opera or Chrome.

**This is what I did to get it to work for Opera or Chrome:**
First Option

Go to the OnlyOffice Welcome Page in the New Browser Software Brand
https://IP Address OnlyOffice Server

If the Welcome Page pulls up successfully, go back and Login again.
You should now be able to Login without the Error Message: ONLYOFFICE cannot be reached. Please contact admin
This procedure should have Establish Communication or Trust between
OwnCloud and Onlyoffice **when using a New Browser that does not have its own Certificate Store to Login**.

or 

Second Option

Signed Certificate
wget https://IP Address OnlyOffice

Self Signed Certificate
wget --no-check-certificate https://IP Address OnlyOffice

This will Copy over the Welcome Page from OnlyOffice which is index.html.
Once successfully copied over by wget, you can delete the copied index.html.
This procedure should have Establish Communication or Trust between
OwnCloud and Onlyoffice **when using a New Browser that does not have its own Certificate Store  to Login**.

Whichever Option you choose should now Allow a New Browser Software Brand to Login without the Error Message: ONLYOFFICE cannot be reached. Please contact admin

I have tried both Options with success.   However

**Comment by igwyd** [comment]
@kenrmayfield welcome)
Yes, it may work, but I think it was more correct to add your root certificate to local cert storage in your system and FF.

**Comment by kenrmayfield** [comment]
@igwyd 

Thanks You for your Help Igor.   Closing Post.
