### ISSUE TITLE
NextCloud & Document server Linux

### ISSUE THREAD

**Issue by sesipod** [ONLYOFFICE/DocumentServer#234]
I have an issue trying to open documents on my Nextcloud instance. I click on a document to edit and the onlyoffice logo just repeats over and over. Never taking me to the document. Could someone please hep me find and fix the issue.

⚠️ Notice: I have xx.com'ed my domains to protect my servers. ⚠️ 

<img width="1414" alt="screen shot 2018-01-26 at 1 12 15 pm" src="https://user-images.githubusercontent.com/1533744/35456288-932edd52-029a-11e8-95a0-0efe89d706ff.png">

![20180126_193338](https://user-images.githubusercontent.com/1533744/35467067-ec7538c2-02cf-11e8-9f6f-bc3710ecec52.png)

I'm using Nextcloud 12.0.4 on Debian 9.0 - 192.168.1.81
OnlyOffice plugin version 1.2.0

Onlyoffice Docker container - 192.168.1.82

--
Apache2 proxy config for onlyoffice.

<IfModule unixd_module>
  User daemon
  Group daemon
</IfModule>

<VirtualHost *:443>
        ServerName office.xx.com
        SSLEngine on
        SSLCertificateFile /root/ssl/fullchain.pem
        SSLCertificateKeyFile /root/ssl/privkey.pem
        SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256$
        SSLProtocol All -SSLv2 -SSLv3
        SSLCompression off
        SSLHonorCipherOrder on
        SetEnvIf Host "^(.*)$" THE_HOST=$1
        RequestHeader setifempty X-Forwarded-Proto https
        RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
        ProxyAddHeaders Off
        ProxyPassMatch (.*)(\/websocket)$ "ws://192.168.1.82/$1$2"
        ProxyPass / "http://192.168.1.82/"
        ProxyPassReverse / "http://192.168.1.82/"
</VirtualHost>

-- 
Apache2 proxy config for Nextcloud. 

<VirtualHost *:443>
    ServerName cloud.xx.com
    SSLEngine On
    SSLCertificateFile /root/ssl/fullchain.pem
    SSLCertificateKeyFile /root/ssl/privkey.pem
    SSLProxyEngine On
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM$
    SSLProtocol All -SSLv2 -SSLv3
    SSLCompression off
    SSLHonorCipherOrder on
    SetEnvIf Host "^(.*)$" THE_HOST=$1
    RequestHeader setifempty X-Forwarded-Proto https
    RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
    ProxyAddHeaders Off
    ProxyHTMLURLMap (.*)192.168.1.81(.*) http://192.168.1.81$2 [Rin]
    ProxyPass / http://192.168.1.81/
    ProxyPassReverse / http://192.168.1.81/
</VirtualHost>

**Comment by calvinlevy** [comment]
Dear @sesipod:
I too experienced this "but" when testing with http only.  Adding http://office.xx.com/ in the next field also under Advanced server settings worked for me during the test.  However, I am struggling with the https setup.  I have submitted a [ticket](https://github.com/ONLYOFFICE/DocumentServer/issues/235) also although my setup may be a little different than yours.

**Comment by sesipod** [comment]
Im almost sure its an Proxy issue at this point. I have been running the document server in a docker container using port 8443 https and its been working all weekend. I have only ever filled out the first line inside of Nextcloud. I also set a hard limit on the amount of ran that docker can use this seems to help not crash the host when memory is over used.

Here is my docker setup.

1.Make the ssl cert dir.
   mkdir -p /app/onlyoffice/DocumentServer/data/certs

2.Copy over your **fullchain.pem** and **privkey.pem**
    cp privkey.pem onlyoffice.key
    cp fullchain.pem onlyoffice.crt

3.Make strong DHE parameters
    cd /app/onlyoffice/DocumentServer/data/certs
    openssl dhparam -out dhparam.pem 2048

4.Run the docker container.
    sudo docker run --memory=3g -i -t -d -p 8443:443 --restart=always \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver

**Comment by agolybev** [comment]
Hi @sesipod, Are there any errors in the browser console when you are openig a document?

**Comment by sesipod** [comment]
Im guessing you are talking about under nextcloud ? If so there was none at all. I thought it was odd.

**Comment by sesipod** [comment]
Im guessing you are talking about under nextcloud ? If so there was none at all. I thought it was odd.

**Comment by agolybev** [comment]
I'm talking about window whrere you open a document. Same behavior is accompanied by errors  in browser console. I think the error occur before all documentserver script is loaded. So document server can't handle such errors.

**Comment by sesipod** [comment]
I switched back over to using the Proxy.
The plugin is loading for now... But here is the error in the browser that its showing to me.

<img width="1661" alt="screen shot 2018-01-31 at 2 33 35 pm" src="https://user-images.githubusercontent.com/1533744/35646119-c4ca7e0a-0693-11e8-9efd-9753c4cff433.png">

**Comment by agolybev** [comment]
Hi, @sesipod It seems to editor doesn't connect to the document server with websocket. I think your proxy server doesn't pass websocket traffic. But it strange if you use config mentioned above.

**Comment by sesipod** [comment]
So is my proxy config correct then?

**Comment by agolybev** [comment]
The seems to be right if you havn't changed it since publishing.

**Comment by sesipod** [comment]
I have not changed it. But still the error :/

**Comment by agolybev** [comment]
OK, let's forget about wss-error for a while. Does the editor work properly?

**Comment by sesipod** [comment]
It is still working at this moment. That is strange to me because I haven't changed a thing since making this post. Except the update to the plugin.

**Comment by agolybev** [comment]
It's working even without any error in browser console?

**Comment by sesipod** [comment]
Its working and yes the web socket error is still there.
But you said to forget about the wss-error. 

Here is what FireFox is spitting out....
![screen shot 2018-02-01 at 10 27 39 am](https://user-images.githubusercontent.com/1533744/35690181-db1ae8c8-073a-11e8-80de-e351ba027234.png)

**Comment by agolybev** [comment]
There are two typical websocket errors:
- Websocket doesn't proxied with proxy server
- Websocket handshake is breaked with antivirus program installed on the client machine or server

**Comment by sesipod** [comment]
I'm sure its the proxy. 

I'm running Debian 9.3 on the Nextcloud box no antivirus.. Really?!? antivirus on a server asking for problems.. 
I'm running vmware photon for the docker container.
I have no antivirus on any of my computers or servers. ( just don't do stupid stuff and you don't need it )

**Comment by agolybev** [comment]
Hi @sesipod, could you provide me whole apache config and apache log?

**Comment by agolybev** [comment]
@sesipod, what is about `LoadModule` statements in apache config? I haven't seen it yet.

**Comment by sesipod** [comment]
The apache2 error log located: /var/log/apache2/error.log is empty except for one line starting ssl for apache2. 👍 

It's at the very bottom of ( apache2.conf ) it just makes a reference to the file that holds the office proxy config. I make separate config files for each of my sites OCD. I don't use the typical sites-enabled config files. 

The line is: 
include /etc/apache2/proxys/office.xx.com


(---------------------------------------------)
nano /etc/apache2/proxys/office.xx.com
(-v----------------v---v--------------------v-)


<IfModule unixd_module>
  User daemon
  Group daemon
</IfModule>

<VirtualHost *:443>
        ServerName office.xx.com
        SSLEngine on
        SSLCertificateFile /root/ssl/fullchain.pem
        SSLCertificateKeyFile /root/ssl/privkey.pem
        SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES25$
        SSLProtocol All -SSLv2 -SSLv3
        SSLCompression off
        SSLHonorCipherOrder on
        SetEnvIf Host "^(.*)$" THE_HOST=$1
        RequestHeader setifempty X-Forwarded-Proto https
        RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
        ProxyAddHeaders Off
        ProxyPassMatch (.*)(\/websocket)$ "ws://192.168.1.82/$1$2"
        ProxyPass / "http://192.168.1.82/"
        ProxyPassReverse / "http://192.168.1.82/"
</VirtualHost>
(---------------------------------------------)

**Comment by agolybev** [comment]
Ensure that websocket proxy module is loaded with `LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so` statement.

**Comment by sesipod** [comment]
Do I just add that full line to the apache2 config?

nano /etc/apache2/apache2.conf
add
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so

**Comment by sesipod** [comment]
I ran the following command `a2enmod proxy_wstunnel`
Think this is what you are talking about after a quick google.

**Comment by sesipod** [comment]
@agolybev - running a2enmod proxy_wstunnel - Fixed the error in the Developer view! 👍

**Comment by agolybev** [comment]
Hi @sesipod.
Is  there `LoadModule proxy_wstunnel_module ...` in apache config? Is there any effects after its adding?

**Comment by agolybev** [comment]
@sesipod, can I close the issue?
