### ISSUE TITLE
CONVERT functions given incorrect result (m2 -> mm2)

### ISSUE THREAD

**Issue by xyont** [ONLYOFFICE/DocumentServer#2350]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36

### Expected Behavior

hi,

it seems, some CONVERT functions with prefix given incorrect results, for example insert cell formula and type =CONVERT(1,"m2","mm2") will show result 1000 (1.00E+03) instead 1000000 (1.00E+06). Also, another incorrect result when typing =CONVERT(1,"m3","mm3") which should be (1.00E+09) instead 1000 (1.00E+03) 

regards,

### Actual Behavior

![OnlyOfficeUnitsIncorrect2](https://github.com/ONLYOFFICE/DesktopEditors/assets/72367311/de03dd77-c57d-440f-986f-3366d350e05e)

### Reproduction Steps

=CONVERT(1,"m2","mm2")

**Comment by rsnegirev** [comment]
@xyont yes, we found this too. The problem with all the values ​​of the metric system, we will try to figure it out.

**Comment by rsnegirev** [comment]
Hi @xyont 

The problem was fixed in this commit https://github.com/ONLYOFFICE/sdkjs/commit/0afb2e194a4bd5808706922f6bd3b0e73c5d58cc.
Fixes will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
