### ISSUE TITLE
docx convert pdf messy code

### ISSUE THREAD

**Issue by camellia57** [ONLYOFFICE/DocumentServer#2351]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.2.1

### Expected Behavior

convert docx to PDF 

### Actual Behavior

sometimes there will be  messy code

### Additional information

![乱码](https://github.com/ONLYOFFICE/DocumentServer/assets/68042888/8df1d5b0-325c-4f25-ad4d-66e962a0a5cb)

**Comment by Rita-Bubnova** [comment]
Hello, @camellia57.
DocumentServer v7.4.1 is released. Is this issue relevant in new version?

**Comment by camellia57** [comment]
> Hello, @camellia57. DocumentServer v7.4.1 is released. Is this issue relevant in new version?

The new version has not been tested

**Comment by camellia57** [comment]
> @camellia57, Please update DocumentServer. If the problem reproduces, please send us your file and details about the browser, OS, and steps to reproduce the problem.

OK

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
