### ISSUE TITLE
Does the oform file not support running macros?

### ISSUE THREAD

**Issue by walirt** [ONLYOFFICE/DocumentServer#2356]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.x

### Expected Behavior

macro not working

### Actual Behavior

macro working

### Additional information

I wrote the macro code in docxf, but the exported oform file didn't run automatically
this is macro code
```
(function()
{
    console.log(111);
    var oDocument = Api.GetDocument();
    Api.attachEvent("onChangeContentControl", function(e) {
        console.log(e);
        var contentControls = oDocument.GetContentControlsByTag(e["Tag"]);
        console.log(contentControls);
        for (var i = 0; i< contentControls.length; i++) {
            var contentControl = contentControls[i];
            var result = JSON.parse(contentControl.ToJSON());
            var content = result.content[0].content;
            if (content && (content.includes('☐') || content.includes('☑'))) {
                var checked = content == '☑' ? true : false;
                if (checked) {
                    var range = oDocument.GetBookmarkRange(e["Tag"]);
                    if (range) {
                        range.Delete();
                    }
                }
            }
        }
    });
})();
```

**Comment by askonev** [comment]
@walirt Yes, in the context oform, the use of macros scripts is forbidden

**Comment by walirt** [comment]
> @walirt Yes, in the context oform, the use of macros scripts is forbidden

Is there a way to run the script with document protection (filling the form)
Scripts are used to dynamically replace default variables within a document

**Comment by askonev** [comment]
@walirt Did I understand your scenario correctly?

1. Set a password on the docxf document
2. Edit macros and set autostart.
3. Create oform and open in form fill mode.

As a result, the script worked

The answer is no, the script will not run in this scenario

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
