### ISSUE TITLE
跨页引用的图未能及时更新

### ISSUE THREAD

**Issue by JiffyChen** [ONLYOFFICE/DocumentServer#2358]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package), Docker

### Version information

7.2.1.34

### Expected Behavior

跨页引用的图能够根据数据的变化及时更新。

### Actual Behavior

跨页引用的图能够根据数据的变化未能及时更新。

### Reproduction Steps

1. sheet 1 存放两行数据
2. sheet 2 存放两行数据，值通过引用sheet1
3. 在sheet 1 添加 2个饼图，饼图1数据是引用sheet1，饼图2数据引用sheet2
4. 变化sheet 1中的行数据，饼图1正常更新，饼图2更新失败
5. 切换sheet2并立即切换回sheet1，饼图2数据显示正常。

### Additional information

[test_refe.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/12436907/test_refe.xlsx)

**Comment by Rita-Bubnova** [comment]
Hello, @JiffyChen. 
DocumentServer v7.4.1 has been released.
Please update the DocumentServer and use English to describe the issue.

**Comment by JiffyChen** [comment]
OK, I will try by 7.4.1, Thanks

**Comment by JiffyChen** [comment]
Have the same problem on v7.4.1

**Comment by Rita-Bubnova** [comment]
@JiffyChen Thank you for the answer.  
Please, fill in all the fields of the form completely in English. This is needed for us to check the problem.

**Comment by trofim24** [comment]
duplicate #2363
