### ISSUE TITLE
Use Indirect formulas, cell options not updated accordingly

### ISSUE THREAD

**Issue by Chenbg69** [ONLYOFFICE/DocumentServer#2366]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

6.3.1.56

### Expected Behavior

When changing this cell option, the corresponding cell option in the second column is immediately updated for selection

### Actual Behavior

When the cell options are changed, the associated cell options have not changed, and the formula needs to be manually executed once

**Comment by Rita-Bubnova** [comment]
Hello, @Chenbg69.
DocumentServer v7.4.1 is released. Please state is this problem is still actual in the new version?

**Comment by VladimirProkofiev52** [comment]
Hello @Chenbg69, Am I understanding correctly that you are using the "=INDIRECT" formula?
I couldn't replicate your issue, could you please provide a more detailed description?

**Comment by Chenbg69** [comment]
> 你好@Chenbg69，我理解你正在使用“=INDIRECT”公式吗？
> 我无法重现你的问题，你能提供更详细的描述吗？

yes, For example, in the formula a: a1, a2, b: b1, b2, but when the first column is a, sometimes the options for the second column cell are not a1, a2, perhaps b1, b2, and the corresponding options are not updated when changing the cell. However, if you manually use the data panel on Excel and the data validation function to verify the current cell, the options can be corresponding again, I would like to know if this issue is caused by the failure to refresh and apply the formula during each edit, or what is the reason? The application scenarios of onDocumentStateChange and onRequestReferenceData in the event

**Comment by VladimirProkofiev52** [comment]
@Chenbg69 I again was unable to reproduce your problem.
Could you send me a screencast of your problem or a sample file containing the problem?

**Comment by Chenbg69** [comment]
![F1DD4AD5-4438-465F-96E2-3EFC1759ECF9](https://github.com/ONLYOFFICE/DocumentServer/assets/143592704/2bf36cd2-1613-4216-8fda-1c3bbd99fd93)

**Comment by Chenbg69** [comment]
![Uploading 9C4476FB-EC8E-4E6D-AEC3-1A7CD4E2EAF7.jpeg…]()

**Comment by Chenbg69** [comment]
> @Chenbg69我再次无法重现你的问题。
> 你能给我发一份你问题的截屏视频或包含该问题的示例文件吗？

The video is too large, please take a look at this image. Team collaboration should be T1, T2, T3, but options are M1, M2

**Comment by VladimirProkofiev52** [comment]
The image did not load, please try again.

**Comment by Chenbg69** [comment]
![C3F32000-DC5C-488C-A58B-2FC2D82084FF](https://github.com/ONLYOFFICE/DocumentServer/assets/143592704/30dcdba4-fccf-49a1-8e1f-3ec51ad73703)

**Comment by VladimirProkofiev52** [comment]
@Chenbg69, сan you send me a file that contains the problem?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
