### ISSUE TITLE
Can the source code be compiled under windows？

### ISSUE THREAD

**Issue by jiangzk123** [ONLYOFFICE/DocumentServer#2368]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I want to  compile under windows  system for debugging, mainly C++ code, such as: core.
Encountered some libraries do not know how to compile,the project path is DocumentServer\core\X2tConverter\test\win32Test
![错误截图](https://github.com/ONLYOFFICE/DocumentServer/assets/90822191/321a9d33-5a66-4a93-8fcf-986ccbc185dd)

**Comment by trofim24** [comment]
See instructions in [build_tools](https://github.com/ONLYOFFICE/build_tools#building-onlyoffice-products-source-code)

**Comment by jiangzk123** [comment]
Thanks. I'll try
