### ISSUE TITLE
Can not use docker container name to connect OnlyOffice.

### ISSUE THREAD

**Issue by Azreulo** [ONLYOFFICE/DocumentServer#2370]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.41.36

### Expected Behavior

I deployed a NextCloud in my network. Here is the contailers and network config.

Create a bridge network named John.
Deploy a MaraiDB, container named MariaDB, a NextCloud container named NextCloud, setup with database use container name MariaDB instead of use IP address, and it works fine.

Deployed an OnlyOffice, container named OnlyOffice,.
`sudo docker run -d --restart=always --name OnlyOffice \
--network=John \
-p 5310:80 \
-p 5320:443 \
-v /data/onlyoffice/fonts:/usr/share/fonts/truetype/custom \
-v /data/onlyoffice/data:/var/www/onlyoffice/Data \
-v /data/onlyoffice/onlyoffice:/var/lib/onlyoffice \
-v /data/onlyoffice/log:/var/log/onlyoffice \
-v onlyoffice_postgres:/var/lib/postgresql \
-v onlyoffice_rabbitmq:/var/lib/rabbitmq \
-v onlyoffice_redis:/var/lib/redis \
-e JWT_SECRET=123456 \
-e SSL_CERTIFICATE_PATH=/var/www/onlyoffice/Data/OnlyOffice.crt \
-e SSL_KEY_PATH=/var/www/onlyoffice/Data/OnlyOffice.key \
-e USE_UNAUTHORIZED_STORAGE=true \
onlyoffice/documentserver`

After that, I configed in NextCloud, ONLYOFFICE Docs addree use `https://OnlyOffice`, it connected and show version 7.41.36 OK.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/21158437/009abd24-7dc9-4527-b728-232e2e7be375)

But when I open a docx file in my NextCloud, it shows that Can not connect to OnlyOffice Server.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/21158437/586585f6-7a40-4570-88f3-34e2c4f38d99)

I changed the ONLYOFFICE Docs address as the container mounted IP address 192.168.1.221, and it works fine again.

But why? I can't understand. The NextCloud and the OnlyOffice container can find each other by container name, but can't show documents correectly.

I expect that ONLY mount a port NextCloud:443 and NextCloud communicate with OnlyOffice by my own docker bridge network John like this.
NextCloud:443<===>OnlyOffice:443

### Actual Behavior

See the above.

**Comment by igwyd** [comment]
Hello @Azreulo, this is because container names only work inside the docker network - [You need an instance of ONLYOFFICE Docs that is resolvable and connectable both from Nextcloud and any end clients](https://helpcenter.onlyoffice.com/integration/gettingstarted-nextcloud.aspx#Requirements_block). You can use a reverse proxy, we have an integration example [here](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud).

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
