### ISSUE TITLE
认证失败，无法访问系统资源，下面还有一层提示当前文件无法保存，点击ok下载

### ISSUE THREAD

**Issue by Chenbg69** [ONLYOFFICE/DocumentServer#2377]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1

### Expected Behavior

打开文件时报如题两个错误

### Actual Behavior

如上所述

**Comment by Chenbg69** [comment]
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/143592704/e2a82d4b-51ec-4972-b9b9-e5f3e775ec40)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
