### ISSUE TITLE
OnlyOffice 7.4 Document server only uses one vCPU

### ISSUE THREAD

**Issue by Jorgemgm** [ONLYOFFICE/DocumentServer#2378]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

OnlyOffice 7.4 Document server

### Expected Behavior

We expected the OnlyOffice 7.4 Document to use all CPUs.

### Actual Behavior

The OnlyOffice 7.4 Document only uses one CPU.

### Reproduction Steps

We installed the Nextcloud and the OnlyOffice 7.4 Document server on separate Proxmox containers.

We can't understand why the OnlyOffice 7.4 Document server only uses one vCPU:
- 4vCPU the CPU usage of 25% of 4 vCPU(s), but only one core.
- 8vCPU the CPU usage of 12.5% of 8 vCPU(s), but only use one core.

For OnlyOffice 7.4 Document server, we configured the RAM on postgresql.conf.

Is this one limitation of OnlyOffice 7.4 Document server?

If not, how do we can configure the use of the other seven vCPU(s) on the OnlyOffice 7.4 Document server?

**Comment by igwyd** [comment]
Hello @Jorgemgm, do you mean that there is only one docservice process? Yes, there is only one in the RPM installation, but you can increase the number of doxservice processes using containers and clustering. What do you mean with RAM and postgresql.conf?

**Comment by Jorgemgm** [comment]
@igwyd 
Thanks for your reply.

"What do you mean with RAM and postgresql.conf?"
Please you can see the print screen.

![postgrepsql conf](https://github.com/ONLYOFFICE/DocumentServer/assets/38436949/a3438060-7b91-4ff5-b296-0eec61d08cfc)


The OnlyOffice 7.4 Document server only uses one CPU.
Please you can see the print screen.

<img width="1418" alt="OO_only_use_1_cpu" src="https://github.com/ONLYOFFICE/DocumentServer/assets/38436949/dd046045-de01-4f05-9f18-41ebb437cdff">

.
How do we configure the OnlyOffice 7.4 Document server to use all CPUs?

**Comment by igwyd** [comment]
Thanks for screenshots, i see you point. The onlyoffice-documentserver convert the documents before open. In Community Edition we have a limitation - only one conversion at time, so only one process and only one core is running. 
To run the documentserver without this limitation you can try Developer Edition or Enterprise Edition for 30 days free trial https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-docs-editions.

**Comment by Jorgemgm** [comment]
@igwyd

Thanks for your reply.

We understand the limitation.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
