### ISSUE TITLE
Create new document - Download failed and request has 403 status code

### ISSUE THREAD

**Issue by raulk89** [ONLYOFFICE/DocumentServer#2383]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)
Ubuntu 22.04

### Version information

Version: 7.4.1. Build: 36

### Expected Behavior

I am on page "http://webserver.domain.com:8080/example/"

Click on Create new "Document"
This url opens up: http://webserver.domain.com:8080/example/editor?fileName=new%20(2).docx
And I get this popup:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/25365468/6a86c101-3342-4d0d-85e9-31dfaf687082)

From developer tools Network tab, I get 403:
```
Request URL:
http://webserver.domain.com:8080/cache/files/data/176.46.122.157new__2_.docx1694462063180/Editor.bin/Editor.bin?md5=KA4fXtoQ1UsZPQr89sV4ow&expires=1697077825&filename=Editor.bin
Request Method:
GET
Status Code:
403 Forbidden
```

Tried the same url from localhost as well, same error, so not network issue:

```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Regards
Raul

### Actual Behavior

New document pops up and I can start editing it.

### Additional information

From nginx access log I get this, there is this 403 as well:

```
80.250.113.249 - - [11/Sep/2023:23:00:34 +0300] "GET /example/download?fileName=new%20(3).docx&useraddress=176.46.122.157 HTTP/1.1" 200 6940 "-" "Node.js/6.13"
176.46.122.157 - - [11/Sep/2023:23:00:35 +0300] "GET /cache/files/data/176.46.122.157new__3_.docx1694462433506/Editor.bin/Editor.bin?md5=i3M703AZmPfhfMdomK4msg&expires=1697078195&filename=Editor.bin HTTP/1.1" 403 180 "http://webserver.domain.com:8080/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=http://webserver.domain.com:8080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

```

**Comment by igwyd** [comment]
Hello @raulk89, I see that you have changed the default port, how did you do that? Do you use our manual(port changing chapter) in the [installation guid](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx)? Describe in more detail your installation steps and provide the documentserver logs ```/var/log/onlyoffice/documentserver/```

**Comment by raulk89** [comment]
I run this
echo onlyoffice-documentserver onlyoffice/ds-port select 8080 | sudo debconf-set-selections

And later I tried it for ssl. Then I followed this instruction:
https://helpcenter.onlyoffice.com/installation/docs-community-https-linux.aspx

From there I coped over ssl conf to ds.conf
There was 8080 and 443 ports.
And then I changed 443 port to 8443 from that file.

These 2 rows:
```
  listen 0.0.0.0:8443 ssl;
  listen [::]:8443 ssl default_server;
```

**Comment by igwyd** [comment]
If you switched to HTTPS following the https://helpcenter.onlyoffice.com/installation/docs-community-https-linux.aspx, then you must use HTTPS protocol for access to intergated test example, follow to https://webserver.domain.com:8443/example/

**Comment by yasirrose** [comment]
@raulk89 Are you able to solve this issue? I am facing 403 error for cache link.
