### ISSUE TITLE
it is not possible to install or remove the document server package on debian 12

### ISSUE THREAD

**Issue by saber716rus** [ONLYOFFICE/DocumentServer#2384]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.1-36

### Expected Behavior

the package is installed or removed

### Actual Behavior
An error pops up
root@saber716rus-BOM-WXX9 ~# nala remove onlyoffice-documentserver
================================================================================
 Configuring                                                                    
================================================================================
  Пакет:                    Версия:                                    Размер:  
  onlyoffice-documentserv…  7.4.1-36                                    1.4 GB  
                                                                                
================================================================================
 Removing                                                                       
================================================================================
  Пакет:                    Версия:                                    Размер:  
  onlyoffice-documentserv…  7.4.1-36                                    1.4 GB  
                                                                                
================================================================================
 Summary                                                                        
================================================================================
 Configure 1 Пакеты                                                             
 Remove    1 Пакеты                                                             
                                                                                
 Disk space to free  1.4 GB   
                              
Do you want to continue? [Д/н] д
╭─ Удаление пакетов ───────────────────────────────────────────────────────────╮
│Removing:   onlyoffice-documentserver (7.4.1-36)                              │
│Preparing for shutdown, it can take a lot of time, please wait...Done         │
│Stopping documentserver services                                              │
│unlink: cannot unlink '/etc/nginx/conf.d/ds.conf': No such file or directory  │
│dpkg: error processing package onlyoffice-documentserver (--remove):          │
│installed onlyoffice-documentserver package pre-removal script subprocess ret…│
│dpkg: too many errors, stopping                                               │
│Errors were encountered while processing:                                     │
│onlyoffice-documentserver                                                     │
│Processing: was halted because there were too many errors.                    │
│╭────────────────────────────────────────────────────────────────────────────╮│
││⠦ Running dpkg … ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 40.0% • 0:00:03 • 2/5││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯
Ошибка: Installation has failed.
If you'd like to file a bug report please include '/var/log/nala/dpkg-debug.log'

Ошибка: error processing package onlyoffice-documentserver (--remove):

Ошибка: error processing package onlyoffice-documentserver (--remove):
 installed onlyoffice-documentserver package pre-removal script subprocess returned error exit status 1
 installed onlyoffice-documentserver package pre-removal script subprocess returned error exit status 1

Ошибка: too many errors, stopping

Ошибка: too many errors, stopping

Errors were encountered while processing:

Errors were encountered while processing:
 onlyoffice-documentserver
 onlyoffice-documentserver

Processing was halted because there were too many errors.

Processing was halted because there were too many errors.
root@saber716rus-BOM-WXX9 ~ [1]# 

### Reproduction Steps
Just install the package

### Additional information
root@saber716rus-BOM-WXX9 ~ [1]# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@saber716rus-BOM-WXX9 ~# 

root@saber716rus-BOM-WXX9 ~ [1]# cat /var/log/nala/dpkg-debug.log
Apt Do Install

Raw = False: [b'Selecting previously unselected package libmng1:amd64.\r\n(Reading database ... \r']
Raw = False: [b'(Reading database ... 5%\r']
Raw = False: [b'(Reading database ... 10%\r']
Raw = False: [b'(Reading database ... 15%\r']
Raw = False: [b'(Reading database ... 20%\r']
Raw = False: [b'(Reading database ... 25%\r']
Raw = False: [b'(Reading database ... 30%\r']
Raw = False: [b'(Reading database ... 35%\r']
Raw = False: [b'(Reading database ... 40%\r']
Raw = False: [b'(Reading database ... 45%\r']
Raw = False: [b'(Reading database ... 50%\r']
Raw = False: [b'(Reading database ... 55%\r']
Raw = False: [b'(Reading database ... 60%\r']
Raw = False: [b'(Reading database ... 65%\r']
Raw = False: [b'(Reading database ... 70%\r']
Raw = False: [b'(Reading database ... 75%\r']
Raw = False: [b'(Reading database ... 80%\r']
Raw = False: [b'(Reading database ... 85%\r']
Raw = False: [b'(Reading database ... 90%\r']
Raw = False: [b'(Reading database ... 95%\r']
Raw = False: [b'(Reading database ... 100%\r(Reading database ... 215510 files and directories currently installed.)\r\n']
line_fix = [b'Selecting previously unselected package libmng1:amd64.\r\n(Reading database ... \r']
Data_Split = [b'Selecting previously unselected package libmng1:amd64.', b'(Reading database ... \r(Reading database ... 100%\r(Reading database ... 215510 files and directories currently installed.)', b'']

Raw = False: [b'Preparing to unpack .../0-libmng1_1.0.10+dfsg-3.1+b5_amd64.deb ...\r\n']

Raw = False: [b'Unpacking libmng1:amd64 (1.0.10+dfsg-3.1+b5) ...\r\n']

Raw = False: [b'Selecting previously unselected package qt5-image-formats-plugins:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../1-qt5-image-formats-plugins_5.15.8-2_amd64.deb ...\r\n']

Raw = False: [b'Unpacking qt5-image-formats-plugins:amd64 (5.15.8-2) ...\r\n']

Raw = False: [b'Selecting previously unselected package fonts-open-sans.\r\n']

Raw = False: [b'Preparing to unpack .../2-fonts-open-sans_1.11-2_all.deb ...\r\n']

Raw = False: [b'Unpacking fonts-open-sans (1.11-2) ...\r\n']

Raw = False: [b'Selecting previously unselected package libsigc++-3.0-0:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../3-libsigc++-3.0-0_3.4.0-1_amd64.deb ...\r\n']

Raw = False: [b'Unpacking libsigc++-3.0-0:amd64 (3.4.0-1) ...\r\n']

Raw = False: [b'Selecting previously unselected package libglibmm-2.68-1:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../4-libglibmm-2.68-1_2.74.0-2_amd64.deb ...\r\n']

Raw = False: [b'Unpacking libglibmm-2.68-1:amd64 (2.74.0-2) ...\r\n']

Raw = False: [b'Selecting previously unselected package libminizip1:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../5-libminizip1_1.1-8+b1_amd64.deb ...\r\n']

Raw = False: [b'Unpacking libminizip1:amd64 (1.1-8+b1) ...\r\n']

Raw = False: [b'Selecting previously unselected package libqrcodegencpp1:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../6-libqrcodegencpp1_1.8.0-1.1_amd64.deb ...\r\n']

Raw = False: [b'Unpacking libqrcodegencpp1:amd64 (1.8.0-1.1) ...\r\n']

Raw = False: [b'Selecting previously unselected package librlottie0-1:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../7-librlottie0-1_0.1+dfsg-4_amd64.deb ...\r\n']

Raw = False: [b'Unpacking librlottie0-1:amd64 (0.1+dfsg-4) ...\r\n']

Raw = False: [b'Selecting previously unselected package libxcb-screensaver0:amd64.\r\n']

Raw = False: [b'Preparing to unpack .../8-libxcb-screensaver0_1.15-1_amd64.deb ...\r\n']

Raw = False: [b'Unpacking libxcb-screensaver0:amd64 (1.15-1) ...\r\n']

Raw = False: [b'Selecting previously unselected package telegram-desktop.\r\n']

Raw = False: [b'Preparing to unpack .../9-telegram-desktop_4.6.5+ds-2_amd64.deb ...\r\n']

Raw = False: [b'Unpacking telegram-desktop (4.6.5+ds-2) ...\r\n']

Raw = False: [b'Setting up libmng1:amd64 (1.0.10+dfsg-3.1+b5) ...\r\n']

Raw = False: [b'Setting up libqrcodegencpp1:amd64 (1.8.0-1.1) ...\r\n']

Raw = False: [b'Setting up libminizip1:amd64 (1.1-8+b1) ...\r\n']

Raw = False: [b'Setting up onlyoffice-documentserver (7.4.1-36) ...\r\n']

Raw = False: [b"ERROR: can't connect to postgressql database\r\n"]

Raw = False: [b'dpkg: error processing package onlyoffice-documentserver (--configure):\r\n installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1\r\n']
Data_Split = [b'dpkg: error processing package onlyoffice-documentserver (--configure):', b' installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1', b'']

Raw = False: [b'Setting up fonts-open-sans (1.11-2) ...\r\n']

Raw = False: [b'Setting up librlottie0-1:amd64 (0.1+dfsg-4) ...\r\n']

Raw = False: [b'Setting up libxcb-screensaver0:amd64 (1.15-1) ...\r\n']

Raw = False: [b'Setting up qt5-image-formats-plugins:amd64 (5.15.8-2) ...\r\n']

Raw = False: [b'Setting up libsigc++-3.0-0:amd64 (3.4.0-1) ...\r\n']

Raw = False: [b'Setting up libglibmm-2.68-1:amd64 (2.74.0-2) ...\r\n']

Raw = False: [b'Setting up telegram-desktop (4.6.5+ds-2) ...\r\nProcessing triggers for mailcap (3.70+nmu1) ...\r\n']
Data_Split = [b'Setting up telegram-desktop (4.6.5+ds-2) ...', b'Processing triggers for mailcap (3.70+nmu1) ...', b'']

Raw = False: [b'Processing triggers for fontconfig (2.14.1-4) ...\r\n']

Raw = False: [b'Processing triggers for desktop-file-utils (0.26-1) ...\r\n']

Raw = False: [b'Processing triggers for hicolor-icon-theme (0.17-2) ...\r\n']

Raw = False: [b'Processing triggers for libc-bin (2.36-9+deb12u1) ...\r\n']

Raw = False: [b'Processing triggers for man-db (2.11.2-2) ...\r\n']

Raw = False: [b'Errors were encountered while processing:\r\n onlyoffice-documentserver\r\n']
Data_Split = [b'Errors were encountered while processing:', b' onlyoffice-documentserver', b'']

['Traceback (most recent call last):\n', '  File "/usr/lib/python3/dist-packages/nala/dpkg.py", line 465, in run_install\n    os._exit(apt.do_install(self.write_stream.fileno()))  # type: ignore[attr-defined]\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 'apt_pkg.Error: E:Sub-process /usr/bin/dpkg returned an error code (1)\n']
root@saber716rus-BOM-WXX9 ~#

**Comment by igwyd** [comment]
Hello @saber716rus, we don't support third party package managers including nala, please use ```apt``` or ```apt-get```.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by saber716rus** [comment]
so I installed it via apt

**Comment by saber716rus** [comment]
root@saber716rus-BOM-WXX9 ~# apt purge onlyoffice-documentserver
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Следующие пакеты будут УДАЛЕНЫ:
  onlyoffice-documentserver*
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 1 пакетов, и 0 пакетов не обновлено.
Установлено или удалено не до конца 1 пакетов.
После данной операции объём занятого дискового пространства уменьшится на 1 392 MB.
Хотите продолжить? [Д/н] y
(Чтение базы данных … на данный момент установлено 217022 файла и каталога.)
Удаляется onlyoffice-documentserver (7.4.1-36) …
Preparing for shutdown, it can take a lot of time, please wait...Done
Stopping documentserver services...
unlink: невозможно удалить ссылку '/etc/nginx/conf.d/ds.conf': Нет такого файла 
или каталога
dpkg: ошибка при обработке пакета onlyoffice-documentserver (--remove):
 подпроцесс из пакета onlyoffice-documentserver установлен сценарий pre-removal 
возвратил код ошибки 1
dpkg: слишком много ошибок — останавливаемся
При обработке следующих пакетов произошли ошибки:
 onlyoffice-documentserver
Обработка остановлена из-за слишком большого количества ошибок.
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@saber716rus-BOM-WXX9 ~ [100]#

**Comment by igwyd** [comment]
I think errors in dpkg are due to installation via nala. On Debian 12 we often check the installation and there are no errors. Probably the simplest solution in your case is to reset the server, update the packages and install the documentserver by our guid https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx.

**Comment by saber716rus** [comment]
saber716rus@saber716rus-BOM-WXX9 ~ [1]> sudo apt install onlyoffice-documentserver
Reading package lists… Done
Building a dependency tree... Done
Reading status information… Done         
The onlyoffice-documentserver package of the newest version (7.4.1-36) has already been installed. 0 packages
have been updated, 0 new packages have been installed, 0 packages have been marked for deletion, and 0 packages have not been updated.
Installed or removed not until the end of 1 packages.
After this operation, the amount of occupied disk space will increase by 0 B.
Do you want to continue? [D/n] y
The onlyoffice-documentserver package is being configured (7.4.1-36) …
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
Generating js caches, please wait...Done
Installing plugins, please wait...Done
dpkg: error when processing the onlyoffice-documentserver package (--configure):
a subprocess from the onlyoffice-documentserver package installed the post-install
ation script returned error code 1
Triggers for libc-bin (2.36-9+deb12u1) are processed …
Errors occurred while processing the following packets:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
saber716rus@saber716rus-BOM-WXX9 ~ [100]> 


saber716rus@saber716rus-BOM-WXX9 ~ [1]> sudo apt install onlyoffice-documentserver
Reading package lists… Done
Building a dependency tree... Done
Reading status information… Done         
The onlyoffice-documentserver package of the newest version (7.4.1-36) has already been installed. 0 packages
have been updated, 0 new packages have been installed, 0 packages have been marked for deletion, and 0 packages have not been updated.
Installed or removed not until the end of 1 packages.
After this operation, the amount of occupied disk space will increase by 0 B.
Do you want to continue? [D/n] y
The onlyoffice-documentserver package is being configured (7.4.1-36) …
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
Generating js caches, please wait...Done
Installing plugins, please wait...Done
dpkg: error when processing the onlyoffice-documentserver package (--configure):
a subprocess from the onlyoffice-documentserver package installed the post-install
ation script returned error code 1
Triggers for libc-bin (2.36-9+deb12u1) are processed …
Errors occurred while processing the following packets:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
saber716rus@saber716rus-BOM-WXX9 ~ [100]>

**Comment by saber716rus** [comment]
saber716rus@saber716rus-BOM-WXX9 ~ [1]> sudo apt install onlyoffice-documentserver
Reading package lists… Done
Building a dependency tree... Done
Reading status information… Done         
The onlyoffice-documentserver package of the newest version (7.4.1-36) has already been installed. 0 packages
have been updated, 0 new packages have been installed, 0 packages have been marked for deletion, and 0 packages have not been updated.
Installed or removed not until the end of 1 packages.
After this operation, the amount of occupied disk space will increase by 0 B.
Do you want to continue? [D/n] y
The onlyoffice-documentserver package is being configured (7.4.1-36) …
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
Generating js caches, please wait...Done
Installing plugins, please wait...Done
dpkg: error when processing the onlyoffice-documentserver package (--configure):
a subprocess from the onlyoffice-documentserver package installed the post-install
ation script returned error code 1
Triggers for libc-bin (2.36-9+deb12u1) are processed …
Errors occurred while processing the following packets:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
saber716rus@saber716rus-BOM-WXX9 ~ [100]>

**Comment by saber716rus** [comment]
deleting a package also goes into this error

**Comment by igwyd** [comment]
Nala could break your dpkg or something else, I won't be able to help with this because not using nala. Try to install documentserver on the new clean updated Debian 12 to the guid from my previos [post](https://github.com/ONLYOFFICE/DocumentServer/issues/2384#issuecomment-1717636678) and you will see that there will be no problems with installation/uninstallation.

**Comment by saber716rus** [comment]
> I think errors in dpkg are due to installation via nala. On Debian 12 we often check the installation and there are no errors. Probably the simplest solution in your case is to reset the server, update the packages and install the documentserver by our guid https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx.

    the thing is that other packages are perfectly installed via nala. I don't need a clean install, I need to fix what your package messed up. who is to blame for this?

**Comment by WilhelmFreiheitsberg** [comment]
I have the same issue, I installed it via .deb file using apt. When I try to remove it or even purge I get the same error:

`➜  klaatu ~ sudo apt remove --purge onlyoffice-documentserver
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  postgresql-client postgresql-client-15 postgresql-client-common pwgen
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  onlyoffice-documentserver*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 1,604 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 281982 files and directories currently installed.)
Removing onlyoffice-documentserver (8.0.1-31) ...
Preparing for shutdown, it can take a lot of time, please wait...Done
Stopping documentserver services...
unlink: cannot unlink '/etc/nginx/conf.d/ds.conf': No such file or directory
dpkg: error processing package onlyoffice-documentserver (--remove):
 installed onlyoffice-documentserver package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 onlyoffice-documentserver
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)`

I am unable to either install or remove anything from my Debian 12 due to this recurrent issue. I don't have any idea why this messed up with dpkg haha help!

**Comment by WilhelmFreiheitsberg** [comment]
Ok, I think I found the issue, when it returns the error:

`installed onlyoffice-documentserver package pre-removal script subprocess returned error exit status 1`

I went to the dpkg script for pre-removal and commented the following lines of code:

`sudo vim /var/lib/dpkg/info/onlyoffice-documentserver.postrm`

![1-tentativa](https://github.com/ONLYOFFICE/DocumentServer/assets/128772261/4b780c9a-f421-421b-847e-1ec7c49a2323)

After it, I could perform both:

`sudo apt remove --purge onlyoffice-documentserver`

&

`sudo apt autoremove`

Now running the following command, don't return any error

`sudo apt-get update && sudo apt-get upgrade -y`

I hope I could help someone that might stumble upon the same issue.

**Comment by sanjaymehta** [comment]
> `unlink: cannot unlink '/etc/nginx/conf.d/ds.conf': No such file or directory`

I had the same issue but solved it by creating this file manually and then re-running apt.
