### ISSUE TITLE
Unable to open a document with onlyofffice in owncloud on an univention server after update in release 7.4.1.36 with connector 7.8.1

### ISSUE THREAD

**Issue by tvfsolutions** [ONLYOFFICE/DocumentServer#2388]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.1.36

### Expected Behavior

when i click on a office document in owncloud, i expect onlyoffice to open the document
i works fine in previous release

### Actual Behavior

when i click on an office document in owncloud, i have the loading windows with the purcentage progress number
but i have an error message
the application not allows my user to load the document

### Additional information

we had fixed it with these command in the docker of onlyoffice

on my end the following fixed it:
shell into the onlyoffice docker container by:
univention-app shell onlyoffice-ds
then edit /etc/onlyoffice/documentserver/local.json to include the following under:
{
“services”: {
“CoAuthoring”: {
"request-filtering-agent": {
"allowPrivateIPAddress": true,
"allowMetaIPAddress": false
},
nano is conveniently available in the onlyoffice-ds docker image.
for a good measure I restart docker container after exiting the shell
with docker restart <containerid>

**Comment by igwyd** [comment]
Hello @tvfsolutions, can you show the error in the onlyoffice-documentserver container log?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
