### ISSUE TITLE
the file cannot be accessed right now

### ISSUE THREAD

**Issue by saygoodbyebye** [ONLYOFFICE/DocumentServer#239]
![1](https://user-images.githubusercontent.com/19968269/35978890-d5f27b08-0d21-11e8-9d43-431d910e7bf5.png)
Has this error has been what is the problem?

**Comment by ShockwaveNN** [comment]
@saygoodbyebye I strongly recommend fill out issue pattern to recieve any help https://github.com/ONLYOFFICE/DocumentServer/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by ShockwaveNN** [comment]
Closing due no feedback
