### ISSUE TITLE
Chinese punctuation is garbled while calling editor.asc_AddText to add text in empty document

### ISSUE THREAD

**Issue by VikiLee** [ONLYOFFICE/DocumentServer#2391]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.3.3-49

### Expected Behavior

Chinese punctuation should not be garbled

### Actual Behavior

Chinese punctuation is garbled 

### Reproduction Steps

1、Call editor.asc_AddText('你好，很高兴认识你') to add text into document
2、Result is as below
[img](https://img1.imgtp.com/2023/09/19/A5dCJxmM.png)

**Comment by KirillovIlya** [comment]
Hello

You can't add text this way. Before adding any text to a document, we finding a set of fonts in which all the characters can be rendered. If some fonts are missing, we download them. This method is used to directly add text to a document, and does not perform these checks. Therefore, if there is no suitable font, the result will be like in your screenshot.

**Comment by VikiLee** [comment]
> Hello
> 
> You can't add text this way. Before adding any text to a document, we finding a set of fonts in which all the characters can be rendered. If some fonts are missing, we download them. This method is used to directly add text to a document, and does not perform these checks. Therefore, if there is no suitable font, the result will be like in your screenshot.

Hi

As I known, Fonts are downloaded before open document. By the way, when I type words in document, it works fine.

**Comment by Mannixhu** [comment]
> Hello
> 
> You can't add text this way. Before adding any text to a document, we finding a set of fonts in which all the characters can be rendered. If some fonts are missing, we download them. This method is used to directly add text to a document, and does not perform these checks. Therefore, if there is no suitable font, the result will be like in your screenshot.

how can i use API to triggle this process( finding a set of fonts in which all the characters can be rendered)
