### ISSUE TITLE
ConvertService PDF output incorrect

### ISSUE THREAD

**Issue by cetra3** [ONLYOFFICE/DocumentServer#24]
Using the ConvertService API appears to utilise a different method to generate PDFs than from the front end.

Using the standard demo document [demo.docx](https://github.com/ONLYOFFICE/DocumentServer/files/218342/demo.docx)

I've used two methods to generate a PDF.  

The first way is by using the Document Editor:
* Open the document in the Editor
* Click File icon
* Click `Download as..`
* Select PDF
* The output is as expected

The second way is via the ConvertService:
* Host the document somewhere accessible via URL
* Use the following URL `http://onlyoffice/ConvertService.ashx` with params:
   * **filetype**=docx
   * **outputtype**=pdf
   * **key**=1234
   * **url**=`accessible URL`

The second way renders the result as attached: [output.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/218340/output.pdf)

Using just the standard docker image.

**Comment by trofim24** [comment]
We are release Open Source Version 4.0.0 and fix this problem.
Now both methods work equally.
