### ISSUE TITLE
Paste as plain text

### ISSUE THREAD

**Issue by alexeyvolkoff** [ONLYOFFICE/DocumentServer#2404]
Editor lacks 'Paste as plain text' menu option. It makes it hard to keep the formatting clean when pasting text from other documents

**Comment by DenisDeeSign** [comment]
Moving this issue to DocumentServer repo, since the issue is not related to CommunityServer.

**Comment by alexeyvolkoff** [comment]
Yes. Is it already solved?

**Comment by ElenaMaaya** [comment]
Hello @alexeyvolkoff!
The actual keyboard shortcuts for “Insert text without style formatting” are Ctrl+⇧ Shift+V.
Thank you for reaching out and have a nice day!

PS This is fixed in DocumentServer and DesktopEditors v7.4.1.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
