### ISSUE TITLE
smooth/animated wheel scrolling

### ISSUE THREAD

**Issue by kde-yyds** [ONLYOFFICE/DocumentServer#2407]
i want to have animated scrolling in onlyoffice,just like that in ms office

**Comment by Rita-Bubnova** [comment]
Hello, @kde-yyds.
Could you write more about your enhancement?

**Comment by kde-yyds** [comment]
hello. i mean when scrolling with mouse wheel, move the content smoothly instead of jumping between two pixels directly.
like the one in the video


https://github.com/ONLYOFFICE/DocumentServer/assets/106876912/9cb51262-035c-4e69-a775-d80f7e1ec615


sorry for my poor english

**Comment by Rita-Bubnova** [comment]
Mayby, is this duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/736?

**Comment by kde-yyds** [comment]
yes,but now all onlyoffice scroll widgets need it,i think

**Comment by TatianaKirillova** [comment]
Hello, @kde-yyds Thanks for your request!
I can confirm - this is know bug, issue #17284 with your  proposal. Sorry for the long wait.
