### ISSUE TITLE
Wrong spaces after new designed bullets 

### ISSUE THREAD

**Issue by shu0406** [ONLYOFFICE/DocumentServer#2408]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.1.36

### Expected Behavior

New bullets picked out of the Symbol-list should be treated like "normal" bullets.
![grafik](https://github.com/ONLYOFFICE/DocumentServer/assets/76654412/71343a5e-ad2e-4d4f-97c1-fbba287c6f0f)
![grafik](https://github.com/ONLYOFFICE/DocumentServer/assets/76654412/213ec150-f6f9-445d-8517-58e06cd5e187)

### Actual Behavior

If I add new designed bullets there is no space after them. So when I start a new line it looks wrong / not clean. 
![grafik](https://github.com/ONLYOFFICE/DocumentServer/assets/76654412/9eebf04c-1f0d-4ca0-b7ee-75617276cfeb)

**Comment by matveevms** [comment]
Hi, @shu0406 
Please note that the problem may be related to the font you are using (aakar), if the default marker is different from the new marker. Could you provide this font to accurately replicate this scenario? And please indicate whether this is the font used when adding the default marker.

**Comment by shu0406** [comment]
Hi, 
I can't reproduce it myself! I works in Desktop Editors (linux + win10) and on our onlyloffice docs server solution now, all of them with version 7.4.1.
Thanks anyways!
![grafik](https://github.com/ONLYOFFICE/DocumentServer/assets/76654412/50dd4ef9-ada0-466f-8c1e-56a28cfd5a41)
![grafik](https://github.com/ONLYOFFICE/DocumentServer/assets/76654412/f158f235-2e6e-4674-88d8-ecde95428a90)
