### ISSUE TITLE
The font you are using does not have characters corresponding to this encoding is displayed empty

### ISSUE THREAD

**Issue by railwayc** [ONLYOFFICE/DocumentServer#2411]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1

### Expected Behavior

it should displayed as other available fonts like microsoft word
![图片](https://github.com/ONLYOFFICE/DocumentServer/assets/8802233/64f5be4c-a887-454d-b5d2-8b8c709c5d07)
![图片](https://github.com/ONLYOFFICE/DocumentServer/assets/8802233/8f800f5a-46e0-4aab-94b3-cdc525691896)

### Actual Behavior

the word 堃 is displayed empty space in onlyoffice docker when using font "方正小标宋简体.ttf" 

### Reproduction Steps

1. upload font to onlyoffice && install font in windows
[方正小标宋简体.zip](https://github.com/ONLYOFFICE/DocumentServer/files/12839665/default.zip)

2. open test-font.docx in word and onlyoffice for diff 
[test-font.docx](https://github.com/ONLYOFFICE/DocumentServer/files/12839659/test-font.docx)

**Comment by railwayc** [comment]
onlyoffice docker displays 堃 like（font Arial and 方正小标宋简体  not support，but 仿宋 support ）
![图片](https://github.com/ONLYOFFICE/DocumentServer/assets/8802233/2a6815c7-811f-4690-9e15-62051bfcf2a3)
![图片](https://github.com/ONLYOFFICE/DocumentServer/assets/8802233/056b235f-4516-474f-a107-11ae5ec95b05)

**Comment by igwyd** [comment]
Hello @railwayc, i follow your Reproduction Steps on the onlyoffice/documentserver:7.4.1 (docker distribution) and don't seen any empty space instead of 堃 when use your font - 方正小标宋简体 or Arial. Can you provide more information how you did it?
![cn](https://github.com/ONLYOFFICE/DocumentServer/assets/67538082/55ee6645-90d1-45d8-9aff-7471d855cf09)

**Comment by railwayc** [comment]
thanks for your reply!
i check it again, find that, when remove all custom fonts but only use 方正小标宋简体.ttf ,it works fine like the result you have post.
it is cause by another font(宋体.ttf), which can search that 堃 word，but display none
![图片](https://github.com/ONLYOFFICE/DocumentServer/assets/8802233/c7799849-ff33-4efb-94b5-1f27dc86e38d)
[宋体.zip](https://github.com/ONLYOFFICE/DocumentServer/files/12869041/default.zip)

it is all okay if i remove it.

thanks!
