### ISSUE TITLE
How do I indent the first line of a paragraph by two characters

### ISSUE THREAD

**Issue by YanaDH** [ONLYOFFICE/DocumentServer#2415]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package), Linux (RPM package), Docker

### Version information

7.3.3

### Expected Behavior

Indent the first line of a paragraph by two characters

### Actual Behavior

The first line of a paragraph cannot be indented by two characters, only by a fixed unit such as two centimeters

**Comment by Leroy-X** [comment]
Hi, I have the same problem, how to solve it?
Thanks.

**Comment by Rita-Bubnova** [comment]
@YanaDH, DocumentServer v7.5.1 is released. Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
> DocumentServer v7.5.1 is released. Please state is this problem still actual for you?

DesktopEditors v7.5.1 is released also.
