### ISSUE TITLE
用的onlyoffice社区版的在线编辑功能打开文档有点慢

### ISSUE THREAD

**Issue by cv-msan** [ONLYOFFICE/DocumentServer#2417]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

我有一个83kb左右的word文档docx格式的，当我去调用请求这个文档在线编辑的时候会在浏览器打开onlyoffice的在线编辑页面，打开这个页面的时候会显示文档正在加载中这个过程稍微有点漫长，大概10秒左右的样子才可以把这个文档加载出来，有的时候会更久，onlyoffice社区版我是安装在了我的windows电脑上的，系统是win11系统，请问是需要调整什么参数可以让他加载的速度更快一点吗？

**Comment by cv-msan** [comment]
我看到控制台下载了169MB的资源，这个地方能不能通过参数调节？
![1697095456571](https://github.com/ONLYOFFICE/DocumentServer/assets/76542419/5d6bf515-97b0-43b5-89d7-7462c6855b4c)

**Comment by Rita-Bubnova** [comment]
Hello, @cv-msan.
Please, use English to describe the  issue.

**Comment by cv-msan** [comment]
I have a word document of about 83kb in docx format. When I call to request online editing of this document, only the online editing page of Office will be opened in the browser. When this page is opened, it will be displayed that the document is loading. This process is a bit troublesome. , it takes about 10 seconds to load this document, sometimes it takes longer. I only have the office community version installed on my windows computer. The system is win11. What parameters need to be adjusted to allow it to be loaded? Does it load faster?

**Comment by cv-msan** [comment]
I saw that the console downloaded 169MB of resources. This location cannot be adjusted through parameters?
https://user-images.githubusercontent.com/76542419/274515818-5d6bf515-97b0-43b5-89d7-7462c6855b4c.jpg

**Comment by igwyd** [comment]
Hello @cv-msan, Unfortunately the first opening of a document will take a long time because the fonts are downloading from the server and Chinese fonts are large. I can only give advice, remove unnecessary fonts from the server.

**Comment by cv-msan** [comment]
Then may I ask in which directory this font file is located?

**Comment by igwyd** [comment]
They are here ```C:\Windows\Fonts```. We have manual for the adding fonts https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-windows.aspx, in your case - remove unnecessary fonts from the server and run ```documentserver-generate-allfonts.bat```

**Comment by Johnson1949** [comment]
@igwyd 
伊格维德先生，您好，我也很喜欢咱们的Only Office软件，我不喜欢WPS，您这款软件好用是好用，就是我下载本地windows版本Excle的确实削微有点卡，希望咱们软件越来越好

**Comment by igwyd** [comment]
Hello @Johnson1949, im glad you like it) Please describe your behavior more detailed in a separate issue and we will try to help.
PS please write in english here, so that other users can also find and solve a similar issue.
