### ISSUE TITLE
Cannot open local files with version 7.4

### ISSUE THREAD

**Issue by davide-aldegheri** [ONLYOFFICE/DocumentServer#2418]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.4.1

### Expected Behavior

Configuring a template with a locally exposed file via IIS can open it correctly

### Actual Behavior

I'm receiving an error of Download failed with error code -4

### Reproduction Steps

I have a template configured like this
```
<!DOCTYPE html>
<html style="height: 100%;">
    <head>
        <title>ONLYOFFICE Api Documentation</title>
    </head>
    <body style="height: 100%; margin: 0;">
        <div id="placeholder" style="height: 100%"></div>
        <script type="text/javascript" src="http://localhost:8082/web-apps/apps/api/documents/api.js"></script>
        <script type="text/javascript">
	var onDocumentStateChange = function (event) {
            console.log("OnlyOffice Loaded");
        };
        var onError = function (event){
            console.log("error "+event.data.errorCode + ", desc: "+event.data.errorDescription);
        };

        window.docEditor = new DocsAPI.DocEditor("placeholder",
        {
        "document": {
            "fileType": "pptx",
            "key": "4f7f496e5f3e2e8866572191e544424a",
            "title": "my-file.pptx",
            "url": "http://localhost/local/docs/office/my-file.pptx",
            "permissions": {
                "comment": false,
                "download": false,
                "edit": false,
                "print": false,
                "review": false
            },
        },
        "documentType": "slide",
        "editorConfig": {
            "customization": {
                "autosave": false,
                "chat": false,
                "commentAuthorOnly": false,
                "compactToolbar": false,
                "zoom": "100"
	    },
        "mode": "view",
	    "lang": "en-US"
        },"events": {
       	 "onDocumentStateChange": onDocumentStateChange,
         "onError": onError
   	 },

        "type": "mobile",
        "height": "100%",
        "width": "100%"
        });
        </script>
    </body>
</html>

```

### Additional information

The file is exposed via IIS as is the browsing of the folders directing to it, the file is on my machine and I can reach it using that same path in the browser.
I was able to open it using OO v7.0.x

Am I missing something?

Thanks for your help

**Comment by davide-aldegheri** [comment]
Found the issue, I had to configure an entry inside default.json like so
```
"request-filtering-agent" : {
				"allowPrivateIPAddress": true,
				"allowMetaIPAddress": false
			}
```

**Comment by viscous-coder** [comment]
i used it

> Found the issue, I had to configure an entry inside default.json like so
> 
> ```
> "request-filtering-agent" : {
> 				"allowPrivateIPAddress": true,
> 				"allowMetaIPAddress": false
> 			}
> ```

i used this but still not worked

**Comment by viscous-coder** [comment]
@davide-aldegheri would you please help me to resolve this error
