### ISSUE TITLE
ONLYOFFICE PPT editor stuck with simple Draw schema

### ISSUE THREAD

**Issue by dcaravana** [ONLYOFFICE/DocumentServer#242]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
ONLYOFFICE Desktop (and web) start loading the remains stuck at a specific percentage (in this case 45%).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the file attached.
[ONLYOFFICE Draw BUG.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/1745735/ONLYOFFICE.Draw.BUG.pptx)

Note: the file has been edited with LibreOffice latest version taking the schema from another PPTX file originally created with Microsoft Office (which I don't have available). The original file cannot be opened by ONLYOFFICE as well. Apple Keynote can open it but beachballs as soon as you click on any part of the schema. 

**What is the expected behavior?**
Open the file as usual.

**Did this work in previous versions of DocumentServer?**
N/A

**DocumentServer version:**
The one included in ONLYOFFICE Desktop 4.8.8.

**Operating System:**
MacOS 10.13.3.

**Browser version:**
N/A for Desktop (or Chrome 64.0.3282.167).

**Comment by flaminestone** [comment]
Thanks for issue. It is realy bug, we will try to fix it in future releases

**Comment by dcaravana** [comment]
You're welcome.

Since being stuck really hits negatively the entire app (which in contrast is really great IMO), it would be good to fix the "being stuck" part of this bug immediately (maybe just giving a proper error and visualising a placeholder instead of the drawing), then fix it properly in a future release.

**Comment by ShockwaveNN** [comment]
Issue is resolved and not reproduce on `onlyoffice-documentserver` 5.1.3
