### ISSUE TITLE
 ONLYOFFICE cannot be reached. Please contact the administrator

### ISSUE THREAD

**Issue by luke6464** [ONLYOFFICE/DocumentServer#2424]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

last version

### Expected Behavior

What did you expect to happen?
Normal Work
Did this work in previous versions of DocumentServer?
No!

### Actual Behavior

Hi, after installing the OnlyOffice App and Document Server in NextCloud, when I try to open a document or create a new one the following error appears:

ONLYOFFICE cannot be reached. Please contact the administrator

from many searches on the internet it seems that this problem is very common and I don't know how to deal with it and analyze it.
Can you help me?
Thank you

**Comment by kovacs-andras** [comment]
Where does OnlyOffice listen on your server? Can you open the welcome page of it?

**Comment by luke6464** [comment]
The correctly configured address of OnlyOffice is:
https://192.168.3.131:8443/index.php/apps/documentserver_community/
but the Welcome page is not reachable...
see attachment
![screenshot_20231020_120147](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/bb689811-a261-4485-a523-d69921b8c12f)
![screenshot_20231020_120247](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/1ea56852-1c25-4c05-87ce-20a868658794)

**Comment by igwyd** [comment]
Hello @luke6464, sorry for the late reply. Which app do you using for integration? This https://apps.nextcloud.com/apps/documentserver_community ?

**Comment by luke6464** [comment]
> Hello @luke6464, sorry for the late reply. Which app do you using for integration? This https://apps.nextcloud.com/apps/documentserver_community ?

Yess, i use "documentserver_community".
Thank you

**Comment by igwyd** [comment]
This is Nextcloud inttegration and they develop it wuthout onlyoffice team. For issues with this  application you should contact the  Nextcloud. 
Our app is here https://apps.nextcloud.com/apps/onlyoffice and we support it.

**Comment by luke6464** [comment]
HI,
I installed the Dcoument Server Community app you suggested and there is yet another connection error on the Nextcloud Onlyoffice App as per the attached screenshots...
How do I solve it?
Thank you
![screenshot_20231120_223254](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/afa9692a-5203-41e1-a6c6-de6527b2b7dc)
![screenshot_20231120_223506](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/3c0d0566-0bd1-4913-9cf8-665ddeeec4cd)

**Comment by igwyd** [comment]
I see that you have some SSL certificate error. Try starting from scratch without HTTPS first  and make sure your deployment works, and then add certs. We have guide for the Nexcloud integration [here](https://helpcenter.onlyoffice.com/integration/gettingstarted-nextcloud.aspx) and docker-compose example [here](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud)(included the example with SSL on the feature/ssl branch).

**Comment by luke6464** [comment]
Hi, 
I'm actually trying to get it to work for now only locally without certificates and without SSL but it seems like there's no way to do it? ... Why is it not possible to simply make it work only with http locally? ...
Attached are all the further tests done to make it work!
Thank you
![screenshot_20231121_120228](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/aee91a2d-9971-4a67-b77c-dc7c737d37fb)
![screenshot_20231121_120149](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/e87c2fad-6e67-4f82-ae5d-121353a3a0a7)

**Comment by igwyd** [comment]
1. Your new error show mixed conent, this because one of your apps is using https. 
2. JWT != https, no need disable it. It’s better to enable it if you are using local deployment, otherwise you will get an error with the private ip address.
3. I already showed you that we have an example of deploying onlyoffice and nexcloud using docker-compose https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/tree/master, try to deploy it and apply to your deployment.

**Comment by luke6464** [comment]
> 1. Your new error show mixed conent, this because one of your apps is using https.
> 2. JWT != https, no need disable it. It’s better to enable it if you are using local deployment, otherwise you will get an error with the private ip address.
> 3. I already showed you that we have an example of deploying onlyoffice and nexcloud using docker-compose https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/tree/master, try to deploy it and apply to your deployment.

HI
I saw the docker-compose that you indicated in the link but I understand that it makes me install another NextCloud (see screenshot)...
I need OnlyOffice to work on my existing NextCloud installation, not on a new one!
How can I solve the connection error problem on my NextCloud installation? ...
Thank you
![screenshot_20231122_143845](https://github.com/ONLYOFFICE/DocumentServer/assets/3793119/aff982cc-b586-49db-a25f-c5480810d619)
