### ISSUE TITLE
Part of the content goes missing when the username includes an ampersand (&) upon download.

### ISSUE THREAD

**Issue by MannixHu** [ONLYOFFICE/DocumentServer#2429]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

v7.4.1

### Expected Behavior

The content of the downloaded file remains the same as before the download

### Actual Behavior

different
<img width="1853" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/16033328/128df211-3ae1-4475-9cfc-771fd34c3fda">

### Reproduction Steps

1. open [before download.docx](https://github.com/ONLYOFFICE/DocumentServer/files/13040432/1.username.contain.dowmload.disappear.some.content.docx)
2. [file]-[Download as]-[docx]
3. open the downloaded file
[after download.docx](https://github.com/ONLYOFFICE/DocumentServer/files/13040433/2.username.contain.dowmload.disappear.some.content.1.docx)

**Comment by Mannixhu** [comment]
Upon comparing the XML content of two DOCX files, it was found that the `&amp;` in the author field was converted to `&`
<img width="1875" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/16033328/9399cfa7-78c8-46ba-8797-4ace6e6bd7ce">

**Comment by Mannixhu** [comment]
@Rita-Bubnova @XDmitryK  I'm just following up on the issue posted about two months ago, and would appreciate any update you might have.

**Comment by XDmitryK** [comment]
@Mannixhu Hi
Sorry for the long response, I checked your case on 7.5.1-23 and the problems do not recur.
Can you update your version and check it again?

**Comment by Mannixhu** [comment]
> @Mannixhu Hi Sorry for the long response, I checked your case on 7.5.1-23 and the problems do not recur. Can you update your version and check it again?

the old data still missing , 
just open the [after download.docx](https://github.com/ONLYOFFICE/DocumentServer/files/13040433/2.username.contain.dowmload.disappear.some.content.1.docx) to reproduce  (v7.5.1)
Could you please consider adding support for legacy corrupted data in future updates?

**Comment by XDmitryK** [comment]
@Mannixhu Hi
I confirm this is bug, issue #66651

**Comment by XDmitryK** [comment]
The bug is fixed in version 8.1.1
[Commit ](https://github.com/ONLYOFFICE/core/commit/f973a0a952abc155a651f7dcc7e1068bfff7ef34)

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
