### ISSUE TITLE
display problem - 显示问题

### ISSUE THREAD

**Issue by ryanzhaorx** [ONLYOFFICE/DocumentServer#2430]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.4.1

### Expected Behavior

Normal display text
正常显示文字

### Actual Behavior

The error display is "??"

错误的显示为 "??"

### Reproduction Steps

"车辆" cannot be displayed properly in Excel Mode
Excel模式中 "车辆" 无法正常显示

### Additional information

<img width="1069" alt="截屏2023-10-10 22 29 55" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/103013573/a8ad5295-b200-476f-b030-3600b6347fbf">

**Comment by TatianaKirillova** [comment]
@ryanzhaorx I'm happy to announce that the issue has been fixed and is now included in version 8.1.0. Don't miss updates)

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
