### ISSUE TITLE
The simplified Chinese translation of view label is incorrect.Only excel is correct(excel has a textual error)

### ISSUE THREAD

**Issue by zxuanhong** [ONLYOFFICE/DocumentServer#2434]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.0

### Expected Behavior

<img width="652" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/3daf042b-81b8-47d4-aa06-7748f3e070c9">
<img width="522" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/76ebfc8f-02f5-4308-9794-98fbbaa005de">
<img width="953" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/1a17e65f-98fd-477b-be99-811c8ad87db2">

### Actual Behavior

<img width="681" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/42b5e68a-696e-4c0c-8723-3658458e48f2">
<img width="461" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/f6123c86-a2b8-4ada-afa3-dc225a4e20d5">

**Comment by ElenaMaaya** [comment]
Hello @zxuanhong!
Thank you for report!
I can confirm that the problem exists. I created ticket 64814  in our issue tracker with your issue.

**Comment by zxuanhong** [comment]
@ElenaMaaya Version 7.5.1 has been resolved. Issue I will close

**Comment by ElenaMaaya** [comment]
Thank you, we have fixed this problem in the latest release version.
