### ISSUE TITLE
Web Document Builder API debug

### ISSUE THREAD

**Issue by unam3** [ONLYOFFICE/DocumentServer#2441]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

that was available at 20 Oct '23 from [here](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx)

### Expected Behavior

Response without error, but with link to created document.

### Actual Behavior

```
normaluseracc@debian:~$ curl -i -X POST -d '{"async": true,"url": "http://192.168.159.131/test.docbuilder"}' http://192.168.159.131/docbuilder;echo
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 20 Oct 2023 05:40:38 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 42
Connection: keep-alive
Vary: Accept-Encoding
ETag: W/"2a-cK53SbykC0IhGZN1KRsDuMNDPt8"

{"key":"bld_331a38c617663964","end":false}
normaluseracc@debian:~$ curl -i -X POST -d '{"async": true,"key": "bld_331a38c617663964"}' http://192.168.159.131/docbuilder
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 20 Oct 2023 05:41:09 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 12
Connection: keep-alive
ETag: W/"c-5lC/GNXd6iIppom73lLvBY0S2ZI"

{"error":-4}
```

### Reproduction Steps

1. Install ONLYOFFICE Docs Community Edition as [stated](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx).
2. add .docbuilder file with content to proper location with content:
```
builder.CreateFile("docx");                 // create a text document file in the .docx format with ONLYOFFICE Document Builder
var oDocument = Api.GetDocument();          // create a new 'oDocument' variable and get the created text document contents
var oParagraph;                             // create the 'oParagraph' variable
oParagraph = Api.CreateParagraph();         // create a new paragraph
oParagraph.SetJc("center");                 // set the paragraph justification to center the text
oParagraph.AddText("Center");               // add a text containing a single 'Center' word to the paragraph
oDocument.Push(oParagraph);                 // push the created paragraph contents with the 'Center' word to the document
builder.SaveFile("docx", "example.docx");   // save the resulting text document as a file in the .docx format with the 'example.docx' name
builder.CloseFile();                        // close the text document file and finish work with ONLYOFFICE Document Builder
```
3. Send 2 requests to web document builder service:
`curl -i -X POST -d '{"async": true,"url": "http://officeserver/test.docbuilder"}' http://officeserver/docbuilder`
`curl -i -X POST -d '{"async": true,"key": "<key form previous request's response>"}' http://officeserver/docbuilder`

### Additional information

Original unansweverd forum message: https://forum.onlyoffice.com/t/web-document-builder-api-debug/6645 .

**Comment by l8556** [comment]
Hi @unam3 !
Based on the response from the forum: https://forum.onlyoffice.com/t/web-document-builder-api-debug/6645
```
-4 Error while downloading the document file to be generated.
```

Make sure that the file is available at the link passed in the request.

Example of a request to the Web Document Builder API using curl

```
curl -i -X POST -d '{"url": "https://example.com/url-to-example-script.docbuilder"}' https://documentserver/docbuilder
```

Most common error codes and their description are listed on the bottom of [Web Document Builder API](https://api.onlyoffice.com/editors/documentbuilderapi) page that you've already provided.

**Comment by unam3** [comment]
> Hi @unam3 ! Based on the response from the forum: https://forum.onlyoffice.com/t/web-document-builder-api-debug/6645
> 
> ```
> -4 Error while downloading the document file to be generated.
> ```

Thanks for your and forum mod response, but I sure can read links before posting the question on the forum and here,


> Make sure that the file is available at the link passed in the request.

How can I do that exaclty?

**Comment by l8556** [comment]
Check if the `.docbuilder` script file can be downloaded from the link passed in the `url` parameter from the post request

`{"url": "https://example.com/url-to-example-script.docbuilder"}`

**Comment by unam3** [comment]
> Check if the `.docbuilder` script file can be downloaded from the link passed in the `url` parameter from the post request
> 
> `{"url": "https://example.com/url-to-example-script.docbuilder"}`

It does not:

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/6318039/5a36d4d6-a7d3-42bc-b2a0-ca77819199da)

**Comment by unam3** [comment]
Ok. Seems like I've misread docs: about that `url` parameter make assumption about correct location for .docbuilder-file ( `/var/lib/onlyoffice/documentserver/App_Data/docbuilder/` ).

Anyway, it is not stated where should should I put .docbuilder-file to make it available to [document storage service](https://api.onlyoffice.com/editors/documentbuilderapi#:~:text=script.docbuilder%22%0A%7D-,Where%20example.com%20is%20the%20name%20of%20the%20server%20where%20document%20storage%20service%20are%20installed.%20See%20the%20How%20it%20works%20section%20to%20find%20out%20more%20on%20Document%20Server%20service%20client%2Dserver%20interactions.,-Response%20format).

If it's the [storageFolderName](https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#services-CoAuthoring-server-savetimeoutdelay:~:text=storageFolderName%22%3A%20%22files%22%2C) - where I can find it on my machine?

**Comment by l8556** [comment]
To work with the Web Document Builder API
You need to share the `.docbuilder` file, 
for example by uploading it to the s3 cloud, or using `nginx`, 
or any other option with direct access to the `.docbuilder` file via the link

**Comment by unam3** [comment]
> You need to share the `.docbuilder` file… using `nginx`, or any other option with direct access to the `.docbuilder` file via the link.

Can you point at any examples of those configurations?

**Comment by unam3** [comment]
Well. I've retried and raw pastebin seems to work:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/6318039/820721c9-c1d5-4d7e-be83-c419deae481d)

Anyway, nginx config: howto?

**Comment by l8556** [comment]
You can read more about nginx [here](https://nginx.org/en/docs/beginners_guide.html#:~:text=considered%20a%20comment.-,Serving%20Static%20Content,-An%20important%20web) for example

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
