### ISSUE TITLE
Inset time into spreadsheets sometimes is a day ahead

### ISSUE THREAD

**Issue by ranger135xp** [ONLYOFFICE/DocumentServer#2446]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36

### Expected Behavior

Expected when hitting hotkey CTRL+; that the date inserted matches the system clock (today's date).

### Actual Behavior

Not sure what times of the day this begins, but usually in the evening/night hours (8PM+) the date insert will be 1 day ahead.
My timezone is Eastern so typically UTC -5.
Insert time (CTRL+SHIFt+;) inserts the correct time, so it's odd that the date insert would be incorrect.

### Reproduction Steps

1. Open a new spreadsheet
2. Insert date with CTRL+; to insert date
3. Try past 8pm EST/DST

### Additional information

N/A

**Comment by VladimirProkofiev52** [comment]
Hello! @ranger135xp 
Great news! We've resolved the issue you reported. The fix will be included in the next update of our editor.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
