### ISSUE TITLE
Conditional Formatting show and understands formulas only in English.

### ISSUE THREAD

**Issue by mobius217** [ONLYOFFICE/DocumentServer#2447]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.5.0.127 (x64 exe)

### Expected Behavior

Conditional Formatting should understand formulas depending on the language of the document, as in any other places in the table.

### Actual Behavior

Now I can only enter formulas in English in Conditional Formatting. Moreover, the formulas are displayed in English, even if they are entered into Microsoft Excel in the document language.

**Comment by rsnegirev** [comment]
@mobius217 the problem was fixed in this commit https://github.com/ONLYOFFICE/sdkjs/commit/7720ef1e79f37e6fc6ddfa0c00ed61967aba0a6a

It will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
