### ISSUE TITLE
*feature* (presentation) implement slide number

### ISSUE THREAD

**Issue by RomaricMourgues** [ONLYOFFICE/DocumentServer#245]
As said in title, a good feature would be to implement slide number in presentation editor, even if I'm sure you're overbooked :)

**Comment by ShockwaveNN** [comment]
Thanks for this idead, we consider implementing it
Issue 37117 in our private issue tracker

**Comment by trofim24** [comment]
We released this feature in [version 5.4.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#540)
