### ISSUE TITLE
Unable to save documents. x2t: stderr:TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by anoadragon453** [ONLYOFFICE/DocumentServer#2450]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.1

### Expected Behavior

I have OnlyOffice installed on one server, with my Nextcloud on a different server, running the ONLYOFFICE Nextcloud plugin v8.2.4.

After editing a document, I'd expect those changes would be saved back to my Nextcloud storage, but instead the document is never saved. I'm using local storage on Nextcloud.

I've installed via NixOS, which pulls the .deb and uses [this script](https://github.com/NixOS/nixpkgs/blob/ca012a02bf8327be9e488546faecae5e05d7d749/pkgs/servers/onlyoffice-documentserver/default.nix#L33) to install OnlyOffice DocumentServer.

### Actual Behavior

Any changes to a document, spreadsheet or presentation file are not saving. Making changes to a file results in an "All changes saved" message, but in Nextcloud's UI, the document does not show as being edited recently.

Closing and opening the document shows the changes, however if I restart OnlyOffice DocumentServer, the changes are lost. Suggesting that changes are only being cached in the DocumentServer, but not being saved back to disk.

The following are errors logged by the OnlyOffice Converter service:

```
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: [2023-10-29T14:22:00.753] [ERROR] [localhost] [768719820] [ochpnw2yfmql_andrew7] nodeJS - error spawnAsync Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t /tmp/ASC_CONVERT123929-bswhy7.4m33l/params.xml exited with signal: SIGILL
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:41:23)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at Object.onceWrapper (events.js:520:26)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at ChildProcess.emit (events.js:400:28)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at maybeClose (internal/child_process.js:1088:16)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     ...
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at spawnProcess (/snapshot/server/build/server/FileConverter/sources/converter.js)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at spawnProcess.next (<anonymous>)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at ExecuteTask.next (<anonymous>)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at /snapshot/server/build/server/FileConverter/sources/converter.js
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at Generator.next (<anonymous>)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: [2023-10-29T14:22:00.755] [ERROR] [localhost] [768719820] [ochpnw2yfmql_andrew7] nodeJS - stdout:
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: [2023-10-29T14:22:00.755] [ERROR] [localhost] [768719820] [ochpnw2yfmql_andrew7] nodeJS - stderr:TypeError: Cannot read property 'length' of undefined
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at Object.a.AscCommon.OT.decode.a.AscCommon.OT.decode (<anonymous>:12188:172)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at e (<anonymous>:12105:526)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at n.iu (<anonymous>:12125:377)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at Object.iu (<anonymous>:12129:488)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at e.uxd (<anonymous>:10758:149)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at e.uxd (<anonymous>:11052:199)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at <anonymous>:10702:351
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at fa (<anonymous>:10029:379)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at Object.a.AscCommon.Nwh (<anonymous>:10208:403)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]:     at e.RN (<anonymous>:10702:314)
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: #
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: # Fatal error in v8::ToLocalChecked
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: # Empty MaybeLocal.
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: #
Oct 29 14:22:00 plonkie onlyoffice-wrapper[1228]: [2023-10-29T14:22:00.755] [ERROR] [localhost] [768719820] [ochpnw2yfmql_andrew7] nodeJS - ExitCode (code=0;signal=SIGILL;error:-80
```

It appears that the problem is due to `x2t` running into an error when attempting to convert the `Editor.bin` file to a `.xlsx` file. I captured the files from `/tmp` that appear momentarily during the conversion process:

[x2t_data.zip](https://github.com/ONLYOFFICE/DocumentServer/files/13198340/x2t_data.zip)

### Reproduction Steps

1. Create a document via Nextcloud's interface.
2. Edit the document.
3. See that OnlyOffice saves "All changes saved"
4. The document is never updated in my Nextcloud storage.

**Comment by anoadragon453** [comment]
I tried running `x2t` manually on the files in the zip file I uploaded, and the conversion ran fine. Is there any way I can add more logging to my OnlyOffice Converter config to perhaps get a better understanding of the issue?

**Comment by igwyd** [comment]
Hello @anoadragon453, unfortunately we don't support NixOS. There are a lot of Linux distributions and we simply don’t have enough resources to support them all. Try to use DEB current Ubuntu or Debian, we are testing it every release.

**Comment by anoadragon453** [comment]
That's fine @igwyd, thanks for the response!

**Comment by Emily3403** [comment]
@anoadragon453 Have you found a workaround for this? I'm having the same issue with .xlsx and .ods files and version 7.5.0

**Comment by anoadragon453** [comment]
Not yet I'm afraid. I still have this issue, and am currently just not making use of my deployment...

**Comment by Emily3403** [comment]
Thanks for the response. I've decided to go with the docker image and not use NixOS options as they apparently don't work
