### ISSUE TITLE
why "You are trying to perform an action you do not have rights for" when download or print?

### ISSUE THREAD

**Issue by congge27** [ONLYOFFICE/DocumentServer#2451]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1.36

### Expected Behavior

Document Server version:7.4.1.36
Document Server docker
OS:centos 7.9
Browser version: edge

1.I integrated OnlyOffice into my own software
2.Now I can edit it and save document

### Actual Behavior

When I want to download document via “download as” button, it says “You are trying to perform an action you do not have rights for.”

### Reproduction Steps

Document Server version:7.4.1.36
Document Server docker
OS:centos 7.9
Browser version: edge

1.I integrated OnlyOffice into my own software
2.Now I can edit it and save document
3.When I want to download document via “download as” button, it says “You are trying to perform an action you do not have rights for.”

But when I use same function in OnlyOffice example , it works correctly.

**Comment by geod-dev** [comment]
Hello! I have the same problem, have you found a solution?

**Comment by l8556** [comment]
Hello @congge27
It was not possible to reproduce this issue.

Try to update the version of the document server to a current version

If the problem recurs, please describe the steps to reproduce in more detail.

If possible, please attach a simplified example of your application to reproduce the issue.

Tested on DS version 8.0.1.31

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
