### ISSUE TITLE
docker container not accepting https connections

### ISSUE THREAD

**Issue by tspr** [ONLYOFFICE/DocumentServer#2454]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

latest (2023-nov-01)

### Expected Behavior

I start the docker container like in the manual attaching Port 443:

docker run -i -t -d -p 443:443 --restart=always -e JWT_SECRET=**redacted** onlyoffice/documentserver

I should be able to connect to the machine through  https://ipaddress.redacted/

### Actual Behavior

I actually get ERR_CONNECTION_REFUSED in the webbrowser for https and http connections.

docker has attached port 443:

85ab95a0945b   onlyoffice/documentserver   "/app/ds/run-documen…"   2 minutes ago   Up 2 minutes                   80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   relaxed_haslett

but after getting shell in container:

root@85ab95a0945b:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      649/nginx: master p 
tcp6       0      0 :::8126                 :::*                    LISTEN      -                   
tcp6       0      0 :::8000                 :::*                    LISTEN      -                   
tcp6       0      0 :::5672                 :::*                    LISTEN      -                   
tcp6       0      0 :::4369                 :::*                    LISTEN      -                   
tcp6       0      0 :::80                   :::*                    LISTEN      649/nginx: master p 
udp        0      0 0.0.0.0:8125            0.0.0.0:*                           -                   

nginx dosn't attach to port 443

### Reproduction Steps

docker run -i -t -d -p 443:443 --restart=always -e JWT_SECRET=**redacted** onlyoffice/documentserver

### Additional information

I follow the manual from
https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx

**Comment by tspr** [comment]
So, i figured one of the problematic things:

The setup-script is extremely picky. If you supply certificates, it needs to have them named onlyoffice.crt and onlyffice.key.

If that is given, things should work, if one links a Data directory into the container, and that neds to contain a /certs directory with "Onlyoffice.crt" and key files.

**Comment by igwyd** [comment]
Hello @tspr, that's right, this is written in the documentation link you provided:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/67538082/7b59f7c5-1efe-4fe1-8adb-9f79b990d651)

After restart docker container, thats all.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
