### ISSUE TITLE
Custom page size not saved when the document is closed

### ISSUE THREAD

**Issue by Bakaba** [ONLYOFFICE/DocumentServer#2456]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36

### Expected Behavior

When I change the page size to a custom size (let's say 118.9cm x 118.9cm, maximum size available) and I save the document, quit and reopen it again, I want my document to be at the same custom size I put it.

### Actual Behavior

The size got edited to 55.88cm x 55.88cm.

### Reproduction Steps

1/ Create a new Document.
2/ In "Layout -> Size -> Custom page size", set the size to: "preset: custom, width: 118.9cm, height: 118.9cm(maximum number possible)"
3/ Save and close the document.
4/ Open it again and check the page size.

### Additional information

IMPORTANT: It happens on an .ODT file but not in a DOCX file.

Since there's no pageless mode yet, I'm trying to free as much space as I can. Thus setting it in the maximum value. But the value got halved for some reason.
Edit: This issue seems to happen for table size too. see my comment below.

**Comment by Bakaba** [comment]
Thank you! 

I thought it was only one issue since it have something to do with custom values itself. I'll create a separate issue.

**Comment by ElenaMaaya** [comment]
Hello @Bakaba! I have a good news! This issue will be fixed in the next release. Keep for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by Maaayank** [comment]
Hi, I am facing this issue for .ODS file as well
Version : 8.0.0

I reproduced this issue on personal.onlyoffice.com . On saving and reopening .ods file the page size goes back to default .A4 size.

**Comment by Maaayank** [comment]
Hi, I am facing this issue for .ODS file as well
Version : 8.0.0

I reproduced this issue on personal.onlyoffice.com . On saving and reopening .ods file the page size goes back to default .A4 size.

**Comment by Rita-Bubnova** [comment]
@Maaayank Please, create an new issue and fill in all the fields of the form completely.
