### ISSUE TITLE
Theme font parsing unsuccessful

### ISSUE THREAD

**Issue by sunbaichi** [ONLYOFFICE/DocumentServer#2457]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Docker

### Version information

7.5

### Expected Behavior

If I have set the theme font, I would like the font displayed in OnlyOffice to be the same as the theme font
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/16381995/76a38c49-8de5-4490-88f3-1bf71a36534e)

### Actual Behavior

It has not been resolved yet, the default font is displayed
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/16381995/4ad346da-9a18-419f-b852-0d96015bb79a)

### Reproduction Steps

1. Create a word and fill in the content

2. Modify the content to the theme font

3. Uploading to onlyOffice, font display error

**Comment by TatianaKirillova** [comment]
@sunbaichi Do I understand correctly that when using standard Chinese fonts in the MS Word editor and opening such a document in the ONLYOFFICE editor, the font is displayed as Arial?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
