### ISSUE TITLE
Manjaro Spreadsheet Cloud COUNTIFS always returns 0

### ISSUE THREAD

**Issue by DAClopotaritei** [ONLYOFFICE/DocumentServer#2459]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.4.0.163 (flatpak)

### Expected Behavior

Until the 26th of October, in Spreadsheets, using the formula 
`COUNTIFS(Range1,Unit1,Range2,Unit1)`, e.g. 
`COUNTIFS(A1:A9,A1,B1:B9,B1)`,

allowed me to count how many times a certain group of values repeat in a range, such as 
3shifts to X of 1hour,
2shifts to X of 2hour,
2shifts to Y of 1hour,
etc...

### Actual Behavior

No matter the input in the `Unit#` fields, the formula returns 0. 
This also applies retroactively to all spreadsheets which were previously correct.

Upon opening an old spreadsheet, the data is correct, as it should be, but upon copying & pasting a `Unit#` cell onto itself, all formulas referring the cell and other cells within its `Range`, update and return 0.

### Reproduction Steps

Interestingly enough, it seems that downloading the Spreadsheet & running it locally instead of using the OnlyOffice Cloud instance, solves the problem, and the formulas return their expected values.

I have attempted reproducing the error on several occasions, but I haven't yet found the exact trigger to the bug, and unfortunately due to GDPR, I am unable to share the whole spreadsheet.

If others have any suggestions how I may go about it, please send a message.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by DAClopotaritei** [comment]
Hi there,
I am currently using
version 7.5.1.23 (flatpak)
And the issue persists with COUNTIFS.

To replicate, have to columns, A & B; 
Column A has names, Column B has times. 

```=COUNTIFS(A:A,A1,B:B,B1)``` used to count how many times A name and B times were repeated in a given table. 
I used to drag down the formula, remove duplicates, and format the results as a table. 

Is the new behaviour intended? If yes, I will look for a workaround.

**Comment by Rita-Bubnova** [comment]
> Hi there, I am currently using version 7.5.1.23 (flatpak) And the issue persists with COUNTIFS.
> 
> To replicate, have two columns, A & B; Column A has names, Column B has times.
> 
> `=COUNTIFS(A:A,A1,B:B,B1)` used to count how often A names and B times were repeated in a given table. I used to drag down the formula, format the results as a table, and remove duplicates.
> 
> Is the new behaviour intended? If yes, I will look for a workaround.

@DAClopotaritei, I think this issue is not related to your first issue and it have specify example. Could you create separate issue?
We prefer to keep issues simple, one issue - one problem.

**Comment by DAClopotaritei** [comment]
@Rita-Bubnova, sure, I can make a different post, though it is the same that I wrote about in the first form I completed; only reworded the "Expected Behaviour".

That being said, I will re-make it now.

**Comment by DAClopotaritei** [comment]
@rsnegirev, sorry, I did not see your reply, but now that I did,
Long story short, I poked around & found out that it does work with normal data but not the way I used it.

Long ago I found a bug in Excel (Microsoft, Libre, & Only | Office), whereby time is sometimes misaccounted.
An easy way to replicate, is
A= 13:30-14:15
B= 12:15-11:30
C= 12:30-11:45
Whichever way you turn it, all results = 0:45, but none equal each other.
That is because formatting as Time, shows the correct minutes, but formatting as General, and adding MANY decimals (16 if I'm not wrong), the value the computer _actually_ sees is different, specifically:
A=0.03125000...
B=0.03124999...
C=0.0312500000000001

To workaround this, I built my formulas to replace any value between 0.44&0.46 with "0.45".
However, since the last update, the replacements all count as different, for some reason.
Manually inputting the times makes the COUNTIFS formula work correctly, but reinstating the past formula brings every COUNTIFS back to 0.

@Rita-Bubnova, just to make sure, should I still write a different bug report?

**Comment by DAClopotaritei** [comment]
Another update:
using `=ROUND((B1-A1),8)` makes them all be valued the same. 
The examples I used all work with rounding up to 6 decimals, but I made it 8 to keep it safe? I don't know what else might interfere.

This, however, broke the Formula Referencing the results to put the time in text format.
Before, part of the formula was `&IFS(A1="00:30"," 30min",A1="00:45"," 45min",A1="01:00"," 1hr",A1="01:15"," 1hr1/4",A1="02:00"," 2hrs")&`.

I tried without the initial 0, so `A1="1:00", "1hr"`, Error; & I tried without the ", Error again.

The simplest workaround I found, is creating a table of static times, for example 9:00-8:00, and use those as reference. 
So, `A1={$result_of_reference$},"1hr`; that way, 
Very important however, the result of 9:00-8:00 must _ALSO_ be rounded to the **same decimal**, else, `A1={$result_of_reference$}`=FALSE

I believe this is important because I assumed the 0s at the end of A,B,& C were not taken into account when checking values, but they obviously are, so `ROUND(X,6)` & `ROUND(X,7)`, even where the 7th decimal would be a 0, are _NOT_ the same.

**Comment by rsnegirev** [comment]
Hi again @DAClopotaritei 

To be honest, all of your information looks too abstract so far. I understand that there is some kind of problem here, but I cannot specify what is it. Because this reminds me a problem with ROUND and CONCATENATE functions, or another one with decimals. But nothing concrete. 

So, can you attach an example file, we will see some specific problem? In the new issue.
