### ISSUE TITLE
Spreadsheet - Header cut off

### ISSUE THREAD

**Issue by Chacsam** [ONLYOFFICE/DocumentServer#2462]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.0.125

### Expected Behavior

Header to be completly displayed on print-out/export

### Actual Behavior

Hello,

I have been trying to create a one-pager spreadsheet with header and footer.
Whatever margin/scaling settings I use, the Left & Right extremities of my header and footer are cut off by a few pixels.

It looks ok in setup, but incomplete in print/pdf export as you can see in this image:

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/28670803/9543ae14-0b79-45af-b493-89559132afc3)

The same document prints out fully in Excel

### Reproduction Steps

Type text in header of spreadsheet, 
Print/export pdf

**Comment by Rita-Bubnova** [comment]
Hello, @Chacsam, thank you for report.
This is  known bug, issue #64743.

It has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/408a9065958c8de1c243f7c13d9ae641e3d7c10c, https://github.com/ONLYOFFICE/sdkjs/commit/10a34e1880d8199af7363041c9392402db151011) and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
