### ISSUE TITLE
set margin when converting files

### ISSUE THREAD

**Issue by christophe195** [ONLYOFFICE/DocumentServer#2464]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello,

I want to convert a html page to pdf, but when i do this i got a nice page with a large margin on te left and top of the page. I have tried to change the margin but it seems it only works with spreadsheets.

Can this setting get used for more file types?

**Comment by XDmitryK** [comment]
@christophe195 Hi
Can you attach this file here?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
