### ISSUE TITLE
*bug* (spreadsheet) invisible cell content

### ISSUE THREAD

**Issue by RomaricMollard** [ONLYOFFICE/DocumentServer#247]
Hello, it's me, again :)

I noticed an other error on the spreadsheet app, it more difficult to explain.

**Current behavior?**
-> Somes cells contains data but are shows empty and no way to have any content without reloading the document.

**Steps to have the bug**
- Write =A1+1 on cell A2
- Convert A2 to $ (it should write $1)
- Copy past A2 somewhere else, the case is empty
- It impossible to replace the content or to get the cell non-empty
- After writing TEXT, it works again (or if I reload the document)

![ezgif-5-0cc4d81da6](https://user-images.githubusercontent.com/14353924/37162527-c080689a-22f5-11e8-829e-20bff7b77006.gif)

**DocumentServer version:**
Last one (tested on desktop versions and server version)

**Operating System:**
Mac OS X High Sierra

**Browser version:**
Chrome 64.0.3282.186

**Comment by ShockwaveNN** [comment]
@RomaricMollard Thank you. I can confirm - this is a bug, issue 37157 in our internal issue tracker

**Comment by ShockwaveNN** [comment]
Fixed in 5.1.0
