### ISSUE TITLE
mobile version only for commercial license 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#2475]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.2.8

### Expected Behavior

we have a 2000 connection license, but we cannot use ONLYOFFICE on mobile devices. 
installed onlyoffice-documentserver-de 
license is till end 2023

### Actual Behavior

we get a notice that mobile editor is only available for commercial license

**Comment by igwyd** [comment]
Hello @hahaxd35, contact please with our tech support for check your license - https://onlyofficesupport.zendesk.com/
