### ISSUE TITLE
【new feature】Allow line breaks in Western words

### ISSUE THREAD

**Issue by zqhexor** [ONLYOFFICE/DocumentServer#2476]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/41619463/090d6fba-4b03-4feb-a3a5-13f99d500172)
hope add new feature in word document： Allow line breaks in English words.

**Comment by TatianaKirillova** [comment]
Hello, @zqhexor 
Thanks for your request!
I can confirm - this is know bug, issue #55103 with your  proposal

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1593.
