### ISSUE TITLE
Cannot select number in drop-down list

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2481]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

In the attached .xlsx file, in cell A1, one should be able to select a number in the drop-down list.

[bug-form-negative-number.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/13365253/bug-form-negative-number.xlsx)

### Actual Behavior

It is not possible to select a number.

### Reproduction Steps

Steps:
- open the attached .xlsx file
- go to cell A1
- try to click on the drop-down list button
=> it is not possible to select a number

**Comment by VladimirProkofiev52** [comment]
Hello! @parrenin 
The issue 65151 will be fixed in the next release.
The fixes for this issue are located in this [commit](https://github.com/ONLYOFFICE/core/commit/848204d7d000fb82d9578ff3f272ab5238092abc).

**Comment by VladimirProkofiev52** [comment]
I see an issue where decimal numbers are being split across two lines. This is incorrect behavior but unrelated to this particular [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/2481#issue-1999049617).

Please create a new issue, and we'll continue the discussion there.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by parrenin** [comment]
OK, I will open a new issue for the new problem.
