### ISSUE TITLE
Use another HTTP port instead of 80 in windows version

### ISSUE THREAD

**Issue by UnknownObject000** [ONLYOFFICE/DocumentServer#2483]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.5.1

### Expected Behavior

By changing some config file, I can use another port to run the server. For example, I can change the port to any port avalable and use http://localhost:PORT/hosting/discovery to access WOPI.

### Actual Behavior

I can't find such config item in all of the config files in the ```config``` folder.

### Reproduction Steps

I installed the ONLYOFFICE Windows Server, NOT a Docker server.

### Additional information

Is there any way to change the default HTTP port 80?

**Comment by igwyd** [comment]
Hello @UnknownObject000, you can change the port before instalation run ```onlyoffice-documentserver.exe /DS_PORT=<PORT_NUMBER>``` or after installation change port number in the nginx config here ```C:\Program Files\ONLYOFFICE\DocumentServer\nginx\conf\ds.conf``` and restart the ONLYOFFICE services.

**Comment by UnknownObject000** [comment]
> 你好@UnknownObject000，您可以在安装运行之前更改端口`onlyoffice-documentserver.exe /DS_PORT=<PORT_NUMBER>`，或者在安装之后更改 nginx 配置中的端口号`C:\Program Files\ONLYOFFICE\DocumentServer\nginx\conf\ds.conf`并重新启动 ONLYOFFICE 服务。

Thanks, I changed my server port successfully.
