### ISSUE TITLE
I encountered an error when calling the document conversion API in the locally deployed community version of OnlyOffice

### ISSUE THREAD

**Issue by cv-msan** [ONLYOFFICE/DocumentServer#2484]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.5

### Expected Behavior

Request successful and return document URL

### Actual Behavior

I returned -8 when calling the interface, which seems to be a permission issue. How can I solve it?
![1700470372373](https://github.com/ONLYOFFICE/DocumentServer/assets/76542419/713592cc-efb9-47eb-9ea4-9b8b13eca0d6)

### Reproduction Steps

Follow the request in the document 】
https://api.onlyoffice.com/editors/conversionapi
![1700470665636](https://github.com/ONLYOFFICE/DocumentServer/assets/76542419/dd1b37ba-2094-4d9d-8f5a-d297af58c62b)

**Comment by cv-msan** [comment]
@Rita-Bubnova Hello, this issue has been pending for quite some time and the person assigned has not been able to handle it. Can you help me change someone else to take a look at this issue?

**Comment by Rita-Bubnova** [comment]
@askonev take a look this, please.

**Comment by l8556** [comment]
Hi @cv-msan !

The `-8 (Invalid token)` error may mean that you have an incorrectly configured JWT.

You can read more about JWT here:

https://helpcenter.onlyoffice.com/installation/docs-configure-jwt.aspx

https://api.onlyoffice.com/editors/signature/

**Comment by cv-msan** [comment]
Hello, after adding my token, it returned -7
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/76542419/28343e60-aa8b-432f-b584-605c632ff5ac)

**Comment by cv-msan** [comment]
问题解决了如果onlyoffice服务开启了token校验就要把这些参数装在token里请求
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/76542419/fb26adfb-9404-4bc7-a385-ba99ef6996d3)
