### ISSUE TITLE
Hovering over an internal link in Presentation crashes the app

### ISSUE THREAD

**Issue by Mer0me** [ONLYOFFICE/DocumentServer#2485]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

Tested on 7.5.1.1 and 7.5.1.23
The Desktop Editor is affected too.

### Expected Behavior

Clicking the link should display the slide linked

### Actual Behavior

When hovering the link, the app crashes and needs a restart.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/6248852/2f3a52e9-a0fd-45de-98a4-6e6185296547)

### Reproduction Steps

1. Create a Presentation document .PPTX with 2 slides
2. On the first slide, make a link on a piece of text to the 2nd slide
3. Play the presentation and hover over the link.

### Additional information

Same file works on PowerPoint 2010
External links on Presentation app are working.

Internal links on Document app are working

Sample file :
[Test.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/13415517/Test.pptx)

**Comment by ElenaMaaya** [comment]
Hello, @Mer0me! This case will be fixed in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
