### ISSUE TITLE
Style Problem in Drag and Drop 

### ISSUE THREAD

**Issue by alaAicy** [ONLYOFFICE/DocumentServer#2487]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.5.1

### Expected Behavior

Normal ui

### Actual Behavior

When I drag and drop a cell, the following style problem occurs during the drag and drop process
image
<img src="https://user-images.githubusercontent.com/52344565/284857060-bd4fea25-1ccd-4bcf-9a1c-37ef521848dc.png">

### Reproduction Steps

Hold down a cell to drag and drop

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
