### ISSUE TITLE
Inserting this .svg image prevents OO to save the file

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2491]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

It should be possible to insert the attached .svg image in a text document and to save the document in .docx format.

![graph-after](https://github.com/ONLYOFFICE/DesktopEditors/assets/4678272/88eb4416-eef9-4af9-8e45-73fba8eb5e2c)

### Actual Behavior

When one inserts the attached .svg file, it is impossible to save the text document afterwards.

### Reproduction Steps

Steps:
- open a new text document
- insert the attached .svg image
- try to save the document
- => nothing has been saved

**Comment by parrenin** [comment]
This bug seems to be fixed in 8.0.0.

**Comment by Rita-Bubnova** [comment]
This has been fixed (https://github.com/ONLYOFFICE/core/commit/4b658617b37df46008faa221b0d10045c4fc395e, https://github.com/ONLYOFFICE/core/commit/3aa91fcfd4caf1206472cf4714ad794f8bd4b236) in the version 8.0.0.

DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
