### ISSUE TITLE
Docx cannot be modified

### ISSUE THREAD

**Issue by Oz246** [ONLYOFFICE/DocumentServer#2493]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.5.0.125

### Expected Behavior

Creating and editing Word documents (docx)

### Actual Behavior

Word document created but modification grayed out

Modifying an exported document is also grayed out

### Reproduction Steps

I create a new documentr via New (New document), this one is opened but impossible to make any modification.

editing works on excel and powerpoint documents 

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/25376126/4d66af99-2dce-41d8-b0ee-afc83daf8e73)

**Comment by XDmitryK** [comment]
@Oz246 Hi
Can you write more about your OS? Also, can you update the current version to 7.5.1? 
Has anyone else currently edited it and check the permission for this file in the file properties.

**Comment by Oz246** [comment]
Hello, first of all thank you very much for your feedback.

Following the update of onlyoffice the problem is still present. 

To answer your questions:
Ubuntu Ubuntu 22.04.3 LTS

The problem is present even if I generate a new docx directly from a new document in Nextcloud. 
On the other hand, there's no problem with excel documents and presentations.

For properties I have the same thing for xlsx and docx user www-data on vm nextcloud 

Translated with DeepL.com (free version)

**Comment by XDmitryK** [comment]
@Oz246 Thanks for unswer 
I still need to clarify which version of NextCloud you are using and which browser?
It is also possible to use a desktop editor and also connect it to any portal Nextcloud. Your problem may not be repeated on the desktop.

**Comment by Oz246** [comment]
@XDmitryK

Thank you for your feedback. 

My version of nextcloud is 27.1.2. Tested with the following browsers :
Chrome / Firefox / Opera / 
 I have just done a test with Nextcloud Agent which works very well. I create a word file via agent ok . I then open it on my browser : Problem again present

**Comment by XDmitryK** [comment]
@Oz246
Unfortunately, I can't help you. The problem does not repeat on a clean nextcloud portal v.27.1.9.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
