### ISSUE TITLE
Insert text into document 

### ISSUE THREAD

**Issue by eduardorost** [ONLYOFFICE/DocumentServer#25]
Is there any way to insert a text into a editing document using nodejs?

**Comment by trofim24** [comment]
You can add your own code on the [server](https://github.com/ONLYOFFICE/server) to paste the text.
Or you can do it directly on the client using its own plug-in editor.
Examples of writing plug-ins [here](https://github.com/ONLYOFFICE/sdkjs-plugins).
We will soon add more full instructions and a description of work with plug-ins.
