### ISSUE TITLE
Can not add comment with config such as  "documentType": "word",  "mode": "edit","edit": false, "comment": true. The function of adding comments is normal when  same configured in the cell.

### ISSUE THREAD

**Issue by zgpnuaa** [ONLYOFFICE/DocumentServer#2503]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

Can add comment with config "documentType": "word",  "mode": "edit","edit": false, "comment": true.

### Actual Behavior

Cannot add comment, but only see the comment with config "documentType": "word",  "mode": "edit","edit": false, "comment": true.
But can add comment with  config "documentType": "cell",  "mode": "edit","edit": false.The function of adding comments is normal when configured in the cell.

### Additional information

My config as follows:
```
{"type": "desktop", 
"documentType": "word", 
"document": {"title": "12345.docx", "url": "http://192.168.120.207:8000/myonlyoffice/download?fileName=12345.docx&documentId=118&userAddress=zhugaoping", 
"directUrl": "http://192.168.120.207:8000/myonlyoffice/download?fileName=12345.docx&documentId=118", 
"fileType": "docx", "key": "-3169614307027241525", 
"info": {"owner": "\\u7ba1\\u7406\\u5458", "uploaded": "2023-12-04 17:54:54", "favorite": false}, 
"permissions": {"edit": false, "comment": true, "deleteCommentAuthorOnly": true, "editCommentAuthorOnly": true, "copy": true, "download": true, "print": true, "fillForms": true, "modifyFilter": true, "modifyContentControl": true, "review": false, "protect": true, "rename": true, "chat": true,
 "reviewGroups": [], "commentGroups": {"edit": ["\\u4eba\\u624d\\u5de5\\u4f5c\\u7ad9"], "remove": ["\\u4eba\\u624d\\u5de5\\u4f5c\\u7ad9"], 
"view": ["\\u4eba\\u624d\\u5de5\\u4f5c\\u7ad9"]}, 
"userInfoGroups": ["\\u4eba\\u624d\\u5de5\\u4f5c\\u7ad9"]}}, 
"editorConfig": {"actionLink": null, "mode": "edit", "lang": "zh", "location": "cn", "callbackUrl": "http://192.168.120.207:8000/myonlyoffice/track?documentId=118&filename=12345.docx&userAddress=zhugaoping", "coEditing": {"mode": "fast", "change": true}, "createUrl": "http://192.168.120.207:8000/myonlyoffice/create?fileType=desktop", "region": "zh-CN", "templates": true, 
"user": {"id": 2, "name": "GP", "group": "\\u4eba\\u624d\\u5de5\\u4f5c\\u7ad9"},
...
```
The function of adding comments is normal when  same configured in the cell.

**Comment by igwyd** [comment]
Hello @zgpnuaa, the problem is in the ```"fillForms": true"```, this parameter is disabling comments feature in the document editor, but does not disable in the cell and presentation because is not used there.

**Comment by zgpnuaa** [comment]
> Hello @zgpnuaa, the problem is in the `"fillForms": true"`, this parameter is disabling comments feature in the document editor, but does not disable in the cell and presentation because is not used there. [fillForms ](https://api.onlyoffice.com/editors/config/document/permissions#fillForms)
> 
> > In case edit is set to "false" and review is set to "false" and fillForms is set to "true" the comments value is not considered and the commenting is not available

Great, I just tried removing `"fillForms": true` and the problem is solved. Thank you very much.
