### ISSUE TITLE
Support Markdown feature

### ISSUE THREAD

**Issue by JermineHu** [ONLYOFFICE/DocumentServer#251]
**I want to request a *feature* is that support the Markdown format document edit .**

**Current behavior is not support markdown file editing .**

Developers often use Markdown to write documents. So will it be considered to support markdown?

**Comment by ShockwaveNN** [comment]
Hi, currently we have no plans to support Markdown, but we may consider it in future

**Comment by elevatingcreativity** [comment]
+1 I would use this as well. Not only for developing, but a lot of writers are adopting markdown because of its simplicity (e.g. several popular writer’s platforms are exclusively in markdown)

**Comment by icnsoft** [comment]
Agreed, MarkDown would definitely be a perk for OnlyOffice. It's quite easy and practical.

**Comment by HanselMRojas** [comment]
Hi, i'm new in the onlyoffice world. I'm a developer and this feature really interesting to me. How i can get info or wiki, to contribute with code for this feature for to the community?

**Comment by ShockwaveNN** [comment]
@HanselMRojas sorry, we have no guides how to develop new features

**Comment by whitelujx** [comment]
I also need this feature very much...

**Comment by akuckartz** [comment]
An alternative might be to use a Wiki instead.

**Comment by whitelujx** [comment]
Wiki only have one problem, It's public...

**Comment by tenglongwentian** [comment]
我也想增加对markdown类型文档的支持，但是刚接触onlyoffice，不知道怎么添加扩展，实现后可以贡献给社区。

**Comment by ShockwaveNN** [comment]
@tenglongwentian Hi, please use only English in our issue tracker

**Comment by ocervell** [comment]
Any updates after 4 years @ShockwaveNN ? How can I help developping support for it ?

**Comment by ShockwaveNN** [comment]
@ocervell Sorry, but this is not a high-priority task - and the best way to help is to contact sales@onlyoffice.com

We got [plugin](https://github.com/ONLYOFFICE/plugin-doc2md) in plans, but currently it's not on production-ready state

**Comment by ShockwaveNN** [comment]
We released a seprate plugin with markdown support [here](https://github.com/ONLYOFFICE/plugin-doc2md)

I'm closing this issue, all the ideas and bugs in doc2md plugin should be reported to it's repo

**Comment by hex-m** [comment]
The linked project is only about converting documents to markdown. This issue ask for support for **editing** markdown files. So I wouldn't consider this completed.

**Comment by ShockwaveNN** [comment]
@hex-m Fair enouth

I've created issue 59376 for discussion withing our team if we need full-blown markdown editor

**Comment by ShockwaveNN** [comment]
We discussed it with our team and right now we got no plans for making a full-blown markdown editor

For such feature, a lot of other application exists, for example, VS Code which work as a desktop application or web application and did it flawlessly

I'm closing this issue, anyone - feel free to leave feedback and maybe we change our plans in future (or as usual contact sales@onlyoffice.com for more specific estimates)
