### ISSUE TITLE
many bug of math

### ISSUE THREAD

**Issue by imagy** [ONLYOFFICE/DocumentServer#2512]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

onlyoffce7.5

### Expected Behavior

[第七节 抛物线.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/13623451/default.pptx)

### Actual Behavior

Unable to display normally, position incorrect, mathematical formula lost

**Comment by ElenaMaaya** [comment]
Hi @imagy! 
Thank you for your attention to our product! 
I can confirm that the problem exists.
I created ticket 65476 in our  issue tracker.

**Comment by imagy** [comment]
@ElenaMaaya how long  will it take？

**Comment by ElenaMaaya** [comment]
Hello @imagy !  Thank you for the report! This issue will be fixed in the next release. Please keep checking for updates. 
Thank you for the report!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
