### ISSUE TITLE
Table borders set to no borders, but borders is present in MS Office

### ISSUE THREAD

**Issue by Akrobs** [ONLYOFFICE/DocumentServer#2519]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.5.1

### Expected Behavior

Table border invisible in OO, but visible in MS Office

### Actual Behavior

When set advanced table settings, borders set to no borders, the borders is present in MS Office.

### Reproduction Steps

1) Create document
2) Insert table
3) Advanced table settings
4) Borders & Backgrounds
5) Set no borders
6) Save document
7) Open in MS Office

**Comment by maruacat** [comment]
Hello @Akrobs 
Unfortunately, I can't reproduce your problem. Can you please attach a file containing a table without borders that has borders when opened in MS Word?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
