### ISSUE TITLE
Support of Drop-down lists

### ISSUE THREAD

**Issue by eraizi** [ONLYOFFICE/DocumentServer#252]
original file:
![11](https://user-images.githubusercontent.com/20589870/37631540-1b778f02-2c25-11e8-9eec-08b92c902c83.png)
upload file:
![22](https://user-images.githubusercontent.com/20589870/37631542-1f6d0236-2c25-11e8-8e65-9670548e7e69.png)

**Comment by ShockwaveNN** [comment]
@eraizi Hi, could you attach this file

**Comment by eraizi** [comment]
@ShockwaveNN 
[Uploading test.xlsx…]()

**Comment by ShockwaveNN** [comment]
@eraizi You're attached file wrong, link to file lead to this issue url

**Comment by eraizi** [comment]
@ShockwaveNN 
[test.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1828723/test.xlsx)

**Comment by Rita-Bubnova** [comment]
Hello.
The drop-down list functionality is unsupported now, but have it in future plans.

**Comment by cpot** [comment]
+1 (functionality highly important in our opinion)

**Comment by fvkn** [comment]
Do you have a timeline for this feature? it appears in many xls forms and is thus a must have for us.

**Comment by kalcaddle** [comment]
not support:

    <dataValidations count="1">
        <dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="B3:B15">
            <formula1>"A,B,C,D,E,F,G,H"</formula1>
        </dataValidation>
    </dataValidations>

when edit a file has Drop-down lists, on saved the file

the dataValidations  missed.

**Comment by Rita-Bubnova** [comment]
Hello.
@kalcaddle, you're right. This part of xml is missing because Document Server hasn't got such functionality at this moment as we told above.
We understand that this is one of the important features, but currently we have no ETA for functionality realization. You can speed things up by contacting sales@onlyoffice.com

**Comment by RemoSchmid** [comment]
Any plans for this feature request? For me it is a must have. Thx

**Comment by ShockwaveNN** [comment]
@RemoSchmid Sorry, no news

**Comment by Floflobel** [comment]
+1 it's a crutial feature for me

**Comment by s-flab** [comment]
+1 for this feature request

**Comment by marmartintsang** [comment]
+1 for this feature request

**Comment by andew311** [comment]
+1 for this feature request

**Comment by kalcaddle** [comment]
+1 for this feature request

**Comment by xiaofeihe** [comment]
+1 for this feature request   
drop-down menu

**Comment by pwepwe973** [comment]
> +1 (functionality highly important in our opinion)
yes very very important it's a pity always not available and in passing bravo for the work in only office

**Comment by AGDELTA** [comment]
+1 for this feature request
drop-down menu

**Comment by ShockwaveNN** [comment]
Hello everyone.
Our team made changes that Dropdown lists will not be lost after opening document at https://github.com/ONLYOFFICE/core/commit/1a7476e4656cafea2847cd059b284bde0d408e0a
But this change will be released not in 5.3, but in next stable version (issue 40316 in our private tracker)
Also there is issue 41548 about full support of dropdowns, but currently we got no any ETA of implementing it, but you can always contact sales@onlyoffice.com to make this task more crucial.

**Comment by cpot** [comment]
Hello,

I think that OnlyOffice is a great product but some major features missing like this one **hurts a lot OnlyOffice adoption**. 

Best,
Christopher

**Comment by pwepwe973** [comment]
Hello,
it's very good news because I could not use google drive any more when I had drop-down menus.
especially that I like very much Onlyoffice because it solicite very little the waiter, but I began to turn to an alternative and there I will be able to wait a little longer.

thank you for your work

**Comment by pwepwe973** [comment]
> Hello everyone.
> Our team made changes that Dropdown lists will not be lost after opening document at [ONLYOFFICE/core@1a7476e](https://github.com/ONLYOFFICE/core/commit/1a7476e4656cafea2847cd059b284bde0d408e0a)
> But this change will be released not in 5.3, but in next stable version (issue 40316 in our private tracker)
> Also there is issue 41548 about full support of dropdowns, but currently we got no any ETA of implementing it, but you can always contact [sales@onlyoffice.com](mailto:sales@onlyoffice.com) to make this task more crucial.

Hello,
it's very good news because I could not use google drive any more when I had drop-down menus.
especially that I like very much Onlyoffice because it solicite very little the waiter, but I began to turn to an alternative and there I will be able to wait a little longer.

thank you for your work

**Comment by ShockwaveNN** [comment]
@pwepwe973 sorry, we got no exact dates

**Comment by pwepwe973** [comment]
> @pwepwe973 sorry, we got no exact dates

hello
it's damage because it's been 3 years that users ask for it and in 2019 it has still not been put in priority of the options to add ... :(

**Comment by homeir** [comment]
+1 
glad to hear it's on its way

**Comment by jguyenot** [comment]
+1 for this feature request
drop-down menu

**Comment by thomaswollburg** [comment]
+1 for this. have a potential customer testing the system and he is not happy is this isnt working... so no sale here...

**Comment by bunjes** [comment]
+1 
functionality highly important for our institute

**Comment by cpot** [comment]
So damaging for OnlyOffice... Wondering how the roadmap is elaborated. 

We will ask a quotation because we can't wait any longer.

**Comment by Medanna** [comment]
Dear @cpot,
thank you for choosing ONLYOFFICE. 
Dropdown lists have already been designed and are waiting for implementation. 
We ask for your patience, if it is possible, and hope for your understanding.

**Comment by recon88** [comment]
Almost 2 years after the request was made, still nothing.

**Comment by Medanna** [comment]
Hi everybody, thank you for using ONLYOFFICE and making it better together with us. Implementation of this feature is planned for ONLYOFFICE Editors version 5.6 (approximately spring 2020). It's not so long to wait.

**Comment by cpot** [comment]
> 
> 
> Hi everybody, thank you for using ONLYOFFICE and making it better together with us. Implementation of this feature is planned for ONLYOFFICE Editors version 5.6 (approximately spring 2020). It's not so long to wait.

As we emphasis several time this issue is highly important for corporation/organization to migrate to Onlyoffice. Good to know that we have just 1 or 2 months to wait

**Comment by Medanna** [comment]
@cpot, thank you for your patience and for choosing ONLYOFFICE. Could you please describe your scenario of using this feature? It would be helpful for product engineering.

**Comment by cpot** [comment]
@Medanna most our customers have spreadsheets with dropdown list in cells. therefore they cannot fully switch to onlyoffice. FYI, i sent a list of top priorities to Galina but can shared it more broadly if you want, just drop me an email

**Comment by Medanna** [comment]
@cpot , thank you, Galina has already shared them with me.

**Comment by AncientMariner67** [comment]
Any news when the drop down list support will be available? My company is using a cooperative document to track work completion, and the drop down lists would improve the functionality of the spreadsheet.

**Comment by plamarque** [comment]
This feature is also much requested by our customers.

**Comment by Samuel-Renault-eXo** [comment]
+1 for this feature. A must-have for our customers!

**Comment by margondicco** [comment]
Really important feature !

**Comment by macmiranda** [comment]
+1

**Comment by trofim24** [comment]
We forced the release of this functionality. The ability to select data in an existing document will be released in **hotfix version 5.5.1**.

**Comment by cpot** [comment]
@trofim24 @Rita-Bubnova  This is an extremely good news ! Thanks a lot

**Comment by ShockwaveNN** [comment]
@cpot we hope to release will be ready this spring, but currently we cannot give any exact date

**Comment by cpot** [comment]
@ShockwaveNN Our GoFAST 3.8 should be finished by mid-april, we hope to integrate OO 5.5.1 as this dropdown feature is so important. I  know it is optimistic

**Comment by ShockwaveNN** [comment]
@cpot to be clear - in 5.5.1 as @trofim24 said, will be only ability to select data from document with already added dropdown
Currently there is no version with ability to add your own dropdown

**Comment by aaylnx** [comment]
> @cpot to be clear - in 5.5.1 as @trofim24 said, will be only ability to select data from document with already added dropdown
> Currently there is no version with ability to add your own dropdown

Ouch. Well, at least it's a first step. Hope the ability to create our own dropdowns will eventually exist.

**Comment by cpot** [comment]
@aaylnx we understood that. from what i recall the full implementation could be for summer. it make sense because asking users to use Libreoffice or Excel to create a drop-down is hardly understandable. But this 5.5.1 is a first good step. Thank you !

**Comment by cpot** [comment]
After some tests on a xlsx, some dropdown, while you select the value in the list, the value is not inserted into the cell. Shall we open a separate issue ?

**Comment by Rita-Bubnova** [comment]
> After some tests on a xlsx, some dropdown, while you select the value in the list, the value is not inserted into the cell. Shall we open a separate issue ?

Yes, please create a new issue and attach file with problem.

**Comment by cpot** [comment]
Done https://github.com/ONLYOFFICE/DocumentServer/issues/854

Please provide a quick fix if possible, our users are expecting very much this feature and would like to avoid disappointment

**Comment by doitux** [comment]
Is this feature still missing?

**Comment by kikislater** [comment]
> Is this feature still missing?

@doitux Yes !

**Comment by macmiranda** [comment]
> Is this feature still missing?

You can only view drop-down fields created in other apps

**Comment by cpot** [comment]
Any news @Rita-Bubnova ? a large customer of us would like a estimated date for this important feature. Thank you

**Comment by Rita-Bubnova** [comment]
@cpot, sorry I'm just a QA specialist, I'm not in position to guarantee any estimates. You better contact sales@onlyoffice.com.

**Comment by hdmr14** [comment]
Will the "Data validation settings for cells" feature in [Version 6.2 Roadmap](https://github.com/ONLYOFFICE/DocumentServer/blob/903fe5ab7a275bd69c3c3346af2d21cf87ebeabf/ROADMAP.md#L25) be able to add drop-down list like Excel's Validation object?

**Comment by aaylnx** [comment]
> Will the "Data validation settings for cells" feature in [Version 6.2 Roadmap](https://github.com/ONLYOFFICE/DocumentServer/blob/903fe5ab7a275bd69c3c3346af2d21cf87ebeabf/ROADMAP.md#L25) be able to add drop-down list like Excel's Validation object?

Yes, I'd be interested in knowing that as well.

**Comment by Rita-Bubnova** [comment]
> Will the "Data validation settings for cells" feature in [Version 6.2 Roadmap](https://github.com/ONLYOFFICE/DocumentServer/blob/903fe5ab7a275bd69c3c3346af2d21cf87ebeabf/ROADMAP.md#L25) be able to add drop-down list like Excel's Validation object?

The dropdown list is included in "Data validation".
Version with the "Data validation" in testing right now.

**Comment by eldelacajita** [comment]
Any news on when this essential feature will be released? Will it make it for 6.2?

**Comment by Rita-Bubnova** [comment]
@eldelacajita, this fix is testing now, it's will be in v6.2.

**Comment by aaylnx** [comment]
> @eldelacajita, this fix is testing now, it's will be in v6.2.

Excellent!

**Comment by trofim24** [comment]
We released Data Validation in [version 6.2.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#620)

**Comment by RumbleWx** [comment]
can it add dropdown list in cell now?🙏

**Comment by JiffyChen** [comment]
![image](https://user-images.githubusercontent.com/4900504/197740180-67b8a9fd-4f7e-466d-a2a8-f3906ad099a9.png)
How to set pull-down list by Api?

**Comment by ShockwaveNN** [comment]
@JiffyChen Please create a separate issue for that

**Comment by JiffyChen** [comment]
> @JiffyChen Please create a separate issue for that

OK

**Comment by rahulmanas** [comment]
the dropdown is not coming for my case. What can we do to add a dropdown? Is there any configuration changes required to activate this?

**Comment by trofim24** [comment]
@rahulmanas no restrictions to use it. You can watch [our video](https://youtu.be/Nr0iMHMJcPw) or read [article](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Spreadsheet-Editor/UsageInstructions/DataValidation.aspx) about Data Validation.
