### ISSUE TITLE
Regarding the issue of font loading speed when opening documents

### ISSUE THREAD

**Issue by dengjinyu1234** [ONLYOFFICE/DocumentServer#2524]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I am currently working on the secondary development of the only office. May I know where the code for loading document fonts is located? What methods can improve the loading speed of fonts when opening documents?
thanks

**Comment by K0R0L** [comment]
https://github.com/ONLYOFFICE/sdkjs/blob/eb92448a74506b94ca984b6c6dd82b715ecf4836/common/Drawings/Externals.js#L79.

In the next releases, we plan to start using https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API. Chrome has it enabled by default.
