### ISSUE TITLE
An error in the document with equation

### ISSUE THREAD

**Issue by Rita-Bubnova** [ONLYOFFICE/DocumentServer#2528]
@ElenaMaaya, @Rita-Bubnova Thank you!
I have another problem with the equation editor that is causing it to crash.
But in order for you to reproduce the error, I need to send you a presentation.
I was making a presentation with a table containing equations and at some point I got an equation state that led to a crash when I tried to delete the equation.

Attached is the file with this presentation.
Try to delete the empty equation in the table cell at the top right and you will get an error message:
```
An error occurred during the work with the document.
Use the 'Save as...' option to save the file backup copy to a drive.
```

[ex10.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/13746078/ex10.pptx)

_Originally posted by @ikulagin in https://github.com/ONLYOFFICE/DocumentServer/issues/2525#issuecomment-1866914015_

**Comment by ElenaMaaya** [comment]
Hello @ikulagin!
We are very grateful for your help! We made a separate issue to your problem.
I can confirm that the problem exists. I created ticket 65676 in our  issue tracker with your issue.

**Comment by ElenaMaaya** [comment]
Hello @ikulagin! I have a good news! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
