### ISSUE TITLE
Image not displayed after multiple openings

### ISSUE THREAD

**Issue by ysq5202121** [ONLYOFFICE/DocumentServer#2529]
[x.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/13770371/x.xlsx)

### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/8586973/a102a581-70f7-4496-a500-50f81cd72aa2)

### Actual Behavior

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/8586973/0f5107b8-ddd1-4aed-b586-1590f3427f23)

**Comment by Rita-Bubnova** [comment]
Hello, @ysq5202121.
Could you attach file with problem?

**Comment by ysq5202121** [comment]
Right at the top

**Comment by ysq5202121** [comment]
The first time you open an image, the image won't be lost, but after opening it again, it seems like you can easily lose the image

**Comment by rsnegirev** [comment]
Hi @ysq5202121 sorry for a long answer.

I tried reproduce this behavior but every time with the same result:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/65603548/31cd06db-a207-4c05-9252-e005286b4cfd)


So file loosing just one object in every cell of the column U. And this is happening since first opening.

Maybe do you have some additional steps?

**Comment by ysq5202121** [comment]
@rsnegirev  It's just opening it multiple times

**Comment by rsnegirev** [comment]
I'll try to figure it out.

**Comment by WangTiankunKenny** [comment]
we are having the same issue here, here are some things we found, 

1.     ctrl-c and ctrl-v from outside to onlyoffice-documet is working.
2.     ctrl-c and ctrl-v from onlyoffice-documet(local) to outside(web only office) is not working.
3.     ctrl-c and ctrl-v from onlyoffice-documet to other onlyoffice-documet is not working.

**Comment by rsnegirev** [comment]
@ysq5202121 I tried, but without the same result as yours, the pictures are still there. Can you check if the same thing is reproduced in the new version 8.0.0?

**Comment by rsnegirev** [comment]
Hi @WangTiankunKenny 

I'm not sure if this is the same. Can you please open a new issue with more detailed information?

**Comment by ysq5202121** [comment]
@rsnegirev  
Thank you very much, but there is still this issue in actual production

**Comment by ysq5202121** [comment]
I don't even know what to do

**Comment by rsnegirev** [comment]
@ysq5202121 Can you please record a screencast which shows a problem?
