### ISSUE TITLE
Cannot copy and paste an entire row in spreadsheet

### ISSUE THREAD

**Issue by rabinnh** [ONLYOFFICE/DocumentServer#2532]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.5.1.23

### Expected Behavior

I attempted to copy and paste an entire row in the spreadsheet.  I can copy using menu or Ctrl-C but when I paste into another row, nothing happens.

### Actual Behavior

Row remains blank

### Reproduction Steps

1 Open existing spreadsheet
2 Click on row number on left to select entire row
3 Right click on "Copy" (or use Ctrl-C)
4 Go to next row and highlight
5 Click on "Paste" (or use Ctrl-V)
6 Copied row should appear in empty row

**Comment by Rita-Bubnova** [comment]
Hello, @rabinnh.
I don't reproduce your problem in DocumentServer version 7.5.1.23.
Could you attach your file with problem? What browser are you using?

**Comment by rabinnh** [comment]
Sorry, but the file has personal information in it.

It's an ODS file on an SMB share.  I can open and copy/paste in LibreOffice but not ONLYOFFICE.

However; I opened the file in ONLYOFFICE and saved it as a XLSX file.  I then reopened it in ONLYOFFICE and was able to copy/paste rows.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
