### ISSUE TITLE
Cant use PowerPoint jump-to-slide feature 

### ISSUE THREAD

**Issue by shu0406** [ONLYOFFICE/DocumentServer#2536]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.1

### Expected Behavior

Presentation with jump-to-slide links made with PP: 
[bug cant jump to slides.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/13887518/bug.cant.jump.to.slides.pptx)

All hyperlinks already in the pptx should work in ONLYOFFICE

### Actual Behavior

When opened in ONLYOFFICE the hyperlinks dont work. Neither jump to 2/3 page nor jump to first page.
The issues is always in desktop editor 7.5.1 but since docs is the main product, I post the issue here.

**Comment by shu0406** [comment]
I think it is not a problem with that specific presentation. Even if I build a new presentation within onlyoffice docs 7.4.1 my "jump to slide" hyperlinks get ignored.

**Comment by ElenaMaaya** [comment]
Hello @shu0406!
Thank you for report!
I can confirm that the problem exists. I created ticket 65850  in our tracker with your issue.

**Comment by ElenaMaaya** [comment]
Hello @shu0406!  Thank you for the report! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
