### ISSUE TITLE
feature (Disable Copy-To-Clipboard)

### ISSUE THREAD

**Issue by winsats** [ONLYOFFICE/DocumentServer#254]
Is there a feature to disable the copy-to-clipboard in editor? Disable all forms of Copy (key, button, menu)?

**Comment by winsats** [comment]
Is there a feature to disable the copy-to-clipboard in editor? Disable all forms of Copy (key, button, menu)?

**Comment by ShockwaveNN** [comment]
No, there is no such option

**Comment by winsats** [comment]
Is it possible to make changes in the source code to disable the copy-to-clipboard permanently?

**Comment by ShockwaveNN** [comment]
@winsats no, there is no easy way to do that

**Comment by winsats** [comment]
Would like to know if you have any details on where in the code this is implemented. I would like to try it. Thanks

**Comment by ShockwaveNN** [comment]
Project is written on Javascript, no so hard to find out it by yourself.
It you want - you can contact our sales team at sales@onlyoffice.com and discuss posibility to make your request as a feature.

**Comment by Medanna** [comment]
> 
> 
> Is there a feature to disable the copy-to-clipboard in editor? Disable all forms of Copy (key, button, menu)?

You don't need the 'Copy' feature in editing or viewing mode? Please, describe a situation when it's important.

**Comment by ice-waves** [comment]
> > Is there a feature to disable the copy-to-clipboard in editor? Disable all forms of Copy (key, button, menu)?
> 
> You don't need the 'Copy' feature in editing or viewing mode? Please, describe a situation when it's important.

just only preview?

**Comment by Medanna** [comment]
Yes, it's planned to add in 2020.

**Comment by ice-waves** [comment]
> > just only preview?
> 
> Yes, it's planned to add in 2020.

ehhh....   but now, how can i disable copy function ?

**Comment by ice-waves** [comment]
@ShockwaveNN , could you tell me how to do it in latest version?

**Comment by ShockwaveNN** [comment]
@ice-waves sorry, do you want to point out part in source that need to changed to disable copy to clipboard? As I said earlier, it's not an easy task and I simply don't know

**Comment by ice-waves** [comment]
> @ice-waves sorry, do you want to point out part in source that need to changed to disable copy to clipboard? As I said earlier, it's not an easy task and I simply don't know

I've found answer in "Disable copy to outside OnlyOffice #117",only the copy button is still there. Anyway,  thanks a lot! 👍

**Comment by ShockwaveNN** [comment]
@ice-waves I far as I remember those modification will not hide copy button, only make button not perform any copiying opeartion, but I'm not sure, issue still not fully resolved

**Comment by trofim24** [comment]
We added [document.permissions.copy](https://api.onlyoffice.com/editors/config/document/permissions#copy) field in version 6.0. See [changelog](https://api.onlyoffice.com/editors/changelog#60)
But we did not disable copy button, because we left it possible to use copying inside the current document. We will add this note to our API.
