### ISSUE TITLE
Unable to connect with S3

### ISSUE THREAD

**Issue by intellisense** [ONLYOFFICE/DocumentServer#2540]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

Onlyoffice will be able to connect with the S3 service and store cache there.

### Actual Behavior

Unable to connect with S3 service.

### Additional information

I am not sure what has changed recently, but the following storage configuration was working fine recently (I guess until `7.4`):

```
{
  "storage": {
    "name": "storage-s3",
    "region": "us-east-1",
    "endpoint": "https://local-S3-url",
    "bucketName": "onlyoffice",
    "storageFolderName": "cache",
    "urlExpires": 604800,
    "accessKeyId": "AKID",
    "secretAccessKey": "SAK",
    "useRequestToGetUrl": true,
    "useSignedUrl": true,
    "sslEnabled": true,
    "s3ForcePathStyle": true,
    "externalHost": ""
  }
}
```

But on the latest versions somehow it tries to connect with `127.0.0.1:443` instead of the endpoint specified:
```
[2024-01-11T21:24:43.470] [ERROR] [localhost] [8312731855134965273] [1] nodeJS - storage.listObjects: Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

[2024-01-11T21:24:48.353] [ERROR] [localhost] [8312731855134965273] [1] nodeJS - Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  '$metadata': { attempts: 3, totalRetryDelay: 200 }
}
```

Please advise. Happy to provide any further information. Thank you!

**Comment by intellisense** [comment]
Any help in this regard is appreciated. I can't move back to `7.4` since it throws an error in the browser but the health check passes with the provided storage configuration (which fails in the recent version as mentioned in the original issue):
```
app.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'relevant_theme_id')
    at Object.init (app.js:8:195194)
    at i.onLaunch (app.js:8:2330031)
    at e.<anonymous> (app.js:8:167758)
    at app.js:8:90390
    at p.each.p.forEach (app.js:8:91488)
    at e.launchControllers (app.js:8:167719)
    at e.start (app.js:8:167051)
    at app.js:8:2872542
    at Object.execCb (require.js:12:16162)
    at i.check (require.js:12:10284)
```

**Comment by intellisense** [comment]
Hi! any updates on this? I see another [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/2549) where the configuration was working in `7.4` but not anymore in the latest version. Thank you!

**Comment by igwyd** [comment]
Hello @intellisense, since 7.5.0 we change the aws sdk version fron 2 to 3 ([commit](https://github.com/ONLYOFFICE/server/commit/8177af1b7012b2f3b7bbfdd018270aa985e484b6)) and we tested it with AWS S3 buckets and other S3 servises on the different regions. As i see you used local S3? Try to check your S3 application documentation,  does it work with aws sdk 3?

**Comment by intellisense** [comment]
Thanks for the response. Yes, I am using [minio](https://min.io/) locally and it does support AWS SDK V3. In [AWS SDK V3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/) I see that `s3ForcePathStyle` is renamed to `forcePathStyle ` perhaps that is the reason it is not working?

**Comment by intellisense** [comment]
I'll create a minimal reproducible app and share it.

**Comment by intellisense** [comment]
Here is the minimal reprdocuible app https://github.com/intellisense/onlyoffice-minio. Please follow the [testing steps](https://github.com/intellisense/onlyoffice-minio?tab=readme-ov-file#testing) mentioned there, currently the way it is, visiting the healthcheck URL at http://127.0.0.1/healthcheck will respond with `false`, and the following error is visible in onlyoffice-documentserver container logs:
```
[2024-01-19T22:59:46.431] [ERROR] [localhost] [docId] [userId] nodeJS - healthCheck error Error: getaddrinfo ENOTFOUND onlyoffice.minio
```

If you switch the [documentserver](https://github.com/intellisense/onlyoffice-minio/blob/main/docker-compose.yml#L15) docker image to `onlyoffice/documentserver:7.4.1` and repeat the testing steps, the healthcheck URL at http://127.0.0.1/healthcheck will respond with `true`.

**Comment by igwyd** [comment]
I couldn't get your app to run, need .env file with variables. Could you please provide it?
```
docker compose up --build
WARN[0000] The "BUCKET_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BUCKET_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ENDPOINT_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string. 
env file /root/onlyoffice-minio/.env not found: stat /root/onlyoffice-minio/.env: no such file or directory
```

**Comment by intellisense** [comment]
Oh sorry, I have updated the README. You can create a `.env` file with these variables:
```
AWS_ACCESS_KEY_ID=minio-access-key
AWS_SECRET_ACCESS_KEY=minio-secret-key
ENDPOINT_URL="http://minio:9000"
BUCKET_NAME=onlyoffice
```

**Comment by intellisense** [comment]
Just checking, are you able to reproduce the issue? any help in this regard is appreciated as this has blocked development. Thank you!

**Comment by igwyd** [comment]
Thank you, yes i reproduced it. I'll let you know when there's news.

**Comment by igwyd** [comment]
I confirm this is bug, issue #66128. You are right - ```s3ForcePathStyle``` renamed to ```forcePathStyle```, we fixed https://github.com/ONLYOFFICE/server/commit/632fb4157b7b6a928d1f37609d9d91a0c847d632 and will be released in the next major release soon.

**Comment by intellisense** [comment]
That is excellent news. I'm looking forward to the release. Do you know when you expect the `8.0` release?

**Comment by igwyd** [comment]
I don't have a date, but as far as I know the release will be very soon.

**Comment by intellisense** [comment]
I can confirm that the latest release, `8.0`, fixes the mentioned issue. I appreciate your support. Kind Regards!

**Comment by softboy99** [comment]
Hi,
@intellisense , Thanks , this greatly help me. @igwyd , Could you please help to push the update of the documentation?https://helpcenter.onlyoffice.com/docs/installation/docs-connect-amazon.aspx

**Comment by igwyd** [comment]
Hello @softboy99, name of param not changed in our config file.
