### ISSUE TITLE
improve the time point for spellchecker initializing

### ISSUE THREAD

**Issue by reidzhou** [ONLYOFFICE/DocumentServer#2541]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

i have tried to off the spellchecker acrroding to the document below
<img width="856" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/34478469/b9d55fa8-6d3e-4a65-b996-bf27c442daed">

but i could still found the worker thread of spellchecker. I'm a little confused about this. In my mind, i thought the worker should not be there if the spellchecker feature is disabled.
so i dive into the code.
aha, the spellchecker initialized when websocket authed successfully.
key code is here: https://github.com/ONLYOFFICE/sdkjs/blob/eb92448a74506b94ca984b6c6dd82b715ecf4836/common/docscoapi.js#L1648

and my question is whether this is necessary to initialize spellchecker while authing. it's better to initialize spellchecker when the main page is ready if feature is enabled.

what's your opinion? :)

**Comment by avdddd1111** [comment]
Hello @reidzhou ! Sorry for late response!

Historically, it happened that the initialization of the spellcheck engine starts upon connection. This is because previously the spellchecker was server-based. Now it's a shared worker. The startup of the worker does not affect the loading speed.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
