### ISSUE TITLE
Conflict between forced save and automatic save

### ISSUE THREAD

**Issue by wspshaopeng** [ONLYOFFICE/DocumentServer#2547]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.2.56

### Expected Behavior

![Uploading 1.png…]()
After canceling the automatic save, you can still use the external save button to call the forced save to save file changes

### Actual Behavior

After canceling automatic save, use force save to save the file and prompt "No changes"

### Reproduction Steps

1.canceling the automatic save,
2.Page modification file content
3.use forcesave api
4.prompt "No changes"

**Comment by matveevms** [comment]
Hello, @wspshaopeng 
Is the problem still relevant on new versions?
