### ISSUE TITLE
Permissions not getting propogated to Chart Editor

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2548]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.5.0

### Expected Behavior

When inserting a chart or double tapping a chart a chart editor popup is opened.
The permission user has should propogate to chart editor. 

If the user has copy permission then only user should be able to copy text in chart editor.

### Actual Behavior

User without copy permission can copy content or perform any other tasks which user doesn't have access to.

### Reproduction Steps

Open a docx file and insert a chart.
Share the file to someone without copy permission

**Comment by avdddd1111** [comment]
Hello @Maaayank ! Sorry for late reply!

Please update the document server to the latest version. And check if the issue persists.

Copy permission implies the ability to copy content only within the current document. 

Details:
https://api.onlyoffice.com/editors/config/document/permissions#copy

I tried to reproduce it, and it's working fine for me. Could you please provide more detailed steps for reproduction?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
