### ISSUE TITLE
7.5.1 can‘t add fonts

### ISSUE THREAD

**Issue by maizi-pei** [ONLYOFFICE/DocumentServer#2549]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Docker

### Version information

7.5.1

### Expected Behavior

With the Dockerfile used in version 7.4.1, the system files were successfully replaced, and configuration updates were correctly applied. Specifically, I expected the following operations to be achieved through the COPY and RUN commands in the Dockerfile:

Overwrite the default configuration with a custom configuration file.
Delete contents from certain font directories and replace them with custom fonts.
Overall, the Dockerfile should modify the container as per the predefined changes during the build process.

build from 7.4.1:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/142878231/1aed72d7-a85f-4238-931a-48d172e551ba)

### Actual Behavior

In version 7.5.1, the Dockerfile does not seem to replace the font files as expected. Despite following the same steps that worked in version 7.4.1, the custom fonts that I attempted to copy into the container are not replacing the existing fonts. This issue is specific to the font replacement and does not reflect the intended behavior observed in the earlier version.

build from 7.5.1:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/142878231/0971ad5b-8309-418f-8e49-686337736c05)

### Additional information

The same Dockerfile used is as follows:

FROM onlyoffice/documentserver:7.5.1

ENV JWT_ENABLED=false
ENV ALLOW_META_IP_ADDRESS=true
ENV ALLOW_PRIVATE_IP_ADDRESS=true

COPY default.json /etc/onlyoffice/documentserver

RUN rm -rf /usr/share/fonts/*

RUN rm -rf /var/www/onlyoffice/documentserver/core-fonts/*

COPY fonts/mini_fonts /usr/share/fonts/mini_fonts/

**Comment by hahaxd35** [comment]
dont remove all fonts from onlyoffice, there are needing in there GUI(?) but there cannot tell wich 

but maybe just run documentserver-gen-all-fonts.sh or like this

**Comment by maizi-pei** [comment]
> dont remove all fonts from onlyoffice, there are needing in there GUI(?) but there cannot tell wich
> 
> but maybe just run documentserver-gen-all-fonts.sh or like this

I tried the following Dockerfile as per your instructions, but still can't see the newly added fonts。The same Dockerfile, with just a change in the version number, works well in version 7.4.1:

# 使用 onlyoffice/documentserver 作为基础镜像
FROM onlyoffice/documentserver:7.5.1

ENV JWT_ENABLED=false
ENV ALLOW_META_IP_ADDRESS=true
ENV ALLOW_PRIVATE_IP_ADDRESS=true

# 复制文件
# COPY out/linux_64/onlyoffice/documentserver /var/www/onlyoffice/documentserver

# 配置文件
COPY default.json /etc/onlyoffice/documentserver

# RUN rm -rf /usr/share/fonts/*

# RUN rm -rf /var/www/onlyoffice/documentserver/core-fonts/*

# copy fonts
COPY fonts/mini_fonts /usr/share/fonts/mini_fonts/

**Comment by hahaxd35** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/1868
here you cant find infos deleting all the fonts is not good

**Comment by maizi-pei** [comment]
> https://github.com/ONLYOFFICE/DocumentServer/issues/1868
> 
> here you cant find infos deleting all the fonts is not good

It's still not working even though I did what you said and didn't delete any fonts.

**Comment by maizi-pei** [comment]
Solved it, it was a caching issue. Using Chrome browser's incognito mode resolved the problem
