### ISSUE TITLE
Firefox doesn't support copy & paste

### ISSUE THREAD

**Issue by TheMrApostel** [ONLYOFFICE/DocumentServer#255]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
You are unable to copy and paste when using the latest version of Mozilla Firefox.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Start Firefox
2. Open a spreedsheet in OnlyOffice
3. Try to copy and paste a value
4. Nothing happens

**What is the expected behavior?**
Copy and paste should be working in- and outside of onlyoffice (Chrome and IE are working just fine)
**Did this work in previous versions of DocumentServer?**
Not sure but i think
**DocumentServer version:**
5.0.7 CE
**Operating System:**
CentOS Linux 7 (Core)
**Browser version:**
Mozilla Firefox 59.0.1

**Comment by ShockwaveNN** [comment]
@TheMrApostel Seems we cannot reproduce your problem on client-side with Ubuntu 16 and Windows 7, 10 and Firefox 59.0.1
What is your client-side OS?

**Comment by TheMrApostel** [comment]
@ShockwaveNN 
I just tested it from my personal computer and the issue does not occure here.
So it must be an issue with our work environment.
