### ISSUE TITLE
Is there a way to listen to the mouse selection event and get the selected text?

### ISSUE THREAD

**Issue by Bloodcapillary** [ONLYOFFICE/DocumentServer#2552]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I think this feature is very important

**Comment by TatianaKirillova** [comment]
Hello, @Bloodcapillary !
If you have Screen Readers installed, then after using the hotkeys ctrl/cmd + alt + z
Voice acting of selected text can be obtained already in version 7.5.1

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
