### ISSUE TITLE
Chinese translation is not accurate

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/DocumentServer#2557]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Docker

### Version information

7.5.1.23

### Expected Behavior

Simplified Chinese

### Actual Behavior

Simplified Chinese is not accurate, many are traditional, and there is also English

**Comment by ElenaMaaya** [comment]
Hello, @yiwen9488! Thank you for your attention to our product!
We are trying to make the translation better. 
Please give a list of examples of incorrect translations into Chinese (simplified) translation. This will help fix the translation faster.

Also the translation into Chinese is not yet complete and may be present words in English. Our specialists are working on it.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
