### ISSUE TITLE
How to use documentbuilder to split a document into multiple document documents according to paragraphs?

### ISSUE THREAD

**Issue by Jelly7655** [ONLYOFFICE/DocumentServer#2563]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I suggest converting the document to JSON format and segmenting it according to paragraph attributes. Currently, I haven't seen this attribute in the JSON format. Looking forward to your answer, thank you！

**Comment by askonev** [comment]
In the context of a docbuidler script, you can create an unlimited number of contexts for a document.

https://api.onlyoffice.com/docbuilder/integrationapi/usingdocbuilderfile
```js
builder.CreateFile("docx");
  ...
  smt
  ...
builder.CloseFile();
```

**Comment by Jelly7655** [comment]
> 1. In the context of a docbuidler script, you can create an unlimited number of contexts for a document.
> 
> https://api.onlyoffice.com/docbuilder/integrationapi/usingdocbuilderfile
> 
> ```js
> builder.CreateFile("docx");
>   ...
>   smt
>   ...
> builder.CloseFile();
> ```
> 
> 2. Inside the context for the base document, convert each necessary document into json
> 
> https://api.onlyoffice.com/docbuilder/textdocumentapi/apiparagraph/tojson
> 
> 3. Pass the paragraph json to the new document context via [GlobalVariable](https://api.onlyoffice.com/docbuilder/howitworks/globalvariable#:~:text=What%20you%20need%2C%20is%20to%20create%20a%20variable%20in%20the%20first%20opened%20or%20created%20file%20using%20the%20GlobalVariable%20method%2C%20e.g.%3A)
> 4. Convert the paragraph object from json and Push it into a new document
> 
> ```js
> var oParagraphFromJSON = Api.FromJSON(json);
> oDocument.AddElement(0, oParagraphFromJSON);
> ```
> 
> 5. Saving the received document
> 
> ```js
> builder.SaveFile("docx", "StrokeToJson.docx");
> builder.CloseFile();
> ```

ok, Thank you. By the way, how to split document by Headings?

**Comment by askonev** [comment]
In general, the checklist is similar. Header is a unique field of Section object. 

https://api.onlyoffice.com/docbuilder/textdocumentapi/apisection

In the source document you get all Sections. Convert them to json. Pass them to the children.

**Comment by Jelly7655** [comment]
> In general, the checklist is similar. Header is a unique field of Section object.
> 
> https://api.onlyoffice.com/docbuilder/textdocumentapi/apisection
> 
> In the source document you get all Sections. Convert them to json. Pass them to the children.
> 
> The difference is that you can't set Sections directly, but after conversion from json to an editor object, you can access Sections and iteratively transfer all elements to a new document.

I got it. Thank you.
