### ISSUE TITLE
Formula incorrect when open xls

### ISSUE THREAD

**Issue by zhangyinag** [ONLYOFFICE/DocumentServer#2569]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

expected: =SUM(A2:B2)
![origin](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/c3ac8340-d899-4a18-a5cd-b891d6acd9b1)

### Actual Behavior

when open the xls file in onlyoffice, the formula become incorrect, does't work also 
![actual](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/15ae69b1-528d-4f6b-8486-d3e082ee0e93)

### Additional information

upload the xls file use example service, will convert to xlsx automatic , also not correct 
![other](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/3046e344-c4ca-4065-8b7d-045a78c31fbe)

the origin xls file: 
[公式11.xls](https://github.com/ONLYOFFICE/DocumentServer/files/14108695/11.xls)

**Comment by LuckySpecialist** [comment]
Hi @zhangyinag!
According to the results of the check, this problem was fixed in release 8.0.
If it is still relevant to you, you can reopen issue again.
Thanks for the feedback.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
