### ISSUE TITLE
The spreadsheet alters the numerical value of cells

### ISSUE THREAD

**Issue by Golffies** [ONLYOFFICE/DocumentServer#2587]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.5.1 (543)

### Expected Behavior

- Numerical values are entered manually into a blank spreadsheet;
- The sum of these values is calculated at the bottom of the columns;
- The spreadsheet is saved locally in ODT or XLS format;
- The spreadsheet is reopened a few seconds later;
- The values entered in all columns remain the same as they were before the spreadsheet was closed;
- The sums at the bottom of all the columns remain the same.
![Capture d’écran 2023-12-07 à 12 37 08](https://github.com/ONLYOFFICE/DesktopEditors/assets/5718159/03f564f6-2df5-4b2f-b135-b9158d31fdb1)

### Actual Behavior

- Numerical values are entered manually into a blank spreadsheet;
- The sum of these values is calculated at the bottom of the columns;
- The spreadsheet is saved locally in ODT or XLS format;
- The spreadsheet is reopened a few seconds later;
- The values entered in certain columns remain the same as they were before the spreadsheet was closed;
- The values entered in certain other columns are all decremented by 1, without user intervention;
- The sums at the bottom of all the columns remain the same; they correspond to the sums of the column values before closing and reopening the worksheet.
![Capture d’écran 2023-12-07 à 12 35 43](https://github.com/ONLYOFFICE/DesktopEditors/assets/5718159/16b1d86a-de2d-4d41-8e42-d4eefee48fad)

### Reproduction Steps

- Create a blank spreadsheet in OnlyOffice;
- Enter data manually in columns;
- Apply the correct currency in accounting format to the relevant columns;
- Save the spreadsheet in ODT or XLS format;
- Reopen the spreadsheet.

### Additional information

During the initial entry of values and choice of formats for the columns, I was warned that an error had occurred, and that I should save my work in progress using the 'download' option. I could no longer modify the cells in the spreadsheet. I couldn't find the "download" option, so it probably doesn't apply to the desktop version of OnlyOffice.

I opened another spreadsheet, copied and pasted the values from the first to the second spreadsheet, and closed the first spreadsheet that had generated the error.

**Comment by rsnegirev** [comment]
Hi @Golffies problem was fixed in this commits https://github.com/ONLYOFFICE/sdkjs/commit/98e74fd30593f2791f67be68a3ceb521a9485cd9
https://github.com/ONLYOFFICE/core/commit/cf19a912ee82cba570a410ab72cca2f6665f87d4

Fixes will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
