### ISSUE TITLE
loss of connection when editing docs

### ISSUE THREAD

**Issue by alecplanet** [ONLYOFFICE/DocumentServer#259]
With multiple documents open I'm finding frequent occurrences where:

1) The file is locked and no changes can be made. Or,

2) A document will state there was a loss of connection after some amount of time.

Both of these cases require a screen refresh.

This screen refresh will take you back to the beginning of a document, causing you to return to your original location / page each time. This seems to happen frequently.

In one case this has resulted in a loss of data.

**Comment by ShockwaveNN** [comment]
Hi, sorry for late response. If issue still actual - please add logs and fill version information about DocumentServer

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
