### ISSUE TITLE
OO hangs when opening this .pttx file

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2591]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.0.0

### Expected Behavior

OO should be able to open this .pptx file.

### Actual Behavior

OO hangs when opening this .pptx file.

### Reproduction Steps

Steps:
- try to open the attached pptx file with OO
=> OO hangs

[bug-OO-hangs-opening.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/14210434/bug-OO-hangs-opening.pptx)

**Comment by ElenaMaaya** [comment]
Hello @parrenin! I have a good news! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
