### ISSUE TITLE
For PDF files,  Can we able to add comments eventhough edit feature is yet to be implemented ?

### ISSUE THREAD

**Issue by Ragul29** [ONLYOFFICE/DocumentServer#2597]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Few queries I have:

1) Can we able to add comments and save for a PDF in onlyoffice pdf editor?

Note: I knew that edit option for pdf is still in the upcoming feature list.

**Comment by Gingetsu** [comment]
Hello, @Ragul29!
Yes, we can to add comments and save for a PDF in onlyoffice pdf editor. Try to upgrade to the latest version.

**Comment by Gingetsu** [comment]
Could you tell me the system and version of your system, please?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
