### ISSUE TITLE
No Touch Support?

### ISSUE THREAD

**Issue by Xarcell** [ONLYOFFICE/DocumentServer#26]
It seems the document editor and spreadsheet do not have proper touch screen support? At least it doesn't on IE touch/surface/winPhone. Anything I touch to focus on doesn't bring up the digital keyboard.

I also noticed quirky behavior using touch screen on the project and calendar apps. I'll touch some an input field, it'll focus on it, then unfocus, then focus, and so on in a unending repeated pattern. I have to close out the tab to stop it.

**Comment by trofim24** [comment]
You can open editors with `type=mobile`. You can see it in a new [integration example](https://github.com/ONLYOFFICE/document-server-integration).
