### ISSUE TITLE
Predefined mail merge source

### ISSUE THREAD

**Issue by str** [ONLYOFFICE/DocumentServer#2604]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

We have an online HR system that can export contacts to use in the mail merge "From URL" option.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/123817/4b9785e7-5489-41b5-a25c-3885c0d6f8db)

Is it possible to pass a variable to OnlyOffice to have preset option? something like 

- mailMerge.appendFromSource('https://internalHR/contacts.csv', 'From HR system');

Thank you.

**Comment by XDmitryK** [comment]
@str Hi
I don't quite understand what you mean.
Do you want a certain variable with a file recipients to always be loaded when creating a new document?

**Comment by str** [comment]
When you click the mail-merge button, it shows you 2 options
- From File
- From URL

We would like the system to have a 3rd option that says 'From company HR system', and when the user selects it, the editor would automatically load the recipients and all other mail-merge fields from a spreadsheet in a specific URL.

We also noticed that the system only allows you to load 100 records.

We are loading the editor  via `new DocsAPI.DocEditor('editor', config);`   It would be great if we could pass a flag to the config variable, where we can append that 3rd option to the mail-merge dropdown. Something similar to:

```js
config.editorConfig.mailMegeSources = [
    {'label': 'From HR system,   1...100', 'https://hr.system/contacts?limit=100&page=1'},
    {'label': 'From HR system, 101...200', 'https://hr.system/contacts?limit=100&page=2'},
    {'label': 'From HR system, 201...300', 'https://hr.system/contacts?limit=100&page=3'}
];
// generate JWT with new mailMegeSources
// and then pass the config to the editor
var docEditor = new DocsAPI.DocEditor('editor', config);
```

Would something like that be possible? 

We are planning on building a plugin if this is not possible.

**Comment by XDmitryK** [comment]
@str
1. In your case, this method may help you. 
https://api.onlyoffice.com/editors/config/events#onRequestSelectSpreadsheet
2. In the case of a number of 100 recipients, it was designed this way. I will clarify whether it is possible to expand the number of recipients.

**Comment by str** [comment]
We ended creating our own plugin.
