### ISSUE TITLE
error: could not create new file from template

### ISSUE THREAD

**Issue by julbroa** [ONLYOFFICE/DocumentServer#2605]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.0.0.9

### Expected Behavior

When creating a new file, whether you select the empty template or any other, the file is created and displayed in the editor

### Actual Behavior

When creating a new file, the window to select the template appears, whichever one I select, the error described appears and it closes. Although if the file is created I have to use it among the files and open it, it even applies the template I select.

### Reproduction Steps

1.- In the file selector a new one is created
2.- Select a template to use
3.- when clicking on the create button the error appears and the template selector closes
![Captura de pantalla 2024-02-10 183057](https://github.com/ONLYOFFICE/DocumentServer/assets/105558823/3f7e37ff-af02-4472-ab08-904e45c28fa4)

**Comment by LuckySpecialist** [comment]
Hi @julbroa, please specify which cloud server you are using and its exact version?

**Comment by julbroa** [comment]
ubuntu server 20.04

**Comment by LuckySpecialist** [comment]
> ubuntu server 20.04

This is an operating system and I need to know which cloud storage is used with our DocumentServer.

**Comment by LuckySpecialist** [comment]
> Tipo: Máquina virtual
> Tamaño: VPS M
> CPU: 2 vCore
> RAM: 4 GB
> Soporte de datos: 160 GB SSD

This is the hardware configuration of your stand, you need to specify which DMS you have installed to work with the ONLYOFFICE Document Server.

**Comment by julbroa** [comment]
Nextcloud 27.1.7  ???

**Comment by LuckySpecialist** [comment]
Hi @julbroa!
I just checked Nextcloud 27.1.7 + ONLYOFFICE Document Server 8.1.0.27 on my test stand and didn't find a problem.
Please describe the scenario of how you set up your stand.
Specify the connector application and its version, how the document server was installed and connected, provide a screenshot of the settings in the connector.

**Comment by julbroa** [comment]
I use in the version of nextcloud that already specified the onlyoffice connector version 8.2.4, the document server was installed according to the guide specified on this page: https://helpcenter.onlyoffice.com/installation/docs-community-install- ubuntu.aspx. The server I use is hosted on a vps.

![imagen](https://github.com/ONLYOFFICE/DocumentServer/assets/105558823/01e11d97-898b-4420-a3a8-9c468c647be3)

**Comment by LuckySpecialist** [comment]
At first glance, the configuration looks correct.
Do you have a problem only when creating new documents from templates or something else?
Do previously created/uploaded documents open without errors?

**Comment by julbroa** [comment]
The problem only appears when you want to generate new files and since I installed and made the connection the problem appeared

**Comment by LuckySpecialist** [comment]
Hi @julbroa!
I'm sorry for the long break. Is the problem still relevant to you or not?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
