### ISSUE TITLE
Paste pitctures could not display contents

### ISSUE THREAD

**Issue by WangTiankunKenny** [ONLYOFFICE/DocumentServer#2609]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.4.1.36

### Expected Behavior

paste picture from another files through web interface could display pictures normally

### Actual Behavior

Pasting pictures shows big red cross.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/47009465/5fef0772-3e4f-4ce3-ae85-336d5b0d7acc)

### Reproduction Steps

1. copy picture from OO  doc file from Web interface,
2. paste picture to another doc file from We interface
3. then it shows a big red X 

### Additional information

1. it is under NextCloud Platform
2. sometimes  when i close this file and open this file again, it shows the picture normally.

**Comment by TatianaKirillova** [comment]
Hello @WangTiankunKenny!
Thank you for your request! Check if your problem persists in the new version 8.0.1. If it repeats, please attach a file with the picture you are copying!

**Comment by WangTiankunKenny** [comment]
its web browser embed with Next Cloud platform, i think its 8.x.x.

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny please attach a file with the picture you need to copy

**Comment by WangTiankunKenny** [comment]
i dont think that's the matter of the picture, i've tried different formats and none of them works, just random picture could cause this problem.

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny 
I can't reproduce your problem. Which version of NextCloud Platform is used? And please check your browser version

**Comment by WangTiankunKenny** [comment]
The Nextcloud platform Version is 27.1.7, and I am using Firfox, the version is 123.0.1。
Let me explain this again, hopefully it would help. For example, I am online editing file A and file B, and trying to copy a picture from file A to file B, then it'll show a red "X". HOWEVER, if I refresh the file B, the picture show the correct picture.

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny I can't reproduce the problem, please attach a file from where I can copy the picture to reproduce the problem

**Comment by WangTiankunKenny** [comment]
![2024-03-27_10-56](https://github.com/ONLYOFFICE/DocumentServer/assets/47009465/97202154-1b04-425f-a908-6a00c73de903)
right before i upload this picture, I tested again and it still shows the same issue, ,make sure once you drag the picture to onlyoffice online edit page, COPY that picture to another onlyoffice online edit page,

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny  Thank you! Do you copy using hotkeys? Ctrl+C Ctrl+V?

**Comment by WangTiankunKenny** [comment]
probably I right click to copy the picture, and Ctrl + V to paste

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny 
Please send me a docx file with a picture inside.

**Comment by WangTiankunKenny** [comment]
what is that file for? still couldn't reproduce the issue?

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny Yes. Unfortunately, this failed.

**Comment by WangTiankunKenny** [comment]
[蝴蝶谷打印.docx](https://github.com/ONLYOFFICE/DocumentServer/files/14787051/default.docx)
try to upload this file into nextcloud and open online editing, Ctrl + C the picture inside of the file and paste(Ctrl + V) to another (or create a new file)

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny thanks!

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny Are you using https://apps.nextcloud.com/apps/documentserver_community as your version of the Nextcloud platform? And please send a screenshot of the document editor version - it can be viewed by clicking the "i" button on the left toolbar.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/72191601/f3e13661-d269-4fa1-8351-a0df3cab221a)




And you can also take a screenshot of your connector settings (Administration Settings - Administration - ONLYOFFICE)

**Comment by WangTiankunKenny** [comment]
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/47009465/5bc05a28-1453-49c7-b970-a9317ddb6e69)
Here,

**Comment by TatianaKirillova** [comment]
@WangTiankunKenny Please take another screenshot of your connector settings (Administration Settings – Administration – ONLYOFFICE). Or do you know that you are using https://apps.nextcloud.com/apps/documentserver_community as your version of the Nextcloud platform?

You need to update your ONLYOFFICE editor version

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
