### ISSUE TITLE
`service nginx start` fails on centos 7

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#261]
**What is the current behavior?**
1. Install `onlyoffice-documentserver` on Centos 7 using https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx
2. On step `sudo service nginx start` there will be error for starting nginx

**DocumentServer version:** 5.1.0.115

**Operating System:** Centos 7 (DigitalOcean)

**Comment by raphson93** [comment]
but someone it still can view others document except docx if you didnt restart the nginx service after updating to the latest document server

**Comment by agolybev** [comment]
@ShockwaveNN, it happend with wrong config file in epel nginx package.
Try replacing default nginx config `/etc/ngnix/ngnix.conf` with config from nginx repo:
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

**Comment by bauerheim** [comment]
Same here! Get 5.1.0 Update via yum update with additional nginx update to Version 1.12.2.2
Bad Gateway

**Comment by raphson93** [comment]
Hi @agolybev are we supposed to have onlyoffice-http.conf in /etc/nginx/includes before we start the nginx service? because after install the latest document server, nginx failed to start because it said the conf file was missing

**Comment by raphson93** [comment]
@lvsbird same with nginx-1.13.10

**Comment by raphson93** [comment]
hi @agolybev still the same after replacing :(

**Comment by agolybev** [comment]
Hi @raphson93 it isn't your issue. I think you have another problem.

**Comment by lvsbird** [comment]
It's not a Problem with nginx. I tested it with current Snapshot. Performed the OnlyOffice Update from 5.0.7 to 5.1.0 without nginx update Package.
After Update Documents will not be opened.
Log entry from /var/log/onlyoffice/documentserver/nginx.error.log

[error] 1199#1199: *2 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/help/de/Contents.json" failed (2: No such file or directory), client: 192.168.195.116, server: , request: "GET /2018-01-11-12-46/web-apps/apps/documenteditor/main/resources/help/de/Contents.json HTTP/1.1", host: "[deleted]:8999", referrer: "[deleted]:8999/2018-01-11-12-46/web-apps/apps/documenteditor/main/index.html?_dc=2018-01-11-12-46&lang=de&customer=ONLYOFFICE&frameEditorId=iframeContainer"

**Comment by lvsbird** [comment]
Tried to restart now nginx after upgrading Onlyoffice-Documentserver-IE.
ERROR nginx: [emerg] open() "/etc/nginx/includes/onlyoffice-http.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/onlyoffice-documentserver.conf:1

Seems the update has changed or deleted existing config-files

**Comment by lvsbird** [comment]
Performed a single nginx update to current version, replaced default nginx config /etc/ngnix/nginx.conf with config from nginx repo. OnlyOffice 5.0.7 works fine.

After Upgrading OnlyOffice to 5.1.0 error appears as mentioned above

**Comment by lvsbird** [comment]
Looked at the Centos Service-Status from supervisord before and after upgrade.
Supervisord is running but only with only one task.
Before Upgrade there are many tasks.
Docservice at Port 8000 isn't running after upgrade.

**Comment by lvsbird** [comment]
Folder /etc/nginx/conf.d
ln -s /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-documentserver-common.conf onlyoffice-documentserver-common.conf
ln -s /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-documentserver-docservice.conf onlyoffice-documentserver-docservice.conf
ln -s /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-documentserver-spellchecker.conf onlyoffice-documentserver-spellchecker.conf
ln -s /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-http.conf onlyoffice-http.conf

**Comment by raphson93** [comment]
hi @ShockwaveNN 

can this issue resolve as fast as possible ?
because our company productions are using it..
Thank you

**Comment by raphson93** [comment]
hi @lvsbird 

did you run the documentserver-configure.sh after update ?
can let me know the output ?
thanks

**Comment by dnutan** [comment]
Just want to confirm what @lvsbird found out. Updating from 5.0.7 to 5.1.0 the rpm package did this (excerpt of most meaningful actions):
```
new directory : /etc/onlyoffice/documentserver/nginx
	number of new files		 : 7
new directory : /etc/onlyoffice/documentserver/supervisor
	number of new files		 : 6
deleted file : /etc/nginx/conf.d/onlyoffice-documentserver-ssl.conf.template
deleted file : /etc/nginx/conf.d/onlyoffice-documentserver.conf.template
deleted file : /etc/nginx/includes/onlyoffice-documentserver-common.conf
deleted file : /etc/nginx/includes/onlyoffice-documentserver-docservice.conf
deleted file : /etc/nginx/includes/onlyoffice-documentserver-spellchecker.conf
deleted file : /etc/nginx/includes/onlyoffice-http.conf
deleted file : /etc/supervisord.d/onlyoffice-documentserver-converter.ini
deleted file : /etc/supervisord.d/onlyoffice-documentserver-docservice.ini
deleted file : /etc/supervisord.d/onlyoffice-documentserver-gc.ini
deleted file : /etc/supervisord.d/onlyoffice-documentserver-metrics.ini
deleted file : /etc/supervisord.d/onlyoffice-documentserver-spellchecker.ini
deleted file : /etc/supervisord.d/onlyoffice-documentserver.ini
changed symbolic_link : /etc/nginx/conf.d/onlyoffice-documentserver.conf
```
Whereas a yum reinstall of 5.1.0 brought:
```
new symbolic_link : /etc/nginx/includes/onlyoffice-documentserver-common.conf
new symbolic_link : /etc/nginx/includes/onlyoffice-documentserver-docservice.conf
new symbolic_link : /etc/nginx/includes/onlyoffice-documentserver-spellchecker.conf
new symbolic_link : /etc/nginx/includes/onlyoffice-http.conf
new symbolic_link : /etc/supervisord.d/onlyoffice-documentserver-converter.ini
new symbolic_link : /etc/supervisord.d/onlyoffice-documentserver-docservice.ini
new symbolic_link : /etc/supervisord.d/onlyoffice-documentserver-gc.ini
new symbolic_link : /etc/supervisord.d/onlyoffice-documentserver-metrics.ini
new symbolic_link : /etc/supervisord.d/onlyoffice-documentserver-spellchecker.ini
new symbolic_link : /etc/supervisord.d/onlyoffice-documentserver.ini
```

**Comment by raphson93** [comment]
hi @ShockwaveNN, the problem has been resolved and the documentserver is running fine thanks to @agolybev

**Comment by WladyX** [comment]
This happens also for the Debian repo, can you please update that package also?
Thank you very much!

**Comment by ShockwaveNN** [comment]
@WladyX Hi, what exactly `This happens also for the Debian repo`?
There is several issues in this thread

**Comment by WladyX** [comment]
Apr 04 11:58:03 onlyoffice systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 04 11:58:03 onlyoffice nginx[56787]: nginx: [emerg] open() "/etc/nginx/conf.d/onlyoffice-documentserver.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:61
Apr 04 11:58:03 onlyoffice nginx[56787]: nginx: configuration file /etc/nginx/nginx.conf test failed

The symlink in /etc/nginx/conf.d is broken.

**Comment by ShockwaveNN** [comment]
@WladyX to be sure - this is after upgrade 5.0.7 -> 5.1.0?
Did you use custom config?

**Comment by WladyX** [comment]
this is a fresh install, no sure what custom config is.

**Comment by WladyX** [comment]
Ubuntu 18.04, yes fresh install.

**Comment by ShockwaveNN** [comment]
@WladyX Oh, it will be better if mention that earlier, what you install it on pre-release software

**Comment by WladyX** [comment]
I will try 16.04 and get back to you, I suspect the /etc/nginx/conf.d/onlyoffice-documentserver.conf symlink will also be broken.

**Comment by ShockwaveNN** [comment]
@WladyX  it was definitely working 6 days ago while I created this issue, but I check on ubunut 16.04 also

**Comment by ShockwaveNN** [comment]
@WladyX  just checked it on 16.04 by building it via [this](https://github.com/onlyoffice-testing-robot/documentserver-install-from-manual) `Dockerfile` and everything seems good.
Still working on 18.08 BTW

**Comment by WladyX** [comment]
I can confirm it works ok on 16.04.
Thanks!

**Comment by dstaykov** [comment]
After Upgrade from 5.0.7-38 to 5.1.2-9 on Centos 7 the symlinks are missing in /etc/nginx/conf.d/. I had to run 
documentserver-configure.sh
I also had to reconfigure https connection do documentserver. On the web page everything looks fine BUT, when I try to connect it with OwnCloud plugin in converter/out.log says:
onlyoffice ;code:UNABLE_TO_VERIFY_LEAF_SIGNATURE;connect:undefined;(id=conv_check_2077101851_docx) Error: unable to verify the first certificate.

It looks like that DocumentServer cannot verfy certificate installed in owncloud server. Which is strage because with 5.0.7-38 it works fine. We ar using public signed wildcard certificate.

**Comment by raphson93** [comment]
is the problem resolve ?
should we close this issue ?

**Comment by ShockwaveNN** [comment]
@raphson93 Yeah, we updated instruction at https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

**Comment by sergiomb2** [comment]
onlyoffice-documentserver.conf.template misses `server_name _;` as it have onlyoffice-documentserver-ssl.conf.template 

```
diff onlyoffice-documentserver.conf.template onlyoffice-documentserver.conf.old2  -up 
--- onlyoffice-documentserver.conf.template     2018-12-21 22:27:45.000000000 +0000
+++ onlyoffice-documentserver.conf 2019-01-10 19:00:03.147480165 +0000
@@ -2,7 +2,8 @@ include /etc/nginx/includes/onlyoffice-h
 server {
   listen 0.0.0.0:80;
   listen [::]:80 default_server;
+  server_name _;
   server_tokens off;
   
   include /etc/nginx/includes/onlyoffice-documentserver-*.conf;
-}
\ No newline at end of file
+}
```

**Comment by dstaykov** [comment]
the problem is not seen in current version at out installation we skipped 5.1.2-9
