### ISSUE TITLE
edit xls save fail  

### ISSUE THREAD

**Issue by zhangyinag** [ONLYOFFICE/DocumentServer#2620]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

when edit xls, will save successfully, this worked at 7.5.1, when upgrade to 8.0.1, this function has problem 
![001](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/5077a879-ce4e-4e2b-989f-401e13b1b7e0)
![002](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/67165ff6-2ccb-464c-8fd8-a419248a1160)

### Actual Behavior

should save xls successfully

### Additional information

At 7.5.1, this worked screenshot as below: 
![003](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/f81b3cf3-1cd5-49e3-9c37-46835100317c)
![004](https://github.com/ONLYOFFICE/DocumentServer/assets/13493363/b46c61f3-38eb-455e-8cf0-290431c03a2e)

**Comment by VladimirProkofiev52** [comment]
Hello! @zhangyinag 
I couldn't replicate your issue.
Could you please confirm if the problem occurs with any XLS file or just with a specific one?
Please send the file where the issue is happening.
Could you please outline step-by-step instructions on how to reproduce the problem?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
