### ISSUE TITLE
Conditional formatting not working for .ods files

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2624]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

The formatting should be retained as expected

### Actual Behavior

Conditional formatting functions are not retained after saving and reopening the file.

### Reproduction Steps

Apply any conditional formatting on .ods file for e.g: Text, Date bars
Save and Reopen the edited copy
The formatting is either missing or not present properly.

**Comment by rsnegirev** [comment]
Hi @Maaayank 

I found a problem with Date formatting but not with Text. Can you please describe it more detailed?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
