### ISSUE TITLE
Table layout changes in the received edited copy of .ods format file.

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2626]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Table layout should be same as configured before closing the file. 

### Actual Behavior

Table layout is not same as configured before closing the file.

### Reproduction Steps

    Open .ods format file in the browser.
    Insert Table of required number of rows and columns.
    Save and close the file.
    Open the received edited copy of the file and verify the size of table.

**Comment by maruacat** [comment]
Hello @Maaayank! Thank you for your request
I didn't completely understand your problem. Do you mean the table formatting, which is set in the Insert tab >  Table and is displayed in the form of cells with different fill colors, or the number of cells and size of the cells has changed in your table? I would be very grateful if you could attach a file with an example of the problem

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
