### ISSUE TITLE
Slide number is not visible in received edited copy of .odp format file.

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2627]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Slide number should be displayed on the slide

### Actual Behavior

Slide number is not displayed on the slide

### Reproduction Steps

    Open .odp format file in browser.
    Insert slide number in the file using 'Slide number' option present under 'Insert' tab.
    Save and close the file.
    Open the received edited copy of the file and observe the slide number.

**Comment by ElenaMaaya** [comment]
Hello @Maaayank !
Thank you for report!
I can confirm that the problem exists. I created ticket 66821  in our  issue tracker.

**Comment by ElenaMaaya** [comment]
Hello @Maaayank! I have a good news! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
This has been fixed (https://github.com/ONLYOFFICE/core/commit/db3d665f8cc04bc78bca5903ac93975bccf8adaf) and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
