### ISSUE TITLE
W: http://archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by quelo1972** [ONLYOFFICE/DocumentServer#263]
I followed instructions from
[http://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx](http://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx)
When I do apt update && apt upgrade I have this warning

`W: http://archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)`

It is normal or an issue?

**DocumentServer version:** 5.1.0-115

**Operating System:** UBUNTU SERVER 16.04 LTS

**Comment by ShockwaveNN** [comment]
Yeah, it's a known issue.
Soon we will  remove line about `echo "deb http://archive.ubuntu.com/ubuntu precise main universe multiverse" | sudo tee -a /etc/apt/sources.list` from instruction, it's not needed since release of 5.1.0

Thanks anyway

**Comment by ShockwaveNN** [comment]
We remove entry about using this old repo from [instruction](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx). Thanks for noticing.
