### ISSUE TITLE
Please support animation for single bullet points in a list

### ISSUE THREAD

**Issue by Photon89** [ONLYOFFICE/DocumentServer#2630]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

It has been mentioned in https://github.com/ONLYOFFICE/DesktopEditors/issues/655 already, but the issue has been closed in the mean time. Though animations have been implemented in general, as follows from #348, it is still impossible to make bullet points in a list appear one by one, as it is customary in other slide presenting software.

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1962.
