### ISSUE TITLE
Vertical textbox is converted into horizontal textbox in the edited copy of the .odp format file

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2632]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Vertical textbox should behave as vertical textbox.

### Actual Behavior

Vertical textbox is converted into horizontal textbox when edited and saved .odp format file is opened again.

### Reproduction Steps

    Open .odp format file in the browser.
    Insert Vertical textbox using 'Textbox' option present under 'Home' tab.
    Save and close the file.
    Open the same file/edited copy of the file received on mail.

**Comment by ElenaMaaya** [comment]
Hello @Maaayank! I have a good news! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
This has been fixed (https://github.com/ONLYOFFICE/core/commit/d0adabc5f7ee99de8cf6a817e5560aece3a80aa5) and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
