### ISSUE TITLE
'Cross Reference' functionality do not work in .odt format files.

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2636]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Cross reference hyperlink should redirect to configured file location.

### Actual Behavior

Inserted cross reference hyperlink in .odt format file do not redirect to the configured location in the file.

### Reproduction Steps

    Open .odt format file in browser and insert 'Cross Reference' using option present under 'References' tab.
    Save and close the file.
    Open the same file.
    Press ctrl and click on hyperlink.

**Comment by TatianaKirillova** [comment]
Hello, @Maaayank  Thanks for your request!
I can confirm that the problem exists. I created issue #66798 for your problem.

**Comment by TatianaKirillova** [comment]
Hello @Maaayank! I hasten to inform you that the problem will be fixed in the next release [by commit](https://github.com/ONLYOFFICE/core/commit/d81e70cfee7dc3976855dbb634a83f4b56dc94d3
). Please stay tuned for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
