### ISSUE TITLE
Track changes option when set to 'ON for me and everyone' do not work properly for every other user in .odt and .rtf format files.

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2637]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Track changes option should be set to 'On for me and everyone' for user2. Changes made by user2 should be tracked. 

### Actual Behavior

When user1 sets Track changes option to 'ON for me and everyone', track changes option is not enabled for other users. Changes made by users other than user1 are not tracked.

### Reproduction Steps

    Open protected .odt/.rtf format file with user1 and set 'Track Changes > On for me and everyone' option present under 'Collaboration' tab.
    Edit file.
    Save and close the file.
    Open the same protected file with user2.
    Verify settings configured for 'Track Changes'.

**Comment by XDmitryK** [comment]
@Maaayank Hi
What do you mean by protected file? Are you using a password for the file?
This problem does not occur in a clean file. Can you attach your file here?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
