### ISSUE TITLE
Format of line number changes after file with .odt format is reopened after editing

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2639]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Line numbering format should be 'Restart each page'.
File contains continuous line numbering instead of restarting line numbering for each page.

### Actual Behavior

Line numbering configuration is not saved for .odt file. Line numbering format configured as 'Restart each page' changes to 'Continuous' after saving & opening the same file. 

### Reproduction Steps

    Open .odt format file in browser.
    Click on 'Layout > Line Numbers > Restart each page'
    Line numbering should start from 1 for each page.
    Save and close the file.
    Open the same file in the browser.
    Observe the line numbering format of the file.

**Comment by maruacat** [comment]
Hello, @Maaayank 
I can confirm - this is bug, so I created issue #67782.
Thank you for the report.

**Comment by maruacat** [comment]
Hello!
I have great news. We have fixed the problem https://github.com/ONLYOFFICE/core/commit/0439347bc3d006a9e3595ea1483b4cf73ab0e631 and it will be available after the release of the new version - 8.1.0.
Have a good day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
