### ISSUE TITLE
NEXTCLOUD ONLYOFFICE integration - Error when trying to connect (Bad Request or timeout error)

### ISSUE THREAD

**Issue by quelo1972** [ONLYOFFICE/DocumentServer#264]
I followed instructions from
http://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx
and then I followed the instruction to activate teh ssl encription and now the documentserver is listening correctly on thee 443 port with ssl encryption

Now I want to to integrate nextcloud with onlyoffice. I've successfully installed in other machine nextcloud with ssl support I installed and activated the ONLYOFFICE app, into NEXTCLOUD, but when go to configure the app inserting `https://<ipaddress-of-onlyoffice-documentserver>/` I have an error that appear to the upper part of the browser

`Error when trying to connect (Bad Request or timeout error)`

and the integration doesn't work.

Any idea?

DocumentServer version: 5.1.0-115
Operating System: Both UBUNTU SERVER 16.04 LTS

**Comment by hamslicejumbomice** [comment]
Same problem, Did you ever figure it out?

What does your log file show?

**Comment by quelo1972** [comment]
I solved usin letsencrypt!

**Comment by hamslicejumbomice** [comment]
I'd be happy is you shared more about how you fixed it exactly :)

**Comment by agolybev** [comment]
Hi @hamslicejumbomice? Do you use self-signed certificate?

**Comment by quelo1972** [comment]
No letsencrypt :)

**Comment by agolybev** [comment]
Hi @quelo1972, I think NextCloud server can't validate documentserver SSL certificate. Could you check NextCloud log for SSL error?

**Comment by quelo1972** [comment]
I solved using letsencrypt :)

**Comment by agolybev** [comment]
@quelo1972, I'm sorry, I wanted to write it to @hamslicejumbomice. 
But how did you fix problem? By letsencrypt certificate? And what kind of certificate did you use before?

**Comment by quelo1972** [comment]
Before I used self signed certificate. I solved by letsencrypt.

**Comment by agolybev** [comment]
@quelo1972, thanks a lot for reply.  I think the issue may be closed.
