### ISSUE TITLE
"Cannot find module './editorDataRedis' " in err.log

### ISSUE THREAD

**Issue by mingpen** [ONLYOFFICE/DocumentServer#2647]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.0.0

### Expected Behavior

start process successfully when using the program which is builded from open source by ourself.

### Actual Behavior

can not location ` editorDataRedis.js ` file which is listed in https://github.com/ONLYOFFICE/server/blob/master/DocService/package.json#L52

pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module './editorDataRedis'
Require stack:
- /snapshot/server/DocService/sources/DocsCoServer.js
- /snapshot/server/DocService/sources/canvasservice.js
- /snapshot/server/DocService/sources/wopiClient.js
- /snapshot/server/FileConverter/sources/converter.js
- /snapshot/server/FileConverter/sources/convertermaster.js

### Reproduction Steps

1. clone open source 
2. build
3. edit conf  with **`redis`** & run process

**Comment by igwyd** [comment]
Hello @mingpen, sorry for the late reply. Did you use this [build_tools](https://github.com/ONLYOFFICE/build_tools?tab=readme-ov-file#build_tools) compilation manual?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by mingpen** [comment]
> Hello @mingpen, sorry for the late reply. Did you use this [build_tools](https://github.com/ONLYOFFICE/build_tools?tab=readme-ov-file#build_tools) compilation manual?

https://github.com/ONLYOFFICE/build_tools/issues/873
