### ISSUE TITLE
After Linux update Onlyoffice document server does not work

### ISSUE THREAD

**Issue by TerjeTM** [ONLYOFFICE/DocumentServer#265]
Hello everybody,
I need urgent help!

Current versions:
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-87-generic x86_64)
Nextcloud 13.0.1
Apache (current version)
nginx version: nginx/1.10.3 (Ubuntu)
Onlyoffice Documentserver 5.0.7 (i suspect)
PHP 7.0.28
DB MYSQL: 5.7.21
Nodejs: v6.14.1
Java Version:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

redis-status = up and running
rabbitmq-server = up and running
apache2-status = up and running (nextcloud running)

-------------------------------------------------------------------------------------------------------

After Linux update and Nextcloud update to version 13.0.1, onlyoffice-document server stops working.
The cloud (Nextcloud) itself works without problems. When updating Linux, I had no mistakes.

I tried to reinstall the documents server. Unfortunately without success. He can not even uninstall.

please refer:
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/api/documents# /etc/init.d/apache2 stop
[ ok ] Stopping apache2 (via systemctl): apache2.service.
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/api/documents# sudo apt purge onlyoffice-documentserver
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  cabextract fonts-crosextra-carlito fonts-dejavu fonts-liberation fonts-opensymbol fonts-takao-gothic fonts-takao-pgothic gcc-4.8-base gconf-service gconf-service-backend gconf2-common icu-devtools libasan0 libasan2 libatomic1
  libboost-regex-dev libboost-regex1.58-dev libboost-regex1.58.0 libboost1.58-dev libc-dev-bin libc6-dev libcilkrts5 libfontenc1 libgcc-4.8-dev libgcc-5-dev libgconf-2-4 libgconf2-4 libglu1-mesa libgomp1 libgtkglext1 libicu-dev libitm1
  liblsan0 libmpx0 libpangox-1.0-0 libquadmath0 libstdc++-4.8-dev libstdc++-5-dev libtsan0 libubsan0 libxaw7 libxfont1 libxkbfile1 libxmu6 libxss1 linux-libc-dev manpages-dev pwgen python-meld3 python-pkg-resources supervisor
  ttf-mscorefonts-installer x11-xkb-utils xfonts-base xfonts-encodings xfonts-utils xserver-common xvfb
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden Pakete werden ENTFERNT:
  onlyoffice-documentserver*
0 aktualisiert, 0 neu installiert, 1 zu entfernen und 6 nicht aktualisiert.
Nach dieser Operation werden 776 MB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] j
(Lese Datenbank ... 106360 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von onlyoffice-documentserver (5.1.0-115) ...
Preparing for shutdown, it can take a lot of time, please wait.../var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:202
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "services.CoAuthoring.requestDefaults" is not defined
    at Config.get (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:202:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:48:33)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/pubsubRabbitMQ.js:14:13)
Done
/var/lib/dpkg/info/onlyoffice-documentserver.prerm: 23: /var/lib/dpkg/info/onlyoffice-documentserver.prerm: DS_COUNT: not found
dpkg: Fehler beim Bearbeiten des Paketes onlyoffice-documentserver (--purge):
 Unterprozess installiertes pre-removal-Skript gab den Fehlerwert 127 zurück
Fehler traten auf beim Bearbeiten von:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/api/documents# sudo rm -rf /var/www/onlyoffice
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/api/documents# sudo rm -rf /etc/onlyoffice/documentserver
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/api/documents# sudo apt install onlyoffice-documentserver
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
»onlyoffice-documentserver« ist bereits die neuste Version (5.1.0-115).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  cabextract fonts-crosextra-carlito fonts-dejavu fonts-liberation fonts-opensymbol fonts-takao-gothic fonts-takao-pgothic ttf-mscorefonts-installer
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 6 nicht aktualisiert.

------------------------------------------------------------------------

I tried the following (History):
724  locate nextcloud.log
  725  cat /var/www/nextcloud.inspiredweb.ch/data/nextcloud.log
  726  cat
  727  cat /data/nextcloud.inspiredweb.ch_data/nextcloud.log
  728  cd /var/www/nextcloud.inspiredweb.ch/apps/
  729  ls
  730  cd onlyoffice/
  731  ls
  732  cat settings.php
  733  cd /etc/init.d/
  734  ls
  735  /etc/init.d/redis-server status
  736  /etc/init.d/rabbitmq-server status
  737  cd /
  738  cat /etc/apache2/ports.conf
  739  systemctl status redis-server
  740  systemctl status rabbitmq-server
  741  node -v
  742  /etc/init.d/apache2 restart
  743  exit
  744  cat /var/log/nginx/nginx_error.log
  745  cd /var/log/nginx/
  746  ls
  747  cat error.log
  748  cd ..
  749  ls
  750  cd onlyoffice/
  751  ls
  752  cd documentserver
  753  ls
  754  cat nginx.error.log
  755  cd /var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/
  756  ls
  757  ls -la
  758  cd ..
  759  ls
  760  cd /
  761  sudo apt-get update
  762  sudo apt-get upgrade
  763  cd /var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/
  764  ls
  765  cd /
  766  sudo apt-get update
  767  sudo apt-get upgrade
  768  reboot -n now
  769  java -version
  770  node -v
  771  curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  772  sudo apt install nodejs
  773  systemctl status redis-server
  774  systemctl status rabbitmq-server
  775  /etc/init.d/apache2 stop
  776  /etc/init.d/apache2 start
  777  /etc/init.d/apache2 stop
  778  sudo apt-get update
  779  sudo apt install onlyoffice-documentserver
  780  /etc/init.d/apache2 start
  781  cd /var/log/
  782  ls
  783  cd onlyoffice/
  784  ls
  785  cd documentserver
  786  ls
  787  cat nginx.error.log
  788  ls
  789  cd docservice/
  790  ls
  791  cat err.log
  792  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys XXXXXYYYYYY
  793  sudo apt reinstall onlyoffice-documentserver
  794  sudo apt re-install onlyoffice-documentserver
  795  sudo apt-get update
  796  sudo apt-get upgrade
  797  echo "deb http://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list
  798  ls
  799  cat out.log
  800  cat /etc/apache2/ports.conf
  801  cd /var/log/supervisor/
  802  ls
  803  cat supervisord.log
  804  cat /var/log/onlyoffice/documentserver/nginx.error.log
  805  cd /var/www/
  806  ls
  807  cd onlyoffice/
  808  ls
  809  cd Data/
  810  ls
  811  cd ..
  812  cd documentserver
  813  ls
  814  cd web-apps/
  815  ls
  816  cd apps/
  817  ls
  818  cd api/
  819  ls
  820  cd documents/
  821  ls
  822  /etc/init.d/apache2 stop
  823  sudo apt purge onlyoffice-documentserver
  824  sudo rm -rf /var/www/onlyoffice
  825  sudo rm -rf /etc/onlyoffice/documentserver
  826  sudo apt install onlyoffice-documentserver
  827  top
  828  kill 1888
  829  top
  830  sudo apt purge onlyoffice-documentserver
  831  sudo rm -rf /var/www/onlyoffice
  832  sudo rm -rf /etc/onlyoffice/documentserver
  833  reboot -n now
  834  /etc/init.d/apache2 stop
  835  cd /etc/
  836  ls
  837  cd onlyoffice/
  838  ls
  839  cd /
  840  sudo apt-get update
  841  sudo apt install onlyoffice-documentserver
  842  top
  843  sudo apt purge onlyoffice-documentserver
  844  sudo service nginx reload
  845  /etc/init.d/apache2 start
  846  cat /var/lib/dpkg/info/onlyoffice-documentserver.prerm
  847  supervisorctl stop
  848  stop supervisorctl
  849  supervisorctl stop onlyoffice-documentserver:
  850  sudo apt purge onlyoffice-documentserver
  851  sudo dpkg --configure -a
  852  sudo apt install onlyoffice-documentserver
  853  sudo apt autoremove
  854  sudo apt-get update
  855  /etc/init.d/apache2 stop
  856  sudo apt install onlyoffice-documentserver
  857  /etc/init.d/apache2 start
  858  systemctl status redis-server
  859  systemctl status rabbitmq-server
  860  Error: Cannot find module '/var/www/onlyoffice/documentserver/server/DocService/sources/shutdown.js'
  861  sudo dpkg --configure --pending
  862  dpkg --get-selections > dpkg-output.log
  863  ls
  864  cat dpkg-output.log
  865  sudo apt-get update && sudo apt-get upgrade
  866  /etc/init.d/apache2 stop
  867  sudo apt install onlyoffice-documentserver
  868  node -v
  869  sudp apt-get remove onlyoffice-documentserver
  870  sudo apt-get remove onlyoffice-documentserver
  871  /etc/init.d/apache2 start
  872  ls
  873  rm dpkg-output.log
  874  ls
  875  node -v
  876  systemctl status redis-server
  877  java -version
  878  history

---------------------------------------------------------------

cat dpkg-output.log:

onlyoffice-documentserver                       purge

---------------------------------------------------------------

nginx.error.log:

2018/02/23 17:05:01 [error] 1673#1673: *16752 open() "/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/help/de/Contents.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/resources/help/de/Contents.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/02/23 17:05:03 [error] 1673#1673: *16752 open() "/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/de_desc.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/de_desc.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/03/06 10:13:50 [error] 1672#1672: *47632 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/help/de/Contents.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/documenteditor/main/resources/help/de/Contents.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/documenteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/03/06 10:13:51 [error] 1672#1672: *47635 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/image-1.jpg" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/documenteditor/main/image-1.jpg HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/documenteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/03/29 11:03:57 [error] 1779#1779: *28423 open() "/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/help/de/Contents.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/resources/help/de/Contents.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/03/29 11:03:59 [error] 1780#1780: *28424 open() "/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/de_desc.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/de_desc.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/03/30 12:37:59 [error] 1780#1780: *31511 open() "/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/help/de/Contents.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/resources/help/de/Contents.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
2018/03/30 12:38:00 [error] 1780#1780: *31511 open() "/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/de_desc.json" failed (2: No such file or directory), client: 192.168.1.138, server: , request: "GET /2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/de_desc.json HTTP/1.1", host: "192.168.1.36", referrer: "http://192.168.1.36/2018-01-11-13-33/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-01-11-13-33&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor"
root@ubuntu-server:/var/log/onlyoffice/documentserver# cd /var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang/
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang# ls
de.json  en_desc.json  en.json  pl.json  ru_desc.json  ru.json
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang# ls -la
insgesamt 260
drwxr-xr-x 2 onlyoffice onlyoffice   4096 Mär 30 19:23 .
drwxr-xr-x 6 onlyoffice onlyoffice   4096 Nov 16 16:18 ..
-rw-r--r-- 1 root       root         9448 Mär 26 16:49 de.json
-rw-r--r-- 1 root       root        76338 Mär 26 16:49 en_desc.json
-rw-r--r-- 1 root       root         8781 Mär 26 16:49 en.json
-rw-r--r-- 1 root       root        10781 Mär 26 16:49 pl.json
-rw-r--r-- 1 root       root       128825 Mär 26 16:49 ru_desc.json
-rw-r--r-- 1 root       root        12248 Mär 26 16:49 ru.json
root@ubuntu-server:/var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/resources/formula-lang#

I hope someone can help me please! Thank you

**Comment by lvsbird** [comment]
Same here

**Comment by ShockwaveNN** [comment]
Try workaround mentioned in https://github.com/ONLYOFFICE/DocumentServer/issues/266#issuecomment-377877431
It's a known problem with incompatible config files moving during releases. We trying figure out solution

**Comment by TerjeTM** [comment]
The document server can not be uninstalled or reinstalled. I have already tried. See history. Thank you

**Comment by ShockwaveNN** [comment]
@TerjeTM try to remove /var/lib/dpkg/info/onlyoffice-documentserver.prerm file and try again to uninstall documentserver.

**Comment by TerjeTM** [comment]
Hello and thank you for the tip.
By deleting the file "/var/lib/dpkg/info/onlyoffice-documentserver.prerm" I was able to uninstall the document server (including DB) and reinstall it again.
Now I have another problem:
I can now open the documents, but neither edit nor save works, even the automatic save does not work.
I am not sure if the DB was deleted properly when I look log.

I tried to recreate the DB, as the system told me that it already exists

Could you please help me?

------------------------------------------------------------------------------------------------------------
postgres Log:
root@ubuntu-server:/var/log/postgresql# cat postgresql-9.5-main.log
2018-04-02 18:20:51 CEST [11063-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 18:20:51 CEST [11063-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 18:20:51 CEST [11068-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 18:20:51 CEST [11068-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 18:20:54 CEST [11073-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 18:20:54 CEST [11073-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 18:21:16 CEST [1662-2] LOG:  received fast shutdown request
2018-04-02 18:21:16 CEST [1662-3] LOG:  aborting any active transactions
2018-04-02 18:21:16 CEST [1836-2] LOG:  autovacuum launcher shutting down
2018-04-02 18:21:16 CEST [1833-1] LOG:  shutting down
2018-04-02 18:21:20 CEST [1833-2] LOG:  database system is shut down
2018-04-02 18:23:15 CEST [1766-1] LOG:  database system was shut down at 2018-04-02 18:21:20 CEST
2018-04-02 18:23:15 CEST [1767-1] [unknown]@[unknown] LOG:  incomplete startup packet
2018-04-02 18:23:15 CEST [1768-1] postgres@postgres FATAL:  the database system is starting up
2018-04-02 18:23:15 CEST [1801-1] postgres@postgres FATAL:  the database system is starting up
2018-04-02 18:23:16 CEST [1832-1] postgres@postgres FATAL:  the database system is starting up
2018-04-02 18:23:16 CEST [1766-2] LOG:  MultiXact member wraparound protections are now enabled
2018-04-02 18:23:16 CEST [1613-1] LOG:  database system is ready to accept connections
2018-04-02 18:23:16 CEST [1849-1] LOG:  autovacuum launcher started
2018-04-02 18:23:40 CEST [2315-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 18:23:40 CEST [2315-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 18:23:40 CEST [2309-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 18:23:40 CEST [2309-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 18:23:40 CEST [2325-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 18:23:40 CEST [2325-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 20:43:35 CEST [27324-1] onlyoffice@postgres ERROR:  must be owner of database onlyoffice
2018-04-02 20:43:35 CEST [27324-2] onlyoffice@postgres STATEMENT:  DROP DATABASE IF EXISTS onlyoffice;
2018-04-02 20:45:55 CEST [28054-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 20:45:55 CEST [28054-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 20:45:55 CEST [28059-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 20:45:55 CEST [28059-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 20:45:55 CEST [28064-1] onlyoffice@onlyoffice ERROR:  relation "checkissupportonconflict" does not exist at character 13
2018-04-02 20:45:55 CEST [28064-2] onlyoffice@onlyoffice STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
2018-04-02 20:52:01 CEST [28927-1] postgres@postgres ERROR:  database "onlyoffice" already exists
2018-04-02 20:52:01 CEST [28927-2] postgres@postgres STATEMENT:  CREATE DATABASE onlyoffice;
2018-04-02 20:52:38 CEST [29072-1] postgres@postgres ERROR:  role "onlyoffice" already exists
2018-04-02 20:52:38 CEST [29072-2] postgres@postgres STATEMENT:  CREATE USER onlyoffice WITH password 'onlyoffice';

**Comment by TerjeTM** [comment]
Hello me again

Everything seems to be all right. Other documents work.

The ticket can be closed. Many thanks for the help

**Comment by ShockwaveNN** [comment]
@TerjeTM Good to hear.
BTW we strongly advice use docker version of our product, because update process will be more streamlined

**Comment by garthh** [comment]
Same error, just take a look at "/etc/onlyoffice/documentserver", after update, I saw here a "default.json.dpkg-dist". Remove your old "default.json" (or rename it), and rename "default.json.dpkg-dist" to "default.json" and restart supervisor... and, onlyoffice is back !

**Comment by garthh** [comment]
Same error, just take a look at "/etc/onlyoffice/documentserver", after update, I saw here a "default.json.dpkg-dist". Remove your old "default.json" (or rename it), and rename "default.json.dpkg-dist" to "default.json" and restart supervisor... and, onlyoffice is back !
