### ISSUE TITLE
The simplified Chinese translation of the word、excel is error

### ISSUE THREAD

**Issue by zxuanhong** [ONLYOFFICE/DocumentServer#2650]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1-31

### Expected Behavior

1. The simplified Chinese translation of the word、excel is error
<img width="1324" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/6015d8ec-1765-4899-940d-20c6760b8d0f">
<img width="897" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/77803b09-e4f8-45bb-ba9a-4661c9d069e2">

**Comment by ElenaMaaya** [comment]
Hello @zxuanhong! I have a good news! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
This has been fixed (https://github.com/ONLYOFFICE/web-apps/commit/2299157184ed1540007f30b2a0e6424305a821be, https://github.com/ONLYOFFICE/web-apps/commit/d828833e193f39956932abb0bd63ad1ec6ad1be5) and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
