### ISSUE TITLE
Multiple docucments at the same time with tabbed ui dialog

### ISSUE THREAD

**Issue by softboy99** [ONLYOFFICE/DocumentServer#2651]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

We need an ui for open multiple documents at the same time with tabbed ui. 
<img width="784" alt="1710236955535" src="https://github.com/ONLYOFFICE/DocumentServer/assets/228731/3ffc6b06-48f6-4abe-ac90-758273f055a7">

**Comment by LuckySpecialist** [comment]
Hi @softboy99, in our editor, each document has its own tab with a toolbar linked to work with the open document and format. You can open several documents that will be in different tabs.
Can you explain what exactly you are not satisfied with this type and what is the advantage of your offer?

**Comment by softboy99** [comment]
Hi,
We want batch operation for multiple documents at the same time, Just like the scenario:
[https://github.com/ONLYOFFICE/DocumentServer/issues/2652#issuecomment-1991772135](url)

**Comment by LuckySpecialist** [comment]
> Hi, Can you share the picture of opening several documents?

Sorry, i don't really understand what needs to be shown. Open several documents and each one will be on a separate tab.

>  I cannot see it on your website.

Maybe [this one](https://www.onlyoffice.com/see-it-in-action.aspx)?

> We want batch operation for multiple documents at the same time, Just like the scenario: #2652

Answered in [this ](https://github.com/ONLYOFFICE/DocumentServer/issues/2651#issuecomment-1991764206) post

**Comment by softboy99** [comment]
Hi,
Maybe [this one](https://www.onlyoffice.com/see-it-in-action.aspx)?

there only open one document

**Comment by softboy99** [comment]
Hi,
@LuckySpecialist , your link only one opened document. I download the install the desktop editor version, it's ok. Is there a online version support this?

**Comment by softboy99** [comment]
Hi,
@LuckySpecialist ,  Is there online demo show off openning multiple document at the same time?

**Comment by LuckySpecialist** [comment]
Hi, @softboy99!
For the web editors, each new document already opens in a new separate browser tab.
Judging by the answer above, our Desktop Editor is suitable for you.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by softboy99** [comment]
> Hi, @softboy99! For the web editors, each new document already opens in a new separate browser tab. Judging by the answer above, our Desktop Editor is suitable for you.

Do you mean cannot do batch operations for multiple opened document in the web browser version?

**Comment by softboy99** [comment]
Hi,
you still didn't get what i said. we need it like wps office
