### ISSUE TITLE
Is it possible to add an custom toolbar button to execute business logic?

### ISSUE THREAD

**Issue by softboy99** [ONLYOFFICE/DocumentServer#2652]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

<img width="861" alt="1710239127528" src="https://github.com/ONLYOFFICE/DocumentServer/assets/228731/80ae0a1e-39da-4c36-8408-a959b464288b">

**Comment by LuckySpecialist** [comment]
Hi @softboy99, for personal customization and discussion of the editor's improvements to suit your needs, you can contact sales@onlyoffice.com.

**Comment by softboy99** [comment]
Hi,
i think it's more suitable to add it to the captionbar

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/228731/9dc6256b-7df6-4b7a-92fe-54ed808f9e07)

**Comment by LuckySpecialist** [comment]
HI @softboy99!
Starting from version 8.1, you can do this using a [visual plugin](https://api.onlyoffice.com/plugin/types).

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
