### ISSUE TITLE
CSV column is being parsed incorrectly

### ISSUE THREAD

**Issue by abcRede** [ONLYOFFICE/DocumentServer#2657]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.1.31

### Expected Behavior

When opening a CSV, as shown in the example below, it's expected that values delimited by quotes will be parsed as text.

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/119939906/bc88e130-7da1-4fea-9419-a21d7b949ca5)

### Actual Behavior

The date values are being interpreted oddly, resulting in gibberish values.

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/119939906/8332c5a2-d2f4-46f6-a9c9-40a4a6d18c38)

Even after removing the formatting.

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/119939906/932657cb-263d-4eba-af82-e09d15592739)
 

### Reproduction Steps

1) Create a new CSV like the following ones.

```csv
"ID","Name","Date Of Birth"
26856,"John Doe","01/01/1960"
25787,"John Doe Jr","02/02/2000"
```

```csv
ID,Name,Date Of Birth
26856,John Doe,01/01/1960
25787,John Doe Jr,02/02/2000
```

2) Try to open in OnlyOffice. 

### Additional information

This format is not affected by the issue, however, all the columns contains a single quote after parsed.

```csv
'ID','Name','Date Of Birth'
26856,'John Doe','01/01/1960'
25787,'John Doe Jr','02/02/2000'
```

![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/119939906/50e3239d-a00d-40cb-968e-00e6e3494576)

**Comment by Rita-Bubnova** [comment]
Sorry for late response, seems we missed this issue.
This has been fixed (https://github.com/ONLYOFFICE/core/commit/fcb4ae39091c99375869b00471379f40f34c63ab, https://github.com/ONLYOFFICE/core/commit/f89becf68fa046e181915d02c44ac8e744e3b91e).

DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
