### ISSUE TITLE
Is it possible to add an custom toolbar button to execute custom business logic?

### ISSUE THREAD

**Issue by softboy99** [ONLYOFFICE/DocumentServer#2665]
![image](https://github.com/ONLYOFFICE/CommunityServer/assets/228731/c4f508dc-914d-4d55-a3bd-a99e0d650a17)
We want batch operation for multiple documents at the same time。

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2652.
