### ISSUE TITLE
Unwanted animation delay in presentation

### ISSUE THREAD

**Issue by moritztim** [ONLYOFFICE/DocumentServer#2667]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

8.0.1.31

### Expected Behavior

The animation delay should be controlled by the user not by the program ._.

### Actual Behavior

See reproduction steps

### Reproduction Steps

1. Create an animation that is triggered "after previous" or "with previous"
2. Check that there is no delay set.
3. Change a different object's animation
4. The first animation now has a delay
5. Remove the delay
6. Change another object's animation
7. Find the delay restored

### Additional information

This has been really annoying because these delays have gone up to 8s, which is longer than my attention span, and I had to troubleshoot why my animation didn't happen while testing

**Comment by ElenaMaaya** [comment]
Hello @moritztim! I have a good news! This bug is fixed in version 8.1.0. Please update to release version 8.1.0.
If the problem persists, please write here again. 
Have a good day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
