### ISSUE TITLE
Accepting a change in table cell with a Content Control can blank out the entire cell contents. 

### ISSUE THREAD

**Issue by jdiller-arteria** [ONLYOFFICE/DocumentServer#2669]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

With Track Changes on, when you accept a change to the text, the new text should replace the original text. 

### Actual Behavior

The cell contents are deleted including both the original text and the changes. A series of small dot-like glyphs appear. 

### Reproduction Steps

Have a document with a table. (Sample attached) 

https://github.com/ONLYOFFICE/DocumentServer/assets/146874554/b88bd56d-6a8f-4263-b6c1-641bd7eff298

Place content controls inside the cells. 
Place text inside the content controls. 
Enable Track Changes.
Turn on non-printable characters.  
Change the cell text, ensure the table-cell end glyph is also selected/marked as deleted.
Accept all changes. 
[Track Changes Bug Demo.docx](https://github.com/ONLYOFFICE/DocumentServer/files/14700788/Track.Changes.Bug.Demo.docx)

**Comment by matveevms** [comment]
Hello, @jdiller-arteria.
I can confirm that the problem exists. I created issue #67071 for your problem.
Thanks for your request!

**Comment by matveevms** [comment]
The problem has been fixed in the next version of the editor, which will be released soon.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
