### ISSUE TITLE
Pasted text not all marked as changed when track changes is on and 'Text Only' is selected after Paste operation. 

### ISSUE THREAD

**Issue by jdiller-arteria** [ONLYOFFICE/DocumentServer#2670]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

When multiple paragraphs of text are pasted with "Track Changes" enabled, all paragraphs should be tracked as a change. 

### Actual Behavior

The final paragraph is not tracked as a change and cannot be accepted or rejected. 

### Reproduction Steps

Have multiple paragraphs of text in the clipboard ready to paste. 
Have an open Document with "Track Changes" enabled. 
Paste the text - it will all appear as a pending change. 
Choose "Keep Text Only" from the paste popup menu. 
Note that the final paragraph of text no longer appears as a change. 

### Additional information

https://github.com/ONLYOFFICE/DocumentServer/assets/146874554/902aabdf-e252-42f1-9715-6188fd206bc0

**Comment by matveevms** [comment]
Hello, @jdiller-arteria 
Indeed, there was such a problem, but it is fixed in the next version of the editor, which will be released soon

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
