### ISSUE TITLE
excel emoji display incorrect

### ISSUE THREAD

**Issue by zhouquan2016** [ONLYOFFICE/DocumentServer#2671]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

onlyoffice/documentserver

### Expected Behavior

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/18661266/6b62e4dc-e2b8-415b-94dc-a08b7320a734)

### Actual Behavior

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/18661266/9ec8397c-6ebf-43a4-9e8d-0d02dff915ab)

### Reproduction Steps

**docker-compose:**
`onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    networks:
      - dev
      - prod
    ports:
      - "9898:80"
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=Asia/Shanghai
      - DB_TYPE=mysql
      - DB_HOST=192.168.1.1
      - DB_PORT=3306
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - DB_PWD=test
      - REDIS_SERVER_HOST=redis_prod
      - REDIS_SERVER_PORT=6379
      - JWT_ENABLED=true
      - JWT_SECRET=test
      - REDIS_SERVER_HOST=redis_prod
      - REDIS_SERVER_PORT=6379
      - AMQP_TYPE=rabbitmq
      - AMQP_URI=amqp://onlyoffice:test@rabbitmq:5672//onlyoffice
    volumes:
      - /home/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
      - /home/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
      - /home/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /root/compose/OnlyOffice/winfont:/usr/share/fonts/truetype/custom
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4g`
**vue method**:
`async loadExcelView () {
      let id = this.docForm.id
      let resp = await getQaExcel(id)
      if (resp.code !== 0) {
        this.$message.error(resp.msg)
        throw new Error(resp.msg)
      }
      const url = resp.data.fileUrl
      const fileName = resp.data.fileName
      // 获取文件后缀（假设最后一个点后面是后缀）
      const fileExtension = fileName.lastIndexOf('.') !== -1 && fileName.substring(fileName.lastIndexOf('.') + 1) || 'xls';
      const key = id.toString() + new Date().getTime()
      resp = await getToken({ key, userName: this.nickname })
      if (resp.code !== 0) {
        this.$message.error("fileId签名失败")
        throw new Error("fileId签名失败")
      }
      const accessToken = resp.data
      this.docForm.key = key
      const callbackUrl = window.location.origin + process.env.VUE_APP_BASE_API +
        "/admin-api/trade/document/callback?token=" + accessToken
      console.log("callbackUrl:{}", callbackUrl)
      const docForm = this.docForm
      const _this = this
      const config = {
        document: {
          fileType: fileExtension,
          key,
          title: fileName,
          url,
        },
        editorConfig: {
          callbackUrl,
          lang: 'zh',
          mode: this.docForm.mode,
          user: {
            "id": String.valueOf(this.userId),
            "image": this.avatar,
            "name": this.nickname
          },
          customization: {
            // 强制保存
            forcesave: false,
            autosave: true,
          }
        },
        token: accessToken,
        events: {
          onDocumentStateChange(event) {
            console.log("onDocumentStateChange", event)
            if (event.data) {
              docForm.changed = true
            }
          },
          onRequestClose() {
            console.log("onRequestClose:", docForm.closeFun)
            if (docForm.closeFun) {
              _this[docForm.closeFun].bind(_this)()
            }
          }
        },
        errorHandling: false
      }
      if (this.docForm.editor) {
        this.docForm.editor.destroyEditor()
      }
      this.docForm.editor = new DocsAPI.DocEditor("qaExcelId", config);

    }`

### Additional information

excel origin file 
[zhi (1).xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/14716960/zhi.1.xlsx)

**Comment by rsnegirev** [comment]
Hi @zhouquan2016 

What version of the ONLYOFFICE do you use?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
