### ISSUE TITLE
购买软件找谁，官网的电话打不通 Who to contact to buy the application? Cannot reach the number from the official website

### ISSUE THREAD

**Issue by GoldIsland** [ONLYOFFICE/DocumentServer#2680]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

ran468650717

### Expected Behavior

ran92387713

### Actual Behavior

ran726841757

### Reproduction Steps

ran984317493

### Additional information

ran848292070

**Comment by flyingsauce** [comment]
Hello, please send an email to this address and we will contact you: sales@onlyoffice.com

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
