### ISSUE TITLE
In ODT format, when you change the wrapping style of an image, and save, the image returns behind text. 

### ISSUE THREAD

**Issue by lea-aglz** [ONLYOFFICE/DocumentServer#2685]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

8.0.1.31

### Expected Behavior

When I changed the wrapping style of a image (like in square, tight, top and bottom and in front of text), the image is correctly modified. Then I saved and I reopened the file, the image has not moved and looks just as it did the last time it was opened. 

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/147405594/21a67116-92bb-4ca7-b21d-9ab8ad058c95)

### Actual Behavior

When I changed the wrapping style of a image (like in square, tight, top and bottom and in front of text), the image is correctly modified. But when I reopened, the image is behind text. Not like when I left the file.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/147405594/bd71d560-b6de-422d-a88f-920ced3dd867)

### Reproduction Steps

1. Go to an .ODT file with texte and images 
2. On an image in the middle of the text, change the wrapping style of the image to square, tight, top and bottom or in front of text. 
3. Save the file 
4. Reopended it, as you can see the image is behind the text : 

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/147405594/e9f9bccb-6a23-4069-bb98-ea6d5d20db55)

### Additional information

Occurs only on .ODT files.

[BLOG 2024, une année de refonte d_architecture tournée vers l_avenir et l_introduction d_IA_v1.6.odt]
(https://github.com/ONLYOFFICE/DocumentServer/files/14837304/BLOG.2024.une.annee.de.refonte.d_architecture.tournee.vers.l_avenir.et.l_introduction.d_IA_v1.6.odt)

I also transfer you the file :)

**Comment by ElenaMaaya** [comment]
Hello @lea-aglz!
I have a good news!
This issue fixed in the v.8.2.0 ([commit 1](https://github.com/ONLYOFFICE/core/commit/6ba40aba515b5b7d132796098b0b030e52897dfc) and [commit 2](https://github.com/ONLYOFFICE/core/commit/24b32a2ba783c4e5eec5c4e7b35829d5cefecd74)).
Please update ONLYOFFICE Editors to version 8.2.0.
Have a nice day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
