### ISSUE TITLE
Cursor jumps back when touching "new paragraph" line. 

### ISSUE THREAD

**Issue by amab8901** [ONLYOFFICE/DocumentServer#2689]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.0.1.31 (deb)

### Expected Behavior

Pressing the down arrow on the keyboard should always move the cursor down. And pressing a blank line should always place the cursor on the line that I clicked. 

### Actual Behavior

Pressing down arrow sometimes makes the cursor jump back an entire paragraph or more. Pressing a blank line sometimes achieves the same result. 

### Reproduction Steps

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/83634595/5803c2a8-9de1-4e0c-bfd5-04057e6adc0c)

1) Create a paragraph that crosses page boundaries (and a few paragraphs before and after). 
2) Append "shift+enter" (I think it's called "blank line") followed by "enter" (I think it's called "new paragraph"). 
3) Place the cursor on the first page (assuming you're crossing the boundary between 1st and 2nd page). 
4a) [option 1] Press the down button in an attempt to reach the next paragraph on page 2. Keep holding the down button and you'll run into a loop.
4b) [option 2] Press the "new paragraph" line and you'll get teleported to the beginning of the page-crossing paragraph. 

### Additional information

This bug is pretty painful and should be high on priority list

**Comment by XDmitryK** [comment]
@amab8901 Hi
Yes, your problem repeated on version 8.0.1-31. But it does not exist in the test version 8.1.0. I am attaching a test file here to check when a new version of DS is released.
[Cursor jumps back when touching new paragraphline.docx](https://github.com/ONLYOFFICE/DocumentServer/files/15108428/Cursor.jumps.back.when.touching.new.paragraphline.GitHub.issue.docx)

**Comment by amab8901** [comment]
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/83634595/fc440b97-db23-4565-a52a-bbd4236dd846)
the bug has been partially solved but there's another related issue where clicking on the blank line after a paragraph makes the cursor jump back up. See screenshot. Here's how to reproduce it:

1) create an arbitrary paragraph on a blank document
2) newline character (return character), then new-paragraph character, then write something arbitrary
3) click on the new-paragraph character => cursor jumps (this is the bug)

**Comment by XDmitryK** [comment]
@amab8901 
Yes, your second problem still exists in version 8.0, but is not repeated in 8.1. We need to wait for the release of a new version

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
