### ISSUE TITLE
After clicking the Save button, file cannot be saved and the callback status is 7

### ISSUE THREAD

**Issue by lantongkun** [ONLYOFFICE/DocumentServer#2690]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.0

### Expected Behavior

Callback handler should receive status 2 along with the url of the saved file

### Actual Behavior

Callback handler received status 7 which refers to save error.

### Additional information

Log in /var/log/onlyoffice/documentserver/converter/out.log
  [2024-04-07T05:08:01.276] [ERROR] [localhost] [THzJJytECB] [061490161] nodeJS - stdout:
  [2024-04-07T05:08:01.276] [ERROR] [localhost] [THzJJytECB] [061490161] nodeJS - stderr:
  [2024-04-07T05:08:01.276] [ERROR] [localhost] [THzJJytECB] [061490161] nodeJS - ExitCode (code=88;signal=null;error:-88)

Log in /var/lib/onlyoffice/documentserver/App_Data/cache/files/error/bin/THzJJytECB_8748/console.txt
  stdout:
  stderr:
  ExitCode (code=88;signal=null;error:-88)

Please find the attached log of /var/lib/onlyoffice/documentserver/App_Data/cache/files/error/  
[error.zip](https://github.com/ONLYOFFICE/DocumentServer/files/14895874/error.zip)
and [/var/log/onlyoffice/documentserver/converter/out.log 
[out.log](https://github.com/ONLYOFFICE/DocumentServer/files/14895875/out.log)

**Comment by askonev** [comment]
@lantongkun 

Can I ask you to repeat the script on my side with saving after activating all logs for the document server?

```bash
docker exec -it $NAME sed -i 's/WARN/ALL/g' \
                             /etc/onlyoffice/documentserver/log4js/production.json
docker exec -it $NAME sed -i 's,access_log off,access_log /var/log/onlyoffice/documentserver/nginx.access.log,' \
                             /etc/onlyoffice/documentserver/nginx/includes/ds-common.conf

docker exec "$NAME" supervisorctl restart all
```

**Comment by askonev** [comment]
@lantongkun There is also a suggestion to update the document server to the current `version 8.0`

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
