### ISSUE TITLE
Remove page break does not work as expected in .xlsx and .ods

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2695]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

1) Page break should be removed once clicked on remove page break.
2) Page break margins should be retained after saving & reopening file.

### Actual Behavior

1) Remove page break does not work as expected in .xlsx and .ods. Page break margins still exists even after clicking on remove page break.
2) After saving and reopening the file, the page break margins disappears.
Same issue in layout tab -> margins

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/35776774/af63b22c-906f-4ccc-b5b5-58637b33a7cb)

### Reproduction Steps

    Open any .xlsx/.ods file.
    Go to Layout tab
    Click on breaks.

**Comment by LuckySpecialist** [comment]
Hi, @Maaayank!
This is the normal operation of the application. These dashed lines show the current markup on the page for visual control of page breaks or their absence. A similar behavior can be observed in MS Office.
If I misunderstand the question, please attach your document to demonstrate the problem.
