### ISSUE TITLE
Wrapping style is getting changed from "Square" to "Behind Text" in .odt files after save back

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2696]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

After opening the edited copy, the wrapping style should be retained as it was.

### Actual Behavior

After opening the edited copy, the wrapping style got changed to 'Behind text' from 'Square'

### Reproduction Steps

    Open any .odt file
    Add any image/shape in the file
    Right click on the image/shape and change wrapping style to sqaure
    Save and close the file

**Comment by Rita-Bubnova** [comment]
Hello, @Maaayank.
DocumentServer v8.0.0 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by cpot** [comment]
Potentially similar than https://github.com/ONLYOFFICE/DocumentServer/issues/2685
