### ISSUE TITLE
Header is getting merged with the data in the sheet in .ods file

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2698]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

Header Should be visible top most in the print preview.

### Actual Behavior

When header is configured in .ods file, and there is data present in the first cell of the sheet, the data & header get merged up and the data is visible above the header.

Header is seen merged with the text in the first cell in the print preview.

### Reproduction Steps

1) Configure header from insert tab in .ods file
2) Add data in the first cell
3) Try to print the file and verify print preview

**Comment by rsnegirev** [comment]
Hi @Maaayank 

This problem sounds very familiar, but I just checked this scenario on version 8.0.1 and no merge happened. I recommend you update your version and check again as this behavior has probably been fixed in previous versions.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
