### ISSUE TITLE
Type of section break changes in the received edited copy of .odt format file

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2699]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

Section break present in the received edited copy of the file should be same as configured before closing the file. 

### Actual Behavior

Type of section break changes in the received edited copy of .odt format file.
If user has inserted section breaks of type 'Continuous Page','Even Page' or 'Odd Page', then these types of breaks are converted to 'Next Page' type break in the received edited copy of the file.

Section break present in the received edited copy of the file are not same as configured before closing the file.

### Reproduction Steps

    Open .odt format file in browser.
    Insert breaks using 'Breaks > Section Breaks > Continuous Page/Even Page/Odd page' option present under Insert tab.
    Save and close the file.
    Open the received copy of the file and verify configured section breaks.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
