### ISSUE TITLE
Feature Request: Task Lists For Projects?

### ISSUE THREAD

**Issue by Xarcell** [ONLYOFFICE/DocumentServer#27]
Any chance of getting a task list feature added to projects so we can better organize our projects tasks & sub-tasks?

**Comment by ibnpetr** [comment]
Hello
We'd recommend to visit [OnlyOffice developers forum](http://dev.onlyoffice.org/viewforum.php?f=42&sid=7f75026707cabd0d005eea4435384e47) and leave your Feature Request there.
It should be posted in the Community Server topic.

**Comment by Xarcell** [comment]
I've posted there, but no response.

**Comment by ibnpetr** [comment]
I've forwarded your comment, thanks for getting back
All your posts are replied on the forum, just checked
