### ISSUE TITLE
Print title settings are not retained in .ods file after opening edited copy

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2700]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.0

### Expected Behavior

Print titles settings should be retained in edited copy.

### Actual Behavior

Print title settings are not retained in .ods file after opening edited copy

### Reproduction Steps

1) Open any .ods file
2) Go go Layout tab -> print titles -> add details
3) Verify the changes by printing the document
4) Save, Close & reopen the edited file
5) Verify the print titles settings from layout tab or by printing the document

**Comment by Rita-Bubnova** [comment]
Hello, @Maaayank.
DocumentServer v8.0.0 is released. Is this issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
