### ISSUE TITLE
xls conversion problems with formulas

### ISSUE THREAD

**Issue by silversword411** [ONLYOFFICE/DocumentServer#2702]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.0.1.31

### Expected Behavior

xls cell references are changing from things like
IY3+IZ3...
See attached spreadsheet. Black columns are data entry, red are calculated fields. 

### Actual Behavior

Excel shows different than onlyoffice.

<img width="525" alt="2024-04-10_153545 - editors_04_Monthly_Totals_APRIL_2024cleaned xls_-_ONLYOFFI" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/13395348/4d6d52de-46ba-43db-b1f9-01c65f9779dd">

<img width="591" alt="2024-04-10_153809 - EXCEL_04_Monthly_Totals_APRIL_2024cleaned xls__ Compatib" src="https://github.com/ONLYOFFICE/DesktopEditors/assets/13395348/b253772c-bb56-4131-911b-eb5f991f96ba">

[04 Monthly Totals APRIL 2024cleaned.xls](https://github.com/ONLYOFFICE/DesktopEditors/files/14936931/04.Monthly.Totals.APRIL.2024cleaned.xls)

**Comment by rsnegirev** [comment]
Hi @silversword411 

The bug was fixed in this commits: https://github.com/ONLYOFFICE/core/commit/af226ceb67e347a8690f5cdd073b0763a3a348f4, https://github.com/ONLYOFFICE/core/commit/7f791ad265e06d8cd1c52e4522a19f778fee2c75

Fixes will be released in the next major version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by gqqnbig** [comment]
Hello, I am using version 8.2.2.22 but still bumped into this issue. 

The formula in a cell references wrong cells when I sort part of the sheet, or when I save, reopen this file.
