### ISSUE TITLE
docx2pdf- can not identify list identification

### ISSUE THREAD

**Issue by ShowerBandV** [ONLYOFFICE/DocumentServer#2708]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

[list-origin.docx](https://github.com/ONLYOFFICE/DocumentServer/files/15093599/list-origin.docx)
[list-onlyoffice.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/15093600/list-onlyoffice.pdf)

[list2-origin.docx](https://github.com/ONLYOFFICE/DocumentServer/files/15093602/list2-origin.docx)
[list2-onlyoffice.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/15093603/list2-onlyoffice.pdf)

### Actual Behavior

docx2pdf- can not identify list identification

### Reproduction Steps

No response

### Additional information

No response

**Comment by matveevms** [comment]
Hello, @ShowerBandV 
If the problem in this issue is that after converting a document from docx to pdf, the list markers change, then in version 8.0.1 this problem does not repeat. You need to update the editor version.

**Comment by ShowerBandV** [comment]
Hello, @matveevms 
I tried version 8.0.1.31, the problem still exists.

**Comment by matveevms** [comment]
![Screenshot_200](https://github.com/ONLYOFFICE/DocumentServer/assets/49515977/2a91688f-f19b-4765-9ef7-9ce1d6f78ad1)
As you can see in the screenshot, I don't have the same problem. Please tell me step by step how the conversion from docx to pdf occurs? Is your font installed on the document server?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
