### ISSUE TITLE
ppt2pdf-Text is converted to the same position

### ISSUE THREAD

**Issue by ShowerBandV** [ONLYOFFICE/DocumentServer#2710]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

[textcoverdtogether.zip](https://github.com/ONLYOFFICE/DocumentServer/files/15093696/textcoverdtogether.zip)
I compressed it with zip because GitHub does not support uploading ppt files

### Actual Behavior

Text is converted to the same position

### Reproduction Steps

No response

### Additional information

No response

**Comment by l8556** [comment]
Hello @ShowerBandV 

Version 8.1.1 of DocumentServer was released recently,
please update your app and check the situation again.
This issue should be fixed in this version, I am looking forward to your feedback.
