### ISSUE TITLE
Localisation bug

### ISSUE THREAD

**Issue by LennyFox** [ONLYOFFICE/DocumentServer#2713]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

Latest version on Windows 11

### Expected Behavior

When opening a new presentation from the main application (editor), the slide formats are in Slowak in stead of Dutch.

### Actual Behavior

See image, I would expect Dutch

### Additional information

![Localisation bug](https://github.com/ONLYOFFICE/DesktopEditors/assets/63356355/4276ea03-4deb-48d8-a336-77e045780a2d)

**Comment by ElenaMaaya** [comment]
Hello @LennyFox! I have a good news! This issue will be fixed in the next release ([commit](https://github.com/ONLYOFFICE/document-templates/commit/8d39f1df76f768688627f638672027b3ef1c82e2)). Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
