### ISSUE TITLE
doc files cannot be saved

### ISSUE THREAD

**Issue by diglab1337** [ONLYOFFICE/DocumentServer#2718]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1.31

### Expected Behavior

When I edit a doc file, I expect that it can be saved. With the old version 7.3.3.49 this still works as expected. With version 8, DOC files can no longer be saved.

Editing and saving docX files works without any problems.

### Actual Behavior

I can open a doc file, but the changes cannot be saved. an error message appears: 

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/77344232/d934a492-dbe6-4830-83b5-ab01bb80aef1)

### Reproduction Steps

* Open or create doc file
* Edit doc file
* When saving, the error message “An error occurred while saving” appears

### Additional information

We use the Helm deployment of Onlyoffice with Kubernetes v1.26.14 as described here: https://github.com/ONLYOFFICE/Kubernetes-Docs

* Saving docX files works without any problems
* Saving doc files no longer works since version 8
* In the old version 7.3 both doc and docX worked without problems

**Comment by igwyd** [comment]
Hello @diglab1337, thank you for the report, we know about it - bug 66766, it will be fixed in the next release.

**Comment by diglab1337** [comment]
Hello @igwyd thank you for your feedback. 
Is there already an approximate date for the next release?

**Comment by diglab1337** [comment]
@igwyd With version 8.1, everything now works as desired. Thank you very much for your support.
