### ISSUE TITLE
[BUG]: OnlyOffice does not open Nextcloud login screen

### ISSUE THREAD

**Issue by jiriks74** [ONLYOFFICE/DocumentServer#2719]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.0.204

### Expected Behavior

Login screen appearing

### Actual Behavior

There's some kind of a splash screen:

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/54378412/ef92408d-a67f-49e4-ab2b-bbecc7369714)

### Reproduction Steps

1. Install OnlyOffice
2. Click `Connect to cloud`
3. Select Nextcloud
4. Insert Nextcloud's URL
5. See no login screen

**Comment by LuckySpecialist** [comment]
Hi, @jiriks74!
Please specify the version of the nextcloud server.
Have you tried using the [current version of the Desktop Editors](https://github.com/ONLYOFFICE/DesktopEditors/releases), is the problem relevant there too?
