### ISSUE TITLE
Document Server suddenly timed out?

### ISSUE THREAD

**Issue by datvm** [ONLYOFFICE/DocumentServer#272]
Hi,

I have installed Document Server on my server successfully. Recently however we cannot use it anymore. I tried accessing http://localhost/ on the server, after a very long time, the Url is redirected to http://localhost/welcome/ with the timeout message:

504 Gateway Time-out
nginx

I have tried to restart the server. How can I troubleshoot this problem?

RAM and CPU stats are good. Nothing spike when I access them.

**DocumentServer version:** I don't know how to check (and cannot access to the UI right now to check). It was the newest version when I installed it a month ago.

**Operating System:** Windows Server 2016

**Browser version:** Google Chrome Version 65.0.3325.181

**Comment by raphson93** [comment]
hi, you may close this issue if resolved.
thanks

**Comment by ShockwaveNN** [comment]
This ticket is being closed due to no response

**Comment by lokesh-soni** [comment]
Having same issue while trying to use document server for development.

**Comment by ShockwaveNN** [comment]
@lokesh-soni Hi, please create new issue and fill out issue template
