### ISSUE TITLE
Korean characters start to separate when two users are typing at the same time

### ISSUE THREAD

**Issue by KhristoforovEvgenii** [ONLYOFFICE/DocumentServer#2727]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.0-ee

### Expected Behavior

Korean letters should display correctly when co-editing a presentation

### Actual Behavior

Korean characters start to separate when two users are typing in presentation at the same time 

### Reproduction Steps

1. Open presentation for editing by 2 different users
2. Start typing by 2 users at the same time

### Additional information

[bug demo.webm](https://github.com/ONLYOFFICE/DocumentServer/assets/142880987/2a753f31-133d-4d9b-afbf-721a0b28b718)

**Comment by TatianaKirillova** [comment]
Hello @KhristoforovEvgenii! Please update your version to 8.0.1. The problem was fixed by [commit](https://github.com/ONLYOFFICE/web-apps/commit/a862863207f479a03792dba79aab4f4905f28e55)
