### ISSUE TITLE
After the callback function is invoked, the returned JSON has a status of 3 and there is no corresponding URL.

### ISSUE THREAD

**Issue by qq997540362** [ONLYOFFICE/DocumentServer#2728]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

20.10.17 and 20.10.14

### Expected Behavior

Yesterday while troubleshooting the logs, I found that OnlyOffice discovered that whenever I opened and edited a .doc or .docx file and saved it, the callback function always received a status of 3. I checked the out.log file located under \var\www\onlyoffice\log\onlyoffice\documentserver\converter 
![out_stdout](https://github.com/ONLYOFFICE/DocumentServer/assets/59379374/493f9b2f-e4be-4bfa-9fee-9b1078031390)
I also checked the logs in other paths \var\www\log\onlyoffice\documentserver\metrics, which provided the following information：
![2024051101](https://github.com/ONLYOFFICE/DocumentServer/assets/59379374/d583ccb0-279e-443b-bc20-e663ee19e420)
I encountered such an error in the logs under the path \var\www\log\onlyoffice\documentserver\docservice
![2024051102](https://github.com/ONLYOFFICE/DocumentServer/assets/59379374/bb23f815-afa6-4fd9-81c4-fbba6d4b1b9c)

How can I resolve this issue?

### Actual Behavior

After I discovered this issue yesterday, I tried to replicate it in my test environment but without success. Both my production and test environments are using the same CentOS 7, with Docker versions 20.10.14 for production and 20.10.17 for testing. The OnlyOffice Document Server used in both environments is onlyoffice/documentserver:7.0.

**Comment by igwyd** [comment]
Hello @qq997540362, this error is related to the conversion of the old format ```doc``` inside docimentserver, we already fix it at https://github.com/ONLYOFFICE/core/commit/04480bb9eb06e3f7dd534821af89e5f2083cb94e, and will be released in the next major release.

**Comment by qq997540362** [comment]
Thank you for your response! Has this bug been fixed in version 8.0 so far, or do we need to wait until version 8.5 for the fix?

**Comment by qq997540362** [comment]
Thank you for your answer and hope you have a smooth day at work today.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
