### ISSUE TITLE
DocumentServer 5.1.1 cannot be installed in Windows

### ISSUE THREAD

**Issue by konfetov** [ONLYOFFICE/DocumentServer#273]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Installation of DocumentServer 5.1.1 requires installation of Visual C++ 2015 Redistributable Packages but the latest version of Visual C++ 2015 Redistr. Pack (Update 3) is already installed.
![onlyoffice-visuall c redistr](https://user-images.githubusercontent.com/3183799/38421303-5a4e9f08-39af-11e8-80c4-a4839039dd07.png)

Seems the problem that starting from DC 5.1.0 the installation requires the first version of the Visual C++ 2015 Redistributable Packages (*build 14.0.23026.0*) but earlier DocumentServer could work with the latest version Visual C++ 2015 Redistributable Packages Update 3 (*build 14.0.24212.0*).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install Visual C++ 2015 Redistributable Packages Update 3 manually.
2. Installation of DocumentServer 5.1.1 is not possible.

**What is the expected behavior?**
DocumentServer should use the latest installed  Visual C++ 2015 Redistributable Packages so the installation should pass.

**Did this work in previous versions of DocumentServer?**
Before DC 5.1.1 it was possible to upgrade its version having Visual C++ 2015 Redistributable Packages Update 3 installed on a computer.

**DocumentServer version:**
5.1.0 / 5.1.1

**Operating System:**
Windows 7 x64

**Browser version:**
Any

**Comment by HellRoad** [comment]
Thank for feedback
We are working on this bug. I think this fix will be in the next update.

**Comment by raphson93** [comment]
hi is this problem resolved for Document Server version 5.1.3 ?

**Comment by HellRoad** [comment]
This problem resolved, but this fix was not included in version 5.1.3
Think that in bug fix 5.1.4 or major update

**Comment by ShockwaveNN** [comment]
To be clear - this issue will be fixed in 5.2 and will be released in several months

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
