### ISSUE TITLE
Only Office Community version, file upload not synchronized

### ISSUE THREAD

**Issue by Mr-XuanSu** [ONLYOFFICE/DocumentServer#2730]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

6.3.1.56

### Expected Behavior

The results obtained by accessing the only office using IP: 8.130.96.170 are consistent with those obtained by accessing the only office using IP 119.165.74.130

### Actual Behavior

The results of accessing two IPs are inconsistent. I found that when I upload files on IP: 8.130.96.170, I cannot view them when accessing the only office using IP: 119.165.74.130. I found that the uploaded files were all saved to the server under/onlyoffice//var/lib/onlyoffice/documentserver example/files, and then the files were saved separately based on their IP addresses.
For example:
I uploaded the a.docx file using IP: 8.130.96.170, and the file was saved under/onlyoffice/var/lib/onlyoffice/documentserver-example/files/8.130.96.170. When I access using IP: 119.165.74.130, I can only see files in the/onlyoffice//var/lib/onlyoffice/documentserver example/files/119.165.74.130 directory
Can I put all the uploaded files in one place and see consistent data regardless of which IP address I use to access them.

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/120170604/0175f8a1-1409-4216-9d27-5aa92c8cc80e)

**Comment by avdddd1111** [comment]
Hello @Mr-XuanSu !

Please update the document server to the latest version. And check if the issue persists. Since we only support the current latest version, and your issue may already be fixed in it.

**Comment by Mr-XuanSu** [comment]
I used Docker for deployment, I pulled the image again, and after running it, the situation remained the same
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/120170604/6cfac0eb-4f0b-445f-a600-ae28bf7c909c)

**Comment by avdddd1111** [comment]
Did you just download the image or update to a new one? The latest version now 8.0.1, you can see it in the editor left panel.
![2024-05-20_10-46](https://github.com/ONLYOFFICE/DocumentServer/assets/148441564/dff6589e-db2a-4dae-a53a-f04b40ad4dc8)

**Comment by Mr-XuanSu** [comment]
I am using the latest image, version 8.0.1.31
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/120170604/7ddb203c-72ba-4db6-b058-11d6c9edaa7c)

**Comment by avdddd1111** [comment]
Inside the Docker container, in the nginx config, set up a proxy to replace the IP in the X-Forwarded-For header with the proxy_host in /etc/nginx/includes/ds-example.conf. After that, restart nginx.
`proxy_set_header X-Forwarded-For $proxy_host;`
![2024-05-20_14-07](https://github.com/ONLYOFFICE/DocumentServer/assets/148441564/4601aeda-7d27-4e6a-bbe3-1386e6321194)

**Comment by Mr-XuanSu** [comment]
I made the modifications according to your configuration and restarted nginx. I also tried to restart the container, but still couldn't achieve the expected effect. If you have any requirements, I can enable SSH for your IP address and allow you to log in to the server to view it
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/120170604/38c70e7e-5b80-42ef-8a14-d23d78e83adc)

**Comment by avdddd1111** [comment]
You used wrong path. Do it that: 
`cd /etc/nginx/includes
nano ds-example.conf`
change 13 line like this:
`proxy_set_header X-Forwarded-For $proxy_host;`

After save chanes and restart nginx
`service nginx restart`

If you want us to assist with support, you can contact us at sales@onlyoffice.com.

**Comment by Mr-XuanSu** [comment]
My problem has been solved, thank you very much
