### ISSUE TITLE
incorrect import of numbers (floats) from a CSV

### ISSUE THREAD

**Issue by janxkoci** [ONLYOFFICE/DocumentServer#2731]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

Opening this as a separate issue as per https://github.com/ONLYOFFICE/DesktopEditors/issues/1544#issuecomment-2100921077

#### test file
Save the following data in a new `test.csv` file:

```
rep,A,B,C
boot0,5.752358097e-07,6.241771831e-07,6.999271312e-07
boot1,5.772195833e-07,6.96334089e-07,7.699275178e-07
boot2,5.740492503e-07,6.570095073e-07,7.349709959e-07
boot3,5.350701888e-07,7.284086319e-07,7.706726658e-07
boot4,6.040161158e-07,6.815208175e-07,7.795943224e-07
boot5,4.912695988e-07,6.104015119e-07,6.836477531e-07
boot6,5.790822242e-07,6.43826624e-07,7.618649987e-07
boot7,5.249489454e-07,6.669570975e-07,7.294331419e-07
boot8,6.030653684e-07,7.332421268e-07,7.659650011e-07
```

(This is part of an actual file I was working on when I discovered the issue.)

Reading the file into a spreadsheet should show correct values in cells.

### Actual Behavior

Importing the above file and selecting any numeric cell will show wrong value in the formula bar. Changing numeric formats keeps showing wrong values - see steps to reproduce below.

### Reproduction Steps

1. Open the above file in OnlyOffice Desktop of version 7.5.1 or higher.
2. Use UTF-8 encoding and comma as delimiter when prompted by OnlyOffice.
3. Select any numeric cell and look at the formula bar (just above the cells) - it incorrectly displays the value as e.g. 0.000001 or even 0 (e.g. cell B7).
4. Try selecting all numeric cells and convert to Scientific notation - most show the value of `1.00E-06`, which is not correct.
5. Try converting to number with 12 decimal points - you will get numbers like 0.000001000000.

#### testing setup
I tried several versions of OnlyOffice, with older versions showing correct behaviour, while newer versions show incorrect behaviour. I noticed the issue first on my main laptop with OnlyOffice from flathub (version 8.0.1), then tried another laptop with OnlyOffice installed as deb package (7.4.0). After that I decided to test it with a few appimages to see when the bug started.

##### Correct

- OnlyOffice 7.4.0.163 (deb, Linux)
- OnlyOffice 7.4.1.36 ([appimage](https://github.com/ONLYOFFICE/appimage-desktopeditors/releases/download/v7.4.1/DesktopEditors-x86_64.AppImage), Linux)

##### Buggy

- OnlyOffice 8.0.1.31 (flatpak, Linux (from flathub))
- OnlyOffice 7.5.1.23 ([appimage](https://github.com/ONLYOFFICE/appimage-desktopeditors/releases/download/v7.5.1/DesktopEditors-x86_64.AppImage), Linux)

#### notes
It's possible (likely) that version 7.5.0 is already affected, but I haven't tried it (the appimages are rather large and I mostly needed some working version on my main laptop, testing all version was not the main priority).

**Comment by janxkoci** [comment]
Thanks @rsnegirev. Do you mean major version of DocumentServer or DesktopEditors?

**Comment by rsnegirev** [comment]
@janxkoci both of them!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
