### ISSUE TITLE
Could you please tell me how to change the port 443 in the OnlyOffice-doc connection?

### ISSUE THREAD

**Issue by yuanhuabiao** [ONLYOFFICE/DocumentServer#2734]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.1

### Expected Behavior

The issue with my OnlyOffice is that it fails to load, and upon investigation, it’s because it’s using the default port 443, whereas the public domain name uses port 843, causing the online documents to fail to load. How do I change the port from 443?

### Actual Behavior

The issue with my OnlyOffice is that it fails to load, and upon investigation, it’s because it’s using the default port 443, whereas the public domain name uses port 843, causing the online documents to fail to load. How do I change the port from 443?

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/155124925/7b2d7dae-09b5-4f9d-9b8d-67f491e7f064)

**Comment by avdddd1111** [comment]
Hello @yuanhuabiao !

What kind of setup do you have? What did you change? 

More details in the help center:
https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx

You can use an additional reverse proxy to set any external network port you need.
https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

**Comment by yuanhuabiao** [comment]
Hi,I have already solved this problem.Thank&nbsp; you for your help my good friend.



---Original---
From: "Ilya ***@***.***&gt;
Date: Fri, May 24, 2024 16:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ONLYOFFICE/DocumentServer] Could you please tell me how tochange the port 443 in the OnlyOffice-doc connection? (Issue #2734)




 
Hello @yuanhuabiao !
 
What kind of setup do you have? What did you change?
 
More details in the help center:
 https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx
 
You can use an additional reverse proxy to set any external network port you need.
 https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

**Comment by Rita-Bubnova** [comment]
@yuanhuabiao, It's a good news.
 I close this issue. Feel free to comment or reopen it if you got further questions.
