### ISSUE TITLE
Alternative text for images, import from ".odt"

### ISSUE THREAD

**Issue by sergiocarlotto** [ONLYOFFICE/DocumentServer#2735]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.0.1.31

### Expected Behavior

When importing a document created in “LibreOffice” .odt, it is possible to set a title and an alternative text for images. However, when importing the document to Onlyoffice Web in production (https://personal.onlyoffice.com/), this title and alternative text are lost.

In LibreOffice:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/2835460/b9f71c48-2deb-4e85-a6a3-4d299dd0201a)

In Onllyoffice:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/2835460/740e53e4-f86f-4260-9e9c-523f701f8a5c)

This "Name" and "Description" information must be migrated to the corresponding "Title" and "Description" fields

### Actual Behavior

Currently the title and description of the images are lost, requiring rework to add this information

### Reproduction Steps

- Save a document in Libreoffice in ".odt" with an image that has an alternative title and descriptions.
- By right-clicking on properties, you can check the options tab and add title and description.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/2835460/9b47a640-1a68-46f0-bf21-e15ab6210fcb)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/2835460/2d69c9a6-9080-4710-908f-b19239451ff3)

Test document:
[Document.odt](https://github.com/ONLYOFFICE/DocumentServer/files/15381703/Document.odt)

- Import the document into the "Onlyoffice Personal" environment

- Access the document
- Right-click on the image
- Access the "advanced image settings" menu

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/2835460/9ccd9184-fcc7-4758-9ddb-bf5fbbc67f0d)

- Check the "Title" and "Description"

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/2835460/a4e4f4df-89e1-4fb9-a9d8-8f0a0c1a6362)

**Comment by rsnegirev** [comment]
Hi @sergiocarlotto 

Problem was fixed in this commit: https://github.com/ONLYOFFICE/core/commit/acbf5b0c400cdaad69be722671663dd47309f616

Fixes will be released in the next major version.

**Comment by sergiocarlotto** [comment]
Hi @rsnegirev 

Is there a release date for this fix?

Thank you very much

**Comment by rsnegirev** [comment]
@sergiocarlotto 

Sorry for a long answer. In the next couple of weeks.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
