### ISSUE TITLE
Unnecessary Full Font Embedding in PDF Conversion Increases File Size

### ISSUE THREAD

**Issue by Dlinw** [ONLYOFFICE/DocumentServer#2739]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

When converting DOCX to PDF using OnlyOffice, the PDF should only contain the subset of fonts used in the document, without embedding the entire font. This behavior helps keep the PDF size minimal.

### Actual Behavior

When converting DOCX to PDF, the resulting PDF contains both the embedded full fonts and their subsets. Embedding the complete fonts is unnecessary and significantly increases the PDF file size. I have tried to disable the full font embedding through the provided configurations, but I couldn't find the relevant configuration option.

**Comment by Dlinw** [comment]
I'm certain this is caused by using docxf forms, resulting in embedding the entire font. However, can this be avoided? Can I choose to include the font subset myself when filling it out?

**Comment by TatianaKirillova** [comment]
@Dlinw Hello!
Thank you for report.
If there is at least one form field, then we are forced to include the entire font (to fill the field correctly). If the document does not have form fields, it will be saved without additional fonts. If you have a file with no form fields, but saving as a pdf saves the entire font, please send it to us.

You can also avoid saving the full font set for a document containing form fields - if you save the file for printing (Print to PDF)

**Comment by Dlinw** [comment]
@TatianaKirillova
Thank you for your reply.

I find that embedding the full font is not very user-friendly, especially since Chinese fonts can make the PDF file extremely large, even though only a few characters are used when filling out the form.

In some cases, I can extract the font subset myself and embed it into the PDF. Additionally, when I use Adobe Acrobat to set up the form, the resulting PDF does not include the full font. It only specifies the font and font size to be used.

Therefore, I wonder if OnlyOffice could provide a configuration parameter that allows users to choose whether or not to embed the full font for the form.

**Comment by Dlinw** [comment]
@TatianaKirillova Thanks you

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
