### ISSUE TITLE
Post-Install Crash on Upgrade to 5.1.1-23 at Ubuntu 16.04

### ISSUE THREAD

**Issue by Nils160988** [ONLYOFFICE/DocumentServer#274]
After upgrade to version 5.1.1-23, the post-install script crashes after the line
Generating AllFonts.js, please wait...Done

Edit: Coming from Version 5.1.0-115

**What is the expected behavior?**
Smooth upgrade

**Operating System:**
Ubuntu 16.04 LTS
on vServer with Kernel 4.4.

Does anybody else see this issue? Any suggestions how to workaround?

**Comment by ShockwaveNN** [comment]
What is the error?

**Comment by Nils160988** [comment]
It gives

dpkg: error processing package onlyoffice-documentserver (--configure)
subprocess installed post-installation script returned error exit status 1

and then stops.

**Comment by ShockwaveNN** [comment]
May be duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/166
It's a known problem with upgrade process so strongly advice use `docker` images or perform clean install
