### ISSUE TITLE
Where can I find the old version 7.1.1 api docs ?

### ISSUE THREAD

**Issue by WangQingye** [ONLYOFFICE/DocumentServer#2742]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.11

### Expected Behavior

My project now is using version 7.1.1 but the api docs on website is version 8.0 now.
There are some new features are not in 7.1.1;
Now I want to develop a new plugin, I fllow the docs  use **Asc.editor.installDeveloperPlugin**, but the console tips the Asc.editor is not undefined, so I think maybe 7.1.1 is not support this api, so where can I find the old version's api docs?

please help me ,thanks so much!

### Actual Behavior

no need

### Reproduction Steps

no need

### Additional information

no need

**Comment by askonev** [comment]
@WangQingye https://api.onlyoffice.com does not store previous versions of documentation. But as a solution, you can check out the documentation source. The documentation site is basically built using JSDoc from the [sdkjs](https://github.com/ONLYOFFICE/sdkjs)

The earliest branch available today is `release/v7.5.0`

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
