### ISSUE TITLE
error connection refused after install 

### ISSUE THREAD

**Issue by wouterverduin** [ONLYOFFICE/DocumentServer#275]
i just installed only office document server by use of the documentation (https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx) 

However: i cant acces it through my browser, neither can i remove it. I was running an instance of home assistant aswell on the same VM, which i cant acces through browser anymore either. 

I tried removing it by using sudo apt-get remove onlyoffice-documentserver. The problem is it gives me an error: that connection is refused. 

Is there a way to remove the installation the hard way? I am running it in an VM with other software and i am not looking forward to having to restall the other things aswell..

**Comment by ShockwaveNN** [comment]
Closing due no responce
