### ISSUE TITLE
The radio buttons and checkboxes added in DOCXF cannot be used after being converted to PDF. 

### ISSUE THREAD

**Issue by Dlinw** [ONLYOFFICE/DocumentServer#2756]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

I hope that the form elements will function properly after being converted to PDF.

### Actual Behavior

The converted form is just a regular box, not a functional form element. When using OpenPDF, the form elements can be retrieved, but the radio button type is incorrectly retrieved as a checkbox type. Additionally, assigning values using OpenPDF does not work, and the radio buttons cannot be selected when the PDF is opened in a PDF viewer.

Here is the editing page in DOCXF：
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/45334447/d5fd37f7-8369-4284-9dba-69bd49d237ad)

Here is the effect of the PDF in the browser：
![CleanShot 2024-06-06 at 10 03 07](https://github.com/ONLYOFFICE/DocumentServer/assets/45334447/845b1e4a-468a-4240-b873-e0d8ef75c9d6)

### Additional information

Additionally, after setting the option values for the radio buttons, OpenPDF still retrieves the option values as Choice*.

**Comment by Dlinw** [comment]
The PDF obtained from the  desktop editor does not have the issue of being unable to select. However, the form type retrieved in OpenPDF still remains as checkbox type.

**Comment by TatianaKirillova** [comment]
Hello @Dlinw !
Sorry, I can't reproduce the problem with switching switches. But 
 I was able to reproduce the issue where they were showing up as a checkbox rather than a circular shape. To work correctly with forms, I suggest using the Google Chrome browser or Adobe Acrobat Reader if it is not possible to use the ONLYOFFICE editor.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
