### ISSUE TITLE
"hiding rows and columns" in a spreadsheet

### ISSUE THREAD

**Issue by zty381309501** [ONLYOFFICE/DocumentServer#2766]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

bug of DocumentServer 8.0.1version.The issue where rows or columns in a spreadsheet are hidden and cannot be unhidden to restore them can be translated into English as:

"The problem with spreadsheets where rows or columns, once hidden, cannot be unhidden to revert to their original state."
![mmexport1718768835612](https://github.com/ONLYOFFICE/DocumentServer/assets/54675237/f0518dc7-db7f-4b8c-b4a3-87869a0e256e)

### Actual Behavior

The issue where rows or columns in a spreadsheet are hidden and cannot be unhidden to restore them can be translated into English as:

"The problem with spreadsheets where rows or columns, once hidden, cannot be unhidden to revert to their original state."

**Comment by rsnegirev** [comment]
Hi @zty381309501 

Can you attach a problem file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
