### ISSUE TITLE
Error when editing fillable PDF with Javascript Editor

### ISSUE THREAD

**Issue by DrZoidberg09** [ONLYOFFICE/DocumentServer#2768]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1

### Expected Behavior

Editing every PDF possible, especially fillable PDFS

### Actual Behavior

Since version 8.1 filling forms throws this error described below

### Additional information

Browser Error Log

Uncaught TypeError: S.sc is not a function
    si https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:1398
    yf https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12903
    uJa https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12260
    eld https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12211
    KFc https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12211
    resize https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12288
    QBa https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12137
    LH https://domain.com/8.1.0-169/sdkjs/word/sdk-all-min.js:1454
    onLayoutChanged https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    onWindowResize https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    E https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    n https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    b https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    dispatch https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    handle https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
sdk-all.js:1398:198
    si https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:1398
    yf https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12903
    uJa https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12260
    eld https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12211
    KFc https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12211
    resize https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12288
    QBa https://domain.com/8.1.0-169/sdkjs/word/sdk-all.js:12137
    LH https://domain.com/8.1.0-169/sdkjs/word/sdk-all-min.js:1454
    onLayoutChanged https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    onWindowResize https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    E https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    n https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    b https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    dispatch https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8
    handle https://domain.com/8.1.0-169/web-apps/apps/pdfeditor/main/app.js:8

**Comment by TatianaKirillova** [comment]
Hello,  @DrZoidberg09 
Thanks for your request!
I can confirm that the problem exists, issue #68768 for your problem.

**Comment by TatianaKirillova** [comment]
@DrZoidberg09 I hasten to inform you that the problem has been fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/3ee0fe2b0a4188cbad030cac46928b644139d517) and will be included in the next release. Please don't miss the update!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
