### ISSUE TITLE
Time Tracking "Invalid time format"

### ISSUE THREAD

**Issue by ArkaineHeinlein** [ONLYOFFICE/DocumentServer#277]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Time tracking in projet = Invalid time format
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Project -> Time tracking -> New time tracking.

**What is the expected behavior?**
When I notice a time less than 1:00 I get the following message:
Invalid time format.

But when i notice a time upper 1:00 i have no error
![2018-03-27_14h59_15](https://user-images.githubusercontent.com/30461640/38495645-a101a3d0-3bfa-11e8-82a6-c34202890575.png)

**Did this work in previous versions of DocumentServer?**
Yes
**DocumentServer version:**
5.1.1.23
**Operating System:**
Ubuntu Server 16.04
**Browser version:**
Firefox 59.0.2

**Comment by ShockwaveNN** [comment]
Seems this is CommunityServer bug, not DocumentServer. Please duplicate it in https://github.com/ONLYOFFICE/CommunityServer/issues

**Comment by ArkaineHeinlein** [comment]
Thx i do tit ;)
