### ISSUE TITLE
ODT files: if saving file with a custom field, the custom property is wiped out from the file

### ISSUE THREAD

**Issue by adminceovision** [ONLYOFFICE/DocumentServer#2774]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

8.1.0-169

### Expected Behavior

Properties set in LibreOffice doesn't get erased when saving a file with OnlyOffice

### Actual Behavior

It's the follow up of this issue => https://github.com/ONLYOFFICE/DocumentServer/issues/2616

When setting a custom property in LibreOffice, displaying it in a custom field in the document, then opening the .odt file with OnlyOffice, if I save the file (event if not modifying anything around the custom field) and reopen it again in LibreOffice, the custom property has disappeared.

### Reproduction Steps

Exactly the same reproduction steps as in the original issue

**Comment by ElenaMaaya** [comment]
Hello @adminceovision!
Thank you for report!
I can confirm that the problem exists. I created ticket 68957 in our issue tracker with your issue.

**Comment by ElenaMaaya** [comment]
Hello @adminceovision! I have a good news! This issue will be fixed in the next release (commit https://github.com/ONLYOFFICE/core/commit/21ba3ac0c9c5f56a499580ff56af1c87f73877ad). Please keep checking for updates.

**Comment by cpot** [comment]
Very good, thank you !

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
