### ISSUE TITLE
Special Characters Displayed in Documents After Changing OnlyOffice Fonts on Server

### ISSUE THREAD

**Issue by avanhovedev** [ONLYOFFICE/DocumentServer#2778]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

8.0.1

### Expected Behavior

The text in the documents should display normally without any special characters.

### Actual Behavior

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/61686963/f57dabcf-0a46-4cd8-92af-29c3eca9547b)
Special characters appear in the document, which disrupts the readability. Please see the attached screenshot for a visual reference.

### Reproduction Steps

- Change the server-side fonts in OnlyOffice.
- Open any document that previously displayed correctly.

### Additional information

Hello,

I hope this message finds you well. We have encountered an issue with our OnlyOffice server setup. After updating the fonts on the server side, special characters are appearing when we open documents. This behavior was not observed before the font change. (We cleared server cache)

We would greatly appreciate your assistance in resolving this issue. Please let us know if there are any logs or further information we can provide that might help diagnose and fix the problem.

Thank you for your attention to this matter. We look forward to your prompt response.

**Comment by XDmitryK** [comment]
@avanhovedev Hi
If possible, can you attach the file here? And we need more information about the font. 1. What font? 2.Is this font available on your server? 3.If the font is not default, can I attach it here or give a link?
My point is that if this font is currently unavailable on the server after an update, then we have a mechanism for selecting a similar font, but it does not always work accurately.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by avanhovedev** [comment]
Hello @XDmitryK,

Sorry for the delay,

Actually if we update fonts on the server side , we open a browser private window , the new font is correctly displayed otherwise if we open the doc not in private window, we need to clear caches to display correctly.

Thanks in advanced,

Alexis

**Comment by avanhovedev** [comment]
Hello @XDmitryK ,
Can you reopen the issue ?

Thanks in advanced,

Alexis

**Comment by XDmitryK** [comment]
@avanhovedev Hi
If the problem is solved by simply clearing the cache, then I don't think you need to reopen the issue.
And soon a function for resetting the cache when generating fonts will be added
