### ISSUE TITLE
Spreadsheet load workbook with chart error

### ISSUE THREAD

**Issue by mymbrooks** [ONLYOFFICE/DocumentServer#2782]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.0.169

### Expected Behavior

workbook load fine

### Actual Behavior

workbook load error

Uncaught TypeError: Cannot read properties of undefined (reading 'val')
:1308/8.1.0-169/sdkj…ell/sdk-all.js:4217 

PS: 8.0 works fine, 8.1 show this error

sample file
[液压千斤顶.xlsx](https://github.com/user-attachments/files/16049372/default.xlsx)

**Comment by VladimirProkofiev52** [comment]
Hello! @mymbrooks 
I can confirm - this is bug, issue #68944.

Thanks for your report!

**Comment by mymbrooks** [comment]
@Rita-Bubnova Thanks This bug has been fixed in 8.1.1

**Comment by rsnegirev** [comment]
Hi @mymbrooks 

The error was fixed in 8.1.1, yes.

But here is still some problems in rendering with empty values. It will be fixed in the next major release.

**Comment by mymbrooks** [comment]
@rsnegirev There is another bug in latest version:
Uncaught TypeError: Cannot read properties of undefined (reading '0')    :1308/8.1.1-26/sdkjs…ell/sdk-all.js:3873

use this sample file
[测力环.xlsx](https://github.com/user-attachments/files/16666799/default.xlsx)

**Comment by rsnegirev** [comment]
Hi @mymbrooks 

The error occurs after certain actions with this file? Because I've just opened it and there is no errors while opening file.

**Comment by mymbrooks** [comment]
@rsnegirev Yes, the error was fixed in 8.1.3 thanks
