### ISSUE TITLE
First letter maj autocorrect

### ISSUE THREAD

**Issue by echanaron** [ONLYOFFICE/DocumentServer#2783]
**Feature request**

**Expected behavior**
First letters of first words of sentences are automatically turned maj.
In other words, "hello, ONLYOFFICE!" is turned automatically to "Hello, ONLYOFFICE!", with a maj H.
With a context option to revert it to the lower case, if the proposal was erroneous.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
