### ISSUE TITLE
Announcements of releases

### ISSUE THREAD

**Issue by y0va** [ONLYOFFICE/DocumentServer#279]
As onlyoffice spreadsheet editor  became unusable by this bug: https://github.com/ONLYOFFICE/DocumentServer/issues/270 I'd like to get a notification of a new release. Haven't found documentation about that. Is there a RSS feed, or mailing list about that?

**Comment by ShockwaveNN** [comment]
Github has ATOM feed for releases 
https://github.com/onlyoffice/documentserver/releases.atom
