### ISSUE TITLE
When I copy a piece of text containing comments, the original comment box is in the wrong position after pasting

### ISSUE THREAD

**Issue by YanaDH** [ONLYOFFICE/DocumentServer#2796]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.3.3

### Expected Behavior

When pasting text, the original comment is not affected

### Actual Behavior

When I copy a piece of text containing comments, the original comment box is in the wrong position after pasting, and after clicking Solve, the comments are not unhighlighted, deleting the comment text will report an error throughout the document

**Comment by Rita-Bubnova** [comment]
Hello, @YanaDH.
DocumentServer v8.1.1 is released. Is this issue relevant?

**Comment by ElenaMaaya** [comment]
Hello @YanaDH!
Thank you for report!
This is a known Bug 69146 in our  issue tracker.

**Comment by ElenaMaaya** [comment]
Hello @YanaDH! 
I have a good news! This issue will be fixed in the next release ([commit](https://github.com/ONLYOFFICE/sdkjs/commit/71519738137cbc39897c79c5feb63cf8c6ec0004)). 
Please keep checking for updates.

**Comment by ElenaMaaya** [comment]
Hello, @YanaDH! We will close the issue after the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
