### ISSUE TITLE
Unable to use formula like =Table1[@[Column1]]

### ISSUE THREAD

**Issue by rokam** [ONLYOFFICE/DocumentServer#2799]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.1.31

### Expected Behavior

When creating a formula, if I reference a cell inside a Table, it uses the direct sheet address (eg. `A2`) instead of 
`TableName[@[ColumnName]]`. And if I force the `TableName[@[ColumnName]]` I receive a formula error message.
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/2856518/2b3a54b6-bb94-433e-a45e-8b93837c392a)

### Actual Behavior

It should return the value of cell C11.

### Reproduction Steps

1. Create a table in your spreadsheet
2. Inside the table create a formula that references any cell in the same line.
3. Replace the address value with the equivalent Table formula format.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
