### ISSUE TITLE
Change default settings

### ISSUE THREAD

**Issue by marceln** [ONLYOFFICE/DocumentServer#28]
Is there any way to change the default settings in the Document Editor (post deployment) and have those apply to all users? 

For example, I'd like to change some settings related to collaborative editing but also to auto-saving. 

Thanks,
Marcel

**Comment by Dean13** [comment]
Hello,

Could you please specify, what exact kind of changes are to be made?

**Comment by trofim24** [comment]
Customizable options are described [here](http://api.onlyoffice.com/editors/advanced)
