### ISSUE TITLE
Behaviour of "save" doesn't meet expectations

### ISSUE THREAD

**Issue by y0va** [ONLYOFFICE/DocumentServer#280]
This is in the spreadsheeteditor on Documentserver 5.1.2 on Nextcloud 13.0.1 

If I click on "save" in the file menu nothing happens on the server file system. For stability reasons I would have expected nextcloud to create a new version of that document and SAVE that on the file system.

**Comment by ShockwaveNN** [comment]
Please, duplicate your newtcloud/owncloud related problem in https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues

**Comment by ShockwaveNN** [comment]
Seems this is a duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/116
