### ISSUE TITLE
Update the functional roadmap of the documentation plan

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/DocumentServer#2812]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Please update the functional roadmap of the document server change plan as appropriate

**Comment by svetlana81** [comment]
Hello. 
Thank you. We'll update the roadmap.

**Comment by yiwen9488** [comment]
Please update the functional roadmap of the document server change plan as appropriate
