### ISSUE TITLE
The editor version has been updated. The page will be reloaded to apply the changes.

### ISSUE THREAD

**Issue by spark-empty** [ONLYOFFICE/DocumentServer#2815]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.1.0

### Expected Behavior

7.5.1.0

### Actual Behavior

When I replaced the 7.5.1.0 version of DocumentServer with 8.1.1.0 version, no changes were made to other environments, and deployment was carried out according to the instructions at that address https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx However, when the new version opens the editor, it prompts that the editor version has been updated. The page will be reloaded for application. What configuration do I need to do to solve this version update issue? We look forward to your reply.

**Comment by spark-empty** [comment]
Hello, do you have time to answer my question?

**Comment by spark-empty** [comment]
This request address（ http://test.jckj.group/onlyoffice/8.1.1-26/doc/2dbd1a9ddf79486c8a4afbfc34d22716/c/?shardkey=2dbd1a9ddf79486c8a4afbfc34d22716&EIO=4&transport=polling&t=P4rs -Gv. 0&sd=2Aj4WsPgeUwvzZApAAAG), the previous version 7.5.1 did not have a version number, but after switching to the new version, it has always had the version numbers 8.1.1-26. This version number causes this prompt, and I am not sure how to clear this setting.

**Comment by askonev** [comment]
The problem was solved on the forum

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
