### ISSUE TITLE
Regarding the issue of XLSM table macros

### ISSUE THREAD

**Issue by DDDJing** [ONLYOFFICE/DocumentServer#2819]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I have an xlsm spreadsheet file that has been edited by onlyoffice. After downloading it locally, the office software no longer opens it. If the file extension is changed to xlsx, it can be opened, but the original macro has been lost. Have there been any updates recently that involve this issue, or are there any solutions

**Comment by l8556** [comment]
Hello @DDDJing 
It was not possible to reproduce this issue.

Can I ask for your spreadsheet to verify this?

And please describe the steps to reproduce in more detail:
- What changes are you making in spreadsheet
- In which office software are you trying to open the saved table after editing in onlyoffice

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
