### ISSUE TITLE
I was trying to open excel life with 22000 rows and it says "An error has occured while opening the file" Small files get opened in no time. seems there is problem in loading big files

### ISSUE THREAD

**Issue by vishalv26** [ONLYOFFICE/DocumentServer#282]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I was trying to open excel life with 22000 rows and it says "An error has occured while opening the file"
Small files get opened in no time. seems there is problem in loading big files
![2018-04-16 17_08_33-fao csv - corient cdrive](https://user-images.githubusercontent.com/22151336/38807034-b8f69f7a-416a-11e8-84d8-c6886749fa90.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Small files open perfectly. But when i try to open big files like the one attached. It fails with above screenshot

[FAO.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1915077/FAO.xlsx)
**What is the expected behavior?**
It should open and show content
**Did this work in previous versions of DocumentServer?**
I didn't check
**DocumentServer version:**
5.1.2 CE
**Operating System:**
Debian 9
**Browser version:**
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by ShockwaveNN** [comment]
This file opens fine for me on Documentserver 5.1.2 CE
What are the specs of server? I used DigitalOcean 2GB instance and everything is good.
You can also look to logs (`/var/log/onlyoffice` inside container for any errors)

**Comment by vishalv26** [comment]
I upgraded my instance for 2 gb still no luck

**Comment by ShockwaveNN** [comment]
You should look for any errors in log files
