### ISSUE TITLE
显示分享按钮

### ISSUE THREAD

**Issue by qiezicai888** [ONLYOFFICE/DocumentServer#2830]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/fd9e1b8a-99a1-445a-aedf-6e12210ac5b9">
这个分享按钮是怎么配置出来的，没有看到相关的配置

**Comment by Rita-Bubnova** [comment]
Hello, @qiezicai888.
Please, when creating an issue, fill in all the fields of the form on English.
