### ISSUE TITLE
Incorrect date returned by document fields

### ISSUE THREAD

**Issue by zer0ring** [ONLYOFFICE/DocumentServer#2831]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

8.1.0.169

### Expected Behavior

Document fields relating to the current date such as `&[Date]` should return the current date, the same should occur for examples displayed when choosing regional settings in File > Advanced Settings > Regional settings.
The same should occur for DocSpace documents opened in a web browser, ie: `&[Date]` = current date, regional settings example should contain the current date & time.

### Actual Behavior

`&[Date]` field used in the document (ie: document footer), returns the previous days' date, the same occurs for the example displayed when choosing regional settings in File > Advanced Settings > Regional settings, the example also shows the wrong time.
The same occurs for DocSpace documents opened in a web browser, ie: `&[Date]` = the previous days' date, regional settings example contains the the previous days' date & an incorrect time.
![image](https://github.com/user-attachments/assets/e5b08ad5-57a6-415f-8f9b-912b7ff3a233)

### Reproduction Steps

NB: the outcome of these steps is dependent upon regional settings, reproduction of issue may require changing system region or time zone.

### Desktop Editors
**Date field**
1. Create any document that supports date fields, ie: spreadsheet
2. Go to Layout > Header & Footer
3. In the footer add &[Date] then click OK
4. Go to File > Print
5. Compare the date in the print preview with current system date and time

**Regional settings example**
1. Go to File > Advanced Settings > Regional settings
2. Compare the date and time in the example displayed beside Region with current system date and time

### DocSpace Editors
Repeat above steps using DocSpace editors in web browser.

### Additional information

Refer to screenshot in Actual Behaviour section

**Comment by ElenaMaaya** [comment]
Hello @zer0ring! I have a good news! This issue will be fixed in the next release ([commit](https://github.com/ONLYOFFICE/web-apps/commit/d7501fcb929a49dcee1a3b3ac0f5d1cacc4eaf99)). Please keep checking for updates.

**Comment by zer0ring** [comment]
That's great, well done :)
I like OnlyOffice and seeing alternatives to major platforms grow & thrive, I look forward to future developments.

I found another issue around the same time as this one, but it's much, much more complicated, it's with formula parsing & execution, I don't even know how to describe it let alone why it's happening. I may open a new issue for it but the title will likely be genralised/misleading, someone with much more depth of knowledge than I would be required to investigate & interpret the issue.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

> I found another issue around the same time as this one, but it's much, much more complicated, it's with formula parsing & execution, I don't even know how to describe it let alone why it's happening. I may open a new issue for it but the title will likely be genralised/misleading, someone with much more depth of knowledge than I would be required to investigate & interpret the issue.

Can you create  separate issue?
