### ISSUE TITLE
Ctrl+; date input in Spreadsheets is missing UTC offset

### ISSUE THREAD

**Issue by t3hwx9** [ONLYOFFICE/DocumentServer#2832]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.1.27

### Expected Behavior

"Ctrl+;" shortcut acts like TODAY() function. Conditional formatting Date = Today works for any timezone.

### Actual Behavior

"Ctrl+;" inputs UTC date, missing timezone offset. It's also reproducible via Date-dependent conditional formatting logic. 
 
![Screenshot from 2024-08-03 01-38-08](https://github.com/user-attachments/assets/eea82d9f-99ca-40d1-932e-54bdb1f0220e)

### Reproduction Steps

0. Set your local timezone to UTC+ [offset] and time to less-than-[offset] past midnight.
1. Input date via TODAY() function
2. Input date via Ctrl+; shortcut in another cell
3. Results will be different. Conditional formatting using Date = Today or Yesterday will be wrong as well.

### Additional information

This issue seems to be related to https://github.com/ONLYOFFICE/DocumentServer/issues/1178 , which fixed NOW() function, but current date variable is used by other components as well.

**Comment by rsnegirev** [comment]
Hi @t3hwx9 

This is the same problem as in this issue: https://github.com/ONLYOFFICE/DocumentServer/issues/2446
