### ISSUE TITLE
New new document editing mode button can't be hidden

### ISSUE THREAD

**Issue by reposeredo** [ONLYOFFICE/DocumentServer#2834]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

8.1.1

### Expected Behavior

According to the [Changelog](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#810), version `8.1.0` added the following `Document` features:

- New button on the top toolbar for changing document editing mode: Editing, Reviewing, Viewing
- Added a parameter to hide the button for switching editing modes in the header: `customization` -> `layout` -> `header` -> `editMode`: `true/false` (`true` by default)

In our testing, setting `customization` -> `layout` -> `header` -> `editMode` to `false` does not appear to hide the new button.

### Actual Behavior

The new document editing mode button is still visible after setting `customization` -> `layout` -> `header` -> `editMode` to `false`.

**Comment by avdddd1111** [comment]
Hello @reposeredo !

Button hiding settings are available to users of the Developer and Enterprise editions with an extended license.

This setting is not available to Community edition users.

If you have the Developer or Enterprise edition and do not have an extended license, please contact the sales department. sales@onlyoffice.com

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
