### ISSUE TITLE
Please document the permissions required to save an edited `PDF` document

### ISSUE THREAD

**Issue by reposeredo** [ONLYOFFICE/DocumentServer#2835]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Could you please document which permission settings are required to be `true` in order to save a `PDF` document?

Using the `8.1.1` Docker image, I am getting the following error when attempting to save an edited `PDF` document:

`You are trying to perform an action you do not have rights for. Please contact your Document Server administrator.`

Using an identical permission set, I have no issue saving non-PDF documents (`docx`, `xlsx`, `pptx`, etc.). It's not obvious to me what the problem is.

**Comment by sreerajkrishnank** [comment]
Is it implemented yet? 
If not, how do I hide the edit PDF button under tool bar using the configurations?

**Comment by avdddd1111** [comment]
Hello @sreerajkrishnank, @reposeredo !

The PDF saving feature has been implemented and is planned for a future release!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
