### ISSUE TITLE
A cross-reference inside a table misses the number

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2836]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.1

### Expected Behavior

It should be possible to insert a reference inside a table.

### Actual Behavior

When inserting a reference inside a table and adding a new reference, the number of the former reference disappears.

### Reproduction Steps

Steps:
- Insert a table
- Insert a caption, e.g. Table 1
- Move this legend inside the table
- Now insert a second table
- Insert a caption for this second table
- => The number of the first caption has disappeared

![image](https://github.com/user-attachments/assets/108d324c-ed1f-4817-bcb9-9c86d7b3ffd0)

**Comment by XDmitryK** [comment]
@parrenin Hi

> Move this legend inside the table

You used Copy\Paste or Dran'n'Drop? Unfortunately, I can't repeat your scenario yet.

Uploading 2024-08-19 16-29-54.mp4…

**Comment by parrenin** [comment]
I used cut/paste to move the legend inside the table.

**Comment by parrenin** [comment]
Here is a video showing the problem:

https://github.com/user-attachments/assets/21a423c4-9f1a-49bf-b02e-140bf7e6d0d9

**Comment by XDmitryK** [comment]
@parrenin Yes, this issue still exists in 8.1.1 but is not reproducible in the development version. We will not close this request until the next release.
