### ISSUE TITLE
 Please help me find sdkjs-native location

### ISSUE THREAD

**Issue by JiffyChen** [ONLYOFFICE/DocumentServer#2838]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

![image](https://github.com/user-attachments/assets/f22f10f3-7210-44c6-89fe-80f8c9582509)
I have an application developed on version 7.2.1 that extends the configuration of line charts, specifically the advanced settings for primary and secondary coordinate configurations in advanced chart settings. However, I noticed that in version 8.0.0, this functionality was refactored and moved to sdkjs-native, but I cannot locate sdkjs-native in the 8.x version. Could you please help me find its location? Thank you

**Comment by trofim24** [comment]
Thanks for interesting in our product.
This code was used only for our mobile apps for [iOS](https://www.onlyoffice.com/office-for-ios.aspx) and [Android](https://www.onlyoffice.com/office-for-android.aspx). We changed interaction with js code.
sdkjs-native is not an open source part for our mobile apps.

Should you have any questions or requests please contact Ascensio System SIA at sales@onlyoffice.com
