### ISSUE TITLE
it's to slowly to loading onlyOffice in a app。anyway to fix this?

### ISSUE THREAD

**Issue by BoYangZuo** [ONLYOFFICE/DocumentServer#284]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Please fill all the field and explain your problem in more details

**Comment by BoYangZuo** [comment]
I have access to onlyOffice in the app. Load documents through UIWebView. However, each loading time is very long. Even if the network is very good, a 15KB word document needs to open in an average of 2 to 3 minutes. why is that? Is there a solution?

**Comment by ShockwaveNN** [comment]
You still not filled any of fields. I'm not sure if this desktop, or mobile version. Not to mention versions
