### ISSUE TITLE
Debian 9 Installation onlyoffice-documentserver crash

### ISSUE THREAD

**Issue by devwald** [ONLYOFFICE/DocumentServer#285]
**Do you want to request a *feature* or report a *bug*?**
a bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Fresh install 
My configuration :

OS     : Debian 9.4 amd64
Kernel : 3.16.0-5-amd64
CPU    : 2x AMD Opteron(tm) Processor 6376                 
Mem    : 7.22 GB

**What is the expected behavior?**
Error during fresh install
**Did this work in previous versions of DocumentServer?**
Fresh install
**DocumentServer version:**
5.1.2-9
**Operating System:**
Debian 9
**Browser version:**

```
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sudo apt install onlyoffice-documentserver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  onlyoffice-documentserver
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/201 MB of archives.
After this operation, 777 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package onlyoffice-documentserver.
(Reading database ... 130098 files and directories currently installed.)
Preparing to unpack .../onlyoffice-documentserver_5.1.2-9_amd64.deb ...
Unpacking onlyoffice-documentserver (5.1.2-9) ...

Setting up onlyoffice-documentserver (5.1.2-9) ...
dpkg: error processing package onlyoffice-documentserver (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 onlyoffice-documentserver
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I already see ant test https://github.com/ONLYOFFICE/DocumentServer/issues/166 (uninstall/install nginx and nginx-extras) 

Any idea ?

Thanks

**Comment by devwald** [comment]
Thanks for answer. How can i do for having log with /var/lib/dpkg/info/onlyoffice-documentserver.postinst ?

**Comment by ShockwaveNN** [comment]
@devwald you can use this answer https://serverfault.com/a/77819/98467

**Comment by devwald** [comment]
Ok thanks.

I have this : 
`s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ set -e
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
^Z
[1]+  Stopped                 sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
s_sc@v-dev-fw\ /var/lib/dpkg/info  $vi /var/lib/dpkg/info/onlyoffice-documentserver.postinst
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
s_sc@v-dev-fw\ /var/lib/dpkg/info  $rm /var/cache/debconf/
config.dat         config.dat-old     passwords.dat      templates.dat      templates.dat-old  
s_sc@v-dev-fw\ /var/lib/dpkg/info  $rm /var/cache/debconf/*
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ ! 1 ]
+ [ -z  ]
+ exec
+ [  ]
+ exec
+ DEBCONF_REDIR=1
+ export DEBCONF_REDIR
+ DIR=/var/www/onlyoffice
+ LOG_DIR=/var/log/onlyoffice
+ APP_DIR=/var/lib/onlyoffice
+ DEFAULT_CONFIG=/etc/onlyoffice/documentserver/default.json
+ EXAMPLE_CONFIG=/etc/onlyoffice/documentserver-example/default.json
+ JSON=json -I -q -f /etc/onlyoffice/documentserver/default.json
+ JSON_EXAMPLE=json -q -f /etc/onlyoffice/documentserver-example/default.json
+ OLD_VERSION=
+ DB_HOST=
+ DB_USER=
+ DB_PWD=
+ DB_NAME=
+ RABBITMQ_HOST=
+ RABBITMQ_USER=
+ RABBITMQ_PWD=
+ REDIS_HOST=
+ CLUSTER_MODE=
+ adduser --quiet --home /var/www/onlyoffice --system --group onlyoffice
+ adduser --quiet www-data onlyoffice
+ npm list -g json
+ npm install -g json
+ read_saved_params
+ db_get onlyoffice/db-host
+ _db_cmd GET onlyoffice/db-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ DB_HOST=localhost
+ db_get onlyoffice/db-user
+ _db_cmd GET onlyoffice/db-user
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-user
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_USER=onlyoffice
+ db_get onlyoffice/db-pwd
+ _db_cmd GET onlyoffice/db-pwd
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-pwd
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_PWD=onlyoffice
+ db_get onlyoffice/db-name
+ _db_cmd GET onlyoffice/db-name
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-name
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_NAME=onlyoffice
+ db_get onlyoffice/rabbitmq-host
+ _db_cmd GET onlyoffice/rabbitmq-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ RABBITMQ_HOST=localhost
+ db_get onlyoffice/rabbitmq-user
+ _db_cmd GET onlyoffice/rabbitmq-user
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-user
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=guest
+ return 0
+ RABBITMQ_USER=guest
+ db_get onlyoffice/rabbitmq-pwd
+ _db_cmd GET onlyoffice/rabbitmq-pwd
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-pwd
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=guest
+ return 0
+ RABBITMQ_PWD=guest
+ db_get onlyoffice/redis-host
+ _db_cmd GET onlyoffice/redis-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/redis-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ REDIS_HOST=localhost
+ db_get onlyoffice/cluster-mode
+ _db_cmd GET onlyoffice/cluster-mode
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/cluster-mode
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=false
+ return 0
+ CLUSTER_MODE=false
+ db_get onlyoffice/jwt-enabled
+ _db_cmd GET onlyoffice/jwt-enabled
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-enabled
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=false
+ return 0
+ JWT_ENABLED=false
+ db_get onlyoffice/jwt-secret
+ _db_cmd GET onlyoffice/jwt-secret
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-secret
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=secret
+ return 0
+ JWT_SECRET=secret
+ db_get onlyoffice/jwt-header
+ _db_cmd GET onlyoffice/jwt-header
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-header
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=Authorization
+ return 0
+ JWT_HEADER=Authorization
+ install_db
+ CONNECTION_PARAMS=-hlocalhost -Uonlyoffice -w
+ [ -n onlyoffice ]
+ export PGPASSWORD=onlyoffice
+ PSQL=psql -q -hlocalhost -Uonlyoffice -w
+ CREATEDB=createdb -hlocalhost -Uonlyoffice -w
+ set +e
+ 
+ ERRCODE=0
+ [ 0 -ne 0 ]
+ set -e
+ psql -q -hlocalhost -Uonlyoffice -w -c ;
+ psql+  -q -hlocalhost -Uonlyoffice -w -lt
cut -d| -f 1
+ grep -qw onlyoffice
+ [ ! false = true ]
+ psql -q -hlocalhost -Uonlyoffice -w -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql
+ psql -q -hlocalhost -Uonlyoffice -w -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql
+ save_db_params
+ json -I -q -f /etc/onlyoffice/documentserver/default.json -e this.services.CoAuthoring.sql.dbHost = 'localhost'
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 106: /var/lib/dpkg/info/onlyoffice-documentserver.postinst: json: not found
`

**Comment by devwald** [comment]
Ok thanks.

This is the result : 
`s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ set -e
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
^Z
[1]+  Stopped                 sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
s_sc@v-dev-fw\ /var/lib/dpkg/info  $vi /var/lib/dpkg/info/onlyoffice-documentserver.postinst
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
s_sc@v-dev-fw\ /var/lib/dpkg/info  $rm /var/cache/debconf/
config.dat         config.dat-old     passwords.dat      templates.dat      templates.dat-old  
s_sc@v-dev-fw\ /var/lib/dpkg/info  $rm /var/cache/debconf/*
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ ! 1 ]
+ [ -z  ]
+ exec
+ [  ]
+ exec
+ DEBCONF_REDIR=1
+ export DEBCONF_REDIR
+ DIR=/var/www/onlyoffice
+ LOG_DIR=/var/log/onlyoffice
+ APP_DIR=/var/lib/onlyoffice
+ DEFAULT_CONFIG=/etc/onlyoffice/documentserver/default.json
+ EXAMPLE_CONFIG=/etc/onlyoffice/documentserver-example/default.json
+ JSON=json -I -q -f /etc/onlyoffice/documentserver/default.json
+ JSON_EXAMPLE=json -q -f /etc/onlyoffice/documentserver-example/default.json
+ OLD_VERSION=
+ DB_HOST=
+ DB_USER=
+ DB_PWD=
+ DB_NAME=
+ RABBITMQ_HOST=
+ RABBITMQ_USER=
+ RABBITMQ_PWD=
+ REDIS_HOST=
+ CLUSTER_MODE=
+ adduser --quiet --home /var/www/onlyoffice --system --group onlyoffice
+ adduser --quiet www-data onlyoffice
+ npm list -g json
+ npm install -g json
+ read_saved_params
+ db_get onlyoffice/db-host
+ _db_cmd GET onlyoffice/db-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ DB_HOST=localhost
+ db_get onlyoffice/db-user
+ _db_cmd GET onlyoffice/db-user
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-user
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_USER=onlyoffice
+ db_get onlyoffice/db-pwd
+ _db_cmd GET onlyoffice/db-pwd
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-pwd
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_PWD=onlyoffice
+ db_get onlyoffice/db-name
+ _db_cmd GET onlyoffice/db-name
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-name
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_NAME=onlyoffice
+ db_get onlyoffice/rabbitmq-host
+ _db_cmd GET onlyoffice/rabbitmq-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ RABBITMQ_HOST=localhost
+ db_get onlyoffice/rabbitmq-user
+ _db_cmd GET onlyoffice/rabbitmq-user
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-user
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=guest
+ return 0
+ RABBITMQ_USER=guest
+ db_get onlyoffice/rabbitmq-pwd
+ _db_cmd GET onlyoffice/rabbitmq-pwd
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-pwd
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=guest
+ return 0
+ RABBITMQ_PWD=guest
+ db_get onlyoffice/redis-host
+ _db_cmd GET onlyoffice/redis-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/redis-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ REDIS_HOST=localhost
+ db_get onlyoffice/cluster-mode
+ _db_cmd GET onlyoffice/cluster-mode
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/cluster-mode
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=false
+ return 0
+ CLUSTER_MODE=false
+ db_get onlyoffice/jwt-enabled
+ _db_cmd GET onlyoffice/jwt-enabled
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-enabled
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=false
+ return 0
+ JWT_ENABLED=false
+ db_get onlyoffice/jwt-secret
+ _db_cmd GET onlyoffice/jwt-secret
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-secret
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=secret
+ return 0
+ JWT_SECRET=secret
+ db_get onlyoffice/jwt-header
+ _db_cmd GET onlyoffice/jwt-header
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-header
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=Authorization
+ return 0
+ JWT_HEADER=Authorization
+ install_db
+ CONNECTION_PARAMS=-hlocalhost -Uonlyoffice -w
+ [ -n onlyoffice ]
+ export PGPASSWORD=onlyoffice
+ PSQL=psql -q -hlocalhost -Uonlyoffice -w
+ CREATEDB=createdb -hlocalhost -Uonlyoffice -w
+ set +e
+ 
+ ERRCODE=0
+ [ 0 -ne 0 ]
+ set -e
+ psql -q -hlocalhost -Uonlyoffice -w -c ;
+ psql+  -q -hlocalhost -Uonlyoffice -w -lt
cut -d| -f 1
+ grep -qw onlyoffice
+ [ ! false = true ]
+ psql -q -hlocalhost -Uonlyoffice -w -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql
+ psql -q -hlocalhost -Uonlyoffice -w -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql
+ save_db_params
+ json -I -q -f /etc/onlyoffice/documentserver/default.json -e this.services.CoAuthoring.sql.dbHost = 'localhost'
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 106: /var/lib/dpkg/info/onlyoffice-documentserver.postinst: json: not found
`

**Comment by devwald** [comment]
Ok thanks.

This is the result : 

```
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ set -e
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
^Z
[1]+  Stopped                 sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
s_sc@v-dev-fw\ /var/lib/dpkg/info  $vi /var/lib/dpkg/info/onlyoffice-documentserver.postinst
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
s_sc@v-dev-fw\ /var/lib/dpkg/info  $rm /var/cache/debconf/
config.dat         config.dat-old     passwords.dat      templates.dat      templates.dat-old  
s_sc@v-dev-fw\ /var/lib/dpkg/info  $rm /var/cache/debconf/*
s_sc@v-dev-fw\ /var/lib/dpkg/info  $sh /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure
+ . /usr/share/debconf/confmodule
+ [ ! 1 ]
+ [ -z  ]
+ exec
+ [  ]
+ exec
+ DEBCONF_REDIR=1
+ export DEBCONF_REDIR
+ DIR=/var/www/onlyoffice
+ LOG_DIR=/var/log/onlyoffice
+ APP_DIR=/var/lib/onlyoffice
+ DEFAULT_CONFIG=/etc/onlyoffice/documentserver/default.json
+ EXAMPLE_CONFIG=/etc/onlyoffice/documentserver-example/default.json
+ JSON=json -I -q -f /etc/onlyoffice/documentserver/default.json
+ JSON_EXAMPLE=json -q -f /etc/onlyoffice/documentserver-example/default.json
+ OLD_VERSION=
+ DB_HOST=
+ DB_USER=
+ DB_PWD=
+ DB_NAME=
+ RABBITMQ_HOST=
+ RABBITMQ_USER=
+ RABBITMQ_PWD=
+ REDIS_HOST=
+ CLUSTER_MODE=
+ adduser --quiet --home /var/www/onlyoffice --system --group onlyoffice
+ adduser --quiet www-data onlyoffice
+ npm list -g json
+ npm install -g json
+ read_saved_params
+ db_get onlyoffice/db-host
+ _db_cmd GET onlyoffice/db-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ DB_HOST=localhost
+ db_get onlyoffice/db-user
+ _db_cmd GET onlyoffice/db-user
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-user
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_USER=onlyoffice
+ db_get onlyoffice/db-pwd
+ _db_cmd GET onlyoffice/db-pwd
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-pwd
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_PWD=onlyoffice
+ db_get onlyoffice/db-name
+ _db_cmd GET onlyoffice/db-name
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/db-name
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=onlyoffice
+ return 0
+ DB_NAME=onlyoffice
+ db_get onlyoffice/rabbitmq-host
+ _db_cmd GET onlyoffice/rabbitmq-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ RABBITMQ_HOST=localhost
+ db_get onlyoffice/rabbitmq-user
+ _db_cmd GET onlyoffice/rabbitmq-user
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-user
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=guest
+ return 0
+ RABBITMQ_USER=guest
+ db_get onlyoffice/rabbitmq-pwd
+ _db_cmd GET onlyoffice/rabbitmq-pwd
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/rabbitmq-pwd
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=guest
+ return 0
+ RABBITMQ_PWD=guest
+ db_get onlyoffice/redis-host
+ _db_cmd GET onlyoffice/redis-host
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/redis-host
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=localhost
+ return 0
+ REDIS_HOST=localhost
+ db_get onlyoffice/cluster-mode
+ _db_cmd GET onlyoffice/cluster-mode
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/cluster-mode
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=false
+ return 0
+ CLUSTER_MODE=false
+ db_get onlyoffice/jwt-enabled
+ _db_cmd GET onlyoffice/jwt-enabled
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-enabled
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=false
+ return 0
+ JWT_ENABLED=false
+ db_get onlyoffice/jwt-secret
+ _db_cmd GET onlyoffice/jwt-secret
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-secret
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=secret
+ return 0
+ JWT_SECRET=secret
+ db_get onlyoffice/jwt-header
+ _db_cmd GET onlyoffice/jwt-header
+ _db_internal_IFS= 	

+ IFS= 
+ printf %s\n GET onlyoffice/jwt-header
+ IFS= 	

+ IFS=
 read -r _db_internal_line
+ RET=Authorization
+ return 0
+ JWT_HEADER=Authorization
+ install_db
+ CONNECTION_PARAMS=-hlocalhost -Uonlyoffice -w
+ [ -n onlyoffice ]
+ export PGPASSWORD=onlyoffice
+ PSQL=psql -q -hlocalhost -Uonlyoffice -w
+ CREATEDB=createdb -hlocalhost -Uonlyoffice -w
+ set +e
+ 
+ ERRCODE=0
+ [ 0 -ne 0 ]
+ set -e
+ psql -q -hlocalhost -Uonlyoffice -w -c ;
+ psql+  -q -hlocalhost -Uonlyoffice -w -lt
cut -d| -f 1
+ grep -qw onlyoffice
+ [ ! false = true ]
+ psql -q -hlocalhost -Uonlyoffice -w -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql
+ psql -q -hlocalhost -Uonlyoffice -w -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql
+ save_db_params
+ json -I -q -f /etc/onlyoffice/documentserver/default.json -e this.services.CoAuthoring.sql.dbHost = 'localhost'
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 106: /var/lib/dpkg/info/onlyoffice-documentserver.postinst: json: not found
```

**Comment by ShockwaveNN** [comment]
@devwald try to install `json` via `npm install json  -g`

**Comment by devwald** [comment]
It's OK : 
`root@v-dev-fw\ /home/wald_f  $npm config set proxy http://wwwcache.uhb.fr:8080
root@v-dev-fw\ /home/wald_f  $npm config set https-proxy http://wwwcache.uhb.fr:8080
root@v-dev-fw\ /home/wald_f  $npm install json -g
/usr/bin/json -> /usr/lib/node_modules/json/lib/json.js
/usr/lib
└── json@9.0.6 `

And there is no error now when i run sh -x /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure

Thanks.
