### ISSUE TITLE
Broken text referenced cells on xls files

### ISSUE THREAD

**Issue by patotorres** [ONLYOFFICE/DocumentServer#2860]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.1.26

### Expected Behavior

If you have a cell that referenced another cell with text instead of numbers, both cells must show the same content

### Actual Behavior

Cell thats references the text cell show 0 instead of "hello world" or whetever text

### Reproduction Steps

Create an XLS file with content on A1 "Hello world", content of A2 =A1, then open it on onlyoffice just fot view or convert it to xlsx and open it in rw mode, cell A2 shows 0

**Comment by VladimirProkofiev52** [comment]
Hello! @patotorres 
I was unable to replicate your issue. 
Could you let me know which editor you're using to create the original file? 
We recently released version 8.1.3 of the editor—does the issue persist in this new version? 
Also, try clearing your browser cache and see if the problem still occurs.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
