### ISSUE TITLE
Pptx preview, with image content covering text

### ISSUE THREAD

**Issue by 9527-lang** [ONLYOFFICE/DocumentServer#2862]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
preview

Error screenshot：
![image](https://github.com/user-attachments/assets/d75926d4-be50-497f-a002-e9c9a3187056)

Local effect：
![image](https://github.com/user-attachments/assets/089e4f5c-d167-4381-9144-6885e578248d)

**Comment by ElenaMaaya** [comment]
Hello @9527-lang!
Thank you for report!
Could you attach the file with the problem?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
