### ISSUE TITLE
pdf (convert from excel by ConvertService api )  insert image watermark  was incorrect.

### ISSUE THREAD

**Issue by givelin6782** [ONLYOFFICE/DocumentServer#2866]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Docker

### Version information

8.10

### Expected Behavior

insert image watermark to a pdf that convert by onlyoffice api (ConvertService.ashx)from an excel file . Can be fully displayed.,like this attached image that convert pdf form Microsoft office . i add image watermark by aspose.pdf

![4830bf12511783049a26859dcb66cb4d](https://github.com/user-attachments/assets/0835d10a-ad86-488a-a4d2-aeb431f4bb2c)

### Actual Behavior

the image watermark is Blocked by merging cells

![e39fe97b72d7cdce46eea8d2d9cab98a](https://github.com/user-attachments/assets/3702db6d-c7b3-4e01-acdf-5f474fa4a863)

**Comment by askonev** [comment]
@givelin6782 greetings. Can you attach the config with which you install watermark via Convert Service?

**Comment by givelin6782** [comment]
@askonev  thanks a lot for your response . 

the watermark is image formate like .jpg , not text , and to add text watermark via Convert Service is workable

BUT Convert Service can NOT add IMAGE watermark, so i use Aspose.pdf to add image watermark ,and it is not workable.

**Comment by askonev** [comment]
@givelin6782 I didn't fully understand the script.

You get a pdf with a jpg watermark-style image in the editor

The next step is to convert to xlsx format.

Did I understand correctly?

**Comment by givelin6782** [comment]
> @givelin6782 I didn't fully understand the script.
> 
> You get a pdf with a jpg watermark-style image in the editor
> 
> The next step is to convert to xlsx format.
> 
> Did I understand correctly?

INCORRECT

how can i  add jpg watermark to pdf use api (ConvertService.ashx) ?

**Comment by askonev** [comment]
@givelin6782 The **document conversion service** does not implement the functionality of adding watermark from images.

The correct way to add watermark via jpg is to use the [Web Document Builder API](https://api.onlyoffice.com/editors/documentbuilderapi)

The process is more complicated if you use the conversion service, but it is not critical

1. Configure the docbuilder script

Adding the url to the document in the OpenFile method

like this https://api.onlyoffice.com/docbuilder/howitworks/globalvariable

2. Implement the script

[Watermark settings](https://api.onlyoffice.com/officeapi/textdocumentapi/apiwatermarksettings)

3. We send a request to the WebDocumentBuilder service containing the url of the script

```json
{
    "async": true,
    "url": "https://example.com/url-to-example-script.docbuilder"
}
