### ISSUE TITLE
when I try to apply a specific formula, I get an error

### ISSUE THREAD

**Issue by lea-aglz** [ONLYOFFICE/DocumentServer#2869]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

8.1.1.26

### Expected Behavior

When I apply a formula, the apply worked.

### Actual Behavior

The formula : =ROUND(AVERAGEIF(D105:D136,"<>0",AU105:AU136),2)
When I apply a formula, I have an error : 
![image](https://github.com/user-attachments/assets/44e3a4fe-908f-4f3d-89a7-1bdfd25246e0)
The video of the process : 

https://github.com/user-attachments/assets/2baccfcd-bfdf-40a7-b120-3ad27763f439

After the error message, I can't do anything on the file. 

### Reproduction Steps

1. I open a file with Only Office 
2. I tried to apply my formula : =ROUND(AVERAGEIF(D105:D136,"<>0",AU105:AU136),2)
3. There are an error message, and I can't do anything on the file

**Comment by VladimirProkofiev52** [comment]
Hello! @lea-aglz 
We’re aware of this issue, and our team is already working on it. The fix is expected to be included in the next minor version of the editor.
Thanks for your report!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
