### ISSUE TITLE
受保护的文档

### ISSUE THREAD

**Issue by liu666-dev** [ONLYOFFICE/DocumentServer#2877]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

对于受保护的文档，文件中的有些内容是可以编辑，有些内容是不能编辑的，在onlyoffice中统计不能进行编辑

**Comment by Rita-Bubnova** [comment]
Hello, @liu666-dev.
Please, when creating an issue, fill in all the fields of the form on English.
