### ISSUE TITLE
When OnlyOffice 8.1.1 is installed on the arm architecture, the custom plug-in does not take effect

### ISSUE THREAD

**Issue by buddy-lin** [ONLYOFFICE/DocumentServer#2881]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.1

### Expected Behavior

add helloworld plugin. but the custom plug-in does not take effect.
![image](https://github.com/user-attachments/assets/fe497dee-e69f-4033-b216-9f368f7ea3e7)

### Actual Behavior

1.pull image.
docker pull onlyoffice/documentserver:8.1.1

2.run.
docker run -i -t -d -p 80:80 --restart=always -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver:8.1.1

3.add helloworld plugin.
![image](https://github.com/user-attachments/assets/ba428da2-1fd0-4b61-bab2-20ce2f6d2737)

4.the custom plug-in does not take effect.
![image](https://github.com/user-attachments/assets/fe497dee-e69f-4033-b216-9f368f7ea3e7)

**Comment by VladimirProkofiev52** [comment]
Hello! @buddy-lin 
Could you please let me know how you added the plugin? 
After adding the plugin, did you restart the services within the container using the command: `supervisorctl restart all` ?

**Comment by buddy-lin** [comment]
> Hello! 你好!@buddy-lin Could you please let me know how you added the plugin?你能让我知道你是如何添加插件的吗? After adding the plugin, did you restart the services within the container using the command: `supervisorctl restart all` ?添加插件后，是否使用命令重新启动容器内的服务:?

Copy the plug-in to the /var/www/onlyoffice/documentserver/sdkjs-plugins directory.
The container has been restarted.
X86 is normal.

**Comment by VladimirProkofiev52** [comment]
Could you please confirm if the issue has been resolved and is no longer occurring?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
