### ISSUE TITLE
In the document editor, the table of contents is built without a hierarchy of headings.

### ISSUE THREAD

**Issue by Belovk-RARUS** [ONLYOFFICE/DocumentServer#2883]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.3.4

### Expected Behavior

The creation of the table of contents takes into account the hierarchy of headings.

### Actual Behavior

The document has several headings and subheadings in them. When creating a table of contents, it is built without hierarchy, but simply a general list. In documents created in OnlyOffice 8.0, the table of contents is displayed correctly, with hierarchy. The problem occurs only when creating a table of contents.

### Reproduction Steps

Insert a new table of contents into the document and it will be generated without a heading hierarchy.

[Table of contents_8.1_bad.docx](https://github.com/user-attachments/files/16962249/Table.of.contents_8.1_bad.docx)
[Table of contents_8.0.docx](https://github.com/user-attachments/files/16962252/Table.of.contents_8.0.docx)

**Comment by uc-ai2** [comment]
This issue will be fixed in the next major release, don't miss the update.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
