### ISSUE TITLE
converter > .wps(19kb) >  double free or corruption (fasttop)

### ISSUE THREAD

**Issue by gowy222** [ONLYOFFICE/DocumentServer#2889]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

Version: 8.0.1. Build: 31

### Expected Behavior

wps to pdf converter should work..

because other filetype works fine! 

just bug with .wps office file

(tested same file libreoffice works fine)

### Actual Behavior

```
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2024-09-14T15:08:58.372] [ERROR] [localhost] [conv_uidrksc1cgyaxkaiqbhh99f_docx] [userId] nodeJS - stdout:
[2024-09-14T15:08:58.372] [ERROR] [localhost] [conv_uidrksc1cgyaxkaiqbhh99f_docx] [userId] nodeJS - stderr:double free or corruption (fasttop)

[2024-09-14T15:08:58.372] [ERROR] [localhost] [conv_uidrksc1cgyaxkaiqbhh99f_docx] [userId] nodeJS - ExitCode (code=0;signal=SIGABRT;error:-80)

```

### Reproduction Steps

wps to pdf/docx

### Additional information

```
post '/ConvertService.ashx'

req body== {
  async: false,
  filetype: 'wps',
  key: 'uidxxxxx...',
  outputtype: 'docx',
  url: 'https://xxxx/somefile.wps',
  codePage: 65001,
  region: 'zh-CN'
}

respond == { error: -3 }
```

**Comment by l8556** [comment]
Hello @gowy222 !

It was not possible to reproduce this problem.

If possible, please attach a wps document on which the problem is reproduced

Tested on DS version 8.1.1.27

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
