### ISSUE TITLE
Document Bouncing When Editing A Shared Document #3

### ISSUE THREAD

**Issue by MaximeMaW** [ONLYOFFICE/DocumentServer#2892]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1.1

### Expected Behavior

When editing a document, I want to be able to see what I'm editing. I don't want the document to start jumping up and down every time someone else on the document makes an edit.

### Actual Behavior

When editing a shared document, whenever someone makes an edit the document would jump around. So, when working on a shared document with multiple people, the document is very jittery. It is constantly jumping up and down, making it feel like you are editing during an earthquake.

[video_earthquake.webm](https://github.com/user-attachments/assets/6c1f7dd8-380f-4adc-8a5e-5d27734d70ce)

### Reproduction Steps

* Share a document with multiple people using an external link
* Set everyone's access (the shared external link) to full access
* Have everyone edit the document at the same time live

### Additional information

Seems like a regression from:
https://github.com/ONLYOFFICE/DocumentServer/issues/1955
https://github.com/ONLYOFFICE/DocumentServer/issues/1999
https://github.com/ONLYOFFICE/DocumentServer/issues/2212
https://github.com/ONLYOFFICE/DocumentServer/issues/2445

So I copied mostly the issue.

**Comment by TatianaKirillova** [comment]
Hello @MaximeMaW! 
Thank you for your request! Please update the version to 8.1.1 - there was an important [correction](https://github.com/ONLYOFFICE/sdkjs/commit/c9979671c7278b0c1965d535e1525ccefa3e50f8) of problems with the cursor during joint editing.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by MaximeMaW** [comment]
Many thanks, indeed the problem seems solved so far :tada:

**Comment by samuk** [comment]
If I'm seeing this in ONLYOFFICE Docs 9.1.0 should I open a fresh issue?

**Comment by Rita-Bubnova** [comment]
> If I'm seeing this in ONLYOFFICE Docs 9.1.0 should I open a fresh issue?

Yes, please, create a new issue.
