### ISSUE TITLE
Feature request: save annotated PDF directly

### ISSUE THREAD

**Issue by hermeneuticlens** [ONLYOFFICE/DocumentServer#2896]
Right now if I open a PDF file it will tell me saving annotated pdfs is not possible, and I will have to save or download a copy. There does not seem to be any reason why this feature cannot be turned on. I tried searching for the internet and couldn't find any clues as to why this feature has been turned off. I understand that co-editing feature is not supported for PDF but most people don't need co-editing for PDFs. Regardless of the risk of potential conflicts in a collaborative setting, I believe that most people would really appreciate the ability to save the annotated PDF directly. OnlyOffice in general competes very strongly against other alternatives even just on desktop. There is currently no way to annotate PDF on NextCloud web interface, and OnlyOffice is the only option that theoretically supports it. It would make the whole platform so much more useful. To whoever contributing to the project, thank you in advance for your consideration!

**Comment by Gingetsu** [comment]
Hello, @hermeneuticlens!
This feature will appear in one of the next releases.
Thank you for the report!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
