### ISSUE TITLE
Excuse me, when I use the Office API and the AddCommint() method under oRange, the selected range will be lost; 

### ISSUE THREAD

**Issue by qzzhujixue** [ONLYOFFICE/DocumentServer#2897]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1

### Expected Behavior

Excuse me, when I use the Office API and the AddCommint() method under oRange, the selected range will be lost; For example, in the following text, I want to match the string "is Tom". If it ends with "is Tom", "is Tom" will lose its selection, but "is Tom" is not the end, so there is no problem

### Actual Behavior

 "is Tom" will lose its selection, but "is Tom" is not the end, so there is no problem

### Additional information

![评论-正常-0](https://github.com/user-attachments/assets/32eafe1f-c6db-442a-9bfa-6e72be1b714d)
![评论-正常-1](https://github.com/user-attachments/assets/ec32ce54-080b-4595-8bd9-e8fa2d9a32e0)
![评论-异常-0](https://github.com/user-attachments/assets/b7239ca4-f44a-474c-ab1d-c3c108e4e1a0)
![评论-异常-1](https://github.com/user-attachments/assets/3ace8e68-7d44-4306-b806-8f7e31ff5f93)

**Comment by qzzhujixue** [comment]
const aSearchs = oDocument.Search(content);
let oRange = aSearchs[0]
let oComment = oRange.AddComment(sText, sAuthor, sUserId);

**Comment by lemonowl** [comment]
Hi, @qzzhujixue!
I checked ApiRange.AddComment method in DocumentServer version 8.1.3 and it works correct
```
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var aSearch = oDocument.Search("is Tom");
aSearch[0].AddComment("comment", "John Smith", "uid-1");
```
Could you text a little more details about what you need to do or attach whole script?

**Comment by qzzhujixue** [comment]
> Hi, @qzzhujixue! 你好！ I checked ApiRange.AddComment method in DocumentServer version 8.1.3 and it works correct我检查了 DocumentServer 版本 8.1.3 中的 ApiRange.AddComment 方法，它工作正常
> 
> ```
> var oDocument = Api.GetDocument();
> var oParagraph = oDocument.GetElement(0);
> var aSearch = oDocument.Search("is Tom");
> aSearch[0].AddComment("comment", "John Smith", "uid-1");
> ```
> 
> Could you text a little more details about what you need to do or attach whole script?您能否通过短信提供更多有关您需要做什么的详细信息或附上整个脚本？

`// 获取选中内容
var oDocument = Api.GetDocument();
var oRange = oDocument.GetRangeBySelect();
    
const sAuthor = "机器人";
const sUserId = "robot";
const sText = "这是批注"
let oComment = oRange.AddComment(sText, sAuthor, sUserId);`

**Comment by qzzhujixue** [comment]
`
// 获取选中内容
var oDocument = Api.GetDocument();
var oRange = oDocument.GetRangeBySelect();
    
const sAuthor = "机器人";
const sUserId = "robot";
const sText = "这是批注"
let oComment = oRange.AddComment(sText, sAuthor, sUserId);
`

**Comment by qzzhujixue** [comment]
> Hi, @qzzhujixue! 你好！ I checked ApiRange.AddComment method in DocumentServer version 8.1.3 and it works correct我检查了 DocumentServer 版本 8.1.3 中的 ApiRange.AddComment 方法，它工作正常
> 
> ```
> var oDocument = Api.GetDocument();
> var oParagraph = oDocument.GetElement(0);
> var aSearch = oDocument.Search("is Tom");
> aSearch[0].AddComment("comment", "John Smith", "uid-1");
> ```
> 
> Could you text a little more details about what you need to do or attach whole script?您能否通过短信提供更多有关您需要做什么的详细信息或附上整个脚本？

// 获取选中内容
var oDocument = Api.GetDocument();
var oRange = oDocument.GetRangeBySelect();
    
const sAuthor = "机器人";
const sUserId = "robot";
const sText = "这是批注"
let oComment = oRange.AddComment(sText, sAuthor, sUserId);

> Hi, @qzzhujixue! I checked ApiRange.AddComment method in DocumentServer version 8.1.3 and it works correct
> 
> ```
> var oDocument = Api.GetDocument();
> var oParagraph = oDocument.GetElement(0);
> var aSearch = oDocument.Search("is Tom");
> aSearch[0].AddComment("comment", "John Smith", "uid-1");
> ```
> 
> Could you text a little more details about what you need to do or attach whole script?

// 获取选中内容
var oDocument = Api.GetDocument();
var oRange = oDocument.GetRangeBySelect();
    
const sAuthor = "机器人";
const sUserId = "robot";
const sText = "这是批注"
let oComment = oRange.AddComment(sText, sAuthor, sUserId);

**Comment by qzzhujixue** [comment]
> Hi, @qzzhujixue! I checked ApiRange.AddComment method in DocumentServer version 8.1.3 and it works correct
> 
> ```
> var oDocument = Api.GetDocument();
> var oParagraph = oDocument.GetElement(0);
> var aSearch = oDocument.Search("is Tom");
> aSearch[0].AddComment("comment", "John Smith", "uid-1");
> ```
> 
> Could you text a little more details about what you need to do or attach whole script?

     var oRange = oDocument.GetRangeBySelect();

    
    const content = "is tom"
     const aSearchs = oDocument.Search(content);

        for (let j = aSearchs.length - 1; j >= 0; j--) {
          const sAuthor = "机器人";
          const sUserId = "robot";
          const sText = "这是批注"
          let oComment = oRange.AddComment(sText, sAuthor, sUserId);
      }

**Comment by qzzhujixue** [comment]
There may be a problem when the content I selected ends with 'is Tom'; Because my requirement is to annotate the content within the selected range, not the entire text

**Comment by qzzhujixue** [comment]
![image](https://github.com/user-attachments/assets/6d1e74ca-698a-454f-875c-66894f20e2f4)

**Comment by lemonowl** [comment]
Hi, @qzzhujixue!
I tried to repeat it on version 8.1.3 
I used GetRange + Select and after that added comment to Search result
```js
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
oParagraph.AddText('My name is Tom Riddle');
var oRange1 = oParagraph.GetRange(0, 14);
oRange1.Select();

var aSearch = oDocument.Search("is tom");
aSearch[0].AddComment("comment", "John Smith", "uid-1");
```
And the range is highlighted correctly
![image](https://github.com/user-attachments/assets/15ea5e74-8373-4cfb-832d-447f79829c71)

Could you record a video demonstrating the issue?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
