### ISSUE TITLE
How to use the Office API to search for content within a selected range?

### ISSUE THREAD

**Issue by qzzhujixue** [ONLYOFFICE/DocumentServer#2898]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

How to use the Office API to search for content within a selected range?

**Comment by lemonowl** [comment]
Hi, @qzzhujixue
All methods for interacting with ApiRange are described in the [documentation](https://api.onlyoffice.com/officeapi/textdocumentapi/apirange)

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
