### ISSUE TITLE
How to use the Office API in the oRange corresponding to oComment?

### ISSUE THREAD

**Issue by qzzhujixue** [ONLYOFFICE/DocumentServer#2899]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

How to use the Office API in the oRange corresponding to oComment?

**Comment by lemonowl** [comment]
Hello, @qzzhujixue
Unfortunately, we currently do not have any methods that link oRange and oComment, except [ApiRange.AddComment](https://api.onlyoffice.com/officeapi/textdocumentapi/apirange/addcomment)
I'm not sure I fully understand your question, could you describe the issue in more details?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
