### ISSUE TITLE
What is the problem with Word not loading？

### ISSUE THREAD

**Issue by weijunnan1992** [ONLYOFFICE/DocumentServer#2903]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

![image](https://github.com/user-attachments/assets/596709b6-7ccc-454c-b3e1-533b3bbc1e0b)

What is the problem with Word not loading? I received an only office request from the frontend through a proxy, but I noticed that there are no websocket requests on the network

**Comment by askonev** [comment]
@weijunnan1992 Specify the version of the server on which the sample is being played

Is the document accessible by the url that you open in the editor?

`curl -o https://current_document.docx` Does it work?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
