### ISSUE TITLE
After converting the picture to Base64 and creating an image (CreateImage), and inserting it into a table, an abnormal permission is caused.

### ISSUE THREAD

**Issue by viest** [ONLYOFFICE/DocumentServer#2908]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.3-4

### Expected Behavior

Insert a table and ensure that the pictures in the table are displayed normally.

### Actual Behavior

Before inserting a table, the document can be edited normally on the webpage. However, after inserting a table, the following situation occurs:

Webpage prompts:
"No permission. Please contact the administrator."

DocumentServer Log：
nodeJS - error commandImgurls: access deny
nodeJS - conn.user.view||isCloseCoAuthoring access deny: type = getLock
nodeJS - conn.user.view||isCloseCoAuthoring access deny: type = getLock

### Reproduction Steps

```
let oRunDrawing = Api.CreateRun();
oRunDrawing.AddDrawing(Api.CreateImage("data:image/jpeg;base64,......", 60 * 36000, 35 * 36000));

let oInlineLvlSdt = Api.CreateInlineLvlSdt();
oInlineLvlSdt.AddElement(oRunDrawing);

oCell.GetContent().GetElement(0).AddElement(oInlineLvlSdt);
```

**Comment by l8556** [comment]
Hello @viest !

It was not possible to reproduce this issue. 

Try to update the version of the document server to a current version.

If the problem reoccurs, please describe the steps to reproduce in more detail and send the complete document builder script.

Tested on DS version 8.2.0.143

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
