### ISSUE TITLE
Spreadsheets: Pasting a lot of fomulas cause some formulas to be inserted as text

### ISSUE THREAD

**Issue by n-goncalves** [ONLYOFFICE/DocumentServer#2919]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.3.4

### Expected Behavior

All formulas should be calculated correctly. 

No idea how it worked on previous versions of DocumentServer.  

### Actual Behavior

Every 5 or so cells, the formula is pasted as text and results seems to be consistent every run.

Going into one of the offending cell and pressing enter causes Onlyoffice to understand that it's dealing with a formula and doing the calculation. Using the "Calculate workbook/current sheet" in the Formula menu didn't update those cells. 

![image](https://github.com/user-attachments/assets/9875261f-9a0b-488e-8f91-78f23e351437)

### Reproduction Steps

I was able to reproduce it quite consistently using this [file](https://github.com/user-attachments/files/17341756/missing_pasted_formulas.xlsx) and trying to paste those [formulas](https://github.com/user-attachments/files/17341767/onlyoffice_paste_formulas.txt) in a new sheet with the A column filled with dates

### Additional information

I can reproduce also reproduce it in the Desktop Editor version 8.1.1.27 (flatpak), but I don't know if that's a official release of yours because it's not in the operating system dropdown.

**Comment by VladimirProkofiev52** [comment]
Hello! @n-goncalves 
I tried to reproduce your issue, but I wasn't able to. 
We recently released version 8.2.0 of our editors. 
Please update your editors to the latest version and try to reproduce the issue. 
If it persists, please let me know.

**Comment by n-goncalves** [comment]
Hello.

I can also confirm it seems to be fixed in 8.2.0. I'll close the ticket.
