### ISSUE TITLE
Filters are only used partially

### ISSUE THREAD

**Issue by TheMrApostel** [ONLYOFFICE/DocumentServer#292]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
1. Select a filter
2. The filter is not applied to your spreedsheet.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[2018_02_15_PM2-05-D03_ToDo-Liste_02032018.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/1967307/2018_02_15_PM2-05-D03_ToDo-Liste_02032018.xlsx)

1. Upload the attached excel file to your onlyoffice documentserver and open it
2. Try to select only values with "Status" is "Erledigt"
3. The filter is not applied / No filter is used
**What is the expected behavior?**
Only values containing the selected "Status" should be displayed
**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
5.1.3 CE
**Operating System:**
CentOS 7
**Browser version:**
Firefox 60.0

This behavior does not occur with a local installation of Microsoft Excel.
[Short_example.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/1967336/Short_example.pdf)

**Comment by Rita-Bubnova** [comment]
Hello, @TheMrApostel.
Thank you. I can confirm - this is a bug, issue 37618 in our internal issue tracker.

**Comment by TheMrApostel** [comment]
Hello @Rita-Bubnova,

many thanks for your answer. 👍 
If you need me to test some changes - just reply :-)

**Comment by Rita-Bubnova** [comment]
Your issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/992347fa9cfb5162f61a3456548488fe5597d81a and will be released as 5.2.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
