### ISSUE TITLE
How to set up or turn email notifications on/off in 8.2.0?

### ISSUE THREAD

**Issue by immanuelfodor** [ONLYOFFICE/DocumentServer#2923]
The release notes for 8.2.0 says: 

```
### Back-end

Ability to send email notifications about warnings related to license and quota
```

How can this be managed?

I looked at the [env parameters](https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx) but there is no one related.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
