### ISSUE TITLE
Can't apply justified to chinese in 5.1.3.

### ISSUE THREAD

**Issue by KAZMAZHANG** [ONLYOFFICE/DocumentServer#293]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Can't apply justified to chinese in 5.1.3. It's always left-aligned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![0](https://user-images.githubusercontent.com/18349061/39624834-62545722-4fcd-11e8-9656-7909c9da8e60.jpg)

**What is the expected behavior?**
In 5.1.2 it's working properly.
![1](https://user-images.githubusercontent.com/18349061/39624937-d611ab92-4fcd-11e8-8b1c-334d1474e699.jpg)

**Did this work in previous versions of DocumentServer?**
yes

**DocumentServer version:**
5.1.3

**Operating System:**
Ubuntu 16

**Browser version:**
Firefox 60.0/Chrome 65

**Comment by KAZMAZHANG** [comment]
This is the document:
[边城.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1974153/default.docx)

**Comment by Rita-Bubnova** [comment]
Hello, @KAZMAZHANG.
Thank you. I can confirm - this is a bug, issue 37659 in our internal issue tracker.

**Comment by ShockwaveNN** [comment]
Fixed in 5.1.4
