### ISSUE TITLE
spreadsheet editor shows 1048577 rows instead of 1048576 allowed by Excel

### ISSUE THREAD

**Issue by nkolotov** [ONLYOFFICE/DocumentServer#2938]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.2.0

### Expected Behavior

Spreadsheet editor should show 1048576 rows [per Excel spec](https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3).

### Actual Behavior

Spreadsheet editor shows 1048577 rows. The last row is not interactive (i.e. can not click on it).

### Reproduction Steps

- Create new spreadsheet in spreadsheet editor.
- Type `A1048576` in cell address box.
- Press Enter.
- Scroll a bit down.
- Now row 1048577 becomes visible.
![row1048576](https://github.com/user-attachments/assets/e53909cf-9403-4512-b8fa-53b9365b3377)

**Comment by LuckySpecialist** [comment]
This problem was fixed by [this](https://github.com/ONLYOFFICE/sdkjs/commit/3904842d697633bf96b6cb16a59bccec3608df89) commit and will be included in the next hotfix version.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
