### ISSUE TITLE
SmartArt in presentations: can't change the number of columns

### ISSUE THREAD

**Issue by miknatr** [ONLYOFFICE/DocumentServer#2940]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher, Linux (DEB package)

### Version information

8.1.1.27

### Expected Behavior

I expect that a change of the number of columns in a SmartArt settings should change the SmartArt.
For example, if I need a SmartArt list for 5 elements instead of the default 3, I can change the number of columns and after the SmartArt list should be redrawn with 5 elements.

### Actual Behavior

Changes to the number of columns are not saved and are not applied to SmartArt objects.

### Reproduction Steps

1. Insert a SmartArt object into slide, for example any object in "List" catalog.
2. Right click on the SmartArt object and select "Shape Advanced Settings".
3. Select "Columns" in the popup window.
4. Change the number of columns, for example, enter 5 columns.
5. Click "OK" in the popup window to save changes.
6. **The SmartArt object is not changed, there are still 3 default elements instead of 5 inputted above.**
7. If I go to "Shape Advanced Settings" -> "Columns" again the number of columns is empty, my changes were not saved.

### Additional information

I tested on Linux Mint 22 and on macOS Sonoma 14.6.1

**Comment by miknatr** [comment]
Hi @ElenaMaaya !

Thank you for the response! I just wanted to clarify — when you mention resolving this issue, does it mean that the option to change the number of columns will be removed, making it unchangeable? Or will there be an actual fix that allows users to set multiple columns as needed?

Thank you for your help!

**Comment by ElenaMaaya** [comment]
Hi @miknatr! 
Thanks for the feedback. The Columns option should not be applied to a SmartArt object.
This issue will be fixed in the next release ([commit](https://github.com/ONLYOFFICE/web-apps/commit/86b6684bd3afee5170f3f297f4f8659144fae4f5)). Please keep checking for updates.

**Comment by miknatr** [comment]
Hi @ElenaMaaya !
Thank you for the response and for planing the fix!
 
So, do understand right, there is no way to change the number of elements in a SmartArt object?

**Comment by ElenaMaaya** [comment]
Hi @miknatr! Sorry, I'm not sure I understand your question exactly. Your question in the issue was about the Columns option. The screenshot shows an example of using this option in shape. This option is not used in SmartArt objects. 
![test_columns](https://github.com/user-attachments/assets/8a5036f7-63f7-4b56-97e3-861afd87b82b)

Do you want to add elements to SmartArt? If so, you need to create a new issue.

**Comment by ElenaMaaya** [comment]
Hi @miknatr! Thank you, this problem description is very clear. Please, you should make a new issue.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
