### ISSUE TITLE
Finding in OnlyOffice Spreadsheets adds new lines temporarily into the sheet

### ISSUE THREAD

**Issue by eurovisionfanatic** [ONLYOFFICE/DocumentServer#2948]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.2.0.143

### Expected Behavior

When you Ctrl + F something in a spreadsheet and cycle through the matches it should jump to that spot in the spreadsheet making no other changes.

### Actual Behavior

When you Ctrl + F something in a spreadsheet it either adds new columns or new rows every time you press the next arrow or press the enter button.  Scrolling away and then back to the spot resolves the issue temporarily.

### Reproduction Steps

Open a spreadsheet
Search for a number in the sheet
Press the next arrow

### Additional information

It works as expected on 8.1.3.4.  This was done using the integration with Nextcloud.

**Comment by Gingetsu** [comment]
Hello, @eurovisionfanatic!
Could you tell me what operating system you have and and attach a video describing the problem, please?

**Comment by profilecomputing** [comment]
Hi @Gingetsu,

Sorry for not getting back to you earlier.

I can confirm that this happens on both Windows 11 and Mac OS and after doing some more testing appears to only be the case when freeze panes are being used as shown in the last section of the video after I show it working correctly.

https://github.com/user-attachments/assets/41d2c4b6-65ca-48be-937f-8798466047e9


Cheers

**Comment by eurovisionfanatic** [comment]
Hi @Gingetsu,

Sorry for not getting back to you earlier.

I can confirm that this happens on both Windows 11 and Mac OS and after doing some more testing appears to only be the case when freeze panes are being used as shown in the last section of the video after I show it working correctly.


https://github.com/user-attachments/assets/e9af1dc4-5a79-4892-b015-4f11a7967d52

**Comment by eurovisionfanatic** [comment]
Hi @Gingetsu, 

I had the issue on Nextcloud 29.0.8, but I have tried again to recreate the issue on 29.0.9 and it is know working :-).

Yay.

Thanks for the help

**Comment by Rita-Bubnova** [comment]
@eurovisionfanatic, I close this issue. Feel free to comment or reopen it if you got further questions.
