### ISSUE TITLE
Since 8.2 VLOOKUP function produces an array instead of a single value as it used to in 8.1 with range as a first argument.

### ISSUE THREAD

**Issue by nkolotov** [ONLYOFFICE/DocumentServer#2956]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

8.2.0

### Expected Behavior

In v8.1 spreadsheet editor `VLOOKUP` function in a single cell produced output to this single cell even when first argument was a range of cells.
This behavior matched to Excel and LibreOffice.

### Actual Behavior

In v8.2 behavior suddenly changed. Now `VLOOKUP` function in a single cell produces an array as an output when first argument is a range of cells. For example `=VLOOKUP(A:A;List1;2;0)` becomes `{=VLOOKUP(A:A;List1;2;0)}` and editor turbofills the cells to show produced array. This breaks existing spreadsheets.

### Reproduction Steps

- select cell `D1`
- type formula `=VLOOKUP(A:A;List1;2;0)`
- press Enter
- with v8.2 editor starts filling `D` column (with v8.1 it would only fill `D1` cell)
- prompt appears for 10000 rows filled asking whether to stop or to continue filling remaining rows

**Comment by VladimirProkofiev52** [comment]
Hello! @nkolotov 
Our specialists have implemented a fix so that arrays now automatically expand only if the argument is an array. This fix will be available in version 8.2.1.

Unfortunately, full support for dynamic arrays is still under development.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
