### ISSUE TITLE
nodejs and libcurl3 dependency problem on ubuntu 18.04

### ISSUE THREAD

**Issue by ralikhan** [ONLYOFFICE/DocumentServer#296]
Hello, good afternoon. I was trying to install Onlyoffice Document Server in Ubuntu server 18.04. Time to install Documentserver requires   **onlyoffice-documentserver : Depends: nodejs (< 7.0.0) but 8.10.0~dfsg-2 is to be installed**. But it does not let me install node js 6 on the ubuntu server 18.04. 
Thank you very much

![1](https://user-images.githubusercontent.com/39272051/40006591-132d5fec-579b-11e8-8de4-31f48ff2e460.png)

**Comment by ShockwaveNN** [comment]
@ralikhan Thanks, it's a known problem and will be fixed in `5.1.4`

**Comment by ralikhan** [comment]
![screenshot 2](https://user-images.githubusercontent.com/39272051/40007275-9cd4d346-579c-11e8-9504-3f747b5e90ec.png)
![2](https://user-images.githubusercontent.com/39272051/40007276-9cf4e1c2-579c-11e8-8778-7620b39781b8.png)

**Comment by ralikhan** [comment]
by default I installed node js 8 and it does not let me install another version.  
@ShockwaveNN Thanks

**Comment by andyl333** [comment]
@ralikhan and @ShockwaveNN : How did you solve the problem? I have exactly the same problem!

**Comment by ShockwaveNN** [comment]
@andyl333 yeah, we removed those dependenceies and it will be fixed in 5.1.4

**Comment by andyl333** [comment]
@ShockwaveNN do you know already, when 5.1.4 will be released?

**Comment by ShockwaveNN** [comment]
@andyl333 in next several weeks

**Comment by andyl333** [comment]
@ShockwaveNN thanks a lot!

**Comment by ralikhan** [comment]
Thank you very much

**Comment by ShockwaveNN** [comment]
5.1.4 released, closing issue

**Comment by ralikhan** [comment]
is solved. Thank you so much.
![image](https://user-images.githubusercontent.com/39272051/40712091-13f799d8-63fd-11e8-9414-f9b172698642.png)

**Comment by ralikhan** [comment]
![image](https://user-images.githubusercontent.com/39272051/40712180-5a31f3bc-63fd-11e8-823f-3e29d2532a99.png)
