### ISSUE TITLE
librabbitmq-tools-0.5.2-1.el7.x86_64

### ISSUE THREAD

**Issue by raphson93** [ONLYOFFICE/DocumentServer#297]
hi, is that possible to update the librabbitmq-tools-0.5.2-1.el7.x86_64 to latest version ?

**Comment by ShockwaveNN** [comment]
@raphson93 hi, I looked at `rpm/requires.spec` and there is no specific version of `librabbitmq-tools` required. Maybe some of dependencies require older version

**Comment by ShockwaveNN** [comment]
@raphson93 Just checked
packaged `librabbitmq-tools` is not included in default centos repo
It's included in latest `epel` repo
And `librabbitmq-tools` is 0.5.2-1.el7 in `epel-release` v 7-11, you should contact epel team if you have some question about version of `librabbitmq-tools`

**Comment by raphson93** [comment]
@ShockwaveNN hi, i was planning to uninstall the package and reinstall it. But the remove command show the output below: 
![image](https://user-images.githubusercontent.com/19220265/40047872-42f1ff44-5863-11e8-91f9-3247a575ba8f.png)

Will it cause any issue to the document server if librabbitmq-tools was removed ?

**Comment by ShockwaveNN** [comment]
@raphson93 I dont think so, it should be installed as dependency in install stage

**Comment by raphson93** [comment]
@ShockwaveNN alright thanks

**Comment by raphson93** [comment]
@ShockwaveNN ye i was plan to remove the package but from the image it did remove the document server together.. this is not the output that I expected.

**Comment by raphson93** [comment]
@ShockwaveNN i think for the next release (5.1.4) the development team should update the librabbitmq-tools to 0.8.02.

**Comment by ShockwaveNN** [comment]
@raphson93 As I said - `librabbitmq-tools` installed from epel repo and we have no plans to host our own newer version of this. As soon of epel update `librabbitmq-tools` - we will use it
