### ISSUE TITLE
Cannot save for doc type files

### ISSUE THREAD

**Issue by baishaochuan** [ONLYOFFICE/DocumentServer#2987]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.0

### Expected Behavior

I was trying to edit and save a doc file, but it gave me an error. However, there was no issue with docx files. 

<img width="1312" alt="企业微信截图_20241113141824" src="https://github.com/user-attachments/assets/0a022eb0-0963-40c2-9a74-a7055658e4b7">

### Actual Behavior

doc

**Comment by baishaochuan** [comment]
Hello, Your meaning is, if I set assemblyFormatAsOrigin to false, I can save the ".doc" file, right?

**Comment by igwyd** [comment]
No, by default ```assemblyFormatAsOrigin=true``` server will try convert to original format ```doc```. If you set false then the server won't even try.
Explain in more detail what result you expect?
If you just need to change the extension, you need to set renaming in the integration ```docx``` to ```doc```.

**Comment by baishaochuan** [comment]
I didn't specifically try to convert the file type. I just wanted to edit a .doc file and save it to my own document server. On my document server, I couldn't get the URL of the new file. Then I checked the OnlyOffice server, and it reported an exception indicating that the file conversion failed.

**Comment by igwyd** [comment]
To edit an old format file like a ```doc```, onlyoffice converts it to a new format ```docx``` when opening it, and this is not difficult. But to return all the changes and display them qualitatively in a file of the old format is not always possible, so we write this WARN message ```nodeJS - rollback to save changes to ooxml. See assemblyFormatAsOrigin param. formatTo=doc``` that the reverse conversion failed, i.e. we had to leave the file in the docx format so that your file does not lose changes and does not break.

**Comment by baishaochuan** [comment]
ok, thanks

**Comment by kunkunj** [comment]
Can you tell me how it was ultimately resolved
