### ISSUE TITLE
Open the word document in iPhone and enter Chinese messy code

### ISSUE THREAD

**Issue by hyman102** [ONLYOFFICE/DocumentServer#299]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by hyman102** [comment]
The DocumentServer version is the latest

**Comment by hyman102** [comment]
The DocumentServer version is the latest

**Comment by ShockwaveNN** [comment]
@hyman102 could you attach screenshot?

**Comment by hyman102** [comment]
![image](https://user-images.githubusercontent.com/39356945/40162861-c70a44c8-59e7-11e8-95d5-6e43cf0a6287.png)

**Comment by hyman102** [comment]
All of the iPhone model tests are the same

**Comment by hyman102** [comment]
But we tested normal in MAC

**Comment by ShockwaveNN** [comment]
Could you attach this document?

**Comment by hyman102** [comment]
[piwik_install.docx](https://github.com/ONLYOFFICE/DocumentServer/files/2012167/piwik_install.docx)

**Comment by hyman102** [comment]
We are using the iPhone Browser Test

**Comment by ShockwaveNN** [comment]
@hyman102 those symbols `➍➏➍➒➒➍➒➍➏➍➒➍➒➒` are stored in document, could you record video how you input them on mobile

**Comment by hyman102** [comment]
How do I send the video to you

**Comment by hyman102** [comment]
The video format is mp4

**Comment by ShockwaveNN** [comment]
@hyman102 you can zip it and attach here

**Comment by hyman102** [comment]
[video.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2012481/video.zip)

**Comment by ShockwaveNN** [comment]
@hyman102 Thanks, this is strange, we looking into it

**Comment by ShockwaveNN** [comment]
@hyman102 yeah, I can confirm - this is a bug, issue 37766 in our private bug tracker

**Comment by ShockwaveNN** [comment]
@hyman102 I think it will be fixed in next major release, 5.2

**Comment by hyman102** [comment]
Is the current version 5.1.1?

**Comment by ShockwaveNN** [comment]
@hyman102 5.1.3

**Comment by hyman102** [comment]
OK,thanks.

**Comment by hqzhen** [comment]
My problem is not Chinese scrambling, but that ihone6 can't input Chinese, only English. My version is 5.2.6 @ShockwaveNN

**Comment by ShockwaveNN** [comment]
@hqzhen could you record a video

**Comment by hqzhen** [comment]
I have solved it. Now I can input Chinese, but like #299 ➍➏➍➒➒➍➒➍➏➍➒➍➒➒, has  #299 been solved?

**Comment by hqzhen** [comment]
I have solved it. Now I can input Chinese, but like #299 ➍➏➍➒➒➍➒➍➏➍➒➍➒➒, has #299 been solved? @ShockwaveNN

**Comment by hqzhen** [comment]
![1b0afbef61d60ab014f58addb93876a8](https://user-images.githubusercontent.com/45785181/52849296-a447fc00-314b-11e9-9d40-e30c3c317499.jpg)

**Comment by ShockwaveNN** [comment]
No, issue is actual, I post update if ther e is any news

**Comment by hqzhen** [comment]
OK,thanks. @ShockwaveNN

**Comment by kevindenight** [comment]
@ShockwaveNN I think the problem is keyboard event prevent 'input' event to trigger in safari mobile. I  changed code in sdkjs/common/text_input.js and deployed to a document server then this problem is fixed.
My changes:
`
			// events:
			var oThis                   = this;
			this.HtmlArea["onkeydown"]  = function(e)
			{
				if (AscCommon.AscBrowser.isSafariMacOs)
				{
					var cmdButton = (e.ctrlKey || e.metaKey) ? true : false;
					var buttonCode = ((e.keyCode == 67) || (e.keyCode == 88) || (e.keyCode == 86));
					if (cmdButton && buttonCode)
						oThis.IsDisableKeyPress = true;
					else
						oThis.IsDisableKeyPress = false;
				}
				if (AscCommon.AscBrowser.isSafari
					&& AscCommon.AscBrowser.isMobile
					&& e.key !== "Backspace") {
					return;
				}
				return oThis.onKeyDown(e);
			};
			this.HtmlArea["onkeypress"] = function(e)
			{
				if (AscCommon.AscBrowser.isSafari
					&& AscCommon.AscBrowser.isMobile
					&& e.key !== "Backspace") {
					return;
				}
				if (oThis.IsDisableKeyPress == true)
				{
					// macOS Sierra send keypress before copy event
					oThis.IsDisableKeyPress = false;
					var cmdButton = (e.ctrlKey || e.metaKey) ? true : false;
					if (cmdButton)
						return;
				}
				return oThis.onKeyPress(e);
			};
			this.HtmlArea["onkeyup"]    = function(e)
			{
				if (AscCommon.AscBrowser.isSafari
					&& AscCommon.AscBrowser.isMobile
					&& e.key !== "Backspace") {
					return;
				}
				oThis.IsDisableKeyPress = false;
				return oThis.onKeyUp(e);
			};
`

**Comment by hqzhen** [comment]
I haven't found sdkjs/common/text_input.js. Your version is, what can I do to solve this problem? @kevindenight

**Comment by kevindenight** [comment]
@hqzhen V5.2.8

**Comment by hqzhen** [comment]
I haven't found sdkjs/common/text_input.js ，Can you teach me?
![1552629976(1)](https://user-images.githubusercontent.com/45785181/54411836-8f02c500-472b-11e9-8b22-f2e2bcef40e9.jpg)

**Comment by hqzhen** [comment]
@kevindenight I haven't found sdkjs/common/text_input.js ，Can you teach me?

**Comment by kevindenight** [comment]
@hqzhen It's in source code, not in deployed server. You may edit source code, rebuild and run a new docker image.

**Comment by hqzhen** [comment]
I won't rebuild and run a new docker image. Can you send me a modified image?
@kevindenight

**Comment by ShockwaveNN** [comment]
This issue should be fixed at https://github.com/ONLYOFFICE/sdkjs/commit/73129024119e0a82d4e27e9cce7784e792963b7a and will be released as 5.3.0

**Comment by hqzhen** [comment]
Will the ONLYOFFICE/DocumentServer #299  be resolved synchronously in ONLYOFFICE/Docker-DocumentServer? If it will be synchronized, which version is it?@ShockwaveNN

**Comment by ShockwaveNN** [comment]
@hqzhen Yes, it will be 5.3.0

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
