### ISSUE TITLE
Prohibit installation of several version of DocumentServer on same host

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#300]
Currently there is possible to install all there version of documentserver package on same host (`onlyoffice-documentserver`, `onlyoffice-documentserver-ie`, `onlyoffice-documentserver-de`), but result will be messed up.

Need to prohibit installation on dpkg-level 

**DocumentServer version:** 5.1.3

**Operating System:** Ubuntu 18.04

**Comment by igwyd** [comment]
Hello @ShockwaveNN) At the moment there is no possibility to install different distribution on one system. The installation is interrupted and doesn't break the current installation.
```
dpkg: error processing archive /var/cache/apt/archives/onlyoffice-documentserver_8.2.0-143_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/documentserver-generate-allfonts.sh', which is also in package onlyoffice-documentserver-ee 8.2.0-143
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/onlyoffice-documentserver_8.2.0-143_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
We will close this.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
