### ISSUE TITLE
Can I not need DocumentServer?

### ISSUE THREAD

**Issue by zengtiansheng** [ONLYOFFICE/DocumentServer#3016]
I just want to integrate the  [web app](https://github.com/ONLYOFFICE/web-apps) front-end capabilities into my application. I don't need DocumentServer, and I don't need capabilities such as saving and collaboration. I want to perform front-end interface display capabilities. Can I only use the   [web app](https://github.com/ONLYOFFICE/web-apps) without DocumentServer? I built and started index.html for the   [web app](https://github.com/ONLYOFFICE/web-apps) , and the browser console reported no errors but I can't use it.

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/d3120900-3d93-4099-94ea-c380e4a5d93a">

**Comment by stepjacky** [comment]
you want  to using  document server without document server  ,are you confusing ？

**Comment by zengtiansheng** [comment]
@stepjacky Sorry, I may not express it clearly. I just want to use the web app, not DocumentServer. I just want to use the web app's capabilities, and do file storage, file permissions, etc. myself. But I found that the web app and DocumentServer are bound together, and I can't separate them and use them separately.

**Comment by stepjacky** [comment]
its done ,only  altnative  its config option  of url and doc server can be easily integered into you so called fronted  web application,not need anything more

**Comment by zengtiansheng** [comment]
@stepjacky Sorry, I don't quite understand what you mean. Do you mean I can directly start [web app](https://github.com/ONLYOFFICE/web-apps) to edit the document without DocumentServer? I have already built [web app](https://github.com/ONLYOFFICE/web-apps), and I started the index.html of [web app](https://github.com/ONLYOFFICE/web-apps) and got a blank page. How should I initialize the configuration?

![image](https://github.com/user-attachments/assets/616c34e7-88e2-43b1-833a-5f2cd81581be)

**Comment by ibnpetr** [comment]
>But I found that the web app and DocumentServer are bound together, and I can't separate them and use them separately.

That’s exactly how it should work. web-apps is the frontend for OO Document Server

>Do you mean I can directly start [web app](https://github.com/ONLYOFFICE/web-apps) to edit the document without DocumentServer?

No, web-apps cannot be used without ONLYOFFICE Document Server or ONLYOFFICE Desktop Editors.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
