### ISSUE TITLE
Change number of connections is legal?

### ISSUE THREAD

**Issue by Senkai350** [ONLYOFFICE/DocumentServer#3017]
The official website says that this software is **recommended** for 20 simultaneous connections (https://www.onlyoffice.com/compare-editions.aspx ), but in fact, no one forbids it* to increase the number of simultaneous connections in the source code by modifying it? 
(for example, here https://github.com/ONLYOFFICE/server/blob/master/Common/sources/constants.js )
Will this change be legal and will I be able to continue using such software still without violating the AGPL v3 license?

*This software is distributed under the GNU Affero General Public License v3.0, which says "Developers that use our General Public Licenses protect your rights
with two steps: (1) assert copyright on the software, and (2) offer
you this License which gives you legal permission to copy, distribute
and/or **modify** the software."

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
