### ISSUE TITLE
Formulas interpreted as plain text

### ISSUE THREAD

**Issue by nektdev** [ONLYOFFICE/DocumentServer#3019]
Since we updated to Nextcloud Hub 9 (30.0.2) all new and edited formulas in previously stable and working spreedsheets applied in the Spreadsheet Editor are interpreted as plain text (raw formula content displayed rather than the value). 

onlyoffice-documentserver version: 8.2.0-143
ONLYOFFICE connector app version: 9.4.0
Nextcloud version: 30.0.2

**Comment by ElenaMaaya** [comment]
Hello, @nektdev ! Thank you for your attention to our product!
There are still not enough details to reproduce your problem. Could you record a video of the problem?

**Comment by nektdev** [comment]
Hi @ElenaMaaya thank you for your reply, it might be that the spreadsheet got corrupt as it was passed between Mac, Windows and Nextcloud (where we use ONLYOFFICE). We are unable to find the same behaviour in other spreadsheets so I suggest closing for now
