### ISSUE TITLE
"Unknown error" while trying to "download as"

### ISSUE THREAD

**Issue by Pisoko** [ONLYOFFICE/DocumentServer#302]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
"Unknown error" while trying to "download as" PDF or ODT or ... or trying to print the document
Otherwise there are no problems and I'm very happy with onlyoffice!

**Did this work in previous versions of DocumentServer?**
Yes - Document Server 5.1.3 CE + Nextcloud 13.0.2 + OnlyOfficeApp 1.3.0

**Operating System:**
Windows 10

**Browser version:**
Firefox - 59.0.3

**Comment by HellRoad** [comment]
I tried to repeat your testcase but I didn't get it on the release version 5.1.3
This problem is repeated somewhere else or is it repeated only on one file?
If the problem is in the file, then send it
Thanks for your Feedback

**Comment by ShockwaveNN** [comment]
This ticket is being closed due to no response
