### ISSUE TITLE
Clipboard pasting in the search field sometimes replaces selected cell contents

### ISSUE THREAD

**Issue by RTechSn** [ONLYOFFICE/DocumentServer#3027]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.1.3.3

### Expected Behavior

Text should be pasted into UI element that is currently in focus (the last you have interacted with).

### Actual Behavior

Text sometimes gets pasted into selected\highlighted cell instead.

### Reproduction Steps

1. Open a spreadsheet with many filled rows
2. Open the search field and paste something that exists in the document, then submit
3. A cell gets auto-selected
4. Select the text in the search field, remove it and paste something else that exists in the document with Ctrl+V
5. Sometimes the text gets pasted into selected cell instead of the search field despite you interacting with the search field last.
6. If not, go to step 4.

### Additional information

The OnlyOffice Editor is opened in a web-browser through Nextcloud integration.

**Comment by Dmitry-Kov** [comment]
Hi @RTechSn,

I have looked into your issue but was unable to reproduce it. 
It would be great if you attached the screencast.

**Comment by RTechSn** [comment]
![onlyoffice_ctrl+v](https://github.com/user-attachments/assets/66f78aca-32ec-41e9-b4db-08cfef1edc9b)

**Comment by RTechSn** [comment]
![onlyoffice_ctrl+v_2](https://github.com/user-attachments/assets/b4420d99-b243-4d3e-bca7-dadc8e149b91)

**Comment by RTechSn** [comment]
I this this is related to the appearance of "(Ctrl)" tooltip.

**Comment by Dmitry-Kov** [comment]
Thank you for providing detailed information. This issue does not occur in the latest versions. I suggest you update to the current version and also try clearing your cache.

**Comment by RTechSn** [comment]
Thank you, i'll find some time for an update.
