### ISSUE TITLE
WORKDAY function broken with day-offset greater then 1

### ISSUE THREAD

**Issue by jkolo** [ONLYOFFICE/DocumentServer#303]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you use the WORKDAY function (Ex. WORKDAY(B3,5,Holidays) with day-offset value greater then 1
function return holiday day and skip day after holiday day.
![image](https://user-images.githubusercontent.com/1894746/40245387-d49247e2-5ac5-11e8-9a26-80ba1576ede4.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[WORKDAY_BUG.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/2017621/WORKDAY_BUG.xlsx)

**What is the expected behavior?**
WORKDAY function should not return holiday day and should return workday after holiday

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.1.3

**Operating System:**
Windows 10 x64 1803

**Browser version:**
Firefox 61.0b4 

**Related issues**
#184 and #194

**Comment by jkolo** [comment]
Sample correct implementation: http://jsfiddle.net/mposr3mp/

**Comment by jkolo** [comment]
Any progress?

**Comment by ShockwaveNN** [comment]
@jkolo hi, currently no, but I remind dev team to have a look, try to include your fix in 5.2.0

**Comment by ShockwaveNN** [comment]
@jkolo your changes are in https://github.com/ONLYOFFICE/sdkjs/commit/b035af02ab9ab6ed0ec05ed331782ca0ff7f2113
This will be released as 5.2, thank you

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
