### ISSUE TITLE
Saving PDFs to storage is not working correctly,  not being saved on close

### ISSUE THREAD

**Issue by oliverschulze** [ONLYOFFICE/DocumentServer#3044]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.2.2

### Expected Behavior

PDF is opened in edit mode (integrated in a WebUI of our product). Communication is done with loadUrl and callbackUrl via callback handler. When comments are added within the pdf and the editor is closed, the callbackUrl is called with status 2 (2 - document is ready for saving), so that the changes can be fetched and saved.

### Actual Behavior

PDF is opened in edit mode (integrated in a WebUI of our product). Communication is done with loadUrl and callbackUrl via callback handler. When comments are added within the pdf and the editor is closed, the callbackUrl is only called with status 4 (4 - document is closed with no changes)

### Reproduction Steps

Open PDF with ONLYOFFICE-Editor, add a comment, close the editor.

### Additional information

Works normally with Word, Excel and Powerpoint but not with PDF. When using forceSave-Feature and save manually, then status "6 - document is being edited, but the current document state is saved" is called in the callbackUrl.

**Comment by igwyd** [comment]
Hello @oliverschulze. 
1. What editor mode (fast or strict) do you enabled? Is there a dialog box with unsaved changes when closing the browser tab?
2. Describe in more detail how you close the editor. Do you just close the browser tab or via [destroyeditor](https://api.onlyoffice.com/docs/docs-api/usage-api/methods/#destroyeditor)?

**Comment by Inso2008** [comment]
We ran into that, too. I think it's because the PDF editor doesn't have "Autosave" enabled by default.

We fixed this by setting the editor configuration "editorConfig.customization.autosave = true" see https://api.onlyoffice.com/docs/docs-api/usage-api/config/editor/customization/#autosave

But yes the PDF editor behaves differently in this property from Word, Excel and Powerpoint.

**Comment by oliverschulze** [comment]
> We ran into that, too. I think it's because the PDF editor doesn't have "Autosave" enabled by default.
> 
> We fixed this by setting the editor configuration "editorConfig.customization.autosave = true" see https://api.onlyoffice.com/docs/docs-api/usage-api/config/editor/customization/#autosave
> 
> But yes the PDF editor behaves differently in this property from Word, Excel and Powerpoint.

Great thank you, it works!

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
