### ISSUE TITLE
Porting Sheet RTL support to sdkjs

### ISSUE THREAD

**Issue by nisbet-hubbard** [ONLYOFFICE/DocumentServer#3053]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

We rely on OnlyOffice through CryptPad, so it’d be really nice to see this ported to your sdkjs when #2577 gets closed.

What would be the usual timeline for new features to appear in the sdk?

**Comment by trofim24** [comment]
We implement all new features only in the sdk repos.
You can see our [roadmap](https://github.com/ONLYOFFICE/DocumentServer/blob/master/ROADMAP.md).

**Comment by catbasilio** [comment]
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/2577
