### ISSUE TITLE
onlyoffice 在wujie微前端子应用中无法加载

### ISSUE THREAD

**Issue by qiuxuky** [ONLYOFFICE/DocumentServer#3057]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

所有版本

### Expected Behavior

<img width="822" alt="微信图片_20241218100612" src="https://github.com/user-attachments/assets/4b17bc11-36af-481f-af93-b15dd5cd7f90" />

### Actual Behavior

<img width="693" alt="微信图片_20241218100450" src="https://github.com/user-attachments/assets/bcff9152-86d4-406b-b8ff-37a34f394b40" />

**Comment by Rita-Bubnova** [comment]
Hello, @qiuxuky.
Please, fill in all the fields of the form on English.
