### ISSUE TITLE
xls to xlsx formula error

### ISSUE THREAD

**Issue by liuwangchao** [ONLYOFFICE/DocumentServer#3063]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

After converting the xls file to an xlsx file, I want the formulas in the original xlsx file to be the same as the formulas in the xls file.

### Actual Behavior

The formula `=IF(ISBLANK(E2),H2,E2)` in the original xls file becomes `=IF(ISBLANK(XFD2),XFD2,XFD2)`, i.e., the number of columns in the coordinates in the formula has changed, and they all become `XFD`.

### Reproduction Steps

Trying to convert this xls file I provided to xlsx will see the wrong formulas in columns I and J.

### Additional information

[error file 241220.xls](https://github.com/user-attachments/files/18209105/error.file.241220.xls)

**Comment by Dmitry-Kov** [comment]
Hello @liuwangchao,

Thank you for providing detailed information. This issue does not occur in the latest versions. I suggest you update to the current version.

**Comment by liuwangchao** [comment]
> Hello @liuwangchao,
> 
> Thank you for providing detailed information. This issue does not occur in the latest versions. I suggest you update to the current version.

I update version 8.2.2 and found that this problem no longer exists, thank you very much!
