### ISSUE TITLE
Deprecated Module and Request Execution Errors in DRIVE

### ISSUE THREAD

**Issue by gala514** [ONLYOFFICE/DocumentServer#3071]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

8.2.2.22

### Expected Behavior

The deprecated module should be replaced with a supported, up-to-date version.
Browser requests should execute without errors.

### Actual Behavior

We have identified a misconfiguration in the server infrastructure for DRIVE. Specifically, the server is utilizing a deprecated module, which may affect system stability and functionality. Please find the screenshot attached (001) for reference.

Additionally, browser request execution errors are being logged, which might be related to code issues within DRIVE. A screenshot illustrating these errors is also attached (002).

Could you please investigate and address these issues at the earliest convenience? Let us know if further details or additional information is required.

Let me know if you'd like to refine or add anything (galinb@rarus.ru).

### Additional information

![001](https://github.com/user-attachments/assets/abea42bb-53b7-479b-aecf-4c9aa82a2ef2)
![002](https://github.com/user-attachments/assets/113549bb-128b-400c-a31c-a62c2532f7da)

**Comment by igwyd** [comment]
Hello, if you look at the error it leads to code that belongs to nextcloud, you need to write an issue to their repo.

**Comment by gala514** [comment]
Hello, new issue https://github.com/nextcloud/server/issues/49985

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
