### ISSUE TITLE
xls file display abnormal

### ISSUE THREAD

**Issue by JoeLucky** [ONLYOFFICE/DocumentServer#308]
Hi, I view this file on onlyoffice (the picture below, I add some shape to it), which is not the same as on PC.

![picture](https://github.com/JoeLucky/Practice/raw/master/xls%20problem/problem.png)

The file:
https://github.com/JoeLucky/Practice/raw/master/xls%20problem/the.xls

Thanks!

**Comment by flaminestone** [comment]
Hello @JoeLucky. Yes, it is bug, thank you.
This is fix - https://github.com/ONLYOFFICE/core/commit/6d3761c20bac18990cb01feb353e7af54ad5659c
It will be released in 5.2

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
