### ISSUE TITLE
recommended to reduce the number of fonts and optimize the loading speed

### ISSUE THREAD

**Issue by zhuangzhijia** [ONLYOFFICE/DocumentServer#310]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?** all

**DocumentServer version:**5.1.2

**Operating System:**server system：centos、client system：win7

**Browser version:**all browser

**Comment by ShockwaveNN** [comment]
@zhuangzhijia a lot of fonts are added to be compatible with more documents in different languages

You can freely remove all unneded fonts from `/var/www/onlyoffice/documentserver/core-fonts` and run
`documentserver-generate-allfonts.sh` after that.
Do not forget to clear browser cache after that
