### ISSUE TITLE
Problem updating to v5.1.4-22 from the previous version (using the deb-installer)

### ISSUE THREAD

**Issue by Soundbytes** [ONLYOFFICE/DocumentServer#313]
It seems there is a problem with the latest deb package when used to update an existing installation.  
After the update I was not able to load any document using the nextcloud webui. Instead I got a lengthy load animation followed by an error message 'document could not be loaded' (or similar)
I had installed onlyoffice only two weeks ago using the official guide here: https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx. (did not write down the installed version number then)

After a lot of trying around I was able to repair the installation. I am afraid I am not able to report all the steps it took because I did a lot of (most probably silly) things that I have not recorded including several attepts to uninstall the document server which always failed with a post removal script error 1.

I finally managed to repair the installation by running 
`sudo apt-get install --reinstall onlyoffice-documentserver`
which gave me the following output:

> (...)
> Vorbereitung zum Entpacken von .../onlyoffice-documentserver_5.1.4-22_amd64.deb ...
> Entpacken von onlyoffice-documentserver (5.1.4-22) über (5.1.4-22) ...
> dpkg: Warnung: Unterprozess altes post-removal-Skript gab den Fehlerwert 1 zurück
> dpkg: stattdessen wird Skript aus dem neuen Paket probiert ...
> dpkg: ... sieht so aus, als hätte das geklappt.
> onlyoffice-documentserver (5.1.4-22) wird eingerichtet ...
> (...)

I am afraid I can not give any more precise information on what caused the miracolous healing except maybe that at one point I removed the entire contents of the /etc/onlyoffice/documentserver/ directory. I then did a partial reinstall of the documentserver and then replaced the default.json with the default.json.dpkg-dist. This may or may not have influenced the final result.

**Comment by ShockwaveNN** [comment]
See workaround at https://github.com/ONLYOFFICE/DocumentServer/issues/275#issuecomment-379657543

**Comment by Soundbytes** [comment]
thanks for the reference. (although I am not sure how this relates to my problem.)
I have to admit I am a bit cautious now about using the deb package updater the next time around. Is there anything I can do on my side to make sure the update goes smoothly? How can I asses potential problems beforehand? 
Fortunately I am still testing at the moment. However I want to go live soon and might have some problems then with another lengthy downtime.
Thanks!

**Comment by ShockwaveNN** [comment]
@Soundbytes we change update procedure on 5.2 in future, but common advice - use docker version, it's preferred type of distribution by our team

**Comment by Soundbytes** [comment]
Thanks for the reassurance and for the advice. I am afraid I won't be able to switch to the docker version anytime soon. I am using a virtual server under Parallels Virtuozzo which does not support docker containers. I am quite happy that you are providung a deb installer and I truely hope you will be able to maintain this alternative installer in the future. 
If I can be of any help with testing or otherwise please let me know. 
best regards!

**Comment by ShockwaveNN** [comment]
Closing since no new info
