### ISSUE TITLE
Trouble after Distr upgrade OnlyOffice and Ubuntu 18.04

### ISSUE THREAD

**Issue by ITMaya** [ONLYOFFICE/DocumentServer#314]
Hi,

After upgrade from Ubuntu 14.04 to 18.04 I have trouble to have OnlyOffice-DocumentServer working.

When trying to install I keep having the following error:
dpkg: error processing package onlyoffice-documentserver (--configure):
"installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 127"
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

The version pushed by the repository is 5.1.4-22.

I tried the following without success:

sudo apt-get install --reinstall --force-yes onlyoffice-documentserver
Gives -> E: Internal Error, No file name for onlyoffice-documentserver:amd64

sudo apt purge onlyoffice-documentserver
sudo rm -rf /var/www/onlyoffice
sudo rm -rf /etc/onlyoffice/documentserver
sudo apt install onlyoffice-documentserver

And Dpkg-reconfigure gives:

dpkg-reconfigure onlyoffice-documentserver
/usr/sbin/dpkg-reconfigure: onlyoffice-documentserver is broken or not fully installed

At some point I got it partially installed but all services in /etc/nginx/includes/onlyoffice-http.conf wouldn't start and even /var/log/onlyoffice would only contain and empty documentserver-example folder. 

Can you please help to have it re-installed entirely? Should I remove nginx also? I currently have nginx-common and nginx-extras installed in version 1.14.0.

**Operating System:**
Ubuntu 18.04

Thank you in advance.

Regards,
John

**Comment by Ke1i** [comment]
Hi @ITMaya..
I had trouble with `sudo dpkg-reconfigure onlyoffice-documentserver
` on Ubuntu Server 18.04 LTS and it turned out nginx was the culprit.
What does `sudo nginx -t`return?

**Comment by ITMaya** [comment]
Hi @Ke1i ,

Thanks for your answer.

nginx -t returns:
# sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

I had to manually create /var/log/onlyoffice/documentserver/ otherwise it would return an error.
I'm sure there is something to do with Nginx but can't figure out how to have it working properly.

John

**Comment by Ke1i** [comment]
Maybe someone with a more technical background can help you solve this. Mine was a clean install and the errors I was getting had to do with nginx failing to start. I'm assuming you have a working nginx install.
Out of curiosity, whats the output of `sudo netstat -nltp | grep 80`?

**Comment by ShockwaveNN** [comment]
@ITMaya try this

**Comment by ITMaya** [comment]
Thank you Shockwave, I tried this already, it works to remove OnlyOffice-DocumentServer package but when I try to re-install it I get the following:

# apt-get install onlyoffice-documentserver
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  onlyoffice-documentserver
0 upgraded, 1 newly installed, 0 to remove and 120 not upgraded.
Need to get 0 B/199 MB of archives.
After this operation, 778 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package onlyoffice-documentserver.
(Reading database ... 116786 files and directories currently installed.)
Preparing to unpack .../onlyoffice-documentserver_5.1.4-22_amd64.deb ...
Unpacking onlyoffice-documentserver (5.1.4-22) ...
Setting up onlyoffice-documentserver (5.1.4-22) ...
dpkg: error processing package onlyoffice-documentserver (--configure):
 installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 onlyoffice-documentserver

Regards,
John

**Comment by ShockwaveNN** [comment]
@ITMaya try to run postint script via `bash /var/lib/dpkg/info/onlyoffice-documentserver-ie.postinst` and see actual error

**Comment by ITMaya** [comment]
I don't have the postint script with -ie suffix.

If I run the one I have here is the result:

bash /var/lib/dpkg/info/onlyoffice-documentserver.postinst

Use of uninitialized value $action in string eq at /usr/share/debconf/frontend line 27.
postinst called with unknown argument `'

**Comment by ITMaya** [comment]
Thank you for your quick reply. I upgraded npm and I still have the same exact issue.
I manage to have onlyoffice-documentserver uninstalled by updating /var/lib/dpkg/info/onlyoffice-documentserver.postrm

```
remove|upgrade)
                #clean_ds_files
                :
        ;;
```

But then when I try to re-install it, it triggers another error:

json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/default.json'
dpkg: error processing package onlyoffice-documentserver (--configure):
 installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)

Same point.

**Comment by ShockwaveNN** [comment]
@ITMaya try to backup and remove `/etc/onlyoffice` and `/var/www/onlyoffice/` dirs

**Comment by ITMaya** [comment]
@ShockwaveNN not sure if it helps, since I deleted /var/www/onlyoffice it  never came back but /etc/onlyoffice always comes back.

I already tried removing these folders and it keeps failing with:

installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ShockwaveNN** [comment]
@ITMaya `bash /var/lib/dpkg/info/onlyoffice-documentserver.postinst` return same erorr with `$action` as before?

**Comment by ITMaya** [comment]
Yes it still does return the same message:

bash /var/lib/dpkg/info/onlyoffice-documentserver.postinst
Use of uninitialized value $action in string eq at /usr/share/debconf/frontend line 27.

**Comment by ShockwaveNN** [comment]
@ITMaya is `json` util is presented on your system?
If not install it by `npm install -g json` - see https://www.npmjs.com/package/json

**Comment by ITMaya** [comment]
@ShockwaveNN yes json is present in version 9.0.6.
I tried to re-install it but I still have the same error with $action while running the postinst file.

**Comment by ShockwaveNN** [comment]
@ITMaya sorry, I'm out of ideas, check that postgres, redis and rabbitmq are running fine without any errors in logs.
Or try docker version :)

**Comment by ITMaya** [comment]
@ShockwaveNN, ok thank you for your help anyway. All the mentioned services are up and running with no errors in logs.

I'll keep digging and let you know if I find anything.

**Comment by piiskop** [comment]
I confirm having the same problem.

**Comment by attardi** [comment]
> Yes it still does return the same message:
> 
> bash /var/lib/dpkg/info/onlyoffice-documentserver.postinst
> Use of uninitialized value $action in string eq at /usr/share/debconf/frontend line 27.

You must call

bash /var/lib/dpkg/info/onlyoffice-documentserver.postinst configure

But it does not show any errors to me.

**Comment by attardi** [comment]
After long investigations I found that the script was failing when restarting nginx, with this error:

[emerg] 11037#11037: directive "ssl_certificate" is not terminated by ";" in /etc/nginx/sites-enabled/onlyoffice:10

where line 10 contained:

                ssl_certificate {{SSL_CERTIFICATE_PATH}};
                ssl_certificate_key {{SSL_KEY_PATH}};

Replaced these with absolute paths and it worked:

                ssl_certificate /var/www/onlyoffice/Data/certs/onlyoffice.crt;
                ssl_certificate_key /var/www/onlyoffice/Data/certs/onlyoffice.key;

This is just a patch. Suggestions for a proper fix are welcome.
