### ISSUE TITLE
Spreadsheet Editor - Filtering and Sorting Issues

### ISSUE THREAD

**Issue by jonathanpantall** [ONLYOFFICE/DocumentServer#315]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Filtering / Sorting in XLSX document via OnlyOffice editor is very slow and sometimes crashes page.
Also
Exporting the filtered / sorted data to XLSX and opening in Microsoft Excel and attempting to then sort the columns will crash program.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Go to launched instance of OnlyOffice.
2. https://api.onlyoffice.com/editors/editor?method=xlsxEditor
3. Enter in a few data fields, just enough to have something to filter / sort
4. Select all rows
5. Click the filter icon on OnlyOffice editor toolbar
6. Select column to filter / sort.
7. Occasionally it will crash the page, other times it will cause a long load time.

For export issue (I can start a new ticket for this, if necessary):
Repeat steps 1 - 5 above.
Export spreadsheet as XLSX.
Open downloaded document in Microsoft Excel.
Attempt to sort / filter by column.
This should cause program to crash.

**What is the expected behavior?**
Should be able to filter / sort without substantial load times or without crashing editor.

Should be able to export spreadsheet as XLSX and open in Microsoft Excel and then filter / sort without crashing program.

**Did this work in previous versions of DocumentServer?**
Not to my knowledge.

**DocumentServer version:**
Current version. https://api.onlyoffice.com/editors/editor?method=xlsxEditor

**Operating System:**
Windows 10

**Browser version:**
Chrome - Version 66.0.3359.181 (Official Build) (64-bit)

Thanks ahead of time!

**Comment by Rita-Bubnova** [comment]
Hello, @jonathanpantall.
Your cases are bugs, issues 37874 and 37875 in our internal tracker problem.

**Comment by ShockwaveNN** [comment]
@jonathanpantall your problems are fixed in 
https://github.com/ONLYOFFICE/sdkjs/commit/bec6e95661cd836d59a811d1a42c5dc4ea8e72e2
https://github.com/ONLYOFFICE/sdkjs/commit/3154ae79dc09d47289352ae600d2e3f6cb32aee1
And will be released as 5.2.0

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
