### ISSUE TITLE
Linebreak recalculate bug.

### ISSUE THREAD

**Issue by KAZMAZHANG** [ONLYOFFICE/DocumentServer#318]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In some lines, when the word and punctuation be warped to next line, the others words with justified style can't fit the line(such as the first line), and even if there is enough space to contain the word and punctuation, they also will be warped(such as the third line):
![2018-06-04_113807](https://user-images.githubusercontent.com/18349061/40898007-25cd7cca-67f1-11e8-9ca5-5121efdaf811.png)

When add/delete something in subsequent lines, the justified format will be broken, but it won't be saved:
https://1drv.ms/v/s!AkK11fTGzlvWhHrPhq-IXmS_wjOh

**DocumentServer version:**
5.1.4

**Operating System:**
Ubuntu 16

**Browser version:**
Firefox 60.0/Chrome 65
[](url)

**Comment by KAZMAZHANG** [comment]
This is the document:
[边城.docx](https://github.com/ONLYOFFICE/DocumentServer/files/2066851/default.docx)

Thank you for everything.

**Comment by ShockwaveNN** [comment]
@KAZMAZHANG Thank you, I created issues 37890 and 37891 with those problems

**Comment by ShockwaveNN** [comment]
@KAZMAZHANG Just recheck - both your bugs are fixed in dev version and will be released as 5.2

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
