### ISSUE TITLE
Ability to install older version of product from default repo

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#319]
1. Add default repo `echo "deb http://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list`
2. Try to install older version of products like
`sudo apt-get update && sudo apt-get -y install onlyoffice-documentserver-ie=5.1.3-35`

Result:
`E: Version '5.1.3-35' for 'onlyoffice-documentserver-ie' was not found`

Same for centos repo

**Operating System:** Ubuntu and Centos

**Comment by Afinogen** [comment]
I have the same problem, I had to install onlyoffice-documentserver 5.2.8 instead of onlyoffice-documentserver-ie 5.3. To somehow earned

**Comment by ShockwaveNN** [comment]
This feature is implemented by @agolybev team

DocumentServer packages since v6.1.0 is available in our repo

---

On debian-based you can list version by:
```
apt-cache madison onlyoffice-documentserver
```

and install specific version by:
```
apt-get install onlyoffice-documentserver=6.1.0-83
```
More details [here](https://askubuntu.com/a/603966/39452)

---

On centos you can list versions by:
```
yum --showduplicates list onlyoffice-documentserver
```

and install older version via
```
yum install onlyoffice-documentserver-6.1.0-83
```
More details [here](https://unix.stackexchange.com/a/151690/80041)
