### ISSUE TITLE
Пустые архивы Source

### ISSUE THREAD

**Issue by SergeyDjam** [ONLYOFFICE/DocumentServer#32]
https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-4.0.0-9

здесь .tar.gz и zip содержат из исходников только файл лицензии и README

**Comment by SergeyDjam** [comment]
https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-4.0.1-34 и здесь архивы пустые

**Comment by trofim24** [comment]
Проблема в том, что подмодули (core, sdkjs и др.), не кладутся в архивы release. Так git работает с submodules.
Как вариант, сделать clone репозитория от этого release-а с командой
`git submodule update --init --recursive`

**Comment by SergeyDjam** [comment]
Хоть и не существенная но проблема. Из-за этого получается что пакеты или не нужно публиковать или как-то по иному их надо формировать. 

Собственно так и решил проблему

**Comment by trofim24** [comment]
Как вариант, можно вместе с дистрибутивом выкладывать и свой архив исходников этой версии. Тогда проблема решится.

**Comment by trofim24** [comment]
Собственно github не собирается эту проблему как-то править.

> Sorry for the trouble! Because of the way git-archive works, if you would like to include submodules in your release we recommend building a source tarball that includes the submodules and manually upload it to the release as a release asset.

**Comment by SergeyDjam** [comment]
Но release естественно пустой... 

в любом случае уже решил эту проблему выгрузкой реп командой

git clone -b $tagname --recursive https://github.com/ONLYOFFICE/DocumentServer.git $tagname
