### ISSUE TITLE
Spreadsheet - French formula

### ISSUE THREAD

**Issue by Loxeno** [ONLYOFFICE/DocumentServer#321]
Hi,

I am trying OnlyOffice - DocumentServer (5.1.4 CE) in a docker container.

I would like to use french formula.
As I can see, on the cloud edition, I can select the language, but can't in my environment.

By advance, thank you.

**Comment by ShockwaveNN** [comment]
We will add french language in 5.1.5, thank you for notificing

**Comment by ShockwaveNN** [comment]
Fixed in https://github.com/ONLYOFFICE/web-apps/commit/a893b47fd7af6063ccac1d7e1585affa52578550

**Comment by ShockwaveNN** [comment]
5.1.5 released yesterday, this issue should be fixed
