### ISSUE TITLE
data validation cells can not normally display drop-down list.

### ISSUE THREAD

**Issue by chinayangh** [ONLYOFFICE/DocumentServer#322]
We use data validation to restrict the type of data or the values that users enter into a cell. 
And following the microsoft guide:https://support.office.com/en-us/article/create-a-drop-down-list-7693307a-59ef-400a-b769-c5402dce407b?ui=en-US&rs=en-US&ad=US
So we create a drop-down list.
And after editing the excel document and upload to nextcloud , we have intergated onlyoffice to view and edit office file online .
I click the file name in nextcloud , file can be opened by onlyoffice online but data validation drop-down list does not display . It's not work.

**Comment by ShockwaveNN** [comment]
Hi. We got support of data validation dropdowns in plans, but currently this is not high priority task and we have no ETA when it will be ready. But you can contact our sales team sales@onlyoffice.com and discuss our priorities.

**Comment by chinayangh** [comment]
https://help.onlyoffice.com/products/files/doceditor.aspx?fileid=5044486&doc=MFRDWEVOeVBqdDF1N0dhOEFtOFdCZW5xdXBnV1NjUFBPTVZKUDcyanN3UT0_IjUwNDQ0ODYi0
I found this link on website.
And I compare two products , but Collabora Online does support data validation drop-down list .

**Comment by ShockwaveNN** [comment]
@chinayangh Yes, you're right, there really no such element in comparison list

**Comment by trofim24** [comment]
We released Data Validation in [version 6.2.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#620)

**Comment by trofim24** [comment]
Duplicate of #252
