### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by Tyil** [ONLYOFFICE/DocumentServer#324]
**What is the current behavior?**

Running the docker container as per [the documentation](https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx) (`docker run -i -t -d -p 8080:80 --restart=always onlyoffice/documentserver`) fails on my machine:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"": unknown.
```

Using `sudo` to run the docker command results in the same error. I've also tried a couple older tags than `latest` (which is currently at `5.1.4.22`), but they all result in the same error for me.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Install a server (in my case Funtoo)
- Install docker (version 18.05.0-ce, build f150324)
- Run `docker run -i -t -d -p 8080:80 --restart=always onlyoffice/documentserver`

**What is the expected behavior?**

The docker container should start without fatal errors.

**DocumentServer version:**

Tested tag `5.1.4.22`, `5.1.3.35` and `5.1.2.9`.

**Operating System:**

Funtoo

**Comment by ShockwaveNN** [comment]
@Tyil does other containers work on your system.
Try 
```
docker run -i -t -d -p 8080:80 --name hello-world hello-world
docker logs hello-world
```
And make sure everything fine. If not - contact support of Funtoo or Docker itself

**Comment by Tyil** [comment]
There's 11 other docker containers running, so I'm very sure Docker itself is not the issue, nor is Funtoo.

**Comment by ShockwaveNN** [comment]
@Tyil Ok, thanks I will take a look

**Comment by Tyil** [comment]
I've tried your command as suggested, and it seems Docker can't do clean upgrades without downtime. I've restarted docker manually (which sadly did bring some downtime), but DocumentServer shows it's running right now. Thanks for the pointer into the right direction!
