### ISSUE TITLE
API for Spellchecker

### ISSUE THREAD

**Issue by badaa** [ONLYOFFICE/DocumentServer#325]
Hi,
Do you have a plan to implement an API for grammar checking?

**Comment by ShockwaveNN** [comment]
@badaa Hi there, currently we have no plans to implement such feature. But you can contact our sales team at sales@onlyoffice.com to discuss it.

**Comment by askonev** [comment]
@badaa Is the issue relevant?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
