### ISSUE TITLE
track changes not working when use input method

### ISSUE THREAD

**Issue by jdkcn** [ONLYOFFICE/DocumentServer#327]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

If use some input method, eg: Chinese input method,then track changes not working.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

If I start typing with Input Method,Not track a adding, If I start typing without input method(just input characters) then use Input method,then the tracking works.

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

I think in all versions.

**DocumentServer version:**
5.1.4
**Operating System:**
MacOS 10.13.5 / Windows 10/ Windows 7
**Browser version:**
Chrome Version 67.0.3396.87

**Comment by jdkcn** [comment]
BTW: The libreoffice online's track changes worked.

**Comment by jdkcn** [comment]
![14_00_07__06_20_2018](https://user-images.githubusercontent.com/3855/41639927-6d8e3a60-7492-11e8-8337-c21f8949ca50.jpg)

**Comment by Rita-Bubnova** [comment]
Hello, @jdkcn.
Thank you. I can confirm - this is a bug, issue 37986 in our internal issue tracker.

**Comment by jdkcn** [comment]
Hello, @ShockwaveNN .

Some schedule for fix this?

May be this is about the key code when use input method? 

This cause the wrong deal about start tracking event?

**Comment by Rita-Bubnova** [comment]
Our dev team took a look at this problem, but so far we cannot estimate the number of code changes to fix this problem. 
So we can not yet say for sure how long this will take.

**Comment by jdkcn** [comment]
@Rita-Bubnova Can u tell me the code about track changes? I wan't to try a fix, Thanks.

**Comment by KirillovIlya** [comment]
This bug will be fixed in one of the nearest release.

**Comment by Rita-Bubnova** [comment]
This has been fixed.
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
