### ISSUE TITLE
Fonts cache problem while adding new fonts

### ISSUE THREAD

**Issue by despens** [ONLYOFFICE/DocumentServer#329]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

After following the [instructions on how to install fonts into document server](https://helpcenter.onlyoffice.com/de/server/linux/document/install-fonts.aspx), all fonts except Arial seem mixed up in the Online Editor. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Following [instructions](https://helpcenter.onlyoffice.com/de/server/linux/document/install-fonts.aspx):
- install TTF files in `/usr/share/fonts` directory on Document Server (one folder per font file set, as found in the provided Deja Vu font)
- run `/usr/bin/documentserver-generate-allfonts.sh`

**What is the expected behavior?**
New fonts should show up in font selector in Online Document Editor

**Did this work in previous versions of DocumentServer?**

Didn't test on previous versions

**DocumentServer version:** 5.1.4-22

**Operating System:** Ubuntu 18.04, both client and server

**Browser version:**  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

Left: Desktop Editor; Right: Online Editor
![selection_999 740](https://user-images.githubusercontent.com/571494/41809400-587f0c64-76ed-11e8-9f10-1fa78f08a062.png)

**Comment by despens** [comment]
I found out that using the Document Server in with an icognito window (no chache) will make the online editor behave correctly and show the right fonts. Clearing my browser cache didn't help though. Is there a specific URL on the Document Server that I should manually reload?

Maybe the cache time for the fonts could be reduced in future versions?

**Comment by ShockwaveNN** [comment]
@despens Could you try to clean cache again?
It's a known problem if you add new fonts and didn't cleanup browser cache - everything will mix up. It's a very old problem and we still have no solution for this. But cleaning browser cache SHOULD work. Try to clean not only cache but other files also.

**Comment by despens** [comment]
I did clean the cache thoroughly and the fonts do appear now (except Times New Roman!)

Maybe you could add a random string to the the fonts' URL when requested by the front end? That string could change each time the fonts are rebuilt with `documentserver-generate-allfonts.sh`. 

That is how most CDNs do it.

**Comment by ShockwaveNN** [comment]
@despens yeah, of course we fought about random string, but we encountered some other troubles, I don't recall exactly that it was, but something with high network load

**Comment by Edison6351** [comment]
hi @ShockwaveNN ,about add new font cache problem, has any update?

**Comment by ShockwaveNN** [comment]
@Edison6351 sorry, currently we have no solution, so cleaning browser cache is the best workaround of this problem

**Comment by Edison6351** [comment]
@ShockwaveNN OK following this problem, thank you

**Comment by igwyd** [comment]
It.s fixed aand will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
