### ISSUE TITLE
Insert an escape characters corrupts the document

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#331]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If you insert, by mistake, with a copy paste for example, an escape characters (ALT+023), it's corrupts the file and the data are lost.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![bug_escape_character](https://user-images.githubusercontent.com/11867613/41915836-f5091096-7956-11e8-8c86-ae32c9799983.gif)

And if you open the file with word, there is an error :

![bug_with_escape_character](https://user-images.githubusercontent.com/11867613/41915942-39700366-7957-11e8-81fe-543c0e318d5b.jpg)

I checked line 1, column 1259 : it's the escape character

Thanks for your help,
Yoann

**DocumentServer version:**
5.1.4

**Operating System:**
Docker

**Browser version:**
Firefox 60.0.2

**Comment by Rita-Bubnova** [comment]
Hello, @ydelattre.
Thank you. I can confirm - this is a bug, issue 39989 in our internal issue tracker.
This problem will be fixed in version 5.2.

**Comment by ydelattre** [comment]
Hello @Rita-Bubnova.
Great ! Thanks a lot for your reactivity and your fix :)

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
