### ISSUE TITLE
Change font name to alternative name after changing interface language

### ISSUE THREAD

**Issue by linmsh** [ONLYOFFICE/DocumentServer#332]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The font is selected in Chinese font, and the toolbar is not displayed in Chinese but displayed in English.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Why does font selection end with "Microsoft YaHei" instead of Chinese?
**What is the expected behavior?**
Font selection "Microsoft YaHei" must be displayed in Chinese.like “微软雅黑”
**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
5.1.4 CE
**Operating System:**
CentOS Linux release 7.0.1406 (Core) 
**Browser version:**
Google Chrome 67.0.3396.62

**Comment by linmsh** [comment]
https://pan.baidu.com/s/1tEqN5ihR8W3UOzKbX-GTNA

**Comment by linmsh** [comment]
My question screenshot.   https://pan.baidu.com/s/1tEqN5ihR8W3UOzKbX-GTNA

**Comment by ShockwaveNN** [comment]
Currently we display only default name of Font, no alternative names.
But we think it's a great idea to change of font name while changing interface language so we will add support of this in future releases

**Comment by linmsh** [comment]
@ShockwaveNN well,cool.Expect the feature to come early

**Comment by linmsh** [comment]
@ShockwaveNN It doesn't really matter. When will the font be displayed in Chinese?
And, if necessary, I can help you with Chinese translation.

**Comment by ShockwaveNN** [comment]
@linmsh currently I have no information about ETA of this changes.
If you wanna translates names of fonts - there is no need in this, this metadata is stored in font files, we just need show them in interface.
But if you wanna help translation of whole interface to Chinese - you can contact documentation@onlyoffice.com

**Comment by linmsh** [comment]
@ShockwaveNN  well,thank for you.
I put the document server on the docker container of the Linux system.if i change the encoding and language of the docker container to the Chinese code. Will the font name on the document toolbar show Chinese?

**Comment by linmsh** [comment]
The encoding and language modification of my docker container is coded in Chinese, and the following command is executed:
1.tar -cv * | docker exec -i 0f5 tar x -C /usr/share/fonts/truetype
2.docker exec 0f5 documentserver-generate-allfonts.sh
But the font name on the document editor toolbar is still not displayed in Chinese.

**Comment by ShockwaveNN** [comment]
>if i change the encoding and language of the docker container to the Chinese code
no, it will not, we need to implement such a thing

**Comment by linmsh** [comment]
great. i see, thank you

**Comment by linmsh** [comment]
@ShockwaveNN oh，I understand. thank for you

**Comment by lixiaomeng8520** [comment]
when will this feature be implemented ?

**Comment by ShockwaveNN** [comment]
@lixiaomeng8520 Hi, currently we have no ETA of implementing this feature. You can contact sales@onlyoffice.com to speed things up.

**Comment by AndrewDi** [comment]
Any ETA now?

**Comment by Rita-Bubnova** [comment]
@AndrewDi, we plan to implement this on the DesktopEditors next year. As for DocumentServer currently we have no dates.

**Comment by ToBigToSmall** [comment]
obviously, I alse have great demand for this. hope to release or any other solution to solve this problem ?

**Comment by Rita-Bubnova** [comment]
Sorry, originally we forgot to mention issue in our private issue tracker. This is issue 43233. And sorry, currently there is no any news about it.

**Comment by ShockwaveNN** [comment]
This problem should be fixed in v6.4.1 soon. 
This fix requires a major refactoring of our codebase, so we are not 100% sure that everything is fine since we do not know Chinese at all )

So I hope we'll release v6.4.1 next week or so and our solution will be enought

**Comment by ShockwaveNN** [comment]
DocumentServer v6.4.1 is released and this problem should be fixed
