### ISSUE TITLE
web-apps spreadsheet missing french formulas

### ISSUE THREAD

**Issue by deajan** [ONLYOFFICE/DocumentServer#333]
In the DocuementServer changelog.md file, version 5.1.3 states:
```Add French translation for formulas```

I've checked in apps/spreadsheeteditor/main/ressources/formula-lang, no fr.json file is present (in web-apps repo).
Any plans on that ?

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/321

**Comment by deajan** [comment]
Thanks (wow! Fastest github issue ever. Didn't finish to update my issue and you already answered :)
