### ISSUE TITLE
Missing number format

### ISSUE THREAD

**Issue by djermann** [ONLYOFFICE/DocumentServer#334]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Number formats like 1.000,00 are possible, but not 1'000.00 or 1’000.00
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
self-explaining
**What is the expected behavior?**
Number formats like 1'000.00 and 1’000.00 have to be available as they are being used in some countries.
**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
5.1.4
**Operating System:**
Debian 9.4 (Docker)
**Browser version:**

**Comment by Rita-Bubnova** [comment]
Hello, @djermann.

The separator changes depending on the selected regional settings (File -> Advanced settings -> Regional settings).
If you want to use an apostrophe as a separator, you can, for example, select the Swiss localization. 
This localization will be added to onlyoffice-documentserver in future version. But you can use it right now in onlyoffice-documentserver-de or onlyoffice-documentserver-ie.

![screenshot_1](https://user-images.githubusercontent.com/25282241/42227460-40ab4e04-7eea-11e8-8157-019417ad4aee.png)

![screenshot_2](https://user-images.githubusercontent.com/25282241/42227461-42c1ca2e-7eea-11e8-9824-37712e0a6ac6.png)

**Comment by djermann** [comment]
Thank you @Rita-Bubnova for your answer.
I use the docker image with the community edition, will this be added there as well? If yes, can you tell in which version this will probably be added?

**Comment by Rita-Bubnova** [comment]
Probably in 5.1.5 in several weeks.

**Comment by ShockwaveNN** [comment]
5.1.5 released yesterday, this issue should be fixed
