### ISSUE TITLE
No option to switch Display Mode between Original, Markup and Final

### ISSUE THREAD

**Issue by BugReporter123** [ONLYOFFICE/DocumentServer#338]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
In the Track Changes menu you can't select the Display Mode.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use "Track Changes" and write Text. Try to hide the changes.

**What is the expected behavior?**
There is no feature called Display Mode, described [here](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/HelpfulHints/Review.aspx), where you can switch between Original, Markup and Final.

**Browser version:**
Tested in Chrome and Firefox

**Comment by ShockwaveNN** [comment]
This feature available only in Integration Edition and Developer Editions.
See https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions
