### ISSUE TITLE
Package onlyoffice-documentserver.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by amikrage** [ONLYOFFICE/DocumentServer#339]
When installed according to the instructions
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

In paragraph "Installing Document Server"
sudo yum install onlyoffice-documentserver
Gives an error "Package onlyoffice-documentserver.x86_64.rpm is not signed"

You have to use "sudo yum install onlyoffice-documentserver --nogpgcheck"

onlyoffice-documentserver-5.1.4-22.x86_64 
CentOS Linux release 7.5.1804 (Core)

The package in the repository needs to be fixed.

**Comment by ShockwaveNN** [comment]
@amikrage Thanks, we working on it

**Comment by ShockwaveNN** [comment]
Should be fixed by now
