### ISSUE TITLE
[7] ERROR FontServiceRoute [(null)] 

### ISSUE THREAD

**Issue by JalalSordo** [ONLYOFFICE/DocumentServer#34]
I installed document server on windows and I got this error on the log files, and the webApp can't even get started in IIS.

**Comment by trofim24** [comment]
You have the fonts in the system are in the folder `C:\Windows\Fonts` ?
If not, then you need to correct a [config option](https://github.com/ONLYOFFICE/server/blob/6816bb407c3851b4329f2cebd52d053b54575c5a/Common/config/development-windows.json#L34) `utils_common_fontdir`.

**Comment by trofim24** [comment]
Or you are using version 3.0 ?

**Comment by JalalSordo** [comment]
i'm using the v2.5.1 becuz i don't like the pragmatic 10 seconds save callback of v3.

**Comment by trofim24** [comment]
Sorry, we do not support version 2.5. Use version 4.0.x
