### ISSUE TITLE
onlyoffice-documentserver-ssl.conf.template

### ISSUE THREAD

**Issue by amikrage** [ONLYOFFICE/DocumentServer#340]
https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx

/etc/nginx/conf.d/onlyoffice-documentserver-ssl.conf.template
Missing in the package

https://helpcenter.onlyoffice.com/ru/server/linux/document/linux-installation-centos.aspx
And also in the Russian installation instructions, duplicated line:
sudo -u postgres psql -c "CREATE DATABASE onlyoffice;"

onlyoffice-documentserver-5.1.4-22.x86_64
CentOS Linux release 7.5.1804 (Core)

**Comment by amikrage** [comment]
rm /etc/nginx/conf.d/onlyoffice-documentserver.conf
sudo cp -f /etc/onlyoffice/documentserver/nginx/onlyoffice-documentserver-ssl.conf.template /etc/nginx/conf.d/onlyoffice-documentserver.conf

You need to improve the instructions

**Comment by ShockwaveNN** [comment]
@amikrage Fixed duplicate lines in https://github.com/ONLYOFFICE/helpcenter/pull/6 (private repo). Update helpcenter soon.

In debian installation `/etc/nginx/conf.d/onlyoffice-documentserver-ssl.conf.template` exists, I'm not sure about centos, need some time to investigate

**Comment by ShockwaveNN** [comment]
Fixed `onlyoffice-documentserver-ssl.conf.template` error in https://github.com/ONLYOFFICE/helpcenter/commit/ca96b7ff38723ced907d88e5a61b603573a511e2

**Comment by ianxo** [comment]
@ShockwaveNN 

> In debian installation `/etc/nginx/conf.d/onlyoffice-documentserver-ssl.conf.template` exists

I just install OO on a fresh debian install and I'm missing `/etc/nginx/conf.d/onlyoffice-documentserver-ssl.conf.template` too.

could someone pleas provide a link to mention file? I'm having trouble finding it...

**Comment by ShockwaveNN** [comment]
Both original issues are fixed and released on helpcenter
