### ISSUE TITLE
Documents that contain complex formulas or charts or functions cannot render a preview or edit interface.

### ISSUE THREAD

**Issue by ggp2018** [ONLYOFFICE/DocumentServer#343]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Q1.Documents that contain complex formulas or charts or functions cannot render a preview or edit interface.
Q2.Documents that contain composite diagrams cannot be fully rendered in the preview or edit interface.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[files.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2179660/files.zip)

**What is the expected behavior?**
Q1.Expected to be properly displayed and consistent with the original document.
Q2.It is expected that the broken line diagram in the composite diagram can be rendered in full.
**Did this work in previous versions of DocumentServer?**
No validation
**DocumentServer version:**
5.1.2
**Operating System:**
CentOS 7.2
**Browser version:**
IE 11 or chrom 67

**Comment by ShockwaveNN** [comment]
@ggp2018 Thanks, we have a look, but in future please create separate issue for each file

**Comment by Rita-Bubnova** [comment]
Hello, @ggp2018.

Thank you. I can confirm -  this is a bug, issue 38172 in our internal issue tracker.

The combined charts are not displayed correctly in the XLSX file. At the moment our developers are working on this issue and we plan to fix this in one of the following versions.

**Comment by ggp2018** [comment]
@Rita-Bubnova is there a plan to solve the problem?

**Comment by ShockwaveNN** [comment]
Your issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/79d103e6347cd8bd9f4ee8436cc73bef6711bb97
And will be released as 5.2.0

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
