### ISSUE TITLE
When editing or previewing an word file, some of the contents of the file are malformed

### ISSUE THREAD

**Issue by ggp2018** [ONLYOFFICE/DocumentServer#344]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When editing or previewing the word file, some of the contents of the file will be in a wrong format, and it will still be wrong after editing and saving.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[Solution V6.0.1 Troubleshooting 01.docx](https://github.com/ONLYOFFICE/DocumentServer/files/2179758/Solution.V6.0.1.Troubleshooting.01.docx)

**What is the expected behavior?**
The desired format remains consistent with the source file.
**Did this work in previous versions of DocumentServer?**
No validation
**DocumentServer version:**
5.1.2
**Operating System:**
CentOS 7.2
**Browser version:**
IE11 or chrom 67

**Comment by flaminestone** [comment]
Hello @ggp2018 . Thank you for issue. Yes, this is bug, and we fix it in future.
I created an issue 38171 in our internal bug tracker

**Comment by ggp2018** [comment]
is there a plan to solve the problem?

**Comment by flaminestone** [comment]
@ggp2018 This problem will be solved in 5.2.0 release

**Comment by trofim24** [comment]
I close this issue, because we fixed this problem and released 5.2.0 version
