### ISSUE TITLE
First row and first column disappear after scrolling

### ISSUE THREAD

**Issue by bicyclist101** [ONLYOFFICE/DocumentServer#345]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
After scrolling down and back up the first row disappears. The first row that can be seen is row 2. 
Same behavior with the columns after scrolling right and left.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open spreadsheet with mobile browser

**What is the expected behavior?**
After Scrolling down and back up the first row should not disappear.

**Did this work in previous versions of DocumentServer?**
I don't know.

**DocumentServer version:**
Nextcloud App - 1.3.0
5.1.0 CE

**Operating System:**
Android 7.1.1

**Browser version:**
Both Firefox for Android 61.0
and Chrome 67.0.3396.87

**Comment by ShockwaveNN** [comment]
@bicyclist101 which version of DocumentServer are you using?

**Comment by bicyclist101** [comment]
@ShockwaveNN Sorry for the missing info. The Version is 5.1.0 CE

**Comment by ShockwaveNN** [comment]
@bicyclist101 could you update to latest version. This issue may be fixed.

**Comment by bicyclist101** [comment]
Hi, I already wrote my nextcloud-hoster and got the reply that an update is not possible because of the new pricing model. 
As I was told upgrading to 5.1.4 would imply cost of 5€ per user. 
Well I did not know that. 
So fixing the bug won't help me specifically.

**Comment by ShockwaveNN** [comment]
@bicyclist101 I advice to change your hoster, since all versions of community edition are completely free.
I'm closing this issue since it should be fixed
