### ISSUE TITLE
[Bug] Read only users can't edit filters

### ISSUE THREAD

**Issue by enric1994** [ONLYOFFICE/DocumentServer#346]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After sharing a filtered Excel to someone who can't edit, the user only can see the filtered contents.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. User A create an Excel and add some data
2. User A share the document to user B, who can't edit the document (read only)
3. User B can view the Excel correctly
4. User A apply a filter, hiding some data
5. User B only can see the filtered data
**What is the expected behavior?**
User B should be able to edit/remove the applied filters
**Did this work in previous versions of DocumentServer?**
IDK
**DocumentServer version:**
5.1.4 CE
**Operating System:**
Debian Strecth
**Browser version:** 
Firefox 61.0.1

**Comment by ShockwaveNN** [comment]
This feature available only in commercial editions with special license type. If you want to use it please contact sales@onlyoffice.com.
