### ISSUE TITLE
Data loss in files

### ISSUE THREAD

**Issue by altokarev** [ONLYOFFICE/DocumentServer#349]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
We're losing the information in the files from time to time. I noticed such behavior for xls files at the moment.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Save the document (menu -> Save or Ctrl+S), close it and open it again - half the information is missing.

**What is the expected behavior?**
The information should not be lost.

**Did this work in previous versions of DocumentServer?**
Nope.

**DocumentServer version:**
5.1.4-22

**Operating System:**
Ubuntu 14.04.5 LTS

**Environment**
Node.js v6.14.1

**Browser version:**
Google Chrome 67.*

**Comment by altokarev** [comment]
Document Server has connected to the Nextcloud (and we're using Group Folders module).

**Comment by ShockwaveNN** [comment]
This issue related to owncloud, so please report it in according repo https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues

**Comment by altokarev** [comment]
Issue moved to [ONLYOFFICE/onlyoffice-owncloud #201](https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/201) via [**ZenHub**](https://www.zenhub.com/)
