### ISSUE TITLE
To allow to specify redis password

### ISSUE THREAD

**Issue by rarapost** [ONLYOFFICE/DocumentServer#353]
Feature request / bug / missing feature ?

it is impossible to connect to redit it it has specified connection  password.

My suggestion is to add new configuration option "password"  to redis part and chage "createClientRedis" function in "pubsubRedis.js" javascript as follow:

```
function createClientRedis() {
  var redisClient;
  if(cfgRedisPort == 0) {
    redisClient = redis.createClient(cfgRedisHost, {});
  } else {
    redisClient = redis.createClient(cfgRedisPort, cfgRedisHost, {});
  }
  if(cfgRedisPasswd && cfgRedisPasswd != "") {
    redisClient.auth(cfgRedisPasswd);
  }
  redisClient.on('error', function(err) {
    logger.error('redisClient error %s', err.toString());
  });
  return redisClient;
}
```
The snippet above involves also unix domain socked as it is suggested in #227.
In the same JS file I neede to add new configuration variable as follow:
```
var cfgRedisPrefix = config.get('prefix');
var cfgRedisHost = config.get('host');
var cfgRedisPort = config.get('port');
// the next row is added due redis password
var cfgRedisPasswd = config.get('password');
```

Both changes (including the unix socket) I have implemented and tested locally, they seem to work well.

**Comment by ShockwaveNN** [comment]
@konovalovsergey take a look

**Comment by Schmuuu** [comment]
Hello,

What is the current status of this issue? Does Onlyoffice still not work with redis when a password (requirepass) is defined in /etc/redis.conf?
I had a password defined and couldn't any place (on file basis) where I could place the password for onlyoffice to know.

**Comment by nebulade** [comment]
Hi, we at [Cloudron](https://cloudron.io) are currently looking at packaging onlyoffice for our platfrom and would also require a redis password to be specified. I would be happy to contribute this if there is any chance of this getting merged.

**Comment by phonon112358** [comment]
I would also love to have this feature...

I inserted the code from @rarapost and saved my redis password in the local.json file... However, unfortunately, it doesn't work for me...
I am on Debian 10, installed onlyoffice/squeeze 8.1.233-5 via the official apt repository of onlyoffice. My redis version is  5:5.0.3-4+deb10u1 .

Without password, everything works fine.

any suggestions what I could do to get onlyoffice running when a requirepass value is set in redis?

**Comment by phonon112358** [comment]
@ShockwaveNN What does "fixed" mean? Do you have any hint for me? 
As said, I edited the `var/www/onlyoffice/documentserver/server/DocService/sources/pubsubRedis.js` and inserted the code from @rarapost as well the `/etc/onlyoffice/local.json` file and saved my redis password there..
I also tried the `/etc/onlyoffice/default.json` for saving the password, but no difference unfortunately...

which further files do I need to edit?

**Comment by ShockwaveNN** [comment]
@phonon112358 This mean @konovalovsergey fix original issue and this code will aviable in next public release 5.5.0 very soon

**Comment by Quedale** [comment]
Nice to see this has been fixed/improved! Thanks for the great work.

**Comment by krakazyabra** [comment]
Excuse me @agolybev , but how to use password option? How to set password there?

**Comment by ShockwaveNN** [comment]
@krakazyabra Hi, you should be able to specify password via [`options` config value](https://github.com/ONLYOFFICE/server/commit/4494be4aee8d0adaa378e7585c9edf84754f9134#diff-bb093a1f3a23fd8ff9d1a6d1c73cdd9bR123)

Also please note that this feature only available on paid version of DocumentServer, since we remove `redis` from DocumentServer CommunityEdition version

If you got any trouble - I think it's better to create new issue

**Comment by krakazyabra** [comment]
hi! @ShockwaveNN! I'm surprised with such a quick response :-D
I saw the commit and `option` there. Am I right, that on Community version I'm not able to configure and use redis for OO? I only wondered, how to specify password in `option` object :)

**Comment by ShockwaveNN** [comment]
If you're using Community Version there is no need of redis server since release of 5.5.0
It's still required as dependency if 5.5.x version, but we remove it in v5.6.0

**Comment by krakazyabra** [comment]
Oh, now I see. Thank you anyway!

**Comment by CSchmidtDD** [comment]
@agolybev How is this issue closed when there is still no way to include a password in the documentation (options fine, but what syntax / semantics to use there?)
I'd recommend to open this issue until a way to use a redis with password is documented.

Feel free to give me a shout wherever I can help with this going forward.
