### ISSUE TITLE
Open file is very slowly in the first time

### ISSUE THREAD

**Issue by twangel** [ONLYOFFICE/DocumentServer#356]
Hi! I install OnlyOffice Community Edition in Windows Server 2016,when I run the demo I find the file is opened very slowly in the first time ,in the next time it will be fast. But if I close the browers and open it again,the same issue will be happened.
![20180801114353](https://user-images.githubusercontent.com/6602951/43499981-d3a5be4a-9580-11e8-8df1-85f23415bf60.png)

I debugging it in my google browers,it will load many file like '336,107,110,100',every file in them will load slowly in the first time ,next time will fast.In the case how can I solve it.

**Comment by ShockwaveNN** [comment]
This is fonts files, the more complex file with a lot different fonts are opening - the longer it will be to load until fonts files caches.
It is not an issue, it's meant that way so I closing it

**Comment by fukai7722** [comment]
How to cdn it?

**Comment by ShockwaveNN** [comment]
@fukai7722 there is no official instruction describing how to use cdn
