### ISSUE TITLE
can't use chinese input method when editing

### ISSUE THREAD

**Issue by renothing** [ONLYOFFICE/DocumentServer#36]
when I edit document, I can't switch input method to chinese. tested on document 4.0.0

**Comment by K0R0L** [comment]
![1](https://cloud.githubusercontent.com/assets/16754960/17098784/ec49f370-526c-11e6-8f8b-69f8c436c9ba.jpg)
In version 4.0, you need to choose an alternative input. Version 4.1 is the usual input. Release is planned in about a month.
