### ISSUE TITLE
Can't create document and existing documents disappeared

### ISSUE THREAD

**Issue by apacoco9861** [ONLYOFFICE/DocumentServer#361]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Document Server Create button not work. And My Documents can't access.
![image](https://user-images.githubusercontent.com/5441738/44008906-a060ae7e-9eda-11e8-9f77-4c2b979d1f70.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Click top bar select Documents and Create button malfunction. My Documents unable to show existing documents.

**What is the expected behavior?**
Create button should prompt drop down menu. My Documents should show existing documents.

**Did this work in previous versions of DocumentServer?**
Don't have update. Just installed the latest DocumentServer docker version with Community Server and Mail Server. Last Friday, user reported issue. Can't simulate/reproduce. This morning, even Administrator account encounter the issue. No modification to any configuration.

**DocumentServer version:**
docker latest v5.1

**Operating System:**
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-30-generic x86_64)

**Browser version:**
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Firefox 61.0.2 (32-bit)

**Comment by apacoco9861** [comment]
Tried restart Community Server and Document Server containers. Not work.

User suspected Traditional Chinese Chars in document name or content causing the issue.

Don't know which logs to check. Please help. Many thanks.

**Comment by apacoco9861** [comment]
When you press Common Documents button, Create button and upload button appear normal.
![image](https://user-images.githubusercontent.com/5441738/44009328-9df0bc8a-9edd-11e8-82e5-11e53135136c.png)
But when you create or upload files, and press My Documents, nothing shown.

**Comment by ShockwaveNN** [comment]
This is Community server issue, not DocumentServer, please duplicate issue at https://github.com/ONLYOFFICE/CommunityServer
