### ISSUE TITLE
How to set the default font the editor loads on startup from arial to other.

### ISSUE THREAD

**Issue by mattronix** [ONLYOFFICE/DocumentServer#365]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Sets Ariel as default
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug.

**What is the expected behavior?**
Config file or Api option to specify default font. 

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer version:**
5.1.5.59

**Operating System:**
Debian 9

**Browser version:**
Firefox 61.0.2 (64bit)

**Comment by ShockwaveNN** [comment]
You should change default empty files.
 https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs/public/samples if you using `docmunetserver-ie(-de)`

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by JOduMonT** [comment]
> You should change default empty files.
> https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs/public/samples if you using `docmunetserver-ie(-de)`

Hi; I know it is a old question but I can't figure where is my public/sample
I'm using OnlyOffice via Docker with Cloudron; I found 2 paths `/var/www/onlyoffice/documentserver/` and `/var/lib/onlyoffice/documentserver/`

**Comment by ShockwaveNN** [comment]
@JOduMonT Hi, It depend on which DMS (nextcloud, owncloud etc.) are you using

**Comment by JOduMonT** [comment]
> @JOduMonT Hi, It depend on which DMS (nextcloud, owncloud etc.) are you using

I'm using NextCloud

**Comment by HelenBelova17** [comment]
Hello @**JOduMonT**
in NextCloud default empty files are located here https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/master/assets

**Comment by tubia** [comment]
Hi @HelenBelova17 editing directly the code of the onlyoffice integration app for nextcloud would raise issues at every update - namely, the new version of the app will override the changes to the templates.

Maybe there is a more durable way to do this?

**Comment by mattronix** [comment]
Whoops i see i never responded my bad !

**Comment by DesertCookie** [comment]
> Hello @**JOduMonT** in NextCloud default empty files are located here https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/master/assets

Both of your links are dead, sadly. Would you mind editing them?

**Comment by ShockwaveNN** [comment]
All new empty files are located [here](https://github.com/ONLYOFFICE/document-templates) and sometimes is subrepo of some main repo, or sometimes checkout on build stage, but you should find those files somewhere inside your DMS integration
