### ISSUE TITLE
"502 bad gateway" error after upgrade

### ISSUE THREAD

**Issue by linus3000** [ONLYOFFICE/DocumentServer#367]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
"502 bad gateway message" after upgrade
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Update onlyoffice-documentserver from 5.1.2-9 to any higher version (last tried with 5.1.5-59)
**What is the expected behavior?**
Update onlyoffice-documentserver from 5.1.2-9 to any higher version works without getting 502 bad gateway message
**Did this work in previous versions of DocumentServer?**
yes until 5.1.2-9
**DocumentServer version:**
any higher version than 5.1.2-9
**Operating System:**
Ubuntu LTS 16.04 lxc container
**Browser version:**
Firefox 61

nginx-error.log says:

2018/08/18 08:43:55 [error] 9185#9185: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.212, server: myserver, reques$
2018/08/18 08:43:55 [error] 9185#9185: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.212, server: myserver, reques$
2018/08/18 08:43:56 [error] 9185#9185: *1 no live upstreams while connecting to upstream, client: 192.168.2.212, server: myserver, request: "GET /welcome/ HTTP/1.$
2018/08/18 08:43:56 [error] 9185#9185: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.212, server: myserver, reques$
2018/08/18 08:43:56 [error] 9185#9185: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.212, server: myserver, reques$
2018/08/18 08:43:56 [error] 9185#9185: *1 no live upstreams while connecting to upstream, client: 192.168.2.212, server: myserver, request: "GET /welcome/ HTTP/1.$

What I tried already:

re-install onlyoffice-documentserver (keep config-files as well as use the maintainers version), 
re-install nginx.
Switch back to  5.1.2-9 works, however tis is no proper solution.

During the upgade onlyoffice-documentserver.conf was changed, however I had a backup of the working version. 
I don‘t know if any other nginx config fies have been changed during the update of onlyofice-documentserver .

**Comment by ShockwaveNN** [comment]
@linus3000 is there any errors in `/var/log/onlyoffice/`?

**Comment by linus3000** [comment]
in /var/log/onlyoffice/  the folders documentserver  and documentserver-example are found.
in folder documentserver the nginx.error.log is there (as posted above).

**Comment by ShockwaveNN** [comment]
>in /var/log/onlyoffice/ the folders documentserver and documentserver-example are found
Yes, it is.
Check logs for errors inside those folders

**Comment by linus3000** [comment]
thans a lot!

do you know which files containing relevant config to back up?

**Comment by ShockwaveNN** [comment]
@linus3000 you should bacup all your `/etc/onlyoffice/documentserver` configs and restore only needed settings after upgrade

**Comment by linus3000** [comment]
Sorry for delayed feedback.

I tried again to upgrade from 5.1.2-9 to 5.1.5-59 and installed the maintainers config versions.
the 502 error is gone, but the welcome screen tells me:

"Something went wrong during installation
Make sure that you have followed the installation instructions"

content of /var/log/onlyoffice/documentserverdocservice/err.log (no other eror-logs):

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:969:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Metrics/node_modules/statsd/lib/config.js:33:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Metrics/node_modules/statsd/stats.js:4:14)
(node:10292) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:522) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:502) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:575) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:569) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:587) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:493) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:4612) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:490) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:499) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:534) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:555) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:493) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:5891) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:508) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:548) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:502) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

**Comment by linus3000** [comment]
...ok after restart of nginx it works now!
I don't know what was different this time? Maybe there was a mistake in the first try when restoring the onlyoffice-documentserver.conf.

Great thanks to ShockwaveNN for support & patience. This issue can be closed I guess.
