### ISSUE TITLE
NewDocumentTitle.docx with size 0 byte do not support

### ISSUE THREAD

**Issue by henadzi** [ONLYOFFICE/DocumentServer#370]
*bug*

Create new document *.docx with Windows Explorer (mouse right click). Try to open it. OnlyOffice say "File format don't support" (Формат файла не поддерживается)

**What is the expected behavior?**
Microsoft Office open the 0 sized without problem.  MS Office even do not create a bit of size if try to save the 0 size document.

**Operating System:** - Windows 10. OnlyOffice localy installed.

**Comment by henadzi** [comment]
Localy installed version  5.1.29.348

**Comment by Rita-Bubnova** [comment]
Hello, @henadzi.
Thank you. I can confirm - this is a bug, issue 38187 in our internal issue tracker.

**Comment by trofim24** [comment]
We've fixed this problem in version 5.5
