### ISSUE TITLE
OnlyOffice try save something, even there is nothing to save.

### ISSUE THREAD

**Issue by henadzi** [ONLYOFFICE/DocumentServer#371]
feature

**What is the current behavior?**
Every time I push Ctrl+S on localy installed OnlyOffice - it try save something, even there is nothing to save.
**What is the expected behavior?**
MS Office do not save document if there is nothing to save.
**Operating System:**
Windows -10. Local installed OnlyOffice.

**Comment by ShockwaveNN** [comment]
This is issue tracker for DocumentServer, please duplicate it in https://github.com/ONLYOFFICE/DesktopEditors/issues
