### ISSUE TITLE
The document crushes after press Ctrl+D, save and close.

### ISSUE THREAD

**Issue by henadzi** [ONLYOFFICE/DocumentServer#372]
bug

if I press Ctrl+D in any document, save it and close - I cann't open it. (even MS word cann't open it)
all text after the place where was the cursor is disappear.

**What is the expected behavior?**
fore example do nothing on Ctrl+D

**Operating System:**
Windows 10. Localy installed version 5.1.29.348.

**Comment by ShockwaveNN** [comment]
This is issue tracker for DocumentServer, please duplicate it in https://github.com/ONLYOFFICE/DesktopEditors/issues
