### ISSUE TITLE
Update bundled libicu to build on latest glibc

### ISSUE THREAD

**Issue by arturlangner** [ONLYOFFICE/DocumentServer#375]
This can be ugly worked around by `touch /usr/include/xlocale.h` 

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Bundled libicu fails to build with the following error `fatal error: xlocale.h: No such file or directory`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`cd core/Common/3dParty && ./make.sh`

**What is the expected behavior?**
Bundled library (and DocumentServer later on) builds fine

**Did this work in previous versions of DocumentServer?**
not applicable

**DocumentServer version:**
git 94548131a14c93e3aa00d991acf52535db3e5d71

**Operating System:**
Ubuntu 18.04.1 LTS, glibc (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

**Browser version:**
not applicable

**Comment by ShockwaveNN** [comment]
related with https://github.com/ONLYOFFICE/core/pull/90

**Comment by ShockwaveNN** [comment]
Fixed in https://github.com/ONLYOFFICE/core/pull/97
