### ISSUE TITLE
Can't support character spacing

### ISSUE THREAD

**Issue by kalcaddle** [ONLYOFFICE/DocumentServer#376]
like this:
![image](https://user-images.githubusercontent.com/3761968/44574590-69789300-a7bc-11e8-954a-895b95e17e47.png)

![image](https://user-images.githubusercontent.com/3761968/44574568-55349600-a7bc-11e8-82e5-9d6265d82ded.png)

[红头文件模板(铁道部).docx](https://github.com/ONLYOFFICE/DocumentServer/files/2317675/default.docx)

**Comment by ShockwaveNN** [comment]
@kalcaddle could you attach screenshot comparison of document render in Onlyoffice and this editor? And/Or translate settings it to English.
I have no idea what do you mean

**Comment by HellRoad** [comment]
If you mean "Charater Spacing Interval", you can open Paragraph advanced menu and choose category "Font" 
Specify a negative value in the field "Spacing"
But if you mean a default preset like "Expanded or Condensed", this function is not yet available.

**Comment by kalcaddle** [comment]
I mean "Expanded or Condensed".
