### ISSUE TITLE
AllFontsGen (complied with clang) segfault during server make install

### ISSUE THREAD

**Issue by arturlangner** [ONLYOFFICE/DocumentServer#377]
Valgrind trace:
[AllFontsGen-valgrind-trace.txt](https://github.com/ONLYOFFICE/DocumentServer/files/2317845/AllFontsGen-valgrind-trace.txt)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`make install` of the server fails, because `AllFontsGen` segfault

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Execute as any user:
```
/var/www/onlyoffice/documentserver/server/tools/AllFontsGen --input="/var/www/onlyoffice/documentserver/core-fonts"\
--allfonts-web="/var/www/onlyoffice/documentserver/sdkjs/common/AllFonts.js"\
--allfonts="/var/www/onlyoffice/documentserver/server/FileConverter/bin/AllFonts.js"\
--images="/var/www/onlyoffice/documentserver

```
**What is the expected behavior?**
`AllFontsGen` does not segfault

**Did this work in previous versions of DocumentServer?**
I don't know

**DocumentServer version:**
git 94548131a14c93e3aa00d991acf52535db3e5d71

**Operating System:**
Ubuntu 18.04.1 LTS, core and server built with gcc 7, 3rd party built with gcc 5 (due to v8 https://bugs.chromium.org/p/chromium/issues/detail?id=691681 )

**Browser version:**
not applicable

**Comment by onny** [comment]
I have this issue too. Here's my package buildscript: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=onlyoffice-documentserver
I use clang to compile v8 because with gcc there are too many issues.

**Comment by ShockwaveNN** [comment]
@onny I think `clang` is the reason, currently we do not test it on clang

**Comment by thomaswollburg** [comment]
Any solution to this? Getting the same error when trying to install via

`sudo apt-get install onlyoffice-documentserver`

on a fresh Ubuntu 16 machine.

**Comment by ShockwaveNN** [comment]
@thomaswollburg I don't think this problem related to your issue, since this issue for manually compiled `AllFontsGen`
You should create separate issue and describe your problem in more details

**Comment by thomaswollburg** [comment]
#396 done :)

**Comment by onny** [comment]
@ShockwaveNN:
I'm still using `clang` in version 5.2.0 and everything is working really good! (getting v8 to work is really more easy using `clang` instead of `gcc`).
`allfontsgen` still segfaults but now it is more verbose with following error message:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
Looks like there's some issue in the code?

**Comment by ShockwaveNN** [comment]
@ShockwaveNN maybe, but currently we have no human resources to have a look at that code at clang, we support only gcc

**Comment by onny** [comment]
Okay I figured out some more things: In case the directory ``/usr/share/fonts`` is empty, ``AllFontsGen`` binary segfaults with following error:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
If I put font-files in there, it seems to work fine. So it is enough to install, e.g. the package ``noto-fonts``. The command is the following (taken from the official installation routine at ``server/Makefile``):
```
sudo -u onlyoffice "/usr/share/webapps/onlyoffice/documentserver/server/tools/AllFontsGen"\
          --input="/usr/share/webapps/onlyoffice/documentserver/core-fonts"\
          --allfonts-web="/usr/share/webapps/onlyoffice/documentserver/sdkjs/common/AllFonts.js"\
          --allfonts="/usr/share/webapps/onlyoffice/documentserver/server/FileConverter/bin/AllFonts.js"\
          --images="/usr/share/webapps/onlyoffice/documentserver/sdkjs/common/Images"\
          --selection="/usr/share/webapps/onlyoffice/documentserver/server/FileConverter/bin/font_selection.bin"\
          --output-web="/usr/share/webapps/onlyoffice/documentserver/fonts"\
          --use-system="true"
```
Setting ``--use-system="false"`` also results in a segfault!

Best regards,
Jonas

**Comment by drebs** [comment]
I am hitting the same problem, using Ubuntu 18.04, DocumentServer 5.3.1, and gcc 5.5.0 for both 3rd party (due to v8 as @arturlangner points out) and DocumentServer core and server.

I think the title of this issue should not have been changed to mention clang as the original problem reported by @arturlangner does not involve clang, only gcc.

My tests also suggest that the issue is not related to using different gcc versions for compiling different parts of the system, as I am using the same version (gcc-5) for everything.

This is the command that fails:

```
root@bb619a76095b:/srv/onlyoffice/DocumentServer/server# sudo -u onlyoffice "strace" \
  "/var/www/onlyoffice/documentserver/server/tools/AllFontsGen" \
  --input="/var/www/onlyoffice/documentserver/core-fonts" \
  --allfonts-web="/var/www/onlyoffice/documentserver/sdkjs/common/AllFonts.js" \
  --allfonts="/var/www/onlyoffice/documentserver/server/FileConverter/bin/AllFonts.js" \
  --images="/var/www/onlyoffice/documentserver/sdkjs/common/Images" \
  --selection="/var/www/onlyoffice/documentserver/server/FileConverter/bin/font_selection.bin" \
  --output-web="/var/www/onlyoffice/documentserver/fonts" \
  --use-system="true" 2> /tmp/AllFontsGen.strace
Segmentation fault
```

And this is the strace output: 
[AllFontsGen.txt](https://github.com/ONLYOFFICE/DocumentServer/files/3266796/AllFontsGen.txt)

**Comment by drebs** [comment]
It looks like some specific fonts are the cause of the segfault. I had to remove the following fonts from `core-fonts` in order to make `AllFontsGen` succeed:

```
for font in \
    lohit-assamese \
    lohit-bengali \
    lohit-devanagari \
    lohit-gujarati \
    lohit-kannada \
    lohit-malayalam \
    lohit-oriya \
    lohit-punjabi \
    lohit-tamil \
    lohit-tamil-classical \
    lohit-telugu \
    nanum \
    noto \
    opensans \
    padauk \
    samyak \
    samyak-fonts \
    tibetan-machine \
    ttf-khmeros-core \
    ubuntu-font-family \
    wqy-zenhei; \
do rm -rf /srv/onlyoffice/DocumentServer/server/build/core-fonts/${font}; done
```

This is a package with the fonts above (except `nanum` and `wqy-zenhei` because they were too big to fit in an github-uploadable file) as I think they might all have something in common and the list of fonts may differ depending on the setup: [problematic_core-fonts.zip](https://github.com/ONLYOFFICE/DocumentServer/files/3267388/problematic_core-fonts.zip)

**Comment by drebs** [comment]
I have built **Document Server 5.3.2** (and deps and everything) using **Ubuntu 18.04** and **gcc-4.8** and the segfault described above does not happen. Looks like that gcc version may be the cause of the segfault?

**Comment by githublyx** [comment]
@ShockwaveNN 
I am using GCC 5.4.0.
Hello, What version of GCC do you suggest?

**Comment by ShockwaveNN** [comment]
@githublyx I think main reason not gcc but some of fonts installed on your server

**Comment by githublyx** [comment]
@ShockwaveNN All then fonts in core-fonts was feched from git. 
Why are there still mistakes?Any more Suggestions? Thanks a lot...

**Comment by ShockwaveNN** [comment]
Do you tried to perform https://github.com/ONLYOFFICE/DocumentServer/issues/377#issuecomment-500024765?

**Comment by githublyx** [comment]
@ShockwaveNN 
Yes, I referred to #377, but  It's no use

**Comment by ShockwaveNN** [comment]
@githublyx Try to remove all fonts (or leave only one), maybe this help.

**Comment by githublyx** [comment]
@ShockwaveNN 
I followed the method of 377 and reported the following error
[ins.log](https://github.com/ONLYOFFICE/DocumentServer/files/3391803/ins.log)
I do

**Comment by githublyx** [comment]
I just left one font, and there were no mistakes.
But what is the root of the problem?

**Comment by ShockwaveNN** [comment]
@githublyx We still was not able to reproduce this issue on our setups, if you attach Dockerfile with this error happens - it may help.

**Comment by githublyx** [comment]
@ShockwaveNN 
Here is my Dockerfile.
[Dockerfile.TXT](https://github.com/ONLYOFFICE/DocumentServer/files/3391844/Dockerfile.TXT)

**Comment by ShockwaveNN** [comment]
@githublyx I mean full Dockerfile with all compiling steps, since it somehow related to gcc version at least. 
Similar to https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/master/Ubuntu14.04/Dockerfile (which works fine with all those fonts)

**Comment by githublyx** [comment]
@ShockwaveNN 
I recompiled all the modules using gcc4.8 and the problem was solved, so I think the **GCC version** is the main problem. I hope to test gcc5.4 sometime later to see what the problem is. Thank you very much for your help.

**Comment by ShockwaveNN** [comment]
@githublyx Good to hear your issue is resolved. I'm not sure, but I think I was able to reproduce this issue on Docker with Ubuntu 16.04 (https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/master/Ubuntu16.04/Dockerfile), I'll recheck

**Comment by ShockwaveNN** [comment]
@githublyx nope, builded with https://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/master/Ubuntu16.04/Dockerfile just fine.
So I'll be thankful if anybody can attach Dockerfile with segfault happened

**Comment by githublyx** [comment]
@ShockwaveNN 
I don't have a complete dockerfile because I installed the dependencies manually, step by step, according to the instructions."https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx"

**Comment by ShockwaveNN** [comment]
@githublyx sorry, without Dockerfile I don't think it'll be very easy to reproduce this problem (I tried on real server, but got no error)

**Comment by notEvil** [comment]
@onny I used your build and it still yields `bad_alloc` for me. I looked at the output of strace, as @drebs did, and it ends with
`mmap(NULL, 288230359038955520, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)`
(mind the 288230359038955520 bytes) Do you see the same?

**Comment by elias-schneuwly** [comment]
> It looks like some specific fonts are the cause of the segfault. I had to remove the following fonts from `core-fonts` in order to make `AllFontsGen` succeed:
> 
> ```
> for font in \
>     lohit-assamese \
>     lohit-bengali \
>     lohit-devanagari \
>     lohit-gujarati \
>     lohit-kannada \
>     lohit-malayalam \
>     lohit-oriya \
>     lohit-punjabi \
>     lohit-tamil \
>     lohit-tamil-classical \
>     lohit-telugu \
>     nanum \
>     noto \
>     opensans \
>     padauk \
>     samyak \
>     samyak-fonts \
>     tibetan-machine \
>     ttf-khmeros-core \
>     ubuntu-font-family \
>     wqy-zenhei; \
> do rm -rf /srv/onlyoffice/DocumentServer/server/build/core-fonts/${font}; done
> ```
> 
> This is a package with the fonts above (except `nanum` and `wqy-zenhei` because they were too big to fit in an github-uploadable file) as I think they might all have something in common and the list of fonts may differ depending on the setup: [problematic_core-fonts.zip](https://github.com/ONLYOFFICE/DocumentServer/files/3267388/problematic_core-fonts.zip)

after removing the fonts as described i still had the issue.
after removing the font "fonts-beng-extra" out of the same directory the build finished without any issues..

**Comment by jrjena136** [comment]
@ShockwaveNN I have also faced some issue while building trying to run `make install` in core and server directory manually.
could you please help me to create the onlyoffice-documentserver package. I have followed the build_tools repo for compilation. compiled output is also present inside out directory. how can I create the debian package.

**Comment by ShockwaveNN** [comment]
> help me to create the onlyoffice-documentserver package

Hi, we do not provide an instruction how to build packages. 
As far as I aware - in general - OpenSource products do not provide OS specific package build instruction, it's done by developers of each Linux distribution
