### ISSUE TITLE
Spreadsheet Editor automatically changed in formula number from localized view "46,025" to "46.025"

### ISSUE THREAD

**Issue by amokmen** [ONLYOFFICE/DocumentServer#378]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Where: Spreadsheet Editor version 5.1.5 (commercial cloud)
Language: Russian  
Problem: Automatically changed last number in formula from "46,025" to "46.025"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Type or insert from buffer next formula to any cell: `=(4+23,15+17,9+16,81+13,83+11,29+5,193)+(46,025)`  
2) Editor would automatically change last number from "46.025", but formula works correct and in cell would be right sum "138,2"

**What is the expected behavior?**
Not changing "," to "." as decimal divider for number.

**Did this work in previous versions of DocumentServer?**
I don't know

**DocumentServer version:**
5.1.5

**Operating System:**
Windows 10 x64

**Browser version:**
Opera 54.0.2952.71

**Comment by Rita-Bubnova** [comment]
Your issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/3a9eca6a9a54ccedbae0defbbc4910ade23c2046 and will be released as 5.2 soon.
