### ISSUE TITLE
PPTXFormatLib.pro has Timing.h listed twice, causing the build to break.

### ISSUE THREAD

**Issue by chrispydizzle** [ONLYOFFICE/DocumentServer#379]
PPTXFormatLib.pro (only matters if you're on linux) has an erroneous second entry that causes the build to break. It lists Timing.h twice, 
on lines **313**:
`../../../PPTXFormat/Logic/Timing/Timing.h \`
and **421**:
`../../../PPTXFormat/Logic/Timing.h \`
but there's only the first one. I'm happy to send you a pull req, let me know.

**Comment by ShockwaveNN** [comment]
Fixed in https://github.com/ONLYOFFICE/core/commit/942767eb79b4ab8891e7e021c8b828f126f98f64

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
