### ISSUE TITLE
No more mirror to try

### ISSUE THREAD

**Issue by raphson93** [ONLYOFFICE/DocumentServer#380]
Can provide alternate way to download the server ?
From centos it always complained no more mirror to try while doing clean installation

**Comment by ShockwaveNN** [comment]
Just checked - everything is fine while downloading `onlyoffice-documentserver` from official repo
You can also download it by direct link 
http://download.onlyoffice.com/install/documentserver/linux/onlyoffice-documentserver.x86_64.rpm
