### ISSUE TITLE
CIFS/SMB shared documents cannot be edited/opened.

### ISSUE THREAD

**Issue by dishu2511** [ONLYOFFICE/DocumentServer#383]
**Do you want to request a *feature* or report a *bug*?**
Just a Query
**What is the current behavior?**
So, we just deployed Nextcloud 13 on Ubuntu 16.04. We are using Nextcloud for the users so that they can access the shared drives (SMB shares) while offsite.
We are using the option of : Login credentials, save in session option for authentication purpose.
The other authentication options are not possible for us, due to security concerns.

The shares are working perfectly fine. But the documents inside the shares can't be opened edited using Onlyoffice, it throws up error message: "Download Failed. Press OK to return to document list."
Onlyoffice document server is working fine, as I can create/edit non-SMB shared documents. 
So, does Onlyoffice supports editing of documents shared via SMB external drives on Nextcloud?
If yes, then please advice.

**Did this work in previous versions of DocumentServer?**
N/A, as we are tyring Onlyoffice for the first time.
**DocumentServer version:**
5.1.5-59
**Operating System:**
Ubuntu 16.04

**Comment by ShockwaveNN** [comment]
This is Nextcloud issue, please duplicate it in https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues
