### ISSUE TITLE
Custom number formats

### ISSUE THREAD

**Issue by denpawy** [ONLYOFFICE/DocumentServer#385]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Real custom number formats are not implemented

1. Rightclick on any cell
2. Number Format --> Advanced Formats
3. Category: Custom
4. Format: Premade selection of a lot of custom formats

**What is the expected behavior?**
To have the possibility to add own custom number formats

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.1

**Operating System:**
Linux

**Browser version:**
All Browsers

**Comment by Harlehatschi** [comment]
Ahoy guys,

> Hello, @denpawy.
> 
> Thank you for your enhancement.
> I created a new issue 38828 in our private issue tracker.
> We will discuss this with our team.

what's the current state of this issue?
I would really like to see this feature, it could make some data WAY more readable and common office alternatives like Excel, LibreOffice Calc and OpenOffice Calc implemented this years ago.

**Comment by ShockwaveNN** [comment]
@Harlehatschi we will notify in this issue if we got any progress

**Comment by similonpascal** [comment]
I need [h]:mm to have the sum hours as duration and only show Hours and minutes (no seconds)

**Comment by totti4ever** [comment]
just out of curiosity, hasn't this been implemented because it's a big effort or because there just have been more important little things?

It is because apparently OnlyOffice can cope with these formats already when defined and saved in excel and opened in OnlyOffice, so I would have thought it is just about replacing the Drop-down with a Combobox

**Comment by AlexanderRevo** [comment]
I hope this gets implemented sooner rather than later. As much as I like the look and feel of OnlyOffice, having no custom formats is a deal-breaker for me.

**Comment by edbrowndesign** [comment]
I have found a workaround to this. I have Excel with work, and if I open the .xlsx in it, I can change the format and upload it back to my nextcloud (which is using the only office). 

Not ideal, I know, and I understand that people probably own the only office as it is free, compared to excel.

I am sad that this still hasn't been added in yet.

**Comment by trofim24** [comment]
We supported custom number formats in [version 6.2.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#620)
