### ISSUE TITLE
Paste Named Ranges

### ISSUE THREAD

**Issue by denpawy** [ONLYOFFICE/DocumentServer#386]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When selecting a cell and typing in:
=MyName
Then I get either a "#Value" as a result or the content of the cell in the named range as long as I'm in the same row.

**What is the expected behavior?**
I would like to be able to paste complete named ranges into the cells next to my selected cell - depending on the defined named range.

For example:
1. Defining a named range for $A$1:$B$2.
2. Selecting cell C3.
3. Typing following or a similar formula, here two examples:
    =paste(MyName)
    =MyName
4. Result:
    The cells C3:D4 have a reference to the cells defined in the name range. Example:
    C3 =$A$1
    D3 =$B$1
    C4 =$A$2
    D4 =$B$2

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.1

**Operating System:**
Linux

**Browser version:**
All

**Comment by ShockwaveNN** [comment]
@denpawy We just checked your example in MS Office 2016 and Libre Office Calc and it work as same as in our editor (#VALUE! error).
If you mean [array formula](https://support.office.com/en-us/article/create-an-array-formula-e43e12e0-afc6-4a12-bc7f-48361075954d) which created by Ctrl+Shift+Enter in Office - we are planning to add this feature in feature (issue 36111), but have no exact date when it will be ready

**Comment by denpawy** [comment]
I did not mean array formulas since I didn't knew them - but they look awesome.
I meant pasting a reference block resprecting the selected cell.
This feature does not exist in Excel either.

Another question while I'm at it:
Can cells from other documents be referenced with onlyoffice?
I tried it in Excel: =MyOtherExcel!A1 and it seems to be working there.
Just curiosity. If it's not possible would you advise me opening another feature-issue?

**Comment by ShockwaveNN** [comment]
@denpawy about first problem - currently we do not planning to implement such a feature, since it's not included in any Spreadsheet editor of which we known (MS, Libre, Google). 

About link to local file - we may implement such a feature in future for DesktopEditors, but not for DocumentServer.
We planning to add support of link to web files in DocumentServer, but only for file on public accessible links (issue 38646)

**Comment by denpawy** [comment]
Thanks for the quick response.
This issue can be closed now, if something were to happen or hits my mind I'll create a new issue =)
