### ISSUE TITLE
Freeze after move column in Spreadsheet Editor

### ISSUE THREAD

**Issue by denpawy** [ONLYOFFICE/DocumentServer#387]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The API-Version freezes when trying to move a column.
I already posted this problem in the forum ([dev.onlyoffice.org](http://dev.onlyoffice.org/viewtopic.php?f=3&t=11702)) but never got an answer.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Select a column by clicking on its name
2. Move the column when grabbing a border of it
3. The editor freezes the browser tab.

**What is the expected behavior?**
The column will be moved between the targeted column where it is being dropped on.

**Did this work in previous versions of DocumentServer?**
I do not know

**DocumentServer version:**
5.1

**Operating System:**
Linux

**Browser version:**
Any

**Comment by ShockwaveNN** [comment]
@denpawy Hi, what do you mean by "API-Version" and "API-Editor"
Could you record video of problem and attach it as a gif?

**Comment by denpawy** [comment]
I am using the [onlyoffice api](https://api.onlyoffice.com/editors/config/).
The document server is installed with docker on a linux server.
About the video: I will answer to this later on. Thank you for the quick response.

**Comment by ShockwaveNN** [comment]
@denpawy I think problem has nothing to do with API

**Comment by denpawy** [comment]
I made a Loom Video which can be found with the following [Link](https://www.useloom.com/share/1f2b3eb24b244ca199808a8d4b02d3cb).
If the gif is necessary then I could try to find a safe converter for the video.
Thanks in advance!

**Comment by Rita-Bubnova** [comment]
Hello, @denpawy.
Thank you. I can confirm - this is a bug, issue 38858 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
Your issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/bc62cecf909cd9f73a6545a546a31a483aea8c6f and will be released as 5.2 in several weeks.

**Comment by ShockwaveNN** [comment]
@denpawy sorry, we have no exact information on update-cycles. We release as soon as release version is ready

**Comment by denpawy** [comment]
@ShockwaveNN No problem =) this ticket can be closed.

**Comment by ShockwaveNN** [comment]
@denpawy we close this issue *after* we release 5.2. Thanks :)

**Comment by ShockwaveNN** [comment]
DocumentServer 5.2.0 released
Issue should be fixed
