### ISSUE TITLE
Implement AutoCorrect feature

### ISSUE THREAD

**Issue by rameesps** [ONLYOFFICE/DocumentServer#388]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by Rita-Bubnova** [comment]
Hello, @rameesps.
Do you mean [AutoCorrect](https://support.office.com/en-us/article/choose-autocorrect-options-for-capitalization-spelling-and-symbols-e7433b94-f3de-4532-9dc8-b29063a96e1f) like in MS Office?
If so - AutoCorrect function is not implemented in our editors.
I created a new issue 38873 in our private issue tracker.

**Comment by rameesps** [comment]
Not AutoCorrect. Populate options , when typing.Like proofing in MS word.

**Comment by rameesps** [comment]
Is there any option to over come it.I need to ad short keys for some words.If i type like HW , automatically populate or replace it with Hello World, or key board short key for same.

**Comment by ShockwaveNN** [comment]
@rameesps 
> .If i type like HW , automatically populate or replace it with Hello World, or key board short key for same.

That you describe is exactly AutoCorrect in MS Office.

> proofing in MS word

Can you add link to MS Office help support site of this feature?

**Comment by rameesps** [comment]
@ShockwaveNN 
Proofing is MS office tool .
Watch this https://www.youtube.com/watch?v=FSWmMpBJVSU

**Comment by ShockwaveNN** [comment]
Ok, this video showing only how to enable Spellcheck in Word (and we got him). Could you record your own video of word with feature you want and how it works?

**Comment by rameesps** [comment]
@ShockwaveNN 
If i type letter 'R' and enter space button , i need to replace 'R' with Ramees(For increasing typing speed with short keys).Like this i need to add lot of letters and its full forms.

**Comment by ShockwaveNN** [comment]
@rameesps and tell me how it differ from [AutoCorrect](https://support.office.com/en-us/article/choose-autocorrect-options-for-capitalization-spelling-and-symbols-e7433b94-f3de-4532-9dc8-b29063a96e1f) in MS?

**Comment by ShockwaveNN** [comment]
@rameesps currently AutoCorrect is not high priority task. You can contact sales@onlyoffice.com to change priorities

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
