### ISSUE TITLE
The document could not be saved

### ISSUE THREAD

**Issue by khanhmas** [ONLYOFFICE/DocumentServer#39]
When i open the document in the editor, it shows up the warning modal with the message : **The document could not be saved. Please check the connection settings...**

I'm using the latest version Document Server (4.0.1) on Docker. The Document Server 3.0.0 doesn't produce this warning modal.

In fact, although this popup is displayed, the document still can be saved into the external storage (Alfresco) and the co-edition seems to work PARTIALLY.

**Comment by trofim24** [comment]
The document storage service must return the following response, otherwise the document editor will display an error message:

`{
    "error": 0
}`

[Callback Handler](http://api.onlyoffice.com/editors/callback#error-0)

**Comment by khanhmas** [comment]
Thanks for your quick reply, do you have any idea about why it produces this error ?

**Comment by trofim24** [comment]
> Thanks for your quick reply, do you have any idea about why it produces this error ?

As you open the document in the editor?
From demo-sample of ONLYOFFICE ™ Integration Edition ?

**Comment by Dean13** [comment]
Hello,

the { "error": 0 } response practically means "Document was returned to the Document Storage without any error". The one to produce the response { "error": 0 } is the Document Storage service, written and implemented on your side.

**Comment by khanhmas** [comment]
Thanks you very much. The problem is solved.

**Comment by gong9949** [comment]
@khanhmas  hello,i have the same problem ,how did you solve it?
Could you please tell me?

**Comment by nguyenvancanh** [comment]
hello. i return { "error": 0 }  at the and of file callback. and the dialog message eror do not diplay. But, when i edit file and save it. it do not save content file as expected. How can i fix it. Thanks
