### ISSUE TITLE
[Feature Request] Make the visibility of the format panel in document editor configurable

### ISSUE THREAD

**Issue by dmkash** [ONLYOFFICE/DocumentServer#393]
**Do you want to request a *feature* or report a *bug*?**
Requesting a feature

**What is the current behavior?**
When the user first loads a page with the embedded ONLYOFFICE document, the format panel on the right-hand side is expanded/visible.  It takes up a lot of the real-estate on the screen and obscures the document.  Once the user hides it, the setting is stored in local storage so that it stays hidden.  However, if the user is on a different computer or browser, the panel will be open again.

**DocumentServer version:**
5.1.21

**Request**
It would be great if there was a configuration option that can be passed when initializing the document editor to hide this panel, or maybe to set it to be hidden by default, so that the user's setting can override it.

**Comment by ShockwaveNN** [comment]
@dmkash Hi, I think it's a good idea, but we should discuss it with a team. I created an issue 39096 in our private bug tracker

**Comment by durandx** [comment]
Hello,

Do you have any news about this feature request ?

Thanks

**Comment by ShockwaveNN** [comment]
Sorry, forgot to close issue
This feature is already implemented

See https://api.onlyoffice.com/editors/config/editor/customization#hideRightMenu for documentation

I'll close issue, but feel free to comment if got any question
