### ISSUE TITLE
Installation of 5.2 doesn't work

### ISSUE THREAD

**Issue by saitam1** [ONLYOFFICE/DocumentServer#395]
**DocumentServer version: 5.2

**Operating System: 18.04.1

**Browser version:**

I just downloaded the new Onlyoffice v5.2 and double-clicked the .deb file to install it. What happened after the installation progress bar went to 100% is that it shows up under add-ons in Ubuntu Software and still offers me to install the programm:

![soft](https://user-images.githubusercontent.com/23245678/46247121-fc819a00-c406-11e8-8feb-14b553b2ba69.png)

If I click on install in the add-ons field of Ubuntu Software it asks me if I want to remove the software.

![soft3](https://user-images.githubusercontent.com/23245678/46247129-0f946a00-c407-11e8-8e6b-1e884a3e8e31.png)

Here is the screenshot of what happens if I click the .deb file after installation again, it still wants to install it, but it doesn't work

![sot2](https://user-images.githubusercontent.com/23245678/46247135-2dfa6580-c407-11e8-8816-92e7ea9ed057.png)

**Comment by saitam1** [comment]
Why do I get this error? Version 5.1. was installed after doubleclick on the .deb file. Have you changed the dependencies?

```
Setting up onlyoffice-documentserver (5.2.0-195) ...
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
dpkg: error processing package onlyoffice-documentserver (--configure):
 installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by ShockwaveNN** [comment]
@saitam1 does postgresql server is running?

**Comment by saitam1** [comment]
I have set up postgres as follows:
```
sudo -i -u postgres psql -c "CREATE DATABASE onlyoffice;"
sudo -i -u postgres psql -c "CREATE USER onlyoffice WITH password 'onlyoffice';"
sudo -i -u postgres psql -c "GRANT ALL privileges ON DATABASE onlyoffice TO onlyoffice;"
```
And I get anyway an authentication error:
```

psql: FATAL:  password authentication failed for user "onlyoffice"
FATAL:  password authentication failed for user "onlyoffice"
psql: FATAL:  password authentication failed for user "onlyoffice"
FATAL:  password authentication failed for user "onlyoffice"
dpkg: error processing package onlyoffice-documentserver (--configure):
 installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by ShockwaveNN** [comment]
@saitam1 try to manually login to postgres and check that `onlyoffice` user and password are correct

**Comment by ShockwaveNN** [comment]
@saitam1 also maybe you're inputted incorrect password in deb-conf window, try to reset it by https://serverfault.com/a/332490/98467

**Comment by saitam1** [comment]
```
sudo echo PURGE | debconf-communicate onlyoffice
debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied
0
```

**Comment by ShockwaveNN** [comment]
try
`sudo sh -c "echo PURGE | debconf-communicate onlyoffice"`

**Comment by saitam1** [comment]
```
sudo sh -c "echo PURGE | debconf-communicate onlyoffice"
0

```

**Comment by ShockwaveNN** [comment]
package name `onlyoffice-documentserver`, not `onlyoffice`

**Comment by saitam1** [comment]
```
sudo echo PURGE | debconf-communicate onlyoffice-documentserver
[sudo] password for johnjackson: debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied
```


```
sudo sh -c "echo PURGE | debconf-communicate onlyoffice-documentserver"
0

```

**Comment by ShockwaveNN** [comment]
@saitam1 so, does it helps? Does installation works?

**Comment by saitam1** [comment]
Unfortunately no

**Comment by ShockwaveNN** [comment]
@saitam1 try to connect to postgres using default credential manually

**Comment by saitam1** [comment]
No doesn't work.

**Comment by ShockwaveNN** [comment]
@saitam1 if you cannot connect to postgresql with default credits it's postgres configuration problem

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by str** [comment]
Same issue here, installation of 7.1 not working in ubuntu 22.04.

`psql onlyoffice --user=onlyoffice -h localhost` does work
