### ISSUE TITLE
Uninstall not possible: Error: connect ECONNREFUSED 127.0.0.1:5672

### ISSUE THREAD

**Issue by DreamFlasher** [ONLYOFFICE/DocumentServer#399]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`sudo apt remove onlyoffice-documentserver`
yields
```Removing onlyoffice-documentserver (5.1.5-59) ...
Preparing for shutdown, it can take a lot of time, please wait...[2018-10-06 06:43:55.493] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)```

**Comment by ShockwaveNN** [comment]
Seems RabbitMQ is stopped, you should start it or remove `postrm` like in this https://github.com/ONLYOFFICE/DocumentServer/issues/275#issuecomment-379657543 and retry

**Comment by DreamFlasher** [comment]
`/var/lib/dpkg/info/onlyoffice-documentserver-ie.postrm` as mentioned in the post does not exist, I removed `/var/lib/dpkg/info/onlyoffice-documentserver.postrm` -- but the error remains. How do I start RabbitMQ and why is it not started with a fresh installation of documentserver? (I was able to update onlyoffice documentserver, but it didn't properly install rabbitmq then. )

**Comment by ShockwaveNN** [comment]
>why is it not started with a fresh installation of documentserver
Maybe something in logs of RabbitMQ can help you

>but the error remains
Are you sure? Seems this is error from `/var/lib/dpkg/info/onlyoffice-documentserver.postrm`
`documentserver-prepare4shutdown.sh || true` line  and if you remove it - delete should continue

**Comment by DreamFlasher** [comment]
Yes, I am sure. I grep'ed for that line and for me it was in `/var/lib/dpkg/info/onlyoffice-documentserver.prerm`. Outcommenting allowed me to sucessfully remove documentserver. Solved, thank you!
