### ISSUE TITLE
What features can one use on the free version?

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/DocumentServer#40]
It's not clear what we can use for free on this new 4.0 version. I run the docker image and the Chat and Comments were there, but I'm not sure one can use it for free. Is the coauthoring still free like in the 3.x version?

**Comment by Dean13** [comment]
Hello,

Yes, the features you describe are totally free.

The only difference in document editing between the Enterprise and Free Edition are Mobile Apps which are not included in Free Edition.

The comparison of ONLYOFFICE Editions is available [http://www.onlyoffice.com/compare-server-editions.aspx](here)

**Comment by iwkse** [comment]
Such features are again removed from the open source version, starting from 4.2.3. I don't really understand what game do you play.
