### ISSUE TITLE
Browser Lag with Excel files

### ISSUE THREAD

**Issue by JulienGelmar** [ONLYOFFICE/DocumentServer#401]
Hey, I want to ask for some help with a strange issue I have with the CommunityServer

Right now, I have integrated OnlyOffice with a private website for file management and editing, DOCX and ODT files work fine and get saved like they should. 

But as soon as I open XLSX/ODS files, OnlyOffice is stuck in "Loading" and my whole browser lags (Firefox 62) and in Chrome the tab even crashes (Chrome 69).

This is the first Version of the DocumentServer that I am using, so I can't tell if it works on an older version. 

My DocumentServer version is 5.2.2-2 on Ubuntu 16.04.5 LTS, it's a DigitalOcean droplet with 2GB RAM and one vCPU.

Also, both the JS Console in the browsers and any out.log/error.log files contain no error message, other than saying the server is working.

**Comment by ShockwaveNN** [comment]
Is this a big files? Can you attach one?

**Comment by ShockwaveNN** [comment]
>it's a DigitalOcean droplet with 2GB RAM and one vCPU.
Do you get swap on this machine? It's need swap for sure

**Comment by ShockwaveNN** [comment]
I just checked DigitalOcean droplet with Ubuntu 18.04 and 2GB ram with 4GB swap
with `docker run -it -p 80:80 onlyoffice/documentserver-ie:5.2.2.2` it worked flawlessly with your file

**Comment by JulienGelmar** [comment]
Hello,

After creating a 4GB Swap it still seems to loop/crash my browser. 

We are using the variant without docker

**Comment by ShockwaveNN** [comment]
@JulienGelmar do you restart all services by `supervisorctl restart all` after creating swap
It it will not help - can you check your problem on another pc, this may be front-end issue, not server-side

**Comment by JulienGelmar** [comment]
After restarting all services and testing it on my colleague's PC, the issue seems to persist there too.

**Comment by JulienGelmar** [comment]
After redoing the front-end implementation the issue has been fixed, seems like it was my mistake. Sorry for the inconvenience and stealing your time :(

**Comment by ShockwaveNN** [comment]
@JulienGelmar no worry, glad to hear everything is fine
