### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by aborderon** [ONLYOFFICE/DocumentServer#402]
Hello,

I'm using Nextcloud 14 with the integration of OnlyOffice DocumentServer using docker.

However, I can not complete the integration in nextcloud because when I validate the installation since the administration of Nextcloud.

I get the following error message in the logs:

```
[2018-10-10 17: 58: 10.182] [ERROR] NodeJS - error downloadFile: url = https: //next.mydomain.fr/apps/onlyoffice/empty doc = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.Ua7cAUZ6v7q72VhTqsuIuH05VBZidgiuHhdeukZGgxQ; attempt = 1;? code: CERT_HAS_EXPIRED; connect: undefined; (id = conv_check_2041411610_docx)
onlyoffice-document-server | Error: certificate has expired
onlyoffice-document-server | at TLSSocket. <anonymous> (_tls_wrap.js: 1116: 38)
onlyoffice-document-server | at emitNone (events.js: 106: 13)
onlyoffice-document-server | at TLSSocket.emit (events.js: 208: 7)
onlyoffice-document-server | at TLSSocket._finishInit (_tls_wrap.js: 643: 8)
onlyoffice-document-server | at TLSWrap.ssl.onhandshakedone (_tls_wrap.js: 473: 38)
```

I understand the error message telling me that my certificate is expired however it is valid.

I tried to re-generate it and add it to `/app/onlyoffice/DocumentServer/data/certs/` but I get the same result.

Do you have an idea of ​​my problem?

Thank you.

**DocumentServer version:**
DocumentServer-5.2.2

**Operating System:**
Ubuntu 16.04

**Comment by ShockwaveNN** [comment]
Do you restart `nginx` (and perhabs all DocumentServer services) after replacing certificate?
Can you open main page of DocumentServer manually and make sure your browser do not complain about cert

**Comment by aborderon** [comment]
Yes I restarted all services.

I access the web page of OnlyOffice (see image) and all is ok, the certificate is present and valid.

www.office.mydomain.tlf in HTTPS
![image](https://user-images.githubusercontent.com/6728728/46823173-c8ef2a00-cd8d-11e8-95be-30c060aa12af.png)

**Comment by ShockwaveNN** [comment]
@aborderon so if I understand you right - DocumentServer running fine and your browser do not complain on DocumentServer certificate. If so - please close this issue and duplicate it in https://github.com/ONLYOFFICE/onlyoffice-nextcloud since seems this is nextcloud issue
