### ISSUE TITLE
How I can use actual theme?

### ISSUE THREAD

**Issue by dmitrydrynov** [ONLYOFFICE/DocumentServer#403]
Hi everyone,

I'm seeing this theme on your website
![image](https://user-images.githubusercontent.com/4089575/46770398-d1952100-ccf7-11e8-9ef2-f61e2702d8e3.png)

but on my document server i'm seeing old theme without tabs
![image](https://user-images.githubusercontent.com/4089575/46770419-f12c4980-ccf7-11e8-9e69-d217a2baffe4.png)

How I can update it?

![image](https://user-images.githubusercontent.com/4089575/46770451-1325cc00-ccf8-11e8-9d5e-afe70a5ccbc2.png)

**Comment by ShockwaveNN** [comment]
@dmitrydrynov Hi, as mentioned in https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions `Tabbed interface` not aviable in `Community Edition`, only in `Integration Edition` or `Developer Edition`

I'm closing this issue but feel free to ask any question about it.

**Comment by sharq88** [comment]
I have enrolled the 30 days trial for developer edition - installed via docker: 
![image](https://user-images.githubusercontent.com/2893497/46957960-a8c2b200-d090-11e8-8688-289e9cede84f.png)
If I run that - It gives the "Integration edition" logo
![image](https://user-images.githubusercontent.com/2893497/46958047-d7408d00-d090-11e8-9c7a-643599d0b8a8.png)
If I upload a document and open it - it gives me (CE) Community Edition? 
![image](https://user-images.githubusercontent.com/2893497/46958153-0eaf3980-d091-11e8-8586-ef41f901d8ec.png)

**Comment by ShockwaveNN** [comment]
@sharq88 I think there is some mixup in your network or local services (like you've already installed standalone DocumentServer version before docker).
I checked by `docker run -it -p 80:80 onlyoffice/documentserver-de:latest` and got my server correct
![image](https://user-images.githubusercontent.com/668524/46958792-4de68600-d0a3-11e8-936f-206aae9ea9fd.png)

**Comment by sharq88** [comment]
@ShockwaveNN thank you - that worked! I can see the same as you now.
