### ISSUE TITLE
Send token over Document Server to our application

### ISSUE THREAD

**Issue by mervekaya** [ONLYOFFICE/DocumentServer#405]
Hello,
We think use only office our project but we encounter with one problem. In our project, there is a token and with this token we call endpoints in the project. How can we send token via Document server ? Firstly we think add token end of the callBackUrl as a request parameter but this is not secure and faced with problems. Is there a different way ?

**Comment by alexanderonlyoffice** [comment]
@mervekaya, no, unfortunately, there is no way to use your token. The only way is to use Document Server JWT token in your service and in Document Server. More information about JWT token you can find [here](https://api.onlyoffice.com/editors/security).

**Comment by mervekaya** [comment]
Thank you for reply. So how can we see document server token ? Can we log anywhere ? We try to see from browser developer tool and  HttpRequest which is send by callBackUrl but we can not see token in header or anywhere ?

**Comment by alexanderonlyoffice** [comment]
@mervekaya, please follow this [link](https://api.onlyoffice.com/editors/security) to find more information about JWT in Document Server. **IMPORTANT:** Please note that since the version 5.2 of the Document Server JWT is enabled in local.json, which is placed in /etc/onlyoffice/documentserver/ (for deb/rpm installations). API documentation is not updated yet.

**Comment by mervekaya** [comment]
Thank you for response. Could we not embed our token as a Authorization Bearer in Document Server JWT ? I read all documentation about Document Server JWT but we want to use our token to authenticate user who log in our system via callbackUrl. I try document server JWT token but this token can not send our token. It send payload and actions. When this token come our system via callbackUrl our system send a exception that _Failed to verify token_ also Document Server send a exception that : 

`{"timestamp":1539868356270,"status":401,"error":"Unauthorized","message":"Unable to authenticate using the Authorization header","path":"/wopi/onlyOffice"}`

at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

I look into utils.js in this javascript code there is a function
 `postRequestPromise(uri, postData, optTimeout, opt_Authorization)`

when i give our token in header like that:

`    var headers = {'Content-Type': 'application/json', 'Authorization' : 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6bjVfZmxxQjJ2QVFiRjBIZlI3S3FVbWJ2dHh4cUVaZnRJT3JEU0cxVVhzIn0.eyJqdGkiOiJlYjdjNWE2NC1iODU0LTRjOTMtODc3Yy0wY2JjYThkZmEwYjYiLCJleHAiOjE1Mzk4Njc5NTgsIm5iZiI6MCwiaWF0IjoxNTM5ODY3NjU4LCJpc3MiOiJodHRwOi8vMTAuMS44MS4xNTg6ODA4MC9hdXRoL3JlYWxtcy9TYWZpckRlcG8iLCJhdWQiOiJzYWZpcmRlcG8tZnJvbnRlbmQtZGV2Iiwic3ViIjoiNzkzYTZlNTktZTA3Ni00YWJm......'};`

then our system is work fine. So i need to give my token dynamically this function. Should i have to change source code like that (if so who call this function in utils.js ) or there is a another way ?

**Comment by falling-star** [comment]
@alexanderonlyoffice Document server version - 5.1.5 has modified JWT default.json settings format but https://api.onlyoffice.com/editors/signature/ doesn't have the updated documentation. 

**Issue** - Not getting signed token in the callbackurl API body from Editing Service to Storage Service after enabling it ?
Please find attached default.json screenshot. Let me know what I need to do in this case.

<img width="1411" alt="screenshot 2018-12-07 at 2 28 55 pm" src="https://user-images.githubusercontent.com/3634908/49639422-f9bbaa80-fa30-11e8-9d25-ead4e1ad17a0.png">

**Comment by falling-star** [comment]
@alexanderonlyoffice got it working. missed the 'inBody' outbox option in config. (by default, It will be present in request headers)

**Comment by konovalovsergey** [comment]
if I understand correctly, external token is different for each user and is used for authorization in a third-party system.
the only way to do this is to add it to callBackUrl (possibly encrypted)
I do not know of example where you can transfer token without a browser. for example, WOPI protocol passes the `access_token `through the browser

**Comment by alexanderonlyoffice** [comment]
@mervekaya, it is required to create a separate option of authorization to ensure that the usual token is not sent to the Document Server in unsecure way. 

It is possible to specify a separate token within the callback parameters and this token will be identified only by callback handler. These parameters can be specified in callbackUrl indicated by the integrator in editorConfig When a request is received one needs to verify JWT signature at first to make sure this request came from the Document Server and then verify the above mentioned token.

**Comment by ShockwaveNN** [comment]
I think I'll close this issue, because there is several not directly related questions in this thread

But feel free to comment or create new issue if still got troubles
