### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by TooMuchRAM** [ONLYOFFICE/DocumentServer#408]
Hello,
I'd like to report what I believe to be a bug.
In the webeditors, I can't change the language I'm currently working in. The option is disabled:
![image](https://user-images.githubusercontent.com/39091235/47042994-d5f48a80-d18c-11e8-936d-b6c6c957335a.png)
It was just disabled one day, I have no idea how that happened. It worked previously. I don't remember I updated it before it broke.
DocumentServer version: 5.2.2-2
Operating System: CentOS 7
Browser version: Firefox 62.0.3

It's not a big issue, but it's bothering me.
Also, when I forcibly enable the button, it doesn't open the dropdown when I click it.

**Comment by ShockwaveNN** [comment]
Please fill issue template correctly https://github.com/ONLYOFFICE/DocumentServer/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by TooMuchRAM** [comment]
I have edited it to reflect your needs.

**Comment by ShockwaveNN** [comment]
@TooMuchRAM please check spellcheker log at `/var/log/onlyoffice/documentserver/spellchecker/out.log` for any issues?

**Comment by TooMuchRAM** [comment]
I think something went wrong...
![image](https://user-images.githubusercontent.com/39091235/47156691-f2590a00-d2e7-11e8-87e6-420861b3dde6.png)

**Comment by ShockwaveNN** [comment]
What version of nodejs you're using? DocumentServer 5.2 require nodejs 8

**Comment by TooMuchRAM** [comment]
I see the problem. I'm now updating Node to version 8.

**Comment by TooMuchRAM** [comment]
Updating node did the trick. Thank you for you support.
