### ISSUE TITLE
Problem with absolute reference when inserting a new row

### ISSUE THREAD

**Issue by StefanHauer** [ONLYOFFICE/DocumentServer#41]
When I reference, say cell A1, by using the command $A$1, and I add a row on top, it will now reference the empty cell A1 and not A2 with the information I want to reference, as one would expect coming from excel.
I use Chrome (Version 51.0.2704.103 m) as my Browser and the problem happened using ONLYOFFICE Version 8.9.0.150.

Is there a way to circumvent this problem, maybe by using a diffferent command for absolute references?

**Comment by trofim24** [comment]
Please give a more detailed scenario of the problem.
For example:
- enter a formula in cell A10 `=$A$1`
- enter in cell A1 number `1`
- insert a row before row 1 or before the row 5

We have tried to replicate the problem on version DocumentServer 4.0.1. But we could not.
We would be grateful for additional information.

**Comment by StefanHauer** [comment]
Thank you for the fast answer.
I am attaching a file for better understanding of my problem.
If I upload the attached file my created names in column "C" say: Step1_Substep1, Step1_Substep2, etc.
However, if I were to insert a row on top of, for instance row 3, something weird happens: While the names for Step1 read out as intended, the names for Step2 now are "_Substep1" etc. instead of "Step2_Substep1" etc.
Furthermore the names for Substep1 and Substep3 of Step3 are shown as intended, while for Substep2 again only "_Substep2" is displayed instead of "Step3_Substep2".

[OnlyOffice_Bug_File.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/396353/OnlyOffice_Bug_File.xlsx)

**Comment by trofim24** [comment]
Thank you. All exactly as you describe.
We will fix that.

**Comment by StefanHauer** [comment]
Great!
Thanks for your help and your fast answers!
