### ISSUE TITLE
DocumentServer 5.2 on nodejs can be installed with nodejs 6

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#410]
**What is the current behavior?**
1. Install DocumentServer 5.2.2 on Centos 7 by [instruction](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx), but replace step
`curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -`
on `curl -sL https://rpm.nodesource.com/setup_6.x | sudo bash -`

**What is the expected behavior?**
DocumentServer should not be installed since https://github.com/ONLYOFFICE/document-server-package/blob/master/rpm/requires.spec
require `nodejs >= 8.0.0`

**What is the actual behavior?**
DocmentServer ignore this requirement
In result spellchecker not working with 
```
Error: Module version mismatch. Expected 48, got 57.
```

This can be fixed by manual update of nodejs to 8

**Did this work in previous versions of DocumentServer?**
DocumentServer 5.1 and earlier require nodejs 6

**DocumentServer version:** 5.2.2

**Operating System:** Centos 7

**Comment by sergiomb2** [comment]
Thank you it worked for me , after upgrade to onlyoffice-documentserver-5.4.0-21.x86_64 it just work with upgrade of nodejs (nodejs-8.16.1-1nodesource.x86_64)

After check /etc/supervisord.d/ds-spellchecker.ini , /var/log/onlyoffice/documentserver/spellchecker/err.log 
and google for [1] I found this solution from [2] (Russian)

[1]
module.js:604 return process.dlopen(module, path._makeLong(filename)); ^ Error: Module version mismatch. Expected 48, got 57

[2]
https://dev.onlyoffice.org/ru/viewtopic.php?f=34&t=16830

**Comment by ShockwaveNN** [comment]
`nodejs` is not required for DocumentServer since 5.5.0. Closing this issue
