### ISSUE TITLE
YOURE HAVE BROKEN MY SERVER

### ISSUE THREAD

**Issue by StevenGeiloo** [ONLYOFFICE/DocumentServer#411]
Removing onlyoffice-documentserver (5.2.2-2) ...
dpkg: error processing package onlyoffice-documentserver (--remove):
 subprocess installed post-removal script returned error exit status 127
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ShockwaveNN** [comment]
Is there any errors in `/var/log/onlyoffice/documentserver`?

**Comment by StevenGeiloo** [comment]
No. The directory doesnt exists because i didnt installed the server because its need nginx and postgreesql. And i tried many of commands to uninstall the server.

**Comment by ShockwaveNN** [comment]
@StevenGeiloo try this
https://github.com/ONLYOFFICE/DocumentServer/issues/404#issuecomment-428872197

**Comment by StevenGeiloo** [comment]
@ShockwaveNN 
i have already tried that. but same error.

**Comment by ShockwaveNN** [comment]
@StevenGeiloo try `rm /var/lib/dpkg/info/onlyoffice-documentserver.prerm`
If this will not help
show me output of 
`ls -la /var/lib/dpkg/info/onlyoffice-documentserver*`

**Comment by StevenGeiloo** [comment]
@ShockwaveNN 
i triet the command but same error.
output of the command:
```
-rw-r--r-- 1 root root    1479 Oct  4 12:42 /var/lib/dpkg/info/onlyoffice-documentserver.conffiles
-rwxr-xr-x 1 root root     991 Oct  4 12:42 /var/lib/dpkg/info/onlyoffice-documentserver.config
-rw-r--r-- 1 root root    1735 Oct 19 16:59 /var/lib/dpkg/info/onlyoffice-documentserver.list
-rw-r--r-- 1 root root 1678629 Oct  4 12:43 /var/lib/dpkg/info/onlyoffice-documentserver.md5sums
-rwxr-xr-x 1 root root    9678 Oct  4 12:42 /var/lib/dpkg/info/onlyoffice-documentserver.postinst
-rwxr-xr-x 1 root root    2799 Oct  4 12:42 /var/lib/dpkg/info/onlyoffice-documentserver.postrm
-rw-r--r-- 1 root root      78 Oct  4 12:42 /var/lib/dpkg/info/onlyoffice-documentserver.shlibs
-rw-r--r-- 1 root root    1898 Oct  4 12:24 /var/lib/dpkg/info/onlyoffice-documentserver.templates
```

**Comment by ShockwaveNN** [comment]
@StevenGeiloo you said you've tried https://github.com/ONLYOFFICE/DocumentServer/issues/404#issuecomment-428872197
`rm /var/lib/dpkg/info/onlyoffice-documentserver.postrm` but I see this file in command output.

**Comment by StevenGeiloo** [comment]
@ShockwaveNN 
The file will be deleted and then i have tried ´´´ sudo apt-get upgrade ´´´ to remove the server.
But the second try works. Thank you very much!

**Comment by ShockwaveNN** [comment]
@StevenGeiloo good to hear, I'm closing this issue
