### ISSUE TITLE
OnlyOffice integration in Nextcloud only works internal

### ISSUE THREAD

**Issue by hattabatatta** [ONLYOFFICE/DocumentServer#412]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
Onlyoffice only working when i am in LAN

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Installed OnlyOffice Documentserver on CentOS7 (192.168.1.199. Installed NextCloud 14 on other CentOS7 (192.168.1.198)
Nextcloud is available from outside my lan and has a letsencrypt cert.
OnlyOffice is only available by its IP and has a self signed cert.
OnlyOffice also is automatically redirected to https.

I added https://192.168.1.199 within the OnlyOffice plugin in NextCloud. Connection works and i can use OnlyOffice as document editor within NextCloud.
If i am connecting from the outside to my NextCloud the cloud itself is working but when i try to open a document it loads like for hours during a white screen, and then the message "ONLYOFFICE cannot be reached. Please contact admin" occurs.

I added the following to the nextcloud config:
'onlyoffice' => 
  array ( 
       'verify_peer_off' =>TRUE, 
  ),
Nothing changed.

I also tried to set "rejectUnauthorized" to false within /etc/onlyoffice/documentserver/default.json
Nothing changed.

What did i do wrong?

**Comment by drebs** [comment]
The onlyoffice instance [must be accessible by the web browser](https://github.com/ONLYOFFICE/onlyoffice-owncloud#configuring-owncloud-onlyoffice-integration-app).

**Comment by hattabatatta** [comment]
It is
<img width="1292" alt="bildschirmfoto 2018-10-23 um 06 30 20" src="https://user-images.githubusercontent.com/15610023/47335827-5172a200-d68d-11e8-8a97-37f5ea70648c.png">

**Comment by hattabatatta** [comment]
I deleted this crappy environment and switched to docker image ... same problem there, but might be "easier" to fix
