### ISSUE TITLE
emf Image in docx is displayed partially incorrect

### ISSUE THREAD

**Issue by mishka88ru** [ONLYOFFICE/DocumentServer#413]
Hi :)
I was asked to duplicate [this](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/20) issue here.

Here is the screenshot from OnlyOffice (5.2.2) Docker on Nextcloud (left) and MS Word 2010 (right):

![1](https://user-images.githubusercontent.com/44462629/47631481-4a4d0780-db57-11e8-92a9-dbe8eb766da1.png)

And the document:
[1.docx](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/files/2524019/1.docx)

Browser:
Firefox 61.0.1 and Chrome 68.0.3440.106

**Comment by HellRoad** [comment]
Hi 
This is a known  bug, but i'm not sure what will be fixed soon. issue 35023
Thanks for your feedback.

**Comment by Rita-Bubnova** [comment]
We checked this bug in ONLYOFFICE Document Server version 8.0 and I confirm - it was fixed. 
Sorry, we forgot to mention that issue was fixed.

I close this issue. Feel free to comment or reopen it if you got further questions.
