### ISSUE TITLE
Question: Can part of a Word document be marked as "Read Only" inside OnlyOffice web editor?

### ISSUE THREAD

**Issue by wshi88** [ONLYOFFICE/DocumentServer#417]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
How can I mark part of a Word document as "read only" and doesn't allow user to edit/delete? 
For example, I don't want to allow user to change the headline of a paragraph, the headline is marked "read only".

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
Latest web document editor

**Operating System:**
WIndows 10

**Browser version:**
Latest version of Chrome

**Comment by ShockwaveNN** [comment]
You can use forms for allow users to change parts in read-only document.
https://api.onlyoffice.com/editors/config/document/permissions#fillForms

We are not planning to implement some more advanced permission system for access control of part of documents in near future

**Comment by ShockwaveNN** [comment]
@ar27111994 If I'm not mistaken - it use fully custom Javascript framework

**Comment by ar27111994** [comment]
if its ok for you, can you please point me to some resource(s) which can help me get started? I'm currently building document server on my machine )

**Comment by ShockwaveNN** [comment]
@ar27111994 all info we got should be on api.onlyoffice.com and build instruction at https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx
