### ISSUE TITLE
Ability to change autosave timeout

### ISSUE THREAD

**Issue by jeyca** [ONLYOFFICE/DocumentServer#420]
Currently it is possible to turn the AutoSave on or off, but is there also any option from UX to change the time after a document is autosaved?

**Comment by evgenykatyshev** [comment]
Hello. What is reason why you want to set timeout before autosaving? Is not the best option when document saves to cloud as fast as possible?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
