### ISSUE TITLE
DEBIAN : onlyoffice documentserver stop every day, how to restart

### ISSUE THREAD

**Issue by Bschalck** [ONLYOFFICE/DocumentServer#422]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Th onlyoffice documentserver stop every dayt at ~ 7:30 am.
A _**ps -eaf|grep only** only shows rabbitmq process

The only command who can restart it it **dpkg-recongure onlyoffice-documentserver**

Can you suggest a command to restart it properly ( which can be done by crontab )  without dpkg commands ? 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Restart onlyoffice-documentserver automatically
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer version:**
5.2.3

**Operating System:**
Debian 8.11 64bits

**Browser version:**

**Comment by Bschalck** [comment]
Here is the logs in /var/log/onlyoffice/documentserver/nginx.error.log

`2018/11/07 23:11:59 [crit] 31912#0: *1942 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 142.93.170.37, server: 0.0.0.0:8080                                                                                                                                   
2018/11/08 07:40:03 [error] 31912#0: *2989 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.254, server: onlyoffice.devloprog.org, request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "onlyoffice.devloprog.org:8080"    `

**Comment by ShockwaveNN** [comment]
@Bschalck is there is any other error in other files?

**Comment by Bschalck** [comment]
From file  : spellchecker/err.log

`Error: The module '/home/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node'                                               
was compiled against a different Node.js version using                                                                                                                
NODE_MODULE_VERSION 57. This version of Node.js requires                                                                                                              
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing                                                                                                      
the module (for instance, using `npm rebuild` or `npm install`).                                                                                                      
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)                                                                                        
    at Module.load (internal/modules/cjs/loader.js:598:32)                                                                                                            
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)                                                                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)                                                                                                   
    at Module.require (internal/modules/cjs/loader.js:636:17)                                                                                                         
    at require (internal/modules/cjs/helpers.js:20:18)                                                                                                                
    at Object.<anonymous> (/home/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)                                                           
    at Module._compile (internal/modules/cjs/loader.js:688:30)                                                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)                                                                                          
    at Module.load (internal/modules/cjs/loader.js:598:32)                                                                                                            
internal/modules/cjs/loader.js:717                                                                                                                                    
  return process.dlopen(module, path.toNamespacedPath(filename));                                                                                                     
                 ^                                                                                                                                                    

Error: The module '/home/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node'                                               
was compiled against a different Node.js version using                                                                                                                
NODE_MODULE_VERSION 57. This version of Node.js requires                                                                                                              
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing                                                                                                      
the module (for instance, using `npm rebuild` or `npm install`).                                                                                                      
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)                                                                                        
    at Module.load (internal/modules/cjs/loader.js:598:32)                                                                                                            
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)                                                                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)                                                                                                   
    at Module.require (internal/modules/cjs/loader.js:636:17)                                                                                                         
    at require (internal/modules/cjs/helpers.js:20:18)                                                                                                                
    at Object.<anonymous> (/home/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)                                                           
    at Module._compile (internal/modules/cjs/loader.js:688:30)                                                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)                                                                                          
    at Module.load (internal/modules/cjs/loader.js:598:32)                                       `

**Comment by ShockwaveNN** [comment]
@Bschalck Not sure this is a reason of restarts, but anyway this is not right, you should upgrade to nodejs 8, since it required by latest DocumentServer

**Comment by Bschalck** [comment]
Well, as I understand, The nodejs version on my server is **10.13.0-1** ( from dpkg -l command ) ....

**Comment by ShockwaveNN** [comment]
@Bschalck oh, you can track issue https://github.com/ONLYOFFICE/DocumentServer/issues/304 about support of nodejs 10, currenlty it is not supported.
If you can - you should downgrade to nodejs 8, and see if your restarts are gone.

**Comment by Bschalck** [comment]
Unfortunetly, I ca not downgrade the nodejs version.
While nodejs 10 is not supported, which command can I use to start onlyoffice-docuementserver in crontab ? 
This one could work  ? 
`su - onlyoffice /usr/bin/node /var/www/onlyoffice/documentserver/server/SpellChecker/sources/server.js`

**Comment by Bschalck** [comment]
In fact,  it doesn't work also via shell  :(

**Comment by ShockwaveNN** [comment]
@Bschalck what is the error?

**Comment by Bschalck** [comment]
well , I will tell you tomorrow on next crash ;)

**Comment by ShockwaveNN** [comment]
@Bschalck Do you have enought memory on your server? 
I can't thought of any reason why DocumentServer will crash  just once a day at same time.

**Comment by Bschalck** [comment]
I think so :) In fact, my server run since few months without any problems, that' why I made this issue .

**Comment by ShockwaveNN** [comment]
@Bschalck this is strange, maybe it's somehow related to upgrade to DocumentServer to 5.2.0, which change requirements from nodejs 6 to nodejs 8. DocumentServer 5.2.0 was released on 28 september of 2018

**Comment by Bschalck** [comment]
I change nodejs from v10 to v8 . I will tell you tomorrow if this change resolves the problem.

**Comment by Bschalck** [comment]
The error is still here.

When I try to restart , I got this : 
`<root@onlyoffice-Debian jessie/8.11> /root $  supervisorctl start all
unix:///var/run/supervisor.sock no such file
`

**Comment by Bschalck** [comment]
Still same error : 
`2018/11/12 21:39:01 [error] 7250#0: *1613 open() "/var/www/onlyoffice/documentse
rver/fonts/072" failed (2: No such file or directory), client: 83.152.170.41, se
rver: onlyoffice.devloprog.org, request: "GET /v5.2.3-64//fonts/072 HTTP/1.1", h
ost: "onlyoffice.devloprog.org:8080"
2018/11/13 07:40:02 [error] 7248#0: *2933 connect() failed (111: Connection refu
sed) while connecting to upstream, client: 192.168.0.254, server: onlyoffice.dev
loprog.org, request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welc
ome/", host: "onlyoffice.devloprog.org:8080"
`

**Comment by Bschalck** [comment]
And the onlyoffice process when it starts after dpkg-reconfigure onlyoffice :

```
<root@onlyoffice-Debian jessie/8.11> /root $ dpkg-reconfigure onlyoffice-documentserver                                                                                     
Preparing for shutdown, it can take a lot of time, please wait...Done
Generating AllFonts.js, please wait...Done
Congratulations, the ONLYOFFICE DocumentServer has been installed successfully!
Traitement des actions différées (« triggers ») pour libc-bin (2.19-18+deb8u10)                                                                                         ...
 
<root@onlyoffice-Debian jessie/8.11> /root $ ps -eaf|grep only
avahi      535     1  0 nov.04 ?       00:00:13 avahi-daemon: running [onlyoffice.local]
rabbitmq  1393  1333  0 nov.04 ?       00:23:18 /usr/lib/erlang/erts-6.2/bin/beam.smp -W w -K true -A30 -P 1048576 -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.3.5/sbin/../ebin -noshell -noinput -s rabbit boot -sname rabbit@onlyoffice -boot start_sasl -kernel inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/var/log/rabbitmq/rabbit@onlyoffice.log"} -rabbit sasl_error_logger {file,"/var/log/rabbitmq/rabbit@onlyoffice-sasl.log"} -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/lib/rabbitmq_server-3.3.5/sbin/../plugins" -rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@onlyoffice-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@onlyoffice" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
onlyoff+ 11140 11128  0 07:55 ?        00:00:00 node /var/www/onlyoffice/documentserver/server/SpellChecker/sources/server.js
onlyoff+ 11141 11128  4 07:55 ?        00:00:01 node /var/www/onlyoffice/documentserver/server/DocService/sources/gc.js
onlyoff+ 11142 11128  2 07:55 ?        00:00:00 node --max_old_space_size=4096 /var/www/onlyoffice/documentserver/server/DocService/sources/server.js
onlyoff+ 11143 11128  2 07:55 ?        00:00:00 node --max_old_space_size=4096 /var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js
onlyoff+ 11188 11140  3 07:55 ?        00:00:00 /usr/bin/node /var/www/onlyoffice/documentserver/server/SpellChecker/sources/server.js
onlyoff+ 11206 11142  5 07:55 ?        00:00:01 /usr/bin/node --max_old_space_size=4096 /var/www/onlyoffice/documentserver/server/DocService/sources/server.js
onlyoff+ 11217 11143  3 07:55 ?        00:00:00 /usr/bin/node --max_old_space_size=4096 /var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js
postgres 11234   758  0 07:55 ?        00:00:00 postgres: onlyoffice onlyoffice 127.0.0.1(33994) idle                                                                   
postgres 11241   758  0 07:55 ?        00:00:00 postgres: onlyoffice onlyoffice 127.0.0.1(33996) idle                                                                   
postgres 11251   758  0 07:55 ?        00:00:00 postgres: onlyoffice onlyoffice 127.0.0.1(33998) idle                                                                   
root     11306  9992  0 07:56 pts/7    00:00:00 grep only
```

**Comment by ShockwaveNN** [comment]
> ```supervisorctl start all unix:///var/run/supervisor.sock no such file```

This is not right
I remember we got such error but long time ago and seems this was fixed it newer version of supervisor fixed it if I recall correctly.

Does any `supervisorctl` command cause this error? What is the version of `supervisor` package

**Comment by ShockwaveNN** [comment]
@Bschalck if I recall correctly `/var/run/supervisor.sock no such file` is actual for supervisor < 3.2
It can be fixed by https://github.com/Supervisor/supervisor/issues/480#issuecomment-110429515

Or if you upgrade to newer one supervisor it should work (on Ubuntu it is `3.2.0-2ubuntu0.2`)

**Comment by Bschalck** [comment]
Thanks for the hint :)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
