### ISSUE TITLE
[Feature Request] Ability to sort spreadsheet by multiple columns

### ISSUE THREAD

**Issue by bhotrock** [ONLYOFFICE/DocumentServer#423]
We are not able to use OnlyOffice for certain spreadsheets that require the ability to sort on multiple columns.  This is a feature of MS Excel and Google Sheets.

This feature was also requested in the comments to the article:
11 Things You Can Do with ONLYOFFICE, But Can’t With Google Docs or MS Word Online

Thanks for your consideration!

**Comment by Rita-Bubnova** [comment]
Hello, @bhotrock.
Thank you for your enhancement.
I created a new issue 39675 in our private issue tracker.
We will discuss this with our team.

**Comment by trofim24** [comment]
We released this in [version 5.5.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#550)
