### ISSUE TITLE
How to compare the differences between two documents? 

### ISSUE THREAD

**Issue by jimmygan** [ONLYOFFICE/DocumentServer#428]
**Do you want to request a *feature* or report a *bug*?**
Question
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

How to compare the differences between two documents? It just like "document comparison" in Microsoft Office Word.

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
Latest web document editor

**Operating System:**
Windows 10

**Browser version:**
Latest version of Chrome

**Comment by Rita-Bubnova** [comment]
Hello, @jimmygan.
Thank you for your enhancement.
I created a new issue 39702 in our private issue tracker.
We will discuss this with our team.

**Comment by zbird** [comment]
we also need this feature, is there any plan for this feature?

**Comment by Rita-Bubnova** [comment]
Hello, @zbird.
Sorry, there is no ETA for this problem.

**Comment by zbird** [comment]
@Rita-Bubnova thanks for you reply, i think diff tow docs is a big feature, hope for your solutions like Draftable.com does

**Comment by Medanna** [comment]
Hello @jimmygan @zbird glad to announce, that the desired feature has been designed and is in progress of implementation now.

**Comment by zbird** [comment]
Thank you for your information,  hope for this feature！-------- 原始邮件 --------主题：Re: [ONLYOFFICE/DocumentServer] How to compare the differences between two documents?  (#428)发件人：Anna Medvedeva 收件人：ONLYOFFICE/DocumentServer 抄送：zbird ,Mention Hello @jimmygan @zbird glad to announce, that the desired feature has been designed and is in progress of implementation now.

**Comment by dirschmi** [comment]
Hi Team,
is there already a ETA?

Thanks Dirk

**Comment by trofim24** [comment]
We released Comparing documents in [version 5.5](https://www.onlyoffice.com/blog/2020/03/compare-documents-in-onlyoffice-5-5/), but it avaliable only in Enterprise Edition and Developer Edition
