### ISSUE TITLE
Facing issue with Document Builder

### ISSUE THREAD

**Issue by Anupam750** [ONLYOFFICE/DocumentServer#430]
I am working on .Net and trying to build word editor but when i am uploading docuement and its keep running. 

Please check it and let me know for the same.

![image](https://user-images.githubusercontent.com/5477380/48619381-509a0b00-e9c2-11e8-9ecc-0afcd8bc07b1.png)

**Comment by ShockwaveNN** [comment]
@Anupam750 Hi, what is server side logs and javascript console logs

**Comment by Anupam750** [comment]
Please find the below screen shot for the same as i am getting these errors. there is no error on server side.


![image](https://user-images.githubusercontent.com/5477380/48703760-c26c9180-ec1a-11e8-81f2-53e7d30dfcc2.png)

**Comment by Anupam750** [comment]
It is existing in our app which i have downloaded from repo




![image](https://user-images.githubusercontent.com/5477380/48704439-8afee480-ec1c-11e8-9c38-aad7ea376f24.png)

**Comment by ShockwaveNN** [comment]
@Anupam750 my question is still actual, please note version of DocumentServer and other details (like host os), without it I cannot help it

**Comment by Anupam750** [comment]
when i am installing then getting this error, Please check this also


![image](https://user-images.githubusercontent.com/5477380/48819071-19d24500-ed74-11e8-8066-fcbb8cd50836.png)

**Comment by ShockwaveNN** [comment]
@Anupam750 Onlyoffice Community Edition do not support Windows 10
![image](https://user-images.githubusercontent.com/668524/48825772-7b48e280-ed79-11e8-95f5-018c33c9377b.png)
https://www.onlyoffice.com/download.aspx
See requirements here
Also I don't fully understand how you trying to install Onlyoffice Community Edition only now, if you tried c# integration example, but didn't install DocumentServer components before

**Comment by Anupam750** [comment]
I have installed it but i am still getting the same issue.. 

![image](https://user-images.githubusercontent.com/5477380/48895215-8f204180-ee6a-11e8-8749-73177b7dc23b.png)

**Comment by ShockwaveNN** [comment]
@Anupam750 you still didn't give me information about DocumentServer version

**Comment by Anupam750** [comment]
document server version v5.2

**Comment by ShockwaveNN** [comment]
`AllFonts.js` should not show any error on first line of JS Console logs
Could you zip log folder C:\Program Files\ONLYOFFICE\DocumentServer\Log and attach to issue

**Comment by Anupam750** [comment]
it is not allowing me to upload zip file

**Comment by ShockwaveNN** [comment]
@Anupam750 Strange, github allow me to upload zip files. Upload it to any cloud drive then.

**Comment by Anupam750** [comment]
ok, I uploaded logs on google drive, Please check this link 
https://drive.google.com/open?id=1lUP3tszmEXO6M9Z6lrIB2Zf84D07mIko

**Comment by ShockwaveNN** [comment]
[Docuemnt Server Logs.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2607918/Docuemnt.Server.Logs.zip)
Attached your logs here

Your DocumentServer cannot connect to redis server. Please make sure you use correct version and can find some more info at https://github.com/ONLYOFFICE/DocumentServer/issues/433

**Comment by Anupam750** [comment]
I did some changes in code and now it is giving error related to "sockjs.min.js" is not found but it exist in document server.






![image](https://user-images.githubusercontent.com/5477380/48929985-56887280-ef13-11e8-95c9-073a1498c3a6.png)

**Comment by ShockwaveNN** [comment]
@Anupam750 something still not right, do you fix redis errors?

**Comment by Anupam750** [comment]
Yes, I think, after some time  it is showing like this

![image](https://user-images.githubusercontent.com/5477380/48935389-92303600-ef2d-11e8-8e6c-7259db2e50c7.png)

**Comment by ShockwaveNN** [comment]
@Anupam750 logs?

**Comment by Anupam750** [comment]
https://drive.google.com/open?id=1HyXv3IXSU6LdIPbH51I62SaAM6F_yHiA

**Comment by ShockwaveNN** [comment]
@Anupam750 if you archive logs to zip, not to rar you will be able to attach it to github

**Comment by ShockwaveNN** [comment]
@Anupam750 according to logs you didn't fix Redis error

**Comment by Anupam750** [comment]
Please check now

[Log.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2610266/Log.zip)

**Comment by ShockwaveNN** [comment]
@Anupam750 still redis, you can see errors at `docservice/out.log`, until you fix them -DocumentServer will not work

**Comment by Anupam750** [comment]
ok

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
