### ISSUE TITLE
Bug : Document cannot open

### ISSUE THREAD

**Issue by mervekaya** [ONLYOFFICE/DocumentServer#432]
Hello,

I install Document server on Ubuntu  16.04 and when i try to open ppt file it gives this error and cannot open document : 

![screenshot from 2018-11-19 16-21-58](https://user-images.githubusercontent.com/6431301/48710348-0a8ab480-ec19-11e8-8ce4-03b62ea5ba69.png)

What should i do ?

**Comment by ShockwaveNN** [comment]
@mervekaya Hi, do you use DocumentServer example or Nextcloud or some other document management system. Also please add info about DocumentServer version and host\client OS

**Comment by mervekaya** [comment]
No i don use Document Server  example or Nextcloud. I only install document server on Ubuntu 16.04 with this commands 

> sudo apt update
> 
> sudo apt upgrade
> 
> curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
> 
> sudo apt-get install postgresql
> 
> sudo -i -u postgres psql -c "CREATE DATABASE onlyoffice;"
> 
> sudo -i -u postgres psql -c "CREATE USER onlyoffice WITH password 'onlyoffice';"
> 
> sudo -i -u postgres psql -c "GRANT ALL privileges ON DATABASE onlyoffice TO onlyoffice;"
> 
> sudo apt-get install redis-server
> 
> sudo apt-get install rabbitmq-server
> 
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
> 
> sudo echo "deb http://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list
> 
> sudo apt-get update
> 
> sudo apt-get install onlyoffice-documentserver

After that, i open html file and write these script 

```
<div id="placeholder"></div>
<script type="text/javascript" src="http://172.16.80.28:80/web-apps/apps/api/documents/api.js"></script>
<script>
new DocsAPI.DocEditor("placeholder", {
    "document": {
        "fileType": "ppt",
        "key": "a8d64ce6-45c3-4a6b-bb73-6fc6a6232eca10",
        "title": "13-Using_Powerpoint.ppt",
        "url": "http://localhost:3000/downloads/downloadId"
    },
    "documentType": "presentation",
    "editorConfig": {
        "callbackUrl": "localhost:3000/wopi/onlyOffice"
    }
});


</script>
```

Then i try to open this html file on browser and i encounter with this pop up. File cannot open .

![screenshot from 2018-11-19 16-21-58](https://user-images.githubusercontent.com/6431301/48761882-cc45d180-ecba-11e8-9529-508943a9b811.png)

**Comment by ibnpetr** [comment]
@mervekaya Every time you are going to start a new editing session you need to use a new [document.key](https://api.onlyoffice.com/editors/config/document#key) 
For more details, please follow the [link](https://api.onlyoffice.com/editors/troubleshooting#key)

**Comment by mervekaya** [comment]
i change key but still same pop up is opening.

**Comment by mervekaya** [comment]
i solve the problem. The problem is not document key. The last version of document server is 5.2.3. I change commondefines.js file and  in this file build version was 5.2.2. So that says  document editor is updated . But file can not reloaded. When i change 5.2.2 to 5.2.3 the problem is solved.

**Comment by ShockwaveNN** [comment]
Problem seems be solved, so I close this issue
