### ISSUE TITLE
Ctrl+Backspace and Ctrl+Delete don't work

### ISSUE THREAD

**Issue by spantaleev** [ONLYOFFICE/DocumentServer#436]
`Ctrl` + `Backspace` (or `Ctrl` + `Delete`) don't work for deleting words in the Document editor (could be affecting more than just the Document editor, though).

**What is the current behavior?**

Trying to use `Ctrl` + `Backspace` and `Ctrl` + `Delete` to delete whole words (to the left and to the right, respectively) don't seem to work.

On a related note, `Ctrl` + `Left|Right arrow` works well for moving between words.

**What is the expected behavior?**

- `Ctrl` + `Backspace` deletes a whole word to the left of the cursor.
- `Ctrl` + `Delete` deletes a whole word to the right of the cursor.

**Did this work in previous versions of DocumentServer?**

Can't tell. I haven't tested any other versions.

**DocumentServer version:** 5.2.2.2

**Operating System:** Document Server runs in a Docker container. The browser that I access it from runs on Linux.

**Browser version:** Firefox 63.0.3

**Comment by Rita-Bubnova** [comment]
Hello, @spantaleev.
Thank you. I can confirm - this is a bug, issue 35048 in our internal issue tracker.

**Comment by ShockwaveNN** [comment]
This feature is implemented in https://github.com/ONLYOFFICE/sdkjs/commit/dcf5455276008e38fc482a56cf0ae76848c72cc4
And will be released in 5.3.0 soon

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.

**Comment by JMoVS** [comment]
I would like to reopen this issue as on MacOS, the terminology is (sadly) different:
essentially one can replace `ctrl` with `cmd` - and then it would be right. Word wise jump with ctr-left for example collides with a system shortcut.

Is the whole text "field" so special that it can't use system defaults? Or can there be a check for a Mac locale? Is such an environment variable possible so it could be an easy fix?

**Comment by ShockwaveNN** [comment]
@JMoVS Not have Mac at my disposal, but our help stated this:
![Screenshot from 2020-12-08 10-27-39](https://user-images.githubusercontent.com/668524/101453224-118bd900-3940-11eb-9217-82ec6d18263f.png)

Anyway, original issue was issued more than year ago and was for any OS
Your issue is OS specific, so it's better to create new one, not reopen old one
