### ISSUE TITLE
Non editable sections of document

### ISSUE THREAD

**Issue by ar27111994** [ONLYOFFICE/DocumentServer#437]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** Don't know

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** No

**What is the expected behavior?**
Is there any way to restrict the editing on particular sections of content (including images/videos/clipart/text etc.) in a docx document?

In case there's not, are there any plans on implementing this functionality?
Is it easy to implement it by creating a plugin?

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.2.3-64

**Operating System:**
Linux

**Browser version:**
Google Chrome 63.0.3239.108

**Comment by ar27111994** [comment]
ok I think I have found the answer in issue #417. Please let me know if there are any updates on this.

**Comment by ar27111994** [comment]
Can you give some direction, if we want to create this feature by editing Only Office core/web-apps, where to start and whether its feasible or not? We want to have this feature in the web version of document editor and want to go with only office as it offers almost everything else that we need.

**Comment by ShockwaveNN** [comment]
@ar27111994 we don't think it is possible to implement such features by plugins and don't think it's feasible to implement this feature at all, it's take a lot of work to implement this feature the right way. 
I will close this issue, if you have something to add - please use issue #417 (basically as you mention it's the same issue)
