### ISSUE TITLE
Official DocumentServer installs wrong version of dependencies

### ISSUE THREAD

**Issue by Anupam750** [ONLYOFFICE/DocumentServer#438]
Hello Onlyoffice team,

I am trying to run the `DocumentBuilder` service on my local dekstop machine running `windows 10 pro` and here are the versions of the basic component services mentioned in the 

```
    Erlang: version 19
    RabbitMQ: version 3.6.5
    Redis: version 3.0.503
    PostgreSQL: version 1.22.1
```

but requirement is different in below link https://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx

so i am not able to run application due to wrong dependency, Please check it and let me know for the same.

**Comment by ibnpetr** [comment]
> Official DocumentServer installs wrong version of dependencies


@Anupam750 Actually it doesn't install them, please make sure that you have all dependencies installed according to [the instructions](https://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx) mentioned in your source post.

> Please check it and let me know for the same

We can assure you that the installation process was properly tested, you only need to follow the instructions from our help page.
Should you have any issues/questions feel free to contact ONLYOFFICE team at sales@onlyoffice.com - they will suggest you all possible way how the software can be installed and configured remotely.
