### ISSUE TITLE
Print Display Blank

### ISSUE THREAD

**Issue by z001356389** [ONLYOFFICE/DocumentServer#447]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
print
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/45818998/49866532-00885a00-fe43-11e8-85bb-f9dfe03f9558.png)
![image](https://user-images.githubusercontent.com/45818998/49866557-0da54900-fe43-11e8-9fd5-3128b07ccba7.png)
The version of Linux docker I used was edited properly but not printed. I made sure there were fonts in the docker.
**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
onlyoffice_5.2.3_docker
**Operating System:**
linux centos 7
**Browser version:**
chorme 70.0.3538.110

**Comment by ShockwaveNN** [comment]
Does this problem occur to Microsoft YaHei font only? Could you try to print document with some default font

**Comment by z001356389** [comment]
What is the default for printing? Well, I need some Chinese fonts to edit the file, so I changed the font list. Thank you

**Comment by ShockwaveNN** [comment]
@z001356389 could you try print file with `Calibri`, `Arial` or `Times New Roman` fonts

**Comment by z001356389** [comment]
@ShockwaveNN I reinstalled the new version, which has solved the problem. Thank you
