### ISSUE TITLE
Document rename operation doesn't update the document title

### ISSUE THREAD

**Issue by ar27111994** [ONLYOFFICE/DocumentServer#448]
**Do you want to request a *feature* or report a *bug*?**
Question/Feature/Bug

**What is the current behavior?**
The document name is not updated in the header after Renaming it, even though the `onRequestRename` event is successfully triggered and the callback function is executed with updated name. How do I sync it with updated name?
![image](https://user-images.githubusercontent.com/13036687/49876805-ef8d1800-fe45-11e8-81c9-a481b6d13365.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Rename document from header or file menu, it is not updated in both places.

**What is the expected behavior?**
It should show the updated name of the document.

**Did this work in previous versions of DocumentServer?**
Don't know.

**DocumentServer version:**
5.2.3

**Operating System:**
Cent OS

**Browser version:**
Google Chrome 63.0.3239.108

**Comment by LinneyS** [comment]
It's great that you found methods without documentation! Such as `onRequestRename`.
In fact, this event is used as a tool for get a new name from the user in the editor interface.
Setting a new name is performed by a request for [command servic](https://api.onlyoffice.com/editors/command)e command with data
```
{
    "c": "meta",
    "key": "Khirz6zTPdfd7",
    "meta": {
        "title": "Example New Document Title.docx"
    }
}
```
All users in co-editing the file will receive a new name.

**Comment by ar27111994** [comment]
It doesn't process `OPTIONS preflight` request from the browser. Works fine from postman. How can I make it work with preflight?
![image](https://user-images.githubusercontent.com/13036687/49939274-2f173b00-fefe-11e8-9caa-8bd97da7bff6.png)
