### ISSUE TITLE
Pivot Tables

### ISSUE THREAD

**Issue by sedivy-va** [ONLYOFFICE/DocumentServer#450]
Hi,

We have NextCloud 13 with ONLYOFFICE Document server 5.1.4 CE. It's work pretty well, but toolbar looks quite simple - e.g. missing "Pivot Tables" tab. 

On official OnlyOffice demo page is "full version" of toolbar:
https://api.onlyoffice.com/editors/demopreview?type=spreadsheet#DemoPreview

It's about Only Office licence? We used CE version.

**Comment by ShockwaveNN** [comment]
Comparison of features is available at https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions.
Closing this issue
