### ISSUE TITLE
Nextcloud 14.0.3, ONLYOFFICE 2.0.4 App, onlyoffice-documentserver-5.2.3 

### ISSUE THREAD

**Issue by merced317** [ONLYOFFICE/DocumentServer#451]
For the life of me I can't get Nextcloud to talk to onlyoffice-documentserver.  Two separate machines, real SSL certs, both can be reached from each other (verified using wget from each host) and I've disabled all cert checking just incase.

"rejectUnauthorized": false
in onlyoffice/documentserver/default.json

'onlyoffice' => 
  array (
    'verify_peer_off' => TRUE,
  )
in nextcloud/config/config.php
![nextcloud_error](https://user-images.githubusercontent.com/1405947/48231095-1d7cc980-e37b-11e8-9bab-2756b444119d.png)
That's the error I get.  

Error when trying to connect (Error occurred in the document service: Conversion error)

I am running the shibboleth plugin if that is an issue.  Not sure.  Please help!

**Comment by ShockwaveNN** [comment]
Close this issue in favor of two one mentioned earlier
