### ISSUE TITLE
page freeze when printing

### ISSUE THREAD

**Issue by R2DPIO** [ONLYOFFICE/DocumentServer#452]
if i try to print a spreadsheet in "spreadsheet viewer" and select scaling -> "show on one page" i am getting an error saying that i do not have the right to change the document and the page freezes.

![frezze](https://user-images.githubusercontent.com/43437349/47503358-285b3880-d86a-11e8-8dfa-01a3049ebed7.png)

Nextcloud: 14.0.3
Onlyoffice Version 5.2.2 CE

help please :)

**Comment by trofim24** [comment]
We [fixed](https://github.com/ONLYOFFICE/sdkjs/commit/d08830a5498aaee47a35dc391b433111cceeb9ea) this bug and released in version 5.2.5
