### ISSUE TITLE
The online table replicates rows and columns

### ISSUE THREAD

**Issue by Wangzizhan666** [ONLYOFFICE/DocumentServer#454]
spreadsheet：

1. Copy a column or a row of an online table and paste it into another row or column to get inconsistent results.

2. Copy a cell with a null value and paste it into a cell with a value. The result of the pasted cell still has a value, and the result of normal office should have a null value.

**Comment by ShockwaveNN** [comment]
@Wangzizhan666 Hi, could you fill issue template correctly. We need information about OS, version and JavaScrip console logs

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
