### ISSUE TITLE
Can you clear the cached file after saving it?

### ISSUE THREAD

**Issue by z001356389** [ONLYOFFICE/DocumentServer#455]
I hope that after the file is saved, the cache file will be cleared. Could you tell me if this can be achieved and how to configure it? Thank you

**Comment by ShockwaveNN** [comment]
If you wanna autoremove cached files please look at https://github.com/ONLYOFFICE/DocumentServer/issues/449

**Comment by z001356389** [comment]
@ShockwaveNN Hello, I saw this article, but I didn't find the default.json configuration file. Do I need to create it manually? My version is 5.2.4 docker

**Comment by ShockwaveNN** [comment]
@z001356389 it should be at `/etc/onlyoffice/documentserver/default.json` on ubuntu or docker image

**Comment by z001356389** [comment]
@ShockwaveNN I found it. Thank you. I'm sorry, but I'd also like to ask if spellcheckText can be disabled by default. Thanks

**Comment by ShockwaveNN** [comment]
@z001356389 Sorry, there is no such option, you can only disable spell checker service completely via stopping in by `supervisorctl`

**Comment by z001356389** [comment]
@ShockwaveNN Okay, thank you
