### ISSUE TITLE
[Feature-Request] Nuxeo integration

### ISSUE THREAD

**Issue by Braintelligence** [ONLYOFFICE/DocumentServer#457]
Hi everyone!

OnlyOffice already supports integration with Alfresco. There's a wave of people leaving Alfresco for other ECMS, especially Nuxeo, because of its open-source-first mentality.

I wish OnlyOffice would provide a plugin for [Nuxeo](https://www.nuxeo.com/). There's [this](https://github.com/EsupPortail/nuxeo-onlyoffice) but I can't tell how sophisticated of a solution this is and would love to have something official from the OnlyOffice-team.

Knowing that OnlyOffice will provide such a plugin would definitely have an impact on our choice of office ecosystem for our IT overhaul.

**Comment by hellonadya** [comment]
Hello! Thanks for the idea, we'll contact the Nuxeo team

**Comment by Braintelligence** [comment]
@hellonadya Awesome news, you made my day. Please keep us updated. :muscle: :smile_cat:

**Comment by trofim24** [comment]
We [released](https://www.onlyoffice.com/blog/2020/07/onlyoffice-joins-nuxeo-marketplace-with-a-new-official-connector/) the official [ONLYOFFICE connector](https://github.com/ONLYOFFICE/onlyoffice-nuxeo).
