### ISSUE TITLE
Style gallery

### ISSUE THREAD

**Issue by attardi** [ONLYOFFICE/DocumentServer#463]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Some styles do not show in the Style Gallery

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Import a Word .docx file that has a paragraph with style Title and one with style Body Text.
Style Body Text does not appear in the Style Gallery.

**What is the expected behavior?**
Both styles Title and Body text should appear in the Style Gallery

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.6.3

**Operating System:**
Windows 10

**Browser version:**
Chrome

**Comment by Rita-Bubnova** [comment]
Hello, @attardi.
Can you attach file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
