### ISSUE TITLE
Bulgarian Regional settings

### ISSUE THREAD

**Issue by ggecata** [ONLYOFFICE/DocumentServer#466]
Is there a way to add Bulgarian Regional settings in Spreadsheet Editor? I mean currency symbol, currency format and date/time format.
I have some skills and can try it myself, but need to know which files to edit.

Thank in advance!

**Comment by Rita-Bubnova** [comment]
Hello, @ggecata.
Thank you for your enhancement.
I created a new issue 40190 in our private issue tracker.

**Comment by ShockwaveNN** [comment]
Issue fixed in https://github.com/ONLYOFFICE/web-apps-pro/commit/db2d6a3a9fce221ba9da65218a3693a123f2a963 and will be released as 5.3.0

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
