### ISSUE TITLE
Spreadsheet hidden numbers

### ISSUE THREAD

**Issue by mariuspana** [ONLYOFFICE/DocumentServer#467]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Some numbers within the Spreadsheet editor do not show up correctly. FOr example, using the format "general", the number 128 shows as 1. Adding decimal places makes it 1.00. Changing the format to "number" does not change this. Changing the format to currency works but these are not currencies.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![ezgif-4-5f972936d1aa](https://user-images.githubusercontent.com/5336530/50721949-88732400-10d0-11e9-9614-6efa32d21842.gif)

**What is the expected behavior?**
Numbers should show up as inserted in the cell.

**Did this work in previous versions of DocumentServer?**
Have not tested.

**DocumentServer version:**
5.1.5-59 

**Operating System:**
Ubuntu 16.04.5 LTS

**Browser version:**
Safari Version 12.0.2 (14606.3.4)

**Comment by mariuspana** [comment]
Sorry. hit enter too quickly there.

**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Some numbers within the Spreadsheet editor do not show up correctly. FOr example, using the format "general", the number 128 shows as 1. Adding decimal places makes it 1.00. Changing the format to "number" does not change this. Changing the format to currency works but these are not currencies.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![ezgif-4-5f972936d1aa](https://user-images.githubusercontent.com/5336530/50721949-88732400-10d0-11e9-9614-6efa32d21842.gif)


**What is the expected behavior?**
Numbers should show up as inserted in the cell.

**Did this work in previous versions of DocumentServer?**
Have not tested.

**DocumentServer version:**
5.1.5-59 

**Operating System:**
Ubuntu 16.04.5 LTS

**Browser version:**
Safari Version 12.0.2 (14606.3.4)

**Comment by Rita-Bubnova** [comment]
Hello, @mariuspana.
Please try to reproduce a problem in another browser (for example, Chrome). Is it still occurs?

**Comment by mariuspana** [comment]
Hello @Rita-Bubnova, thank you for the hint. I have just tested in Chrome and Firefox and
 this issue does not exist. Im not sure how many users are using Safari but if there is anything I can help with to get this resolved it would be great. 

Thanks!

**Comment by Rita-Bubnova** [comment]
It is known bug 38167 in our internal issue tracker.
Thanks for the feedback.

**Comment by mariuspana** [comment]
Is it possible for us/me to follow this issue somewhere to be notified when it gets resolved? Or does that happen here with this issue? Thanks

**Comment by ShockwaveNN** [comment]
Problem fixed and released in DocumentServer 5.2.8
