### ISSUE TITLE
How can i check URL of document Server which is installed on my server

### ISSUE THREAD

**Issue by Anupam750** [ONLYOFFICE/DocumentServer#468]
How can i check URL of document Server which is installed on my server, Please let me know for the same

thanks

**Comment by Anupam750** [comment]
any update on it guys?

**Comment by ShockwaveNN** [comment]
Sorry, I don't understand you question. Your default url of DocumentServer is `http://localhost:80`

**Comment by Anupam750** [comment]
I already tried it (http://localhost:80) but it is not working at all.

I installed document server on my local server and Now i need to connect it with Community server but I am not able get URL for this installed document server.

Please let me know for the same.

thanks

**Comment by ShockwaveNN** [comment]
Which way of installation do you use, your operating system? Please fill all data from issue template https://github.com/ONLYOFFICE/DocumentServer/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Anupam750** [comment]
I am using windows server 2016

**Comment by Anupam750** [comment]
ok

**Comment by Anupam750** [comment]
I have started but still getting the same issue

**Comment by Anupam750** [comment]
Can we run document server and Community Server on same machine?

or we need different machine for both of them?

**Comment by ShockwaveNN** [comment]
@Anupam750 you can install `ONLYOFFICE Community Edition` (https://www.onlyoffice.com/download.aspx) which include both DocumentServer and CommunityServer

**Comment by Anupam750** [comment]
I am compiling code and deploying it. I have done with the community server deployment but now I am facing issue with document server.

I installed only office document server  on my windows server 2016 and I browse it on http://localhost:80 and it is not showing anything other words it is not working.

Now I want to connect document server with community serer. 
so now ....

Can we run document server and Community Server on same machine?
or we need different machine for both of them?

or let me know any other instructions for it on Windows Server 2016 not on other platform like Ubuntu etc..

**Comment by ShockwaveNN** [comment]
@Anupam750 
> it is not showing anything other words it is not working.
It it now working - you should look out for logs for errors.
I think it's a good idea to contact our support at support@onlyoffice.com since your problems seems not just single issue and I have troubles understanding you

**Comment by Anupam750** [comment]
I send mail and they are saying that we are not providing any solution for open source, if you want then i can share my email response here.

But i need some suggestion for the same please...

**Comment by Anupam750** [comment]
I am not facing any issue with community server . I am facing issue with document server as i said earlier messages .
