### ISSUE TITLE
Choose CVS options

### ISSUE THREAD

**Issue by hanitao** [ONLYOFFICE/DocumentServer#473]
i think this  is a bug 

like this :
![123321](https://user-images.githubusercontent.com/9604093/51086616-86b9f800-1783-11e9-9099-2c25c31a31c7.png)

Why does this happen?

document server is the latest

**Comment by ShockwaveNN** [comment]
Could you attach this file?

**Comment by hanitao** [comment]
[new (2).xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/2754309/new.2.xlsx)

**Comment by hanitao** [comment]
I use the Java language

**Comment by LinneyS** [comment]
What [fileType](https://api.onlyoffice.com/editors/config/document#fileType) do you specify?
Is the file link available from the document server?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
