### ISSUE TITLE
Spreadsheet numbers change by clicking on them

### ISSUE THREAD

**Issue by djermann** [ONLYOFFICE/DocumentServer#477]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
A customer of us reported that sometimes when he clicks on numbers in a spreadsheet, they change like this:
1’000 —> 1'00
1’000.00 —> 1’00.00
50’000 —> 50’00
Unfortunately, we could not reproduce this behavior. He said it only appears on some spreadsheets which were uploaded and converted from xls.
Is such a behavior known already?

**Did this work in previous versions of DocumentServer?**
not sure

**DocumentServer version:**
5.2.6 CE Docker

**Operating System:**
Debian 9.6

**Comment by Rita-Bubnova** [comment]
Hello, @djermann.
Can you attach file with problem?

**Comment by djermann** [comment]
Hello @Rita-Bubnova ,
Unfortunately, we cannot ask the customer for these files, because they contain confidential information.

**Comment by djermann** [comment]
I was able to reproduce this problem with another file from the customer. It seems to only appear in Safari. You can download the file here: [format_problem.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/2773518/format_problem.xlsx) When you change the dark red fileds, sometimes the lighter red fields get formated wrong, like this: 
![format_problem](https://user-images.githubusercontent.com/20949681/51396178-df501300-1b3e-11e9-9ce0-3ff7269689d0.png)

**Comment by Rita-Bubnova** [comment]
Hello, @djermann.
Thank you.It is known bug 39878 in our internal issue tracker.

**Comment by ShockwaveNN** [comment]
Problem fixed and released in 5.2.8
