### ISSUE TITLE
Document Server is not running

### ISSUE THREAD

**Issue by Anupam750** [ONLYOFFICE/DocumentServer#481]
1. downloaded document server
2. Installed Document Server
3. deployed on IIS
4. After that getting below issue

![capture](https://user-images.githubusercontent.com/5477380/51525966-6101b280-1e57-11e9-883b-6167726a20ee.PNG)

**Comment by Anupam750** [comment]
I checked logs as well but did not found any error in it.



[Log.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2782171/Log.zip)

**Comment by Anupam750** [comment]
any update on it guys?

**Comment by agolybev** [comment]
@Anupam750, first of all, you have to read [the installation guide](https://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx) and reinstall document server according to it.

**Comment by Anupam750** [comment]
I did it almost 20 time but getting same issue. So please provide me solution about it

**Comment by Anupam750** [comment]
Hello guys, 

I did it on Linux machine and document server is running on it. When  i added a URL of live document server into the community server then i am getting below error. 

Please check it and let me know for the same.


![1screen](https://user-images.githubusercontent.com/5477380/51814041-5fb10980-22df-11e9-8b9f-b7829bc4f106.PNG)
![2screen](https://user-images.githubusercontent.com/5477380/51814042-5fb10980-22df-11e9-95e4-79f64d7d0cd9.png)

**Comment by Anupam750** [comment]
any update guys on it ?

**Comment by Filiecs** [comment]
I have actually been getting a similar issue.
In version 5.4 I was able to get the document server running on IIS normal HTTP, but when I made it HTTPS it kept timing out requests sent to it.
Now on version 5.5 it won't start at all.

**Comment by Filiecs** [comment]
Turns out I needed to install newer versions of the dependencies than it lists on its website (update RabbitMQ, and Erlang), now it works perfectly.

**Comment by ShockwaveNN** [comment]
Is this issue still actual?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
