### ISSUE TITLE
Clarification: Licence

### ISSUE THREAD

**Issue by Natureshadow** [ONLYOFFICE/DocumentServer#482]
Hi,

the licence file states that ONLYOFFICE is published under AGPL-3. However, the README document states that not more than 20 connections are allowed in the community edition. This adds a (probably illegal) limitation to the licence, as I read it.

Is this intended? If not, could you somehow clarify that, please?

Thanks,
Nik

**Comment by Natureshadow** [comment]
Follow-up discussions from a Twitter thread:

The note in the README is not legally binding. So if there is code that limits the code to 20 connections, anyone could just remove that limitation under the AGPL. However, they would then be required to publish this modified code and provide it through the ONLYOFFICE web interface.

So the question then is: Is it intended to make that so hard ☺?

**Comment by hellonadya** [comment]
ONLYOFFICE is distributed under AGPL v3. You are right, the not in our README does not set any additional legal restrictions for the license terms

**Comment by Natureshadow** [comment]
But the code as it is published here sets an intentional limit on the number of active connections, which would have to be changed in the code to use it for more users?

**Comment by hellonadya** [comment]
Correct.

**Comment by Natureshadow** [comment]
OK. Thanks for clarifying that ONLYOFFICE is - not legally, but practically - non-free.
