### ISSUE TITLE
Support of Form Controls (Checkbox, option buttons)

### ISSUE THREAD

**Issue by stoneNyKing** [ONLYOFFICE/DocumentServer#484]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
@stoneNyKing Hi, yeah we got plans to support form controls, but we got no exact date when it'll be ready

**Comment by stoneNyKing** [comment]
Hey, I want a callback function to support the current form action

**Comment by ShockwaveNN** [comment]
@stoneNyKing Seems I do not understand you. Describe your request in more details

**Comment by Cyrus-InfoTrack** [comment]
Hi, is there any updates about the form control (Checkbox) functions?

**Comment by ShockwaveNN** [comment]
@Cyrus-InfoTrack sorry, no news, this is not a high priority task. You can contact sales@onlyoffice.com to speed things up

**Comment by david-synctech** [comment]
Would be amazing if radio buttons were supported. I was going to make a sale for your document server but the customer turned down the offer based on this missing feature :( 

Please let me know if you have an ETA for when this feature might be available.

**Comment by op-nitsch** [comment]
Hi there, 
Checkboxes and the like are also missing a lot on our end. We're paying customers. Please add as soon as possible. 
Cheers! And keep up the good work!

**Comment by trofim24** [comment]
We released support content controls in [version 5.5.0](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#550). Editing content controls avaliable in all our solutions, but adding avaliable only in Enterprise Edition and Developer Edition.
