### ISSUE TITLE
Hey, I found that in the process of using a paragraph, I input half of Chinese, and then half of English or numbers and English will change lines.

### ISSUE THREAD

**Issue by stoneNyKing** [ONLYOFFICE/DocumentServer#485]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I found that in the process of using a paragraph, I input half of Chinese, and then half of English or numbers and English will change lines.
**Did this work in previous versions of DocumentServer?**
 yes
**DocumentServer version:**
5.2.7
**Operating System:**
win10
**Browser version:**
chrome 70.0.3538.77

![_20190124181536](https://user-images.githubusercontent.com/18079345/51671518-15403c00-2004-11e9-8249-29c7719a0d47.png)

In fact, it's just a form of expression. Chinese has a lot of spacing, which leads to letter wrapping.

**Comment by kingkazmam** [comment]
If you try this in microsoft word, it also happen.
I don't think it's a bug, maybe just a line rule.

**Comment by nwpulele** [comment]
This is not a bug. I could also reproduce this scenario, I think it's nomal. As @kingkazmam  said, it's a line rule.

**Comment by ShockwaveNN** [comment]
I'm closing this issue, since it's normal
