### ISSUE TITLE
Encrypted cells can be edited

### ISSUE THREAD

**Issue by tangchunwei** [ONLYOFFICE/DocumentServer#488]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Read an excel file containing encrypted non-editable cells, which can still be edited

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please encrypt and read the cell

**What is the expected behavior?**
Encrypted cells can still be edited

**Did this work in previous versions of DocumentServer?**
invalid
**DocumentServer version:**
5.2.7 CE
**Operating System:**
ubuntu 18.10
**Browser version:**
Google Chrome Version 71.0.3578.98 (Official Version) (64 bits)

**Comment by Rita-Bubnova** [comment]
Hello, @tangchunwei.
At the moment, we have not implemented protection sheet (or a specific area of ​​the sheet) from editing.
This is bug 40375 in our internal issue track.

**Comment by aignerat** [comment]
hey, is there any planned date when this feature will be provided?

**Comment by ShockwaveNN** [comment]
@aignerat Sorry, we got no exact ETA of this feature. You can contact sales@onlyoffice.com to speed things up

**Comment by freumichCH** [comment]
@Rita-Bubnova 
Hello Rita
This issue is open since over a year. Can you give us a Update to that topic?

**Comment by Rita-Bubnova** [comment]
Hello, @freumichCH.
Sorry, no update.

**Comment by aignerat** [comment]
As far as I understood from talking to a developer of OO this feature would have the flaw, that the password for removing the protection temporary needs to be remembered somehow, that would be a security risk. Hope this helps for understanding why this issue isn't solved for a long time now.

**Comment by cpot** [comment]
> As far as I understood from talking to a developer of OO this feature would have the flaw, that the password for removing the protection temporary needs to be remembered somehow, that would be a security risk. Hope this helps for understanding why this issue isn't solved for a long time now.

If you want organisation to leave Office for Onlyoffice massively they need to have the same major features. 

At least if the functionnality is not implemented, not loosing data when saving back from Onlyoffice and then open again with Excel. I think issue https://github.com/ONLYOFFICE/DocumentServer/issues/1013 should not have been close, if it is only the fact not to loose protection information (sheet, tab, cell) of an Excel spreadsheet saved from Onlyoffice

**Comment by aignerat** [comment]
onlyoffice 5.0.0 has some new core features, for example the "backsaving" happens even when one editor didn't close the file (configurable)

**Comment by stavros-k** [comment]
Bump

**Comment by ShockwaveNN** [comment]
This is rather complicated task, so there is no news

No need to bump issue, as soon there will be - we report them

**Comment by cpot** [comment]
any update on this one ?

**Comment by ShockwaveNN** [comment]
This issue is fixed in v7.1, which we released yesterday

I'll close this issue, but feel free to comment or create a new ones if you got troubles
