### ISSUE TITLE
Can't find content control

### ISSUE THREAD

**Issue by benben994** [ONLYOFFICE/DocumentServer#489]
Hi, my document server version is 5.2.6 and I've seen this documentation. [content control](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/UsageInstructions/InsertContentControls.aspx)

But I couldn't find the button to add content control.
Here is my toolbar, can anyone help please?

![2019-01-29 11 34 10](https://user-images.githubusercontent.com/17497586/51882439-d7ebfd80-23b9-11e9-954c-8a21d98a93bc.png)

**Comment by ShockwaveNN** [comment]
@benben994 Hi, https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions
Content control only aviable in Integration Edition or Developer Edition
