### ISSUE TITLE
Add an option to enable access via different URL

### ISSUE THREAD

**Issue by izzy** [ONLYOFFICE/DocumentServer#49]
Feature request:

**_Current behavior:_** Currently the server is only accessible via 'proto://server/'.

**_Expected behavior:_** It would be good to have a configuration option to set a different URL. This would make integrating the DocumentServer in different environments possible. One could use the DocumentServer behind proxies/load balancers and in other apps.

The configuration might look like the following:

```
{
    'protocol': 'https',
    'server': 'example.com',
    'port': '8443',
    'path': '/subdirectory/'
}
```

This would force the server backend and server frontend to use `https://example.com:8443/subdirectory/` as base-URL.

The only reference to the actual URL we found digging through the source was in [sockjs](https://github.com/ONLYOFFICE/web-apps/blob/7a5e775d597724591f1898439546ed8bcf5db9de/vendor/sockjs/sockjs.js#L5343) around line 5343, but this only works for the frontend part. For the backend we did find requests for cached files in `/cache`, but could not find the actual backend source where the URL is generated.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
