### ISSUE TITLE
fillForms permission don't work

### ISSUE THREAD

**Issue by filippoangileri** [ONLYOFFICE/DocumentServer#492]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
I can't use the fillForms permission i can only set edit permission to false to disable editing on the entire document. I want make edit only on forms.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
On configuration i set:
 permissions: {
                            download: true,
                            edit: false,
                            review: false,
			    fillForms: true
                        }
**What is the expected behavior?**
Edit only the forms
**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
5.2.7-2 CE
**Operating System:**
Linux
**Browser version:**
Firefox 64

**Comment by filippoangileri** [comment]
thanks for the fast reply!, when you plan to correct this bug?
My system is already configured and work very but i want use the forms permission.

**Comment by ShockwaveNN** [comment]
@filippoangileri sorry, can't give you exact date

**Comment by filippoangileri** [comment]
Hi this bug was fixed?

**Comment by ShockwaveNN** [comment]
Just checked with Docker images. All setup with `fillForms: true`
`onlyoffice/documentserver:5.2.7.2` - cannot modify Content Controls
`onlyoffice/documentserver-ie:5.2.7.2` - can input to Content Controls
`onlyoffice/documentserver:5.4.2.46` - can input to Content Controls
`onlyoffice/documentserver-ie:5.4.2.46` - can input to Content Controls

So I think issue is resolved, I'll close it. Feel free to comment or create new issue if problem repdoduced

**Comment by seyeonHello** [comment]
Does 'fillForms permission' only work on docs?

**Comment by ShockwaveNN** [comment]
Yes, since you cannot fill forms in Spreadsheet or Presentations

**Comment by seyeonHello** [comment]
Thank you I have another question.
Is "fillForms permission" a API that allows someone to edit and others to check the edited content in real time?

**Comment by ShockwaveNN** [comment]
No. it's for filling form

I think you need [comment](https://api.onlyoffice.com/editors/config/document/permissions#comment) or [review](https://api.onlyoffice.com/editors/config/document/permissions#review) mode
