### ISSUE TITLE
Document Server is running on Linux but getting timeout issue on Windows  Server 2016 in community server

### ISSUE THREAD

**Issue by Anupam750** [ONLYOFFICE/DocumentServer#494]
Document server is running on Linux live server
When connecting it with community server then getting timeout issue and i debug the code and getting error code (-4). Please let me know guys what causing problem.

![2screen](https://user-images.githubusercontent.com/5477380/52105799-2dbce180-2616-11e9-971a-614f26c4cd81.png)

**Comment by alexanderonlyoffice** [comment]
Hello @Anupam750, please note that we do not know what is the reason of the issue you face, as you compiled Community Server and Document Server by you own. It will take a lot of time to figure out the real cause of the problem for us, as we do not have an access to the server and to the code you used. That is why we cannot guarantee that it will work. For this difficult problem we have already offered you paid support case and notified you that we do not offer free personal technical support for open source versions of ONLYOFFICE products. If you are interested in paid support case please contact us at support@onlyoffice.com. If not, please install Community Edition, which has all components already preconfigured in the right way and there is no need to set anything up. Follow this [link](https://helpcenter.onlyoffice.com/server/docker/opensource/index.aspx) to find Community Edition installation guide.

**Comment by ShockwaveNN** [comment]
This issue was closed by moving conversation to email support
