### ISSUE TITLE
DocumentBuilder: GetNumbering is not working

### ISSUE THREAD

**Issue by aleksinpavel** [ONLYOFFICE/DocumentServer#499]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?**
Right now it's not possible to get information about numbering using DocumentBuilder's function [GetNumbering](https://api.onlyoffice.com/docbuilder/textdocumentapi/apiparagraph/getnumbering) for paragraph. It's throwing error on calling it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open [Document editor.](https://api.onlyoffice.com/editors/editor?method=docxEditor)
2. Set numbered list for first paragraph using OnlyOffice interface
![image](https://user-images.githubusercontent.com/12109564/52457388-12a91f00-2b8c-11e9-8148-8632f5c39bb5.png)
3. Open Plugins section and create new Macros with this code:
```
var oDocument = Api.GetDocument();
var oParagraph, oRun, oNum;
oParagraph = oDocument.GetElement(0);
try {
    oNum = oParagraph.GetNumbering();
} catch (err) {
    console.log(err);
}
```
4. Open DevTools in browser with console
5. See the error
![image](https://user-images.githubusercontent.com/12109564/52457472-89461c80-2b8c-11e9-975e-244f791e2264.png)

**What is the expected behavior?**
GetNumbering() must return info about numbering according to DocumentBuilder documentation.
**Did this work in previous versions of DocumentServer?**
not checked
**DocumentServer version:**
5.2.8
**Operating System:**
macOS 10.14.2
**Browser version:**
Google Chrome 71.0.3578.98 (64 bit)

**Comment by flaminestone** [comment]
Hello @aleksinpavel. Yes, it is bug, thank you. It will fixed in future release

**Comment by flaminestone** [comment]
Fix https://github.com/ONLYOFFICE/sdkjs/commit/017a33cd1d1f8e18df6c9d7c1657fb0be77ca410

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
