### ISSUE TITLE
possibility to create a new document

### ISSUE THREAD

**Issue by allan-simon** [ONLYOFFICE/DocumentServer#5]
certainly i've missed something but after installing the docker image, the main page does not propose to create new document, only to upload an existing one or to use the samples ones 

it would be great that either if the button exists, that is is made more obvious, or to have that feature if not existing

**Comment by AnaMih** [comment]
Probably you have installed only OnlyOfficeDocumentServer where you may upload or use the samples. If you'd like to create new document or see the list with uploaded files, also you should install DockerCommunityServer.

**Comment by allan-simon** [comment]
ok I see, just one question, is there some API to create a service (or command line tool) to create a new document without needing to also pop a  CommuniServer instance, as it would be for my personnal needs and so I don't need all the features.

**Comment by AnaMih** [comment]
For using documents without CommunityServer, please, use Document API (http://api.onlyoffice.com/editors/) or describe your task more detailed.
