### ISSUE TITLE
Time field in spreadsheat not displayed 

### ISSUE THREAD

**Issue by fcmildef** [ONLYOFFICE/DocumentServer#501]
Bug

**What is the current behavior?**
If you create a document in libreoffice calc, set the field type to "time"  and enter a time value, the value is not displayed when opened in onlyoffice. 
The type is correct, you just dont see the value
when saved as an xlsx file in libreoffice, the value does get shown.

**What is the expected behavior?**
That the value of the field is displayed 

**DocumentServer version:**
 onlyoffice-documentserver-ie        5.2.6-3 

**Operating System:**
ubuntu 16.04

**Browser version:**
firefox 65.0

**Comment by Rita-Bubnova** [comment]
Hello, @fcmildef.
Can you attach file with problem?

**Comment by fcmildef** [comment]
[timetest.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2854830/timetest.zip)
The times in in the time column are not displayed when I open this document in onlyoffice

**Comment by Rita-Bubnova** [comment]
Please upgrade to latest stable release 5.2.8 - this problem should be fixed.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
