### ISSUE TITLE
IPhone can't input Chinese，but Android and PC can

### ISSUE THREAD

**Issue by hqzhen** [ONLYOFFICE/DocumentServer#503]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/299
If not - please fill table template correctly
