### ISSUE TITLE
Choose TXT options

### ISSUE THREAD

**Issue by TrustMSYT** [ONLYOFFICE/DocumentServer#504]
Hello, I am using document server, why load a new document, prompt "Choose txt option Encoding", can I set the default document encoding format into UTF-8?

**Comment by ShockwaveNN** [comment]
Hi, could you describe your issue in more details, describe steps and fill issue template

**Comment by TrustMSYT** [comment]
i use docEditor to load a doc file which i created in java code for edit,when i use this created doc file url as document's url to load, page remind me "Choose TXT option ", to choose  enconding of this file,but when i load a native doc file, page don't remind

**Comment by ShockwaveNN** [comment]
Are you sure this doc file is correct? Could you attach it?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by balakrishna-gajam** [comment]
hi.. i am also looking for solution..

**Comment by ShockwaveNN** [comment]
@afterlogic-support Maybe this is because you reopen file as soon as closing it?
DocumentServer require some time to build a new version of file, could you try for example to add 1 minute timeout after closing file and see if problem persists?

If so - please create separate issue
