### ISSUE TITLE
Document keys with colon make server fail silently

### ISSUE THREAD

**Issue by labkode** [ONLYOFFICE/DocumentServer#505]
When using the community edition of OnlyOffice and sending document keys that contains colon (:) OnlyOffice silently fails. 

This is the configuration we send to OnlyOffice:

```
{
  "document": {
    "fileType": "pptx",
    "key": "home:45495229209378816",
    "title": "/hello.pptx",
    "url": "https://myowncloud/index.php/apps/onlyoffice/storage/download/hello.pptx?x-access-token=xxxx"
  },
  "documentType": "presentation",
  "editorConfig": {
    "callbackUrl": "https://myowncloud/index.php/apps/onlyoffice/storage/track/hello.pptx?x-access-token=xxxx",
    "customization": {
      "goback": {
        "url": "https://myowncloud/index.php/apps/files/?dir=/"
      }
    },
    "lang": "en",
    "mode": "edit",
    "user": {
      "id": "peter",
      "name": "Peter Pan"
    }
  },
  "type": "desktop"
}
```

After that, OnlyOffice tries periodically to get this URL:

```
GET https://onlyofficehost:9443/v5.2.8-24//doc/home:45495229209378816/c/info?t=1550483711968
```
that systematically returns 404 [1].

The OnlyOffice UI only shows the OnlyOffice icon and a loading text [2]  until a timeout is hit and the UI shows a message [3]

[1] 
<img width="1398" alt="screenshot 2019-02-18 at 11 12 22" src="https://user-images.githubusercontent.com/5175912/52943765-26176f80-336e-11e9-9bc5-dcd1db76facf.png">

[2]
<img width="837" alt="screenshot 2019-02-18 at 11 11 56" src="https://user-images.githubusercontent.com/5175912/52943804-3a5b6c80-336e-11e9-86b1-cb5c2be2fdb0.png">

[3]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/5175912/52943918-7ee70800-336e-11e9-8e06-d3a7f2ba58ab.png">

The [documentation](https://api.onlyoffice.com/editors/config/document) says:

**The key characters can be used: 0-9, a-z, A-Z, -._=. The maximal key length is 20 characters.**

**Comment by ibnpetr** [comment]
@labkode 
We use that key for building a path to the file in the storage, this is why we added such kind of limitation.
The only way is to replace it on your side to meet the requirements mentioned in your original post.
(The key characters can be used: 0-9, a-z, A-Z, -._=. The maximal key length is 20 characters.)

**Comment by labkode** [comment]
@ibnpetr Thanks.

Our file ids are of the form home:1318230138198380 and they usually exceed the 20 characters limitation. I can try to workaround substituting the colon (:) for a - and see what happens, but we will still be hitting the 20 characters limitation.

**Comment by ibnpetr** [comment]
> I can try to workaround substituting the colon (:) for a -

That will fix the issue, 

> The maximal key length is 20 characters.

It also will work with longer values, so feel free to use your internal ID's (with substituted colon), we will update the documentation.

**Comment by labkode** [comment]
I close the issue, only missing part is to update the documentation to specify that symbol limit of 20 is a recommendation and maybe specify the hard limit.
