### ISSUE TITLE
Disable Save Menu button in edit mode

### ISSUE THREAD

**Issue by ar27111994** [ONLYOFFICE/DocumentServer#506]
**Do you want to request a *feature* or report a *bug*?**
*feature*
**What is the current behavior?**
don't know
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
not a bug
**What is the expected behavior?**
I want to have the document editing enabled for user without the possibility of saving the document therefore I want to disable `Save` menu item alongside already disabled autosave.
**Did this work in previous versions of DocumentServer?**
don't know
**DocumentServer version:**
5.2.8
**Operating System:**
Cent OS
**Browser version:**
71.0.3578.80

**Comment by ShockwaveNN** [comment]
@ar27111994 Hi, so to be clear - you want ability to edit document for user, but after closing this documents all changes should be lost? This is very strange case for me

**Comment by ar27111994** [comment]
yes, its for editing and printing some database generated data.

**Comment by ShockwaveNN** [comment]
@ar27111994 I don't think it'll be possible to do, especially if there is co-edit mode between several users

**Comment by ar27111994** [comment]
@ShockwaveNN yes we don't have co-edit enabled in this case.

**Comment by ijohnson-TCR** [comment]
Is this possible yet? I am in a use case where we only need users to fill out fields on documents and print it / save the pdf. No need to save the changes.

**Comment by trofim24** [comment]
@ar27111994 @ijohnson-TCR Sorry, we have full customization including "disable Save button" in [the ONLYOFFICE Docs Developer Edition](https://www.onlyoffice.com/developer-edition.aspx). For more information you can contact to [integration@onlyoffice.com](mailto:integration@onlyoffice.com) or [sales@onlyoffice.com](mailto:sales@onlyoffice.com)
