### ISSUE TITLE
Excel printing settings losts when saving

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#510]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Print parameters / Scale : It does not import or save scaling parameters ("Show all columns on one page", ...) from the .xlsx file
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Advanced Parameters / Page Parameters 
Set the scaling factor to "Show all columns on one page" to a xlsx file
**What is the expected behavior?**
The scaling setting is loaded and saved from/to the .xlsx file
Save
Open the file with Excel / LO
![image](https://user-images.githubusercontent.com/3287514/53284736-9f410900-3758-11e9-9049-6ef26c940d3d.png)
Or it should be (if set "Show all columns on one page")
![image](https://user-images.githubusercontent.com/3287514/53284756-bed83180-3758-11e9-806c-c1b674c4dff3.png)

**Did this work in previous versions of DocumentServer?**
Not sure
**DocumentServer version:**
5.2.4
**Operating System:**
Centos7.5
**Browser version:**
Not browser related

**Comment by Rita-Bubnova** [comment]
Hello, @cpot.
Thank you. I can confirm - this is a bug, issue 40695 in our internal issue tracker.

**Comment by cpot** [comment]
Any news about this important bug fix ?

Thanks,

**Comment by Rita-Bubnova** [comment]
Sorry, there is no ETA for this problem.

**Comment by cpot** [comment]
Still no fix for this critical problem?  For you to know **most excel users does not switch to onlyoffice** because of this bug. It is hurting Onlyoffice adoption !

**Comment by Rita-Bubnova** [comment]
@cpot, already fixed and will be released in future major release.

**Comment by cpot** [comment]
Very good news, thx

**Comment by cpot** [comment]
@Rita-Bubnova is the major release is 6 where scaling is fixed, a version where drop-down lists has been promised too. This 2 issues are very hot.

**Comment by Rita-Bubnova** [comment]
This issue has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/7b17de375715f726643f9597f9fd43666ae00eb8) and will be released in future major release (5.5).

Clarify what you mean by "drop-down lists has been promised too"?
Issue https://github.com/ONLYOFFICE/DocumentServer/issues/699 or https://github.com/ONLYOFFICE/DocumentServer/issues/252?

**Comment by cpot** [comment]
> 
> 
> This issue has been fixed ([ONLYOFFICE/sdkjs@7b17de3](https://github.com/ONLYOFFICE/sdkjs/commit/7b17de375715f726643f9597f9fd43666ae00eb8)) and will be released in future major release (5.5).
> 
> Clarify what you mean by "drop-down lists has been promised too"?
> Issue #699 or #252?

Sorry for the delay

699 is a bug when opening a spreadsheet with drop-down lists (it seems to be half implemented, cells should be 'grayed' IMHO until the functionality is implemented)
252 is the functionality (the one highly expected by our customers, some recent comments by @Medanna about delivery). Discussed with Galina at the Paris Open Source Summit 2 days ago.

**Comment by Rita-Bubnova** [comment]
For a better understanding of the status and improving deadlines of each problem, I suggest discussing the drop-down lists in #699 and #252.

This issue is about print settings.

**Comment by cpot** [comment]
@Rita-Bubnova Of course, i will do

**Comment by OnlyOffsub** [comment]
i have a spreadsheet on Excel where page size is on A4 (21x29,7). Spreadsheet is too large so Excel automatically reduce size to fit the A4 size page and print my document.
When the file is imported in OnlyOffice, i can use "Show all columns on one page" to print but in this case, OnlyOffice increase the size page (21x45) and doesn't respect the size page (A4) settings.

**Comment by Rita-Bubnova** [comment]
@OnlyOffsub, I’m not sure I understood your problem correctly, so please create a new problem and fill out the form template with file attached.

**Comment by OnlyOffsub** [comment]
Ok thank you for your answer. A new problem is created #723 (Can you test if it's correct with new version 5.5 please ?)

**Comment by trofim24** [comment]
We fixed this problem in version 5.5.0
