### ISSUE TITLE
If there are more than 7 nested if statements, there will be problems

### ISSUE THREAD

**Issue by hanitao** [ONLYOFFICE/DocumentServer#511]
the formula:
IF(H12<H10,0,IF(I10<=0,0,IF(ABS(IF(G10<0,G10,0)+IF(H10<0,H10,0))>I10,I10,ABS(IF(G10<0,G10,0)+IF(H10<0,H10,0))-IF((H12+F10)>0,H12+F10,0))))

java poi  can generate this formula,but onlyoffice can’t show  this formula in web;

**Comment by Rita-Bubnova** [comment]
Hello, @hanitao. 
Could you show which regional settings are applied in the XLSX file?
You can see them here:
File -> Advanced settings -> Regional settings.

**Comment by hanitao** [comment]
it's default settings,I'm not change this settings.
the formula:
IF(H12<H10,0,IF(I10<=0,0,IF(ABS(IF(G10<0,G10,0)+IF(H10<0,H10,0))>I10,I10,ABS(IF(G10<0,G10,0)+IF(H10<0,H10,0))-IF((H12+F10)>0,H12+F10,0))))
can  normal  show in my local excel,but can't show in onlyoffice web.

**Comment by Rita-Bubnova** [comment]
@hanitao, please attach a screenshot advanced settings.

**Comment by hanitao** [comment]
I use the Chinese version.
![image](https://user-images.githubusercontent.com/9604093/53336966-f56da200-393a-11e9-9435-74cf6789e03d.png)

**Comment by Rita-Bubnova** [comment]
We need settings screenshot of ONLYOFFICE Spreadsheet Editor.

**Comment by hanitao** [comment]
![image](https://user-images.githubusercontent.com/9604093/53337809-3797e300-393d-11e9-9048-f9a6b3738ba5.png)
 Regional settings  is wrong ?

**Comment by Rita-Bubnova** [comment]
I cannot reproduce your problem.
You can attach a video with a demo of the problem?

**Comment by hanitao** [comment]
the regional settings is wrong? I'm not setting onlyofiice，all settings is default, 
What should I do?

**Comment by Rita-Bubnova** [comment]
Unfortunately, I cannot help you without a video demonstrating the problem.
Attach a video, please.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
