### ISSUE TITLE
Version History does not include tracked changes

### ISSUE THREAD

**Issue by dmkash** [ONLYOFFICE/DocumentServer#515]
**Do you want to request a *feature* or report a *bug*?**
Potential bug, but if it is not a bug, this will be a feature request.

**What is the current behavior?**
When viewing the version history for a document with track changes turned on, the suggested changes do not appear in the version until they are accepted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
If User A suggests a change and the document saves, then User B suggests a change and the document saves, there are two versions of the document in the history, which is expected.  However, looking at those two versions the document appears to be completely blank. 

If User C goes in and accepts the change from User A and the document saves, now there is a third version visible in the history with only the change from User A.

**What is the expected behavior?**
I was hoping that each version would display the suggested changes from each user.  

**Did this work in previous versions of DocumentServer?**
Unfortunately, I haven't tested in previous versions.

**DocumentServer version:**
5.2.2

**Operating System:**
CentOS 7

**Browser version:**
All browsers

**Comment by XDmitryK** [comment]
Hi 
We knon about this bug and we will fixed he in future updates.
Thanks for your feedback

**Comment by dmkash** [comment]
Hi, @XDmitryK ! Thank you for the response.  Are you able to give me any idea on timing for the fix?  Thank you!

**Comment by sharq88** [comment]
@XDmitryK @ShockwaveNN Can you give us an update? Have this been fixed? Thanks

**Comment by XDmitryK** [comment]
What version DS using? We fixed this in version 5.3  and over

**Comment by XDmitryK** [comment]
@sharq88 
What version DS using? We fixed this in version 5.3 and over

**Comment by sharq88** [comment]
@XDmitryK  Excellent, thank you!

**Comment by ShockwaveNN** [comment]
I'm closing this issue, if you got some trobules - feel free to comment or open new issue
