### ISSUE TITLE
Powerpoint file requires repair when opening with microsoft powerpoint

### ISSUE THREAD

**Issue by laopisai** [ONLYOFFICE/DocumentServer#516]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Modified a powerpoint file using onlyoffice. Download it and then open it using ms powerpoint.
ms powerpoint complains and ask to repair file.
After repairing, some objects are randomly missing.

**What is the expected behavior?**
onlyoffice does not break compatibility

**Did this work in previous versions of DocumentServer?**
Yes

**DocumentServer version:**
5.2.8

**Operating System:**
Centos 7

** Nextcloud version **
15.0.4

** Onlyoffice/Nextcloud connector version **
2.1.2

**Comment by Rita-Bubnova** [comment]
Hello, @laopisai.
Can you attach a file that repeats the problem?

**Comment by laopisai** [comment]
Hi, after further testing we find that it happens to files using our powerpoint template.
This file will trigger the repair dialogue box in MS powerpoint but nothing is visually missing

[Test.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/2918316/Test.pptx)

Our PowerPoint version is 1901 (Build 11231.20174) by the way

**Comment by Rita-Bubnova** [comment]
Hello, @laopisai.
This problem may be fixed in next release of DocumentServer, but to be sure - can you attach original file, not files that downloaded from DocumentServer?

**Comment by laopisai** [comment]
Not sure if this is what you mean?
[template.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/2923954/template.pptx)

The file that i previously attached was this template uploaded to nextcloud, then edit using onlyoffice, and finally downloaded from nextcloud.

**Comment by laopisai** [comment]
Mistakenly closed this bug

**Comment by ShockwaveNN** [comment]
@laopisai Hi, this is known issue and should be fixed in next major release, thanks

**Comment by laopisai** [comment]
Is it possible to fix existing affected files?

**Comment by ShockwaveNN** [comment]
Yes, after next release is out - just resave all corrupt files again via DocumentServer and they should be fine for MS Powerpoint (I just checked your broken Test.pptx and after reasave on 5.3.0 - Powerpoint has no complains)

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
