### ISSUE TITLE
Users can delete other users' comments even when `commentAuthorOnly` is `true`

### ISSUE THREAD

**Issue by dmkash** [ONLYOFFICE/DocumentServer#517]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Comments entered by users can be delete by other users, even when the value of `commentAuthorOnly` is `true` in the configuration to the editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Ensure the configuration to the editor contains `commentAuthorOnly` being set to `true`
2. As User A, add a comment to the document
3. View the document as User B

User B can see a trashcan icon next to User A's comment. When User B clicks on that icon, User A's comment is deleted.

**What is the expected behavior?**
User B should not see the trashcan icon next to User A's comment.  User B should not have any way to delete User A's comment.

**Did this work in previous versions of DocumentServer?**
Not sure.

**DocumentServer version:**
5.2.2

**Operating System:**
CentOS 7

**Browser version:**
All browsers

**Comment by ShockwaveNN** [comment]
@dmkash Hi, short answer - it was designed like this.
This flag prohibit only editing of comments of other users (As described in documentation). Edit icon should be hidden.
But this flag do not prohibit removing comments, since second user can simply remove all text for which comment applied and by this remove comment, even if this flag will prohibit deleting comment via comment bubble.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by ar27111994** [comment]
but what if the current user doesn't have edit permissions to the document (but can comment)? They shouldn't be allowed to delete comments in this case, right?

**Comment by ShockwaveNN** [comment]
@ar27111994 Hi, we thought about this and changed behaviour - in version 5.3 (which is currently is unreleased but will be released soon) user in comments mode will not be able to delete other users comments if `commentAuthorOnly` is enabled
