### ISSUE TITLE
document viewer height is very short with firefox

### ISSUE THREAD

**Issue by olaulau** [ONLYOFFICE/DocumentServer#519]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
document viewer height is very short with firefox

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just require a demo from onlyoffice, open the spreadsheet example with

**What is the expected behavior?**
web app uses full browser window

**Did this work in previous versions of DocumentServer?**
I don't know

**DocumentServer version:**
9.6.4 

**Operating System:** (of the client I suppose)
ubuntu 18.10 (same on windows 10)

**Browser version:**
Firefox 65 (works fine with chomium / chrome)

**misc:**
seems to be no error loading something, and no JS error in the console.

![screenshot_2019-03-03 onlyoffice sample spreadsheets xlsx](https://user-images.githubusercontent.com/1771905/53700834-c651a780-3df6-11e9-990a-9b21234e6b23.png)

**Comment by ShockwaveNN** [comment]
@olaulau Hi, could you describe in more details what do you mean `just require a demo from onlyoffice`
Do you install DocumentServer on your local server or something else?

>DocumentServer version:
> 9.6.4

This is not a DocumentServer version, it's CommunityServer version

**Comment by olaulau** [comment]
demo request here : https://www.onlyoffice.com/en/registration.aspx?from=main#
not installed on my own server at this time.

**Comment by ShockwaveNN** [comment]
@olaulau everything seems fine to me on my Ubuntu 18.04 with Firefox 65
Could you try to reproduce your problem on another pc?

**Comment by olaulau** [comment]
found that it was the FF extension "i don't care about cookies" which causes the problem.
just adding an exception for the domain resolves the bug.
thanks !
