### ISSUE TITLE
Cannot view comments in "view" mode for documents

### ISSUE THREAD

**Issue by dmkash** [ONLYOFFICE/DocumentServer#520]
**Do you want to request a *feature* or report a *bug*?**
Not sure if this is a bug or a feature request.

**What is the current behavior?**
When viewing a document in "view" mode, comments are not visible. Even if the `comment` value for the `document` configuration is `true`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. As a user that can edit a document, add a comment
2. As a user who cannot edit a document ("view" mode for the editor)

**What is the expected behavior?**
Comments added by users who can edit the document are displayed to a user who cannot edit the document (editor is in "view" mode).

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer version:**
5.2.2

**Operating System:**
CentOS 7

**Browser version:**
All browsers

**Comment by XDmitryK** [comment]
@dmkash We have finished working on this functionality and think it will be released in future updates
Thanks for feedback.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
