### ISSUE TITLE
help config not work

### ISSUE THREAD

**Issue by lixiaomeng8520** [ONLYOFFICE/DocumentServer#521]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The help menu is not hidden when I set the help config to false.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
"customization": {
     "help": false,
 }
**What is the expected behavior?**
The help menu is hidden
**Did this work in previous versions of DocumentServer?**
I do not konw, I use the latest version
**DocumentServer version:**
5.2.8.24
**Operating System:**
windows7
**Browser version:**
Google Chrome 72.0.3626.96

**Comment by ShockwaveNN** [comment]
Hi, this issue is fixed in https://github.com/ONLYOFFICE/web-apps/commit/a621d455c9a6f64936431afce6605cc8b1a6ce2c and will be released as 5.3.0

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
