### ISSUE TITLE
Onlyoffice server page slow loading in windows server 2012 

### ISSUE THREAD

**Issue by OpsHealthcode** [ONLYOFFICE/DocumentServer#522]
We are not able to load new doc or sheet & unable to load old docs also.

below is the screenshot on windows server:

![onlyoffice error](https://user-images.githubusercontent.com/48128178/53813862-8c161080-3f84-11e9-8e1e-86400c643ff6.JPG)
![onlyoffice_error2](https://user-images.githubusercontent.com/48128178/53813983-c97a9e00-3f84-11e9-8287-fa7f48b6150f.JPG)

**Comment by OpsHealthcode** [comment]
It loads forever, does not complete loading

**Comment by ShockwaveNN** [comment]
@OpsHealthcode Hi, please show browser JS console and attach logs from `C:\Program Files\ONLYOFFICE\DocumentServer\Log`

**Comment by OpsHealthcode** [comment]
Please find the api.js & log files
[Log.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2931750/Log.zip)

[api.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2931758/api.zip)

**Comment by ShockwaveNN** [comment]
You got troubles connecting to RabbitMQ
See https://github.com/ONLYOFFICE/DocumentServer/issues/433 for more details

**Comment by OpsHealthcode** [comment]
Hi,

We have updated all the packages with below requirements:

OS 64-bit Windows 7 or later
Additional Requirements
Erlang: version 19.1
RabbitMQ: version 3.5.4
Redis: version 2.8
PostgreSQL: version 9.6

we reinstalled all softwares 3 times but still not able to view or edit docs & spreadsheets; also there are no new logs generated in logs folder after re installation but the site loads forever, cant see anything

**Comment by OpsHealthcode** [comment]
![onlyoffice error](https://user-images.githubusercontent.com/48128178/53877756-0485db80-4030-11e9-9d6a-aedcf11a9943.JPG)

We are getting this screen forever

**Comment by CarlOnlyoffice** [comment]
@OpsHealthcode Hello,
Can you please specify why you are trying to access the example via https://localhost? Have you enabled https? Please try to access it via domain name then. Also please send the full description of the issue to support@onlyoffice.com with the link to this thread.

**Comment by OpsHealthcode** [comment]
HI,

I have sent a mail with all details, could you please check & let me know if we are missing something

**Comment by JRR5143** [comment]
Hi All ,
I have i am also facing same issue.. While clicking on create or edit or view a document in localhost/example page , it is simply opening a new tab and showing loading documents.....
![onlyoffice error](https://user-images.githubusercontent.com/48288564/53892088-a5d15980-4051-11e9-823f-303686163bd9.JPG)

**Comment by CarlOnlyoffice** [comment]
@OpsHealthcode Unfortunately, we haven't received your mail. Please re-send it (support@onlyoffice.com)
@JRR5143 Please check Document Server logs for errors.

**Comment by ShockwaveNN** [comment]
Issue closed. If the problem persists, the author is advised to contact the support team at support@onlyoffice.com.
