### ISSUE TITLE
forgotten files

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#523]
**Do you want to request a *feature* or report a *bug*?**
maybe a feature request if not exist 
**What is the current behavior?**
 in case server cannot download the modified file the file will move to forgotten directory 
but  the callbackUrl is "lost"
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I would say you edit an document on your web server. 
Now the Web server Crash and the ducument-server will save this document and send the download link to web server.
But the web server is crashed and never get his download link.
Now the file will move to forgotten.

**What is the expected behavior?**
some retrys or other ways to get this file

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.2.8.24
**Operating System:**
Debian 9, No Docker
**Browser version:**

**Comment by hahaxd35** [comment]
maybe you need it 
[DEBUG] nodeJS - commandSfcCallback restore 1 status: docId = WvzIkZlV8E7UvNGFQQxg
[DEBUG] nodeJS - storeForgotten: docId = WvzIkZlV8E7UvNGFQQxg
[DEBUG] nodeJS - End commandSfcCallback: docId = WvzIkZlV8E7UvNGFQQxg
[DEBUG] nodeJS - End receiveTask: docId = WvzIkZlV8E7UvNGFQQxg

maybe you can get owner of forgotten files from "changesHistory.json" and write an api commad to ask server for forgotten files with Owner

**Comment by ShockwaveNN** [comment]
Hi, we understand that this is a problem, but currently have no perfect solution for this

**Comment by hahaxd35** [comment]
this issue get closed in new release
