### ISSUE TITLE
Api document is not complete

### ISSUE THREAD

**Issue by lixiaomeng8520** [ONLYOFFICE/DocumentServer#524]
I get the config of the DocumentServer from https://api.onlyoffice.com/editors/ , but I find it is not complete.  For example, the config below is not in the api document:
```
customization: {
    loaderName: 'customName',
    loaderLogo: 'customLogo'
}
```
I hope that you can complete the page of the api document.

**Comment by alexanderonlyoffice** [comment]
Hello @lixiaomeng8520 , please note that open source version of ONLYOFFICE Document Server provided by AGPL license does not allow customization of logo information. All available possibilities of customization for open source version are listed in our [API documentation](https://api.onlyoffice.com/editors/config/editor/customization). 

Customers with commercial licenses can modify the logo information within the conditions of purchased license and by means described in API documentation.

**Comment by lixiaomeng8520** [comment]
@alexanderonlyoffice Thanks！
