### ISSUE TITLE
Can document.url be used with Java iO?

### ISSUE THREAD

**Issue by hqzhen** [ONLYOFFICE/DocumentServer#525]
eg:
```
@RequestMapping("/domload")
 public void domload1(HttpServletResponse response, HttpServletRequest request) throws IOException  {
  
  String path = request.getServletContext().getRealPath("/resource/pdf/test.doc");
  System.out.println(path);
  File file = new File(path);
 
  response.setHeader("Content-Disposition", "attachment;filename="+URLEncoder.encode(file.getName(),"UTF-8"));
  

  FileReader reader = new FileReader(file);
  
  PrintWriter out = response.getWriter();
 
  char buffer[] = new char[1024];
 
  int len = 1024;

  while((len = reader.read(buffer))!=-1){
   out.write(buffer,0,len);
  }
  


  reader.close();
  out.flush();
  out.close();
  
 } 
```
![企业微信截图_15530485565221](https://user-images.githubusercontent.com/45785181/54656122-64d04f00-4aff-11e9-8d16-98bec6ba9cdd.png)
![企业微信截图_15530485836799](https://user-images.githubusercontent.com/45785181/54656128-6a2d9980-4aff-11e9-8e0b-dd29acd8ec33.png)

**Comment by ShockwaveNN** [comment]
Seems if you get this result - you cannot. Looks like incorrect file, for correct `doc` it should not ask for text encoding. Sorry, we do not have enough knowledge of Java, so if anyone interesting - feel free to help

**Comment by LinneyS** [comment]
Hi @hqzhen 
We have an [example of integrating](https://api.onlyoffice.com/editors/example/java) editors on Java.

Maybe these lines will help you:
https://github.com/ONLYOFFICE/document-server-integration/blob/f54e505aad6fa25c7fc2ae1d90a562d996e48e8e/web/documentserver-example/java/src/main/java/controllers/IndexServlet.java#L375-L405

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
