### ISSUE TITLE
API Doubts and Collaboration Usage

### ISSUE THREAD

**Issue by GlauberF** [ONLYOFFICE/DocumentServer#526]
I have docker with DocumentServer, I need to create communication in nodejs and angular 7.

Is there any complete example of communicating with nodejs to DocumentServer?

Another question, how to tame the part of the collaboration?

My application nodejs will save in folders within amazon S3, and when the user clicks create or edit, will open in angular using (/web-apps/apps/api/documents/api.js)

**Comment by ShockwaveNN** [comment]
I think since you created issue at https://github.com/ONLYOFFICE/document-server-integration/issues/58 later you found out about our noedjs test example and this issue can be closed?
