### ISSUE TITLE
Error occurred in the ConvertService: Error convertation Error

### ISSUE THREAD

**Issue by wangruofeianccl** [ONLYOFFICE/DocumentServer#527]
When the document is more than 4M, docx convert PDF Error: Error occurred in the ConvertService: Error convertation Error;

But no error code was returned. What caused the ConvertService fail?

**Comment by wangruofeianccl** [comment]
What caused the ConvertService fail?

**Comment by ShockwaveNN** [comment]
Hi, does this happen with every docx? I think only for some specific docx files and I need these files to investigate your problem

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
