### ISSUE TITLE
documenterver docker | doubt

### ISSUE THREAD

**Issue by GlauberF** [ONLYOFFICE/DocumentServer#529]
I have a doubt and concern.

Can I use in production on my server the documenterver docker, is it stable and safe to be used in production?

**Comment by ShockwaveNN** [comment]
Yes, our docker version is pretty stable and we recommend to use docker version for anyone

**Comment by GlauberF** [comment]
@ShockwaveNN thank you,

is there any root user that we should worry about, example in postgresql?
Because I do not want to have some frustration from someone getting access to the DB data or something externally.

**Comment by ShockwaveNN** [comment]
@GlauberF If you have any doubt - you can ispect Dockerfile by yourself https://github.com/ONLYOFFICE/Docker-DocumentServer/

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
