### ISSUE TITLE
Debian repository for armhf (for ARM based mini-servers)?

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/DocumentServer#53]
I have a small ARM based mini-server (ARMv7 1.8ghz quadcore with 2gb ram) that runs Ubuntu 16.04 and should in theory be able to run the OnlyOffice server, but the OnlyOffice Ubuntu/Debian repositories do not officer armhf support right now.

Do I need to re-compile anything, or could I just force install it anyways? But adding armhf support to the repository would probably be quite useful. Thanks!

**Comment by ibnpetr** [comment]
Hello 
Unfortunately we cannot guarantee that it will work on arm based mini servers. 
We will discuss this point, thanks a lot for your interest.
Hope we'll find a solution.

**Comment by EWouters** [comment]
Are there any instructions on how to compile the onlyoffice-communityserver? I would like to try to compile it on my ARMv7 server.

**Comment by trakloz** [comment]
Hi, any updated on this one? I'm up against the same wall, thanks in advance.

**Comment by trakloz** [comment]
Hi, any updates on this one? I'm up against the same wall, thanks in advance.

**Comment by ShockwaveNN** [comment]
@trakloz You can try to compile it by our [insturction](http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx), but we never tryied it.

**Comment by ShockwaveNN** [comment]
Clsoing it in favor of https://github.com/ONLYOFFICE/DocumentServer/issues/152

**Comment by jsanfe** [comment]
Any news?
