### ISSUE TITLE
Hide OnlyOffice Powered By section in About menu page

### ISSUE THREAD

**Issue by ar27111994** [ONLYOFFICE/DocumentServer#530]
**Do you want to request a *feature* or report a *bug*?**
Question
**What is the current behavior?**
OnlyOffice Powered By section is visible in About menu page
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Question
**What is the expected behavior?**
Want to hide/replace OnlyOffice Powered By section is visible in About menu page. Is it  possible? If yes, how?
![image](https://user-images.githubusercontent.com/13036687/54947817-05d66400-4f5d-11e9-9762-cef5b74b527b.png)

**Did this work in previous versions of DocumentServer?**
Don't know
**DocumentServer version:**
5.2.8-24
**Operating System:**
Cent OS
**Browser version:**
71.0.3578.80

**Comment by ShockwaveNN** [comment]
Hi, we provide ability to change or hide some entries in about menu, but only with special license, you should contact sales@onlyoffie.com and discuss it

**Comment by ar27111994** [comment]
What license is required to make this property true? (Found this while looking for code that makes `about` page hidden as `editorConfig.customization.about = false` isn't working for me).
![image](https://user-images.githubusercontent.com/13036687/56350774-f9080180-61e4-11e9-923e-1e571f60e04b.png)

**Comment by ShockwaveNN** [comment]
@ar27111994 as I said you should contact sales@onlyoffice.com
