### ISSUE TITLE
Changing Default Paper Size

### ISSUE THREAD

**Issue by technomancer-101** [ONLYOFFICE/DocumentServer#531]
I suppose this counts as a feature-request and a bug.

**What is the current behavior?**

Living in Canada, our standard paper size is 8.5"x11" (Letter). OnlyOffice defaults to A4 when creating new documents.
When trying to print pages from a Mac, tested on El Capitan, High Sierra and Mojave, if using a browser that requires the Mac print dialog, such as Safari or Firefox, it cannot render the page or print. This issue is not present in Chrome when using Chrome's print dialogue.

Is there currently a way I can change a configuration file to set default size to Letter?

**Did this work in previous versions of DocumentServer?**

No

**DocumentServer version:**
Docker documentserver:5.2.0.195

**Operating System:**
Docker running in CentOS 7 minimal VM

**Comment by ShockwaveNN** [comment]
Hi, you need to replace default empty document with one with Letter pages

**Comment by technomancer-101** [comment]
Hi, is there a way to do that so that every page defaults to letter?

**Comment by ShockwaveNN** [comment]
After replacing empty document every new page should be like first one, or I'm not sure I understand you correctly

**Comment by technomancer-101** [comment]
Sorry if I confused you. When creating a new document, as in a separate file, (Create...-->Document), it always creates the new file as an A4. Is there a way to change it so they are automatically set as letter?

**Comment by ShockwaveNN** [comment]
You shoud replace new document on server side, do you use our test example or Nextcloud-Ownloud or some other DMS?

**Comment by technomancer-101** [comment]
Right now I'm using your DMS in a docker container

**Comment by ShockwaveNN** [comment]
We support several DMS so I'm not sure which one in `our` :) Could you attach screenshot of DMS, it will be easier

**Comment by technomancer-101** [comment]
Whoops, sorry :) I'm using Community Server tied to Document Server 
![image](https://user-images.githubusercontent.com/48957155/55080102-84b9c280-506b-11e9-9a4a-0adc45ee5e0a.png)

**Comment by ShockwaveNN** [comment]
At here
https://github.com/ONLYOFFICE/CommunityServer/tree/master/web/studio/ASC.Web.Studio/Products/Files/DocStore/newdocuments
So in docker in will be around `/var/www/onlyoffice/WebStudioProducts/Files/DocStore/newdocuments`

**Comment by technomancer-101** [comment]
Thank you so much! I believe that took care of it.

**Comment by ShockwaveNN** [comment]
Closing issue since I think question is answered. Feel free to comment if there is any questions left
