### ISSUE TITLE
how to hide right menu auto?

### ISSUE THREAD

**Issue by eraizi** [ONLYOFFICE/DocumentServer#537]
**Do you want to request a *feature* or report a *bug*?**

I want to hide right menu,when I first enter the onlyoffice page.
image1
![image](https://user-images.githubusercontent.com/20589870/55523921-b4954580-56bd-11e9-91d2-81ebc6774849.png)

image2
![image](https://user-images.githubusercontent.com/20589870/55523961-d8f12200-56bd-11e9-9832-3276b727538d.png)

**Comment by ShockwaveNN** [comment]
@eraizi Hi, we already implemented this feature, but currently in only aviable in DocumentServer IntegrationEdition and DeveloperEdition and undocumented. We hope we add documentation soon

**Comment by trofim24** [comment]
You can use [hideRightMenu](https://api.onlyoffice.com/editors/config/editor/customization#hideRightMenu) option.
