### ISSUE TITLE
Debian deb-conf options for external RabbitMQ/Redis/PostgreSQL

### ISSUE THREAD

**Issue by slater0013** [ONLYOFFICE/DocumentServer#542]
**Do you want to request a *feature* or report a *bug*? Documentation update**

**What is the current behavior?**
If you use this guide to install Document Server Integration Edition : https://helpcenter.onlyoffice.com/de/server/integration-edition/linux/linux-installation.aspx

It is not indicated that you can specify plenty of deb-conf options ! Only onlyoffice/ds-port is suggested (which indication led me to uncompress the deb file and find that there are many more)

**What is the expected behavior?**
You might update the documentation with the available parameters which allow an easier cluster installation !

echo onlyoffice-documentserver-ie onlyoffice/db-host  string <DB_HOST> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/db-user  string <DB_USER> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/db-pwd  password <DB_PASSWORD> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/db-name  string <DB_NAME> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/cluster-mode  boolean true | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/redis-host  string <REDIS_HOST> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/rabbitmq-host  string <RABBITMQ_HOST> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/rabbitmq-user  string <RABBITMQ_USER> | debconf-set-selections
echo onlyoffice-documentserver-ie onlyoffice/rabbitmq-pwd  password <RABBITMQ_PWD> | debconf-set-selections

Thanks ;)
GS.

**DocumentServer version: 5.2.8-24**

**Operating System: Debian 9**

**Browser version: Not Relevant**

**Comment by ShockwaveNN** [comment]
@slater0013 Hi, we agree this is not right, we'll fix it )

**Comment by slater0013** [comment]
One interesting point, related to the PostGres configuration, the specified user/password must have rights on the "postgres" database, in order to run the "lt" command (in the post_install script) ! 

GS

**Comment by alexandervnuchkov** [comment]
https://helpcenter.onlyoffice.com/server/integration-edition/linux/linux-installation.aspx#moreOptions

**Comment by slater0013** [comment]
;) thanks
