### ISSUE TITLE
Compiling Document Server for a local server error

### ISSUE THREAD

**Issue by xbitlabs** [ONLYOFFICE/DocumentServer#543]
server : ubuntu-18.04.2-live-server-amd64

cd core/Common/3dParty && ./make.sh       

________ running 'cipd ensure -log-level error -root /usr/local/src/DocumentServer/core/Common/3dParty/v8 -ensure-file /tmp/tmpU2RrD8.ensure' in '.'
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8123 
Error: Command 'cipd ensure -log-level error -root /usr/local/src/DocumentServer/core/Common/3dParty/v8 -ensure-file /tmp/tmpU2RrD8.ensure' returned non-zero exit status 35
Running depot tools as root is sad.
Syncing projects: 100% (27/27), done.                                                

________ running 'cipd ensure -log-level error -root /usr/local/src/DocumentServer/core/Common/3dParty/v8 -ensure-file /tmp/tmp6CXb0d.ensure' in '.'
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8123 
Error: Command 'cipd ensure -log-level error -root /usr/local/src/DocumentServer/core/Common/3dParty/v8 -ensure-file /tmp/tmp6CXb0d.ensure' returned non-zero exit status 35
gn.py: Could not find gn executable at: /usr/local/src/DocumentServer/core/Common/3dParty/v8/v8/buildtools/linux64/gn
ninja: Entering directory `out.gn/linux_64'
ninja: fatal: chdir to 'out.gn/linux_64' - No such file or directory

**Comment by ShockwaveNN** [comment]
Hi, seems this error is some kind of network issues https://stackoverflow.com/a/13686783/820501
Make sure you have correct date on your PC and firewall do not block any connections

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
