### ISSUE TITLE
Display number when input Chinese Pinyin

### ISSUE THREAD

**Issue by LanserShi** [ONLYOFFICE/DocumentServer#545]
**Type: Bug**

**Env: iPhone6s iOS12.2**

**Steps**
1. Enter Onlyoffice document on mobile
2. Switch input method to Chinese Pinyin
3. Input any key

**Expect**
Work as other app. Display Chinese characters to select.

**Did this work in previous versions of DocumentServer?**
Not sure,I installed docker.io/onlyoffice/documentserver about 3 month ago.

**DocumentServer version:**
Not sure, pulled by docker 3 month ago.

**Operating System:**
Docker daemon works on Centos. Android mobile works well.

**Browser version:**
iOS WebView

**Other info:**
Look at [http://school.tengyou.info/1.png](url), (4) (5) (6) displayed after pressing [GHI] [JKL] [MNO]

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/299

**Comment by LanserShi** [comment]
Good news and thanks! Do you known the time v5.3.0 (docker) would be released?

**Comment by ShockwaveNN** [comment]
@LanserShi sorry, currently we have no exact ETA but we are working on it :)
