### ISSUE TITLE
Cannot edit file

### ISSUE THREAD

**Issue by xbitlabs** [ONLYOFFICE/DocumentServer#546]
![QQ图片20190415022937](https://user-images.githubusercontent.com/9734921/56097489-89192300-5f27-11e9-97a1-97fb30f962ac.png)
![QQ图片20190415023314](https://user-images.githubusercontent.com/9734921/56097493-99310280-5f27-11e9-94c5-8650e4488960.png)

**Comment by ShockwaveNN** [comment]
https://api.onlyoffice.com/editors/troubleshooting#error0
And seems you have some errors in your editor config

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
