### ISSUE TITLE
No ECDHE support in dockerimage due to Nodejs 8

### ISSUE THREAD

**Issue by mcmufffin** [ONLYOFFICE/DocumentServer#549]
Hi Onlyoffice Team,

it seems like the docker image does not support a connection to ECDHE upstream server:

```
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
[2019-04-23T10:39:29.991] [ERROR] nodeJS - error downloadFile:url=*someseafileurl with ECDHE only key exchange*
attempt=2;code:EPROTO;connect:null;(id=8dd7c3311b066cdb2120)
Error: write EPROTO 140166482388800:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
```

My cipherlist which is NOT working:
`ssl_ciphers 'ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';`

The cipherlist on which connection works flawless:
`ssl_ciphers 'ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA';`

As you can see its the same list + DHE Keyexchange which id like to replace by ECDHE only (less performance required and more secure)

This seems to be related to the nodejs version.

```
root@d130d520a52b:/# nodejs --version
v8.15.0
```

https://github.com/nodejs/node/issues/21513
Fix:
```
require("tls").DEFAULT_ECDH_CURVE = "auto"
```

May you include the fix listed on the above link??

Thanks!

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Docker image is not supporting connection with ECDHE
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-running docker image
-connect via downloadfile to upstream server
**What is the expected behavior?**
- connection with ECDHE does work
**Did this work in previous versions of DocumentServer?**
dont know
**DocumentServer version:**
onlyoffice/documentserver   latest              8f735fe61177        2 months ago        1.74GB
**Operating System:**
Debian 9
**Browser version:**
Firefox 66

**Comment by ShockwaveNN** [comment]
@mcmufffin Hi, am I understanding correctly and to add support of ECDHE we need to upgrade to node js 10? Or any newer releases of nodejs 8 after 8.15.0 support this feature?

**Comment by mcmufffin** [comment]
Hi,

im not @home atm but if i understood it currectly nodejs 8 does support ecdhe but doesnt have a curve selected. The snipped i provided should enable autonegation of a curve and therefore ecdhe should work. So no major upgrade should be required

Regards

Am 23. April 2019 13:34:59 MESZ schrieb Pavel Lobashov <notifications@github.com>:
>@mcmufffin Hi, am I understanding correctly and to add support of ECDHE
>we need to upgrade to node js 10? Or any newer releases of nodejs 8
>after 8.15.0 support this feature?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ONLYOFFICE/DocumentServer/issues/549#issuecomment-485765667

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ShockwaveNN** [comment]
@mcmufffin Ok, I understand, we'll think about adding this fix `require("tls").DEFAULT_ECDH_CURVE = "auto"`
But in meantime we'll have plans on updating our app to nodejs and this issue should be fixed, but I cannot get exact dates

**Comment by mcmufffin** [comment]
I see. Thanks! 

Am 23. April 2019 14:21:55 MESZ schrieb Pavel Lobashov <notifications@github.com>:
>@mcmufffin Ok, I understand, we'll think about adding this fix
>`require("tls").DEFAULT_ECDH_CURVE = "auto"`
>But in meantime we'll have plans on updating our app to nodejs and this
>issue should be fixed, but I cannot get exact dates
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ONLYOFFICE/DocumentServer/issues/549#issuecomment-485779377

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
