### ISSUE TITLE
Segfault for x2t on excel to pdf conversion

### ISSUE THREAD

**Issue by cetra3** [ONLYOFFICE/DocumentServer#55]
Using the following file: [example.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/554920/example.xlsx)

We can trigger a segmentation fault when converting this file to PDF.

I.e, using `x2t params.xml` with the following params:

```
<?xml version="1.0" encoding="utf-8"?>
<TaskQueueDataConvert>
    <m_sFileFrom>/var/tmp/example.xlsx</m_sFileFrom>
    <m_sFileTo>/var/tmp/example.pdf</m_sFileTo>
    <m_nFormatFrom>257</m_nFormatFrom>
    <m_nFormatTo>513</m_nFormatTo>
</TaskQueueDataConvert>
```

Same issue with converting via document server.

**Comment by ibnpetr** [comment]
Thanks for the information, we have found the issue. It will be resolved soon.
We encourage you to send us any problem files, we will analyze them.
