### ISSUE TITLE
Fuzzy font

### ISSUE THREAD

**Issue by eraizi** [ONLYOFFICE/DocumentServer#551]
Hi guys，
 when I use edge,  the word is fuzzy font, how can I deal with it.
![image](https://user-images.githubusercontent.com/20589870/56704798-1d159680-6741-11e9-8f30-fd8173c2062a.png)

**Comment by ShockwaveNN** [comment]
@eraizi Hi, I think this is known problem and already fixed in DocumentServer 5.3. We will release it soon

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
