### ISSUE TITLE
[feature] LanguageTool integration

### ISSUE THREAD

**Issue by emericv** [ONLYOFFICE/DocumentServer#558]
It will be nice to have LanguageTool integration to be able to interact with LanguageTool server via the REST API (http://wiki.languagetool.org/public-http-api) like the LanguageTool Firefox plugin do

**Comment by ShockwaveNN** [comment]
@emericv Hi, thanks for your idea, I like it, but I don't think we will be able to implement it any time soon, but we post any news in this issue

**Comment by DevPre24** [comment]
+1 This would be such a nice feature.

**Comment by oscar-renteria** [comment]
Is this already happening? 
That would be great!

![image](https://user-images.githubusercontent.com/20833418/112768169-ea563600-901a-11eb-820a-3157a07f6acf.png)
Src: https://www.onlyoffice.com/blog/2016/11/onlyoffice-document-editors-now-support-plugins/

**Comment by trofim24** [comment]
We've already [released](https://www.onlyoffice.com/blog/2021/08/languagetool-and-grammalecte/) plugin [LanguageTool](https://github.com/ONLYOFFICE/plugin-languagetool)
