### ISSUE TITLE
[Debian 9.9] Problem with redis

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [ONLYOFFICE/DocumentServer#559]
**Do you want to request a *feature* or report a *bug*?** Bug

**DocumentServer version:** Latest

**Operating System:** Debian 9.9

**Browser version:** Latest Chrome

Hey, basically I am running the documentserver on my debian VM, I found out that I had redis port disabled, now I enabled and still not working.  I will link to logs below
Thanks ,
Miguel de Carvalho

[out.log](https://del.dog/docserver_miguel.makefile) from docserver

**Comment by ShockwaveNN** [comment]
@MiguelNdeCarvalho Hi, is there any errors in redis logs? `/var/log/redis/redis-server.log` 
If everything is ok - try to connect to redis server via `redis-cli`, if connection failed - you should contact redis support, it's behind our scope

**Comment by MiguelNdeCarvalho** [comment]
Here is redis log https://del.dog/ikujubocoj.coffeescript
