### ISSUE TITLE
how to make it faster when loading fonts

### ISSUE THREAD

**Issue by hanfeicode** [ONLYOFFICE/DocumentServer#562]
![image](https://user-images.githubusercontent.com/10413864/57605686-cf4eba00-7599-11e9-991e-e68bc628e868.png)

i used gzip ,but cache do not work

load font everytime

**Comment by ShockwaveNN** [comment]
@hanfeicode Hi, it should load font only one time in browser, if you refresh page without clearing browser cache - font file is cached and should not load

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
