### ISSUE TITLE
[Presentation] make hyperlink available in slideshow

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#563]
**Do you want to request a *feature* or report a *bug*?** *feature*

**What is the current behavior?**

When there is an hyperlink in a presentation, in the slideshow you can't follow the link. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![hyperlink](https://user-images.githubusercontent.com/11867613/57612745-ad434080-7575-11e9-8f94-1f45a9c7c369.gif)

**What is the expected behavior?**

You can click and follow the hyperlink

**Did this work in previous versions of DocumentServer?**

No

**DocumentServer version:**

5.2.8

**Operating System:**

Windows 10

**Browser version:**
Firefox 66.0.5

**Comment by Rita-Bubnova** [comment]
Hello, @ydelattre.
Thank you. I can confirm - this is a known bug, issue 34835 in our internal issue tracker. It should be fixed in Document Server version 5.3.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
