### ISSUE TITLE
Ability to set default Spreadsheet Regional Settings via config

### ISSUE THREAD

**Issue by wouterVE** [ONLYOFFICE/DocumentServer#564]
I'm struggling to find how I can change the default regional settings from "English (United Kingdom)" to "Nederlands (Nederland)" for spreadsheeteditor for **all users** (instead of every user having to change their own regional settings).

Which file do I have to edit to accomplish this? 

**DocumentServer Docker tag:**
latest

**Host Operating System:**
Ubuntu 16.04.6 LTS
docker-ce  5.18.09

**Comment by wouterVE** [comment]
@ShockwaveNN  ok thanks for your answer, this would be a great improvement as in our region we are used to the DD/MM/YYYY format notation (and it's difficult to make every user to change this for themselves which leads to confusion as some have changed it, others not)

Anyway, thanks for adding this to future enhancements, I appreciate it very much!

**Comment by ShockwaveNN** [comment]
@wouterVE Hi, we add ablity to set Regional Settings via config at https://github.com/ONLYOFFICE/web-apps-pro/pull/225
This will be released as 5.4, but currently we have no ETA for release

**Comment by wouterVE** [comment]
@ShockwaveNN Thanks for your messag.
I'll look it up as soon as i've installed 5.4.

kr
Wouter

**Comment by ShockwaveNN** [comment]
DocumentServer 5.4.0 released and issue should be implemented

**Comment by wouterVE** [comment]
Hi
I've tested this and it seems to work!

Just to be sure, this setting is done in the following way?

Edit `/var/www/onlyoffice/documentserver/web-apps/apps/api/documents/api.js`

and add the following code (or uncomment):


```
config = {

editorConfig: {
 region: nl-BE // can be 'en-us' or lang code
}

}
```

(I'm using docker so to apply this setting I execute `supervisorctl restart all` **within** the container.)

Thanks for implementing this!
