### ISSUE TITLE
Onlyoffice edited pptx after saving using office 2010 to open the prompt to find the document has a problem, need to be repaired

### ISSUE THREAD

**Issue by 1208460349** [ONLYOFFICE/DocumentServer#565]
Onlyoffice edited pptx after saving using office 2010 to open the prompt to find the document has a problem, need to be repaired, I click the repair button to prompt to download the converter, how to solve this compatible office 2010 problem?

**Comment by ShockwaveNN** [comment]
Hi, please fill out issue template correctly and attach original file

**Comment by 1208460349** [comment]
I use only office version v5.2.8-24. Source file address https://github.com/1208460349/back-doc/blob/master/sample-test.pptx. I think it's a compatibility problem with slide templates in files. Now I don't know how to do compatibility.

**Comment by Rita-Bubnova** [comment]
Hello, @1208460349.
Thank you. This is a bug should be fixed in Document Server version 5.3, we will release it soon.

**Comment by 1208460349** [comment]
Thank you for your reply. I'm looking forward to solving this problem.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed
