### ISSUE TITLE
Deletion of text is not tracked while two users are collaborating on documents

### ISSUE THREAD

**Issue by srikantkrishnan** [ONLYOFFICE/DocumentServer#570]
**Do you want to request a *feature* or report a *bug*?**

It appears to be a bug

**What is the current behavior?**

When two users are collaborating on the same document - one user adds some text, which is tracked by onlyoffice. However, if the second user deletes the same text which is added by the first user - there is no tracking of the deletion as well as the original addition.  Both the actions of addition and deletion is done by two different users.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

User 1 adds a word document and shares it with user 2 for editing. Both users have track changes mode on.  User 1 adds some text - the changes are visible to User 2. User 2 deletes the same text which has been added by User 1.  The entire changes are no longer visible as track changes neither the added portion nor the deleted portion.

**What is the expected behavior?**

All changes by the users must be shown as track changes.

**Did this work in previous versions of DocumentServer?**

Not aware

**DocumentServer version:**

ONLYOFFICE Developer Edition 30 days Trial version 

**Operating System:**

Windows

**Browser version:**

Chrome 74.0.3729.157

**Comment by ShockwaveNN** [comment]
@srikantkrishnan Hi, we redisgned Review Mode and it DocumentServer 5.3, which we will release soon this issue should be resolved

**Comment by srikantkrishnan** [comment]
So many thanks, when can we expect this release?

**Comment by ShockwaveNN** [comment]
@srikantkrishnan we got no exact date, but we hope in several weeks

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed
