### ISSUE TITLE
(Document Editor) Table size is changed uncontrollably

### ISSUE THREAD

**Issue by truongngomb** [ONLYOFFICE/DocumentServer#571]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
My table are faulty when I upload my file to  **personal.onlyoffice.com**.

- Microsoft Office Word 2016

![image](https://user-images.githubusercontent.com/50867122/58086319-98575480-7be8-11e9-85b2-3b9713c02876.png)

- OnlyOffice 5.2.8 (**personal.onlyoffice.com**)

![image](https://user-images.githubusercontent.com/50867122/58086408-c9d02000-7be8-11e9-8427-d8cb9d154c74.png)

**What is the expected behavior?**
The width of the table must be the same between Microsoft Office Word and OnlyOffice.

**----**
**Operating System:** 
Windows 10

**Browser:** 
Google Chrome lastest version

**Comment by Rita-Bubnova** [comment]
Hello, @truongngomb.
Can you attach file with problem?

**Comment by truongngomb** [comment]
This is my faulty file (deleted some content)
[testing file.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3204585/testing.file.docx)

**Comment by Rita-Bubnova** [comment]
Thank you. I can confirm - this is a bug, issue 41657 in our internal issue tracker.

**Comment by KirillovIlya** [comment]
https://github.com/ONLYOFFICE/sdkjs/commit/42a8dbfdb4dae9270fb3e84fe05dc493b3692df9
