### ISSUE TITLE
Metrics daemon not listening

### ISSUE THREAD

**Issue by slater0013** [ONLYOFFICE/DocumentServer#572]
**Do you want to request a *feature* or report a *bug*?** BUG Request

**What is the current behavior?**
The Metrics daemon is not accepting connections on port 8125 from localhost.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Standard installation on Debian, netstat does not list any daemon listening on port 8125.

Tried to modify default.json :
 --> "useMetrics": true,
--> "host": "actualDNSnameofTheHost", (also tried IP address)

nothing changed.

Tried to modify /var/www/onlyoffice/documentserver/server/Metrics/config/config.js
--> "host": "actualDNSnameofTheHost", (also tried IP address)

still nothing listening on port 8125.

**What is the expected behavior?**

My goal is to graph statistics in Grafana/Graphite.

**Did this work in previous versions of DocumentServer?**

Never tried.

**DocumentServer version:**

Debian pkg / onlyoffice-documentserver-ie 5.2.8-24                 

**Operating System:**

Debian 9.9

**Browser version:**

Not relevant.

For debug purposes :

out.log for metrics //

Flushing stats at  Fri May 24 2019 11:20:56 GMT+0200 (GMT+02:00)
{ counters:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 4,
     'statsd.metrics_received': 4 },
  timers:
   { 'ds.coauth.data.isSaveLock': [],
     'ds.coauth.data.saveChanges': [],
     'ds.coauth.data.getLock': [],
     'ds.coauth.saveFromChanges': [],
     'ds.conv.downloadFileFromStorage': [],
     'ds.conv.spawnSync': [],
     'ds.conv.postProcess': [],
     'ds.conv.deleteFolderRecursive': [],
     'ds.conv.allconvert': [],
     'ds.coauth.openDocument.open': [],
     'ds.coauth.data.auth': [],
     'ds.conv.downloadFile': [],
     'ds.coauth.data.getMessages': [],
     'ds.coauth.data.unLockDocument': [] },
  gauges:
   { 'ds.expireDoc.connections.edit': 2,
     'ds.expireDoc.connections.view': 1,
     'statsd.timestamp_lag': -309 },
  timer_data:
   { 'ds.coauth.data.isSaveLock': { count_ps: 0, count: 0 },
     'ds.coauth.data.saveChanges': { count_ps: 0, count: 0 },
     'ds.coauth.data.getLock': { count_ps: 0, count: 0 },
     'ds.coauth.saveFromChanges': { count_ps: 0, count: 0 },
     'ds.conv.downloadFileFromStorage': { count_ps: 0, count: 0 },
     'ds.conv.spawnSync': { count_ps: 0, count: 0 },
     'ds.conv.postProcess': { count_ps: 0, count: 0 },
     'ds.conv.deleteFolderRecursive': { count_ps: 0, count: 0 },
     'ds.conv.allconvert': { count_ps: 0, count: 0 },
     'ds.coauth.openDocument.open': { count_ps: 0, count: 0 },
     'ds.coauth.data.auth': { count_ps: 0, count: 0 },
     'ds.conv.downloadFile': { count_ps: 0, count: 0 },
     'ds.coauth.data.getMessages': { count_ps: 0, count: 0 },
     'ds.coauth.data.unLockDocument': { count_ps: 0, count: 0 } },
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0.006666666666666667,
     'statsd.metrics_received': 0.006666666666666667 },
  sets: {},
  pctThreshold: [ 90 ] }
24 May 11:20:56 - [12897] reading config file: ../../config/config.js
24 May 11:20:56 - server is up INFO

Thanks,
GS.

**Comment by ShockwaveNN** [comment]
Hi, did you setup graphite service to collect this info?
https://graphiteapp.org/
And BTW metrics module is not production ready, we do not guarantee that it will work on all systems and have no official documentation

**Comment by slater0013** [comment]
Here is my /var/www/onlyoffice/documentserver/server/Metrics/config/config.js :

{
graphiteHost: "FQDN_OF_MY_GRAPHITE_SERVER"
, graphitePort: "2003"
, flushInterval: 60000 // 6 sec for debug
, backends: [ "./backends/graphite" ]
}

restarted the Metrics Component via supervisorctl.

Is it the good file to edit ? Any tweaking in /etc/onlyoffice/documentserver/default.json ?

Still no traffic between the Graphite and onlyOffice.

**Comment by slater0013** [comment]
ok... VM reboot and statistics are transferring... who knows ...
