### ISSUE TITLE
Compile error: cannot convert ‘bool’ to ‘SVG::DrawElement*’ in return

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/DocumentServer#575]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
With gcc 8.3 on Archlinux x64 i get following error, trying to compile DocumentServer 5.3:
```
../../../raster/Metafile/svg/SVGFramework.h: In member function ‘SVG::DrawElement* SVG::Parser::Create(XmlUtils::CXmlNode&, bool)’:
../../../raster/Metafile/svg/SVGFramework.h:5939:13: error: cannot convert ‘bool’ to ‘SVG::DrawElement*’ in return                                                                                          
      return false; 
[...]
make[1]: *** [Makefile:2216: ../core_build/linux_64/release/obj/SVGFramework.o] Error 1
make[1]: Leaving directory '/home/onny/projects/onlyoffice-documentserver/src/DocumentServer-ONLYOFFICE-DocumentServer-5.3.0/core/DesktopEditor/graphics/pro/graphics.build'
make: *** [Makefile:278: build/lib/linux_64/libgraphics.so*] Error 2
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```
  # Download & build third party modules 
  cd core/Common/3dParty
  ./make.sh

  # Building core
  cd ../..
  make
```

**What is the expected behavior?**
Compilation should run fine

**Did this work in previous versions of DocumentServer?**
Yes

**Comment by ShockwaveNN** [comment]
@onny Hi, could you try to build with this fix?
https://github.com/ONLYOFFICE/core/commit/d2efc3fdd6985a42e1ba0e59ca07b50dc027d1b0

**Comment by onny** [comment]
Yep that fixed the issue

**Comment by ShockwaveNN** [comment]
@onny I leave issue opened until we release fix as master

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.1 is released and this problem should be fixed
