### ISSUE TITLE
OnlyOffice down after update 5.2.8-24 => 5.3.0-243

### ISSUE THREAD

**Issue by CedricGoby** [ONLYOFFICE/DocumentServer#579]
Hi,

**Do you want to request a *feature* or report a *bug*?**
This is a bug I guess...

**What is the current behavior?**
The URL for the onlyoffice server says "Connection failed"

**What is the expected behavior?**
The URL for the onlyoffice should open a page wich says OnlyOffice works fine

**Did this work in previous versions of DocumentServer?**
Yes.

**DocumentServer version:**
onlyoffice-documentserver:amd64 5.3.0-243
A few months ago I followed this tutorial for the installation : https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx

**Operating System:**
Ubuntu server 16.04. My server has an automatic weekly update

**Browser version:**
Mozilla Firefox 67 for Ubuntu

In addition you'll find all updated packages below 

--------------------- dpkg status changes Begin ------------------------ 

 Upgraded:
    bsdutils:amd64 1:2.27.1-6ubuntu3.6 => 1:2.27.1-6ubuntu3.7
    grub-legacy-ec2:all 18.5-45-g3554ffe8-0ubuntu1~16.04.1 => 19.1-1-gbaa47854-0ubuntu1~16.04.1
    libblkid1:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    libfdisk1:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    libgnutls-openssl27:amd64 3.4.10-4ubuntu1.4 => 3.4.10-4ubuntu1.5
    libgnutls30:amd64 3.4.10-4ubuntu1.4 => 3.4.10-4ubuntu1.5
    libmount1:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    libseccomp2:amd64 2.3.1-2.1ubuntu2~16.04.1 => 2.4.1-0ubuntu0.16.04.2
    libsmartcols1:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    libuuid1:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    mount:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    nodejs:amd64 10.15.3-1nodesource1 => 10.16.0-1nodesource1
    onlyoffice-documentserver:amd64 5.2.8-24 => 5.3.0-243
    util-linux:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7
    uuid-runtime:amd64 2.27.1-6ubuntu3.6 => 2.27.1-6ubuntu3.7

Thanks for your help

**Comment by ShockwaveNN** [comment]
@CedricGoby Hi, is there any errors in nginx logs?
Also see for error at onlyoffice logs at `/var/log/onlyoffice`

**Comment by CedricGoby** [comment]
Hi @ShockwaveNN,

Thank you for handling the issue.

Here are some logs :
`tail -f /var/log/nginx/access.log`
--> Empty

`tail -f /var/log/nginx/error.log`
--> Empty

`tail -f /var/log/onlyoffice/documentserver/nginx.error.log`
--> Empty

`tail -f /var/log/nginx/access.log`
--> Empty

Date of server :
```
date
lundi 3 juin 2019, 11:30:30 (UTC+0200)
```
Last onlyoffice log file
-rw-r--r-- 1 www-data   onlyoffice  211 juin   2 03:32 nginx.error.log-20190602

```
tail -f nginx.error.log-20190602
2019/06/02 03:32:14 [crit] 8446#8446: *2440 SSL_do_handshake() failed (SSL: error:1408A0A0:SSL routines:ssl3_get_client_hello:length too short) while SSL handshaking, client: 108.178.16.154, server: 0.0.0.0:443
```

nginx status
```
service nginx status
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since lun. 2019-06-03 06:19:07 CEST; 5h 19min ago
  Process: 1614 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 1306 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 1616 (nginx)
    Tasks: 3
   Memory: 11.6M
      CPU: 788ms
   CGroup: /system.slice/nginx.service
           ├─1616 nginx: master process /usr/sbin/nginx -g daemon on; master_process on
           ├─1617 nginx: worker process                           
           └─1618 nginx: worker process                           

juin 03 06:19:06 myhost systemd[1]: Starting A high performance web server and a reverse proxy server...
juin 03 06:19:07myhost systemd[1]: Started A high performance web server and a reverse proxy server.
```

network status
```
netstat -tanpu
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1622/beam.smp   
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1549/redis-server 1
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1452/epmd       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1480/sshd       
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1619/postgres   
tcp        0      0 127.0.0.1:4369          127.0.0.1:37215         ESTABLISHED 1452/epmd       
tcp        0      0 127.0.0.1:37215         127.0.0.1:4369          ESTABLISHED 1622/beam.smp   
tcp        0    300 serverip:22       laptopip:60728       ESTABLISHED 6480/0          
tcp        0      0 127.0.1.1:4369          127.0.0.1:53819         TIME_WAIT   -               
tcp6       0      0 :::5672                 :::*                    LISTEN      1622/beam.smp   
tcp6       0      0 :::4369                 :::*                    LISTEN      1452/epmd       
tcp6       0      0 :::22                   :::*                    LISTEN      1480/sshd       
tcp6       0      0 ::1:5432                :::*                    LISTEN      1619/postgres   
udp        0      0 127.0.0.1:323           0.0.0.0:*                           1590/chronyd    
udp6       0      0 ::1:323                 :::*                                1590/chronyd    
udp6       0      0 ::1:53306               ::1:53306               ESTABLISHED 1619/postgres
```

**Comment by ShockwaveNN** [comment]
This is strange, nginx seems running fine
Is there any other errors in other log files at `/var/log/onlyoffice/documentserver`

**Comment by markushagge** [comment]
The same problems occured here. The problem is that some nginx-config-Files have changed her names to ds-xxxxx.conf instead auf documentserver-xxxx.conf with the result that nginx is running, but try to deliver the defaults. The solution is to adatp the changes from the old config-files to the new  and then restart nginx and supervisor (Attention: there seems also a new property in default.json, which a had to complete in my default.json)

**Comment by CedricGoby** [comment]
Hi @markushagge

That's sound good.

Could you be more precise please ?
What modifications should be done in which files (please give us absolute path) ?
Could you share your modified files with us ?
What is supervisor and how to restart it ?

Regards

**Comment by markushagge** [comment]
The config.files can be found in /etc/onlyoffice/documentserver/nginx respectively in /etc/nginx/conf.d and /etc/nginx/includes as symlinks to the files in the onlyoffice-Folder. You must search for files with "documentserver" in the name and then copy the content to the correspondig "ds"-file. At on or two places in the files there are paths, which you must change to the "ds"-file.

It depends on your local configuration, so my files won´t help you

supervisor ist the prozess which controls the documentserver. You start it with

> sudo service supervirsor start

and stop it with

> sudo service supervirsor stop

both together you can type

> sudo service supervirsor restart

**Comment by CedricGoby** [comment]
Everything is fine now, thank you for your help.
Because it was an automatic update I couldn't choose to replace the documentserver-files by the new ds-files

Regards
