### ISSUE TITLE
In edit mode, this editor show another editor’s name?

### ISSUE THREAD

**Issue by sdls10qq** [ONLYOFFICE/DocumentServer#58]
How to set DocumentServer Editor, to show another editor’s name?
![20161102112458](https://cloud.githubusercontent.com/assets/6747741/19915726/51c58388-a0ef-11e6-900f-7c609fa53b45.png)

**Comment by ibnpetr** [comment]
Hello 
Could you please specify what do you mean by editor's name.
Where exactly should it be shown?

**Comment by sdls10qq** [comment]
in view mode,show editor’s name
Example:
![e73b2b32d373426b8dda9c2744017165](https://cloud.githubusercontent.com/assets/6747741/19957815/efea8dc0-a1d4-11e6-8734-f925d437e0dc.png)

**Comment by trofim24** [comment]
You mean [the author](https://api.onlyoffice.com/editors/config/document/info) ?

**Comment by sdls10qq** [comment]
The name of the author of this line

**Comment by KirillovIlya** [comment]
Can you explain more precisely what do you need?  Do you use collaboartion? Is it in the fast mode or in the strict mode? Also could you please repost your screenshots in the full size.
