### ISSUE TITLE
not readable font

### ISSUE THREAD

**Issue by Happyfeet01** [ONLYOFFICE/DocumentServer#581]
Hello,

when i open an document (docx) i can´t read the Text in it. The font is font readable.
No Logentry in Nextcloud and the Docker logs. Whats happen here? 

Latest Docker image and Nextcloud Onlyoffice App.
Browser: Firefox
with the Chrome Browser it looks normal and the font is readable. Maybe an Browser issue?

![19-05-31 20-14-11 0648](https://user-images.githubusercontent.com/3295104/58727257-1931ff80-83e4-11e9-93f0-31c0812ffce7.jpg)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
