### ISSUE TITLE
"ds: ERROR (no such group)" and 5.3.0 upgrade failure

### ISSUE THREAD

**Issue by osscombat** [ONLYOFFICE/DocumentServer#583]
Server with v.5.2.8 installed per [instructions](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx).
During 'yum update' there is a "`ds: ERROR (no such group)`" message. After that, the documentserver-configure.sh script ends with:

`chown:` invalid user: ‘ds:ds’
`chown:` invalid user: ‘ds:ds’
`Restarting services... Job for supervisord.service failed because the control process exited with error code. See "systemctl status supervisord.service" and "journalctl -xe" for `details.

When did this ds user or group change happened and how to fix the 5.3.0 upgrade?
Thanks!

**Comment by hahaxd35** [comment]
have a look @/etc/onlyoffice/ducumentserver/[nginx,supervisor] and delete old config's 
new conf files named "ds-*.conf" 


I would say its easier to backup local confs and purge the packed and reinstall.... [debian]

**Comment by ShockwaveNN** [comment]
This problem will be fixed in 5.3.1 
https://github.com/ONLYOFFICE/document-server-package/commit/834dd26799211e2257978739c5a5edcbce329832
(private repo)

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.1 is released and this problem should be fixed
