### ISSUE TITLE
Support of Page Break in Spreadsheet Editor

### ISSUE THREAD

**Issue by ilyasokay** [ONLYOFFICE/DocumentServer#588]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Print area from current files are not transferred into Spreadsheet Editor. Same problem exists with download process. When downloading it overrides and deletes print area.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open excel file with microsoft office and make a print area, then open it with onlyoffice, it will have nothing...

**What is the expected behavior?**
It should be viewed on onlyoffice without any other process.

**Did this work in previous versions of DocumentServer?**
No.

**DocumentServer version:**
5.3.0

**Operating System:**
Windows Server 2012 R2

**Browser version:**
Chrome

**Comment by Rita-Bubnova** [comment]
Hello, @ilyasokay.

Please specify what you mean by "overrides and deletes print area"? 
The print area is saved when downloading a book in XLSX format, as well as when the page is reloaded. You can verify this by opening the "Name Mamager" window in which the specified print area is displayed.

If you mean visual deletion of the print area (the dashed line disappears), then at the moment there is really no possibility to quickly display the dotted line of the print area (Bug 40591).

**Comment by ilyasokay** [comment]
Hi Rita,

The problem is that onlyoffice doesn't support microsoft office's print area. After opening a file that created with microsoft application, it overrides and deletes its previously made print area. It forces to re-create print area in onlyoffice itself.

**Comment by Rita-Bubnova** [comment]
Please, specify when opening XLSX book in ONLYOFFICE Spreadsheet Editor in the "Name Manager" window the "Print_Area" is displayed (as shown in the screenshot)?

![image](https://user-images.githubusercontent.com/25282241/59190346-250c8700-8b85-11e9-9311-9c25ca3ce208.png)

**Comment by ilyasokay** [comment]
You are right, that is not because of the print area. After checking all of the related issues I found out that it is due to the unsupported "page break" feature in spreadsheet editor.

**Comment by Rita-Bubnova** [comment]
@ilyasokay you are right, that the "Page break" feature is not  supported in the Spreadsheet Editor.
I created a new issue 41951 in our private issue tracker.

**Comment by smarquespt** [comment]
@Rita-Bubnova any update? 3 years and still no page break?

**Comment by ShockwaveNN** [comment]
Sorry, no. Currently, this is not a high-priority task. If you want to change that - better contact sales@onlyoffice.com

**Comment by rsnegirev** [comment]
Page breaks was added in 7.5 version, commit https://github.com/ONLYOFFICE/web-apps/commit/74077b2dc71fe8daeb82355977636ed3b0298767.

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
