### ISSUE TITLE
How to let its support for Chinese?

### ISSUE THREAD

**Issue by sdls10qq** [ONLYOFFICE/DocumentServer#59]
I asked if I could to zh.json send to 
/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/locale/

**Comment by trofim24** [comment]
Yes.
Add file zh.json to document-editor locale path (/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/locale/) and set `lang` parameter `'zh'` ([editor config](https://api.onlyoffice.com/editors/config/editor)).
We accept pull request if you want to add this language.
