### ISSUE TITLE
process out of memory

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#591]
**Do you want to request a *feature* or report a *bug*?**
Bug?
**What is the current behavior?**
The convert service produce "process out of memory" Fatal Error but the server have over 1.3G Free 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Dont know when this issue happen maybe by converting to large file? 
**What is the expected behavior?**
Take more memory? change some default settings?

**DocumentServer version:**
5.3.0
**Operating System:**
Debian 9.9
**Browser version:**
----

LOG:
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [/usr/bin/node]
 2: 0x8cd14c [/usr/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 6: 0xe0eac8 [/usr/bin/node]
 7: v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [/usr/bin/node]
 8: v8::internal::IncrementalMarkingJob::Task::RunInternal() [/usr/bin/node]
 9: v8::internal::CancelableTask::Run() [/usr/bin/node]
10: node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/bin/node]
11: 0x9b989b [/usr/bin/node]
12: 0x9ca5c0 [/usr/bin/node]
13: uv_run [/usr/bin/node]
14: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [/usr/bin/node]
15: node::Start(int, char**) [/usr/bin/node]
16: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
17: 0x89f301 [/usr/bin/node]

**Comment by ShockwaveNN** [comment]
@hahaxd35 Hi, this can happen on converting file, but we need file on which this error is happened

**Comment by hahaxd35** [comment]
> @hahaxd35 Hi, this can happen on converting file, but we need file on which this error is happened

year and thats problem i dont have that file ( saw this by checking Log's after some errors from monitoring) 

This server is onlyoffice only <-- see that pun? :D 
can i give all process more memory?

**Comment by ShockwaveNN** [comment]
@hahaxd35 Do you monitor your memory?
>server have over 1.3G Free

Does it has 1.3G free at time of file convert? I think it just peaked on some file, we do not limit memory use of our app

**Comment by hahaxd35** [comment]
I have startet a cronjob every minute to log memory usage

since logging i dont see any peak - typical ;)
i have found some another nginx error's
2019/06/18 08:07:10 [error] 12577#12577: *106248 connect() failed (111: Connection refused) while connecting to upstream, client: 10.111.39.19, server: , request: "POST /ConvertService.
ashx HTTP/1.0", upstream: "http://[::1]:8000/ConvertService.ashx", host: "HOST"

is there any context?

**Comment by ShockwaveNN** [comment]
@hahaxd35 This maybe result of first out of memory error, but not a reason.
Do you have swap on your server?

**Comment by hahaxd35** [comment]
OK just think its better to know :)

nope we dont use SWAP it had enough memory but i can test it for latter lage files ;)

Thanks for help i think this was only setting problem by default values

**Comment by ShockwaveNN** [comment]
We recommend use swap on all servers exactly for `out of memory` cases in
peak scenarios like yours

**Comment by hahaxd35** [comment]
Hay i cant review this issue.
see: https://github.com/ONLYOFFICE/DocumentServer/issues/600

Empty Logfiles with Loglevel Debug

**Comment by hahaxd35** [comment]
seems to work with swap 

thanks!

**Comment by ShockwaveNN** [comment]
@hahaxd35 Good to hear, please note that swap is required to correct work of DocumentServer - Convert Service can require a lot of memory in peak shor-time bursts.
