### ISSUE TITLE
Import CA authority

### ISSUE THREAD

**Issue by tanguy-opendsi** [ONLYOFFICE/DocumentServer#593]
hi

I want secure my Onlyoffice app, but i have some troubles with configuration. 
I have a internal root CA authority, how can i import it to Onlyoffice ?
I'm using nextcloud with it.
The server talk together with https but by default the servers did not allow self signed or unknown CA ROOT authority

The goal here is to use an internal CA certificate like a private company certificate. 

Did this work in previous versions of DocumentServer : no 

Document server version : 5.3.0
Operation system : Debian 9 

Best regards

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi Please fill issue template correctly and provide more details

**Comment by tanguy-opendsi** [comment]
> @tanguy-opendsi Please fill issue template correctly and provide more details

I update the issue. 
Not realy different ^^

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi 
We got no complete guide for using CA, but we think process will be the same for importing CA for any nodejs application

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN  thx for reply do you have working dock about that ?

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi sorry, no

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN it's possible to add this feature to the app?

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi I think this is not a feature of our app, but nodejs (or at least nginx) feature.

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN 
In your app we have possibility to disable ssl verification. 
If i'm good, i think here the client is nodejs when onlyoffice upload the file to nextcloud server. 
I found that : 
export NODE_EXTRA_CA_CERTS=[your CA certificate file path]
But i don't know where i have to place this export.
Inside supervisorctl? 
Best regards

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi yep, I think you should add this env to all supervisor scripts in `/etc/supervisor/conf.d/`

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN  sorry i don't realy undrestand what is the syntax inside supervisorctl

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi I think for example
`/etc/supervisor/conf.d/ds-docservice.conf`
should contain 
`environment=NODE_ENV=production-linux,NODE_CONFIG_DIR=/etc/onlyoffice/documentserver,NODE_DISABLE_COLORS=1, NODE_EXTRA_CA_CERTS=[your CA certificate file path]`
and same for all other files in this dir

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN Thx for this fast reply !!! 
i'll check it. Wait my return ;)

**Comment by tanguy-opendsi** [comment]
Unfortunatly this is not working. 
We are working with openssl-ca because in command there is --use-openssl-ca.
Wait my return again.

**Comment by tanguy-opendsi** [comment]
Hi we found the solution. 
The goal here is to add the certificate inside the linux distribution. 
On debian 9 : 
Copy your ca certificate (.crt) to /usr/share/ca-certificates/
then
update-ca-certificates

Best regards

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi Hi, good to hear your resolved the problem :) I close this issue
