### ISSUE TITLE
[spreadsheet] Graph not updating when adding row

### ISSUE THREAD

**Issue by MaximeMaW** [ONLYOFFICE/DocumentServer#597]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
In spreadsheets, when a chart is plotted from a data row, the graph does not update when a row is added. This behaviour is incorrect/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a file with two rows, filled with numbers: line 1 and line 2
2. plot line 2 row using a line chart
3. add a new line 1
-> The graph updates and keeps plotting line 2

The data range is Sheet1!$A$2:$N$3

**What is the expected behavior?**
new line 3 should be plotted instead : By default the data range  should be, so that it tracks the same date when rows are added:

Sheet1!A2:N3

**Did this work in previous versions of DocumentServer?**
Don't know. I suppose not.

**DocumentServer version:**
Latest

**Operating System:**
Debian stretch
DocumentServer CE v5.2.8

**Browser version:**
Firefox version : 67.0.4

**Comment by Rita-Bubnova** [comment]
Hello, @MaximeMaW .
Can you attach file with problem?

**Comment by MaximeMaW** [comment]
Hello @Rita-Bubnova ,
Thank you very much for your message. Here are two files, one was obtained from the other by inserting one row (row 1).  I would expect the graph not to update.

Many thanks!

[Before bug graph.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3331073/Before.bug.graph.xlsx)
[After bug graph.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3331074/After.bug.graph.xlsx)

**Comment by Rita-Bubnova** [comment]
@MaximeMaW, unfortunately, according to the scenario you specified, I cannot reproduce the problem.
But it seems that the result displayed in the file "After.bug.graph.xlsx" can be obtained after inserting two row and then undoing the last action. 

If we have other steps to reproduce the problem, please describe them in more detail or attach a video demonstrating the problem.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
