### ISSUE TITLE
How to achieve the display of historical version?

### ISSUE THREAD

**Issue by sdls10qq** [ONLYOFFICE/DocumentServer#60]
My run java example,How to achieve the display of historical version?
onRequestHistory，onRequestHistory，how you implement it。
![20161104113720](https://cloud.githubusercontent.com/assets/6747741/19993784/4959ebfe-a283-11e6-9af2-d3cdc8b8e7b9.png)

**Comment by sdls10qq** [comment]
Did you have a example?

**Comment by trofim24** [comment]
We have an [example on Node.js](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs)
