### ISSUE TITLE
custom loggin dont work

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#600]
**Do you want to request a *feature* or report a *bug*?**

BUG
**What is the current behavior?**

Logging Config get ignored? after upgrade
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
custom log work befor 5.3.x 
**What is the expected behavior?**

log all in /var/log/onlyoffice/node.log nothing in other logs

**Did this work in previous versions of DocumentServer?**

YES - 5.2.8

**DocumentServer version:**

5.3.2

**Operating System:**

Debian 9.9

**Browser version:**

dont matter ;)

Config: `/etc/onlyoffice/documentserver/log4js/production.json`
```
{
"appenders": {
        "default": {
                "type": "file",
                "filename": "/var/log/onlyoffice/node.log",
                "backups": "7",
                "compress": "true"
        }
},
        "categories": {
                "default": { "appenders": [ "default" ], "level": "DEBUG" }
            }
    }
```
`/etc/onlyoffice/documentserver/proiduction-linux.json`:
```
{
  "log": {
    "filePath": "/etc/onlyoffice/documentserver/log4js/production.json"
  },
```

**Comment by ShockwaveNN** [comment]
@hahaxd35 Hi, first thing I noticed - you got `proiduction` in `/etc/onlyoffice/documentserver/proiduction-linux.json` - is it a typo in issue or it's real file name on your server?

**Comment by ShockwaveNN** [comment]
@hahaxd35 I cheked your config on current stable version of DocumentServer 
`docker run -it -p 80:80 onlyoffice/documentserver-ie:5.3.2.20`
and I got entries at `/var/log/onlyoffice/node.log` file

**Comment by hahaxd35** [comment]
> @hahaxd35 Hi, first thing I noticed - you got `proiduction` in `/etc/onlyoffice/documentserver/proiduction-linux.json` - is it a typo in issue or it's real file name on your server?

Sorry my mistake this was only a typo 

Okay strange... I don't use docker but this should be matter?

Do you want to see other config like local.json? but i dont touch any other file

**Comment by ShockwaveNN** [comment]
>I don't use docker but this should be matter?
Maybe version of loggin 3d party library is different?
In docker version is 
```
cd /var/www/onlyoffice/documentserver/server/Common
npm list --depth=0 | grep log4js
```
Mine is `log4js@3.0.6`

**Comment by hahaxd35** [comment]
chown -R ds:ds /var/log/onlyoffice ;)

**Comment by ShockwaveNN** [comment]
Yep, seems about right, we change user name in 5.3. Sorry about your troubles
