### ISSUE TITLE
[Bug Report] Can't input Chinese since V5.3.0

### ISSUE THREAD

**Issue by nwpulele** [ONLYOFFICE/DocumentServer#601]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Can not input Chinese when editing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a doc file, able to input English character smoothly, but can't input Chinese. 

**What is the expected behavior?**
Being able to input Chinese as usual.

**Did this work in previous versions of DocumentServer?**
Yes, it worked in V5.2.8. I could input Chinese without any problem in V5.2.8.

**DocumentServer version:**
V5.3.0, V5.3.2 (didn't test V5.3.1, but I guess it's same.)
I'm using LATEST Community server version which is V10.0.1, but this bug also happened at V9.6.4. 

**Operating System:**
Deployed at CentOS 7.4 x64
Client: Windows 10 x 64

**Browser version:**
Firefox Quantum 58.0

P.S: Not sure if any other Chinese users have same issue?

**Comment by Rita-Bubnova** [comment]
Hello, @nwpulele.
Thank you. I can confirm - this is a bug, issue 41999 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
@nwpulele, this problem has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/0d8202cd30c327dc413dccfb362e98a7926ce304) and will be available in the next version.

**Comment by nwpulele** [comment]
@Rita-Bubnova Thanks! That'll be great!

**Comment by ShockwaveNN** [comment]
I reopen this issue until we release fixed version

**Comment by ShockwaveNN** [comment]
5.3.4 is released, issue should be resolved
