### ISSUE TITLE
Getting weird coding when I open documents

### ISSUE THREAD

**Issue by 1998CC2** [ONLYOFFICE/DocumentServer#602]
**Do you want to request a *feature* or report a *bug*?**
NO

**What is the current behavior?**
The document server is opening the documents within NextCloud, but is showing the wrong text encoding.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I think not a bug, misconfiguration maybe.

**What is the expected behavior?**
The document should be shown in the correct text encoding.

**Did this work in previous versions of DocumentServer?**
N/A

**DocumentServer version:**
5.3.2-10

**Operating System:**
Debian Stretch, fresh install.

**Browser version:**
Chrome Mac 75.0.3770.100

Please see attached 2 screenshots, for some reasons I get the wrong text encoding. This is a docx, but I get it with every document I try to open.

![Bildschirmfoto 2019-07-03 um 14 26 00](https://user-images.githubusercontent.com/52410596/60591724-5c92db80-9d9f-11e9-8a3a-743a8a331098.png)
![Bildschirmfoto 2019-07-03 um 14 26 19](https://user-images.githubusercontent.com/52410596/60591726-5c92db80-9d9f-11e9-9c7d-e08fd929faf9.png)

Thanks in advance,
Alex

**Comment by Rita-Bubnova** [comment]
Hello, @1998CC2.
Can you attach file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
