### ISSUE TITLE
Loading docx into the editor removes the first page number

### ISSUE THREAD

**Issue by Znert** [ONLYOFFICE/DocumentServer#603]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When importing a .docx into the editor, the first page number is missing and the next occurrence starts with 2.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create a .docx file via LibreOffice with multiple pages and page numbering in the header (Word should work as well)
- Upload the .docx file to ONLYOFFICE
- When opening the file, the first page will not have any page number displayed, only on the second page and onwards

Simple document to reproduce the bug:
[simple_doc.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3361334/simple_doc.docx)

Though the bug also occurs when using a document which restarts the numbering counter in the middle of the document (again, the first page number is missing in the middle and continues with 2), but sadly I cannot the disclose the document used.

**What is the expected behavior?**
The first occurrence of the page number should be preserved.

**Did this work in previous versions of DocumentServer?**
Unsure, as I am a new user

**DocumentServer version:**
Docker image `onlyoffice/documentserver:5.3.2.20`

**Operating System:**
Linux/Docker

**Browser version:**
Browser independent, tested on Firefox 67.0.4 (64-bit) on Fedora

**Comment by Rita-Bubnova** [comment]
Hello, @Znert.
Thank you. I can confirm - this is a bug, issue 42022 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/2dc8874223cd47483c50648df8662b19aebbfbee) and will be released in future major release.

**Comment by trofim24** [comment]
We fixed this in version 5.4.0
