### ISSUE TITLE
when i run make at sdkjs, error: Warning: Error: spawn /home/DocumentServer/web-apps-pro/build/node_modules/optipng-bin/vendor/optipng ENOENT in file ../apps/documenteditor/main/resources/img/file-recent.png Use --force to continue.  

### ISSUE THREAD

**Issue by githublyx** [ONLYOFFICE/DocumentServer#605]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Hi, could you specify which os you use for build. 
And attach full build log
Also, to be sure - did you build `core` before?

**Comment by githublyx** [comment]
Hello ShockwaveNN,
 I use ubuntu16.04, gcc5.4.0;
I've compiled core. Thank you:-)
[out.log](https://github.com/ONLYOFFICE/DocumentServer/files/3376833/out.log)

**Comment by ShockwaveNN** [comment]
@githublyx could you check what exact repo do you fetch in `web-apps` folder (`git remote -v` in this folder)

**Comment by githublyx** [comment]
@ShockwaveNN 
1. I deleted “build/node-modules and web-apps-pro/build/node-modules”.
2. Remake it, and issue solved.
3. Maybe the module is incomplete.

Thank you very much!

**Comment by ShockwaveNN** [comment]
@githublyx Glad to hear :)
