### ISSUE TITLE
Convert API - xlsx to zip/images conversion. Only one sheet is getting converted.

### ISSUE THREAD

**Issue by falling-star** [ONLYOFFICE/DocumentServer#606]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

While converting xlsx to zip/images, Only one sheet is getting converted to zip/images.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Any xlsx file with multiple sheets and try to convert it to zip.

https://onlyoffice.veraeng.com/ConvertService.ashx
{
	"async": false,
	"filetype": "xlsx",
	"outputtype": "zip",
	"url": "https://transfer.sh/wdHOl/XLS_Size1MB.xlsx",
	"thumbnail": {
		"first": false,
		"height": 1054,
		"width": 816
	},
	"key": "random_44"
}

**What is the expected behavior?**

All sheets should be converted to zip/images.

**Did this work in previous versions of DocumentServer?**

Not sure.

**DocumentServer version:**

5.2.8

**Operating System:**

centos

**Browser version:**

**Comment by falling-star** [comment]
@ShockwaveNN @agolybev Please see If I am missing any parameter for the conversion API. Thanks.

**Comment by ShockwaveNN** [comment]
@falling-star Hi
We got some additional config option
`doctparams:2`
This is special param, equivalent for DocumentEditor settings (via interface)
```
Print Range - All Sheets
Scaling - Fit sheet on one page
```
Sorry, this parameter is undocumented currently, we plan to change it interface to be more streamlined, but you can try to use it.

Also please note, that your file is pretty big, so `async: false` may be return 504 gateway timeout (more than 30 seconds for convert),
I tried this way and got results:

```
{
"async": true,
"doctparams":2,
"filetype": "xlsx",
"outputtype": "zip",
"url": "https://transfer.sh/wdHOl/XLS_Size1MB.xlsx",
"thumbnail": {
"first": false,
"height": 1054,
"width": 816
},
"key": "deda"
}
```
[output (1).zip](https://github.com/ONLYOFFICE/DocumentServer/files/3376999/output.1.zip)

**Comment by falling-star** [comment]
@ShockwaveNN Thanks. Using doctparams = 2 converts all the sheets but Scaling is 'Fit sheet on one page'. If sheet is bigger, I get empty image for that sheet since it can't fit. What should be the value of doctparams If I want Scaling to be auto Scaling i.e. sheet should not fit in one image but should be converted in to multiple A4 print images ?

**Comment by ShockwaveNN** [comment]
@falling-star Sorry, currently `doctparams` support only one type of convertion. We plan to implement new features, but cannot give exact date

**Comment by Shedevro** [comment]
@konovalovsergey Привет!
Есть ли варианты как конвертировать все листы docx в один или несколько png/jpg?
Пробовал по примеру выше, но входной файл у меня docx, в ответ ошибка с кодом -7.
Спасибо!

**Comment by ShockwaveNN** [comment]
@Shedevro Hi, please use English for describing your issue, this is only allowed language in this issue repo

And yes, there is a way, I think you should create separate issue with examples of your request, seems some params are incorrect

**Comment by xiaguangsiying** [comment]
> @falling-star Hi
> We got some additional config option
> `doctparams:2`
> This is special param, equivalent for DocumentEditor settings (via interface)
> 
> ```
> Print Range - All Sheets
> Scaling - Fit sheet on one page
> ```
> 
> Sorry, this parameter is undocumented currently, we plan to change it interface to be more streamlined, but you can try to use it.
> 
> Also please note, that your file is pretty big, so `async: false` may be return 504 gateway timeout (more than 30 seconds for convert),
> I tried this way and got results:
> 
> ```
> {
> "async": true,
> "doctparams":2,
> "filetype": "xlsx",
> "outputtype": "zip",
> "url": "https://transfer.sh/wdHOl/XLS_Size1MB.xlsx",
> "thumbnail": {
> "first": false,
> "height": 1054,
> "width": 816
> },
> "key": "deda"
> }
> ```
> 
> [output (1).zip](https://github.com/ONLYOFFICE/DocumentServer/files/3376999/output.1.zip)

Hi, if I want convert xlsx to pdf with multi sheets, I should use this special param:`"doctparams":2`

**Comment by ShockwaveNN** [comment]
@xiaguangsiying We are removed `doctparams` since it was workaround for missing interface

There is no a lot of different option for convertation via [spreadsheetLayout](https://api.onlyoffice.com/editors/conversionapi#spreadsheetLayout)

if `spreadsheetLayout` param is missing only active sheet will be converted
But if it exists, even empty - all sheet will be in pdf

For example simplest request in Postman
```
{
	"async": false,
	"filetype": "xlsx",
	"key": "{{$guid}}",
	"outputtype": "pdf",
	"title": "workbook_with_two_sheets.xlsx",
	"url": "https://testing-documentserver-files.s3.amazonaws.com/workbook_with_two_sheets.xlsx",
        "spreadsheetLayout": {}
}
```

**Comment by ShockwaveNN** [comment]
I'm closing this rather old issue, because now Conersion API support a lot of [spreadsheetLayout options](https://api.onlyoffice.com/editors/conversionapi#spreadsheetLayout)

If there is still question or uncertainty about conversion options - please feel free to comment here or create a new issue
