### ISSUE TITLE
config files went missing 

### ISSUE THREAD

**Issue by momovideo** [ONLYOFFICE/DocumentServer#609]
Hi. I updated my CentOS 7 and after that my config files went missing, specifically
/etc/nginx/conf.d/onlyoffice-documentserver.conf
/etc/nginx/includes/onlyoffice-http.conf
/etc/nginx/includes/onlyoffice-documentserver-common.conf
/etc/nginx/includes/onlyoffice-documentserver-docservice.conf

I already found the first two somewhere on the web, but I'm still missing the latter two. Could someone upload those files for me?

**Comment by hahaxd35** [comment]
config files names have been change in 5.3.0 to ds-*.conf

**Comment by momovideo** [comment]
Hi. Thanks for the reply. There were no config files at all - folders were empty. I manage to recover everything from an old backup.
