### ISSUE TITLE
Can't input Chinese in chrome@52

### ISSUE THREAD

**Issue by tangjunweb** [ONLYOFFICE/DocumentServer#610]
hello author 
On Google 52, the space after entering Chinese becomes English

**Comment by ShockwaveNN** [comment]
Sorry, we do not support such old version of chrome

**Comment by tangjunweb** [comment]
thanks 
The lowest version to support Google is？

**Comment by ShockwaveNN** [comment]
We got an I ternal rule about support of 3 version before current stable,
it's not very strict rule, it chrome 52 is two years old and not supported
by Google
