### ISSUE TITLE
When I run "make install" in server dir, It reported the error "Segmentation fault"

### ISSUE THREAD

**Issue by githublyx** [ONLYOFFICE/DocumentServer#611]
[ins.log](https://github.com/ONLYOFFICE/DocumentServer/files/3385639/ins.log)

**Comment by ShockwaveNN** [comment]
I think this is a duplicate of #377 
And there is a possible solutino at https://github.com/ONLYOFFICE/DocumentServer/issues/377#issuecomment-500024765
