### ISSUE TITLE
File converter Processmanagment? 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#615]
**Do you want to request a *feature* or report a *bug*?**
Bug?
**What is the current behavior?**
Its seem that the converter download all files and proceed every convert jobs parallel and this take server DOWN (not responding)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See screenshot 
**What is the expected behavior?**
Server should do process management is there any way? maybe in config?

**Did this work in previous versions of DocumentServer?**
nope?

**DocumentServer version:**
5.3.2

**Operating System:**
Debian 9.9 - wihout Docker

**Browser version:**
dont matter

![ooconverter](https://user-images.githubusercontent.com/48324739/61283811-ff931e80-a7bd-11e9-8559-956d5f103787.png)
![ooconverter2](https://user-images.githubusercontent.com/48324739/61283813-ff931e80-a7bd-11e9-8150-9877d089fd8c.png)

**Comment by ShockwaveNN** [comment]
@hahaxd35 Hi, you could limit it by changing value of config param
`services -> FileConverter -> converter -> maxprocesscount`
Default value is one
For example if you have 8 cores and want to use only 4 threads - change it to 0.5
(see https://github.com/ONLYOFFICE/server/blob/7db900bdc9506862798b20a3b5556fcc9be53708/FileConverter/sources/convertermaster.js#L50)

**Comment by hahaxd35** [comment]
Hi Thanks - good to know but on swapping system this don't really help

now the converter have 8GB RAM 
In this case 4GB RAM was not enough for 16-21 Files 

maybe the converter start only ( $max_process_count ) jobs at ones so the system will not use swap anytime the server got more files 

swapping take system really really slow

i don't know if i'm the only one with this problem

**Comment by ShockwaveNN** [comment]
@hahaxd35 Sorry, I'm not sure that do you mean. Could you describe in more details?
,

**Comment by hahaxd35** [comment]
Sorry i was on Holidays.

Okay i try again.

You can say this is a bug.
This Bug allow denial of service. Send 100 files that need litte bit more time to convert and server gets DOWN (you can give Server more RAM or SWAP but this dont realy matter then send 1000 files)

**Comment by ShockwaveNN** [comment]
Are you sure you changed `maxprocesscount` config value and restart all services? I don't think you can smap convert service if some your cores are left unused

**Comment by hahaxd35** [comment]
Yes i have Test it right now. 

This configuration dont help if system is swaping.

i have send 50 16kb .docx Files to convert to PDF and Server goes DOWN.
"maxprocesscount": 0.5, (Total 2 CORES)

2GB RAM + 2GB SWAP
Connecting to CONVERTER... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

**Comment by ShockwaveNN** [comment]
@hahaxd35 Do you use sync or async requests to ConvertService?

**Comment by hahaxd35** [comment]
we use async

**Comment by ShockwaveNN** [comment]
@hahaxd35 could you try to setup `maxprocesscount` to 0.25?

**Comment by hahaxd35** [comment]
Done but Server still not response 
Connecting to CONVERTER... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

You see this testing Serve has only 2 Cores?

**Comment by ShockwaveNN** [comment]
@hahaxd35 Seems we found a problem and you're right.
Problem occured after this commit https://github.com/ONLYOFFICE/server/commit/1797f3c83929497e90c2fb978a2b9467b5b20310

We are working on solution now

**Comment by yangbing007** [comment]
I want to change my account bounded phone number，but I can not find where
can I do this

Pavel Lobashov <notifications@github.com>于2019年7月29日 周一下午10:48写道：

**Comment by ShockwaveNN** [comment]
@yangbing007 I think you in incorrect thread

**Comment by hahaxd35** [comment]
> @hahaxd35 Seems we found a problem and you're right.
> Problem occured after this commit [ONLYOFFICE/server@1797f3c](https://github.com/ONLYOFFICE/server/commit/1797f3c83929497e90c2fb978a2b9467b5b20310)
> 
> We are working on solution now

Thanks :) and sorry for complications

**Comment by ShockwaveNN** [comment]
@hahaxd35 It's ok, you found a bug and thank you for this )

**Comment by ShockwaveNN** [comment]
@hahaxd35 Hi, your issue fixed in https://github.com/ONLYOFFICE/server/commit/08a12e293d7beaeee1997f853dcdeba8536aaf96
And will be released as DocumentServer 5.4 (but currently we cannot give a release date)

**Comment by hahaxd35** [comment]
> @hahaxd35 Hi, your issue fixed in [ONLYOFFICE/server@08a12e2](https://github.com/ONLYOFFICE/server/commit/08a12e293d7beaeee1997f853dcdeba8536aaf96)
> And will be released as DocumentServer 5.4 (but currently we cannot give a release date)

Thanks! 
should i test befor release?

**Comment by ShockwaveNN** [comment]
@hahaxd35 you can try it with our testing docker image
`onlyoffice/4testing-documentserver-ie:5.3.99.1519`

**Comment by hahaxd35** [comment]
i have replaced files from commit and there work as expected :+1:

**Comment by ShockwaveNN** [comment]
@hahaxd35 I leave this issue opoen until we release fix as stable
