### ISSUE TITLE
Typing blanks to Japanese with English and line break problem

### ISSUE THREAD

**Issue by kevindenight** [ONLYOFFICE/DocumentServer#616]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Typing blanks to Japanese string with English and line break, sometimes will input a big blank like tab, sometimes nothing inputed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Paste a Japanese copied from a web site, then typing blanks to a line with english and line break, the problem appears.

**Did this work in previous versions of DocumentServer?**

yes

**DocumentServer version:**

5.3.0

**Operating System:**

macOS and windows 

**Browser version:**

chrome 75.0

**Comment by kevindenight** [comment]
Example strings：
PS4の高い描写力と処理性能によって、臨場感あふれる映像表現、没入感の深いゲーム体験を提供します。

**Comment by Rita-Bubnova** [comment]
Hi, @kevindenight.
Sorry, I cannot reproduce your problem.
Please, attach a video with its demo.

**Comment by kevindenight** [comment]
![Jul-17-2019 19-04-49](https://user-images.githubusercontent.com/8637962/61370791-d493f200-a8c5-11e9-9761-9f229187fb3d.gif)

**Comment by Rita-Bubnova** [comment]
Seems your problem is not related to justify text?
Justify alignment with the text lined up by both the left and the right sides of the page (additional spacing is added where necessary to keep the alignment).

**Comment by kevindenight** [comment]
So it`s not a bug, it is composing algorithm?

**Comment by Rita-Bubnova** [comment]
Unfortunately, I am not familiar with Japanese grammar.
But this behavior seems to be true. Does the size of the space decrease with alignment changes?

**Comment by kevindenight** [comment]
Yes it decreases with alignment changes.

**Comment by Rita-Bubnova** [comment]
You can turn off justify and everything will be ok.
Or as I said maybe it has to do with Japanese, could you reproduce your problem in English?
Does other office suites behave different for Japanese with Justify on?

**Comment by kevindenight** [comment]
Guess CJK language all have the same behavior.
I cant reproduce this problem in English.
I tried [LibreOffice](https://www.libreoffice.org/)  desktop app, it has no this problem.
Typing blank several times but only one blank is inputed is the primary problem.

**Comment by kevindenight** [comment]
I tried Microsoft office 365 word on mac, it has the same behavior.
So it is not a bug.
Close this issue.
