### ISSUE TITLE
Different formatting in Excel and in Documentserver online

### ISSUE THREAD

**Issue by ratermir** [ONLYOFFICE/DocumentServer#618]
Documentserver shows spreadsheet differently from Excel. I have a bit uncommon spreadsheet with vertical layout, and this spreadheet (which is shown correctly in Excel) does not show text in cells even if there should be enough space around the text (see attachments)

![Correct layout (in Excel)](https://user-images.githubusercontent.com/52619304/61440078-026b4c00-a943-11e9-8dad-69c69de7f106.png)

![Incorrect layout from Onlyoffice online, Iron browser = Chrome 74](https://user-images.githubusercontent.com/52619304/61440145-22027480-a943-11e9-81d8-c6b6cffba9bd.png)

[Original XLSX file](https://github.com/ONLYOFFICE/DocumentServer/files/3405411/Velikonoce.-.casovani.xlsx)

I know this is a minor issue, but I post it for your awareness

This issue lasts over several versions (I observed it first in version 5.0.XX, and persists till current version)

**Comment by Rita-Bubnova** [comment]
Hello, @ratermir.
Thank you. I can confirm - this is a bug, issue 42134 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/ae7d4033bb32a57a0ed8fb66c9731b239c31996) in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
