### ISSUE TITLE
what’s the method that onlyoffice draw document to the browser

### ISSUE THREAD

**Issue by seuliang** [ONLYOFFICE/DocumentServer#619]
How does the onlyoffice draw word file to the browser?
could you describe how this online editor works, espically the method to break content to different pages?

**Comment by ShockwaveNN** [comment]
All our source codes are available in this repo, so I think you should just debug JS in browser to figure out all technical details

**Comment by trofim24** [comment]
Each editor (word, cell, slide) use different methods for draw. You can find them in [sdkjs repo](https://github.com/ONLYOFFICE/sdkjs) and debug JS in browser will help you.
