### ISSUE TITLE
Edit document error

### ISSUE THREAD

**Issue by sdls10qq** [ONLYOFFICE/DocumentServer#62]
I'am install  Document Server with Community Server on docker,by step “Installing Document Server integrated with Community and Mail Servers“.But i'am editing documents, an error has occured on this page. 
![20161107114227](https://cloud.githubusercontent.com/assets/6747741/20045892/a74a4afc-a4df-11e6-966e-1728d5c5c236.png)
I‘am see log,error:
![20161107114122](https://cloud.githubusercontent.com/assets/6747741/20045903/cd8e097e-a4df-11e6-8f04-936a3de417ef.png)

**Comment by sdls10qq** [comment]
I was solved. 80 port is bind tcp6,firewall is filter 80 port in tcp by system default。
I'm off the firewall,this problem is solved。

**Comment by trofim24** [comment]
good
