### ISSUE TITLE
Missing keyboard shortcut for unbreakable space

### ISSUE THREAD

**Issue by ratermir** [ONLYOFFICE/DocumentServer#620]
According to the documentation there should be "CTRL+SHIFT+Space" keyboard combination for unbreakable space, but this does not work in online version (I didn't test desktop version).

Even if it is still possible to put "hard" space using ALT + 255 on num keyboard, it is not available on most laptops and also most of people do not know tis option.

Documentserver 5.3.1 - docker installation
Chrome 74.0.3850

**Comment by Rita-Bubnova** [comment]
Hello, @ratermir.
Thank you. I can confirm - this is a bug, issue 42235 in our internal issue tracker.

**Comment by trofim24** [comment]
We fixed this in version 5.5.0
