### ISSUE TITLE
Document Server cannot be started by supervisord

### ISSUE THREAD

**Issue by porunov** [ONLYOFFICE/DocumentServer#622]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After following the next tutorial the document server cannot be started. Supervisord cannot startup any of `ds` services.
The tutorial which was used: https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

The only difference: NodeJS 10 instad of NodeJS 8

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have tried to install the document server multiple times but without success.

`bash documentserver-configure.sh` connects to `PostgreSQL`, `Redis` and `RabbitMQ` successfully.
`SELINUX` is set to `disabled` in `/etc/selinux/config`.
All ports are opened:
```
firewall-cmd --zone=public --add-port=1-65535/tcp --permanent
sudo firewall-cmd --reload
```

I've tried to use default port and `8089` (i.e. `export DS_PORT=8089` in `/etc/environment`).

The steps are:
1. install NodeJS
2. install `nginx`
3. install `postgresql` and `postgresql-server`
4. `service postgresql initdb` and `chkconfig postgresql on`
5. Change `ident` to `trust` in `/var/lib/pgsql/data/pg_hba.conf`
6. `service postgresql restart`
7. `cd /tmp`
8. `sudo -u postgres psql -c "CREATE DATABASE onlyoffice;"`  
`sudo -u postgres psql -c "CREATE USER onlyoffice WITH password 'onlyoffice';"`  
`sudo -u postgres psql -c "GRANT ALL privileges ON DATABASE onlyoffice TO onlyoffice;"`
9. install `redis`
10. `service redis start` and `systemctl enable redis`
11. `yum install rabbitmq-server`
12. `service rabbitmq-server start`  
`systemctl enable rabbitmq-server`
13. `sudo yum install https://download.onlyoffice.com/repo/centos/main/noarch/onlyoffice-repo.noarch.rpm`
14. `yum install onlyoffice-documentserver`
15. 
```
 service supervisord start
 systemctl enable supervisord
 service nginx start
 systemctl enable nginx
```
16. `bash documentserver-configure.sh` and provide all creds (all default)
17. Restart server

In addition before `17` in several installation tries I was trying this fix https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/3#issuecomment-414944028

In addition, in some installation tries I was trying to setup next properties to all `/etc/supervisord.d/ds*` services which cause a lot of restart tries but all of them are failed.
```
startretries=5
startsecs=0
```

In addition I would like to mention that Nextcloud version 16 is installed on the server also.

`rwx` permissions are granted to users and groups `ds`, `nginx`, `root` for folders `/var/www/onlyoffice/` and `/etc/onlyoffice`.

After that go to `http://localhost:8089` or `http://localhost` (if installed with default port). It will redirect you to `http://localhost:8089/welcome/` or `http://localhost/welcome/` and show you `502 Bad Gateway`.

---

`cat /var/log/onlyoffice/documentserver/nginx.error.log`
```
2019/08/01 18:21:31 [error] 25600#0: *12 no live upstreams while connecting to upstream, client: ::1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8089"
2019/08/01 18:22:22 [error] 25600#0: *12 connect() failed (111: Connection refused) while connecting to upstream, client: ::1, server: localhost, request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "localhost:8089"
2019/08/01 18:22:22 [error] 25600#0: *12 connect() failed (111: Connection refused) while connecting to upstream, client: ::1, server: localhost, request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "localhost:8089"
2019/08/01 18:22:22 [error] 25600#0: *12 no live upstreams while connecting to upstream, client: ::1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8089"
2019/08/01 18:39:55 [error] 25600#0: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 27.115.124.6, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "109.86.184.197", referrer: "http://www.baidu.com"
2019/08/01 18:39:55 [error] 25600#0: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 27.115.124.6, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "109.86.184.197", referrer: "http://www.baidu.com"
2019/08/01 18:39:57 [error] 25600#0: *22 no live upstreams while connecting to upstream, client: 27.115.124.6, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://localhost/welcome/", host: "109.86.184.197", referrer: "http://www.baidu.com"
2019/08/01 18:50:00 [error] 25600#0: *24 connect() failed (111: Connection refused) while connecting to upstream, client: ::1, server: localhost, request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "localhost:8089"
2019/08/01 18:50:00 [error] 25600#0: *24 connect() failed (111: Connection refused) while connecting to upstream, client: ::1, server: localhost, request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "localhost:8089"
2019/08/01 18:50:00 [error] 25600#0: *24 no live upstreams while connecting to upstream, client: ::1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8089"
```
---

`cat /var/log/onlyoffice/documentserver/docservice/err.log`
```
supervisor: couldn't chdir to /var/www/onlyoffice/documentserver/server/DocService/sources/: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /var/www/onlyoffice/documentserver/server/DocService/sources/: EACCES
supervisor: child process was not spawned
```

---
`supervisorctl restart all`
```
ds:docservice: ERROR (spawn error)
ds:converter: ERROR (spawn error)
ds:spellchecker: ERROR (spawn error)
ds:metrics: ERROR (spawn error)
ds:gc: ERROR (spawn error)
```
---
`supervisorctl status`
```
ds:converter                     FATAL     Exited too quickly (process log may have details)
ds:docservice                    FATAL     Exited too quickly (process log may have details)
ds:gc                            FATAL     Exited too quickly (process log may have details)
ds:metrics                       FATAL     Exited too quickly (process log may have details)
ds:spellchecker                  FATAL     Exited too quickly (process log may have details)
```
---
`cat /var/log/supervisor/supervisord.log`
```
2019-08-01 18:26:08,046 INFO exited: docservice (exit status 127; not expected)
2019-08-01 18:26:08,048 INFO exited: converter (exit status 127; not expected)
2019-08-01 18:26:08,048 INFO exited: spellchecker (exit status 127; not expected)
2019-08-01 18:26:08,051 INFO exited: metrics (exit status 127; not expected)
2019-08-01 18:26:08,052 INFO exited: gc (exit status 127; not expected)
2019-08-01 18:26:11,059 INFO spawned: 'docservice' with pid 7236
2019-08-01 18:26:11,062 INFO spawned: 'converter' with pid 7237
2019-08-01 18:26:11,064 INFO spawned: 'spellchecker' with pid 7238
2019-08-01 18:26:11,065 INFO spawned: 'metrics' with pid 7239
2019-08-01 18:26:11,067 INFO spawned: 'gc' with pid 7240
2019-08-01 18:26:11,068 INFO exited: docservice (exit status 127; not expected)
2019-08-01 18:26:11,068 INFO gave up: docservice entered FATAL state, too many start retries too quickly
2019-08-01 18:26:11,069 INFO exited: converter (exit status 127; not expected)
2019-08-01 18:26:11,070 INFO gave up: converter entered FATAL state, too many start retries too quickly
2019-08-01 18:26:11,070 INFO exited: spellchecker (exit status 127; not expected)
2019-08-01 18:26:11,071 INFO gave up: spellchecker entered FATAL state, too many start retries too quickly
2019-08-01 18:26:11,071 INFO exited: metrics (exit status 127; not expected)
2019-08-01 18:26:11,073 INFO gave up: metrics entered FATAL state, too many start retries too quickly
2019-08-01 18:26:11,073 INFO exited: gc (exit status 127; not expected)
2019-08-01 18:26:12,075 INFO gave up: gc entered FATAL state, too many start retries too quickly
```
---

**What is the expected behavior?**

Start document server correctly.

**Did this work in previous versions of DocumentServer?**

I was able to run Onlyoffice DocumentServer and Nextcloud on the same server in Fedora 28. I don't remember the exact version of Onlyoffice but it was > 5. The version of Nextcloud was 13.

**DocumentServer version:**

5.3.4

**Operating System:**

Fedora 30

**Browser version:**

Firefox Quantum 68.0

**Comment by ShockwaveNN** [comment]
Hi, seems there is some permissions issues with `/var/www/onlyoffice/documentserver/server/DocService/sources/` folder.
Also please note, that we officially do not support Fedora as rpm, and I think it's a better idea to you to use Docker on Fedora

**Comment by porunov** [comment]
@ShockwaveNN I don't know why there are such permissions problems but I followed your suggestion and installed Docker on Fedora and started Document server as you proposed. Document server started perfectly in Docker.

**Comment by ShockwaveNN** [comment]
@porunov Glad to hear, I think issue may be closed. Feel free to open new issue if you if you find some more troubles.
