### ISSUE TITLE
Got error code when preview a pdf with no embed chinese font 

### ISSUE THREAD

**Issue by mysugar** [ONLYOFFICE/DocumentServer#624]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

Got error code when preview a pdf with no embed font 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

[not_embed_font.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/3485729/not_embed_font.pdf)

**What is the expected behavior?**
display correctly, the text in the demo pdf is "测试文字"

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
5.3.5
**Operating System:**

**Browser version:**
Chrome 75

**Comment by Rita-Bubnova** [comment]
Hello, @mysugar.
Thank you. I can confirm - this is a bug, issue 40367 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This is issue fixed. I checked this issue in version 7.5.1.

DocumentServer v7.5.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
