### ISSUE TITLE
compile v8 failed

### ISSUE THREAD

**Issue by lugeluge** [ONLYOFFICE/DocumentServer#627]
I tried to compile ONLYOFFICE CORE on Windows platform
But it failed because of the Google V8 engine. could you please provide a compiled V8 lib library. I tried many times but failed. thanks a lot

**Comment by ShockwaveNN** [comment]
@lugeluge Hi, could you specify OS version and compiler you used to build v8

**Comment by lugeluge** [comment]
win10 and vs2017 release version

**Comment by ShockwaveNN** [comment]
@lugeluge we use win10 and vs2015 to compile v8, could you try it?

**Comment by lugeluge** [comment]
ok  i will try,Whether the core only provides conversion functions, not editing APIs

**Comment by ShockwaveNN** [comment]
@lugeluge DocumentServer will not work without core in any form, conversion functions are required for work

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
