### ISSUE TITLE
Additional tab alignment won't work with custom styles

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ONLYOFFICE/DocumentServer#628]
So I wanted to create a style where tabbing will make it right aligned.  Saving the style causes the custom tab to disappear.  I'll attach [my resumé](https://github.com/ONLYOFFICE/snap-desktopeditors/files/3527221/JonasGamao_Resume.docx) as an example.

**Comment by ShockwaveNN** [comment]
Problem actual in DocumentServer, moved to this repo

**Comment by trofim24** [comment]
We fixed this in version 5.4.0

**Comment by ShockwaveNN** [comment]
Fixed by https://github.com/ONLYOFFICE/sdkjs/commit/b1652fb9ebd3096f683aa9aad9b1f7f950b59a3a
