### ISSUE TITLE
Plug-in configuration config.json, if set icons:["], report 500 errors in the console

### ISSUE THREAD

**Issue by anwenbiao** [ONLYOFFICE/DocumentServer#629]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by flaminestone** [comment]
Hello @anwenbiao. I can not to reproduce this issue. Can you attach your `config.json` file?

**Comment by anwenbiao** [comment]
Hello @flaminestone Here is my config. json :
{
    "baseUrl": "",
    "guid": "asc.{GEE1F462-1EB2-5381-980D-4CC84940B75M}",
    "name": "dataSources",
    "variations": [
        {
            "buttons": [
                { "text": "OK", "primary": true  },
                { "text": "cancel", "primary": false }
            ],
            "description": "DATASOURCES",
            "EditorsSupport": ["word","html","text"],
            "icons": [""],
            "initData": "",
            "initDataType": "ole",
            "initOnSelectionChanged": true,
            "isInsideMode": true,
            "isModal": false,
            "isUpdateOleOnResize": true,
            "isViewer": true,
            "isVisual": true,
            "url": "emr.html"
        }
    ]
}
![image](https://user-images.githubusercontent.com/17916543/63778870-365d6800-c918-11e9-9cfc-08dbdb91bd86.png)

**Comment by flaminestone** [comment]
I still can not to reproduce this behavior. Are you sure it is because of  ```"icons": [""]```?
And you have an error in ```EditorsSupport``` parameter. It can only contain  "word", "cell" and "slide"
https://api.onlyoffice.com/plugin/config
Can you attach the whole plugin?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
