### ISSUE TITLE
OnlyOffice DocumentServer Spreadsheet Filter Consistency

### ISSUE THREAD

**Issue by heiligerstein22** [ONLYOFFICE/DocumentServer#63]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Some rows was erased after save a spreadsheet without user interaction.

https://youtu.be/M6_sEu8_F_E

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a spreadsheet
2. Paste a csv file
3. Create a sort filter
4. Use the sort filter (A-Z)
5. Close the file (wait saving process)
6. Open the file (BANG: some rows was erased)

**What is the expected behavior?**

Sorted data without lost.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

Google Chrome, DocumentServer 4.0, Ubuntu 14.04

**Comment by trofim24** [comment]
Thanks for the bug and video description.
We have corrected this problem in [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/db71e0e2569c5f296c4c1401eb25763e9ac3a85f).

This correction will in version 4.2.0.

**Comment by heiligerstein22** [comment]
Thanks for the fast answer. I'll compile and test before close the issue.
