### ISSUE TITLE
XLS->XLSX converter corrupts files

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#631]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I convert this file [test.xls](https://drive.google.com/open?id=1HVTc3xM-SFlo7ayrS4VwtW-3ryAvHVjt) as a result I receive corrupted xlsx file (it's seen only in MS Office, not in OnlyOffice). If after that I open and edit it in OnlyOffice the file is healed back.

**DocumentServer version:**
5.3.2.20

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
It is know issue 42542 in our private tracker.
This problem has been fixed (https://github.com/ONLYOFFICE/core/commit/98114aa7a5530cc80267fe7ee932337c6d1ed27d) and will be available in future versions.

**Comment by RuslanGabbasov** [comment]
Ok thanks a lot!

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.
