### ISSUE TITLE
Bug with fonts adding

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#632]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Adding new fonts (with executing documentserver-generate-allfonts.sh) destroy behavior of fonts dropdown control.
![fonts-bug](https://user-images.githubusercontent.com/20418709/63996277-b05a4080-cb14-11e9-8c57-06969e8cd704.gif)

**DocumentServer version:**
5.3.2.20

**Operating System:**
Windows 10 LTSC 1809

**Browser version:**
Firefox Quantum 68.0.2 (64-bit)

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov Hi, try to clear browser cache or use incognito mode

**Comment by RuslanGabbasov** [comment]
Thanks a lot! Clearing browser cache helped.
