### ISSUE TITLE
ДВССЫЛ (INDIRECT) function works improperly with sheet names beginning by a number

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#636]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![e262a328b9b74fa6a71134e826bb1f8b](https://user-images.githubusercontent.com/20418709/64175853-a8343500-ce75-11e9-8626-7cfde6fe5875.gif)

**DocumentServer version:**
5.3.2.20

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Can you attach file with problem?

**Comment by RuslanGabbasov** [comment]
Hello, @Rita-Bubnova 
[indirect_test](https://drive.google.com/open?id=1KYIwxRGLfX0qrVVcOccFDuOjYx12yG1A)

**Comment by Rita-Bubnova** [comment]
Thank you. 
I can confirm - this is a bug, issue 42692 in our internal issue tracker.

**Comment by trofim24** [comment]
We fixed this in version 5.5.0

**Comment by ShockwaveNN** [comment]
Fixed by https://github.com/ONLYOFFICE/sdkjs/commit/85e32be360750f1b3f47752a286e982533012ade
