### ISSUE TITLE
Print area problem still exists

### ISSUE THREAD

**Issue by ilyasokay** [ONLYOFFICE/DocumentServer#637]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
Spreadsheet editor is not able to find and edit previously created print areas in Microsoft Excel. It also fails when downloading file with print area. After checking it in excel it losts.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open Microsoft Excel and create a new file with a print area.
- Upload the created file to the speadsheet editor and try to print it.
- It will fail to find out the exact lines of print area, print preview of the file in spreadsheet editor is not same as in Excel.
- You can check with Excel again by downloading it to computer. It is not the same file as it was created. Print area lost.
- This is an important problem for us. 
- Demo file is attached...
- It is also a problem in document editor.

[PRINT AREA DEMO.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3569961/PRINT.AREA.DEMO.xlsx)

**What is the expected behavior?**
It should recognize the print area created by Excel.

**Did this work in previous versions of DocumentServer?**
No.

**DocumentServer version:**
5.4.0.17

**Operating System:**
Windows 10 64 Bit

**Browser version:**
Chrome 64 bit - v. 76.0.3809.132

**Comment by Rita-Bubnova** [comment]
Hello, @ilyasokay.
Thank you. I can confirm - this is a bug, issue 42693 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue occurs because the "Page break" feature is not yet supported in the Spreadsheet Editor.
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/588.
