### ISSUE TITLE
Can turned off spell checking option by default?

### ISSUE THREAD

**Issue by wangruofeianccl** [ONLYOFFICE/DocumentServer#639]
Can turned off spell checking option by default?How to set default off?

**Comment by Rita-Bubnova** [comment]
Hello, @wangruofeianccl.
Unfortunately, now there is no way to disable spell checking by default.
I created a new issue 42696 in our private issue tracker.
Thank you for your enhancement.

**Comment by wangruofeianccl** [comment]
@Rita-Bubnova Ok, thanks!

**Comment by trofim24** [comment]
We added [spellcheck](https://api.onlyoffice.com/editors/config/editor/customization#spellcheck) option in version 6.0.0

**Comment by nobt854** [comment]
> We added [spellcheck](https://api.onlyoffice.com/editors/config/editor/customization#spellcheck) option in version 6.0.0
@trofim24 
This property is only valid for preview documents, not for editing documents

**Comment by ShockwaveNN** [comment]
@nobt854 Not sure if this is true, please create a new issue (with all necessary data), maybe it's just a bug
