### ISSUE TITLE
Spreadsheet Editor - Unselect filter does not fully remove filter

### ISSUE THREAD

**Issue by mpass3** [ONLYOFFICE/DocumentServer#643]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The Filter button does is not enabled if you select new fields beside an original table, even if you removed the filter on the original table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a table in the spreadsheet, 
2. Select that table and push the filter button. It creates the filtered table.
3. Select a cell in that table and push the filter button. It removes the filter.
4. Add a column with data beside the original filtered columns.
5. Try to select the old filtered columns, and the new column you want to add to the filter. The filter button is greyed out and you are unable to add the new column to the filtered table.

**What is the expected behavior?**
Unfiltering the table should remove the filter from the table, when selecting and additional column to add, the filter button should be enabled to allow for a full table to be selected.

**Did this work in previous versions of DocumentServer?**
Unknown

**DocumentServer version:**
OnlyOffice Cloud hosted by OnlyOffice.com

**Operating System:**
Windows 10

**Browser version:**
Chrome 76

**Comment by mpass3** [comment]
Another example;

1. Remove the filter from a table
2. Copy those cells.
3. Paste the table somewhere else. The filter reappears.

**Comment by Rita-Bubnova** [comment]
Hello, @mpass3.
I'm not sure, I understand correctly your problems.
Please, attach a video with their demonstration.

**Comment by mpass3** [comment]
Hi Rita,

Well, now I can't because whatever it was that was broken yesterday is working today. I cannot replicate even in the original sheet... I will repost bug and take video if it happens again.
