### ISSUE TITLE
Configure default unit of measurement and paper size?

### ISSUE THREAD

**Issue by hifihedgehog** [ONLYOFFICE/DocumentServer#645]
Related to issue #564, I would like the ability to change the default unit of measurement and paper size. It is handy that cookies can help settings persist between documents once a user has set them from their browser. I attempted changing the region to en-us but that did not change the default unit of measurement or paper size when accessing from a clean browser session or a different browser. It would be convenient if these settings could be configured with a global default within the app.js configuration file.

**Comment by ShockwaveNN** [comment]
@hifihedgehog Hi, thanks for ideas.
For unit of measurement I created issue in our internal issue tracker - 42788, I think we'll implement it in some future version.

For `page size` - could you specify - you want to set default page size by name, like `A4`, or by exact size (for some custom size)

**Comment by SLYtiger16** [comment]
Could the defaults be set by the region. For example: Region is US then use US letter and inch.

**Comment by ShockwaveNN** [comment]
Oh, seems I forgot to close this issue.
Setting unit of mesaurement imeplemnted (see https://api.onlyoffice.com/editors/config/editor/customization#unit)

Setting of page size is not implement, since original user didn't answer any question about how to do it.
I'm closing this issue

@SLYtiger16 please create new issue about paper size

**Comment by ShockwaveNN** [comment]
Setting unit of measures implemented at https://github.com/ONLYOFFICE/web-apps/commit/2ee40024e7f5ea00c6cdfeac6cca5743b01021ac

**Comment by SLYtiger16** [comment]
@ShockwaveNN Could you advise how to edit this setting for all users? Is it the /etc/onlyoffice/documentserver/default.json? I have scoured the internet and cannot find _where_ to change this, and my default.json has none of the parameters listed in the referenced documentation.

**Comment by ShockwaveNN** [comment]
@SLYtiger16 Those parameters should be edited not in DocumentServer configs, but in configs of integration with your file storage service (nextcloud, owncloud, your own)
