### ISSUE TITLE
URL-parser grab ending dot

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#646]
**Do you want to request a *feature* or report a *bug*?**
*UX bug*

**What is the current behavior?**
When you paste URL to document or in a comment at a cell and add ending dot, parser change text to hyperlink with a target with a dot at the end. Certainly, according to RFC 3986 Appendix B, it is absolutely right but in MS Office, Slack, and many other programs it works otherwise.

**What is the expected behavior?**
Parser drop ending dot in URL

**DocumentServer version:**
5.3.2.20 and 5.4.0.21

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Please describe the steps to reproduce the problem or attach a video showing the problem.
How exactly do you add a hyperlink?

**Comment by RuslanGabbasov** [comment]
![in OnlyOffice](https://user-images.githubusercontent.com/20418709/65588715-6c3a4e80-dfa1-11e9-810f-94da3484b077.gif)
![In MS Office](https://user-images.githubusercontent.com/20418709/65588734-765c4d00-dfa1-11e9-99a6-53bcfde2daa6.gif)

**Comment by Rita-Bubnova** [comment]
Thank you, @RuslanGabbasov. 
I can confirm the error when entering the hyperlink in the comment - issue 42962 in our issue tracker.

**Comment by Rita-Bubnova** [comment]
This problem has been fixed (https://github.com/ONLYOFFICE/web-apps/commit/13aef92894d84914b0916a2b18effaf2772b2ce9) and will be available in future versions.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.

**Comment by RuslanGabbasov** [comment]
I think you hurried to close the bug
Document server v5.5 works the same like previous version.
![end dot](https://user-images.githubusercontent.com/20418709/76402730-a0fe5e80-63a5-11ea-94e3-88f7606ddd83.gif)

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov maybe we have not completly fixed in all cases
@Rita-Bubnova please take a look

**Comment by RuslanGabbasov** [comment]
It's okey, not need to additional check.
