### ISSUE TITLE
Open error in Internet explorer 11. Interface language is not the same as Google

### ISSUE THREAD

**Issue by wangruofeianccl** [ONLYOFFICE/DocumentServer#647]
Open normal under Google, open error report under Internet explorer 11, interface language is not consistent with Google, as shown in the figure below:
Google：
![image](https://user-images.githubusercontent.com/25164718/65020247-6b7d3900-d95f-11e9-9e13-9dcee9079b0d.png)

Internet explorer 11：
![image](https://user-images.githubusercontent.com/25164718/65020406-bb5c0000-d95f-11e9-8774-c1d7450d16ee.png)

**Comment by wangruofeianccl** [comment]
![image](https://user-images.githubusercontent.com/25164718/65020626-1db50080-d960-11e9-94cd-491fd2f1cb95.png)

**Comment by Rita-Bubnova** [comment]
Hello, @wangruofeianccl.
Thank you. I can confirm - this is a bug, issue 42845 in our internal issue tracker.

**Comment by ShockwaveNN** [comment]
Fixed at https://github.com/ONLYOFFICE/web-apps-pro/commit/5a129c700d4e23c636a1edc270e9e3b0ffda9ddb

DocumentServer 5.4.1 with this fix is released
