### ISSUE TITLE
On big tables in document editor text cursor slows down

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#649]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
![cursor slows down](https://user-images.githubusercontent.com/20418709/65142582-78b42980-da2c-11e9-8aa0-81e7d549f18b.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a big table (more than 100-200 rows on 15-20 pages) and start to write text in a cell.
Only one user edit document.
Bug reproduced every time on different computers.
If I write a text under the table, the cursor works properly.

**DocumentServer version:**
5.3.2.20, 5.4.0.21

**Operating System:**
Windows 10
Core i5-7400 16 Gb

**Browser version:**
Mozilla Firefox Quantum, Google Chrome and other

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Can you attach file XLSX with problem?

**Comment by RuslanGabbasov** [comment]
This problem affects DOCX editor, not XSLX

**Comment by RuslanGabbasov** [comment]
https://drive.google.com/file/d/1taPV3b6-OBNhAs7l6Vlu0qjEhqpW62Za/view
I understood the problem. It reproduced if cell longer than 1 page.

**Comment by Rita-Bubnova** [comment]
Sorry for the typo (meaning DOCX file).
I can confirm - this is a bug, issue 42872 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
Issue 42872 has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/5c2293cba7a85aa5174e83c64931bc716990e436) and will be released in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.
