### ISSUE TITLE
The font name in onlyoffice does not support the Chinese language.

### ISSUE THREAD

**Issue by wudiMD** [ONLYOFFICE/DocumentServer#651]
If the font name was changed into  Chinese name. Then its name will be shown as "????"

**Comment by ShockwaveNN** [comment]
@wudiMD Hi, could you attach file with such font name

**Comment by wudiMD** [comment]
> @wudiMD Hi, could you attach file with such font name
Thank you for your reply. I have use a kind of font editor to change the font name to its chinese name. But the chinese name can not be display in the interface correctly.
[华文中宋.zip](https://github.com/ONLYOFFICE/DocumentServer/files/3644716/default.zip)

**Comment by ShockwaveNN** [comment]
@wudiMD Thanks. I can confirm - this is some bug. I created issue 42926 in our private issue tracker

**Comment by wudiMD** [comment]
Thank you very much. Actually I think the problem is about the decode function which is used to decode the font name.

**Comment by ShockwaveNN** [comment]
Issue should be resolved by https://github.com/ONLYOFFICE/core/commit/7faa83eb8ae029f5c23375ea13ea508fe69617d3

And fixed in DocumentServer 5.4.1, which already released.
Closing this issue, feel free to comment
