### ISSUE TITLE
Presentation editor remove animation in PowerPoints slides

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#654]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Presentation editor doesn't show but remove an animation from elements in PPTX.

**What is the expected behavior?**
It's possible to skip animation because this feature still not realized but it does not admit to removing it from a file.

**DocumentServer version:**
5.3.2.20 and 5.4.0.21

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov. 
Thank you. I can confirm - this is a bug, issue 42961 in our internal issue tracker.

**Comment by trofim24** [comment]
We fixed this in version 6.3.0

**Comment by ShockwaveNN** [comment]
Fixed by https://github.com/ONLYOFFICE/core/commit/ceb0d864f5af8825acb14f9a3df3dceaf23ff4e8
