### ISSUE TITLE
Failed to fetch icu source codes

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#656]
**What is the current behavior?**
1. While building core:
`DocumentServer/core/Common/3dPart/make.sh`
There is https://github.com/ONLYOFFICE/core/blob/a76e93cea65c9183886522c372844de12a2d8f0a/Common/3dParty/icu/fetch.sh#L57
`svn export http://source.icu-project.org/repos/icu/tags/release-$ICU_MAJOR_VER-$ICU_MINOR_VER/icu4c ./icu
`

Which cause:
```
svn: E175011: Unable to connect to a repository at URL 'http://source.icu-project.org/repos/icu/tags/release-58-2/icu4c'
svn: E175011: Repository moved temporarily to 'http://site.icu-project.org/repository'; please relocate
```

According to 
http://site.icu-project.org/repository
![image](https://user-images.githubusercontent.com/668524/65869496-3e7b4e00-e383-11e9-8969-49a25f90f579.png)

And I think we should use git to clone icu sources:

**DocumentServer version:** 5.4.1

**Operating System:** Ubuntu 18.04

**Comment by agolybev** [comment]
Fixed by https://github.com/ONLYOFFICE/core/pull/198

**Comment by ShockwaveNN** [comment]
Can confirm, fixed on `master`
