### ISSUE TITLE
Document editor replaces embedded visio schemes with static images

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#660]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
After editing a document with embedded Visio schemes all of them replaces in a final document with static images, this behavior is different from embedded excel tables, they are remain in the editable state after editing in OnlyOffice.

**DocumentServer version:**
5.3.1.20-5.4.1.39

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Can you attach file  with embedded Visio schemes?

**Comment by RuslanGabbasov** [comment]
[embedded visio example](https://drive.google.com/file/d/1O9AhTh4bdL40u8NsZ8GMKqzjJB7C6jpz/view?usp=sharing)

**Comment by Rita-Bubnova** [comment]
@RuslanGabbasov, thanks for the attached file.
I can confirm - this is a bug, issue 43071 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue has been fixed (https://github.com/ONLYOFFICE/core/commit/5075d49b402246284bd7ee647a7d128d7e7ea0a3, https://github.com/ONLYOFFICE/sdkjs/commit/5a6ff119f0126e6878d85474a9fa137cc4a1f36c) and will be released in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.
