### ISSUE TITLE
Row sizes automatically resize when push enter on filter tables

### ISSUE THREAD

**Issue by SolarDesalination** [ONLYOFFICE/DocumentServer#662]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When have a cell with multiple lines, I have the row sized to show all the text. However if I edit the text in the cell and push enter, it default resizes to a single row line. I have to manually resize the row height again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a filter table with multiple rows and columns
Wrap a cell. Resize the cell to be larger than the normal cell height.
Insert multiple lines of text in that cell with alt+enter. Push enter.
The cell will resize to the single height. Sometimes. Sometimes it doesn't. It's random.

**What is the expected behavior?**
When you resize a cell height with wrap on, it doesn't resize.

**Did this work in previous versions of DocumentServer?**
Not since 5.3 when I started using.

**DocumentServer version:**
5.4 (Cloud OnlyOffice)

**Operating System:**
Windows 10

**Browser version:**
Chrome 77

**Comment by Rita-Bubnova** [comment]
Hello, @mpass3.
Can you attach file with problem?

**Comment by Rita-Bubnova** [comment]
@mpass3, it seems I was facing a similar problem (43095 in our internal issue tracker). 
Already fixed and will be released in future major release.

**Comment by trofim24** [comment]
We fixed this in version 5.5.0
