### ISSUE TITLE
XLS (with conditional formatting) ->XLSX converter makes file corrupted

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#665]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
XLS (with conditional formatting) ->XLSX converter makes file corrupted. After opening converted files in MS Excel it will can't be saved again. [file converter-error](https://drive.google.com/open?id=1YYXkMcUoYNHHX3lqWwbY_Nq74P5Kp3CD)

**DocumentServer version:**
5.3.2 - 5.4.1

**Comment by trofim24** [comment]
We fixed this in version 5.5.0

**Comment by ShockwaveNN** [comment]
Fixed by https://github.com/ONLYOFFICE/core/commit/06b5f0e8b86081033d0819d80db8827aa2b7459f
