### ISSUE TITLE
"ghost" cache files and database entries

### ISSUE THREAD

**Issue by slater0013** [ONLYOFFICE/DocumentServer#668]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** 
When using the prepare for shutdown script, before upgrading onlyoffice to 5.4.1, there are still documents in the file cache and database entries in task_result and doc_changes tables !

Garbage Collector log files are empty, is there something I am missing ?

**DocumentServer version:** 5.3.4

**Operating System:** Debian 9

PS: I ajusted the following in local.json
{
  "services": {
    "CoAuthoring": {
      "expire": {
        "sessionidle": "10m",
	"files": 900
[...]
}

Thanks !
GS

**Comment by ShockwaveNN** [comment]
Hi, seems this is a really-really old issue and we've missed it, sorry

Could you clarify if you still using our system and if this issue is still actual on latest stable v7.1.1?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
