### ISSUE TITLE
Context menu action «Start new list» crashes document editor

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#669]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
When I invoke a context menu on a fourth line and click Start new list editor crushes:
![start-new-list-crash](https://user-images.githubusercontent.com/20418709/66986469-6cc59100-f0d8-11e9-8138-1459660150e2.gif)

[example document](https://drive.google.com/file/d/1sb4fNzwOvCHjo25Ur3LdvXKh5QodV97P/view?usp=sharing)

**DocumentServer version:**
5.3-5.4

**Browser version:**
Chrome, Firefox

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Thank you. I can confirm - this is a bug, issue 43224 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue has been fixed and will be released in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.

**Comment by RuslanGabbasov** [comment]
I don't want to upset you, but it doesn't work too.
![numberlist](https://user-images.githubusercontent.com/20418709/76406815-33096580-63ac-11ea-93eb-80029863d0f7.gif)

**Comment by ShockwaveNN** [comment]
Are you sure you upgrade process of DocumentServer finished correctly?
I just checked this scenario and can confirm with docker of `documentserver-ie` 5.4.1.39 error happens and with Docker `documentserver-ie` 5.5.0.165 there is no error

**Comment by RuslanGabbasov** [comment]
It was first question that I have asked myself ) And I have checked it twice:
![image](https://user-images.githubusercontent.com/20418709/76418658-d1072b00-63c0-11ea-8f5c-73d80b2eaf9d.png)
Tomorrow I'll check it on different machine. On the off-chance.

**Comment by ShockwaveNN** [comment]
I think this maybe something to do with browser cache
I rechecked again and I'm sure that your error is fixed in 5.5.0.165
Please make sure in browser debugger (Chrome devtools for example) you have correct version in file path 5.5.0-165

![image](https://user-images.githubusercontent.com/668524/76421560-ec6c3900-63b4-11ea-9c74-5a3ecd54f327.png)

**Comment by RuslanGabbasov** [comment]
Oh, sorry, it's my bad.
Strangest thing has happened, in my case it was image tagged by latest version but contains previous.
I can confirm that all works properly, thanks a lot!

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov this may be happen if you run container with `docker run onlyoffice/documenserver:latest` - in that case it just use latest image you already download

To run actual latest version of container you should first run `docker pull onlyoffice/documentserver:latest` and after that use `docker run`
