### ISSUE TITLE
DocumentServer on Centos 8

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#670]
**What is the current behavior?** Cannot resolve dependencies on Centos 8

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Try to install DocumentServer on Centos via https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

Several troubles are found:
1. `nodejs` repo is not required, since by default Centos 8 comes with nodejs 10
2. `rabbitmq` is not found. Could be installed via this instruction:
https://computingforgeeks.com/how-to-install-rabbitmq-on-rhel-8/
3. After that installing DocumentServer cause:
```
$ sudo yum install onlyoffice-documentserver-ie
Failed to set locale, defaulting to C
Last metadata expiration check: 0:02:51 ago on Fri Oct 18 17:00:52 2019.
Error: 
 Problem: conflicting requests
  - nothing provides gtkglext-libs needed by onlyoffice-documentserver-ie-5.4.1-39.x86_64
  - nothing provides supervisor >= 3.0b2 needed by onlyoffice-documentserver-ie-5.4.1-39.x86_64
  - nothing provides policycoreutils-python needed by onlyoffice-documentserver-ie-5.4.1-39.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Need to update instruction or use some other sources of packages

**DocumentServer version:** 5.4.1

**Operating System:** Centos 8

**Comment by QwertyVVA** [comment]
Hi, I can not find gtkglext-libs and policycoreutils-python for CentOS 8. Maybe you have already compiled from source?

**Comment by ShockwaveNN** [comment]
Still actual as of 2020.01.07 with:
```
[virtualbox@localhost tmp]$ sudo yum install onlyoffice-documentserver
Failed to set locale, defaulting to C
onlyoffice repo                                                                                                   466 kB/s | 754 kB     00:01    
Last metadata expiration check: 0:00:01 ago on Tue Jan  7 11:45:32 2020.
Error: 
 Problem: conflicting requests
  - nothing provides policycoreutils-python needed by onlyoffice-documentserver-5.4.2-46.x86_64
  - nothing provides gtkglext-libs needed by onlyoffice-documentserver-5.4.2-46.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by elkekou** [comment]
Hi,
Same problem for me.
Just a precision  policycoreutils-python seems to be renamed in policycoreutils-python-utils.noarch so just an adjustement in rpm onlyoffice depencies.
Problem still exist fort gtklext-libs.
Any workaround somewhere? Perhaps need to open bugzilla @redhat

**Comment by ShockwaveNN** [comment]
@elkekou we just discussed this problem and `gtklext-libs` is not needed by us, we remove it in future update.
But since `policycoreutils-python` rename in Centos8, but we do not want to drop support of Centos7 or create separate package for Centos8 currently we have no ideal solution.
You can try manually install `policycoreutils-python-utils` and `--skip-broken` on DocumentServer install

**Comment by elkekou** [comment]
Thanks for your reply the 'skip-broken' for now does not work perhaps because dnf search gtklext-libs.
I'll try the next update as soon it will be available.

**Comment by fperget** [comment]
You can try the following rpm to alias the renamed package and install the other one :

Import gtkglext-libs from winswitch
`curl -o /etc/yum.repos.d/winswitch.repo https://winswitch.org/downloads/CentOS/winswitch.repo`

Create a file named policycoreutils-python-compact.spec with the following content :

```
Name:       policycoreutils-python-compact
Version:    1
Release:    1
Summary:    None
License:    FIXME
Provides:	policycoreutils-python
Requires:	policycoreutils-python-utils

%description
policycoreutils-python compat package

%prep
# we have no source, so nothing here

%build
# we have no source, so nothing here

%install
# we have no source, so nothing here

%files
# we have no source, so nothing here

%changelog
# let's skip this for now
```

then rpmbuild -ba policycoreutils-python-compact.spec

then rpm -iv ~/rpmbuild/RPMS/x86_64/policycoreutils-python-compact-1-1.x86_64.rpm

You should be able to install onlyoffice-documentserver now

**Comment by elkekou** [comment]
thanks it work like a charm.

**Comment by ShockwaveNN** [comment]
Issue fixed by https://github.com/ONLYOFFICE/document-server-package/commit/19b36be3b05f39a70c14be4b0c7abe264fed01ea (pirvate repo) and will be available in next major release

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.

**Comment by dstaykov** [comment]
Will test tomorrow and report here!

**Comment by dstaykov** [comment]
Works perfect!

**Comment by ShockwaveNN** [comment]
@dstaykov Glad to hear :+1:
