### ISSUE TITLE
how to generate a document.key，what are the rules?

### ISSUE THREAD

**Issue by ice-waves** [ONLYOFFICE/DocumentServer#671]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ice-waves** [comment]
![image](https://user-images.githubusercontent.com/21362901/67382938-e372fa80-f5c0-11e9-9df1-300af00181f6.png)
when I open a new file, it occurred.....

**Comment by ice-waves** [comment]
window.docEditor = new DocsAPI.DocEditor("placeholder",
        {
            "document": {
                "fileType": "xlsx",
                "key": "c0367a6e1db1ca4",
                "title": "xxxmmm.xlsx",
                "url": "http://oa2.user1.com/legal/contract-attachment/4490/3a3feabf0cce06ca4d078b113f7187b1/9205d9286fbb611d4e63a2f7a7bba38c/1571825831/0/show",
                "permissions": {
                    "comment": false,
                    "download": false,
                    "edit": false,
                    "fillForms": false,
                    "print": false,
                    "review": false
                },
            },
            "documentType": "spreadsheet",
            "editorConfig": {
                "callbackUrl": "",
                "customization": {
                    "chat": false,
                    "comments": false,
                    "help":false
                },
                "mode": "view"
            },
            "height": "100%",
            "width": "100%"
        });

this is my config

**Comment by ice-waves** [comment]
@ShockwaveNN

**Comment by ShockwaveNN** [comment]
https://api.onlyoffice.com/editors/config/document

**Comment by ice-waves** [comment]
![image](https://user-images.githubusercontent.com/21362901/67384016-e969db00-f5c2-11e9-9c75-53be4249f597.png)

I tried, but I still got an error. 
Is the mistake due to the wrong key？:) @ShockwaveNN

**Comment by ShockwaveNN** [comment]
Maybe error is because file url is not accesseble?

For me `wget http://oa2.user1.com/legal/contract-attachment/4490/3a3feabf0cce06ca4d078b113f7187b1/9205d9286fbb611d4e63a2f7a7bba38c/1571825831/0/show` cause `unable to resolve host address ‘oa2.user1.com’`, but for you it may work

Also look at logs

**Comment by ice-waves** [comment]
@ShockwaveNN 
emm, the url is in my local environment,  i can access the link by curl in my local docker. 
![image](https://user-images.githubusercontent.com/21362901/67387838-38673e80-f5ca-11e9-9208-e823bf267bad.png)


I just met another question：different key，different url，access the same file ？

![image](https://user-images.githubusercontent.com/21362901/67388159-bc212b00-f5ca-11e9-8cbb-2e81f7885eaa.png)
![image](https://user-images.githubusercontent.com/21362901/67388204-ce02ce00-f5ca-11e9-81fc-c87761061095.png)

**Comment by ShockwaveNN** [comment]
> I just met another question：different key，different url，access the same file ？

sorry, have no idea, take a look at requests from DocumentServer on load file

**Comment by ice-waves** [comment]
> > I just met another question：different key，different url，access the same file ？
> 
> sorry, have no idea, take a look at requests from DocumentServer on load file

I got answer, the response header need  "Accept-Ranges:bytes" :)
