### ISSUE TITLE
Ability to disable drag n drop and cut/paste of content control

### ISSUE THREAD

**Issue by ar27111994** [ONLYOFFICE/DocumentServer#678]
**Do you want to request a *feature* or report a *bug*?**
question: is there a possibility to have an ability to disable drag n drop and cut/paste of content control either via config or via plugins/sdkjs api?
**What is the current behavior?**
Don't know
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A
**What is the expected behavior?**
to have an ability to disable drag n drop and cut/paste of content control either via config or via plugins/sdkjs api
**Did this work in previous versions of DocumentServer?**
Don't know
**DocumentServer version:**
5.4.1.39
**Operating System:**
Linux
**Browser version:**
74.0.3729.169

**Comment by ShockwaveNN** [comment]
Hi, are you sure `fillForms` parameter for DocumentEditor or DocumentViewer is not enought for you?
https://api.onlyoffice.com/editors/config/document/permissions#fillForms

Am I understand correctly - you want user to not be able to copy content from content control input? I don't really think this is very logical

**Comment by ar27111994** [comment]
Hi @ShockwaveNN , no, `fillForms` disables all operations of every content control in view mode, whereas we can assign individual permissions to content controls in edit mode as well, via `Control Settings` dialog, the problem is that user is able to `Cut` a content control from the document even if that content control is locked for deletion.
![image](https://user-images.githubusercontent.com/13036687/68407960-4316fb80-01a6-11ea-926a-4edb435a9c4c.png)
![image](https://user-images.githubusercontent.com/13036687/68408028-65107e00-01a6-11ea-9b46-d7407f994a7c.png)

**Comment by Rita-Bubnova** [comment]
Hello, @ar27111994.
Thank you.
This know issue (41049 in our private tracker) fixed https://github.com/ONLYOFFICE/sdkjs/commit/b799344d9697fd60e0fb5f3daa6a05c859ba0cd5 and will be released in future major release.

**Comment by trofim24** [comment]
We fixed this in version 5.5.0
