### ISSUE TITLE
Provide Windows Server Package

### ISSUE THREAD

**Issue by cetra3** [ONLYOFFICE/DocumentServer#68]
Wondering if we can get the newer versions above 3 as a windows package?

**Comment by ibnpetr** [comment]
Hello 
At the moment windows version is [available](http://www.onlyoffice.com/integration-request.aspx) as a commercial product only.
Thanks a lot for your interest in our product.
Keep in touch

**Comment by agolybev** [comment]
Windows version is available since v5.0.3
