### ISSUE TITLE
Load only different sheet that have access righ

### ISSUE THREAD

**Issue by widechina** [ONLYOFFICE/DocumentServer#680]
How to set each people load only different sheet that have access right?

Thanks.

**Comment by Rita-Bubnova** [comment]
Hello, @widechina.
Do you want us to implement different sheet permissions or share  specific sheets to different persons? Fill out issue template correctly (may be issue #488).

**Comment by widechina** [comment]
Thanks for you support!

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
