### ISSUE TITLE
Compiling DocumentServer Error

### ISSUE THREAD

**Issue by filedos** [ONLYOFFICE/DocumentServer#681]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
core compile
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

An error occurred while compiling core && 3dpart. The error message is as follows:

`In file included from ../memorystream.h:39:0,
                 from ../memorystream.cpp:32:
../../../Common/3dParty/v8/v8/include/v8.h:3012:5: note: candidate: v8::String::Value::Value(v8::Isolate*, v8::Local<v8::Value>)
     Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~
../../../Common/3dParty/v8/v8/include/v8.h:3012:5: note:   candidate expects 2 arguments, 1 provided
../memorystream.cpp: In function ‘void _ms_copy(const v8::FunctionCallbackInfo<v8::Value>&)’:
../memorystream.cpp:98:44: error: no matching function for call to ‘v8::Value::ToUint32()’
     size_t pos = (size_t)args[1]->ToUint32()->Value();
                                            ^
In file included from ../memorystream.h:39:0,
                 from ../memorystream.cpp:32:
../../../Common/3dParty/v8/v8/include/v8.h:2529:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^~~~~~~~
../../../Common/3dParty/v8/v8/include/v8.h:2529:44: note:   candidate expects 1 argument, 0 provided
../memorystream.cpp:99:44: error: no matching function for call to ‘v8::Value::ToUint32()’
     size_t len = (size_t)args[2]->ToUint32()->Value();
                                            ^
In file included from ../memorystream.h:39:0,
                 from ../memorystream.cpp:32:
../../../Common/3dParty/v8/v8/include/v8.h:2529:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^~~~~~~~
../../../Common/3dParty/v8/v8/include/v8.h:2529:44: note:   candidate expects 1 argument, 0 provided
../memorystream.cpp: In function ‘void _ms_pos(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’:
../memorystream.cpp:113:36: warning: unused parameter ‘name’ [-Wunused-parameter]
 void _ms_pos(v8::Local<v8::String> name, const v8::PropertyCallbackInfo<v8::Value>& info)
                                    ^~~~
../memorystream.cpp: In function ‘v8::Handle<v8::ObjectTemplate> CreateMemoryStreamTemplate(v8::Isolate*)’:
../memorystream.cpp:123:68: error: no matching function for call to ‘v8::ObjectTemplate::New()’
     v8::Local<v8::ObjectTemplate> result = v8::ObjectTemplate::New();
                                                                    ^
In file included from ../memorystream.h:39:0,
                 from ../memorystream.cpp:32:
../../../Common/3dParty/v8/v8/include/v8.h:6107:32: note: candidate: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(
                                ^~~
../../../Common/3dParty/v8/v8/include/v8.h:6107:32: note:   candidate expects 2 arguments, 0 provided
../../../Common/3dParty/v8/v8/include/v8.h:6283:32: note: candidate: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::internal::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(internal::Isolate* isolate,
                                ^~~
../../../Common/3dParty/v8/v8/include/v8.h:6283:32: note:   candidate expects 2 arguments, 0 provided
../memorystream.cpp:119:72: warning: unused parameter ‘isolate’ [-Wunused-parameter]
 v8::Handle<v8::ObjectTemplate> CreateMemoryStreamTemplate(v8::Isolate* isolate)
                                                                        ^~~~~~~
Makefile:364: recipe for target '../core_build/linux_64/release/obj/memorystream.o' failed
make[1]: *** [../core_build/linux_64/release/obj/memorystream.o] Error 1
make[1]: Leaving directory '/onlyoffice/DocumentServer/core/DesktopEditor/doctrenderer/doctrenderer.build'
Makefile:288: recipe for target 'build/lib/linux_64/libdoctrenderer.so*' failed
make: *** [build/lib/linux_64/libdoctrenderer.so*] Error 2
`

**What is the expected behavior?**
DocumentServer compile is successful.

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
last 
**Operating System:**
ubuntu18.4
**Browser version:**
None

**Comment by zacharyrs** [comment]
@filedos, I'm just wondering how you fixed this?
