### ISSUE TITLE
Cells does raise property not found in script and spreadsheets dont open

### ISSUE THREAD

**Issue by martinspaeth** [ONLYOFFICE/DocumentServer#683]
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
* Spreadsheets don't open in onlyoffice with javascript error:

```
Uncaught TypeError: Cannot read property 'ucb' of undefined
    at onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all.js:35244
    at onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all.js:39538
    at onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all.js:274744
```

and 
```
Uncaught TypeError: Cannot read property 'ma' of undefined
    at e.ma (onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all-min.js:575)
    at e.se (onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all-min.js:575)
    at Pa.ijc (onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all-min.js:763)
    at Pa.ijc (onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all-min.js:934)
    at HTMLScriptElement.Pa (onlyoffice.example.com/5.4.1-39//sdkjs/cell/sdk-all-min.js:730)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Run nextcloud and install onlyoffice as app (running in docker). 
images:
* nextcloud:15.0.5 
* onlyoffice/documentserver:5.4.1.39

open a spreadsheed

**What is the expected behavior?**
the sheets open 

**Did this work in previous versions of DocumentServer?**
yes also docs and presentations work fine
**DocumentServer version:**

**Operating System:**

**Browser version:**
chrome

**Comment by martinspaeth** [comment]
quick update it works with 
onlyoffice/documentserver:5.4.0.21

**Comment by Rita-Bubnova** [comment]
Hello, @martinspaeth.
Could you attach file with problem?

**Comment by martinspaeth** [comment]
All files, also a new one

**Comment by ShockwaveNN** [comment]
@martinspaeth could you look for log files for other errrors? Seems something went wrong during update

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
