### ISSUE TITLE
Co-edit fast mode not working reliably on long files

### ISSUE THREAD

**Issue by drikqlis** [ONLYOFFICE/DocumentServer#684]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When editing long docx file (approx. 75 pages, only text, 130kb) co-edit fast mode is not working reliably. On a new almost empty file 2 users can write simultaneously without interrupting each other. When file is long, input for one user is blocked when the other is typing until the changes are synced (which is visibly delayed compared to seamless sync when the file is almost empty). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create docx file and fill it with approx. 75 pages of plain text.
2. Share the file to other user.
3. Try to co-edit file in fast mode.

**What is the expected behavior?**
Co-editing should be working reliably on every kind of file, files as big as 100mb are supported and 75 pages of text is only ~150kb, sync shouldn't be delayed.

**Did this work in previous versions of DocumentServer?**
No.

**DocumentServer version:**
OnlyOffice DocumentServer 5.4.1 integrated with Nextcloud 16.0.5 by OnlyOffice Nextcloud app 3.0.2

**Operating System:**
Ubuntu 18.04.2 LTS

**Browser version:**
Firefox 70.0.1
Chrome 78.0.3904.97

**Comment by drikqlis** [comment]
The problem still persists on OnlyOffice DocumentServer 5.5, can anybody reproduce?

**Comment by ShockwaveNN** [comment]
Hi there, seems we should fixed this problem some releses ago, probably in 6.1 but I'm not sure

Could you please state is this problem actual in DocumentServer v6.3.1?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
