### ISSUE TITLE
How to have document server with other host in same server

### ISSUE THREAD

**Issue by ejgutierrez74** [ONLYOFFICE/DocumentServer#689]
I have a LEMP instance with ubuntu 18.04 ...

My /etc/hosts:
127.0.0.1 localhost 
127.0.0.1 nextcloud.eduardo.com 
127.0.0.1 onlyoffice.eduardo.com

I have a working instance of nextcloud in: nextcloud.eduardo.com, and i want that document server would run in onlyoffice.eduardo.com...

I have installed document server using deb package as your documentation says....
Also would like that default server would be localhost pointing to /var/www/html as usual...

I can get it to work as i dont know how to setup document server with nginx...

Here is all my configuration nginx in /etc/nginx
https://drive.google.com/drive/u/1/folders/1I2ZiRUKqmm8u5U5TsqyoOKUvfTwY-SPA

Thanks in advance

**Comment by ShockwaveNN** [comment]
Hi there, sorry for late restonse, seems we missed this issue

Please state is this problem still actual for you?

And generally speaking I don't thinks it's a good idea use native versions of packaged on one server - I think for your situation docker image of DocumentServer is more appropriate

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
