### ISSUE TITLE
Chinese font garbled,仿宋_GB2312

### ISSUE THREAD

**Issue by sdls10qq** [ONLYOFFICE/DocumentServer#69]
I am upload a file.The document have  仿宋_GB2312 font.Chinese characters are not displayed properly。
I am installed 仿宋_GB2312 in linux system.by step 
cd /usr/share/fonts/
tar cv * | docker exec -i onlyoffice-document-server tar x -C /usr/share/fonts/
docker exec onlyoffice-document-server /usr/bin/documentserver-generate-allfonts.sh
But Chinese characters are still not displayed properly。
![20161222171721](https://cloud.githubusercontent.com/assets/6747741/21420830/c6b96da6-c86a-11e6-846c-2e0be66595f5.png)

**Comment by iehyxue** [comment]
我感觉一般多刷两遍就好了。。。。。你打完中文紧再接着打个标点，中文会不会重复？

**Comment by K0R0L** [comment]
請用英語寫作 )

**Comment by K0R0L** [comment]
We are not experts in the Chinese language, so we are grateful for the help. It would be the exact scenario.
1) What browser and version.
2) What are the key press and in which order.
Thank you!

**Comment by sdls10qq** [comment]
I am upload a file to Community Server,then open it.
![20161223202738](https://cloud.githubusercontent.com/assets/6747741/21453844/592a631e-c94e-11e6-8c6a-5f42ff4c73ef.png)

**Comment by JohnPerkin** [comment]
Dear ONLYOFFICE users!
We are working hard on implementation of asian fonts in Document Server. So we need both standard and non-standard fonts to analyze their behaviour in our product. Please send us fonts via support@onlyoffice.com or attach them to your messages. We will appreciate your assistance.
Best regards
John
ONLYOFFICE support team

**Comment by chicol** [comment]
@iehyxue 
我也遇到你说的问题了，打完中文再打标点符号，中文会重复输出。
现在还没解决？

**Comment by iehyxue** [comment]
@chicol  in document advanced setting, choose Alternate Input  :Turn on hieroglyphs
try this way

**Comment by chicol** [comment]
@iehyxue thanks for you reply. It works well.
I have another question, did you meet it?
I upload one document which created in windows. The text wrote in "宋体" font.
The character is garbled when open it on onlyoffice.

**Comment by ShockwaveNN** [comment]
@chicol if issue is still actual - could you attach file?

**Comment by zjutzhz** [comment]
@iehyxue 试试IE IE下没这个问题

**Comment by ShockwaveNN** [comment]
This issue is being closed due to no response
