### ISSUE TITLE
Changes lost and file keep locked

### ISSUE THREAD

**Issue by kevindenight** [ONLYOFFICE/DocumentServer#691]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

While first websocket closed fast unexpected for some reason, another websocket connection will be start in web client, then there will be two **'auth'** message sent to server via this websocket connection. 
After that your will see "Document is currently being edited by several users. kevindenight@gmail.com(2)". 
Click "Reload this page" in browser several times, the "kevindenight@gmail.com(x)" becomes (3) (4) (5)... .
This file remain locked forever after back to our website.

This problem is reported by our users, i try hard to reproduce it and find the reason finally.

We reproduce this problem by editing codes in sever/DocService/sources/DocsCoServer.js :

```
let first = true;
...
exports.install = function(server, callbackFunction) {
  sockjs_echo.on('connection', function(conn) {     return co(function* () {
...
    conn.on('data', function() {...}
    conn.on('error', function() {...}
    conn.on('close', function() {...}

    if (first) {
      first = false;
      setTimeout(function () {
        first = true;
      }, 10000);
      conn.close();
      return;
    }

    _checkLicense(conn);
  });
...
};
```

After several days we figure out a solution: prevent web client sending "auth" message twice.
Here is codes in sdkjs/common/docscoapi.js:
```
  DocsCoApi.prototype.auth = function(isViewer, opt_openCmd, opt_isIdle) {
    if (this.sockjs._authSent) return;
...
    this._send({});

    this.sockjs._authSent = true;
  };
```

Does this solution fix this problem correctly? Maybe your guys have batter solution?

**DocumentServer version:**

5.3.4

**Comment by konovalovsergey** [comment]
Thanks. Nice issue.
