### ISSUE TITLE
documentserver high load without doining anything

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#692]
**Do you want to request a *feature* or report a *bug*?**
bug?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

just installed documentserver and recompile spellchecker and for the first test opend a document and file cant be loaded. Since jesterday the documentserver 2 prozesses have 100% CPU 
```
node --max_old_space_size=4096 /var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js 
node /var/www/onlyoffice/documentserver/server/DocService/sources/gc.js     
```                                      
cant find any file that has to be converted 
reboot, supervisorctl restart all dont help 

**DocumentServer version:**
5.4.1
**Operating System:**
Debian 10
node --version
v10.15.2

**Browser version:**

**Comment by Akrobs** [comment]
You need to use Node JS v8.x with OO DS

**Comment by hahaxd35** [comment]
> You need to use Node JS v8.x with OO DS

Nope another Server with Debian 10 and Node JS v10 work

**Comment by hahaxd35** [comment]
Maybe found my own solution:
i have custom  /etc/onlyoffice/documentserver/log4js/production.json 

```
{
"appenders": {
        "default": {
                "type": "file",
                "filename": "/var/log/onlyoffice/node.log",
                "backups": "7",
                "compress": "true"
        }
},
        "categories": {
                "default": { "appenders": [ "default" ], "level": "DEBUG" }
            }
    }
```
After chown -R ds:ds /var/log/onlyoffice and supervisor restart all it works again 
.... damn it
