### ISSUE TITLE
In the spreadsheet editor, if add filter with frozen row shows visual artifacts.

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#696]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
When I add filter in the spreadsheet with frozen title shows visual artifacts
![filter with fixed row](https://user-images.githubusercontent.com/20418709/69137136-f30d3280-0add-11ea-86a3-6a60ffe25c6c.gif)

[example spreadsheet](https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_100.xlsx)

**DocumentServer version:**
5.4.1.39

**Operating System:**
Windows 10

**Browser version:**
Chrome, Firefox

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Thank you. I can confirm - this is a bug, issue 43581 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
@RuslanGabbasov, your issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/8697e4673a315b9c9e959075968ceb16904c87f4 and will be released in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
