### ISSUE TITLE
Issue Opening Word Document

### ISSUE THREAD

**Issue by zacharyrs** [ONLYOFFICE/DocumentServer#697]
I'm suffering from a bug when opening a word document.
In particular, the page simply displays the loading screen, with the following in devtools.

```
fonts.js:40 Uncaught TypeError: qe.zEb is not a function
    at fonts.js:40
    at fonts.js:40
fonts.js:25 Uncaught (in promise) TypeError: f.AscFonts.zEb is not a function
    at bc (fonts.js:25)
    at Ia (fonts.js:11)
    at e (fonts.js:18)
    at wb (fonts.js:19)
    at Jm (fonts.js:34)
    at f (fonts.js:12)
    at w (fonts.js:12)
Promise.then (async)
db @ fonts.js:14
Xc.asm @ fonts.js:25
sdk-all.js:1057 Uncaught TypeError: d.AscFonts.zEb is not a function
    at sdk-all.js:1057
    at sdk-all.js:1057
    at sdk-all.js:10013
sdk-all-min.js:559 Uncaught TypeError: Cannot read property 'ma' of undefined
    at e.ma (sdk-all-min.js:559)
    at e.we (sdk-all-min.js:559)
    at Da.Oa.Adc (sdk-all-min.js:674)
    at Da.Adc (sdk-all-min.js:911)
    at HTMLScriptElement.Oa (sdk-all-min.js:648)
```

I'm running OnlyOffice 5.4.1 on Archlinux, built per [onlyoffice aur](https://aur.archlinux.org/packages/onlyoffice-documentserver/). I'm using an up-to-date (v78) Chrome browser.

Interestingly, the spreadsheet editor can open a document completely fine.

**Comment by zacharyrs** [comment]
As an aside, the spellchecker also appears to be facing issues, returning `Cannot GET /spellchecker/doc/2f047b4036ae1d2f8a4d/c/info` for every page. I can't see what's wrong with it though... Should I open a second issue for this?

**Comment by ShockwaveNN** [comment]
@zacharyrs Hi, does this error happened on any document or some specific?
Seems this may be some troubles with generating font files, please look at logs of documentserver on installation

**Comment by zacharyrs** [comment]
Seems to happen on word documents in general, though I'll try with a blank one this afternoon. 

Regarding the logs, I didn't see anything running as development mode, are there some flags I should use for verbose output?

**Comment by ShockwaveNN** [comment]
@zacharyrs I may have something to to with `aur` and arch, please not we currently do not support Arch you may contact maintainers of this package, or you may better try to use Docker version of DocumentServer

**Comment by zacharyrs** [comment]
Unfortunately the previous maintainer seems to have disappeared, so I adopted the package. I've tweaked it only slightly to compile 5.4.1.

As far as I can tell, I'm pretty much following [this](https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx).

The doesn't seem to be much documentation otherwise, like for configuring logging etc, or perhaps I'm just missing it?

**Comment by ShockwaveNN** [comment]
If you give some system with this error reproducable I'll try to look at it, but currently I don't know there to start

**Comment by zacharyrs** [comment]
Would it be sufficient to just set up a docker image running arch?

**Comment by ShockwaveNN** [comment]
@zacharyrs yeah, Docker is fine

**Comment by zacharyrs** [comment]
Sweet, I'll put that together asap.

**Comment by zacharyrs** [comment]
Unfortunately seems that docker doesn't behave nicely with fakeroot...

I don't have time to pursue this further right now, but when I get a chance I'll reopen this.

**Comment by ShockwaveNN** [comment]
@zacharyrs If you'll be able to combine an virtualbox image it'll fine too. Any way I get to reproduce the problem
