### ISSUE TITLE
Document server doesn't send callback with "status": 2 when a connection to user drops physically

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#698]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
When a user opens a document the document server sends first callback [status: 1 actions type: 1]. After that, if user close browser as normally we receive the second callback [status: 1 action type: 0]. But if the connection between the user and the document server drops with some networks problem (physically disconnection or proxy reconnection, VPN/SSH-tunnel problems, etc) second callback doesn't send. The document from the document server can be saved when the next user opens this document next time and close it, but information about the first user is lost forever.

**Example log 1:**
```
User opened the document:
{"key":"9a673cc6876cc60cd061b3acbeb48ad588b787214d7885c304701d57c3005d37","status":1,"users":["1319"],"actions":[{"type":1,"userid":1319}]}

Connection was temporary unavailable and user refreshed browsers tab with the save config for the  DocumentServer:
{"key":"9a673cc6876cc60cd061b3acbeb48ad588b787214d7885c304701d57c3005d37","status":1,"users":["1319"],"actions":[{"type":1,"userid":1319}]}

The user closed the page:
{"key":"9a673cc6876cc60cd061b3acbeb48ad588b787214d7885c304701d57c3005d37","status":2,"url":"https://host/editor/cache/files/9a673cc6876cc60cd061b3acbeb48ad588b787214d7885c304701d57c3005d37_9555/output.docx/output.docx?md5=WJGswOfD6h1_Et44HQOpWQ&expires=1573821073&disposition=attachment&ooname=output.docx","changesurl":"https://host/editor/cache/files/9a673cc6876cc60cd061b3acbeb48ad588b787214d7885c304701d57c3005d37_9555/changes.zip/changes.zip?md5=wfyrD-B4TII7LrBBIxjkNQ&expires=1573821073&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.4.1","changes":[{"created":"2019-11-15 05:50:16","user":{"id":"1319","name":"Габбасов Руслан"}}]},"users":["1319"],"actions":[{"type":0,"userid":1319}],"lastsave":"2019-11-15T12:15:50.407Z","notmodified":false}
```
There were no other activities from the Document server.

**Example log 2:**
```
User A opened the document:
{"key":"f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8","status":1,"users":["1319"],"actions":[{"type":1,"userid":1319}]}

User B opened the document:
{"key":"f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8","status":1,"users":["1358"],"actions":[{"type":1,"userid":1358}]}

User B reopened the document with the same config for the Document Server:
{"key":"f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8","status":1,"users":["1358"],"actions":[{"type":1,"userid":1358}]}

User B sent request "info" to the CommandService with with userData "kickAllRequest":
{"key":"f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8","status":1,"users":["1358"],"userdata":"kickAllRequest"}

For all users from previous callback with userData was sent command "drop" 
{"key":"f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8","status":2,"url":"https://host/editor/cache/files/f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8_6323/output.docx/output.docx?md5=cNtADICpdnijQsMC4S9pcQ&expires=1574082851&disposition=attachment&ooname=output.docx","changesurl":"https://host/editor/cache/files/f9a8780d26cc9846c0ed69e3b23f076d42b6e1a7f8d6d713f8fcf57af61ae2d8_6323/changes.zip/changes.zip?md5=hL2_rsnWDn-cpLbyCW3U6Q&expires=1574082851&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.4.1","changes":[{"created":"2019-11-18 11:51:54","user":{"id":"1319","name":"Габбасов Руслан"}}]},"users":["1319"],"actions":[{"type":0,"userid":1358}],"lastsave":"2019-11-18T12:47:42.466Z","notmodified":false}
```
There were no other activities from the Document server too.

**What is the expected behavior?**
The second callback about users exiting is always expected.

**DocumentServer version:**
5.4.1

**Comment by hahaxd35** [comment]
if i understand you right you need to configure:
/etc/onlyoffice/documentserver/default.json 

and change default values in /etc/onlyoffice/documentserver/local.json (just a snip) 
`{
  "services": {
    "CoAuthoring": {
      "callbackBackoffOptions": {
        "retries": 100,
        "timeout": {
          "factor": 2,
          "minTimeout": 1000,
          "maxTimeout": 60000,
          "randomize": false
        },
        "httpStatus": "429,500-599"
      },`

**Comment by RuslanGabbasov** [comment]
No, it's different situation, connection between the Document Server and our service stays stable but when connection between user and Document Server lost without WebSocket Close Handshake (without opcode 0x08 sending) it seems that Document Server forgets about this user connection and recollect about it only if other users open it with the same document key.

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov Hi, our dev team seems that something is odd in this setup, maybe to quick reconnect is the reason.
Could you enable detailed logs in DocumentServer (like this https://github.com/onlyoffice-testing-robot/doc-linux-docker-updater/blob/master/after-run.sh#L7) and try to reproduce the problem

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
