### ISSUE TITLE
spreedsheet with drop-down blocked after modifying cell

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#699]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Spreadsheet blocked with an error "Une erreure s'est produite lors du travail avec le document"
(aprox."An error occurred when working with the document")
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
File : [test drop-down_liste déroulante.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3874289/test.drop-down_liste.deroulante.xlsx)
Try to modify B6 cell
**What is the expected behavior?**
Be able to modify the cell
**Did this work in previous versions of DocumentServer?**
Unknown
**DocumentServer version:**
5.4.1
**Operating System:**
Client Windows10
**Browser version:**
Firefox 70.0.1 and other browsers

**Comment by Rita-Bubnova** [comment]
Hello, @cpot.
Thank you. I can confirm - this is a bug, issue 43608 in our internal issue tracker.

**Comment by cpot** [comment]
First of all, I wish a very good year to Onlyoffice team. Success to all of you and your great product

Back to work :)
I imagine that this bug will not be corrected before drop-down implementation ?

**Comment by Rita-Bubnova** [comment]
Hello, @cpot! Thanks for the good wishes.
This issue has been fixed and will be released in future major release, but drop-down list has not yet been implemented.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
