### ISSUE TITLE
chinese font not display correctly

### ISSUE THREAD

**Issue by sidealice** [ONLYOFFICE/DocumentServer#7]
is this problem caused by font or built in library?

**Comment by AnaMih** [comment]
In order to resolve the issue, please, set chinese fonts in *.aff and *.dic to 
/etc/fonts/ And restart Onlyoffice Spellchecker Service. After that you should choose the font for your document.
For chinese language may be used the following fonts: Ming Liu, Pming Liu, Dotum Che

Also you may find the information here: http://helpcenter.onlyoffice.com/server/windows/document/install-fonts.aspx

**Comment by sidealice** [comment]
thanks for your help , i would try to follow your way. by the way how to contribute to the project, I would like to make this update to the core and help other chinese clients to use it.

**Comment by AnaMih** [comment]
I regret to inform you that we do not currently have ssh protocol.
Feel free to fork the repo and continue working.

**Comment by sidealice** [comment]
thanks now get the font worked , but still not perfect. because if my original document was wrote in Chinese, when I open it , the document not rendered in Chinese by default. I have to select all text and choose the font again. Is this an improvement for the software or it was caused by the font missing or font auto detection issue on the server?

**Comment by AnaMih** [comment]
This is standard situation. The algorithm is: if the necessary font is not found the editors select the most suitable. (usually - arial font)
There are two solutions:
1) download the complete Arial font package (free for home usage only)
2) change the document fragments with incorrect symbols to the font that supports necessary characters

**Comment by eqmo** [comment]
I solve the issue with this:

apt-get install fonts-arphic-ukai
    cd /usr/share/fonts/
    tar cv * | docker exec -i XXX tar x -C /usr/share/fonts/
    docker exec XXX  /var/www/onlyoffice/documentserver/Tools/GenerateAllFonts.sh
where XXX is the container ID


Then clear cache browser and logon again.

**Comment by hisys3122** [comment]
Chinese font not display correctly in onlyoffice spreadsheet chart ?

**Comment by ibnpetr** [comment]
Please describe the issue more detailed and send us an examle for analyzing
Make sure that the fonts are installed

**Comment by hisys3122** [comment]
Our test server:

1. OS -> CentOS Linux release 7.2.1511 (Core)
2. Docker -> 1.8.2  10.el7.centos
3. Server -> HP DL360 G8
4. onlyoffice documentserver -> image download from DockerHub
5. chinese fonts -> copy from windows 7 and installed correctly.  

We open the "Sample Spreadsheet" file, and change Rank 1 "USA" to Chinese fonts, chinese font not display correctly in the chart. 

Screenshot is in the attache file.

![chinese_error](https://cloud.githubusercontent.com/assets/17635086/13559249/f1688922-e44c-11e5-81aa-f538286aff16.png)

**Comment by ibnpetr** [comment]
Hello
The feature is planned for future versions, at the moment areal font only can be used in the chart inside the spreadsheet.

**Comment by JohnPerkin** [comment]
Dear ONLYOFFICE users!
We are working hard on implementation of **asian** fonts in Document Server. So we need both standard and non-standard fonts to analyze their behaviour in our product. Please send us fonts via support@onlyoffice.com or attach them to your messages. We will appreciate your assistance.
Best regards
John
ONLYOFFICE support team

**Comment by leangjia** [comment]
@JohnPerkin 
Dear John!
Thanks for for your reply this issues.
I am Chinese, and I am more concerned about this problem.
Is it working right now?

**Comment by agolybev** [comment]
Hi @leangjia. Thank you for intresting for Document Server. 
It's difficult feature, so we are still working on it.

**Comment by jianbosu** [comment]
my doc 's Chinese fonts is ok,but the interface have some trouble.....
![tim 20171205150642](https://user-images.githubusercontent.com/17507066/33594269-3ba2fd92-d9ce-11e7-80fb-d20f077013b0.png)

**Comment by agolybev** [comment]
Hi @jianbosu, could you provide us this document?

**Comment by jianbosu** [comment]
@agolybev [你的姓名.docx](https://github.com/ONLYOFFICE/DocumentServer/files/1645640/default.docx)

**Comment by jianbosu** [comment]
@agolybev i delete all file in /usr/share/fonts,  then cp my font into it.    and run Then run the script: documentserver-generate-allfonts.sh    &&      Clear the browser cache and reopen the page. Everything is worked perfect.
![tim 20180119160237](https://user-images.githubusercontent.com/17507066/35140440-33612460-fd32-11e7-9ab2-30656cce5a3c.png)

**Comment by JoeLucky** [comment]
Hi, @jianbosu .  'my font',  your font means which fonts？

**Comment by JoeLucky** [comment]
@jianbosu  Did you delete all the fonts except Chinese fonts? So onlyoffice force all words to Chinese fonts. I donot think that is a good practice.

**Comment by jianbosu** [comment]
@JoeLucky yes，i copy some Chinese fonts into your system，and delete all others，clear browser cache，at the end  everything will be work perfect。
![1](https://user-images.githubusercontent.com/17507066/35509246-6ce2555c-052e-11e8-8c8f-cd144b8b526e.png)

**Comment by 3xxx** [comment]
@jianbosu 请问你的界面是如何变成中文的？
How does your interface become Chinese?


![snap6](https://user-images.githubusercontent.com/10678867/36362489-4bb55d5a-1570-11e8-8f45-8abeb9cd8eb3.jpg)

**Comment by 3xxx** [comment]
THANK you，According to your method, now is ok. thank you。
 ```
"editorConfig": {
                    "callbackUrl": "http://192.168.99.1/url-to-callback?id={{.Doc.Id}}",
                    "user": {
                        "id": "{{.Uid}}",
                        "name": "{{.Uname}}"
                    },
                    "lang": "zh-CN",//"en-US",
                },
```

**Comment by xwinfo** [comment]
@3xxx 请问这个配置"editorConfig":  在哪个文件里面修改呢？

**Comment by tangpeibin123456** [comment]
在哪里加的

**Comment by 3xxx** [comment]
https://github.com/3xxx/ONLYOFFICE-golang
@xwinfo 就是你调用的页面里啊。
```
<!DOCTYPE html>
<html style="height: 100%;">
<head>
    <title>fei-OnlyOffice</title>
</head>
<body style="height: 100%; margin: 0;">

    <div id="placeholder" style="height: 100%"></div>
    <script type="text/javascript" src="http://192.168.99.100:9000/web-apps/apps/api/documents/api.js"></script>
    <script type="text/javascript">
        // alert({{.Doc.FileName}});
        window.docEditor = new DocsAPI.DocEditor("placeholder",
            {
                "document": {
                    "fileType": "{{.fileType}}",
                    "key": "{{.Key}}",//"Khirz6zTPdfd7"
                    "title": "{{.Doc.FileName}}",
                    "url": "http://192.168.99.1/attachment/onlyoffice/{{.Doc.FileName}}"
                },
                "documentType": "{{.documentType}}",
                "editorConfig": {
                    "callbackUrl": "http://192.168.99.1/url-to-callback?id={{.Doc.Id}}",
                    "user": {
                        "id": "{{.Uid}}",
                        "name": "{{.Uname}}"
                    },
                    "lang": "zh-CN",//"en-US",
                },
                "height": "100%",
                "width": "100%"
            });
    </script>
</body>
</html>
```

**Comment by 3xxx** [comment]
https://github.com/neroxps/Docker-Only-Office-Chinese-font
中文字体。

**Comment by 3xxx** [comment]
有20个连接限制，不是一个文件限制20个连接，是整个限制20个连接，假如有几个文档编辑，很容易就突破20个人了。超过的连接只能读，不能编辑。

**Comment by linmsh** [comment]
为什么我的字体显示“yahei”而不显示“微软雅黑”

**Comment by jcklpe** [comment]
Is this solution still valid? I installed new fonts on my host machine and they are not showing up in my onlyoffice instance. I tried running ` docker exec XXX /var/www/onlyoffice/documentserver/Tools/GenerateAllFonts.sh` but it did not work. I ssh'd into the docker container and there does not appear to be a Tools folder as specified in this solution. 

Any clue on how to fix this issue?

**Comment by jcklpe** [comment]
Okay found the info. GenerateAllFonts is now in the usr/bin folder of the docker container. 

I ran the script though and it didn't work.

**Comment by jcklpe** [comment]
I'm manually `docker cp` the fonts files into onlyoffice:/usr/share/font and run the generate font script and while now the files appear on the frontend of the instance, the actual fon is incorrect and it automatically tries to turn the text into a different unrelated font (which judging by it's name just happens to be whatever the next font is in line alphabetically)

**Comment by punkyard** [comment]
> Okay found the info. GenerateAllFonts is now in the usr/bin folder of the docker container.

Hi,
if fonts are added to the container, won't they be deleted after restart?

**Comment by Hicutecow** [comment]
I use the onlyoffice at android . How can I write the chinese?

**Comment by trofim24** [comment]
@Hicutecow we're working on this problem on mobile app. You can try to use our mobile web version
