### ISSUE TITLE
When copying texts from a odt file some words are stuck

### ISSUE THREAD

**Issue by LAfricain** [ONLYOFFICE/DocumentServer#701]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
CTRL+V from a odt file some words are stuck together. A space is lacking between them.
**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Write a text in LibreOffice, Copy the text, Paste it in OnlyOffice. See some words stuck together. 
But If I use to paste in text only I don't have this issue. And I don't have this issue with Google docs, I think because Google docs works with odt standard.
**What is the expected behavior?**
The formatting should be respected
**Did this work in previous versions of DocumentServer?**
NO
**DocumentServer version:**
5.4.1
**Operating System:**
Ubuntu 18.04
**Browser version:**
Firefox 68.0.2

![stickedword](https://user-images.githubusercontent.com/19690477/69436371-3f8b8480-0d0f-11ea-9a14-47a0eb5ca43e.png)

**Comment by Rita-Bubnova** [comment]
Hello, @LAfricain.
Can you attach file ODT with problem?

**Comment by LAfricain** [comment]
file with problem:
[example.zip](https://github.com/ONLYOFFICE/DocumentServer/files/3880529/example.zip)

**Comment by LAfricain** [comment]
I can add that when importing an other odt file with pictures, I lost all the layout.

**Comment by Rita-Bubnova** [comment]
Thank you. I can confirm - this is a bug, issue 43632  in our internal issue tracker.

> I can add that when importing an other odt file with pictures, I lost all the layout.

Could you create new issue and attach file?

**Comment by LAfricain** [comment]
>  Could you create new issue and attach file?

#706

**Comment by Rita-Bubnova** [comment]
This issue has been fixed (https://github.com/ONLYOFFICE/core/commit/b48406c941f7871a4b9b507fab9f5af295b5b38a) and will be released in future major release.

**Comment by LAfricain** [comment]
OK спасибо и да здравствует Россия!

**Comment by mvvvmd** [comment]
Has this issue been resolved in the 5.5 release of the onlyoffice-documentserver?

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.
