### ISSUE TITLE
Questions for number of users

### ISSUE THREAD

**Issue by sinichi19** [ONLYOFFICE/DocumentServer#704]
1st nice work for onlyoffice..

I already integrate the latest onlyoffice on our nextcloud17 my question is, where onlyoffice depends the number of users on the server hardeware side? or the community edition have limitations for 20 users only.

because i have more than 100 users it means only 20 can open docu simultaneously?

thank you

**Comment by ShockwaveNN** [comment]
@sinichi19 Hi, only Community Edition has limitation of 20 users simultaneously
You can compare editions at https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions

**Comment by sinichi19** [comment]
> @sinichi19 Hi, only Community Edition has limitation of 20 users simultaneously
> You can compare editions at https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions

thank you for reply..
it means this tutorial https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx
if i upgrade more hardware = more users..

i confuse sorry is the document server is different to community server.

thank you

**Comment by ShockwaveNN** [comment]
> upgrade more hardware = more users

Generally speaking - yes

>  document server is different to community server.

Yes, DocumentServer and CommunityServer is completly different products

**Comment by sinichi19** [comment]
> > upgrade more hardware = more users
> 
> Generally speaking - yes
> 
> > document server is different to community server.
> 
> Yes, DocumentServer and CommunityServer is completly different products

thank you sir for clarifications
