### ISSUE TITLE
504 Gateway Time-out  / TypeError: Cannot read property 'length' of undefined for `require('os').cpus().length;`

### ISSUE THREAD

**Issue by kinimodmeyer** [ONLYOFFICE/DocumentServer#705]
when i want to connect my cloud to the document server i get after a while the following error: 

```
Server error response [url] https:\/\/cloud.secret.de:1443\/ConvertService.ashx [status code] 504 [reason phrase] Gateway Time-out
```

when i go into the document server docker i can see that  convert is not running.
in the log /var/log/onlyoffice/documentserver/converter/err.log i have the following:

```
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js:18:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js:18
  const numCPUs = require('os').cpus().length;
```

any ideas how i can fix this problem. it is a complete new install from manual

when i fix the meantion errors like descriped on https://github.com/nodejs/node/issues/19022 with 
```
const cpus = (require('os').cpus() || { length: 1 }).length
```

the service comes up. but what will be the correct number?

**Comment by ShockwaveNN** [comment]
@kinimodmeyer Hi, this is strange. Seems something went wrong during DocumentServer installation, please specify DocumentServer version, type of installation and OS type and nodejs version

**Comment by kinimodmeyer** [comment]
hello @ShockwaveNN thanks for the answer.
i upgraded the last days my systems to debian 10 buster.
now i don´t have the problem anymore.

i remember that it was nodejs.
os type was debian stretch.
document-server the last docker pull.

i think we can close it. if someone have simular problem he knows he should maybe upgrade :slightly_smiling_face:

**Comment by ShockwaveNN** [comment]
@kinimodmeyer Oh, glad for you but was very interested in problem, never seen anything before )
Thanks anyway
