### ISSUE TITLE
Importing odt file with pictures, layout lost

### ISSUE THREAD

**Issue by LAfricain** [ONLYOFFICE/DocumentServer#706]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Layout well kept
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Layout kept
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.4.1
**Operating System:**
Ubuntu 18.04
**Browser version:**
Firefox 68.0.2

**Comment by Rita-Bubnova** [comment]
Hello.
@LAfricain, can you attach file ODT with problem?

**Comment by LAfricain** [comment]
I have a problem with privacy on the files in general. I accept to share it with you but after one hour I'll remove it.
[Présentation_de_tib.zip](https://github.com/ONLYOFFICE/DocumentServer/files/3887170/Presentation_de_tib.zip)

**Comment by Rita-Bubnova** [comment]
Thank you the attached file. 
I can confirm - this is a bug, issue 43643 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue has been fixed (https://github.com/ONLYOFFICE/core/commit/fd1bc80682693d7d620a135d5ce466081686629c) and will be released in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
