### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#712]
**Do you want to request a *feature* or report a *bug*?**
need help 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

we use a proxy for internal use. But server can see each other. Is there any spezial configuration for proxy use? witch ports needs to be allowed? i know port 8080 is in use but need  i to allow this in proxyto or is this only for localhost? all other installation was without any proxy.

thanks for help!

**Comment by hahaxd35** [comment]
FYI i found 
document-server-proxy/nginx but dont know if this config is up to date and i dont know witch config file i have to replace.

**Comment by agolybev** [comment]
Hi @hahaxd35, first see the article [Using Document Server behind the proxy](https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx). Next, choose suitable config depended on your proxy server type.

**Comment by hahaxd35** [comment]
okay and any but all configs in /etc/onlyoffice/documentserver/nginx/includes ?
and dont replace any file?

**Comment by hahaxd35** [comment]
are this configuration files for documentserver or for proxyserver?
