### ISSUE TITLE
Threaded comment added by the spreadsheet editor unsupported in MS Office 2013-2019

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#713]
Today we have noticed that comments added by the spreadsheet editor unsupported in MS Office 2013-2019. Excel shows notification about it: 
> [Threaded comment]
> 
> Your version of Excel allows you to read this threaded comment; however, any edits to it will get removed if the file is opened in a newer version of Excel. Learn more: https://go.microsoft.com/fwlink/?linkid=870924
> 
> Comment:
>     Тестовый комментарий

I don't understand what the version of MS Office needs to able to edit these documents.
In my opinion, this feature must be configurable because it makes backward incompatibility with classical desktop editors.

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
This is a known and rather complicated issue (42948 in our private tracker). We are thinking about its solution and plan to release in future release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.

**Comment by RuslanGabbasov** [comment]
This problem wasn't be solved too. All version of Excel except 365 show incompatibility notification before comments. In my humble opinion best solution of this problem might be configurable option to use/not use threaded comments in spreadsheets.
