### ISSUE TITLE
print titles in excel not take effect

### ISSUE THREAD

**Issue by yoyomule** [ONLYOFFICE/DocumentServer#714]
**Do you want to request a "" report a *bug*?**
bug.
**What is the current behavior?**
Hello, I set the print title in excel and set the top two lines as the title. But I found that this setting does not take effect when outputting in onlyoffice. Can you consider adding this function.

**Did this work in previous versions of DocumentServer?**
No.
**DocumentServer version:**
5.3.7
**Operating System:**
Centos
**Browser version:**
Chrome 79

**Comment by Rita-Bubnova** [comment]
Hello, @yoyomule.
Thank you for your enhancement.
I created a new issue 43869 in our private issue tracker.

**Comment by dengwoadeng** [comment]
Mainly when the excel file is turned out to pdf with api, the title will not take effect.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/web-apps/commit/35164b41af5a276281b1cc3b8802bb077a881b00, https://github.com/ONLYOFFICE/web-apps/commit/8d88fe6acaa8077f0d5fa38c422bff5953dbbb77) in future release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
