### ISSUE TITLE
How do I limit editable cells？How do I verify that the current edit is valid?

### ISSUE THREAD

**Issue by hzdjulytech** [ONLYOFFICE/DocumentServer#719]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
I wanted to limit the editable cells and input of XLSX but could not find the relevant callback method
 
**DocumentServer version:**
5.4.2

**Comment by ShockwaveNN** [comment]
Hi, currently we do not support protecting sheet or any area of sheet.
Discuessed here https://github.com/ONLYOFFICE/DocumentServer/issues/488
