### ISSUE TITLE
Fonts break on server after running documentserver-generate-allfonts.sh [Bug]

### ISSUE THREAD

**Issue by jcklpe** [ONLYOFFICE/DocumentServer#720]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I wanted to add a font to my docker instance. 
I followed information found in this issue: https://github.com/ONLYOFFICE/DocumentServer/issues/7

The result is now no fonts work properly. The fonts I installed are visible on the frontend: 
![image](https://user-images.githubusercontent.com/9451726/71029006-14107580-20d4-11ea-9464-2e342c03ebf6.png)

 but any piece of text changed to them in the editor will just change to whatever font comes next in the alphabet (so in this case trying to change the text to Merriweather will change it to Mukti Narrow)

![image](https://user-images.githubusercontent.com/9451726/71028645-55545580-20d3-11ea-8ff2-2d5759f3d114.png)

Additionally now ALL fonts don't work properly. When I write a new document and try to set the font to "Arial Black" it looks exactly like if I try to write something in Comic Sans. 

![image](https://user-images.githubusercontent.com/9451726/71028759-8df42f00-20d3-11ea-8032-8363ad7456db.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I just used a standard container hooked up to Nextcloud, installed using the defaults of this ansible playbook: https://github.com/ReinerNippes/nextcloud

**What is the expected behavior?**
I should be able to change fonts 

**Did this work in previous versions of DocumentServer?**
I've never tried before
**DocumentServer version:**
Version 4 of the nextcloud app
Version 5.4.2 of OnlyOffice
https://github.com/ReinerNippes/nextcloud

**Operating System:**
Ubuntu 18

**Browser version:**
Firefox 71

**Comment by jcklpe** [comment]
Just tried reinstalling the docker container from scratch and I'm still having the same problems. 

I stopped the container, removed the image, and deleted the volumes, and then reinstalled using the ansible script and it's still broken. Not really sure what's up with that. If it's a browser cache issue or what. I'm getting rid of the cache but it's still showing the old fonts that I tried to install

**Comment by jcklpe** [comment]
Just restarted the container and now the fonts I tried to install are no longer showing up in the frontend  (which is good. They shouldn't be because I reinstalled everything) BUT I'm still having improper rendering of fonts like Arial Black etc.

**Comment by ShockwaveNN** [comment]
@jcklpe Hi, you should clear browser cache (or use incognito mode) after installing new fonts

**Comment by jcklpe** [comment]
@ShockwaveNN Yeah seems to be working now. Thanks!
