### ISSUE TITLE
Unable to update Spellchecker on Ubuntu 18.4

### ISSUE THREAD

**Issue by tridoan** [ONLYOFFICE/DocumentServer#721]
Hello,
Im having an issue with the SpellChecker feature in my installation of OnlyOffice (used within Owncloud). 

I've followed the directions exactly as laid out here numerous times, under the section "Rebuilding spellchecker (Ubuntu 18.04)": https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx

But am seeing an error upon running the command `npm install` with sudo.

![image](https://user-images.githubusercontent.com/1179626/71133274-e4826b80-21ae-11ea-9597-1e56fe11cd87.png)

As a result of this updating error, i believe this is the reason why im seeing this console error on the front-end with regards to the SpellChecker:
![image](https://user-images.githubusercontent.com/1179626/71133177-9ff6d000-21ae-11ea-8abd-925dca485b5c.png)

Any help in finding a solution would be greatly appreciated. Thanks.

**Comment by ShockwaveNN** [comment]
@tridoan Hi, try to google `sudo npm install could not create leading directory`, this is some kind problem with permission and `npm`, there is several solution

**Comment by tridoan** [comment]
I've tried the commands below and still no luck.

`  cd /var/www/onlyoffice/documentserver/server/SpellChecker/
  npm install -g npm
  supervisorctl stop all
  apt-get install build-essential git
  npm install -g
  npm install -g --unsafe-perm
  supervisorctl start all
`

**Comment by ShockwaveNN** [comment]
@tridoan Hi, that are your error in logs?

**Comment by tridoan** [comment]
> @tridoan Hi, that are your error in logs?

I took a look within /var/log/onlyoffice/documentserver/spellchecker/err.log and see a lot of this:

Error: Cannot find module '/var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/package.json',
  requestPath: 'nodehun'
}
internal/modules/cjs/loader.js:305
      throw err;
      ^

**Comment by ShockwaveNN** [comment]
Could not reproduce this problem, I see use use `npm` 6.13.4, but that version of `nodejs` are you using?
From ubuntu repo, or nodejs repo?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
