### ISSUE TITLE
A4 size is not correct when printing spreadsheet document

### ISSUE THREAD

**Issue by OnlyOffsub** [ONLYOFFICE/DocumentServer#723]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

OnlyOffice doesn't keep A4 size page when spreadsheet is printed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open attached file with Excel and print it in PDF :
A4
Customize scaling options

Open PDF file (pdf_with_excel.pdf) : there is 4 pages. you can control size page in document properties is correct [29.70 * 21.00 cm]

Open attached file with OnlyOffice and print it in PDF :
A4
Show all columns on one page

Open PDF file (pdf_with_onlyoffice.pdf) : there is 8 pages. size page in document properties is incorrect [45.78 * 21.00 cm]

**What is the expected behavior?**

When users print in A4 format with OnlyOffice, the size page must be [29.70 * 21.00 cm]

**Did this work in previous versions of DocumentServer?**

no

**DocumentServer version:**

5.4.1

**Operating System:**

Windows 10

**Browser version:**

Chrome Version 79.0.3945.79
[pdf_with_excel.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/3982828/pdf_with_excel.pdf)
[OnlyOffice_size.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3982829/OnlyOffice_size.xlsx)
[pdf_with_onlyoffice.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/3982830/pdf_with_onlyoffice.pdf)

**Comment by Rita-Bubnova** [comment]
Hello, @OnlyOffsub.
This issue has been fixed (https://github.com/ONLYOFFICE/sdkjs/pull/629) and will be released in future major release (version 5.5).

**Comment by OnlyOffsub** [comment]
Hello, thank you... i will wait for this release

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
