### ISSUE TITLE
Array Formula goes missing on reloading document

### ISSUE THREAD

**Issue by DigNZ** [ONLYOFFICE/DocumentServer#724]
**Do you want to request a *feature* or report a *bug*?**
A Bug
**What is the current behavior?**
I have an array formula to take a list from a box in the first 9 columns and make a list of unique values in the 10th column.

It works when entered, and also works when exported to xlsx and opened in Office365 but when reopened in OnlyOffice the list is not working correctly and cannot be fixed without deleteing the 10th column and reentering the array formula.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Put some values in columns A - I
The following formula goes in J2, entered with Shift + Ctrl + Enter to create an array formula and then drag down a number of cells. All the unique values from A4:I25 excluding blanks will be placed into column J
`=
IFERROR(
IFERROR(
IFERROR(
IFERROR(
IFERROR(
IFERROR(
IFERROR(
IFERROR(
IFERROR(
INDEX($A$4:$A$25,MATCH(0,COUNTIF($J$1:J1,$A$4:$A$25)+($A$4:$A$25=""),0)),
INDEX($B$4:$B$25,MATCH(0,COUNTIF($J$1:J1,$B$4:$B$25)+($B$4:$B$25=""),0))),
INDEX($C$4:$C$25,MATCH(0,COUNTIF($J$1:J1,$C$4:$C$25)+($C$4:$C$25=""),0))),
INDEX($D$4:$D$25,MATCH(0,COUNTIF($J$1:J1,$D$4:$D$25)+($D$4:$D$25=""),0))),
INDEX($E$4:$E$25,MATCH(0,COUNTIF($J$1:J1,$E$4:$E$25)+($E$4:$E$25=""),0))),
INDEX($F$4:$F$25,MATCH(0,COUNTIF($J$1:J1,$F$4:$F$25)+($F$4:$F$25=""),0))),
INDEX($G$4:$G$25,MATCH(0,COUNTIF($J$1:J1,$G$4:$G$25)+($G$4:$G$25=""),0))),
INDEX($H$4:$H$25,MATCH(0,COUNTIF($J$1:J1,$H$4:$H$25)+($H$4:$H$25=""),0))),
INDEX($I$4:$I$25,MATCH(0,COUNTIF($J$1:J1,$I$4:$I$25)+($I$4:$I$25=""),0))),
"")`

**What is the expected behavior?**
This works the first time, close and reopen the spreadsheet and the values in Column J will be missing. 

Saving the document as xlsx and opening in Office365 shows the correct data in the column.

**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
I'm running DocumentServer on Docker, latest version.
**Operating System:**
Linux (Client and Server)
**Browser version:**
Chrome and OnlyOffice Desktop Editors show the same behaviour

**Comment by Rita-Bubnova** [comment]
Hello, @DigNZ.
What formula language do you have installed (`File` -> `Advanced Settings ...` -> `General` -> `Regional Settings`)?

**Comment by DigNZ** [comment]
Formula Language: English
Regional Settings: English (United States)

**Comment by Rita-Bubnova** [comment]
@DigNZ, this issue has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/0c30c2ea38db66a4ee4467ad7e1ae387f48cdf1b) and will be released in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
