### ISSUE TITLE
Wrong url ID's accessed by Nextcloud

### ISSUE THREAD

**Issue by casKd-dev** [ONLYOFFICE/DocumentServer#728]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Font ID's have missing 0's before them resulting in a 404 when loading them

Example:
```
0002 - 2
0227 - 227
1202 - 1202
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Put fonts into `/usr/share/fonts`
2. Run `/usr/bin/documentserver-generate-allfonts.sh`
3. Load a document on the online editor (Nextcloud)

**What is the expected behavior?**
Fonts should be accessed with their actual ID

**Did this work in previous versions of DocumentServer?**
Did not test

**DocumentServer version:**
5.2.8.24 (Latest docker image)

**Operating System:**
Ubuntu 16.04 xenial

**Browser version:**
Vivaldi 2.3.1440.48 (Stable channel) (64-bit)
Revision 38c6381358a1ec7a9fc161a038fb9d7407334aa4-refs/branch-heads/3626@{#858}

**Nextcloud version**
RedXen Cloud 15.0.5

**PHP Version**
PHP 7.2.16-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.16-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by ShockwaveNN** [comment]
@casKd-dev Hi again, we still not able to reproduce your issue, could you provide any image or instruction for setting up enviroment like yours

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
