### ISSUE TITLE
Slow Loading Onlyoffice document server on windows server

### ISSUE THREAD

**Issue by OpsHealthcode** [ONLYOFFICE/DocumentServer#730]
Hi,

We are not able to load new doc or sheet & unable to load old docs also.

below is the screenshot on windows server:

![onlyoffice error](https://user-images.githubusercontent.com/48128178/53644372-72ab5680-3c5c-11e9-93d4-24134ea17ea9.JPG)

**Comment by LinneyS** [comment]
Duplicate #522
