### ISSUE TITLE
Porting x2t converter to WebAssembly

### ISSUE THREAD

**Issue by ldubost** [ONLYOFFICE/DocumentServer#731]
Hi,

I am from the CryptPad team which has integrated the editors javascript code inside CryptPad as a pure Javascript application running in the browser to provide spreadsheets feature for our users. 

We have started investigating porting the x2t file converter which imports and exports  spreadsheet files from Excel or LibreOffice, to WebAssembly for running 100% in the browser.

This could be interesting to provide a cross platform build of x2t. In the case of cryptpad it's interesting to allow to preserve user's file privacy by fully running in the browser.

The investigation is a success for a simple xlsx file back and forth running for now in nodejs (browser coming). 

Here is a quick preview: https://photos.google.com/photo/AF1QipNB4S3P3t08P6ffNDmNrtJCX6O9g-mSh0RGXwxc

We have made a docker build here:
https://git.xwikisas.com/caubin/onlyoffice-x2t-wasm/
(this repository also includes a docker build of the onlyoffice core, for which it was difficult to have a working environment, which is why we went the docker way, which is great because reproducible)

and the hacked onlyoffice core branch is here:
https://github.com/ldubost/core/tree/wasm32-5.2.6

I'd be interested to know which features of the spreadsheets and other formats would need to be specifically tested to use more of the code from x2t, as not all libraries have been included (namely doctrenderer, htmlrenderer, pdfviewer, pdfwriter are currently excluded)

**Comment by ShockwaveNN** [comment]
@ldubost Thank you, this is very interesting
@agolybev @trofim24 @SergeyKirillov please take a look at this project

**Comment by ldubost** [comment]
The code has been improved to also include the ICU code and now also works with ods and xls formats.

The complicated part which is not working yet is the code relying on doctrenderer which relies on v8.

**Comment by ShockwaveNN** [comment]
@ldubost Ok, thanks. Currently our team on winter holidays, but I try to get review of this project as soon as holidays end (in a week)

**Comment by trofim24** [comment]
@ldubost
Sorry for late response.

Thanks for your attension.
If we port x2t to wasm the module will be large. We're not planning to do this in the near feature.
And if we're going to do it we'll use our "converter tools" for this operation.
Thanks for understanding.
