### ISSUE TITLE
Onlyoffice can't connect to MySQL

### ISSUE THREAD

**Issue by keuse168** [ONLYOFFICE/DocumentServer#737]
I'm trying to install onlyoffice document server on windows server 2016. I had install MySQL8.0 prior to install the onlyoffice. When the installation step go to confirm installation path and I click next, it popup a window that show can't found database source and didn't define default driver. How can I fix this?

**Comment by Akrobs** [comment]
onlyoffice not support MySQL, use a PostgreSQL DB server.

**Comment by keuse168** [comment]
I had fixed it when I delete the MySQL ODBC drive and let the installer prerequisites re-install that.
