### ISSUE TITLE
Much too small UI when using a Hi-PPI screen

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/DocumentServer#739]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
UI is much too small
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install Onlyoffice Document server
2. plug it in to nextcloud
3. The Onlyoffice UI is much too small

**What is the expected behavior?**
The UI should be bigger so that it is not that small. and better usable from normal distances.
**Did this work in previous versions of DocumentServer?**
don't know
**DocumentServer version:**
don't know. Docker install, so probably the newest version
**Operating System:**
Windows 10
**Browser version:**
Chromium 79 based browser 
**Here is a Screenshot:**
![image](https://user-images.githubusercontent.com/42591237/72005778-aa0c6b80-324e-11ea-9b31-ba8edbb6c091.png)
(just compare the Nextcloud App icons, that have a normal, usable size and the Onlyoffice-UI size in comparison. That shows all problems with that imo. (this is on a 13" inch laptop, and near to unusable state")

**Comment by ShockwaveNN** [comment]
Thanks, this is a known issue. We'll try to fix it in future releases, but cannot give any ETA.
Related issue for DesktopEditors https://github.com/ONLYOFFICE/DesktopEditors/issues/53

**Comment by LuckySpecialist** [comment]
A lot of intermediate scales have been added, so the problem can be closed.
If it is still relevant, you can open it again with details (screen size and resolution in pixels, application version, browser version).
