### ISSUE TITLE
Chinese-font name show character ???

### ISSUE THREAD

**Issue by ToBigToSmall** [ONLYOFFICE/DocumentServer#740]
Hi, developers. I was truck in a problem below. 
![image](https://user-images.githubusercontent.com/33725817/72034802-0021f300-32d1-11ea-8f1c-51fee42314c3.png)

As u can see, I use font-creator modify font file, for exmple, font original name is "SimSun" and I modify to "SimSuntest" then use "documentserver-generate-allfonts.sh" to init font, i work well. But when I try to add Chinese character such as rename to "SimSun宋体", it will show "SimSun??".

And I check file "var/www/onlyoffice/documentserver/sdkjs/common/AllFonts.js" which is init by "documentserver-generate-allfonts.sh" command, the name with Chinese character also show ??.

I try to modify linux system coding but it doesn't work.

Please give me some ideas to deal with random code. 

Thanks!

**Comment by ToBigToSmall** [comment]
correct form like this 
![image](https://user-images.githubusercontent.com/33725817/72036119-d074ea00-32d4-11ea-8fc7-d01469ccb62d.png)

**Comment by Rita-Bubnova** [comment]
Hello, @ToBigToSmall.
Please, attach the font you are using.

**Comment by ToBigToSmall** [comment]
I use font-creator 9.0 to modify step:
![image](https://user-images.githubusercontent.com/33725817/72063697-3bdeac00-3315-11ea-9ec8-8cb0441a26ce.png)

font file orgin / modify is below:
http://gazalle-wuyuefeng.oss-cn-hangzhou.aliyuncs.com/font.zip

**Comment by ToBigToSmall** [comment]
If you want reappear this problem just add the file path "font/change font family by fontcreator/simsun.ttf" to onlyoffice document server path "usr/share/font/" then excuse "/usr/bin/documentserver-generate-allfonts.sh", you can find the same problem.

I try many ways to solve this problem. bless ...

**Comment by K0R0L** [comment]
Hello. Please indicate server version. I fixed this bug.

**Comment by ToBigToSmall** [comment]
Hi KOROL,
    I use onlyoffice/documentserver:5.2.8.24

**Comment by ToBigToSmall** [comment]
I think there may two possible: one is Chinese character may be out of font ASCII range, so it shows random codes. The other one may be linux system or web encoding / decoding not by gbk but use utf-8, it can't decode gbk properly.

**Comment by ToBigToSmall** [comment]
![image](https://user-images.githubusercontent.com/33725817/72123339-e0a3cc80-339b-11ea-871a-27ffa721be22.png)

**Comment by ToBigToSmall** [comment]
result is : 
![image](https://user-images.githubusercontent.com/33725817/72123397-15178880-339c-11ea-85f3-48423ec58844.png)

**Comment by ToBigToSmall** [comment]
then I  use fc-list:
![image](https://user-images.githubusercontent.com/33725817/72123564-a4bd3700-339c-11ea-88c5-cd8fd59bebee.png)

**Comment by K0R0L** [comment]
Please update your version. This bug was fixed in 5.4.2

**Comment by ToBigToSmall** [comment]
I see. thanks!
