### ISSUE TITLE
How to open a spreadsheet with password without typing password?

### ISSUE THREAD

**Issue by VivienZhai** [ONLYOFFICE/DocumentServer#741]
When I use OnlyOffice to open an xlsx file with encrypt password, I don't want to enter the password in the textbox when the file is loading. How can I jump this step?

**Comment by Rita-Bubnova** [comment]
Hello, @VivienZhai.
Please describe in more detail what result do you want to get without entering a password?
Do any other editors implement the behavior you expect?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
