### ISSUE TITLE
Undo/Redo Question

### ISSUE THREAD

**Issue by fangjialong2019** [ONLYOFFICE/DocumentServer#743]
Can undo/redo actions be supported in fast mode collaborative editing. 
By modifying the source code(sdkjs) ,I've implemented it myself, but it's not perfect.

We don't need strict mode, so we simplify the application layer code.(web-apps).
The user is not allowed to switch edit mode to strict

**Comment by trofim24** [comment]
We are working on supporting undo / redo in fast collaborative editing.
In the document and presentation editor, undo is already implemented. There are some difficulties with implementation, because you want to cancel / repeat your action, and not the last action on the document.

**Comment by fangjialong2019** [comment]
In the document and presentation editor, redo is not implemented.
In the spreadsheet editor, undo and redo are not implemented.
I have solved the above problems by modifying the source code, but the solution is not perfect.
Hope the authorities can provide a solution

**Comment by fangjialong2019** [comment]
May I ask when the problem can be solved?

**Comment by fangjialong2019** [comment]
(function(){
    
    var api = Asc['spreadsheet_api'];
    var asc_Range = Asc['Range'];

    function UpgradeCollaborativeUndoRedo(){
        var History = AscCommon.History;
        var isRealObject = AscCommon.isRealObject;
        var oFormulaLocaleInfo = {};
        oFormulaLocaleInfo.Parse = true;
        oFormulaLocaleInfo.DigitSep = true;
        var c_oAscLockTypes = AscCommon.c_oAscLockTypes;
        var Workbook = AscCommonExcel.Workbook;
        var WorksheetView = AscCommonExcel.WorksheetView;
        var WorkbookView = AscCommonExcel.WorkbookView;
        var CCollaborativeEditing = AscCommonExcel.CCollaborativeEditing;
        var CHistory = AscCommon.CHistory;
        var g_memory = AscFonts.g_memory;

        Workbook.prototype.SerializeHistory = function(){
            var aRes = [];
            //соединяем изменения, которые были до приема данных с теми, что получились после.
    
            var t, j, length2;
    
            // Пересчитываем позиции
            AscCommon.CollaborativeEditing.Refresh_DCChanges();
            
            //(vivo):Upgrade Start
            //var aActions = this.aCollaborativeActions.concat(History.GetSerializeArray());
            var aActions
            if (AscCommon.CollaborativeEditing.Is_Fast()) {
                //快速模式（协同编辑）撤销也要发送修改记录
                aActions = this.aCollaborativeActions.concat(History.GetSerializeArrayForCoEdit());
            } else {
                //协同编辑还有严格模式，所以这里保持原汁原味
                aActions = this.aCollaborativeActions.concat(History.GetSerializeArray());
            }
            //(vivo):Upgrade End

            if(aActions.length > 0)
            {
                var oMemory = new AscCommon.CMemory();
                for(var i = 0, length = aActions.length; i < length; ++i)
                {
                    var aPointChanges = aActions[i];
                    for (j = 0, length2 = aPointChanges.length; j < length2; ++j) {
                        var item = aPointChanges[j];
                        this._SerializeHistoryBase64(oMemory, item, aRes);
                    }
                }
                this.aCollaborativeActions = [];
                this.snapshot = this._getSnapshot();
            }
            return aRes;
        };

        Workbook.prototype.DeserializeHistory = function(aChanges, fCallback){
            var oThis = this;
            //сохраняем те изменения, которые были до приема данных, потому что дальше undo/redo будет очищено
            this.aCollaborativeActions = this.aCollaborativeActions.concat(History.GetSerializeArray());
            if(aChanges.length > 0)
            {
                this.bCollaborativeChanges = true;
                //собираем общую длину
                var dstLen = 0;
                var aIndexes = [], i, length = aChanges.length, sChange;
                for(i = 0; i < length; ++i)
                {
                    sChange = aChanges[i];
                    var nIndex = sChange.indexOf(";");
                    if (-1 != nIndex) {
                        dstLen += parseInt(sChange.substring(0, nIndex));
                        nIndex++;
                    }
                    aIndexes.push(nIndex);
                }
                var pointer = g_memory.Alloc(dstLen);
                var stream = new AscCommon.FT_Stream2(pointer.data, dstLen);
                stream.obj = pointer.obj;
                var nCurOffset = 0;
                var aUndoRedoElems = [];
                for (i = 0; i < length; ++i) {
                    sChange = aChanges[i];
                    var oBinaryFileReader = new AscCommonExcel.BinaryFileReader();
                    nCurOffset = oBinaryFileReader.getbase64DecodedData2(sChange, aIndexes[i], stream, nCurOffset);
                    var item = new AscCommonExcel.UndoRedoItemSerializable();
                    item.Deserialize(stream);
                    aUndoRedoElems.push(item);
                }
                var wsViews = window["Asc"]["editor"].wb.wsViews;
                if(oThis.oApi.collaborativeEditing.getFast()){
                    AscCommon.CollaborativeEditing.Clear_DocumentPositions();
                }
                for (var i in wsViews) {
                    if (isRealObject(wsViews[i]) && isRealObject(wsViews[i].objectRender) &&
                        isRealObject(wsViews[i].objectRender.controller)) {
                        wsViews[i].endEditChart();
                        if (oThis.oApi.collaborativeEditing.getFast()) {
                            var oState = wsViews[i].objectRender.saveStateBeforeLoadChanges();
                            if (oState) {
                                if (oState.Pos) {
                                    AscCommon.CollaborativeEditing.Add_DocumentPosition(oState.Pos);
                                }
                                if (oState.StartPos) {
                                    AscCommon.CollaborativeEditing.Add_DocumentPosition(oState.StartPos);
                                }
                                if (oState.EndPos) {
                                    AscCommon.CollaborativeEditing.Add_DocumentPosition(oState.EndPos);
                                }
                            }
                        }
                        wsViews[i].objectRender.controller.resetSelection();
                    }
                }
                oFormulaLocaleInfo.Parse = false;
                oFormulaLocaleInfo.DigitSep = false;
                AscFonts.IsCheckSymbols = true;
                //(vivo):Upgrade Start
                //History.Clear();
                if (!AscCommon.CollaborativeEditing.Is_Fast()) {
                    //不是协同编辑 或 不是快速模式
                    History.Clear();
                }
                //快速模式（协同编辑）不执行原有清空逻辑
                //(vivo):Upgrade End
                History.TurnOff();
                var history = new AscCommon.CHistory();
                history.init(this);
                history.Create_NewPoint();
    
                history.SetSelection(null);
                history.SetSelectionRedo(null);
                var oRedoObjectParam = new AscCommonExcel.RedoObjectParam();
                history.UndoRedoPrepare(oRedoObjectParam, false);
                var changesMine = [].concat.apply([], oThis.aCollaborativeActions);
                oThis._forwardTransformation(oThis.snapshot, changesMine, aUndoRedoElems);
                for (var i = 0, length = aUndoRedoElems.length; i < length; ++i)
                {
                    var item = aUndoRedoElems[i];
                    if ((null != item.oClass || (item.oData && typeof item.oData.sChangedObjectId === "string")) && null != item.nActionType) {
                        if (window["NATIVE_EDITOR_ENJINE"] === true && window["native"]["CheckNextChange"]) {
                            if (!window["native"]["CheckNextChange"]())
                                break;
                        }
                        // TODO if(g_oUndoRedoGraphicObjects == item.oClass && item.oData.drawingData)
                        //     item.oData.drawingData.bCollaborativeChanges = true;
                        history.RedoAdd(oRedoObjectParam, item.oClass, item.nActionType, item.nSheetId, item.oRange, item.oData);
                    }
                }
                AscFonts.IsCheckSymbols = false;
    
                var oFontMap = this._generateFontMap();
                window["Asc"]["editor"]._loadFonts(oFontMap, function(){
                    if(oThis.oApi.collaborativeEditing.getFast()){
    
    
                        for(var i in wsViews){
                            if(isRealObject(wsViews[i]) && isRealObject(wsViews[i].objectRender) && isRealObject(wsViews[i].objectRender.controller)){
                                var oState = wsViews[i].objectRender.getStateBeforeLoadChanges();
                                if(oState){
                                    if (oState.Pos)
                                        AscCommon.CollaborativeEditing.Update_DocumentPosition(oState.Pos);
                                    if (oState.StartPos)
                                        AscCommon.CollaborativeEditing.Update_DocumentPosition(oState.StartPos);
                                    if (oState.EndPos)
                                        AscCommon.CollaborativeEditing.Update_DocumentPosition(oState.EndPos);
                                }
                                wsViews[i].objectRender.loadStateAfterLoadChanges();
                            }
                        }
                    }
                    oFormulaLocaleInfo.Parse = true;
                    oFormulaLocaleInfo.DigitSep = true;
                    history.UndoRedoEnd(null, oRedoObjectParam, false);
                    History.TurnOn();
                    oThis.bCollaborativeChanges = false;
                    //make snapshot for faormulas
                    oThis.snapshot = oThis._getSnapshot();
                    if(null != fCallback)
                        fCallback();
                });
            } else if(null != fCallback) {
                fCallback();
            }
        };

        CCollaborativeEditing.prototype.sendChanges = function (IsUserSave, isAfterAskSave) {
			// Когда не совместное редактирование чистить ничего не нужно, но отправлять нужно.
			var bIsCollaborative = this.getCollaborativeEditing();

			var bCheckRedraw = false, bRedrawGraphicObjects = false, bUnlockDefName = false;
			var oLock = null;
			if (bIsCollaborative) {
				if (0 < this.m_arrNeedUnlock.length || 0 < this.m_arrNeedUnlock2.length) {
					bCheckRedraw = true;
					this.handlers.trigger("cleanSelection");
				}

				// Очищаем свои изменения
				while (0 < this.m_arrNeedUnlock2.length) {
					oLock = this.m_arrNeedUnlock2.shift();
					oLock.setType(c_oAscLockTypes.kLockTypeNone, false);

					var drawing = AscCommon.g_oTableId.Get_ById(oLock.Element["rangeOrObjectId"]);
					if(drawing && drawing.lockType !== c_oAscLockTypes.kLockTypeNone) {
						var bLocked = drawing.lockType !== c_oAscLockTypes.kLockTypeNone && drawing.lockType !== c_oAscLockTypes.kLockTypeMine;
						drawing.lockType = c_oAscLockTypes.kLockTypeNone;
						bRedrawGraphicObjects = true;
						if(drawing instanceof AscCommon.CCore) {
							if(bLocked) {
								Asc.editor && Asc.editor.sendEvent("asc_onLockCore", false);
							}
						}
					}
					if(!bUnlockDefName){
						bUnlockDefName = this.handlers.trigger("checkDefNameLock", oLock);
					}

					this.handlers.trigger("releaseLocks", oLock.Element["guid"]);
				}

				// Очищаем примененные чужие изменения
				var nIndex = 0;
				var nCount = this.m_arrNeedUnlock.length;
				for (;nIndex < nCount; ++nIndex) {
					oLock = this.m_arrNeedUnlock[nIndex];
					if (c_oAscLockTypes.kLockTypeOther2 === oLock.getType()) {
						if (!this.handlers.trigger("checkCommentRemoveLock", oLock.Element)) {
							drawing = AscCommon.g_oTableId.Get_ById(oLock.Element["rangeOrObjectId"]);
							if(drawing && drawing.lockType !== c_oAscLockTypes.kLockTypeNone) {
								var bLocked = drawing.lockType !== c_oAscLockTypes.kLockTypeNone && drawing.lockType !== c_oAscLockTypes.kLockTypeMine;
								drawing.lockType = c_oAscLockTypes.kLockTypeNone;
								bRedrawGraphicObjects = true;
								if(drawing instanceof AscCommon.CCore) {
									if(bLocked) {
										Asc.editor && Asc.editor.sendEvent("asc_onLockCore", false);
									}
								}
							}
							if(!bUnlockDefName){
								bUnlockDefName = this.handlers.trigger("checkDefNameLock", oLock);
							}
						}

						this.m_arrNeedUnlock.splice(nIndex, 1);
						--nIndex;
						--nCount;
					}
				}
			}

			// Отправляем на сервер изменения
			this.handlers.trigger("sendChanges", this.getRecalcIndexSave(this.m_oRecalcIndexColumns), this.getRecalcIndexSave(this.m_oRecalcIndexRows), isAfterAskSave);

			if (bIsCollaborative) {
				// Пересчитываем lock-и от чужих пользователей
				this._recalcLockArrayOthers();

				// Очищаем свои изменения (удаляем массив добавленных строк/столбцов)
				delete this.m_oInsertColumns;
				delete this.m_oInsertRows;
				this.m_oInsertColumns = {};
				this.m_oInsertRows = {};
				// Очищаем свои пересчетные индексы
				this.clearRecalcIndex();

				// Чистим Undo/Redo
                //(vivo):Upgrade Start
                //AscCommon.History.Clear();
                //严格模式保持原样，清空记录吧。快速模式本地提交不清空历史信息
                if (!this.m_bFast) {
                    AscCommon.History.Clear()
                }
                //(vivo):Upgrade End


				// Перерисовываем
				if (bCheckRedraw) {
					this.handlers.trigger("drawSelection");
					this.handlers.trigger("drawFrozenPaneLines");
					this.handlers.trigger("updateAllSheetsLock");
					this.handlers.trigger("showComments");
				}

				if (bCheckRedraw || bRedrawGraphicObjects)
					this.handlers.trigger("showDrawingObjects");

//                if(bUnlockDefName){
                    this.handlers.trigger("unlockDefName");
//                }

				this.handlers.trigger("updateAllLayoutsLock");
				this.handlers.trigger("asc_onLockPrintArea");
				this.handlers.trigger("updateAllHeaderFooterLock");

				if (0 === this.m_nUseType)
					this.m_nUseType = 1;
			}
			AscCommon.History.Reset_SavedIndex(IsUserSave);
        };
        
        CCollaborativeEditing.prototype.startCollaborationEditing = function() {
            this.m_nUseType = -1;
            //进入快速模式（协同编辑）的时候需要把历史记录全部设置为已与服务器同步
            if (this.getFast()) {
                for (var i = 0; i < AscCommon.History.Points.length; i++) {
                    AscCommon.History.Points[i].sync = true;
                }
            }
        };
        
        CHistory.prototype.Clear = function(){
            this.Index         = -1;
            this.Points.length = 0;
            this.TurnOffHistory = 0;
            this.Transaction = 0;

            this.SavedIndex = null;
            this.ForceSave= false;
            this.UserSavedIndex = null;

            //(vivo):Upgrade Start
            // window['AscCommon'].g_specialPasteHelper.SpecialPasteButton_Hide();
            // this.workbook.handlers.trigger("toggleAutoCorrectOptions", null, true);
            // this._sendCanUndoRedo();

            //初始化就进入协同模式的时候，workbook是没初始化，所以是空的
            if (this.workbook) {
                window['AscCommon'].g_specialPasteHelper.SpecialPasteButton_Hide()
                this.workbook.handlers.trigger('toggleAutoCorrectOptions', null, true)
            }
            this._sendCanUndoRedo()
            //(vivo):Upgrade End
        };

        CHistory.prototype.Undo = function(){
            // Проверяем можно ли сделать Undo
            if (true !== this.Can_Undo()) {
                return false;
            }

            if (this.Index === this.Points.length - 1)
                this.LastState = this.workbook.handlers.trigger("getSelectionState");

            var Point = this.Points[this.Index--];

            //(vivo):Upgrade Start
            if (!Point) {
                return false;
            }
            //撤销后把该记录设置为未同步（sync为新加字段）
            Point.sync = undefined;
            //(vivo):Upgrade End

            var oRedoObjectParam = new AscCommonExcel.RedoObjectParam();
            this.UndoRedoPrepare(oRedoObjectParam, true);

            // Откатываем все действия в обратном порядке (относительно их выполенения)
            for ( var Index = Point.Items.length - 1; Index >= 0; Index-- ){
                var Item = Point.Items[Index];

                if(!Item.Class.RefreshRecalcData)
                    Item.Class.Undo( Item.Type, Item.Data, Item.SheetId );
                else{
                    if (Item.Class){
                        Item.Class.Undo();
                        Item.Class.RefreshRecalcData();
                    }
                }
                this._addRedoObjectParam(oRedoObjectParam, Item);
            }
            this.UndoRedoEnd(Point, oRedoObjectParam, true);
            return true;
        };

        CHistory.prototype.Redo = function(){
            if ( true != this.Can_Redo() )
                return;

            var oRedoObjectParam = new AscCommonExcel.RedoObjectParam();
            this.UndoRedoPrepare(oRedoObjectParam, false);

            var Point = this.Points[++this.Index];

            //(vivo):Upgrade Start
            //重做后把该记录设置为未同步（sync为新加字段）
            Point.sync = undefined
            //(vivo):Upgrade End

            this.RedoExecute(Point, oRedoObjectParam);
            this.UndoRedoEnd(Point, oRedoObjectParam, false);
        };

        CHistory.prototype._sendCanUndoRedo = function(){
            if (this.workbook.bCollaborativeChanges) {
                return;
            }

            if (this.workbook) {
                this.workbook.handlers.trigger("setCanUndo", this.Can_Undo());
                this.workbook.handlers.trigger("setCanRedo", this.Can_Redo());
                this.workbook.handlers.trigger("setDocumentModified", this.Have_Changes());
            }
        };
        
        CHistory.prototype.GetDeleteIndex = function() {
            return null;
        }

        CHistory.prototype.GetSerializeArrayForCoEdit = function() {
            var aRes = [];
            var undo = this.Index + 1;
            if (undo < this.Points.length) {
                for (var q = this.Points.length - 1; q >= undo; q--) {
                    var point = this.Points[q];
                    if (point.sync) {
                        continue;
                    }
                    var aPointChanges = [];
                    for (var j = point.Items.length - 1; j >= 0; j--) {
                        var elem = point.Items[j];
                        if (!elem.Data) {
                            if(elem.Class.CreateReverseChange){
                                var reverseClass = elem.Class.CreateReverseChange();
                                aPointChanges.push(
                                    new AscCommonExcel.UndoRedoItemSerializable(
                                        reverseClass, elem.Type,elem.SheetId,elem.Range,elem.Data,elem.LocalChange
                                ));
                            }
                            continue;
                        }
                        doConvertUndoItem(elem, aPointChanges);
                    }
                    aRes.push(aPointChanges);
                    point.sync = true;
                }
            }
            for (var i = 0; i <= this.Index; ++i) {
                var point = this.Points[i];
                if (point.sync) {
                    continue;
                }
                var aPointChanges = [];
                for (var j = 0, length2 = point.Items.length; j < length2; ++j) {
                    var elem = point.Items[j];
                    aPointChanges.push(
                        new AscCommonExcel.UndoRedoItemSerializable(
                            elem.Class,elem.Type,elem.SheetId,elem.Range,elem.Data,elem.LocalChange
                    ));
                }
                aRes.push(aPointChanges);
                point.sync = true;
            }
            return aRes
        };

        WorkbookView.prototype.redo = function() {
            if (!this.getCellEditMode()) {
                while (History.Index < History.Points.length - 1) {
                    var Point = History.Points[History.Index + 1];
                    if(isSheetAdd(Point)){
                        History.Index++;
                        continue;
                    }
                    if(isSheetRemove(Point)){
                        History.Index++;
                        continue;
                    }
                    break;
                }
                if (History.Index < History.Points.length - 1) {
                    History.Redo();
                } else {
                    History._sendCanUndoRedo();
                }
            } else {
                this.cellEditor.redo();
            }
        };

        WorkbookView.prototype.undo = function() {
            var oFormulaLocaleInfo = AscCommonExcel.oFormulaLocaleInfo;
            oFormulaLocaleInfo.Parse = false;
            oFormulaLocaleInfo.DigitSep = false;
            if (!this.getCellEditMode()) {
                while (History.Index >= 0) {
                    var Point = History.Points[History.Index];
                    var currentIndex = History.Index;
                    if(isSheetAdd(Point)){
                        History.Points.splice(currentIndex, 1);
                        History.Index--;
                        continue;
                    }
                    if(isSheetRemove(Point)){
                        History.Points.splice(currentIndex, 1);
                        History.Index--;
                        var tmp = [];
                        History.Points.forEach(function(item,index){
                            if(Point.UndoSheetId == item.UndoSheetId){
                                tmp.push(index);
                            }
                        });
                        var count = 0;
                        tmp.forEach(function(index){
                            var spliceIndex = index - count;
                            History.Points.splice(spliceIndex, 1);
                            if(spliceIndex <= History.Index){
                                History.Index--;
                            }
                            count++;
                        });
                        continue;
                    }
                    break;
                }
                History.Undo()
            } else {
              this.cellEditor.undo();
            }
            oFormulaLocaleInfo.Parse = true;
            oFormulaLocaleInfo.DigitSep = true;
        };
        

    }

    /**
     * 将撤销记录转换为重做记录
     * @param elem History.Point.Item
     */
    function doConvertUndoItem(elem, aPointChanges){
        var data = elem.Data;
        // 修复撤销操作并且协同到远端
        // 原理是把本地undo逆转为redo
        if (data instanceof AscCommonExcel.UndoRedoData_CellSimpleData) {
            //发现设置数据单元和普通的信息不一致，在这里判断当type=1的时候修复下
            var oNewVal = data.oNewVal;
            var oOldVal = data.oOldVal;
            if (oOldVal && oOldVal.constructor.name == AscCommonExcel.UndoRedoData_CellData.name) {
                //逆转：组合单元格后的重置数据（包括样式）
                //有数据的组合单元格，解除组合后，出现数据设置不成功问题
                var redoSetValue = new AscCommonExcel.UndoRedoData_CellSimpleData(data.nRow, data.nCol,oNewVal, oOldVal.value, data.sFormula);
                var redoSetStyle = new AscCommonExcel.UndoRedoData_CellSimpleData(data.nRow, data.nCol, oNewVal, oOldVal.style, data.sFormula);
                aPointChanges.push(
                    new AscCommonExcel.UndoRedoItemSerializable(
                        AscCommonExcel.g_oUndoRedoCell, 16, elem.SheetId, elem.Range, redoSetValue, elem.LocalChange
                ));
                aPointChanges.push(
                    new AscCommonExcel.UndoRedoItemSerializable(
                        AscCommonExcel.g_oUndoRedoCell, 18, elem.SheetId, elem.Range, redoSetStyle, elem.LocalChange
                ));
            } else {
                var type = elem.Type;
                // type == 1 historyitem_Cell_Fontname: 1 改变字体
                // type == 16 historyitem_Cell_ChangeValue: 16  改变cell的值（value）
                // if (type ==1 ) {
                //     type = 16;
                // }

                //逆转设置数据（普通），具体行为根据Type确定
                var redoData = new AscCommonExcel.UndoRedoData_CellSimpleData(
                    data.nRow, data.nCol, oNewVal, oOldVal, data.sFormula
                );
                aPointChanges.push(
                    new AscCommonExcel.UndoRedoItemSerializable(
                        elem.Class, type, elem.SheetId, elem.Range, redoData, elem.LocalChange
                ));
            }
        } else if (data instanceof AscCommonExcel.UndoRedoData_FromTo) {
            //逆转：组合单元格
            var redoData = new AscCommonExcel.UndoRedoData_FromTo(
                data.to, data.from, data.copyRange, data.sheetIdTo
            );
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_SortData) {
            var redoData = new AscCommonExcel.UndoRedoData_SortData(
                data.bbox, data.places
            );
            aPointChanges.push(new AscCommonExcel.UndoRedoItemSerializable(
                elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_FromToRowCol) {
            var type = elem.Type;
            var bRow = data.bRow;
            var to = data.to;
            var from = data.from;
            if(elem.Type == 2){
                // historyitem_Worksheet_RemoveRows(2) => 增加行 => 逆转成删除列 historyitem_Worksheet_AddRows: 4
                type = 4;
            } else if (elem.Type == 4){
                // 删除列 historyitem_Worksheet_AddRows(4) 逆转成 historyitem_Worksheet_RemoveRows(2)
                type = 2;
            } else if (elem.Type == 5){
                // historyitem_Worksheet_AddCols => 增加列 => 逆转成删除列 historyitem_Worksheet_RemoveCols: 3
                type = 3;
            } else if(elem.Type == 3){
                // 删除列 historyitem_Worksheet_RemoveCols(3) 逆转成 historyitem_Worksheet_AddCols(5)
                type = 5;
            } else if(elem.Type == 28){
                // 28：historyitem_Worksheet_RowHide
                to = data.from
                from = data.to
                bRow = !data.bRow;
            } else {
                console.error('撤销不支持====>UndoRedoData_FromToRowCol===>', type);
                throw new Error();
            }
            //逆转：显示行
            var redoData = new AscCommonExcel.UndoRedoData_FromToRowCol(
                bRow, to, from
            );
            
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, type, elem.SheetId, elem.Range, redoData, elem.LocalChange
            ));
        } else if (data instanceof Asc.asc_CCommentData) {
            //逆转：插入批注
            var type = elem.Type;
            if(type == 1){
                type = 2;
            } else if(type == 2){
                type = 1;
            }
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, type, elem.SheetId, elem.Range, data, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_IndexSimpleProp) {
            //逆转：隐藏列
            var redoData = new AscCommonExcel.UndoRedoData_IndexSimpleProp(
                data.index, data.bRow, data.oNewVal, data.oOldVal
            );
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange )
            );

        } else if (data instanceof AscCommonExcel.UndoRedoData_AutoFilter) {
            //逆转：筛选条件
            var type = elem.Type;
            var oldData = data;
            data = new AscCommonExcel.UndoRedoData_AutoFilter();
            
            data.activeCells = oldData.undo.Ref;
            var oldFilter = oldData.undo.oldFilter;
            if(oldFilter){
                if (oldFilter.TableStyleInfo){
                    data.styleName = oldFilter.TableStyleInfo.Name;
                }
                data.activeCells = oldFilter.Ref;
            }
            var TableStyleInfo = oldData.undo.TableStyleInfo
            if(TableStyleInfo){
                data.displayName = TableStyleInfo.Name;
                data.styleName = TableStyleInfo.Name;
            }

            data.moveTo = oldData.moveFrom;
            data.moveFrom = oldData.moveTo;

            if (oldData.undo.val){
                data.val = oldData.undo.val
            }
            if (oldData.undo.nCol){
                data.nCol = oldData.undo.nCol
            }
            if (oldData.undo.nRow){
                data.nRow = oldData.undo.nRow
            }

            data.bWithoutFilter = oldData.bWithoutFilter

            if(!data.activeCells) {
                data.activeCells = $.extend( true , {}, oldData.activeCells );
            }

            if (oldData.autoFiltersObject) {
                data.autoFiltersObject = $.extend( true , {}, oldData.autoFiltersObject );
                var FilterColumns = oldData.undo.FilterColumns
                if (!FilterColumns || FilterColumns.length === 0){
                    data.autoFiltersObject.values.forEach(function(item){
                        item.visible = true;
                    })
                } else {
                    if (FilterColumns[0].Filters) {
                        var Values = FilterColumns[0].Filters.Values;
                        data.autoFiltersObject.values.forEach(function(item){
                            item.visible = Values[item.val] ? true : false;
                        })
                    }
                }
            }

            if (elem.Type == 1) {
                //1:historyitem_AutoFilter_Add   -->   3:historyitem_AutoFilter_Empty
                type = 3;
            } else if (elem.Type == 2) {
                //排序
                type = 2;
            } else if (elem.Type == 3) {
                //3:historyitem_AutoFilter_Empty   -->   1:historyitem_AutoFilter_Add
                type = 1;
            } else if (elem.Type == 5) {
                //5:historyitem_AutoFilter_Apply
                type = 5;
            } else if (elem.Type == 6) {
                //6:historyitem_AutoFilter_Move
                type = 6;
            } else if (elem.Type == 8) {
                //8:historyitem_AutoFilter_Delete   -->   1:historyitem_AutoFilter_Add
                type = 1;
            } else if (elem.Type == 9) {
                //9:historyitem_AutoFilter_ChangeTableStyle
                type = 9;
            } else if (elem.Type == 10) {
                //10:historyitem_AutoFilter_Change
                //场景一：插入表格，删除列后撤销

                if (oldData.undo.oldFilter instanceof AscCommonExcel.AutoFilter){
                    // 先消掉这个筛选框，然后再增加
                    aPointChanges.push(
                        new AscCommonExcel.UndoRedoItemSerializable(
                            elem.Class, 8, elem.SheetId, elem.Range, data, elem.LocalChange
                    ));
                }
                type = 1;
            } else if (elem.Type == 16) {
                //16:historyitem_AutoFilter_ChangeColumnName
                type = 16;
            } else {
                throw new Error();
            }
            
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, type, elem.SheetId, elem.Range, data, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_SheetAdd) {
            //逆转：增加WorkSheet
            // var redoData = new AscCommonExcel.UndoRedoData_SheetRemove(null, data.sheetid, null);
            // aPointChanges.push(new AscCommonExcel.UndoRedoItemSerializable(elem.Class, 2, elem.SheetId, elem.Range, redoData, elem.LocalChange));
            //因为删除无法实现完美逆转，干脆增加也不要逆转好了
            console.error('撤销不支持====> UndoRedoData_SheetAdd===>');
            throw new Error();
        } else if (data instanceof AscCommonExcel.UndoRedoData_SheetRemove) {
            //逆转：删除Sheet
            //删除表格可以逆转创建，但是如果有很多数据怎么办？要逆转吗？
            //最好禁止逆转删除WorkSheet
            // var redoData = new AscCommonExcel.UndoRedoData_SheetAdd(data.index, data.sheet.sName, null, data.sheetId, null);
            // redoData.sheet = data.sheet;
            // aPointChanges.push(new AscCommonExcel.UndoRedoItemSerializable(elem.Class, 1, elem.SheetId, elem.Range, redoData, elem.LocalChange));
            console.error('撤销不支持====> UndoRedoData_SheetRemove===>');
            throw new Error();
        } else if (data instanceof AscCommonExcel.UndoRedoData_BBox) {
            var type = elem.Type;

            if(elem.Type == 7){
                type = 9;
            } else if (elem.Type == 9){
                type = 7;
            } else if(elem.Type == 6){
                type = 8;
            } else if(elem.Type == 8){
                type = 6;
            } else {
                console.error('撤销不支持====> UndoRedoData_BBox===>', type);
                throw new Error();
            }
            //逆转：删除单元格
            var redoData = new AscCommonExcel.UndoRedoData_BBox(data)
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, type, elem.SheetId, elem.Range, redoData, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_Layout) {
            //逆转：修改布局方式
            var redoData = new AscCommonExcel.UndoRedoData_Layout(
                data.to, data.from
            );
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_FromToHyperlink) {
            //逆转：插入超级链接
            var redoData = new AscCommonExcel.UndoRedoData_FromToHyperlink(
                 data.to, data.from, data.hyperlink
            );
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange
            ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_ClrScheme) {
            //逆转：更改配色方案
            var redoData = new AscCommonExcel.UndoRedoData_ClrScheme(
                data.oldVal,data.newVal
            );
            aPointChanges.push(
                new AscCommonExcel.UndoRedoItemSerializable(
                elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange
                ));
        } else if (data instanceof AscCommonExcel.UndoRedoData_IndexSimpleProp) {
                //逆转：更改表格模板
                var redoData = new AscCommonExcel.UndoRedoData_IndexSimpleProp(
                    data.index, data.bRow, data.oOldVal, data.oNewVal
                );
                aPointChanges.push(
                    new AscCommonExcel.UndoRedoItemSerializable(
                    elem.Class, elem.Type, elem.SheetId, elem.Range, redoData, elem.LocalChange
                ));
        } else {
            console.error('撤销不支持====> other ===>');
            throw new Error();
        }
    }

    function isSheetAdd(Point){
        for (var i=0; i<Point.Items.length; i++) {
            var Data = Point.Items[i].Data;
            if(Data instanceof AscCommonExcel.UndoRedoData_SheetAdd){
                return true;
            }
        }
        return false;
    }

    function isSheetRemove(Point){
        for (var i=0; i<Point.Items.length; i++) {
            var Data = Point.Items[i].Data;
            if(Data instanceof AscCommonExcel.UndoRedoData_SheetRemove){
                return true;
            }
        }
        return false;
    }
    

    function UpgradeDefaultFont(){
        var o_openDocument = api.prototype._openDocument;
        api.prototype._openDocument = function(data){
            o_openDocument.call(this, data);
            var font = AscCommonExcel.g_oDefaultFormat.Font;
            font.setName("SimSun");
        }
    }
    
    Asc['UpgradeCollaborativeUndoRedo'] = UpgradeCollaborativeUndoRedo;
    Asc['UpgradeDefaultFont'] = UpgradeDefaultFont;
})();

**Comment by ShockwaveNN** [comment]
@fangjialong2019 could you at least create pull request with your changes. I cannot promise to you that it'll be merged, but at least we can review it

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
