### ISSUE TITLE
XIRR calculation wrong

### ISSUE THREAD

**Issue by alex9434** [ONLYOFFICE/DocumentServer#746]
**Bug report:** Calculation of XIRR delivers wrong result

Calculation of XIRR for the following payments:
1/1/2020 | 1260404.83
11/1/2020 | -2881.40
10/1/2020 | -10565.62
10/1/2020 | 20000.00
15/1/2020 | -1278822.63

**Current behaviour:** Result: 27.61%

**Expected behaviour:** Expected result: 18.35% (as delivered by MS Excel and LibreOffice)

**Document server version:** 5.4.2
**Operating System:** Devuan Ascii (64 bit)
**Browser:** Chromium 78.0.3904.108 built on Debian 10.2, running on Debian 10.2 (64-bit)

**Comment by Rita-Bubnova** [comment]
Hello, @alex9434.
I created the [IssueXIRR.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/4070229/IssueXIRR.xlsx) file according to your data. In cell C1, the function `=XIRR(B1:B5,A1:A5)` is calculated in ONLYOFFICE Spreadsheet Editor, MS Excel, LibreOffice the result of the calculation is `27.61%`.

Could you attach your file demonstrating error?

**Comment by alex9434** [comment]
You are right, there obviously was an error with the XLS sheet. Apologies. I close now.
