### ISSUE TITLE
Warning message on initial load

### ISSUE THREAD

**Issue by fabiowillian** [ONLYOFFICE/DocumentServer#748]
Hi!

I'm trying to see how DocumentServer works in html pages, so I installed it via Docker Compose and created a simple html page, according to the documentation.

When I open the html page the following message appears:

> The document could not be saved. Please check connection settings or contact your administrator. When you click the 'OK' button, you will be prompted to download the document. Find more information about connecting Document Server 

Also, the text editor does not open page editing and all menus appear disabled.

Is there anyway to fix this problem? It happens for any missing settings?

**Comment by ShockwaveNN** [comment]
@flaminestone please take a look

**Comment by ShockwaveNN** [comment]
@fabiowillian Hi, sorry for very slow responce, seems we missed your issue

Please state - is problem still actual, and if so - do you open your webpage via localhost url or via real ip (external or internal) because you cannot use localhost if you're using docker

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
