### ISSUE TITLE
Onlyoffice preview theme icon blank

### ISSUE THREAD

**Issue by elkekou** [ONLYOFFICE/DocumentServer#755]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Only office does not show preview on theme icon.
I use onlyoffice plugin inside nextcloud instance.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

Fresh install on Centos 8 following tutorial on onlyoffice website + trick of this issue to bypass dep error #670
Selinux disabled

What is the expected behavior?
preview on theme print correctly

DocumentServer version:
onlyoffice-documentserver.x86_64 5.4.2-46 @ONLYOFFICE

Operating System:
Centos 8 (selinux disable)
Thanks for help.
![Capture](https://user-images.githubusercontent.com/17431253/72906563-b73b5700-3d32-11ea-9c85-0ad4229fbdce.JPG)

**Comment by ShockwaveNN** [comment]
Which browser are you using? Not Brave Browser?

**Comment by elkekou** [comment]
Hi thank you for answer i look everywhere on server and completely forgot to look client side. You're right i'm using brave, with other browsers no problem.

**Comment by ShockwaveNN** [comment]
@elkekou There is an opened issue with brave browser here
https://github.com/ONLYOFFICE/DocumentServer/issues/539
But currently we have no solution (and not much resources to look at not so popular browser)

**Comment by elkekou** [comment]
Thank you,
as workaround you can whitelist the nextcloud/owncloud website and the onlyoffice website, now it's work without problem.
