### ISSUE TITLE
Saving only happens on content change not format change - ODS

### ISSUE THREAD

**Issue by baarkerlounger** [ONLYOFFICE/DocumentServer#756]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
If I open an existing ODS spreadsheet and make some formatting changes only (no content changes), the save icon does not flash to indicate auto saving, and it is not enabled for manual clicking. Closing and reopening the spreadsheet does not persist the changes. On .xlsx spreadsheet files, formatting changes trigger auto-saving as expected.

**What is the expected behavior?**
Formatting changes should trigger an auto-save the same way they do on xlsx.

**DocumentServer version:**
5.4.2

**Operating System:**
Ubuntu 18.04 LTS x86

**Browser version:**
Firefox/Chrome

**Comment by Rita-Bubnova** [comment]
Hello, @baarkerlounger.
Are you editing an ODS file? Our scheme of work is to convert the ODS file to XLSX format and its further editing.
What document management system you using?

**Comment by baarkerlounger** [comment]
Nextcloud 18 and yes it was editing an ODS file directly. Converting it to xlsx before working on it works fine.

**Comment by Rita-Bubnova** [comment]
Please attach a screenshot with the ONLYOFFICE settings you are using?
![image](https://user-images.githubusercontent.com/25282241/73062143-bfb79d00-3eac-11ea-9eec-f05c1e469cb5.png)

**Comment by baarkerlounger** [comment]
![Screenshot from 2020-01-24 12-37-07](https://user-images.githubusercontent.com/5101747/73069693-46b54700-3ea6-11ea-961d-0594be620794.png)

**Comment by Rita-Bubnova** [comment]
I am using Nextcloud 18 and DocumentServer version 5.4.2-46 and cannot reproduce the problem.
Please, attach an ODS file that demonstrates the problem.

**Comment by baarkerlounger** [comment]
Can't seem to reproduce now also, perhaps some networking issue. Will close this.
