### ISSUE TITLE
Cut command make a copy instead of a cut

### ISSUE THREAD

**Issue by L3o-pold** [ONLYOFFICE/DocumentServer#758]
In a spreadsheet, the cut command (by right clicking or using keyboard) make a copy instead of a cut.

It's reproductible with latest stable version documentserver:5.4.1.39 and latest testing version onlyoffice/4testing-documentserver-ie:5.5.0.64.

I know this bug is not present in 5.4.0-21

![Tg3sRHeyQb](https://user-images.githubusercontent.com/4710495/73058323-ac4c0800-3e93-11ea-99b7-363346915c97.gif)

**Comment by Rita-Bubnova** [comment]
Hello, @L3o-pold.
What operating system and browser are you using?

**Comment by L3o-pold** [comment]
Hi @Rita-Bubnova, test both with Windows 10 and OSX Catalina.
Using Chrome browser.

**Comment by Rita-Bubnova** [comment]
What dms do you used? What config do you use to integrate editors in you system?

**Comment by L3o-pold** [comment]
Using onlyoffice/documentserver-de:5.4.1.39 default config

**Comment by Rita-Bubnova** [comment]
We check in onlyoffice/documentserver-de: 5.4.1.39 (Chrome browser) and the problem does not reproduce. `Cut` / `paste` is done correctly.
![image](https://user-images.githubusercontent.com/25282241/73063082-fdb5c080-3eae-11ea-9977-48d666e36c42.png)

Pay attention to the screenshot - in the upper right corner there should be an `Open file location` button, which you do not have.
Please indicate what dms do you used?

**Comment by L3o-pold** [comment]
@Rita-Bubnova what's DMS?

**Comment by Rita-Bubnova** [comment]
@L3o-pold, DMS is document management system (Nextcloud, ownCloud or your own system).

**Comment by L3o-pold** [comment]
Own system.

**Comment by L3o-pold** [comment]
```json
{"document":{"fileType":"xlsx","key":"******","permissions":{"edit":true},"title":"******.xlsx","url":"******"},"documentType":"spreadsheet","type":"desktop","editorConfig":{"mode":"view","customization":{"compactHeader":false,"feedback":false,"comments":true,"logo":{"image":"******","url":"******"}}},"token":"******"}
```

**Comment by L3o-pold** [comment]
The socket event has the `deleteIndex:null` 

```
0: "{"type":"saveChanges","changes":"[\"****\"]","startSaveChanges":true,"endSaveChanges":true,"isCoAuthoring":false,"isExcel":true,"deleteIndex":null,"excelAdditionalInfo":null,"unlock":false,"releaseLocks":false}"
```

**Comment by L3o-pold** [comment]
@Rita-Bubnova could you explain to me how the DMS influence this? Maybe I can check what's wrong with it.

**Comment by ShockwaveNN** [comment]
@L3o-pold We do not know how DMS influence this, but we know that on `documentserver-ie` with integrated test example copy-paste working fine (at least on our servers), so can you compare that on `https://documentserver-url/example` copy paste is working?

**Comment by L3o-pold** [comment]
`Cannot GET /example/`

**Comment by ShockwaveNN** [comment]
`supervisorctl start all`

**Comment by L3o-pold** [comment]
By removing user from the config it works as expected:

```json
"editorConfig":{ 
      ....
      "user":{ 
         "id": 1212,
         "name":"*****"
      },
```

**Comment by L3o-pold** [comment]
Ok this is because `id` is an int and not a string... 
The [documentation](https://api.onlyoffice.com/editors/config/editor#user) said string but I was not expected such behavior...

**Comment by ShockwaveNN** [comment]
@L3o-pold Year, our dev team known about some strange issues if user.id in not string, we'll try to figure it out
