### ISSUE TITLE
API: Error 400 on compiled version.

### ISSUE THREAD

**Issue by republicus** [ONLYOFFICE/DocumentServer#760]
I wish to contribute to development and began to build according to the build instructions. Those instructions are largely out of date and it took several attempts to make it work. Sadly the only success I have had is by using Ubuntu 14.04 as the instructions indicate. But I know the packaged versions work on Debian 10.

I think my setup is complete..  as other issues brought up indicate that a working setup should say:
**Cannot GET /** when loading the default url in a web browser.

![image](https://user-images.githubusercontent.com/47370709/73129123-967d3680-3faa-11ea-988c-7bdab5e855e3.png)

As I try to edit a document, though I am receiving an error:

```Error when trying to connect (Client error: `GET http://192.168.71.173:8080/cache/files/conv_check_811109724_docx/output.docx/check_811109724.docx?md5=3HW7c3GguTFcvd5WuqGqyw&expires=1579999628&disposition=attachment&ooname=output.docx` resulted in a `400 Bad Request` response)```

Checking the path for cache appears correct:

![image](https://user-images.githubusercontent.com/47370709/73129182-ca0c9080-3fab-11ea-8c58-bac37bf34810.png)

Ive updated Ngnix to a  later version and tested the packaged version's nginx's DocumentServer configuration files. With that setup I see the Welcome page saying ONLYOFFICE server is running... BUT, the API has the same error.

I am using the latest Nextcloud/ONLYOFFICE integration app.

Any thoughts?
Thanks in advance

**Did this work in previous versions of DocumentServer?**
Debian 10 with packaged version of ONLYOFFICE DocumentServer works.

**DocumentServer version:**
Latest

**Comment by ShockwaveNN** [comment]
@republicus I think there should be major errors in server logs

> But I know the packaged versions work on Debian 10.

Yeah, but we compile this version on Ubuntu 14.04
I'm think on Debian 10 there will be troubles compiling Google v8 (at least old version we use)

**Comment by republicus** [comment]
Thanks for replying @ShockwaveNN 
All of the examples above are compiled on Ubuntu 14.04

Also, you're right, v8 is the issue I ran into on Deb 10 when trying to compile the core.

**Comment by ShockwaveNN** [comment]
@republicus Look out for error in run services, especially in `/var/www/onlyoffice/documentserver/server/DocService/sources/server.js` process

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
