### ISSUE TITLE
Can't resize oleObject in plugin

### ISSUE THREAD

**Issue by VadymLeonov** [ONLYOFFICE/DocumentServer#762]
**Do you want to request a *feature* or report a *bug*?**
Can't change oleObject size by calling `window.Asc.plugin.executeMethod("EditOleObject", [params], cb);`

**What is the current behavior?**
I can add an object with a given size and it works. But when I trying to update - data, imgSrc, widthPix, heightPix changes as expected but it dsnt resize.

config:
`{
  "name"       : "oleObjectPlugin",
  "guid"       : "plugin_guid",
  "variations" : [
    {
      "description"         : "some description",
      "url"                 : "index.html",
      "icons"               : ["icon.png", "icon@2x.png"],
      "EditorsSupport"      : ["word"],
      "initDataType"        : "ole",
      "initData"            : "",
      "isSystem"            : true,
      "isViewer"            : false,
      "isVisual"            : false,
      "isModal"             : false,
      "isInsideMode"        : false,
      "isUpdateOleOnResize" : true,
      "buttons"             : []
    }
  ]
}`

`window.Asc.plugin.info.recalculate = true;`
`var imgSrc = 'some base64 img';`
`var params = {
  guid: 'plugin_guid',
  widthPix: 100,
  heightPix: 100,
  imgSrc: imgSrc,
  data: someData,
  objectId: someData.objectId,
  resize: true,
};`

`window.Asc.plugin.executeMethod("EditOleObject", [params], someCb);`

**DocumentServer version:**
5.4.1-39

Could you help me pls?

**Comment by ShockwaveNN** [comment]
@flaminestone please, take a look

**Comment by askonev** [comment]
Hello @VadymLeonov. Is your question still relevant?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
