### ISSUE TITLE
insert block text in document using a pluggin .js code ... Its possible? 

### ISSUE THREAD

**Issue by leonardo-alencar** [ONLYOFFICE/DocumentServer#763]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by leonardo-alencar** [comment]
window.Asc.plugin.itemClick = function(item) {
    var sScript = '\nconsole.log("Begin !!!");';
    sScript += '\nvar oDocument = Api.GetDocument();';
    sScript += '\nvar oParagraph, oRun;';
    sScript += '\noParagraph = oDocument.GetElement(0);';
    sScript += '\noInlineLvlSdt = Api.CreateInlineLvlSdt();';
    sScript += '\noParagraph.AddInlineLvlSdt(oInlineLvlSdt);';
    sScript += '\noRun = Api.CreateRun();';
    sScript += '\noRun.AddText("This is just a sample text. Nothing special.");';
    sScript += '\noInlineLvlSdt.AddElement(oRun,0);';
 window.Asc.plugin.info.recalculate = true;
 window.Asc.plugin.executeCommand("command", sScript);

**Comment by ShockwaveNN** [comment]
@flaminestone

**Comment by flaminestone** [comment]
Hello @leonardo-alencar. Adding block text via api is not possible now, there are not public methods. But I think, it can be added in future version.

**Comment by askonev** [comment]
plugin.executeCommand() is deprecated. To execute the api builder script, use the [callCommand](https://api.onlyoffice.com/plugin/callcommand)

**Comment by askonev** [comment]
The oInlineLvlSdt and Run must be installed correctly

```js
window.Asc.plugin.init = function () {
    this.callCommand(function() {
            var oDocument = Api.GetDocument();
            var oParagraph, oRun, oInlineLvlSdt;
                oParagraph = oDocument.GetElement(0);
                oInlineLvlSdt = Api.CreateInlineLvlSdt();
                oParagraph.AddInlineLvlSdt(oInlineLvlSdt);
                oRun = Api.CreateRun();
                oRun.AddText("This is just a sample text. Nothing special.");
                oInlineLvlSdt.AddElement(oRun,0);
    }, true);
};
```

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by will961123** [comment]
> 必须正确安装 oInlineLvlSdt 和 Run
> 
> window.Asc.plugin.init = function () {
>     this.callCommand(function() {
>             var oDocument = Api.GetDocument();
>             var oParagraph, oRun, oInlineLvlSdt;
>                 oParagraph = oDocument.GetElement(0);
>                 oInlineLvlSdt = Api.CreateInlineLvlSdt();
>                 oParagraph.AddInlineLvlSdt(oInlineLvlSdt);
>                 oRun = Api.CreateRun();
>                 oRun.AddText("This is just a sample text. Nothing special.");
>                 oInlineLvlSdt.AddElement(oRun,0);
>     }, true);
> };

Hello, I have a similar problem. I want to insert text at the cursor. The example provided in the document is fixed to insert text in the first paragraph. How should I adjust this code?

```js
       var oDocument = Api.GetDocument();
       var oParagraph = oDocument.GetElement(0);
       var oRun = Api.CreateRun();
       oRun.AddText("This is a text run");
       oParagraph.AddElement(oRun);
```

**Comment by askonev** [comment]
@will961123 Hi, please open a new issue because your problem is not related to the one under discussion.
