### ISSUE TITLE
revers proxy requiments

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#766]
Hi,

we have revers-proxy to connect to onlyoffice. 
Because we have high security "rules" we have disable many features in revers-proxy(not default settings).

Can someone tell me which features i have to enable in nginx(revers-proxy) that documentserver work?

examble: we know we have to allow Websockets (websocket update was disabled)

Thanks!

**Comment by ShockwaveNN** [comment]
@agolybev could you help?

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
