### ISSUE TITLE
[Bug] Enabling "track changes" mode is not synchronised between OnlyOffice Desktop Editor and Nextcloud

### ISSUE THREAD

**Issue by philipreimer** [ONLYOFFICE/DocumentServer#768]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Text entered in step 11 below is not marked as changed text.
Track Changes mode is **not** enabled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

0. Install Nextcloud Hub (18) and Document Server Community Edition - I used the docker images from here: https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
1. Setup two users in Nextcloud
2. Login to Nextcloud as User A
3. Create a document
4. Write some text
5. Enable Track Changes mode
6. Save document
7. Share document in nextcloud with User B
8. Open OnlyOffice Desktop Editor
9. Connect to nextcloud and login as User B
10. Open the document, which was shared by User A
11. Write some text

**What is the expected behavior?**
Track Changes mode should be enabled.
Text entered by User B should be marked as change in both Desktop Editor and Nextcloud

**Did this work in previous versions of DocumentServer?**
This is the first version I tested

**DocumentServer version:**
Latest docker images of 01. Feb. 2020 - see https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud

**Operating System:**
MacOS 10.14.6 (Desktop Editor)
Document Server is running in docker image see https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud (Ubuntu 16.04.6 LTS)

**Browser version:**
Firefox 72.0.2

**Comment by alexanderonlyoffice** [comment]
@philipreimer, please note that when you are opening the file the editing mode is opened by default.

**Comment by philipreimer** [comment]
@alexanderonlyoffice I don't know what you mean by "editing mode" and how it is related to my report.

To clarify: if I enable the "Track Changes" mode in menu "Collaboration", all the text I enter afterwards appears in a different colour and I get the little comment-like boxes at the right-hand side that allow me to either accept or undo the change.

This setting "Track Changes = ON" does not seem to be saved with the document. This means that when another user opens the file again and changes something, her changes will **not** be marked as such.

Especially in a situation where multiple people are collaborating on one document you will want to see who changed what. And it is unlikely to expect that everyone who starts working on the doc will pause and think "oh, wait, I need to enable track changes mode first, because otherwise the others won't know what I have changed".

Moreover, this behaviour is very confusing for people coming from MS Word, where - once enabled - track changes mode stays enabled, regardles of who opens the file.

BTW, this also does not work when just working with a local file in OnlyOffice. If I open a local file again, the track changes mode is also off.

**Comment by CarlOnlyoffice** [comment]
Hello @philipreimer,

In Nextcloud, a file will always be opened with Track Changes mode disabled because Nextcloud currently supports only edit and view permissions. In the future, if Nextcloud introduces extended sharing rights support, it will be possible to share a document for reviewing, so Track Changes is enabled.

As for ONLYOFFICE Desktop Editors, I see you received a reply in another issue.

**Comment by philipreimer** [comment]
Hello @CarlOnlyoffice 

I think there is some kind of misunderstanding here. I am not looking for some other mode of sharing the file. Both users A and B can and should edit the file.
All I am looking for is, that when user A saves the file, user B can open the same file and find it in the same state that user A left it in.
I mean, the font also does not change when a file is opened again by some other user.

**Comment by philipreimer** [comment]
Hello @LinneyS, any updates? This is still not working with Nextcloud App ONLYOFFICE 6.1.0 and Document Server version 5.6.5.

**Comment by trofim24** [comment]
We've already added ability to save track changes to file and enable/disable for all users.
It released in version 6.3.0
