### ISSUE TITLE
Redis connection to localhost:6379

### ISSUE THREAD

**Issue by guosteven** [ONLYOFFICE/DocumentServer#770]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Hi, please fill issue template correctly

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
