### ISSUE TITLE
freezes call application

### ISSUE THREAD

**Issue by f0ma85** [ONLYOFFICE/DocumentServer#774]
When you try to copy 14,000 lines in a table application, the microsoft edge freezes the page and offers to complete the script. There is no such problem in the Chrome browser (freezes for 5-8 seconds and continues to work). All versions of programs have been updated to the latest release, including Windows 10.

**Comment by Rita-Bubnova** [comment]
Hello, @f0ma85.
Could you attach file with problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
