### ISSUE TITLE
Collaboration: Users with read-only rights do not receive real-time updates

### ISSUE THREAD

**Issue by stefandesu** [ONLYOFFICE/DocumentServer#775]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a document is open with two users, one having read-only rights on the document in Nextcloud, the user with read-only rights will not receive real-time updates if the document is being edited.

Note: If User 2 has editing rights, they will see the changes in real-time like expected.

Note: Switching between Fast and Strict co-editing does not change anything about this issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create a new document with User 1 in Nextcloud (tested with Document and Spreadsheet)
- Share that document with another user (User 2), remove that user's rights to edit the document
- Open the document simultaneously with both users (i.e. with a private browser window)
- Edit the document with User 1
- You will not see changes in the opened document of User 2 (but User 2 can see that User 1 is current editing the document in the top right corner)

**What is the expected behavior?**
User 2 should be able to see the changes in real-time.

**Did this work in previous versions of DocumentServer?**
I don't know, just started using it. (I can test with older versions if necessary.)

**DocumentServer version:**
5.4.2.46 (latest) via Docker

**Operating System:**
Server: Ubuntu 18.04.3 LTS
Client: macOS 10.14.6

**Browser version:**
Safari 13.0.4

**Comment by Rita-Bubnova** [comment]
Hello, @stefandesu.
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/552.

**Comment by stefandesu** [comment]
Thanks @Rita-Bubnova, I was searching for it but I didn't choose the right keywords to find it. 😅 I'll close this and comment on the other one.
