### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by aol-nnov** [ONLYOFFICE/DocumentServer#777]
I'm observing this error message in chrome dev tools console.

also, most of letters in the document are not rendered.  While toggling non-printable characters, some missing (not rendered) printable characters appear, other, to the opposite, disappear. During that, the aforementioned error message is printed.

Documentserver: latest docker image
Chrome: Version 80.0.3987.100 (Official Build) (64-bit) on MacOS 10.15.2 (19C57)

Firefox 73.0 (64-bit) does not suffer from this problem

If it's relevant, documentserver is integrated with nextcloud and was working flawlessly for a long time. So, I tend to think, it's a Chrome-related issue.

screenshots illustrating the problem:

![image](https://user-images.githubusercontent.com/43190/74317001-a5762e00-4d8b-11ea-9ac9-015510cf5a8a.png)
![image](https://user-images.githubusercontent.com/43190/74317022-af982c80-4d8b-11ea-8bef-3cb7aa04cfc2.png)

**Comment by aol-nnov** [comment]
just figured out, that text rendering issue occures on some document zoom (cmd + mouse wheel)

browser zoom level is 100% in all cases.

**Comment by aol-nnov** [comment]
possible fix for "Unable to preventDefault inside passive event" is https://github.com/inuyaksa/jquery.nicescroll/issues/799#issuecomment-522275951

**Comment by Rita-Bubnova** [comment]
Hello, @aol-nnov.
This problem seems to be related use hardware acceleration in browser Chrome.
Try disabling the option "Use hardware acceleration when available" in settings Chrome and check if the problem remains.

**Comment by aol-nnov** [comment]
@Rita-Bubnova yes, disabling hw acceleration, kind of, solves the issue, but it is still unclear to me why it triggers in the single and only one document which was created from scratch in that OnlyOffice app.

I'm using Documentserver for a while now in a small team and nobody reports rendering issues. Me neither since two days ago.

I'm not sure if Chrome was autoupdated at some point in time, though...

**Comment by Rita-Bubnova** [comment]
@aol-nnov, could you attach file with problem?

**Comment by aol-nnov** [comment]
@Rita-Bubnova, I can't provide the original document as it's for internal usage only, but I've just created a new document with the very same problems:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/43190/74533729-4e1abe00-4f43-11ea-8095-0e24b2ed0ef3.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/43190/74533744-570b8f80-4f43-11ea-805f-bacad4b8dcb7.png">


and the document in question: 
[АБ_фывфывцукендр_апрнгл_зщшрп_123_456.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4204549/_._._._123_456.docx)

**Comment by aol-nnov** [comment]
Oh, seems to be the table which is causing problems! (and it was copied from another document of unknown origin. Well, they all are in the nextcloud instance now, but I'm not sure how each of them was created)

If table is created by means of OnlyOffice app, there are no rendering issues in Chrome.

**Comment by K0R0L** [comment]
Repeatedly! This is a chrome bug. It has been fixed in the Canary version (please check?). We have two letter blitting modes. For different browsers. At the "default value" the bug is repeated, but on the other it is not (there is a different cache / letter blitting). We will put this into the configuration to the interface in version 5.5. It can sometimes help.

**Comment by aol-nnov** [comment]
@K0R0L do you read me right? As I stated in https://github.com/ONLYOFFICE/DocumentServer/issues/777#issuecomment-586284239 it is not reproduced in the very same Chrome browser if I do not copy that header table from another document, but manually create it.

Also, there are tons of other documents over here without any rendering problems using the very same computer with the very same Chrome browser, etc. for a long time (say, past 6 months)

Still, it is a Chrome bug. I do not get it...

// when 5.5 is due, BTW?

**Comment by K0R0L** [comment]
I read). This is not related to the table. Just rendering commands were formed in the way that leads to the bug. Unfortunately, I don’t have the opportunity to debug Chrome itself right now. It is strange that the same commands are drawn differently depending on the option whether the video card is used for rendering or not. In another blitting mode, we are using another cache letters, and the bug does not repeat on it.

Version 5.5 will be released within a month. We will try early).

**Comment by aol-nnov** [comment]
Okay, thank you for the explanation! Looking forward to 5.5!

And I'll try chrome canary next week. Will report back!

**Comment by aol-nnov** [comment]
Well, I confirm that rendering issues are not reproduced in Chrome Version 82.0.4056.3 (Official Build) canary (64-bit)

Also, I've noticed that if I select all text and then set paragraph background color to white, all letters are rendered just fine at any document zoom level even in Chrome Version 80.0.3987.106 (Official Build) (64-bit), which originally had rendering issues.

**Comment by aol-nnov** [comment]
@K0R0L I've just experienced same rendering issues on Chrome Canary.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/43190/74726269-377cab80-5250-11ea-956a-2d76e49e995e.png">

**Comment by aol-nnov** [comment]
@K0R0L rendering issues still persist in 5.5.0

![image](https://user-images.githubusercontent.com/43190/76450986-c5772c80-63df-11ea-8079-09ad9ea33539.png)

documentserver: 5.5.0
chrome: Version 80.0.3987.132 (Official Build) (64-bit)

> We will put this into the configuration to the interface in version 5.5. It can sometimes help.

what kind of configuration? are you talking about font hinting?

just switched it to "native" and it kind of helped. (not sure for how long ;) )

**Comment by Rita-Bubnova** [comment]
I created issue 50828 in our private issue tracker.
