### ISSUE TITLE
Disconnected after sleep state

### ISSUE THREAD

**Issue by ischiros** [ONLYOFFICE/DocumentServer#778]
Hello,

When I use online edition, each time my computer is back from sleep state, I am disconnected from the document and have to reload the page.
It is quite disturbing because the error message comes after one or two minutes. If I don't think to it before, I sometimes loose data that I've typed.

I run Onlyoffice 4.1.4 with a Nextcloud 16.0.4 VM, hosted by zaclys.com
I use Firefox 72 with MacOS 10.14.6 or 10.15.3.

Screen capture of the error message which is displayed : 
![Capture d’écran 2020-02-12 à 15 21 35](https://user-images.githubusercontent.com/1273505/74344232-92278a80-4dac-11ea-9a1b-aa8469fbc409.png)

Is it an actual bug, or is there some configuration which can be done to solve this issue ?
Thanks in advance,
Mathieu

**Comment by LinneyS** [comment]
Must be fixed
https://github.com/ONLYOFFICE/sdkjs/commit/69850e59f723affcb3c7aa64dfb1c60362f0e5f1

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
