### ISSUE TITLE
Editing cells with controlled values call exception

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#779]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
[Test spreadsheet](https://drive.google.com/open?id=19ZY0Q_CmJJ6h5TahR-Mf_PaGywLYmLwn)
Editing cell in range C4:C64 calls exception.

**DocumentServer version:**
5.4.1.39

**Browser version:**
Firefox, Chrome, etc

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
This problem is due to the lack of data validation in our editor.
This is known issue 41055 in our private tracker.  Same issue for DesktopEditors #159.

**Comment by trofim24** [comment]
We've already implemented support for Data Validation in UI in version 6.2.0.
