### ISSUE TITLE
Support for nodejs 10.x and more

### ISSUE THREAD

**Issue by NewRedsquare** [ONLYOFFICE/DocumentServer#781]
**What is the current behavior?**
Nodejs 8.x is deprecated since 1st January 2020.

**What is the expected behavior?**

It is urgent to get an **official** support for nodejs > 8.x before security issues come.

**Did this work in previous versions of DocumentServer?**
i tried nodejs = 10.x but i had excessive usage of CPU

**DocumentServer version:**
5.4.2-46 (debian package)

**Operating System:**
Ubuntu 18.04.4 LTS

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5 will be released with nodejs 10 support

> i tried nodejs = 10.x but i had excessive usage of CPU
It can be fixed by https://github.com/ONLYOFFICE/DocumentServer/issues/312#issuecomment-392479211

**Comment by NewRedsquare** [comment]
It seems like my problem was due to a problem of permissions.
https://github.com/ONLYOFFICE/DocumentServer/issues/312#issuecomment-493868305
