### ISSUE TITLE
fatal error during document editing

### ISSUE THREAD

**Issue by aol-nnov** [ONLYOFFICE/DocumentServer#782]
While editing a document, whole contents of a document disappears and user is prompted to use "Download as" to save a backup copy.

During that, Chrome Dev tools console shows the following:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/43190/74631433-062baf00-516e-11ea-84be-6482154863fb.png">

Documentserver: latest docker image
Chrome: Version 82.0.4056.3 (Official Build) canary (64-bit)

**Comment by aol-nnov** [comment]
same issue with desktop editor v5.4.2 (367):
<img width="557" alt="image" src="https://user-images.githubusercontent.com/43190/74632212-e7c6b300-516f-11ea-9451-03d787a84497.png">

but "save as..." does not work.

Seems, I've lost some changes now... Bummer!..

**Comment by Rita-Bubnova** [comment]
Hello, @aol-nnov.
You can attach the source file, and the file that was downloaded after the message "An error occurred during the work with the document.
Use the 'Download as...' option to save the file backup copy to your computer hard drive"?

Can you describe what actions led to the error?

**Comment by aol-nnov** [comment]
Unfortunately, those documents are for internal usage only, so I'm unable to expose them.

Also, I've proceeded with desktop editor right after downloading a doc, so I do not have a "right after error" copy of a doc...

> Can you describe what actions led to the error?

Nothing fancy: there was a 9-page table in this document. I was pasting contents from a pdf doc into one column and writing comments in the other column.

The crash was during just typing text.

**Comment by Rita-Bubnova** [comment]
@aol-nnov, can you change the confidential data of the original document without changing its structure?

**Comment by aol-nnov** [comment]
@Rita-Bubnova it's not a "TOP SECRET" :) , I just do not want to expose it in public.

Could you please provide me with some private communication channel?

**Comment by Rita-Bubnova** [comment]
You can send the file to my e-mail: Margarita.Bubnova@onlyoffice.com.

**Comment by aol-nnov** [comment]
Thank you. Just mailed you those files now.

**Comment by Rita-Bubnova** [comment]
Thanks for the mailed file. I can confirm - this is a bug, issue 44526 in our internal issue tracker.

**Comment by aol-nnov** [comment]
Sad to hear that.. Any ETA for the fix or a workaround, may be?..

**Comment by KirillovIlya** [comment]
> Sad to hear that.. Any ETA for the fix or a workaround, may be?..

It will be fixed in the 5.5 version

**Comment by ShockwaveNN** [comment]
Fixed by https://github.com/ONLYOFFICE/sdkjs/commit/fee15c4978e3e2235cf99cfb65ac97e049646698

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
