### ISSUE TITLE
markup issue while leaving collaboration comments

### ISSUE THREAD

**Issue by aol-nnov** [ONLYOFFICE/DocumentServer#783]
While editing a document (provided to @Rita-Bubnova as a part of https://github.com/ONLYOFFICE/DocumentServer/issues/782) I experience the following issue:

In the document with a table a text fragment is selected and comment is added to this fragment via Collaboration -> comment.
Later in the document another fragment is pasted into the table row and those fragments may be non-consecutive - there could be some more text between them.

While editing that newly inserted row (erasing text characters) comment highlight from previous fragment may propagate through the whole text block from previous comment area down to the place where text is currently being edited.

Not sure if it's a rendering issue or comment highlight indeed propagates.

In most cases this can be undone via undo action and wokred around by erasing text charactres in the different order or by adding extra symbols and later removing them.

Chrome Version 82.0.4056.3 (Official Build) canary (64-bit)
Documentserver: latest official docker version

**Comment by Rita-Bubnova** [comment]
Hello.
@aol-nnov, can you attach video or gif of this problem?

**Comment by aol-nnov** [comment]
Sure thing! Will upload to your mailbox shortly.

**Comment by Rita-Bubnova** [comment]
Thank you for attach file and video.
I can confirm - this is a bug, issue 44529 in our internal issue tracker.

**Comment by aol-nnov** [comment]
Hello! Any ETA for this issue? Still able to reproduce it with documentserver 5.5.0.165..

Very annoying.. :(

**Comment by Rita-Bubnova** [comment]
In next major release, possible 5.6.0.
This bug fixed ONLYOFFICE/sdkjs@8921043.

**Comment by trofim24** [comment]
We fixed this problem in version 6.0.0
