### ISSUE TITLE
How to set the font drop-down list of word document to Chinese

### ISSUE THREAD

**Issue by garfieldkai** [ONLYOFFICE/DocumentServer#784]
I installed document server 5.4.2 and I add chinese fonts, but the drop-down list of font are non-chinese.
So how can i set the font drop-down list of word document to Chinese?

**Comment by ShockwaveNN** [comment]
Did you clean browser cache?

**Comment by garfieldkai** [comment]
yes, I cleared after I added fonts
![image](https://user-images.githubusercontent.com/11343590/74670658-99073080-51e4-11ea-9554-27a6792b8e33.png)
These two were my new additions. How to set them to Chinese……

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/332

**Comment by garfieldkai** [comment]
Thank you, so you have no plan to implement this on the documentserver……

**Comment by ShockwaveNN** [comment]
@garfieldkai We plan to implement this feature, but it is not high priority. You can contact sales@onlyoffice.com to change priorities
