### ISSUE TITLE
[feature] Permit to open the left panel at startup

### ISSUE THREAD

**Issue by durandx** [ONLYOFFICE/DocumentServer#785]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
It is not possible to open the ~~right~~ left panel (comments, chat, plugin, navigation, ...) at statup. 

**What is the expected behavior?**
I wanted to open the document editor with the plugin panel automatically open. Unfortunatelly, the autostart parameter only starts the plugin but did not open the panel.

**Did this work in previous versions of DocumentServer?**
No, it's a feature request.

**DocumentServer version:**
5.1.3.35

**Operating System:**
Centos 7.1

**Browser version:**
Google Chrome 79.0.3945.130

**Comment by ShockwaveNN** [comment]
> right panel (comments, chat, plugin, navigation, ...)

This is left panels, not right

> DocumentServer version:
5.1.3.35

This is pretty old (and unsupported) version, could you update, maybe your issue is already resolved

**Comment by durandx** [comment]
Hi, 

In a recent version (5.5), this problem seems to be fixed. The panel is correctly opened at startup when requested.
