### ISSUE TITLE
Chromium based browsers (Yandex, Chrome) in some cases doesn't show some symbols

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#786]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I have no idea how you could reproduce it but in some cases chromium based browser show empty spaces in place of some symbols.
![F2F0A51E](https://user-images.githubusercontent.com/20418709/74738859-93a7f580-5279-11ea-8fd0-3cf5d8119994.PNG)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Maybe it depends on long ping time.

**DocumentServer version:**
5.4.1.39

**Operating System:**
Windows 10

**Browser version:**
Chrome, Yandex

**Comment by Rita-Bubnova** [comment]
Hello, @RuslanGabbasov.
Could you attach file with problem?

This problem seems to be related use hardware acceleration in browser Chrome.
Try disabling the option "Use hardware acceleration when available" in settings Chrome and check if the problem remains.

**Comment by RuslanGabbasov** [comment]
You are absolutely right, disabling hardware acceleration solved the problem. Thanks a lot!

**Comment by Rita-Bubnova** [comment]
Duplicate #777.

**Comment by ShockwaveNN** [comment]
I'll close this issue, main discussion at #777
