### ISSUE TITLE
Incorrect appearance of smart apostrophes in equations

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#788]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
When typing a smart apostrophe in an equation, this apostrophe looks wrong.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert an equation and type "a'" (see attached file).
**What is the expected behavior?**
The apostrophe should look right: small and upper with respect to the previous letter.
Open the attached document in Word to see how it should appear.
**Did this work in previous versions of DocumentServer?**
I don't know.
**DocumentServer version:**
5.4.2, but it happens also on Desktop Editors
**Operating System:**
Linux
**Browser version:**
Firefox 73
[Document1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4225858/Document1.docx)

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
This issue has been fixed and will be released in will be release in v5.5.0.

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is release. This problem should be fixed.
