### ISSUE TITLE
How to config availability of history/revision panel?

### ISSUE THREAD

**Issue by RuslanGabbasov** [ONLYOFFICE/DocumentServer#789]
**Do you want to request a *feature* or report a *bug*?**
*need help*

In documentation https://helpcenter.onlyoffice.com/ru/onlyoffice-editors/onlyoffice-document-editor/usageinstructions/viewdocinfo.aspx showed: 
![image](https://user-images.githubusercontent.com/20418709/74909131-6d996700-53d9-11ea-8308-fff6340e6e36.png)
The panel that displays version and revision history. But we can't find any information describes a configuration of document server that makes it possible. In examples that represented on https://api.onlyoffice.com/editors/try, it doesn't work too.

Please help us. How it works and how we can enable it?

**Comment by ShockwaveNN** [comment]
Hi, you can get a view of this panel using `onlyoffice-documentserver-ie` or `onlyoffice-documentserver-de` integrated test example:
![image](https://user-images.githubusercontent.com/668524/74912282-6bcaa600-53cf-11ea-9111-19515101032e.png)

Also documentation is here:
https://api.onlyoffice.com/editors/history

**Comment by RuslanGabbasov** [comment]
Thank you for helping!

**Comment by ShockwaveNN** [comment]
I'll close this issue, feel free to ask any question or create new issue if anything happens )

**Comment by RuslanGabbasov** [comment]
Hi!
I have added two callback in configuration file:
        var onRequestHistory = function() {
            docEditor.refreshHistory({
                "currentVersion": 1,
                "history": [
                    {
                        "created": "2010-07-06 10:13 AM",
                        "key": "be87eb7ca44e5898964847a717aef440920175e86a34f4a9e78b0aa526d866b8",
                        "user": {
                            "id": "52",
                            "name": "Kate Cage"
                        },
                        "version": 1
                    },
                ]
            });
        };

        var onRequestHistoryData = function(event) {
            var version = event.data;
            docEditor.setHistoryData({
                "key": "be87eb7ca44e5898964847a717aef440920175e86a34f4a9e78b0aa526d866b8",
                "url": "https://example.com/url-to-example-document.docx",
                "version": version
            })
        };

And have added in config:
            "onRequestHistory": onRequestHistory,
            "onRequestHistoryData": onRequestHistoryData,

But when I click on History button I always get endless spinner:
![image](https://user-images.githubusercontent.com/20418709/75030539-20df8a00-54c6-11ea-920f-75cababd5ed5.png)

Browser console is empty, document server log is empty too.
What I do wrong?

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov Sorry, this is out of my area of knowledge.
Maybe @LinneyS can help?

**Comment by RuslanGabbasov** [comment]
Sorry, it's my mistake. I figured out what was wrong.

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov Could you describe your mistake if anyone notice same error?

**Comment by RuslanGabbasov** [comment]
Of course. In my case in the scope of onRequestHistory function wasn't docEditor object. But the error was caught in your code and didn't was shown.

**Comment by ShockwaveNN** [comment]
@RuslanGabbasov Ok, thanks, so if issue resolved - I'll close this issue. Feel free to comment here or create new if something happens

**Comment by new-ranger** [comment]
@RuslanGabbasov I am getting same error " loading version history" continuously coming. Could you plz describe what exactly issue was? What does mean scope of onRequestHistory function wasn't docEditor object?

**Comment by RuslanGabbasov** [comment]
@new-ranger It happened 2 years ago, and I hardly recall what was wrong. In my example just constant docEditor was undefined.

**Comment by ShockwaveNN** [comment]
@new-ranger I think you may get some other error with a similar look

I think it's better to create a new issue, check the JS console for error,s and add more info about your environment (os, DMS etc..)
