### ISSUE TITLE
upgrade from 5.1 to 5.5 installation is broken

### ISSUE THREAD

**Issue by unicorn667** [ONLYOFFICE/DocumentServer#797]
report a bug?

**What is the current behavior?**
After Upgrading from 5.1.5-59 to 5.5.0-165 all config files are overwritten and the installation is broken.  apt ask me if i want the replace this file, a say no. but not work 

How to upgrade from 5.15-59 to the current version ? Any ideas?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

yes

**DocumentServer version:**

root@onlyoffic:~# apt list -a onlyoffice-documentserver                                                                                                      
Listing... Done                                                                                                                                              
onlyoffice-documentserver/squeeze 5.5.0-165 amd64 [upgradable from: 5.1.5-59]                                                                                
onlyoffice-documentserver/now 5.1.5-59 amd64 [installed,upgradable to: 5.5.0-165]    

**Operating System:**
Ubuntu 16.04

**Browser version:**

latest Firefox

**Comment by ShockwaveNN** [comment]
> apt ask me if i want the replace this file, a say no

I think this is correct behavior, config files changed, if you will not replace them old config files with 5.1.5 will not work with 5.5.0. You should backup your config files, replace with new one and setup your custom options again

**Comment by unicorn667** [comment]
Hello,

ok it runs with the new version. But it is not very comfortable. After upgrade and replace the config files.
you must add symlinks in your nginx configuration manual and edit the ds.conf file again.  

copy the onlyoffice-documentserver-ssl.conf.template => ds.conf 

add your ssl certificate and tweak your ssl setup für a+

add following symlinks in your nginx folder /etc/nginx/includes

check nginx config nginx -t

works fine

> 
ds-common.conf -> ../../onlyoffice/documentserver/nginx/includes/ds-common.conf                                     
ds-docservice.conf -> ../../onlyoffice/documentserver/nginx/includes/ds-docservice.conf                             
ds-spellchecker.conf -> ../../onlyoffice/documentserver/nginx/includes/ds-spellchecker.conf                         
http-common.conf -> ../../onlyoffice/documentserver/nginx/includes/http-common.conf                                 
onlyoffice-documentserver-common.conf -> /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-documentserver-common.conf                                                                                                                                                     
onlyoffice-documentserver-docservice.conf -> /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-documentserver-docservice.conf                                                                                                                                             
onlyoffice-http.conf -> /etc/onlyoffice/documentserver/nginx/includes/onlyoffice-http.conf
