### ISSUE TITLE
Error trying to open document from nextcloud after upgrading to version 5.5.0

### ISSUE THREAD

**Issue by much-doge** [ONLYOFFICE/DocumentServer#798]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
Before the upgrade, I can open any document from Nextcloud just fine. After I upgrade Documentserver to 5.5.0 I can't open any document

This is the error I get from nextcloud log
> Error | onlyoffice | GetConvertedUri  on check error: Error occurred in the document service: Error while  downloading the document file to be converted. |  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a document < this step works fine
2. Try to open it, document editor would load up. But it wont be able to open the document, and error would show up.

**What is the expected behavior?**
I can open and edit document from nextcloud

**Did this work in previous versions of DocumentServer?**
Yes, it works flawlessly in version 5.4.2-26

**DocumentServer version:**
5.5.0-165

**Operating System:**
Debian Buster

**Browser version:**
Firefox 73

**Comment by ShockwaveNN** [comment]
Hi, could you look for any errors in DocumentServer logs? at `/var/log/onlyoffice`
