### ISSUE TITLE
debian dependecy hell

### ISSUE THREAD

**Issue by guard43ru** [ONLYOFFICE/DocumentServer#8]
Подключил все репозитории, начинаю установку:

    root@onlyoffice:/var# apt-get install onlyoffice-documentserver
    Чтение списков пакетов… Готово
    Построение дерева зависимостей       
    Чтение информации о состоянии… Готово
    Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
    или же используете нестабильную версию дистрибутива, где запрошенные вами
    пакеты ещё не созданы или были удалены из Incoming.
    Следующая информация, возможно, поможет вам:

    Пакеты, имеющие неудовлетворённые зависимости:
     onlyoffice-documentserver : Зависит: mysql-server-5.6 (>= 5.6.4)
    E: Невозможно исправить ошибки, у вас отложены (held) битые пакеты.

Проверяем что ему нужно:

    root@onlyoffice:/var# aptitude search mysql-server-5.6
    v mysql-server-core-5.6 -

Это виртуальный пакет, который ссылается на:

    root@onlyoffice:/var# aptitude show mysql-server-5.6
    Пакет: mysql-server-5.6
    Состояние: не реальный пакет
    Предоставляется: mysql-community-server

Проверяем пакет:

    root@onlyoffice:/var# dpkg -l | grep mysql
    ii  mysql-client                   5.6.25-1debian7             amd64        MySQL Client meta package depending on latest version
    ii  mysql-common                   5.6.25-1debian7             amd64        MySQL Common
    ii  mysql-community-client         5.6.25-1debian7             amd64        MySQL Client
    ii  mysql-community-server         5.6.25-1debian7             amd64        MySQL Server
    ii  mysql-server                   5.6.25-1debian7             amd64        MySQL Server meta package depending on latest version

Пакеты стоят, но onlyoffice ставиться не будет.

deb-src не нашел, чтобы самостоятельно исправить зависимости, т.к. зайти через веб на репозиторий неполучается чтобы посмотреть структуру и доступные пакеты.

P.S: На CentOS 7 тоже "проблемы", там приходится подключать репозиторий mysql хотя доступна mariadb

P.P.S: Подключение репо squeeze, когда у тебя jessie вызывает моральный дискомфорт, если обновления репо редкие возможно стоит переименовать на stable?)

**Comment by remort** [comment]
Да, у них какаято проблема. onlyoffice-communityserver зависит от mysql-server-5.5 (ну или просто обычного mysql для системы), а onlyoffice-documentserver требует mysql-server-5.6. И все, вместе они не ставятся. А по отдельности не нужны.

Пробовал как на debian8 так и на ubuntu-server 14.04 LTS.
По этому мануалу от них же:
https://help.onlyoffice.com/products/files/doceditor.aspx?fileid=4381391&doc=ZDdHWWYrTVJJMmpUTEVLRkNTOHhUSEplZklDQjQwQWVSajNhQ2VYamk4Zz0_IjQzODEzOTEi0

Удалось запустить это все в докер-контейнерах но оно тормозит безбожно, не могу работать с нашими корпоративными документами, они большие. Так что нужна нормальная версия из пакетов, но не могу ее установить.

Попробую установить onlyoffice-communityserver с его зависимостями , а onlyoffice-documentserver с игнором зависимостей. Но скорее всего ничего хорошего из этого не выйдет.

Это баг, реально, чините.

**Comment by AnaMih** [comment]
To remort: 
Уточните,пожалуйста, следующее: 
1. Насколько большие документы загружаются. Если возможно, то пришлите пример такого документа по адресу support@onlyoffice.com с указанием этогой темы.
2. Конфигурацию сервера, на который производится установка.

**Comment by remort** [comment]
XLS файл 35 мегабайт. Там конфиденциальная, критичная для нашего бизнеса информация. Не могу выслать его вам к сожалению.

Сервера: Оба виртуальные машины под virtual box с включенным апп. эмуляцией, 4 Гб ОЗУ, 20 Гб HDD. debian 8 64 bit и ubuntu server 14.04 64 bit. Пакетная версия устанавливается и работает быстро и адекватно, очень хочется ее попробовать, но не удалось связать communityserver и documentserver (установить их обоих из пакетов).

**Comment by AnaMih** [comment]
Проблема, связанная с xls форматом воспроизвелась. В версии, готовящейся к выпуску подобной проблемы уже нет. Версию планируется выпустить осенью 2015.
Приносим свои извинения за предоставленные неудобства.

**Comment by remort** [comment]
@AnaMih немного не понял:
1. Как вы воспроизвели проблему с xls файлом если у вас не было образца ? Обнаружили проблему открытия больших xls файлов и починили ? Это хорошо, но это не гарантирует что наш файл сконвертируется. Там возможно по другим причинам не конвертируется.
2. Баг вообще не об этом а о том что deb-пакетами невозможно установить на современные дистрибутивы community и document сервер одновременно. С этой проблемой вы сталкивались ? Если у вас все нормально устанавливается, приведите мануал успешной установки, пожалуйста.

**Comment by AnaMih** [comment]
1. Проблема общая для всех xls-файлов. Решение проблемы вошло в тестируемую сейчас версию. Как только версия будет опубликована, Вы сможете проверить на Вашем файле. Шансы решить специфичную проблему конкретных файлов без самих файлов, к сожалению, уменьшаются.
2. Были найдены некоторые проблемы в зависимостях Document и Community Server, разбираемся в чем проблема. Как только она будет решена, решение появится у нас на сайте.

**Comment by remort** [comment]
@AnaMih вот это отличные новости. Быстрое устранение неисправностей располагает к дальнейшему использованию.

**Comment by remort** [comment]
@AnaMih какие прогнозы по этой задаче ? Хочется таки попробовать и настроить ваше решение с перспективой перевода офис на него. Я сижу и жду вас.

**Comment by AnaMih** [comment]
Версия 3.5 с исправлением и прочими изменениями планируется к выпуску в течении месяца.

**Comment by oleg-krv** [comment]
Когда можно ожидать исправленную версию deb пакета?

**Comment by AnaMih** [comment]
К сожалению, на данный момент мы не можем указать временные рамки выпуска deb пакета.
В настоящее время ведется работа по выпуску версии Enterprise. Надеемся выпустить deb пакет через 1-2 месяца, после релиза Enterprise.
Спасибо за терпение.

**Comment by guard43ru** [comment]
Как у вас дела с Document server? А то с сентября 2015 нет никаких изменений.

**Comment by ibnpetr** [comment]
Добрый день
Новая версия [доступна](http://helpcenter.onlyoffice.com/server/linux/enterprise/linux-installation-enterprise.aspx) для установки.
Отпишитесь о результате, пожалуйста.

**Comment by mrartanis** [comment]
Добрый вечер.
Пробовал сегодня.
Onlyoffice-communityserver зависит от мета-пакета mysq, который ссылается на mysql-server-5.5
Onlyoffice-documentserver зависит от mysql-server-5.6.

Скажите, они могут работать на одной версии mysql и можно просто собрать свой мета пакет mysql-server? Или этим компанентам нужны разные версии mysql?

**Comment by mrartanis** [comment]
Вообще, решается это сборкой пакетика mysql-server и mysql-client с зависимостью от mysql-server-5.6 и mysql-client-5.6 соответственно.
Ну, или если лень бэкпортировать, можно просто поставить указанные мета-пакеты из более свежей убунты(например 15.10) на 14.04 - а после начать установку oo.

Ну и да, с выходом 16.04 проблема исчезнет.

**Comment by trofim24** [comment]
Выпустили новую версию. В зависимостях у documentserver-а mysql-server (>= 5.5)

**Comment by efureev** [comment]
Как решить проблему, если установлена mariadb?

**Comment by mrartanis** [comment]
Установить ее на отдельный хост :)
А еще можно закостылить: http://blog.rot13.org/2014/04/fixing-debian-depenencies-using-fake-package.html

А вообще, в зависимостях оо можно было бы сделать и package1 | package2. С другой стороны, хотя maria db тот же mysql, но разработчики оо тестировались именно с последним.

**Comment by efureev** [comment]
@mrartanis тоже так считаю. Для целей этого сервера - это полный аналог. Спасибо за фейковые зависимости)

**Comment by Schroedingers-Cat** [comment]
Could someone summarize this in english? Is there a solution to this problem?

**Comment by mrartanis** [comment]
In old versions os onlyoffice packages, document server depend of mysql-5.5 and communityserver depend on mysql-5.6.
Your options:
Use ubuntu 16.04 - all fine there
If you use 14.04 - backport mysql-server metapackage from newer ubuntu (15.10 for example), or just install it manually before installing OnlyOffice.

In current version of OnlyOffice developers fix this. Both packages depends of mysql-server-5.6
