### ISSUE TITLE
Access Rights to the Web Server Directory /var/www/ 

### ISSUE THREAD

**Issue by nils-schween** [ONLYOFFICE/DocumentServer#802]
Hello everyone,

I would like to report a somewhat strange glitch, which I found while setting up the OnlyOffice Document Server on Debian Buster.
To install the Document Server I followed the instructions which can be found in the [helpcenter](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx). Hence, I am using the Debian repository and I installed the Document Server with apt.

It was not working out of the box, and looking into the log files (e.g, /var/log/onlyoffice/documentserver/docservice/err.log) I saw the following error messages:

`supervisor: couldn't chdir to /var/www/onlyoffice/documentserver/server/DocService: EACCES`  
`supervisor: child process was not spawned`
`supervisor: couldn't chdir to /var/www/onlyoffice/documentserver/server/DocService: EACCES`
`supervisor: child process was not spawned`

The supervisor was not able to access my web server's directory. 
I checked the rights of the web server's directory and I got the following result
`drwx-rwx---- www-data www-data /var/www/`

In a next step, I checked if the user to whom OnlyOffice belongs, which is the user "ds", was part of the www-data group. Here is the output of `cat /etc/group | grep www-data` :
`ds:x:119:www-data`

Hence, "ds" was part of the "www-data" group and I expect it to have the rights to access the web-server's directory /var/www/ . But obviously the "supervisor" tool did not have access.

I changed the owner of the /var/www/ directory to be "ds". And it worked. 

I really do not like this setup, the /var/www/ should belong to the "www-data" user and not to the owner of the document server "ds". Why is it, that "ds" must own /var/www/ and can we change this to the more expected behaviour, that if "ds" is part of www-data group it has access to its files?

Thanks a lot.

**Comment by ShockwaveNN** [comment]
@agolybev please take a look

**Comment by agolybev** [comment]
Hi @nils-schween, I think you have to install nginx (`nginx-extras` package) before document server installation. There is a notice about it in the installation guide but it mentioned only Ubuntu releases.

**Comment by nils-schween** [comment]
Hi,
@agolybev thanks for your answer. To be honest I am a little bit confused. What does the order of installation change? I would, for example, love to see how the config files in /etc/supervisor/conf.d would look like, if I had installed nginx-extras before the document server. 
All the ds-*.conf files in this folder  contain a line with
`user=ds` 
This line seems to restrict the access of the supervisor program to folders which are owned by the user "ds". 
Would there be an additional line, which tells supervisor, that it also has access to folders which belong to the "www-data" group?

Can you post the content of these files for the scenario that the user running the web server (www-data) is different from the user owning the document server (ds)? And are other config files which I have to change.

Once more: thank you.
Nils

**Comment by the-technat** [comment]
Is this still an issue tracked? I encountered the same issue and stumbled upon that. It seems to be true that the document services only work when `/var/www` is owned by `ds:ds`. Would also be interested in seeing if this could be changed somehow without having to edit all configuration files coming with the onlyoffice-documentserver debian package...

**Comment by ShockwaveNN** [comment]
@igwyd Please take a look, this is a good explanation of the problem

@the-technat Thanks for detailed report

**Comment by igwyd** [comment]
Hello @the-technat, by default the directory /var/www owner is user root(in nginx and apache) and with default permissions ONLYOFFICE DocumentServer install without errors. Why do change owner /var/www?

**Comment by the-technat** [comment]
@igwyd it was just the easiest way for my backup solution. If I remember correctly the user home of `www-data` is `/var/www`, so I places my scripts in there. But will definitely try to find another solution for this and switch the owner of `/var/www`  to root. 

If this works, I think this issue can be closed as it only appears on non-default setups...

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
