### ISSUE TITLE
How to switch Document Server to HTTPS protocol?

### ISSUE THREAD

**Issue by Sys-Admin889** [ONLYOFFICE/DocumentServer#806]
Hello everyone,
I have an onlyoffice document server v 5.5.0 installed on Ubuntu 18.4, installed as the following instructions: https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx
But I need to install HTTPS protocol to integrate onlyoffice document server with nextcloud server, I tried to follow these instructions: https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx to install HTTPS protocol but I don't know how to get these parameters "paths" that described below?

Edit the /etc/onlyoffice/documentserver/nginx/ds.conf file changing all the parameters in double curly brackets {{...}} for the actually used:
{{SSL_CERTIFICATE_PATH}} - the path to the SSL certificate you have got;
{{SSL_KEY_PATH}} - the path to the SSL certificate private key;
{{SSL_VERIFY_CLIENT}} - whether or not the verification of client certificates is enabled (with available values of on, off, optional and optional_no_ca);
{{CA_CERTIFICATES_PATH}} - the path to the client certificate which will be verified if enabled with the previous parameter;
{{ONLYOFFICE_HTTPS_HSTS_MAXAGE}} - advanced configuration option for setting the HSTS max-age in the Document Server NGINX vHost configuration, and applicable only when SSL is in use (usually defaults to 31536000 which is considered to be safe enough);
{{SSL_DHPARAM_PATH}} - the path to the Diffie-Hellman parameter;
Please see NGINX documentation for more information on SSL parameters used in the configuration file.

Also I need to know how to create a security certificate and the certificate private key?

**Comment by ShockwaveNN** [comment]
> I don't know how to get these parameters "paths" that described below?

I think you missed step 2
`sudo cp -f /etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl /etc/onlyoffice/documentserver/nginx/ds.conf`|

> Also I need to know how to create a security certificate and the certificate private key?

It's up to you how do you want create certificate, you can buy, create self signed or use let's encrypt cert

**Comment by Sys-Admin889** [comment]
@ShockwaveNN Thanks for clarification, I prefer to create self signed certificate, Do you advise me to follow these instructions? https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-18-04.

**Comment by ShockwaveNN** [comment]
@Sys-Admin889 Sorry, cannot advise any instruction, I'm not very good at understanding SSL, but I think any instruction will be good
Also you can find some info at [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/#generation-of-self-signed-certificates)

**Comment by Sys-Admin889** [comment]
Solved.
