### ISSUE TITLE
Cannot read property 'b8d' of undefined

### ISSUE THREAD

**Issue by metaxy** [ONLYOFFICE/DocumentServer#808]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The files does not open

![Screenshot_20200312_092012](https://user-images.githubusercontent.com/82704/76501526-b4133c00-6442-11ea-9ebc-d27a62677691.png)

We were editing a docx document. Somewhere in middle where not able to open it anymore.
In the console log this error was thrown: 
```
sdk-all.js:6227 Uncaught TypeError: Cannot read property 'b8d' of undefined
    at dc.nb.BG (sdk-all.js:6227)
    at dq.Xg (sdk-all.js:7004)
    at Pa.D3d (sdk-all-min.js:615)
    at aE.ab.ETc (sdk-all-min.js:619)
    at aE.ab.r_b (sdk-all-min.js:618)
    at Ia.Xzb (sdk-all-min.js:916)
    at Object.aaf (sdk-all-min.js:391)
    at Ia.Xzb (sdk-all-min.js:916)
    at Ia.njd (sdk-all-min.js:915)
    at Object.osa (sdk-all.js:4755)
```
in this code in `sdkjs/word/sdk-all.js`

```
 nb.prototype.BG = function() {
        this.bb && (this.bb.ey.b8d(),
        this.bb.kd.Z7a(Kl))
    }
    ;
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Click on the file and wait. I cannot reproduce the file, because i cannot open or export it.

**What is the expected behavior?**

It should open and be editable

**Did this work in previous versions of DocumentServer?**

Don't know.

**DocumentServer version:** Version: 5.4.2 (build:46) (because we are using nextcloud with the following apps Community Document Server: 0.1.5  and ONLYOFFICE: 4.1.4)

**Operating System:** Ubuntu 18.04

**Browser version:** Chrome 80 and Firefox 73

**Comment by ShockwaveNN** [comment]
1. 5.4.2 is not latest version of DocumentServer, please upgrade to 5.5.0
2. > because we are using nextcloud with the following apps Community Document Server: 0.1.5
 
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository.

**Comment by metaxy** [comment]
Thank you. Yes i did open a issue with them: https://github.com/nextcloud/documentserver_community/issues/88

But the question for me is, whether the document is recoverable? Could it work again after a update to 5.5.0?

**Comment by ShockwaveNN** [comment]
I'm not sure, I have no experience with `Community Document Server`. It's a separate product which use some codebase of ONLYOFFICE, but it's it's different in major ways

**Comment by ShockwaveNN** [comment]
And I'll close this issue, since it's not ONLYOFFICE bug, but feel free to comment if have any question

**Comment by ShockwaveNN** [comment]
Moving this issue to onlyoffice-nextcloud repo to apply tag.
