### ISSUE TITLE
How to modify default font size 

### ISSUE THREAD

**Issue by ToBigToSmall** [ONLYOFFICE/DocumentServer#816]
Hi...Developers. I want to add font size in scroll bar,just like 
![image](https://user-images.githubusercontent.com/33725817/76945697-db37a500-693d-11ea-9040-278f97627fd1.png)
Please tell me how to editor default font size.
Best wishes to u.

**Comment by ToBigToSmall** [comment]
I had change all app.js file and remove all cache and  "/usr/bin/documentserver-generate-allfonts.sh", but seems not work.
![image](https://user-images.githubusercontent.com/33725817/76945883-218d0400-693e-11ea-98fe-d655ff1eafc9.png)

**Comment by ShockwaveNN** [comment]
@ToBigToSmall Hi, currently there is no easy way to customize this list. 
In theory we can add this feature, but this need approval from sales team. You'll better to contact sales@onlyoffice.com and discuss this

**Comment by ToBigToSmall** [comment]
ok，thanks
