### ISSUE TITLE
can I upload documents as data stream

### ISSUE THREAD

**Issue by garfieldkai** [ONLYOFFICE/DocumentServer#819]
when I upload a document from my computer to the document server, I have to set "document.url" in DocsAPI.DocEditor, and the document must be on my disk drive，but data is insecurity; my question is can I upload document as data stream? Is there any relevant interface to implement this.

**Comment by ShockwaveNN** [comment]
> the document must be on my disk drive

You can attach any link to doc, not only on local drive.

Could you  provide a more detailed example of that you want to do?
