### ISSUE TITLE
Missing help langages in RPM package

### ISSUE THREAD

**Issue by durandx** [ONLYOFFICE/DocumentServer#82]
**Do you want to request a *feature* or report a *bug*?**
BUG Report
**What is the current behavior?**

Nginx error 404 when fetching help in  langage de, es, it, fr

```
[error] 8084#8084: *224264 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/help/fr/Contents.json" failed (2: No such file or directory),
...
```

The latest RPM binary onlyoffice-documentserver.x86_64.rpm only conains help langage for en and ru.

The following langage are missing for help pages (\var\www\onlyoffice\documentserver\web-apps\apps\documenteditor\main\resources\help\):

de, es, it, fr

Those files exists in : https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/main/resources/help

Do we need to install extra langages packages ?

FYI, those langages are correctly bundled in \var\www\onlyoffice\documentserver\web-apps\apps\documenteditor\main\locale\

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use a langage in de, es, it, fr
```javascript
            docEditor = new DocsAPI.DocEditor({
                                         ....
                                         editorConfig; {
                                                 ...
                                                 lang: "de",
                                                 ...
                                         }
                                         ...
                               });
```
**What is the expected behavior?**
No errors and a localized Help.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
Version DocumentServer : 4.2.10
OS: CentOs 7.3

**Comment by ibnpetr** [comment]
Hello 
I regret to inform you that DocumentServer doesn't have localized help files at the moment, we will do our best to add other languages to the help files in the nearest future.

> Those files exists in : https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/main/resources/help

I am afraid that you are mistaken, those files are the interface localized resources and do not have anything in common with help files.

**Comment by durandx** [comment]
I thought the localized resources where under https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/main/locale.

When I go to the help page in French i got : 
![image](https://cloud.githubusercontent.com/assets/9220437/23407041/37fb75cc-fdc2-11e6-8b56-36c6ff584da7.png)

When I copy all the files under https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/main/resources/help

in /var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/help

I got the correct help page :
![image](https://cloud.githubusercontent.com/assets/9220437/23407093/7c77a608-fdc2-11e6-8533-0326b2ec7e6f.png)

After patching the files under /var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/help with https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/main/resources/help files, the problem is solved for me.

**Comment by ibnpetr** [comment]
Sorry, my mistake, of course I meant https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/main/locale
The fact is that we do not include the help files in other languages as they are not actual at this moment.
We will include them as soon as the are updated.
