### ISSUE TITLE
Error editing spreadsheet and presentation

### ISSUE THREAD

**Issue by sankura** [ONLYOFFICE/DocumentServer#820]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
currently we testing our onlyoffice license with nextcloud.
DocumentServer is installed via docker.
currently, editing and working with documents is flawless, but spreedsheets and presentation wont work.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open xlsx or pptx in nextcloud enterprise 17.0.4 with onlyoffice
Error:
`[2020-03-23T11:07:40.438] [ERROR] nodeJS - changesError: docId = 1707157236 Error: TypeError: dd.dKb is not a function Script: https://hostname/5.5.0-165/sdkjs/common/libfont/wasm/fonts.js Line: 37:282 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/2010010
1 Firefox/74.0 platform: Win32 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: @https://hostname/5.5.0-165/sdkjs
/common/libfont/wasm/fonts.js:37:282
@https://hostname/5.5.0-165/sdkjs/common/libfont/wasm/fonts.js:37:289`

**What is the expected behavior?**
opens the document
**Did this work in previous versions of DocumentServer?**
N/A
**DocumentServer version:**
5.5.0-165
**Operating System:**
Debian Buster
**Browser version:**
Firefox 74

**Comment by ShockwaveNN** [comment]
@sankura Hi, this is strange error. Does this error happens to any xlsx or pptx file, or just empty?
Does this error only for firefox on happens in Google Chrome?

**Comment by sankura** [comment]
Hello @ShockwaveNN 

we figured out it was a problem with some users having ublock installed on firefox.
its rather strange, but whitelisting the documentserver fixes the problem.
