### ISSUE TITLE
The problem of thinning after saving the pull-down bar

### ISSUE THREAD

**Issue by ileayn** [ONLYOFFICE/DocumentServer#821]
What is the current behavior?

I first create an EXECL and save it. At this time, the lower progress bar is normal. When the file version becomes ver.1.0, I open it again. The  lower progress bar very small. If I pull it, I will run to the back. Because it's too small, I will pull it down a lot.
Whether I delete the unnecessary content or delete the list, the progress bar below is still small.

DocumentServer version:
5.5.0

Operating System:
Windows10   Windows7   WindowsXP

Browser version:
Google 
Firefox

**Comment by Rita-Bubnova** [comment]
Hello, @ileayn.
Could you attach video of this problem?

**Comment by ileayn** [comment]
Hello Bubnova, 
     Thanks for your reply.
     When you create a new Execl file， the execl file Dropdown bar is OK. After the add information and Close the file.


   When open again，Update file to Ver1.0, The Dropdown bar change the small.
I'm Sorry.My english is not good.Can you understand that?


发件人："Rita-Bubnova" <notifications@github.com>
发送日期：2020-03-24 15:54:05
收件人：ONLYOFFICE/DocumentServer <DocumentServer@noreply.github.com>
抄送人：ileayn <wjwu@syncozymes.com>,Mention <mention@noreply.github.com>
主题：Re: [ONLYOFFICE/DocumentServer] The problem of thinning after saving the pull-down bar (#821)


Hello, @ileayn.
Could you attach video of this problem?

**Comment by Rita-Bubnova** [comment]
Sorry @ileayn, I can't under understand what you mean. 
Could you attach video of this problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
