### ISSUE TITLE
Installed the Chinese font, open a document, as long as the carriage return, the Chinese garbled

### ISSUE THREAD

**Issue by LanyeWu** [ONLYOFFICE/DocumentServer#83]
Centos 7 installed in the Chinese font, in the windows environment to create a new word document. And then use OnlyOffice open, as long as there is no carriage return, you can normally enter the Chinese. After the carriage return, the font automatically becomes an imitation 仿宋_GB2312. Is there any solution?
![default](https://cloud.githubusercontent.com/assets/3364827/23542149/88ba9a5e-0026-11e7-96c5-9909e8196b69.png)
![default](https://cloud.githubusercontent.com/assets/3364827/23542163/98fae522-0026-11e7-98f6-970a674accf4.png)

**Comment by JohnPerkin** [comment]
Hello!
Please send to us a document where the issue occurs.
Thank you for the interest in ONLYOFFICE.

**Comment by JohnPerkin** [comment]
Dear ONLYOFFICE users!
We are working hard on implementation of asian fonts in Document Server. So we need both standard and non-standard fonts to analyze their behaviour in our product. Please send us fonts via support@onlyoffice.com or attach them to your messages. We will appreciate your assistance.
Best regards
John
ONLYOFFICE support team

**Comment by nettree** [comment]
Have you tried to clear the browser cache? I just encounter some issue with font list after installing a new font, maybe you can try this solution and see whether it fixes the issue.

**Comment by ShockwaveNN** [comment]
I think this issue should be resolved by now, if not please open a new issue with example document attached
