### ISSUE TITLE
768 worker_connections are not enough

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#830]
**Do you want to request a *feature* or report a *bug*?**
dont know
**What is the current behavior?**
in time of corona we have a huge user on uur onlyoffice Server. We have a license with 1000 Conections. 

**What is the expected behavior?**
Configure ONLYOFFICE to support maximum License connection

**DocumentServer version:**
5.4.2
**Operating System:**
Debian 10.3 
Linux version 4.19.0-8-cloud-amd64

I have read there are some configuration that might be work:

> worker_connections
> 
> The total amount of connections is worker_process * worker_connections. Half in load balancer mode.
> 
> Now we're reaching the toaster part. There are many seriously underrated system limits:
> 
>     ulimits is 1k max open files per process on linux (1k soft, 4k hard on some distro)
>     systemd limits is about the same as ulimits.
>     nginx default is 512 connections per worker.
>     There might be more: SELinux, sysctl, supervisord (each distro+version is slightly different)

Do you have any best practice?

**Comment by flaminestone** [comment]
Hello @hahaxd35. 
By default, connection count is different for some installation.

If you want to change it, you can change `worker_connections` in nginx config, and apply this chages by `nginx reload`. It is a good way for quick fix you problem.

**Comment by hahaxd35** [comment]
thanks work (for now)

**Comment by ShockwaveNN** [comment]
I'll close this issue but feel free to comment if have any question or create new issue
