### ISSUE TITLE
Translator some Error code when show

### ISSUE THREAD

**Issue by ttqminh** [ONLYOFFICE/DocumentServer#834]
Dear All,
When i open one spreadsheet with another tab, Dialog it's show. I need translate some error code to text message. It's configuration files?

![error_code](https://user-images.githubusercontent.com/42667254/78648917-e6e80d00-78e6-11ea-8d19-9512d0b4337b.png)

**DocumentServer version:**
Version: 5.5.0 (build:165)
**Operating System:**
CentOS 7
**Browser version:**
Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by Rita-Bubnova** [comment]
Hello, @ttqminh.
Thank you for your report.
This bug fixed https://github.com/ONLYOFFICE/web-apps/commit/ed372021333902cae3921dc8f35ff980a7cdd098.
We hope this will be release as 5.5.2.

**Comment by ShockwaveNN** [comment]
DocumentServer 5.5.3 released, this issue should be fixed
