### ISSUE TITLE
txt options select

### ISSUE THREAD

**Issue by Edison6351** [ONLYOFFICE/DocumentServer#839]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
i'm iIntegration the DocumentEditor ,but i got this error please help on this.
![image](https://user-images.githubusercontent.com/8285762/78987762-81538500-7b61-11ea-87ea-3b1a8bf1cdbe.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
No
**DocumentServer version:**
5.4.2
**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment]
Which filetype you are sending?
https://api.onlyoffice.com/editors/config/document#fileType

**Comment by Edison6351** [comment]
i send file_type:'docx', it's that correct?

**Comment by Edison6351** [comment]
i'm don't know , i send the docx file to editor but, some file are editor very well.and some file are show the txt options select window, where to find log?thank you every much :)

**Comment by ShockwaveNN** [comment]
@Edison6351 log at `/var/www/onlyoffice/documentserver`

> i send the docx file to editor but, some file are editor very well.and some file are show the txt options

Could you attach one example of bad file

**Comment by Edison6351** [comment]
I can‘t find any useful info in that path，i can promise my file was open by MS Office correct

**Comment by ShockwaveNN** [comment]
@LinneyS Please take a look, maybe you have some idea?

**Comment by Edison6351** [comment]
error file, like this @ShockwaveNN 
[5e4b49a872b40.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4461785/5e4b49a872b40.docx)

**Comment by Edison6351** [comment]
does this warning message any help? @ShockwaveNN 
![image](https://user-images.githubusercontent.com/8285762/78997927-1f534980-7b7a-11ea-92ea-8741cb7b844d.png)

**Comment by ShockwaveNN** [comment]
@Edison6351 No, I dont think was error can cause it.

Could you attach all logs in /var/log/onlyoffice?

**Comment by Edison6351** [comment]
[onlyoffice.tar.gz](https://github.com/ONLYOFFICE/DocumentServer/files/4462000/onlyoffice.tar.gz)
here is the log

**Comment by ShockwaveNN** [comment]
@Edison6351 First I advice you to upgrade to latest version of DocumentServer

Second one -  I see a lof of different errors in logs, especially ones with database and I don't like.

So I think it's better to cleanup logs from your previous attempts and try out this error again

**Comment by Edison6351** [comment]
there's no useful info in the logs, where i can open the debug mode in DocumentEditor? @ShockwaveNN

**Comment by ShockwaveNN** [comment]
We think possible reason is this error:
```
[2020-04-10T18:34:15.451] [WARN] nodeJS - downloadUrlPromise body size mismatch: uri=https://lbp.it.lixiangoa.com:9528/lbp/work/get_document_file/191/docx; content-length=212096; body.length=81588
```

You can try to debug via adding
`NODE_DEBUG=request`
to enviroment line in 
`/etc/onlyoffice/documentserver/supervisor/ds-converter.conf`
and 
`/etc/onlyoffice/documentserver/supervisor/ds-docservice.conf`

**Comment by Edison6351** [comment]
OK, add this option need to restart service? you mean body size mismatch cause the error, right?

**Comment by ShockwaveNN** [comment]
@Edison6351 Yeah, we think so, but don't know the reason of this mismatch

**Comment by Edison6351** [comment]
ok，i‘ll try later please don't close this.

**Comment by Edison6351** [comment]
> We think possible reason is this error:
> 
> ```
> [2020-04-10T18:34:15.451] [WARN] nodeJS - downloadUrlPromise body size mismatch: uri=https://lbp.it.lixiangoa.com:9528/lbp/work/get_document_file/191/docx; content-length=212096; body.length=81588
> ```
> 
> You can try to debug via adding
> `NODE_DEBUG=request`
> to enviroment line in
> `/etc/onlyoffice/documentserver/supervisor/ds-converter.conf`
> and
> `/etc/onlyoffice/documentserver/supervisor/ds-docservice.conf`

this conf no effect, not more log generate. @ShockwaveNN

**Comment by ShockwaveNN** [comment]
@konovalovsergey Please take a look

**Comment by Edison6351** [comment]
@ShockwaveNN many thanks for reply, i found the issue. it's on my supply the file to onlyoffice.
