### ISSUE TITLE
How to setup local development environment？

### ISSUE THREAD

**Issue by dickeyxian** [ONLYOFFICE/DocumentServer#84]
Hi, I installed a ONLYOFFICE Document Server Docker Version.  I changed the web-apps or sdkjs code and need make build code every time, It takes long time.  How do you build a local development environment? or Can you introduce how you developed it？

**Comment by trofim24** [comment]
Hi. We run the server separately by [this instruction](https://github.com/ONLYOFFICE/server/blob/master/Readme.md)
And we open through [integration example](https://github.com/ONLYOFFICE/document-server-integration)

**Comment by sumanth-spotdraft** [comment]
@hackerxian were you able to run locally without having to wait for long build time?
