### ISSUE TITLE
504 Timeout, installed with /DS_PORT option

### ISSUE THREAD

**Issue by T0MuX** [ONLYOFFICE/DocumentServer#841]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
I get 504 Gateway Time-out when I access it. Tiny detail : I access it by http://localhost:8020/ and when the timeout shows up I see this url in the adress bar http://localhost:8020/welcome/. So, I think the web server get the initial request, but the reverse proxy to others modules doesnt work correctly (I guess).
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
First, I install it with the following command `onlyoffice-documentserver.exe /DS_PORT=8020` (because the 80 port is already used on this server)
**What is the expected behavior?**
Just working out of the box :) (I mean, accessing normally to the document server on localhost and using the choosen port)
**Did this work in previous versions of DocumentServer?**
I don't know, this is my first time
**DocumentServer version:**
5.3.4
**Operating System:**
Windows Server 2012R2
**Browser version:**
Firefox 75 x64

**I provide some other details, and tests**
Context & versions : 
- Erlang v22 on localhost
- RabbitMQ v3.5.4 on locahost
- Redis v3.2.100 on localhost
- PostgreSQL on another server (a dedicated linux database server on the same network)

I took a look into the nginx configuration (ds.conf) and the listening port is 8020 `listen 0.0.0.0:8020;`
Also, in the http-common.conf file, I have this : 
```
upstream docservice {  
  server localhost:8000;
}

upstream spellchecker {  
  server localhost:8080;
}
```

I tried with this instead, but dint change anything :
```
upstream docservice {  
  server localhost:8021;
}

upstream spellchecker {  
  server localhost:8022;
}
```

I also tried with this, in nginx.conf, didnt change anything neither :
`keepalive_timeout 65;`

**Comment by ShockwaveNN** [comment]
> DocumentServer version:
5.3.4

Could you update to latest release, this version is pretty outdated

**Comment by T0MuX** [comment]
So, just to mention : this wiki make me download a 5.3 version https://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx. So, I downloaded the latest from https://sourceforge.net/projects/teamlab/files/ONLYOFFICE_DocumentServer/v5.5/binaries/onlyoffice-documentserver.exe/download

Then, I updated DocumentServer (always using the /DS_PORT argument). Then, the installation detects the previous version, and suggest to uninstall it before install the new, I press OK. And now, the uninstall process is stuck at the start :D 

I tried to stop all the DS services... nothing better. I just can't uninstall it :open_mouth: 
![image](https://user-images.githubusercontent.com/19415987/79225733-764c6d80-7e5d-11ea-9855-859c167ed06b.png)

**Comment by ShockwaveNN** [comment]
@DenisDeeSign Take a look please, seems like this is windows specific problem

**Comment by DenisDeeSign** [comment]
Hello, @T0MuX.
Please describe what version you finally installed? You can check it at Programs and Features on your server.

**Comment by T0MuX** [comment]
Hi @DenisDeeSign 
as described, I couldn't uninstall the installed version, which is 5.3.4 (first post).
I don't know why, but Windows doesn't want to uninstall it. It is stuck like the screenshot I posted (I tried to let it all the night, didn't move).

**Comment by DenisDeeSign** [comment]
Seems RabbitMQ version is too old for current version Erlang and its service couldn't be start. Look at [compatibility table](https://www.rabbitmq.com/which-erlang.html). Update RebbitMQ to version 3.7.15 or higher.

**Comment by T0MuX** [comment]
But, the fact I can't uninstall DocumentServer is not related to this. I just updated RabbitMQ to 3.8.3, and I still can't upgrade OODE to 5.5.1.76. The installer suggest to uninstall the installed version, and the uninstaller is stuck exactly like the previous screenshot.

BUT, excellent news : since the upgrade of RabbitMQ, I access correctly to my fresh installed OnlyOffice DE.

BUT (again), I still can't upgrade it.

**Comment by T0MuX** [comment]
May I create a new issue regarding the uninstall/upgrade specificly ?

**Comment by DenisDeeSign** [comment]
@T0MuX, please, restart Redis and RabbitMQ services and try to update DocumentServer once again. If it will not help, plese create a separate issue.
And DocumentServer is now working on a port 8020, doesn't it?

**Comment by T0MuX** [comment]
@DenisDeeSign Yes, I can access to OnlyOffice DE on localhost:8020. So I think this issue is closed.

Indeed, I will create a separate issue for the uninstall/upgrade problem. I just tried to stop every services before uninstalling, nothing more happens.
