### ISSUE TITLE
OnlyOffice open file slow.

### ISSUE THREAD

**Issue by yoyomule** [ONLYOFFICE/DocumentServer#843]
Hi! I install OnlyOffice Community Edition use docker,when I run the demo I find the file is opened very slowly in the first time ,in the next time it will be fast. But if I close the browers or open opening another file and open it again,the same issue will be happened. I tested a 4MB word file and it took more than a minute to open. At the same time, actually requested a file close to 60MB.
   I have checked some information, it seems that it is because a lot of font files are loaded. Is there a better solution to this problem, such as using a good caching mechanism, or other solutions.Onlyoffice is a good product, but this problem does affect the user experience. Thanks.
![QQ截图20200415085157](https://user-images.githubusercontent.com/10000818/79288205-b1e84580-7ef8-11ea-8ffa-85391c37cf7a.png)

**Comment by ShockwaveNN** [comment]
> But if I close the browers or open opening another file and open it again,the same issue will be happened.

This is not right, Those fonts should be cached only once on each browser, after that - opening file should be much quicker.
Maybe some browser addons blocking this?

**Comment by cpot** [comment]
We have also the problem

**Comment by ShockwaveNN** [comment]
@cpot Sorry, without some details it's impossible to understand that is the problem

**Comment by cpot** [comment]
@ShockwaveNN  thank you for the answer; i will see if we can put some resources on it to do additional tests

**Comment by yoyomule** [comment]
![image](https://user-images.githubusercontent.com/10000818/101869216-e3193280-3bb9-11eb-9fa5-166ba46a880d.png)
![image](https://user-images.githubusercontent.com/10000818/101869221-e6142300-3bb9-11eb-9422-b69df10eb534.png)
It seems that not only the font problem, but also some other problems cause the slowness. Basically it is relatively slow, this is just a small file.

**Comment by yoyomule** [comment]
![image](https://user-images.githubusercontent.com/10000818/101869216-e3193280-3bb9-11eb-9fa5-166ba46a880d.png)
![image](https://user-images.githubusercontent.com/10000818/101869221-e6142300-3bb9-11eb-9422-b69df10eb534.png)
It seems that not only the font problem, but also some other problems cause the slowness. Basically it is relatively slow, this is just a small file.

**Comment by ShockwaveNN** [comment]
@yoyomule As far as I know those are just static icons that served by nginx, maybe you got something wrong with it, maybe some network issues

I'm not very good at network diagnostic, so only advice I can give to you - try to open file on same machine you're setup DocumentServer to make sure, that network connection is not an issue

**Comment by yoyomule** [comment]
It is very fast to open the picture address directly through the browser, I don't think it is a network problem.
![image](https://user-images.githubusercontent.com/10000818/101872543-60e03c80-3bc0-11eb-81da-a06a27da69fc.png)
![image](https://user-images.githubusercontent.com/10000818/101872544-6178d300-3bc0-11eb-8ad1-bcb313ca1692.png)

**Comment by ShockwaveNN** [comment]
@yoyomule I have no idea unless this is some specific nginx setup, couly you try to setup our default Docker image and check if this problem actual there too

**Comment by yoyomule** [comment]
Yes, it is the docker image you provided.

**Comment by cpot** [comment]
After some internal discussions, it seems that this bad behavior could be because that the Font selection listbox is not created asynchronously and large fonts like "WenQuanYi Bitmap Song" slow down a lot Onlyoffice opening. 

This is a shame because a lot of users are working remotely with ADSL network and complain a about this.

Remember that some organizations can force to empty the cache of the browser when it is closed at the end of the working day. Therefore, every day, there will be a performance impact for every users, just to build the "font listbox"
![image](https://user-images.githubusercontent.com/3287514/119512212-68149480-bd73-11eb-95d6-1f2def7fac8c.png)

**Comment by ShockwaveNN** [comment]
@cpot Any idea how we should resolve it?

If we try to open document until complicated CJK fonts are loaded - if this document contain those fonts - it'll render incorrect

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
