### ISSUE TITLE
Keyboard shortcuts for inserting entire row/column

### ISSUE THREAD

**Issue by asoltesz** [ONLYOFFICE/DocumentServer#844]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There are no keyboard shortcuts for inserting an entire row or column.

These are very often used operations in spreadsheet editing. Similar web/desktop editors (Google, LibreOffice desktop) have shortcuts for these operations.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not a bug.

**What is the expected behavior?**

Both operations have a dedicated shortcut for them:
- insert row (above)
- insert column (before)

**Did this work in previous versions of DocumentServer?**

No

**DocumentServer version:**

5.5.1

Tested with the NexCloud distribution.

**Operating System:**

Linux, Ubuntu 18.04

**Browser version:**

Firefox 75

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DesktopEditors/issues/282.
