### ISSUE TITLE
这是之前总结的onlyoffice编辑器使用技巧，大家略作参考

### ISSUE THREAD

**Issue by wylc** [ONLYOFFICE/DocumentServer#848]
https://www.songbin.top/column/list?cid=5

**Comment by ShockwaveNN** [comment]
Please, use only English in issues

**Comment by wylc** [comment]
why?Perhaps Chinese friends would prefer to see Chinese.
This may attract more attention from Chinese friends to this good project.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pavel Lobashov"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 下午3:19
收件人: "ONLYOFFICE/DocumentServer"<DocumentServer@noreply.github.com&gt;; 
抄送: "疾风细雨楼"<1370811553@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ONLYOFFICE/DocumentServer] 这是之前总结的onlyoffice编辑器使用技巧，大家略作参考 (#848)





 
Please, use only English in issues

**Comment by ShockwaveNN** [comment]
Because we are international project, English is a default language for anyone related to IT and information in issues should be available to all, not only people who know chinese.

**Comment by wylc** [comment]
Well, it's changed



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pavel Lobashov"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 下午3:42
收件人: "ONLYOFFICE/DocumentServer"<DocumentServer@noreply.github.com&gt;; 
抄送: "疾风细雨楼"<1370811553@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ONLYOFFICE/DocumentServer] 这是之前总结的onlyoffice编辑器使用技巧，大家略作参考 (#848)





 
Because we are international project, English is a default language for anyone related to IT and information in issues should be available to all, not only people who know chinese.

**Comment by wylc** [comment]
Thanks for such a great open source project




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pavel Lobashov"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 下午3:42
收件人: "ONLYOFFICE/DocumentServer"<DocumentServer@noreply.github.com&gt;; 
抄送: "疾风细雨楼"<1370811553@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ONLYOFFICE/DocumentServer] 这是之前总结的onlyoffice编辑器使用技巧，大家略作参考 (#848)





 
Because we are international project, English is a default language for anyone related to IT and information in issues should be available to all, not only people who know chinese.
