### ISSUE TITLE
Can't upgrade/uninstall

### ISSUE THREAD

**Issue by T0MuX** [ONLYOFFICE/DocumentServer#849]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
The uninstaller is stuck while trying to upgrade.
I run the installer of the latest version (5.5.1.76) with this command
`onlyoffice-documentserver.exe /DS_PORT=8020` then the installer detects the installed version, and suggests to uninstall it. I click yes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I run the installer of the latest version (5.5.1.76) with this command
`onlyoffice-documentserver.exe /DS_PORT=8020` then the installer detects the installed version, and suggests to uninstall it before install the new. I click yes. Then the uninstaller starts and stay stuck at the begining.

**What is the expected behavior?**
The uninstaller go to the end, and then install the latest OODE version normally.

**Did this work in previous versions of DocumentServer?**
I don't know, this is my first OODE installation/upgrade.

**DocumentServer version:**
actual : 5.3.4
latest I wan't to install : 5.5.1.76

**Operating System:**
Windows Server 2012 R2

![image](https://user-images.githubusercontent.com/19415987/79225733-764c6d80-7e5d-11ea-9855-859c167ed06b.png)

**Comment by T0MuX** [comment]
#841 I just mention it because I discovered this one (849) from it.

**Comment by T0MuX** [comment]
Little up :)

**Comment by DenisDeeSign** [comment]
Hello, @T0MuX. 
1. Please close all active sessions (opened documents) to prevent data loss.
2. Clean a content of a documentserver-prepare4shutdown.bat.
3. Run an installer of latest DocumentServer.

**Comment by T0MuX** [comment]
Hi, @DenisDeeSign 
I never opened any documents, so i think it's okay for this first step lol. But, I can't find documentserver-prepare4shutdown.bat ? Where this script is supposed to be ? I searched in my server (windows search function), didn't find it.

**Comment by DenisDeeSign** [comment]
You can find the script in this folder, if you didn't change the installation folder
C:\Program Files\ONLYOFFICE\DocumentServer\bin

**Comment by T0MuX** [comment]
Oh wait, something happened !
I was checking in the path you mentioned, and saw the "bin" folder doesnt exist... I look my taskbar, and see the OnlyOffice icon.... The setup of the latest version was opened ! This means I had let (literally abandoned lol) the uninstaller of the previous version running... and miracle ! It went to the end ! I don't know why (too bad), but nice, my issue is solved.
Thank you anyway for your help !

**Comment by DenisDeeSign** [comment]
Glad to hear.
