### ISSUE TITLE
Missing spaces after opening of ODF document

### ISSUE THREAD

**Issue by erikfdev** [ONLYOFFICE/DocumentServer#850]
This is a bug.
**What is the current behavior?**
After opening the NextCloud "about.odt" in NextCloud OnlyOffice, several space characters are missing. 
"Nextcloud is the open" is shown as "Nextcloudistheopen" after the import.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the about.odt file in  NextCloud OnlyOffice.
[About.zip](https://github.com/ONLYOFFICE/DocumentServer/files/4492944/About.zip)

**What is the expected behavior?**
Spaces are preserved.
**Did this work in previous versions of DocumentServer?**
Don't know.
**DocumentServer version:**
Community Document Server 0.1.5
**Operating System:**
Linux Mint 19.3
**Browser version:**
Firefox 75.0
Chrome 81.0.

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by ShockwaveNN** [comment]
Moving this issue to onlyoffice-nextcloud repo to apply tag.
