### ISSUE TITLE
rabbitmq process running as user 105. Conflicts with host avahi service.

### ISSUE THREAD

**Issue by stalinCCCP415** [ONLYOFFICE/DocumentServer#851]
By default debian and other systems use UID 105 for the avahi service. This service has a limit to only running 3 instances on the host as a security measure. Due to the fact that only office spawns several processes using UID 105 for rabbitmq, it breaks the host avahi service.

In general best practice is to use UIDs >500 to avoid system conflicts.

**Comment by stalinCCCP415** [comment]
Reference:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856311
https://github.com/lathiat/avahi/issues/97

**Comment by ShockwaveNN** [comment]
Hi, we just installed rabbitmq from apt and didn't change any configs for using UID of it as far as i remember.

Any advice - that is the best way of setting UID of rabbitmq?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
