### ISSUE TITLE
Problem with Edge and Cursor 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#852]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
cursor  position not right on edge (other browser has no problem)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When clicking on for example on Title 1 my cursor is in Head
when clicking on List NR. 3 cursor end in list NR. 1 
**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
last version was 5.4.2
**DocumentServer version:**
5.5.1
**Operating System:**
Debian 10 (Server)
Client: Windows
**Browser version:**
Edge 44

any ideas?

**Comment by cpot** [comment]
if i can, just a comment, EDGE legacy is dead, you should upgrade to Chromium-EDGE https://www.microsoft.com/en-en/edge/?ocid=SMC-lifecycle

**Comment by hahaxd35** [comment]
> if i can, just a comment, EDGE legacy is dead, you should upgrade to Chromium-EDGE https://www.microsoft.com/en-en/edge/?ocid=SMC-lifecycle

You can :-) but i'm writen because a customer writing us

**Comment by cpot** [comment]
it is what i say also to our customers using EDGE-Legacy and IE11 also :-), and for our GoFAST platform including Onlyoffice. those 2 crappy browsers must disappear, it will save a lot of money for software vendors like us and improve security and  compatibility. after 25 years Microsoft managed to build a real browser, thanks to opensource

**Comment by Rita-Bubnova** [comment]
Hello.
Sorry for late response.

@hahaxd35 could you check the problem in the current version of the DocumentServer and Microsoft Edge browser?
If the problem is actual, could you attach a video?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
