### ISSUE TITLE
Dropdown list problem with non equal number of lines

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#854]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
If you have a column with a different number of lines than the column where the dropdown is locate, if you select a value it does not fill the cell with that value

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/3287514/79990884-e38d7d80-84b1-11ea-9c21-4308030cbb02.png)
[dropdown issue.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/4516539/dropdown.issue.xlsx)

**What is the expected behavior?**
When selecting a value in the dropdown it fills the cell with that value

**Did this work in previous versions of DocumentServer?**
NO (not implemented)

**DocumentServer version:**
5.5.1

**Operating System:**
Client Win10 / Serveur CentOS7

**Browser version:**
EDGE-Chromium, Firefox 75, ...

**Comment by Rita-Bubnova** [comment]
Hello, @cpot.
Thank you for report. I can confirm - this is a bug, issue 44858 in our internal issue tracker.
Out developers will try to fix that in next major release this summer.

At the moment, as a workaround, you can click on the top of the merged cell, then the cell will be filled.
For example, your file: on the "TEST" sheet, click on cell "B2" (that is, at the top of the merged cell) and select the desired item from the drop-down list.

**Comment by cpot** [comment]
Hi @Rita-Bubnova : ok for the workaround we will go for that, thank you (the summer release is the release where it will be able to create a dropdown list, i did not forgot :-)

**Comment by cpot** [comment]
Issue still exists ! (a large customer of ours noticed it), **why this is has been closed ?** 
cc @ShockwaveNN

**Comment by ShockwaveNN** [comment]
This issue is not closed and it's unresolved

And as usual - if you need higher priority in resolving this issue - it's better to contact sales@onlyoffice.com\support@onlyoffice.com

**Comment by cpot** [comment]
We (or our onlyoffice paying customers) will not be keen to pay for bug fixes

**Comment by ShockwaveNN** [comment]
It's out of my job responsibilities to decide what we fix and that we are not, sorry, you're talking with wrong guy

**Comment by alinasafonova** [comment]
Hello, @cpot

This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/9db0544fc94e93a917159d7aa46bac06c9b4bca6

It will be released as v7.1.0

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
