### ISSUE TITLE
cluster-mode still important?

### ISSUE THREAD

**Issue by madsi1m** [ONLYOFFICE/DocumentServer#855]
Hi, we are running 5.5.0 and am going through many docs on your website and here and i see reference to setting cluster-mode to true. How/Where do I do this when using the documentserver-de? default.json doesn't seem to mention it. Also https://helpcenter.onlyoffice.com/server/integration-edition/linux/linux-installation.aspx#moreOptions doesn't mention it either.

Cheers

**Comment by ShockwaveNN** [comment]
> Hi, we are running 5.5.0 and am going through many docs on your website and here and i see reference to setting cluster-mode to true

Hi, could you point out for such places?

**Comment by madsi1m** [comment]
From further inspection it is mentioned in a word doc from Alexander and scattered on the forums https://dev.onlyoffice.org. Digging through documentserver-de scripts it looks like all cluster-mode does is drop some tables from its local db on startup. Does this mode do anything else?

**Comment by ShockwaveNN** [comment]
@madsi1m this mode is for safely adding new nodes to cluster. without adding or deleting data in DB

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
