### ISSUE TITLE
"Something went wrong during installation" on Windows Server 2012 R2

### ISSUE THREAD

**Issue by T0MuX** [ONLYOFFICE/DocumentServer#856]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Immediately after the installation of all components, and following the wiki, the error "Something went wrong during installation" shows up while accessing OnlyOffice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just follow the wiki https://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx on Windows Server 2012 R2, and you'll probably have the same.

**What is the expected behavior?**
Just install, and work.

**Did this work in previous versions of DocumentServer?**
Don't know, this is my first installation.

**DocumentServer version:**
5.5.1.76

**Operating System:**
Windows 2012 R2 x64

**Browser version:**
Firefox 75 x64

**Additionals details**
OODE was installed with this command, to make it work on 8020 port (the same way the wiki suggest) : 
`onlyoffice-documentserver.exe /DS_PORT=8020`

Erlang v22 on localhost
RabbitMQ v3.5.4 on locahost
Redis v3.2.100 on localhost
PostgreSQL on localhost

To know : I was suspicious about the database. At the start, because I have a database dedicated server, I installed the pg database on it. I was wondering myself maybe the issue comes from this... so I tried exactly the same way as wiki, I mean install the pgsql database on localhost but this didnt change anything.

I have nothing in the browser console.

I have this in nginx.error.log (seems to be related to the issue) : 

> 2020/04/22 11:20:55 [error] 11736#12108: *3 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://[::1]:8000/healthcheck", host: "localhost:8020", referrer: "http://localhost:8020/welcome/"
> 2020/04/22 11:21:55 [error] 11736#12108: *3 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "localhost:8020", referrer: "http://localhost:8020/welcome/"
> 2020/04/22 11:25:23 [error] 11736#12108: *9 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://[::1]:8000/healthcheck", host: "localhost:8020", referrer: "http://localhost:8020/welcome/"
> 2020/04/22 11:26:23 [error] 11736#12108: *9 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "localhost:8020", referrer: "http://localhost:8020/welcome/"
> 2020/04/22 19:46:56 [error] 11736#12108: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "localhost:8020"
> 2020/04/22 19:47:56 [error] 11736#12108: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "localhost:8020"
> 2020/04/22 19:50:37 [error] 11736#12108: *19 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "localhost:8020"
> 

Thank you by advance

**Comment by T0MuX** [comment]
Hi, little up :)

**Comment by T0MuX** [comment]
Tiny news : I activated the log for access in nginx, I have not so much informations on access : 

> 127.0.0.1 - - [27/Apr/2020:07:34:08 +0200] "GET /welcome/ HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
> 127.0.0.1 - - [27/Apr/2020:07:34:08 +0200] "GET /healthcheck HTTP/1.1" 304 0 "http://localhost:8020/welcome/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
> 127.0.0.1 - - [27/Apr/2020:07:34:08 +0200] "GET /welcome/img/icon-cross.png HTTP/1.1" 304 0 "http://localhost:8020/welcome/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"

**Comment by T0MuX** [comment]
Hi, up

**Comment by DenisDeeSign** [comment]
Hello, @T0MuX.
Please attach a logs folder from C:\Program Files\ONLYOFFICE\DocumentServer\Log.

**Comment by T0MuX** [comment]
@DenisDeeSign Yes, here they are. https://catdrop.drycat.fr/r/VEUaGsgL#WFIWGM4u1/Yo8ikRCD4TQzGzjhLhkEB8PKx/0HxnZzA= (file available until 18/05/20)

**Comment by DenisDeeSign** [comment]
Seems RabbitMQ service is stopped.
In your [first issue](https://github.com/ONLYOFFICE/DocumentServer/issues/841#issuecomment-614476654) I recommend you upgrade it for compatibility with Erlang, but you specified RabbitMQ version 3.5.4 again.

**Comment by T0MuX** [comment]
@DenisDeeSign no, I'm in 3.8.3 since 17/04/20

![Screen Capture_select-area_20200512110938](https://user-images.githubusercontent.com/19415987/81665656-446cfd80-9441-11ea-9f73-c523ea7484e8.png)

**Comment by DenisDeeSign** [comment]
What happened after you start it?

**Comment by T0MuX** [comment]
If you mean after I start the RabbitMQ Server, just nothing. The service appears online, simply running.

**Comment by DenisDeeSign** [comment]
Now please restart all services of DocumentServer and check http://localhost:8020/healthcheck

**Comment by T0MuX** [comment]
Okay I restarted all these services : 
DsConverterSvc
DsDocServiceSvc
DsProxySvc
DsSpellcheckerSvc

And http://localhost:8020/healthcheck shows "false" (and nothing else)

**Comment by DenisDeeSign** [comment]
I found out more information in your logs. A database server refused a connection from DocumentServer. Make shure servers are available for each other. The easyest way is installing PGAdmin4 on DocumentServer host and connecting to Postgres host.

**Comment by T0MuX** [comment]
Hi, I checked the database, and yes there was an access issue, the server hosting OODE couldnt access to the database. So, I review the configuration, and now it is all okay. I can connect, with pgadmin4, to the database from the hosting server. But, the issue still occurring

**Comment by DenisDeeSign** [comment]
1. Please make shure port 5432 is opened on both side by this instruction (note **).
https://helpcenter.onlyoffice.com/server/docker/document/open-ports.aspx
2. Make shure Reddis and RabbirMQ services are working.
3. Restart all services of DocumentServer after data-base issue was fixed.
4. Create new document.
5. If issue would be exist, please send new logs.

**Comment by T0MuX** [comment]
@DenisDeeSign Hi, I was going to open all those ports, and I saw this in the firewall : there is one entry per ONLYOFFICE DocumentServer service -> DocService Service, Proxy Service and Spellchecker Service. Each rules grant access to the process itself, not the port. I'm going to try despite this. Maybe the process granting is not enough ?

**Comment by T0MuX** [comment]
So, I think the "process granting" is enough when the processes are launched on the same machine. Just to remind : OnlyOffice is entirely installed on one server, except the Postgresql database which is installed on another one. So, I just opened the database port (5432), IN and OUT, on the server where OO is installed. I restarted all the related services, and now when I access to https://localhost:8020, it redirects to https://localhost:8020/welcome (seems normal), and shows "Please wait...", so it seems better, I wait a while and see what happens.

**Comment by DenisDeeSign** [comment]
@T0MuX, yes, logs just confims the issue with Rabbit. 
I should have asked it before: is your server administrator account contain non-ASCII characters? If it doesn't I need to view RabbitMQ logs from C:\Users\Administrator\AppData\Roaming\RabbitMQ\log

**Comment by T0MuX** [comment]
@DenisDeeSign By "account", you mean "username" ? If yes, no, my account's username is "admin2". And the display name is "Administrateur (TH & CB)". I give you the mentioned log however.
[log.zip](https://github.com/ONLYOFFICE/DocumentServer/files/4632912/log.zip)

**Comment by T0MuX** [comment]
Hi, did you found something more in the logs ?

**Comment by DenisDeeSign** [comment]
Hi, @T0MuX. There is a recurring errors in rabbitmq logs what causes service fault.
`2020-04-17 12:23:00.015 [error] <0.956.0> Error on AMQP connection <0.956.0> (127.0.0.1:56778 -> 127.0.0.1:5672, vhost: '/', user: 'guest', state: running), channel 0:
 operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"`
Any information about fixing that is very limited, so our developers team has no clue.
However, we can try reinstall the DocumentServer with log running this (path mat be different in your case).
[onlyoffice-documentserver.exe /DS_PORT=8020 /LOG="C:\setupLog.txt"](url)
You are able to send new log to support@onlyoffice.com with mark "github/DocumentServer #856" for saving personal data.

**Comment by T0MuX** [comment]
Hi, sorry for the late, I join the log here (Should I send it by mail anyway ?). Good luck, I checked the log, it is very long :open_mouth: 
[setupLog.txt](https://github.com/ONLYOFFICE/DocumentServer/files/4829830/setupLog.txt)

**Comment by T0MuX** [comment]
Hi, I don't know if we have to keep this issue opened, but I finally chose to install PostgreSQL on localhost. Since this, no problem. Installation OK, running OK.

**Comment by DenisDeeSign** [comment]
We made several attempts to reproduce your issue, but everithing was fine for us. Glad to hear your DocumentServer is working now.
I'll close the issue.
