### ISSUE TITLE
when i run make at sdkjs, error: Unsupported platform for google-closure-compiler-osx@20190301.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"linux","arch":"x64"})

### ISSUE THREAD

**Issue by songlin51** [ONLYOFFICE/DocumentServer#858]
When I run the make ats SDKJS, error: Unsupported platform for google-closure-compiler-osx@20190301.0.0: wanted {" OS ":" Darwin ", "arch" : "x64 and x86"} (current: {" OS ":" Linux ", "arch" : "x64"})

Are there configuration files that support Linux?

System: ubuntu: 14.0.4

Thank you very much

**Comment by ShockwaveNN** [comment]
Yeah, I got same message as warning, not an error

Which version of nodejs and npm are you using?
Did you change some settings and\or files?

**Comment by songlin51** [comment]
node : v6.9.0
npm : 3.10.8



The previous version of node I used was 10.14.0 but an error prompted NPM WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.14.0"," NPM ":"6.14.4"})
So I downgraded the node version to 6.9.0

Thank you for your reply

**Comment by ShockwaveNN** [comment]
I've got 
```
node -v # v12.16.2
npm -v # 6.14.4
```
and make process is fine.
But I've used Ubuntu 18.04 as base, but I dont think it's the reason

**Comment by songlin51** [comment]
I upgraded node & npm
node - v # v12.16.2
npm - v # 6.14.4

But here's a hint:
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.




I don't know how to do 😥

**Comment by ShockwaveNN** [comment]
To be sure - which version of `sdkjs` you checkout? 
`git rev-parse HEAD
`

**Comment by songlin51** [comment]
Version is : b852e6751642be708246cfa80d6950976245cf6d

**Comment by ShockwaveNN** [comment]
Try to clean your modules, I recheked on Ubuntu 14.04 with same version as your and on same sdkjs revision and I got installed another version of `got` library 

```
npm list -g | grep got
  | |   +-- got@6.7.1
```

Or provide some dockerfile with which I will be able to reproduce it

**Comment by songlin51** [comment]
Unfortunately, I still cannot compile the past.
NPM WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":"> "=0.10.0 <7"} (current: {"node":"10.14.0"," NPM ":"6.14.4"})
NPM WARN notsup Not compatible with your version of node/ NPM: got@5.7.1

NPM ERR! Code ELIFECYCLE
NPM ERR! Errno 1
NPM ERR! phantomjs-prebuilt@2.1.16 install: ` node the js `
NPM ERR! The Exit status 1
NPM ERR!
NPM ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
NPM ERR! This is probably not a problem with NPM. There is likely additional logging output above.


I can't provide dockerfile for the moment. Sorry, I don't know much about docker.
All I can learn is this

Ubuntu: 14.0.4
Node - v # 12.16.2
NPM - v # 6.14.4

Thank you very much for your reply. I hope to hear your good news

**Comment by ShockwaveNN** [comment]
I think there is something wrong with your nodejs setup. It install some old modules for some reason

Try to remove `build/node_modules/`
Maybe this helps

**Comment by songlin51** [comment]
I've tried to delete node_modules but still get the same error

**Comment by songlin51** [comment]
By the way, I modified the Makefile

- WEBAPPS_DIR: = web apps
+ WEBAPPS_DIR: = web apps - pro


Because the code base directory is web-apps-pro

**Comment by ShockwaveNN** [comment]
> Because the code base directory is web-apps-pro

`web-apps-pro` was renamed to `web-apps` a long time ago

I think you should update all your dependencies to latest version and see if problem actual

I even don't understand why you're tryint to use `b852e6751642be708246cfa80d6950976245cf6d`, this is version is half-year old

I tryed to reproduce this in clean docker enviroment with this Dockerfile:
```
FROM ubuntu:14.04

RUN apt-get -y update && \
    apt-get  -y install git make curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
RUN apt-get -y install nodejs
RUN git clone https://github.com/ONLYOFFICE/sdkjs.git
WORKDIR /sdkjs
RUN git checkout b852e6751642be708246cfa80d6950976245cf6d
RUN make
```

It installed node modules fine, but failed in next step, since I'm not cloned web-apps

So I'm still thinking something wrong with your setup.
And in any case - this error is with npm installing modules, it's not problem in DocumentServer source code.

If you'll able to setup some environment for me to see this problem to reproduce - I'm willing to investigate it.

**Comment by songlin51** [comment]
Thank you for your patient reply.
Before I clone version because the execution of the git clone https://github.com/ONLYOFFICE/DocumentServer.git
After code/Common / 3 dparty directory without "fetch. Sh" because I'm in accordance with the https://autoize.com/building-onlyoffice-document-server-from-source/ this tutorial for installation, in carrying out the core/Common/CD 3 dparty &&. / make. When sh does not rely on installation,

So I execute
Git clone - branch ONLYOFFICE DocumentServer - 5.4.2 -- recursive https://github.com/ONLYOFFICE/DocumentServer.git
This version. I'm sorry that you can't reproduce the problem without dockerfile.

**Comment by ShockwaveNN** [comment]
> https://autoize.com/building-onlyoffice-document-server-from-source/
In any case - this instruction is outdated, you should use https://github.com/ONLYOFFICE/build_tools
to compile latest public release

**Comment by songlin51** [comment]
Thanks for your reply, and I'll try build_tools again. Thank you very much
