### ISSUE TITLE
download fonts is slow

### ISSUE THREAD

**Issue by zjs-apple** [ONLYOFFICE/DocumentServer#864]
I set up a document service running on docker on my computer. 
Reference:https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx
Edit files on another computer on the LAN.
But download fonts is slow

**Comment by ShockwaveNN** [comment]
Could you attach screenshot of Network tab of Chrome Debug tool?

But in general - first time loading font, especially CJK-fonts is not very fast, since font files are big.
But font files are browser cached and loading of font should be happened once on browser side

**Comment by zjs-apple** [comment]
What I can't figure out is why the transmission is very slow in the LAN.
There are no restrictions on this LAN

**Comment by ShockwaveNN** [comment]
> Could you attach screenshot of Network tab of Chrome Debug tool?

**Comment by cpot** [comment]
duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/843

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
