### ISSUE TITLE
graphical issues

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#865]
Are there some graphical issues known? ( reported a IE problem days ago)

we got some feedbac kand user tell they have problem with graphics.

Sometime we press "d" and got " ", after closing and opening the problem is gone. But now all "i" are missing (only graphical)
 
Do you have any ideas? 

Brwoser:
Chrome

OS:
Windows 10

**Comment by Rita-Bubnova** [comment]
Hello, @hahaxd35.
Is the problem reproducing only on one file?
What version DocumentServer are you using?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
