### ISSUE TITLE
Can't change listening port, can't put behind proxy

### ISSUE THREAD

**Issue by Luticus** [ONLYOFFICE/DocumentServer#87]
**Do you want to request a *feature* or report a *bug*?**  Both maybe?

**What is the current behavior?**  
I'm trying to use this with the nextcloud app.  The problem is both nextcloud and onlyoffice listen at 443.  If I try to redirect the port via iptables, change the listening port in nginx, or even use proxypass in apache where nextcloud is (ideal), it fails.  Changing the listening port in nginx results in an unknown error when I try to view documents, proxypass results in the nextcloud plug in claiming it's unconfigured. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**   
Set this up with 2 servers, nextcloud on one and office on the other.  Nextcloud and office will both listen on 443, which is fine for internal connections but for external connection that setup doesn't work well if you only have one static IP address.  Try setting up proxypass, switching the listening port, or setting up port redirection via iptables, it will fail.

**What is the expected behavior?**
I should be able to use the nextcloud plugin over the WAN or LAN.  Ideally via proxypass so that I don't have to expose another port to the WAN. 

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

Newest document server,
Debian 8 is the OS
All browsers
This is the first version of documentserver I have tried.

Newest Nextcloud and Nextcloud plugin
Nextcloud is hosted on apache2 in Debian 8

**Comment by JohnPerkin** [comment]
Hello!
Please specify method of DS installation: docker or .deb-package

**Comment by Luticus** [comment]
I've actually attempted with both.  I have 2 vms, nextcloud on one and onlyoffice documentserver on the other, as well as a test docker image on the nextcloud box.  I'd prefer to use the seperate server if possible to free up resources on the nextcloud box, but if the container is the only way to make it work then that's fine too.  I've tried redirecting ports there too.  9980:80 in the docker line and it doesn't seem to work either.

**Comment by ShockwaveNN** [comment]
Custom port currently not working.
Will be working in release 4.3
See https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/15

**Comment by Luticus** [comment]
Do you have documentation or some method of placing the documentserver behind an apache proxypass?  I think that it may be failing due to the rewrites in nginx on the documentserver but not sure if there's a workaround.  ProxyPass would be ideal because no other ports would be needed.  So in the event the user is coming from a networked that is locked down and blocks many ports this would still work because everything would still just be 443 from their perspective.

If that's not the case then I suppose I look forward to your next release.  

Thanks, for looking into this.

**Comment by ShockwaveNN** [comment]
@Luticus no, we do not have documentation on it.
There is a possible way to do this, but we haven't enoth time to try it ourselfs and perform QA, so we decided to concentrate on next release, it which there wil be no need to workaround, instead of trying to get this workaround to work in current release.
