### ISSUE TITLE
how to close mobile virtual keyboard in mode=view

### ISSUE THREAD

**Issue by ChefWu551** [ONLYOFFICE/DocumentServer#872]
Dear developers,
       when I view in my mobile phone, the vitual keyboard is to big,  it make me hard to operate on mobile, can anyway to close it default?
       If possible, I want to ask how to close scrollbar, it also make me difficult to operate, it may easy  operate by touch screen instead of  touch scrollbar

**Comment by ChefWu551** [comment]
can i make when mode=view then current page will show like a picture, or drag current doc not though scrollbar

**Comment by nav-fess** [comment]
Hi, ChefWu551. 
These answers apply only to the mobile web.

> when I view in my mobile phone, the vitual keyboard is to big, it make me hard to operate on mobile, can anyway to close it default?

 - Smartphone keyboard can be closed via the key back.

>If possible, I want to ask how to close scrollbar, it also make me difficult to operate, it may easy operate by touch screen instead of touch scrollbar

-So originally designed. Scroll bar only shown while swiping down / up .

> can i make when mode=view then current page will show like a picture, or drag current doc not though scrollbar but use drag gesture or Remove the current document cursor

- In the context menu of the file, select the item Preview
![Preview](https://user-images.githubusercontent.com/22593004/81679218-c0277400-945a-11ea-82a7-c59a1459c603.jpg)

**Comment by ChefWu551** [comment]
ok, I see, I'll try. Thank u for answer me. Best wish.

**Comment by ChefWu551** [comment]
> * Smartphone keyboard can be closed via the key back.

Dear nav-fess:
     what did you mean "via the key back"? Can I shut it down by  this? 
```
var docEditor = new DocsAPI.DocEditor("placeholder", {
    "documentType": "text",
    "height": "100%",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.t-IDcSemACt8x4iTMCda8Yhe3iZaWbvV5XKSTbuAn0M",
    "type": "desktop",
    "width": "100%",
    ...
});
```
or anyway can i do ?

**Comment by nav-fess** [comment]
via the key back
![github2](https://user-images.githubusercontent.com/22593004/134507031-fa29b976-1f91-4844-9d18-2cc5a47bb1dd.jpg)
![github1](https://user-images.githubusercontent.com/22593004/134507038-b9f50287-bd77-404c-945f-64ec3db7a596.jpg)
.

**Comment by nav-fess** [comment]
Mobile keyboard can not be disabled in the configuration settings.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
