### ISSUE TITLE
Please add socks5 proxy function for users from China

### ISSUE THREAD

**Issue by ydsjqt** [ONLYOFFICE/DocumentServer#875]
Cloud function IP is blocked and cannot be used, please add socks5 proxy function Thank you

**Comment by ShockwaveNN** [comment]
Could you describe that you want in more details? I'm not really sure that socks5 support should be implemented on our end, you could setup some kind of proxy by yourself.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
