### ISSUE TITLE
As the file size increases, the loading time becomes longer and longer in OnlyOffice

### ISSUE THREAD

**Issue by widechina** [ONLYOFFICE/DocumentServer#876]
**Do you want to request a *feature* or report a *bug*?**
Request a feature
**What is the current behavior?**
It takes 13 seconds when loading a large size file of 6.5m in Onlyoffice,but in WPS online editor merely 4 seconds.As the file size increases, the loading time becomes longer and longer in OnlyOffice,but cost about 4 seconds in WPS online editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug.

**What is the expected behavior?**
It cost less 10 seconds when loading a large size file of 6.5m by lazy loading techonology.

**Did this work in previous versions of DocumentServer?**
Did not.

**DocumentServer version:**
5.4.2

**Operating System:**
Windows server 2012
**Browser version:**
Chrome  81.0.4044.138(64 bit)

**Comment by ShockwaveNN** [comment]
Could you attach example file in which you have long loads?

**Comment by widechina** [comment]
Thanks for you reply,the url of example file  is below:
https://wpsfile.ksyun.com/9569d541cef1d06ba78768ddd33a662e46f6bc06?response-content-disposition=attachment%3Bfilename%2A%3Dutf-8%27%27test.xlsx&KSSAccessKeyId=AKLTzXTtaXFBQB-5i517RTCRkQ&Expires=1589955206&Signature=uMVUsLknUBF4TvqYCv9icNZ9wb0%3D

**Comment by ShockwaveNN** [comment]
![image](https://user-images.githubusercontent.com/668524/82416065-20816b80-9a82-11ea-99a7-866485948908.png)
Just upload it to github if it have no private information

**Comment by widechina** [comment]
Updated download url as below:
https://pan.baidu.com/s/1qDVqTjXVY9Zbdnf_wF_liw
password:3bvs

**Comment by ShockwaveNN** [comment]
Cannot download it since cannot find english interface button on those side and google translated didn't tranlaste it either.

One again, please upload it on github

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by RTechSn** [comment]
So just swipe it under the carpet.
