### ISSUE TITLE
API example code for Python: File cannot be accessed right now

### ISSUE THREAD

**Issue by kevinkhao** [ONLYOFFICE/DocumentServer#877]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Creating a new document is impossible, an error screen pops up
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. On ubuntu 20.04, run snap install onlyoffice-ds
2. Observe localhost/healthcheck works. DocumentServer is running on locahost:80 
3. edit config.py and edit values like so:
DOC_SERV_CONVERTER_URL = 'http://localhost:80/ConvertService.ashx'
DOC_SERV_API_URL = 'http://localhost:80/web-apps/apps/api/documents/api.js'
DOC_SERV_PRELOADER_URL = 'http://localhost:80/web-apps/apps/api/documents/cache-scripts.html'
EXAMPLE_DOMAIN = 'http://localhost'
4. Run manage.py runserver 0.0.0.0:8002 . 
5. Observe interface works correctly
6. Click on "Create document"
7. Observe the error dialogs in the screenshot attached

Tried with a docker image setup to the same result.
![Screenshot from 2020-05-20 17-27-40](https://user-images.githubusercontent.com/19902174/82465222-55f87a00-9abf-11ea-8703-51eeb922d49e.png)
**What is the expected behavior?**
We should be able to edit the document according to the instructions

**Operating System:**
Ubuntu 20.04

**Comment by kevinkhao** [comment]
Additional information: screenshot of console output

![Screenshot from 2020-05-20 18-25-09](https://user-images.githubusercontent.com/19902174/82471710-5ac12c00-9ac7-11ea-945c-f14253a00d03.png)

**Comment by ShockwaveNN** [comment]
Could you try same with Docker version of DocumentServer, snap is outdated and may have some troubles

**Comment by kevinkhao** [comment]
Okay, here are the steps I used:
1. sudo docker run -i -t -d -p 80:80 --restart=always onlyoffice/documentserver
note: healthcheck works on localhost/healthcheck
2. edit python config plugin with the following values:
DOC_SERV_CONVERTER_URL = 'http://localhost:80/ConvertService.ashx'
DOC_SERV_API_URL = 'http://localhost:80/web-apps/apps/api/documents/api.js'
DOC_SERV_PRELOADER_URL = 'http://localhost:80/web-apps/apps/api/documents/cache-scripts.html'
EXAMPLE_DOMAIN = 'http://localhost:8002'
3. Open browser and navigate to localhost:8002
4. Click on "Create Document
5. Observe the following 
![Screenshot from 2020-05-20 19-19-54](https://user-images.githubusercontent.com/19902174/82477024-20f42380-9acf-11ea-97c3-9196cff4b945.png)

**Comment by ShockwaveNN** [comment]
@flaminestone Please take a look at this, am I correct that python test example is written by you?

**Comment by kevinkhao** [comment]
Here are the logs following the steps described in previous post. 

* Starting PostgreSQL 10 database server                                [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                    [ OK ] 
Starting redis-server: redis-server.
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron                              [ OK ] 
 * Starting nginx nginx                                                  [ OK ] 
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx                                   [ OK ] 
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-05-20T17:43:24.579] [WARN] nodeJS - update cluster with 1 workers
[2020-05-20T17:43:41.232] [ERROR] nodeJS - error downloadFile:url=http://localhost:8002/static/127.0.0.1/new (42).docx;attempt=1;code:ECONNREFUSED;connect:null;(id=6268538167071579624)
Error: connect ECONNREFUSED 127.0.0.1:8002
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[2020-05-20T17:43:42.236] [ERROR] nodeJS - error downloadFile:url=http://localhost:8002/static/127.0.0.1/new (42).docx;attempt=2;code:ECONNREFUSED;connect:null;(id=6268538167071579624)
Error: connect ECONNREFUSED 127.0.0.1:8002
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[2020-05-20T17:43:43.239] [ERROR] nodeJS - error downloadFile:url=http://localhost:8002/static/127.0.0.1/new (42).docx;attempt=3;code:ECONNREFUSED;connect:null;(id=6268538167071579624)
Error: connect ECONNREFUSED 127.0.0.1:8002
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
20 May 17:43:09 - [1015] reading config file: ./config/config.js
20 May 17:43:09 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
[2020-05-20T17:43:09.651] [WARN] nodeJS - start cluster with 1 workers
[2020-05-20T17:43:09.657] [WARN] nodeJS - worker 1082 started.
[2020-05-20T17:43:09.937] [WARN] nodeJS - Express server starting...
[2020-05-20T17:43:09.974] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode

**Comment by flaminestone** [comment]
Hello @kevinkhao. Are you using a test example from github? Or are you using an example from the archive from api.onlyoffice.com?

**Comment by kevinkhao** [comment]
Hi @flaminestone I used the one visible on this page : 
https://api.onlyoffice.com/editors/demopreview
That is, the one for python is on this link : 
https://api.onlyoffice.com/app_data/editor/Python%20Example.zip
I did not find an example for Python on Github.

**Comment by flaminestone** [comment]
Python example is placed on develop branch:

https://github.com/ONLYOFFICE/document-server-integration/tree/develop/web/documentserver-example/python

I think, it is bug in old version of example, I can't reproduce problem on version from github

**Comment by kevinkhao** [comment]
I have used the example on github, with the same steps.

Here is the screenshot when trying to create a document.

![Screenshot from 2020-05-21 12-02-24](https://user-images.githubusercontent.com/19902174/82548226-475fa080-9b5b-11ea-8fbd-fad2d7ef4bbf.png)

Here is the docker logs.

 * Starting PostgreSQL 10 database server                                [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                    [ OK ] 
Starting redis-server: redis-server.
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron                              [ OK ] 
 * Starting nginx nginx                                                  [ OK ] 
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx                                   [ OK ] 
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-05-21T10:00:44.508] [WARN] nodeJS - update cluster with 1 workers
[2020-05-21T10:00:44.532] [WARN] nodeJS - worker 871 started.
[2020-05-21T10:00:44.534] [WARN] nodeJS - update cluster with 1 workers
[2020-05-21T10:01:13.526] [WARN] nodeJS - update cluster with 1 workers
[2020-05-21T10:01:13.541] [WARN] nodeJS - worker 938 started.
[2020-05-21T10:01:13.542] [WARN] nodeJS - update cluster with 1 workers

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2020-05-21T10:00:45.232] [WARN] nodeJS - Express server starting...
[2020-05-21T10:00:45.238] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-05-21T10:00:45.578] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-05-21T10:01:09.289] [ERROR] nodeJS - dnsLookup error: hostname = locahost
Error: getaddrinfo ENOTFOUND locahost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[2020-05-21T10:01:09.290] [WARN] nodeJS - checkIpFilter error: docId = 8155380883748317516;url = http://locahost:8000track?filename=new (3).docx&userAddress=127.0.0.1
[2020-05-21T10:01:11.674] [WARN] nodeJS - Express server starting...
[2020-05-21T10:01:11.678] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-05-21T10:01:11.846] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
21 May 10:00:43 - [833] reading config file: ./config/config.js
21 May 10:00:43 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
[2020-05-21T10:00:43.891] [WARN] nodeJS - start cluster with 1 workers
[2020-05-21T10:00:43.911] [WARN] nodeJS - worker 861 started.
[2020-05-21T10:00:44.859] [WARN] nodeJS - Express server starting...
[2020-05-21T10:00:44.936] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2020-05-21T10:02:22.501] [ERROR] nodeJS - dnsLookup error: hostname = locahost
Error: getaddrinfo ENOTFOUND locahost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[2020-05-21T10:02:22.501] [WARN] nodeJS - checkIpFilter error: docId = -4160884591650212797;url = http://locahost:8000track?filename=new (4).docx&userAddress=127.0.0.1
kevkh@kevkh-Inspiron-13-5368:~/untitled/python$ 

Here is result of cat /etc/hosts :
kevkh@kevkh-Inspiron-13-5368:~/untitled/python$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	kevkh-Inspiron-13-5368

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

This is an ubuntu 18.04 install without other modifications.

**Comment by kevinkhao** [comment]
And here is a cat of config.py

kevkh@kevkh-Inspiron-13-5368:~/untitled/python$ cat config.py 
import os

FILE_SIZE_MAX = 5242880
STORAGE_PATH = 'app_data'

DOC_SERV_VIEWED = [".pdf", ".djvu", ".xps"]
DOC_SERV_EDITED = [".docx", ".xlsx", ".csv", ".pptx", ".txt"]
DOC_SERV_CONVERT = [
    ".docm", ".doc", ".dotx", ".dotm", ".dot", ".odt",
    ".fodt", ".ott", ".xlsm", ".xls", ".xltx", ".xltm",
    ".xlt", ".ods", ".fods", ".ots", ".pptm", ".ppt",
    ".ppsx", ".ppsm", ".pps", ".potx", ".potm", ".pot",
    ".odp", ".fodp", ".otp", ".rtf", ".mht", ".html", ".htm", ".epub"
]

DOC_SERV_TIMEOUT = 120000

DOC_SERV_CONVERTER_URL = 'http://localhost/ConvertService.ashx'
DOC_SERV_API_URL = 'http://localhost/web-apps/apps/api/documents/api.js'
DOC_SERV_PRELOADER_URL = 'http://localhost/web-apps/apps/api/documents/cache-scripts.html'

EXAMPLE_DOMAIN = 'http://locahost:8000'

DOC_SERV_JWT_SECRET = ''


EXT_SPREADSHEET = [
    ".xls", ".xlsx", ".xlsm",
    ".xlt", ".xltx", ".xltm",
    ".ods", ".fods", ".ots", ".csv"
]

EXT_PRESENTATION = [
    ".pps", ".ppsx", ".ppsm",
    ".ppt", ".pptx", ".pptm",
    ".pot", ".potx", ".potm",
    ".odp", ".fodp", ".otp"
]

EXT_DOCUMENT = [
    ".doc", ".docx", ".docm",
    ".dot", ".dotx", ".dotm",
    ".odt", ".fodt", ".ott", ".rtf", ".txt",
    ".html", ".htm", ".mht",
    ".pdf", ".djvu", ".fb2", ".epub", ".xps"
]


if os.environ.get("EXAMPLE_DOMAIN"):
    EXAMPLE_DOMAIN = os.environ.get("EXAMPLE_DOMAIN")
if os.environ.get("DOC_SERV"):
    base = os.environ.get("DOC_SERV").rstrip('/')
    DOC_SERV_CONVERTER_URL = base + '/ConvertService.ashx'
    DOC_SERV_API_URL = base + '/web-apps/apps/api/documents/api.js'
    DOC_SERV_PRELOADER_URL = base + '/web-apps/apps/api/documents/cache-scripts.html'

**Comment by flaminestone** [comment]
It is not good idea to use `localhost` when you using docker, because localhost in docker, and localhost on host is a different localhosts. Try to use youre ip instead this.

I see, you use `127.0.0.1` like host address when start. It the same.
You need to use `0.0.0.0:8000` instead of `127.0.0.1:8000`, or ip address

**Comment by kevinkhao** [comment]
Thanks @flaminestone, this your hint helped solve this.

**Comment by yokesh22** [comment]
I'm using below config.py

`
import os

VERSION = '1.5.1'

FILE_SIZE_MAX = 5242880
STORAGE_PATH = 'assets/new'

DOC_SERV_FILLFORMS = [".oform", ".docx"]
DOC_SERV_VIEWED = [".pdf", ".djvu", ".xps", ".oxps"]  # file extensions that can be viewed
DOC_SERV_EDITED = [".docx", ".xlsx", ".csv", ".pptx", ".txt", ".docxf"]  # file extensions that can be edited
DOC_SERV_CONVERT = [                                           # file extensions that can be converted
    ".docm", ".doc", ".dotx", ".dotm", ".dot", ".odt",
    ".fodt", ".ott", ".xlsm", ".xlsb", ".xls", ".xltx", ".xltm",
    ".xlt", ".ods", ".fods", ".ots", ".pptm", ".ppt",
    ".ppsx", ".ppsm", ".pps", ".potx", ".potm", ".pot",
    ".odp", ".fodp", ".otp", ".rtf", ".mht", ".html", ".htm", ".xml", ".epub", ".fb2"
]

DOC_SERV_TIMEOUT = 120000

DOC_SERV_SITE_URL = 'http://192.168.1.119:8050/'

DOC_SERV_CONVERTER_URL = 'http://192.168.1.119:8050/ConvertService.ashx'
DOC_SERV_API_URL = 'web-apps/apps/api/documents/api.js'
DOC_SERV_PRELOADER_URL = 'web-apps/apps/api/documents/cache-scripts.html'
DOC_SERV_COMMAND_URL='coauthoring/CommandService.ashx'

EXAMPLE_DOMAIN = "http://192.168.1.119:8050/"

secret_key = os.urandom(32).hex()

DOC_SERV_JWT_SECRET = "my_jwt_secret"  # the secret key for generating token
DOC_SERV_JWT_HEADER = 'Authorization'

DOC_SERV_VERIFY_PEER = False

EXT_SPREADSHEET = [
    ".xls", ".xlsx", ".xlsm", ".xlsb",
    ".xlt", ".xltx", ".xltm",
    ".ods", ".fods", ".ots", ".csv"
]

EXT_PRESENTATION = [
    ".pps", ".ppsx", ".ppsm",
    ".ppt", ".pptx", ".pptm",
    ".pot", ".potx", ".potm",
    ".odp", ".fodp", ".otp"
]

EXT_DOCUMENT = [
    ".doc", ".docx", ".docm",
    ".dot", ".dotx", ".dotm",
    ".odt", ".fodt", ".ott", ".rtf", ".txt",
    ".html", ".htm", ".mht", ".xml",
    ".pdf", ".djvu", ".fb2", ".epub", ".xps", ".oxps", ".oform"
]

LANGUAGES = {
    'en': 'English',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'zh' : 'Chinese (People\'s Republic of China)',
    'zh-TW' : 'Chinese (Traditional, Taiwan)',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'fi': 'Finnish',
    'fr': 'French',
    'gl': 'Galego',
    'de': 'German',
    'el': 'Greek',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'it': 'Italian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'lv': 'Latvian',
    'lo': 'Lao',
    'ms': 'Malay (Malaysia)',
    'nb': 'Norwegian',
    'pl': 'Polish',
    'pt' : 'Portuguese (Brazil)',
    'pt-PT' : 'Portuguese (Portugal)',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'es': 'Spanish',
    'sv': 'Swedish',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'vi': 'Vietnamese',
    'aa-AA': 'Test Language'
}

if os.environ.get("EXAMPLE_DOMAIN"):  # generates a link for example domain
    EXAMPLE_DOMAIN = os.environ.get("EXAMPLE_DOMAIN")
if os.environ.get("DOC_SERV"):  # generates links for document server
    DOC_SERV_SITE_URL = os.environ.get("DOC_SERV")

`
but it is not being fixed why ?

out.log

 [ERROR] [localhost] [-694738620544879904] [uid-1] nodeJS - postData error: url = http://192.168.1.119:8050//track?filename=new.docx&userAddress=127.0.0.1;data = {"key":"-694738620544879904","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiItNjk0NzM4NjIwNTQ0ODc5OTA0Iiwic3RhdHVzIjoxLCJ1c2VycyI6WyJ1aWQtMSJdLCJhY3Rpb25zIjpbeyJ0eXBlIjoxLCJ1c2VyaWQiOiJ1aWQtMSJ9XSwiaWF0IjoxNjkyODEwNTQ5LCJleHAiOjE2OTI4MTA4NDl9.-M7R7wxkChAQzvIwTuGN1c6Ds0wE4O6Mau-ym9wT6aw"} Error: Error response: statusCode:404; headers:{"server":"nginx","date":"Wed, 23 Aug 2023 17:09:09 GMT","content-type":"text/html; charset=utf-8","transfer-encoding":"chunked","connection":"keep-alive","vary":"Accept-Encoding","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff","content-encoding":"gzip"}; body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST //track</pre>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at Gunzip.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at Gunzip.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by trofim24** [comment]
@yokesh22
We have an example for python server [here](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/python). Did you try it?
If you have problems with this example, create [new issue in that repo](https://github.com/ONLYOFFICE/document-server-integration/issues)
