### ISSUE TITLE
onDocumentStateChange is not triggered in fast co-edit mode

### ISSUE THREAD

**Issue by nettree** [ONLYOFFICE/DocumentServer#88]
**Do you want to request a *feature* or report a *bug*?**
I am not sure this is a potential bug or this is an designed behaviour

**What is the current behavior?**
I bind a callback function to `onDocumentStateChange` event of OnlyOffice editor, and it works well when only one user is editing the specific document, but when another user starts to edit the same document, this event will never be triggered any more no matter which user makes change to that document, and I found if I change co-edit mode to strict, then this event can be triggered again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Bind any callback function to `onDocumentStateChange` event and pass it to constructor of OnlyOffice online editor as part of config object, open a document in editor, check the callback function is invoked when there is any change made and saved. 
Leave the editor open, open another editor window by using a different user, you can see the callback function will not be invoked any more in both of editor window when changes are made

**What is the expected behavior?**
The expected behaviour is no matter how many users are editing the specific document, this event will still be triggered so that the callback function bind to `onDocumentStateChange` event can be invoked correctly for each user rather than having to switch co-edit mode to strict from fast.

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
I am developing a new feature based on the OnlyOffice, so I am not sure whether this works in previous versions or not. We're using version 4.2.10.

I can reproduce this issue in both Chrome 57.0.2987.98 and Firefox 47.0, my OS is Ubuntu 15.10

I think this issue should belong to the frontend team, but I couldn't find where to raise a new issue there, so please help me transfer this issue to that project if needed. Thank you.

**Comment by JohnPerkin** [comment]
Hello!
We really appreciate your reasonable remarks on ONLYOFFICE working.
This behaviour of Document Server is connected with necessary measures which were taken for certain reasons. It is actual only for the current version 4.2. In 4.3 release editors will behave in accordance with the documentation. You may monitor its releasing in our [Changelog](https://github.com/ONLYOFFICE/DocumentServer/releases)
Thank you for the interest in our product

**Comment by nettree** [comment]
Thank you John! It's said that this issue will be fixed in 4.3, then I will keep an eye on it.

**Comment by nettree** [comment]
Hi John, can I expect 4.3 release to be available within next three weeks? If possible, can you please advise the specific date? Thank you.
