### ISSUE TITLE
Comments not highlighted in the document and navigation via the left sidebar doesn't work.

### ISSUE THREAD

**Issue by thorsten-panknin** [ONLYOFFICE/DocumentServer#880]
**Do you want to request a *feature* or report a *bug*?**
I'd like to report a bug.

**What is the current behavior?**
When I add a comment to some text, the commented text is not colour-highlighted. Furthermore, clicking on the comment's entry in the left sidebar does not jump to the respective comment in the document. (I realise this are probably two issues, but ohwell)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Select some text

2. Create a comment by right-clicking and clicking the entry to create a comment

3. Result: A comment is created in the left sidebar, but the commnted on text is not highlighted. Clicking on the comment entry does not jump to the respective comment

**What is the expected behavior?**
The commented on text should be highlighted (which is supposed to be toggleable in the options, haven't found it) and clicking a comment's entry in the left sidebar should jump to the respective comment in the text.

**Did this work in previous versions of DocumentServer?**
I don't know.

**DocumentServer version:**
I'm using NC 18.0.3 as a managed instance by a service provider.

**Operating System:**
No idea.

**Browser version:**
Firefox latest and Brave latest on Linux.

**Comment by Rita-Bubnova** [comment]
Hello, @thorsten-panknin.
Could you attach a screenshot of the tab "About"?

**Comment by thorsten-panknin** [comment]
I don't see an About tab, where is it supposed to be?

I can provide you with the OnlyOffice version right now if that helps: 5.4.2.46

**Comment by Rita-Bubnova** [comment]
@thorsten-panknin, unfortunately, we do not update version 5.4 any more.
Could you reproduce your problem on current stable version 5.5?

**Comment by thorsten-panknin** [comment]
No, I can't, because I'm on a managed instance. I'm depending on the DocumenServer version which comes with Nextcloud.

**Comment by ShockwaveNN** [comment]
> I'm depending on the DocumenServer version which comes with Nextcloud.

But that are you expecting from us, ONLYOFFICE team?
We not 100% sure, but think your issue is fixed in current stable version of DocumentServer.
If you can't update your instance - how you possible think we can fix your issue

**Comment by thorsten-panknin** [comment]
Im not expecting you to fix anything on a version you are not updating anymore. I was simply replying to your colleague. And yeah, it might be the community server.

**Comment by ShockwaveNN** [comment]
Sorry if I seems to be rude)

Also pleasenote, that Community DocumentServer is separate project from us, ONLYOFFICE, so if you using it, better to report your problem to their issue tracker

**Comment by ShockwaveNN** [comment]
Moving this issue to onlyoffice-nextcloud repo to apply tag.
