### ISSUE TITLE
Allow import .thmx to presentation

### ISSUE THREAD

**Issue by Mysterycz** [ONLYOFFICE/DocumentServer#881]
Hello,

If I open some of our presentations on nextcloud, there is white background with bad formating. Can you add option to import themes (.thmx) to presentation module?

**Comment by Rita-Bubnova** [comment]
Hello, @Mysterycz.
Could you describe in more detail how you want to import themes in the presentation?

At the moment, this can be done by following the instruction: https://helpcenter.onlyoffice.com/server/linux/document/add-themes.aspx.
But this is only suitable for `pptx`, `potx`, `pptm`, `potm` (not for `thmx`).

**Comment by Mysterycz** [comment]
Hello @Rita-Bubnova 
I would like to import themes this way:
https://www.webucator.com/how-to/how-save-custom-theme-microsoft-powerpoint.cfm
Anyway, does this import via your advice work for onlyoffice in Nextcloud instance?

**Comment by Rita-Bubnova** [comment]
@Mysterycz, the script you are describing (https://www.webucator.com/how-to/how-save-custom-theme-microsoft-powerpoint.cfm) is used in the MS PowerPoint desktop editor.
We don’t understand where you want to save the themes (to the local disk)? And how should the document server get theams from there?

**Comment by Mysterycz** [comment]
Well, I would like to save it to my local disk and import it to the server.  I thought there is some command or script which import/install this theme (.thmx) to the document server. 
It seems I can just upload my .pptx to /onlyoffice/documentserver/sdkjs/slide/themes/src and it start s to working without any command. (I am using onlyoffice in Nextcloud)

All these missunderstandings comes from this:
https://github.com/ONLYOFFICE/DocumentServer/issues/7
Where you can import font via shell script. I thought you have to do it for PowePoint themes too.
Anyway thanks.

**Comment by ShockwaveNN** [comment]
> it start s to working without any command
Actually this is strange, but if it's working for you I'll close this issue

Feel free to comment if got any question

**Comment by Mysterycz** [comment]
One more question, which .sh script do I need to run in Nextcloud onlyoffice to generate these templates? It seems that some of them are not working even if first two which I coppied just did. 
Thank you.

**Comment by ShockwaveNN** [comment]
As it said in https://helpcenter.onlyoffice.com/server/linux/document/add-themes.aspx
You shuold run 
```
/usr/bin/documentserver-generate-allfonts.sh
```
(ignore that it just fonts in naming, you can see by content of this script - it generate fonts and themes templates

**Comment by Mysterycz** [comment]
Sure, but I have this version:
https://github.com/nextcloud/documentserver_community
Which is little different I guess and there is no such a .sh script.

Add font by path occ documentserver:fonts --add /usr/share/fonts/myfont.ttf

This is for font but missing command for presenter templete or can I add it manually?

**Comment by ShockwaveNN** [comment]
> Sure, but I have this version:
https://github.com/nextcloud/documentserver_community

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
