### ISSUE TITLE
/web-apps/apps/documenteditor/main/index.html  not show

### ISSUE THREAD

**Issue by stereo720712** [ONLYOFFICE/DocumentServer#884]
Excuse me,
I use build tools to build DocumentServer.
after I build,
test for the index page, but it is not correct show
can anyone help ?
thanks
the page like the follow
https://imgur.com/a/wsyWOGI

**Comment by ShockwaveNN** [comment]
Please stop spamming

https://github.com/ONLYOFFICE/build_tools/issues/98
