### ISSUE TITLE
Metrics daemon is not running

### ISSUE THREAD

**Issue by falling-star** [ONLYOFFICE/DocumentServer#886]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behaviour?**

Metrics daemon is not running. I have few questions -

What is the use case of Metrics daemon ?
Is Metrics daemon a hard requirement for Document Server to work ?

Error logs at - /var/log/onlyoffice/documentserver/metrics/err.log-20200522
<img width="1438" alt="Screenshot 2020-05-23 at 7 08 36 PM" src="https://user-images.githubusercontent.com/3634908/82732131-ed143a80-9d28-11ea-90f6-4866ce2c8f55.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Metrics daemon is not running while installing version "5.5.1".

**What is the expected behavior?**

If Metrics daemon is not a hard requirement for Document Server to work, we are good.

**Did this work in previous versions of DocumentServer?**

Not sure If Metrics daemon was there in previous versions.

**DocumentServer version:**

5.5.1

**Operating System:**

Linux 3.10.0-1127.el7.x86_64 x86_64

**Browser version:**

Doesn't apply.

**Comment by ShockwaveNN** [comment]
> If Metrics daemon is not a hard requirement for Document Server to work, we are good.

Yeah it's optional daemon to get metrics, you can safely disable it

But not sure why you get that error, is there any custom configs? Seems default backend for statsd is `backends: [ "./backends/console" ]`, not sure why it trying to find module `statsd-datalog-backend`

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
