### ISSUE TITLE
server router  http://xxxx/converter converter docx to html error

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/DocumentServer#887]
I use http://xxxx/converter converter docx to html but got error -7, converter pdf , txt is OK。

![image](https://user-images.githubusercontent.com/11469578/82795739-03480500-9ea7-11ea-88ad-65a51efc9d6b.png)

**Comment by ShockwaveNN** [comment]
https://api.onlyoffice.com/editors/conversionapi#text-matrix

Accroding to our docs we do not support converting formats to `html`

**Comment by cs686** [comment]
@ShockwaveNN thanks, callback url payload can get docx url, can I got a html url
![image](https://user-images.githubusercontent.com/11469578/82796995-fe845080-9ea8-11ea-9e34-1746c285d746.png)

**Comment by ShockwaveNN** [comment]
> callback url payload can get docx url, can I got a html url 

I do not understand that do you mean

If you want to able to edit html files  without converting to docx - there is no such way

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by dmkash** [comment]
@ShockwaveNN Hi, there! Sorry to update on a closed issue.  We actually just yesterday were talking about using the conversion service to convert a DOCX to HTML, and then read the docs.  😩  Are there any plans to implement this conversion?  Or is this something not even on the radar?  Thanks!

**Comment by ShockwaveNN** [comment]
Hi, I asked our dev team - and currently we do not planning to add docx -> html

But you can create new issue (because I think description of this issue is misleading) and we monitor if a lot of user request it we think about implementation

**Comment by dmkash** [comment]
@ShockwaveNN Thank you!
