### ISSUE TITLE
OnlyOffice doesn't open/edit CSV-files correct 

### ISSUE THREAD

**Issue by configonfi** [ONLYOFFICE/DocumentServer#889]
**Do you want to request a *feature* or report a *bug*?**
Bug!

**What is the current behavior?**
If I click on a CSV-File to open it Openoffice starts with the message "Loading table", but nothing else happens. It doesn't matter if I click on the file, or rightclick on it. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simple upload a CSV-File (no matter if Comma- or semikolon-seperated) and try to open/edit it with OnlyOffice.

**What is the expected behavior?**
I expect to be able to edit the CSV-File like a XLSX-File.

**Browser version:**
Firefox 76

We use the "Community Document Server 0.1.5" and Nextcloud 18.04.

**Comment by ShockwaveNN** [comment]
Hi, please add version of DocumentServer and which file storage you using (nextcloud, owncloud etc...)

**Comment by configonfi** [comment]
> Hi, please add version of DocumentServer and which file storage you using (nextcloud, owncloud etc...)

We use the "Community Document Server 0.1.5" and Nextcloud 18.04.

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by ShockwaveNN** [comment]
Moving this issue to onlyoffice-nextcloud repo to apply tag.
