### ISSUE TITLE
Configure default paper size

### ISSUE THREAD

**Issue by SLYtiger16** [ONLYOFFICE/DocumentServer#891]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
This is unavailable as a default option
**What is the expected behavior?**
api would allow for default paper sizing based on 'name' such as 'US Letter' or 'A4'.

New more specific request created from closed issue #645

**Comment by ShockwaveNN** [comment]
Ok, thanks for your enhancement, i created new issue 45480 in our private bug tracker. I'll post here as soon as there will be any news about that feature

**Comment by ShockwaveNN** [comment]
Hi, we have a discussion withing our team and decided, that page size is not an just an inteface option, line unit of meaurements, it's document property.

In that case you want to change default document, which used for creating new empty document.
This can be changed on DocumentManagementSystem side. Replace empty file, or add some code that will set different empty file depending of which region set in DMS
