### ISSUE TITLE
I Cannot open with the source code

### ISSUE THREAD

**Issue by fangjialong2019** [ONLYOFFICE/DocumentServer#896]
'sdkjs/develop/sdkjs/cell/scripts.js' Not Found

Please pull the scripts to github

**Comment by ShockwaveNN** [comment]
I do not understand you. Please fill issue template corectly

**Comment by fangjialong2019** [comment]
@ShockwaveNN Hi

This is not a bug.

We have been using the social version of OnlyOffice for a long time. We have modified some of the source code to meet our internal requirements.

Before version 5.5, you could broker network requests to local directories, such as SDKJS and Web-apps, directly from Fiddler or Charles. SDKJS source code is loaded through a file called SDk_dev_scripts.js.

But since 5.5 the tag, sdk_dev_scripts. Js was removed, replaced by 'SDKJS/develop/SDKJS/cell/scripts. Js'. However, the file could not be found in the code repository.

**Comment by ShockwaveNN** [comment]
> This is not a bug.

I never said this is a bug, but an issue, and template is for all

> SDKJS source code is loaded through a file called SDk_dev_scripts.js.

Still didn't get, could you locate old file in history of github repo and point out how to find `SDKJS/develop/SDKJS/cell/scripts.js` in current version.
`develop` in path is very strange for me

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
