### ISSUE TITLE
502 nginx / ds:docservice FATAL Exited too quickly

### ISSUE THREAD

**Issue by krosseyed** [ONLYOFFICE/DocumentServer#897]
I am reporting a bug as I am unable to start the document service in the document server container

Here is an output of the document server err.log logfile:

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadConfigurationFile (/var/www/onlyoffice/documentserver/server/Common/node_modules/log4js/lib/log4js.js:49:17)
    at Object.configure (/var/www/onlyoffice/documentserver/server/Common/node_modules/log4js/lib/log4js.js:58:20)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/logger.js:15:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
undefined:1`

I was expecting this to start up as usual, and this was working before I changed the IP address of the VM running the onlyoffice docker containers

**DocumentServer version:**
5.4.2.46

**Operating System:**

Linux onlyoffice 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

**Browser version:**

I am using Firefox on Windows 10, but this is impacting any browser I test this with.

**Comment by ShockwaveNN** [comment]
> start the document service in the document server container

Which command are you using to start container? Seems you mounting volume with incorrect config file

**Comment by krosseyed** [comment]
I am very sorry about the delay in response. I have scrapped this particular build and will be rebuilding on a ppc64el server.

I will close this ticket as this issue has been resolved via deletion.

**Comment by ShockwaveNN** [comment]
Ok

Also please note:

> rebuilding on a ppc64el server

Currently we do not support ppc64el https://github.com/ONLYOFFICE/DocumentServer/issues/859
And there was attemt to implement it https://github.com/ONLYOFFICE/build_tools/pull/87, but not finished

**Comment by krosseyed** [comment]
@ShockwaveNN I will follow #859 to monitor progress on this. I have a pretty beefy power9 server that I would love to run OnlyOffice on, but I know ppc64el resources are limited.

Let me know if there is anything I can do to help. I am glad that you are now hooked up with Integricloud as they are great people that are serious about their platform.
