### ISSUE TITLE
german quotation marks missing / not working

### ISSUE THREAD

**Issue by derdjme** [ONLYOFFICE/DocumentServer#898]
I'm using the community version DocumentServer 5.5.3. on Nextcloud 18.0.5. The error I'm going to describe occurs in documents, sheets and presentations. It is impossible to use german quotation marks. When using quotation marks in german it always starts with a lower quotation mark and ends with an upper quotation mark like this: **„bla bla bla“** 

Is there a fix for this? Or is it simply just not implemented?

**Comment by Rita-Bubnova** [comment]
Hello, @derdjme.
Thank you for report. You're right, it is not implemented.
I create new issue 45591 in our private issue tracker.

**Comment by derdjme** [comment]
> Hello, @derdjme.
> Thank you for report. You're right, it is not implemented.
> I create new issue 45591 in our private issue tracker.

You're welcome. Glad I could help. Looking forward to see it working in future releases.

**Comment by Rita-Bubnova** [comment]
This issue fixed in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Comment by elfenfeuer** [comment]
Hello, i have this same problem. I need the quotation marks to automatically come up „like this“. I have tried changing them in Math AutoCorrect. Hasn't worked.  My language is set up to be German (Austria). Please advise, as I couldn't find any help online.
