### ISSUE TITLE
bad gateway after upgrade to licensed version

### ISSUE THREAD

**Issue by thommierother** [ONLYOFFICE/DocumentServer#899]
I bought a license key for ONLYOFFICE Integration Edition Home Server. Added the license file to my already running free doc server and it is now in /var/www/onlyoffice/Data/. Now I see gateway 502 error from the nginx, the error message is:

2020/06/06 21:10:37 [error] 1528#1528: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 195.54.160.135, server: , request: "GET /solr/admin/info/system?wt=json HTTP/1.1", upstream: "http://127.0.0.1:8000/solr/admin/info/system?wt=json", host: "136.243.85.153", referrer: "http://136.243.85.153:80/solr/admin/info/system?wt=json"
root@docs:~# cd /etc/

Did I miss something or do I need to reinstall the whole code before I can use the licensed version?

Thanks for help,
thommie

**Comment by ShockwaveNN** [comment]
Hi, is there any errors in `/var/log/onlyoffice/`?

Seems DocumentServer trying to connect to some http://127.0.0.1:8000/solr/admin/info/system?wt=json url, which is not aviable. I think DocumentServer itselft may working fine
Could you also try to see that is out ot 

http://documentserver-url:port/healthcheck

**Comment by thommierother** [comment]
Healthcheck doesnt oirk because of the 502, log contains

nginx.error.log
2020/06/08 12:27:35 [error] 25308#25308: *327 connect() failed (111: Connection refused) while connecting to upstream, client: 195.54.160.135, server: , request: "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP HTTP/1.1", upstream: "http://127.0.0.1:8000/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP", host: "136.243.85.153", referrer: "http://136.243.85.153:80/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP"
2020/06/08 12:40:29 [error] 25308#25308: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/08 12:40:29 [error] 25308#25308: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/favicon.ico", host: "docs.netzwissen.de"

2020/06/08 12:27:35 [error] 25308#25308: *327 connect() failed (111: Connection refused) while connecting to upstream, client: 195.54.160.135, server: , request: "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP HTTP/1.1", upstream: "http://127.0.0.1:8000/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP", host: "136.243.85.153", referrer: "http://136.243.85.153:80/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP"
2020/06/08 12:40:29 [error] 25308#25308: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/08 12:40:29 [error] 25308#25308: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/favicon.ico", host: "docs.netzwissen.de"

**Comment by thommierother** [comment]
But I dont understand the http://127.0.0.1:8000/solr/admin/info/system?wt=json ist this a new url?

**Comment by ShockwaveNN** [comment]
> Healthcheck doesnt oirk because of the 502, log contains

If healthcheck fails - something wrong, need more logs from `/var/log/onlyoffice`

>http://127.0.0.1:8000/solr/admin/info/system?wt=json

Don't sure that you mean, `solr/admin/info` defenetly is not a part of any DocumentServer urls

**Comment by thommierother** [comment]
I have no idea either where it comes from... The only thing I did was the update of the docserver through apt with the normal repo from https://download.onlyoffice.com/repo/debian squeeze main.

More logs:

```
root@docs:/var/log/onlyoffice/documentserver# tail -n 200 docservice/err.log
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Configuration property "pgPoolExtraOptions" is not defined
    at Object.Config.get (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/postgreSqlBaseConnector.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:25:18)
pkg/prelude/bootstrap.js:1185
      throw error;
```
      
Looks like an exception form a missing property? Something new which cam through the update?

**Comment by ShockwaveNN** [comment]
Yeah, this is error from DocumentServer, `pgPoolExtraOptions` is new options from some of recent updates

You can add missing option like in defaul.json:
https://github.com/ONLYOFFICE/server/blob/e6731c54dc932c0e1d42e5595e10be20574c14d5/Common/config/default.json#L120

**Comment by thommierother** [comment]
ok, the exception from the missing property is gone now, but healthcheck still says 

Cannot GET /welcome/healthcheck

in the log:

2020/06/08 15:00:23 [error] 25308#25308: *345 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/08 15:00:24 [error] 25308#25308: *345 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/08 15:00:24 [error] 25308#25308: *345 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de

**Comment by thommierother** [comment]
... and https://docs.netzwissen.de/welcome/ is ok now, no gateway error.

**Comment by ShockwaveNN** [comment]
> Cannot GET /welcome/healthcheck

This is not right, are your sure there is no other errors in many `/var/log/onlyoffice` log files?
If not - are all services running correctly - check by `supervisorctl status all`

If everything ok - I think problem with nginx config, try to compare it with default config, maybe something missed in upgrade. You can look out this file in docker

**Comment by thommierother** [comment]
Good morning,
hm, services are running:

root@docs:~# supervisorctl status all
ds:converter                     RUNNING   pid 1490, uptime 15:20:50
ds:docservice                    RUNNING   pid 1487, uptime 15:20:50
ds:metrics                       RUNNING   pid 1484, uptime 15:20:50
ds:spellchecker                  RUNNING   pid 1486, uptime 15:20:50

But we have a handshake issue left in the log (the "Connection refused" entries are from before adding the "pgPoolExtraOptions") :

```
"GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/08 15:00:24 [error] 25308#25308: *345 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/08 15:00:24 [error] 25308#25308: *345 connect() failed (111: Connection refused) while connecting to upstream, client: 87.183.234.207, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "docs.netzwissen.de"
2020/06/09 03:23:10 [crit] 1387#1387: *80 SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking, client: 184.105.247.196, server: 0.0.0.0:443

```

**Comment by ShockwaveNN** [comment]
So seems there is only one current error (judging by date) - SSL_do_handshake

I've googled
`SSL routines:tls_early_post_process_client_hello:version too low` and seems this is problem with not matching SSL libs version, something like this https://github.com/openssl/openssl/issues/4989
I'm not very good in SSL, I think you just at least try to update openssl and all other ssl libraries, maybe they outdated

**Comment by thommierother** [comment]
Well, the whole server is auto-updated through unattended updates and its the current standard package for 18.04 lts: 

root@docs:~# dpkg -s openssl
Package: openssl
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 1223
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1.1.1-1ubuntu2.1~18.04.6
Depends: libc6 (>= 2.15), libssl1.1 (>= 1.1.1)

**Comment by ShockwaveNN** [comment]
Could you try to disable SSL/https and see if DocumentServer is working?
I'm almost out of ideas, can advise use docker, it's much simpler to debug any problem

**Comment by thommierother** [comment]
ok, I can try that, but I don't understand how this happened: the server was running normal for months and the issue came up after the last upgrade and switch to the licensed version

**Comment by ShockwaveNN** [comment]
>  the issue came up after the last upgrade 

I think this is related to upgrade, but switchin to licensed version has nothing to do, it's just `.lic` file, without any major changes in code of DocumentServer

**Comment by thommierother** [comment]
I made a reboot of the doc server and the ssl error is gone, the nginx log is clean now.  
next step: I updated the owncloud connector from https://marketplace.owncloud.com/apps/onlyoffice.  I see the following error in out.log:

root@docs:/var/log/onlyoffice/documentserver# tail -f docservice/out.log
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-06-09T10:07:18.957] [ERROR] nodeJS - postData error: docId = 2942984089;url = https://devel.netzwissen.de/owncloud/index.php/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ0ZXN0NiIsIm93bmVySWQiOiJ0aG9tbWllNEB3d3cubmV0endpc3Nlbi5kZVwvb3duY2xvdWQiLCJmaWxlSWQiOjU5NCwiZmlsZVBhdGgiOiJcL3Rlc3QuZG9jeCIsInNoYXJlVG9rZW4iOm51bGwsImFjdGlvbiI6InRyYWNrIn0.8-xU1120cLsHjmg4El5Qq_Mpw2Yya0ofgptx-N8zvI0;data = {"key":"2942984089","status":1,"users":["ocm8iylg8yj1_test6"],"actions":[{"type":1,"userid":"ocm8iylg8yj1_test6"}]}
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

When using the docserver from out test machine. No change on the OC server concerning docserver settings (api key etc). The test machine has owncloud 10.5 beta, but that should no be important ...

**Comment by ShockwaveNN** [comment]
I think this error is not replated to Documentserver itself, since it's from connector.
Please create new issue at https://github.com/ONLYOFFICE/onlyoffice-owncloud/

**Comment by thommierother** [comment]
No, this has nothing to do with the connector, I think. We also have that exception when connecting the docserver directly at

https://docs.netzwissen.de/welcome/healthcheck

I see "Cannot GET /welcome/healthcheck" as the response 
and a corresponding exception in out.log:

```
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root@docs:/var/log/onlyoffice/documentserver# 
```
And nothing in the nginx log. So, the problem originates in the app server, not in the web server.

**Comment by ShockwaveNN** [comment]
https://docs.netzwissen.de/welcome/healthcheck

You should check not this url, but

https://docs.netzwissen.de/healthcheck

**Comment by thommierother** [comment]
true

**Comment by thommierother** [comment]
ok, it seems like the secret key has been removed from the local.json during update

**Comment by ShockwaveNN** [comment]
> ok, it seems like the secret key has been removed from the local.json during update

This can be. See https://github.com/ONLYOFFICE/DocumentServer/issues/892

**Comment by thommierother** [comment]
Hm, what was the correct syntax here? I still get "invalid token" when saving in the connector application

....
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "Authorization",
          "inBody": false
        },
        "outbox": {
          "header": "Authorization",
          "inBody": false
        }
      },
      "secret": {
        "inbox": {
          "string": "xxxx"
        },
        "outbox": {
          "string": "xxxx"
        },
        "session": {
          "string": "xxxx"
        }
      }

**Comment by ShockwaveNN** [comment]
Yeah, everything seems fine in syntax, is this placed in `/etc/onlyoffice/documentserver/local.json`?

**Comment by thommierother** [comment]
yes

**Comment by thommierother** [comment]
are there any characters which can **not** be used in the jwt secret? I've set a new key but get "invalid tooken" replies all the time on both OC 10.4 and 10.5

**Comment by ShockwaveNN** [comment]
> are there any characters which can not be used in the jwt secret?

I'm not sure
I'm still think problem is not related to DocumentServer per-se
Could you try to start integrated test example via `supervisorctl start all`
Go to `https://documentserver/example` and see if files are opened and saved correctly?

**Comment by thommierother** [comment]
ok, II*ll try. Here is the local.json just to double check if all is OK:

```
{
  "services": {
    "CoAuthoring": {
      "sql": {
        "dbHost": "localhost",
        "dbName": "onlyoffice",
        "dbUser": "onlyoffice",
        "dbPass": "onlyoffice",
        "type": "postgres",
        "dbPort": "5432"
      },
      "redis": {
        "host": "localhost"
      },
      "token": {
        "enable": {

"request": {
  "inbox": true,
  "outbox": true
},
"browser": true
},
"inbox": {
"header": "Authorization",
"inBody": false
},
"outbox": {
"header": "Authorization",
"inBody": false
}
},
"secret": {
"inbox": {
"string": "xxx"
},
"outbox": {
"string": "xxx"
},
"session": {
"string": "xxx"
}
}
}
},
"rabbitmq": {
"url": "amqp://admin:6swdBuoXyyir8YmX@localhost"
}
}
```

**Comment by ShockwaveNN** [comment]
Yeah, I think it should be OK, if not - you'll see errors in logs

**Comment by thommierother** [comment]
```
root@docs:/etc/onlyoffice/documentserver# ls -la
total 76
drwxr-xr-x 6 root   root   4096 Jun  9 13:54 .
drwxr-xr-x 3 root   root   4096 Nov  3  2019 ..
-rw-r--r-- 1 100000 100000 6115 Jun  8 15:00 default.json
-rw-r--r-- 1 100000 100000 6141 Mai 18 20:13 default.json.dpkg-dist
-rw-r--r-- 1 root   root   6085 Jun  8 14:59 default.json.old
-rw-r--r-- 1 root   root   1241 Mai 18 20:13 development-linux.json
-rw-r--r-- 1 100000 100000 1522 Apr  6 14:48 development-mac.json
-rw-r--r-- 1 100000 100000 1527 Mär  2 22:40 development-windows.json
-rw-r--r-- 1 root   root    989 Jun  9 13:49 local.json
-rw-r--r-- 1 root   root    950 Jun  9 12:16 local.json.old

```

**Comment by ShockwaveNN** [comment]
This is not right, it should be something like
```
ls -la /etc/onlyoffice/documentserver
total 56
drwxr-xr-x 6 root root 4096 May 22 12:27 .
drwxr-xr-x 4 root root 4096 May 22 12:27 ..
-rw-r--r-- 1 root root 6140 May 18 21:02 default.json
-rw-r--r-- 1 root root 1241 May 18 21:02 development-linux.json
-rw-r--r-- 1 root root 1522 May 18 21:02 development-mac.json
-rw-r--r-- 1 root root 1527 May 18 21:02 development-windows.json
-rw-r--r-- 1 root root  885 May 22 12:27 local.json
drwxr-xr-x 2 root root 4096 May 22 12:27 log4js
drwxr-xr-x 2 root root 4096 May 22 12:27 logrotate
drwxr-xr-x 3 root root 4096 May 22 12:27 nginx
-rw-r--r-- 1 root root 2189 May 18 21:02 production-linux.json
-rw-r--r-- 1 root root 1622 May 18 21:02 production-windows.json
drwxr-xr-x 2 root root 4096 May 22 12:27 supervisor
```

**Comment by thommierother** [comment]
Hi Pavel,

meanwhile I disabled the jwt token stuff for testing. https://docs.netzwissen.de/healthcheck replies with true. nginx log is clean and /docservice/out.log only has some warnings

```
root@docs:~# tail -f /var/log/onlyoffice/documentserver/docservice/out.log
[2020-06-11T06:25:05.222] [WARN] nodeJS - Express server starting...
[2020-06-11T06:25:05.225] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-06-11T06:25:05.340] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
```

Even without the jwt token I see errors on the owncloud side for both oc 10.4 and 10.5 RC

```
"reqId":"kr19GWjjdowUcj6oicWU","level":3,"time":"2020-06-11T07:06:22+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/new","message":"Use of undefined constant shareToken - assumed 'shareToken' (this will throw an Error in a future version of PHP) at \/var\/www\/owncloud\/apps\/onlyoffice\/controller\/editorcontroller.php#175"}
{"reqId":"kr19GWjjdowUcj6oicWU","level":3,"time":"2020-06-11T07:06:22+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/new","message":"touch(): Unable to create file \/mnt\/data\/ocdata\/admin\/files\/test.docx because No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#217"}
{"reqId":"kr19GWjjdowUcj6oicWU","level":3,"time":"2020-06-11T07:06:22+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"POST","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/new","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(66): OC\\\\Files\\\\Node\\\\Node->checkPermissions()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/onlyoffice\\\/controller\\\/editorcontroller.php(232): OC\\\\Files\\\\Node\\\\File->putContent()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Onlyoffice\\\\Controller\\\\EditorController->create()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(916): OC\\\\Route\\\\Router->match()\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}"}
```

I think the problem lies inside the connector 4.2.1. We already had an issue in an earlier version where the connector did not work in combination with an encrypted oc storage. I think this re-appeared now and we have a regression, >> something for https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues

Bye, Thommie

**Comment by ShockwaveNN** [comment]
> and /docservice/out.log only has some warnings
Yeah, those warning completely normal

> I think this re-appeared now and we have a regression, >> something for https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues

Ok, I'll agree, in that case I'll close this issue, but feel free to comment if got some new info

**Comment by thommierother** [comment]
ok, I had some communication with @LinneyS then, created new issue now at https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/310
