### ISSUE TITLE
Issue with kazakh letter "ө" when typing on keyboard

### ISSUE THREAD

**Issue by deedarb** [ONLYOFFICE/DocumentServer#9]
This letter located between "0" and "+", when i press it "-" is typed.
Trying to turn on "hieroglyph" adds additional input on screen.
For more info http://dev.onlyoffice.org/ru/viewtopic.php?f=35&t=2070

**Comment by deedarb** [comment]
fix please :) users hate us for copy pasting this letter

**Comment by AnaMih** [comment]
It will be fixed in one of the next releases. Sorry for the inconveniences.

**Comment by trofim24** [comment]
fix

**Comment by deedarb** [comment]
is it possible to patch existing old DocumentServer without recompiling?

**Comment by trofim24** [comment]
> @trofim24 is it possible to patch existing old DocumentServer without recompiling?

No. We completely rewrote the server. Renounce the use of layers of mono.
It is necessary to re-compile server. We are now appends the updated instructions.
