### ISSUE TITLE
Roadmap shows same common task within two Versions (4.5 / 5.0)

### ISSUE THREAD

**Issue by math** [ONLYOFFICE/DocumentServer#90]
Within the **Common tasks for all**  the bullet **Undo/redo for fast collaborative editing** is shown in the target of **version 4.5** and **5.0**.

Is this an improper release note definition or does this mean that the task is resolved either in version 4.5 or 5.0 depending on the progress?

**Comment by JohnPerkin** [comment]
Hello @math!
Thank you for your remark, we will correct roadmap. 
Undo is already implemented in 4.3 release for documents and presentations and will appear in 4.5 for spreadsheets. Redo will appear in later versions.

**Comment by agolybev** [comment]
#97
