### ISSUE TITLE
Service not properly defined in logrotate configuration

### ISSUE THREAD

**Issue by elpito** [ONLYOFFICE/DocumentServer#902]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Service does not restart after logfile rotation. This is a RPM installation!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just run `logrotate /etc/logrotate.d/ds.conf`, but only works, if the logfile is rotated!

**What is the expected behavior?**
supervisord.service restartet

**Did this work in previous versions of DocumentServer?**
Don't know, it's a fresh installation

**DocumentServer version:**
onlyoffice-documentserver-5.5.3-39.x86_64

**Operating System:**
CentOS 8
**Browser version:**
Not relevant

**FIX:**
Change following line in `/etc/onlyoffice/documentserver/logrotate/ds.conf`:
`service supervisor restart > /dev/null`
to:
`service supervisord restart > /dev/null`

**Comment by ShockwaveNN** [comment]
Yeah, seems this is a bug, ther is no `supervisor` service, but only `supervisord`

```
# systemctl | grep super
supervisord.service                                                                       loaded active running   Process Monitoring and Control Daemon  
```

Seems problem is that this service named `supervisor` on Ubuntu and `supervisord` on Centos

@agolybev Please take a look

**Comment by heatray** [comment]
I fixed issue at https://github.com/ONLYOFFICE/document-server-package/pull/99 (private repo)

Fix will be available in the next bugfix release

**Comment by sharq88** [comment]
@ShockwaveNN or @papacarlo can you see when the next version will be released?

**Comment by ShockwaveNN** [comment]
@sharq88 we hope it will be ready in next several weeks, but I cannot guarantee

**Comment by ShockwaveNN** [comment]
DocumentServer v5.6.0 is released and this problem should be fixed
