### ISSUE TITLE
Difference between disable websocket in conf or in RPA

### ISSUE THREAD

**Issue by svgta1** [ONLYOFFICE/DocumentServer#904]
Hi,

Is there a difference in doc server if we disable websocket in onlyoffice configuration file or if we block it in RPA ? 
I saw that with websocket enable, when there is a network problem, websoket try to reconnect. But, with xhr, after few attempts, it's stop to try te reconnect.

**Comment by ShockwaveNN** [comment]
> if we block it in RPA

Could you describe that RPA mean, I'm not sure that it is

**Comment by svgta1** [comment]
Reverse Proxy.
In apache or nginx we can not enable websocket. But, onlyoffice try to use it if enable in the conf file, but there is a 500 error.

**Comment by ShockwaveNN** [comment]
Could you attach HAR file from browser when situation with xhr
> But, with xhr, after few attempts, it's stop to try te reconnect.

is happened

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
