### ISSUE TITLE
namespace error : Namespace prefix wp14 on sizeRelH is not defined

### ISSUE THREAD

**Issue by makakken** [ONLYOFFICE/DocumentServer#905]
Bug Report:

[index] Error: OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
^
namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
^
at <>

    /var/www/example.com/apps/documentserver_community/lib/DocumentConverter.php line 123
    OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_QKaaUf-.xml", null)
    /var/www/example.com/apps/documentserver_community/lib/Document/DocumentStore.php line 229
    OCA\DocumentServer\DocumentConverter->runCommand(OCA\DocumentServ ... {})
    /var/www/example.com/apps/documentserver_community/lib/LocalAppData.php line 100
    OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document{closure}("*** sensitive parameters replaced ***")
    /var/www/example.com/apps/documentserver_community/lib/Document/DocumentStore.php line 232
    OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\SimpleFS\SimpleFolder {}, Closure {})
    /var/www/example.com/apps/documentserver_community/lib/Controller/DocumentController.php line 179
    OCA\DocumentServer\Document\DocumentStore->convertForDownload(918111026, null, {c: "save",id: " ... "})
    /var/www/example.com/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\DocumentController->download(918111026, {c: "save",id: " ... "})
    /var/www/example.com/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "download")
    /var/www/example.com/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "download")
    /var/www/example.com/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\DocumentSe ... r", "download", OC\AppFramework\ ... {}, {docId: "9181110 ... "})
    <>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({docId: "9181110 ... "})
    /var/www/example.com/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {docId: "9181110 ... "})
    /var/www/example.com/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... 6")
    /var/www/example.com/index.php line 38
    OC::handleRequest()

POST /apps/documentserver_community/3rdparty/onlyoffice/documentserver/downloadas/918111026?cmd=%7B%22c%22%3A%22save%22%2C%22id%22%3A%22918111026%22%2C%22userid%22%3A%22ocabjdjvxihu_makakken%22%2C%22outputformat%22%3A65%2C%22title%22%3A%22Zwischenbericht%20explore%2020200612.docx%22%2C%22nobase64%22%3Atrue%2C%22savetype%22%3A3%2C%22saveindex%22%3A1%2C%22userconnectionid%22%3A%22ocabjdjvxihu_xxx1%22%7D
from 94.134.91.66 by xxx at 2020-06-13T11:39:14+00:00

I really often experience such issues. Can Anyone tell me why my OnlyOffice Server, or the DocumentServerCommunity have so much problems while converting .docx files? is there something i can do?

**Comment by ShockwaveNN** [comment]
Hi, are you using `Nextcloud Community Document Server` or `ONLYOFFICE DocumentServer`?
If last one - please fill issue template and add info about OS and product version

**Comment by makakken** [comment]
it's `Nextcloud Community Document` Server.

**Comment by ShockwaveNN** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by ShockwaveNN** [comment]
Moving this issue to onlyoffice-nextcloud repo to apply tag.
