### ISSUE TITLE
Spreadsheet number format negative time

### ISSUE THREAD

**Issue by vogych** [ONLYOFFICE/DocumentServer#906]
Negative times would also be ideal for a time sheet (spreadsheet).

Should work time 40:00:00
Working time is 38:00:00
Total -02: 00: 00

Why are there only positive time formats?
Can the formats be adjusted somewhere compared to Excel?

**Comment by slisystem** [comment]
@Rita-Bubnova I do have the same issue and it actually occurred to me in the same use-case. I wrote a small work-time tracking spreadsheet and "negative" overtime is not being displayed. Oddly though, the computations do still work: I am tracking overtime per week and total overtime. In one week my overtime was negative and the cell only displayed "########", but the total overtime got correctly reduced by the entry in this cell.

**Comment by Caaruzo** [comment]
same issue for me, also need this feature please. Its also not possible to create custom time format with >24h.
See here: https://github.com/ONLYOFFICE/DesktopEditors/issues/682

**Comment by ulimoebius** [comment]
same issue still for me. this is disturbing, that only-office cant show negative time. is there a timeline for an solution?

**Comment by Rita-Bubnova** [comment]
The issue about support 1904 date system fixed (https://github.com/ONLYOFFICE/sdkjs/commit/8b84700ad8eb912682b984dac3f69b1a51d0123d, https://github.com/ONLYOFFICE/web-apps/commit/98a418f7e33f620de5dfc14f24853c479001771a, https://github.com/ONLYOFFICE/web-apps/commit/8e6ad3b0c685482934fceac60e0efc8433ca2f07) in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Comment by whimboo** [comment]
Yesterday I've upgraded to version 8.0 after seeing that 7.x doesn't still allow me to format a cell as time which contains a negative value.

![Screenshot 2024-02-02 at 08 33 00](https://github.com/ONLYOFFICE/DocumentServer/assets/129603/0167aeac-ad9b-4993-9376-01ca901fc2af)

 So we probably should reopen this issue?

**Comment by whimboo** [comment]
That indeed fixes the issue for me. Thanks a lot for clarifying.
