### ISSUE TITLE
Fonts are not sharp when using document editor in Firefox

### ISSUE THREAD

**Issue by k-matti** [ONLYOFFICE/DocumentServer#908]
![image](https://user-images.githubusercontent.com/66017397/84229744-a70df380-aaea-11ea-8797-ea5136ee5591.png)

As you can see spreadsheet font looks not sharp.
When I open the same document in nextcloud app on my iphone font looks ok

I am using NC 19
Onlyoffice app 4.2.0
Document server the newest version in docker container

**Comment by ShockwaveNN** [comment]
@k-matti Hi, that is zoom value on this page in Firefox?

**Comment by k-matti** [comment]
@ShockwaveNN 

Sorry for the problem, I didn't notice I have default zoom level 120% in Firefox
I had to set it to 120% because of dpi scanning problem in Ubuntu.

Setting zoom level to 100% in Firefox fixed the issue with non sharp fonts

**Comment by ShockwaveNN** [comment]
@k-matti We hope we'll fix this problem in future, but already has issue regarding 120% and other zooms for Firefox - see https://github.com/ONLYOFFICE/DocumentServer/issues/765
