### ISSUE TITLE
Cannot unzip cef.7z when building from source

### ISSUE THREAD

**Issue by krosseyed** [ONLYOFFICE/DocumentServer#910]
**Do you want to request a *feature* or report a *bug*?**

This is a bug report

**What is the current behavior?**

When running the automate.py script from the [build tools repository](https://github.com/ONLYOFFICE/build_tools.git), I get an error about cef_binary.7z not being an archive file.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Run the following commands
```
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py server
```

Error Output:
```
7-Zip 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,72 CPUs LE)

Scanning the drive for archives:
1 file, 302 bytes (1 KiB)

Extracting archive: ./cef_binary.7z
ERROR: ./cef_binary.7z
./cef_binary.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
Error (7z): 2
Error (./make.py): 1
```

**What is the expected behavior?**

To complete the installation.

**Did this work in previous versions of DocumentServer?**

Not sure, this is the first time I have tried doing this. I did run the x86 version, but I have a feeling that this is ppc64el specific.

**DocumentServer version:**

Latest from the automated installer script

**Operating System:**

Ubuntu Server 20.04 LTS

**Browser version:**

N/A

**Comment by krosseyed** [comment]
https://github.com/ONLYOFFICE/DocumentServer/issues/897#issuecomment-646696594

**Comment by negroben** [comment]
Verifique los permisos sobre el file cef_binary.7z
