### ISSUE TITLE
 [Spreadsheet] French version of hyperlink formula throw an internal error

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#913]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![bug_escola_1](https://user-images.githubusercontent.com/11867613/85297518-21ebec80-b4a3-11ea-9d1d-4de9533cd554.jpg)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Insert in a cell this formula : 
```
=LIEN_HYPERTEXTE("https://github.com/ONLYOFFICE/CommunityServer/issues/"&B2;"Issue")
```
**What is the expected behavior?**
create an hyperlink
**Did this work in previous versions of DocumentServer?**
i don't know
**DocumentServer version:**
5.5.1

**Operating System:**
Windows 10
**Browser version:**
 Firefox 77.0.1 64 bits

**Comment by Rita-Bubnova** [comment]
Hello, @ydelattre.
I can confirm, this is bug - issue 45690 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/4630b730cee0632d680ce00d876a00de1649705b) in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
