### ISSUE TITLE
Converter docx to png only first page

### ISSUE THREAD

**Issue by Shedevro** [ONLYOFFICE/DocumentServer#915]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Service converts only first docx page to png.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Request data:
```
{
      async: true,
      doctparams: 2,
      codePage: 65001,
      filetype: 'docx',
      outputtype: 'png',
      key: '...',
      url: '...',
}
```
**What is the expected behavior?**

Expect service to convert docx to png image or images.

**Did this work in previous versions of DocumentServer?**
Don't know.

**DocumentServer version:**
5.5

May be it is not implemented feature yet. But how can I do it?
Thanks.

**Comment by ShockwaveNN** [comment]
Try to remove `doctparams: 2` from your request, it should convert all docx pages to  images and store it in zip archive

**Comment by Shedevro** [comment]
@ShockwaveNN 
Thanks for answer.
I have removed `doctparam`
For now it returns png file (because `outputtype` set to `png`?);
Response data:
```
 "data": {
   "fileUrl": "http://onlyoffice/cache/files/conv_a71bcb45-f7d2-49af-93db-f0865ac62d77_png/output.png/output.png?md5=9CUT_OTIugjmJb3W14DlHA&expires=1593098458&disposition=attachment&filename=output.png",
   "percent": 100,
   "endConvert": true
}
```
I supposed to set `outputtype` to `zip`, but it returns -7 error code.

**Comment by ShockwaveNN** [comment]
Try this:
```
{
	"async": false,
	"filetype": "docx",
	"key": "random_key",
	"outputtype": "png",
	"thumbnail": 
	{
		"aspect" : 0,
		"first" : false,
		"height" :3000,
		"width" :2000
	},
	"title": "test.docx",
	"url": "http://example.com/test.docx"
}
```

More info at [documentation](https://api.onlyoffice.com/editors/conversionapi#thumbnail)

**Comment by Shedevro** [comment]
It works! Thanks!

**Comment by ShockwaveNN** [comment]
Glad to hear, I'll close this issue
