### ISSUE TITLE
Images become BLACK BOXES when saving as PDF

### ISSUE THREAD

**Issue by unamundan** [ONLYOFFICE/DocumentServer#916]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Imported / placed images become BLACK BOXES when saving as PDF.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a document. Import / place an image. Download the document as a PDF. Placed images are black boxes.

**What is the expected behavior?**
Placed images are placed images.

**Did this work in previous versions of DocumentServer?**
Unknown

**DocumentServer version:**
OnlyOffice Document Server 0.1.7 with OnlyOffice Nextcloud app 4.3

**Operating System:**
Nextcloud 19.0 running on Ubuntu 18.04.4 LTS

**Browser version:**
Firefox 77.0.1 x64 on macOS 10.13.6

**Comment by unamundan** [comment]
UPDATE: It works using Safari 12.1.1 (13607.2.6.1.2) and Tor 9.5 x64 (based on Mozilla Firefox 68.9.0esr) but there’s a NEW problem. The image is cropped incorrectly, using either of these browsers.

(For privacy, I avoid Chrome.)

**Comment by ShockwaveNN** [comment]
> OnlyOffice Document Server 0.1.7
This is not a version of ONLYOFFICE DocumentServer, this is version of Nextcloud's Community Document Server

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by unamundan** [comment]
Thank you, @ShockwaveNN. I’ve posted there.

**Comment by ShockwaveNN** [comment]
Moving this issue to `onlyoffice-nextcloud` repo to apply tag.
