### ISSUE TITLE
Group cells

### ISSUE THREAD

**Issue by yyelena** [ONLYOFFICE/DocumentServer#917]
**Do you want to request a *feature* or report a *bug*?** feauture

**What is the current behavior?** no feature

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**not a bug

**What is the expected behavior?** group cells : be able to copy the value  automatically to the last adjacent cell with the content opn Onlyoffice.

**Did this work in previous versions of DocumentServer?** no feature

**DocumentServer Docker tag:** 5.5.3

**Host Operating System:** CentOs 7.4

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's not related to Docker

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
