### ISSUE TITLE
Feature Request: Provide support for converting Word document files into HTML

### ISSUE THREAD

**Issue by dmkash** [ONLYOFFICE/DocumentServer#918]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Conversion service does not currently support converting Word document files (.docx) to HTML files.  It would be awesome if this conversion could be supported!

**Did this work in previous versions of DocumentServer?**
Nope!

**DocumentServer version:**
5.5

**Comment by ShockwaveNN** [comment]
Issue created from here:
https://github.com/ONLYOFFICE/DocumentServer/issues/887#issuecomment-650246708

As I mention there
Currently we do not planning to add docx -> html
But  we monitor this issue and if a lot of user request it we think about implementation

**Comment by cxgreat2014** [comment]
some people (like me) need this feature to generate static site from docx

**Comment by gdzhu8023** [comment]
Yes. Hope to support docx -> html .

**Comment by maruacat** [comment]
Hello!
Currently, our editor has successfully implemented the function of converting .docх format to HTML. So I think we can close this issue

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.0.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
