### ISSUE TITLE
Generate thumbnail is blank picture

### ISSUE THREAD

**Issue by cisiqo** [ONLYOFFICE/DocumentServer#921]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Generate jpg thumbnail of docx file, some thumbnail is blank.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The doc file can reproduce the problem. [service startup.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4883202/service.startup.docx)

**What is the expected behavior?**
The thumbnail maybe is the docx file first page.

**Did this work in previous versions of DocumentServer?**
No.

**DocumentServer version:**
5.5.3.39

**Operating System:**
Ubuntu 18.04.4 LTS

**Browser version:**
Google Chrome is up to date
Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by ShockwaveNN** [comment]
Hi

> Generate jpg thumbnail of docx file, some thumbnail is blank.

Am I right and you using [converion API](https://api.onlyoffice.com/editors/conversionapi#thumbnail) to generate thumnail?

Could you attach full list of params of request?

**Comment by cisiqo** [comment]
Yes. The params is
`{
    "filetype": "docx",
    "key": "Khirz6zTPdfd7",
    "outputtype": "jpg",
    "url": "the file url"
}`

**Comment by ShockwaveNN** [comment]
Generated jpg image using your file with such params in Postman:

```
{ 
	"filetype": "docx", 
  	"key": "{{$guid}}", 
	"outputtype": "jpg", 
	"url": "https://github.com/ONLYOFFICE/DocumentServer/files/4883202/service.startup.docx" 
}
```

In result got correct image:

![image](https://user-images.githubusercontent.com/668524/86773907-bbe49500-c05e-11ea-84bc-785fd576791b.png)

Everything is fine with this file I think

**Comment by cisiqo** [comment]
Sooooooo sorry, it's my fault. Thank you very much.
