### ISSUE TITLE
document command service API  find the information about users who are currently editing the document

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/DocumentServer#922]
Hi:
I use document command service API  find the information about users who are currently editing the document，
![20200708172308](https://user-images.githubusercontent.com/11469578/86902095-13a6fd00-c140-11ea-9b90-765c2a5ef257.jpg)
but I just got `{"key":"941430943","error":0}`

**Comment by ShockwaveNN** [comment]
@flaminestone Please take a look
Screenshot from this page:
https://api.onlyoffice.com/editors/faq/coediting#coediting_2

**Comment by flaminestone** [comment]
Hello @cs686. You need to take responce with users data in [callback handler](https://api.onlyoffice.com/editors/callback). It is not clear enough, and I hope, we add more information about it in future

**Comment by cs686** [comment]
@flaminestone thanks, if I want to drop a coediting user,do you have any API to use?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by hasangok** [comment]
Hello @cs686 and @flaminestone,

I got stuck in this exact situation and couldn't figure out how to retrieve actively editing users of a document. Could you please assist me to make proper request? My callback url is: `http://localhost:3000/track?filename=Git_Documentation_v1.docx` and this is from default nodejs app template downloaded from [here](https://api.onlyoffice.com/editors/example/nodejs). I'm using DocServer version 6.4.2.6.

Thanks a lot.

**Comment by ShockwaveNN** [comment]
@hasangok Hi, I'm not qutes sure, never worked with that part of code

But I think as soon as you send something like this:
```
curl --location --request POST 'http://192.168.1.238/coauthoring/CommandService.ashx' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "c": "info",
    "key": "192.168.1.238http___192.168.1.238_example_files_192.168.1.238_new.docx1649681365842"
}'
```
This request should return `error:0` (if you replace key on your key from some document)
and on callback URL there will be data with info

**Comment by ShockwaveNN** [comment]
I think if you run example on Debug or add some logging this event should be received on this line of code:

https://github.com/ONLYOFFICE/document-server-integration/blob/master/web/documentserver-example/nodejs/app.js#L430

**Comment by ShockwaveNN** [comment]
@hasangok Glad I was usefull )
