### ISSUE TITLE
JS error while drag-n-drop on slide list 

### ISSUE THREAD

**Issue by MurphyFENG** [ONLYOFFICE/DocumentServer#923]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I open a presentation file in the mobile browser, a warning will pop up on the page that an error occurred while processing the file.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** 
open a presentation file and touch the screen or slide the screen.

**What is the expected behavior?** 
do not pop up this waring and do not console error in browser console.

**Did this work in previous versions of DocumentServer?**
not sure
**DocumentServer Docker tag:**
5.5.3
**Host Operating System:**
windows chrome phone simulation, Android browser
the server os is Ubuntu 18.4

**Comment by ShockwaveNN** [comment]
This issue should be fixed in https://github.com/ONLYOFFICE/sdkjs/commit/268800525447fef4ec5f7369ee866a5f8322708f and release as v6.0 a long time ago, so I'm closing this issue
