### ISSUE TITLE
what's FontDictionary.h use for?

### ISSUE THREAD

**Issue by fendaq** [ONLYOFFICE/DocumentServer#925]
i found something wrong when i use chinese font，i seems some code in map.js replaced  chinese font index with wrong index,
FontMaps.cpp generate the file "FontDictionary.h"

but in FontMaps.cpp :
int main(int argc, char* argv[])
{
    CApplicationFonts oFonts;
    **oFonts.InitializeFromFolder(L"D:\\onlyoffice_trunk\\fonts\\all");**
    //oFonts.Initialize();

Hard-code the font dir as **D:\\onlyoffice_trunk\\fonts\\all**，so  the generated  file "FontDictionary.h"  may not be fit  with my fonts?

is it a bug？

**Comment by ShockwaveNN** [comment]
You mean this line? 
https://github.com/ONLYOFFICE/core/blob/master/DesktopEditor/freetype_names/FontMaps/FontMaps.cpp#L113

According to @K0R0L - this code used only in development process on developer pc, but we agree that hard coded  paths is not correct

Meanwhile - could you describe problems with your chinese fonts in more details and we take a look at it
