### ISSUE TITLE
Random character disappearing / not rendering while typing

### ISSUE THREAD

**Issue by hibearpanda** [ONLYOFFICE/DocumentServer#926]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
One of our users spotted a bug with the Document Editor.

At times while typing, a certain character will disappear from the current view.

For example:

![image](https://user-images.githubusercontent.com/11482515/87771782-66289d80-c853-11ea-8d33-139986c2aecf.png)
![image (1)](https://user-images.githubusercontent.com/11482515/87771787-6759ca80-c853-11ea-91d3-4294896bd0d1.png)

First screenshot - the character `o` has disappeared.

Second screenshot - the character `a` has disappeared.

Our user has seen this behaviour happen to the following characters at the moment:
- `c`
- `a`
- `o`
- `i`

Resizing the document using the zoom button on the bottom bar fixes the issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Happens randomly so far. Not entirely sure how to replicate.

The user reports that it happens while typing.

**What is the expected behavior?**
We expect the characters to not disappear. :)

**Did this work in previous versions of DocumentServer?**
No idea.

**DocumentServer version:**
We are currently using OnlyOffice Developer Edition 5.5.3 (Docker version).

**Operating System:**
Docker Version

**Browser version:**
Chrome Version 81.0.4044.129 (Official Build) (64-bit) on Windows 10

**Comment by adamaiken89** [comment]
Our side encountered a similar issue either. I think it is a quite serious bug.

**Comment by cpot** [comment]
Duplicate : https://github.com/ONLYOFFICE/DocumentServer/issues/709

**Comment by hibearpanda** [comment]
Thanks @cpot .
