### ISSUE TITLE
Setting default document and spellcheck language (Nextcloud)

### ISSUE THREAD

**Issue by nooblag** [ONLYOFFICE/DocumentServer#927]
**Do you want to request a *feature* or report a *bug*?**
Possible bug report.

**What is the current behaviour?**
I’m running Nextcloud 19.0.1 with OnlyOffice.

I have the following options set in `/var/www/nextcloud/config/config.php`:

```
  'default_locale' => 'en_AU',
  'force_locale' => 'en_AU',
  'default_language' => 'en',
  'force_language' => 'en',
```

And I have the following set in `/var/www/onlyoffice/documentserver/web-apps/apps/api/documents/api.js`:

```
DocsAPI.DocEditor.defaultConfig = {
        type: 'desktop',
        width: '100%',
        height: '100%',
        editorConfig: {
            lang: 'en',
            region: 'en-AU',
            canCoAuthoring: true,
            customization: {
                about: true,
                feedback: false
            }
        }
    };
```

But I notice that when I create a new .docx file inside Nextcloud and open it with OnlyOffice, the default language is English (United States), despite the above configs.

**What is the expected behaviour?**
Default spellcheck language and document language for new files is English (Australian) *not* English (United States)

**Did this work in previous versions of DocumentServer?**
Unsure

**DocumentServer version:**
Document Editor 5.5.3

**Operating System:**
Ubuntu 18.0.4

**Comment by ShockwaveNN** [comment]
> Default spellcheck language and document language for new files is English (Australian) not English (United States)

According to [documentation](https://api.onlyoffice.com/editors/config/editor#region) `region` is not for setting up spellchecker language
> Defines the default display format for currency and date and time (in the Spreadsheet Editor only).

Document language is stored in document itself, you could create new empty document with en-AU language and replace empty new documents
