### ISSUE TITLE
Secruity Issue - Cookies and Passwords for Excel Files

### ISSUE THREAD

**Issue by SaschaMuehl** [ONLYOFFICE/DocumentServer#928]
Hi,
I am using ONLYOFFICE in NextCloud and everything works so far. Thanks for the great product.
The only issue I came across is when I use a password locked Excel file. 

Expected behavior: On clicking the link to the excel file it should be asked every time for the password. Every time I update the link it should be asked for the password.

But, once I typed in the password in the excel file is shown in blank characters after updating the link in the same browser. (Imagine you access the file in a public PC and the psw is saved in the cookies or some where else)  

Is there a possibility to solve this security issue?

**Comment by ShockwaveNN** [comment]
Seems this issue is not related to nextcloud, but for DocumentServer

To be clear - could you specify version of DocumentServer and Nextcloud your using, installation method and host's operation system

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
