### ISSUE TITLE
Error 403 [reason phrase] Forbidden during healtcheck from owncloud

### ISSUE THREAD

**Issue by mbaesso** [ONLYOFFICE/DocumentServer#929]
Hi,
after upgrade owncloud EE to 10.3.2 and deploy new Onlyoffice connector 4.0.1 we receive an http response 403 during check as below:

Client error response [url] https://servizionline.aifa.gov.it/documentserver/cache/files/conv_check_1309080636_docx/output.docx/output.docx?md5=n6V5wivCuFsyQEeeA3O_nw%3D%3D&expires=1578587175&disposition=attachment&ooname=output.docx [status code] 403 [reason phrase] Forbidden

we see generated file correctly inside cache.
how we can debug this problem? could you please let us know if there are any incompatibilities with onlyoffice documentserver Integration edition 5.1.5?
how we can trace api call from plugin in order to analyze problem?

thanks
Mirko Baesso

**Comment by ShockwaveNN** [comment]
Hi @fireraiserDE 

Could you specify your ownCloud + DocumentServer setup?
Versions of product
Installation Method
Server OS's

**Comment by fireraiserDE** [comment]
> Hi @fireraiserDE
> 
> Could you specify your ownCloud + DocumentServer setup?
> 
> Versions of products
> Installation Method
> Server OS's

**fireraiserDE** is currently on vacation.  ;-)
I'll report when I am back in the office.

**Comment by Alain75006** [comment]
Hi there,
I have exactly the same issue, did you track any solution for this problem ?
Thanks a lot

**Comment by Alain75006** [comment]
Hi,
Is there anybody that found a solution to this issue.
No more expert from Onlyoffice, it's toobad, I was really pleased using this Office solution until a crash forced me to re create a new server, before that I had no problem using it...
Help !

**Comment by OdairTrujillo** [comment]
Hi, I don't know if you are running onlyoffice with docker or with a package system, but I have this tutorial that covers the whole installation and configuration process, including the part of the token that it is your problem maybe, like was mine.

[Check it out](https://odair.dev/es/posts/2020-12-onlyoffice-owncloud/), it is written in spanish language, but I think that you will find it useful. Tell as what you find. 

Maybe the debconf settings fits to similar settings in the docker config file.

**Comment by julyusito** [comment]
Same error here

**Comment by ondrejlohnisky** [comment]
same here

**Comment by ondrejlohnisky** [comment]
Ok i found solution for me. 
The problem was maybe incorrect configuration but even when i did it 4x times the way it should, nothing helped. Only removing the error from Nextcloud database:
`delete from oc_appconfig where appid='onlyoffice' AND configkey ='settings_error';`
GL HF

**Comment by alexanderonlyoffice** [comment]
Issue is closed as the solution of the initial problem was introduced in version 5.3.1.
