### ISSUE TITLE
Unable to edit/add formatting presets 

### ISSUE THREAD

**Issue by phonon112358** [ONLYOFFICE/DocumentServer#931]
I have onlyoffice-documentserver 5.5.1 installed on Debian 10, and (on the same machine) nextcloud 18.0.4 with the onlyoffice app 4.1.4.

So far, everything works well. 
However, somehow I am missing the default presets for headings (https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/UsageInstructions/FormattingPresets.aspx). 
![2020-05-03 at 17-37-55](https://user-images.githubusercontent.com/22647281/80918617-372b8100-8d66-11ea-95c2-53d2ff67dad2.png)
I also tried to add them manually as described in the article linked above (right click on a formatted text -> Formatting as Style -> Create new Style). But, unfortunately nothing changes in the list. 
I need them for creating a table of contents...

Furthermore, it seems to me that I can't edit any existing formatting preset/style...

Does anyone have an idea what I need to do?
Or is it a bug?

**Comment by ShockwaveNN** [comment]
Hi, seeems your empty documents, which used for creating new documents somehow changed

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
