### ISSUE TITLE
Error message:"Track MustSave error: Client error response - shown after editing/saving a document in OnlyOffice

### ISSUE THREAD

**Issue by ravi-mrk** [ONLYOFFICE/DocumentServer#932]
Installed latest versions of owncloud server and OnlyOffice document server. Both are on docker installations. Able to open and edit documents in OnlyOffice but unable to save changes and make them available for other collaborators.

This error is being shown:
{"reqId":"0on0nXkGI4ihTqPbDjV6","level":3,"time":"2020-05-04T13:33:37+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xyz","app":"onlyoffice","method":"POST","url":"\/apps\/onlyoffice\/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJyYXZpa20iLCJvd25lcklkIjoicmF2aWttIiwiZmlsZUlkIjoyMjQxTYSTDKCUGF0aCI6IlwvRG9jdW1lbnQxLmRvY3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.ulIbwZ-xd891A4A4PuzQby_BFUqoAWok6OIuSb-YSYM","message":"Track MustSave error: Client error response [url] https:\/\/abc.example.com\/cache\/files\/4236335616_5829\/output.docx\/output.docx?md5=pY-tPvuOW2W6BDUXNSyMoOQ%3D%3D&expires=1588600118&disposition=attachment&ooname=output.docx [status code] 403 [reason phrase] Forbidden"}

The jwt is currently blank. Also, I am able to successfully curl the document server and the owncloud server URLs without any issues.

Any fix for this?

**Comment by LinneyS** [comment]
#929
