### ISSUE TITLE
I installed onlyoffice by docker and where is the default.json?

### ISSUE THREAD

**Issue by FEliuze** [ONLYOFFICE/DocumentServer#935]
Hello!Help!Where is default.json?
My install-command is "sudo docker pull onlyoffice/documentserver"
My run-command is "sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver"
There is no onlyoffice in /etc/
I tried to find it in docker containers but aoso failed...

**Comment by ShockwaveNN** [comment]
Please stop spamming, this is 4th issue with same question
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/266
