### ISSUE TITLE
🐞: Context menu does not show up on hitting menu key

### ISSUE THREAD

**Issue by joe733** [ONLYOFFICE/DocumentServer#937]
**Do you want to request a *feature* or report a *bug*?**
A Bug.

**What is the current behaviour?**
The menu key in the keyboard (en-US layout) does no open context menu.

![photo_2020-07-29_12-35-45](https://user-images.githubusercontent.com/38415384/88768075-28533f80-d198-11ea-8903-752914ed0331.jpg)

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Type in `opensource`.
2. Obviously red underline shows up.
3. To change it to `open-source` I'm forced to use mouse right click.

**What is the expected behaviour?**
The menu key opens the context menu.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

- Office: ONLYOFFICE Desktop Editors version 5.5.1.78
- OS: elementary OS 5.1.6 Hera

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer, since problem actual there and it's our base product

**Comment by joe733** [comment]
Thanks for the response and fix.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
