### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by Tachi107** [ONLYOFFICE/DocumentServer#946]
This kinda is both a feature request and a bug report. I just installed the DocumentServer on my Nextcloud machine (yes, same server for both), and I couldn't complete the setup because of an error when trying to set the DocumentServer address in the Nextcloud settings, as I kept getting the "Error while downloading the document file to be converted" error. 
After reading the logs at `/var/log/onlyoffice/documentserver/docservice/out.log` (`[ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672`) and `/var/log/onlyoffice/documentserver/converter/out.log` (`[ERROR] nodeJS - error downloadFile:url=https://nextcloud.mydomain.com/apps/onlyoffice/empty?doc=eyJ0eXAiOyaddayadda;attempt=3;code:EPROTO;connect:null;(id=conv_check_2037244900_docx)`, `Error: write EPROTO 140395977918272:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 70`), i tried disabling TLSv1.3 in nginx's `ds.conf`, and everything started working. 
I enabled TLS 1.3 'cause it is faster and more secure than TLS 1.2, and I did it without thinking much about it. 
How hard would it be to enable TLS 1.3 support for the DocumentServer? Does it even needs to be supported by OnlyOffice or that's up to its dependencies (rabbitmq, postgresql...)?

Thanks a lot for this awesome product! <3

DocumentServer version: 5.6.1-6, Debian package
Operating System: Debian 10 Buster

**Comment by ShockwaveNN** [comment]
Hi, did you enable tls in global nginx config?
I'm not 100% sure, but I think it's not enabled by default in 
```
# cat /etc/nginx/nginx.conf | grep ssl_protocols
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
```

**Comment by Tachi107** [comment]
Yep, I enabled it, it wasn't on by default. That's a thing I usually do when I can, given the benefits, and since there wasn't a warning anywhere I removed old ssl and tls protocols and enabled only TLS 1.3

**Comment by ShockwaveNN** [comment]
@Tachi107 Sorry, not quite follow your message - after you enabled TLS 1.3 in `/etc/nginx/nginx.conf` everything work fine? Or there is troubles?

**Comment by Tachi107** [comment]
I enabled TLS 1.3 in `/etc/onlyoffice/documentserver/nginx/ds.conf` (same file as `/etc/nginx/conf.d/ds.conf`). The `ds.conf` that I modified was a copy of `/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl`.
I enabled TLS 1.3 before connecting the DocumentServer to Nextcloud, and I had problems. Disabling TLS 1.3 was the solution to the issue.

**Comment by Tachi107** [comment]
Can you replicate the issue?
I think that the problem is that one of the DocumentServer's dependencies, `rabbitmq-server`, does not support TLS 1.3 on Debian 10, because `rabbitmq-server` depends on various `erlang` packages, that on Debian are stuck at version `21.2.x`, and, as far as I can tell, erlang supports TLS 1.3 only from version 22 and above.
erlang 22 is available on Ubuntu Eoan (19.10) and above... I'm going to check if on that Ubuntu version the issue is still present, I'll let you know!

**Comment by Tachi107** [comment]
Yes, the issue seems to go away using Ubuntu Focal with `erlang` 22... Nice!
Sorry for opening this. 
Still, I think that we should add a warning in `/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl` saying that `TLSv1.3` is not supported if the `erlang` version packaged by your distribution is older than version 22, that would save a lot of headaches to people like me!

Thanks again for OnlyOffice, it's just awesome.

**Comment by ShockwaveNN** [comment]
Thank you for your time to check this issue.
I don't think it's a good idea to add comments in `ds-ssl.conf.tmpl` since only TLSv1.2 is hard-coded

I think this issue will be best documentation if anyone find it

**Comment by fictitiousexistence** [comment]
Hi, I am getting this same issue/ error with tls 1.3 and erl 23.

`107:14)
e:url=https://nc.server.com/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ooUG3IWORkbNhvvUTtxycpBdTD_AO8lJHLIJs4D8g64;attempt=1;code:EPROTO;co>
nes:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL **alert number 70`**

Erl version is 23 `Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:5:5] [ds:5:5:10] [async-threads:1] [hipe]`

OS: Arch Linux

Thanks.

**Comment by ShockwaveNN** [comment]
@fictitiousexistence Hi

> Yes, the issue seems to go away using Ubuntu Focal with erlang 22... Nice!

This those on Ubuntu, but you're using Arch Linux, maybe it's some kind Arch specific error? 
Since we do not have official Arch support, maybe Arch community and\or creator of Archa package have some info?
