### ISSUE TITLE
When will the pivot table be available in Community Edition?

### ISSUE THREAD

**Issue by VivienZhai** [ONLYOFFICE/DocumentServer#947]
Will the pivot table be available in Community Edition?  If possible，when will the function be available in Community Edition?

**Comment by Rita-Bubnova** [comment]
Hello, @VivienZhai.
Unfortunately, at the moment we are not planning to add this functionality to Community Edition.
As for commercial builds, it will appear in next major release.

**Comment by VivienZhai** [comment]
Thanks for your reply.

**Comment by ShockwaveNN** [comment]
I'll close this issue, if you got any other question - please comment or create new issue
