### ISSUE TITLE
Disable TLS 1.0 and TLS 1.1 in default nginx ssl config

### ISSUE THREAD

**Issue by kleener** [ONLYOFFICE/DocumentServer#949]
I would prefer to disable TLS 1.0 and TLS 1.1, this should increase security. It would be possible to store the config of the nginx outside of the container. You can also adjust the log format and remove the IPs, which increases data protection.

**Comment by kleener** [comment]
Thank you, that's great :-)

**Comment by kleener** [comment]
I think I can close the ticket.
I just checked with SSL Labs, 1.0 and 1.1 are disabled.

**Comment by ShockwaveNN** [comment]
I'm not sure, we still have 1.0 and 1.1 in default configs 
https://github.com/ONLYOFFICE/document-server-package/blob/master/common/documentserver/nginx/ds-ssl.conf.tmpl.m4#L44

And devs said nothing to me about fixing it, I'll remind them and reopen this issue until we got some specific news

**Comment by ShockwaveNN** [comment]
This issue if fixed in https://github.com/ONLYOFFICE/document-server-package/commit/9ebae802c85547b844d8a67699dbf97b69fc3525

And will be released as v7.1.0

**Comment by ShockwaveNN** [comment]
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles
