### ISSUE TITLE
open a file and show 'txt option'

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/DocumentServer#950]
Hi, when I open a doc sometimes show this, why this happen, and how to avoid this, thanks
![image](https://user-images.githubusercontent.com/11469578/89761345-baf0c880-db20-11ea-9ec6-58ae33329c69.png)

**Comment by ShockwaveNN** [comment]
Seems you're trying open not a document, looks like eml or some other type

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by hehaoNo1** [comment]
help，same request，do not konw why？
