### ISSUE TITLE
Caption does not contain chapter number if checked

### ISSUE THREAD

**Issue by kernie** [ONLYOFFICE/DocumentServer#951]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Caption does not contain chapter number
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I add a caption to an image and check the option to include chapter number in label. The label in chapter 3 then is Figure 0-1, which should be 3-1.
**What is the expected behavior?**
Chapter number should be included
**Did this work in previous versions of DocumentServer?**
Don't know
**DocumentServer version:**
5.6.2
**Operating System:**
Ubuntu 20.04
**Browser version:**
Firefox

**Comment by kernie** [comment]
Just figured out that adding another figure does not lead to an increment of the label number (see image)
![Bildschirmfoto 2020-08-10 um 18 27 10](https://user-images.githubusercontent.com/23321751/89806316-247bd180-db37-11ea-8582-eacdb1f3507c.png)

**Comment by matveevms** [comment]
Hello, @kernie.
Could you attach file with problem?

**Comment by kernie** [comment]
[TeileDokument.docx](https://github.com/ONLYOFFICE/DocumentServer/files/5058022/TeileDokument.docx)

**Comment by matveevms** [comment]
@kernie , Thank you for the file.
This feature does not work unless numbering or a multilevel list is applied. For example, to include a title number in caption, apply a numbered list to the chapter number as in the attached document.
[TeileDokument (1).docx](https://github.com/ONLYOFFICE/DocumentServer/files/5061999/TeileDokument.1.docx)

**Comment by kernie** [comment]
I see. So I propose to grey out the option to include the chapter number, unless the chapters are created with numbering?

**Comment by matveevms** [comment]
This function is implemented by analogy with MS Word
