### ISSUE TITLE
INDEX function does not return a range inside SUMPRODUCT

### ISSUE THREAD

**Issue by Excali78** [ONLYOFFICE/DocumentServer#955]
Thé INDEX function should return a range when the row or column parameter is set to zero or omitted.

In the attached file, the behavior of the INDEX function used alone in an array formula seems correct when the column parameter is set to zero (G20:I20). It is not correct when the column parameter is omitted (G19:I19).

If we try to use the INDEX function in the array mode inside a SUMPRODUCT function (which is a hidden array formula in EXCEL), the SUMPRODUCT function returns a #NUMBER error (J2:J4 ans J9:J11). It should return L2:L4 and L9:L11 results.

I use DesktopEditors 5.5.1 on Windows 10. The problem was the same with a previous versions.
BTW, the FORMULATEXT() function applied on an array formula should add braces arround the text result as in EXCEL.
[TestBook.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/4642707/TestBook.xlsx)

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer, since it's our base product and issue actual there too

**Comment by Rita-Bubnova** [comment]
Issue 45387 and 45388 fixed  (https://github.com/ONLYOFFICE/sdkjs/commit/af4272af9d0ac20ffb5ea6553a6c9e02b7d0abd3, https://github.com/ONLYOFFICE/sdkjs/commit/2df6cc4729eee6589f1754f5973fdfbf7cbea778) in future major release.
But there is a problem with the evaluation of the function "= FORMULATEXT (M20)" in cell M22 (issue 46180 in our private issue tracker).

**Comment by Rita-Bubnova** [comment]
> But there is a problem with the evaluation of the function = FORMULATEXT (M20) in cell M22 (issue 46180 in our private issue tracker).

This problem fixed (https://github.com/ONLYOFFICE/sdkjs/commit/6e9fcb42d920235c307f3d5fd8247b8528b38909)  in future major release.

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
