### ISSUE TITLE
Different line length in OO and Word

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#956]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
**What is the current behavior?**
When opening the attached .docx document in OO and Word, the length of the lines is different.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce, open the attached document in OO and Word.
**What is the expected behavior?**
The appearance of the .docx file should be the same in both softwares.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.4.2
[test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/4394261/test.docx)

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.
