### ISSUE TITLE
  Spreadsheet preview questions

### ISSUE THREAD

**Issue by xzxiangzml** [ONLYOFFICE/DocumentServer#962]
The composite pie chart does not display extended content. The radar map was not resolved. There is no trend line in scatter plot, and bubble in bubble chart is not bubble

**Comment by Rita-Bubnova** [comment]
Hello, @xzxiangzml.
Could you create new issues for each problem / question? 
Please attach files to demonstrate the problem.

**Comment by ShockwaveNN** [comment]
Thank you for creating separate issues.
I'll close this one
