### ISSUE TITLE
Onlyoffice Cluster With Community document server 5.6.3

### ISSUE THREAD

**Issue by tanguy-opendsi** [ONLYOFFICE/DocumentServer#970]
hi, we use Onlyoffice document server  5.4.1-39 100 on cluster 
Sharing the same psql, same rabbit and same redis.
And it's work fine.
But if we upgrade to 5.6 the cluster is not working when we edit files on 2 différents nodes.
And redis looks like not used anymore on  Onlyoffice document server (5.6)  but is used with  Onlyoffice document server integration édition ?

Clustering with community server is still available on 5.6 Onlyoffice ? 

Best regards

**Comment by ShockwaveNN** [comment]
> Onlyoffice document server 5.4.1-39 100 on cluster

Hi, could you point out to instruction and\or more detail explanation how did your cluster was setup

**Comment by tanguy-opendsi** [comment]
Ok,
We have : 
In front 1 haproxy "roundrobin mode with cookies" 
3 onlyoffices Nodes
1 redis
1 postgresql
3 rabbitmq (HA MODE) 

We use it whis nextcloud app 
When we used  5.4.1-39 cluster we can edit files on 2 différents node onlyoffice-1 and onlyoffice 2 

But when we use 5.6 we only can edit files when we are on same nodes.

The only différence i found it's onlyoffice on 5.6 did not use redis anymore (No key found) 

When 5.4 is use  we founds keys named ds:XX for exemple ds:editorconnections. 

 does version 5.6 work in a cluster?

Why 5.6 is not unsing redis ?  

When we use documentserver-ie (Integration edition) redis is used and the cluster work. 

It is a bug ?

**Comment by ShockwaveNN** [comment]
> does version 5.6 work in a cluster?

As far as I know we never supported this mode officially (But I may be wrong)

> Why 5.6 is not unsing redis ?

We simplify requirements for our basic version

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN 
Ok thx for your reply, and i think redis was used by cluster ;)

**Comment by ShockwaveNN** [comment]
> Maybe you can ré-introduce redis inside your basic version

Sorry, I don't think so
It was a decision of sales team, so you just contact sales@onlyoffice.com for detailed explanation
This question is out of my responsibilities

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN  Thx for your reply. 
Have good day :) 
I close the ticket 
Best regards
