### ISSUE TITLE
Logrotate config on centos7 is generating annoying output

### ISSUE THREAD

**Issue by Linuxfabrik** [ONLYOFFICE/DocumentServer#972]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Logrotate config on centos7 is generating annoying output:
`/etc/cron.daily/logrotate:`
`Redirecting to /bin/systemctl restart supervisord.service`

This is because the config is using `service` instead of `systemctrl` to restart the daemon.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
No output

**Did this work in previous versions of DocumentServer?**
No. Previous configuration of logrotate was faulty in general. Daemon `supervisord` was misspelled.

**DocumentServer version:**
5.6.3

**Operating System:**
CentOS7

**Browser version:**
Doesn't matter

**Comment by ShockwaveNN** [comment]
Hi, thank you for noticing

I've create an 46447 issue in our private issue tracker

**Comment by ShockwaveNN** [comment]
Hi, this issue if fixed at https://github.com/ONLYOFFICE/document-server-package/pull/126

And will be available in next major release (presumable 6.1.0)

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors 6.1 is released. This issue should be fixed
