### ISSUE TITLE
sync presenter slideshow with viewers 

### ISSUE THREAD

**Issue by sfalihi** [ONLYOFFICE/DocumentServer#974]
does onlyoffice 'presentation' have the ability to sync presenter slideshow with other viewers?
it can be useful e.g. in `virtual classroom`.(students can see which slide the presenter is teaching...).
if it has chat-room already, why not to have sync slideshow?

extra: what about presenter 'voice'?

**Comment by Rita-Bubnova** [comment]
Hello, @sfalihi.
I'm not sure I understand you correctly.
Could you describe in more detail what is needed or give an example application where this is implemented?

Could you try out Presenter View (more [here](https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Presentation-Editor/UsageInstructions/PreviewPresentation.aspx)) , maybe it's what you want?

**Comment by sfalihi** [comment]
i know onlyoffice doesnt use WOPI. but wopi has something called 'Broadcast' view.
`Broadcast
A broadcast is a special Office for the web scenario where navigation through a document is driven by one or more presenters. A set of attendees can follow along with the presenter remotely.`

so my question is, you have something called Presenter-VIew. what about attender-View? can attender see presenter navigations?

**Comment by Rita-Bubnova** [comment]
> so my question is, you have something called Presenter-VIew. what about attender-View? can attender see presenter navigations remotely?

We are not planning to do that.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
