### ISSUE TITLE
how to apply system installed fonts to onlyoffice

### ISSUE THREAD

**Issue by semdy** [ONLYOFFICE/DocumentServer#977]
**Do you want to request a *feature* or report a *bug*? no**

**What is the current behavior? not work when apply with a system installed font**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior? use system fonts to onlyoffice**

**Did this work in previous versions of DocumentServer? no**

**DocumentServer version: 4.3.0**

**Operating System: win 10**

**Browser version: chrome 83**

Now, i can get the system installed fonts, but when apply one of it, webapps does not work.

**Comment by ShockwaveNN** [comment]
> DocumentServer version: 4.3.0

Are you sure you're using ONLYOFFICE DocumentServer, not Nextcloud's Community Document Server?

If you're using ONLYOFFICE DocumentServer, please update to latest release, v4.3.0 is very old, current is v5.6.3 and try to generate fonts data by [instruction](https://helpcenter.onlyoffice.com/server/linux/document/install-fonts.aspx)

**Comment by semdy** [comment]
How to apply sytem installed fonts from Windows/Fonts for online web-apps, like DesktopEditor, without generate fonts data by instruction.  Because loading too many font files can affect page loading speed.

**Comment by semdy** [comment]
I made a misstake, my current DocumentServer version is 5.5.3.
How to apply sytem installed fonts from Windows/Fonts for online web-apps, like DesktopEditor, without generate fonts data by instruction. Because loading too many font files can affect page loading speed.

**Comment by semdy** [comment]
I made a mistake, my current DocumentServer version is 5.5.3.
How to apply sytem installed fonts from Windows/Fonts for online web-apps, like DesktopEditor, without generate fonts data by instruction. Because loading too many font files can affect page loading speed.

**Comment by ShockwaveNN** [comment]
> How to apply sytem installed fonts from Windows/Fonts for online web-apps, like DesktopEditor, without generate fonts data by instruction. 

There is only one way to do that and it's described in instructions

**Comment by semdy** [comment]
Sorry to trouble you. Is there a quick way switch render text to canvas's own font rendering?

**Comment by ShockwaveNN** [comment]
> text to canvas's own font rendering

Do not fully understand that you mean, some example would help, but in general - I don't think so, there is no alternative font rendering engines

**Comment by semdy** [comment]
As we konwn, onlyoffice SDK renders text as a bitmap by generated fonts data, we want render text with canvas "fillText" API.
