### ISSUE TITLE
nginx configuration rewrites address using client gateway not host

### ISSUE THREAD

**Issue by Soraphiroth** [ONLYOFFICE/DocumentServer#978]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when rewriting the address nginx uses `$the_host` which contains the client gateway, not the server hostname/IP. When Nextcloud tries to open a file with the document server it just creates a blank page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Fresh install of Document Server 5.6.3 using onlyoffice-documentserver rpm. Then connect to http(s)://servername (works as intended when typing directly http(s)://servername/welcome).

the three rewrite in `/etc/nginx/includes/ds-docservice.conf` are wrong:
```
#welcome page
rewrite ^/$ $the_scheme://$the_host/welcome/ redirect;

#support old version
rewrite ^\/OfficeWeb(\/apps\/.*)$ $the_scheme://$the_host/5.6.3-2/web-apps$1 redirect;

#script caching protection
rewrite ^(\/web-apps\/apps\/(?!api\/).*)$ $the_scheme://$the_host/5.6.3-2$1 redirect;
```

**What is the expected behavior?**
It should be `$this_host` instead of `$the_host`

**DocumentServer version:**
5.6.3

**Operating System:**
CentOS 8

**Comment by ShockwaveNN** [comment]
@agolybev could you look into this issue, I'm no good at nginx configs

**Comment by igwyd** [comment]
Hello, @Soraphiroth 
I can't to reproduce your error, in my case documents are opened correctly in onlyoffice-documentserver. Please provide more information. Are you running Onlyoffice-documentserver and Nextcloud on the same or different servers? How do you installed the Nextcloud (rmp, docker etc.). Attach settings onlyoffice-integration application in Nextcloud.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
