### ISSUE TITLE
Kubernetes yaml files for onyoffice 2 pods

### ISSUE THREAD

**Issue by viju2008** [ONLYOFFICE/DocumentServer#981]
Hello,

We need to deploy only office on a kuberneted cluste wirh 2 pods. We request to provide sample kubernetes yaml files which we will modify further

We would like to keep logs , data and postgre data outside the container and mount it from Persisten volume claims. Also provide the pvc part of it

We are doing in our own setup and not on cloud

**Comment by ShockwaveNN** [comment]
I'm not any good at Kubernetes, so if anyone willing to help - please welcome

**Comment by viju2008** [comment]
Anyone can help

**Comment by ShockwaveNN** [comment]
We released sample k8s examples
https://github.com/ONLYOFFICE/Kubernetes-Docs
