### ISSUE TITLE
how to hidden some menu on toolbar 

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/DocumentServer#984]
![image](https://user-images.githubusercontent.com/11469578/92586879-6ed4a780-f2c9-11ea-9d29-f404a8417292.png)
hi, I want to hidden the menu with some parameters on this toolbar, is there any api to control the toolbar, thanks

**Comment by ShockwaveNN** [comment]
Hi, there is no public api to disable some of tabs and I don't htink it's a good idea just to hide some panel

Could you describe your usercase, why you need that?

**Comment by cs686** [comment]
we want some documents to somebody approval ,but don't want them edit, just comment. So we develop an approval button in plugins tab, and set the document config {edit: false}, but the toolbar hidden also. We want the plugins tab still show

**Comment by ShockwaveNN** [comment]
Are you considering using [review](https://api.teamlab.info/editors/config/document/permissions#review) mode?
Or disable `edit` and allow only comments via [this](https://api.teamlab.info/editors/config/document/permissions#comment) param?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
