### ISSUE TITLE
No icon for change uppercase and lowercase text

### ISSUE THREAD

**Issue by maravento** [ONLYOFFICE/DocumentServer#987]
There is no icon to change uppercase and lowercase text (like in MS Word)

In MS word 2010
![Captura de pantalla -2020-09-10 09-36-07](https://user-images.githubusercontent.com/14880802/92748037-62446380-f34a-11ea-8b72-9f121f8f505f.png)

In MS word 2016-2019
![changecase_icon_word](https://user-images.githubusercontent.com/14880802/92749670-f400a080-f34b-11ea-8785-df85c4e3d53d.jpg)

In ONLYOFFICE Desktop Editors version 5.6.4.20
![Captura de pantalla -2020-09-10 09-47-05](https://user-images.githubusercontent.com/14880802/92748288-9b7cd380-f34a-11ea-9b21-2fc7f616006f.png)

PD: I apologize for opening this issue in the wrong place (it is a DesktopEditors issue and not a Document Server issue)

Thanks in advanced

**Comment by Rita-Bubnova** [comment]
Hello, @maravento.
Seems to be a duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/991.
