### ISSUE TITLE
Why the docx content 十二 convert to 12.

### ISSUE THREAD

**Issue by ohmyheartbeat** [ONLYOFFICE/DocumentServer#990]
I Upload word file, with section one, two... in onlyoffice review then show : source file is 十二 , but the broswer is 12.
how can i fix it？

**Comment by Rita-Bubnova** [comment]
Hello, @ohmyheartbeat.
Could you attach file demonstrating problem?

**Comment by ohmyheartbeat** [comment]
<img width="1119" alt="图片" src="https://user-images.githubusercontent.com/31534021/92882493-900cd380-f442-11ea-84fc-4c2f711accb9.png">

**Comment by ohmyheartbeat** [comment]
you can see the picture,left is in onlyOffice,right is source file.

**Comment by Rita-Bubnova** [comment]
This is know issue 44723 in our private issue tracker.
Issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/19a220be8a045b591ea24535a347f61b2a919380) in future major release.

**Comment by Rita-Bubnova** [comment]
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/734.
