### ISSUE TITLE
502 bad Gateway (Document server .deb 5.6)

### ISSUE THREAD

**Issue by bastiencyr** [ONLYOFFICE/DocumentServer#992]
Hey, 
I tried in January to install Document server for Nextcloud but it was a failed. Now, I have configured a subdomain of my main domain (onlyoffice.mydomain.fr) and try to install Onlyoffice. All installation is OK. But I have a 502 bad gateway error. 
In Nginx log, it said that it cant connect to live upstream : 
`  *40 connect() failed (111: Connection refused) while connecting to upstream, client: 0.0.0.0, server: onlyoffice.asso-psi.mydomain.fr, request: "GET /welcome/ HTTP/2.0", upstream: "http://[::1]:8000/welcome/", host: "onlyoffice.mydomain.fr"
`
I have many errors with supervisor too :  
```
2020-09-11 18:24:12,781 INFO exited: spellchecker (exit status 127; not expected)
2020-09-11 18:24:12,782 INFO gave up: spellchecker entered FATAL state, too many start retries too quickly
2020-09-11 18:24:12,782 INFO exited: metrics (exit status 127; not expected)
2020-09-11 18:24:12,783 INFO gave up: metrics entered FATAL state, too many start retries too quickly
2020-09-11 18:24:12,784 INFO exited: converter (exit status 127; not expected)
2020-09-11 18:24:12,784 INFO exited: converter (exit status 127; not expected)
2020-09-11 18:24:12,785 INFO gave up: converter entered FATAL state, too many start retries too quickly
2020-09-11 18:24:12,785 INFO gave up: converter entered FATAL state, too many start retries too quickly
2020-09-11 18:24:12,787 INFO exited: docservice (exit status 127; not expected)
2020-09-11 18:24:13,789 INFO gave up: docservice entered FATAL state, too many start retries too quickly
```
In my ds.conf, I put the secure configuration (with port 443) and generate certificate with cerbot. I put my subdomain in ds.conf

Thanks for helping !!!

**Comment by ShockwaveNN** [comment]
Moved this issue to DocumentServer repo

Could you see which errors caused all services to restart at `/var/log/onlyoffice/documentserver`

**Comment by bastiencyr** [comment]
Thanks for your response 

> Could you see which errors caused all services to restart at `/var/log/onlyoffice/documentserver`
In `/var/log/onlyoffice/documentserver/nginx.error.log`

`2020/09/12 09:56:34 [error] 7901#7901: *4194 no live upstreams while connecting to upstream, client: 0.0.148.173, server: onlyoffice.mydomain, request: "GET /favicon.ico HTTP/2.0", upstream: "http://docservice/favicon.ico", host: "onlyoffice.mydomain.fr"`

In  `/var/log/onlyoffice/documentserver/docservice/out.log`
```
supervisor: couldn't chdir to /var/www/onlyoffice/documentserver/server/DocService/sources/: ENOENT
supervisor: child process was not spawned
```
In  `/var/log/onlyoffice/documentserver/spellchecker/out.log`
```
supervisor: couldn't chdir to /var/www/onlyoffice/documentserver/server/SpellChecker/sources/: ENOENT
supervisor: child process was not spawned
```
I have same errors in metric, gc and converter.

**Comment by ShockwaveNN** [comment]
That are permissions for
```
ls -la /var/www/onlyoffice/documentserver/
```
Correct one are:

```
root@295dcb077bf7:/# ls -la /var/www/onlyoffice/documentserver/
total 120
drwxr-xr-x  1 ds   ds    4096 Sep  5 01:44 .
drwxr-xr-x  1 root root  4096 Sep  5 01:44 ..
-rw-r--r--  1 ds   ds    5315 Sep  5 01:24 3rd-Party.txt
drwxr-xr-x 40 ds   ds    4096 Sep  5 01:43 core-fonts
drwxr-xr-x  1 ds   ds   36864 Sep  5 06:10 fonts
drwxr-xr-x  2 ds   ds    4096 Sep  5 01:43 license
-rw-r--r--  1 ds   ds   10759 Sep  5 01:24 LICENSE.txt
drwxr-xr-x  2 ds   ds    4096 Sep  5 01:43 npm
drwxr-xr-x  1 ds   ds    4096 Sep  5 01:43 sdkjs
drwxr-xr-x  1 ds   ds    4096 Sep  5 06:09 sdkjs-plugins
drwxr-xr-x  1 ds   ds    4096 Sep  5 01:43 server
drwxr-xr-x  1 ds   ds    4096 Sep  5 01:43 web-apps
```

That OS are you using and that instruction do you use to install DocumentServer?

**Comment by bastiencyr** [comment]
Oh... Niiice... You are good. 
I am on Debian and install OO with [official documentation ](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx). But its not the first time I set up OO, So it can explains why it was the same issue. Anyway, now it works. Thank you very much :+1:
