### ISSUE TITLE
The plugins don't show on the Comment permission type

### ISSUE THREAD

**Issue by xiaguangsiying** [ONLYOFFICE/DocumentServer#993]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
The plugins don't show when I set the document only comment permission.But I see the onlyoffice demo example is show  (https://api.onlyoffice.com/editors/editor?method=docxComment)

![WX20200914-142116](https://user-images.githubusercontent.com/17639104/93050623-c726f300-f695-11ea-89e2-398e107b90bc.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The plugins should be show always
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.6.4
**Operating System:**
CentOS Linux release 7.4.1708
**Browser version:**
Chrome 83.0.4103.61

**Comment by ShockwaveNN** [comment]
@flaminestone Please take a look

**Comment by flaminestone** [comment]
Hello @xiaguangsiying. Are you using documentserver from our site of documentations? (https://api.onlyoffice.com) There are many problems in this case, and you need to setup your own documentserver for this. 

I can not to reproduce this issue. Can you attach documentserver logs, and all your configs of DocEditor object?

**Comment by xiaguangsiying** [comment]
> Hello @xiaguangsiying. Are you using documentserver from our site of documentations? (https://api.onlyoffice.com) There are many problems in this case, and you need to setup your own documentserver for this.
> 
> I can not to reproduce this issue. Can you attach documentserver logs, and all your configs of DocEditor object?

Thanks for your review.The answer is the plugins are show in the edit mode but the plugins aren't show in the comment permission only.Other config is same.
<img width="1580" alt="WX20200915-135215@2x" src="https://user-images.githubusercontent.com/17639104/93171175-2bf85100-f75b-11ea-85fe-91f5e210d8d1.png">
![WX20200915-134621](https://user-images.githubusercontent.com/17639104/93171194-3286c880-f75b-11ea-9355-affffa0db4c2.png)

**Comment by flaminestone** [comment]
@xiaguangsiying? Are you using documentserver from our site of documentations, or using your own documentserver? 
I create small project for detect this problem
https://github.com/no-flamine/documentserver-nginx-example

Is a test example with your configuration. And I see plugins in both of cases. Can you try to check your scenario on this project?

Link for download project with your confirs in first release - https://github.com/no-flamine/documentserver-nginx-example/archive/0.1.zip

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
