### ISSUE TITLE
Incorrect Gradient Direction in pptx file

### ISSUE THREAD

**Issue by KuenzelIT** [ONLYOFFICE/DocumentServer#994]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Gradients of power point files are rotated when viewed in the browser with nextcloud and onlyoffice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Upload the attached arrowgradients.pptx and view the file in onlyoffice.

**What is the expected behavior?**
The gradients should be the same as in PowerPoint/LibreOffice.

**Did this work in previous versions of DocumentServer?**
Unknown

**DocumentServer version:**
Document Server: 5.6.3-2
Presentation Editor 5.6.3

**Operating System:**
Linux Mint 19.3

**Browser version:**
Firefox 80.0

Files
https://www.file-upload.net/download-14290555/arrowgradients.pptx.html
https://www.file-upload.net/download-14290556/arrowgradients_onlyoffice.png.html

**Comment by Rita-Bubnova** [comment]
Hello, @KuenzelIT.
I can confirm - this is bug, issue 46573 in our private issue tracker.

**Comment by KuenzelIT** [comment]
Thank you! Did you have time to work on this bug yet?

**Comment by Rita-Bubnova** [comment]
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/b3176b074e391224c7740aba51276f406a152cf7)  in future major release.
