### ISSUE TITLE
"OnlyOffice Documents" app in play store works offline. How ?

### ISSUE THREAD

**Issue by falling-star** [ONLYOFFICE/DocumentServer#999]
We see that "OnlyOffice Documents" app in play store ( https://play.google.com/store/apps/details?id=com.onlyoffice.documents&hl=en_IN ) works offline also.

@ShockwaveNN  Can you please explain How the "OnlyOffice Documents" app is able to edit / view / save documents in offline mode without DocumentServer ? How do we integrate the same to work for any other mobile app ?

Note - We have licensed DocumentServer 5.5 installed in our own infrastructure.

**Comment by ShockwaveNN** [comment]
Sorry, @falling-star, mobile apss is out of my job responsibilities, all I know it compile `core` repo with base framework as well and use custom front-end

If you have licensed DocumentServer you can try to contact support and maybe they come up with detailed explanation of mobile apps internals

**Comment by ShockwaveNN** [comment]
Or maybe @ayuzhin or @alexeymusinov can share more detailed info

**Comment by falling-star** [comment]
Thanks @ShockwaveNN . @ayuzhin @alexeymusinov Can you please provide higher level context / steps for the above query, will create a HelpDesk ticket for detailed response ? Thank you.

**Comment by ayuzhin** [comment]
The mobile application on Android, when working with documents on the device, does not interact with the DocumentServer. All editing and conversion actions take place autonomously within the device.

**Comment by ShockwaveNN** [comment]
Closing this issue since developer answered a question and OP has no comments
